### ISSUE TITLE
Factory function returns undefined

### ISSUE THREAD

**Issue by calebwaldner** [vitest-dev/vitest#1011]
### Describe the bug

I am having trouble using the factory function for a mocked import.  I'm importing a custom hook, which I'd like mocked for unit tests. 

I can successfully mock the import using `vi.mock("@/importedFile")`; I can console log the import and see I've got a mocked function, so this works. 
But when I add a factory function, the console log returns `undefined`. I've tried a bunch of variations of the factory function, none seem to ever give me a result other than `undefined`.  

I know I could use a __mocked__ folder, but I want to use factory functions for some of my mocks. 

It's possible I'm just doing this wrong, but after trying a bunch of things and reading plenty vitest and jest documentation, it seems there might be something going on here.

Thanks for any help and/or fixes

### Reproduction

I've prepared a demo GH repo.
https://github.com/calebwaldner/vitest-mock-hook-test

### System Info

```shell
System:
    OS: macOS 12.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 294.64 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.6.0 - ~/.nvm/versions/node/v17.6.0/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 8.5.1 - ~/.nvm/versions/node/v17.6.0/bin/npm
  Browsers:
    Chrome: 99.0.4844.83
    Firefox: 96.0.2
    Firefox Developer Edition: 99.0
    Safari: 15.3
  npmPackages:
    @vitejs/plugin-vue: ^2.2.2 => 2.2.4
    vite: ^2.8.4 => 2.8.6
    vitest: ^0.5.0 => 0.5.9
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`default` exports should be on `default` key of module object, like this:

```ts
vi.mock("path", () => {
  return {
    default: () => ({})
  }
})
```

Your example worked in jest, because commonJS doesn't have this concept, but ESM does.

**Comment by sheremet-va** [comment]
> WOW, that works! Thanks so much. Feels like a bit of a gotcha with ESM. Will this caveat make it into the docs? I'm happy to help if needed.

Sure, if you can find a place for it. Maybe inside ["Mocking"](https://vitest.dev/guide/mocking.html#modules) section? We will gladly release it.

**Comment by calebwaldner** [comment]
Just created a PR. Ended up adding it to the API section under `vi.mock`, seemed to go well there in my opinion. 
https://github.com/vitest-dev/vitest/pull/1021

Hope this helps!
