### ISSUE TITLE
Vitest doesn't reload on types.ts change if it's watching a JS file using the types with JSDOC

### ISSUE THREAD

**Issue by thelinuxlich** [vitest-dev/vitest#1014]
### Describe the bug

If Vitest checks a file like this:

```js
// src/index.js

// @ts-check
/** @typedef { import("./types").Controller } Controller */

// in-source test suites
if (import.meta.vitest) {
  // test code...
}
```

Then it will never reload if I change `src/types.ts` file, even if I have `includeSource: ['src/**/*.{js,ts}']` in vitest.config.ts

### Reproduction

You can test with my sample project: https://github.com/thelinuxlich/test_jsdoc_ts

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 19.71 GB / 23.43 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 17.7.1 - ~/.nvm/versions/node/v17.7.1/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 8.5.2 - ~/.nvm/versions/node/v17.7.1/bin/npm
  npmPackages:
    vite: ^2.8.6 => 2.8.6 
    vitest: ^0.6.1 => 0.6.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
We are using `Vite` moduleGraph when restarting tests. Not sure if it's possible to do what you are asking, since Vite doesn't store these. Maybe open an issue in Vite repository?
