### ISSUE TITLE
docs: Need clearer description about `triple slash command`

### ISSUE THREAD

**Issue by alexzhang1030** [vitest-dev/vitest#1019]
### Clear and concise description of the problem

In the vitest documentation, i think we should clearer description about `triple slash command`,

👇 This is the description of aaa in the documentation

To configure vitest itself, add test property in your Vite config. You'll also need to add a reference to Vitest types using a [triple slash command](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types-) at the top of your config file, if you are importing defineConfig from vite itself.

```ts
import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    // ...
  },
})
```

### Suggested solution

should we update the doc to this ? 👇

To configure vitest itself, add test property in your Vite config. You'll also need to add a reference to Vitest types using a [triple slash command](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types-) at the top of your config file, if you are importing defineConfig from vite itself.

using defineConfig from `vite` you should follow this: 

```ts
/// <reference types="vitest" />
import { defineConfig } from 'vite'

export default defineConfig({
  test: {
    // ...
  },
})
```

using `defineConfig` from `vitest/config` you should follow this: 

```ts
import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    // ...
  },
})
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by meshantz** [comment]
I couldn't get this to work following the instructions as documented. The thing that was missing from my understanding was that 'vitest' needed to be imported for the reference to work. Could we add that into the docs as well?

ie:
```
import 'vitest'
/// <reference types="vitest" />
import { defineConfig } from 'vite'
```

**Comment by nmay231** [comment]
@meshantz I had the exact same issue. I don't know what the problem was exactly, but I nuked my lock file and reinstalled and that did the trick.

```bash
rm yarn.lock
yarn install
```

Note: you only either need the triple reference in your `vite.config.ts` (`/// <reference types="vitest" />`), or you can just add `"vitest/globals"` to your types in your `tsconfig.json`.

```json
{
  "compilerOptions": {
    "types": ["vitest/globals"]
  }
}
```

It might have been because I had multiple versions of vite installed unintentionally (`yarn why vite` said I had `4.1.2` and `4.0.4` installed), but I'm not certain.
