### ISSUE TITLE
Console logs not working when timer is used in test

### ISSUE THREAD

**Issue by mckelveygreg** [vitest-dev/vitest#1022]
### Describe the bug

When using fake timers, console logs after timers do not fire :/

By using the sample code from the [Timers Guide](https://vitest.dev/guide/mocking.html#timers), there are few things I don't understand.

First, only the first test's mock seems to fire (or at least is shown in the console).
Second, the console log at the end of the third test never fires (the difference I think is that is the only test using `advanceToNextTimer`)

In my own code, I was hoping for some console logging to help debug what values are and what has been called, but my logs are coming blank :(

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-38lgxv?file=test/suite.test.ts

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.34 GB / 7.72 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 3.1.1 - /usr/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  npmPackages:
    @vitejs/plugin-react: ^1.1.4 => 1.1.4 
    vite: ^2.8.6 => 2.8.6 
    vitest: ^0.7.10 => 0.7.10
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
For now you can call `vi.useRealTimers()` after `vi.runAllTimers`. This will unblock console.

**Comment by mckelveygreg** [comment]
Thank you all!! Using vitest has been a great experience both in code and community 🎉
