### ISSUE TITLE
Debug test file on vscode failed

### ISSUE THREAD

**Issue by alexzhang1030** [vitest-dev/vitest#1023]
### Describe the bug

i follow the docs about [how to debugging test file on vscode](https://vitest.dev/guide/debugging.html#vscode) create a launch configuration in project root/.vscode path.

![1648173808(1)](https://user-images.githubusercontent.com/49969959/160040115-a9191351-1942-4ca2-93e9-f6f1846757ef.png)

i have two debug mode, and i am sure i selected `Debug Current Test File`. when i open my test file, and press F5. sadly, it failed. the fail reason is cannot find any test file, but i am sure i have it.

![image](https://user-images.githubusercontent.com/49969959/160062501-cd6ede2b-e48a-4f43-b1a4-72a2be614954.png)

but when i selected `Run script: test`, it worked !

### Reproduction

sorry i can't using stackblitz to show this bug

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 3.64 GB / 15.86 GB
  Binaries:
    Node: 16.13.2 - D:\nodejs\node.EXE
    Yarn: 1.22.17 - D:\nodejs\node_global\yarn.CMD
    npm: 8.1.2 - D:\nodejs\npm.CMD
  Browsers:
    Chrome: 99.0.4844.82
    Edge: Spartan (44.22000.120.0), Chromium (99.0.1150.46)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ysaskia** [comment]
This is because it uses `vitest run` which seems to have issues with backslash used by windows  path. 
To confirm it, I've tested it in an existing solution with windows path:

```
pnpm exec vitest run packages\components\lib\Button\Button.test.ts

 RUN  v0.8.1 C:/Users/Yoann/Desktop/fibre

No test files found
``` 

And here the expected result in the same session by replacing backslashes:

```
pnpm exec vitest run packages/components/lib/Button/Button.test.ts

 RUN  v0.8.1 C:/Users/Yoann/Desktop/fibre

 √ packages/components/lib/Button/Button.test.ts (1)

Test Files  1 passed (1)
     Tests  1 passed (1)
      Time  7.27s (in thread 20ms, 37219.32%)
```

**Comment by ysaskia** [comment]
Issue is here:

https://github.com/vitest-dev/vitest/blob/43ef6bbfea686fc726cb06b00605b1ee31ff83e7/packages/vitest/src/node/core.ts#L406

This is a very quick fix. It should test for path normalization using `process.platform` instead of `process.arch`. 
The `process.arch` value can be `win32` or `x64` but `process.platform` will always be `win32`.
