### ISSUE TITLE
Debug hangs up when using ElementPlus

### ISSUE THREAD

**Issue by hansonfang** [vitest-dev/vitest#1024]
### Describe the bug

got error when import elementPlus in setupFiles

```sh
TypeError: Invalid URL
 ❯ Object.<anonymous> node_modules/.pnpm/normalize-wheel-es@1.1.1/node_modules/normalize-wheel-es/dist/index.js:1:348


⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

Test Files  1 failed (1)
     Tests  no tests
      Time  2.12s (in thread 0ms, Infinity%)
```

As long as I remove ElementPlus importing, test back to normal.

### Reproduction

https://github.com/hansonfang/vitest_element_debug

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1013.61 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.19.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 99.0.4844.83
    Edge: 99.0.1150.46
    Safari: 15.4
  npmPackages:
    @vitejs/plugin-vue: ^2.2.4 => 2.2.4 
    vite: ^2.8.6 => 2.8.6 
    vitest: ^0.7.10 => 0.7.10
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This fixed it for me:

```ts
import { config } from "@vue/test-utils";
document.baseURI = "https://localhost/";
import ElementUI from "element-plus";

config.global.plugins = [ElementUI];
```

**Comment by hansonfang** [comment]
I updated `normalize-wheel-es` to `1.1.2` and this issue gone. but there comes a new one which is
when I use debug mode, terminal seems frozen with a RUN prompt. Nothing going on.
As long as I remove ElementPlus importing or run `pnpm test ` everything perform normally.

**Comment by sheremet-va** [comment]
> Issue solved by updating `normalize-wheel-es` to `1.1.2` Whereas there comes a new problem which is when I use debug mode, terminal seems frozen with a RUN prompt. Nothing going on. As long as I remove ElementPlus importing or run `pnpm test ` everything perform normally.

I don't have any errors running code in reproduction. Maybe you can push `lock` file also?

**Comment by hansonfang** [comment]
> 

@sheremet-va I've uploaded `lock` file pls check out. Meanwhile I took a shot on the problem
![Mar-28-2022 10-16-50](https://user-images.githubusercontent.com/22868119/160315709-d10c69d2-034c-4c8b-b908-38399e8279fe.gif)

**Comment by sheremet-va** [comment]
Reproduction works correctly on the latest Vitest version.
