### ISSUE TITLE
Module modified in `globalSetup` not persisted during run

### ISSUE THREAD

**Issue by lmiller1990** [vitest-dev/vitest#1049]
### Describe the bug

Modules modified in `globalSetup` are not persisted. Are these run in a different environment to the actual specs? Find a runnable reproduction the repo below. The TL;DR:

Module:

```js 
let foo = 'foo'

export function setFoo () {
  foo = 'bar'
}

export function getFoo () {
  return foo
}
```

Test:

```js
import { it, expect } from 'vitest'
import { getFoo } from './mod'

it('works', () => {
  expect(getFoo()).toBe('bar')
})
```

Global:

```js
import { setFoo } from './src/mod'

export default function () {
  setFoo('bar')
}
```

Config:

```js
export default {
  test: {
    globalSetup: ['./global.js']
  }
}
```

When running, I expect `foo` to be modified by `setFoo` before the spec runs. The global function is getting executed and `foo` is set to `bar` before the test runs, but it looks like we get a fresh, unmodified module in the actual run, that's different to the one in global.

### Reproduction

https://github.com/lmiller1990/vitest-global-bug

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 AMD Ryzen 3 3200G with Radeon Vega Graphics
    Memory: 10.48 GB / 31.30 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.11 - /usr/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Chromium: 99.0.4844.84
    Firefox: 98.0.2
  npmPackages:
    @vitejs/plugin-vue: ^2.2.0 => 2.2.4 
    vite: ^2.8.0 => 2.8.6 
    vitest: ^0.7.12 => 0.7.12
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lmiller1990** [comment]
`yarn vitest --run` has the same problem. I think `setupFiles` is also in another context? Is that right?

If so, we should note this - it's quite different to what I was expecting, coming from Jest.

**Comment by sheremet-va** [comment]
setupFiles shouldn’t run in another context

**Comment by lmiller1990** [comment]
Seems like they are, at least according to the reproduction I've posted. Am I doing it wrong?

We only have one very simple test: https://github.com/vitest-dev/vitest/blob/main/test/global-setup/setupFiles/add-something-to-global.ts. I could try adding my reproduction in Vitest.

**Comment by sheremet-va** [comment]
> Seems like they are, at least according to the reproduction I've posted. Am I doing it wrong?
> 
> We only have one very simple test: https://github.com/vitest-dev/vitest/blob/main/test/global-setup/setupFiles/add-something-to-global.ts. I could try adding my reproduction in Vitest.

Code in `setupFiles` should be executed on the first level. When I remove `export default` and leave only `setFoo`, test passes.

`export default` is only needed in `globalSetup` as a startup function. It is very similar to [jest's counterpart](https://jestjs.io/docs/configuration#globalsetup-string). I think you got confused a little bit because of the naming.

**Comment by lmiller1990** [comment]
I see. So I just needed to remove `export default`. Thanks!
