### ISSUE TITLE
Custom matchers with auto definition types

### ISSUE THREAD

**Issue by edimitchel** [vitest-dev/vitest#105]
For some custom needs, special matcher are needed.
`expect` from jest provides an [`extend method`](https://jestjs.io/fr/docs/expect#expectextendmatchers) for doing that.
[Jasmine is also able to do it](https://medium.com/bb-tutorials-and-thoughts/angular-how-to-add-jasmine-custom-matchers-in-unit-testing-3edd40f567ec).

There is something common between both solutions which Vitest can improve: **generate the type definition automatically**.

So being able to add our custom matchers, and then, get automatically the type globally either by a definition type file put in the source code or by a type put in cache somewhere in `node_modules` of Vitest which would be taken in order by typescript on test files.

**Comment by sheremet-va** [comment]
I think developers should do it themselves. The best we can do is provide documentation. Hope we can close the issue.
