### ISSUE TITLE
docs: page title is 404 on reload page

### ISSUE THREAD

**Issue by baboon-king** [vitest-dev/vitest#1050]
### Describe the bug

page title is 404 on reload page;

It could be a bugs

https://user-images.githubusercontent.com/63645337/160346026-0fd35884-8525-417e-9b6d-fe980ddfeec1.mov

### Reproduction

none

### System Info

```shell
none
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
it seems something related with `vitepress`, on dev before initializing the app the title `404` is there:

![imagen](https://user-images.githubusercontent.com/6311119/160398944-c1c19e35-1533-4f9e-80e8-0126b63ea4c6.png)

**Comment by userquin** [comment]
https://github.com/vuejs/vitepress/pull/590
