### ISSUE TITLE
Flaky test marking and retrying

### ISSUE THREAD

**Issue by lukasholzer** [vitest-dev/vitest#1057]
### Clear and concise description of the problem

Often some tests tend to be flaky which is a nightmare in large CI/CD pipelines as you have to retrigger and rerun.

There is not always the time to fix those flaky tests (what would be the ideal case - no doubt)
But in reality it happens.

It would be nice to have a retry mechanism that does not block CI runs.

### Suggested solution

I propose a feature that would mark tests as flaky (and then it would retry them up to a max that is specified when it fails)

like:

```typescript
test.flaky('This test is marked as flaky', () => { /* some flaky logic */ })
```

in the `vitest.config.ts` it could be then configured how often a flaky test should be retried on failure (default to 3 times)

```typescript
/// <reference types="vitest" />
import { defineConfig } from 'vite';

export default defineConfig({
  test: {
    flakyTestRetries: 4, // default would be 3
  },
})
```

the test would then be rerun if it fails up to the maximum specified.

It would only do that for tests that are marked as `test.flaky` (Therefore it needs an incentive of the user to say this test is really flaky I know but I don't have time to fix it now)

In the summary of the end it could then be written 3 flaky tests detected in addition to how many are passed or skipped.

### Alternative

Not implement this feature

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kwangure** [comment]
There should also be a way to retry ALL failed tests without needing special syntax like `test.flaky(....)`, similar to [@playwright/test retries](https://playwright.dev/docs/test-retries). This is especially convenient when you have several flaky tests for one reason or the other.

**Comment by bluwy** [comment]
On top of this, if `beforeEach` provides a hint that it's currently a retry (or the current retry index), it would help to setup "debug features" for more verbose test results, e.g. with Playwright I can turn on [tracing](https://playwright.dev/docs/api/class-tracing) when retrying.

**Comment by kwangure** [comment]
Two other features of Playwright I've missed in Vitest are:
1) The ability to distinguish initial runs from retries. Like in the [@playwright/test retries](https://playwright.dev/docs/test-retries#retries) docs demo, it allows clearing cache on the server or browser for example.
2) Expect `isNot` hints. Expect passes a boolean hint to matchers indicating whether it's a negation (i.e `expect(locator).not.conditionThatDoesNotMatch`. This is is helpful if you want to distinguish true/false positives and negatives and only retry a particular subset. It allows retries at the matcher level than test level.
