### ISSUE TITLE
`vi.runAllTimers` triggers timeout when used in a `async`/`await` test

### ISSUE THREAD

**Issue by pikax** [vitest-dev/vitest#1058]
### Describe the bug

When using `fakeTimers` if you `runAllTimers` on a `async` test it will timeout the test.  On `sync` tests it does not timeout and also when you pass `0` on the second argument.

### Reproduction

```ts
import { describe, expect, test, vi, beforeEach, afterEach } from 'vitest';

describe('test', () => {
  beforeEach(() => {
    vi.useFakeTimers();
  });
  afterEach(() => {
    vi.useRealTimers();
  });

  // fails
  test('timeout example async', async () => {
    await Promise.resolve();
    vi.runAllTimers();

    expect(1).toBe(1);
  });
  
  // passes
  test('timeout example infinite async', async () => {
    await Promise.resolve();
    vi.runAllTimers();

    expect(1).toBe(1);
  }, 0);

  // passes
  test('timeout example', () => {
    vi.runAllTimers();

    expect(1).toBe(1);
  });
});
```

https://stackblitz.com/edit/vitest-dev-vitest-1tmbqm?file=test/basic.test.ts

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 17.50 GB / 63.94 GB
  Binaries:
    Node: 16.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.13 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.24.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (99.0.1150.55)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Your example works with the lastest version: https://stackblitz.com/edit/vitest-dev-vitest-62r1y6?file=test/basic.test.ts

For some reason stacklitz loads `0.6.0` as the `latest` 🤔

**Comment by pikax** [comment]
That was an oversight, I guess it loads `0.6.0` because I forked stackblitz this from another error I opened a couple weeks ago, I'll be more careful next time :) 

Thank you
