### ISSUE TITLE
ReferenceError: describe is not defined

### ISSUE THREAD

**Issue by yanzhangshuai** [vitest-dev/vitest#1063]
### Describe the bug

When I upgrade from 0.7.13 to 0.8.1，There has been an error
![image](https://user-images.githubusercontent.com/31086862/161089930-67d099ea-bfae-4d15-b3ea-1f668711bf9b.png)

### Reproduction

https://github.com/yanzhangshuai/spa-template-thin

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 1.64 GB / 7.89 GB
  Binaries:
    Node: 16.13.2 - D:\install\node\node.EXE
    npm: 8.1.2 - D:\install\node\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.55)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
change "global" options to "globals"
