### ISSUE TITLE
Using `console.log` don't log anything in the console tab

### ISSUE THREAD

**Issue by edimitchel** [vitest-dev/vitest#1065]
### Describe the bug

When console are used in test, no more logs are send to the console tab.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-c1cevv?initialPath=__vitest__

### System Info

```shell
@vitest/ui: "0.8.1"
vitest: "0.8.1"
vite: "2.9.1"
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
@edimitchel it seems the logs aren't sent with the task id

![imagen](https://user-images.githubusercontent.com/6311119/161308184-fe617f00-7d01-448a-8e8e-f0f6453bb99d.png)

**Comment by userquin** [comment]
it seems something related to stackblizt, on local just works

**Comment by MantasSutkevicius** [comment]
Local doesn't work for me either:

![image](https://user-images.githubusercontent.com/33446531/161375104-0a446866-e842-49fe-99c8-fadeb85800d4.png)

**Comment by userquin** [comment]
I have this repo on github https://github.com/userquin/vitejs-vite-latest (link on gh repo to open it on stackblitz) and it is working on local, and on stackblitz on firefox and chrome (the logs with weird symbols, it seems when using numbers, just updated to use strings).

This gist also working on stackblitz, it is the same code on the previous gh repo, but on stackblitz: https://stackblitz.com/edit/vitejs-vite-nfjsbi

**Comment by userquin** [comment]
@sheremet-va I think it is not only ui bug, on server the task id is also missing, the `unknown test` when logging is also the same problem but on the base reporter (screenshot from @edimitchel repro):

![imagen](https://user-images.githubusercontent.com/6311119/161422200-c9586072-effa-49b2-a979-081c68b22b23.png)
