### ISSUE TITLE
Multiple output-files / Allow extension of existing reporters

### ISSUE THREAD

**Issue by steve-py96** [vitest-dev/vitest#1068]
### Clear and concise description of the problem

Before going to the problem I have to... Thank for this awesome lib, you're doing an insanely great job 👍🏿 

The problem:
I have the case where I need the json and junit reporter at once (one dataset goes into some documentary, the other to gitlab), when using both they merge their results into the specified `outputFile`. Since I cannot access the default reporter classes (https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/node/reporters/json.ts f.e.) to overwrite some stuff I'd need to create a custom one by merging junit & json reporters which seems kinda cubersome.

(sidenote: if the FR is not declined I'd try to contribute to this ofc, if I may :P)

### Suggested solution

If `outputFile` would accept a Record in a format like `{ [reporter]: outputFilePath }` (besides the string, the simple solution should ofc remain for the simple cases :D) the reporters could be run in parallel (would result in code like `this.ctx.config.outputFile.json || this.ctx.config.outputFile` or `typeof this.ctx.config.outputFile === 'string' ? this.ctx.config.outputFile  : this.ctx.config.outputFile.json` or sth).

### Alternative

By exposing the default reporters somehow they could be overwritten (would result in code like `class MyCustomReporter extends JsonReporter { ... }` where the ctx could be overwritten at a certain point).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I like the suggested solution, if you can make it work 🤔

**Comment by ericjgagnon** [comment]
I'm in the process of creating a Jetbrains run/debug configuration plugin for Vitest that would require me to create a custom reporter to emit messages in a format that the plugin framework understands.  

@sheremet-va would you be open to me creating a PR for @steve-py96 alternative solution?  I'd love to bring first class support for Vitest to Jetbrains IDEs.

**Comment by AriPerkkio** [comment]
> If outputFile would accept a Record in a format like { [reporter]: outputFilePath } (besides the string [...]

How could we use this with custom reporters? Currently the `reporters` option only allows class declarations, e.g. [`new SonarReporter()`](https://www.npmjs.com/package/vitest-sonar-reporter).

Maybe it should allow package names of custom reporters as keys there. Vitest should then check if it's built in one - if not, import the given package and initialize it. Something similar as built-in ones have here:

https://github.com/vitest-dev/vitest/blob/978d37c11259506a3e523341a4fc6b10cf331ec7/packages/vitest/src/node/reporters/index.ts#L11-L19

This `id` could then also be used when declaring reporters from CLI, e.g. `vitest run --reporters vitest-sonar-reporter`. Currently this CLI API only allows built-in ones. 

Maybe this first PR should only address the built-in reporters. I'm happy to help extending this functionality to cover custom 3rd party reporters.

**Comment by AriPerkkio** [comment]
Right, the custom reporters would actually work with the suggested changes. Simply with `outputFile: { 'my-custom-reporter': 'some/path.xml' }`, and in code `this.ctx.config.outputFile['my-custom-reporter']`. 
I think I was mixing this with `reporters` configuration. 😄

**Comment by steve-py96** [comment]
@AriPerkkio was thinking about the CLI too tho, the `--outputFile` arg only allows 1 path after all... It'd make sense to limit this feature to a config but also it'd make sense to allow multiple outputFile args and attach them in proper order to the provided reporters f.e., idk what to prefer

**Comment by sheremet-va** [comment]
> @AriPerkkio was thinking about the CLI too tho, the `--outputFile` arg only allows 1 path after all... It'd make sense to limit this feature to a config but also it'd make sense to allow multiple outputFile args and attach them in proper order to the provided reporters f.e., idk what to prefer

We can allow dot-nested options: https://github.com/cacjs/cac#dot-nested-options

**Comment by sheremet-va** [comment]
> @sheremet-va would you be open to me creating a PR for @steve-py96 alternative solution? I'd love to bring first class support for Vitest to Jetbrains IDEs.

Yeah, I think it's ok if we export `default` reporter for extending it's functionality.

**Comment by steve-py96** [comment]
Didn't check the used CLI lib, neat stuff 👌🏿
Adding that to the documentation later

**Comment by sheremet-va** [comment]
What do you mean? Don't we already have PR for this feature? I was waiting for @steve-py96 to make last changes before merging.

**Comment by ericjgagnon** [comment]
@sheremet-va there has definitely been a mixup, potentially by me. I'm going to open a separate enhancement request to describe my scenario in detail.

**Comment by steve-py96** [comment]
@sheremet-va sorry it was done already! I somehow managed to not push :(, it is up now
