### ISSUE TITLE
Reporter is flushing the console

### ISSUE THREAD

**Issue by craciuncezar** [vitest-dev/vitest#1072]
### Describe the bug

I've noticed that the reporter is flushing/clearing the console when the number of lines printed to the terminal is equal to the number of lines visible in the terminal, so eventually you'll get a blank terminal until the runner finishes and the whole output is printed. 

https://streamable.com/u0px0q

### Reproduction

Can be reproduced by running `pnpm run test` from the root level in the vitest repo.

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 79.97 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.9.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.5.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 99.1.36.117
    Chrome: 100.0.4896.60
    Firefox: 95.0.2
    Safari: 15.3
  npmPackages:
    vite: 2.9.0-beta.9 => 2.8.6 
    vitest: workspace:* => 0.8.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
I digged down this and found that it was a bug with `log-update` (sindresorhus/log-update#57).

**Comment by pmdarrow** [comment]
I'm experiencing this as well, and have come up with another isolated reproduction of it here: https://github.com/pmdarrow/vitest-bug.

While fitting to terminal height might make sense for watch mode, I don't think it does for `vitest run`. I've resorted to redirecting vitest output to a file so I can get the full test output, e.g.

```
npm run test:unit > test-output 2>&1
```

and in a separate terminal:

```
tail -f -n +1 test-output
```

**Comment by sapphi-red** [comment]
My PR has been merged and release with `log-update` v5.0.1!

**Comment by sapphi-red** [comment]
It has been updated by 0479656925859f0ddfa3a484f59b4807e5f76a83 and released in Vitest 0.9.4.
It's working in my environment.

**Comment by sheremet-va** [comment]
@craciuncezar can you confirm, the bug is fixed? If so, feel free to close the issue.

**Comment by pmdarrow** [comment]
I can confirm that the reporter is no longer flushing the console in 0.9.4, though I still think it behaves incorrectly. I can't scroll up in my console and see the test output - the output is limited to the height of my terminal. Is there a way to disable this behaviour that I'm missing? If for some reason that behaviour is intentional, there should be an option to turn it off - I find it quite frustrating.

![bug](https://user-images.githubusercontent.com/586800/164726964-88850a63-bbfc-4ff6-85e7-923c92af3ad5.gif)

**Comment by sheremet-va** [comment]
> I find it quite frustrating.

How so? It will output all errors that you can scroll after it finishes running tests

**Comment by anri-asaturov** [comment]
@sheremet-va if something fails within vitest itself, for example, you won't see the full log.

**Comment by sheremet-va** [comment]
> @sheremet-va if something fails within vitest itself, for example, you won't see the full log. Happened to me during migration from jest. Harder to debug.

Please, open a separate issue, if you have a problem.
