### ISSUE TITLE
Coverage is very slow on large projects

### ISSUE THREAD

**Issue by wtchnm** [vitest-dev/vitest#1075]
### Describe the bug

Hello!

My tests run in good time, but the coverage report is very slow:

```
Test Files  134 passed (134)
     Tests  572 passed (572)
      Time  64.91s (in thread 435.65s, 14.90%)
________________________________________________________
Executed in  208.93 secs    fish           external
   usr time   15.56 mins    0.00 micros   15.56 mins
   sys time    0.66 mins  680.00 micros    0.66 mins
```

It took almost 3:30 minutes to finish.

Using jest with the V8 coverage provider:
```
Test Suites: 134 passed, 134 total
Tests:       574 passed, 574 total
Snapshots:   44 passed, 44 total
Time:        50.658 s
________________________________________________________
Executed in   51.76 secs    fish           external
   usr time  717.91 secs  201.00 micros  717.91 secs
   sys time   20.59 secs  142.00 micros   20.59 secs
```

The project has about 1600 source files.

### Reproduction

I'm not sure how to provide a reproduction as I'm converting my company project to Vitest.

### System Info

```shell
System:
    OS: Linux 5.16 Fedora Linux 35 (Workstation Edition)
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 9.62 GB / 15.59 GB
    Container: Yes
    Shell: 3.3.1 - /usr/bin/fish
Binaries:
    Node: 16.14.2 - ~/.local/share/pnpm/node
    Yarn: 1.22.18 - ~/.local/share/pnpm/yarn
    npm: 8.5.0 - ~/.local/share/pnpm/npm
Browsers:
    Brave Browser: 99.1.36.119
    Firefox: 98.0
npmPackages:
    @vitejs/plugin-react: 1.2.0 => 1.2.0 
    vite: 2.8.6 => 2.8.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sapphi-red** [comment]
`test-exclude` which is used inside `c8` was taking time with my project.
So I changed the config like below. Is it also effective for your project?
```js
  test: {
    coverage: {
      include: ['src/**/*'],
      exclude: [],
    }
  }
```

**Comment by wtchnm** [comment]
Thanks, @sapphi-red! There was a significant performance improvement:

Before:
- Tests: 64.91s
- Coverage: 144.02s

After:
- Tests: 66.37s
- Coverage: 13.53s

As the difference was huge, I believe we should mention this issue in the documentation. What do you think?

**Comment by edimitchel** [comment]
@patak-dev we should document [about configuring coverage](https://github.com/vitest-dev/vitest/issues/1075#issuecomment-1086780957) on the vitest docs.

**Comment by sapphi-red** [comment]
Improving performance of `test-exclude` is ideally. But IMO it is good to mention it in the document in the meantime.

**Comment by sheremet-va** [comment]
We have a lot of exludes: 
```
  'coverage/**',
  'packages/*/test{,s}/**',
  '**/*.d.ts',
  'cypress/**',
  'test{,s}/**',
  'test{,-*}.{js,cjs,mjs,ts,tsx,jsx}',
  '**/*{.,-}test.{js,cjs,mjs,ts,tsx,jsx}',
  '**/__tests__/**',
  '**/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc}.config.{js,cjs,mjs,ts}',
  '**/.{eslint,mocha,prettier}rc.{js,cjs,yml}',
```
Maybe some of them could be removed?

**Comment by patak-dev** [comment]
Why does excluding takes so much time? It is counter-intuitive that adding to `exclude` is having this effect. Is it a c8 bug in the way this is handled?
Maybe one of these patterns is the issue? It could be interesting to try to remove each and check if that is the case.

**Comment by sapphi-red** [comment]
I measured timings with the config below with my project.
```ts
test: {
  coverage: {
    all: true
  }
}
```

- [bcoe/c8:/lib/report.js#L66-L78](https://github.com/bcoe/c8/blob/ae1f5e599476ae38b09b92c9f7db837e79cd1693/lib/report.js#L66-L78) was taking 37.878s. This is the total time for generating coverage.
- [bcoe/c8:/lib/report.js#L177-L184](https://github.com/bcoe/c8/blob/ae1f5e599476ae38b09b92c9f7db837e79cd1693/lib/report.js#L177-L184) was taking 33.341s.
- Also [bcoe/c8:/lib/report.js#L187-L219](https://github.com/bcoe/c8/blob/ae1f5e599476ae38b09b92c9f7db837e79cd1693/lib/report.js#L187-L219) was taking 3.658s.

Sum of these are 36.999s, so these two parts are taking almost all time.

After digging a bit more, I found caching this `this.exclude.shouldInstrument(v8ScriptCov.url)` call ([bcoe/c8:/lib/report.js#L290](https://github.com/bcoe/c8/blob/ae1f5e599476ae38b09b92c9f7db837e79cd1693/lib/report.js#L290)) makes a huge improvement.
It dramastically reduced this part ([bcoe/c8:/lib/report.js#L177-L184](https://github.com/bcoe/c8/blob/ae1f5e599476ae38b09b92c9f7db837e79cd1693/lib/report.js#L177-L184)) to 2.545s (which was 33.341s).
I will create a PR to `c8` for this.

But I feel it is possible to make it faster if `test-exclude` can be improved. (`test-exclude` seems not to be actively maintained.)

**Comment by sapphi-red** [comment]
My PR was merged and released with c8 v7.11.2!

**Comment by wtchnm** [comment]
Much thanks, @sapphi-red! The performance is now fine with `exclude`:

### Before:

Tests: 64.91s
Coverage: 144.02s

### After:

Tests: 68.69s
Coverage: 12.87s

**Comment by wtchnm** [comment]
I think we can close the issue now, what do you think @patak-dev and @sapphi-red?

**Comment by sapphi-red** [comment]
I think so.
