### ISSUE TITLE
Build fails because of missing type definitions

### ISSUE THREAD

**Issue by MantasSutkevicius** [vitest-dev/vitest#1076]
### Describe the bug

Whenever I add a test to the project and try to run `npm run build`, I get type definition errors. Errors are related to @types/node and @types/ws. I know I could just install these within my own devDependencies, but I think this should not be the case?

![image](https://user-images.githubusercontent.com/33446531/161374286-097c0426-6282-45b5-a5e9-725788ba114d.png)

![image](https://user-images.githubusercontent.com/33446531/161374500-d2c09d04-8f3b-43b9-a4fe-866f6b66105d.png)

### Reproduction

This is a fresh install of Vite+Vitest. The only change by me here is adding a test. Try running `npm run build` here:
https://stackblitz.com/edit/vitejs-vite-kmvhms

### System Info

```shell
-
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Not sure about "@types/ws", but "@types/node" is required

You can also try passing "--skipLibCheck" to tsc command

**Comment by MantasSutkevicius** [comment]
I know that `skipLibCheck` solves the issue, but I would rather keep the rule as `true`. I think I'll just install these deps on my own.

**Comment by david-crespo** [comment]
I'm also running into this when adding Vitest to a project. Had to add `@types/ws` and `@types/babel__core`. Will update if I find an alternative. It's a bit weird.

**Comment by sheremet-va** [comment]
Can confirm the bug: https://github.com/sheremet-va/vitest-types-bug

Note, we also require `esModuleInterop: true` in tsconfig at the moment (because of `chai`)
