### ISSUE TITLE
automocking fails in some cases when implementation involves symbols

### ISSUE THREAD

**Issue by eleith** [vitest-dev/vitest#1082]
### Describe the bug

on vitest `v0.6.3` automocking with the [pino logging library ](https://github.com/pinojs/pino)worked as intended.

since vitest `v0.7.0` and up, automocking the `pino` logging library now introduces a behavior change such that `restoreAllMocks` does not properly restore some functions to its original implementation and any future test will error out if they depend on the implementation.

please note, this behavior doesn't happen if spies are directly used. i can only replicate this behavior with automocking.

### Reproduction

in `log.ts`

```typescript
import logger from 'pino'
export default logger() 
```

in `log.test.ts`

```typescript
import { vi, test, expect } from 'vitest'
import log from './log'

vi.mock('./log') 

test('always true', () => {
   log.warn('help')
   vi.restoreAllMocks()
   log.warn('me')

   expect(true).toBeTruthy()
 })
```

the following test will pass on vitest `v0.6.3` and fail on `v0.7.0` and up.

this test will fail with the following error

```
TypeError: this[writeSym] is not a function
```

`writeSym` is referring to the use of a [symbol to index into an object that maps log levels to a log function](https://github.com/pinojs/pino/blob/572ac0a2c0b270f39bfa6b95b01212ac33653b84/lib/tools.js#L58).

### System Info

```shell
Binaries:
    Node: 16.14.0 
    Yarn: 1.22.18 
    npm: 8.5.2
  npmPackages:
    vitest: 0.7.0 => 0.7.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by eleith** [comment]
@antfu thanks for addressing. while this addresses one of the errors, i'm still unable to automock `pino` in `v0.8.4` (though the halting error is different this time).

given your PR, i was able to dig deeper and isolate the root error. 

in `symbol.ts`

```typescript
const helloSym = Symbol('hello')

const logger = {
  [helloSym]: (): string => {
    return 'hello'
  },
}

export { helloSym, logger }
```

and in `symbol.test.ts`

```typescript
import { vi, test, expect } from 'vitest'
import * as symbolModule from './symbol'

vi.mock('./symbol')

test("automock mocks all methods", () => {
  expect(() => {
    symbolModule.logger[symbolModule.helloSym]()
  }).not.toThrow()
})
```
i tried to enable automocking of symbol indexed methods by enabling [getAllProperties](https://github.com/sheremet-va/vitest/blob/8bc13a276b687b1aa7e12ca4f6d7cc77501fbb5b/packages/vitest/src/runtime/mocker.ts#L17) to track both string and symbol index properties (by making use of `Object.getOwnPropertySymbols`.

however, in the end, tinyspy's [spyOn method](https://github.com/tinylibs/tinyspy/blob/d097117d51f1ca7df2cb851420f12d3f95f1150e/src/spyOn.ts#L60) needs to be updated as it is currently restricted to string methods. (passing in a symbol as the second parameter results in a javascript error)

i'm not sure if supporting symbol index methods are desired by either project, so i'll pause here for reflection. 

for now, i'll manually mock `pino` instead of relying on automock.

**Comment by sheremet-va** [comment]
well, you don't need this method, since it's private, no?

we just mock methods, that you actually call. after you restore mock that calls it, it's still on a prototype.

**Comment by eleith** [comment]
agreed, i don't need the method. however, i think this issue may need to be re-opened as my goal is to automock `pino` (and i did not have errors in `v0.6.3`)

however, even with #1083 and `v0.8.4` the following will still fail

in `log.ts`

```typescript
import pino from 'pino'

export default pino()
```

in `log.test.ts`

```typescript
import { vi, test, expect } from 'vitest'
import logger from './log'

vi.mock('./log')

test("automock doesn't throw when unmocked", () => {
  expect(() => {
    vi.restoreAllMocks()
    logger.warn('help')
  }).not.toThrow()
})
```
one of [methods on the prototype](https://github.com/pinojs/pino/blob/83f95842c75883d467723cb648911c08e1edf1b5/lib/proto.js#L175) is still not being restored correctly and thus an error throws and tests fail.

**Comment by eleith** [comment]
i can reproduce the bug in `v0.9.0` now without relying on an external library

in `log.ts`

```typescript
const sym = Symbol('a')

const obj = {
  [sym]: () => {
    return 'hi'
  },

  hello: () => {
    return this[sym]()
  },
}

export default obj
```

and in `log.test.ts`

```typescript
import { vi, test, expect } from 'vitest'
import logger from './log'

vi.mock('./log')

test('auto mocked', () => {
  expect(() => {
    logger.hello()
  }).not.toThrow()
})

test('restoring auto mock', () => {
  vi.restoreAllMocks()
  expect(() => {
    logger.hello()
  }).not.toThrow()
})
```

in the above, the first test will pass and the second one will fail when `this[sym]` is called after being restored

i wonder if upgrading `tinyspy` to `0.3.1` would impact this at all?

**Comment by eleith** [comment]
#1119 now resolves this issue and i can confirm that auto mocking of `pino` works and it can later be successfully restored

however, i did encounter an internal issue with `vi.restoreAllMocks()` that causes tests to fail (but only on linux and only when run in `examples/mocks` as opposed to a clean project directory. 

i have a workaround in the PR to address this, but if the underlying issue can be resolved, i can remove the workaround.
