### ISSUE TITLE
Switch between jsdom and happy-dom environments per test

### ISSUE THREAD

**Issue by donferi** [vitest-dev/vitest#1109]
### Clear and concise description of the problem

As a developer using Vitest, I want to be able to override the environment on a per-test basis. The use case is that `happy-dom` is way faster than `jsdom`, however, there are a decent amount of browser apis that `happy-dom` does not support that `jsdom` do.

I wish to run most of my tests with `happy-dom` but then be able to switch to `jsdom` for the ones that require some extra apis that are not implemented yet on `happy-dom`.

### Suggested solution

Since this is setup in the configuration file, I honestly have no idea if it's possible and what an api would look like. 

Maybe something like:
```js
import { describe, it, setEnvironment } from 'vitest';

describe('...', () => {
   it('....', () => {
      setEnvironment('jsdom')
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
We already have `@vitest-environment`, no? https://vitest.dev/config/#environment

**Comment by shawn-p-m** [comment]
Super quick for anyone reading this later:

```
/**
 * @vitest-environment jsdom
 */
```
or 
```
/**
 * @vitest-environment node
 */
```

At the top of your test file will do the trick! 🪄

**Comment by vighnesh153** [comment]
How do you configure setup/teardown files for different environments?
