### ISSUE TITLE
Support to view the contents of old version documents

### ISSUE THREAD

**Issue by GreenMashimaro** [vitest-dev/vitest#1110]
### Clear and concise description of the problem

I can't find an entry to jump to the old version of the document on vite's official website https://vitest.dev/.
Although the header has a v0 8.4 buttons.
But I can't see the content of the old vite document.

![image](https://user-images.githubusercontent.com/23225539/161930028-76a5267d-4f74-4e36-afcb-09bd2361e057.png)

I think this function is very important, because if the old project uses the old version and it is inconvenient to upgrade, in this case, I need to check the document content corresponding to the old version to enter business development.

### Suggested solution

We can refer to angular or jest. There is an entry to display the historical version number.

#### In angular js

https://docs.angularjs.org/tutorial

Documents like angular are consistent with the release version.

![wlOE9FWBZU](https://user-images.githubusercontent.com/23225539/161929363-b0bb6aab-5098-4e47-9599-141bdc3c49d4.png)

#### In jest

https://jestjs.io/

Documents like jest are also consistent with the release version.

![MoTsTvYXgy](https://user-images.githubusercontent.com/23225539/161929387-15656d3d-3507-44e5-a57a-66dba173e0ae.png)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by akowalska622** [comment]
Any update on that? I can't upgrade my vite to v5, so I need to setup vitest using older version, but can't find docs for that.

**Comment by akowalska622** [comment]
Thanks for a quick reply! 
So there's now way to access docs for older versions? 
If not, would it be possible to include somewhere information which Vitest version is compatibile with which Vite and/or Node version? I'm using Vite 4.4.4 in a commercial project (that said I have way no bump it for now) and Node 16.4.2. I had to try to install various Vitest versions until I finally found the one that works within this setup.

**Comment by sheremet-va** [comment]
The next major release will add v0 and v1 documentations. We are planning to have documentations only for different major versions because they provide significant changes to the API. For minor versions, user should have no problem upgrading - all additive changes are labeled and can be easily tracked.
