### ISSUE TITLE
`--changed` option only takes into account changed source files and ignores test files

### ISSUE THREAD

**Issue by markgaze** [vitest-dev/vitest#1113]
### Describe the bug

When I change a test file, no tests are run when using the `--changed` flag. It works fine when I change the source files that the file tests.

This might just be my misunderstanding of how this was meant to work but I assumed that it would also run tests when the test files had changed.

### Reproduction

1. Modify a test file e.g. `Button.spec.tsx`
2. Run `vitest run --changed`
3. Vitest reports: `No test files found, exiting code with 0`
4. Modify `Button.tsx`
5. Run `vitest run --changed` again
6. Vitest runs the tests in `Button.spec.tsx`

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 1.89 GB / 16.00 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 17.0.1 - /usr/local/bin/node
    npm: 7.5.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 99.0.4844.84
    Firefox: 98.0.2
    Safari: 15.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Yes, it runs only tests that are affected by imported changes. I think it's a bug, will try to fix it 👀

**Comment by markgaze** [comment]
Amazing, thanks for the quick fix! I'll test it out today 🙂
