### ISSUE TITLE
Vitest fails to import under Vite App

### ISSUE THREAD

**Issue by rayfoss** [vitest-dev/vitest#1118]
### Describe the bug

I'd like to use the same syntax for my client side assertions as my build time testing framework. Unfortunately, Vite seems to load Node.js dependent code when you import Vitest. Is Vitest not compatible with browsers?

```
ERROR: No matching export in "browser-external:fs" for import "existsSync"
```

I'm using v0.8.4: https://unpkg.com/browse/vitest@0.8.4/package.json

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-6undtu?file=src%2Fmain.ts&initialPath=__vitest__

### System Info

```shell
StackBlitz
Vite: 2.9.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest cannot run in a browser at the moment, but there is a PR that allows a fraction of Vitest functionality to be used in a browser: https://github.com/vitest-dev/vitest/pull/891

**Comment by rayfoss** [comment]
Ended up using straight up chai/expect. Pretty sure cypress will not run in the browser due to the dependency of a browser.
