### ISSUE TITLE
Server API

### ISSUE THREAD

**Issue by antfu** [vitest-dev/vitest#112]
to pass `--api` or `api: true` option, we can make the vite server listen to HTTP requests. This could help provide the editor integration (#107) and potential the UI that @wheatjs is working on.

**Comment by posva** [comment]
Wouldn't it be worth somehow merging with https://peeky.dev/ to get the API and the UI features? It seems both projects to be converging on the same goals. 

Peeky already has a server with a GraphQL API that allows having subscriptions and it has a really useful UI using that very same API. I think an HTTP API would be limited for the use cases of testing (e.g. watching files to run tests again)
I personally build things on top of this GraphQL API for exercises with automatic tests integrated right into the web app, It's pretty cool!

Here is a demo of the apollo playground (automatically available at localhost:8000) (which is so good to try out and discover the api!) using one of the available subscriptions:

https://user-images.githubusercontent.com/664177/147073480-176f232c-12f8-4a8c-af15-7a216d881934.mp4

**Comment by antfu** [comment]
Thanks for the suggestions, but I personally would feel graphql is overkill for this scenario. I am quite satisfied with our current solution of websocket and https://github.com/antfu/birpc. I think the foundation is done for this issue, closing now.
