### ISSUE TITLE
Allow custom reporters to be resolved using the Vitest CLI 

### ISSUE THREAD

**Issue by ericjgagnon** [vitest-dev/vitest#1122]
### Clear and concise description of the problem

I am creating a custom run/debug configuration plugin using the Jetbrains/Intellij platform.  This plugin will give users first-class support for running Vitest in Jebrains' IDEs that support JavaScript/Typescript.  If you've used the out-of-the-box integration for [Jest](https://www.jetbrains.com/help/idea/running-unit-tests-on-jest.html), then it will be almost identical. When running the plugin from within the IDE it will run Vitest's CLI and listen for special messages coming from stdout/stderr specific to the platform for things like number of tests and test progress (i.e. successes, failures, and skips).  Currently, there's no built-in reporter that emits the necessary messages. It also wouldn't be a great user experience if you had to install the IDE plugin and a node module, as well as, alter your vite/vitest config file to get it to work.  

I'd like to put in a PR for this enhancement, if allowed.

### Suggested solution

Allow an absolute path or module name reference to be passed to the Vitest `CLI --reporter` option.  The Vitest code would then use a dynamic import to load the module and instantiate a new custom reporter. The class or function should be the default export and allows for instantiation using the new keyword. This keeps the custom reporter consistent with the other built-in reports.

### Additional context

This issue was spun off after a bit of confusion around https://github.com/vitest-dev/vitest/issues/1068.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
> Allow an absolute path or module name reference to be passed to the Vitest CLI --reporter option.

In addition to CLI it would be great to provide same feature in configuration file's `reporters` option. Equivalent for `vitest --reporter @company/my-custom-reporter` would be `{ test: { reporters: '@company/my-custom-reporter' } }`. I think adding CLI support would cover most of the implementation already. This could of course be split into separate PR if needed.

**Comment by ericjgagnon** [comment]
@AriPerkkio I believe you're right because instantiation and now loading of the reports happens after the CLI's `--report` and the config's `reporters` options merge into a single reporters array. In fact, it may happen for "free". 
@sheremet-va any thoughts about this proposal? I have go ready for PR and I would like to iterate on this soon, if possible

**Comment by sheremet-va** [comment]
> @sheremet-va any thoughts about this proposal? I have go ready for PR and I would like to iterate on this soon, if possible
Yeah, I'm fine with the proposal, let's see a PR

**Comment by ericjgagnon** [comment]
@sheremet-va  thanks. I'll get it ready
