### ISSUE TITLE
Tests in `vitest/test/fails` fail.

### ISSUE THREAD

**Issue by sakit0** [vitest-dev/vitest#1127]
### Describe the bug

Attempted to contribute to Vitest but failed the test.
Running tests in vitest/test/fails fails.

1. ` cd vitest/test-fails `
2. ` pnpm run test `

``` bash
 FAIL  test/runner.test.ts > should fails > empty.test.ts
AssertionError: Snapshot `should fails > empty.test.ts > empty.test.ts 1` mismatched
 ❯ test/runner.test.ts:35:18
     33|         .find(i => i.includes('Error: '))
     34|         ?.trim()
     35|       expect(msg).toMatchSnapshot(file)
       |                  ^
     36|     }, 10000)
     37|   }

  - Expected   "\"Error: No test suite found in file /Users/antfu/i/vitest/test/fails/fixtures/empty.test.ts\""
  + Received   "\"Error: No test suite found in file /Users/Project/vitest/test/fails/fixtures/empty.test.ts\""

```

### Reproduction

No response

### System Info

```shell
No response
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sakit0** [comment]
OK.I will create a PR.

**Comment by userquin** [comment]
@sakit0 my PR resolves this (Joaquín on discrod)?

**Comment by rluiten** [comment]
I created a new minial vite + vitest project today as I encountered this error in another project.

If I am using `pnpm` for packages I get the "No test suite found in file" for my test files when running `vitest`.
If I switch to `npm` as the package manager then running `vitest` finds and executes the tests correctly.

I am on windows 10.
Information on the version of vite and vitest and typescript in my project in case it helps.

```
    "typescript": "^4.6.3",
    "vite": "^2.9.5",
    "vitest": "^0.10.0"
```

With a trivial test file as follows, which I Copied from the `vitest` documentation.
```typescript
import { assert, expect, test } from "vitest";

// Edit an assertion and save to see HMR in action

test("Math.sqrt()", () => {
  expect(Math.sqrt(4)).toBe(2);
  expect(Math.sqrt(144)).toBe(12);
  expect(Math.sqrt(2)).toBe(Math.SQRT2);
});

test("JSON", () => {
  const input = {
    foo: "hello",
    bar: "world",
  };

  const output = JSON.stringify(input);

  expect(output).eq('{"foo":"hello","bar":"world"}');
  assert.deepEqual(JSON.parse(output), input, "matches original");
});

```

**Comment by sheremet-va** [comment]
> I created a new minimial vite + vitest project today as I encountered this error in another project.

@rluiten not sure what do you mean. This issue is about running tests inside Vitest monorepo. If you are having an issue with Vitest, please open a new issue.
