### ISSUE TITLE
Missing type for test.fails when using testing library

### ISSUE THREAD

**Issue by charklewis** [vitest-dev/vitest#1133]
### Describe the bug

When I use `test.fails` I get the typescript error `Property 'fails' does not exist on type 'It'`. I can fix this by importing the vitest `test`, however wondering if there is a way I can have this apply without my needing to import it. 

I think this is happening due to typescript linting picking up the jest version of `It`. 

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-larkt5?file=test/basic.test.ts

### System Info

```shell
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I think you have jest types for "test". If so, there is nothing we can do to fix this.

**Comment by charklewis** [comment]
> I think you have jest types for "test". If so, there is nothing we can do to fix this.

I have't added this myself, I assume it is coming from one of the `@testing-library` packages. If import `test` from `vitest` then it resolves the issue, I was just hoping I wouldn't have to (like I don't with jest). If that is the only solution at the moment, feel welcome to close this issue 🙂

Thanks for the prompt reply!

**Comment by sheremet-va** [comment]
Probably jest-dom https://github.com/testing-library/jest-dom/issues/427
