### ISSUE TITLE
Memory Leak with threads enabled

### ISSUE THREAD

**Issue by JonasKruckenberg** [vitest-dev/vitest#1135]
### Describe the bug

When setting `threads: true` (the default) a full rebuild (as happens when you press ctrl+s in the config file) leaks memory. The amount of memory is proportional to the amount of test files/source files present.

### Reproduction

[Here](https://stackblitz.com/edit/vitest-dev-vitest-ky3w2e) is a minimal reproduction that uses a very large snapshot to inflate memory usage.

1. Run `vitest` and make sure to have threads enabled
2. Navigate to the `vite.config.ts` file and press `ctrl+s` many times
3. See the memory usage of the `node` process increase

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 1023.63 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/Library/Caches/fnm_multishells/73424_1648464793541/bin/node
    Yarn: 3.0.1 - ~/.yarn/bin/yarn
    npm: 8.5.0 - ~/Library/Caches/fnm_multishells/73424_1648464793541/bin/npm
  npmPackages:
    vite: ^2.8.6 => 2.8.6 
    vitest: ^0.6.0 => 0.6.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vrslev** [comment]
I experience the exact same issue.

**Comment by HashemKhalifa** [comment]
any updates regarding this issue?

**Comment by AriPerkkio** [comment]
Is this issue still valid? I've been trying to reproduce it with the linked setup and cannot get memory leaks. I've been running it for several minutes and saving the configuration file as instructed, but memory usage doesn't raise much. GC seems to be cleaning up fine.

I'm running Node `v20.13.1` + MacOS.

**Comment by AriPerkkio** [comment]
The linked reproduction is using quite old version of Vitest, `v0.9.3`. With that one I can reproduce the memory leak easily. Noticable leak on each test re-runs.

After upgrading Vitest to latest `v1.6.0` the memory leak does not reproduce at all. This issue seems to be fixed. Feel free to open a new issue with minimal reproduction if you are running into this.
