### ISSUE TITLE
Error when Vue SFC and Vitest UI

### ISSUE THREAD

**Issue by sxzz** [vitest-dev/vitest#1139]
### Describe the bug

When importing Vue SFC and enabling `--ui`, an error is reported.
```
TypeError: __vite_ssr_import_1__.defineComponent is not a function
```

Without `--ui`, it works.

### Reproduction

GitHub Repo: https://github.com/sxzz/vitest-issue

1. Clone repo
2. `pnpm vitest --ui`

```ts
// vitest.config.ts
import { defineConfig } from 'vitest/config'
import Vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [Vue()],
  test: {},
})
```

```ts
// demo.test.ts
import { it } from 'vitest'
import DemoApp from '../src/demo-app.vue'

it('demo', () => {
  console.log(DemoApp)
})
```

```vue
<script setup lang="ts">
// demo-app.vue
console.log('Hello world')
</script>

<template>
  <h1>Hello World</h1>
</template>
```

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.32 GB / 32.00 GB
    Shell: 3.4.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.15 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 100.0.4896.75
    Edge: 100.0.1185.36
    Firefox: 98.0.2
    Safari: 15.4
    Safari Technology Preview: 15.4
  npmPackages:
    @vitejs/plugin-vue: ^2.3.1 => 2.3.1 
    vitest: ^0.9.3 => 0.9.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is a known error. Add this to your config:
```
  optimizeDeps: {
    exclude: ["vue"],
  },
  ```
  We are waiting for a `optimizeDeps: false` in Vite.

**Comment by sxzz** [comment]
Thanks, it works!

**Comment by sxzz** [comment]
Duplicate of #553
