### ISSUE TITLE
使用antd-mobileV5，报错

### ISSUE THREAD

**Issue by jerrywu001** [vitest-dev/vitest#1140]
### Describe the bug

使用antd-mobileV5，报错

```
[error] SyntaxError: Unexpected token ':'
[log]  ❯ Object.compileFunction ../../../../node:vm:352:18
[log]  ❯ Object.<anonymous> node_modules/antd-mobile/cjs/global/index.js:3:1
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-mdeqpn?file=vitest.config.ts&initialPath=__vitest__

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 51.83 GB / 63.87 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (100.0.1185.36)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitejs/plugin-legacy: ^1.8.0 => 1.8.0 
    @vitejs/plugin-react: ^1.3.0 => 1.3.0 
    vite: ^2.9.1 => 2.9.1 
    vitest: ^0.9.3 => 0.9.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jerrywu001** [comment]
需要将``` import { Button } from 'antd-mobile';```  改成 ``` import { Button } from 'antd-mobile/es';``` , test才正常通过，但是run dev没问题

**Comment by sheremet-va** [comment]
1. Reproduction works
2. Please, use English when reporting issues
