### ISSUE TITLE
Cannot get `vi.spyOn` to work

### ISSUE THREAD

**Issue by smeevil** [vitest-dev/vitest#1143]
### Describe the bug

Hi,

I'm converting a project from jest to vitest and the progress is going quite well :) 

I am running into one problem with using `vi.spyOn` where it does not seem to be recording any calls.
I have made a small StackBlitz reproduction where I'm trying to spy on window.localStorage for example.
When running the dev server you can see it works as intended, and in the test you can see the text's are updating as well, but in the end, no calls to the spy have been recorded.

Am I missing a crucial component or setup maybe?
I've tried different spies as well without any success where the same worked well in jest for example.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-9t6e2r?file=package.json&terminal=test

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.77 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - ~/dev/reisbalans/reisbalans-interface/node_modules/.bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Edge: 99.0.1150.55
    Firefox: 98.0
    Safari: 15.2
  npmPackages:
    @vitejs/plugin-react: 1.3.0 => 1.3.0
    @vitejs/plugin-react-refresh: ^1.3.6 => 1.3.6
    vite: 2.9.1 => 2.9.1
    vitest: ^0.8.1 => 0.8.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I am not sure if you can spy on localStorage? For reference: https://github.com/jsdom/jsdom/issues/2318

I think you need to reassign localStorage to some mocked class.

**Comment by smeevil** [comment]
You are absolutely right.

This helped me solve it : https://stackoverflow.com/a/54157998

Sorry to have bothered you with my ignorance.
