### ISSUE TITLE
`globalThis` is not the same as `self` when using jsdom

### ISSUE THREAD

**Issue by nknapp** [vitest-dev/vitest#1146]
## Observation

When testing react-components, you have to make sure that component-state changes are wrapped in an `act()` function call, otherwise the warning `Warning: An update to App inside a test was not wrapped in act(...).` will be displayed.

In the normal `create-react-app` setup, this warning is disabled when the code is currently running inside the `waitFor` function of `@testing-library/react`.

The same test, run with `vitest` shows the warning again. 

## Expectation

My expectation is that no warning is shown.

## Analysis

I figured out that `@testing-library/react` sets [self.IS_REACT_ACT_ENVIRONMENT](https://github.com/testing-library/react-testing-library/blob/c8c93f83228a68a270583c139972e79b1812b7d3/src/act-compat.js#L7) to `false`, while react [accesses `IS_REACT_ACT_ENVIRONMENT` directly](https://github.com/facebook/react/blob/d5b6b4b865ebf13a1eaf2342d623101056e5e197/packages/react-reconciler/src/ReactFiberAct.old.js#L44) to determine, whether to the warning or not.

In `jsdom`-environment of`vitest`, `self` and `globalThis` seem to be different object, so setting `self.IS_REACT_ACT_ENVIRONMENT` does not disable the warnings.

When I run the same test with `react-scripts test` (i.e. in jest), they are the same

## Expectation

`self` and `globalThis` should be the same object.

### Reproduction

I created the repository https://github.com/nknapp/vitest-react-18-testing-library-missing-act-workaround to reproduce the error. 

0. Setup dependencies

   ```
   yarn 
   ```

1. Run the test with `jest`, no warning will appear

   ```
   yarn test
   ```

2. Run the test with `vitest`, there will be a warning

   ```
   yarn vitest
   ```
    
3. Open [src/setupVitest.js](https://github.com/nknapp/vitest-react-18-testing-library-missing-act-workaround/blob/master/src/setupVitest.js) and remove the comments from the workaround-code.
The run `yarn vitest` again. No warning will appear

   The workaround defines `IS_REACT_ACT_ENVIRONMENT` as property that proxies its value to `self.IS_REACT_ACT_ENVIRONMENT`, so that the deactivation works correctly.

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz
    Memory: 2.73 GB / 15.51 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Brave Browser: 99.1.36.122
    Chrome: 99.0.4844.84
    Firefox: 99.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lukebelliveau** [comment]
I had a similar issue - it seemed the only way I could get the warning to go away was putting `globalThis.IS_REACT_ACT_ENVIRONMENT = true` in the actual `*.test.ts` file.

After much trial & error, here's what worked for me:

`vitest.config.ts`
```ts
import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  test: {
    environment: "jsdom",
    setupFiles: "./testSetup.ts",
  },
});
```

`testSetup.ts`
```ts
globalThis.IS_REACT_ACT_ENVIRONMENT = true;

```

**Comment by sheremet-va** [comment]
I think this is a bug in testing-library. Why `self` should be equal to `globalThis` in Vitest?

If they are putting a property on a global object that is read somewhere else, then the function to get the `globalThis` should be compatible in both reading/writing code.

**Comment by eps1lon** [comment]
> If they are putting a property on a global object that is read somewhere else, then the function to get the globalThis should be compatible in both reading/writing code.

What does "properly" mean here?

The [way we're doing it](https://github.com/testing-library/react-testing-library/blob/c8c93f83228a68a270583c139972e79b1812b7d3/src/act-compat.js#L5-L28), does match the [`globalThis` polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#examples).

**Comment by sheremet-va** [comment]
> > If they are putting a property on a global object that is read somewhere else, then the function to get the globalThis should be compatible in both reading/writing code.
> 
> What does "properly" mean here?
> 
> The [way we're doing it](https://github.com/testing-library/react-testing-library/blob/c8c93f83228a68a270583c139972e79b1812b7d3/src/act-compat.js#L5-L28), does match the [`globalThis` polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#examples).

I wrote “property”. What I mean is it should write the same way it is read inside react (I haven’t check how it is read).

Also, MDN’s polyfill doesn't check for existing “globalThis”, assuming it is always undefined, which is in my opinion incorrect behaviour. If you a polyfilling something, you should firs check if you need to.

**Comment by eps1lon** [comment]
> I wrote “property”. What I mean is it should write the same way it is read inside react (I haven’t check how it is read).

React just reads it with `IS_REACT_ACT_ENVIRONMENT`. But you can't write that way so you have to polyfill `globalThis`.

We can check for `globalThis` first but that still leaves vitest with with incorret behavior for how one writes global variables.

**Comment by qlniu** [comment]
version：
"@testing-library/jest-dom": "^5.16.4",
"@testing-library/react": "^13.2.0",
"react": "^18.1.0",
"react-dom": "^18.1.0",

Setting globalThis.IS_REACT_ACT_ENVIRONMENT = true in the jest.setup.js file does not work. On the contrary, the test runs continuously after the setting, repeating the problem of act()

![image](https://user-images.githubusercontent.com/46595240/167248755-c3a5c7dd-2397-4567-99f9-e2a89182c9df.png)

**Comment by sheremet-va** [comment]
This is a separate problem. See #1242
