### ISSUE TITLE
Tests of components using Moment-Timezone throw errors

### ISSUE THREAD

**Issue by oneillsp96** [vitest-dev/vitest#1151]
### Describe the bug

I realize this is an outdated library, but we're stuck with it until we can rewrite to get on date-fns or something like that.
Basically, running Vitest causes this error with moment-timzone, which we don't see when running Vite.

TypeError: Cannot read properties of undefined (reading 'format')

     38|                 {moment(props.children)
     39|                     .tz("timezone here")
     40|                     .format("format string here")

I am importing moment timezone like this:
import moment from "moment-timezone";

Any tips/hacks/workarounds would be appreciated!

### Reproduction

write a function using moment-timezone's .tz function
run "vitest"
the output of .tz() is undefined

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 14.38 GB / 31.83 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 100.0.4896.75
    Edge: Spartan (44.19041.1266.0), Chromium (100.0.1185.39)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @vitejs/plugin-react: 1.1.4 => 1.1.4
    vite: 2.9.1 => 2.9.1
    vitest: ^0.9.3 => 0.9.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
I'm also new to Vitest but I'm thinking if [deps.inline](https://vitest.dev/config/#deps) might worth a try, see this other issue #843 which seems similar. Also note that Vitest is ESM first and that is causing problem with older libs.

**Comment by oneillsp96** [comment]
Probably not an option for everyone, but I ended up just refactoring and removing moment-timezone from our codebase entirely.

**Comment by ghiscoding** [comment]
lol yeah when you have that option to refactor then it's nice even if it takes more time at first. On my side, I was fighting with Axios which doesn't ship an ESM build and had some `import` and `require()` in its codebase and the `require` is the big issue for a Vite prod build (because of RollupJS which doesn't like `require`) and had to also adjust Vitest to work too, I came up with something like this in my `vite.config.js` which is not great but seems to work
```ts
deps: {
  inline: ['@bundled-es-modules/axios'],
},
```
`@bundled-es-modules` is a lib forked from Axios to export semi-ESM code... so kinda related to your issue but yeah it's a bit painful to deal with old lib in both Vite/Vitest, not everything is ESM ready yet :S
