### ISSUE TITLE
Using `console.log` in test when `useFakeTimers` results in unexpected timer added from `birpc` package

### ISSUE THREAD

**Issue by justrhysism** [vitest-dev/vitest#1154]
### Describe the bug

If a test contains a call to `console`, a `setTimeout` is invoked by the `birpc` package, which when combined with `useFakeTimers` can lead to unexpected results.

This does appear to only occur on _first_ usage of `console`. Subsequent usages the behaviour is not exhibited. As such I've found a workaround by doing the following:

```ts
function timerBugWorkaround() {
    console.log();
    vi.clearAllTimers();
  }

beforeEach(() => {
    vi.useFakeTimers();
    timerBugWorkaround(); // Uncomment to invoke workaround
});
```

Unfortunately for me, I have spent many hours trying to figure out what was going on here when extra timers were being added from seemingly nowhere. Whilst this bug may not be a major issue, it does result in unexpected changes for something as common as using `console.log` (which is default go-to debugging tool before reaching for the inspector).

I believe this did also result in some issues from timers which are added later being automatically run without explicitly being advanced, however I can't seem to get a solid repro of that issue at this time—I haven't investigated further as I do believe it was ultimately caused by this issue.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-qmkkke?file=test/basic.test.ts 

### System Info

```shell
Not relevant, repro in StackBlitz
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Cannot reproduce with the latest version. Can you confirm the issue is fixed?

**Comment by sheremet-va** [comment]
birpc is environment-agnostic. it shouldn’t now about such things. this issue should be handled by vitest.

**Comment by gkubisa** [comment]
> birpc is environment-agnostic. it shouldn’t now about such things. this issue should be handled by vitest.

Sure, that makes sense. I was just pointing out the source of the issue. I managed to reproduce it consistently using the following snippet.

```javascript
import { afterAll, beforeAll, describe, test, vi } from 'vitest';

const { setTimeout } = window;

function delay(timeout) {
  return new Promise((resolve) => {
    setTimeout(resolve, timeout);
  });
}

function checkExtraTimers(location) {
  const count = vi.getTimerCount();
  if (count > 0) {
    console.log(`got extra timers (${location}): ${count}`);
  }
}

beforeAll(() => {
  vi.useFakeTimers();
});

afterAll(() => {
  vi.useRealTimers();
});

describe.each([1, 2])('group %d', (group) => {
  test('test', async () => {
    checkExtraTimers(`group ${group}a`);
    vi.advanceTimersByTime(60000 + 1);

    await delay(10);

    checkExtraTimers(`group ${group}b`);
    vi.advanceTimersByTime(60000 + 1);
  });
});
```
