### ISSUE TITLE
import calss filed name throw ReferenceError

### ISSUE THREAD

**Issue by DiamondYuan** [vitest-dev/vitest#1155]
### Describe the bug

test.spec.ts
```
import { value } from "./const";

describe("test class", () => {
  it("test class", () => {
    console.log("value", value);
    class A {
      [value]() {}
    }
  });
});

```

const.ts
```
export const value = "value";
```

### Reproduction

create file
run test

ReferenceError: value is not defined
 ❯ w.spec.ts:7:7
      5|     console.log("value", value);
      6|     class A {
      7|       [value]() {}
       |       ^
      8|     }
      9|   });

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 38.11 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 100.0.4896.88
    Edge: 99.0.1150.39
    Safari: 15.4
  npmPackages:
    vitest: ^0.9.3 => 0.9.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is a Vite bug. Please, open an issue there and link it with this one, so it will automatically be closed.

**Comment by DiamondYuan** [comment]
> ### Describe the bug
> test.spec.ts
> 
> ```
> import { value } from "./const";
> 
> describe("test class", () => {
>   it("test class", () => {
>     console.log("value", value);
>     class A {
>       [value]() {}
>     }
>   });
> });
> ```
> 
> const.ts
> 
> ```
> export const value = "value";
> ```

This code work correct in the vite project

**Comment by sheremet-va** [comment]
Vitest processes files with `ssr` flag. This is the cause of your error. Vite doesn't do that for code running in browser.
