### ISSUE TITLE
`throw` from an `async` method,  exits `vitest watch`

### ISSUE THREAD

**Issue by dennismphil** [vitest-dev/vitest#1165]
### Describe the bug

The same bug also exits `vitest --ui`

### Code

```ts
// myMethod.ts
export function myMethod(someRequiredString: string) {
  if (someRequiredString.trim().length ===  0) {
    throw new Error('String cannot be empty')
  }
}
```

### Test

```ts
// myMethod.spec.ts
describe('myMethod', () => {
  it('should throw for empty strings', () => {
    expect(() => myMethod('   ')).toThrow()

    // instead this works as expected
    // expect(getToken('  ')).rejects.toThrow();
  });
});
```

### Output

Exits from the watch mode

```
$ pnpm test:watch

> cloud-ui@0.0.1 test:watch /Users/dennis/code
> vitest watch --reporter=verbose

...
...
       press h to show help, press q to quit

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: String cannot be empty
 ❯ Module.myMethod src/services/accessApiService.ts:3:10
 ELIFECYCLE  Command failed with exit code 1. 

$ 
```

### Async function

![2022-04-18_12-28-27](https://user-images.githubusercontent.com/4141366/163871149-c1913a54-4c7c-4fc7-b168-6d09f0744a59.png)

### Sync function

Synchronous methods works well without any issues

![2022-04-18_12-29-21](https://user-images.githubusercontent.com/4141366/163871107-040efda3-3ecf-4584-a95b-6f6348378994.png)

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-dmkwpf?file=test/code.test.ts

### System Info

```shell
vitest --v  
vitest/0.9.3 darwin-arm64 node-v17.9.0   
```
```


### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by crjm** [comment]
Hey, sorry if I'm mistaken, but I've just reproduced the example and apparently we have to make the unit test _async_. As the function being tested is async, the test is expecting a promise.
I think that the Error never gets handled, and that is what's causing the process to exit.

Leaving code.ts untouched, I only modified code.test.ts and all tests passed.

```
test('myMethod', async () => {
  await expect(() => myMethod('   ')).rejects.toThrow();
});
```
Per the docs
https://vitest.dev/api/#rejects

**Comment by sheremet-va** [comment]
Yes, this is not a bug.

**Comment by dennismphil** [comment]
@crjm @sheremet-va Its quite normal for any programmer to miss writing `rejects` or throw any error in code. The vitest watch mode quitting on any error is what this bug is about. 

It would provide a much better experience if the watch keeps running giving the programmer a chance to fix the error before not bailing out.
