### ISSUE TITLE
feat(vite-node): support passing through arguments

### ISSUE THREAD

**Issue by ayuhito** [vitest-dev/vitest#1178]
### Clear and concise description of the problem

Similar to how the `node` command works where you can run `node file.ts arg1 arg2`, it would be great if we could pass arguments similar to above where calling `npx vite-node file.ts arg1` passes the `arg1` to the file when executed. This is useful for CLI tools or apps that use arguments themselves.

Perhaps it might be better to put the pass-through arguments behind a flag to prevent conflicting with vite-node's own args/flags.

### Suggested solution

My real concern is whether this is even possible with the Vite runner code? I went through the current project and I couldn't see a clear approach to modify the code to support arguments, so is this perhaps a limitation with this Vite oriented model? Or is it possible?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I am not sure how this would be possible, since you can pass several files to `vite-node`: `vite-node ./f1.ts ./f2.ts`?

I think you might want something like [tsx](https://github.com/esbuild-kit/tsx).

**Comment by Pomax** [comment]
The universal behaviour here is to forward everything after the first `--` in the process argument list.

**Comment by robertlong** [comment]
Agreed, I just ran into this myself and expected everything after `--` to be passed to `vite-node`. Seems like a simple addition which would allow for using `vite-node` for cli tools.
