### ISSUE TITLE
`todo` test results output as `'skipped'`

### ISSUE THREAD

**Issue by justrhysism** [vitest-dev/vitest#1179]
### Describe the bug

"todo" tests (e.g. `test.todo()`) are reported as "skipped" which doesn't align with Jest's reporting.

I don't mind tackling this one myself, however before proceeding I would like some insight as to whether other parts of Vitest are reliant on the "skipped" value (e.g. the UI).

### Reproduction

Create test file with `test.todo('foobar', () => {})`

Run tests with JSON output: `vitest --reporter json --outputFile=test-results.json`

Check JSON at `testResults[].assertionResults[].status`. Reported as `"skipped"`, however I believe this should be `"todo"`.

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.18 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.cache/fnm_multishells/22837_1650506632325/bin/node
    Yarn: 3.2.0 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - ~/.cache/fnm_multishells/22837_1650506632325/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Edge: 99.0.1150.36
    Firefox: 97.0.2
    Firefox Developer Edition: 98.0
    Safari: 15.3
  npmPackages:
    @vitejs/plugin-vue: ^2.3.1 => 2.3.1 
    vite: ^2.9.5 => 2.9.5 
    vitest: ^0.9.3 => 0.9.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This status is generated by reporter and used only there, so you are safe to fix it. 

Our initial idea for this reporter was to align with how jest outputs json, so I guess it's a bug that needs fixing.

**Comment by thiagobraddock** [comment]
Hy guys.
Is it real fixed? because keeps displaying only (1 todo) and not the description as it would in jest.
