### ISSUE TITLE
Clear console in watch mode

### ISSUE THREAD

**Issue by Visual-Dawg** [vitest-dev/vitest#1183]
### Clear and concise description of the problem

When iterating over components, while having my test run in the background, the console starts to fill up extremely fast and it becomes hard to get to the beginning of the latest report. 
If the console would clear itself, simply scrolling up would suffice.
I also had some other ideas, which might be cool.

### Suggested solution

Providing an option to toggle this behaviour in the config maybe like this:

```javascript
// vitest.config.js || vite.config.js . test
  {
        ... ,
        watch: {
            clear:  true,
            reporter: "dot",  // maybe also offering the option to change the reporter for watch mode? 
            stackTrace: false,   // could be useful, when you have a lot of failing test and the stack trace creates a lot of noise
        }

  }
```

### Alternative

Also making some / all functionality part of the interactive CLI. 
The "show no stack trace" would fit in quite well there, since hard-coding that in the configuration could be suboptimal, but be just right during one session.
The others maybe not that much.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by underfisk** [comment]
I've run into this issue before, looking for a solution to prevent the logs of just simply disappear or when an uncaught error is thrown to be able to read it, this is also replicable on the single run mode

**Comment by antfu** [comment]
Open for PR, thanks!

**Comment by sheremet-va** [comment]
Console is cleared in watch mode by default.

**Comment by gkiely** [comment]
@sheremet-va While it clears the console it retains the past results and scrollbar so it does not function like ⌘ + k.

This is an issue when debugging something like testing-library that outputs dom html that can take up a lot of vertical screen space.  A user would scroll up and then has to scroll back down to re-engage the terminal instead of just updating a test and seeing the new results.

I can provide a video of this if you need to see the issue in detail.

The ability to truly clear the terminal like Jest does would be great.

**Comment by sheremet-va** [comment]
> @sheremet-va While it clears the console it retains the past results and scrollbar so it does not function like ⌘ + k.
> 
> 
> 
> This is an issue when debugging something like testing-library that outputs dom html that can take up a lot of vertical screen space.  A user would scroll up and then has to scroll back down to re-engage the terminal instead of just updating a test and seeing the new results.
> 
> 
> 
> I can provide a video of this if you need to see the issue in detail.
> 
> 
> 
> The ability to truly clear the terminal like Jest does would be great.

Vitest clears the terminal like Jest does. Check that you don't disable `clearScreen` in your configuration.

**Comment by gkiely** [comment]
Here's what I mean:
https://www.loom.com/share/4570b607ff564cd4b2dcb0a1947532dd

Jest clears the scrollbar and terminal where vitest does not.

**Comment by sheremet-va** [comment]
> Here's what I mean: [loom.com/share/4570b607ff564cd4b2dcb0a1947532dd](https://www.loom.com/share/4570b607ff564cd4b2dcb0a1947532dd)

I cannot reproduce it:

https://github.com/vitest-dev/vitest/assets/16173870/1b5cef78-26f5-4082-b626-5493ee3efe67

**Comment by AriPerkkio** [comment]
> Try in the mac terminal.

I'm able to reproduce this on Mac's terminal. However it works fine using VSCode's internal terminal and Warp.

Here's minimal reproduction case which demonstrates the issue. Run script, manually scroll up and wait for 3s. Mac terminal is the only one that does not work. The `logger.clearFullScreen` does not work as expected.

```js
// repro.mjs
const message = "Hello World";

await new Promise((r) => setTimeout(r, 1000));
Array(200).fill(0).forEach((_, i) => console.log(`Row ${i}`));
console.log("Scroll up now");

await new Promise((r) => setTimeout(r, 3000));
console.log(`\x1Bc${message}`); // Vitest's logger.clearFullScreen
console.log("Testing");
```

Top left terminal is Warp, top right Mac terminal and bottom one is VSCode:

<details>

https://github.com/vitest-dev/vitest/assets/14806298/c2c5ef48-63d3-46c8-9ac1-f04a53d9a895

</details>
