### ISSUE TITLE
Handle gherkin syntax

### ISSUE THREAD

**Issue by flcarre** [vitest-dev/vitest#1193]
### Clear and concise description of the problem

I would like to write my test in gherkin like in jest with jest-cucumber

### Suggested solution

A vitest-cucumber module or anything else handling gherkin syntax

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
What is stopping you?

**Comment by Korijn** [comment]
> What is stopping you to use jest-cucumber?

Does this mean vitest is compatible with jest-cucumber?

**Comment by sheremet-va** [comment]
> Does this mean vitest is compatible with jest-cucumber?

I think so, yes. I haven't tried it tho. Our APIs with Jest is largely compatible. The only thing you might need is to setup global `jest` variable:

```ts
// setupFile.js
import { vi } from 'vitest'
globalThis.jest = vi
```

**Comment by jeff-wishnie** [comment]
@Korijn have you gotten this to work?

@sheremet-va I get the following error in steps definitions using `jest-cucumber` with `vitest` and a simple feature (just to see if I could get it going)

```
 FAIL  src/tests/unit/steps/example.steps.ts [ src/tests/unit/steps/example.steps.ts ]
ReferenceError: describe is not defined
 ❯ Proxy.defineFeature ../node_modules/jest-cucumber/dist/src/feature-definition-creation.js:150:5
 ❯ src/tests/unit/steps/example.steps.ts:9:0
```
Feature and Step attached (with `.txt` appended so git hub will accept them)
[example.feature.txt](https://github.com/vitest-dev/vitest/files/9124947/example.feature.txt)
[example.steps.ts.txt](https://github.com/vitest-dev/vitest/files/9124950/example.steps.ts.txt)
.

**Comment by jeff-wishnie** [comment]
Solved it--needed to set `test: { globals: true}}` in vitest.config -- seems to work without explicitly setting `globalThis.jest`

**Comment by SalahAdDin** [comment]
> Solved it--needed to set `test: { globals: true}}` in vitest.config -- seems to work without explicitly setting `globalThis.jest`

It would be better with native support. Isn't it?

**Comment by Korijn** [comment]
> @Korijn have you gotten this to work?

Sadly no. I ended up writing a custom vite config file to run cucumber via its programmatic API as a post build event. So I didnt use vitest in the end.

**Comment by thelinuxlich** [comment]
can confirm jest-cucumber works with vitest by setting globals to true

**Comment by thelinuxlich** [comment]
I've created a repo demonstrating how to inject Vitest into jest-cucumber: https://github.com/thelinuxlich/svelte-atdd-vitest-playwright

**Comment by SalahAdDin** [comment]
> I've created a repo demonstrating how to inject Vitest into jest-cucumber: https://github.com/thelinuxlich/svelte-atdd-vitest-playwright

With **playwright**!!! I have to check it.

**Comment by SamZiegler** [comment]
FYI... I created this plugin in order to enable this:
https://github.com/SamZiegler/vitest-cucumber-plugin
