### ISSUE TITLE
Missing imports on a monorepo with packages with `type` set to `module`

### ISSUE THREAD

**Issue by cef62** [vitest-dev/vitest#1198]
### Describe the bug

Upgrading from `0.8.5` to the latest version of `vitest` my tests started failing. 
It seems that #1097 is introducing the issue.

The tests fails when:
- you are in a monorepo (I'm using `pnpm`)
- your package `A` consumes another local package `B`
- package `B` compiles to files with the `.js` extension, and its package.json `type` is set to `module`

When `shouldExternalize` validates the imports `isValidNodeImport` from `mlly` will consider it a valid import and therefore mark it as externalized, the tests will fail.

A possible workaround is to mark your local dependencies not to be externalized in your configuration

```ts
test: {
  deps: {
    inline: [/\/packages\/.*\/esm\/(.*\.js)$/],
  },
},
```

If my solution is the right approach for such use cases, I'd' like to contribute to the project by adding documentation for it. Before opening a PR, I wanted to understand whether this was the expected behavior or a bug.

### Reproduction

[This GitHub repo](https://github.com/cef62/vitest-monorepo-issue-repro) is a minimal reproduction of the bug.
Install the project dependencies with `pnpm install --frozen-lockfile` and then run `pnpm start` to reproduce the issue.
Uncomment line 16 in [vite.config.ts](https://github.com/cef62/vitest-monorepo-issue-repro/blob/main/packages/other-library/vite.config.ts), to have the tests pass.

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 624.33 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I think this is more about monorepo support. 

If we revert the change to inline as we did previously, it will even inline external packages. I personally think your `deps.inline` solution is the way to move forward. @antfu, what do you think?

**Comment by sheremet-va** [comment]
Also, the fact that it is considered valid esm is not a reason for it to fail. I see your imports inside `esm` are incorrect - Node requires a files extension when importing another file. For example, `packages/my-utilities/dist/esm/index.js` imports `'./repeat'`, but it is not a valid Node import.

So, if your library was consumed by native Node, it would give you an error.

**Comment by sheremet-va** [comment]
There was a discussion about this in TypeScript repo: https://github.com/microsoft/TypeScript/issues/42151

I also found a [package](https://www.npmjs.com/package/tsc-esm-fix) that fixes it, but I haven't used it, since I don't use `tsc` to build files.

**Comment by cef62** [comment]
Thank you for all the answers and the context. 
I'm closing the issue. 
I'll try to open a PR adding some docs for the usage inside a monorepo.
