### ISSUE TITLE
Unhandled error when suite name is a function reference

### ISSUE THREAD

**Issue by underfisk** [vitest-dev/vitest#1201]
### Describe the bug

Recently during migration from Jest to Vitest I've encountered that my tests were existing with process exit code 1 because one of my describe blocks was using the function reference as the name (Jest under the hood used `.name` therefore it was working as if we pass `MyFunction.name`) but with Vitest it just silently throws an error

### Reproduction

```typescript
function MyReactHook(){
  const myFunction = () => {}
  return {myFunction}
}

describe(MyReactHook, () => {
  it('should render', () => {
    // TODO: This is just a mimic, we could use renderHook
  })
})

```
The code above will lead to the problem shown on the screenshot below

![Screenshot 2022-04-27 at 11 48 16 PM](https://user-images.githubusercontent.com/15980884/165643772-de42be42-9a13-450f-84cb-8c90bdd4db50.png)

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 8.00 GB / 64.00 GB
    Shell: 3.2.2 - /usr/local/bin/fish
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.7.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Safari: 15.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Resolved in https://github.com/vitest-dev/vitest/pull/1202
