### ISSUE TITLE
Custom error message with a .toMatchSnapshot assertion

### ISSUE THREAD

**Issue by mquandalle** [vitest-dev/vitest#1211]
### Describe the bug

Hi,

I'm trying to customize the error message displayed in case of a failed `toMatchSnapshot` assertion :

```js
expect(Math.sqrt(4), 'abc').toBe(3); // ✅ It works: message "abc" is displayed

expect(Math.sqrt(4), 'def').toMatchSnapshot(); // ❌ Doesn't work: message "def" is not displayed
```

Also this feature of using the second parameter of `expect` to customize the error message doesn't appear in the documentation https://vitest.dev/api/#expect

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-q1v26v?file=test/basic.test.ts

### System Info

```shell
System:
    OS: Linux 5.16 Pop!_OS 21.10
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 652.77 MB / 15.40 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.11.0 - ~/.nvm/versions/node/v16.11.0/bin/node
    Yarn: 3.2.0 - ~/.nvm/versions/node/v16.11.0/bin/yarn
    npm: 8.0.0 - ~/.nvm/versions/node/v16.11.0/bin/npm
  Browsers:
    Brave Browser: 100.1.37.116
    Chromium: 101.0.4951.41
    Firefox: 99.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Have you tried passing a message to `toMatchSnapshot` function itself? Does it behave like you would expect?

**Comment by mquandalle** [comment]
Yes I tried, but it append the message to the generated snapshot name, whereas I'm trying to output it in the console in case of a failed test.
