### ISSUE TITLE
`vi.fn()` mocks not being called with `@testing-library/user-event` when using same key multiple times

### ISSUE THREAD

**Issue by SarcevicAntonio** [vitest-dev/vitest#1228]
### Describe the bug

Using `@testing-library/user-event` `user.keyboard` to trigger event listeners that call `vi.fn` mocks is bugged when using the same key.

I wasn't sure wheter this should be reported here or at testing-library, but I'm reporting here, since it's the mock who isn't counting right... If I should report over there I can.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-79r9sx?file=test%2Fuserevent.test.ts

### System Info

```shell
❯  npx envinfo --system --npmPackages '{vitest,vite,@vitejs/*}' --binaries --browsers
success Install finished in 0.636s

 
  System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: Unknown - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    vite: ^2.9.5 => 2.9.6 
    vitest: latest => 0.10.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You forgot to `await` it. `userEvent.keyboard` returns a promise.

**Comment by SarcevicAntonio** [comment]
Oh damn, I feel so stupid.

Im very thankfull for the super super quick awnser <3
