### ISSUE TITLE
Localized test runner

### ISSUE THREAD

**Issue by edimitchel** [vitest-dev/vitest#123]
I didn't know any test runner which support other langage than english.
The idea is to provide localized text to support multi langage.

This is an idea to do in middle-term, as it's a bonus.

By defining inside the `.npmrc` file or in environment, the developer can change the default langage (english) to his native tongue.
This would like the Vue docs which was the first to provide a translated documentation.
Localize a test runner, which is for someone anoying, will permit the inclusion for those prefer to work with his native tongue.

**Comment by sheremet-va** [comment]
I don't see a lot of requests for this feature, and it would require a lot of support from different language teams, increasing the maintenance even further. I think sticking to English makes the most sense.
