### ISSUE TITLE
Coverage threshold bumper

### ISSUE THREAD

**Issue by tqn-treezor** [vitest-dev/vitest#1241]
### Clear and concise description of the problem

There is currently no way to insure continuous improvement regarding the test coverage, in the context of continuous integration.

### Suggested solution

Provide a package such as the following: https://github.com/Litee/jest-coverage-thresholds-bumper
(And include it directly into the framework)

It could take the shape of a boolean property in vitest's `defineConfig`:
```typescript
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    coverage: {
      statements: 97.25,
      branches: 95.96,
      functions: 88.53,
      lines: 98,
      thresholdAutoUpdate: true,
    },
});
```

### Additional context

I would love to have ideally 3 cases handled and clear logs when running `vitest run --coverage`:
- The case where the coverages increased and "You may want to push with updated coverage thresholds"
- The case where a coverage hasn't changed
- The case where a coverage threshold hasn't been reached (already handled by the "standard" command)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
I'll start to work on this feature next. I'm not yet sure if we can support this in watch mode, since editing `vitest.config.ts` re-triggers the test run. If that cannot be easily disabled we might want to keep this for `vitest run` only.
