### ISSUE TITLE
Global scope object should be `window` when using `happy-dom`

### ISSUE THREAD

**Issue by mikestopcontinues** [vitest-dev/vitest#1243]
### Describe the bug

One of my react hooks relies on a third party library (`react-use`) to function. That library references the raw global `cancelAnimationFrame()`, not `window.cancelAnimationFrame()`. This is perfectly valid JS DOM code, but it throws an error in `vitest`, because the global scope object doesn't contain `cancelAnimationFrame()` since it is not `window`.

I think that the global scope object should be `window` when using `happy-dom` (or `jsdom`, though I'm not using it, so I'm not sure if it's working already).

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-uwd1uk?file=test/basic.test.ts

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 161.24 MB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 3.2.0 - ~/.nvm/versions/node/v14.19.0/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v14.19.0/bin/npm
  Browsers:
    Brave Browser: 98.1.35.101
    Chrome: 101.0.4951.54
    Firefox: 99.0
    Safari: 15.4
  npmPackages:
    vitest: 0.10.4 => 0.10.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It is impossible to do with the current architecture. Right now we are copying the Window object properties to global. If they are not copied, it could mean they are not returned from `getOwnPropertyNames` on window, or not in our `jsdom-keys` array.

PR welcome to add the key on `OTHER_KEYS` in [jsdom-keys](https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/integrations/env/jsdom-keys.ts#L167)

**Comment by mikestopcontinues** [comment]
@sheremet-va I'm happy to make a PR! Question though: Those two arrays are getting concatenated. What about looping over the enumerable props on happy-dom's (and jsdom's) `Window`? That way as they fill in API gaps themselves, we automatically get the benefits? As far as I can tell, happy-dom is still playing catch up—and there's always new DOM APIs coming. What do you think?

**Comment by sheremet-va** [comment]
> @sheremet-va I'm happy to make a PR! Question though: Those two arrays are getting concatenated. What about looping over the enumerable props on happy-dom's (and jsdom's) `Window`? That way as they fill in API gaps themselves, we automatically get the benefits? As far as I can tell, happy-dom is still playing catch up—and there's always new DOM APIs coming. What do you think?

We are already looping over them tho? See [utils](https://github.com/vitest-dev/vitest/blob/d9ad0441945cf17808e4e9bb4c2b1615f7428021/packages/vitest/src/integrations/env/utils.ts).

**Comment by mikestopcontinues** [comment]
Ohh, you are! It looks like the issue is that happy-dom [GlobalWindow](https://github.com/capricorn86/happy-dom/blob/master/packages/happy-dom/src/window/GlobalWindow.ts) extends Window, so `Object.getOwnPropertyNames` only detects a subset of the available props. 

How about a PR that changes the loop logic to loop _all_ properties with a custom omit list for special cases? Likely, there won't be any special cases.

**Comment by sheremet-va** [comment]
I honestly don’t remember the exact reason. But some properties should not be moved to global space, as they will conflict with happy-dom. (setTimeout will go into infinite loop, for example)

I prefer if we just add a key right now. Also I’ve changed how global is populated in #1256, maybe I will invest more time with globals after we resolve react issues.
