### ISSUE TITLE
Find what test files went through each line in the coverage report

### ISSUE THREAD

**Issue by tqn-treezor** [vitest-dev/vitest#1248]
### Clear and concise description of the problem

It is impossible right now to know what test file went through a given file in the coverage report:
![image](https://user-images.githubusercontent.com/94844805/167106049-0fa6b95a-5536-41e4-bc8a-3faee3879440.png)

In this image for example, I can see that I went through a given line 818 times, which feels totally wrong, and I'd like to know why and which file went through each.

(Another problem would be that there seems to be a sliding of the lines shown, but that's another topic)

### Suggested solution

Ideally: an interactive interface from the given interface: when clicking / hovering `818x`, I would like a modal to appear and show me a list of test files going through that, with pagination and maybe a link "Show all files" linking to another page.

### Alternative

Maybe a CLI command `vitest run --analyze myFile.ts`?

### Additional context

I noticed that while observing huuuuuge coverage gaps with the default Jest configuration (https://github.com/vitest-dev/vitest/discussions/1240) I've started to investigate:
- `types.ts` were ignored by default in Jest and not in Vitest
- `*.entity.ts` were ignored by default in Jest and not in Vitest
- `*.test.ts` were ignored by default in Jest and not in Vitest
- For includes/excludes, Vitest takes absolute paths, Jest accepts relative paths

And I still have a *3 factor difference between the total number of lines/branches/statements detected by Vitest and Jest, so I'm still investigating.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Coverage files are generated by c8, so I am not sure, if we can help with that?

**Comment by sheremet-va** [comment]
Please, open issue to c8.
