### ISSUE TITLE
vitest fails a test due to "sandbox.restore()" usage?

### ISSUE THREAD

**Issue by tal-rofe** [vitest-dev/vitest#1253]
### Describe the bug

I have some unit tests where I use the `afterEach` hook and creating a sandbox right at the beginning.
I use `sandbox.restore` in the hook, but after running vitest, I got an error:

```
Error: sandbox.restore() does not take any parameters. Perhaps you meant stub.restore()
 ❯ restore ../../../../../file:/C:/Users/Tal/Desktop/cz-vinyl/node_modules/sinon/pkg/sinon-esm.js:3002:19
```

### Reproduction

Here is a link for github repo: https://github.com/tal-rofe/vitest-bug-reproduction

You should clone it, install deps (`pnpm i`) and then run `npx vitest`.

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 1.33 GB / 7.76 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.32)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`afterEach` has an argument of `context`: https://vitest.dev/guide/test-context.html

Rewrite to:

```ts
afterEach(() => sandbox.restore())
```
