### ISSUE TITLE
Unable to check axios calls after bumping vitest from 0.10.4 to 0.12.0

### ISSUE THREAD

**Issue by dennybiasiolli** [vitest-dev/vitest#1274]
### Describe the bug

The mocked `axios.get` function doesn't seems to have been called, even if before updating vitest everything was working fine.

I'm acting like this

```js
import axios from 'axios'
import { something } from '@/store/modules/todo' // axios.get is used here

vi.mock('axios',  () => ({
  default: {
    get: vi.fn(),
  },
}))
```

A workaround I found is to import axios after mocking:

```js
import { something } from '@/store/modules/todo' // axios.get is used here

vi.mock('axios',  () => ({
  default: {
    get: vi.fn(),
  },
}))

import axios from 'axios'
```

### Reproduction

- clone the repo here: https://github.com/dennybiasiolli/vuex-to-pinia-vue3
- checkout branch `dependabot/npm_and_yarn/vitest-0.12.0`
- `npm install`
- `npm run test`

Tests are failing in `tests/unit/store/modules/todo.spec.js`.

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 315.52 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 3.2.0 - /usr/local/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 101.0.4951.54
    Firefox: 99.0.1
    Safari: 15.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Moving import under `todo` will also work: 
```ts
import { something } from '@/store/modules/todo' // axios.get is used here
import axios from 'axios'

vi.mock('axios',  () => ({
  default: {
    get: vi.fn(),
  },
}))
```
Thank you for the issue, I will try to find a proper solution.
