### ISSUE TITLE
vitest UI doesn't log html correctly in the "console log" tab.

### ISSUE THREAD

**Issue by MarkLyck** [vitest-dev/vitest#1279]
### Describe the bug

When trying to log out HTML text in the console log with vitest UI, vitest UI is cutting up the output a lot, missing entire tags and symbols.

Example of broken output:
![Screen Shot 2022-05-09 at 11 08 56](https://user-images.githubusercontent.com/6841110/167440132-859f4d43-428e-4c70-91c8-70ffe2052529.png)

This is what the exact same output looks like in my terminal:
![Screen Shot 2022-05-09 at 11 09 53](https://user-images.githubusercontent.com/6841110/167440327-b061a30d-e3cf-4fa8-b6d1-c879c73942d9.png)

vitest UI seems to be removing all lines starting with `<` so entire lines like `<body>` are missing in the output.

This makes it extremely hard to debug anything to do with HTML when using vitest UI and I have to revert to using my console every time.

As a React developer who uses `@testing-library/react` and `screen.debug()` a lot. I am constantly looking at HTML output in my tests.

### Reproduction

Try to console log any HTML in a test with vitest UI.

Or use React testing library's `screen.debug` method in any component to see the broken output.

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.49 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.6.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 101.1.38.111
    Chrome: 101.0.4951.54
    Firefox: 99.0.1
    Safari: 15.4
  npmPackages:
    @vitejs/plugin-react: 1.3.2 => 1.3.2
    vite: 2.9.8 => 2.9.8
    vitest: ^0.12.1 => 0.12.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
@MarkLyck 

A simple test is working https://stackblitz.com/edit/vitest-dev-vitest-grlue7, what version of vitest are you using? 

About the `screen.debug` we added colored log to the UI (https://github.com/vitest-dev/vitest/pull/1108): it seems that method is also encoding the dom output to be colored and so the editor on the ui shows the formatted html. I have it working using `outerHTML` on a div (https://stackblitz.com/edit/vitest-dev-vitest-brpxau):
```ts
console.log(screen.getByText('Hello').outerHTML);
```

**Comment by userquin** [comment]
as expected, the change in the filter makes other use cases not work as they should

![imagen](https://user-images.githubusercontent.com/6311119/174601003-c13fa2ab-9266-4781-9b0e-bb10518ad905.png)

**Comment by userquin** [comment]
ok, the body isn't the problem, the html is sent colored:

![imagen](https://user-images.githubusercontent.com/6311119/174603566-a2ce9537-75d8-446f-9dec-fcdb8d77fdae.png)

**Comment by userquin** [comment]
there is no solution to this, either it escapes or it doesn't, we can't do both things at the same time, I think it would be convenient to add some warning in the documentation ( using [screen.debug](https://testing-library.com/docs/queries/about/#screendebug) and [prettyDOM](https://testing-library.com/docs/dom-testing-library/api-debugging/#prettydom) in the UI)

**Comment by TheNotary** [comment]
Hello all, I hope this ping isn't an intrusion, but I wound up here from google because I was debugging a very large component and wasn't seeing all the HTML and it felt hopeless for a while for me.  I eventually by chance found out that the env variable `DEBUG_PRINT_LIMIT=10000` can help by increasing the amount of test output visible in vitest (and all node tests I guess).  

Regards and happy testing!

**Comment by fabiobaser** [comment]
For anyone who is facing the same Issue and is not concerned with highlighting but wants the formatting thats missing when using just `console.log(screen.getByText('Hello').outerHTML);` you could use `screen.debug(screen.getByText("hello"), 1000, {highlight: false })`
That way, your output is formatted just without colors
