### ISSUE TITLE
Stuck in ci: close timed out after 1000ms

### ISSUE THREAD

**Issue by Mister-Hope** [vitest-dev/vitest#1288]
### Describe the bug

![image](https://user-images.githubusercontent.com/33315834/167857765-022a4e96-4fba-4801-aafe-028c2c825fff.png)

Runing with `vitest run --coverage`.  All tests passed and coverage is generated, while the process stucks.

Addtional info:

All functions in tests are sync, we are absolutely sure that we do not have any async functions in test, also we are not creating child process. Also the test works well in local environment.

I supposed that the issue is not on our side, as jest is working well before switching to `vitest`  and the test is actually just markdown tests using `marked` and `markdown-it`, all test are sync (without `done()`) and as the test passes, the script should be completed

### Reproduction

https://github.com/walinejs/waline/runs/6387036857?check_suite_focus=true

### System Info

```shell
Latest vitest@0.12.4 vite@2.9.9. Other env follows github ci.
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Arnagos** [comment]
We have the same problem.

**Comment by Qocotzxin** [comment]
Same error here. We do have a lot of async tests, but the error won't show up on watch mode, only when running `vitest run` or when setting `CI=true`.

**Comment by Qocotzxin** [comment]
> > Same behavior here. We do have a lot of async tests, but the error won't show up on watch mode, only when running `vitest run` or when setting `CI=true`.
> 
> Do you run with `--coverage`? Or it happens on a simple `run`?

At first, I thought it was only with coverage, but I executed `vitest run` and I was able to reproduce the issue. It's also worth to mention that I don't see an explicit error, but only the message 'close timed out after 1000ms'.

**Comment by baitkul** [comment]
I've got same error thrown, but only on CI running with `vitest run`

![Screen Shot 2022-06-02 at 18 15 42](https://user-images.githubusercontent.com/26372326/171627512-6a92ef3c-fab8-471d-a632-eee8c7564344.png)

**Comment by mckelveygreg** [comment]
We are also using `--coverage`. This is happening on our CI server in a docker container, so it stalls out our whole build.

**Comment by antfu** [comment]
We might need a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to investigate further about this.

**Comment by Qocotzxin** [comment]
So this is quite interesting. I was trying to figure out which part was actually failing to create a repro and found out that the problem was not any vitest feature or configuration itself, but actually an external dependency. For anyone trying to solve this problem check your plugins. In my particular case, I was using [vite-aliases](https://www.npmjs.com/package/vite-aliases) to automatically generate the aliases paths, but when I removed it and replaced it with vite resolve.alias option, everything started to work properly. Now tests are finishing correctly.

To be brutally honest, I have no idea why this happened. I can just assume there's an async operation around that is not letting vitest finish, but seems to be a bug from that library (unless I'm missing something, again, it's not pretty clear to me).

I hope this helps!

**Comment by Demivan** [comment]
I have checked source of vite-aliases. It starts a chokidar file system watcher and never stops it. Active file system watcher will prevent a proper vitest shutdown.

**Comment by antfu** [comment]
Nice spotting @Demivan! In this case, I think Vitest's behavior is expected. You might want to raise an issue in `vite-aliases` instead. Thanks

**Comment by michealroberts** [comment]
Can confirm I am seeing the same issue.

**Comment by silverwind** [comment]
I happen to have one case where it reproduces locally, in a around 1 in 10 runs. When it happens, the node process goes to 100% cpu and hangs forever. I managed to hook up the inspector and saw that it apparendly hit some kind of infinite loop:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/115237/205638527-dffeca41-916d-42f6-ae1d-82e6fb0a7437.png">

`processReallyExit` is from module [`signal-exit`](https://github.com/tapjs/signal-exit/blob/d4adbebea89cee95da197e9e94f32b3d685b4c80/index.js#L171) module which `vitest` has multiple dependencies on:

```
vitest@0.25.3
├─┬ @antfu/install-pkg@0.1.1
│ └─┬ execa@5.1.1
│   └── signal-exit@3.0.7
├─┬ execa@6.1.0
│ └── signal-exit@3.0.7
└─┬ log-update@5.0.1
  └─┬ cli-cursor@4.0.0
    └─┬ restore-cursor@4.0.0
      └── signal-exit@3.0.7
```
