### ISSUE TITLE
Random test crashes with "window is not defined" error

### ISSUE THREAD

**Issue by dartess** [vitest-dev/vitest#1293]
### Describe the bug

From time to time I get the error `ReferenceError: window is not defined`.

<img width="993" alt="image" src="https://user-images.githubusercontent.com/15047511/168019993-72420440-35bb-4b24-8215-0f538d743af5.png">

or

<img width="941" alt="image" src="https://user-images.githubusercontent.com/15047511/168020110-b9d70ba6-7bd6-4d84-883c-47cf764696ed.png">

### Reproduction

I couldn't find any pattern. It just happens sometimes.

This happens with any value of environment, and `happy-dom` and `jsdom`.

`vitest.config.ts`:

```
/// <reference types="vitest" />

import path from 'path';
import { defineConfig } from 'vite';

// eslint-disable-next-line import/no-default-export -- by design
export default defineConfig({
  test: {
    environment: 'happy-dom',
    include: ['**/*.test.ts'],
    setupFiles: [path.resolve(__dirname, 'vitest.setup.ts')],
  },
});

```

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.14 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 101.1.38.111
    Chrome: 101.0.4951.54
    Chrome Canary: 103.0.5057.0
    Firefox: 100.0
    Safari: 15.3
  npmPackages:
    vite: ^2.9.9 => 2.9.9 
    vitest: ^0.12.4 => 0.12.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Also, please provide code samples (reproduction).

**Comment by dartess** [comment]
>  What command do you use to run Vitest?

`vitest run src/services/socket/__tests__/index.test.ts` (in the screenshot - in the loop)

**Comment by sheremet-va** [comment]
I _think_ you run some code (maybe not explicitly), when tests are already completed. Try `console.trace` or debug to see why this code is run.

**Comment by dartess** [comment]
I couldn't make a small reproduction. The more I reduced the code, the less often the error was reproduced.

@sheremet-va You're absolutely right. Thank you very much. Some socket handlers worked after the tests were completed.

**Comment by dartess** [comment]
@vincent-lecrubier-skydio unfortunately I can't give you the right solution. I just refactored the code.

**Comment by rbrta** [comment]
same problem

**Comment by odinho** [comment]
It seems like `vitest` should not tear down the environment if there's still stuff in the event queue then?

I get that this is some async thing that's coming in late, but usually it would find `window` and it'd be a-ok. Never had this issue with `jest` which we just came from (same tests), which might indicate that they do wait(?).

If it is meant to be a feature, then it should always warn about things being run after teardown, and not just when it crashes due to an env issue.

These are some quite big integration tests, and I'm also unable to tell which tests they came from, even almost-so. The `console.log` I put in doesn't happen for this after-teardown run, only for things inside the test. :thinking:

**Comment by itm-platform** [comment]
Similar situation here. I get `ReferenceError: document is not defined` and ` window is not defined` both using jsdom and happy-dom

```js
/**
 * @vitest-environment 'jsdom'
 */
import { ITMEditor } from '../../src/itm-editor.js';
import { afterEach, describe, test, expect } from 'vitest';
describe('ITMEditor', () => {
    afterEach(() => {
        document.body.innerHTML = ''; document.head.innerHTML = '';
    });
    describe('Editor setup', () => {
        test('Assign value returns value', async () => {
            const editor = document.createElement('itm-editor');
            await window.customElements.whenDefined('itm-editor');
                editor.value = 'test';
                expect(editor.value).toBe('testtt');
                console.log(editor.value);
        });
    });
});

**Comment by npriebe** [comment]
I had the same problem with an integration test. The problem was that the "window" object was global. Normally vitest starts in enviroment mode "node" [More here](https://vitest.dev/config/#environment)

My solution was to set the environment to "jsdom" in my "vite.config.js".

```
  test: {
    environment: "jsdom"
  }
```

**Comment by luckylooke** [comment]
I put 
```ts
test: {
    environment: "jsdom"
  }
```
under `build` by mistake 🤦
As soon as I realised, I converted config file to `.ts`, not to repeat similar mistake again, so I really recommend using typescript also for configs 😊 

Happy coding!

**Comment by VladislavVB** [comment]
`vitest --sequence.setupFiles list --environment jsdom`

This helped me, since now the tests will go in order, and not randomly
`--sequence.setupFiles lis`

**Comment by sunny15100** [comment]
I have the same problem, random happened
![企业微信截图_68e6ef59-89b2-4f79-ad64-95286c210209](https://github.com/vitest-dev/vitest/assets/17845065/5ef85fd4-5be2-44b2-9826-6d1f0bf9b7c0)

**Comment by sheremet-va** [comment]
> Catch-22

You need to remove this when running in Vitest, because Vitest runs in node where it exists. You can remove it conditionally with `process.env.VITEST` or `mode === 'test'`:

```ts
export default defineConfig(({ mode }) => ({
  define: process.env.VITEST ? {} : { global: 'window' }
})
```

**Comment by lqueryvg** [comment]
@sheremet-va thank you so much !
This solution looks so simple I feel stupid.
