### ISSUE TITLE
beforeEach called in the middle of a test

### ISSUE THREAD

**Issue by vim-daniel** [vitest-dev/vitest#1297]
### Describe the bug

The before each statement and i think also general things like `mocksClear` are called in the middle of an async test...

This makes this framework unreliable...

### Reproduction

I wasn't able to reproduce in StackBlitz but i have the attached video

https://user-images.githubusercontent.com/49188777/168087983-1cc26045-8978-49f7-aaf3-469eb12d17d3.mp4

### System Info

```shell
I'm using pnpm version 6.32.4, don't know if that's related

 System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 75.94 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Safari: 15.4
  npmPackages:
    vite: ^2.9.5 => 2.9.5 
    vitest: ^0.12.4 => 0.12.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Recording doesn't really help, if I'm not able to reproduce and test it. Please, try to create a small reproduction.

**Comment by vim-daniel** [comment]
Turns out the test has overridden the Promise.race implementation which caused this behaviour 🥲
Thanks for the time :)
