### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'stacks')

### ISSUE THREAD

**Issue by wieringen** [vitest-dev/vitest#1314]
### Describe the bug

The library https://github.com/jsdom/jsdom throws a DOMException error in some cases. Seems like this error is not well handled by vitest and crashes during a call to parseStacktrace.

#654

### Reproduction
```js
import DOMException from "domexception";
import {it, describe} from 'vitest'

describe('The Index Page', () => {
  it('should display content if no params are given', () => {
    throw new DOMException("Something went wrong", "BadThingsError");
  })
})
```
### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 653.17 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.0.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 97.0.1
    Safari: 14.1.2
  npmPackages:
    vitest: ^0.12.6 => 0.12.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by syy11cn** [comment]
Here is the reproduction demo: https://stackblitz.com/edit/node-opjme7?file=test/basic.test.ts

**Comment by syy11cn** [comment]
It seems the variable `error` [here](https://github.com/vitest-dev/vitest/blob/03a54e0651f51b739b7833817d14d2cbcf474ede/packages/vitest/src/node/reporters/base.ts#L233) to be `undefined`. Hope this helpful.
