### ISSUE TITLE
Happy DOM - window.Blob is not equal to globalThis.Blob

### ISSUE THREAD

**Issue by capricorn86** [vitest-dev/vitest#1323]
### Describe the bug

Hi! :slightly_smiling_face: 

A bug was reported in [Happy DOM](https://github.com/capricorn86/happy-dom) related to "new Blob()" not being an instance of globalThis.Blob.

There seem to be two different implementations of Blob used in window.Blob vs globalThis.Blob. Node does not support Blob, so there must be something else adding the second implementation.

I investigated a bit further and I also noticed that window isn't the same as globalThis and global. Vitest should probably set `global.window` to be `global`.

Related bug in [Happy DOM](https://github.com/capricorn86/happy-dom):
https://github.com/capricorn86/happy-dom/issues/471

### Reproduction

```javascript
// Outputs "false"
console.log(window.globalThis === globalThis);

// Outputs "false"
console.log(window.Blob === globalThis.Blob);

// Outputs "false"
console.log(window.globalThis.Blob === globalThis.Blob);

// Outputs "false"
console.log(Blob === globalThis.Blob);

// Outputs "false"
console.log(Blob === globalThis.Blob);
```

### System Info

```shell
System:
    OS: Linux 5.17 Pop!_OS 22.04 LTS
    CPU: (4) x64 Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
    Memory: 6.43 GB / 15.56 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/bin/node
    Yarn: 1.22.10 - ~/.npm-global/bin/yarn
    npm: 8.5.5 - /usr/bin/npm
  Browsers:
    Chrome: 101.0.4951.41
    Firefox: 100.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nakleiderer** [comment]
I experienced this issue then upgrading from `vitest@0.11.0` to `vitest@0.12.0` and it resulted in this error:
> TypeError: Class extends value does not have valid prototype property undefined
Object. node_modules/@web-std/file/dist/src/file.cjs:59:15
Object. node_modules/@web-std/file/dist/src/lib.node.cjs:6:12

**Comment by sheremet-va** [comment]
> There seem to be two different implementations of Blob used in window.Blob vs globalThis.Blob. Node does not support Blob, so there must be something else adding the second implementation.

It was actually because we binded function to window on each access resulting in a different function. 

> I investigated a bit further and I also noticed that window isn't the same as globalThis and global. Vitest should probably set global.window to be global.

We actually had a very over engineered implementation for accessing globals, because jsdom got itself into an infinite loop/failed on accessing EventTarget. I _think_ I fixed it in #1340 tho, and we now use a more simplistic implementation, as you suggested.

**Comment by davidortner-ipex** [comment]
@sheremet-va nice to hear! :slightly_smiling_face:

**Comment by capricorn86** [comment]
@sheremet-va nice to hear! :slightly_smiling_face:
