### ISSUE TITLE
Wrong coverage information 

### ISSUE THREAD

**Issue by ocavue** [vitest-dev/vitest#1330]
### Describe the bug

The JSON coverage report doesn't provide correct positions of functions, which causes some problems when I try to merge the vitest coverage reports with other reports from different tools.

### Reproduction

I created a mini repo to show this issue. https://github.com/issueset/vitest-coverage-issue 

```
$ git clone https://github.com/issueset/vitest-coverage-issue 
$ cd vitest-coverage-issue 
$ pnpm install 
$ pnpm test:c8
$ cat coverage-c8/coverage-final.json
$ pnpm test:vitest
$ cat coverage-vitest/coverage-final.json
```

If I output the coverage using `pnpm test:c8`, the coverage information `coverage-c8/coverage-final.json` are very reasonable:

```json
  {
    "path": "/Users/ocavue/code/play/vitest-coverage/mjs/code.mjs",
    "fnMap": {
      "0": {
        "name": "FUNC_01",
        "decl": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 3, "column": 1 }
        },
        "loc": {
          "start": { "line": 1, "column": 0 },
          "end": { "line": 3, "column": 1 }
        },
        "line": 1
      },
      "1": {
        "name": "FUNC_02",
        "decl": {
          "start": { "line": 4, "column": 0 },
          "end": { "line": 6, "column": 1 }
        },
        "loc": {
          "start": { "line": 4, "column": 0 },
          "end": { "line": 6, "column": 1 }
        },
        "line": 4
      },
      "2": {
        "name": "FUNC_03",
        "decl": {
          "start": { "line": 10, "column": 0 },
          "end": { "line": 12, "column": 1 }
        },
        "loc": {
          "start": { "line": 10, "column": 0 },
          "end": { "line": 12, "column": 1 }
        },
        "line": 10
      }
    }
  }
```

However, if I run `pnpm test:vitest`, the coverage information (shown below) is odd. 

Specifically,
1. The start line of `FUNC_01` should be `1` instead of `2`
1. The `column` of `FUNC_01` is -1
2. The end position of `FUNC_01` is `{ "line": 4, "column": 2 }`, but `FUNC_01` only takes the first three lines.

```json
{
    "path": "/Users/ocavue/code/play/vitest-coverage/mjs/code.mjs",
    "fnMap": {
      "0": {
        "name": "FUNC_01",
        "decl": {
          "start": { "line": 2, "column": -1 },
          "end": { "line": 4, "column": 2 }
        },
        "loc": {
          "start": { "line": 2, "column": -1 },
          "end": { "line": 4, "column": 2 }
        },
        "line": 2
      },
      "1": {
        "name": "FUNC_02",
        "decl": {
          "start": { "line": 4, "column": 1 },
          "end": { "line": 7, "column": 0 }
        },
        "loc": {
          "start": { "line": 4, "column": 1 },
          "end": { "line": 7, "column": 0 }
        },
        "line": 4
      },
      "2": {
        "name": "FUNC_03",
        "decl": {
          "start": { "line": 10, "column": 1 },
          "end": { "line": 13, "column": 0 }
        },
        "loc": {
          "start": { "line": 10, "column": 1 },
          "end": { "line": 13, "column": 0 }
        },
        "line": 10
      }
    }
  }
```

If I check the coverage information for `code.ts`, then I can find more weird things: 

1. I can't find `FUNC_03` and I can get three `get` functions from nowhere. 
2. `FUNC_01` ends at `{ "line": 4, "column": 19 }`, which has a lot of overlay with `FUNC_02`.

```json
  {
    "path": "/Users/ocavue/code/play/vitest-coverage/ts/code.ts",
    "fnMap": {
      "0": {
        "name": "FUNC_01",
        "decl": {
          "start": { "line": 1, "column": 19 },
          "end": { "line": 4, "column": 19 }
        },
        "loc": {
          "start": { "line": 1, "column": 19 },
          "end": { "line": 4, "column": 19 }
        },
        "line": 1
      },
      "1": {
        "name": "FUNC_02",
        "decl": {
          "start": { "line": 4, "column": 0 },
          "end": { "line": 10, "column": 19 }
        },
        "loc": {
          "start": { "line": 4, "column": 0 },
          "end": { "line": 10, "column": 19 }
        },
        "line": 4
      },
      "2": {
        "name": "get",
        "decl": {
          "start": { "line": 14, "column": 0 },
          "end": { "line": 14, "column": 19 }
        },
        "loc": {
          "start": { "line": 14, "column": 0 },
          "end": { "line": 14, "column": 19 }
        },
        "line": 14
      },
      "3": {
        "name": "get",
        "decl": {
          "start": { "line": 15, "column": 0 },
          "end": { "line": 15, "column": 19 }
        },
        "loc": {
          "start": { "line": 15, "column": 0 },
          "end": { "line": 15, "column": 19 }
        },
        "line": 15
      },
      "4": {
        "name": "get",
        "decl": {
          "start": { "line": 16, "column": 0 },
          "end": { "line": 16, "column": 19 }
        },
        "loc": {
          "start": { "line": 16, "column": 0 },
          "end": { "line": 16, "column": 19 }
        },
        "line": 16
      }
    }
  }
```

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 100.78 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 99.0.1
    Safari: 15.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
@ocavue is this issue still relevant?

> [...] causes some problems when I try to merge the vitest coverage reports with other reports from different tools.

Are you merging `c8` results with other V8 results (chromium profiler, nodejs native), or some other instrumented coverage results? The V8 coverage reports produced by `c8` simply cannot be merged with instrumented coverage providers like `istanbul`. The way how they collect the coverage is too different. `v8-to-istanbul` package used by `c8` tries its best but still, not possible. 

However you should be able to use [`istanbul` provider from Vitest](https://vitest.dev/guide/features.html#coverage) and merge those results with other tools, e.g. `nyc`. I'm merging Vitest's `istanbul` reports with Cypress results and they work perfectly together.

**Comment by ocavue** [comment]
I just updated all dependencies to latest versions in my [testing repo](https://github.com/issueset/vitest-coverage-issue) and I still can reproduce this issue. 

I tried to merge the coverage json output by `vitest` (using `@vitest/coverage-c8`) and chromium profiler and failed. As far as I know, they both use V8 code coverage under the hood, which makes this failure weird. 

After a little digging, I found that coverage json from `@vitest/coverage-c8` has wrong sourcemap information. If I use `c8` directly without invoking vitest, I can get the correct result. That's why I believe it's a vitest bug and opened this issue. 

---

By the way, I'm not using istanbul at all in my case, simply because `[babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul)` (which is required when using Cypress coverage) slows down the app significantly and increases the waiting time for end-to-end testing.

**Comment by AriPerkkio** [comment]
@ocavue could you try if adding some random comment on first line of the files changes anything? This might indeed by a sourcemapping issue.

Comparing "pure C8" vs Vitest with C8 below.

Before:
![image](https://user-images.githubusercontent.com/14806298/209856981-92941fb9-428f-4928-83b1-93129e2fa205.png)


After, now results match:
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/14806298/209856885-20eed6d4-5008-4703-bf96-114b2ad1061a.png">

**Comment by ocavue** [comment]
Adding some comment doesn't improve or worsen the sourcemap issue. 

Take the screenshot below as an example, the range of `FUNC_01` in the coverage json is too wide. It shouldn't include line 14 at all.

![vitest-coverage-4](https://user-images.githubusercontent.com/24715727/209915754-481385c9-d4e2-42fc-9fc0-1c399e791977.png)

**Comment by AriPerkkio** [comment]
Make sure the versions of `vitest` and `@vitest/coverage-c8` in your `package.json` match. There is some hacky offset used by `@vitest/coverage-c8` which depends on `vitest` package's implementation. https://github.com/issueset/vitest-coverage-issue/blob/d85b02755ee9288447ff7982a4921674d8b5b837/package.json#L18-L19

Here is the same reproduction case on my machine. By adding the top level comment, the coverage reports match. If you could also verify this, I'd be able to narrow down the root cause for this and maybe find a solution. 
![image](https://user-images.githubusercontent.com/14806298/209925569-794222d5-2ad0-4110-8d8d-b2c19248c910.png)

However the branch count of Vitest's reports won't match. Vitest has to add some wrapper code around the files under testing, and those end up in V8 reports. As C8 does not do any AST based filtering, there won't be an easy way to remove those wrappers added by Vitest.

**Comment by ocavue** [comment]
I will double check the version. Does code.ts also works on your machine? Your screenshot seems to be code.mjs.

**Comment by AriPerkkio** [comment]
> Does code.ts also works on your machine?

Location of `FUNC_01` looks better than in https://github.com/vitest-dev/vitest/issues/1330#issuecomment-1367113170.

![image](https://user-images.githubusercontent.com/14806298/209948446-69e856fe-1926-481b-b17a-c60f9181e360.png)

**Comment by ocavue** [comment]
I make a full dependency upgrading in my [testing repo](https://github.com/issueset/vitest-coverage-issue) and the coverage information does look much more accurate! That's a good news. I will do some further test in our real project and see if everything is ok.

**Comment by ocavue** [comment]
@AriPerkkio  I'm not see any wrong coverage recently. I will close this issue. Thanks for your helping!
