### ISSUE TITLE
Add new option to prevent setting `process.env.NODE_ENV`

### ISSUE THREAD

**Issue by Dunqing** [vitest-dev/vitest#1334]
### Clear and concise description of the problem

I want to prevent `vitest` from setting `process.env.NODE_ENV`.

Because `vite` supports setting `process.env.NODE_ENV` in env files, e.g. .env files. But vite only allows setting when `process.env.NODE_ENV` is `undefined`.

I want to prevent `vitest` set NODE_ENV.

Because `vite` support `process.env.NODE_ENV` set in env file, e.g: .env file. but vite only allow to set when `process.env.NODE_ENV` is `undefined`

### Related code

https://github.com/vitest-dev/vitest/blob/4701e0b9b07728fc64189b655c53708346ac9293/packages/vitest/src/node/cli-api.ts#L18

### Related pr:
https://github.com/vitejs/vite/pull/8218

### Suggested solution

Add `preventSetNodeEnv` option, default is `false`.
Don't set `process.env.NODE_ENV` when `preventSetNodeEnv` is true.

### Additional context

https://github.com/vitejs/vite/pull/8218#discussion_r876491905

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Your examples shows that NODE_ENV is not set, if it was already set. So, what is the problem here?

**Comment by Dunqing** [comment]
If it is already set, causing `NODE_ENV` in the env file to not work.

https://github.com/vitejs/vite/pull/8218/files#diff-11e17761d4ecfee8f8fde15c6d79b7bc0260176396a30dfd8e6f6bbaf5af4745R399

**Comment by Dunqing** [comment]
I found the workaround.
We can override process.env.NODE_ENV with the env option.

https://github.com/vitest-dev/vitest/blob/4701e0b9b07728fc64189b655c53708346ac9293/packages/vitest/src/node/cli-api.ts#L35-L36
