### ISSUE TITLE
Can't mock dependency of dependency

### ISSUE THREAD

**Issue by christian-bromann** [vitest-dev/vitest#1336]
### Describe the bug

Given I have `packageA` that depends on `packageB` which depends on `packageC`. If I write tests for `packageA` I can't mock `packageC`, e.g.:

```ts
// package B
import got from 'got'
export default got
```

```ts
// packageA
import packageB from 'packageB'
export default request (url: string) {
    return packageB(url)
}
```

Now If I want to write tests for `packageA` I want to be able to mock the dependency of `packageB` rather than the whole package:

```ts
import { vi, ... } from 'vitest'
import packageA from '../src/index.ts'

vi.mock('got', () => { ... })

describe(() => {
    // ...
})
```

Unfortunately it is impossible to mock `got` in this case. In Jest however this is possible.

### Reproduction

In [this example](https://stackblitz.com/edit/vitest-dev-vitest-payj4m?file=package.json,test%2Fsuite.test.ts&initialPath=__vitest__) I mock `loglevel` which is a direct dependency of `@wdio/logger`. The test should throw an error because the dependency was mocked out with an undefined value but the test passes.

### System Info

```shell
n/a
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You need to inline that dependency, using deps.inline config option.

It is not inlined by default because of performance reasons.

**Comment by christian-bromann** [comment]
@sheremet-va thanks for the quick response, are you saying doing something like this:

```ts
export default defineConfig({
  test: {
    deps: {
      inline: ['loglevel'],
    },
    /* for example, use global to avoid globals imports (describe, test, expect): */
    // globals: true,
  },
});
```

?

**Comment by sheremet-va** [comment]
> @sheremet-va thanks for the quick response, are you saying doing something like this:

You need to inline the dependency that _you_ are using. So, according to you example, you need to inline `@wdio/logger`.

If you don't inline dependency, if doesn't go through Vite pipeline and can't benefit from our mock system, because it relies on it.

**Comment by christian-bromann** [comment]
I tried this in the [Stackblitz example](https://stackblitz.com/edit/vitest-dev-vitest-payj4m?file=vite.config.ts,test%2Fsuite.test.ts&initialPath=__vitest__) without success.

**Comment by sheremet-va** [comment]
They don't bundle ESM, so we cannot mock their call to `loglevel`. `require` mocks are not supported in Vitest, because our module resolution is asynchronous.

**Comment by christian-bromann** [comment]
That makes sense. Thanks for the clarification.

**Comment by sheremet-va** [comment]
Vitest supports mocking dynamic modules

**Comment by christian-bromann** [comment]
> Vitest supports mocking dynamic modules

But not if they are inlined dependencies. I am trying to build a reproducible but it is quite difficult.

**Comment by sheremet-va** [comment]
> > Vitest supports mocking dynamic modules
> 
> But not if they are inlined dependencies. I am trying to build a reproducible but it is quite difficult.

Mocking only works with files, that are processed by Vitest. Usually, node modules are not processed. If you use “deps.inline”, then every import inside that dependency will work with mocking system.

**Comment by christian-bromann** [comment]
Nevermind, it started to work for random reasons after debugging vitest. Not sure what has changed.
