### ISSUE TITLE
Issues importing zustand

### ISSUE THREAD

**Issue by InfraK** [vitest-dev/vitest#1338]
### Describe the bug

There is a strange issue when importing the popular state management library zustand for react. See the reproduction link for more details

The error in questions
```
❯ resolveDispatcher node_modules/react/cjs/react.development.js:1476:13
 ❯ Proxy.useReducer node_modules/react/cjs/react.development.js:1511:20
 ❯ Module.useStore node_modules/zustand/esm/index.js:46:28
     44|   const api = typeof createState === "function" ? …
     45|   const useStore = (selector = api.getState, equal…
     46|     const [, forceUpdate] = useReducer((c) => c + …
       |                            ^
     47|     const state = api.getState();
     48|     const stateRef = useRef(state);
 ❯ eval test/basic.test.ts:17:14
 ```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-wnd4i6?file=store.ts

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 133.59 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 3.2.0 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.9.0 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0.1
    Safari: 15.3
  npmPackages:
    @vitejs/plugin-react: 1.3.0 => 1.3.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
The error:
```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

Have you tried calling it inside a React hook?

**Comment by sheremet-va** [comment]
Running inside React hook works:

```tsx
export const Comp = () => {
  const { counter } = useStore()
  return <button>{counter}</button>
}
```
