### ISSUE TITLE
Printf formatting not working as expected - possible bug?

### ISSUE THREAD

**Issue by jasperdunn** [vitest-dev/vitest#1343]
### Describe the bug

The `printf` formatting isn't working as expected from the example in the [documentation](https://vitest.dev/api/#describe-each).

```ts
describe.each([
  { a: 1, b: 1, expected: 2 },
  { a: 1, b: 2, expected: 3 },
  { a: 2, b: 1, expected: 3 },
])('describe object add(%i, %i)', ({ a, b, expected }) => {
  test(`returns ${expected}`, () => {
    expect(a + b).toBe(expected)
  })
})
```

I would expect to get

```
describe object add(1, 1)
    returns 2
describe object add(1, 2)
    returns 3
describe object add(2, 1)
    returns 3
```

### Reproduction

Run the example code.

You will get output:

<img width="269" alt="Screen Shot 2022-05-20 at 10 59 48 pm" src="https://user-images.githubusercontent.com/26566353/169533097-7a73a7e6-8df6-421c-889d-91549df4d903.png">

### System Info

```shell
Node: v16.5.0
Vite: 2.9.1
Vitest: 0.9.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ooohmydawn** [comment]
I have the same problem.

**Comment by btea** [comment]
`%i, %i` should be replaced by `$a, $b`
```js
describe.each([
  { a: 1, b: 1, expected: 2 },
  { a: 1, b: 2, expected: 3 },
  { a: 2, b: 1, expected: 3 },
])('describe object add($a, $b)', ({ a, b, expected }) => {
  test(`returns ${expected}`, () => {
    expect(a + b).toBe(expected)
  })
})
```

**Comment by jasperdunn** [comment]
I didn't know that was possible, thanks!

However it doesn't format arrays and objects correctly. Anything to help with this?

```
[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
```

**Comment by btea** [comment]
You can take a look at test. Arrays and objects seem to have different formats~
https://github.com/vitest-dev/vitest/blob/f8db7d7346c3ff3650bf450f5eba93b0dd8e73ff/test/core/test/each.test.ts#L22-L58

**Comment by jasperdunn** [comment]
I'm comparing big arrays / objects of data as params into a function that I'm testing.

e.g.

```
describe.each([ 
   { a: [{value: true}, {value: false}], b: [3,4], expected: [{value: true, total: 3}, {value: false}] },
 ])('describe object fooBar(#a, #b)', ({ a, b, expected }) => { 
 ```
 
 So this doesn't solve my issue.

**Comment by btea** [comment]
This does not seem to handle complex data formats: 
https://github.com/vitest-dev/vitest/blob/f8db7d7346c3ff3650bf450f5eba93b0dd8e73ff/packages/vitest/src/runtime/suite.ts#L28-L31

**Comment by ooohmydawn** [comment]
> `%i, %i` should be replaced by `$a, $b`
> 
> ```js
> describe.each([
>   { a: 1, b: 1, expected: 2 },
>   { a: 1, b: 2, expected: 3 },
>   { a: 2, b: 1, expected: 3 },
> ])('describe object add($a, $b)', ({ a, b, expected }) => {
>   test(`returns ${expected}`, () => {
>     expect(a + b).toBe(expected)
>   })
> })
> ```

@btea  I try to run the code, but throws an error : 
```js
// error
Test result not found. 
Can you run vitest successfully on this file? Does it need custom option to run?
```

**Comment by btea** [comment]
@ooohmydawn Could you provide the code?

**Comment by ooohmydawn** [comment]
> @ooohmydawn Could you provide the code?

https://github.com/vitest-dev/vitest/issues/1343#issuecomment-1136669370 

from your example.

**Comment by btea** [comment]
I have no problem running this code locally.

**Comment by QuiiBz** [comment]
@ooohmydawn the documentation has been updated with a working example in https://github.com/vitest-dev/vitest/pull/1368

The right syntax is `add($a, $b)` instead of `add(%i, %i)`, see https://vitest.dev/api/#describe-each

**Comment by sheremet-va** [comment]
@QuiiBz is correct. `%` syntax should be used, if you use arrays instead of objects. Use `$` syntax for object properties.

**Comment by jasperdunn** [comment]
Excellent, thanks for fixing the example in the documentation!

What about an array of objects instead?

```js
describe.each([
  { a: { value: 1 }, b: { value: 1 }, expected: { value: 2 } },
  { a: { value: 1 }, b: { value: 2 }, expected: { value: 3 } },
  { a: { value: 2 }, b: { value: 1 }, expected: { value: 3 } },
])('describe object add($a, $b)', ({ a, b, expected }) => {
  test(`returns ${JSON.stringify(expected)}`, () => {
    expect(a.value + b.value).toBe(expected.value)
  })
})
```

returns:
<img width="432" alt="Screen Shot 2022-07-02 at 6 15 31 pm" src="https://user-images.githubusercontent.com/26566353/176992681-ac7ad079-0eb6-49c2-9873-264160a47d28.png">


I tried percentage as well and that also didn't work:
<img width="610" alt="Screen Shot 2022-07-02 at 6 14 46 pm" src="https://user-images.githubusercontent.com/26566353/176992661-13931ec1-751f-43d5-8936-cb1aef044221.png">
