### ISSUE TITLE
v0.12.7: regression on vi.spyOn(Storage.prototype)

### ISSUE THREAD

**Issue by cexbrayat** [vitest-dev/vitest#1344]
### Describe the bug

In previous versions, it was possible to spy on `Storage.prototype`

For example:
```
vi.spyOn(Storage.prototype, 'setItem');
```

When upgrading to v0.12.7, this now throws:
```
Error: spyOn could not find an object to spy upon
 ❯ <anonymous> test/basic.test.ts:12:5
     10| 
     11| test('JSON', () => {
     12|   vi.spyOn(Storage.prototype, 'setItem');
```

Maybe this is an intended change, but I did not see something relevant in the changelog

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-sfvqc9?file=test%2Fbasic.test.ts,package.json,vite.config.ts&initialPath=__vitest__

Revert to `0.12.6` in `package.json` to see the error go away.

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 14.97 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.volta/tools/image/node/16.15.0/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.10.0 - ~/.volta/tools/image/npm/8.10.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0.1
    Safari: 15.5
  npmPackages:
    @vitejs/plugin-vue: 2.3.3 => 2.3.3
    vite: 2.9.9 => 2.9.9
    vitest: 0.12.7 => 0.12.7
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by bjon** [comment]
I get the same error.
