### ISSUE TITLE
Unhandled error when configure `setupFiles`

### ISSUE THREAD

**Issue by sabertazimi** [vitest-dev/vitest#1346]
### Describe the bug

With `vitest.config.ts`:

```ts
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    setupFiles: 'setupTests.ts',
  },
});
```

get unhandled error:

```bash
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: Cannot read properties of undefined (reading 'length')
    at normalize (file:///home/sabertaz/git/OJs/node_modules/vitest/dist/chunk-utils-global.2fab7e5c.js:79:13)
    at file:///home/sabertaz/git/OJs/node_modules/vitest/dist/chunk-vite-node-externalize.fc385bba.js:10032:74
    at Array.map (<anonymous>)
    at resolveConfig (file:///home/sabertaz/git/OJs/node_modules/vitest/dist/chunk-vite-node-externalize.fc385bba.js:10032:60)
    at Vitest.setServer (file:///home/sabertaz/git/OJs/node_modules/vitest/dist/chunk-vite-node-externalize.fc385bba.js:10315:22)
    at Object.configureServer (file:///home/sabertaz/git/OJs/node_modules/vitest/dist/chunk-vite-node-externalize.fc385bba.js:10958:19)
    at createServer (/home/sabertaz/git/OJs/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:59950:41)
    at async createVitest (file:///home/sabertaz/git/OJs/node_modules/vitest/dist/chunk-vite-node-externalize.fc385bba.js:10984:18)
    at async startVitest (file:///home/sabertaz/git/OJs/node_modules/vitest/dist/chunk-vite-node-externalize.fc385bba.js:11071:15)
    at async start (file:///home/sabertaz/git/OJs/node_modules/vitest/dist/cli.js:665:9)
```

When change `setupTests.ts` to `./setupTests.ts`, it works correctly.

### Reproduction

- Repo link: https://github.com/sabertazimi/OJs.
- Failed CI report link: https://github.com/sabertazimi/OJs/runs/6536380411?check_suite_focus=true.

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 2.71 GB / 7.65 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 3.2.1 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Firefox: 100.0
  npmPackages:
    vitest: ^0.12.8 => 0.12.8
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
@nieyuyao maybe we should check that it resolved correctly and show an error, if file not found?

**Comment by sabertazimi** [comment]
Pull request #1347 may fix this.

**Comment by sabertazimi** [comment]
This bug introduced by #1312.

**Comment by sheremet-va** [comment]
Not sure `setupTests.ts` should be allowed. I would prefer throwing an error with a hint on how to fix it, if file is not found. Because you might mistyped it, and you will have a rough evening debugging it :P

**Comment by sabertazimi** [comment]
I think you're right. My English is poor and I can't decide which kind hint to print out, so I will close pull request #1347 and this issue.

**Comment by sheremet-va** [comment]
You know, I remembered that it will actually fail when importing, so we don't need to throw error here. I think we can actually merge your PR.

**Comment by nieyuyao** [comment]
@sheremet-va I think it needs to be fixed because it was supported before 1312. 🤔 so this pr looks ok.
