### ISSUE TITLE
process.env doesn't work when running vitest

### ISSUE THREAD

**Issue by 1018715564** [vitest-dev/vitest#1349]
### Describe the bug

process.env doesn't work when running vitest, In my method, it is executed 2 times, the first time process.env is empty, the second time it is successfully set. how can i resolve it problems? 

### Reproduction

```ts
describe('transform-event', () => {
  it('a full event object', async () => {
    process.env.platform = 'unicloud';

    const event: UnicloudEvent = {
      route: '/test/test',
      method: 'POST',
      params: {},
      query: {}
    };
    const result = await adaptEvent(event);
    expect(result).toEqual({
      req: event,
      res: null,
      url: event.route,
      method: event.method,
      params: event.params,
      query: event.query
    });
  });
});

```

```ts
// main.ts
if (process.env.VITEST) {
    // first run is 'undefined', second run is 'unicloud'
    console.log(process.env.platform);
}
```

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 161.31 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
  Browsers:
    Safari: 15.1
  npmPackages:
    vitest: latest => 0.12.8
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Can you provide a better reproduction? I don't understand how this code is suppose to work together.

Preferably with https://vitest.new/

**Comment by 1018715564** [comment]
vitest run --threads false --isolate false
