### ISSUE TITLE
Error when testing with @testing-library/user-event

### ISSUE THREAD

**Issue by hornta** [vitest-dev/vitest#1354]
### Describe the bug

I have a simple test setup with @testing-library/react and @testing-library/user-event and I want to perform a test that clicks on a button. This fails with an error: 

```TypeError: target.ownerDocument.createRange is not a function```

This is currently blocking us from moving away from Jest

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-k7rfte?file=test/basic.test.tsx

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is not Vitest API. Please open an issue in happy-dom repository or use jsdom environment.
