### ISSUE TITLE
`mocked()` does not allow constructor overloads

### ISSUE THREAD

**Issue by simon-abbott** [vitest-dev/vitest#1362]
### Describe the bug

I can't use `vi.mocked()` with a class that has constructor overloads, because it only passes through the last overload. This causes any use of any other overloads to fail type checking. Since overloads are a pure-ts thing the tests _run_ fine, but they break ts builds.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-tc6u5m?file=test/basic.test.ts

### System Info

```shell
npmPackages:
    vitest: 0.12.9 => 0.12.9
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is just how typescript works. If you have any overload, I suggest you just cast a type.
