### ISSUE TITLE
Vitest tries to bind to HMR port

### ISSUE THREAD

**Issue by erikpukinskis** [vitest-dev/vitest#1363]
### Describe the bug

I'm running Vitest in codespaces, which normally works great. But in projects where I also have a dev server set up, when I set the HMR port in the vite config, it causes Vitest to throw an error:

```
WebSocket server error:
Error: listen EACCES: permission denied 0.0.0.0:443
    at Server.setupListenHandle [as _listen2] (node:net:1313:21)
    at listenInCluster (node:net:1378:12)
    at Server.listen (node:net:1465:7)
    at new WebSocketServer (/workspaces/vitest-port-bug/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:51165:20)
    at createWebSocketServer (/workspaces/vitest-port-bug/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:51616:15)
    at createServer (/workspaces/vitest-port-bug/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:59794:16)
    at async createVitest (file:///workspaces/vitest-port-bug/node_modules/vitest/dist/chunk-vite-node-externalize.42b0363f.js:10993:18)
    at async startVitest (file:///workspaces/vitest-port-bug/node_modules/vitest/dist/chunk-vite-node-externalize.42b0363f.js:11080:15)
    at async CAC.start (file:///workspaces/vitest-port-bug/node_modules/vitest/dist/cli.js:665:9)
 √ true.test.ts (1)

Test Files  1 passed (1)
     Tests  1 passed (1)
      Time  1.09s (in thread 2ms, 54691.21%)

 PASS  Waiting for file changes...
```

As you can see, it doesn't interfere with Vitest running and the tests passing, it's just an uncaught exception that leaks out. 

I have a minimal test case that fails right here: https://github.com/outerframe/vitest-port-bug. The bug is caused by the Vite config below. Without this it runs just fine:

```
    server: {
        hmr: {
            port: 443
        }
    }
```

It also runs fine for me on my local machine, but in a Codespace with I presume stricter security controls it fails. I think maybe on Linux by default you can't bind to 443 unless you are root, but on MacOS maybe that's OK?

What's interesting is that a dev server with this config starts up just fine in the Codespace, binds to 443 and then can be accessed from the outside! So it's not like there's something broken about setting that port. It's just Vitest that throws this error. I'm not sure why Vitest is even looking at that config though.

If anyone would like access to a Codespace on that repo, just let me know and I'll add you as a collaborator and you can just pop open a Codespace!

### Workaround

I'm able to get around this by creating a separate Vite config for Vitest and removing that `server` config, but this makes my config a bit messier so I'd like to avoid it.

### Reproduction

https://github.com/outerframe/vitest-port-bug

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 2.13 GB / 3.84 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nodejs/current/bin/node
    Yarn: 1.22.15 - /opt/yarn/stable/bin/yarn
    npm: 8.5.0 - ~/.nodejs/current/bin/npm
  npmPackages:
    vite: ^2.9.9 => 2.9.9 
    vitest: ^0.12.9 => 0.12.9 
```
```


### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by erikpukinskis** [comment]
> I'm using [a bit different approach here](https://github.com/AriPerkkio/vite-everything/blob/043067c62a0117cfcc889d0ee62ed278b3b9e97f/vite.config.ts#L21-L22).

@AriPerkkio I love that idea! That's a much simpler workaround.

Although in my case, my `NODE_ENV` seems to be `development` in both the tests and during dev server start, so I'd have to find a way to change that first.

**Comment by antfu** [comment]
Vitest fires up a Vite server under the hood, which ofc, reads all Vite configs to align with Vite's behavior. I'd recommend using a separate `vitest.config.js` file. Refer to https://vitest.dev/guide/#configuring-vitest
