### ISSUE TITLE
support importmap

### ISSUE THREAD

**Issue by aladdin-add** [vitest-dev/vitest#1365]
### Clear and concise description of the problem

refs: https://nodejs.org/api/packages.html#subpath-imports

I was using 
* node.js v18.1.0
* vitest v0.12.4

the package.json imports:
```json
{
  "imports": {
    "#@": "./src/"
  },
}
```

```js
import { actuator } from '#@/actuator.js'
```

got the err:

```bash
 FAIL  __tests__/actuator.spec.ts [ __tests__/actuator.spec.ts ]
Error: [vite-node] Failed to load #@/actuator.js
```

### Suggested solution

just load the module successfully.

### Alternative

n/w

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
We are using Vite's `resolveId` function on `pluginContainer`, so this is more about Vite's support. Please, open an issue in their repository.

**Comment by sheremet-va** [comment]
Please, follow this PR in Vite, if you are interested in this feature: https://github.com/vitejs/vite/pull/7770

**Comment by sheremet-va** [comment]
Should be supported since https://github.com/vitejs/vite/pull/7770
