### ISSUE TITLE
Module graph reports multiple times same modules imports

### ISSUE THREAD

**Issue by underfisk** [vitest-dev/vitest#1374]
### Describe the bug

I have been playing around with the module graph and I was curious if the reported modules are actually duplicated or if it's just an analysis of the file imports because it looks like lodash is represented more than once and some other packages (mostly @mui related but even testing library appears multiple times).

<img width="686" alt="Screenshot 2022-05-25 at 7 19 38 PM" src="https://user-images.githubusercontent.com/15980884/170338160-c10784d1-6d55-4e10-9bc1-42c3ceeaf005.png">

### Reproduction

https://github.com/underfisk/vitest-module-graph

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.49 GB / 64.00 GB
    Shell: 3.2.2 - /usr/local/bin/fish
  Binaries:
    Node: 16.15.0 - ~/.volta/tools/image/node/16.15.0/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 8.5.5 - ~/.volta/tools/image/node/16.15.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Safari: 15.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by underfisk** [comment]
@nieyuyao Correct, i believe that for the testing library it does make sense but `jest-dom` is invoked only at the setup file so its not directly invoked through the file.

**Comment by sheremet-va** [comment]
> @nieyuyao Correct, i believe that for the testing library it does make sense but `jest-dom` is invoked only at the setup file so its not directly invoked through the file.

Setup file is part of the suite, tho. Module Graph shows you every module that was invoked durug the run.
