### ISSUE TITLE
Importing `.mjs` breaks leaf imports

### ISSUE THREAD

**Issue by JoviDeCroock** [vitest-dev/vitest#1375]
### Describe the bug

in [preact-testing-library](https://www.runpkg.com/?@testing-library/preact@3.1.1/dist/esm) we point the `import` export map entry at the `.mjs` file which subsequently imports other files. I have tried a few things like:

- converting everything to import with `.js` extensions --> works but doesn't work in node as it needs `.mjs` or `type: nodule`
- adding `.mjs` extensions in the imports --> does not work

The error states:

```
Error: Cannot find module '\my-test-app\node_modules\@testing-library\preact\dist\esm\pure' imported from \my-test-app\node_modules\@testing-library\preact\dist\esm\index.mjs
```

### Reproduction

https://github.com/JoviDeCroock/vitest-repro

run `yarn` and then `yarn test`

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 7.22 GB / 15.94 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 101.0.4951.67
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vite: ^2.9.9 => 2.9.9
    vitest: ^0.12.9 => 0.12.9
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is just how Node works. More explanation: https://github.com/sheremet-va/dual-packaging

**Comment by sheremet-va** [comment]
according to https://nodejs.org/api/esm.html (see import specifiers) import statements need file extension. Your mjs files import pure without it.

**Comment by JoviDeCroock** [comment]
As the linked pr and the explanation, even with it seems to fail 😅 but yes I'll experiment further might have misunderstood

**Comment by sheremet-va** [comment]
> As the linked pr and the explanation, even with supplied extensions it seems to fail 😅 but yes I'll experiment further might have misunderstood

Hm, for me the changes in the PR don't change how `imports` are built. I still see statements without extensions. If I change manually files to use `.mjs` in the import statement, everything works find for me.

**Comment by JoviDeCroock** [comment]
You are right, I had to add it to the export all specifier as well which I forgot, apologies and thank you!
