### ISSUE TITLE
Inline snapshots not being created

### ISSUE THREAD

**Issue by p4bloch** [vitest-dev/vitest#1376]
### Describe the bug

Under some specific settings unkown to me yet (dependencies, maybe?), inline snapshots do not work. To be more specific:
- They are not written when there is only one `toMatchInlineSnapshot` assertion
- They are written to the wrong assertion when there are more than one

This happened to my first project with vite/vitest and for a while assumed that they just weren't working but trying out a new project from scratch didn't have this issue. I believe this is somewhat of an edge case, and even though I narrowed my dependencies to the bare minimum in a StackBlitz project, I cannot seem to find the root cause.

Thanks!

### Reproduction

1. Go to https://stackblitz.com/edit/vitejs-vite-vxrdhg?file=tests/unit/utils/dates.spec.js&view=editor
2. Run `npm run test`
3. See how the second snapshot gets created with the value of the first snapshot.

More variants:
- Remove the second test block, see how vitest says the snapshot was written but it is not

### System Info

```shell
I don't think this is relevant given there is a StackBlitz repro, but still

  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 963.97 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Brave Browser: 97.1.34.81
    Chrome: 101.0.4951.64
    Firefox: 100.0.2
    Safari: 14.1.1
  npmPackages:
    @vitejs/plugin-vue: ^2.3.3 => 2.3.3
    vite: ^2.9.9 => 2.9.9
    vitest: ^0.12.9 => 0.12.9
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I found that the problem is with the source map for `.js` files:

https://github.com/vitest-dev/vitest/blob/3199dc7d689a58033336bdd99075c0833d39aa81/packages/vitest/src/utils/source-map.ts#L15

This line returns invalid original position. Need investigating.

**Comment by p4bloch** [comment]
Just updated to 0.15.2 and can now use inlineSnapshots in the project. Many thanks @sheremet-va 🙇
