### ISSUE TITLE
Compatible names with Jest Snapshots

### ISSUE THREAD

**Issue by moltar** [vitest-dev/vitest#1380]
### Clear and concise description of the problem

While migrating from Jest, lots of snapshots get replaced, just because of the name.

But the issue is that it's not just the name change. Because the name is different, the snapshot is not found, and thus it is re-generated as if it did not exist.

```ts
describe('foo', () => {
  it('bar', () => {
    // ...
  })
})
```

```diff
- foo bar
+ foo > bar
```

### Suggested solution

Allow for compatibility with Jest snapshot naming.

### Alternative

Update every single snapshot, which causes huge diffs.

### Additional context

Jest 26.6.3

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
There comes a point where we can't be compatible with Jest. And snapshot naming is one of the Jest's pains. We don't like it and we use our own way, so you will need to rebuild all your snapshots. 

They are 100% compatible otherwise, so you shouldn't worry about commit size.

**Comment by sheremet-va** [comment]
#686 is about pressing `u` in terminal. If Vitest doesn't remove snapshots on `vitest run`, please, open another issue.
