### ISSUE TITLE
Unable to use local variable as argument for `vi.fn().mockReturnValue()`

### ISSUE THREAD

**Issue by abineetds** [vitest-dev/vitest#1381]
### Describe the bug

Hello, 

I'm running into this issue where I'm unable to use local variable as argument for `vi.fn().mockReturnValue()`. I want to be able to have the variable be an object which points to another method that I want to check is getting called.

Code sample below.

Thanks

### Reproduction

```
import { beforeEach, describe, expect, it, vi } from "vitest";
import * as authHelpers from 'my_library';
import apiHandler from './some_path';

describe('test', () => {
  let mockClient;

  beforeEach(() => {
    mockClient = {
      handleAuth: vi.fn().mockReturnValue(vi.fn())
    };
    vi.mock('my_library', async () => {
      const library = await vi.importActual('my_library');
      return ({
        ...library,
        init: vi.fn().mockReturnValue(mockClient)
      });
    });

  it('test run', async () => {
    ...
  });
});
```

The above throws an error that `mockClient is not defined`.

When I replace it with `initAuth0: vi.fn().mockReturnValue(vi.fn().mockReturnValue(vi.fn()))` everything works.

### System Info

```shell
System:
    OS: macOS 12.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 114.89 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Safari: 15.0
  npmPackages:
    @vitejs/plugin-react: ^1.3.1 => 1.3.1 
    vite: ^2.9.7 => 2.9.7 
    vitest: ^0.10.0 => 0.10.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Yes, you cannot access variables, because `vi.mock` is hoisted to the top of the file. This is by design.

**Comment by sheremet-va** [comment]
You can use `vi.doMock` for this, but beware that already imported modules are not mocked, and you will probably need to `await import` after you mock a module.

**Comment by sheremet-va** [comment]
> > This is by design.
> 
> Is there any plan in the future to implement this? I know that jest has an exception in that variables that start with `mockFooBar` are allowed inside jest.mock

I don't like the jest convention, but we can implement something more explicit:

```ts
import { getValue } from './path.js'
const mocks = vi.hoisted(() => {
  return {
    someVariable: '1'
  }
})

vi.mock('./path.js', () => {
  return { getValue: () => mocks.someVariable }
})

mocks.someVariable = '1'
expect(getValue).toBe('1')
mocks.someVariable = 33
expect(getValue).toBe(33)
```
