### ISSUE TITLE
Both CJS and ESM versions of dependency loaded, causing React Context mismatch in test

### ISSUE THREAD

**Issue by carlosdp** [vitest-dev/vitest#1387]
### Describe the bug

In [my repo](https://github.com/metaphor-xyz/ens-small-grants), I have some context that is not being recognized by another package. I've identified the issue as caused by the [React provider](https://github.com/metaphor-xyz/ens-small-grants/blob/main/src/test/utils.tsx#L22) being loaded from the ESM version of the `wagmi` package, but the [next context](https://github.com/metaphor-xyz/ens-small-grants/blob/main/src/test/utils.tsx#L24) which consumes the `WagmiConfig` context, loading the CJS version of the `wagmi` package. Because react context is based on a global, having two different files loaded is causing context to not work.

The app works fine in `vite dev`! I'm having trouble tracking down why `vitest` is loading the ESM version of the `wagmi` dependency in the direct reference, but the CJS one when referenced from the `@rainbow-me/rainbowkit` package.

### Reproduction

https://github.com/metaphor-xyz/ens-small-grants

`yarn install && yarn test`

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 81.39 MB / 16.00 GB
    Shell: 3.4.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.14.2 - ~/.local/share/nvm/v16.14.2/bin/node
    Yarn: 3.2.1 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - ~/.local/share/nvm/v16.14.2/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 101.1.38.119
    Chrome: 102.0.5005.61
    Firefox: 92.0
    Safari: 15.4
  npmPackages:
    @vitejs/plugin-react: ^1.3.0 => 1.3.2
    vite: ^2.9.9 => 2.9.9
    vitest: ^0.12.9 => 0.12.9
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by carlosdp** [comment]
A little more investigation on this, I found a workaround by inlining `@rainbow-me/rainbowkit`:

```typescript
/// <reference types="vitest" />
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vite';

// https://vitejs.dev/config/
export default defineConfig({
  define: {
    global: process.env.VITEST ? 'global' : 'globalThis',
  },
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: './src/test/setup.ts',
    deps: {
      inline: ['@rainbow-me/rainbowkit'],
    },
  },
});
```

I dug into a little of how the `VitestPlugin` works, it seems likely the culprit here is resetting the `mainFields` config option:

https://github.com/vitest-dev/vitest/blob/3d8eba4e8bcfdee7c6f0800fb637e9814fb2c583/packages/vitest/src/node/plugins/index.ts#L72-L77

However, simply removing that line causes other libraries to break, because of the behavior described in the comment. This workaround is fine, but I'm wondering if there is a way to fix this behavior, since it does work fine in the Vite dev server. It's also a very tricky bug to track down, I spent several hours figuring this out!

**Comment by sheremet-va** [comment]
`mainFields` is a field on top level of your `package.json`. Usually Node cannot import this files, because they are not actually ESM (for example, named `.js` in a `commonjs` package). This is why it is disabled.

Vitest imports a cjs version of `wagmi` package, because their [`exports` field](https://github.com/tmm/wagmi/blob/main/packages/core/package.json) is incorrect. See [explanation](https://github.com/sheremet-va/dual-packaging).

The right way to do it is to create an issue in the repo and fix it. And inline dependency, while they are fixing it.
