### ISSUE TITLE
Unknown file extension ".css" when using with unplugin-vue-components

### ISSUE THREAD

**Issue by WodahsOrez** [vitest-dev/vitest#1388]
### Describe the bug

In my case, I just use element-plus , unplugin-vue-components and vitest together。it shows this expcetion
![image](https://user-images.githubusercontent.com/41291430/170829482-06ec1e86-925b-4301-8da4-35e3f0f15401.png)
all i did is in this commit [ca52a35](https://github.com/WodahsOrez/vitesse-my/commit/ca52a3558e57621b5b03c142d31b33509f880ebc)

### Reproduction

https://github.com/WodahsOrez/vitesse-my
`pnpm install && pnpm test`

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 14.01 GB / 31.87 GB
  Binaries:
    Node: 14.17.6 - D:\Code\Environment\nodejs\node.EXE
    Yarn: 1.22.17 - D:\Code\Environment\nodejs\node_global\yarn.CMD
    npm: 6.14.15 - D:\Code\Environment\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Add `element-plus` to `deps.inline`, [see docs](https://vitest.dev/config/#deps-inline)

**Comment by songyu641660583** [comment]
请问这个问题解决了吗，我也遇到相同的问题

**Comment by songyu641660583** [comment]
> 添加`element-plus`到`deps.inline`，[请参阅文档](https://vitest.dev/config/#deps-inline)



> 添加`element-plus`到`deps.inline`，[请参阅文档](https://vitest.dev/config/#deps-inline)

![image](https://user-images.githubusercontent.com/30134628/235073831-8eb4a08a-a3e9-4dda-bc24-842f072d081d.png)

**Comment by canbax** [comment]
there is not `test` property inside `options` object

**Comment by silverwind** [comment]
Also ran into this issue with a module that was using [`vite-plugin-libcss`](https://github.com/wxsms/vite-plugin-libcss) to bundle its CSS file. `deps.inline` works, but I wonder if there if vitest could be automatically made to handle such CSS imports, or if there is a better solution than `vite-plugin-libcss` for CSS bundling without requiring an explicit CSS file import on the consumer side.
