### ISSUE TITLE
Add support for self-referencing the current package in tests

### ISSUE THREAD

**Issue by ifiokjr** [vitest-dev/vitest#1394]
### Clear and concise description of the problem

As a user of `vitest` I would like to self reference the current package by name when importing in a test. This is a [builtin node](https://nodejs.org/api/packages.html#self-referencing-a-package-using-its-name) feature for projects which specify `"type": "module"`.

Given a folder structure of:

```
my-package/
├─ package.json
├─ index.js
├─ tests/
│  ├─ my-package.spec.js
```

And files with this content:

```json5
// my-package/package.json

{
  "name": "my-package",
  "type": "module",
  "exports": "./index.js"
}
```

```js
// my-package/tests/my-package.spec.js

import myPackage from 'my-package';
import { test, expect } from 'vitest';

test('myPackage', () => {
  expect(myPackage).toBeTruthy();
})
```

I would like to be able to write the following in the test folder. Currently, when I do this I get the following error: 

```diff
- Error: [vite-node] Failed to load my-package
```

### Suggested solution

I'm not sure whether this is a request that should be raised in `vite`, or should be added as a `vite-plugin`.

#### Example

Here is a reproduction of the current issue faced: https://stackblitz.com/edit/github-w9fjy7-bba6ny?file=my-package.spec.js

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
You can set alias in your vite.config.ts

```ts
export default defineConfig({
  resolve: {
    alias: {
      'my-package': resolve('./src/index.ts')
    }
  }
})
```

**Comment by ifiokjr** [comment]
Thanks @antfu this works. 

In a monorepo environment with multiple packages, each package will have to be added as an alias, which means all packages will be available from all test code regardless of location. 

Ideally, the location of the test should determine how self-reference package names are resolved. 

I'll see if I can create a general purpose `vite` plugin to handle this.
