### ISSUE TITLE
Vitest ui throws SyntaxError when starting

### ISSUE THREAD

**Issue by nieyuyao** [vitest-dev/vitest#1399]
### Describe the bug

An error occurred when upgrading to the latest version of vitest and starting the `vitest -ui`.

```javascript
Uncaught SyntaxError: Unexpected token '-'
```
<img width="868" alt="image" src="https://user-images.githubusercontent.com/17698194/171002560-a96f3b4a-196d-4443-8d39-ffbaa5c08f4e.png">

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-peyoui?file=test%2Fbasic.test.ts

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 190.04 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Chrome Canary: 103.0.5048.0
    Edge: 97.0.1072.55
    Firefox: 100.0.2
    Safari: 15.1
  npmPackages:
    vite: latest => 2.9.9 
    vitest: 0.13.0 => 0.13.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hugoattal** [comment]
I got the same bug, it seems to be introduced by 12.10 (It works on 12.9 and below, and stop working on 12.10 and 13.0)

I'm taking a look right now. (I'll do a PR if I find anything)

**Comment by hugoattal** [comment]
Pretty weird, but I identified that commit to be the culprit... And it only updated the pnpm-lock file 🤔...
https://github.com/vitest-dev/vitest/commit/3d8eba4e8bcfdee7c6f0800fb637e9814fb2c583

**Comment by nieyuyao** [comment]
@hugoattal yes, -1 should be surrounded by quotes. so the error was thrown when parsing script.

**Comment by nieyuyao** [comment]
@hugoattal I noticed that the vite version has changed, is this the problem? 🤔

**Comment by hugoattal** [comment]
@nieyuyao I didn't see any vite version change in the suspect commit (https://github.com/vitest-dev/vitest/commit/3d8eba4e8bcfdee7c6f0800fb637e9814fb2c583), where did you see that?

**Comment by nieyuyao** [comment]
@hugoattal  The code will be incorrect after being processed by the `buildEsbuildPlugin`.

https://github.com/vitejs/vite/blob/e7843657ac81a94af07bec3c290ee579cc19aa0f/packages/vite/src/node/plugins/esbuild.ts#L227
