### ISSUE TITLE
Test result not found on VS Code Ext

### ISSUE THREAD

**Issue by acostaf** [vitest-dev/vitest#1407]
### Describe the bug

Right clicking the test on Vscode returns “Test result not found”

### Reproduction

Right clicking the test on Vscode

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 16.94 GB / 31.78 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-react: ^1.3.2 => 1.3.2
    vite: ^2.9.9 => 2.9.9
    vitest: ^0.12.9 => 0.12.10
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by itpropro** [comment]
I have the same problem in VSCode with a simple test that just checks for `toBeDefined`. In the terminal it works fine including watch mode, in VSCode, it throws the following error:
![image](https://user-images.githubusercontent.com/15030951/172620422-8f6bb2fe-3cca-4bca-a6c0-c397d7190412.png)

**Comment by itpropro** [comment]
Multiple issues were fixed by @zxch3n in the vscode repository (thanks!). If @acostaf doesn't have any additional problems, I think we can close this issue.

**Comment by acostaf** [comment]
Fixed, thanks everyone.

**Comment by denisonepiece** [comment]
@acostaf not working with multiple workspaces in last version. After opening folder in new vscode window, everthing is ok. Maybe reproducing on macos?

**Comment by enekaken** [comment]
I'm encountering the same bug.. 

tried the command line option cd to the root where my package lies in my workspace along with ` && rushx test` but getting this error.

![image](https://user-images.githubusercontent.com/60019746/183112130-0928a5cf-dbff-4e03-bcaa-12fe2b7c5841.png)

```
  "@vitejs/plugin-react": "^1.3.1",
"vite": "^2.9.9",
"vitest": "^0.20.3"
```

**Comment by sheremet-va** [comment]
Please, if you have an issue with vscode extension, open an issue in [its repository](https://github.com/vitest-dev/vscode).
