### ISSUE TITLE
window.getComputedStyle is not a function inside setInteval under heavy load

### ISSUE THREAD

**Issue by alfeg** [vitest-dev/vitest#1415]
### Describe the bug

We stumbled upon test flakiness caused by third party library.
I managed to make a minimum repro without third party but using same code pattern.

Sample Vue component that illustrate issue
```vue
<template>
  <div>
    <div>Hello</div>
  </div>
</template>
<script setup lang="ts">
import { ref } from 'vue';

const main = ref(null);
const el = window.document.body;
window.getComputedStyle(el).fontFamily;

setInterval(() => {
  const el = window.document.body;
  window.getComputedStyle(el).fontFamily;
}, 1);
</script>
```

Sample test file 
```typescript
describe('suite name ' + i,  () => {
    it('hello', () => {
      const wrapper = mount(Hello});
      expect(wrapper.text()).toBe('Hello');  
    });
});
```

Executing this test along will not cause any errors. 
But when there is a 10-100 files are executing in parallel, then sometime this error is produced:
(window is not defined inside the body of `setInterval` function)
```
node:internal/event_target:912
  process.nextTick(() => { throw err; });
                           ^
ReferenceError [Error]: window is not defined
    at Timeout._onTimeout (C:/src/exp/vitest-dev-vitest-mkcbtg/Hello.vue:13:19)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
Emitted 'error' event on Tinypool instance at:
    at EventEmitterReferencingAsyncResource.runInAsyncScope (node:async_hooks:202:9)
    at Tinypool.emit (file:///C:/src/exp/vitest-dev-vitest-mkcbtg/node_modules/tinypool/dist/esm/index.js:59:31)
    at Worker.<anonymous> (file:///C:/src/exp/vitest-dev-vitest-mkcbtg/node_modules/tinypool/dist/esm/index.js:543:30)
    at Worker.emit (node:events:527:28)
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
```

### Reproduction

For some reason StackBlitz is running fine - without errors. But on local Windows machine this fails almost every time. On our CI those tests are failing under Ubuntu system.

https://github.com/alfeg/vitest-dev-vitest-mkcbtg 

May require multiple reruns to hit an error.

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 2.85 GB / 15.41 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (101.0.1210.53)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitejs/plugin-vue: ^2.3.3 => 2.3.3
    vite: ^2.9.9 => 2.9.9
    vitest: latest => 0.13.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is not an error on Vitest side. You need to clear side effects yourself. Vitest cannot do this for you.

**Comment by sheremet-va** [comment]
I should've elaborated before closing issue:

Your code is running outside of test, hence why `window` is undefined (jsdom is destoyed after tests are run). Destoying might code before your `setTimeout` function run, or sometimes after. Whenever Node decides to run it.

**Comment by sheremet-va** [comment]
Also running `concurrent` on anything dom-related is highly discouraged, because your tests compete of what comes first.

**Comment by alfeg** [comment]
@sheremet-va 
Thanks for reponse.

I've added concurrent only to make more flaky.

Issue here is that I cannot control 3rd party library https://github.com/DevExpress/DevExtreme/blob/6750b4ceb9f4c7fdab1143d5cc7495e9c12130b5/js/ui/themes.js#L91  
setInterval is executed during import of the page

There is no way to prevent this setInterval execution in current Vitest implementation.
