### ISSUE TITLE
`Mr is null` running `--ui`

### ISSUE THREAD

**Issue by beefchimi** [vitest-dev/vitest#1418]
### Describe the bug

On the latest version of `vitest + @vitest/ui` _(`0.13.1`)_, running `vitest --ui` will:
- Run all tests in the console and indicate they have passed
- Open a new browser window to the `localhost` UI page
- Nothing loads on the `localhost` page...
- Inspecting the `dev console` gives an error `Mr is null`

![mr-is-null](https://user-images.githubusercontent.com/643944/171864249-f1952714-921e-4af8-a534-43c12caaca9b.png)

### Reproduction

This was introduced in the following commit:
https://github.com/beefchimi/react-hooks/pull/44/commits/d62a41313c42f9166572cc498540cc293eae79bf

From this repo:
https://github.com/beefchimi/react-hooks

Without that commit - using the previous `0.9.4` version of `vitest` - `vitest --ui` works as expected.

### System Info

```shell
System:
  OS: macOS 12.4
  CPU: (10) arm64 Apple M1 Max
  Memory: 8.67 GB / 32.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 17.3.0 - ~/.nvm/versions/node/v17.3.0/bin/node
  Yarn: 1.22.15 - ~/.nvm/versions/node/v17.3.0/bin/yarn
  npm: 8.3.0 - ~/.nvm/versions/node/v17.3.0/bin/npm
Browsers:
  Firefox: 100.0.2
  Safari: 15.5
npmPackages:
  @vitejs/plugin-react: ^1.3.2 => 1.3.2 
  vite: ^2.9.9 => 2.9.9 
  vitest: ^0.13.1 => 0.13.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by madrus** [comment]
I have not traced the code but tried to install different versions. The above mentioned error was introduced in `v0.12.10` (the last one working fine is v0.12.9). And beginning from `v0.13` up until the now latest `0.14.1` the errors have multiplied: 

![image](https://user-images.githubusercontent.com/7058116/172290226-099cf832-7cd8-4095-a7c0-ef6c9d909c36.png)

For now, I have downgraded to `v0.12.9` to keep enjoying the UI.
