### ISSUE TITLE
Fails test when `assert { type: 'json' }` is used

### ISSUE THREAD

**Issue by aMediocreDad** [vitest-dev/vitest#1419]
### Describe the bug

I have noticed I cannot use the import type assertions that were included with Node 16.14.2 and onwards.

With Node 16.14.2, JSON import in ESM modules have landed on the same spec as browsers. 

```js
import jsonFile from './some-json.json' assert { type: 'json' }
```

However using this syntax in a test module or any module imported (recursively) by Vitest results in a syntax error.

This is somewhat strange as Vite otherwise bundles files like these without issue.

### Reproduction

See an example based on the `basic` example in this repo: https://github.com/aMediocreDad/vitest-json-assert

> Stackblitz cannot be used due to lack of support for LTS node.

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 433.97 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.1.0 - ~/.volta/tools/image/node/18.1.0/bin/node
    npm: 8.9.0 - ~/.volta/tools/image/npm/8.9.0/bin/npm
  Browsers:
    Firefox: 100.0.2
    Safari: 15.4
  npmPackages:
    vite: ^2.9.9 => 2.9.9 
    vitest: latest => 0.13.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It works for you because it is not processed by ssr. Ssr rewrites imports to a custom function, that's why assertions are left out
