### ISSUE TITLE
[proposal] move `examples` out of pnpm workspace

### ISSUE THREAD

**Issue by pd4d10** [vitest-dev/vitest#1440]
### Clear and concise description of the problem

The projects under `examples` folder are currently in the pnpm workspace, which causes slow installation. And it would become slower as the number of examples grows, 

Since the examples are hosted at [StackBlitz](https://github.com/vitest-dev/vitest/blob/main/examples/README.md), and don't involve any development or CI process, I thought it might be better to move these out of pnpm workspace.

Just tested it locally: The line number of `pnpm-lock.yaml` went from 20k+ to less than 10k

### Suggested solution

Move `examples` out of pnpm workspace.

I'll submit a PR if this can be agreed.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I approve 👍🏻

**Comment by antfu** [comment]
We are using them for CI tests.

**Comment by sheremet-va** [comment]
> We are using them for CI tests.

Can we have sub-monorepo? :P

**Comment by pd4d10** [comment]
> We are using them for CI tests.

Oh, I missed that. The CI did fail: https://github.com/vitest-dev/vitest/runs/6751171711?check_suite_focus=true

I'll look into it later to find better solution

**Comment by antfu** [comment]
Sub-monorepo will cause more duplication and it would be more complex to link-local packages for testing.

I guess if you really want to reduce the packages installed you might want to use [`pnpm install --fitler ./packages/*`](https://pnpm.io/cli/install#--filter-package_selector) (I didn't test).
