### ISSUE TITLE
Terminal output obscures user prompts

### ISSUE THREAD

**Issue by douglance** [vitest-dev/vitest#1447]
### Describe the bug

We use [`readline-sync`](https://www.npmjs.com/package/readline-sync) to prompt the user to interact with the test suite as it's running. We need to do this because our tests are running against a hardware product that must be set into a particular state for tests to complete successfully. 

The bug is that `readline-sync` generates output to the terminal that awaits for user input. These user input requests can destroyed by `vitest`'s output, which makes it hard for users to interact with the terminal while `vitest` is running.  

If you run the reproduction with just `example.test.ts` active, it will hang on the `beforeAll` and you'll either see a prompt briefly or not at all. If you hit enter while it's stuck loading, the test will complete. 

It seems like the loading indicator animation in the terminal is affecting the rendering of the terminal output. If you remove the `beforeAll' statement in the reproduction, it will not clear out the user input request; and you'll be able to hit enter to complete the test.

Also, you can make the terminal non-responsive if you run both `example.test.ts` and `example2.test.ts` at the same time, and hit enter in the terminal.

If this is a good issue for a first-time contributor, please let me know where to start. Though it seems like it is a pretty complicated one that is related to the stdout rendering. 

Thanks!

### Reproduction

Here's the [Repo](https://github.com/douglance/vitest-dev-vitest-h4xxy9) of the minimal reproduction. I don't think the [StackBlitz](https://stackblitz.com/edit/vitest-dev-vitest-h4xxy9?file=test/example.test.ts) version of the repo works very well. I think the StackBlitz sandbox is interfering with it.

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor             
    Memory: 43.02 MB / 32.00 GB
    Shell: 5.8.1 - /usr/local/bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: 2022.02.28.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 101.1.38.111
    Chrome: 102.0.5005.61
    Chrome Canary: 104.0.5104.0
    Firefox: 101.0
    Firefox Developer Edition: 100.0
    Safari: 15.1
  npmPackages:
    vitest: ^0.13.1 => 0.13.1 
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by douglance** [comment]
I looked into this deeper. The default reporter [renders every 200ms](https://github.com/vitest-dev/vitest/blob/3199dc7d689a58033336bdd99075c0833d39aa81/packages/vitest/src/node/reporters/renderers/listRenderer.ts#L107) and uses [Sindre Sorhaus's log-update](https://github.com/sindresorhus/log-update), which wipes the local console output when it renders.

**Comment by douglance** [comment]
`log-update` actually has a system where if the output doesn't change, then it doesn't re-render. So if we disable the loading spinner, then output is consistent, and therefore user prompts in the CLI remain there are are interactable.

**Comment by douglance** [comment]
So if we were to set [this](https://github.com/vitest-dev/vitest/blob/3199dc7d689a58033336bdd99075c0833d39aa81/packages/vitest/src/node/reporters/renderers/utils.ts#L127) and [this](https://github.com/vitest-dev/vitest/blob/3199dc7d689a58033336bdd99075c0833d39aa81/packages/vitest/src/node/reporters/renderers/utils.ts#L157=) spinner to a static symbol, perhaps `⟳`, then we could allow users to have input with the CLI using the Default reporter. 

Maybe we could have a `prefersReducedMotion` config option like in the browser? I'm not sure the best way to approach a solution here.

**Comment by sheremet-va** [comment]
> Maybe we could have a `prefersReducedMotion` config option like in the browser? I'm not sure the best way to approach a solution here.

I think we can do that.

**Comment by sheremet-va** [comment]
You can just use `verbose` or `basic` reporter now to remove the spinner. Generally speaking, I think it's better to mock the stream or provide your own implementation when testing CLI interactions.
