### ISSUE TITLE
`vi.mock` ignored if module is imported in setup file

### ISSUE THREAD

**Issue by MaartenPetiet** [vitest-dev/vitest#1450]
### Describe the bug

Registration of `vi.mock` on a module will not work if that module is imported in a file added to the `setupFiles` array in `vite.config.ts`.

### Use case

We use Vue 3 with global component registration (this is needed because of the way our CMS works). To accomplish this in our tests, we register these components in `vitest.setup.ts` to the `@vue/test-utils` config as the example below.

```js
import { config } from '@vue/test-utils';

config.global.components[name] = component;
```

This causes the mocks set on the imports of these components to be ignored. Although this is our use case, this issue is unrelated to Vue. See the minimal reproduction for more details.

### Reproduction

Here is a minimal repo: https://stackblitz.com/edit/vitest-dev-vitest-etmse4?file=vitest.setup.ts

In `test/foo.test.ts` a mock is used. This fails, unless I remove the only line in `vitest.setup.ts`.

### System Info

```shell
System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
    Memory: 4.85 GB / 16.00 GB
  Binaries:
    Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 102.0.5005.63
    Internet Explorer: 11.0.17763.2145
  npmPackages:
    @vitejs/plugin-vue: ^2.3.3 => 2.3.3
    vite: ^2.9.9 => 2.9.9
    vitest: 0.14.1 => 0.14.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MaartenPetiet** [comment]
Thanks, I have added `vi.resetModules()` at the end of `vitest.setup.ts` to only call it once and that seems to work too.

**Comment by sheremet-va** [comment]
Module was already evaluated and cached with code that you provided in setup, so when it is imported next time, it uses this cached version. I don't think there is a good way for us to clear that cache automatically, so you need to use `vi.resetModules`.
