### ISSUE TITLE
pretty-format doesn't format snapshots for svelte

### ISSUE THREAD

**Issue by vish01** [vitest-dev/vitest#1463]
### Describe the bug

I'm having issue with snapshot formatting. After I run tests, it creates snapshots with all code in one line. The svelte example in this repo represents the same.

### Reproduction

https://github.com/vish01/svelte-vitest-repro

### System Info

```shell
System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 11.63 GB / 31.85 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: master_preferences.txt
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    vitest: latest => 0.14.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`innerHTML` returns a string in one line. Vitest just saves the raw string and matches against it, it doesn't know it's an HTML . Try passing down DOM element itself.

**Comment by vish01** [comment]
@sheremet-va Got it to work by passing in just the DOM element and modify the tests a bit. Also, there's no way to format `innerHTML`? Is that a bug or this is how `Vitest` is supposed to handle it?

**Comment by sheremet-va** [comment]
innerHTML is just a string. You can configure how it is processed with expect.addSnapshotSerializer
