### ISSUE TITLE
Running vitest with @vitejs/plugin-vue fails on a DataCloneError

### ISSUE THREAD

**Issue by mruthh** [vitest-dev/vitest#1491]
### Describe the bug

I'm attempting to migrate from Jest to Vitest.
My unit test files import *.vue files.

When I use this `vitest.config`, I am prompted to install `@vitejs/plugin-vue.`
```
import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    include: ['**/(*.)unit.js'],
    globals: true,
    environment: 'jsdom'
  }
})
```

When I install `@vitejs/plugin-vue` and use this config instead...

```
import { defineConfig } from 'vitest/config'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  test: {
    include: ['**/(*.)unit.js'],
    globals: true,
    environment: 'jsdom',
    plugins: [vue()]
  }
})

```

...`vitest` fails on the following error:

```
Error: Errors occurred while running tests. For more information, see serialized error.
 ❯ Object.runTests node_modules/vitest/dist/chunk-vite-node-externalize.db158bfb.mjs:7088:17
 ❯ processTicksAndRejections node:internal/process/task_queues:96:5
 ❯ async file:/Users/megan/code/vitest-vue-data-error/node_modules/vitest/dist/chunk-vite-node-externalize.db158bfb.mjs:10368:9
 ❯ Vitest.runFiles node_modules/vitest/dist/chunk-vite-node-externalize.db158bfb.mjs:10378:12
 ❯ Vitest.start node_modules/vitest/dist/chunk-vite-node-externalize.db158bfb.mjs:10305:5
 ❯ startVitest node_modules/vitest/dist/chunk-vite-node-externalize.db158bfb.mjs:11073:5
 ❯ CAC.start node_modules/vitest/dist/cli.mjs:666:9

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: {
  "errors": [
    [DataCloneError: handleHotUpdate(ctx) {
      if (!filter(ctx.file)) {
        return;
      }
      return handleHotUpdate(ctx, options);
    } could not be cloned.],
  ],
}
```

As far as I can tell, this is a bug. But if it's actually a configuration issue on my end, could we please provide a more helpful error message?

### Reproduction

https://github.com/mruthh/vitest-vue-data-error

Run `yarn test:unit` or `npm run test:unit`

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 850.94 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 101.0.1
    Safari: 15.5
  npmPackages:
    @vitejs/plugin-vue: ^2.3.3 => 2.3.3 
    vite: ^2.9.9 => 2.9.12 
    vitest: ^0.15.0 => 0.15.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Put plugins inside root level config, not inside test.
