### ISSUE TITLE
Vitest fails when Vite config has "preserveSymlinks: true" when using pnpm

### ISSUE THREAD

**Issue by Yuval-Peled** [vitest-dev/vitest#1493]
### Describe the bug

Hi, we have a monorepo that utilizes pnpm.
Our `vite.config.js` has this configuration: `resolve: { preserveSymlinks: true }` which is needed, otherwise our imports from the monorepo fail.
When trying to migrate to Vitest, we get the following error:
```
FAIL  tests/test.spec.ts [ tests/test.spec.ts ]
Error: [vite-node] Failed to load local-pkg
```
The tests run well if we remove `preserveSymLinks: true` but of course this breaks the rest of the application.

In the minimum reproducible example, the error is a little different:
```
FAIL  src/test/numbers.test.ts [ src/test/numbers.test.ts ]
Error: [vite-node] Failed to load chai
```

My guess: All imports would fail, but the error message happens to show the 1st import that fails.

### Reproduction

https://github.com/Yuval-Peled/vite-symlinks-mre

After cloning:
```
cd vite;
npx pnpm i;
vitest;
```

### System Info

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
    Memory: 73.92 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Safari: 14.1.2
  npmPackages:
    @vitejs/plugin-react: ^1.3.0 => 1.3.2
    vite: ^2.9.9 => 2.9.12
    vitest: ^0.15.0 => 0.15.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Doesn't seem like this is an issue anymore.
