### ISSUE TITLE
Cannot redefine property: Symbol(expect-global)

### ISSUE THREAD

**Issue by Djaler** [vitest-dev/vitest#1496]
### Describe the bug

```
TypeError: Cannot redefine property: Symbol(expect-global)
 ❯ ../../node_modules/.pnpm/vitest@0.15.0/node_modules/vitest/dist/chunk-runtime-chain.ce7f4b92.mjs:1856:8
    1854| }
    1855| const globalExpect = createExpect();
    1856| Object.defineProperty(globalThis, GLOBAL_EXPECT, {
       |        ^
    1857|   value: globalExpect
    1858| });
```

### Reproduction

https://github.com/Djaler/vue-use-route-query/pull/14

problem appears in 0.15.0

### System Info

```shell
System:                                                    
    OS: Windows 10 10.0.19044                                
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   
    Memory: 6.37 GB / 15.87 GB                               
  Binaries:                                                  
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE         
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD             
  Browsers:                                                  
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.41)
    Internet Explorer: 11.0.19041.1566

P.S. Same thing happens in Github Actions too https://github.com/Djaler/vue-use-route-query/runs/6908663229?check_suite_focus=true
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Interesting why this is executed twice 🤔
