### ISSUE TITLE
`only` flag should work across files

### ISSUE THREAD

**Issue by ianstormtaylor** [vitest-dev/vitest#1497]
### Describe the bug

The `test.only` flag should only show the results from a single test, even if there are multiple files being tested. The way it works currently (where it runs only that test in the file, but also all other tests) makes it not particularly useful, because the output isn't focused...

### Reproduction

None needed, more general.

### System Info

```shell
  System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 7.53 GB / 64.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v16.10.0/bin/npm
  Browsers:
    Brave Browser: 100.1.37.116
    Chrome: 102.0.5005.115
    Firefox: 101.0
    Safari: 15.5
    Safari Technology Preview: 15.4
  npmPackages:
    @vitejs/plugin-react: ^1.3.2 => 1.3.2 
    vite: ^2.9.12 => 2.9.12 
    vitest: ^0.14.2 => 0.14.2 
```
```


### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is not a bug. `only` has a scope of a suite it is defined in.

Also it wouldn't be possible with our architecture. Spec files don't know what happens inside other spec files, they are isolated.

If you want to run only one file, use `vitest <path>` command.

**Comment by Dragomir-Ivanov** [comment]
@sheremet-va Thank you, I was looking exactly for this. Maybe adding these note in the official documentations is worth it.
This is very common use case.

**Comment by sheremet-va** [comment]
> @sheremet-va Thank you, I was looking exactly for this. Maybe adding these note in the official documentations is worth it.
> This is very common use case.

PR welcome! 😄
