### ISSUE TITLE
Line numbers completely wrong in UI test report

### ISSUE THREAD

**Issue by yankeeinlondon** [vitest-dev/vitest#1499]
### Describe the bug

![image](https://user-images.githubusercontent.com/980757/174154390-1251c08c-5e21-437d-9e11-8b607416d206.png)

I'm using the `0.15.1` release of both **vitest** and `@vitest/ui` and for several releases now I've noticed that the console output reports the correct line number but surprisingly the web UI is completely wrong. No idea what could cause this but the enclosed image is the same error.

### Reproduction

clone `@antfu/vite-plugin-md` and then cause a break in any of the tests to see this behavior. I suspect you could get the same results with any TS/VueJS project but that's speculation.

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (28) x64 Intel(R) Xeon(R) W-2170B CPU @ 2.50GHz
    Memory: 7.84 GB / 128.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 102.1.39.122
    Chrome: 102.0.5005.115
    Firefox: 101.0
    Safari: 15.5
  npmPackages:
    @vitejs/plugin-vue: ^2.3.3 => 2.3.3 
    @vitejs/plugin-vue-jsx: ^1.3.10 => 1.3.10 
    vite: ^2.9.12 => 2.9.12 
    vitest: ^0.15.1 => 0.15.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It's working in Node, because we are processing it:

https://github.com/vitest-dev/vitest/blob/b8590f159d42d7a2ac8d66b01efcb9d9fcc8d0b4/packages/vitest/src/utils/source-map.ts#L24

Maybe we need to do it before sending the error to UI.
