### ISSUE TITLE
vi mocked method type definitions are missing ( .calls .lastCall )

### ISSUE THREAD

**Issue by v-dawg** [vitest-dev/vitest#1502]
### Describe the bug

Typescript complains that `.calls` and `.lastCall` are not defined on a mocked object, even though I am using vi.mocked( ). 
In the Stackblitz example you can see that the code works fine, but Typescript is not happy with it.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-vs32pv?file=test/suite.test.ts

Edit: `.lastCall` does not seem to work, but maybe I am doing something wrong

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
These are internal `tinymock` properties, and are not available in types to not case confusion. Use `vi.mocked().mock.calls`.
