### ISSUE TITLE
When `global` is false, failed to import `@testing-library/jest-dom`

### ISSUE THREAD

**Issue by swallowtail62** [vitest-dev/vitest#1504]
### Describe the bug

I'm testing react components with `@testing-library/react`, `@testing-library/jest-dom` and `vitest`.

```ts:vite.config.ts
import react from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [react()],
  test: {
    // globals: true,
    environment: "jsdom",
    setupFiles: "./src/test/setup.ts",
  },
});
```

If global api is enabled, can extend `expect` from jest-dom, but if disabled, the following error occurs and the test fails.

```
ReferenceError: expect is not defined
 ❯ Object.<anonymous> ../node_modules/@testing-library/jest-dom/dist/extend-expect.js:9:1
 ❯ Object.<anonymous> ../node_modules/@testing-library/jest-dom/dist/index.js:3:1
      1| "use strict";
      2| 
      3| require("./extend-expect");
       | ^

```

![image](https://user-images.githubusercontent.com/45661101/174474390-a557c05b-2209-4e7f-bfad-ca2a6e55caaf.png)

Is it possible to use `jest-dom`'s `expect` while disabling the global api?

### Reproduction

https://codesandbox.io/s/gallant-diffie-zf9pus?file=/src/Button.spec.tsx

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 70.52 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.asdf/installs/nodejs/16.13.0/bin/node
    Yarn: 1.22.17 - ~/.asdf/installs/nodejs/16.13.0/.npm/bin/yarn
    npm: 8.1.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 102.0.5005.115
    Safari: 15.5
  npmPackages:
    @vitejs/plugin-react: ^1.3.2 => 1.3.2 
    vitest: ^0.15.1 => 0.15.1 
```
```


### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Yes, it is possible:

```ts
import matchers from '@testing-library/jest-dom/matchers'
import { expect } from 'vitest'

expect.extend(matchers)
```

**Comment by xsjcTony** [comment]
> Yes, it is possible:
> 
> ```ts
> import matchers from '@testing-library/jest-dom/matchers'
> import { expect } from 'vitest'
> 
> expect.extend(matchers)
> ```

Running into the same problem, tried your solution, but still not working. Where should put the code into?

**Comment by sheremet-va** [comment]
> > Yes, it is possible:
> 
> > 
> 
> > ```ts
> 
> > import matchers from '@testing-library/jest-dom/matchers'
> 
> > import { expect } from 'vitest'
> 
> > 
> 
> > expect.extend(matchers)
> 
> > ```
> 
> 
> 
> @sheremet-va Running into the same problem since I don't want to turn globals on, tried your solution, but still not working. Where should put the code into?

In `setupFiles`.
