### ISSUE TITLE
vitest --ui Error : listen EACCES: permission denied 127.0.0.1:51204

### ISSUE THREAD

**Issue by Waxoussou** [vitest-dev/vitest#1513]
### Describe the bug

Working on windows, npx vitest --ui does not work and throw an error on launch :
```bash 
Error: listen EACCES: permission denied 127.0.0.1:51204
    at Server.setupListenHandle [as _listen2] (node:net:1313:21)
    at listenInCluster (node:net:1378:12)
    at doListen (node:net:1516:7)
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  code: 'EACCES',
  errno: -4092,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 51204
}
```

### Reproduction

```
"devDependencies": {
    "@vitest/ui": "^0.14.2",
    "typescript": "^4.5.4",
    "vite": "^2.9.9",
    "vitest": "^0.15.1"
  }
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) ia32 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 2.06 GB / 15.87 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - C:\Program Files (x86)\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.44)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vite: ^2.9.9 => 2.9.12
    vitest: ^0.15.1 => 0.15.1
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I think error is self explanatory, no? Give it permissions 👀

**Comment by Waxoussou** [comment]
I'd love to. But Have not been able to find  how to ... Is there anything to do in vitest config ? I did not find anything about that in the documentation on vitest.

**Comment by Kjir** [comment]
Ensure that nothing else is listening on that port (with Linux I would use something like `netstat -np --tcp --listen | grep :51204`, not sure about Windows).

**Comment by rayfoss** [comment]
Something is cursed ... Check this out, the code is EXACTLY the same as vitest.new , yet it mysteriously breaks at some point. I get 404 not found errors.

https://stackblitz.com/edit/vitest-dev-vitest-qu4fws?file=test%2Fsuite.test.ts

**Comment by Waxoussou** [comment]
> Ensure that nothing else is listening on that port (with Linux I would use something like `netstat -np --tcp --listen | grep :51204`, not sure about Windows).

Thanks for the tips. But unfortunately, I 've been trying that and did not see that port was used by anything else.  
Still seeking from where or why permissions would be constraint for vitest (other tools like vitest -ui that require opening browser and tcp connection are working, like vue ui for example. So i still don't understrand what i'm doing wrong with vitest...)

**Comment by yyi0708** [comment]
Support you, currently I am also running `vitest --ui` on Windows  reporting the same problem

**Comment by rayfoss** [comment]
Looks like my issue was a File IO problem... clearing node_modules may have helped sporadically, or upgrading to Vite 3.

My haunted sandbox is no longer haunted after an SB update, it was frozen, so nothing changed.

Here's what I got before the update:
![Screenshot from 2022-06-28 10-09-23](https://user-images.githubusercontent.com/876076/176215492-43f5ec26-cf55-4135-a21b-1fcd22c623d8.png)

**Comment by dusionlike** [comment]
```
vitest --ui --api 9527
```

**Comment by Waxoussou** [comment]
> 

oooh yeah ! 
it works for me !!! thanks so much @dusionlike
