### ISSUE TITLE
vitest clobbers playwright in a fresh SvelteKit installation.

### ISSUE THREAD

**Issue by kyllerss** [vitest-dev/vitest#1520]
### Describe the bug

Installing `vitest` in a fresh SvelteKit project causes `playwright` tests to fail with a runtime error. The project's [README.md](https://github.com/kyllerss/vitest-playwright-bug/blob/main/README.md) provides the full error report, but a sample of the error message is as follows:

```
[WebServer] [vite-plugin-svelte] /home/my_home/vitest-playwright-bug/.svelte-kit/runtime/components/layout.svelte:15:1 The keyword 'let' is reserved
file: /home/my_home/vitest-playwright-bug/.svelte-kit/runtime/components/layout.svelte:15:1
 13 |  
 14 |  function create_fragment(ctx) {
 15 |    let current;
         ^
 16 |    const default_slot_template = /*#slots*/ ctx[1].default;
 17 |    const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[0], null);
[WebServer] > /home/my_home/vitest-playwright-bug/.svelte-kit/runtime/components/layout.svelte:15:1 The keyword 'let' is reserved
[WebServer] 13: 
14: function create_fragment(ctx) {
15:   let current;
      ^
16:   const default_slot_template = /*#slots*/ ctx[1].default;
17:   const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[0], null);
    at error (file:///home/my_home/vitest-playwright-bug/node_modules/svelte/compiler.mjs:17716:19)
...
```

### Reproduction

I have created a public repo that illustrates the problem:

[https://github.com/kyllerss/vitest-playwright-bug](https://github.com/kyllerss/vitest-playwright-bug)

The commit history is clean to illustrate where things break.

### System Info

```shell
Fresh SvelteKit installation w/ Typescript + Playwright.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Please, follow SvelteKit support here: https://github.com/sveltejs/kit/pull/5094

**Comment by benmccann** [comment]
`@sveltejs/kit/experimental/vite` [has been released](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next353) in `@sveltejs/kit` version `1.0.0-next.353`. Feedback welcome in https://github.com/sveltejs/kit/issues/5184

**Comment by kyllerss** [comment]
The issue has shifted now. I will file a separate bug report as I think the issue now lies elsewhere. Considering this closed.
