### ISSUE TITLE
Jest migration documentation is incomplete

### ISSUE THREAD

**Issue by Kjir** [vitest-dev/vitest#1521]
### Clear and concise description of the problem

I recently moved a project from `jest` to `vitest` and noticed that the documentation is incomplete in regards to the necessary changes. I'm opening this discussion to list all the steps I had to take, which can help keep track of what needs to be added to the migration guide (or be fixed as an inconsistency).

### `beforeEach`/`afterEach`/`beforeAll`/`afterAll` require an empty return value
I had many instances of one of these:
```javascript
afterEach(vi.restoreAllMocks);
beforeEach(() => (someVariable = vi.fn()));
beforeEach(() => setActivePinia(createTestingPinia()));
```
All of these would fail because the function returns a value. I had to modify them as follows:

```typescript
afterEach(() => { vi.restoreAllMocks() });
beforeEach(() => { someVariable = vi.fn() } );
beforeEach(() => { setActivePinia(createTestingPinia()) });
```

### `jest.Mock` has no equivalent in `vitest`

There is no corresponding `vi.Mock<T>` in `vitest`. So I had to change my type definitions as such:

```typescript
// Before
function createMockConnection(): jest.Mock<Connection> {
  // [...]
}


// After
import { MockedObject } from "vitest";

function createMockConnection(): MockedObject<Connection> {
  // [...]
}
```

If the type is a mocked function:

```typescript
// Before
let mockedFn: jest.Mock;

// After
import { SpyInstanceFn } from "vitest";

let mockedFn: SpyInstanceFn;
```

### There is no `legacy` timers in `vitest`

In Jest you have the option to use "legacy" timers instead of the modern ones. `vitest` doesn't support other timers, so the calls to `jest.useFakeTimers("legacy")` had to be updated to `vi.useFakeTimers()`

### `vi.mock("./some/module")` is not equivalent to `jest.mock("./some/module")` and won't automagically mock functions

In my tests I had sometimes a call to `jest.mock("./some/module")` just to prevent side effects from ever happening. For example given the following file:

```typescript
// ./some/module.ts
export let globalObject = {
  someFunction() {
    // ...
  }
}

// in test

jest.mock("./some/module");
import { globalObject } from "./some/module";

globalObject.someFunction.mockReturnValue("Works"); // It's a mock
```

`vi.mock("./some/module")` will not mock the functions and that unexpectedly allows side-effects to happen.

I had to change - where appropriate - to:

```typescript
vi.mock("./some/module", () => {
  return {
    globalObject: {
      someFunction: vi.fn()
    }
  } 
}
```

### `it.each`/`describe.each` does not support a template literal to create the table

The tests that used template literals to define the table of cases with `it.each`/`describe.each` had to be converted to use the array syntax instead.

Before:
```typescript
it.each`
a    | b    | expected
${1} | ${3} | ${4}
${2} | ${2} | ${4}
`("adds $a to $b", ({a, b, expected}) => {
  expect(add(a, b)).toEqual(expected);
}
```

After:
```typescript
it.each([
  [1, 3, 4],
  [2, 2, 4],
])("adds %d to %d", (a, b, expected) => {
  expect(add(a, b)).toEqual(expected);
}
```

### Alternative

Some of these inconsistencies naturally make sense for `vitest` and just need to be documented in the migration guide.

Some others could possibly be considered as a missing feature or bug (e.g.: template literals for `it.each`)

### Additional context

The migration was from jest `27.4.7` to vitest `0.14.2`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Template literals for each are intentionally omitted to avoid complexity.

The fact that a function is not mocked with automocking is a bug, I suggest you create an issue.

Also I don’t know think afterAll/beforeAll accepts value for a return.

Some other points, like types, can be discussed and even implemented, we might just missed it.

**Comment by Kjir** [comment]
> Template literals for each are intentionally omitted to avoid complexity.
then this needs to be documented :+1: 

> The fact that a function is not mocked with automocking is a bug, I suggest you create an issue.

Will do, let me reproduce a case

> Also I don’t know think afterAll/beforeAll accepts value for a return.
It doesn't, but in case of `jest` it will work (ignore it), in the case of `vitest` it will fail

**Comment by sheremet-va** [comment]
> It doesn't, but in case of `jest` it will work (ignore it), in the case of `vitest` it will fail

Only `beforeEach` expects a return value, others will not throw: https://vitest.dev/api/#beforeeach
