### ISSUE TITLE
`vi.mock()` removes functions from classes

### ISSUE THREAD

**Issue by Kjir** [vitest-dev/vitest#1523]
### Describe the bug

When mocking a module with `vi.mock("./some/module")`, some unexpected behaviour happens: classes exported by the module won't have the correct functions when instantiated.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-8vqu9r?file=test/basic.test.ts

The same code (transformed in CommonJS format) works with jest, which is creating an inconsistency when migrating (cfr. #1521 )

### System Info

```shell
System:
    OS: Linux 5.18 Arch Linux
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 5.16 GB / 15.51 GB
    Container: Yes
    Shell: 3.4.1 - /usr/bin/fish
  Binaries:
    Node: 16.15.1 - ~/.nodenv/shims/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.5.5 - ~/.nodenv/shims/npm
  Browsers:
    Brave Browser: 102.1.39.122
  npmPackages:
    vite: ^2.9.9 => 2.9.12
    vitest: latest => 0.15.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nieyuyao** [comment]
We got a new function `fn` by calling the `spyOn` when mocking `class`. But `fn.prototype` is not set to point to `class.prototype`? 🤔

**Comment by sheremet-va** [comment]
> We got a new function `fn` by calling the `spyOn` when mocking `class`. But `fn.prototype` is not set to point to `class.prototype`? 🤔

🤔 

The logic when auto mocking is not quite right. I'm thinking if we maybe should follow jest's approach and collect "metadata" for an object and then recreate it? Right now it just takes all properties (including prototype) and reassigns them, and then also puts original `prototype` on top of it 🤔 Doesn't seem to be reliable.

If someone has time and ideas on how to improve auto mocking, please, open a discussion or PR 😄

**Comment by simon-abbott** [comment]
I put up a PR fixing this! https://github.com/vitest-dev/vitest/pull/1648
