### ISSUE TITLE
Move or deleting a test that uses .only causes a crash in watch mode

### ISSUE THREAD

**Issue by OmgImAlexis** [vitest-dev/vitest#1524]
### Describe the bug

If I have a test file like `src/__test__/report.test.ts` and rename it to `src/__test__/report/report.test.ts` while in watch mode `vitest` crashes with an error similar to this. It's not always the exact same error either.

The same goes for if I delete the test file while it's running.

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: Cannot read properties of undefined (reading 'mode')
 ❯ getStateSymbol node_modules/vitest/dist/chunk-vite-node-externalize.0ec89ad1.mjs:7275:12
 ❯ renderTree node_modules/vitest/dist/chunk-vite-node-externalize.0ec89ad1.mjs:8046:24
 ❯ Object.stop node_modules/vitest/dist/chunk-vite-node-externalize.0ec89ad1.mjs:8109:37
 ❯ DefaultReporter.onTestRemoved node_modules/vitest/dist/chunk-vite-node-externalize.0ec89ad1.mjs:8130:53
 ❯ Vitest.report node_modules/vitest/dist/chunk-vite-node-externalize.0ec89ad1.mjs:10557:5
 ```

### Reproduction

1. Open [this StackBlitz
](https://stackblitz.com/edit/vitest-dev-vitest-dcdm9n?file=test/basic.test.ts) and wait for the ui, etc. to load
2. Drag `basic.test.ts` out of the test directory and then back in
3. Crash

### System Info

```shell
System:
    OS: Windows 10 10.0.25140
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 2.87 GB / 15.92 GB
  Binaries:
    Node: 18.3.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.25140.1000.0), Chromium (102.0.1245.41)
    Internet Explorer: 11.0.25140.1000
  npmPackages:
    vitest: ^0.14.1 => 0.14.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DerYeger** [comment]
I can have a look at this (though only in a few days).

What would be the expected behaviour in such a case?
My first approach would be simply re-collecting the tests.
