### ISSUE TITLE
describe.concurrent: All tests have the same VITEST_WORKER_ID

### ISSUE THREAD

**Issue by flunderpero** [vitest-dev/vitest#1530]
### Describe the bug

My expectation is that `describe.concurrent` would do exactly what Playwright's `describe.parallel` would do (the documentation states that this feature was inspired by Playwright): Run each test in its own isolated environment as if each test would have been in its own spec-file.

That does not seem to be the case. When I use `describe.concurrent` I get the same `VITEST_WORKER_ID` which leads me to suspect that all tests are run in the same process/worker. That does not work for us (and many other use-cases I would guess), because we have external dependencies like databases that need to be set-up. Besides that, I would expect the same level of isolation with `describe.concurrent` that I get with parallel execution of multiple spec-files.

Either way, the documentation should state, what exactly to expect when using `describe.concurrent`.

### Reproduction

`describe.concurrent` should launch each test in an isolated worker.

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 153.94 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 3.1.0 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.10.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 100.0.2
    Safari: 15.5
  npmPackages:
    vitest: 0.15.2 => 0.15.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is correct behaviour. Isolation is provided only for spec **files** and only with `--threads` and `--isolation` (default).

**Comment by sheremet-va** [comment]
Can you point me to the docs, where it says it is inspired by Playwright? I thought it's just for compatibility with Jest.

**Comment by flunderpero** [comment]
@sheremet-va Sorry, I got that mixed up with context/fixtures being inspired by Playwright. I first saw `describe.parallel` in Playwright (and loved it right away). Jest has `test.concurrent` but not `describe.concurrent`, so I thought it would work more like Playwright than Jest.

I already assumed that this might be the intended behaviour, but I would suggest to change it or offer means to configure it. One of the main reasons for me to switch over to vitest was the strict test isolation vitest provides. I had so many problems with Jest in that regard. Some third-party libs would cause memory leaks or otherwise break isolation due to inner state. And having a huge test-suite makes hunting down these problems really hard/impossible.

Using `describe.parallel` in Playwright is nearly a no-brainer, because each test is run in its own context. That together with `test.step` allows for great control over the environment. With `describe.concurrent` in `vitest` I have to be super aware about how I use module scoped variables, or that deps behave correctly etc. That limits the usefulness of this feature and - for me - breaks the way you reason about a spec file.

I understand that you want `vitest` to be similar to Jest, but I hope `vitest` develops beyond that. I migrated a test-suite of ~5000 tests within two days even though I hit some road blocks along the way. That is an amazing achievement on `vitest`'s part! Having `describe.concurrent` behave differently to Jest's `test.concurrent` wrt isolation would only add a minor inconvenience for people coming from Jest. I personally would not sacrifice test isolation a single bit. Sorry for becoming philosophical on this.

Anyway, feel free to close this issue if you strongly disagree. I will weep for a bit then. :-)

**Comment by flunderpero** [comment]
I can see how this is not a simple switch. I think `describe.parallel` would be a good distinction to `describe.concurrent`.

No, you don't state isolation in the docs, but that's what I implied. Maybe it's just me.

Should I open a new issue as a feature request?

**Comment by sheremet-va** [comment]
> Should I open a new issue as a feature request?

Sure! I think this is something we can implement. I will close this issue then.
