### ISSUE TITLE
__dirname and import.meta.url is wrong

### ISSUE THREAD

**Issue by flunderpero** [vitest-dev/vitest#1534]
### Describe the bug

I am using the following `vite.config.ts` (I am using only vitest, not vite):
```
import {configDefaults, defineConfig} from "vitest/config"

export default defineConfig({
    test: {
        exclude: [...configDefaults.exclude, "**/*_e2e*", "**/test.web.wdio/**"],
        setupFiles: ["packages/lib.shared.test/test_setup.ts"],
        threads: false,
        maxThreads: 7,
        minThreads: 1,
        testTimeout: 8000,
        hookTimeout: 10000,
        coverage: false,
    },
})
```

Everything's fine when running the test-suite on my development machine running MacOS. But when I go to our CI server,  a Linux VM, `__dirname` and `import.meta.url` start with the actual project root twice. Say, I add `console.log(__dirname)` to `packages/lib.shared.test/test_setup.ts` (or any spec-file, it does not matter), then on MacOS it will print (correctly)
`/Users/pero/src/packages/lib.shared.test` (the project root and CWD is `~/src`).
On Linux the project is located at `/src`, the CWD is `/src` and the output is `/src/src/packages/lib.shared.test`. The CWD is somehow used twice. I tried to set `root` in `vite.config.ts` to `.` or `./` or even `/src` - it's always the same.

`__dirname` is correct in `vite.config.ts`, btw.

This might have something to do with `vite` rather than `vitest`, but I am new to both and could not find anything related to this problem in either GitHub-repo.

Can anybody give me a hint to what the problem could be? `/src` is mount-point on Linux, if that matters.

### Reproduction

I don't know how to provide a reproducible repo for this specific problem.

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Xeon(R) CPU @ 2.20GHz
    Memory: 14.53 GB / 15.63 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.2 - /usr/bin/node
    Yarn: 3.1.0 - /usr/bin/yarn
    npm: 8.5.0 - /usr/bin/npm
  npmPackages:
    vitest: 0.15.2 => 0.15.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Please, can you try `v0.16.0`?
