### ISSUE TITLE
`test` field gives a TS error in Vite 3 

### ISSUE THREAD

**Issue by arpi17** [vitest-dev/vitest#1537]
### Describe the bug

When using with TypeScript upgrading to Vite 3 beta suddenly gives a TypeError for the `test` field in the `vite.config.ts` file. Namely that `Argument of type '{ test: {}; }' is not assignable to parameter of type 'UserConfigExport'.` The vitest types are referenced with the triple slash command and it all work using Vite 2.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-9wpbx8?file=vite.config.ts

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1
    Memory: 94.69 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Brave Browser: 102.1.39.122
    Firefox: 101.0.1
    Safari: 15.4
  npmPackages:
    @vitejs/plugin-vue: ^2.3.3 => 2.3.3 
    vite: 3.0.0-beta.1 => 3.0.0-beta.1 
    vitest: ^0.14.2 => 0.14.2
```
```


### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vite 3 is not supported at the moment. We have Vite 2 pinned in package.json.

**Comment by straach** [comment]
Same problem seems to apply to vite 2.9.3
```
  System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 106.50 MB / 16.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.4.0/bin/yarn
    npm: 8.12.1 - ~/.nvm/versions/node/v18.4.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 101.0.1
    Safari: 15.5
  npmPackages:
    @vitejs/plugin-react: 1.3.2 => 1.3.2 
    vite: 2.9.13 => 2.9.13 
    vitest: 0.16.0 => 0.16.0 
```

Error:
> error TS2345: Argument of type '{ plugins: (Plugin | PluginOption[])[]; define: { ...; }; build: { sourcemap: true; }; server: { proxy: { 'https://localhost:3000': string; }; https: { ...; }; }; test: { ...; }; }' is not assignable to parameter of type 'UserConfigExport'.
  Object literal may only specify known properties, and 'test' does not exist in type 'UserConfigExport'.

**Comment by sheremet-va** [comment]
It is expected. Vitest requires 2.9.10. You are installing two versions of Vite, but Vitest augments it’s own Vite.

**Comment by sheremet-va** [comment]
Vite 3 is now supported.

**Comment by michealroberts** [comment]
I'm still seeing this issue with vitest v.0.19.1 and vite v.3.0.0 ...

**Comment by sheremet-va** [comment]
> I'm still seeing this issue with vitest v.0.19.1 and vite v.3.0.0 ...

Latest Vitest version is 0.21.1
