### ISSUE TITLE
run  vitest ui Error 

### ISSUE THREAD

**Issue by zxxvGW** [vitest-dev/vitest#1548]
### Describe the bug

When running the vitest --ui command, open the http://localhost:51205  the browser and throw an error 
**Uncaught SyntaxError: The requested module '/node_modules/react/index.js' does not provide an export named 'default' (at useCounter .ts:1:1)**

### Reproduction

this project examples

https://github.com/vitest-dev/vitest/tree/main/examples/react-testing-lib

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz   
    Memory: 2.32 GB / 7.87 GB
  Binaries:
    Node: 16.14.0 - D:\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - D:\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.44)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-react: ^1.3.2 => 1.3.2 
    vite: ^2.9.9 => 2.9.12 
    vitest: latest => 0.16.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Why would you open `http://localhost:51205/`? Vitest UI is located at http://localhost:51205/__vitest__

Our example is working fine: https://stackblitz.com/edit/vitest-dev-vitest-2vanl8?initialPath=__vitest__

**Comment by sheremet-va** [comment]
I guess we need to fix the path:

<img width="421" alt="Screenshot 2022-06-25 at 18 38 11" src="https://user-images.githubusercontent.com/16173870/175780616-14d32f91-8865-4f99-a44a-ecaec8856c58.png">

Do you mean that?

**Comment by zxxvGW** [comment]
yes  i just click here。Thank you for your answer @sheremet-va

**Comment by ottergeorge** [comment]
The Stackblitz example is throwing errors

**Comment by khaiquangnguyen** [comment]
Any progress on this? I just encountered this issue again. the stackblitz example is throwing the same error
