### ISSUE TITLE
jsxFactory support

### ISSUE THREAD

**Issue by Maxim-Mazurok** [vitest-dev/vitest#1560]
### Describe the bug

Vitest seems to ignore jsxFactory field in tsconfig.json

### Reproduction

`vitest` branch: https://github.com/Maxim-Mazurok/vue-2-tsx-example/tree/vitest

run `yarn && yarn test` and observe `ReferenceError: VueTsxSupport is not defined`

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 28.98 GB / 31.32 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.2.0 - ~/.nvm/versions/node/v18.2.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.2.0/bin/yarn
    npm: 8.9.0 - ~/.nvm/versions/node/v18.2.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
  npmPackages:
    vitest: ^0.16.0 => 0.16.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is Vite limitation: https://vitejs.dev/guide/features.html#jsx

**Comment by sheremet-va** [comment]
You might also need to configure this: https://vitest.dev/config/#transformmode

**Comment by Maxim-Mazurok** [comment]
Turns out all I had to do was to use `jsx: true` option of `vite-plugin-vue2`:

```ts
import { defineConfig } from "vite";
import { createVuePlugin as Vue2 } from "vite-plugin-vue2";

export default defineConfig({
  plugins: [Vue2({ jsx: true })],
  test: {
    environment: "jsdom",
    setupFiles: ["./test/setup.ts"],
    deps: {
      inline: ["vuetify"],
    },
    clearMocks: true,
  },
});
```
