### ISSUE TITLE
Dependency resolution difference between vitest and vite

### ISSUE THREAD

**Issue by dennisMeeQ** [vitest-dev/vitest#1562]
### Describe the bug

When using Material UI, we have the option to [exchange the css-in-js solution from emotion to styled-components](https://mui.com/material-ui/guides/styled-engine/#how-to-switch-to-styled-components) by basically aliasing the styled-components wrapper onto the emotion wrapper.

This works perfectly fine in vite (see step 2 in the stackblitz repro below) but when using the same setup with vitest (see step 3) it crashes because it cannot resolve the peer-dependency to `@emotion/styled`. This peer-dependency is technically not needed because `styled-components` and `@mui/styled-engine-sc` serve as replacements but vitest is unhappy about it.

I can work around this issue by installing `@emotion/styled` as dev dependency but that is probably not an ideal solution.

### Reproduction

1. https://stackblitz.com/edit/vitejs-vite-pxpnnv
2. Run `npm start` => the app starts and the styled-components CSS works
3. Run `npm run test` => the test crashes with a dependency resolution problem:

```
 FAIL  src/Foo/foo.test.tsx [ src/Foo/foo.test.tsx ]
Error: Cannot find module '@emotion/styled'
Require stack:
- /home/projects/vitejs-vite-pxpnnv/node_modules/@mui/styled-engine/node/index.js
- /home/projects/vitejs-vite-pxpnnv/node_modules/@mui/system/index.js
- /home/projects/vitejs-vite-pxpnnv/node_modules/@mui/material/node/styles/adaptV4Theme.js
- /home/projects/vitejs-vite-pxpnnv/node_modules/@mui/material/node/styles/index.js
- /home/projects/vitejs-vite-pxpnnv/node_modules/@mui/x-date-pickers/node/CalendarPicker/CalendarPicker.js
- /home/projects/vitejs-vite-pxpnnv/node_modules/@mui/x-date-pickers/node/CalendarPicker/index.js
```

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.31 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 99.0
    Safari: 15.5
  npmPackages:
    vite: ^2.9.9 => 2.9.13 
    vitest: latest => 0.16.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You will need to install it, or use `deps.inline` for problematic dependencies: https://vitest.dev/config/#deps

You should expect some level of differences, because Vite runs your code in browser, but Vitest runs your code in Node. Stack you see tells me that Native Node resolution kicks in. If you don't want this behaviour, use `test.deps.inline` or `ssr.noExternal`.

**Comment by dennisMeeQ** [comment]
Thanks

**Comment by matheusmb** [comment]
Hi @dennisMeeQ , could share your solution? I tried to add `@emotion/styed` to test.deps.inline but it is not working.

```typescript
export default defineConfig({
  plugins: [react(), tsconfigPaths()],
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: './test/vitest.setup.ts',
    deps: {
      inline: [
        '@emotion/styled'
      ],
    },
  },
});
```

**Comment by dennisMeeQ** [comment]
Hmm, quite some time ago. But iirc the solution in the end was to simply live with the workaround described in my original description: Install `@emotion/styled` as dev dependency

**Comment by sheremet-va** [comment]
> I'd really prefer to not include another styled library into the app as a workaround. With all this, any other suggestions?

Try enabling deps.experimentalOptimizer.

**Comment by sheremet-va** [comment]
> Is there perhaps some combination of things I can enable that you might know of?

I think the best way is to follow Vite's recommendation about SSR aliases (which is what is being used here, unless [`experimentalOptimizer`](https://vitest.dev/config/#deps-experimentaloptimizer) is enabled): https://vitejs.dev/config/shared-options.html#resolve-alias

**Comment by grahamhency** [comment]
@sheremet-va ahh. I did not put it together that this was SSR. I'll look into that, but styled-components seems to not work with SSR per MUI's docs: https://mui.com/material-ui/guides/styled-engine/#how-to-switch-to-styled-components

Also the node_module aliases suggested in the https://vitejs.dev/guide/ssr.html#ssr-externals won't apply here as we're using npm.

I'll tinker some more and if I can't find another solution, seems like we'll just have to install `@emotion/styled` as a devDependency and call it a day for now.

Thank you for your assistance!
