### ISSUE TITLE
Allow JSX in .js files

### ISSUE THREAD

**Issue by RobinVdBroeck** [vitest-dev/vitest#1564]
### Clear and concise description of the problem

I want to use JSX in .js files, but that currently gives following issue:
```
FAIL  src/.../<retracted>.test.jsx [ src/.../<retracted>.test.jsx ]
Error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
 ❯ formatError node_modules/vite/dist/node/chunks/dep-8f5c9290.js:39055:46
 ❯ TransformContext.error node_modules/vite/dist/node/chunks/dep-8f5c9290.js:39051:19
 ❯ TransformContext.transform node_modules/vite/dist/node/chunks/dep-8f5c9290.js:58269:22
 ❯ Object.transform node_modules/vite/dist/node/chunks/dep-8f5c9290.js:39292:30
 ❯ doTransform node_modules/vite/dist/node/chunks/dep-8f5c9290.js:50012:29
```

This file imports normal .js files which include jsx.

Chaning all the .js files to .jsx fixes the problem, but might not be ideal in every situation.

### Suggested solution

Allow to threat js files as jsx.
This is allready posible in vite (https://github.com/vitejs/vite/discussions/3448)

### Alternative

Force all users to use .jsx for files containing jsx

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
You can still use workaround from https://github.com/vitejs/vite/discussions/3448 in Vitest

This is intentional limitation of Vite, and we stand by it.

**Comment by RobinVdBroeck** [comment]
As far as I can see, and I can be wrong, you can't pass esbuild nor the ooptimizeDeps options from [vite](https://github.com/vitejs/vite/discussions/3448#discussioncomment-747542) to vitest. 
Could you please elobrate on how you would do such a thing.
