### ISSUE TITLE
structuredClone is not defined

### ISSUE THREAD

**Issue by masedri** [vitest-dev/vitest#1568]
### Describe the bug

Similar a Jest issue https://github.com/facebook/jest/pull/12631/files

<img width="1193" alt="Screenshot 2022-06-29 at 09 10 19" src="https://user-images.githubusercontent.com/21109779/176386952-b4446b70-b4b8-4392-a24a-edd680e6c5ea.png">

### Reproduction

Use structureClone

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1
    Memory: 83.06 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 101.0.1
    Safari: 15.4
  npmPackages:
    @vitejs/plugin-vue: ^2.3.3 => 2.3.3 
    vite: ^2.9.9 => 2.9.9 
    vitest: 0.16.0 => 0.16.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Upgrade Node to at least 17.0: https://developer.mozilla.org/en-US/docs/Web/API/structuredClone
