### ISSUE TITLE
Option to run tests in random order

### ISSUE THREAD

**Issue by cexbrayat** [vitest-dev/vitest#1570]
### Clear and concise description of the problem

I may have missed the option in the docs, but it would be great to be able to execute tests in a random order, as Jest or Jasmine allow to.

This is particularly useful to track tests that accidentally depend on another run previously, and that fail when run in isolation.

### Suggested solution

Ideally, having a `random` option that can be set to true to run the tests in random order would be great.
The output could then log the seed used.

Jasmine also allows setting a seed, allowing to run the test in a specific order (for example when a seed failed locally or on CI). So another `seed` option that could be set to a specific number would be great

### Additional context

See Jasmine options: https://jasmine.github.io/setup/nodejs.html

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
We can provide a `sequelizer` option, maybe? And `RandomSequelizer` in `vitest/node`.

**Comment by sheremet-va** [comment]
> `sequelizer` feels maybe a bit harder to understand compared to the `random` and `seed` options from jasmine?
 
I think this is how jest does it? `sequelizer` allows you to define your own function for sorting tests. We can technically implement it, and give a shortcuts with `random` and `seed` options.
