### ISSUE TITLE
Support React JSX automatic runtime

### ISSUE THREAD

**Issue by silverwind** [vitest-dev/vitest#1572]
### Clear and concise description of the problem

@vitejs/plugin-react [supports](https://github.com/vitejs/vite/tree/main/packages/plugin-react#vitejsplugin-react-) the automatic JSX runtime, so one can omit the `React` import with vite, but vitest currently does not support this, leading to `React is not defined` errors during tests for code that otherwise builds fine with vite.

[Example repo](https://github.com/silverwind/vitest-react-automatic-runtime) showing the issue:

```
 FAIL  test/basic.test.tsx > Link changes the class when hovered
ReferenceError: React is not defined
 ❯ test/basic.test.tsx:13:4
     11| test('Link changes the class when hovered', () => {
     12|   const component = renderer.create(
     13|     <Link page="http://antfu.me">Anthony Fu</Link>,
       |    ^
     14|   )
     15|   let tree = toJson(component)
```

### Suggested solution

Support automatic runtime during JSX transpilation via either esbuild or babel.

### Alternative

Workaround is to manually import `React` like in the React 16.x days, but this may lead to increased bundle size as it inhibits tree-shaking for bundlers.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
You are linking `plugin-react`, but you don't use it in your reproduction. Why?

**Comment by sheremet-va** [comment]
Installing plugin solves your problem:

```ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: "happy-dom",
  },
});
```

Please, remember that `vitest.config` _overrides_ `vitest.config`: https://vitest.dev/config/

**Comment by silverwind** [comment]
Indeed, that was the issue. I had the plugin present in `vite.config.plugins` and did not define `vitest.config.plugins`, assuming it was using vite's plugins as JSX already worked on a basic level.
