### ISSUE TITLE
jest-preview for vitest

### ISSUE THREAD

**Issue by gkiely** [vitest-dev/vitest#1578]
### Clear and concise description of the problem

Testing react components with react-testing-library can be difficult when looking at a html output in the terminal.

### Suggested solution

Build jest-preview functionality for vitest to allow rendering components in the browser when testing.

Example:
https://www.jest-preview.com/docs/getting-started/intro

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
`jest-preview` should work with Vitest, no?

We also already have this PR open, that should cover this, I guess: 
- https://github.com/vitest-dev/vitest/pull/1302

**Comment by gkiely** [comment]
Oh cool! Closing this, thanks.

**Comment by nvh95** [comment]
@gkiely I just launched `vitest-preview` yesterday, fist-class support for Vitest, built on top of Vite, blazing fast. If you still write Vitest tests, you can take a look at:
- GitHub: https://github.com/nvh95/vitest-preview
- Installation guide: https://www.vitest-preview.com/guide/getting-started

Thanks.

**Comment by gkiely** [comment]
@nvh95 I will check this out today, nice work.
