### ISSUE TITLE
vittest fails for webworkers

### ISSUE THREAD

**Issue by jantimon** [vitest-dev/vitest#1584]
### Describe the bug

@vitest/web-worker does not allow to test web-workers

The test fails immediately with the following error:

```
Error: `new URL(url, import.meta.url)` is not supported in SSR.
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-wn53bu?file=vite.config.ts

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) x64 Apple M1 Max
    Memory: 3.91 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvs/default/bin/node
    Yarn: 1.22.17 - ~/.nvs/default/bin/yarn
    npm: 8.1.3 - ~/.nvs/default/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 103.1.40.107
    Chrome: 103.0.5060.53
    Chrome Canary: 105.0.5146.0
    Edge: 103.0.1264.44
    Firefox: 99.0
    Firefox Developer Edition: 102.0
    Safari: 15.5
    Safari Technology Preview: 15.4
  npmPackages:
    vitest: ^0.17.0 => 0.17.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is Vite compilation error. Please, make an issue in [Vite](https://github.com/vitejs/vite) repo.

In the meantime, you can rewrite it as:

```ts
const baseUrl = import.meta.url
new URL(url, baseUrl)
```

**Comment by sheremet-va** [comment]
Although I think it's already fixed: https://github.com/vitejs/vite/pull/8846

You might need to update Vite, or ask Vite team to back port it to Vite 2.
