### ISSUE TITLE
Use alias to import files/components in tests

### ISSUE THREAD

**Issue by ady642** [vitest-dev/vitest#1585]
### Clear and concise description of the problem

It will be nice to configure vitest to have the possibility to import files with alias:

### Suggested solution

Instead of this:
```
import Plan from '../../../../modules/Pricing/models/Plan'
```

Have the possibility to use the alias:
```
import Plan from '@/modules/Pricing/models/Plan'
```

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Use resolve.alias: https://vitejs.dev/config/#resolve-alias
