### ISSUE TITLE
Vite's config setting `resolve.conditions` isn't respected when recursing through dependencies.

### ISSUE THREAD

**Issue by thislooksfun** [vitest-dev/vitest#1588]
### Describe the bug

When `vitest` is recursing through the dependencies in `node_modules` it loses track of the [`resolve.conditions`](https://vitejs.dev/config/#resolve-conditions) setting, meaning that nested imports with conditional exports resolve to the wrong file.

### Reproduction

https://github.com/thislooksfun/vitest-mre

### System Info

```shell
Not relevant to the bug.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by thislooksfun** [comment]
Vitest also doesn't respect Vite's default `resolve.conditions` — if you load the linked MRE and comment out the `resolve.conditions` in the `vite.config.js` file then _both_ tests will fail — but that might be better reported as a separate issue.

**Comment by sheremet-va** [comment]
Use test.deps.inline for node_modules, if you need to apply Vite transforms to it.

**Comment by sheremet-va** [comment]
> but that might be better reported as a separate issue.

This is nog a bug, Vitest processes files with SSR flag, which mean `browser` condition is not respected. This is intentional - a lot of dependencies will just not work with `browser` field in Node.

**Comment by thislooksfun** [comment]
Ok, that's a decent reason to have different defaults, but it's not actually a response to this bug. If you look at the MRE I made, the "shallow" import DOES respect `resolve.conditions`, while the "deep" import DOES NOT. Either way this is unintended behavior, and is not surfaced to the user in understandable ways. Either way you cut it this is unintended behavior that causes really confusing behavior like https://github.com/solidjs/solid-testing-library/issues/10. Either fully respect `resolve.conditions` or don't respect it _at all_.

**Comment by sheremet-va** [comment]
We respect `resolve.condition` for all processed files. `node_modules` files are not processed by default, and their execution is delegated to Node for performance reasons. If you need to process them, use `test.deps.inline`, as I already said.

If there is a way to provide condition to Node directly, we could add it.
