### ISSUE TITLE
Cannot use ESM inside `node:vm` when running tests

### ISSUE THREAD

**Issue by XiNiHa** [vitest-dev/vitest#1590]
### Describe the bug

It's currently impossible to use ESM inside `node:vm` when running tests.
It happens because ESM support inside `node:vm` is currently behind a feature flag (`--experimental-vm-modules`) and Vitest doesn't provide any ways to pass feature flags to Node.
This is especially critical when using packages like `miniflare`, which utilizes `node:vm` to simulate the Cloudflare Workers environment.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-ferg4y?file=test/basic.test.ts

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    vite: ^2.9.9 => 2.9.13 
    vitest: latest => 0.17.0

(ran on StackBlitz)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> Vitest doesn't provide any ways to pass feature flags to Node

But what about `NODE_OPTIONS='--experimental-vm-modules' vitest`?

**Comment by XiNiHa** [comment]
Well that worked. Wasn't aware of that option, thanks!
Should this issue be closed, then?
