### ISSUE TITLE
Rerun all tests when package.json changes

### ISSUE THREAD

**Issue by elliotwestlake** [vitest-dev/vitest#1592]
### Clear and concise description of the problem

Currently if `package.json` changes and you're running tests with the `--changed` flag you will get no tests running.

<img width="573" alt="image" src="https://user-images.githubusercontent.com/17042376/177113000-92c9a2f1-b570-43f1-a027-a8250fbdce00.png">

### Suggested solution

Run all tests when `package.json` has changed

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
On what basis should we run all tests?

**Comment by sheremet-va** [comment]
Maybe we should rerun all tests that are specified in `forceRerunTrigger` 🤔, if any file is changed

**Comment by elliotwestlake** [comment]
> On what basis should we run all tests?

It's possible a dependency update could break the tests. 

> Maybe we should rerun all tests that are specified in `forceRerunTrigger` 🤔, if any file is changed

This sounds like a great idea

**Comment by elliotwestlake** [comment]
Happy to try and get a pr up for this if you need?

**Comment by sheremet-va** [comment]
> Happy to try and get a pr up for this if you need?

Sure. Just a heads up, we are filtering files here:

https://github.com/vitest-dev/vitest/blob/3e4f3bef5c8a961ffc6ea0df638dcaf629e1be75/packages/vitest/src/node/core.ts#L175

I think we should first check if any related files are in `forceRerunTrigger`, then if yes, just return full list of files without filtering.
