### ISSUE TITLE
Vitest UI very slow with large modules graph

### ISSUE THREAD

**Issue by MPeloquin** [vitest-dev/vitest#1602]
### Describe the bug

I have an app with a large module graph, and when I run `vitest --ui`, the ui is very unresponsive, even if I don't have the modules tab opened. 

When I uncheck the two checkboxes, then the ui is reponsive again
![CleanShot 2022-07-05 at 16 30 03](https://user-images.githubusercontent.com/755469/177411101-446eaa4a-355f-48b9-92b7-77b04cf03c75.png)

I don't use these modules graphs, it would be nice if having the tab closed would not affect the performance of the UI.

See video:

https://user-images.githubusercontent.com/755469/177412893-79c506cf-1bfb-48c5-9114-a2927c3b00ce.mp4

### Reproduction

https://github.com/MPeloquin/VitestUiSlowModules

Module graph is larger than the one I have on my app, but the issue is the same, UI becomes very slow.

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 413.05 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
  npmPackages:
    @vitejs/plugin-react: ^1.2.0 => 1.3.2 
    vite: ^2.9.9 => 2.9.9 
    vitest: ^0.17.0 => 0.17.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
running the `dev` script in the repo, the browser is failing (circular reference: 200+ modules)

@DerYeger can you take a look at the repro, my laptop with 64GB of RAM cannot load it (there are 200+ modules)

**Comment by MPeloquin** [comment]
@userquin I removed circular references and reduces the number of modules dependencies a bit, let me know. Thanks

**Comment by DerYeger** [comment]
> running the `dev` script in the repo, the browser is failing (circular reference: 200+ modules)
> 
> @DerYeger can you take a look at the repro?, my laptop with 64GB of RAM cannot load it (there are 200+ modules)

Sorry for the late response.

I just tried the repro, and it is definitely very slow, though I can open it.

The graph view is active/alive while other tabs are selected, to prevent the graph from resetting every time the tab is selected.

For module graphs of this size an interactive graph view is probably not the right choice in the first place.
