### ISSUE TITLE
jsdom environment error - localStorage is not available for opaque origins

### ISSUE THREAD

**Issue by rowanwins** [vitest-dev/vitest#1605]
### Describe the bug

I'm having trouble getting a test environment running for an [mapbox-gl](https://github.com/mapbox/mapbox-gl-js) application. I'm using jsdom as my environment and adding as  the `jsdom-worker` plugin but when I try and run my tests I get

````
Error: Failed to fully serialize error: Cannot read properties of undefined (reading 'name')
Inner error message: localStorage is not available for opaque origins
````

Looking through the jsdom repo I found a [similar issue](https://github.com/jsdom/jsdom/issues/2304) where people were able to specify a jest configuration option which enabled things to work, but there doesn't seem to be an equivalent option for vitest.

### Reproduction

Tried setting up a minimal example with stackblitz but couldn't get it properly working, but I'll retry and post an update if I can get it to work.
https://stackblitz.com/edit/vitest-dev-vitest-yembxk?file=test/basic.test.js

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 20.75 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.10 - ~/opt/miniconda3/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Brave Browser: 102.1.39.122
    Firefox: 89.0.1
    Safari: 15.5
  npmPackages:
    @vitejs/plugin-vue: ^2.3.3 => 2.3.3
    vite: ^2.9.9 => 2.9.12
    vitest: ^0.16.0 => 0.16.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You can provide `url` with `environmentOptions.jsdom`

**Comment by rowanwins** [comment]
Thanks for the suggestion @sheremet-va , unfortunately setting it didn't make any difference, looks like it already has a default of `'http://localhost:3000'`
https://github.com/vitest-dev/vitest/blob/5d0dfe9c6d0269c633ccdc7a068f46b79e5f8f45/packages/vitest/src/types/jsdom-options.ts#L24
