### ISSUE TITLE
with node 16 "assert {type: 'json'}" is required but can't be parsed by vitest

### ISSUE THREAD

**Issue by francois-spectre** [vitest-dev/vitest#1610]
### Describe the bug

With node >= 16.14, importing a json file require to add an assertion like
```
import pkg from '../package.json'  assert {type: 'json'}
```
If I don't provide it, I get an error `ERR_IMPORT_ASSERTION_TYPE_MISSING`
If I provide it, it breaks the vitest run with 
```
Error: Parse failure: Unexpected token (18:33)
Contents of line 18: import pkg from '/package.json'  assert {type: 'json'}
```

### Reproduction

- try to import a json file with node > 16.14
- add the json assertion assert {type: 'json'}
- run the tests

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 116.70 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 15.3
  npmPackages:
    vitest: ^0.17.0 => 0.17.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest doesn't parse anything, please follow Vite issue: https://github.com/vitejs/vite/issues/4934

**Comment by francois-spectre** [comment]
ok yes thank you for the link to the vite issue.
But it seems that it is merged in vite but still not working with vitest (I have just tried with the last version 0.17.1)

**Comment by sheremet-va** [comment]
> ok yes thank you for the link to the vite issue.
> But it seems that it is merged in vite but still not working with vitest (I have just tried with the last version 0.17.1)

I don't think Vite released a new version with a fix, it was merged 2 days ago. You would also need Vite 3 for this to work

**Comment by francois-spectre** [comment]
oh yes so I tried with `3.0.0-beta.7` and it is working! thank you!

**Comment by terwer** [comment]
Still not work 

```
Contents of line 125:     const { default: data } = await import(fullJsonPath, { assert: { type: "json" } });
```

Vitest latest version

```
"vitest": "^0.30.1"
```

**Comment by terwer** [comment]
Full stack

```

Error: Parse failure: Unexpected token (195:18)
At file: /src/lib/siyuanDevice.ts
Contents of line 195:       fullJsonPath,
    at ssrTransformScript (file:///Users/terwer/Documents/mydocs/zhi/node_modules/.pnpm/registry.npmjs.org+vite@4.2.2_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-d305c21f.js:53410:15)
    at ssrTransform (file:///Users/terwer/Documents/mydocs/zhi/node_modules/.pnpm/registry.npmjs.org+vite@4.2.2_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-d305c21f.js:53385:12)
    at Object.ssrTransform (file:///Users/terwer/Documents/mydocs/zhi/node_modules/.pnpm/registry.npmjs.org+vite@4.2.2_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-d305c21f.js:62785:20)
    at loadAndTransform (file:///Users/terwer/Documents/mydocs/zhi/node_modules/.pnpm/registry.npmjs.org+vite@4.2.2_@types+node@18.15.11/node_modules/vite/dist/node/chunks/dep-d305c21f.js:41231:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```
