### ISSUE TITLE
"Unexpected end of JSON input"

### ISSUE THREAD

**Issue by v-dawg** [vitest-dev/vitest#1611]
### Describe the bug

Whenever I want to run the test of my `main` directory (the project is builded on [vite-electron-builder](https://github.com/cawa-93/vite-electron-builder)), the test just instantly shuts down without giving an error message.
However, the tests of my `renderer` directory run just fine. 
And on my laptop which runs macOs it also works. 
Going back in the git history, removing `node_modules` and reinstalling and restarting my PC does not help.

I put in debugger keyword in vite.config.js and went through the execution:.
And I get this error in `chunk-vite-node-externalize.1efbe319.mjs`: 
```
message: "Unexpected end of JSON input",
stack: "SyntaxError: Unexpected end of JSON input\n    at JSON.parse (<anonymous>)\n    at ResultsCache.readFromCache (file:///F:/sing/node_modules/vitest/dist/chunk-vite-node-externalize.1efbe319.mjs:8733:51)\n    at async Vitest.setServer (file:///F:/sing/node_modules/vitest/dist/chunk-vite-node-externalize.1efbe319.mjs:10313:5)\n    at async Object.configureServer (file:///F:/sing/node_modules/vitest/dist/chunk-vite-node-externalize.1efbe319.mjs:10952:11)\n    at async createServer (F:\\sing\\node_modules\\vite\\dist\\node\\chunks\\dep-80fe9c6b.js:60247:28)\n    at async createVitest (file:///F:/sing/node_modules/vitest/dist/chunk-vite-node-externalize.1efbe319.mjs:10983:18)\n    at async startVitest (file:///F:/sing/node_modules/vitest/dist/chunk-vite-node-externalize.1efbe319.mjs:11070:15)\n    at async CAC.start (file:///F:/sing/node_modules/vitest/dist/cli.mjs:666:9)"
```

Are there some caches which could be cause of this?

```
async function VitestPlugin(options = {}, ctx = new Vitest()) {
  let haveStarted = false;
  // ... 
      async configureServer(server) {
        if (haveStarted)
          await ctx.report("onServerRestart");
        try {
          await ctx.setServer(options, server);
          haveStarted = true;
          if (options.api && options.watch)
            (await import('./chunk-api-setup.5282c6cb.mjs')).setup(ctx);
        } catch (err) {
          ctx.printError(err, true); 
          /* err: {
            message: "Unexpected end of JSON input",
           stack: "SyntaxError: Unexpected end of JSON input\n    at JSON.parse (<anonymous>)\n    at ResultsCache.readFromCache (file:///F:/sing/node_modules/vitest/dist/chunk-vite-node-externalize.1efbe319.mjs:8733:51)\n    at async Vitest.setServer (file:///F:/sing/node_modules/vitest/dist/chunk-vite-node-externalize.1efbe319.mjs:10313:5)\n    at async Object.configureServer (file:///F:/sing/node_modules/vitest/dist/chunk-vite-node-externalize.1efbe319.mjs:10952:11)\n    at async createServer (F:\\sing\\node_modules\\vite\\dist\\node\\chunks\\dep-80fe9c6b.js:60247:28)\n    at async createVitest (file:///F:/sing/node_modules/vitest/dist/chunk-vite-node-externalize.1efbe319.mjs:10983:18)\n    at async startVitest (file:///F:/sing/node_modules/vitest/dist/chunk-vite-node-externalize.1efbe319.mjs:11070:15)\n    at async CAC.start (file:///F:/sing/node_modules/vitest/dist/cli.mjs:666:9)"
         }

      */
          process.exit(1);
        }
        if (!options.watch)
          await server.watcher.close();
      }
    },
    //...
```

### Reproduction

Not possible

### System Info

```shell
I work with electron, but the code is testing node.

 System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 20.93 GB / 31.91 GB
  Binaries:
    Node: 17.4.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (95.0.1020.30)
  npmPackages:
    vite: ^2.9.13 => 2.9.13
    vitest: ^0.17.0 => 0.17.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Yes, we have a cache in `node_modules/.vitest`. You can disable cache with `test.cache: false` for now. Please, create a reproduction with your broken JSON.

**Comment by v-dawg** [comment]
There were two `node_modules` folders in `renderer` and `main` and each of them had a `results.json`. 
The one in `main` (the one that did not work) was empty. Deleting it fixed it. 
I am not sure why the folders where there in the first place and I suspect that they were created by the vitest plugin, which does not work for my folder structure, but I wanted to test if it can give me error messages for my problem.
So the error might have existed before the `results.json` and it vanished just as suddenly as it came.
Also I am sorry, I know this really is not all to helpful ^^

**Comment by jorroll** [comment]
I started running into this same error which prevented my tests from running. Strangely, I only encounter the error if I use `yarn vitest run`. If I use `yarn vitest` (i.e. watch mode) then all the same tests run but there is no error. I don't have a reproduction either. I'm running vitest `0.16.0` and there doesn't appear to be a `test.cache` option and there is no `node_modules/.vitest` folder either. If I end up digging into this I'll post more information. For the time being I might just disable the tests locally though. They still seem to run fine on CI.

**Comment by vittau** [comment]
I'm having this issue running some tests using the VSCode [Vitest](https://marketplace.visualstudio.com/items?itemName=ZixuanChen.vitest-explorer) extension. Including `test.cache: false` on the config file doesn't seem to help. Apparently the JSON file doesn't even exist. Any solution or workaround to this issue?

**Comment by jorroll** [comment]
@vittau unfortunately, I don't think I ever figured out the cause and the problem just went away at some point. You could try seeing if you are running the latest version of vitest. FWIW I'm still running vite `2.x`.

**Comment by Kapcash** [comment]
I confirm that the issue is caused by the [vitest](https://marketplace.visualstudio.com/items?itemName=ZixuanChen.vitest-explorer) VSCode extension. When the extension is running and you run `yarn vitest` at the same time, the error might occur.
The funny part is the json I have in `node_modules/.vitest/results.json` is valid. Maybe a conflict when both process (cli + extension) update the file?

**Comment by maxstue** [comment]
@Kapcash Did you find any solution? because i am having the same problem at the moment
