### ISSUE TITLE
Empty test causes writableLength undefined error

### ISSUE THREAD

**Issue by natew** [vitest-dev/vitest#1615]
### Describe the bug

I get this even with nothing but an empty `test('', () => {})` in my test file:

```
text|nate/dev⚡ ⇒ yarn test
$ test
$ vitest --config ../vite-plugin-internal/vite.config.ts

 DEV  v0.17.1 /Users/n8/tamagui/packages/text

 ✓ src/wrapChildrenInText.test.tsx (2)

Test Files  1 passed (1)
     Tests  2 passed (2)
      Time  803ms (in thread 1ms, 80323.73%)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run. This might cause false positive tests.
Please, resolve all the errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Errors occurred while running tests. For more information, see serialized error.
 ❯ Object.runTests ../../node_modules/vitest/dist/chunk-vite-node-externalize.0fc8ed68.mjs:7046:17
 ❯ processTicksAndRejections node:internal/process/task_queues:96:5
 ❯ async file:/Users/n8/tamagui/node_modules/vitest/dist/chunk-vite-node-externalize.0fc8ed68.mjs:10428:9
 ❯ Vitest.runFiles ../../node_modules/vitest/dist/chunk-vite-node-externalize.0fc8ed68.mjs:10441:12
 ❯ Vitest.start ../../node_modules/vitest/dist/chunk-vite-node-externalize.0fc8ed68.mjs:10362:5
 ❯ startVitest ../../node_modules/vitest/dist/chunk-vite-node-externalize.0fc8ed68.mjs:11110:5
 ❯ CAC.start ../../node_modules/vitest/dist/cli.mjs:666:9

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: {
  "errors": [
    [TypeError: Cannot read properties of undefined (reading 'writableLength')],
  ],
}
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
```

### Reproduction

```
git clone git@github.com:tamagui/tamagui.git
cd tamagui
./script/ci-prepare.sh
yarn
cd packages/text
yarn test
```

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 81.06 MB / 16.00 GB
    Shell: 5.8 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 16.14.0 - ~/Library/Caches/fnm_multishells/69747_1653603955297/bin/node
    Yarn: 3.2.1 - ~/Library/Caches/fnm_multishells/69747_1653603955297/bin/yarn
    npm: 8.3.1 - ~/Library/Caches/fnm_multishells/69747_1653603955297/bin/npm
    Watchman: 2022.06.27.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 103.1.40.113
    Chrome: 102.0.5005.61
    Firefox: 100.0.2
    Safari: 15.5
    Safari Technology Preview: 16.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by natew** [comment]
Can confirm this is something to do with the CLI output, using `--reporter json` doesn't produce the error.

**Comment by laurentpayot** [comment]
By the way skipping my test was not enough to prevent the suite from failing. I had to comment a `vi.mock()` (internally calling a `vi.importActual()`) for the skipping to work. Hope it helps.

**Comment by laurentpayot** [comment]
UPDATE: Replacing
```js
vi.fn().mockReturnValue(Promise.reject(new Error("TEST_ERROR")))
```
by
```js
vi.fn().mockRejectedValue(new Error("TEST_ERROR"))
```
fixed the issue _for me_. Weird.

**Comment by sheremet-va** [comment]
> The test itself passes but it looks like there is a bug in the default reporter that makes the test suite fail:

Vitest doesn't throw the error: `TEST_WRITEBATCH_ERROR`, you have some package that does it.

json reporter works, because it gives you errors inside a json 😄

**Comment by laurentpayot** [comment]
> Vitest doesn't throw the error: `TEST_WRITEBATCH_ERROR`, you have some package that does it.

@sheremet-va my bad, I should have mentionned that `TEST_WRITEBATCH_ERROR` actually is a part of the mock I wrote (like in the example below for  `TEST_SETDOC_ERROR`):

```typescript
vi.mock('@firebase/firestore', async () => {
    const firestore: typeof import('@firebase/firestore') =
        await vi.importActual('@firebase/firestore')
    return {
        ...firestore,
        setDoc: vi.fn().mockRejectedValue(new Error("TEST_SETDOC_ERROR"))
    }
})
```
I’m testing the behavior of some functions when `firestore.setDoc()` they internally use returns whatever error. So the `TEST_XXXXXXX_ERROR` triggering is actually the normal behavior of the test :wink: 

Once more, using the json reporter leads to a correct suite behavior. There must be a weird bug in the default reporter :thinking:

**Comment by laurentpayot** [comment]
Note that my example above does not produce the bug. It was when I was (incorrectly?) using the following:
```js
vi.fn().mockReturnValue(Promise.reject(new Error("TEST_SETDOC_ERROR")))
```

**Comment by sheremet-va** [comment]
Still, I am not able to reproduce the error with reproduction steps that were provided.
