### ISSUE TITLE
`config.sequence.sequencer`: Type declaration conflicts

### ISSUE THREAD

**Issue by AriPerkkio** [vitest-dev/vitest#1619]
### Describe the bug

When creating custom `sequencer` by extending the `BaseSequencer` there are some type errors. I think the root cause is similar as https://github.com/vitest-dev/vitest/issues/991. 

```ts
import { defineConfig } from 'vitest/config';
import { BaseSequencer, Vitest } from 'vitest/node';

export default defineConfig({
    test: {
        sequence: {
            sequencer: class Seqencer extends BaseSequencer {
                protected ctx: Vitest;

                constructor(ctx: Vitest) {
                    super(ctx);
                    this.ctx = ctx;
                }

                async shard(files: string[]) {
                    return files;
                }

                async sort(files: string[]) {
                    return files;
                }
            },
        },
    },
});

// Type 'typeof Seqencer' is not assignable to type 'TestSequencerContructor'.
//  Types of parameters 'ctx' and 'ctx' are incompatible.
//   Type 'import("/workspaces/vitest-sonar-reporter/node_modules/vitest/dist/index").Vitest' is not assignable to type 'import("/workspaces/vitest-sonar-reporter/node_modules/vitest/dist/node").Vitest'.
```

https://vitest.dev/config/#sequence-sequencer 

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-wr6xms?file=vite.config.ts&initialPath=__vitest__

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 5.27 GB / 7.77 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.2 - /usr/bin/node
    Yarn: 1.22.15 - /opt/yarn/stable/bin/yarn
    npm: 8.5.0 - /usr/bin/npm
  npmPackages:
    vite: ^2.9.14 => 2.9.14 
    vitest: ^0.17.1 => 0.17.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Our `vitest/config` and `vitest` files use different type files. I wonder if it's possible with rollup to generate shared types file?
