### ISSUE TITLE
Use trace to locate the position of tests and suites

### ISSUE THREAD

**Issue by antfu** [vitest-dev/vitest#162]

**Comment by yesmeck** [comment]
Is it possible to run tests with a specified line number? For instance, the following command runs a test at line 20.

```javascript
$ vitest --run test/basic.test.ts:20
```

**Comment by sheremet-va** [comment]
Supported in 1.4.0: https://vitest.dev/config/#includeTaskLocation

**Comment by sheremet-va** [comment]
Closed in favour of #5445
