### ISSUE TITLE
Degradation v0.18.0: Terminal no longer reloads on save

### ISSUE THREAD

**Issue by gkiely** [vitest-dev/vitest#1621]
### Describe the bug

0.17.1: reloads the terminal on save, this is helpful for developer feedback.
0.18.0: doesn't reload the terminal, shows a blue indicator

The original 0.17.1 version had this right, it's a much better dev experience seeing the full reload. The new version is much harder to discern if the test updated.

In the case that the maintainers decide v0.18.0 is the ideal experience, a fallback proposal would be to allow an option to reload on save.

### Reproduction

[Repo](https://github.com/gkiely/vite-react-template)

v0.17.1
```
npm i
npm test
```
- Make any update to App.test.tsx
- See terminal reload

v0.18.0
```
npm i vitest@latest
npm test
```
- Make any update to App.test.tsx
- Terminal does not reload, only `rerun x2` updates

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 438.05 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.4.0 - ~/.volta/tools/image/node/18.4.0/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 8.12.1 - ~/.volta/tools/image/node/18.4.0/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 101.0.1
    Safari: 15.3
  npmPackages:
    @vitejs/plugin-react: ^1.3.0 => 1.3.2 
    vite: ^2.9.9 => 2.9.14
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by gkiely** [comment]
Related PR: https://github.com/vitest-dev/vitest/pull/1166

Related comment:
https://github.com/vitest-dev/vitest/pull/1166#issuecomment-1103607998

**Comment by sheremet-va** [comment]
It’s better to discuss first, since the change is intentional.

**Comment by FossPrime** [comment]
Whats the best workaround? I'm using vite-node directly. Best workaround I can think of is involves nodemon, but there's gotta be a better way.

**Comment by gkiely** [comment]
@FossPrime This is the plugin I use

```ts
import type { Plugin } from 'vite';
import pc from 'picocolors';

const clear = () => {
  process.stdout.write('\x1B[2J\x1B[3J\x1B[H\x1Bc\n');
};

// Clear terminal on initial and subsequent loads for vitest
const plugin = (): Plugin => ({
  name: 'clear-vitest',
  load: (p) => {
    clear();
    console.log(pc.black(pc.bgBlue(' RERUN ')), pc.gray(p.match(/(src)\/.+/)?.[0]), '\n');
  },
});

export default plugin;
```

```ts
import { defineConfig } from 'vitest/config';
import clearVitest from './scripts/vite-plugin-clear-vitest';

const TEST =
  typeof process !== 'undefined' &&
  process.env.NODE_ENV === 'test' &&
  process.env.npm_lifecycle_event === 'test';

export default defineConfig({
  plugins: [
    // Clear terminal in watch mode
    TEST && clearVitest(),
  ],
});

```

**Comment by sheremet-va** [comment]
The team likes how the terminal behaves at the moment.
