### ISSUE TITLE
Support jest-like `moduleNameMapper` in vitest

### ISSUE THREAD

**Issue by zthxxx** [vitest-dev/vitest#1628]
### Clear and concise description of the problem

Sometime we have to deal with non-standard third-party packages, such as replace `xxx/es/` to `xxx/lib` which are no need in "vite dev / build" but ONLY need in testing phase, and it's also NOT satisfy vitest [`deps.fallbackCJS`](https://vitest.dev/config/#deps-fallbackcjs) mode.

### Suggested solution

Maybe support some configuration like [jest `moduleNameMapper`](https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Use config option [`resolve.alias`](https://vitejs.dev/config/#resolve-alias).

**Comment by zthxxx** [comment]
@sheremet-va  such as replace xxx/es/ to xxx/lib which are **NO need in "vite dev / build"** but ONLY need in testing phase

**Comment by sheremet-va** [comment]
> @sheremet-va such as replace xxx/es/ to xxx/lib which are **NO need in "vite dev / build"** but ONLY need in testing phase

Use `process.env.VITEST` or `mode === 'test'` to distinguish between test and dev env.

**Comment by zthxxx** [comment]
Ugly, and that's why vitest has a [`fallbackCJS` mode to do those alias](https://github.com/vitest-dev/vitest/blob/v0.18.0/packages/vite-node/src/externalize.ts#L19).

**Comment by sheremet-va** [comment]
> Expose the capability to the user is better than [hide everything behind guessCJSversion](https://github.com/vitest-dev/vitest/blob/v0.18.0/packages/vite-node/src/externalize.ts#L6-L41).

We expose this capability with `resolve.alias`. 

`guessCJSversion` is a fallback option that was enabled some time ago to run wrongly packaged nom packages. It is disabled by default now, and might be removed in the future, because we found a better solution. Please, use `resolve.alias`, `deps.inline` or `vitest.config.ts` to run your tests with different config. If you write "ugly" code, there is nothing we can do to help you, sorry.

**Comment by zthxxx** [comment]
"because we found a better solution" <- What is that?

**Comment by sheremet-va** [comment]
> "because we found a better solution" <- What is that?

Check `isValidNodeImport`.

**Comment by sheremet-va** [comment]
Strictly speaking, packages should define valid `exports` field. If `cjs` version should be loaded, it should be defined with `"require": "cjs"`. If they are not, this is not a problem with Vitest.

More about this: https://github.com/sheremet-va/dual-packaging

**Comment by zthxxx** [comment]
Is that `deps.inline` not compatible with `jsdom` environment？

<img width="800" alt="image" src="https://user-images.githubusercontent.com/15135943/178448951-0c116df1-1cf4-4270-8edc-537388a45cf3.png">

vitest config here:

```ts
  test: {
    include: ['src/**/*.test.(ts|tsx)'],
    globals: true,
    environment: 'jsdom',
    deps: {
      inline: true,
    },
  },
```

Should this needs open with an new issuse?

**Comment by zthxxx** [comment]
> Strictly speaking, packages should define valid `exports` field. If `cjs` version should be loaded, it should be defined with `"require": "./file.cjs"`. If they are not, this is not a problem with Vitest.
> 
> More about this: https://github.com/sheremet-va/dual-packaging

There is no doubt, that's exactly correct, I couldn't agree more!

However, as this issue said at first,

**Sometime we have to deal with non-standard / wrongly / uncontrolled third-party packages**  ☹️

**Comment by sheremet-va** [comment]
> Should this needs open with an new issuse?

Do you have jsdom installed?

`deps.inline: true` means every file will be processed by Vite, including `node_modules`. You can use string or RegExp to inline only needed packages.

> Sometime we have to deal with non-standard / wrongly / uncontrolled third-party packages ☹️

I hope you are also opening issues in this packages, so others don't need to deal with it 😄

**Comment by zthxxx** [comment]
Yes, I have tell those maintainers about the issues for fix some days ago before open this issue in vitest.

**Comment by zthxxx** [comment]
Because of the time, I want to try some way to bypass the problem before they fixed and publish a new version.

I have tried to use `deps.inline: true` (with install jsdom fix the error above) and also `vitest.config.ts` with [`resolve.alias`](https://github.com/rollup/plugins/tree/master/packages/alias#regular-expression-aliases), but nothing works.

With [`resolve.alias`](https://github.com/rollup/plugins/tree/master/packages/alias#regular-expression-aliases), the reason maybe `vite` use [`@rollup/plugin-alias`](https://github.com/rollup/plugins/tree/master/packages/alias) which use [`@rollup/plugin-node-resolve`](https://www.npmjs.com/package/@rollup/plugin-node-resolve) cannot make alias for sub-dependencies with  PNPM。

**Comment by lwazevedo-vortigo** [comment]
In my research I found this solution:
https://divotion.com/blog/how-to-configure-import-aliases-in-vite-typescript-and-jest

And in my case it worked.
