### ISSUE TITLE
isolate not working

### ISSUE THREAD

**Issue by NikolayMakhonin** [vitest-dev/vitest#1629]
### Describe the bug

# isolate not working
**vite.config.mjs**
```js
{
  test: {
    threads: false,
    isolate: false, // true or false - it doesn't matter
    include: [
      'src/**/*.test.js',
    ],
  },
}
```

I declared the `const globalNumber` in the `globalNumber.js` file, and used it in 3 test files:
I expect that this globalNumber will be the same in all 3 tests. But I got this in the console:
```sh
stdout | src/test1.test.js > tests1 > test1
test1: globalNumber=0.6011612733245435

stdout | src/test2.test.js > tests2 > test2
test2: globalNumber=0.5386640966171241     

stdout | src/test3.test.js > tests3 > test3
test3: globalNumber=0.1810086381828495     
```

The `globalNumber` is different for all the tests.

I tried to use global variable to store the `globalNumber`, it worked, but the isolate feature can not disable it. The isolate option seems to have no effect at all. 

### Reproduction

[See my repo to reproduce it](https://github.com/NikolayMakhonin/vite-issues/tree/issue-vitest-isolate)

### System Info

```shell
System:                                                 
    OS: Windows 10 10.0.19042                             
    CPU: (8) x64 Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz
    Memory: 5.63 GB / 15.89 GB                            
  Binaries:
    Node: 16.15.1 - E:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - E:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (103.0.1264.49)
    Internet Explorer: 11.0.19041.906
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`isolate` for tests works only with `threads: true`. If you disable workers, you loose isolations, because it depends on it. Please, read [docs](https://vitest.dev/config/#isolate).

When you disable both, it just means tests are running in the same scope with Vite server and plugins.

The fact that your modules are reevaluated is because we clear all cache before running each test.
