### ISSUE TITLE
feature request: vitest/node cjs distribution

### ISSUE THREAD

**Issue by unicornware** [vitest-dev/vitest#1631]
### Clear and concise description of the problem

As a developer using Vitest, I want to use Vitest programmatically, rather than through the cli so that I can implement custom scripts and Vite plugins.

It seems that I'm unable to do this in cjs projects because `vitest/node` doesn't have a cjs export.

```typescript
  /**
   * Runs Vitest.
   *
   * @see https://vitest.dev
   * @see https://vitejs.dev/guide/api-plugin.html#universal-hooks
   *
   * @public
   * @async
   *
   * @return {void} Nothing when complete
   */
  public async buildStart(): Promise<void> {
    const { startVitest } = await import('vitest/node')

    if (this.opts as UserConfig | undefined) {
      this.ran = await startVitest(this.filters, this.opts, this.overrides)
    }
  }
```

throws

```zsh
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './node' is not defined by "exports" in /xxx/node_modules/vitest/package.json
```

### Suggested solution

Distribute `vitest/dist/node.cjs`.

### Alternative

Running my file with `vite-node` works. My use case includes Storybook, however, and I haven't been able to run Storybook with `vite-node`. CLI flags aren't passed properly, and the `ERR_PACKAGE_PATH_NOT_EXPORTED` error is still thrown.

Re-exporting `startVitest` and importing the function via the proxy file also throws `ERR_PACKAGE_PATH_NOT_EXPORTED`.

### Additional context

- I want to use my custom plugin in my Storybook projects to generate a test report file during the app bootstrap process. The report file will be consumed by [`@storybook/addon-jest`][1]
- Storybook's current implementation prevents me from switching to esm. Storybook v7 makes major improvements to esm support, [but doesn't seem to support Vite][2]

[1]: https://storybook.js.org/addons/@storybook/addon-jest
[2]: https://github.com/storybookjs/storybook/issues/18601#issuecomment-1181064416

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
We don't support CJS, since it's not needed for the majority of users. You can fork Vitest and build CJS version for yourself.

**Comment by unicornware** [comment]
too much of an opportunity for an inconsistencies.
