### ISSUE TITLE
Allow to test for Error instance type

### ISSUE THREAD

**Issue by MonsieurMan** [vitest-dev/vitest#1636]
### Clear and concise description of the problem

I like to use custom Error types to help my user manage errors effectively, and I'd like a way to test it simply in vitest.

It seems Jest allows to do so using: https://jestjs.io/docs/expect#tothrowerror, which states it can accept an `error class: error object is instance of class`.

I tried to find a previous issue or discussion about it in vitest but couldn't, so here's one :)

### Suggested solution

Jest implementations allow to do so :

```js
test('Custom error instance', () => {
  expect(drinkOctopus).toThrowError(DisgustingFlavorError);
});
```

### Alternative

As of now, I wrote a test I don't really like which uses a `try/catch` and an expect(true).to.eq(false) at the end to make it fail if there was no error.

### Additional context

I guess it's here I tell you that Vitest is such a pleasure to use and you guys do a great job :)
Happy to help or provide further information if needed !

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
This should already be implemented. Please provide reproduction.

**Comment by MonsieurMan** [comment]
It works for an error class, I'd say it's only a matter of documenting it here:

https://vitest.dev/api/#tothrowerror
```diff
You can provide an optional argument to test that a specific error is thrown:
  - regular expression: error message matches the pattern
  - string: error message includes the substring
+ - error class: error object is instance of class
```

---

Passing an error instance does not work though, reproduction here: https://stackblitz.com/edit/vitest-dev-vitest-cdj66q?file=test/basic.test.ts

I'd expect vitest to compare class instance, and the message to match in this case.

It's stated as such in Jest's documentation: `error object: error message is equal to the message property of the object`

**Comment by sheremet-va** [comment]
@MonsieurMan your reproduction works if I use `toThrowError` instead of `throws` which is `chai` function, and is not documented as Jest-compatible.

**Comment by MonsieurMan** [comment]
Will do tomorrow, maybe it's just a matter of documenting it then ! :)
