### ISSUE TITLE
unable to alias modules using Vitest/Vite

### ISSUE THREAD

**Issue by TeemuKoivisto** [vitest-dev/vitest#1638]
### Describe the bug

I am replacing my old Jest tests with Vitest (awesome work btw) but I am unable to alias a module in similar manner. Failing to do so the different versions conflict and crash, failing the test. This might be more related to Vite but I succeeded aliasing the same module using just Vite so I'm not sure what's the cause of the problem.

### Reproduction

https://github.com/TeemuKoivisto/vite-unable-to-alias-module

### System Info

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 232.34 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 102.0
    Safari: 14.1.2
  npmPackages:
    vite: ^3.0.0 => 3.0.0 
    vitest: ^0.18.0 => 0.18.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Haven't tested it, but `@manuscripts/manuscript-transform` is not ESM package, and it loads cjs version of `prosemirror-model`, while when you directly import it in a test ESM version is loaded.

Try adding `@manuscripts/manuscript-transform` to `test.deps.inline`.

**Comment by TeemuKoivisto** [comment]
Hey thanks for advice! Hmm adding it to the inline list I get another error:
```
TypeError: exports.hasOwnProperty is not a function
 ❯ __exportStar node_modules/.pnpm/@manuscripts+manuscript-transform@0.49.4/node_modules/@manuscripts/manuscript-transform/dist/cjs/index.js:10:54
      8| }));
      9| var __exportStar = (this && this.__exportStar) || function(m, exports) {
     10|     for (var p in m) if (p !== "default" && !exports.hasOwnProperty(p)) __createBinding(exp…
       |                                                      ^
     11| };
     12| Object.defineProperty(exports, "__esModule", { value: true });
```

I have succeed in loading `@manuscripts/manuscript-transform` with Vite without duplicating `prosemirror-model` using alias before so I'm really baffled why it's breaking now.

**Comment by rgripper** [comment]
I suspect I have the same issue. Preact alias is not applied when running vitest against a third-party library that itself imports` react`. But vite itself  builds and runs without an issue.
Here is a tiny repro
https://github.com/rgripper/bug-demo

And error (it is from slightly different source code)
```
TypeError: Cannot read properties of null (reading 'useState')
 ❯ useState ../../node_modules/.pnpm/react@18.2.0/node_modules/react/cjs/react.development.js:1622:21
 ❯ d.N [as constructor] ../../node_modules/.pnpm/@headlessui+react@1.6.6/node_modules/@headlessui/react/dist/components/switch/switch.js:1:857
```

 ❯ d.O [as render] ../../node_modules/.pnpm/preact@10.10.0/node_modules/preact/dist/preact.mjs:1:8158

**Comment by sheremet-va** [comment]
Code of deps is not runing through Vite pipeline. At the moment we don't have a good solution for this. To fix this, you can use `deps.inline` option.
