### ISSUE TITLE
`ERR_DLOPEN_FAILED` rerunning tests

### ISSUE THREAD

**Issue by tangdaoyuan** [vitest-dev/vitest#1639]
### Describe the bug

1. only appears in mac (native module with Napi & object-c)
2. It works running vitest watching mode
3. Triggering vitest rerun case following error:
![image](https://user-images.githubusercontent.com/8007202/178975549-bb86a89c-623c-4e3b-adaf-0af6f123f1b4.png)

ps:

*  [`isolate`](https://vitest.dev/config/#isolate) will solve this problem
*  I guess it has something to do with tinypool and native module code (napi or object-c)
 

### Reproduction

https://github.com/tangdaoyuan/vitest-bug-reporter

Reproduction Step 

* pnpm install
* pnpm run test
* trigger `rerun`

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 740.74 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
    npm: 7.10.0 - ~/.nvm/versions/node/v16.0.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 86.0.1
    Safari: 13.1.3
  npmPackages:
    vite: 2.9.14 => 2.9.14
    vitest: 0.18.0 => 0.18.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by giladgd** [comment]
This also happens to me.
Is there any progress on this?

**Comment by sheremet-va** [comment]
Use `--pool=forks` if you have a native dependency. A lot of native dependencies don't support multi-threading which Vitest uses by default.
