### ISSUE TITLE
Issue with `fs` module mock

### ISSUE THREAD

**Issue by mrmckeb** [vitest-dev/vitest#1645]
### Describe the bug

When trying to mock `fs` (or `node:fs`), I'm only able to mock the return value or mock implementation under certain conditions.

In the below reproduction, switching the order of the two tests actually makes the tests work.

Note that this project is set to ESM, via `"type": "module"` in `package.json`.

### Reproduction

File:
```ts
import { readFileSync } from 'node:fs';

export const readFile = () => {
  try {
    return readFileSync('some-file', 'utf-8');
  } catch (e) {
    return '';
  }
};
```

Test:
```ts
import { readFileSync } from 'node:fs';
import { afterEach, describe, expect, it, vi } from 'vitest';

vi.mock('node:fs', () => ({
  readFileSync: vi.fn().mockImplementation(() => ''),
}));

const mockReadFileSync = vi.mocked(readFileSync);

describe('env', () => {
  afterEach(() => {
    vi.resetModules();
  });

  it('should handle a missing file', async () => {
    mockReadFileSync.mockImplementation(() => {
      throw new Error('Some error');
    });
    const { readFile } = await import('./repro');
    expect(readFile()).toBe('');
  });

  it('should read a file', async () => {
    mockReadFileSync.mockImplementation(() => 'Some contents');
    const { readFile } = await import('./repro');
    expect(readFile()).toBe('Some contents');
  });
});
```

Config:
```ts
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    mockReset: true,
  },
});
```

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 177.42 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.6.0 - ~/Library/Caches/fnm_multishells/11869_1657854968244/bin/node
    npm: 8.13.2 - ~/Library/Caches/fnm_multishells/11869_1657854968244/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Edge: 103.0.1264.62
    Firefox: 102.0.1
    Safari: 15.5
  npmPackages:
    vitest: ^0.18.0 => 0.18.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`vi.resetModules` removes mocks. This is bug with `resetModules`, and not with ESM mocking. Importing `fs` has nothing to do with ESM.

**Comment by mrmckeb** [comment]
Thank you!
