### ISSUE TITLE
`test.runIf(...).each is not a function` when condition is false

### ISSUE THREAD

**Issue by mikestopcontinues** [vitest-dev/vitest#1647]
### Describe the bug

Using `test.runIf()` when condition evaluates to `false`, I get the following error. However, when the condition evaluates to `true`, everything runs fine.

```
TypeError: test.runIf(...).each is not a function
 ❯ file.test.ts:24:20
     22| 
     23| describe('PageParser<amazon, profile>', () => {
     24|   test.runIf(false).each([
       |                    ^
```

### Reproduction

Here's a [repro](https://stackblitz.com/edit/vitest-dev-vitest-guk5we?file=test/basic.test.ts).

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.68 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/Library/Caches/fnm_multishells/64764_1657806820989/bin/node
    Yarn: 3.2.0 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/Library/Caches/fnm_multishells/64764_1657806820989/bin/npm
  Browsers:
    Brave Browser: 103.1.41.96
    Chrome: 103.0.5060.114
    Chrome Canary: 105.0.5181.0
    Firefox: 99.0
    Safari: 15.4
```
```


### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Demivan** [comment]
`each` is not chainable. It is the same as doing `test.skip.each` and that is not supported. 
I will adjust types to reflect this.

You can use `describe.runIf` and move `test.each` inside of it.

@antfu What do you think, should we support `test.skip.each?` I'm not sure how it should work :)

**Comment by mikestopcontinues** [comment]
Thanks for clarifying it's a type issue! I have other solutions for my use-case, but I do think this would be a wise direction. Whether it's `skip.each` or `skipIf().each` (etc), it's an added bit of convenience.

My inclination would be to use some thin classes for `SuiteAPI` and `TestAPI` to reduce the cost of instantiating an additional swath of funcs, but preserve the functional style by producing new instances upon each chain operation. For instance, `skip` and `skipIf` can be modeled with something like:

```ts
get skip: () => {
  return new SuiteAPI({...this.state, skip: true});
}

skipIf: (cond: any) => {
  return new SuiteAPI({...this.state, skip: !!cond});
}
```

Would this work?
