### ISSUE TITLE
import NodeTypes from '@vue/compiler-core', NodeTypes is undefined

### ISSUE THREAD

**Issue by xusyang** [vitest-dev/vitest#1650]
### Describe the bug

``` typescript
import { describe, expect, it } from 'vitest';
import { NodeTypes } from '@vue/compiler-core';

describe('suite name', () => {
  it('import NodeTypes', () => {
   // TypeError: Cannot read properties of undefined (reading 'ATTRIBUTE')
    expect(NodeTypes.ATTRIBUTE).toMatchInlineSnapshot();
  });
});
```
why NodeTypes is undefined? I can't sure that is vite's reason.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-ycjtaj?file=test/suite.test.ts

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 94.02 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 15.3
  npmPackages:
    vitest: ^0.17.0 => 0.17.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Demivan** [comment]
`NodeTypes` is a `const enum`, it exists only in Typescript. It is compiled out of Vue, every instance is replaced with appropriate value. That is why you cannot import it.

And from Vite docs: https://vitejs.dev/guide/features.html#typescript
> .. because esbuild only performs transpilation without type information, it doesn't support certain features like const enum and implicit type-only imports.

**Comment by xusyang** [comment]
em, thks.
