### ISSUE TITLE
Configurable `CLOSE_TIMEOUT`

### ISSUE THREAD

**Issue by ifiokjr** [vitest-dev/vitest#1659]
### Clear and concise description of the problem

When running tests with the `globalSetup` option, the tests often timeout before the full teardown is completed. 

For example, I spin up a database and then shut it down in the teardown, The current 1000ms is not sufficient for the task.

### Suggested solution

Allow this timeout to be configured. Perhaps `teardownTimeout`.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I don't see any timeout in the code. Can you show the actual error?

**Comment by ifiokjr** [comment]
Here's an [example](https://stackblitz.com/edit/node-dy7o2r). 

```bash
npm run test
```

Will result in an error 

```diff
-close timed out after 1000ms
```

It is defined here:

https://github.com/vitest-dev/vitest/blob/ffa358517eb6a5ae6c975495d9ac3a05bfd9939f/packages/vitest/src/node/core.ts#L23

and here:

https://github.com/vitest-dev/vitest/blob/ffa358517eb6a5ae6c975495d9ac3a05bfd9939f/packages/vitest/src/node/core.ts#L433-L442
