### ISSUE TITLE
Coverage does not ignore yarn3 .pnp.csj and .pnp.loader.mjs

### ISSUE THREAD

**Issue by ZiperRom1** [vitest-dev/vitest#1668]
### Describe the bug

When running `vitest run --coverage --config ./vitest.config.ts --reporter dot ` on a vuejs3 empty project, the files `.pnp.csj` and `.pnp.loader.mjs` are not ignored in the report while they are excluded from the following config file.

**vitest.config.ts**

```ts
import { fileURLToPath, URL } from "url";
import { configDefaults, defineConfig } from 'vitest/config';

import vue from "@vitejs/plugin-vue";
import vueJsx from "@vitejs/plugin-vue-jsx";


export default defineConfig({
  plugins: [vue(), vueJsx()],
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url))
    }
  },
  test: {
    exclude: [...configDefaults.exclude, '.{pnp.cjs,pnp.loader.mjs}'],
    environment: 'happy-dom',
    coverage: {
      reporter: ['cobertura', 'text']
    }
  }
});
```

**Console output**

```
 RUN  v0.18.1 /home/rom1/Projects/daia-ihm

··

Test Files  1 passed (1)
     Tests  2 passed (2)
      Time  1.71s (in thread 3ms, 56902.52%)

-------------------------|---------|----------|---------|---------|---------------------------------
File                     | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s               
-------------------------|---------|----------|---------|---------|---------------------------------
All files                |   69.14 |    64.06 |   31.67 |   69.14 |                                 
 daia-ihm                |    69.1 |    64.06 |   31.67 |    69.1 |                                 
  .pnp.cjs               |   69.08 |    63.51 |   31.22 |   69.08 | ...7016,17049-17062,17082-17129 
  .pnp.loader.mjs        |   70.47 |    72.05 |      50 |   70.47 | ...,138-146,150-161,163-170,259 
 daia-ihm/src/components |     100 |      100 |     100 |     100 |                                 
  the-top-bar.vue        |     100 |      100 |     100 |     100 |                                 
-------------------------|---------|----------|---------|---------|---------------------------------
```

### Reproduction

Empty vuejs3 project using yarn3 PnP with `.pnp.csj` and `.pnp.loader.mjs` files.

[minimal project here](https://github.com/ZiperRom1/vitetest-minmal-reproductible-exemple)

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 55.05 GB / 62.72 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.16.0 - /usr/bin/node
    Yarn: 3.2.1 - /usr/bin/yarn
    npm: 8.11.0 - /usr/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 102.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Use `coverage.exlude` options. `test.exclude` is for excluding tests that should not run.
