### ISSUE TITLE
During the CI process, the memory of my vitest will explode

### ISSUE THREAD

**Issue by spicylemonhaha** [vitest-dev/vitest#1674]
### Describe the bug

During the CI process, the memory of my vitest will explode

### Reproduction

+ cd apps/promotion
+ rushx test
Found configuration in /home/code/rush.json
Rush Multi-Project Build Tool 5.71.0 - Node.js 14.18.1 (LTS)
> "vitest run"
 RUN  v0.18.0 /home/code/apps/promotion
events.js:377
      throw er; // Unhandled 'error' event
      ^
RangeError [Error]: WebAssembly.instantiate(): Out of memory: wasm memory
    at internal/deps/cjs-module-lexer/dist/lexer.js:1:33593
Emitted 'error' event on process instance at:
    at emitUnhandledRejectionOrErr (internal/event_target.js:579:11)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:403:9)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26)
The script failed with exit code 1

### System Info

```shell
System:
    OS: Linux 5.4 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (104) x64 Intel(R) Xeon(R) Platinum 8269CA CPU @ 2.50GHz
    Memory: 29.09 GB / 32.00 GB
    Container: Yes
    Shell: 5.0.3 
  Binaries:
    Node: 14.18.1 
    Yarn: 1.22.15 
    npm: 6.14.15
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
What is `apps/promotion`?

**Comment by spicylemonhaha** [comment]
Sub-applications of micro frontends.
The content of rushx test is vitest run.
And the vitest config is default.

**Comment by sheremet-va** [comment]
> Sub-applications of micro frontends.
> The content of rushx test is vitest run.
> And the vitest config is default.

I didn't understand any of it. Can you provide a reproduction inside a repo?

**Comment by spicylemonhaha** [comment]
Sorry, we cannot reproduce the environment due to the complex project structure and the error is in the CI environment. In fact, although it is a sub-application of micro-frontend, you can understand it as an independent project for this apps/promotion.

**Comment by sheremet-va** [comment]
Sorry, but we cannot help you, if you don't provide minimal reproduction.

**Comment by spicylemonhaha** [comment]
> // in package.json
"test": "NODE_OPTIONS=--max-old-space-size=1536 vitest run --config ./vitest.config.js",
// in vitest.config.js
test: {
    minThreads: 2,
    maxThreads: 3,
  },

With these configurations, our tests in CI don't seem to crash anymore. Can you tell me why this is.

**Comment by frankwallis** [comment]
I'm seeing the same thing. It's interesting that it only happens in CI - I wonder if vitest is trying to utilise all the available cores on the physical node when calculating the number of threads to allocate.

**Comment by spicylemonhaha** [comment]
> 


Do you know how to fix this now?

> I'm seeing the same thing. It's interesting that it only happens in CI - I wonder if vitest is trying to utilise all the available cores on the physical node when calculating the number of threads to allocate.


Do you know how to fix this now?

**Comment by spicylemonhaha** [comment]
> I'm seeing the same thing. It's interesting that it only happens in CI - I wonder if vitest is trying to utilise all the available cores on the physical node when calculating the number of threads to allocate.


Do you know how to fix this now?

**Comment by alexlafroscia** [comment]
We're seeing this error sporadically in our own CI process, and setting the `--max-old-space-size` alone didn't fix things for us

**Comment by szhang-brighte** [comment]
We don't see node failure, but the tests are not passing without setting `minThreads` and `maxThreads`. Running tests locally is fine. We have to do this to make ci working
```typescript
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '');
  return {
    /* other configs */
    test: {
      /* other configs */
      ...(env.CI && {
        minThreads: 4,
        maxThreads: 4,
      }),
    }
```
