### ISSUE TITLE
Unable to run project after importing Vitest in project (Nuxt3)

### ISSUE THREAD

**Issue by ASoldo** [vitest-dev/vitest#1683]
### Describe the bug

When I added the vitest and @nuxt/test-utils-edge in project i tried it to see if the tests are working and they are working. But when I try to serve my app with npm run dev I get this error message. If I remove Vitest it is working again.

`TypeError: Cannot read properties of undefined (reading 'config')
    at file:///C:/Users/Korisnik/Documents/nuxt-app/node_modules/vitest/dist/chunk-runtime-chain.b60d57da.mjs:1888:34
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)`

This is my index.test.ts file:
`import { assert, describe, expect, it } from 'vitest'
describe('suite name', () => {
  it('foo', () => {
    expect(1 + 1).toEqual(2)
    expect(true).to.be.true
  })
  it('bar', () => {
    assert.equal(Math.sqrt(4), 2)
  })
  it('snapshot', () => {
    expect({ foo: 'bar' }).toMatchSnapshot()
  })
})`

Am is missing something here? Watching tutorials online didn't mention any configs or extra steps. 
Thank you

### Reproduction

It is a fresh Nuxt3 project but this are my dependencies 
`{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "dev:https": "nuxt dev --https",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "docs:dev": "vitepress dev docs",
    "docs:build": "vitepress build docs",
    "docs:serve": "vitepress serve docs",
    "test": "vitest --reporter verbose --globals",
    "test:coverage": "vitest --coverage",
    "test:watch": "vitest --reporter verbose --globals"
  },
  "devDependencies": {
    "@nuxt/content": "^2.0.1",
    "c8": "^7.11.3",
    "nuxt": "3.0.0-rc.5",
    "tailwindcss": "^3.1.6",
    "vitepress": "^1.0.0-alpha.4",
    "vitest": "^0.18.1"
  },
  "dependencies": {
    "@heroicons/vue": "^1.0.6",
    "@nuxt/test-utils-edge": "^3.0.0-rc.6-27635653.88f4525",
    "@nuxt/types": "^2.15.8",
    "@nuxt/typescript-build": "^2.1.0",
    "@pinia/nuxt": "^0.3.0",
    "@storyblok/nuxt": "^4.0.1",
    "pinia": "^2.0.16",
    "pinia-plugin-persistedstate": "^1.6.3",
    "pixi.js": "^6.4.2",
    "three": "^0.134.0",
    "troisjs": "^0.3.4",
    "vue3-lottie": "^2.2.5"
  }
}`

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz
    Memory: 2.81 GB / 15.87 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.62)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitest: ^0.18.1 => 0.18.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by GeoffreyDick** [comment]
@ASoldo were you able to find a solution for this? I'm running into the same problem.
