### ISSUE TITLE
Tests pass but vitest fails non-deterministically and sometimes causes Unhandled Rejection

### ISSUE THREAD

**Issue by prabhatsharma** [vitest-dev/vitest#1692]
### Describe the bug

While test cases results themselves are deterministic but the runs are not. Some of the runs produce unhandled rejection. This seems to be similar to https://github.com/vitest-dev/vitest/issues/1191 but not same. My test specs are fairly minimal at this time, like just checking for component rendering and not much.

```shell
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 2 unhandled errors during the test run. This might cause false positive tests.
Please, resolve all the errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: 
 ❯ post node_modules/vitest/dist/worker.mjs:70:14
 ❯ node_modules/vitest/dist/chunk-vite-node-utils.8077cd3c.mjs:1376:11
 ❯ sendCall node_modules/vitest/dist/chunk-vite-node-utils.8077cd3c.mjs:1373:16
 ❯ node_modules/vitest/dist/chunk-runtime-rpc.9d1f4c48.mjs:7:55
      5|   return new Proxy(rpc2, {
      6|     get(target, p, handler) {
      7|       const sendCall = Reflect.get(target, p, handler);
       |                                                       ^
      8|       const safeSendCall = (...args) => withSafeTimers(() => sendCall(...args));
      9|       safeSendCall.asEvent = sendCall.asEvent;
 ❯ withSafeTimers node_modules/vitest/dist/chunk-utils-global.0a7416cf.mjs:472:20
 ❯ Proxy.safeSendCall node_modules/vitest/dist/chunk-runtime-rpc.9d1f4c48.mjs:7:41
 ❯ process.<anonymous> node_modules/vitest/dist/worker.mjs:34:11
 ❯ process.emit node:events:527:28
 ❯ emit node:internal/process/promises:140:20


```

### Reproduction

You should be able to reproduce it using this repo.

https://github.com/zinclabs/zinc/tree/38303f59af5f329c62068a320eecd4f53c17b107

steps.

```shell
git clone https://github.com/zinclabs/zinc
cd zinc
git checkout 38303f59af5f329c62068a320eecd4f53c17b107
cd web
npm i 
npm run test-once
```
run the test a couple of times. You will notice that sometimes tests are successful however sometimes there is unhandled rejection.

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M2
    Memory: 372.69 MB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 103.1.41.96
    Chrome: 103.0.5060.134
    Safari: 15.5
  npmPackages:
    @vitejs/plugin-vue: ^2.3.3 => 2.3.3 
    vite: ^2.9.14 => 2.9.14 
    vitest: ^0.18.1 => 0.18.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nieyuyao** [comment]
This should be caused by some promises not catching errors.

**Comment by rogerleung0411** [comment]
May i ask there is any possible solution? same issue here :(

**Comment by calvinf** [comment]
If you have a vitest setup file via `--setupFiles` ([link](https://vitest.dev/config/#setupfiles)), inside of it you can add a very loud failure for `unhandledRejection`.

```
// FAIL LOUDLY on unhandled promise rejections / errors
process.on('unhandledRejection', (reason) => {
  // eslint-disable-next-line no-console
  console.log(`FAILED TO HANDLE PROMISE REJECTION`);
  throw reason;
});
```

This helped me to find the specific file that I was failing to await a Promise that needed to be handled (which was difficult due to hundreds of files/tests).

**Comment by sheremet-va** [comment]
@calvinf thank you for pointing it out, Vitest didn't serialise errors thrown in `unhandledRejection`, so some errors might've slipped as `Unknown Error: undefined`. #2253 should fix it.

**Comment by hugw** [comment]
@sheremet-va could you confirm if the issue was fixed? Facing the same problem right now and I'm using version 0.24.5.
I am randomly getting unhandled rejection errors.
Like 30% of the time the tests pass but get this unhanded rejection that doesn't show exactly which test caused it.

<img width="805" alt="Screen Shot 2022-11-08 at 12 34 40 PM" src="https://user-images.githubusercontent.com/4526523/200635981-8505fd7b-548e-4ab1-8977-55a6b26cce5d.png">

**Comment by sheremet-va** [comment]
> @sheremet-va could you confirm if the issue was fixed? Facing the same problem right now and I'm using version 0.24.5.
> 
> I am randomly getting unhandled rejection errors.
> 
> Like 30% of the time the tests pass but get this unhanded rejection that doesn't show exactly which test caused it.
> 
> 
> 
> <img width="805" alt="Screen Shot 2022-11-08 at 12 34 40 PM" src="https://user-images.githubusercontent.com/4526523/200635981-8505fd7b-548e-4ab1-8977-55a6b26cce5d.png">
> 
> 

Yes, mentioned in this PR error is fixed.

You probably have an asynchronous process that's executed after all tests have passed. Vitest cannot track it, it's unhandled.

**Comment by hugw** [comment]
I see, thanks for getting back.

**Comment by IlyaEremin** [comment]
@sheremet-va I'm facing smae issue with unhandled error. What's the strategies to catch it and find a source?

**Comment by thoriumdesign** [comment]
> @sheremet-va I'm facing smae issue with unhandled error. What's the strategies to catch it and find a source?

I followed the steps above in https://github.com/vitest-dev/vitest/issues/1692#issuecomment-1293941666

My vitest has a config file, vitest.config.ts in the root of my project.

The config contains this (truncated example, I removed `environment`, `include`, and `plugins`):

```ts
// vitest.config.ts

export default defineConfig({
  test: {
    setupFiles: ['test/vitest/setup-file.ts'],
  }
});
```

The setup file now has the snippet mentioned above:

```ts
// test/vitest/setup-file.ts

// FAIL LOUDLY on unhandled promise rejections / errors
process.on('unhandledRejection', (reason) => {
  // eslint-disable-next-line no-console
  console.log('FAILED TO HANDLE PROMISE REJECTION');
  throw reason;
});

export default {};
```

(Note the `export default {};` at the end, to make it a valid TS file.)

All I can say is, while I don't yet understand why, the non-deterministic failures seem to have disappeared, and I'm also not getting the console log from setup-file.ts.

**Comment by kb-0311** [comment]
@sheremet-va If I do have some async process running in a test suite and it passes only when all the other tests have passes, else throws this unhandled error as mentioned  https://github.com/vitest-dev/vitest/issues/1692#issuecomment-1307588732 what might be the best way to handle it?
