### ISSUE TITLE
run console.log in vitest ，the file and code line number infomation is missing

### ISSUE THREAD

**Issue by zhengwh** [vitest-dev/vitest#1694]
### Clear and concise description of the problem

<img width="410" alt="image" src="https://user-images.githubusercontent.com/7886873/180122034-f27d6743-ed05-4936-bd7e-2cae95d8bee3.png">

### Suggested solution

i think the log number will be more helper to location the code

<img width="917" alt="image" src="https://user-images.githubusercontent.com/7886873/180122095-ae47f710-3239-437e-a5d8-07d14718cc94.png">

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by geekox86** [comment]
Greetings,

If this is easy to do, I would like to give it a shot with a PR. I also suggest to show codeframes for console.warn and maybe others?

**Comment by sheremet-va** [comment]
We can add an option to show the stacktrace.

**Comment by sheremet-va** [comment]
This is closed by https://github.com/vitest-dev/vitest/pull/5720. Use `--print-console-stack` flag to show stack traces for every console log (available since [v2.0.0-beta.4](https://github.com/vitest-dev/vitest/releases/tag/v2.0.0-beta.4)).
