### ISSUE TITLE
Watch mode doesn't work on Windows

### ISSUE THREAD

**Issue by DannyFeliz** [vitest-dev/vitest#17]
I'm testing the watch mode `vitest -w` but it's not rerunning the tests when I make a file change.

**Comment by Lauro235** [comment]
> I don't have Windows to test out right now. But if anyone got interested, here might be the cause:
> 
> https://github.com/antfu-sponsors/vitest/blob/3a3193d71ee109335d8bba7de55d10e39e84749d/src/run/index.ts#L242
> 
> The path from `chokidar` might use backslash while on Vite we normalize them. We might just need to replace all backslash to slash and append a leading `/` if there isn't one. Thanks.

Please, if you wouldn't mind expanding on this. I'm not quite sure which folder / file to go into and edit. Does the change take place in the vitest module, the chokidar module or in a local project file?

Thanks!
