### ISSUE TITLE
Filter out stdout/stderr messages

### ISSUE THREAD

**Issue by jackfranklin** [vitest-dev/vitest#1700]
### Clear and concise description of the problem

I'm working on a LitHtml project and when you run it in development mode it logs a message to the console, that appears when I do test runs:

```
stderr | unknown test
Lit is in dev mode. Not recommended for production!
 See https://lit.dev/msg/dev-mode for more informat
ion.
```

When running my tests, I get this multiple times and it provides no value. I know I can use `--silent` to ignore all output, but I do want to see any other messages.

### Suggested solution

I was picturing a configuration setting that you could set:

```
{
  ignoreConsoleMessages: {
    source: 'stderr' // 'stdout' | 'stderr'
    match: /Lit is in dev mode/
  }
}
```

Or similar. That way the developer can very explicitly ignore certain messages, but can still see all other messages.

If this is acceptable, I would be happy to make an attempt at implementation in a PR :+1: 

### Alternative

I think I could solve this in user-land by using a stubbing library such as sinon, and mock the console methods. But I think this is something worth considering solving in the configuration layer.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I think this should be done in user land. You can do something like this:

```ts
const log = console.log
console.log = (...msg) => {
  if(!msg.join(' ').includes('Lit')) {
    log(...msg)
  }
}
```

**Comment by jackfranklin** [comment]
Sure! Just wanted to see if there was interest in this landing upstream.

**Comment by nicooprat** [comment]
This is the workaround that finally removed all I need, hope it can help someone else:

```js
const { info, log, warn, error } = console;
const ignored = ['You are running Vue in development mode.', 'Download the Vue Devtools extension', '[Elastic APM]'];

const filterIgnored = (callback, ...args) => {
  const msg = args?.[0];
  if (typeof msg !== 'string' || !ignored.some((ignoredMsg) => msg.includes(ignoredMsg))) {
    callback(...args);
  }
};

console.info = (...args) => filterIgnored(info, ...args);
console.log = (...args) => filterIgnored(log, ...args);
console.warn = (...args) => filterIgnored(warn, ...args);
console.error = (...args) => filterIgnored(error, ...args);
```

This **must** be done before importing `Vue` for instance, at the very top of `vitest.setup.js`.

I tried everything else to prevent these to be emitted at first, but couldn't find the solution. For instance, configs like these seems to be completely ignored: 

```js
Vue.config.productionTip = false;
Vue.config.devtools = false;
```

🤷‍♂️

**Comment by treardon17** [comment]
@nicooprat I had the same issue as you -- not being able to disable the productionTip/devtools logging. After messing with the config for a bit, I was able to finally disable the logs by creating a `vitest.config.js` containing this:

```javascript
import { vi } from 'vitest';

vi.mock('vue', async () => {
  const Vue = await vi.importActual('vue') as any;

  Vue.default.config.productionTip = false;
  Vue.default.config.devtools = false;

  return Vue;
});
```

and then adding this to my `vitest.config.js`:

```javascript
{
  test: {
    setupFiles: [
      path.resolve(__dirname, './vitest.setup.ts'),
    ],
  },
}
```

**Comment by nicooprat** [comment]
Looks cleaner, but I couldn't make it work. I'm using latest Vue 2.7 release by the way, don't know if it's your case too...?

**Comment by treardon17** [comment]
I'm on Vue 2.7 as well. Do you have other scripts configured in `setupFiles`? Maybe something is loading vue before it gets mocked?

**Comment by nicooprat** [comment]
Looks like `import vue from '@vitejs/plugin-vue2';` in `vite.config.ts` indeed loads Vue before the mock happens. How did you manage to make it work? Do you have a separate config for Vitest?

**Comment by treardon17** [comment]
I'm working in a monorepo and have a base config that I merge other configs into. I think that import in `vite.config.ts` is just importing the plugin? There are references to `'vue/compiler-sfc'` but I would imagine that's just the compiler code. Perhaps something else is importing vue? Do you have a complex `vite.config`?

**Comment by panzerdp** [comment]
@treardon17 Your solution to disable the devtools console message worked for me. Thanks!

**Comment by BenShelton** [comment]
It appears you can now also do this with a (currently undocumented) option in your vite/vitest config:

```ts
test: {
  onConsoleLog (log) {
    if (log.includes('Download the Vue Devtools extension')) return false
    if (log.includes('Lit is in dev mode.')) return false
  },
```

**Comment by nicooprat** [comment]
Just tested with Vitest `0.25.7` and it works, thanks! 🙏 

As a side note, do you also have the logs prepended with `[log]`, `[error]` or `[warn]` like this?

```
[log]  Test Files  67 passed | 1 skipped (68)                                
[log]  Tests  533 passed | 7 skipped (540)                              
[log]  Start at  10:27:58                                                  
[log]  Duration  65.33s (transform 7.60s, setup 6.33s, collect 66.86s, tests 11.63s)
```

Could find any way to clean it up.

**Comment by nicooprat** [comment]
Thank you very much... I'm finally getting clean logs! Here's my solution:

```js
vite.config.js
...
plugins: [
  process.env.VITEST !== 'true' &&
    // This must not be statically imported because it mutates console methods
    // https://github.com/vbenjs/vite-plugin-html/issues/58
    (await import('vite-plugin-html')).createHtmlPlugin({
      inject: {
        data: foo,
      },
    }),
]
...
```
