### ISSUE TITLE
Type 'Plugin' is not assignable to type 'PluginOption'

### ISSUE THREAD

**Issue by spacedawwwg** [vitest-dev/vitest#1706]
### Describe the bug

<img width="738" alt="image" src="https://user-images.githubusercontent.com/1691867/180676031-8e539a67-3756-4c08-b5a9-64499e7b6ea3.png">

### Reproduction

N/A

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 18.16 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 3.1.1 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Brave Browser: 103.1.40.107
    Chrome: 103.0.5060.134
    Firefox: 102.0.1
    Safari: 15.5
  npmPackages:
    @vitejs/plugin-vue: 2 => 2.3.3 
    vite: 2 => 2.9.14 
    vitest: 0.18.0 => 0.18.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This means you have 2 versions of Vite installed. Cleanup your lock file.

**Comment by ben-xD** [comment]
I had a similar issue, and upgrading **vitest** fixed it. My `package.json` went from using `^0.25.5` to `^0.27.1`.

**Comment by gxxcastillo** [comment]
In my case, I manually installed the latest version of rollup(v3.17.2) and the issue went away.

**Comment by karolstawowski** [comment]
Had to update Vite to the lastest stable version `4.1.0` -> `4.1.4`
