### ISSUE TITLE
Vitest doesn't use mjs file and produce "SyntaxError: Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by sklme** [vitest-dev/vitest#1713]
### Describe the bug

I use third part UI lib: tencent-design-next, vite build and serve is ok, but fail in vitest.

<img width="682" alt="image" src="https://user-images.githubusercontent.com/4933537/180753361-42f39bea-40df-4a03-90a1-cd458c4384f8.png">

What I did: 
1、checking if there are `.mjs` and  `module` field in `package.json` of this package.(Yes, there are)
![image](https://user-images.githubusercontent.com/4933537/180753305-4c4ec643-9647-4168-9543-442b9f2bb4a1.png)
2、try add the following code to `vite.confi.ts`(produce error still).
<img width="423" alt="image" src="https://user-images.githubusercontent.com/4933537/180754081-69c57026-9081-43ef-bdd9-a61caab32ab3.png">

### reproduction url
https://stackblitz.com/github/sklme/vite-vue3-template/tree/vitest-error-reproduce?file=vite.config.ts

### reproduction step
run `vitest`

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (20) x64 Intel(R) Core(TM) i9-10910 CPU @ 3.60GHz
    Memory: 1.18 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.2.0 - ~/.nvm/versions/node/v18.2.0/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v18.2.0/bin/yarn
    npm: 8.9.0 - ~/.nvm/versions/node/v18.2.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.5
    Safari Technology Preview: 16.0
  npmPackages:
    @vitejs/plugin-vue: ^3.0.1 => 3.0.1 
    vite: 3 => 3.0.2 
    vitest: ^0.18.1 => 0.18.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Node.js doesn't support `module` field as resolving entry. Please, open an issue in your library to add `exports` field. More about that: https://github.com/sheremet-va/dual-packaging

In the meantime, you can do what the errors says you should do. You can also extend `resolve.mainFields`, and add `module` field yourself, but you other packages might fail (or they might not).
