### ISSUE TITLE
Unable to mock 'vue-meta'

### ISSUE THREAD

**Issue by jagoncalves14** [vitest-dev/vitest#1714]
### Describe the bug

I was trying to upgrade Vitest from version `0.12.9` to `0.19.0` and now tests that are asserting a specific function from a module to have been called started failing.

That module is an npm package called `vue-meta`. ([Link](https://www.npmjs.com/package/vue-meta/v/3.0.0-alpha.10))
I have components that `import { useMeta } from 'vue-meta'`.

That `useMeta` function is called when some components are mounted or created.
All I want to do is to spy `useMeta` and assert it, expecting that it gets called. Should be easy, right? 

But for some reason this stopped working after the upgrade and I'm clueless in understanding why.

I was able to create StackBlitz reproducing this. Just open the link and the test will run automatically.

### Reproduction

https://stackblitz.com/edit/vue-vitest-demo

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 819.89 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    npm: 8.3.2 - ~/Projects/clearancejobs/node_modules/.bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 100.0
    Safari: 15.5
  npmPackages:
    @vitejs/plugin-vue: 2.1.0 => 2.1.0
    vite: 2.9.9 => 2.9.9
    vitest: 0.19.0 => 0.19.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jagoncalves14** [comment]
Note: This started happening in **vitest@0.14.2**

**Comment by sheremet-va** [comment]
It's mention in #1740 that #1726 fixed it, can you confirm? If so, you can close the issue.

**Comment by ChpShy** [comment]
By my test, it's ok in `v0.20.1`.

**Comment by jagoncalves14** [comment]
@sheremet-va, @ChpShy. Just tested it in both `v.0.20.1` and `v.0.20.2` and the issue is fixed.

Thanks to everyone involved, that was a super quick fix! 
I'm closing the issue as its been resolved.
