### ISSUE TITLE
HTML reporter

### ISSUE THREAD

**Issue by flunderpero** [vitest-dev/vitest#1716]
### Clear and concise description of the problem

`@vitest/ui` already creates a beautiful and very useful HTML report. We would like to have something similar created in our CI.

### Suggested solution

Make `@vitest/ui` also a regular reporter.

### Alternative

We can always convert the Junit output to HTML, but the UI of `@vitest/ui` is so much better.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sounds like a good idea. To make it possible, it might require some bug refactoring to UI to allow reading from static data instead of the WebSocket RPC.
