### ISSUE TITLE
Test passes, but fails with .then() 

### ISSUE THREAD

**Issue by kevmul** [vitest-dev/vitest#1720]
### Describe the bug

I have a test where I set the props when creating the `wrapper`. After testing everything lines up, I change my props with an `await wrapper.setProps()`. The following assertions pass, but the assertions for computed properties do not pass. As if they are not updating after the await.

I then thought to try removing the `await` and creating a `.then()` function to see if that works, and ran into this interesting issue. My test passes, but fails after within the `.then()` function.

![image](https://user-images.githubusercontent.com/5790104/180868487-9091155d-a6a1-4905-9b39-e4747992c988.png)

I believe this is similar to #1692

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-ef3jdp?file=test/computed.test.js

This should create a quick Vite app with Vue 2.7 and Vitest.

Once created, the test runner should fire, and you will see that 1 test passes, and 1 test fails. They check the exact same stuff, just have to deal with the `await` vs `then`

### System Info

```shell
Mac M1
Vite:    2.9.14
Vitest:  0.18.1
Node:    18.6.0 / 16.16.0 (I tried on both)
Vue:     2.7.7 (cannot upgrade to v3 yet :/ )
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is correct behaviour. Code inside then is running after test is done, so we can’t catch it. Return a promise from test, or use await.
