### ISSUE TITLE
Vue test fails - computed property not updating

### ISSUE THREAD

**Issue by kevmul** [vitest-dev/vitest#1724]
### Describe the bug

It seems that the computed properties do not update when updating props within a Vue component. 

I like to have a test start at one state, then update to create a next state, and test against this new state. Lets say we have a component that shows a div when a computed property returns true, and the computed property is checking a passed in prop of `limit`.

When we start with a `limit` of `0`, we do not see the div. Then when we update the prop to be `100` we should see the div.

This doesn't work with `Vitest` as it did with `Jest`

### Reproduction

I have created a quick demo of the issue in `StackBlitz`
https://stackblitz.com/edit/vitest-dev-vitest-fnwjqo?file=test/computed.test.js

There are three tests, the first two are tests broken out to prove the div shows up in both situations.

The third test fails as it is dependant on the computed property to change as the passed in prop does. 

### System Info

```shell
Mac M1
Vite:    2.9.14
Vitest:  0.18.1
Node:    18.6.0 / 16.16.0 (I tried on both)
Vue:     2.7.7 (cannot upgrade to v3 yet :/ )
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kevmul** [comment]
So I wanted to know if this was fixed with Vue3, and I think it is. I recreated the exact same tests in stackblitz and the tests work. 

https://stackblitz.com/edit/vitest-dev-vitest-voeqg2?file=test/computed.test.js

The question is, is this a bug with vitest or vue-test-utils?

**Comment by nieyuyao** [comment]
I found that the reason is that the `vue` used by the `Demo.vue` is `vue.runtime.esm.js`, but the `vue-test-utils`uses `vue.runtime.common.js`.

**Comment by sheremet-va** [comment]
Yes, vue-test-utils@1.3.0 doesn't prove ESM entry. To force CJS Vue, you should use alias option:

```
test: {
  alias: [{ find: /^vue$/, replacement: "vue/dist/vue.runtime.common.js" }]
}
```
To fix overall problem, vue-test-utils need to release a version for Vue 2 with correct `exports` field.

**Comment by kevmul** [comment]
Thanks @sheremet-va This solved my problem!
