### ISSUE TITLE
vi.actualImport fails if module file path includes "/dist/"

### ISSUE THREAD

**Issue by behnoodk** [vitest-dev/vitest#1725]
### Describe the bug

Hi.

If I call `vi.importActual` for a yarn workspace that has  the main script outside of src folder, it fails to resolve the file. I have created a minimal repo to demonstrate this.

https://github.com/behnoodk/vitest-importactual

steps to reproduce:
1. `yarn install`
2. `yarn workspace @myorg/testsrv test`

imortActual works as expected for the package `@myorg/testpkg` but fails for `@myorg/testpkgts`. the error message printed is this:

```
 FAIL  index.test.ts [ index.test.ts ]
Error: Error: Cannot find module /Users/mohsen/Documents/projects/vitest-importactual/services/testsrv/Users/mohsen/Documents/projects/vitest-importactual/packages/testpkgts/dist/index.js imported from file:///Users/mohsen/Documents/projects/vitest-importactual/services/testsrv, file:///Users/mohsen/Documents/projects/vitest-importactual/services/testsrv/node_modules
```

So it's looking for the entrypoint of package in the wrong place.

I'd appreciate if someone more familiar with vitest could point me in the right direction.

### Reproduction

https://github.com/behnoodk/vitest-importactual

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) x64 Apple M1 Pro
    Memory: 123.96 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 3.2.0 - ~/.nvm/versions/node/v14.19.1/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by behnoodk** [comment]
I did some digging and the problem is that if the path to be imported includes `"/dist/"`, it will be considered an external module. This was introduced in this commit: 

https://github.com/vitest-dev/vitest/commit/bb77e4f88a590fe5c34a6e3864b0ce0e87a609fe

Relying just on this check gives us false positives. I'm not sure how to approach and fix this but thought this may help someone else to pick this up and create a fix.

**Comment by sheremet-va** [comment]
I am not sure what do you expect here? Your package has wrong/insufficient entry point. Even typescript fails to find it. If you want to use your original files, you can use `test.alias` option:

```ts
// vitest.config.ts
{
  test: {
    alias: [
       { find: /^@myorg/testpkg$/, replacement: 'path to wanted entry point' }, 
    ]
  }
}
```

You can also add `exports` field with `development` condition:

```json
{
  "//": "package.json",
  "exports": {
    ".": {
      "development": "./src/index.ts"
    }
  }
}
```
