### ISSUE TITLE
types: wrong generic type params in type `MockedClass`

### ISSUE THREAD

**Issue by Tanimodori** [vitest-dev/vitest#1730]
### Describe the bug

The primary part of `MockedClass<T>` is `MockInstance<InstanceType<T>, ConstructorArgs<T>>`

https://github.com/vitest-dev/vitest/blob/34b06dba5927ebc217fc97da56560357c1e161f6/packages/vitest/src/integrations/spy.ts#L101-L106

But I think `MockInstance<A, R>` which is primarily `SpyInstance<TArgs, TReturns>` is a kind of mock `new (...Targs)=>TReturns`, should `MockedClass<T>` be `MockInstance<ConstructorArgs<T>, InstanceType<T>>` instead of `MockInstance<InstanceType<T>, ConstructorArgs<T>>`?

https://github.com/vitest-dev/vitest/blob/34b06dba5927ebc217fc97da56560357c1e161f6/packages/vitest/src/integrations/spy.ts#L39-L56

https://github.com/vitest-dev/vitest/blob/34b06dba5927ebc217fc97da56560357c1e161f6/packages/vitest/src/integrations/spy.ts#L58

### Reproduction

n/a

### System Info

```shell
n/a
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Yes, I think you are right. PR welcome.
