### ISSUE TITLE
Partial types for mocked return values

### ISSUE THREAD

**Issue by jfrs** [vitest-dev/vitest#1739]
### Clear and concise description of the problem

As a developer using Vitest I want to be able to mock only certain properties or functions of a module so that I can keep the type checking from TypeScript but only mock what I need for the test.

Currently when using `vi.mocked` and `mockReturnValue` with TypeScript it will expect a fully compatible type, but most of the time since you're mocking you only need some of the properties to be set.

This is an issue I face a lot when mocking but I haven't found a proper solution, the most common solution to this seems to be casting to `unknown` and but then you lose the type checking.

### Suggested solution

There's a solution suggested [here](https://github.com/kulshekhar/ts-jest/issues/1065) but I think just changing the return type to be a `Partial<T>` would work?

(Copied suggestion just in case:)

```ts
type DeepPartial<T> = {
    [P in keyof T]?: T[P] extends Array<infer U>
        ? Array<DeepPartial<U>>
        : T[P] extends ReadonlyArray<infer U>
            ? ReadonlyArray<DeepPartial<U>>
            : DeepPartial<T[P]>
};

type PartialReturnType<T extends MockableFunction> = 
    ReturnType<T> extends Promise<infer U>
        ? Promise<DeepPartial<U>>
        : ReturnType<T> extends Array<infer P>
            ? Array<DeepPartial<P>>
            : DeepPartial<ReturnType<T>>;

interface MockWithArgs<T extends MockableFunction> extends jest.MockInstance<PartialReturnType<T>, ArgumentsOf<T>> {
    new (...args: ConstructorArgumentsOf<T>): T;
    (...args: ArgumentsOf<T>): PartialReturnType<T>;
}
```

### Alternative

I use `@ts-ignore` so I can keep the types but disable the error.

There's also [this](https://github.com/vitest-dev/vitest/issues/351) related issue but it solves a different problem I think.

### Additional context

My current use case for this is mocking Pinia stores:

```ts
vi.mocked(useAuthStore).mockReturnValue({
  loggedIn: true
});
```
This will produce an error because the return value is missing a lot of Store properties and functions.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I don't see us "just" changing type to partial, since someone might rely on it. 

I am not against `partiallyMocked` utility function thought.
