### ISSUE TITLE
[0.20.2]: Tets fails if importing `tslib`

### ISSUE THREAD

**Issue by thebuilder** [vitest-dev/vitest#1753]
### Describe the bug

After upgrading to v0.20.x, most of my tests are now failing with:

```
SyntaxError: Named export '__assign' not found. The requested module 'tslib' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'tslib';
const { __assign } = pkg;
```

It's caused by framer-motion using [tslib](https://github.com/microsoft/tslib). The package does include an [exports field](https://github.com/microsoft/tslib/blob/main/package.json#L29-L36) and module support, so a bit weird why this is popping up. Thinking it's related to how node modules are resolved now after #1673.

### Reproduction

The issue can be replicated by importing `<framer-motion>` in a test file. 
https://stackblitz.com/edit/vitest-dev-vitest-ue9bu2?file=test/App.test.tsx

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    @vitejs/plugin-react: ^1.3.2 => 1.3.2 
    vite: ^2.9.9 => 2.9.14 
    vitest: 0.20.2 => 0.20.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by metonym** [comment]
I'm seeing a similar error after upgrading to vitest^0.20 when using `@testing-library/user-event` which has `@testing-library/dom` as a dependency.

```txt
SyntaxError: Named export 'createEvent' not found. The requested module '@testing-library/dom' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@testing-library/dom';
const { createEvent: createEventBase } = pkg;
```

**Comment by saharbit** [comment]
I'm experiencing a similar issue in the latest version(0.20.2), on some very basic tests

**Comment by thebuilder** [comment]
Looks like tslib is not following the ESM standard correctly, and guessing it's the same issue with other packages. 😑
https://github.com/microsoft/tslib/issues/173

**Comment by thebuilder** [comment]
Setting [deps.registerNodeLoader](https://vitest.dev/config/#deps-registernodeloader) to `false` (to skip the new Node logic) allows the test to run again.

**Comment by sheremet-va** [comment]
Yes, for now you can opt-out of this behaviour with `deps.registerNideLoader`. I guess we can hardcode tslib for now, since it's used in TypeScript extensively, but the project seems to be abandoned according to linked issues.

**Comment by sheremet-va** [comment]
> I'm experiencing a similar issue in the latest version(0.20.2), on some very basic tests

Please, create a reproduction, if the issue doesn't involve tslib.

**Comment by ggowtham67** [comment]
Getting similar issue with CJS export. In my case it's with one of [cheerio](https://www.npmjs.com/package/cheerio) packages's dep.

```bash
SyntaxError: Named export 'AttributeAction' not found. The requested module 'css-what' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'css-what';
const { AttributeAction, SelectorType } = pkg;
```

Reproduction: https://github.com/ggowtham67/vitest-v0.20.2-cjs-broken-export-repro

**Comment by revmischa** [comment]
Getting this as well
```
SyntaxError: Named export 'v4' not found. The requested module 'uuid' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
```

**Comment by metonym** [comment]
Upgrading vitest to v0.21.0 now solves the issue.

`deps.registerNodeLoader` is now `false` by default so it can be removed from the config.

```diff
/** @type {import('vite').UserConfig} */
export default {
  test: {
-   registerNodeLoader: false,
  },
};
```

**Comment by sheremet-va** [comment]
> Upgrading vitest to v0.21.0 now solves the issue.

Technically this PR should also work with `registerNodeLoader` enabled, but performance might suffer for now.
