### ISSUE TITLE
Custom Error Serializer

### ISSUE THREAD

**Issue by altano** [vitest-dev/vitest#1762]
### Describe the bug

I'm trying to write a custom snapshot serializer for `Error`. I want to strip an absolute path in the error so that the test is portable beyond my local dev machine. The error is being snapshotted with code that looks like:

```
expect(fn).rejects.toThrowErrorMatchingSnapshot();
```

By the time the `Error` makes it to my custom serializer it is a `string`, so I need to match on `string` values in my serializer. This isn't currently easy to do without causing infinite recursion, because the `printer` passed to my serializer results in my serializer being called again.

An example of a generic string serializer is:

```
expect.addSnapshotSerializer({
  serialize(val, config, indentation, depth, refs, printer) {
    return `Pretty: ${printer(val, config, indentation, depth, refs)}`;
  },
  test(val) {
    return typeof val === 'string';
  },
});
```

To avoid the infinite recursion we can do a workaround to detect when our snapshot serializer has already run, to avoid reentry:
```
expect.addSnapshotSerializer({
  serialize(val, config, indentation, depth, refs, printer) {
    return `Pretty: ${printer(val, config, indentation, depth, refs)}`;
  },
  test(val) {
    return typeof val === 'string' && !val.startsWith('Pretty');
  },
});
```

What I expect to happen instead:

`printer(...)` should run all serializers OTHER than the one we're currently in.

### Reproduction

https://stackblitz.com/edit/node-wtwbyd?file=test-setup.js,vite.config.js,test%2Fstring.test.ts,test%2Ferror.test.ts

When the tests run they will fail with the error `PrettyFormatPluginError: Maximum call stack size exceeded`

### System Info

```shell
From stackblitz:


  System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    vite: ^2.7.10 => 2.7.10 
    vitest: ^0.0.136 => 0.0.136 
```
```


### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
We don't control this API. Please, check pretty-format repo.
