### ISSUE TITLE
vitest never completes when module exports a function named `then`

### ISSUE THREAD

**Issue by philipnilsson** [vitest-dev/vitest#1767]
### Describe the bug

Create a file `tmp.ts` containing the following

```ts
export function then() {
  return null;
}
```

in folder `__test__` create `tmp.test.ts` containing the following

```ts
import { test } from "vitest";
import { then } from "../tmp";

test("resolve", () => {
  then;
});
```

vitest will never complete running. Renaming the export to e.g. `then_` causes vitest to complete as expected.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-seut9k?file=tmp.ts,test%2Ftmp.test.ts&initialPath=__vitest__

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 8.04 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.3
  npmPackages:
    vitest: ^0.18.1 => 0.18.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ChpShy** [comment]
This bug is because `vite-node`'s `directRequest` is an async function, and the exports content like
```javascript
exports = {
    [Symbol.toStringTag]:  'Module',
    then: function() { ... }
}
```
so, async will run `exports.then` then get the `pending` status and the error exports content.

line https://github.com/vitest-dev/vitest/blob/main/packages/vite-node/src/client.ts#L247

Curious how to solve it~

**Comment by sheremet-va** [comment]
Doesn't work in Native node either 🤔 

https://stackblitz.com/edit/node-2kwr6a?file=index.js,then.mjs

**Comment by ChpShy** [comment]
It is ok without await. Maybe result can be wrapperred by a function. e.g.
```javascript
return () => exports
```

But, it is terrible...

**Comment by nieyuyao** [comment]
An object with `.then` is treated as a Thenable, just like a Promise. The code below is ok. 🤔

```
export const then = (onFulfilled) => {
  onFulfilled(null);
};
```

**Comment by sheremet-va** [comment]
This is expected behavior. Native Node.js also doesn't finish `import`.

This might've worked before in Jest because it uses `require` when loading modules.
