### ISSUE TITLE
useFakeTimers not working with promise / setTimeout

### ISSUE THREAD

**Issue by will-stone** [vitest-dev/vitest#1772]
### Describe the bug

Hi 👋 

Firstly, thank you for all your work on this project. I'm trying out the inline tests at the moment, and they work really well in a utility library I'm building.

I've made a very simple `sleep` function which is just a wrapper around a promised `setTimeout`. I've found that the `useFakeTimers` isn't working as expected, so when the timers are advanced beyond when you'd expect the callback to be called, the spy is not identified as being called. Reproduction below.

Thanks,

Will.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-fx4gh6?file=source/sleep.ts

### System Info

```shell
From StackBlitz:

System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    vite: ^2.9.9 => 2.9.14 
    vitest: latest => 0.20.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I think you need to wait until the end of the event loop, if you are using Promises inside synchronous function. Try adding empty `await` to trigger it. Like this, for example:

```ts
  test('sleeps for given milliseconds', async () => {
    sleepWrapper(3000, callbackSpy);

    vi.advanceTimersByTime(1000);
    expect(callbackSpy).not.toBeCalled();

    await vi.advanceTimersByTime(2001);
    expect(callbackSpy).toHaveBeenCalledTimes(1);
  });
```

**Comment by will-stone** [comment]
That did it! Thank you @sheremet-va 🙂 

https://stackblitz.com/edit/vitest-dev-vitest-shuqa4?file=source/sleep.ts
