### ISSUE TITLE
Configuration option to allow empty test suites to pass

### ISSUE THREAD

**Issue by cartogram** [vitest-dev/vitest#1780]
### Clear and concise description of the problem

Similar to the `passWithNoTests` configuration option (which allows Vitest to pass if no tests are found), I am wondering if it would make sense to provide configuration for Vitest to pass when it finds test suites with no tests. I am experiencing a need for this option when experimenting with in-source testing, where some source files have tests in them and some do not.

I've changed the `include` option to find a number of component files (actual source files within my project), some of these have a test within the same file (below the component) but some do not. The files included need to have a test in them or Vitest will fail with `Error: No test found in suite`. 

### Suggested solution

We can add a `passSuitesWithNoTests` option that would enable Vitest to pass if a tests suite (a file matched by the `include`) is empty.

### Alternative

Modify the configuration of the existing `passWithNoTests` option to support `boolean | 'suite' | 'all'. 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by cartogram** [comment]
Update, I was able to accomplish this with the `importSource` option instead. 👍

**Comment by Gregoor** [comment]
Heya @cartogram, can you describe what `importSource`? I can neither find it in this repo nor on the wider web. Thanks!

**Comment by taylor1791** [comment]
@Gregoor I believe that he meant the `includeSource` option. This option is documented in the [in-source testing](https://vitest.dev/guide/in-source.html), but is only mentioned in passing in the [config reference](https://vitest.dev/config/).
