### ISSUE TITLE
No test found after encapsulate

### ISSUE THREAD

**Issue by Sepush** [vitest-dev/vitest#1783]
### Describe the bug

Error: No test found in suite #getCheckedKeys (async cascade)
![image](https://user-images.githubusercontent.com/39197136/182763669-2dfe3bd2-8481-45c6-912e-b6be76fbade8.png)

### Reproduction

https://github.com/Sepush/treemate/tree/vi
then check this test suite
`src/__tests__/async-check.spec.ts > async-check > #getCheckedKeys (async cascade)`
```ts
export function expectCheckedStatusSame (
  status1: {
    checkedKeys: Key[]
    indeterminateKeys: Key[]
  },
  status2: {
    checkedKeys: Key[]
    indeterminateKeys: Key[]
  }
): void {
  expect(Array.from(status1.checkedKeys).sort()).toEqual(
    Array.from(status2.checkedKeys).sort()
  )
  expect(Array.from(status1.indeterminateKeys).sort()).toEqual(
    Array.from(status2.indeterminateKeys).sort()
  )
}
```
```ts
describe('#getCheckedKeys (async cascade)', () => {
    const treeMate = createTreeMate(asyncCascadeTree)
    expectCheckedStatusSame(
      treeMate.getCheckedKeys(['4'], { cascade: true, checkStrategy: 'child' }),
      {
        checkedKeys: ['4'],
        indeterminateKeys: ['0', '2']
      }
    )
  })
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 833.58 MB / 7.89 GB
  Binaries:
    Node: 16.14.0 - ~\AppData\Local\fnm_multishells\6948_1659584657685\node.EXE
    Yarn: 1.22.15 - ~\AppData\Local\fnm_multishells\6948_1659584657685\yarn.CMD
    npm: 8.3.1 - ~\AppData\Local\fnm_multishells\6948_1659584657685\npm.CMD
  Browsers:
    Chrome: 103.0.5060.134
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.77)
  npmPackages:
    vitest: ^0.20.3 => 0.20.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You don't have `it`/`test` block inside a suite (`describe`).
