### ISSUE TITLE
'vue-demi' causes errors when importing (only the .mjs file breaks it)

### ISSUE THREAD

**Issue by dmix** [vitest-dev/vitest#1788]
### Describe the bug

I get this error whenever I import a Pinia store into my test:

```shell
SyntaxError: The requested module 'vue-demi' does not provide an export named 'computed'
 ❯ ../../async /Users/dmix/dev/callpixels/app/javascript/__tests__/stores/target_options_test.ts:1:256

```

Also got a more detailed version with some tweaks:

```shell
SyntaxError: Named export 'computed' not found. The requested module 'vue-demi' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vue-demi';
const { getCurrentInstance, inject, toRaw, watch, unref, markRaw, effectScope, ref, isVue2, isRef, isReactive, set, onUnmounted, reactive, toRef, del, nextTick, computed, toRefs } = pkg;

 ❯ ../../async /Users/dmix/dev/callpixels/app/javascript/__tests__/stores/target_options_test.ts:1:256
```

This is the code in the test file (removing pinia stuff resolves the error)

```javascript
import { setActivePinia, createPinia } from 'pinia'
import {
    useTargetOptionStore,
    TargetOptionState,
} from '../../stores/target_options'

describe('TargetOption Store', function() {
    beforeEach(() => {
        setActivePinia(createPinia())
        store = useTargetOptionStore()
    })
    ...

```

This is not a new issue, others have managed to solve it by explicitly add .mjs settings to webpack:

https://github.com/vueuse/vueuse/issues/718#issuecomment-946508863

The problem is that I'm using Vite and not webpack, so I dont know how to apply a similar config setting.

I resolved the issue by simply deleting the .mjs file `rm ./node_modules/pinia/dist/pinia.mjs`, this is fine because there's also the exact same .js version of this file

Is there a way to fix this mjs issue?

### Reproduction

My full vite.config.ts file:

https://gist.github.com/dmix/780c81495d3fdfdf140e7cbe1e95e4c0

### System Info

```shell
MacOS
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You can disable this behaviour with `test.deps.registerNodeLoader: false` for now.

**Comment by dmix** [comment]
@sheremet-va thanks but that didnt seem to stop the error:

I added this to my `vite.config.ts`:

```
    test: {
        globals: true,
        environment: 'jsdom',
        include: ['__tests__/**/*_{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
        deps: {
          registerNodeLoader: false,
        }
    },
```
