### ISSUE TITLE
Named export is not defined when used in destructuring object

### ISSUE THREAD

**Issue by inakiabt** [vitest-dev/vitest#1791]
### Describe the bug

Looks like imported named exports are not being correctly transformed when used in object desctructuring.

```javascript
// types.js
export const NAME = 'test';
```

```javascript
// helper.js
import { NAME } from './types';

console.log('NAME', NAME);
export const run = ({ [NAME]: result }) => result;
```

When running I get this error:
```
 FAIL  test/helper1.spec.js > should 
ReferenceError: NAME is not defined
 ❯ Module.run test/helper1.js:4:31
      2| 
      3| console.log('NAME', NAME);
      4| export const run = ({ [NAME]: result }) => result;
       |                               ^
      5| 
```

This is the transform result of my helper.js file:
![image](https://user-images.githubusercontent.com/606852/182934954-9f1fc9a0-f189-41f8-aaae-d81146663bc1.png)

As can be seen, `NAME` isn't not correctly referenced.

_Originally posted by @inakiabt in https://github.com/vitest-dev/vitest/discussions/1789_

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-eg6hlk?file=test%2Fhelper1.js

There are 3 tests. All of them tests a simple function that uses an imported constant to destruct an object and return the result.

for test 1 and 2, the constant (NAME) seems to be "not defined" to vitest.
for test 3, I use a different the constant (n) that seems to be defined but it doesn't have the correct value when running the test.

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 795.55 MB / 16.00 GB
    Shell: 5.1.16 - /usr/local/bin/bash
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 102.0.1
    Safari: 15.6
  npmPackages:
    vite: ^2.9.14 => 2.9.14 
    vitest: ^0.20.3 => 0.20.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Open an issue in Vite repository, VItest doesn't do any transformations on its own.

**Comment by inakiabt** [comment]
🤦

**Comment by inakiabt** [comment]
@sheremet-va While I was opening the issue in vite repository, I realized that running it with vite works.
So I think it could be a vitest issue, couldn't be?

Here's an example:
https://stackblitz.com/edit/vitejs-vite-euhfit?file=main.js

**Comment by sheremet-va** [comment]
No, this is error with Vite SSR. Vite doesn't do this transformations for browser.

**Comment by inakiabt** [comment]
I see. How can I reproduce it using just vite? I want to create an example reproducing the error to create the issue

**Comment by sheremet-va** [comment]
> @sheremet-va I see. How can I reproduce it using just vite? I want to create an example reproducing the error to create the issue

You can give the same reproduction. Vitest internally uses Vite's `server.ssrTransform`.

**Comment by sheremet-va** [comment]
Here is the more generalized reproduction tho: https://stackblitz.com/edit/node-pmokln?file=index.mjs
