### ISSUE TITLE
Spy in settimeout did not work

### ISSUE THREAD

**Issue by Sepush** [vitest-dev/vitest#1794]
### Describe the bug

during I migrate test from jest to vitest
I some component meet the following error

![image](https://user-images.githubusercontent.com/39197136/182995385-db9e2bb6-7ff5-4bc2-9a8a-a71e5b3fa85c.png)

and it did not figure out which test failed I think this should be improve

### Reproduction

https://github.com/Sepush/naive-ui/tree/vi

clone this branch 

pnpm i

the fllowing components tests meet this issue alert input radio tree

// could pass the component name to only run the related Tests
pnpm test alert

I have try to debug found this issue 
alert cause by `src/alert/tests/Alert.spec.ts > n-alert > should trigger callback when closed`
the last test case `onAfterLeave` didn't been called
![image](https://user-images.githubusercontent.com/39197136/182996866-06ef2fa0-1e9a-45d0-9d5f-63854ddd97b6.png)

input is cause be `src/input/tests/input.spec.ts > n-input> should work with `blur` `focus` `select` methods`

![image](https://user-images.githubusercontent.com/39197136/182996923-e7e3facb-0489-4a40-9569-187a8767e181.png)

all of this works on jest

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 833.58 MB / 7.89 GB
  Binaries:
    Node: 16.14.0 - ~\AppData\Local\fnm_multishells\6948_1659584657685\node.EXE
    Yarn: 1.22.15 - ~\AppData\Local\fnm_multishells\6948_1659584657685\yarn.CMD
    npm: 8.3.1 - ~\AppData\Local\fnm_multishells\6948_1659584657685\npm.CMD
  Browsers:
    Chrome: 103.0.5060.134
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.77)
  npmPackages:
    vitest: ^0.20.3 => 0.20.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You cannot put code inside setTimeout like that. This code is running after test is completed. If you want for some reason use setTimeout, return a promise from test:

```
return new Promise(resolve => {
  setTimeout(() => {
    expect().toBe()
    resolve()
  })
})
```

**Comment by Sepush** [comment]
> You cannot put code inside setTimeout like that. This code is running after test is completed. If you want for some reason use setTimeout, return a promise from test:
> 
> ```
> return new Promise(resolve => {
>   setTimeout(() => {
>     expect().toBe()
>     resolve()
>   })
> })
> ```

I try to refactor it to async await or promise but not work
![image](https://user-images.githubusercontent.com/39197136/182999867-2a3f8147-5e2d-40cf-a74e-0a3f5b191247.png)

**Comment by Sepush** [comment]
have tried with stil fail
```ts    
await flushPromises()
expect(handleOnAfterLeave).toBeCalled()
```

**Comment by sheremet-va** [comment]
Do your tests work with done callback? https://jestjs.io/docs/asynchronous#callbacks

Please, read carefully. It explains why you shouldn’t test code like you did.

**Comment by Sepush** [comment]
> Do your tests work with done callback in Jest? https://jestjs.io/docs/asynchronous#callbacks
> 
> Please, read carefully. It explains why you shouldn’t test code like you did.

I have read it.Yes we shouldn't test code this way.and I will try to find the proper way to test Transition onAfterLeave hook.
