### ISSUE TITLE
Filter tests by filename in watch mode

### ISSUE THREAD

**Issue by netcoding87** [vitest-dev/vitest#1797]
### Clear and concise description of the problem

As a developer using Vitest I want to have the option to filter test by filename in watch mode so that I can simply run only the test file I am currently working on and do not have to execute all test suites. 

I am coming from jest where I really often used this filter option (jest-watch-typeahead/filename) and it is very helpful for me.

### Suggested solution

Add a filter option like [jest-watch-typeahead/filename](https://github.com/jest-community/jest-watch-typeahead)

### Additional context

vitest
<img width="354" alt="image" src="https://user-images.githubusercontent.com/54022880/183005909-0fde9d48-f62a-44be-b25e-57b247248a47.png">

jest
<img width="369" alt="image" src="https://user-images.githubusercontent.com/54022880/183005947-86a02414-9743-4a2e-9f00-8d1434536b3c.png">

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Benoit-Vasseur** [comment]
Hello,

You can filter the tests when you launch vitest => https://vitest.dev/guide/filtering.html#cli
But yes the option "filter by filename" is misssing in watch usage

**Comment by netcoding87** [comment]
Yes, I saw that option. But as mentioned from yourself it is not available in watch mode :(

> It could override the pattern given at launch ?

Hmm... That is a usecase I did not consider. I do not know how exactly that should work 🤔

**Comment by zvolcsey** [comment]
Hey, it is an intresting task. I am taking a stab at it. 😀
