### ISSUE TITLE
Types: Better local test context support

### ISSUE THREAD

**Issue by Tanimodori** [vitest-dev/vitest#1798]
### Clear and concise description of the problem

I use [test context](https://vitest.dev/guide/test-context.html#extend-test-context) quite often for setting up same fixtures for test. Let's say we have the following test spec code: 

```ts
describe('Test A', () => {
  beforeEach((context) => {
    context.foo = 'foo';
  });
  it('Test A - SubTest A', (context) => {
    expect(context.foo.toUpperCase()).toBe('FOO');
  });
});

describe('Test B', () => {
  beforeEach((context) => {
    context.bar = 'bar';
  });
  it('Test B - SubTest A', (context) => {
    expect(context.bar.toUpperCase()).toBe('BAR');
  });
});

```

According to the official docs, We need to aggregate the `TestContext` type:

```ts
declare module 'vitest' {
  export interface TestContext {
    foo?: string;
    bar?: string;
  }
}
```

This introduces some problems, which are caused by the fact that different tests have different context but we cannot do a "local aggregation", so the `TestContext` must be the supertype of all contexts. Those problems are:

* Introducing unnecessary optional properties. I have to check those optional properties in each test, which brings unnecessary code for assertions (`!`), nullish operators (`?.`), or type guards. If I made them required, they become required for all tests which may cause typos (e.g. it is legal to write `context.foo` in "Test B - SubTest A" but we don't set it up yet)
* Type interference.  What if we have two `context.foo` in different tests but with different types? We could write `context.testA.foo` but it seems ugly.

So my question here is that is it possible to declare "local test context" rather than a global context?

As I search the typings, there's a `ExtraContext` passing around. But the `test` has a fixed `{}` as `ExtraContext` so it won't works.

### Suggested solution

There could be a solution for add some TypeScript helpers, without changing the underlying js code while keep it compatible for global context as following. [(playground)](https://www.typescriptlang.org/play?#code/C4TwDgpgBAwgFgQwJYDsECMA2EBiBXFAY2CQHsUAeAFSggA9gIUATAZyleACdUBzAGig4AfFAC8QqADIoAbwBQUKAG0A1hBBRUUKgF0AXLESoM2fERLlqgkfIC+8+akZcAZgkLQqETjHKMGOShXUlJDFDwAW3QILigHUEgoAEEAd2RgUwhqUQkaAB8oAAUuUkikVggAGSR1HIBuR0SvH2BzYjJKAFEGLgQ-FADgcTk7XKgACkJ-emBDb18ZwJke7n6l4ABKcVE0jKyKBBQQUUKAN1IkZkbmo2Q0LAgF4GSigEkKVb6BoZHZMZG8HuWXalkoAHJpkQ8FwuExgOCoIVweRMCBEcjWKokGAMVBwcBSMxSHjwe4kJhWODBIooNRaAwmGwoF91oNZiNWT9ZsIJmhIhB9JweCgBMEUAB+eatUGdHKCEgC0h4YBSqARaKxbZiUQXK7yYSOZyxdyeKBVUiEBCYZ7cwKyKDoBBcQzCvjxRwAek9OlarzeUFSfTA7CBJkez39gjKSGGcFiEHkzAghEwzugUM4UEYnEMYYe2Ej7wo-0N8hzwAmBNaUChQ2pkzrs21ogUSluduAVHA0AkzVIrlrG0aSm9vsW7IY9k2TVaFAtVptrU7vOrWabDAbUw2LbktI7G27ST7PYHQ8nwBHUDHto20nNlutt4v08c5daADpCcSP1icfPHyXCchlXCtz3rQRtwvXc22zHtYEPeCT0gM8N0vWkb2XO8ZAXJ8sJfOwZyAA)

```ts
type ChainableFunction<T extends string, F> = F & {
  [key in T]: ChainableFunction<T, F>
}

interface TestContext { foo: number }
type Awaitable<T> = T | PromiseLike<T>;

type TestFunction<ExtraContext = {}> = (context: TestContext & ExtraContext) => Awaitable<any> | void;
type ChainableTestAPI<ExtraContext = {}> = ChainableFunction<'concurrent' | 'only' | 'skip' | 'todo' | 'fails', 
  <T extends ExtraContext = ExtraContext>(name:string, fn?: TestFunction<T>, timeout?: number) => void
>

interface LocalTestContext { bar: string }

// TestAPI wraps ChainableTestAPI, omit here
declare const test: ChainableTestAPI<{}>

test('test context', (context) => {
  type ContextType = typeof context;
  // TestContext
})

test<LocalTestContext>('test context', (context) => {
  type ContextType = typeof context;
  // TestContext & LocalTestContext
})


test.todo.skip<LocalTestContext>('test context', (context) => {
  type ContextType = typeof context;
  // TestContext & LocalTestContext
})

```

The story is the same for `beforeEach` and `afterEach`.

### Alternative

Alternatively, I have to use type casts to shim the `LocalTestContext` to `{}`.

```ts
// extract BeforeEach hooks
type BeforeEachFunction<T = unknown> = Parameters<typeof beforeEach>[0] extends (
  context: infer C,
  ...args: infer P
) => infer R
  ? (context: C & T, ...args: P) => R
  : never;

describe('Test A', () => {
  interface LocalTestContext {
    foo: string;
  }
  beforeEach(((context) => {
    context.foo = 'foo';
  }) as BeforeEachFunction<LocalTestContext> as BeforeEachFunction);
  it('Test A - SubTest A', ((context) => {
    expect(context.foo.toUpperCase()).toBe('FOO');
  }) as TestFunction<LocalTestContext> as TestFunction);
});

describe('Test B', () => {
  interface LocalTestContext {
    bar: string;
  }
  beforeEach(((context) => {
    context.bar = 'bar';
  }) as BeforeEachFunction<LocalTestContext> as BeforeEachFunction);
  it('Test B - SubTest A', ((context) => {
    expect(context.bar.toUpperCase()).toBe('BAR');
  }) as TestFunction<LocalTestContext> as TestFunction);
});
```

Although the type of `context` is correct (`TestContext & LocalTestContext`) here, it seems less elegant than the proposed apporach.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by beorn** [comment]
This feature is great, but I am wondering if anyone has found a way to infer the type of LocalContext based on the return-type of beforeEach?  Would that be possible with a slightly tweaked API, such as one where beforeEach and afterEach are provided as arguments to describe instead of as functions called inside of the suite factory?  E.g.,

```ts
describe("my suite", {
  suite({ test }) {
    test("my test", ({expect}) => expect(false).toBe(true))
  },
  beforeEach(ctx) { ctx.extra = true; return ctx },
  /* afterEach: optional */
})
```

**Comment by Tanimodori** [comment]
@beorn We have no way to tell TypeScript that the types of context of `beforeEach` and `test` are same unless we explicitly specify the underlying types. You can use a context factory function, infer return types from it and pass it to vitest test functions.

**Comment by Tanimodori** [comment]
Some code example:

```ts
import { describe, test, expect, beforeEach, type TestContext } from 'vitest';

describe('Test', () => {
  // You want to avoid writing this
  interface LocalContext {
    extra: boolean;
  }

  function setupContext(ctx: TestContext) {
    // But you cannot extend TestContext by this
    ctx.extra = true;
    return ctx;
  }

  beforeEach<LocalContext>((ctx) => {
    setupContext(ctx);
  });

  test<LocalContext>('test', (ctx) => {
    expect(ctx.extra).toBe(true);
  });
});

describe('Test2', () => {
  // You can use Object.assign to extend TestContext
  // if you want to avoid writing interfaces
  function setupContext(ctx: TestContext) {
    const localContext = {
      extra: true,
    };
    return Object.assign(ctx, localContext);
  }
  type LocalContext = ReturnType<typeof setupContext>;

  beforeEach<LocalContext>((ctx) => {
    setupContext(ctx);
  });

  test<LocalContext>('test', (ctx) => {
    expect(ctx.extra).toBe(true);
  });
});
```

**Comment by beorn** [comment]
Simplest workaround I've found so far.  Example usage:

```ts
import { describe, beforeEach } from 'easy-typed-vitest'

describe("my suite", () => {
  const t = beforeEach((ctx) => ({ ...ctx, extra: true }))
  t.afterEach(({ extra }) => console.log("afterEach", extra))
  t.test("hello", ({ expect, extra }) => expect(extra).toBe(true))
})
```

Implementation:

```ts easy-typed-vitest.ts
/*
 * Convenient and type safe testing by wrapping beforeEach
 * - return value of beforeEach's function argument becomes the type of LocalContext
 * - returns an object with test/it/afterEach that have been typed for context
 */
import * as vitest from "vitest"
import type { Awaitable, TestContext } from "vitest"

export function beforeEach<T extends TestContext>(
  beforeEach: (ctx: TestContext) => Awaitable<T>
) {
  vitest.beforeEach(async (ctx) => {
    Object.assign(ctx, await beforeEach(ctx)) //eslint-disable-line
  })
  return {
    test: vitest.test<T>,
    it: vitest.test<T>,
    afterEach: vitest.afterEach<T>
  }
}

export const describe = vitest.describe
export const test = vitest.test
```

**Comment by beorn** [comment]
This also works, passing beforeEach and afterEach as arguments in one go:

```ts
export function withContext<
  F extends (ctx: TestContext) => Promise<any> | any //
>(
  beforeEachFn: F, //
  afterEachFn?: (ctx: Awaited<ReturnType<F>>) => Promise<void> | void
) {
  vitest.beforeEach<Awaited<ReturnType<F>>>(async (ctx) => {
    Object.assign(ctx, await beforeEachFn(ctx)) //eslint-disable-line
  })
  if (afterEachFn) vitest.afterEach<Awaited<ReturnType<F>>>(afterEachFn)
  return {
    test: vitest.test<Awaited<ReturnType<F>>>,
    it: vitest.test<Awaited<ReturnType<F>>>,
    afterEach: vitest.afterEach<Awaited<ReturnType<F>>>
  }
}
```
