### ISSUE TITLE
`.only` annotation is ignored

### ISSUE THREAD

**Issue by softwarerero** [vitest-dev/vitest#1811]
### Describe the bug

`.only` annotations are ignored and all tests are executed all the time. 

Also the API reference does not mention that `allowOnly` requires `threads` to be `false`.

### Reproduction

Sorry, I have no reproduction repository at hand but I use the following vitest.config.ts:

```
// <reference types="vitest" />
import { defineConfig } from 'vitest/config';
import { resolve } from 'path';

export default defineConfig({
  test: {
    environment: 'happy-dom',
    alias: {
      // as soon as we use an alias for '@', allowOnly stops working
      '@': `${resolve(__dirname, 'src')}`,
      vue: 'vue/dist/vue.esm-bundler.js',
    },
    globals: true,
    allowOnly: true,
    threads: false,
    // silent: true,
  },
});
```

### System Info

```shell
System:
    OS: macOS 12.2
  Binaries:
    Node: 18.1.0 - ~/.nvm/versions/node/v18.1.0/bin/node
    npm: 8.8.0 - ~/.nvm/versions/node/v18.1.0/bin/npm
  npmPackages:
    @vitejs/plugin-vue: ^2.3.3 => 2.3.3
    vite: ^2.9.9 => 2.9.9
    vitest: ^0.21.0 => 0.21.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> Also the API reference does not mention that allowOnly requires threads to be false.

It doesn't require that.

**Comment by softwarerero** [comment]
I'm not sure if I will have time for a reproduction repo, but here is a fix: https://github.com/vitest-dev/vitest/pull/1812

**Comment by softwarerero** [comment]
Here it can be reproduced: https://stackblitz.com/edit/vitest-dev-vitest-bvxzaf?file=test%2Fbasic.test.ts,vite.config.ts&initialPath=__vitest__

**Comment by sheremet-va** [comment]
> Here it can be reproduced: https://stackblitz.com/edit/vitest-dev-vitest-bvxzaf?file=test%2Fbasic.test.ts,vite.config.ts&initialPath=__vitest__

I think this is expected behaviour. Any flag (`.skip`, `.todo`, `.only`) marks tests inside that suite with the same flag, so you other tests only has `.only`.

Also, `.only` works only inside one spec file, and doesn't affect other file specs. If you want to test a single file, use `Vitest <filepath>`. You can also just edit a single file in watch mode, and it will rerun tests inside.

**Comment by softwarerero** [comment]
I see, I'm coming from a test envirnoment where `(.skip, .todo, .only)` would have effect on the whole test run and was expecting this to be the same in Vitest. Thanks for the explanation and laying out the alternatives, I close the ticket.
