### ISSUE TITLE
v0.21.0 introduces regression in module resolution

### ISSUE THREAD

**Issue by jonluca** [vitest-dev/vitest#1817]
### Describe the bug

Vite fails on resolving internal node module imports with 

```
Error: Cannot find module 'har-to-openapi/node_modules/@openapi-contrib/json-schema-to-openapi-schema/dist/mjs/const' imported from har-to-openapi/node_modules/@openapi-contrib/json-schema-to-openapi-schema/dist/mjs/index.js
```

when running tests on https://github.com/jonluca/har-to-openapi

### Reproduction

In this repo https://github.com/jonluca/har-to-openapi

Run `yarn install` then `yarn test` - it should pass all tests

Upgrade vitest from `0.20.3` to `0.21.0` - you should now see 

```
Error: Cannot find module 'har-to-openapi/node_modules/@openapi-contrib/json-schema-to-openapi-schema/dist/mjs/const' imported from har-to-openapi/node_modules/@openapi-contrib/json-schema-to-openapi-schema/dist/mjs/index.js
```

### System Info

```shell
Ok to proceed? (y) y

  System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 407.34 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.1 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 102.1.39.120
    Chrome: 104.0.5112.79
    Firefox: 103.0
    Safari: 15.6
  npmPackages:
    vitest: ^0.21.0 => 0.21.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jonluca** [comment]
```typescript
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    dir: "test",
    watch: false,
    threads: false,
    testTimeout: 5000,
    isolate: false,
    passWithNoTests: true,
    reporters: ["verbose"],
    coverage: { reporter: ["lcov", "html", "text"] },
    deps: {
      fallbackCJS: true,
      registerNodeLoader: true,
    },
  },
});

```

setting `registerNodeLoader: true` to true fixes it

**Comment by sheremet-va** [comment]
This is not a regression. `json-schema-to-open-api-schema` has wrongly bundled esm (imports have to have an extension in Node). 

`registerNodeLoader` is mean to fix it, but it can also break your imports, so you should enable it on your own risk for now.

**Comment by jonluca** [comment]
Ah that makes sense. I wrote the new updates to that package so I'll update it as well. Thanks for the context
