### ISSUE TITLE
report with the call stack

### ISSUE THREAD

**Issue by Sepush** [vitest-dev/vitest#1831]
### Describe the bug

did not report the call stack and point out which file test case line cause the error

### Reproduction

![image](https://user-images.githubusercontent.com/39197136/183829464-f8b29f72-8a89-4306-94d9-c4fc3e0b51cc.png)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
    Memory: 833.58 MB / 7.89 GB
  Binaries:
    Node: 18.7.0 - ~\AppData\Local\fnm_multishells\6948_1659584657685\node.EXE
    Yarn: 1.22.15 - ~\AppData\Local\fnm_multishells\6948_1659584657685\yarn.CMD
    npm: 8.3.1 - ~\AppData\Local\fnm_multishells\6948_1659584657685\npm.CMD
  Browsers:
    Chrome: 103.0.5060.134
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.77)
  npmPackages:
    vitest: ^0.20.3 => 0.20.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Unhandled errors cannot point to test, because they are "Unhandled", they happen outside of test. Stacktrace should be visible tho.

**Comment by Sepush** [comment]
> Unhandled errors cannot point to test, because they are "Unhandled", they happen outside of test. Stacktrace should be visible tho.

got it

**Comment by Sepush** [comment]
> Unhandled errors cannot point to test, because they are "Unhandled", they happen outside of test. Stacktrace should be visible tho.

how about point out which file I think this is possible
