### ISSUE TITLE
Publish `vitest/globals` under `@types` scope

### ISSUE THREAD

**Issue by sagargurtu** [vitest-dev/vitest#1845]
### Clear and concise description of the problem

`vitest/globals` needs to be added to the `"types"` field in `tsconfig.json` to get TypeScript working with the global APIs

```
// tsconfig.json
{
  "compilerOptions": {
    "types": ["vitest/globals"]
  }
}
```

However, this overrides the default behavior of TypeScript and all visible `@types` packages are no longer automatically included in the compilation. With a project relying on a lot of `@types` packages, each one now has to be specified individually which is a bad developer experience.

For context, I'm migrating from Jest which already has a `@types` scoped package and it never had to be explicitly added to `tsconfig.json`.

### Suggested solution

Publish `vitest/globals` type definitions under `@types/` scope.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Globals are optional, so we can't enable global types by default.

**Comment by antfu** [comment]
You may also use type comments like:

```ts
/// <references types="vitest/globals"/>
```

As @sheremet-va mentioned, globals are optional, and this is something we intended to make an opt-in.

**Comment by DevDengChao** [comment]
I still feel the pain migrating from jest to vitest for each existing project: I have to create a `vitest.config.js` and update the `tsconfig.js` to enable global functions.

While the steps are quite simple when migrating from mocha to jest :
```diff
- "test": "mocha"
+ "test": "jest"
```
