### ISSUE TITLE
Nesting `expect.objectContaining` results in Eslint Typescript errors

### ISSUE THREAD

**Issue by narthur** [vitest-dev/vitest#1855]
### Describe the bug

`expect.objectContaining` returns type `any`, resulting in Eslint TypeScript errors when it's nested within itself.

### Reproduction

Open reproduction:

https://stackblitz.com/edit/vitest-dev-vitest-eisbmu?file=test/suite.test.ts

Open a new terminal and run:

`npx eslint .`

Observe error:

```
/home/projects/vitest-dev-vitest-eisbmu/test/suite.test.ts
  19:9  error  Unsafe assignment of an `any` value  @typescript-eslint/no-unsafe-assignment
```

Offending test was added to the end of `suite.test.ts`.

### System Info

Reproduction:

```shell
❯ npx envinfo --system --npmPackages '{vitest,vite,@vitejs/*}' --binaries --browsers
success Install finished in 1.109s


  System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    vite: latest => 3.0.7 
    vitest: latest => 0.21.1 


~/projects/vitest-dev-vitest-eisbmu
```

Local:

```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 54.02 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/Library/pnpm/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 8.5.5 - ~/Library/pnpm/npm
    Watchman: 2022.07.04.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 104.0.5112.79
    Edge: 104.0.1293.54
    Firefox Developer Edition: 97.0
    Safari: 15.5
  npmPackages:
    vite: ^3.0.5 => 3.0.7 
    vitest: ^0.21.1 => 0.21.1 
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by narthur** [comment]
Would having `expect.objectContaining` return type `unknown` instead of `any` solve this issue?

**Comment by narthur** [comment]
For the time-being, this workaround solves the issue, even if it doesn't feel great:

```ts
expect(result).toEqual(expect.objectContaining({
  foo: expect.objectContaining({ bar: "baz" }) as unknown;
})
```

**Comment by sheremet-va** [comment]
Returning something else would only worsen DX unfortunately. Technically, `objectContaining` returns AsymmetricMatcher. It returns `any` instead, so it can be used like this and still satisfy TypeScript:

```ts
interface SomeValue {
  test: {
    name: string
    count: number
  }
}
const expected: SomeValue = {
  test: expect.objectContaining({
     name: '123'
  })
}
```
