### ISSUE TITLE
test.each's behaviour deviates from jest's

### ISSUE THREAD

**Issue by jf-paradis** [vitest-dev/vitest#1858]
### Describe the bug

As noted previously in https://github.com/vitest-dev/vitest/issues/1461, there are significant differences in `test.each()` between `vitest` and `jest`.

### Reproduction

1. When invoking `test.each()` with an array containing null, e.g. `test.each([null])`, the value will be processed as an array containing null (`[null]`) on Jest and converted to a `null` on Vitest.

Vitest used to return an empty array in that scenario, but this was changed in https://github.com/vitest-dev/vitest/pull/1462) and is enforced in this test:

```js
test.each([
  null,
  [null],
])('null is null', (value) => {
  expect(value).toBe(null)
})
```
https://github.com/vitest-dev/vitest/blob/main/test/core/test/each.test.ts#L11

However, the same test will fail in Jest:
```
 FAIL  core/test/each.test.ts
  ●  null is null
    expect(received).toBe(expected) // Object.is equality

    Expected: null
    Received: [null]

      43 |       [null],
      44 |     ])('null is null', (value) => {
    > 45 |       expect(value).toBe(null)
         |                     ^
      46 |     })
      47 |
      48 |     it.each([true, false])(

      at core/test/each.test.ts:45:21

Test Suites: 1 failed, 0 passed, 1 total
Tests:       1 failed, 0 skipped, 0 passed, 1 total
```

2. In addition, empty arrays are treated as empty arrays in Jest and `undefined` in Vitest:

```js
test.each([
  true, false,
  0, 1234,
  new Date(),
  [], {}, () => {},
])('primitives', (value) => {
  console.log(value, typeof value);
});
```

On Jest, the output is:
```
      true boolean
      false boolean
      0 number
      1234 number
      2022-08-15T21:52:20.000Z object
      [] object // <-- Difference
      {} object
      [Function (anonymous)] function
```

On Vitrest, the output is:
```
      true boolean
      false boolean
      0 number
      1234 number
      2022-08-15T21:52:20.000Z object
      undefined undefined // <-- Difference
      {} object
      [Function (anonymous)] function
```

### System Info

```shell
Binaries:
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Safari: 15.6
  npmPackages:
    vite: 3.0.x => 3.0.7 
    vitest: 0.21.x => 0.21.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by bartoszgolebiowski** [comment]
Should we align with jest behavior?

**Comment by williamthorsen** [comment]
Jest's behaviour is exactly what I'd expect, even if I didn't know anything about Jest.

What's the rationale for converting `[]` to `undefined` and `[null]` to `null`?

**Comment by bartoszgolebiowski** [comment]
I am waiting for confirmation from core team. I think we should align to jest behavior. @sheremet-va

**Comment by sheremet-va** [comment]
> I am waiting for confirmation from core team. I think we should align to jest behavior. @sheremet-va

let's align the behaivour.

**Comment by williamthorsen** [comment]
Clarification of Jest's behaviour (v29.0.3). This wasn't entirely as expected.

These tests pass:

```typescript
test.each([
  null,
])('value is null', value => {
  expect(value).toBeNull();
});

test.each([
  [null, null],
  [null, null],
])('if all cases are arrays of equal length, treats array elements as arguments', (value) => {
  // typeof value: null
  expect(value).toBeNull()
})
```

These tests fail:

```typescript
test.each([
  null,
  [null], // <-- FAIL: value is `[null]`
])('null value or null item is null', (value) => {
  // typeof value: null | any[]
  expect(value).toBeNull()
})

test.each([
  [null], // <-- FAIL: value is `[null]`
  null,
])('null value or null item is null', value => {
  // typeof value: null | any[]
  expect(value).toBeNull()
})

// ** FAIL: Test times out **
test.each([
  [null],
  [null, null],
])('', (value, _value?) => {
  expect(value).toBeNull();
});
```
