### ISSUE TITLE
more `mock` APIs

### ISSUE THREAD

**Issue by sheremet-va** [vitest-dev/vitest#186]
https://jestjs.io/docs/27.2/jest-object#mock-modules

extending #185

- [ ] ~~`jest.disableAutomock()`~~
- [ ] ~~`jest.enableAutomock()`~~
- [ ] ~~`jest.createMockFromModule()`/`jest..getMockFromModule(moduleName)`~~ -> use `vi.mock` or `vi.importMock`
- [x] ~~`jest.mock(moduleName, factory, options)`~~
- [ ] ~~`jest.doMock(moduleName, factory, options)`~~ - not supported, since static imports won't work then. if you need dynamic import, you can use `vi.importMock`. may support in the future if needed
- [x] ~~`jest.unmock(moduleName)` / `jest.dontMock(moduleName)`~~
- [ ] ~~`jest.setMock(moduleName, moduleExports)`~~ -> use `vi.mock`
- [x] `jest.requireActual(moduleName)` -> `vi.importActual`
- [x] `jest.requireMock(moduleName)` -> `vi.importMock`
- [x] `jest.mocked<T>(item: T, deep = false)`

Current `vitest` implementation does not support automocking, so these functions are left out:

- [ ] `jest.disableAutomock()` - not sure if we should support automocking, it's a very confusing feature for users
- [ ] `jest.enableAutomock()`

Not really a part of this issue:

- [ ] `jest.resetModules()`
- [ ] `jest.isolateModules(fn)`

**Comment by eratio08** [comment]
Maybe support for class/interface mocking like with [jest-mock-extended](https://github.com/marchaos/jest-mock-extended)

```
interface PartyProvider {
   getPartyType: () => string;
   getSongs: (type: string) => string[]
   start: (type: string) => void;
}

 const mock = mock<PartyProvider>();
```

**Comment by sheremet-va** [comment]
I think this is an interesting idea, but not a part of this issue, I am afraid. If you want this to be implemented, you can create another issue. We can discuss it there. For now closing this, since all APIs are implemented now.
