### ISSUE TITLE
Error: [vite-node] Failed to load /@fs/src/http

### ISSUE THREAD

**Issue by Duo-Huang** [vitest-dev/vitest#1866]
### Describe the bug

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/50909268/185114762-e35bac05-0950-4902-9c9a-e01c9f2352f7.png">
<img width="935" alt="image" src="https://user-images.githubusercontent.com/50909268/185114957-d43b00fe-ddf8-4596-ad62-863640c5c0a9.png">
<img width="950" alt="image" src="https://user-images.githubusercontent.com/50909268/185114986-a4bae367-f842-4926-91dd-e7d105c72592.png">
<img width="622" alt="image" src="https://user-images.githubusercontent.com/50909268/185115077-70a746f4-27a5-4c3e-b8cd-83760de02d92.png">
When I use @ in my test it doesn't resolve correctly, I found this is only related to my http/index.ts, @ in other files works fine. I have done import request from http/request and it works fine, I tested it in rollup and everything works fine

### Reproduction

vitest + vite
<img width="687" alt="image" src="https://user-images.githubusercontent.com/50909268/185129352-a31f2a45-3432-4668-9cbb-5977e137fa9a.png">

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 179.44 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 15.6
  npmPackages:
    @vitejs/plugin-vue: ^3.0.2 => 3.0.2 
    vite: ^3.0.6 => 3.0.6 
    vitest: ^0.21.1 => 0.21.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Duo-Huang** [comment]
I have reproduced it in https://stackblitz.com/edit/vitest-dev-vitest-fzswom?file=test/reproduce.test.js

**Comment by VivianSolide** [comment]
I think it's due to your alias.

**Comment by Duo-Huang** [comment]
> I think it's due to your alias.
> 
> edit: you may just import like this `import request from 'http'`
> 
> link: https://stackblitz.com/edit/vitest-dev-vitest-xni4cy?file=vite.config.ts,test%2Freproduce.test.js

http is internal module of node，so i changed folder name，you can test again

**Comment by Duo-Huang** [comment]
https://stackblitz.com/edit/vitest-dev-vitest-ogin7f?file=test%2Freproduce.test.js,src%2Futils%2Findex.js
I found that it is the same as rollup except that import dir is not supported by default, so what should I do?
