### ISSUE TITLE
TS: Object literals can specify only known properties, and "test" is not in type "UserConfig"

### ISSUE THREAD

**Issue by CharleeWa** [vitest-dev/vitest#1871]
### Describe the bug

This is a type error, please tell me the correct solution. 

### Reproduction

```
/// <reference types="vitest" />
import type { ConfigEnv, UserConfig } from 'vite'

export default ({ command, mode }: ConfigEnv): UserConfig => {
   return {
      test: {},
   }
}
```

### System Info

```shell
mac os
```

### Used Package Manager

yarn

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You might have different versions of Vite installed, and Vitest extends it's own Vite config type.

**Comment by CharleeWa** [comment]
> You might have different versions of Vite installed, and Vitest extends it's own Vite config type.

Thank you for your reply, but I have checked and they are all the latest versions.

vite: 3.0.8
vitest: 0.22.0

It's really confusing！

**Comment by kevinvalk** [comment]
Exact same problem here:
```
yarn list v1.22.19
├─ @vitejs/plugin-vue@3.1.0
├─ @vitest/coverage-c8@0.23.1
├─ vite-plugin-checker@0.5.1
├─ vite-tsconfig-paths@3.5.0
├─ vite@3.1.0
└─ vitest@0.23.1
   └─ vite@3.0.0
```

One of our devs was so smart to cast the `defineConfig({}  as Parameters<typeof defineConfig>[0])`

**Comment by dominikbulaj** [comment]
Guys, I found solution. We need to import `defineConfig` from `vitest` 

In my case, just changing import did the trick (I use `vite.config.ts`)

```diff
- import { defineConfig } from 'vite'
+ import { defineConfig } from 'vitest/config';

export default defineConfig({
  // ...
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: './tests/setup.ts',
  },
})
```

Now TS error is gone. Hope it helps

**Comment by sheremet-va** [comment]
So, this happens when you have several Vite versions installed. Check your lockfile and resolve the inconsistency. You can also bypass this by using `defineConfig` from `vitest/config`. Closing issue since this is not Vitest problem.

**Comment by CharleeWa** [comment]
> So, this happens when you have several Vite versions installed. Check your lockfile and resolve the inconsistency. You can also bypass this by using `defineConfig` from `vitest/config`. Closing issue since this is not Vitest problem.

I see, Thanks!
