### ISSUE TITLE
Can't run two web worker test cases in one file

### ISSUE THREAD

**Issue by mysteryven** [vitest-dev/vitest#1873]
### Describe the bug

Firstly, I used `@vitest/web-worker` to simulate web worker: 
```
export default defineConfig({
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['@vitest/web-worker'],
  },
})
```
Next, I wrote two test in one file(If I only add one test, It will be OK).

```typescript
const createWorker = () => new Worker(new URL('./fibonacci', import.meta.url), {
  type: 'module'
})

test('run MyWorker first time', async () => {
  const worker = createWorker()
  const ret = await promiseWorker(worker, 10)
  expect(ret).toBe(89)
})

// The second test will print such errors:
// Error: Test timed out in 5000ms.
// If this is a long-running test, pass a timeout value as the last argument or configure it globally with "testTimeout".
test('run MyWorker second time', async () => {
  const worker = createWorker()
  const ret = await promiseWorker(worker, 10)
  expect(ret).toBe(89)
})

function promiseWorker(worker: Worker, n: number) {
  return new Promise((resolve, reject) => {
    worker.onmessage = function({data}) {
      resolve(data)
    }
    worker.onmessageerror = function({data}) {
      reject(data)
    }

    worker.onerror = function(e) {
      reject(e)
    }

    worker.postMessage(n)
  }) 
}
```

This is my `fibonacci.ts` file, If I not import `exportWorker` but inline it, the tests will all passed : 

```typescript
import exportWorker from "./exportWorker"

// If I use the `exportWorker` from ./exportWorker.ts , It will be broken.
exportWorker(fibonacci)

// If I use inline exportWorker, It will passed
// function exportWorker(fn: CallableFunction) {
//   self.onmessage = function({data}) {
//     const result = fn(data)

//     self.postMessage(result)
//   }
// }
```

### Reproduction

[vitest-web-worker-reproduction](https://github.com/mysteryven/vitest-web-worker-reproduction)

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 16.84 MB / 8.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Firefox: 80.0.1
    Safari: 15.5
  npmPackages:
    vite: ^3.0.0 => 3.0.8 
    vitest: latest => 0.22.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Yeah, dependencies of worker are not cleared, but should be.

**Comment by sun0day** [comment]
> Yeah, dependencies of worker are not cleared, but should be. There is `invalidates` that should be populated on import:
> 
> https://github.com/vitest-dev/vitest/blob/285ac7c24ef74ee244ce927b5e3bc757feaa918a/packages/web-worker/src/pure.ts#L116
> 
> And we actually have a function that can do that now: [b8922aa](https://github.com/vitest-dev/vitest/commit/b8922aa1954fc6c208ac8ef5698c57774938c323)

I can offer a PR @sheremet-va.
