### ISSUE TITLE
describe.only don't work

### ISSUE THREAD

**Issue by Duo-Huang** [vitest-dev/vitest#1875]
### Describe the 
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/50909268/185527495-a0c53d9f-76a6-413d-9200-194f145a2751.png">

### Reproduction

https://github.com/Duo-Huang/demo-app

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 143.34 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Safari: 15.6
  npmPackages:
    @vitejs/plugin-vue: ^3.0.2 => 3.0.2 
    vite: ^3.0.6 => 3.0.6 
    vitest: ^0.21.1 => 0.21.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`.only` works only inside one file, it's not shared between different suites. If you want to run only one file, use `vitest <path>`

**Comment by Duo-Huang** [comment]
got it, thank you, you can close it

**Comment by Duo-Huang** [comment]
<img width="1258" alt="image" src="https://user-images.githubusercontent.com/50909268/185555512-5ce7c0db-b90b-4129-9465-41ff22191576.png">
it still doesn't work

**Comment by bartoszgolebiowski** [comment]
I will check it today

**Comment by bartoszgolebiowski** [comment]
According to the jest [documentation](https://jestjs.io/docs/api#describeonlyname-fn), the second **describe** should be skipped. I will try to resolve it, but it seems like we have some unit tests which does not respect this rule. 
So what should we do? 
Should we align with jest [documentation](https://jestjs.io/docs/api#describeonlyname-fn), or leave it like it is? @sheremet-va

**Comment by bartoszgolebiowski** [comment]
Try to wrap the second assertion into `it `or `test` section.
We should not make assertions directly in `describe` section.

If we use jest and place assertion directly inside `describe` section, `only` keyword will not work, and 
```js
describe("should not run tests inside", () => {
  expect(true).toBe(false);
});
```
will be triggered. 

[codesandbox](https://codesandbox.io/s/mystifying-montalcini-kc4rgb?file=/src/index.test.js)


![image](https://user-images.githubusercontent.com/39523638/188003318-2a0f018c-c45e-4466-9041-841eb3e69ff5.png)

**Comment by sheremet-va** [comment]
@bartoszgolebiowski is correct. `describe.only` just marks all tests inside with `.only`, but it always runs collection phase. If you put anything beside `test` block inside it will run.
