### ISSUE TITLE
Subordinate confusing "Failed to fully serialize error" to the original error information

### ISSUE THREAD

**Issue by kaorukobo** [vitest-dev/vitest#1882]
### Clear and concise description of the problem

A minimum reproduction of the problem is as follows:

```sh
# Use latest vite, vitest, and axios
npm i -D vitest@latest axios@latest

# Create a test which throws AxiosError object
mkdir test
cat > test/issue.test.js <<'EOS'
import axios from 'axios'
import { test } from 'vitest'

test("it", async () => {
  await axios.get('https://github.com/vitest-dev/vitest/issues/99999999')
})
EOS

# Run
./node_modules/.bin/vitest run
```

Then I get the following output:

```
Error: Failed to fully serialize error: Illegal invocation
Inner error message: Request failed with status code 404
```

While what developers would want to get are...

- The original error message `Request failed with status code 404`
- Codeframe/stacktrace of the original error.

But the above output looks that something weird happens, such as a bug from the vitest.
Also it does not provide enough information to solve the original error.

### Suggested solution

I suspect that there are many cases that an error object cannot be serialized. (While I don't know what this error serialization is for.)

So in such case, it would be better if the output could be as follows:

```
FAIL  test/issue.test.ts > it
AxiosError: Request failed with status code 404  (Internal Error: Failed to fully serialize error: Illegal invocation) 
 ❯ test/issue.test.js:5:X
      3| 
      4| test("it", async () => {
      5|   await axios.get('https://github.com/vitest-dev/vitest/issues/99999999')
       |        ^
      6| })
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
You cannot see stack trace **because** Vitest failed to serialize error. Serialisation happens here:

https://github.com/vitest-dev/vitest/blob/285ac7c24ef74ee244ce927b5e3bc757feaa918a/packages/vitest/src/runtime/error.ts#L56

PR welcome.

**Comment by kaorukobo** [comment]
@sheremet-va
Thanks. I got why serialization is needed. I might try a PR.

It would be nice to change the serialization strategy from "fully done or fail" to best-effort, substituting the failed value with `"(UNSERIALIZABLE_VALUE)"` or like that.
