### ISSUE TITLE
Istanbul code coverage differs from nyc result

### ISSUE THREAD

**Issue by marvin-j97** [vitest-dev/vitest#1887]
### Describe the bug

I tried running Vitest + Istanbul and the result seems to differ from using Istanbul (+ Mocha, but I also tried Cypress) itself.

- Vitest seems to output a Linux-style path for coverage-final.json, even when running on Windows, this breaks NYC merge
- The branch coverage seems to differ
- (_coverageSchema, hash, contentHash are missing, but they are probably not important)

![image](https://user-images.githubusercontent.com/33938500/185669004-2a7b425b-b5f5-4e9b-91a0-664b68999c0a.png)
![image](https://user-images.githubusercontent.com/33938500/185669032-cff4ba35-14bb-4ea2-9826-36424c346e98.png)
First image: Mocha + NYC, second image: Vitest

I'm not 100% sure if this a Istanbul or Vitest issue

### Reproduction

https://github.com/marvin-j97/vitest-windows-path

(I also have a more complex repo trying to merge Vitest + Cypress Typescript coverage reports: https://github.com/marvin-j97/good-next-template/tree/dev)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 8.75 GB / 15.96 GB
  Binaries:
    Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.54)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitest: 0.22.1 => 0.22.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by azaleta** [comment]
>The branch coverage seems to differ

I think vitest report is correct.

Only one branch(if at line 2~4) exists [am i right?]
this branch could not be reached. So the result is `0/1`

compare `branchMap` of  coverage-final.json, you will find same if branch is repeated twice in mocha and only one in vitest.
I guess Istanbul is doing "exclude" on branch report so the mocha result is `1/2`
