### ISSUE TITLE
Spying on `global.window` property in jsdom makes `window` becomes `undefined` (concurrency issue?)

### ISSUE THREAD

**Issue by dwiyatci** [vitest-dev/vitest#1888]
### Describe the bug

When spying on `global.window` property (jsdom env) in one test, the `window` object unexpectedly becomes `undefined` in the other (subsequent) tests, even after `.mockRestore()`.

Note that I'm migrating tests from Jest to Vitest, and the same piece of code works fine in Jest! 😮 

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-umyubc?file=test/suite.test.ts

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    vite: latest => 3.0.9 
    vitest: latest => 0.22.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by flcarre** [comment]
+1

Just updated vitest from 0.6 to 0.22 make some tests crash cause of a spyOn on window

**Comment by hhsl** [comment]
hey, with `vi.stubGlobal` I was able to mock stuff on the global window object like so:

```typescript
vi.stubGlobal('innerWidth', 5);
vi.stubGlobal('innerHeight', 10);
vi.stubGlobal('addEventListener', vi.fn());
vi.stubGlobal('removeEventListener', vi.fn());
... (dont ask why :D)
```

see: https://vitest.dev/guide/mocking.html#globals
Hope this will help!

**Comment by sheremet-va** [comment]
Seems like this was fixed. Cannot reproduce this on the latest Vitest version.
