### ISSUE TITLE
Failed to resolve entry for package "vue-router v3.6.0"

### ISSUE THREAD

**Issue by kingyue737** [vitest-dev/vitest#1898]
### Describe the bug

Import vue-router v3.6.0 will result into error:
```
Error: Failed to resolve entry for package "vue-router". The package may have incorrect main/module/exports specified in its package.json.
```

Not sure whether a bug with `vue-router` or `vitest`

Temporary workaround:
```ts
export default defineConfig({
  test: {
    alias: {
      'vue-router/composables': 'vue-router/dist/composables.mjs',
      'vue-router': 'vue-router/dist/vue-router.esm.js',
    },
})
```

### Reproduction

https://stackblitz.com/edit/vitest-router-x7aswn

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 4.88 GB / 15.68 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (104.0.1293.63)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vite: ^3.0.9 => 3.0.9
    vitest: ^0.22.1 => 0.22.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest doesn't have any custom resolving algorithm, we just use Vite with enabled SSR. And this error is thrown by Vite. This is probably an error on vue-router part.

**Comment by kingyue737** [comment]
Thanks for confirmation. Fixed in vue-router
