### ISSUE TITLE
Make vitest --coverage cover all files by defaults to  or configurable directly in CLI

### ISSUE THREAD

**Issue by NemoStein** [vitest-dev/vitest#1904]
### Clear and concise description of the problem

In my experience, more often than not, it's desirable to have code coverage for all files, not only the tested ones.

Considering that I tend to keep my config files at the bare minimum (`package.json` and `tsconfig.json` only) I usually have the following npm test script:
```json
"test": "standard && tsc && vitest --coverage"
```
This lints, type-checks, tests and cover my source.
The only problem with this is the code coverage not reaching all files.

Having to create a `vitest.config.js` just to declare `test.coverage.all = true` feels a bit awkward and an unnecessary step.

### Suggested solution

The simplest (and unlikely to cause any trouble) solution is to add a `--coverage-all` or similar flag to CLI.

Another solution is to make `vitest --coverage` to cover all files by default.
Although I can't think of a reason for this to be a breaking change (in the sense that things would stop working) I understand that this would change the behavior of the tooling in an unexpectable way for some users.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Doesn't `--coverage.all` just work?

**Comment by NemoStein** [comment]
> Doesn't `--coverage.enabled --coverage.all` just work?

Wow! Thanks @sheremet-va.
Indeed, it works!

Question is, is this documented somewhere? I couldn't find it.
