### ISSUE TITLE
v0.22 with c8 coverage does not clear tmp

### ISSUE THREAD

**Issue by mmk0083** [vitest-dev/vitest#1917]
### Describe the bug

After upgrading to v0.22 we noticed each run of vitest was getting progressively slower. After awhile it stopped working entirely and would fail with an out of memory error. After some digging - it seems that the files in `/coverage/tmp` are not being cleared out between runs. Prior to v0.22 this was happening automatically and seems like it should be the default behavior per c8's documentation.

### Reproduction

We are running `vitest run --environment jsdom --coverage`. After running - look in `/coverage/tmp` and note the number of `.json` files present. Each time you run, this folder gets larger.

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 8.64 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Firefox: 100.0.2
    Safari: 15.6.1
  npmPackages:
    @vitejs/plugin-vue: ^3.0.0 => 3.0.3 
    vite: ^3.0.0 => 3.0.9 
    vitest: ^0.22.1 => 0.22.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VividLemon** [comment]
I'm running `"vitest": "^0.23.1"` and this issue is still occurring.
