### ISSUE TITLE
When using importActual with Chakra UI v2 I get a default import instead of named import.

### ISSUE THREAD

**Issue by Qocotzxin** [vitest-dev/vitest#1923]
### Describe the bug

First of all sorry if this is not a bug, but we couldn't find anything to help solving this issue.

We just updated our stack to use Chakra V2 + React 18 + Vitest 0.22 + Vite 3. During the migration we realized the tests using importActual broke. When debugging we realized that importActual was now returning an object with a default key instead of the named exports as usual. So when doing:

```
  const actual: Record<string, unknown> = await vi.importActual(
    '@chakra-ui/react'
  );
```

We ended up with: `{ default: {Box, Button,... }}`.
Instead of `{ Box, Button, ...}` which was the behavior with Chakra v1 + React 17 (with the same Vitest and Vite version).

The workaround for now has been to take all the exports from the default key when returning the new partial mocked object, but it is totally unexpected since the named imports works as expected in the actual code. Not sure if this is a bug or something we missed in our config, or maybe something from Chakra, but it is easily reproducible as shown in the link below (you will see that it can't find the Button component) and any help would be much appreciated.

Thanks!

### Reproduction

Just run npm run test src/App to see the failing test. There is also a console.log inside the mock block to show how is the structure returned by Vitest.

https://stackblitz.com/edit/vitest-dev-vitest-8b32za?file=src/App.spec.tsx

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 40.05 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 17.6.0 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.volta/bin/yarn
    npm: 8.5.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 104.1.42.97
    Chrome: 104.0.5112.101
    Firefox: 102.0.1
    Safari: 15.6.1
  npmPackages:
    @vitejs/plugin-react: 2.0.1 => 2.0.1 
    vite: 3.0.3 => 3.0.3 
    vitest: 0.22.1 => 0.22.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> which was the behavior with Chakra v1 + React 17 (with the same Vitest and Vite version).

Did you open an issue in Charka repo? From you description it doesn't seem like this is an error on Vitest side.

I've also tried to redirect importing from `.cjs.js` to `.esm.js`, but it throws another error due to how Chakra is bundled:

```
ReferenceError: Cannot access '__vite_ssr_import_5__' before initialization
      9| import { cx } from "@chakra-ui/shared-utils";
     10| var fallbackIcon = {
     11|   path: /* @__PURE__ */ React.createElement("g", {
       |      ^
     12|     stroke: "currentColor",
     13|     strokeWidth: "1.5"
 ❯ eval node_modules/@chakra-ui/accordion/dist/index.esm.js:72:31
```

**Comment by Qocotzxin** [comment]
Hey @sheremet-va thanks for your reply. I did not create an issue in Chakra repo because the only scenario where this is reproducible is when using Vitest + importActual. The code works fine in development/production (using Vite) and even in test environment when using Jest's requireActual or Vitest but without partial mocking. This makes me think the issue might be related specifically to importActual but can't seem to find the root cause.

I'll create an issue in Chakra repo then to see if I can get more information about it. Thanks!

**Comment by sheremet-va** [comment]
> Vitest but without partial mocking

It works with `Vitest`, because we access `default` key for modules, if we didn't find one (you can disable It with `esModuleInterop`). You can see that it doesn't have these properties, when using `import`. We don't do the same for mocked modules, because you have all the power there.

> Jest's requireActual

Jest uses `require` to load modules, so resolution will differ from ESM. Node cannot find dynamic exports to put them as names exports, so you can only access it on `default` property.

> The code works fine in development/production (using Vite) 

Vite doesn't run your code, it smartly bundles it for browser, so everything works fine there.

**Comment by Qocotzxin** [comment]
Thanks for the great explanation, that helps a lot! So I guess for some reason is not finding the named exports, even though they are there. But at least now it's clear why it doesn't work only when using importActual.

I'll be taking a look more in depth to try understanding why those named exports are not being found and raise an issue with Chakra if needed. I'll close this one for one. Really appreciate the help, thanks!

**Comment by sheremet-va** [comment]
> I guess for some reason is not finding the named exports

This is the lever used by Node, when parsing cjs to expose named exports on ESM: https://github.com/guybedford/es-module-lexer

Main thins is that exports should be statically analysable.
