### ISSUE TITLE
Screen not clearing when `clearScreen: true`

### ISSUE THREAD

**Issue by YolCruz** [vitest-dev/vitest#1924]
### Describe the bug

Might be related to #1125. I have the option `clearScreen: true` but when in watch mode, the screen is not clearing when the files change.

I have the configuration split in the following way:

```typescript
// vite.config.ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      // A bunch of paths
    },
  },
  build: {
    sourcemap: true,
    manifest: true,
  },
  clearScreen: true,
});
```

```typescript
// vitest.config.ts
import { mergeConfig } from "vite";
import { defineConfig } from "vitest/config";
import viteConfig from "./vite.config";

export default mergeConfig(
  viteConfig,
  defineConfig({
    test: {
      globals: true,
      environment: "jsdom",
      setupFiles: ["./src/reduxSetup.ts", "./src/setup.ts"],
      cache: false,
      sequence: {
        shuffle: false,
      },
    },
    clearScreen: true,
  })
);
```

### Reproduction

Change the test in the [StackBlitz](https://stackblitz.com/edit/vitest-dev-vitest-vjyctr?file=test/basic.test.ts) to see the terminal not being cleared up

### System Info

```shell
System:
  OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
  CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
  Memory: 12.30 GB / 15.60 GB
  Container: Yes
  Shell: 5.8 - /usr/bin/zsh
Binaries:
  Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
  npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
npmPackages:
  @vitejs/plugin-react: ^2.0.1 => 2.0.1 
  vite: ^3.0.9 => 3.0.9 
  vitest: ^0.22.1 => 0.22.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sun0day** [comment]
I didn't find `clear Screen` definition in official site. Maybe it's left out in the documentation? @sheremet-va 

In source code, `clearScreen` real effect is to clear `rerun` test suits result, not clear all the stdout characters in your terminal @YolCruz

**Comment by silverwind** [comment]
I think this is fixed since https://github.com/vitest-dev/vitest/pull/2228. cc: @sheremet-va
