### ISSUE TITLE
Some way to refer to all tests suites for educated progress decisions

### ISSUE THREAD

**Issue by emahuni** [vitest-dev/vitest#1926]
### Clear and concise description of the problem

I am trying to only close a server that has services and other things that I am testing, but only when all tests suites are done running (from different files in a single thread). 

So I am using the [setupFiles](https://vitest.dev/config/#setupfiles) example to share a global reference to the server and then checking in a beforeAll if it is defined or not then do certain things. The problem is closing the server when everything that needs it has finished with it.

```js
import { config } from '@some-testing-lib'

if (!globalThis.defined) {
  config.plugins = [myCoolPlugin]
  computeHeavyThing()
  globalThis.defined = true
}

// hooks are reset before each suite
afterEach(() => {
  cleanup() // ****** there is no way to only run this when all tests suites are done
})

globalThis.resetBeforeEachTest = true
```

There is no way to do this, as far as I am aware.

### Suggested solution

Cypress allows you to tap into the test runner and get information about running tests, and the kind of thing I was I was hoping Vitest provides. 

The closest thing is the test context object that provides information about a suite, but it does not allow us to see all tests suites that are queued to run or any information whether this is the last suite or whether others failed or passed. This information can go a lot way to make Vitest very extensible and usable.

I suggest that Vitest adds this information so that we can use hooks like beforeAll/afterAll to do something like this:

```js
// beforeEach..., test, ... beforeAll or afterAll where context is exposed 
whichEverHook((context)=> {
  // and that context will contain something like
  context == {
     .... ,  // the current context obj vitest is giving
     allSuites: [...], // all test suites that are to be run or have run
     current, // cyclic ref to the current suite (the context)
     isFirst: false|true, // whether this is the first test suite in the list
     isLast: false|true, // whether this is the last test suite in the list
     allDone: false|true,
     ... // other useful info the runner can provide
  }
})
```

This allows us to make decisions when working with hooks:

```js
import { config } from '@some-testing-lib'

beforeAll((context) => {
  if (context.isFirst) {
    config.plugins = [myCoolPlugin]
    computeHeavyThing()
    globalThis.defined = true
  }
})

// hooks are reset before each suite
afterAll((context) => {
   if(context.allDone && context.isFirst) cleanup() 
})
```

So this allows us to do this in a expressive and much cleaner manner.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Can't you just use `afterAll`?

**Comment by emahuni** [comment]
`allDone` is a flag I am proposing, that is set by vitest when all tests files in `allSuites` have run, i.e.: vitest is about to wait for changes if this is `watch mode`. Sorry I didn't properly comment it above.

unfortunately `afterAll` runs after all tests **in a file**, not after all files.

**Comment by emahuni** [comment]
Other alternative I am just thinking of at the moment is to introduce a new pair of hooks:

`beforeAllSuites` and `afterAllSuites` 


- They behave like the globalSetup files's `setup` and `teardown` exports.
- They run ONCE before all suites and after all suites, but in the same global scope as setup files, meaning test files in a single thread can access it.

**Comment by emahuni** [comment]
YET ANOTHER other alternative I am just thinking of at the moment is to allow the same API as globalSetup, but for setupFiles.

if a setup file exports `setup` and `teardown`:
- They behave like the globalSetup files's `setup` and `teardown` exports.
- They run ONCE before all suites and after all suites, but in the same global scope as setup files, meaning test files in a single thread can access their globals.

**Comment by sheremet-va** [comment]
> They run ONCE before all suites and after all suites, but in the same global scope as setup files, meaning test files in a single thread can access their globals.

This can't work with `threads: true`, because global scope is unique to test file.

In fact, your proposal cannot work with `threads: true` at all, I think:

- `isFirst`/`isLast` is impossible to determine, because tests are running in parallel, so they will be scoped to test single _file_
- `current` will be different for each suite

Your proposal works by accident for `threads: false`, because tests are running sequentially there.

**Comment by sheremet-va** [comment]
> Your proposal works by accident for `threads: false`, because tests are running sequentially there.

Maybe we can add some kind of `setupBeforeEnv` (don't like the name), which will run before `setupFiles` - for `threads: true` it will basically be the same, but for `threads: false` it will run only once before all tests, and `teardown` will run after all tests, like you are proposing here: https://github.com/vitest-dev/vitest/issues/1926#issuecomment-1229158156

This can be done here: 

https://github.com/vitest-dev/vitest/blob/5b190e8490092f835240b60112fbef449c1af801/packages/vitest/src/runtime/entry.ts#L8

PR welcome.

**Comment by emahuni** [comment]
> > They run ONCE before all suites and after all suites, but in the same global scope as setup files, meaning test files in a single thread can access their globals.
> 
> This can't work with `threads: true`, because global scope is unique to test file.
> 
> In fact, your proposal cannot work with `threads: true` at all, I think:
> 
> * `isFirst`/`isLast` is impossible to determine, because tests are running in parallel, so they will be scoped to test single _file_
> * `current` will be different for each suite
> 
> Your proposal works by accident for `threads: false`, because tests are running sequentially there.

Yes, only with threads off, wish there was a way for workers to share a global scope if required, coz this will make a lot of things easier and possible. In fact this accidental trait is why I chose vitest, there are a lot of people who want this as well. Jest has a long standing issue about this. A lot of use cases in the issue. It's a trade-off worth it for global access between tests files.

**Comment by sheremet-va** [comment]
> Yes, only with threads off, wish there was a way for workers to share a global scope if required,

I think you can share global scope with `--no-isolate` flag

**Comment by emahuni** [comment]
> > Yes, only with threads off, wish there was a way for workers to share a global scope if required,
> 
> I think you can share global scope with `--no-isolate` flag

🤯 whaaaaaaa
