### ISSUE TITLE
Typo in https://cn.vitest.dev/guide/comparisons.html#cypress

### ISSUE THREAD

**Issue by DevDengChao** [vitest-dev/vitest#1927]
### Describe the bug

The document in [cn.vitest.dev](https://cn.vitest.dev/guide/comparisons.html#cypress) is `像 Vitest 这样的基于节点的测试框架支持各种实现部分浏览器环境的第三方包`, while it is `Node-based runners like Vitest support various partially-implemented browser environments` in [vitest.dev](https://vitest.dev/guide/comparisons.html#cypress), thus the correct translation should be `像 Vitest 这样的基于 Node.js 的测试框架支持各种实现部分浏览器环境的第三方包`.

Btw, how should we contribute for the translated site (cn.vitest.dev) ?

### Reproduction

![image](https://user-images.githubusercontent.com/16363180/187066711-f69d4cf9-aab8-47cc-84e3-59384a43459a.png)

### System Info

```shell
(not related)
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Please, open issue in https://github.com/vitest-dev/docs-cn
