### ISSUE TITLE
vite:env-replacer incorrectly replaces import.meta.env inside string literals and comments

### ISSUE THREAD

**Issue by tony19** [vitest-dev/vitest#1941]
related [vitejs/vite#9791](https://github.com/vitejs/vite/pull/9791/files/bb34dd12da630df982f9d4c7a371841684f59217#diff-549eafb0508edbd712731e6b064bf7f4ac695383189a619d607bc3167a51611e)

### Describe the bug

The `vite:env-replacer` plugin is indiscriminately replacing `import.meta.env` everywhere in a source file, including string literals and comments.

For example, this test file:

```js
// MyComponent.spec.js
test('ignores import.meta.env', () => {})
```

...gets transformed into:

```js
// MyComponent.spec.js
test('ignores process.env', () => {})
```

Another example:

```js
// importMetaEnv.test.ts
it('import.meta.env equals import' + '.meta.env', () => {
  expect('import.meta.env').toBe('import' + '.meta.env') // ❌ fails
})
```

...which results in:

```shell
 ❯ test/importMetaEnv.test.ts (1)
   ❯ process.env (1)
     × process.env equals import.meta.env

 ❯ eval test/importMetaEnv.test.ts:5:30
      3| describe('import.meta.env', () => {
      4|   it('import.meta.env equals import' + '.meta.env', () => {
      5|     expect('import.meta.env').toBe('import' + '.meta.env');
       |                              ^
      6|   });
      7| });

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/importMetaEnv.test.ts > process.env > process.env equals import.meta.env
AssertionError: expected 'process.env' to be 'import.meta.env' // Object.is equality
  - Expected   "import.meta.env"
  + Received   "process.env"

Test Files  1 failed (1)
     Tests  1 failed (1)
  Start at  23:19:24
  Duration  49ms
```

### Workaround

Use string concatenation to avoid the string replacement (as was done in the `importMetaEnv.test.ts` above):

```js
'import' + '.meta.env'
```

### Solution 1: Strip literals from analysis

Use `strip-literal` on the [string being scanned for `import.meta.env`](https://github.com/vitest-dev/vitest/blob/924ba44/packages/vitest/src/node/plugins/envRelacer.ts#L13):

```diff
-const envs = code.matchAll(/\bimport\.meta\.env\b/g)
+if (!/\bimport\.meta\.env\b/g.test(code))
+  return null
+
+const envs = stripLiteral(code).matchAll(/\bimport\.meta\.env\b/g)
```

This would mimic [the way Vite does it](https://github.com/vitejs/vite/pull/8054).

### Solution 2: Remove `EnvReplacer`; use Vite `env` instead

Vite already replaces `import.meta.env` in its [`vite:define` plugin](https://github.com/vitejs/vite/blob/7d810a9/packages/vite/src/node/plugins/define.ts#L48-L55) and [`vite:import-analysis` plugin](https://github.com/vitejs/vite/blob/7d810a9e157b232c44490bee8016a08bc9167c50/packages/vite/src/node/plugins/importAnalysis.ts#L580-L593), so this plugin seems unnecessary.

### Reproduction

[StackBlitz](https://stackblitz.com/edit/vitest-dev-vitest-jw9wba?file=test%2FimportMetaEnv.test.ts&initialPath=__vitest__)

### System Info

```shell
System:
    OS: macOS 11.6.7
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 259.93 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/n/bin/node
    Yarn: 1.22.19 - ~/n/bin/yarn
    npm: 8.15.0 - ~/n/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Chrome Canary: 107.0.5271.0
    Firefox: 103.0.2
    Safari: 15.6
  npmPackages:
    vite: ^3.0.9 => 3.0.9 
    vitest: workspace:* => 0.22.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vite replaces it to static variables, but we replace it to dynamic process.env, so users can redefine it in runtime, so solution 2 will break usage.

Solution 1 is ok, PR welcome.
