### ISSUE TITLE
Issue with testing compoent that imported TimeRangeSlider from react-time-range-slider.

### ISSUE THREAD

**Issue by Artem-Bosenko-01** [vitest-dev/vitest#1957]
### Describe the bug

When I try to run a test for the component that imported TimeRangeSlider from `react-time-range-slider` module run fails before execution of the test. Following are logs from the error:
```
SyntaxError: Unexpected token '.'
 - node:vm:353:18
 - /node_modules/react-time-range-slider/dist/index.js:17:1
```

### Reproduction

Component file: 
```js
import TimeRangeSlider from "react-time-range-slider"

const TestedComponent = () => {
 return (
  <TimeRangeSlider ... />
 )
}

export default TestedComponent
```

Test file
```js
import TestedComponent from "./"
import { render } from "@testing-library/react"

test(() => {
 render(<TestedComponent/>)
})
```

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 30.54 MB / 16.00 GB
    Shell: 5.1.16 - /usr/local/bin/bash
  Binaries:
    Node: 18.5.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.12.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.6.1
  npmPackages:
    @vitejs/plugin-react: ^2.0.1 => 2.0.1 
    vite: ^3.0.8 => 3.0.9 
    vitest: ^0.22.0 => 0.22.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I guess it fails, because it load css with `require`. Try adding this to you `test.setupFiles`:

```ts
require.extensions['.css'] = () => ({})
```
