### ISSUE TITLE
vite-node — TypeError: p.closeBundle.call is not a function

### ISSUE THREAD

**Issue by acarl005** [vitest-dev/vitest#1960]
### Describe the bug

This error gets thrown at the end of my script when i run `vite-node` from the command line.

```
TypeError: p.closeBundle.call is not a function
    at eval (file:///home/projects/sveltejs-kit-template-default-t83pry/node_modules/vite-node/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35663:81)
    at Array.map (<anonymous>)
    at Object.close (file:///home/projects/sveltejs-kit-template-default-t83pry/node_modules/vite-node/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35663:39)
    at async Promise.all (index 2)
    at async Object.close (file:///home/projects/sveltejs-kit-template-default-t83pry/node_modules/vite-node/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:59298:13)
    at async CAC.run (file:///home/projects/sveltejs-kit-template-default-t83pry/node_modules/vite-node/dist/cli.mjs:684:5)
```

See my [repro](https://stackblitz.com/edit/sveltejs-kit-template-default-t83pry?file=foo.ts,run.js,scripts%2Frun.sh,package.json&terminal=dev) and run `chmod +x ./scripts/run.sh && npm run foo`.

### Reproduction

See my [repro](https://stackblitz.com/edit/sveltejs-kit-template-default-t83pry?file=foo.ts,run.js,scripts%2Frun.sh,package.json&terminal=dev) and run `chmod +x ./scripts/run.sh && npm run foo`.

I added a `console.log(p.closeBundle)` to see why `call` isn't a function, and this is what is printed:

```
{ sequential: true, handler: [AsyncFunction: handler] }
```

### System Info

```
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    vite: ^3.1.0-beta.1 => 3.1.0-beta.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
vite-node defines its Vite version as `^2.9.12 || ^3.0.0-0`, so any Vite 3 version is compatible with it. I assume you installed a new Vite version, but for some reason vite-node kept its local old version. Try updating your package-lock.

**Comment by dominikg** [comment]
latest version of SvelteKit is already using vite 3.1.0-beta and the new object-style hook syntax from rollup 2.78.0.

https://github.com/rollup/rollup/pull/4600

I guess vite-node needs to support it by checking for hook.handler` too

**Comment by sheremet-va** [comment]
> I guess vite-node needs to support it by checking for `hook.handler` too

Vite-node doesn't call this code. You can see in the stack trace that it just runs Vite. @acarl005 has several Vite versions installed, and vite-node uses its local Vite version.

**Comment by acarl005** [comment]
Ah yes that's correct. According to the `package-lock.json`...

```
"node_modules/vite": {
  "version": "3.1.0-beta.2"
},
"node_modules/vite-node/node_modules/vite": {
  "version": "3.0.9"
}
```

I see that the version spec for `vite` in the `vite-node` `package.json` is `"vite": "^2.9.12 || ^3.0.0-0"`. If I understand NPM's versioning semantics, this means beta versions of Vite cannot be used with vite-node? So the solution here would be to wait until Sveltekit is able to run on the stable version of Vite instead of the beta?

**Comment by sheremet-va** [comment]
>  If I understand NPM's versioning semantics, this means beta versions of Vite cannot be used with vite-node?

Do you have any source on that? According to the [link I mentioned](https://jubianchi.github.io/semver-check/#/%5E3.0.0-0/3.1.0-b), it satisfies semver.

**Comment by acarl005** [comment]
Hm.. yeah you're right, `3.1.0-beta.2` *should* be satisfying `3.0.9`. I tried deleting `package-lock.json` and `node_modules` and doing a fresh install, but I keep ending up with `vite-node` having its own separate version 3.0.9.

**Comment by acarl005** [comment]
@sheremet-va It seems the "official" semantic versioner disagrees. Check out this code snippet.

```js
const semver = require('semver')
semver.satisfies("3.1.0-beta.2", "^3.0.0-0") // false
```

According to the [NPM docs](https://docs.npmjs.com/cli/v6/using-npm/semver), that is the official package used to determine semver compatibility.

**Comment by sheremet-va** [comment]
> Basically, it looks like it is impossible to opt-in to all prerelease versions within a range, even if your range is `*`!

I guess the only way to test `beta` versions would be to use [`overrides`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) (for NPM) field then.
- PNPM: https://pnpm.io/ru/package_json#pnpmoverrides
- Yarn: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/#toc-how-to-use-it

I don't think we can put every beta version 😄 If this satisfies you, we can close the issue.

**Comment by acarl005** [comment]
Yep that works! Thanks for your help!
