### ISSUE TITLE
Custom environment support

### ISSUE THREAD

**Issue by nickmccurdy** [vitest-dev/vitest#1961]
### Clear and concise description of the problem

Jest supports running tests in custom environments using the [`testEnvironment` option](https://jestjs.io/docs/configuration#testenvironment-string). I'd like to have a similar feature in Vitest, both to make it easier to migrate from Jest to Vitest, and so users of [my custom environment](https://github.com/nickmccurdy/jest-environment-url) can use Vitest. This would also make it easier to support Vitest in the [Testing Library Recorder Extension](https://github.com/testing-library/testing-library-recorder-extension), since it uses my custom environment.

### Suggested solution

1. Support using custom strings with the `environment` option
   - Optionally, we could also support passing an environment class directly to the option
2. Support using custom strings with `@vitest-environment` (also `@jest-environment` for compatibility)
3. Resolve strings like `jsdom` to `vite-environment-jsdom` (or `jest-environment-jsdom` if we can figure out how to support Jest environments directly)

### Alternative

Use the [adapter pattern](https://sourcemaking.com/design_patterns/adapter) to load Jest environments instead of supporting them directly

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
We don't support jest environments, it has a different logic to how we run tests.

**Comment by nickmccurdy** [comment]
Do you think it would be possible using the adapter pattern? If not, I can edit the issue to focus on supporting new Vitest environments instead.

**Comment by sheremet-va** [comment]
> Do you think it would be possible using the adapter pattern? If not, I can edit the issue to focus on supporting new Vitest environments instead.

Currently Vitest environments are just objects: 
```
{ name, setup(global, options): { teardown() } }
```

Global arguments doesn't really matter, because it's always `globalThis`. We don't isolate context with `vm`, like jest does. We rely on running workers with isolated flag.

These functions are called inside a worker, but config is resolved in the main thread, so we can't pass down any unserializable data, but we can import anything inside, so importing `vite-environment-#{name}` is possible.

> Support using custom strings with `@vitest-environment` (also `@jest-environment` for compatibility)

`@jest-environment` is already supported for our envs, btw.

**Comment by sheremet-va** [comment]
> Currently Vitest environments are just objects

So technically, you can do everything that you do with envs inside `test.setupFiles`

**Comment by nickmccurdy** [comment]
Perhaps we could support `environment: custom` or ` as a shortcut for
```js
test: { ..., setupFiles: [..., `vitest-environment-${custom}`] }
```

This would also make it easier to support Vitest in [Testing Library Recorder Extension](https://github.com/testing-library/testing-library-recorder-extension) because Chrome DevTools only lets you export a single JS file, so I can use dynamic comments but not a dynamic config.

**Comment by sheremet-va** [comment]
I think your original proposal is fine. We would have:

```ts
// vitest.config
export default {
  test: {
    environment: 'custom',
    environmentOptions: {
       custom: {} // options
   }
  }
}

// package "vitest-environment-custom"
import {
  type EnvironmentSetup,
  environments // default env if needed
  populateGlobal, // copies values to global, should only really be used for browser APIs
} from 'vitest/node'
export default <EnvironmentSetup>{
  name: 'custom',
  setup() {
    return { teardown: () => {} }
  }
}
```

**Comment by sheremet-va** [comment]
We can also move to classes and adapter pattern, of course, so it's easier to overwrite.

**Comment by nickmccurdy** [comment]
We would also need to support `@{vitest/jest}-environment-options` comments for compatibility with Jest.

**Comment by nickmccurdy** [comment]
> We can also move to classes and adapter pattern, of course, so it's easier to overwrite.

So are you suggesting an API similar to [`JestEnvironment`](https://github.com/facebook/jest/blob/2fa8763db2e661b520ebebeef45a22897d6da673/packages/jest-environment/src/index.ts#L40-L51)? Personally I'm not really a fan of this approach, as it encourages inheritance. Also, since Jest similarly runs tests in separate environments (using VMs instead of workers), the instances aren't really shared much outside of Jest's internal APIs.

**Comment by sheremet-va** [comment]
@nickmccurdy I've opened #1963. Feedback appreciated
