### ISSUE TITLE
Environment options are not parsed from comments

### ISSUE THREAD

**Issue by nickmccurdy** [vitest-dev/vitest#1962]
### Describe the bug

Vitest supports parsing `@{vitest,jest}-environment` comments to set an environment, but it should also support `@{vitest,jest}-environment-options` comments for [compatibility with Jest](https://jestjs.io/docs/configuration#testenvironmentoptions-object).

#### `index.test.js`
```js
/**
 * @jest-environment jsdom
 * @jest-environment-options {"url": "https://example.com/"}
 */
test("use jsdom and set the URL in this test file", () => {
  expect(location.href).toBe("https://example.com/")
})
```
#### `vite.config.js`
```js
export default {
  test: {
    globals: true,
  },
}
```
#### Expected result from Jest
```
 PASS  ./index.test.js
  ✓ use jsdom and set the URL in this test file (2 ms)
```

#### Actual result from Vitest
```
 FAIL  index.test.js > use jsdom and set the URL in this test file
AssertionError: expected 'http://localhost:3000/' to be 'https://example.com/' // Object.is equality
 ❯ index.test.js:6:25
      4|  */
      5| test("use jsdom and set the URL in this test file", () => {
      6|   expect(location.href).toBe("https://example.com/")
       |                         ^
      7| })
      8| 

  - Expected   "https://example.com/"
  + Received   "http://localhost:3000/"
```

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 43.91 MB / 8.00 GB
    Shell: 3.5.1 - /usr/local/bin/fish
  Binaries:
    Node: 18.8.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.1 - /usr/local/bin/npm
    Watchman: 2022.08.29.00 - /usr/local/bin/watchman
  npmPackages:
    vitest: ^0.18.0 => 0.18.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nickmccurdy** [comment]
I just noticed that the JSDOM options are scoped under a `jsdom` property, so there would have to be a change to that API or an adapter to fix this.

**Comment by sheremet-va** [comment]
> I just noticed that the JSDOM options are scoped under a `jsdom` property in `setup`, so there would have to be a change or adapter for that API to fix this.

We can just put options inside a key of current env:

```ts
/**
 * @jest-environment jsdom
 * @jest-environment-options {"url": "https://example.com/"}
 */
// environmentOptions -> { jsdom: { url: string } }
```

```ts
/**
 * @jest-environment-options {"url": "https://example.com/"}
 */
// node is default environment. if config is used, will put into the one specified with config
// environmentOptions -> { node: { url: string } }
```

All spec files have environment. By default, so should not be a problem.

**Comment by nickmccurdy** [comment]
I'm mostly thinking about Jest compatibility, and it doesn't use a `jsdom` property. Can you pass top level options to an environment?

**Comment by sheremet-va** [comment]
> I'm mostly thinking about Jest compatibility, and it doesn't use a `jsdom` property.

`environment` will never be jest compatible, so I don't see any reason to be jest compatible here.

**Comment by nickmccurdy** [comment]
The environment API may not be compatible, but we already promise compatibility with the `@jest-environment` comment, so I would prefer to to find a way where we can also be compatible with using `@jest-environment-options` with JSDOM without an intermediate property.

**Comment by sheremet-va** [comment]
> The environment API may not be compatible, but we already document compatibility with the `@jest-environment` comment, so I would prefer to to find a way where we can also be compatible with using `@jest-environment-options` with JSDOM without an intermediate property.

You wouldn't need to write `@jest-environment-options { jsdom: { option } }`, you would write `@jest-environment-options { option }`, since we already know the environment for the file.

**Comment by nickmccurdy** [comment]
Oh sorry, I think I misunderstood the purpose of the key. Is it just there so options other than those in the comments can be passed to the environment?

**Comment by sheremet-va** [comment]
> Oh sorry, I think I misunderstood the purpose of the key. Is it just there so options other than those in the comments can be passed to the environment?

Yes, you can have multiple environments, so you need a key for each.

> Also can I still use that with a custom environment without having a 2D object?

You would use it like this:

```ts
// config
export default {
  test: {
    environmentOptions: {
       custom: {} // your options
    }
  }
}

// or inside a spec file
/**
 * @vitest-environment custom
 * @vitest-environment-options { url: "http://example.com" } 
 */ 
```
