### ISSUE TITLE
Degradation: Significant slow down of C8 coverage report

### ISSUE THREAD

**Issue by gkiely** [vitest-dev/vitest#1964]
### Describe the bug

[0.22.0](https://github.com/vitest-dev/vitest/releases/tag/v0.22.0) Introduces a significant slowdown of C8 coverage.

### Reproduction

Repo: https://github.com/gkiely/vite-react-starter
```sh
git clone git@github.com:gkiely/vite-react-starter.git
npm run test-all # Runs fast as it's using 0.17.1, 0.21.1 also runs fast
# Update package json to "vitest": "0.22.0",
npm run test-all
```

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 4.53 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.4.0 - ~/.volta/tools/image/node/18.4.0/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 8.12.1 - ~/.volta/tools/image/node/18.4.0/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 105.0.5195.102
    Firefox: 103.0.2
    Safari: 15.3
  npmPackages:
    @vitejs/plugin-react: ^2.0.1 => 2.0.1 
    vite: ^3.0.9 => 3.0.9 
    vitest: 0.22.0 => 0.22.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Demivan** [comment]
Duplicate of #1917?

**Comment by gkiely** [comment]
Fixed with latest version.
