### ISSUE TITLE
Suggestion: vitest rich assertion information support for node's assert - similar to jest

### ISSUE THREAD

**Issue by IgnusG** [vitest-dev/vitest#1965]
### Clear and concise description of the problem

In jest using node's `assert` adds meaningful information to the assertion when it's displayed such as for `assert.equal(parameter1, parameter 2, message)` displaying both the value for parameter 1 and parameter 2:

![image](https://user-images.githubusercontent.com/6438760/188312818-44d6e2fb-5b3e-47f2-a5b8-a378f6ffd81b.png)

Meanwhile vitest does not do anything special to asserts which results in this being shown instead (if the actual and expected values were behind variables you would not be able to tell what the actual value was):

![image](https://user-images.githubusercontent.com/6438760/188312836-7e46af8e-723c-4d99-940f-30f6e3618a51.png)

The problem with simply using expect is that some libraries specifically target `assert` such as https://github.com/babel-utils/babel-plugin-tester. These don't work well with vitest and I could not find any way to mock assert or add a workaround (except patching the original library by replacing assert with expect - we lose the message but at least the actual output is shown in case the comparison fails).

### Suggested solution

It would be great if vitest offered something like jest does either behind a flag or an additional package.

### Additional context

I've tested this on this super simple repo https://github.com/sanfilippopablo/jest-no-diff-output by adding vitest and running both vitest and jest on the same test.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Interesting. AssertionError provides both `actual` and `expected`, Vitest has a check to show diff:

https://github.com/vitest-dev/vitest/blob/aa7eb7d14bf5a5df43e67c2078f035da454f7e31/packages/vitest/src/node/error.ts#L72

I guess all we need to extend this check 🤔

**Comment by IgnusG** [comment]
Modifying it to: `if (e.showDiff || (e.name === "AssertionError" && e.actual && e.expected)) {` correctly displays the diff 👍

**Comment by sheremet-va** [comment]
> Modifying it to: `if (e.showDiff || (e.name === "AssertionError" && e.actual && e.expected)) {` correctly displays the diff 👍

This is not correct behaviour though, because Vitest's `expect` also throws `AssertionError`, but it has `showDiff`. We should check it by `instanceof` or other properties, maybe?

**Comment by IgnusG** [comment]
> > Modifying it to: `if (e.showDiff || (e.name === "AssertionError" && e.actual && e.expected)) {` correctly displays the diff 👍
> 
> This is not correct behaviour though, because Vitest's `expect` also throws `AssertionError`, but it has `showDiff`, which might be `false`! We should check it by `instanceof` or other properties, maybe? Or we can assume that if it has `actual` and `expected`, but doesn't have `showDiff`, always show diff. PR welcome.

Ah I see, since the diff only needs `actual` and `expected` for the sake of future extensibility (not relying on a specific AssertionError` instance check should we go with the second alternative? Showing a diff in case showDiff is undefined otherwise checking it for true/false? 

I can open a PR for this

**Comment by sheremet-va** [comment]
> Showing a diff in case showDiff is undefined otherwise checking it for true/false?

Sure.
