### ISSUE TITLE
Undocumented breaking change for reporters in 0.23.0

### ISSUE THREAD

**Issue by nickmccurdy** [vitest-dev/vitest#1968]
### Clear and concise description of the problem

0.23.0 includes #1963, which I believe is a breaking change, but it is not documented as a breaking change. The version number is correctly incremented, but a user upgrading Vitest may be getting an additional breaking change they're not aware of. This is also something I think reporter maintainers should be aware of.

Specifically, if a reporter is designed to only support the native environments, using a custom environment could break the reporter in production. Additionally if a reporter using TypeScript, this breaking change in the type declarations could break its build or builds of its dependents.

### Suggested solution

Please edit the 0.23.0 release notes to move the entry for #1963 to the breaking changes section.

### Alternative

If release notes can't be edited (I noticed they're posted by a bot), let me know and I can release a PR documenting the breaking change. That PR should be released as a patch release, not a minor release, as it is a documentation fix that we would want all users of the current minor to get, and does not actually introduce a breaking change.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
What part exactly is a breaking change? It was impossible to use custom environments before, meaning this change doesn't affect users.

**Comment by nickmccurdy** [comment]
Correct me if I'm wrong but I was under the impression that reporters get passed the instance of the current Vitest config.

**Comment by sheremet-va** [comment]
Yes, but do you have examples with reporters relying on config environment?

With this logic almost every change is a breaking change, because everything depends on Vitest instance, even those fixing types 🤔

**Comment by nickmccurdy** [comment]
I'm working on an example for this issue.

> With this logic almost every change is a breaking change, because everything depends on Vitest instance, even those fixing types 🤔
I wouldn't consider this a type fix because it widens the type.

**Comment by sheremet-va** [comment]
I updated breaking changes.

**Comment by nickmccurdy** [comment]
Great, thanks for all your work on this! I plan on releasing a custom environment soon.
