### ISSUE TITLE
RLT Watch Error

### ISSUE THREAD

**Issue by fadi-george** [vitest-dev/vitest#197]
For tests written with React Testing Library, simple tests can run fine on first run, but there are issues with files being watched.
E.g., changing the name/title of the test will leads errors like:

```
Error: Unable to find an accessible element

Ignored nodes: comments, <script />, <style />
<body
  style=""
/>
 ❯ Object.getElementError node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:368:17
    366|   getElementError: function getElementError(…
    367|     var prettifiedDOM = prettyDOM(container);
    368|     var error = new Error([message, "Ignored…
       |                 ^
    369|     error.name = 'TestingLibraryElementError…
    370|     return error;
    
 ❯ node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1362:25
 ❯ node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1334:24
 ❯ node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1387:25
```

**Comment by CroquetMickael** [comment]
Hey there, it's more than just renaming the test, got trouble too, I did not rename the test but just relaunching with a save make the second run and more going in fail:

First run :
![image](https://user-images.githubusercontent.com/23740372/146924501-19b5a54c-1b94-42a7-9319-695bfce7c438.png)

Second run and more, you just need to save again files without modifying them :
![image](https://user-images.githubusercontent.com/23740372/146924607-45b39c16-afb3-4ecd-a48a-7520ad762cdd.png)


Using [create-vite](https://github.com/vitejs/vite/tree/main/packages/create-vite) for react with : 


  ```json
"dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@testing-library/react": "^12.1.2",
    "@vitejs/plugin-react": "^1.0.7",
    "c8": "^7.10.0",
    "jsdom": "^19.0.0",
    "vite": "^2.7.2",
    "vitest": "0.0.103"
  }
```

My vite config : 

```javascript
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  test: {
    global: true,
    environment: 'jsdom',
  },
})

```

**Comment by antfu** [comment]
Can you try with v0.0.105?

**Comment by CroquetMickael** [comment]
Working :) fine now ! Save or rename test no more trouble !
