### ISSUE TITLE
Error: Module did not self-register when using Canvas + jsdom

### ISSUE THREAD

**Issue by jsolly** [vitest-dev/vitest#1982]
### Describe the bug
A fatal error occurs when using jsdom and the npm package, [canvas](https://www.npmjs.com/package/canvas).

I came upon the workaround shown in the Reproduction from reading [this blog post](https://xebia.com/blog/how-to-solve-canvas-crash-in-vitest-with-threads-and-jsdom/). It seems that this is a jsdom/canvas issue, not Vitest, but I definitely burned a lot of time googling around to find a solution.

Could we add a note to the docs about this? Happy to open a PR to include the info.

### Reproduction
1 - Install jsdom and include it in your vitest.config.ts 
```ts
export default defineConfig({
  test: {
    environment: 'jsdom',
  },
});
```
2 - Install canvas with `npm i canvas` 
You may also need to run `npm rebuild canvas --update-binary` as mentioned in this [blog post](https://www.the-koi.com/projects/vitest-how-to-mock-a-canvas/).

3 - Attempt to run any test
Error
```
Module did not self-register: '~/my-project/node_modules/canvas/build/Release/canvas.node'
```

### Workaround
Disable threads. Error goes away

```ts
export default defineConfig({
  test: {
    environment: 'jsdom',
    threads: false,
  },
});
```

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 128.45 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 105.1.43.88
    Chrome: 105.0.5195.102
    Firefox: 101.0.1
    Safari: 15.6.1
  npmPackages:
    vite: ^3.0.9 => 3.1.0 
    vitest: ^0.22.1 => 0.22.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
duplicate if https://github.com/vitest-dev/vitest/issues/740
