### ISSUE TITLE
Mocking Node modules multiple times

### ISSUE THREAD

**Issue by JPtenBerge** [vitest-dev/vitest#1988]
### Describe the bug

I can't seem to mock an imported Node.js module like `fs` multiple times.

Simplified, here's a bit of code I'm testing:

```ts
import { existsSync } from 'fs';

export function exists() {
  console.log('exists:', existsSync('test'));
  return existsSync('test');
}
```
The [cheat sheet of the docs](https://vitest.dev/guide/mocking.html#cheat-sheet) along with [this comment](https://github.com/vitest-dev/vitest/issues/110) aided me with testing this code:

```ts
it('returns false', () => {
  vi.mock('node:fs', async () => {
    return {
      existsSync: vi.fn().mockReturnValue(false),
    };
  });

  expect(exists()).toBe(false);
});
```
And this works, yay! However, when I duplicate this test and change the mocked return value to `true`, things start to break. The first test that defines the return value is the one that passes, the other one fails.

I've tried calling `restoreAllMocks()`, `resetAllMocks()` and/or `resetModules()` from an `afterEach()`, all to no avail. I've also tried using a `beforeEach()` to define the mock and store the mocked function in a variable:

```ts
let mockExists: Mock<any[], any>;

beforeEach(() => {
	mockExists = vi.fn().mockReturnValue(true);
	vi.mock('node:fs', () => {
		return {
			existsSync: mockExists,
		};
	});
});
```
But that lead to this very, very strange error:

    ReferenceError: mockExists is not defined

Basic variables that are suddenly out of scope is highly irregular behavior and a can of worms on its own, I suspect.

All in all, I'm a bit stuck it seems. I'm quite sure it's buggy behavior. But it could still be that it's just me doing something wrong. Any tips, fixes and/or workarounds would be highly appreciated.

### Reproduction

I've reproduced it [here](https://stackblitz.com/edit/vitest-dev-vitest-wqy1bh?file=test/exists.test.ts).

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz   
    Memory: 2.98 GB / 15.79 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 104.0.5112.102
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.27)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitest: ^0.22.1 => 0.22.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
From https://vitest.dev/api/#vi-mock:

> If factory is defined, will return its result. Factory function can be asynchronous. You may call [vi.importActual](https://vitest.dev/api/#vi-importactual) inside to get the original module. **The call to vi.mock is hoisted to the top of the file, so you don't have access to variables declared in the global file scope!**

All `vi.mock` calls are placed at the top of the file, and it's the first thing that's getting called. To change implementation for different tests, you can do:

```
vi.spyOn(fs, 'existsSync').mockImplementation(() => {
 // new implementation
})
```

**Comment by sheremet-va** [comment]
> But I have a grip on the situation again and am gonna try some more stuff.

You should be able to, if you have at the top:

```ts
vi.mock('node:fs', () => {
  return {
    existsSync: vi.fn(),
  };
});
```

**Comment by JPtenBerge** [comment]
Right you are, double thanks!
