### ISSUE TITLE
Vitest does not work on Node versions lower than 16.

### ISSUE THREAD

**Issue by prarabdhb** [vitest-dev/vitest#1989]
### Describe the bug

Since version 0.23.0, with this PR, https://github.com/vitest-dev/vitest/pull/1029, `vitest` uses `tinybench`. While building a project on node versions lesser than 16, it reports `tinybench@2.1.4: The engine "node" is incompatible with this module. Expected version ">=16.0.0". Got "14.18.3"`

### Reproduction

Basic build setup on any node version below 16

### System Info

```shell
Vitest: 0.23.0
Node Version: 14.18.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Aslemammad** [comment]
Released a new version of Tinybench (2.1.5), Hope this fixes the issue.
