### ISSUE TITLE
Docs: features guide

### ISSUE THREAD

**Issue by patak-dev** [vitest-dev/vitest#199]
Review and complete sections of the features: guide https://preview.vitest.dev/guide/features.html

- [ ] Shared config between test, dev and build
- [x] Watch Mode by default
- [ ] Smooth integration with UI Frameworks
- [ ] Common web idioms out-of-the-box
- [ ] ESM first
- [x] Threads
- [ ] Filtering
- [ ] CLI filtering
- [ ] Specifying a Timeout
- [ ] Filtering
- [ ] Running tests concurrently
- [ ] Snaphot
- [ ] Chai and Jest expect compatibility
- [x] Mocking
- [ ] Coverage

If you have knowledge about one of these topics, consider sending individual PRs for that sections

**Comment by Aslemammad** [comment]
Working on threads!

**Comment by Aslemammad** [comment]
working on watch mode by default
