### ISSUE TITLE
Missing docs for bench CLI and API

### ISSUE THREAD

**Issue by nickmccurdy** [vitest-dev/vitest#1997]
### Clear and concise description of the problem

As far as I can tell, we haven't added any CLI or API docs for `vitest bench` and `bench()` yet.

### Suggested solution

Document the benchmarking tool like we document other parts of the test runner.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by FINDarkside** [comment]
I think the docs are still quite lacking, for example it seems like there's some pattern to match `bench.ts` files but I couldn't find any mention of it in docs. I just guessed since it seemed intuitive.
