### ISSUE TITLE
Type error when using {retry: 2} in describe()

### ISSUE THREAD

**Issue by johnfraney** [vitest-dev/vitest#1998]
### Describe the bug

I'm getting a type error when using the new retry option (#1929) of `describe()`:

> error TS2554: Expected 1-2 arguments, but got 3

### Reproduction

This will run successfully but trigger a type error:

```ts
describe('tests', () => {
  ...
}, {retry: 2})
```

### System Info

```shell
npx: installed 1 in 1.517s

  System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 2.67 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nvm/versions/node/v14.18.0/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.0/bin/npm
    Watchman: 2022.05.16.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 104.0.5112.101
    Firefox Developer Edition: 105.0
    Safari: 15.6.1
  npmPackages:
    @vitejs/plugin-react: ^1.3.0 => 1.3.2 
    vite: ^2.9.5 => 2.9.14 
    vitest: ^0.23.0 => 0.23.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by bartoszgolebiowski** [comment]
Hello, 
I just checked this typescript error, and I would like to share my conclusions.
We are missing types for `describe` section, but the `options?: number | TestOptions` argument will somehow affect this section.

For this scenario, the retry option will retry `describe` section 10 times.

```
let count4 = 0
describe('description retry', () => {
    count4 += 1
    expect(count4).toBe(10)
}, { retry: 10 })
```

but for this scenario, it will not.
```
describe('description retry', () => {
  let count4 = 0
  it('retry test fails', () => {
    count4 += 1
    expect(count4).toBe(10)
  })
}, { retry: 10 })
```

The question is. Should the `options?: number | TestOptions` from `describe `section propagate to all tests inside, or this is undocumented behavior and vitest does not want to support it?
