### ISSUE TITLE
Ability to filter the stack trace

### ISSUE THREAD

**Issue by aleclarson** [vitest-dev/vitest#1999]
### Clear and concise description of the problem

In some cases, stack traces contain a bunch of lines from third party packages, and I would prefer to omit those lines from the stack trace, as it's extremely unlikely that I need to be aware of them.

### Suggested solution

Add an option like `filterStack` that takes a function that receives a file path and returns a boolean to indicate whether the stack frame should be removed from the trace. This is what I do in Saus (my Vite-based framework), and [it works great](https://github.com/alloc/saus/blob/next/src/core/vm/formatAsyncStack.ts#L63).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by g4rry420** [comment]
@aleclarson Can you please update this link - [it works great](https://github.com/alloc/saus/blob/next/src/core/vm/formatAsyncStack.ts#L63). ? I wanted to take a look into it.

**Comment by sheremet-va** [comment]
Vitest already parses error stack traces, so this feature should be straightforward to implement. We can do the same thing we did for console log filtering: https://vitest.dev/config/#onconsolelog

```ts
export default defineConfig({
  test: {
    onStackTrace({ method, file, line, column }) {
      if(file.includes('unexpected')) return false
    }
  }
})
```
