### ISSUE TITLE
Vitest filtering not support relative path with YARN.

### ISSUE THREAD

**Issue by mokeyish** [vitest-dev/vitest#2017]
### Describe the bug

![图片](https://user-images.githubusercontent.com/16131917/189466348-22c735ba-b936-4aac-913e-24c59b51d129.png)

### Reproduction

stackblitz https://stackblitz.com/edit/vitest-dev-vitest-ezv4ju

- ok
   ```shell
   yarn test some.spec.ts
   ```

   ```shell
   npm run test some.spec.ts
   ```
- error
   ```shell

   yarn test ./test/some.spec.ts
   ```

### System Info

```shell
System:
    OS: Linux 5.10 Kali GNU/Linux Rolling 2022.3
    CPU: (64) x64 AMD Ryzen Threadripper 3970X 32-Core Processor
    Memory: 22.72 GB / 31.28 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  npmPackages:
    vite: ^3.1.0 => 3.1.0 
    vitest: ^0.23.1 => 0.23.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Filtering is just a regexp against all files, it doesn't suppose to work like that by design
