### ISSUE TITLE
Errors from running Vite nodejs tests

### ISSUE THREAD

**Issue by ydcjeff** [vitest-dev/vitest#202]
I tried to migrate Vite nodejs tests to Vitest. Half of them passed and half failed.

I don't know how to debug this, so make a report here.

Reproduction: https://github.com/ydcjeff/vite/tree/test/vitest

Reproduction steps:
- pnpm i
- cd packages/vite && pnpm run dev
- pnpm run test-serve (2nd terminal)

Error trace:

![Screen Shot 2021-12-17 at 22 38 35](https://user-images.githubusercontent.com/32727188/146573905-2b1aecd6-c6b5-492f-a340-275b9b577d30.png)

**Comment by ydcjeff** [comment]
The last error from the screenshot can be fixed by adding `exports` field in `totalist` `package.json`.

**Comment by antfu** [comment]
Try add `define: { "process.env.NODE": "process.env.NODE" }` in vitest.config

And add `totalist` to `test: { deps: { inline: ['totalist'] }}}`

**Comment by ydcjeff** [comment]
unfortunately, it didn't work.

**Comment by atk** [comment]
Shouldn't it be `define: { "process.env.NODE": process.env.NODE }`?

**Comment by vinothvk** [comment]
I am also seeing this 'Directory import xyz is not supported resolving ES Modules imported from' error
tried using deps.inline and it didn't help

**Comment by sheremet-va** [comment]
So, I found that we always replace `NODE_ENV` because of this: https://github.com/vitejs/vite/blob/3480f27d4db7f7ebd27164d9185e7b387762274e/packages/vite/src/node/plugins/clientInjections.ts#L52

@antfu do you have any ideas how we can bypass this? I wanted to redefine `define` config in Vitest plugin - instead of replacing it statically, I wanted to put them on global, so people can reassign them in tests. Right now this is impossible to do with `NODE_ENV`

**Comment by antfu** [comment]
We could just remove the `vite:client-inject` plugin in configResolve to see if it fixes the issue

**Comment by sheremet-va** [comment]
> We could just remove the `vite:client-inject` plugin in configResolve to see if it fixes the issue

It failes, because `/@vite/env` depends on it.

**Comment by sheremet-va** [comment]
> Maybe we could split `vite:client-inject` in Vite core in two plugins so we only get `__DEFINES__` for Vitest
> 
> Or actually, we could remove `vite:client-inject` and add a copy of it in Vitest that only injects `__DEFINES__`?

I like your first idea more :P

**Comment by sheremet-va** [comment]
Is this still a problem?

**Comment by ydcjeff** [comment]
This is no longer a problem since
- https://github.com/vitejs/vite/pull/8040
