### ISSUE TITLE
Give more useful error messages on exceptions

### ISSUE THREAD

**Issue by jez9999** [vitest-dev/vitest#2030]
### Clear and concise description of the problem

As a developer using Vitest I want clear errors during the development of test specs so that I can see which file and line I've made a mistake on.  I'll often write tests along the lines of:

```
describe('test data truthy', () => {
	// Arrange
	const testData = new Testdata(1, -2, 1);

	// Act
	testData.doThing();

	// Assert
	it('behaves correctly', () => {
		expect(testData.result).toBeTruthy();
	});
});
```

If I get an exception during any time, especially during Arrange or Act, vitest just displays an "unhandled errors" message which doesn't even tell me which test file the error occurred in.

### Suggested solution

Vitest should give the file, line number, and exception error message if an unhandled exception occurs during tests.  In addition, the unhandled error causes the test monitor to stop monitoring the file.  Once the file is fixed, the monitor should continue to detect changes to the file and re run the tests when it's saved.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
> Vitest should give the file, line number, and exception error message if an unhandled exception occurs during tests

It's unhandled, the only thing we can provide is stack trace, and we already do that, otherwise we would be able to catch it.

**Comment by jez9999** [comment]
@sheremet-va I might be misunderstanding how JS works, but that test is executing in an arrow function callback.  Can't that be wrapped and errors from it caught?

**Comment by jez9999** [comment]
Argh, I think this may be because I was using a slightly old version of Vitest for some reason.  Switched to the latest version and it deals with the error better and keeps watching for file changes.
