### ISSUE TITLE
Vitest reports 'No test suite found in file' when run from within VS2019 build/publish

### ISSUE THREAD

**Issue by jez9999** [vitest-dev/vitest#2032]
### Describe the bug

When I run Vitest as part of my VS2019 project build, Vitest apparently can't find my test suites.  It works fine if I run from the commandline:

```
npm run test:unit:nowatch

> myapp@1.0.0 test:unit:nowatch
> vitest run --no-color --environment jsdom


 RUN  v0.23.2 C:/Development/MyApp/MyApp.Web/ClientApp

 ✓ src/lib/__tests__/libHex.spec.js (4)
 ✓ src/components/__tests__/Counter.spec.js (1)

Test Files  2 passed (2)
     Tests  5 passed (5)
  Start at  19:09:04
  Duration  1.64s (transform 533ms, setup 1ms, collect 200ms, tests 13ms)
```

But as part of a VS2019 build/publish, I get the error in the output window:

> Error : No test suite found in file

### Reproduction

Setup a VS2019 project that contains an `npm run` script as part of the build/publish process, ie. a `.csproj` file like:

```
  <Target Name="PublishRunWebpack" AfterTargets="ComputeFilesToPublish">
    <!-- As part of publishing, ensure the JS resources are freshly built in production mode -->
    <Exec WorkingDirectory="$(SpaRoot)" Command="npm run test:unit:nowatch" />
```

... with a `package.json` containing:

```
"scripts": {
  "test:unit:nowatch": "vitest run --no-color --environment jsdom"
}
```

And try to publish.

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
    Memory: 3.66 GB / 15.64 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (105.0.1343.33)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @vitejs/plugin-vue: ^3.0.1 => 3.1.0
    vite: ^3.0.4 => 3.1.0
    vitest: ^0.23.0 => 0.23.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest now throws an error, if two Vitest versions are installed.
