### ISSUE TITLE
Provide nuxt module

### ISSUE THREAD

**Issue by tobiasdiez** [vitest-dev/vitest#2044]
### Clear and concise description of the problem

If one uses vitest with nuxt, one encounters a couple of issues:
- `alias` are not resolved correctly
- auto-import of components is not working
- config needs to be specified in `vite.config.ts` instead of `nuxt.config.ts`

### Suggested solution

Provide a [Nuxt module](https://v3.nuxtjs.org/guide/going-further/modules/) that takes care of these issues by forwarding the nuxt config to vitest.

### Alternative

Manual config with workarounds such as https://github.com/nuxt/framework/discussions/5379#discussioncomment-2942984

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I don't think that's Vitest responsibility, to be honest. SvelteKit provides a way to test its components just fine. Vitest doesn't have any "unconventional" functionality. If Nuxt could provide `vite.config`, other tools could reuse it.

Even if it's impossible, I don't think Vitest team should support each and every framework that wants to use Vitest. We are open to make any API that might be required for frameworks to work though. For example, Nuxt team could add `nuxt test` command and pass generated config from `.nuxt` folder.

**Comment by pi0** [comment]
Nuxt CLI has `nuxi test` command with vitest first-class support. We are improving testing support but indeed it makes sense that this command is by frameworks rather than embedding into vitest.

**Comment by tobiasdiez** [comment]
@pi0 please correct me, but `nuxi test` is more for integration testing, right? As of now, I only want to run simple unit tests via vitest that don't require a full built of nuxt. Is this currently supported with `nuxi test`?

**Comment by tobiasdiez** [comment]
Thanks for the explanation. Makes sense! I've opened https://github.com/nuxt/framework/issues/7672 to keep track of this (hopefully I didn't miss an already existing issue again 🙄 )
