### ISSUE TITLE
vitest crashes silently with long async test on windows 

### ISSUE THREAD

**Issue by dkent600** [vitest-dev/vitest#2045]
### Describe the bug

vitest crashes silently with long async test.  Such a test looks like the one provided below.  The test run includes this test plus others.  It is only with the inclusion of this test that the crash happens.  The test run aborts without reporting an error nor any other kind of result.  The crash is intermittent and does not always happen at the same place during the run.

The `testTimeout` config setting should be set high enough to easily allow the "simple example" test given below to run without timing out.

```
import { describe, expect, it } from 'vitest';

describe('simple example', () => {
  it('sleeps for 10 seconds', () => {
    return new Promise((resolve: (args: unknown[]) => void): unknown => setTimeout(resolve, 10000)).then(() => expect(true));
  });
});
```

### Reproduction

On Windows PowerShell (I haven't tried elsewhere):

1) clone this: https://github.com/Kolektivo/kolektivo-dapp/tree/vitest-crash
2) run `npm ci`
3) run `npm run test`

If it doesn't reproduce the first time, try a few more times.  It is intermittent, maybe 50-50.  When it fails it will stop without reporting the final summary results of the run.

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 14.90 GB / 31.68 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (105.0.1343.33)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vite: ^3.1.0 => 3.1.0
    vitest: ^0.23.1 => 0.23.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dkent600** [comment]
When I run in Git Bash I often see this being issued upon abort in the same place where the abort happens in PowerShell:

`/c/Program Files/nodejs/npx: line 48:  1860 Segmentation fault      "$NODE_EXE" "$NPX_CLI_JS" "$@"`

**Comment by mrspartak** [comment]
Have kinda same issue. Tests were developed on Mac and running fine, but on Windows server 2022 I get 'Segmentation fault'
This is the only message I get 

```
> vitest run --dir=./test/

 RUN  v0.24.3 C:/Users/***

/c/Program Files/nodejs/npm: line 37:  2046 Segmentation fault      "$NODE_EXE" "$NPM_CLI_JS" "$@"
```

**Comment by kaminskypavel** [comment]
might be related https://github.com/vitest-dev/vitest/issues/2415

**Comment by moishinetzer** [comment]
Same issue happening to me - Any updates?

**Comment by enzoferey** [comment]
Since this is appeared at the top of the Google search, I'm leaving the two things that were causing issues on my side:

1. Not using `it.each` or `test.each` and just looping through an array creating `it` / `test` statements on the fly.
2. My project is not using Vite and I did not have a `vitest.config.ts`, it seems to be one of the three possible options to [configure](https://vitest.dev/config/#configuration) Vitest. I find the get started docs not very clear about this, it should be mentioned right below the installation command if you ask me.

**Comment by sheremet-va** [comment]
The worker threads incompatibilities might cause this. Vitest 2.0 switches to using `child_processes` by default, which makes it more stable. If you are seeing unexpected segfaults or exits, check your [configured pool](https://vitest.dev/config/#pool).
