### ISSUE TITLE
Add an --exact flag to vitest cli

### ISSUE THREAD

**Issue by haikyuu** [vitest-dev/vitest#2046]
### Clear and concise description of the problem

Let's take the following directory for example:
```
timeout.test.ts
each-timeout.test.ts
```
When running `vitest timeout.test.ts`, both test files will run. And that's sometimes an unwanted behaviour.

### Suggested solution

Add a `vitest run --exact` flag that is meant to receive the exact path to the file to test.

### Additional context

Here is an example in Vitest tests themselves that I encountered. And that was a tricky thing to discover 😅

https://github.com/vitest-dev/vitest/blob/95da4d66933db46da368d5d66f422afd26fba4c1/test/fails/test/runner.test.ts

The test runs multiple tests that are supposed to fail for a specific reason. And that reason is save in a snapshot. So when running two tests at the same time instead of one, the wrong reason is picked and the test fails **sometimes**, other times ... it works, depending on the first test to have completed

```diff
  const files = await fg('*.test.ts', { cwd: root })

  for (const file of files) {
    it(file, async () => {
-     await execa('npx', ['vitest', 'run', file])
+     await execa('npx', ['vitest', 'run', '--exact', file])
    })
}
```
That would solve it without having to check 10 files and see if there's an overlap

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
You can just pass down whole file path to Vitest:

```shell
npx vitest /tests/file.test.ts 
```
