### ISSUE TITLE
Broken TypeScript support for 'this' in custom generic matchers

### ISSUE THREAD

**Issue by seangwright** [vitest-dev/vitest#2054]
### Describe the bug

In the [documentation for custom matchers](https://github.com/vitest-dev/vitest/blob/main/docs/guide/extending-matchers.md) it's stated that the `this` of the matchers functions has access to some utility functions.

However, the typings of `expect.extend({})` do not work when the custom matchers are generic functions in TypeScript:

```typescript
expect.extend({
  toBeATypedArray<T>(array1: T[], array2: T[]) {
    const pass = this.equals(array1, array2); // no type support on 'this'!

    return {
      message: () => 'Array 1 equals array 2',
      pass,
    };
  },
});
```

The error that TypeScript provides is as follows:

```
The 'this' context of type 'MatchersObject<MatcherState>' is not assignable to method's 'this' of type 'MatcherState'.
  Type 'MatchersObject<MatcherState>' is missing the following properties from type 'MatcherState': assertionCalls, equals, isNot, environment, and 4 more
```

As soon as I remove the generic constraint on the matcher, the typing errors go away.

This is an issue for me because I've written custom matchers for my library that uses generic container objects which have their own methods and I want to make assertions on those. If I can't make the matchers generic then I can't use my library's types in the matchers.

I'm currently resorting to using `this` as `const eq = (this as any).equals(val1, val2);`

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-q2fenv?file=test/expectExtensions.ts

### System Info

```shell
npx envinfo --system --npmPackages '{vitest,vite,@vitejs/*}' --binaries --browsers

  System:
    OS: Windows 10 10.0.19044
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 16.36 GB / 31.93 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.13.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 105.0.5195.127
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.42), ChromiumDev (107.0.1379.1)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitest: ^0.23.4 => 0.23.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I'm not TS expert, so not sure what can be done here. Technically though you can pass anything to a matcher (if you don't use TS, for example), so I would still use type guards for this, so this is not a blocking issue, as you are describing.

**Comment by seangwright** [comment]
Thanks for the suggestion. I removed the generics and added type guards using `instanceof` which revealed several false positive tests that I needed to fix.
