### ISSUE TITLE
Being able to change Environment per Suite

### ISSUE THREAD

**Issue by Shumuu** [vitest-dev/vitest#2060]
### Clear and concise description of the problem

As far as I know you can only change the Environment your tests run either in the config file OR via docblock comment

config Example
```TypeScript
// vitest.config.ts
export default defineConfig({
  test: {
    environment: 'happy-dom',
  },
});
```

Inside Test File Example

```TypeScript
// some test file
// @vitest-environment node
// now this test file will run in the node environment
```

While this does the job *just fine* it is less than ideal since you need to create two test files.

### Suggested solution

I'd like to be able to change the Environment on a per Suite (`describe`) basis.

### Additional context

I am currently working on a [Remix](https://remix.run/) Project where a file could both run in the Browser AND the Server Environment. 

Since I need to verify [IBAN](https://en.wikipedia.org/wiki/International_Bank_Account_Number) in both Browser and the Server, I needed to access the `BigInt` Property. In the Browser I check if it is available on the window Object  (`window.BigInt`) which fails in the Server Enviroment. So I wrote a check if I am in the Browser Environment. To test both Environments I needed to create two test files which I think is bothersome and prone to Errors.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Sorry, but this will not be supported due to technical complexity we don't want to bring into Vitest.

I would recommend creating two separate files: `test.server.spec.ts`, `test.browser.spec.ts`

**Comment by Shumuu** [comment]
That's too bad! Thanks anyway
