### ISSUE TITLE
Error: Not implemented: window.computedStyle(elt, pseudoElt)

### ISSUE THREAD

**Issue by fikryfahrezy** [vitest-dev/vitest#2061]
### Describe the bug

Vitest show `Error: Not implemented: window.computedStyle(elt, pseudoElt)` while Jest not.

I'm about to migrate my react app with [Ant Design](https://ant.design/) from Jest to Vitest, after I'm done following [migration guide](https://vitest.dev/guide/migration.html#migrating-from-jest) and try run the new test with Vitest, Vitest show the error message come from JSDOM.

The error message only show if I test the the specific Ant Design component (Table in this case).

### Reproduction

https://github.com/fikryfahrezy/my-react-app

Run test with Jest

`yarn test:jest src/index.jest.test.tsx`

Run test with Vitest

`yarn test:vitest src/index.vitest.test.tsx`

### System Info

```shell
System:
    OS: Linux 5.19 undefined
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 6.58 GB / 19.39 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 14.20.0 - /run/user/1000/fnm_multishells/390656_1663662564383/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 6.14.17 - /run/user/1000/fnm_multishells/390656_1663662564383/bin/npm
  Browsers:
    Brave Browser: 105.1.43.89
    Firefox: 103.0.2
  npmPackages:
    @vitejs/plugin-react: ^2.1.0 => 2.1.0 
    vite: ^3.1.0 => 3.1.3 
    vitest: ^0.23.4 => 0.23.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I don't know what Jest does under the hood, but this is normal JSDOM behaviour as far as I understand. Try workaround from this thread: https://github.com/nickcolley/jest-axe/issues/147

**Comment by fikryfahrezy** [comment]
The error not showing after try the workaround from [NickColley/jest-axe/#147](https://github.com/NickColley/jest-axe/issues/147).

Thanks @sheremet-va for your help.
