### ISSUE TITLE
Mock importing undefined not mocked value

### ISSUE THREAD

**Issue by ig-onoffice-de** [vitest-dev/vitest#2067]
### Describe the bug

I want to test a function and mock a custom module with `vi.mock` and `vi.mocked(...).mockReturnValue(...)` but the mock always returns undefined in the tested file (but not in the `.test.ts` file). 
I already tried to add the workaround from !1918

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-gdhswk?file=vite.config.ts

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 3.00 GB / 15.81 GB
  Binaries:
    Node: 18.8.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.42)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-vue: ^3.1.0 => 3.1.0
    vite: ^3.1.3 => 3.1.3
    vitest: ^0.23.4 => 0.23.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Well, you mock the call after the module is already evaluated. You need to use `await import('../src/withI18nMessage')`, or mock a call inside `vi.mock`.

**Comment by ig-onoffice-de** [comment]
Ups, thanks for your help! 👍
