### ISSUE TITLE
SyntaxError: The requested module 'vue' does not provide an export named 'BaseTransition'

### ISSUE THREAD

**Issue by bittermeatball** [vitest-dev/vitest#2082]
### Describe the bug

I am not able to run component testing in the project using `nuxt-edge`:

- `nuxt-edge@lastest`
- `vitest@^0.23.4`
- `@vue/test-utils@^2.0.2`

The application is super simple and newly created using `yarn create nuxt-app` and upgraded to `nuxt-edge` follow this guide:
https://v3.nuxtjs.org/bridge/overview#update-your-scripts

Test script:
```js
import { mount } from '@vue/test-utils'
import NuxtLogo from '@/components/NuxtLogo.vue'

describe('NuxtLogo', () => {
  test('is a Vue instance', () => {
    const wrapper = mount(NuxtLogo)
    expect(wrapper.vm).toBeTruthy()
  })
})

```

The error simply show:
```
SyntaxError: The requested module 'vue' does not provide an export named 'BaseTransition'
❯ ../../../../../../../async C:/Users/Asus/nuxt-edge-test/test/NuxtLogo.spec.js:1:256
```

### Reproduction

I have created a codesanbox reproduction here:
https://codesandbox.io/p/github/bittermeatball/nuxt-edge-vitest-bug-report/draft/quizzical-bell

### System Info

```shell
Package versions:

- `nuxt-edge@lastest`
- `vitest@^0.23.4`
- `@vue/test-utils@^2.0.2`

My PC: Window 10
Node versions: v16.15.0 and v16.17.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by bittermeatball** [comment]
Codesandbox screencapture:
https://codesandbox.io/p/github/bittermeatball/nuxt-edge-vitest-bug-report/draft/quizzical-bell
![image](https://user-images.githubusercontent.com/46400321/192137925-ac29baca-9ed0-4a08-9965-a2309cb0a8ba.png)

**Comment by sheremet-va** [comment]
You are using `@vue/test-utils` for Vue 3 component, but you have Vue 2 installed.

**Comment by bittermeatball** [comment]
Thank @sheremet-va, I missed that we've already switched the whole ecosystem to Vue 3 by default
I resolved this by install the whole Vue 2 pack for the project:
For vite

- `@vitejs/plugin-vue2`
- `@vitejs/plugin-vue2-jsx` (optional)

For vitest component testing

- `@vue/test-utils^1.3.0`
- `@vue/server-test-utils^1.3.0`
