### ISSUE TITLE
Externalize chai Jest compat wrapper into a separate package, e.g. `chai-jest`

### ISSUE THREAD

**Issue by brillout** [vitest-dev/vitest#2089]
### Clear and concise description of the problem

The Jest compatibility layer on top of chai is super nice.

But it cannot be used independently of Vitest.

### Suggested solution

It'd be nice to be able to use it independently of Vitest as an independent package e.g. `chai-jest`. It adds significant value to justify living in its own package.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by roydukkey** [comment]
Feel this might be relevant here too. https://github.com/vitest-dev/vitest/issues/2118#issuecomment-1416159050

**Comment by sheremet-va** [comment]
It's already done as @vitest/expect

**Comment by brillout** [comment]
Neat 😍.
