### ISSUE TITLE
TypeError: i is not a function

### ISSUE THREAD

**Issue by joshnuss** [vitest-dev/vitest#2092]
### Describe the bug

Test fails with error message `TypeError: i is not a function`, and there is no stack trace displayed.

It appears the error is caused when a callback to a hook function (like `beforeEach`, `beforeAll` ) returns certain data types, like an array:

```javascript
// TypeError: i is not a function
beforeEach(() => [])

// but this  is ok
beforeEach(() => Promise.resolve())
```

### Reproduction

https://github.com/joshnuss/vitest-type-error-repro

### System Info

```shell
System:
    OS: Linux 5.15 Linux Mint 20.3 (Una)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 1.33 GB / 15.52 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.15.1 - ~/.asdf/installs/nodejs/16.15.1/bin/node
    npm: 8.11.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 105.0.5195.52
    Firefox: 105.0
  npmPackages:
    vitest: ^0.23.4 => 0.23.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`beforeEach` expects a function to be returned: https://vitest.dev/api/#beforeeach

**Comment by joshnuss** [comment]
`beforeEach` seems to accept return values like `null` or `Promise`.

Two things:
- If other values aren't allowed, a better error message would be helpful.
- The error message didn't contain a stack trace, so it made it harder to debug the issue.

**Comment by sheremet-va** [comment]
> `beforeEach` seems to accept return values like `null` or `Promise`.

cannot reproduce

<img width="879" alt="Screenshot 2022-09-28 at 09 51 56" src="https://user-images.githubusercontent.com/16173870/192721015-8d75efd6-547d-4b8d-a5e9-44566e852737.png">

> If other values aren't allowed, a better error message would be helpful.

Agree

> The error message didn't contain a stack trace, so it made it harder to debug the issue.

Stacktrace leads to internal implementations - we hide those, because otherwise throwing in a test will be bloated.

**Comment by joshnuss** [comment]
> cannot reproduce
I believe you mean you cannot reproduce with TS, but it is reproducible with JS.

> Stacktrace leads to internal implementations - we hide those, because otherwise throwing in a test will be bloated

can you clarify? From a debugging perspective, if something went wrong while invoking `beforeEach`, it would be helpful to know where the error came from. Usually the stack trace helps with that kind of thing.

**Comment by sheremet-va** [comment]
> if something went wrong while invoking beforeEach, it would be helpful to know where the error came from. Usually the stack trace helps with that kind of thing.

If something on your side is going wrong, you will see a stack trace to your code. Here the problem is with Vite internals, so you don't see an error.

**Comment by jherdman** [comment]
This is definitely reproducible with TS. I hit the issue in converting a JS-based test to TS. What tripped me up was the Migration guide's recommendation for a `done` callback: https://vitest.dev/guide/migration.html. If you're not careful you end up with callback that the before hook doesn't like. Perhaps an assertion for the return type with a friendly error message would be useful?

**Comment by kswope** [comment]
Same problem here

seems the promise must return a "void" value or vitest gets confused and barfs out something like 

I think this is hinted at in the docs: Awaitable<void>.
```
Type: beforeEach(fn: () => Awaitable<void>, timeout?: number)
```

To be more clear

works
```
beforeEach(() => Promise.resolve())
```

doesn't
```
beforeEach(() => Promise.resolve("hi!"))
```

probably because of the cleanup function
```
beforeEach(() => Promise.resolve(() => console.log("cleaning up")))
```

So I guess Awaitable<void> is either a promise wrapping a function or nothing?

Probably should check if the returned value is a function before it says incoherent things like "TypeError: i is not a function"

**Comment by joshnuss** [comment]
Thanks @sheremet-va!
