### ISSUE TITLE
Allow test title to be generated by a function

### ISSUE THREAD

**Issue by ycmjason** [vitest-dev/vitest#2093]
### Clear and concise description of the problem

When writing test title, especially for `test.each`, it is important to make both the test cases and title to be descriptive.

Consider:

```ts
it.each([
  [10, 100, 0.2, 800],
  [0, 100, 0, 0],
  ...
])('should calculate the price correctly, given %d apples at cost $%d with %d off, to be $%d') => { ... })
```

As seen from the previous example, the test cases aren't very descriptive and could be confusing to maintain. 

Consider:

```ts
it.each([
  [{ appleAmount: 10, applePrice: 100, discount: 0.2 }, 800],
  ...
])('should calculate correct price', () => {...})
```

Now the test cases are more descriptive, but it is tricky to format the title properly.

### Suggested solution

I suggest allowing `test` / `it` to accept a function that returns a `string` for generating the titles.

Suggested API:

```ts
it(() => `should be ${amazingThing}`, () => {...})
```

With `it.each`:
```ts
it.each([
  [{ appleAmount: 10, applePrice: 100, discount: 0.2 }, 800],
  ...
])(
  ({ appleAmount, applePrice, discount }, expectedPrice) =>
    `should calculate the price correctly, given ${appleAmount} apples at cost $${applePrice} with ${discount} off, to be $${expectedPrice}`,
  () => {},
);
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
You can use `$` syntax (https://vitest.dev/api/#describe-each):
```ts
it.each([
  [{ appleAmount: 10, applePrice: 100, discount: 0.2 }, 800],
  ...
])('should calculate correct price with $appleAmount and $applePrice', () => {...})
```

Documented for `describe.each`, but is not documented for `test.each` for some reason. PR welcome.
