### ISSUE TITLE
Symbol can't be imported

### ISSUE THREAD

**Issue by mattaiod** [vitest-dev/vitest#2094]
### Describe the bug

In a TS file `symbol.ts`, I create and export a symbol `AGE`

In a Vue component `component.vue`, I create a variable test with value the symbol imported `AGE`

When I run pnpm test and one of my test mount the component.vue
=> it crashs with the following error: No "AGE" export is defined on the `./symbol.ts`

PS: When I do pnpm dev, all works

### Reproduction

If you want reproduce the bug use my repo:
https://github.com/mattaiod/Vitest-Vue.js---Examples.git
-> pnpm install,  pnpm test 

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Memory: 267.81 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Edge: 105.0.1343.53
    Firefox: 94.0.2
    Safari: 15.6
  npmPackages:
    @vitejs/plugin-vue: ^3.1.0 => 3.1.0 
    vite: ^3.1.3 => 3.1.3 
    vitest: ^0.23.4 => 0.23.4
```

### Used Package Manager

pnpm

### Validations

- [ ] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It fails, because you mock a module, but don't specify all used variables. This error is for debugging.

Please, refer to documentation about vi.mock. IT ID HOISTED, meaning it doesn't matter where you call it, it's always evaluated before all imports.
