### ISSUE TITLE
Multiple Benchmarks don't run in description blocks

### ISSUE THREAD

**Issue by hmt** [vitest-dev/vitest#2097]
### Describe the bug

Consider this code from https://github.com/SVWS-NRW/SVWS-Server:

```ts
describe.skip.each([s, n, l])(
	"java.util.Vector, getestet mit $name",
	({ a, b, c, d, e }) => {
		beforeEach(() => {
			v = new Vector();
			v.add(a);
			v.add(b);
			v.add(c);
			v.add(d);
			v.add(e);
		});
		bench( "Array from", () => {
				Array.from(v);
			}, { iterations: 500 });

		bench( "toArray", () => {
				v.toArray();
			}, { iterations: 500 });
	}
);
```

It will run but fail:
<img width="416" alt="Screenshot 2022-09-28 at 11 37 38" src="https://user-images.githubusercontent.com/1246495/192953618-0b128a58-a0ab-404b-93a7-92bd318148bc.png">

### Reproduction

Repo from above, in directory `SVWS-Server/svws-webclient/src/ts-lib-test/ts/` run `npx vitest bench` to see the error

### System Info

```shell
envinfo@7.8.1
Ok to proceed? (y)

  System:
    OS: macOS 12.6
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 948.05 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.9.1 - /usr/local/bin/node
    npm: 8.19.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 106.1.44.101
    Chrome: 106.0.5249.61
    Firefox: 104.0.2
    Safari: 16.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Aslemammad** [comment]
beforeEach is not implemented yet, instead, consider using `setup` and `teardown` options in bench.

**Comment by hmt** [comment]
oh, thank you. Didn't know the different parts had their own implementation. Thank you for looking into it. Your work on vitest is highly appreciated.

**Comment by Aslemammad** [comment]
@hmt I appreciate that, and thank you for creating the issue.
