### ISSUE TITLE
import.meta.env.PROD/DEV vars are strings instead of boolean

### ISSUE THREAD

**Issue by fc** [vitest-dev/vitest#2105]
### Describe the bug

When trying to set `import.meta.env.PROD` to `true` it is set to `"true"` instead.

### Reproduction

Check this branch out, do a build of vitest then go into the example/basics and run pnpm test
https://github.com/fc/vitest/tree/fc/env-vars

The commit itself:
https://github.com/fc/vitest/commit/83ae17872c671e31080b67665ce6039d8ff40952

### System Info

```shell
macos
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Yes, it's impossible to make them boolean as they are converted to `process.env`. Please, try to use falsy/truthy values instead of boomean.

**Comment by sheremet-va** [comment]
It is because Node doesn't allow `process.env` to be anything but boolean.
