### ISSUE TITLE
Benchmark results are off by 3 orders of magnitude

### ISSUE THREAD

**Issue by FINDarkside** [vitest-dev/vitest#2109]
### Describe the bug

Bencmark result are wrong by many orders of magnitue. The operations/sec might be operations/millisec or something else.

### Reproduction

```ts
import { bench, describe } from 'vitest';

describe('Deserialize', async () => {
  bench('1ops', async () => {
    await new Promise((res) => setTimeout(res, 1000));
  });
  bench('2ops', async () => {
    await new Promise((res) => setTimeout(res, 500));
  });
  bench('10ops', async () => {
    await new Promise((res) => setTimeout(res, 100));
  });
  bench('100ops', async () => {
    await new Promise((res) => setTimeout(res, 10));
  });
});
```

Result:

```
 ✓ test/test.bench.ts (4) 15126ms
   ✓ Deserialize (4) 15123ms
     · 1ops    0.0010 ops/sec ±0.76% (10 samples) slowest
     · 2ops    0.0020 ops/sec ±1.08% (10 samples)
     · 10ops   0.0092 ops/sec ±2.31% (10 samples)
     · 100ops  0.0641 ops/sec ±1.77% (33 samples) fastest```

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 6.47 GB / 15.93 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 105.0.5195.127
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.53)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-vue: ^3.0.3 => 3.1.0
    vite: ^3.0.8 => 3.1.3
    vitest: ^0.23.4 => 0.23.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Aslemammad** [comment]
These issues are solved in the last version of Tinybench.
