### ISSUE TITLE
Vitest cannot load test environment variables

### ISSUE THREAD

**Issue by Leoff00** [vitest-dev/vitest#2123]
### Describe the bug

I was searching a way to create environment test variables to test my *DB* in a different environment, i read the documentation and follow step-by-step of what was written, but when i try to run my script throws an error saying that i the vitest can't load the environment variable, however i don't know if this is a bug or it really can't possible to do. 

The doc: https://vitest.dev/guide/environment.html

the file: 
```ts
import { resolve } from "path";
import dotenv from "dotenv";
import type { Environment } from "vitest";

dotenv.config({
  path: resolve(__dirname, "./.env.test"),
});

export default <Environment>{
  name: "TEST_ENV",
  setup() {
    const connectionString = process.env.DATABASE_URL;
    global.process.env.DATABASE_URL = connectionString;

    return {
      teardown() {
        // called after all tests with this env have been run
      },
    };
  },
};

```

Picture below 👇

![image](https://user-images.githubusercontent.com/66839023/194431680-a992daac-a343-4edb-8acd-518e35cee424.png)

### Reproduction

```sh 
vitest __tests__/integrations run --coverage
```

### System Info

```shell
What version of vitest are you using?
^0.23.1

What version of Node.js are you using?
18.4.0

What operating system are you using?
Windows 10

What CPU architecture are you using?
x86_64

What Node versions, OSs and CPU architectures are you building for?
node14-win-arm64
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by azaleta** [comment]
Do you make it as a package?

A ref for you
https://github.com/azaleta/vi-env

1. build env package `vitest-environment-cust`
2. run the test in `test-app`

**Comment by Leoff00** [comment]
> 

Yes! I do, but when i confirm the build of the package vitest give me another error. 
Picture below 👇
![image](https://user-images.githubusercontent.com/66839023/194627983-0d218cfa-29a5-49d2-a0fd-127ac3c93234.png)

**Comment by azaleta** [comment]
in your picture
the first line showing you are access remote registry for download you env package.
if you want to do this, you could publish your env package to npm registry .

In my case I use pnpm workspace and just link them at local.
env + main app as a mono repo
so you could build env first then link it to your main app by package.json

**Comment by Leoff00** [comment]
Bro I'm so sorry about my late reply! I'll try to do what you advised, and if i can resolve, then i'll close the issue, thanks for you time!

**Comment by Leoff00** [comment]
UPDATE: I finally can run the test environment with you advice @azaleta, I just remove my custom env from the vite.config, include my test environment docblock and also figured out that is optional publish the test environment (I really don't know if this information is even in the vitest docs, but i'll leave the solution in the gist), but again, thanks for your advice! i'm closing this issue.

Gist link: https://gist.github.com/Leoff00/7449abda3cb784676c3b4318e8fb8dba
