### ISSUE TITLE
Errors in benchmarks are displayed as `Unknown Error: undefined`

### ISSUE THREAD

**Issue by nickmccurdy** [vitest-dev/vitest#2134]
### Describe the bug

It seems like if a benchmark throws an error, Vitest doesn't properly print its name and stack trace, as I'd expect from a Vitest test.

### Reproduction

```js
import { bench } from "vitest";

bench("Throwing error", () => {
  throw new Error("Example");
});
```
```
 FAIL  test/basic.bench.ts [ test/basic.bench.ts ]
Error: Transform failed with 1 error:
/project/sandbox/test/basic.bench.ts:3:30: ERROR: Unexpected "throw"

 RERUN  test/basic.bench.ts x3

 ✓ test/basic.bench.ts (1) 775ms
   · Throwing error  218.04 ops/sec ±0.71% (109023 samples) fastest

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/basic.bench.ts [ test/basic.bench.ts ]
Unknown Error: undefined


⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
```
https://codesandbox.io/p/sandbox/vitest-benchmark-throwing-error-s1uxfk?file=%2Ftest%2Fbasic.bench.ts

### System Info

```shell
System:
    OS: Linux 5.4 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 AMD EPYC
    Memory: 380.22 MB / 1.95 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/pitcher/bin/yarn
    npm: 8.15.0 - /opt/pitcher/bin/npm
    Watchman: 20220528.183901.0 - /usr/local/bin/watchman
  npmPackages:
    vite: latest => 3.1.7 
    vitest: latest => 0.24.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by poyoho** [comment]
It is seem to fixed
