### ISSUE TITLE
vitest alias not working as expected?

### ISSUE THREAD

**Issue by jclaessens97** [vitest-dev/vitest#2135]
### Describe the bug

To prevent larger relative imports in the form of `../../../something` I configured my `tsconfig` to work with path aliasing. It works when running the app, but it doesn't work when using vitest.

I did configure `resolve.alias` however as I found in a couple of examples, but it doesn't seem to change anything.

### Reproduction

https://github.com/jclaessens97/vitest-alias-repro

### System Info

```shell
Jeroens-MacBook-Pro in vitest-alias-repro on  main via  v18.10.0 on ☁️  (eu-west-1)
✖ envinfo --system --npmPackages '{vitest,vite,@vitejs/*}' --binaries --browsers

  System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 504.02 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.10.0 - ~/.asdf/installs/nodejs/18.10.0/bin/node
    npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 15.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
@jclaessens97 replace your alias with `"@/": path.resolve(__dirname, "./src/"),`. Your current one (`@`) replaces every `@` with a path (including, `@prisma`).

**Comment by jclaessens97** [comment]
To recap (from the linked issue):

I've tried changing the alias to the above (which makes a lot of sense). Although the issue remains. Apparently it's not a vitest issue, but a node issue, however I can't seem to resolve it, even with `deps.registerNodeLoader: true`.

My current `vitest.config.ts`:

```typescript
import path from 'path';
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    deps: {
      registerNodeLoader: true,
    },
  },
  resolve: {
    alias: {
      '@/': path.resolve(__dirname, './src/'),
    },
  },
});
```

I also changed the import of app in my test to use the alias '@/app'. This leads to getting the error earlier than the `@/db` one. I'm guessing I still miss some configuration one way or the other but I'm totally at a loss of how to debug it.

I updated the repro with the latest changes.

**Comment by azaleta** [comment]
![image](https://user-images.githubusercontent.com/22554452/195253685-3e8747f3-74ba-4aba-993f-f3ee163bd70f.png)
```
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src/'),
    },
  },
```

this works fine. 
(just get the no fetch implement and no import error)
PS: I am running on windows.

**on the other hand
`  '@/': path.resolve(__dirname, './src/'),` could not be recognize.(don't know why, that's upstream thing)**

may be you should use regex
```
  resolve: {
    alias: [{
      find: new RegExp('@/'), replacement: *****,
    }],
  },
```

**Comment by jclaessens97** [comment]
I just tested it out with the following regex, and I still get the same error.
I am running on macOS though...

```
    alias: [
      // {
      //   find: new RegExp('@/'),
      //   replacement: path.resolve(__dirname, './src'),
      // },
      {
        find: new RegExp('^@/(.*)$'),
        replacement: path.resolve(__dirname, './src/$1'),
      },
    ],
```

![image](https://user-images.githubusercontent.com/10177148/195274219-ad25465a-eb1d-40b7-9505-ab4231f90723.png)

**Comment by azaleta** [comment]
Sorry for my poor english.
What I mean is vitest `alias` is works fine.  (I updated node to v18 and get the same error as you)
If you check the error message, it comes from `fastifyAutoload`
I guess this pkg override vitest config.

If you comment out `app.register` part in app.ts
and run the test, you can see it go to `atferAll`  this means test is be executed.

Also the request log (404 by the way) as well
```
{"level":30,"time":1665564148527,"pid":28424,"hostname":"LAPTOP-FJFO7FCV","reqId":"req-1","res":{"statusCode":404},"responseTime":7.248600006103516,"msg":"request completed"}
```

![image](https://user-images.githubusercontent.com/22554452/195296410-b7bc1da8-6e9e-4f27-995b-697b790e072b.png)

**Comment by jclaessens97** [comment]
Ahhh alright, gotcha! Thanks for taking the time.
