### ISSUE TITLE
Restart tests when the watcher finds changes

### ISSUE THREAD

**Issue by nickmccurdy** [vitest-dev/vitest#2136]
### Clear and concise description of the problem

Vitest continues running old code, even when I edit the tests to something new. This makes it longer than it needs to be to see results of tests (and especially slower benchmarks) in the browser.

### Suggested solution

Vitest should restart tests when their code (or source code they import) is changed on disk.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
So, current workflow is:

- Tests are running
- Change source code
- Start running tests
- Change source code again
- Still running tests against previous change
- Stop running tests
- Start running tests agains previous change

And you want this:

- Tests are running
- Change source code
- Stop running tests
- Start running tests agains new code

**Comment by nickmccurdy** [comment]
Yes. And if it’s running tests against the previous version twice, I suppose this is a performance bug rather than just a feature request.

**Comment by sheremet-va** [comment]
This is implemented as far as I know.
