### ISSUE TITLE
Regression: generateScopedName ignored by vitest

### ISSUE THREAD

**Issue by Doeke** [vitest-dev/vitest#2146]
### Describe the bug

Upgrade from vitest 0.18.1 to 0.24.1 causes my tests fail because generateScopedName setting is being ignored.

Possibly caused by this PR: https://github.com/vitest-dev/vitest/pull/1803

I tried setting classNameStrategy to 'scoped' which should make it respect generateScopedName but it doesn't work

In the reproduction link below, tests fail unless you downgrade vitest version (eg to 0.18.1): 

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-fdmmn9?file=package.json

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 2.66 GB / 15.33 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    npm: 8.18.0 - ~/.nvm/versions/node/v14.19.1/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
  npmPackages:
    @vitejs/plugin-vue: ^3.1.2 => 3.1.2 
    vite: ^3.1.7 => 3.1.7 
    vitest: ^0.24.1 => 0.24.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is not a regression. You need to use `css.include` option, if you want your files to gow through Vite pipeline instead of being mocked.

**Comment by Doeke** [comment]
Thanks, with this I can get my generated class names to work again:

```
css: { modules: { classNameStrategy: 'scoped' }, include: /.*/ },
```

Imo by default generated class names during tests should be the same as in production to avoid issues going undetected but w/e
