### ISSUE TITLE
Port some matchers from jest-extended

### ISSUE THREAD

**Issue by silverwind** [vitest-dev/vitest#2148]
### Clear and concise description of the problem

[jest-extended](https://jest-extended.jestcommunity.dev/docs/matchers/) brings many useful additional matchers, and while it's already possible to use it to extend vitest's `expect`, I'm wondering if there is any willingness to include a few more basic matchers from it into vitest itself because jest-extended is rather heavyweight.

I'm primarily looking at very simple matchers like [.toStartWith(prefix)](https://jest-extended.jestcommunity.dev/docs/matchers/string/#tostartwithprefix), [.toInclude(substring)](https://jest-extended.jestcommunity.dev/docs/matchers/string/#toincludesubstring) or the type matchers like [.toBeNumber()](https://jest-extended.jestcommunity.dev/docs/matchers/number/#tobenumber).

### Suggested solution

Port over a few of the generally useful matchers from jest-extended.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
What are "generally useful" matchers, and why should they be in a core? If community wants to have a light weight jest-extended package, let them create one. We might mention it in a docs.

**Comment by silverwind** [comment]
There are of course no hard rules on which matchers are generally useful, but for example

```js
expect('string').toStartWith('string')
```

feels more "natural" because it's like `String.prototype.startsWith` than the regexp alternative vitest offers:

```js
expect('string').toMatch(/^string/).
```

**Comment by silverwind** [comment]
Actually, I think `jest-extended` is already [reasonably lightweight](https://packagephobia.com/result?p=jest-extended) and with https://github.com/jest-community/jest-extended/pull/520, it should now also not pull in `jest` any more via `peerDependencies` like it previously did.

So I'm personally happy with keeping it as a dependency with vitest.
