### ISSUE TITLE
TypeError: Unknown file extension ".wasm"

### ISSUE THREAD

**Issue by sqrtsanta** [vitest-dev/vitest#2150]
### Describe the bug

Vitest fails with an error `TypeError: Uknown file extension ".wasm"` if I use url-import with external packages:

```ts
import wasmSrc from 'jsmpeg-lite/jsmpeg.wasm?url';

export function builder() {
  return {
    id: 'aaaa-bbbb-cccc-dddd',
    wasmSrc,
  };
}
```

Meanwhile Vite works perfectly generating url for that wasm file. You can run `npm run dev` in provided StackBlitz link and check console.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-eagna5

### System Info

```shell
System:
    OS: Linux 5.18 Fedora Linux 36 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 18.80 GB / 31.10 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
Browsers:
    Chrome: 103.0.5060.114
    Firefox: 105.0.2
npmPackages:
    @vitejs/plugin-react: ^2.1.0 => 2.1.0
    vite: ^3.1.7 => 3.1.8
    vitest: ^0.24.1 => 0.24.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dannygoldstein** [comment]
Also hitting this

**Comment by MTRNord** [comment]
I am also hitting this

**Comment by sheremet-va** [comment]
As a temporary workaround, you can add this to your config file:

```ts
export default {
  test: {
    deps: {
      inline: [/\?url$/],
    },
  }
}
```
