### ISSUE TITLE
Upgrade from 0.14.2 to 0.24.3 results in "MISSING DEP  Can not find dependency '@vitest/coverage-c8'"

### ISSUE THREAD

**Issue by kpturner** [vitest-dev/vitest#2152]
### Describe the bug

We use `renovate` in GitHub qhich suggest we should make this upgrade - but if we do then running tests with vitest with `--coverage` then fail with `MISSING DEP  Can not find dependency '@vitest/coverage-c8'` with no obvious clue where.  I guess we could simply install this package - but if it is a dependency shouldn't vitest include it automatically? 

### Reproduction

Upgrade from 0.14.2 to 0.24.3 then run tests with `--coverage` option.

### System Info

```shell
System:
    OS: macOS 11.6.8
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 295.07 MB / 16.00 GB
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> Upgrade from 0.14.2 to 0.24.3 then run tests with `--coverage` option.

This is not a reproduction.

> I guess we could simply install this package - but if it is a dependency shouldn't vitest include it automatically?

I don't know if you tried running it locally, but it usually gives a prompt: https://vitest.dev/guide/coverage.html#coverage-providers. Just install the package, it's optional - we cannot bundle it with Vitest.

**Comment by AriPerkkio** [comment]
Just want to add that this was intentional breaking change in `v0.22.0`. https://github.com/vitest-dev/vitest/releases/tag/v0.22.0

You should see this mentioned in changelogs of Renovate's PR.

**Comment by kpturner** [comment]
Ok thanks that’s very useful info
