### ISSUE TITLE
"Patterns must be a string" error when passing `undefined` to `include` option

### ISSUE THREAD

**Issue by thetarnav** [vitest-dev/vitest#2153]
### Describe the bug

The types for the `include` and `exclude` options allow for passing `undefined` as the value.
This is very nice since it allows for applying the option conditionally very easily.
```ts
{
  include: testSSR ? ["server.test.{ts,tsx}"] : undefined
}
```
But this error appears in the console when trying to do this
```
TypeError: Patterns must be a string (non empty) or an array of strings
```
As a walkaround, I can do this, but it doesn't seem intentional...
```ts
{
  ...(testSSR && { include: ["server.test.{ts,tsx}"] })
}
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-atexbn?file=vite.config.ts

### System Info

```shell
System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 920.68 MB / 7.79 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (106.0.1370.42)
    Internet Explorer: 11.0.19041.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
What exactly are you trying to do with undefined?

**Comment by thetarnav** [comment]
To not set the value.
I want to conditionally apply this option, if the condition is true—limit the included files, if it's not—leave it as default.
To be more specific, I'm deciding which tests to run by running cli command with a `--mode ssr` flag. To run normal tests, or ssr tests with appropriate settings.
I could just split it up to two separate files with one config each, but it's just more concise this way 🤷‍♂️
Here is the entire config: https://github.com/solidjs-community/solid-primitives/pull/233/files#diff-6659eb66c30f408e5a440486e7e473bff2673b66a23bea1e8dcf93509ac3ebb8

**Comment by sheremet-va** [comment]
> I want to conditionally apply this option, if the condition is true—limit the included files, if it's not—leave it as default.

Then as another temporary solution, you can use `configDefaults` from `vitest/config`.

I think the problem comes from us merging configs:

```ts
{
  ...defaultConfig,
  ...userConfig
}
```

And since `undefined` is on this object, it gets replaced anyway 🤷🏻

**Comment by thetarnav** [comment]
> Looking at your config, I think better way would be to separate them, since almost all values are different 😄

I'll think about it 😉
