### ISSUE TITLE
Mock + mockImplementation = undefined return value

### ISSUE THREAD

**Issue by ilteoood** [vitest-dev/vitest#2158]
### Describe the bug

With this issue I want to describe a possible bugs of the `mock` function.
If, in the factory function, I use `vi.fn implementation`, `mockReturnValue` or `mockImplementation`, instead of the desired value I obtain `undefined`.

I've reproduced all three cases on stackblitz, using 0.24.3 version: you can find the in the `mock.test.ts` file.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-nccs1u?file=test/mock-with-implementation.test.ts

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    vitest: ^0.24.3 => 0.24.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This has nothing to do with `vi.fn`. `vi.mock` function calls are hoisted (this means that all `vi.mocks` are evaluated BEFORE your imports no matter where you define them in your source code), so it doesn't matter how much time you called it, only one call will be used, when module is imported. This is a bug in your code. If you don't want mock to be hoisted, you can use `vi.doMock`, but you will need to import module again:

```ts
vi.doMock('./transform', () => ({ ... })
const mod = await import('./transform')
```

**Comment by sheremet-va** [comment]
I see now that even when using one mock, it still fails. Will need to investigate, this happens only to mocked modules.

**Comment by ilteoood** [comment]
You are right, it happens only on mocked value.

I understand the hoisting of the mock function, but I expect the mocked return value to be correctly available.

**Comment by sheremet-va** [comment]
> I understand the hoisting of the mock function, but I expect the mocked return value to be correctly available.

You reproduction will always return the same results for all your `test` functions.

**Comment by sheremet-va** [comment]
This is not a bug. You have `restoreMocks: true` in your config file. It removes implementation that was set by `mockImplementation` before each test. If you want to restore "original" implementation, pass it down to `fn`:

```ts
const test2 = vi.fn(() => true)
test2() // true
test2.mockRestore()
test2() // true
```
