### ISSUE TITLE
Run jest test in vitest

### ISSUE THREAD

**Issue by tobiasdiez** [vitest-dev/vitest#2171]
### Clear and concise description of the problem

If you migrate a large test suite from jest to vitest, it would be nice if vitest would be able to run jest tests. This would enable incremental migration to vitest. Moreover, it would support the usage of test suites bundled in installable packages in jest and vitest runners (admittedly, this is a bit of an edge case)

### Suggested solution

Polyfill basic jest functions like `it`, `describe` etc with vitests functions, so that basic tests declared with jest can be run with vitest.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
What do you mean? Can't you just enable `--globals`?

**Comment by tobiasdiez** [comment]
What I would like to have is that running vitest on this jest suite "just works":
```ts
import {describe, expect, test} from '@jest/globals';

describe('sum', () => {
  test('adds 1 + 2 to equal 3', () => {
    expect(1 + 2).toBe(3);
  });
});
```
So when `vitest` encounters a `@jest/globals` import, then it replaces it by an import from vitest (plus some light patching if necessary like for `jest.mock`).

With this, the migration from jest to vitest can look as follows:
- Replace the jest runner by vitest; now all your jest tests are invoked by vitest
- Replace imports from `@jest/globals` by `vitest`, and migrate the tests (if necessary)

Right now you need to do both steps at the same time, and you cannot have a project with "half vitest" and "half jest" tests that are run by vitest.

(Of course, as with any migration tool there shouldn't be put too much work into handling edge cases or e.g. the global setup).

**Comment by sheremet-va** [comment]
Sorry, we will not do that. This is on hands of the community. You can literally just add vi.mock for jest module.
