### ISSUE TITLE
No test suite found in vite.config.js when it's not included in include glob

### ISSUE THREAD

**Issue by haikyuu** [vitest-dev/vitest#2172]
### Describe the bug

No test suite found in vite.config.js when it's not included in include glob. This is caused by `includeSource` since the error is gone when that's commented.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-jqgret?file=vite.config.ts

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 79.06 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Chrome Canary: 109.0.5366.0
    Safari: 15.5
    Safari Technology Preview: 16.4
  npmPackages:
    vite: ^3.1.8 => 3.1.8 
    vitest: ^0.24.3 => 0.24.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Not sure what to do here? You are including a lot of source tests, and `vite.config` is part of glob, and had `"import.meta.vitest"`, so it is treated as a test file, and test files throw error if there are no tests inside.

**Comment by haikyuu** [comment]
Ah, got you.

I think it's safe to exclude `vite.config.{j,t)s` from the glob in that case. Thoughts?

**Comment by sheremet-va** [comment]
> Ah, got you.
> 
> I think it's safe to exclude `vite.config.{j,t)s` from the glob in that case. Thoughts?

Yeah, I guess we can add those to [default excludes](https://github.com/vitest-dev/vitest/blob/3fae52109719a43a52e9a14c0715a3f84583ef37/packages/vitest/src/defaults.ts#L4). PR welcome (we also need to mention it in docs).
