### ISSUE TITLE
can't get prototype methods from sub classing

### ISSUE THREAD

**Issue by JavanShen** [vitest-dev/vitest#2187]
### Describe the bug

i have a class like this:
```TypeScript
// https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement/Audio
class Player extends Audio {
    constructor(xxx) {
        super(xxx)
        this.source = xxx
    }

    loadedData(fn) {
        super.addEventListener('loadeddata', fn)
    }
}
```
then i test it
```TypeScript
// @vitest-environment jsdom

describe('xxx',() => {
    const player = new Player(xxx)

   test('xxx',() => {
        // success
        expect(player).toBeInstanceOf(HTMLAudioElement)
    })

    test('xxx',() => {
        // success
        expect(player.source).toBeTypeOf('string')
        // fail: AssertionError: expected undefined to be type of 'function'
        expect(player.loadedData).toBeTypeOf('function')
    })
})
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-xkawtb?file=test/basic.test.ts

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Memory: 5.03 GB / 15.88 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.674.0), Chromium (106.0.1370.47)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-react: ^2.1.0 => 2.1.0
    @vitejs/plugin-vue: ^3.1.2 => 3.1.2
    @vitejs/plugin-vue-jsx: ^2.0.1 => 2.0.1
    vite: ^3.1.6 => 3.1.6
    vitest: ^0.24.3 => 0.24.3
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I don't think JSDOM supports it: https://github.com/jsdom/jsdom/issues/2155#issuecomment-366703395

Please, open an issue in the environment that you use.
