### ISSUE TITLE
Script fails if contains .css imports via require()

### ISSUE THREAD

**Issue by danielkita** [vitest-dev/vitest#2189]
### Describe the bug

If I try to import a css file via require() I get an error:
```
SyntaxError: expected expression, got '.'
```

Looks like Vitest try to treat CSS like a script. Everything works fine if I try importing the file as a module - I get `undefined` as a value.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-mt1bvg?file=test%2Fdemo.css,test%2Fbasic.test.ts,test%2Fsuite.test.ts&initialPath=__vitest__

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 87.32 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Safari: 16.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by poyoho** [comment]
because `require('.css')` will load not via vite-node.

**Comment by sheremet-va** [comment]
Yes, it's a known limitations, since Vitest doesn't intercept `require` calls and doesn't process it's content to be JavaScript. You can bypass css by adding this to your `setupFiles`:

```ts
require.extensions['.css'] = () => ({})
```

**Comment by andreydrozd** [comment]
I had the same error, I'm glad I found this issue and a solution.

Out of curiosity, why doesn't vite-node resolve `require` calls? I'm assuming vite does because my builds have been fine, no errors like the above.
