### ISSUE TITLE
Setup file(s) end up in the coverage report

### ISSUE THREAD

**Issue by KingSora** [vitest-dev/vitest#2190]
### Describe the bug

After running the tests the coverage report contains the setup files which was provided in the config. This happens only on my linux machine and not on my windows machine.

Linux output:
```
-------------------------|---------|----------|---------|---------|-------------------
File                     | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-------------------------|---------|----------|---------|---------|-------------------
All files                |     100 |      100 |     100 |     100 |
 home/projB/local/vitest |     100 |      100 |     100 |     100 |
  vitest.setup.js        |     100 |      100 |     100 |     100 |
 src                     |     100 |      100 |     100 |     100 |
  MyComponent.vue        |     100 |      100 |     100 |     100 |
-------------------------|---------|----------|---------|---------|-------------------
```

Windows output:
```
-----------------|---------|----------|---------|---------|-------------------
File             | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-----------------|---------|----------|---------|---------|-------------------
All files        |     100 |      100 |     100 |     100 |
 MyComponent.vue |     100 |      100 |     100 |     100 |
-----------------|---------|----------|---------|---------|-------------------
```

As a  workaround I've added the setup file(s) and the `include` globs to the `exclude` array of the `config.coverage` object. 
**Side note:** If I would add only the setup file(s) to the `config.coverage.exclude` array the `.test` files would show up in the coverage report (which is also a bug I suppose). - Thats why I've also added the `include` globs to it.

### Reproduction

Here is the minimal reproduction: https://stackblitz.com/edit/vitest-dev-vitest-dboudc 

> __Note__: **You have to download the project and run `npm i && npm run test` because for some reason the coverage report is always empty on Stackblitz.**

### System Info

```shell
## On Wndows: 

System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 2.98 GB / 15.69 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (106.0.1370.52)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vite: latest => 3.1.8
    vitest: latest => 0.24.3


## On Linux:

 System:
    OS: Linux 5.10 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 5.77 GB / 7.61 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  npmPackages:
    vite: latest => 3.1.8
    vitest: latest => 0.24.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Hurtak** [comment]
I can also reproduce this

**Comment by sheremet-va** [comment]
>  If I would add only the setup file(s) to the config.coverage.exclude array the .test files would show up in the coverage report (which is also a bug I suppose). - Thats why I've also added the include globs to it.

This is expected behaviour. If you need to extend exclude, you should also use `configDefaults.coverage`:

```ts
import { defineConfig, configDefaults } from 'vitest/config'

export default defineConfig({
  test: {
    coverage: {
      exclude: [...configDefaults.coverage.exclude, './vitest.setup.ts']
    }
  }
})
```

> After running the tests the coverage report contains the setup files which was provided in the config

I guess we should add them to `coverage.exclude` by default somewhere here

https://github.com/vitest-dev/vitest/blob/f7b27af01aa00be3c07161ad21bec3a965361526/packages/vitest/src/node/config.ts#L187
