### ISSUE TITLE
Option to turn off strict mode

### ISSUE THREAD

**Issue by Charuru** [vitest-dev/vitest#2198]
### Clear and concise description of the problem

Currently, strict mode is forced on instead of being an option, making it not usable for certain types of codebases.

### Suggested solution

config toggle to turn off strict mode.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Your code is treated as ESM. You cannot disable strict mode in ESM.

**Comment by Charuru** [comment]
What do you think about having alternative options to include setupFiles?

**Comment by sheremet-va** [comment]
What do you mean?

**Comment by Charuru** [comment]
Copy the setup files code on top of the test files without it being a module.

**Comment by sheremet-va** [comment]
Test files are also treated as modules. Every file is treated as a module

**Comment by Charuru** [comment]
@sheremet-va I guess what I'm asking is how difficult would it be to have an option to not do that? 

For example karma puts setup files in <script> tags. But karma is very slow.

Or maybe it's easier to copy the contents of setup files to into the same module as the test file? I feel like this should definitely be possible.

**Comment by ncoder** [comment]
Yes please. want this.

I had to patch my client.mjs:

```js
-    const codeDefinition = `'use strict';async (${Object.keys(context).join(",")})=>{{`;
+    const codeDefinition = `async (${Object.keys(context).join(",")})=>{{`;

```

**Comment by sheremet-va** [comment]
Vitest runs code in strict mode by default because it assumes the file follows ESM spec. We won't add an escape hatch for non-strict mode because we don't support CJS tests.
