### ISSUE TITLE
Spy on vi.mock 

### ISSUE THREAD

**Issue by cjoecker** [vitest-dev/vitest#2206]
### Clear and concise description of the problem

I would like to see if the `isAuthenticated` function of this mock has been called once:
```
vi.mock('remix-auth', () => {
  const Authenticator = vi.fn();
  Authenticator.prototype.isAuthenticated = vi.fn();
  Authenticator.prototype.use = vi.fn();
  return { Authenticator };
});
```

From what I see in the documentation, it is not possible. Or am I missing something?

### Suggested solution

Something like this would be intuitive for me

```
const spy = vi.spyMock('remix-auth', () => {
  const Authenticator = vi.fn();
  Authenticator.prototype.isAuthenticated = vi.fn();
  Authenticator.prototype.use = vi.fn();
  return { Authenticator };
});
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
you can just import from `remix-auth` in your test, it will be the same module you mocked.

after that use `expect(Authenicator.prototype.use)toHaveBeenCalledOnce()`

**Comment by cjoecker** [comment]
@sheremet-va  thanks for the fast answer!

I cannot import `remix-auth` because it has some logic and I want to use a mocked version of it.
How can I spy on a mocked dependency?

**Comment by sheremet-va** [comment]
just use import statement with your setup. if you called `vi.mock`, all import of this module will be mocked

**Comment by cjoecker** [comment]
Aa ok, got it, thanks for the information!

I was missing that in the documentation.
I would make a PR to add that to the Mock cheatsheet. 
What do you think to add this [here](https://github.com/vitest-dev/vitest/blob/93a0f4277d47dec9c904166c9ff3a7ea950088c7/docs/guide/mocking.md?plain=1#L380)?:

```
- Spy on a mock from a exported class implementation

``ts
import { SomeClass } from 'some-path'
vi.mock('some-path', () => {
  const SomeClass = vi.fn()
  SomeClass.prototype.someMethod = vi.fn()
  return { SomeClass }
})

...

test('someMethod is being called', () => {
  expect(SomeClass.prototype.someMethod).toHaveBeenCalledTimes(1)
});
``

```

**Comment by cjoecker** [comment]
@sheremet-va 6 months after, I had the same doubt and my answer above answered how to spy on a mocked class method. So, I guess that part I sent you in the answer above is still missing in the vitest docs. Should I make a PR to add it to the docs?

**Comment by sheremet-va** [comment]
> @sheremet-va 6 months after, I had the same doubt and my answer above answered how to spy on a mocked class method. So, I guess that part I sent you in the answer above is still missing in the vitest docs. Should I make a PR to add it to the docs?

It is there with your example: https://vitest.dev/guide/mocking.html

**Comment by cjoecker** [comment]
@sheremet-va  I don't see it 😅 I don't find anywhere that you can test if a mocked class method is called with `expect(SomeClass.prototype.someMethod).toHaveBeenCalledTimes(1)
});`
Or am I missing something?

**Comment by cjoecker** [comment]
@sheremet-va  I don't see it 😅 I don't find anywhere that you can test if a mocked class method is called with `expect(SomeClass.prototype.someMethod).toHaveBeenCalledTimes(1)
});`
Or am I missing something?
