### ISSUE TITLE
Linux下vitest运行出错 Failed to load React

### ISSUE THREAD

**Issue by tangtangtangtangtang** [vitest-dev/vitest#2208]
### Describe the bug

<img width="562" alt="image" src="https://user-images.githubusercontent.com/24206594/197776345-ef9bcb4b-6f1e-4a04-9434-8e3350132a0f.png">

mac下跑正常，linux下跑报错Failed to load React，实际用pnpm list能找到React

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-hautmy?file=test%2Findex.test.tsx,vite.config.ts&initialPath=__vitest__

### System Info

```shell
System:
    OS: Linux 3.10 CentOS Linux 7 (Core)
    CPU: (80) x64 Intel(R) Xeon(R) Gold 6248 CPU @ 2.50GHz
    Memory: 106.40 GB / 125.05 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Use `@vitejs/plugin-react`, if you are relying on global `React` variable

**Comment by tangtangtangtangtang** [comment]
> Use `@vitejs/plugin-react`, if you are relying on global `React` variable
do not work, now has another error `[vite-node] Failed to load react-dom/server`

**Comment by tangtangtangtangtang** [comment]
> Use `@vitejs/plugin-react`, if you are relying on global `React` variable

this(Failed to load React) only happens when i'm in Linux, it is fine when running in macos @sheremet-va
