### ISSUE TITLE
Different result in bench with mitata

### ISSUE THREAD

**Issue by Nisgrak** [vitest-dev/vitest#2220]
### Describe the bug

Hi!

I was creating a bench with `mitata` and `vitest bench` and the result are very different.

Mitata shows a x15 diff with the slowest option, vitest only a x2.

### Reproduction

Vitest bench
https://stackblitz.com/edit/node-odkzk5?file=package.json,tests%2Fexample.bench.ts
Execute `npm install` and `npm run bench`
![telegram-cloud-photo-size-4-5967514422937237619-x](https://user-images.githubusercontent.com/19597708/198342900-0433c493-de7f-489c-a52d-c986c22a24b6.jpg)

Mitata
https://stackblitz.com/edit/node-fnlpam?file=package.json
Execute `npm install` and `tsx bench.ts`
![telegram-cloud-photo-size-4-5967514422937237614-x](https://user-images.githubusercontent.com/19597708/198342933-f33a78d5-5c46-4910-a151-15091c005b13.jpg)

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    vitest: ^0.24.3 => 0.24.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This might be the problem with tinybench library. @Aslemammad I checked the reproduction and it still shows only a 2 times difference, do you think there might be a bug in tinybench?

**Comment by Aslemammad** [comment]
Yes, it might be! Can we have an upstream issue on Tinybench so I check it soon? Thanks.

**Comment by sirenkovladd** [comment]
The reason is that you are using different data sets in these tests

vitest
```ts
const data = new Array(1000000).fill(0).map((_, i) => ({
  name: faker.name.fullName(),
  cellName: faker.music.genre(),
  test: faker.lorem.paragraph(),
}));
```

mitata
```ts
const data = new Array(1000000).fill(0).map((_, i) => ({
  name: faker.name.fullName(),
  cellName: faker.name.fullName(),
  test: faker.lorem.paragraph(),
}));
```

note the cellName column

if you are interested in comparing these libraries, you can try this template
https://stackblitz.com/edit/node-vitest-2220?file=bench.js

**Comment by sheremet-va** [comment]
Thank you!
