### ISSUE TITLE
Junit reporter align to jest-junit

### ISSUE THREAD

**Issue by rikbrowning** [vitest-dev/vitest#2224]
### Clear and concise description of the problem

Hey all,
Currently the `<testsuites>` element in the junit report doesn't have any attributes. This is causing a few errors when some of our CI integrations trying to parse the file. 

 

### Suggested solution

Would it be possible to get a rollup of all the testsuites added to the element.  Similar to the attributes already available on `<testsuite>`. This is what jest-junit currently does.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
What properties to you expect there?

**Comment by rikbrowning** [comment]
Hey, so I think the parser I was trying to use was complaining about time missing. I found this https://www.ibm.com/docs/en/developer-for-zos/14.1?topic=formats-junit-xml-format it seems to just be totalling all child testsuites for different metrics.
