### ISSUE TITLE
v0.24.0 break lit test (with happy-dom)

### ISSUE THREAD

**Issue by christophe-g** [vitest-dev/vitest#2225]
### Describe the bug

I have a series test for some lit based web-components. The test run o.k. until v0.23.4 and break with v0.24.0 (as if lit reactive properties stopped working).

I see that the lit example has been upgraded with this release ([see here](https://github.com/vitest-dev/vitest/pull/1928/files)): `happy-dom` replaced by `jsdom`. 

Is there another potential fix than replacing `happy-dom` with `jsdom` in all test files (which could be quite cumbersome)? 

### Reproduction

run lit-basic test as of 0.23.4 under 0.24.0

### System Info

```shell
System:
    OS: Linux 5.15 Linux Mint 21 (Vanessa)
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 1.87 GB / 7.66 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 107.0.5304.68
    Firefox: 106.0.1
  npmPackages:
    vite: 2.9.13 => 2.9.13 
    vitest: 0.24.3 => 0.24.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by christophe-g** [comment]
Related discussion: 
https://discord.com/channels/917386801235247114/918805768541728779/1038100039949619281

**Comment by christophe-g** [comment]
Hey @capricorn86 - thanks a lot for the proposed hand here!

After some futher test, I actually don't think the issue has anything to do with Happy DOM, but with the way latest version of vitest play with lit. 

For instance, simple test like https://github.dev/vitest-dev/vitest/pull/2274 fail (at least on my machine) with JSDOM as well. 

Seems no one is complaining, so I might also miss smth completely trivial.

**Comment by capricorn86** [comment]
@christophe-g It looks like the test should be able to run.

I used the latest version of `Vitest` with `Lit` today for a new project and I found no issues setting it up and run it.

What is weird is that I did not need to use `await element.updateComplete`. I wonder if `Lit` has changed something related to how `await element.updateComplete` works.

The test I wrote looks similar to this:

```javascript
import { beforeEach, describe, expect, it, vi } from 'vitest'
import '../src/my-button'

describe('Button with increment', async () => {
  let element
  
  beforeEach(() => {
    element = document.createElement('my-button')
    document.body.appendChild(element)
  })

  it('should react to props change', () => {
    element.name = 'Vitest'
    expect(element?.shadowRoot?.textContent).toContain('Vitest')
  })
})
```

**Comment by davidortner-ipex** [comment]
I noticed in another test that I had to wait for render to complete, but `await element.updateComplete` was not enough then. To solve it I used `await element.requestUpdate()` instead, but it doesn't feel correct.

**Comment by capricorn86** [comment]
I noticed in another test that I had to wait for render to complete, but await element.updateComplete was not enough then. To solve it I used await element.requestUpdate() instead, but it doesn't feel correct.

**Comment by sheremet-va** [comment]
Looks like the issue was resolved.
