### ISSUE TITLE
Mocking `Math.random` Causes Random `birpc` Timeouts

### ISSUE THREAD

**Issue by alexlafroscia** [vitest-dev/vitest#2230]
### Describe the bug

For weeks, my application has been plagued by flakey failures due to different forms of the following error:

```
Error: [birpc] timeout on calling "onAfterSuiteRun"
```

Where `"onAfterSuiteRun"` was sometimes `"snapshotSaved"` or `"onTaskUpdate"` instead. When this happened, all of my tests would pass, but after completing the tests there would be a long pause followed by the test suite eventually failing due to the above error from somewhere within Vitest itself.

Sometimes, depending on _which_ task timed out, the reporter UI in the terminal would end up in some kind of odd state (like a test never being marked as having completed and passed, despite having done so).

I found #1154, which is the only issue I could find related at all to `birpc`, but that didn't lead to any insights on how to resolve my problem.

I eventually thought to look in Discord and [found this message from May](https://discord.com/channels/917386801235247114/918057998914568213/973526896098832425), which described the same issue that I ran into along with something useful -- the error seems related to stubbing `Math.random`!

Sure enough, I adjusted my code to avoid the `Math.random` stub and I haven't seen a single one of these errors since!

### Reproduction

I have a StackBlitz [here](https://stackblitz.com/edit/vitest-dev-vitest-7q69qj) that can _sometimes_ show the issue.

Unfortunately, because it's flakey test behavior, I have been unable to consistently reproduce the error (both locally in my app's test suite, before I replaced the `Math.random` mock, or in StackBlitz). However, after enough times re-running the tests in StackBlitz, I eventually saw the issue a few times

![CleanShot 2022-10-28 at 11 05 35@2x](https://user-images.githubusercontent.com/1645881/198673278-83ca8b81-7061-4242-a11c-d146e206e7b7.png)

![CleanShot 2022-10-28 at 11 10 58@2x](https://user-images.githubusercontent.com/1645881/198673310-eb35ba00-6bcb-4f42-a519-8c470b1ad8a1.png)

### System Info

```shell
N/A -- see reproduction in StackBlitz
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I guess we can add original `Math.random`, when running `withSafeTimers`, PR welcome

**Comment by rasyidf** [comment]
xcuse me, this problem presist again on 0.31.1
![image](https://github.com/vitest-dev/vitest/assets/28984914/38d63d1c-aa6f-4254-a552-9ebb14fb7197)

**Comment by sheremet-va** [comment]
> xcuse me, this problem presist again on 0.31.1 ![image](https://user-images.githubusercontent.com/28984914/239380374-38d63d1c-aa6f-4254-a552-9ebb14fb7197.png)
> 
> I've had to revert into 0.30.1 to make it work again.

Create a separate issue with reproduction.
