### ISSUE TITLE
Native method non-rewritable with a Proxy

### ISSUE THREAD

**Issue by hanako-eo** [vitest-dev/vitest#2233]
### Describe the bug

I made the "yeap" library and added more tests on the internal responsiveness system (using Proxy), I made tests on my browser and with node js and everything works correctly BUT as soon as I run the tests the result with vitest is not there and the problem occurs only with the native methods, with the methods of a custom object, no bug

### Reproduction

```js
import { createReactor } from "yeap/app"

const a = createReactor([0])

console.log(a.map((a) => a + 2)()) // "[2]" with node/chrome/firefox but "TypeError: a.map(...) is not a function" with vitest
```

https://stackblitz.com/edit/vitest-dev-vitest-4h8w6g?file=test_node.js

### System Info

```shell
System:
    OS: Linux 5.19 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
    Memory: 6.44 GB / 15.52 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.16.0 - ~/.volta/tools/image/node/16.16.0/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 8.11.0 - ~/.volta/tools/image/node/16.16.0/bin/npm
  Browsers:
    Firefox: 105.0.3
  npmPackages:
    vitest: ^0.24.3 => 0.24.3
```

### Used Package Manager

pnpm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Stackblitz gives following error when running with Vitest:

```
Cannot find module '/home/projects/vitest-dev-vitest-4h8w6g/node_modules/yeap/lib/constantes' imported from /home/projects/vitest-dev-vitest-4h8w6g/node_modules/yeap/lib/app.j
```

Which is justifiable, since your ESM packaging is wrong (`--es-module-specifier-resolution` makes it work for Node, but I just want to warn you that this flag was removed in the latest Node version). All you need to do to fix it is to add extension to the filenames.

I would recommend making your lib actually Node ESM compatible, but you can also `inline` dependency in Vitest config, so it uses browser bundlers resolver inside your dependency:

```ts
// vitest.config.ts
export default {
  test: {
    deps: {
      inline: [/yeap/],
    },
  },
};
```

**Comment by hanako-eo** [comment]
Okay, thanks for the explanation, finally the problem comes from my side, still a question, how my code can work with the browser and node but not during the tests 🤔, the problem comes from the bad use of `Object.hasOwn` (the keyword in is finally better in my case)

Sorry for the inconvenience
