### ISSUE TITLE
Vitest is not importing "dotfolders" inside node_modules properly

### ISSUE THREAD

**Issue by ravshansbox** [vitest-dev/vitest#2234]
### Describe the bug

Prisma generates a package `.prisma` inside `node_modules` from `schema.prisma` file. Test files that import it fail when running through vitest, but work when running through jest. This makes migration from jest difficult. The issue looks like the dot character in folder name, if it's renamed it to any name without a dot and imports are updated accordingly, then it works on both vitest and jest.

### Reproduction

https://github.com/ravshansbox/vitest-prisma

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 18.06 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Safari: 16.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This seems like a Vite problem. Vite server wasn't able to resolve this path 🤔 

Does this work with just Vite on the frontend? Or in SSR mode?

**Comment by ravshansbox** [comment]
@sheremet-va looks like vite also can't resolve it. It may be related to relative import semantics that start with a single dot.

**Comment by sheremet-va** [comment]
Your reproduction is no longer available.
