### ISSUE TITLE
Vitest did not work on GitHub Action

### ISSUE THREAD

**Issue by sametcelikbicak** [vitest-dev/vitest#2236]
### Describe the bug

I activated GitHub actions for testing my code with `vitest`. I did some changes but still `vitest` does not work properly.

### Reproduction

You can have a look this exception: https://github.com/sametcelikbicak/tsci/actions/runs/3354938512/jobs/5558830441
or my source code: https://github.com/sametcelikbicak/tsci
with branch: https://github.com/sametcelikbicak/tsci/tree/add-build-test-action

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/5312741/198872192-2ca54a37-c2ca-492e-bafb-b7e10e6ad41e.png">

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 57.45 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/local/bin/node
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Safari: 16.1
  npmPackages:
    vitest: ^0.24.3 => 0.24.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest required Node >=v14, your pipeline installs Node 12.22.12
