### ISSUE TITLE
passing variable  from globalSetup to test suites 

### ISSUE THREAD

**Issue by Madvinking** [vitest-dev/vitest#2238]
### Clear and concise description of the problem

i would like to use a global puppeteer instance to run different test files on different puppeteer tabs.
so for that, I want to initialize a global puppeteer instance and pass It down to each test Suite
Unfortunately, the test files are different than the globalSetup file, so i can't attach it to the instance to the globalSetup file global.

### Suggested solution

maybe have the ability to share the global variable between test files and globalsetup 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I highly doubt we will do this, since each test file is isolated and you will need to run globalSetup again, which is just a setupFile, but it's still possible to have a single puppeteer instance and share some context. You can see how it's done in Vite tests: https://github.com/vitejs/vite/tree/main/playground

**Comment by Madvinking** [comment]
mm ok, u wrote the wsEndpoint to a file and then connect to it each time...
nice solution but a little bit messy.

with jest, I created a test environment and then attach the instance to global.
but for some reason custom environment doesn't work the same way, or at least I wasn't able to configure one

**Comment by sheremet-va** [comment]
Jest has it's own system, we only provide similar API. The internals are very different. Environments are basically the same as using `setupFiles`.

**Comment by brc-dd** [comment]
Just wanted to ask, is there a drawback in directly adding the ws endpoint to process.env.something (instead of writing it to a file and reading later)?

**Comment by sheremet-va** [comment]
> Just wanted to ask, is there a drawback in directly adding the ws endpoint to process.env.something (instead of writing it to a file and reading later)?

If it works, it works 😄 

We can't provide this API, so I am closing the issue.
