### ISSUE TITLE
[RFC] Standard API to run test suites or cases on different platform or architectures

### ISSUE THREAD

**Issue by gemwuu** [vitest-dev/vitest#2240]
### Clear and concise description of the problem

Currently, running test cases on specific platforms or architectures is nasty.

See [this commit](https://github.com/node-modules/urllib/pull/418/commits/fa998e2c191f315c7f314c02537290ab9d1e593a) for show case.

### Suggested solution

There should be a standard way to solve this cases. For example.

Add a `if` API for condition customization. A `if` accepts a function( or async function) which returns with a `boolean` to decide whether current case should be skip or run.

`if` defaults to be `true`

```js
// platform
describe.if(() => os.platform() !== 'win32').skip('cases on Windows', () => {});
describe.if(() => os.platform() === 'darwin').run('cases on macOS', () => {});
it.if(() => os.platform() !== 'win32').skip('should work on Windows', () => {});
it.if(() => os.platform() === 'darwin').run('should work on macOS', () => {});


// architectures
describe.if(() => os.arch() !== 'x86' ).skip('cases on x86', () => {});
describe.if(() => os.arch() === 'arm64' ).run('cases on arm64', () => {});
```

The default API should run equally as below
```js
describe('all platforms', () => {});
describe.if(() => true).run('all platforms', () => {});

describe.skip('all platforms', () => {});
describe.if(() => false).run('all platforms', () => {});

it('should work on all platforms', () => {});
it.if(() => true).run('should work on all platforms', () => {});
it('should skip on all platforms', () => {});
it.if(() => false).run('should skip on all platforms', () => {});
```
The async function
``` js
import fs from 'fs/promises';
describe.if(async () => { return await fs. readFile('file.txt') === 'run'}).run('all platforms', () => {});
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
You can already do `test.runIf `or `test.slipIf`. The same methods are available on `describe`.

**Comment by gemwuu** [comment]
> You can already do `test.runIf` or `test.skipIf`. The same methods are available on `describe`.
> 
> 
> 
> Please, refer to [API documentation](https://vitest.dev/api/#test-skipif).

my bad, thanks a lot
