### ISSUE TITLE
v0.24.4: Unable to load custom reporters by package name

### ISSUE THREAD

**Issue by AriPerkkio** [vitest-dev/vitest#2245]
### Describe the bug

Likely related to #2184 (👋 @poyoho).

Custom reporters cannot be loaded by using the package name in `vitest@0.24.4`. There are no errors or any logging printed, the program just exits. Everything works fine with `vitest@0.24.3`.

As this has broken before #1194, I think it is time to add test cases for this. 

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-hubyyo

Stackblitz is working weirdly now so here is minimal vitest config also:

```ts
export default defineConfig({
  test: {
    outputFile: 'report.xml',

    // Works on 0.24.3, breaks on 0.24.4
    reporters: ['vitest-sonar-reporter'],

    // Works on 0.24.4
    // reporters: ['node_modules/vitest-sonar-reporter/dist/index'],
  },
});
```

### System Info

```shell
Stackblitz, Github Codespaces
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by poyoho** [comment]
I add the test case in #2249, but it seems to ok?
