### ISSUE TITLE
vite + RTL: increase the log output when test failed

### ISSUE THREAD

**Issue by dominikabieder** [vitest-dev/vitest#2246]
### Clear and concise description of the problem

My test is failing, but I don't see the problem as my component doest fully show up in the failed test.

### Suggested solution

I'd like to be able to see more output of the failed test

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
What do you mean?

**Comment by dominikabieder** [comment]
when a test fails it prints out the component and what it looks like into the console. the problem is that when a component is relatively big (still under 100 LoC!), the log output doesn't print the entire component, but only a part of it. I'd like to see more to be able to debug it better.

**Comment by sheremet-va** [comment]
I don't understand how this is Vitest issue? Have you tried looking into RTL settings? For example, changing `DEBUG_PRINT_LIMIT`
