### ISSUE TITLE
Fail to run test with node 16.1.0

### ISSUE THREAD

**Issue by znagadeon** [vitest-dev/vitest#2251]
### Describe the bug

It throws unhandled error.

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Initiated Worker with invalid execArgv flags: -C
 ❯ new NodeError node:internal/errors:363:5
 ❯ new Worker node:internal/worker:200:13
 ❯ ThreadPool._addNewWorker node_modules/tinypool/dist/esm/index.js:500:20
 ❯ ThreadPool._ensureMinimumWorkers node_modules/tinypool/dist/esm/index.js:485:12
 ❯ new ThreadPool node_modules/tinypool/dist/esm/index.js:475:10
 ❯ new Tinypool node_modules/tinypool/dist/esm/index.js:739:31
 ❯ createPool node_modules/vitest/dist/chunk-vite-node-externalize.e66d46f6.js:7167:16
 ❯ node_modules/vitest/dist/chunk-vite-node-externalize.e66d46f6.js:9998:21
 ❯ Vitest.runFiles node_modules/vitest/dist/chunk-vite-node-externalize.e66d46f6.js:10015:7
 ❯ Vitest.start node_modules/vitest/dist/chunk-vite-node-externalize.e66d46f6.js:9932:5

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: {
  "code": "ERR_WORKER_INVALID_EXEC_ARGV",
}
```

### Reproduction

I downloaded stackblitz sample vitest project and run it in **node 16.1.0** without any change.

<https://stackblitz.com/fork/github/vitest-dev/vitest/tree/main/examples/basic?initialPath=__vitest__>

### System Info

```shell
System:
  OS: macOS 12.4
  CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Memory: 4.38 GB / 32.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 16.1.0 - ~/.asdf/installs/nodejs/16.1.0/bin/node
  Yarn: 1.22.17 - ~/.asdf/installs/nodejs/16.1.0/.npm/bin/yarn
  npm: 7.11.2 - ~/.asdf/plugins/nodejs/shims/npm
Browsers:
  Chrome: 107.0.5304.87
  Safari: 15.5
npmPackages:
  vite: latest => 3.2.2
  vitest: latest => 0.24.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Update your Node version to latest Node 16.x at least

**Comment by znagadeon** [comment]
But the document says it requires [node >= v14](https://vitest.dev/guide/#adding-vitest-to-your-project) to use vitest v0.24.4. I think one of them should be fixed.

By the way, I circumvented this issue by downgrading vitest to 0.24.3 :)

**Comment by sheremet-va** [comment]
Yes, Vitest should support it. I just told how to fix it in the meantime 😄

**Comment by danez** [comment]
I have the exact same problem with version 14.16.0.
