### ISSUE TITLE
Avoid/Control clear-screen behaviour

### ISSUE THREAD

**Issue by silverwind** [vitest-dev/vitest#2255]
### Clear and concise description of the problem

Since https://github.com/vitest-dev/vitest/pull/2228 vitest clears the screen in both watch and non-watch mode which I find rather disturbing because it removes potentially useful information from commands that ran before.

https://github.com/vitest-dev/vitest/issues/2070 specifically only requested the clear-screen only for watch mode so I think the implementation forgot about non-watch mode.

### Suggested solution

I would suggest to never clear the screen when in non-watch mode and make the behaviour of the clear in watch mode configurable, like vite does via the [`clearScreen`](https://vitejs.dev/config/shared-options.html#clearscreen) option.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Vitest already respects clearScreen option

**Comment by sheremet-va** [comment]
Fixed in https://github.com/vitest-dev/vitest/commit/c3d89504e1b8b3cf8d055ef4f70ca2019e60fe9d

**Comment by silverwind** [comment]
Thanks.

> Vitest already respects clearScreen option

I don't see this option documented in either `--help` or on https://vitest.dev/. Are the docs missing?

**Comment by sheremet-va** [comment]
It’s an option in Vite config (since Vitest extends Vite config, it inherits the same options), its not available ad a CLI option.
