### ISSUE TITLE
Unable to import commonjs file with default export

### ISSUE THREAD

**Issue by danez** [vitest-dev/vitest#2258]
### Describe the bug

This is the same as #2219, but I wasn't able to reopen.

The initial bug was resolved, but I ran into it again when importing a file from `node_modules`. I tried different things, but I'm not sure why it happens with this one file and not with other cases.

I updated the reproduction example.

### Reproduction

https://github.com/danez-labs/vitest-default-commonjs with latest commit

- `npm i`
- `npm test`

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 AMD EPYC 7B13
    Memory: 29.12 GB / 62.80 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  npmPackages:
    vite: ^3.2.2 => 3.2.2 
    vitest: ^0.24.5 => 0.24.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Type definition of `@vercel/nft` assume it returns default function, and not a `default.default` function. It also provides `__esModule` hint for bundlers to look for. By default Vitest respects it, because most of the code is bundled wrongly and users usually don't care, since bundlers fix it for them, when they run code in a browser.

You can disable this behaviour with `deps.interopDefault: false` option.

**Comment by sheremet-va** [comment]
I guess we can disable it by default, if `environment` is `Node` 🤔 @antfu what do you think?

**Comment by danez** [comment]
> You can disable this behaviour with `deps.interopDefault: false` option.

Ah yes this worked, thanks.

**Comment by tobiasdiez** [comment]
I had the same issue, but it seems to be fixed now (with v. 0.28.3).

**Comment by sheremet-va** [comment]
Yes, this is fixed. We tried enabling it by default for `node` environments, but there were a lot of unexpected issues, so we rolled it back. Vitest always tries to interop default. If you rely on Node behavior, disable `deps.interopDefault` manually.
