### ISSUE TITLE
toThrowError() doesn’t catch async throws

### ISSUE THREAD

**Issue by drwpow** [vitest-dev/vitest#2262]
### Describe the bug

When `expect(…).toThrowError()` is used with an async function, Vitest doesn’t catch it.

```ts
test('async throws', async () => {
  await expect(async () => {
    await asyncFunctionThatThrows();
  }).toThrowError();
});
```

Vitest reports that the function didn’t throw, _and_ there was an uncaught exception that happened elsewhere.

```
AssertionError: expected [Function] to throw an error
 ❯ test.test.ts:20:7
     18|     await expect(async () => {
     19|       await asyncFunctionThatThrows();
     20|     }).toThrowError();
       |       ^
     21|   });
     22| });

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

Test Files  1 failed (1)
     Tests  1 failed | 1 passed (2)
  Start at  17:59:00
  Duration  1.54s (transform 522ms, setup 0ms, collect 104ms, tests 11ms)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Aaah!
```

Note that `expect.toThrowError()` works just fine with synchronous throws.

I’d love to try submitting a PR to fix this if desired 🙏 

### Reproduction

https://github.com/drwpow/vitest-throw-repro

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 90.48 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/Library/Caches/fnm_multishells/56571_1667433083650/bin/node
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/56571_1667433083650/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 105.0.2
    Firefox Developer Edition: 107.0
    Safari: 16.1
  npmPackages:
    vitest: ^0.24.5 => 0.24.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by drwpow** [comment]
Actually, I have found that this works, and there are existing tests for this:

```ts
  await expect((async () => {
    await asyncFunctionThatThrows();
  })()).rejects.toThrowError();
```

But this seems to be a deviation from the Jest API. If this is the intended way to run async expectations, could this be added to the docs?

Or is there something here about allowing the simpler syntax for parity with Jest?

**Comment by sheremet-va** [comment]
This is expected behaviour. If you look at type definition, `.toThrowError` doesn't return a Promise, so `await` on him yields nothing.

> But this seems to be a deviation from the Jest API. If this is the intended way to run async expectations, could this be added to the docs?

It also doesn't work in Jest, and not a deviation from Jest API. You can rewrite your example as:

```js
await expect(asyncFunctionThatThrows).rejects.toThrowError();
```

We can add a note in docs on how to test it asynchronously, and redirect to `.rejects` helper section.

**Comment by drwpow** [comment]
Sounds good to me. And thanks for double-checking.

Feel free to close this issue as it seems to be documentation then (unless you want to track that via this issue).

Also I am glad to open up a PR for that documentation if desired!

**Comment by sheremet-va** [comment]
> Sounds good to me. And thanks for double-checking.
> 
> 
> 
> Feel free to close this issue as it seems to be documentation then (unless you want to track that via this issue).
> 
> 
> 
> Also I am glad to open up a PR for that documentation if desired!

PR is always welcome 👍

**Comment by MrShnaider** [comment]
Hello. Faced the same problem and found a solution with `rejects` only on some random site. It would be great if the documentation specifically mentioned `rejects` as a way of working with asynchronous functions and in the absence of exceptions, the user was reminded that he might have forgotten `rejects`

**Comment by wighawag** [comment]
Hey, I am having the same issue and tried what @sheremet-va said to use in this stackblitz : https://stackblitz.com/edit/vitest-dev-vitest-54pdz4?file=test%2Fsuite.test.ts

I guess I am doing something wrong, but I have no idea what ?
