### ISSUE TITLE
When registerNodeLoader is enabled, the package that imported react/jsx-runtime is not resolved correctly

### ISSUE THREAD

**Issue by 0xDing** [vitest-dev/vitest#2271]
### Describe the bug

Some react packages such as `react-dnd` has imported `react/jsx-runtime`. And, `@vitejs/plugin-react-refresh` will inject HMR code when `react/jsx-runtime` is imported. But vitest's esm loader doesn't resolve this edge case.

Related cases:
- https://github.com/vitest-dev/vitest/discussions/2055

Referenceable solutions:
- https://github.com/callstack/linaria/issues/1044

### Reproduction

- See [https://github.com/0xDing/vitest-esm-loader-issue-reproduce](https://github.com/0xDing/vitest-esm-loader-issue-reproduce)

Steps to reproduce:

1. `yarn install`
2. `yarn test`
3. See error: `The argument 'path' must be a string or Uint8Array without null bytes. Received '\x00react/jsx-runtime'`
4. Set `registerNodeLoader` to `false` in `vite.config.ts`
5. `yarn test`
6. It works now

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 962.06 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.10.0 - ~/.volta/tools/image/node/18.10.0/bin/node
    Yarn: 3.2.4 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.19.2 - ~/.volta/tools/image/npm/8.19.2/bin/npm
    Watchman: 2022.10.24.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 105.0.3
    Safari: 16.1
  npmPackages:
    @vitejs/plugin-react: ^2.2.0 => 2.2.0 
    vite: ^3.2.2 => 3.2.2 
    vitest: ^0.24.5 => 0.24.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 0xDing** [comment]
Monkey patch for interim fixes:
```patch
diff --git a/dist/loader.js b/dist/loader.js
index 3263472ab803bf1204eb99e5881419725eeea57d..b2bd99764257ed76cf0fdb019a6c16850b29e9ae 100644
--- a/dist/loader.js
+++ b/dist/loader.js
@@ -47,7 +47,7 @@ const resolve = async (url, context, next) => {
   const { parentURL } = context;
   const state = getWorkerState();
   const resolver = state == null ? void 0 : state.rpc.resolveId;
-  if (!parentURL || isNodeBuiltin(url) || !resolver)
+  if (!parentURL || isNodeBuiltin(url) || !resolver || url.startsWith('react/jsx-'))
     return next(url, context, next);
   const id = normalizeModuleId(url);
   const importer = normalizeModuleId(parentURL);
```

**Comment by sheremet-va** [comment]
`registerNodeLoader` is deprecated, and will be removed before 1.0.0 is released. We will experiment with the API in the future when it will be more stable.
