### ISSUE TITLE
Assert one mock called before another mock 

### ISSUE THREAD

**Issue by Luncher** [vitest-dev/vitest#2287]
### Clear and concise description of the problem

I'd like to assert that one mock function is called before another similar to Jest's toHaveBeenCalledBefore spy.

Is this a feature that's been considered/is being considered?

### Suggested solution

jest implementation: https://github.com/jest-community/jest-extended/issues/98

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
You can use jest-extended with Vitest
