### ISSUE TITLE
Docs on how to create coverage badge

### ISSUE THREAD

**Issue by janosh** [vitest-dev/vitest#2288]
### Clear and concise description of the problem

The [docs on coverage](https://vitest.dev/guide/coverage.html) are a great starting point but don't go into detail.

### Suggested solution

Add a paragraph on how to create a coverage badge.

Example:

![Coverage badge][coverage-badge]

[coverage-badge]: https://img.shields.io/badge/Coverage-100%25-brightgreen.svg

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by khalwat** [comment]
I'd like to see this too. I'd previously been using this: 

https://dev.to/thejaredwilcurt/coverage-badge-with-github-actions-finally-59fa

...to generate a coverage badge via GitHub action. But I'm unclear on how to pass down the `--coverageReporters='text-summary'` flag, as it doesn't appear that Vitest supports this flag from the CLI?

**Comment by khalwat** [comment]
Here's a working example with Vitest: https://github.com/nystudio107/rollup-plugin-critical/blob/master/.github/workflows/node.js.yml

This is the npm script it references to build the coverage summary for the above GitHub action:

```json
    "test-ci": "vitest run --coverage.enabled --coverage.reporter='text-summary'",
```
