### ISSUE TITLE
X-Post from @adobe/react-spectrum

### ISSUE THREAD

**Issue by just-Bri** [vitest-dev/vitest#2296]
### Describe the bug

https://github.com/adobe/react-spectrum/issues/3721

The linked issue has all the details as well as a [Codesandbox link](https://codesandbox.io/s/pensive-boyd-inj2op) that demonstrates the error when running `npm run test`

### Reproduction

See above

### System Info

```shell
See above
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest doesn't intercept `require` calls. It's a known limitations. You can bypass css by adding this to your `setupFiles`:

```ts
require.extensions['.css'] = () => ({})
```

**Comment by just-Bri** [comment]
@sheremet-va Omg... You are a life saver!
I figured it was some config thing or some kind of setup but I completely forgot about the require/css issue!

Closing this, thank you!

**Comment by ant-dep** [comment]
I still got TypeError: Unknown file extension ".css" for ...node_modules\@react-spectrum\actiongroup\dist\main.css
