### ISSUE TITLE
vite-node: can't resolve 2-distance baseUrl-base-import while can resolve 1-distance.

### ISSUE THREAD

**Issue by LumaKernel** [vitest-dev/vitest#2297]
### Describe the bug

Import based on `baseUrl` option, we can import from directly imported by entrypoint while we can't import from imported module from imported module (2 distance).

### Reproduction

# From scrach

1. Create TS files with following import dependency graph, _without_ using relative import.
  - 1-distance(success): `a0.ts --> a1.ts`
  - 2-distance(failure): `b0.ts --> b1.ts --> b2.ts`
2. Put tsconfig.json with `compilerOptions. baseUrl=.`
3. Run vite-node from `a0.ts` --> succes
4. Run vite-node from `b0.ts` --> failure

# From reproduction repo

1. Clone https://github.com/LumaKernel/issue_vite-node-cannot-2dist-import
2. Run `npm ci`
3. Run `npx vite-node ./a0.ts` --> success
4. Run `npx vite-node ./b0.ts` --> failure

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 3.71 GB / 15.38 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 14.20.0 - ~/.volta/tools/image/node/14.20.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 6.14.17 - ~/.volta/tools/image/node/14.20.0/bin/npm
  Browsers:
    Firefox: 106.0.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sebastian-fredriksson-bernholtz** [comment]
@LumaKernel In you repro repo you're trying to import something from b1 that is not exported:
```typescript
// b0.ts
import { a1 } from 'b1'; // this will fail because b1.ts does not export a1, it only exports b1
console.log(a1);

// b1.ts
import {b2} from 'b2';
export const b1 = b2;
```

**Comment by LumaKernel** [comment]
@sebastian-fredriksson-bernholtz Thanks! I fixed that.

**Comment by sheremet-va** [comment]
Vite-Node uses Vite's module resolve algorithm, which as far as I know doesn't respect tsconfig. If you want to change it, I would suggest opening an issue in Vite repo.
