### ISSUE TITLE
Run `vitest typecheck` together with normal test in one `watch`

### ISSUE THREAD

**Issue by Shinigami92** [vitest-dev/vitest#2299]
### Clear and concise description of the problem

- As a user
- I want to run `vitest typecheck` and `vitest` in just one command (e.g. just `vitest` or `vitest --with-typecheck`)
- so that I don't need to run e.g. two separate terminal windows in my VSCode editor in parallel to run all tests while I'm working on my project

### Suggested solution

Run `typecheck` by default alongside the normal running tests by default.
(I use `*.test-d.ts` as recommended in the docs)

### Alternative

Let us use a flag for running with `typecheck` via `--with-typecheck` (alternative wording welcome)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by bugeats** [comment]
This could also be addressed by adding a shell command hook to run before reload. Ex:

```bash
vitest --watch --before-run "tsc --noEmit"
```

In my case I have multiple things I'd also like to do on re-test: clear my tmux buffer, run lints, etc.

**Comment by posva** [comment]
It would also be nice if they appear in the UI and are reported through the API
