### ISSUE TITLE
When running `vitest typecheck` in GitHub Action the `*.test-d.ts` files are not listed.

### ISSUE THREAD

**Issue by Shinigami92** [vitest-dev/vitest#2300]
### Describe the bug

When running `vitest typecheck` in GitHub Action the `*.test-d.ts` files are not listed.

### Reproduction

<img src="https://user-images.githubusercontent.com/7195563/200628331-d21a323b-3cac-43c6-ac97-2377fc8afd15.png" width="600px" />

### System Info

```shell
GitHub Action
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by unicornware** [comment]
experiencing this on my local machine as well - should i open a separate issue?
