### ISSUE TITLE
--no-threads doesn't seem to do anything (trying to use on lerna repo)

### ISSUE THREAD

**Issue by JamesHenry** [vitest-dev/vitest#2301]
### Describe the bug

I feel like I must be doing something wrong here...

I was curious if we could make use of `vitest` on `lerna` to help us run our tests as efficiently as possible.

It cannot complete because of a ton of these errors:

![image](https://user-images.githubusercontent.com/900523/200630725-38298c33-ebc8-46be-aadb-5bfd6ff95243.png)

The fixtures we on the Nrwl team inherited when we took over stewardship of the lerna project do a `process.chdir()`ing

These errors with vitest are despite running with the `--no-threads` options

### Reproduction

(This is not the end state of adding `vitest` to `lerna` because I would want to clean up the jest usage etc, but until I can get past this fundamental issue there is no point in going any further.)

I did the following:

- checked out https://github.com/lerna/lerna
- installed vitest with npm
- added the following `vite.config.ts`

```ts
import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    globals: true,
  },
})
```

- ran `npx vitest`
- Hit the above mentioned error, so then ran `npx vitest --no-threads` and it made no difference

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.66 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.volta/tools/image/node/16.15.0/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 8.12.1 - ~/.volta/tools/image/npm/8.12.1/bin/npm
  Browsers:
    Brave Browser: 106.1.44.105
    Safari: 16.1
  npmPackages:
    vitest: ^0.25.1 => 0.25.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You cannot disable this behaviour. No threads just reduces the number of workers to one.

**Comment by JamesHenry** [comment]
Apologies I’ve noticed this is actually a duplicate of https://github.com/vitest-dev/vitest/issues/1436, closing in favour of that one.

But would really appreciate any kind of hint of path forward for tests which need this…

I don’t believe it’s currently documented as part of the Jest migration guide and it should be because jest supports this just fine
