### ISSUE TITLE
Files with no tests cause failure even when `passWithNoTests: true`

### ISSUE THREAD

**Issue by mattoni** [vitest-dev/vitest#2304]
### Describe the bug

I'm trying to use the rust-like inline tests, but out of necessity have to include my src folder for tests, where most of the files don't have tests in them. I'm getting a 'no test found' error for every file that doesn't have one, despite having set `passWithNoTests: true`

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-5vzkqu?file=vite.config.ts

### System Info

```shell
System:
    OS: Linux 5.19 Pop!_OS 22.04 LTS
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 33.92 GB / 46.96 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 19.0.0 - /tmp/fnm_multishells/11210_1668034408490/bin/node
    Yarn: 3.2.1 - /usr/local/bin/yarn
    npm: 8.19.2 - /tmp/fnm_multishells/11210_1668034408490/bin/npm
  Browsers:
    Firefox: 106.0.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest expects actual test files there. In-source testing uses "includeSource" config option

**Comment by mattoni** [comment]
Wow thank you, it wasn't showing up in the autocomplete for the settings but it did solve the issue.
