### ISSUE TITLE
Inconsistent external script execution with happy-dom and jsdom environments

### ISSUE THREAD

**Issue by lund0n** [vitest-dev/vitest#2308]
### Describe the bug

I have some code that injects `script` elements into the page, with the `onload` and `onerror` handlers being used to resolve a promise. The external script adds a variable to the `window` object. I would like to test this code.

**Issue**

While it appears that the script loading generally works with `happy-dom`, it is not working with `jsdom`. While `jsdom` successfully executes the `onload` handler, the variable that the script set in the `window` object is always `undefined`. I have confirmed that this working with `jest` in `jsdom` environment, so I suspect that there is either a misconfiguration on my part of the `jsdom` environment in `vitest` or an difference with how `vitest` interacts with `jsdom`.

**Expected Behavior**

Variables set in the external script on `window` are available in the calling code.

Thank you.

### Reproduction

I have a small reproduction in StackBlitz here: https://stackblitz.com/edit/vitest-dev-vitest-j5udwn?file=test/using-jsdom.test.ts

I also have a larger repo that compares jest and vitest, along with `happy-dom` and `jsdom` implementations here: https://github.com/lund0n/load-scripts-test

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 83.53 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.asdf/installs/nodejs/18.12.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/shims/yarn
    npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Brave Browser: 106.1.44.112
    Firefox: 106.0.5
    Firefox Developer Edition: 105.0
    Safari: 15.6.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I am not sure if it can work with Vitest. We don't use VM's contexts to isolate environments, so `window` inside script tag and `window` inside your test are two different windows.

So, if you define something globally in your test, it won't appear inside script tag and vice versa.

**Comment by Odas0R** [comment]
I think the same thing is happening to me. I'm executing an external script that injects an object on the window but it is undefined.

Using `jsdom` solely outside of the Vitest context works, the object is there. 

How should one test this if the behavior is as you describe? @sheremet-va

**Comment by atk** [comment]
There is a workaround: forgo the jsdom environment and set it up yourself, like I did in https://github.com/solidjs-community/solid-primitives/blob/5640fa5c88ee267bee8f3d7d8a87ce96987e629c/packages/script-loader/test/index.test.ts

You may need to add more stuff to the global scope for your scripts to work.
