### ISSUE TITLE
Nuxt3 test function use auto imports api, is not defined

### ISSUE THREAD

**Issue by warmthsea** [vitest-dev/vitest#2309]
### Describe the bug

![image](https://user-images.githubusercontent.com/45450994/201022461-89271fa9-3a9b-4716-b4bd-04d726b6c4b0.png)

### Reproduction

https://stackblitz.com/edit/github-6fqvfv?file=test/utils.test.ts

`npm run test`

![image](https://user-images.githubusercontent.com/45450994/201021672-5b0cab01-90d2-454e-9b1e-ef34946838a5.png)

### System Info

```shell
nuxt Rc13
vitest @last
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Not a Vitest bug. There is an open discussion about it: https://github.com/vitest-dev/vitest/discussions/1737. I would recommend opening a feature request in Nuxt repo.
