### ISSUE TITLE
Not able to import modules from node_modules that don't use the ".js" extension

### ISSUE THREAD

**Issue by web-ts** [vitest-dev/vitest#2313]
### Describe the bug

Vitest fails to find modules that don't use the ".js" extension. 

Example:   
.
└── node_modules/
    ├── my-module/
    │   ├── index.js
    │   ├── some-function/
    │   │   ├── some-function.js
    │   │   └── ...
    │   └── ...
    └── ...

In the above structure if `my-module` has a `export * from "./some-function/some-function" `  vitest will complaint that it can't find the module, if the file is `export * from "./some-function/some-function.js" `  everything will work.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-khx8sn?file=test/basic.test.ts

https://github.com/web-ts/vitest-broken-imports

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-1240P
    Memory: 16.02 GB / 31.59 GB
  Binaries:
    Node: 16.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.24.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.35)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vite: ^3.2.3 => 3.2.3
    vitest: ^0.25.1 => 0.25.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is how ESM works, spec doesn't support imports without extension. If you want Vite behaviour for `node_modules` libraries, inline them with `deps.inline`.
