### ISSUE TITLE
Coverage report is not only generated for changed files in watch mode

### ISSUE THREAD

**Issue by netcoding87** [vitest-dev/vitest#2316]
### Describe the bug

As a developer using Vitest I want to coverage report in watch mode only for files affected by code changes instead of all so that I can easily see how my changes affected the code.

I know this behavior from using `jest` on projects setup with `cra`. In my current project with more than 100 files it is very frustrating to have to search out the files from the report after every run...

### Reproduction

Repository to investigate: https://github.com/netcoding87/vitest-coverage (see `README.md`)

### System Info

```shell
System:
    OS: macOS 12.6.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 246.67 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 106.0.3
    Safari: 16.1
  npmPackages:
    @vitejs/plugin-react: ^2.2.0 => 2.2.0 
    vite: ^3.2.3 => 3.2.3 
    vitest: ^0.25.1 => 0.25.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DevathiMahesh** [comment]
Yes. Even i am facing the same issue. Its running for all the files in the codebase.......

**Comment by AriPerkkio** [comment]
@netcoding87, @DevathiMahesh, does `cleanOnRerun` work for you? In the reproduction case it is providing same experience as Jest does. It doesn't exactly limit the included files to only those ones that have changed, but includes those ones that are used by the test that was re-run. This will limit the coverage report a lot. 

```ts
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    coverage: {
      provider: "istanbul",
      cleanOnRerun: true,
    },
    reporters: "verbose",
  },
});
```

What Jest does is more complicated. It's using `git` to see which files have changes, and includes only those ones in coverage report.

- https://jestjs.io/docs/jest-platform#jest-changed-files
- https://archive.jestjs.io/blog/2018/05/29/jest-23-blazing-fast-delightful-testing#other-improvements
