### ISSUE TITLE
Repeat modifiers for `describe` and `it`

### ISSUE THREAD

**Issue by lukemovement** [vitest-dev/vitest#2317]
### Clear and concise description of the problem

Currently we can not re-run a test multiple times in order to stress a piece of code.

### Suggested solution

Like the `it.only` and `it.skip` methods, we could have an `it.repeats` modifier to allow for a specific test to be ran multiple times in order to get an average execution time.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by poyoho** [comment]
I think now we can use the `vitest branch` to get the same result. 😁

**Comment by samkevin1** [comment]
Hey! Is this still desirable? I can try to create a PR for it.

**Comment by sheremet-va** [comment]
> Hey! Is this still desirable? I can try to create a PR for it.

Sure, give it a try.
