### ISSUE TITLE
Example of react testing lib & msw error 

### ISSUE THREAD

**Issue by agmcleod** [vitest-dev/vitest#2328]
### Describe the bug

Referring to this example here: https://github.com/vitest-dev/vitest/tree/main/examples/react-testing-lib-msw, i tried to give it a run having some issues with my svelte project after trying to update dependencies. The error with the example is as such:

```
 FAIL  src/App.test.tsx [ src/App.test.tsx ]
Error: Package subpath './lib' is not defined by "exports" in /Users/aaron.mcleod/src/react/vitest/examples/react-testing-lib-msw/node_modules/headers-polyfill/package.json
 ❯ Object.<anonymous> node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/NodeClientRequest.ts:5:1

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: {
  "code": "ERR_PACKAGE_PATH_NOT_EXPORTED",
}


⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  no tests
   Start at  16:26:10
   Duration  817ms (transform 328ms, setup 0ms, collect 0ms, tests 0ms)
```

I imagine this has to do with a mix of module types, but i can't seem to figure out how to resolve it.

### Reproduction

Running example as is: https://github.com/vitest-dev/vitest/tree/b70593955fbece56f9b7c1d81dffebd8b10376dc/examples/react-testing-lib-msw

### System Info

```shell
Trying this on MacOS 12.5.1
Node v16.15.0, using npm (I tried version 14 as well, and also yarn, no difference in terms of the error).
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by BrunoQuaresma** [comment]
Having the same issue.
