### ISSUE TITLE
global error event not fired

### ISSUE THREAD

**Issue by unional** [vitest-dev/vitest#2329]
### Describe the bug

I have tests that listen to the global error (`window.addEventHandler('error', handler)`) to make sure certain error are fired.

For example rendering a React component without the context provider.

It is working in `jest`, but with `vitest`, the `handler` is not triggered.

Does `vitest` capture and suppress all these errors?

Is there a way to access these errors or if there is a way to disable this behavior?

### Reproduction

```ts
const ComponentThatThrowDuringRender = () => throw new Error('some error')

test('...', () => {
  window.addEventListener('error', ()=> { /* should reach here */ })
  render(<ComponentThatThrowDuringRender/>)
})
```

### System Info

```shell
System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 76.03 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Brave Browser: 107.1.45.123
    Chrome: 107.0.5304.110
    Firefox: 105.0.3
    Safari: 16.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Node doesn't fire this event by itself. Jest does some magic to capture it: https://github.com/facebook/jest/blob/main/packages/jest-environment-jsdom/src/index.ts

PR welcome!

**Comment by unional** [comment]
Um... interesting. Do you mean `vitest` also run the tests in workers so need some work to pipe the errors from the worker back to the runner process?

**Comment by mysteryven** [comment]
I find that vitest can trigger the handler after adds js-dom :

```js
export default defineConfig({
  test: {
    environment: 'jsdom' 
  }
})
```

```js
const ComponentThatThrowDuringRender = () => { throw new Error('some error') }

test('...', () => {
  const fn = vi.fn()
  window.addEventListener('error', fn)
  try {
    render(<ComponentThatThrowDuringRender />)
  } catch {}

  expect(fn).toBeCalled()
})
```

**Comment by unional** [comment]
That's interesting. Seems to be opposite of what I have encounter. Will need to do a repro

**Comment by mysteryven** [comment]
I used v0.26.3, there is my [online demo](https://stackblitz.com/edit/vitejs-vite-zocyrt?file=src/globalEvent.test.tsx), you can try it again :)

**Comment by sheremet-va** [comment]
This should work since 0.27.3.
