### ISSUE TITLE
Istanbul coverage fails with `TypeError: Cannot read properties of null (reading 'split')` for files with `import.meta.env` statements

### ISSUE THREAD

**Issue by benmandr** [vitest-dev/vitest#2332]
### Describe the bug

 Coverage on files using `import.meta.env` statements fails with `TypeError: Cannot read properties of null (reading 'split')` error.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-yl61zx?file=vite.config.js,package.json&terminal=dev

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitejs/plugin-vue: ^3.2.0 => 3.2.0 
    vite: ^3.2.3 => 3.2.4 
    vitest: ^0.25.2 => 0.25.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
When the source file contains any `import.meta.env`, the Rollup plugin context returns sourcemap which has `null` in `sources[]` array. This does not match its typings. 

```js
SourceMap {
  version: 3,
  file: null,
  sources: [ null ],
  sourcesContent: [ null ],
  names: [],
  mappings: 'AAAA,... <looks ok>'
}
```

So to reproduce add `import.meta.env` in any source file and debug here:

https://github.com/vitest-dev/vitest/blob/3038991347500f1336089698a3517ee5c5a5b4f3/packages/coverage-istanbul/src/provider.ts#L81


However it works fine when the source file includes just `import.meta`:

```
SourceMap {
  version: 3,
  file: null,
  sources: [ '/workspace/repro-istanbul/src/util.js' ],
  sourcesContent: [
    'export function test() {\n' +
      '  console.log(import.meta)\n' +
      '}\n' +
      '\n'
  ],
  names: [],
  mappings: 'AAAA, ... <looks ok>'
}
```

This needs some more debugging to see if some other Vite plugin is causing this - or maybe even Rollup itself.
