### ISSUE TITLE
Default config for coverage with 'c8' provides empty report

### ISSUE THREAD

**Issue by benmandr** [vitest-dev/vitest#2333]
### Describe the bug

Repro has only one `.js` file added with a function returning 'test' string. Test passes, but generated coverage is completely blank/empty:
<img width="524" alt="image" src="https://user-images.githubusercontent.com/37113532/201955908-e835fe2c-02d0-44b3-b16d-b44224795ec8.png">

### Reproduction

https://stackblitz.com/edit/vitejs-vite-shzgnb?file=src/__test__/util.spec.js

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitejs/plugin-vue: ^3.2.0 => 3.2.0 
    vite: ^3.2.3 => 3.2.4 
    vitest: ^0.25.2 => 0.25.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Downloaded the reproduction repository and run `yarn coverage`. Looks good to me. 

```
$ yarn coverage
yarn run v1.22.19
$ vitest run --coverage

 RUN  v0.25.2 /workspace/repro
      Coverage enabled with c8

 ✓ src/__test__/util.spec.js (1)

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  18:03:00
   Duration  3.41s (transform 570ms, setup 0ms, collect 6ms, tests 4ms)

 % Coverage report from c8
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |                   
 util.js  |     100 |      100 |     100 |     100 |                   
----------|---------|----------|---------|---------|-------------------
Done in 5.48s.
```

@benmandr note that Stackblitz does not implement `require('v8').takeCoverage()` API. You cannot run `c8` in Stacklitz's webcontainer.

**Comment by benmandr** [comment]
I have encountered a similar behaviour on my local machine, but with the given context, now I'll have to double check.
Thanks guys for the answers, if something, I'll open a separate issue. 🙇
