### ISSUE TITLE
Globally install snapshot serializer

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vitest-dev/vitest#2366]
### Clear and concise description of the problem

The migration guide just shows:

```js
import vueSnapshotSerializer from 'jest-serializer-vue';

// Add Snapshot Serializer
expect.addSnapshotSerializer(vueSnapshotSerializer);
```

However, it doesn't actually say *where* to put that code. From looking in GitHub Issues, it looks like you'd actually have to add it to every single test manually, which is.... insane?

```js
test('Renders correctly', () => {
  expect
    .addSnapshotSerializer(serializer);

  expect(wrapper)
    .toMatchSnapshot();
});
```

### Suggested solution

Jest lets you just add an array of serializers in in `/jest.config.js`:

```
module.exports = {
  snapshotSerializers: [
    '<rootDir>/tests/unit/serializer.js'
  ]
};
```

### Alternative

My only alternative is to just use Jest. I'm not putting this line inside of every single test.

### Additional context

I'm hoping a solution for this already exists and just the documentation needs updated to make it clear and obvious.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
> However, it doesn't actually say where to put that code

You would add it in `setupFiles`.

> Jest lets you just add an array of serializers

PR welcome.

**Comment by sheremet-va** [comment]
> The page linked doesn't show if that is a file called setupFiles.js in the root, or if it is a property in an object, inside of some file?

The link points to configuration documentation:

<img width="778" alt="Screenshot 2022-11-22 at 14 33 07" src="https://user-images.githubusercontent.com/16173870/203326888-0d08bd00-c7a7-40d8-8c1a-d2395facbc87.png">

It is a property on configuration file:

```ts
{
  test: {
    setupFiles: ['./path.to.setup.file.ts']
  }
}
```

> I can't do a PR to correct documentation, if I don't know what the correction is?

There is no need to correct anything in the documentation regarding this topic.

**Comment by TheJaredWilcurt** [comment]
hey, almost there. but I still literally don't know what to do. This is why the docs need to be more clear

So this is good:

```js
// vite.config.js
{
  test: {
    setupFiles: ['./serializer.js']
  }
}
```

But then, is this right?

```js
// serializer.js
import vueSnapshotSerializer from 'jest-serializer-vue';

expect.addSnapshotSerializer(vueSnapshotSerializer);
```

I could try locally and see, but the point of documentation is to clearly communicate how to interact with the library and it's API's, not to have to do trial and error.

**Comment by TheJaredWilcurt** [comment]
I just asked if the second part is correct and I still don't know

**Comment by sheremet-va** [comment]
> I just asked if the second part is correct and I still don't know

It is correct. We describe it in documentation.
