### ISSUE TITLE
describe.skip does not skip the test

### ISSUE THREAD

**Issue by lpatiny** [vitest-dev/vitest#2371]
### Describe the bug

I would expect that `describe.skip` does not execute the callback but this appears not to be the case.

### Reproduction

```js
import { describe } from 'vitest';

describe.skip('skipped test', () => {
  // Test skipped, no error
  throw new Error();
});
```

Even if those tests are skipped vitest reports an error

```
 FAIL  src/__tests__/abc.test.js [ src/__tests__/abc.test.js ]
Error: 
 ❯ src/__tests__/abc.test.js:5:9
      3| describe.skip('skipped test', () => {
      4|   // Test skipped, no error
      5|   throw new Error();
       |         ^
      6| });
      7| 
```

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M2
    Memory: 141.09 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.volta/tools/image/node/18.12.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.19.2 - ~/.volta/tools/image/node/18.12.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Chrome Canary: 110.0.5434.2
    Firefox: 106.0.1
    Safari: 15.6.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is intended behaviour. Describe always collects tests (for summary). But it will skip running tests.

**Comment by lpatiny** [comment]
Thanks for your quick answer.

I have test files with many `describe` and I'm used to focus on a test using `describe.only` and add some console.log in my code for development purpose.

Like for example in: https://github.com/cheminfo/peaks-similarity/blob/5c2855e0abdb43c05aa8f61676273358c0a7024a/src/__tests__/basic.test.js

I guess it is a bad habit on my side and will flatten more the tests and remove this extra `describe` layer.
