### ISSUE TITLE
toThrowError not working

### ISSUE THREAD

**Issue by sysmat** [vitest-dev/vitest#2375]
### Describe the bug

it expect with exception should work

### Reproduction

```typescript
import { describe, expect, it } from 'vitest';
import { ZodError } from 'zod';
import z from 'zod'

describe('ZOD validation', () => {    

    it('test object validation', () => {
        const CarSchema = z.object({
           sits: z.number().lte(5).positive(),
           haveAlarm: z.boolean(),
          sport: z.boolean().optional(),
        });

        expect(CarSchema.parse({
            sits: -5,
            haveAlarm: true,
            sport: 'yes',
        })).toThrowError(ZodError);
    });
});
```
- console info:

```
 FAIL  tests/validation.zod.test.ts > ZOD validation > test object validation
ZodError: [
  {
    "code": "too_small",
    "minimum": 0,
    "type": "number",
    "inclusive": false,
    "message": "Number must be greater than 0",
    "path": [
      "sits"
    ]
  },
  {
    "code": "invalid_type",
    "expected": "boolean",
    "received": "string",
    "path": [
      "sport"
    ],
    "message": "Expected boolean, received string"
  }
]

```

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz
    Memory: 3.87 GB / 15.89 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\.yarn\bin\yarn.CMD
    npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 107.0.5304.107
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.56)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitest: ^0.25.3 => 0.25.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You need to wrap your call in function:

```diff
-  expect(CarSchema.parse({
+  expect(() => CarSchema.parse({
      sits: -5,
      haveAlarm: true,
      sport: 'yes',
  })).toThrowError(ZodError);
```

Otherwise it's impossible to catch the error. Please, read [documentation](https://vitest.dev/api/#tothrowerror) before creating an issue.

**Comment by sysmat** [comment]
strong type of expect should be stronger then
