### ISSUE TITLE
Unhandled Rejection when symbolic links in package (watch mode)

### ISSUE THREAD

**Issue by infodusha** [vitest-dev/vitest#2384]
### Describe the bug

If the repository has symbolic links in repo (i have README.md symlink) after calling `vitest` unhandled rejection is thrown:
`Error: ELOOP: too many symbolic links encountered, stat 'path_to_package/README.md'`
Trying to exclude this file in the config does not help, removing file helps.
Also, everything is fine when doing `vitest run --coverage`

### Reproduction

create README.md file outside the package
`ln -s ../../README.md README.md`
`npm i vitest`
set test script to call vitest `"test": "vitest"`
create at least singe test file
`npm run test`

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 284.70 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Firefox: 103.0.2
    Safari: 16.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by infodusha** [comment]
Update:
I've found out that `vitest run` works while `vitest dev` throws and error.
It has to be watch mode throws an error so in my case adding the file to `watchExclude` helped.
I still think it worth to show detailed error message in similar cases or silently add this to ignore list.

**Comment by sheremet-va** [comment]
Vitest doesn't control the behaviour of the watcher. If you encounter any issues with the watcher, try opening an issue in [Vite](https://github.com/vitejs/vite) repo.
