### ISSUE TITLE
Restart on configuration change broken since v0.24.4

### ISSUE THREAD

**Issue by AriPerkkio** [vitest-dev/vitest#2393]
### Describe the bug

Since #2228 the automatic restart on configuration file change in watch mode broke. `vitest@0.24.3` works as expected.

By commenting out this block the crash does not happen.

https://github.com/vitest-dev/vitest/blob/824e18c3792ee63eba3e01301d897c19a47f6c9b/packages/vitest/src/node/cli-wrapper.ts#L64-L69

```
Restarting due to config changes...

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: Cannot read properties of undefined (reading 'logger')
 ❯ VerboseReporter.onCollected ../vitest/packages/vitest/dist/chunk-vite-node-externalize.fd4469d3.js:8316:46
 ❯ ../vitest/packages/vitest/dist/chunk-vite-node-externalize.fd4469d3.js:10900:51
 ❯ Vitest.report ../vitest/packages/vitest/dist/chunk-vite-node-externalize.fd4469d3.js:10898:38
 ❯ Proxy.onCollected ../vitest/packages/vitest/dist/chunk-vite-node-externalize.fd4469d3.js:7671:13
 ❯ MessagePort.<anonymous> ../vitest/packages/vitest/dist/chunk-vite-node-client.bea3705d.js:376:42
 ❯ [nodejs.internal.kHybridDispatch] node:internal/event_target:734:20
 ❯ exports.emitMessage node:internal/per_context/messageport:23:28
```

### Reproduction

Stackblitz boilerplate without any changes: https://stackblitz.com/edit/vitest-dev-vitest-vrwfeu?file=vite.config.ts&initialPath=__vitest__

Run vitest and make a whitespace change to the configuration file. 

### System Info

```shell
Stackblitz
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by LeonardoRick** [comment]
I'm getting the same error!

**Comment by AriPerkkio** [comment]
This also breaks coverage reporters on restart.

When starting Vitest, the execution order is `setServer` -> `start`. On restart it is the opposite. I'm looking into whether reporters and coverage providers could be initialized in `setServer` or some other handle executed after it instead. 

https://github.com/vitest-dev/vitest/blob/8595c0e5fd3c10c12f65a9a827a710e4ec81d099/packages/vitest/src/node/core.ts#L58

https://github.com/vitest-dev/vitest/blob/8595c0e5fd3c10c12f65a9a827a710e4ec81d099/packages/vitest/src/node/core.ts#L202
