### ISSUE TITLE
Upgrade TS to 4.9

### ISSUE THREAD

**Issue by fc** [vitest-dev/vitest#2398]
### Describe the bug

Wanted to use the new `satisfies` operator in my config but it errors out:

```
test.config.ts:94:10: ERROR: Expected "}" but found "satisfies"
```

### Reproduction

n.a

### System Info

```shell
n.a
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest doesn't do transformations, Vite does. Vite depends on esbuild. Try updating your dependencies, or create an issue there.
