### ISSUE TITLE
If you want to send PR

### ISSUE THREAD

**Issue by antfu** [vitest-dev/vitest#24]
Leave a comment below so I can give you permission to push a branch in this repo. Sorry, this has to be manual since the permission control in free GitHub org is very limited. Thanks!

When doing PR, **please do NOT commit directly to `main` branch**. Please create branch follow `<your-gh-id>/<short-describe>` and push your change to the branch to send PR. For example: `antfu/fix-typo` or `patak/feat-concurrent-mode`. Thanks

**Comment by Saul-Mirone** [comment]
Hello 👋

**Comment by patak-dev** [comment]
Hey @Saul-Mirone, no need to get write access now. You can fork the repo and send a PR from there 👍🏼
