### ISSUE TITLE
Custom snapshot console colors (A11Y)

### ISSUE THREAD

**Issue by TheJaredWilcurt** [vitest-dev/vitest#2401]
### Clear and concise description of the problem

* Colors work differently in different editors/consoles/terminals/shells/CI's/etc.
* Some people have different visual, or cognitive impairments that make certain color combinations frustrating or difficult to discern.

### Suggested solution

The default red/green approach is fine by me, and probably good for the majority of users. But it would be nice if there was a `vite.config.js` option for customizing the colors used by Vitest, particularly in snapshot failures.

```js
import chalk from 'chalk';
import { defineConfig } from 'vite';

export default defineConfig({
  test: {
    diff: {
      // I'm not sure what the API would look like here, So I'll just use what
      // jest-diff documents for this example. The following is copied directly from
      // https://github.com/facebook/jest/tree/main/packages/jest-diff#options
      aAnnotation: 'Expected',
      aColor: chalk.green,
      aIndicator: '-',
      bAnnotation: 'Received',
      bColor: chalk.red,
      bIndicator: '+',
      changeColor: chalk.inverse,
      changeLineTrailingSpaceColor: string => string,
      commonColor: chalk.dim,
      commonIndicator: ' ',
      commonLineTrailingSpaceColor: string => string,
      compareKeys: undefined,
      contextLines: 5,
      emptyFirstOrLastLinePlaceholder: '',
      expand: true,
      includeChangeCounts: false,
      omitAnnotationLines: false,
      patchColor: chalk.yellow
    }
  }
});
```

By exposing all options, it empowers communities to create their own commonly recommended settings, like so:

```js
import { defineConfig } from 'vite';
import diff from 'vitest-deuteranopia-diffs';

export default defineConfig({ test: { diff } });
```
```js
import { defineConfig } from 'vite';
import diff from 'vitest-cognitive-diffs';

export default defineConfig({ test: { diff } });
```
```js
import { defineConfig } from 'vite';
import diff from 'vitest-win-cmd-diffs';

export default defineConfig({ test: { diff } });
```
etc.
There could even be an `awesome-vitest-diffs` repo with screenshots of each library, so users can more easily choose what works best for them or their teams. This could all be community-lead, but we need Vitest to allow for this.

### Additional context

This same feature request was submitted to Jest, and approved for PR.

* https://github.com/facebook/jest/issues/12576

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by mst101** [comment]
Yes, I'd really appreciate this. I find it hard to read red text on a black background and would love to be able to use a slightly different colour.

**Comment by Fitzpaa** [comment]
Yes please!

**Comment by sheremet-va** [comment]
We now use the same `diff` method that jest uses, so it should be possible to reuse the same config. PRs to implement this are welcome. Please, note that the new option should be a string that references a module with a default export containing this config.

It should be loaded inside a test context and passed down to the `diff` method.
