### ISSUE TITLE
Support JSON config file

### ISSUE THREAD

**Issue by sagargurtu** [vitest-dev/vitest#2411]
### Clear and concise description of the problem

Support `vitest.config.json` file similar to Jest.

A JSON config file will be helpful in cases where we need to manipulate test configuration dynamically.

### Suggested solution

N/A

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
You can always create your own JSON config, and import it inside vitest.config:

```json
{
  "//": "my.custom.config.json",
  "port": 1000
}
```

```ts
import customConfig from './my.custom.config.json'

export default {
  server: {
    port: customConfig.port,
  }
}
```

**Comment by sagargurtu** [comment]
That's a nice workaround. However, we'd need to maintain two files for test configuration. In a monorepo with 'x' packages, this will mean '2x' config files.
