### ISSUE TITLE
Vitest does not filter when test name same as folder name.

### ISSUE THREAD

**Issue by ice-breaker-tg** [vitest-dev/vitest#2413]
### Describe the bug

vitest does not filter properly when the test file name is the same as the "project/root" folder name.

### Reproduction

To reproduce, have some project folder and a test file in a test dir with the same name... for example:

my-lib/test/my-lib.test.js
my-lib/test/another.test.js

vitest run my-lib -> runs all tests, not just my-lib.test.js

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
    Memory: 3.20 GB / 11.49 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 107.0.5304.121
  npmPackages:
    vitest: ^0.25.2 => 0.25.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
yeah, it checks the whole path

**Comment by poyoho** [comment]
#2404 seems to fix it. I think it is same with #2046.

**Comment by sheremet-va** [comment]
This is expected behaviour. Vitest doesn't know relative to what your tests are located. You can also use any part of the file path in the filter. If you want precise filtering, you can use fullpaths. If you are using VSCode for example, you can right click on a file and choose "Copy path".
