### ISSUE TITLE
tests are successful but process ends with error

### ISSUE THREAD

**Issue by kaminskypavel** [vitest-dev/vitest#2415]
### Describe the bug

migrating prisma examples of integration tests to vitest.
running `pnpm test` - everything is passing, but the process ends with errors

<img width="422" alt="image" src="https://user-images.githubusercontent.com/4253088/205364672-2ad3d989-beb2-4302-831f-1fb65f2be55b.png">

---

I suspect it has something to do with the in-memory mongo I'm instantiating in `vitest.setup.ts`.
jest has `--detectOpenHandles` for this case, but I couldn't find anything related in vitest.

**_off-topic_**: 

what is the recommended way to share env variable from `vitest.setup.ts` and the tests themselves? 
as per [documentation](https://vitest.dev/config/#globalsetup) 

```
WARNING
Beware that the global setup is run in a different global scope, so your tests don't have access to variables defined here.

```

### Reproduction

1. clone https://github.com/kaminskypavel/vitest-prisma-inmem-mongo
2. pnpm i
3. pnpm test

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz
    Memory: 41.38 GB / 63.82 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\.yarn\bin\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.62)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vite: ^3.2.4 => 3.2.4 
    vitest: ^0.25.3 => 0.25.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I don't think `watch` mode can ever end with non 0? Because watch mode never ends. You either Ctrl+C it (which make status code 1), or something breaks, which also makes status code 1.

Did you mean to run it as `vitest run`?

**Comment by kaminskypavel** [comment]
> I don't think `watch` mode can ever end with 0? Because watch mode never ends. You either Ctrl+C it (which make status code 1), or something breaks, which also makes status code 1.
> 
> Did you mean to run it as `vitest run`? Don't forget that watch mode is enabled by default.

yeah i did mean to `vitest run`. as so I did. now getting a segmentation fault

```
 ✓ tests/prisma.test.ts (9)
   ✓ example test with Prisma Client (9)
     ✓ test query
     ✓ create user
     ✓ create a user with posts
     ✓ Find user based on user id
     ✓ Find user and related posts based on user id    
     ✓ Find posts based on author id
     ✓ Filter posts based on title
     ✓ Update posts - increment count
     ✓ Delete post

 Test Files  1 passed (1)
      Tests  9 passed (9)
   Start at  12:49:47
   Duration  3.54s (transform 825ms, setup 0ms, collect 174ms, tests 103ms)

Segmentation fault
```

**Comment by poyoho** [comment]
![image](https://user-images.githubusercontent.com/36070057/205439379-86ad83af-52ca-470a-b70e-1afc4fb09c5e.png)
😅

**Comment by kaminskypavel** [comment]
😅😅😅
<img width="398" alt="image" src="https://user-images.githubusercontent.com/4253088/205441129-3d1f732d-3c76-411d-9a6d-ba348d1c2364.png">

**Comment by poyoho** [comment]
@kaminskypavel  So this is no an error?

**Comment by kaminskypavel** [comment]
is the `Segmentation fault` intended?

**Comment by enzoferey** [comment]
Since this is appeared at the top of the Google search, I'm leaving the two things that were causing issues on my side:

1. Not using `it.each` or `test.each` and just looping through an array creating `it` / `test` statements on the fly.
2. My project is not using Vite and I did not have a `vitest.config.ts`, it seems to be one of the three possible options to [configure](https://vitest.dev/config/#configuration) Vitest. I find the get started docs not very clear about this, it should be mentioned right below the installation command if you ask me.

**Comment by sheremet-va** [comment]
The recommended solution when working with Prisma is using the `forks` pool. Vitest 2.0 uses it by default instead of worker threads.
