### ISSUE TITLE
Better typing for `setup` method in `Environment` interface

### ISSUE THREAD

**Issue by ahnpnl** [vitest-dev/vitest#2436]
### Clear and concise description of the problem

When I tried to write a custom environment for Vitest in TypeScript, I noticed that it wasn't so handy to use args of `setup` method in `Environment` interface. 

This is because `global` args is typed as `any` and `options` are typed as `Record<string, any>`, see https://github.com/vitest-dev/vitest/blob/d43f3f5c4d88129ed35950d1f5bdb92428d55024/packages/vitest/src/types/general.ts#L39

### Suggested solution

I think we should have better types for `setup` method in `Environment` interface. For example:

- `global` arg should have more type information about what it contains.
- `options` arg should allow to have generic so that one can create interface of their test environment options and pass to it.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
`global` can contain anything. It is usually `globalThis`. `options` are ALL options that are passed down to `environmentOptions`, so.

**Comment by sheremet-va** [comment]
> Can we have at least `options` type? Besides, when I print out `global`, I see it has `config` which is typed as `InlineConfig` too. Is there a hint somewhere to tell us something always exists in `global`?

`options` as a generic? You can just use your own type in setup tho:

```ts
setup(global, options: { customEnv: MyOptionsInterface }) {}
```

We should probably pass down only needed options, but it would be a breaking change.

> Besides, when I print out global, I see it has config which is typed as InlineConfig too. Is there a hint somewhere to tell us something always exists in global?

It's `globalThis`. It should not have "config" on it, it might have `_vitest_worker_` which has config, but this is private interface.

**Comment by ahnpnl** [comment]
> > Can we have at least `options` type? Besides, when I print out `global`, I see it has `config` which is typed as `InlineConfig` too. Is there a hint somewhere to tell us something always exists in `global`?
> 
> `options` as a generic? You can just use your own type in setup tho:
> 
> ```ts
> setup(global, options: { customEnv: MyOptionsInterface }) {}
> ```

Yes this one I'm doing which is actually fine.

> 
> We should probably pass down only needed options, but it would be a breaking change.
> 
> > Besides, when I print out global, I see it has config which is typed as InlineConfig too. Is there a hint somewhere to tell us something always exists in global?
> 
> It's `globalThis`. It should not have "config" on it, it might have `_vitest_worker_` which has config, but this is private interface.

Hmm, my case is I want to access to test config which Idk where I can get it in `setup`. With Jest custom environment, Jest config is retrieved in constructor. This is actual my issue when I can't see the type hint by current type definition of `setup`.

**Comment by sheremet-va** [comment]
> Hmm, my case is I want to access to test config which Idk where I can get it in setup. With Jest custom environment, Jest config is retrieved in constructor. This is actual my issue when I can't see the type hint by current type definition of setup.

Config is not available to public interfaces currently. And even it it was, it would not be full, because it's transferred from the main thread to the worker that runs a test.

**Comment by sheremet-va** [comment]
> Can we make it somehow easy to migrate from custom Jest environment by improving the typings? That would help a lot.

Jest environments are very different than Vitest environments, so I don't think it would be possible. We already discussed it in another thread.

Vitest environment is basically `setupFile`.

**Comment by ahnpnl** [comment]
Thanks, I gonna switch to use `setupFiles` then:)
