### ISSUE TITLE
vitest warns about obsolete snapshots for from skipped tests

### ISSUE THREAD

**Issue by dominikg** [vitest-dev/vitest#2442]
### Describe the bug

vite-plugin-svelte uses `describe.runIf` to conditionally run some e2e tests only during `vite dev` or `vite build`.

One of these uses snapshots, and when the runIf condition isn't met, vitest logs that the associated snapshots are obsolete.

while true for the current run, they are still needed for others.

similar to #2174 

### Reproduction

code here: https://github.com/sveltejs/vite-plugin-svelte/blob/main/packages/e2e-tests/import-queries/__tests__/import-queries.spec.ts#L94

log output: https://github.com/sveltejs/vite-plugin-svelte/actions/runs/3628891097/jobs/6120463873#step:9:60

### System Info

```shell
linux, 
node18
vite: ^3.2.5 => 3.2.5 
vitest: ^0.25.4 => 0.25.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> Hey! Can I try to work on this one?

Yes

**Comment by samkevin1** [comment]
I'm a bit confused, is the log the problem or are these snapshots not being used?

**Comment by dominikg** [comment]
the snapshots are used conditionally, the warning is logged when the condition leads to skipped tests. but removing the snapshots would cause errors for the test that uses them with the negated condition.

**Comment by dominikg** [comment]
the value of `isBuild` in the code linked in the og report is controlled via an env var: https://github.com/sveltejs/vite-plugin-svelte/blob/360171392990cd907c87b6ba16e17d7698fe9f8e/package.json#L11
and can be both true or false.

**Comment by samkevin1** [comment]
Hmm, so it shouldn't log the warning when the tests are skipped?

**Comment by dominikg** [comment]
in my opinion, yes.a test that is conditionally skipped isn't a safe indication that a snapshot is unused.  

though that makes it harder to  detect unused too. Not sure what a different solution could look like. Maybe mark them as skipped in the list or log a separate skipped snapshots list in a lower loglevel ?

in vite-plugin-svelte we currently log an extra line to avoid accidental remove

**Comment by samkevin1** [comment]
Hey! Sorry it took so long to come back to this. Is this bug still happening? Couldn't replicate it here. @sheremet-va @dominikg

**Comment by samkevin1** [comment]
@dominikg @sheremet-va Were you guys able to replicate it?

**Comment by dominikg** [comment]
Yes, the basic pattern is a conditional test that uses a snapshot

```js
describe.runIf(someCondition)('a test using a snapshot', () => {
  test( 'a test', () => {
    expect(something).toMatchSnapshot()
  }
})
```

if `someCondition` is false, vitest logs that there is an unused snapshot.
