### ISSUE TITLE
Mock cache cann't be clear

### ISSUE THREAD

**Issue by liujiayi666** [vitest-dev/vitest#2445]
### Describe the bug

seem problems with this link， go to the repro link : [repro](https://stackblitz.com/edit/node-vzowau?file=test%2Fbasic.test.ts)  and update the vitest version to latest. case still fails！ How do I go about solving it?
https://github.com/vitest-dev/vitest/issues/1940

### Reproduction

https://stackblitz.com/edit/node-vzowau?file=test%2Fbasic.test.ts

### System Info

```shell
vitest:0.25.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
https://github.com/vitest-dev/vitest/issues/1940#issuecomment-1232470901

https://github.com/ChpShy/vitest/blob/main/test/core/test/unmock-import.test.ts
