### ISSUE TITLE
toEqual output is truncated

### ISSUE THREAD

**Issue by rcoundon** [vitest-dev/vitest#2448]
### Describe the bug

When running a test to check the equality of two objects, the output is truncated if there are more than 2 properties.

I.e. the output looks like this:
`AssertionError: expected { hello: 'world', …(3) } to deeply equal { hello: 'world', …(2) }`
Which means it's not possible to establish what was wrong.

I wondered if setting [this](https://github.com/vercel/satori/pull/47/files) might help but it doesn't seem to make a difference here 

### Reproduction

In [this](https://github.com/rcoundon/vitest-axios) repo there's a test called `it demonstrates toEqual output is truncated` in ApiCaller.test.ts that shows the problem.

### System Info

```shell
"vite": "3.2.5",
"vitest": "0.25.4",

System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 814.89 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 9.1.3 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Brave Browser: 108.1.46.134
    Chrome: 108.0.5359.94
    Edge: 108.0.1462.41
    Firefox Developer Edition: 108.0
    Safari: 16.1

"vite": "3.2.5",
"vitest": "0.25.4",
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rcoundon** [comment]
Ok, this looks like a Webstorm issue in the parsing of that output then.

**Comment by rcoundon** [comment]
It seems that tools that are parsing this are failing to do so for some reason. For example, this occurs in @vite/ui (not sure if it's meant to show the equality detail there but it seems reasonable that it would) as well as VSCode and Webstorm.

**Comment by sheremet-va** [comment]
They don’t parse it. Expected and actual exist on an error as properties to read
