### ISSUE TITLE
Failed to load when node_modules in parent directory

### ISSUE THREAD

**Issue by Lucianod28** [vitest-dev/vitest#2450]
### Describe the bug

I moved `node_modules` to it's parent directory, from `project-root/frontend` to `project-root`, now my directory structure looks like this:
```
📁 project-root
   📁 node_modules
   📁 frontend
      📄 package.json
      📄 package-lock.json
````
When I run `npx vitest` from inside `frontend`, all my tests fail with the following error:
```
Error: [vite-node] Failed to load /@fs//project-root/node_modules/vitest/dist/entry.js
 ❯ VitestRunner.directRequest ../node_modules/vitest/dist/chunk-vite-node-source-map.d0aa773d.js:237:13
```
The directory `project-root/node_modules/vitest/dist/entry.js` does exist. My understanding is `node_modules` can be in a parent directory. Other commands such as `npx vite` have no problem.

### Reproduction

Wasn't able to exactly reproduce, but moved the node_modules up a directory here and got a different error: https://stackblitz.com/edit/vitest-dev-vitest-77heac?file=package-lock.json

### System Info

```shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1270P
    Memory: 10.66 GB / 15.44 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 19.2.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.1.3 - /node_modules/.bin/npm

When I put node_modules in frontend it also outputs:
  npmPackages:
    vite: ^3.2.5 => 3.2.5 
    vitest: ^0.25.5 => 0.25.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> The directory project-root/node_modules/vitest/dist/entry.js does exist

The directory doesn't exist, because it expects full path (from the system root). This can be a regression since v0.25.4.

> Wasn't able to exactly reproduce, but moved the node_modules up a directory here and got a different error

I don't understand what you mean. Where moved? What error? Why do you provide a reproduction with a _different_ error? Please, provide a runnable reproduction.

**Comment by Lucianod28** [comment]
The error occurs when I run `npx vitest`. I copied all my configuration into Stackblitz but am getting a different `no such file or directory`. However, I've tried in multiple vitest environments and the only necessary replication steps are `mv node_modules ..` then `npx vitest`. Might try again tomorrow.

**Comment by Lucianod28** [comment]
@sheremet-va here's a reproduction, just `cd frontend` then `npx vitest`. https://github.com/Lucianod28/vitest-reproduction. The error doesn't occur if I remove `transformMode` from `vite.config.ts`

**Comment by sheremet-va** [comment]
> @sheremet-va here's a reproduction, just `cd frontend` then `npx vitest`. https://github.com/Lucianod28/vitest-reproduction. The error doesn't occur if I remove `transformMode` from `vite.config.ts`

You should not use `web`, if you don't have web framework, like Vue JSX or Solid that use jsx. If you are using react, you also don't need to enable it.

**Comment by sheremet-va** [comment]
You should probably open an issue in Vite repo. If you add this file to your `frontend` folder, you can attach the reproduction to their issues:

```js
// vite.mjs
import { createServer } from "vite";
import { fileURLToPath } from "url";
import { resolve } from "path";
const server = await createServer({
  optimizeDeps: {
    disabled: true,
  },
});
await server.listen();
const filename = fileURLToPath(import.meta.url);
const suitePath = resolve(filename, "../../node_modules/vitest/dist/suite.js");
const code = await server.transformRequest(
  `/@fs/${suitePath}`,
  { ssr: false } // works with `ssr: true`
);
console.log(code);
server.close();
```

If you run this code with `node vite.mjs` you can see it returns `null`. If you change `ssr` to `true`, it returns actual code.

**Comment by Lucianod28** [comment]
> `web`, if you don't have web framework, like Vue JSX or Solid that use jsx. If you are using react, you also don't need to enable it.

Actually I'm using Solid, I just removed all the other dependencies to minimize the reproduction.

> I think this happens for frontend code, because vite restrict filesystem access, if you don't configure `server.fs` options. If I disable this policy, it works fine:
> 
> ```ts
> // vite.config.js
> export default {
>   server: {
>     fs: {
>       strict: false,
>       allow: ['..'] // or this with `strict: true` (default)
>     }
>   }
> }
> ```
This fixed it. Interestingly, I need both `strict: false` and `allow: ['..']` to fix it (doesn't work without `strict: false`). I find it strange that this fixes it because the vite dev server runs fine without this.

**Comment by sheremet-va** [comment]
> I find it strange that this fixes it because the vite dev server runs fine without this.

Because you don't run Vitest in your browser, so you never ask for a file outside of you project. This is expected behavior.
