### ISSUE TITLE
Vite starts watcher, even if --watch is false

### ISSUE THREAD

**Issue by sheremet-va** [vitest-dev/vitest#2467]
### Describe the bug

When Vitest starts in `run` mode, watcher is initiated and later stopped. In this time watcher can start watching a lot of files.

We should probably not even initiate chokidar watcher. To do this, we need to pass down `watch: { ignored: ['*'] }` to `createServer`.

There is a problem that `watch` and `run` flags can be configured inside `vite.config`, which is resolved after `createServer` call. We should disable this, and allow `--watch` and `--run` to be configured only as CLI flags. This way we can determine watch mode before calling `createServer`. This would be a breaking change.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-q5uxuk?file=README.md&initialPath=__vitest__

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by silverwind** [comment]
> There is a problem that watch and run flags can be configured inside vite.config, which is resolved after createServer call.

Having these flags in the config is convenient though as I can just `npx vite` and have it not watch. Can the config be parsed first? Generally I'd say parsing config is the first thing a application should do.
