### ISSUE TITLE
use reporter in ci as default reporter

### ISSUE THREAD

**Issue by trim21** [vitest-dev/vitest#2477]
### Clear and concise description of the problem

`config.test.reporters` has many available options but non of them is same with current reporter in ci.

I really like the reporter in CI and it it possible to set it as default reporter instead of setting env `CI=true`?

### Suggested solution

add an reporter `default-ci` or some similar name

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by alok-runner** [comment]
In a similar vein, verbose with `CI=true` is also good. Especially as a potential "workaround" for #2602

**Comment by adam-arthur** [comment]
Confirmed that the CI reporter is not subject to the degraded performance of other console reporters. 

Thanks! Will use that for my use case now
