### ISSUE TITLE
 vitest-setup global is readonly in node v19

### ISSUE THREAD

**Issue by pwang2** [vitest-dev/vitest#2478]
### Describe the bug

following code will complains as below in Node V19. Node V16 and V18 are okay. 

```ts
import { vi } from "vitest"
import { Crypto } from "@peculiar/webcrypto"
global.crypto = new Crypto()
```
![image](https://user-images.githubusercontent.com/1592014/206824981-761398b3-3cdd-4b24-a4f3-ee50e0869efe.png)

### Reproduction

switch node runtime to node 19 and add code above to vitest-setup file.

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 18.70 GB / 24.81 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 19.2.0 - ~/.local/bin/node
    Yarn: 1.22.19 - /home/linuxbrew/.linuxbrew/bin/yarn
    npm: 9.1.3 - /home/linuxbrew/.linuxbrew/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  npmPackages:
    @vitejs/plugin-vue: ^3.2.0 => 3.2.0
    vite: ^3.2.4 => 3.2.4
    vitest: ^0.24.3 => 0.24.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Not sure what you mean? Node 19 puts global web crypto API that you cannot rewrite, there is nothing we can do currently.

**Comment by pwang2** [comment]
Oh, I don’t know that, that’s even awesome.

Thanks for the information!
