### ISSUE TITLE
Can't change mocked module with conditional exports

### ISSUE THREAD

**Issue by davletovalmir** [vitest-dev/vitest#2479]
### Describe the bug

Hi, I can't mock the constants imported from the local module, that are used in the conditional exports. See the code examples below for more context. If I run these tests, it will throw the error:

```
ReferenceError: Cannot access 'mockIsDev' before initialization
 ❯ Object.get IS_US [as IS_US] paths.test.ts:5:27
      4| const mockIsDev = vi.fn().mockReturnValue(false);
      5| 
      6| vi.mock('./constants', () => ({
       |                          ^
      7|   get IS_US() {
      8|     console.log('inside', mockIsDev());
 ❯ eval paths.ts:3:27
```

Here is the simplified version of the failing code. We use conditional exports to reduce the bundle size of our application.

**./constants.ts**
```ts
export const IS_US = process.env.REGION === "US"
```

**./paths.ts**
```ts
import { IS_US } from './constants';

export const signInPath = IS_US ? () => '/sign-in' : () => '/login';
```

**./paths.test.ts**
```ts
import { vi, test, expect } from 'vitest';
import { signInPath } from './paths';

const mockIsDev = vi.fn().mockReturnValue(false);

vi.mock('./constants', () => ({
  get IS_US() {
    console.log('inside', mockIsDev());
    return mockIsDev();
  },
}));

test('path is correct for US', () => {
  mockIsDev.mockReturnValue('hello');
  expect(signInPath()).toBe('/sign-in');
});

```

I have no idea how to test it, I tried using functions as they're also hoisted, nothing really helps. Would appreciate if you could help me to solve this issue 🙏

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-wknbcs?file=paths.ts

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 57.09 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.3 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 106.1.44.105
    Chrome: 107.0.5304.110
    Firefox: 106.0.5
    Safari: 16.1
  npmPackages:
    @vitejs/plugin-react: ^2.2.0 => 2.2.0
    vitest: ^0.25.6 => 0.25.6
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by davletovalmir** [comment]
So far, I've found several solutions:
1. Declare `mockIsDev` before importing the `signInPath`. That way module will be mocked BEFORE it's imported
2. Declare `mockIsDev` in separate file and import before the `signInPath`. Works in the same way as 1
3. In a separate file, reassign `vi.mock` to `const mockModule = vi.mock.bind(vi)` and use carefully call in the right place, it won't be hoisted. I end up with this solution and declared the generic function to mock constants module, as I'll be reusing it a lot, so now I just import `mockConstants` and mocked functions (such as `mockIsDev`) and call `mockConstants` before importing the module with conditional export (e.g. `./paths`)

If you find a better ways to resolve this problem, please let me know! 🙏

**Comment by sheremet-va** [comment]
vi.mock is hoisted, so you don't have access to variables defined in global scope.

You can use vi.doMock which does the same, but is not hoisted. But you will need to load module asynchronously after.
