### ISSUE TITLE
Ignore code coverage

### ISSUE THREAD

**Issue by freakzlike** [vitest-dev/vitest#2491]
### Describe the bug

After updating `vitest` from `0.25.4` to `0.25.7` the ignore comments for code coverage `/* istanbul ignore if -- @preserve */` are no longer working. Running `npm run test` within the reproduction with `0.25.7` will have uncovered lines. With `0.25.4` there are none.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-cg758y?file=test/basic.test.ts&view=editor

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (5) x64 AMD Ryzen 5 4500U with Radeon Graphics
    Memory: 2.95 GB / 6.79 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 8.19.3 - ~/dev/frontend-utils/node_modules/.bin/npm
  npmPackages:
    @vitejs/plugin-vue: 4.0.0 => 4.0.0
    vite: 4.0.0 => 4.0.0
    vitest: 0.25.7 => 0.25.7
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Does setting `esbuild.legalComments = 'inline'` work?

```ts
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: { ... },
  esbuild: {
    legalComments: "inline",
  },
});
```

Looks like `esbuild@0.16.0` contained breaking change affecting this:
https://github.com/evanw/esbuild/blob/main/CHANGELOG.md#0160

> - Change the default "legal comment" behavior
> [...] You now have to opt-in to preserving them if you want this behavior.

If that works, it could be something that Vitest sets by default.

**Comment by freakzlike** [comment]
Yes, it's working with `legalComments: "inline"`. Thank you

**Comment by sheremet-va** [comment]
> If that works, it could be something that Vitest sets by default.

I think this should be enabled by default in Vitest 👍🏻
