### ISSUE TITLE
How to properly handle "unhandled" exceptions 

### ISSUE THREAD

**Issue by danez** [vitest-dev/vitest#2493]
### Describe the bug

I have a test that asserts that an import throws, because the imported module is not found.

even though the actual error is caught by `expect().rejects.toThrowError()` it still shows up as unhandled.

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Error: Cannot find module 'does-not-exist'
Require stack:
- /private/var/folders/y3/2b5xsndd3zvd32j6n_ypjg5r0000gn/T/zip-it-test-bundler-nft-31679-4ePKnlfzcJsT/node-module-missing/function.js
- /var/folders/y3/2b5xsndd3zvd32j6n_ypjg5r0000gn/T/zip-it-test-bundler-nft-31679-4ePKnlfzcJsT/function.js
 ❯ Function.Module._resolveFilename node:internal/modules/cjs/loader:995:15
```

I tried marking all the folders as external, but that does nothing.

There is also this message:
```
✘ [ERROR] Could not resolve "does-not-exist"

    tests/fixtures/node-module-missing/function.js:1:25:
      1 │ module.exports = require('does-not-exist')
        ╵                          ~~~~~~~~~~~~~~~~

  You can mark the path "does-not-exist" as external to exclude it from the bundle, which will
  remove this error. You can also surround this "require" call with a try/catch block to handle this
  failure at run-time instead of bundle-time.

```
which does not fail any test, but I also cannot get rid of, even if I set the importing file as external.

### Reproduction

Minimal repro:
https://github.com/danez-labs/vitest-import-unhandled

- `npm i`
- `npm test`

Or the original problem:

https://github.com/netlify/zip-it-and-ship-it/pull/1286

- `npm i`
- `npm exec vitest -- run -t 'Throws on missing dependencies '`

### System Info

```shell
System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.90 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.asdf/installs/nodejs/lts/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Safari: 16.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is a bug in Vitest, the fix is not released yet.

**Comment by sheremet-va** [comment]
> There is also this message

You can ignore it by returning `false` from `onConsoleLog` in test config.

**Comment by danez** [comment]
> > There is also this message
> 
> You can ignore it by returning `false` from `onConsoleLog` in test config.

That does not work, it does not look like these errors go through the user log. Is this error coming from vite? I cannot find anything in vitest regarding this error message.

**Comment by sheremet-va** [comment]
> Is this error coming from vite?

Yes.

**Comment by danez** [comment]
Seems the error is coming directly[ from `esbuild`](https://github.com/evanw/esbuild/blob/9430fa02d0a149af2d363dc5879da3c3442cb17c/internal/bundler/bundler.go#L552). Funny enough the [transform API](https://esbuild.github.io/api/#transform-api) from `esbuild` (which is used in vitest/vite/rollup, not sure where exactly) has no `external` option. 🤣  So I guess I'm back to ignoring this message :)
```
Error: Transform failed with 1 error:
/Users/danieltschinder/Projects/netlify/zip-it-and-ship-it/node_modules/esbuild/lib/main.js:247:12: ERROR: Invalid option in transform() call: "external"
```
