### ISSUE TITLE
require vitest (common-js)

### ISSUE THREAD

**Issue by jcalfee** [vitest-dev/vitest#2495]
### Describe the bug

I still have non-module projects to test.  Is it possible to `require` vitest?

### Reproduction

```bash
$ wc -l node_modules/vitest/index.cjs

0 node_modules/vitest/index.cjs
```

```node
> require('vitest')
{}
```

### System Info

```shell
nodejs, vitest 0.25.7
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It is not possible to require vitest, it is ESM only.

**Comment by jcalfee** [comment]
That is what I was thinking.  But I tried again under v14.19.3 were package.json does not mark this as a module and my test file ends in `.js`.  I could mix imports:

```js
import { expect, test } from 'vitest'
const debug = require('debug')
//...
```
And naturally the other common js files can require each other..

I was prepared to hack it by getting my own require instance, but that was not needed.  To my surprise it worked.  Must be nodejs making progress.

**Comment by sheremet-va** [comment]
> That is what I was thinking. But I tried again under v14.19.3 where package.json is not marking this as a module and my test file ends in `.js`. I could mix imports:
> 
> ```js
> import { expect, test } from 'vitest'
> const debug = require('debug')
> //...
> ```
> 
> And naturally the other common js files can require each other.. I was prepared to hack it by getting my own require instance, but that was not needed. To my surprise it worked. Must be nodejs making progress.

If you are running it with `vitest` command, then Vitest treats your code as ESM. You can use both require and import inside, because `vite-node` allows it.
