### ISSUE TITLE
[feat] - Add `coverageReporters` CLI flag

### ISSUE THREAD

**Issue by khalwat** [vitest-dev/vitest#2502]
### Clear and concise description of the problem

I'd like to create a coverage badge using Vitest as per this article:

https://dev.to/thejaredwilcurt/coverage-badge-with-github-actions-finally-59fa

...which I'd previously done with my Jest tests. Unfortunately, Vitest [doesn't appear to have](https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/node/cli.ts#L14) the [`coverageReporters`](https://jestjs.io/docs/configuration#coveragereporters-arraystring--string-options) option that the setup mentioned in the article has.

### Suggested solution

Add the `coverageReporters` CLI option to override the `coverage/reporters` setting from the config.

### Alternative

Some other way to support coverage badge generation via GitHub actions

### Additional context

This would also satisfy this issue: https://github.com/vitest-dev/vitest/issues/2288

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
You can use `--coverage.reporters` CLI flag

**Comment by khalwat** [comment]
With this script: 
```json
    "test-ci": "vitest run --coverage --coverage.reporters='text-summary'",
```

the output is:

```
vitest run --coverage --coverage.reporters='text-summary'

file:///app/node_modules/vitest/dist/cli.js:235
    t = t[keys[i]] = i === length - 1 ? val : x != null ? x : !!~keys[i + 1].indexOf(".") || !(+keys[i + 1] > -1) ? {} : [];
                   ^

TypeError: Cannot create property 'reporters' on boolean 'true'
    at setDotProp (file:///app/node_modules/vitest/dist/cli.js:235:20)
    at CAC.mri (file:///app/node_modules/vitest/dist/cli.js:628:9)
    at CAC.parse (file:///app/node_modules/vitest/dist/cli.js:543:27)
    at file:///app/node_modules/vitest/dist/cli.js:668:5
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async main (file:///app/node_modules/vitest/dist/cli-wrapper.js:59:5)
```

**Comment by sheremet-va** [comment]
Don’t use single —coverage. If its not working with just reporters, use —coverage.enabled

**Comment by khalwat** [comment]
Got it. This is the syntax that works:

```json
    "test-ci": "vitest run --coverage.enabled --coverage.reporter='text-summary'",
```

Thank you, closing it up!
