### ISSUE TITLE
Add ability to expose "vitest --ui" for using with Docker

### ISSUE THREAD

**Issue by the-illarionov** [vitest-dev/vitest#2506]
### Clear and concise description of the problem

I'm using Docker and want to make separate container for testing, so i can have something like "localhost/__vitest__" on my main proxy and it will redirect to that container. But since "vitest --ui" fires a server with "localhost" only it's impossible.

### Suggested solution

Add ability to expose just like with "vite --host --port=80"

### Alternative

Right now i have to install nginx on that container and use it to proxy requests to vitest ui.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Did you try `--api.host`?

**Comment by the-illarionov** [comment]
@sheremet-va isn' it for api only? I want to use [vitest ui](https://vitest.dev/guide/ui.html)

**Comment by the-illarionov** [comment]
@sheremet-va my bad, i thought "vitest --ui" spawns dedicated server
