### ISSUE TITLE
window.customElements.whenDefined times out (web component support)

### ISSUE THREAD

**Issue by itm-platform** [vitest-dev/vitest#2507]
### Describe the bug

When testing ` return window.customElements.whenDefined('my-component').then(() => {` or `await window.customElements.whenDefined('my-component');` the test times out.

I have tried jsdom and happy-dom

### Reproduction

```js
/**
 * @vitest-environment jsdom
 */
// also tried with 'happy-dom'

import { ITMButton } from '../../src/itm-button.js';
import { afterEach, describe, test, expect } from 'vitest';

describe('ITMButton', () => {
    afterEach(() => {
        document.body.innerHTML = ''; document.head.innerHTML = '';
    });

    test('return promise times out', () => { // It times out (revolves in 20 milliseconds in the browser)
        const button = document.createElement('itm-button');
        return window.customElements.whenDefined('itm-button').then(() => {
            button.setAttribute('type', 'primary');
            expect(button.getAttribute('type')).toBe('primary');
        });
    });

    test('return await times out', async () => { // It times out (revolves in 20 milliseconds in the browser)
        const button = document.createElement('itm-button');
        await window.customElements.whenDefined('itm-button');
        button.setAttribute('type', 'primary');
        expect(button.getAttribute('type')).toBe('primary');
    });

    test('using setTimeout instead of window.customElements.whenDefined', () => { // It passes.
        const button = document.createElement('itm-button');
        setTimeout(() => {
            button.type = 'invalidTypeThatWillBeReplacedByPrimary';
            expect(button.type).toBe('primary');
        }, 200);
    });
});
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 5.53 GB / 15.86 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 108.0.5359.124
    Edge: Spartan (44.22621.819.0), Chromium (108.0.1462.46)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Your reproduction doesn't have all needed code. What is `itm-button.js`? Is it where it supposed to be? Do you have other packages installed? What Vitest version are you using? Please, provide a runnable reproduction (so maintainers can just download it and run).

**Comment by itm-platform** [comment]
Nothing like creating a reproduction. I missed the component definition. Sorry about that, and thanks.
