### ISSUE TITLE
Vitest v24+ appears to break some default exports

### ISSUE THREAD

**Issue by kyle-sawatsky** [vitest-dev/vitest#2509]
### Describe the bug

While upgrading to Vite 4 I also needed to upgrade vitest which was at 0.23.4.

Upgrading to any version of 0.24.x appears to break imports of modules that use a default export. I personally encountered this with `react-dropzone` and `react-router-navigation-prompt`.

### Reproduction

This stackblitz (https://stackblitz.com/edit/github-w9fjy7-juwvvx) has vitest at 0.23.4 and it renders the dropzone.

This one (https://stackblitz.com/edit/github-w9fjy7-9uzxfy) fails because the import from `react-dropzone` ends up being an object, not the functional component. The only different is vitest at 0.24.4

I am not an expert in all the clashes with different module types etc. but the changelog doesn't seem to indicate that this would be an issue.

### System Info

```shell
System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.17 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Safari: 16.2
  npmPackages:
    @vitejs/plugin-react: ^3.0.0 => 3.0.0 
    vite: ^4.0.0 => 4.0.1 
    vitest: ^0.24.4 => 0.24.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by charles-stuart-appdetex** [comment]
I'm seeing this with named exports. Using `0.23.4` solves the issue.
