### ISSUE TITLE
Can't properly access got request parameters as types are not resolving

### ISSUE THREAD

**Issue by christian-bromann** [vitest-dev/vitest#2514]
### Describe the bug

I tried to find projects using [`got`](https://github.com/sindresorhus/got) with Vitest without success. I wonder how to access the `got` mock properly given that:

```ts
expect(vi.mocked(got).mock.calls[0][1].pathname);
```

fails as:

```ts
vi.mocked(got).mock.calls[0]
```

resolves into:

```ts
[url: undefined, options: undefined, defaults: Options]
```

making it impossible to have type safety when accessing the parameters. This might also be related to the `got` library as it seems the last option from [`GotRequestFunction`](https://github.com/sindresorhus/got/blob/main/source/types.ts#L146-L179) is being used. Given Vitest has no idea how `got` was used I assume it takes the last entry as it matches all others as well. However I wonder what would be the best way to resolve this?

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-a1gs2v?file=test/suite.test.ts

### System Info

```shell
n/a
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I don't think it's possible to create a type that inherits overloads in TypeScript? I will always fallback to the last one.
