### ISSUE TITLE
Respect vite.config.ts resolve.dudupe configuration

### ISSUE THREAD

**Issue by cpakken** [vitest-dev/vitest#2521]
## use case

I built an utility library which has `mobx` as an externalized dependency. Let's call it `mobx-utils`

I have another project that consumes this utility library with 'mobx-utils' via pnpm locally (symlinked)
```js
//package.json 
"mobx-utils": link../relative/path/to/file, //symlinked
"mobx": "^6"
```
```js
//vite.config.js
resolve: {dedupe: ['mobx']}
```

In normal `vite dev`, this works fine with both app and mobx-utils using the same 'mobx' instance

In vitest, I keep getting errors because `mobx-utils > mobx` and `app > mobx` is resolved to a different location. Both using its closest `mobx` module based on its `node_modules` resolution path

### Reproduction

Don't know how I can replicate locally linked pnpm setup using stackblitz

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
    Memory: 1.04 GB / 7.96 GB
  Binaries:
    Node: 18.1.0 - C:\Program Files\nodejs\node.EXE      
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.8.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.46)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vite: ^4.0.0 => 4.0.1
    vitest: ^0.25.8 => 0.25.8
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Have you tried using test.deps.inline? Vitest doesn't resolve paths inside node_modules automatically.

**Comment by sheremet-va** [comment]
> Don't know how I can replicate locally linked pnpm setup using stackblitz

You don't have to use stackblitz.

**Comment by cpakken** [comment]
Sorry, I made a minimal reproduction here
https://github.com/cpakken/vitest-dedupe

**Comment by sheremet-va** [comment]
You reproduction doesn't have vite config though? What is the error that you are receiving? And what do you expect to receive?

**Comment by sheremet-va** [comment]
Also, for Vite resolution to work, you need to inline your external dependencies. In your case, your utils are externalized by default. Use this config to enable Vite resolution algorithm to your plugins:

```ts
export default {
  test: {
    deps: {
      inline: [/mobx-utils/],
    },
  },
};
```

**Comment by sheremet-va** [comment]
> I updated the test repo to include these changes, but still no dice.

Please, reread my message. You need to use regex, not a string.

**Comment by cpakken** [comment]
Thanks for the help, that did the trick.
