### ISSUE TITLE
Issue with spyOn mockImplementation in a class after reset

### ISSUE THREAD

**Issue by pmosconi** [vitest-dev/vitest#2523]
### Describe the bug

I am mocking a class method
`  spy = vi
    .spyOn(client, 'mySqrt')
    .mockImplementation((_) => {
      return 42;
      });
});`
The mock works correctly the first time (before reset), but it returns undefined after being reset.

### Reproduction

[https://github.com/pmosconi/vitest-issue](https://github.com/pmosconi/vitest-issue)

The same code is in 2 tests one after another, mock is set in beforeAll and reset in afterEach
Actual: second test fails
Expected: both succeed.

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 16.60 GB / 31.76 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vite: ^4.0.1 => 4.0.1
    vitest: ^0.25.8 => 0.25.8
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is expected behaviour: https://vitest.dev/api/#mockreset

If you want to clear the state of `.mock` (calls, results), use `vi.mockClear()`: https://vitest.dev/api/#mockclear

**Comment by pmosconi** [comment]
Thank you very much for pointing out my mistake and for the great work!
