### ISSUE TITLE
Vitest doesn't read variables starting with VITE_* in .env files 

### ISSUE THREAD

**Issue by remiconnesson** [vitest-dev/vitest#2529]
### Describe the bug

Despite having .env files at the root of the project with variables prefixed with `VITE_` , those variables aren't available  in the unit tests.

I'm running WSL2 with a vite project straight out of `npm init vue` with typescript and vitest

### Reproduction

https://github.com/remiconnesson/vitest-bug-import-meta-env

there's a bunch of `.env` files at the root

`npm run dev` shows vite can read the env files
<img width="307" alt="image" src="https://user-images.githubusercontent.com/28846642/208423549-9cce0ea4-943b-42e6-a848-5a0411f129b0.png">

but `npm run test:unit` shows vitest can't
<img width="775" alt="image" src="https://user-images.githubusercontent.com/28846642/208423773-5a22dbe2-04be-4a99-8b4e-9ffdb6d4f6ea.png">

the variable is undefined

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 9 6900HS with Radeon Graphics
    Memory: 14.26 GB / 15.26 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 19.1.0 - ~/.nvm/versions/node/v19.1.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v19.1.0/bin/npm
  npmPackages:
    @vitejs/plugin-vue: ^3.1.2 => 3.2.0
    vite: ^3.1.8 => 3.2.5
    vitest: ^0.24.3 => 0.24.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Your reproduction works for me with `pnp install`/`npx vitest`:

<img width="578" alt="Screenshot 2022-12-19 at 15 19 21" src="https://user-images.githubusercontent.com/16173870/208424681-afa600b7-1740-4a99-9208-ecc2aca4e750.png">

But you have `root` option specified to `src`, which is why it's not working for you. Env files are determined against the root by Vite, not Vitest.

**Comment by remiconnesson** [comment]
Amazing thank you..

I didn't notice this option `--root` in the package.json which wan't there a couple of months ago in the starter code provided
<img width="548" alt="image" src="https://user-images.githubusercontent.com/28846642/208425672-4d5b341e-b70c-455c-9ee6-3bf27edbdc4b.png"> 

Spend an hour trying to debug my old code after updating when it was just under my nose.

Thanks
