### ISSUE TITLE
0.26.0 causes TypeError: __vite_ssr_import_1__.default.fileURLToPath is not a function

### ISSUE THREAD

**Issue by NathanVss** [vitest-dev/vitest#2531]
### Describe the bug

The upgrade from `0.25.7` to `0.26.0` causes this crash when running `vitest run`

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: __vite_ssr_import_1__.default.fileURLToPath is not a function
 ❯ ../../node_modules/vitest/dist/chunk-utils-env.03f840f2.js:256:64
    255| const defaultPort = 51204;
    256| const EXIT_CODE_RESTART = 43;
    257| const API_PATH = "/__vitest_api__";
       |                                  ^
    258| const configFiles = [
    259|   "vitest.config.ts",
 ❯ VitestRunner.directRequest ../../node_modules/vite-node/dist/client.mjs:283:5
 ❯ VitestRunner.cachedRequest ../../node_modules/vite-node/dist/client.mjs:146:14
 ❯ VitestRunner.dependencyRequest ../../node_modules/vite-node/dist/client.mjs:181:14
 ❯ async /node_modules/vitest/dist/chunk-typecheck-constants.3f865d14.js:3:31
 ❯ VitestRunner.directRequest ../../node_modules/vite-node/dist/client.mjs:283:5
 ❯ VitestRunner.cachedRequest ../../node_modules/vite-node/dist/client.mjs:146:14
 ❯ VitestRunner.dependencyRequest ../../node_modules/vite-node/dist/client.mjs:181:14
 ❯ async .../node_modules/vitest/dist/entry.js:3:31
 ❯ VitestRunner.directRequest ../../node_modules/vite-node/dist/client.mjs:283:5

```

### Reproduction

Upgrading to `0.26.0`

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 280.63 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by danez** [comment]
I have the same problem: here is a minimal repro: https://github.com/danez-labs/vitest-import-url

This happens when the `url` package is installed in the project.
https://www.npmjs.com/package/url

**Comment by SirZach** [comment]
Been trying to fix this all morning. I noticed if I added
```
console.log(url.fileURLToPath)
```
to the `node_modules/vitest/dist/chunk-utils-env.<build number>.js` file, the log output goes back and forth between logging
```
[Function: fileURLToPath]
```
and `undefined`

**Comment by sheremet-va** [comment]
You should be able to fix this temporary by enabling `deps.interopDefault`. I will look into why this doesn't work natively tomorrow.

**Comment by SirZach** [comment]
Added to my `vitest.config.ts` file
```
/// <reference types="vitest" />

import { defineConfig } from "vite";

export default defineConfig({
  test: {
    globals: true,
    environment: "happy-dom",
    deps: {
      interopDefault: true,
    },
  },
});
```
But getting the same error

**Comment by ffxsam** [comment]
Same issue here. Reverting to 0.25.7 fixes this.

**Comment by sheremet-va** [comment]
Another workaround:

```ts
export default {
  test: {
    alias: {
      url: "node:url",
    },
  }
}
```

**Comment by betabandido** [comment]
Enabling `deps.interopDefault` doesn't work for me either. And, I cannot revert to 0.25, since 0.26 fixed an issue when importing default exports from some dependencies.
