### ISSUE TITLE
Vitest 0.26.0 crashes with 'TypeError: Writable is not a constructor'

### ISSUE THREAD

**Issue by jeff-wishnie** [vitest-dev/vitest#2533]
### Describe the bug

After upgrading 0.25.8 -> 0.26.0 Vitest fails a simple unit test run with:
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/84994260/208482341-337f07c0-672e-43a5-bc02-338d06df6365.png">

```
 ERROR  TypeError: Writable is not a constructor                                                                                                                                 09:07:36


 ERROR   ❯ setupConsoleLogSpy ../../.yarn/__virtual__/vitest-virtual-7105f2e077/0/cache/vitest-npm-0.26.0-ecce3965e0-5a603e57f6.zip/node_modules/vitest/dist/chunk-runtime-setup.4c1b529e.js:106:18


 ERROR      104|         timers.set(id, timer);                                                                                                                                  09:07:36
    105|       }
    106|       let buffer = stdoutBuffer.get(id);
       |                  ^
    107|       if (!buffer) {
    108|         buffer = [];


 ERROR   ❯ Module.setupGlobalEnv ../../.yarn/__virtual__/vitest-virtual-7105f2e077/0/cache/vitest-npm-0.26.0-ecce3965e0-5a603e57f6.zip/node_modules/vitest/dist/chunk-runtime-setup.4c1b529e.js:40:5


 ERROR   ❯ run ../../.yarn/__virtual__/vitest-virtual-7105f2e077/0/cache/vitest-npm-0.26.0-ecce3965e0-5a603e57f6.zip/node_modules/vitest/dist/entry.js:59:3                      09:07:36


 ERROR   ❯ ../../.yarn/cache/tinypool-npm-0.3.0-e11f8ec8eb-92291c309e.zip/node_modules/tinypool/dist/esm/worker.js:109:20                                                        09:07:36
```

Resolution: Reverted to 0.25.8

### Reproduction

don't think a repro is needed, but can add if required

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 308.41 MB / 32.00 GB
    Shell: 5.2.15 - /opt/homebrew/bin/bash
  Binaries:
    Node: 19.3.0 - /opt/homebrew/bin/node
    Yarn: 3.3.0 - /opt/homebrew/bin/yarn
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Edge: 108.0.1462.54
    Firefox: 107.0.1
    Safari: 16.1

Stack:
- Vite 4.0.2
- Vue 3.2.45
- TypeScript 4.9.3
- Yarn: 3.3.0 w/PnP
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alexlafroscia** [comment]
I'm getting a very similar error with an import of `EventEmitter`:

```js
import { EventEmitter } from 'node:events';

let emitter: EventEmitter;

beforeEach(() => {
  emitter = new EventEmitter();
});
```

This worked perfectly fine with `vitest@0.23.4` but now is failing with the following error on `0.26.0`:

```
TypeError: EventEmitter is not a constructor
 ❯ tests/utils/events.test.ts:14:15
     12| 
     13| beforeEach(() => {
     14|     emitter = new EventEmitter();
       |               ^
     15| });
     16| 
```

If I use a `debugger` to explore what's imported, the module seems incorrect:

<img width="657" alt="CleanShot 2022-12-19 at 12 48 59@2x" src="https://user-images.githubusercontent.com/1645881/208488309-205f36bf-002f-4684-97e5-c6caeac28b61.png">

`__vite_ssr_import_0__` is the import of `node:events`; it seems odd that it would only have the `default` and `once` exports when in reality, there are lot more things exported from `node:events`.

**Comment by alexlafroscia** [comment]
I wonder if this is related to #2512, which changed some handling around named imports... I wouldn't expect that to have affected imports from `node:*` modules, but maybe that was an unintended side-effect?

**Comment by sheremet-va** [comment]
This is imported with `await import()`. Does importing this in native Node gives the same result? If yes, this is intended change.

**Comment by alexlafroscia** [comment]
> This is imported with `await import()`

What are you indicating is imported this way?

>  Does importing this in native Node gives the same result? If yes, this is intended change.

No; the native behavior does not match what I'm seeing in Vitest. If I use the Repl to import `node:events`, I can access an `EventEmitter` named export without issue

```
Welcome to Node.js v16.15.0.
Type ".help" for more information.
> const { EventEmitter } = await import('node:events');
undefined
> EventEmitter
<ref *1> [Function: EventEmitter] {
  once: [AsyncFunction: once],
  on: [Function: on],
  getEventListeners: [Function: getEventListeners],
  EventEmitter: [Circular *1],
  usingDomains: true,
  captureRejectionSymbol: Symbol(nodejs.rejection),
  captureRejections: [Getter/Setter],
  EventEmitterAsyncResource: [Getter],
  errorMonitor: Symbol(events.errorMonitor),
  defaultMaxListeners: [Getter/Setter],
  setMaxListeners: [Function (anonymous)],
  init: [Function (anonymous)],
  listenerCount: [Function (anonymous)]
}
```
