### ISSUE TITLE
Double reporters with config and cli parameter

### ISSUE THREAD

**Issue by polRk** [vitest-dev/vitest#2537]
### Describe the bug

In console prints two reports if one define in vitest.config.ts and another define via cli arg `--reporter=verbose`

```output
$ npx vitest --reporter=verbose

 DEV  v0.16.0 ~/packages/h


 DEV  v0.16.0 ~/packages/h

 ✓ src/h.test.ts (5)
 ✓ src/h.test.ts (5)
   ✓ h (5)
     ✓ should render open and close tags
     ✓ should render attributes
     ✓ should escape double quote in attribute value
     ✓ should stringify attribute value
     ✓ should render body

Test Files  1 passed (1)
     Tests  5 passed (5)
      Time  484ms (in thread 1ms, 48363.75%)


Test Files  1 passed (1)
     Tests  5 passed (5)
      Time  484ms (in thread 1ms, 48400.27%)


 PASS  Waiting for file changes...
       press h to show help, press q to quit

 PASS  Waiting for file changes...
       press h to show help, press q to quit
```

### Reproduction

```
import { defineConfig } from 'vitest/config'

export default defineConfig({
	test: {
		reporters: 'default',
	},
})
```

npx vitest --reporter=verbose

### System Info

```shell
System:
    OS: macOS 12.6.1
    CPU: (8) arm64 Apple M1
    Memory: 110.00 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.0 - ~/.nvm/versions/node/v19.0.0/bin/node
    npm: 9.0.1 - ~/.nvm/versions/node/v19.0.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mysteryven** [comment]
I want to try  provide a PR, but I found the `reporters` support Array, may be merge command args with config file and show two reporters result is not a bug. Did I get it wrong?

**Comment by sheremet-va** [comment]
> I want to try provide a PR, but I found the `reporters` support Array, may be merge command args with config file and show two reporters result is not a bug. Did I get it wrong?

It shouldn't merge, but override.
