### ISSUE TITLE
c8 coverage seems broken when testing vue file with style tag

### ISSUE THREAD

**Issue by Polluux** [vitest-dev/vitest#2539]
### Describe the bug

Hi,
I'm using c8 for test coverage in a Vite/Vue project and encountered an issue while testing a `.vue` file with a `<style>` tag.
When having a `<style>` tag with content, coverage report indicate only 1 line, and 100% coverage.
Removing the tag content causes the coverage report to display correct values.
(Running test with `istanbul` does not raise this issue.)

**Result**:
Statements   : 100% ( 1/1 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 1/1 )

**Expected Result**:
Statements   : 91.66% ( 11/12 )
Branches     : 0% ( 0/1 )
Functions    : 100% ( 0/0 )
Lines        : 91.66% ( 11/12 )

### Reproduction

Here is a repository to reproduce : https://github.com/Polluux/demo-c8-issues
(Note : This repository contains multiple issues for c8)

### System Info

```shell
System: 
  Ubuntu 22.04.1 LTS x86_64 GNU/Linux
Node:
  v16.15.1
Dependencies:
  "vue": "^3.2.45"
  "@vitejs/plugin-vue": "^4.0.0",
  "@vitest/coverage-c8": "^0.26.0",
  "@vue/test-utils": "2.2.6",
  "c8": "^7.12.0",
  "jsdom": "^20.0.3",
  "typescript": "^4.9.4",
  "vite": "^4.0.2",
  "vitest": "^0.26.0",
  "vue-tsc": "^1.0.14"
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
This one is weird. There seems to be some flakiness in how sourcemaps load. I can reproduce the issue about 70% times, but rest of the runs work fine. When coverage is incorrect, the sourcemaps seem to be missing `source` and `sourceContent`.

~30% of the runs look fine, as below.  
```
--------------|---------|----------|---------|---------|-------------------
File          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
--------------|---------|----------|---------|---------|-------------------
All files     |   93.33 |        0 |     100 |   93.33 |                   
 StyleTag.vue |   93.33 |        0 |     100 |   93.33 | 3                 
--------------|---------|----------|---------|---------|-------------------

=============================== Coverage summary ===============================
Statements   : 93.33% ( 14/15 )
Branches     : 0% ( 0/1 )
Functions    : 100% ( 0/0 )
Lines        : 93.33% ( 14/15 )
================================================================================
```
