### ISSUE TITLE
c8 coverage seems broken when using import.meta.env

### ISSUE THREAD

**Issue by Polluux** [vitest-dev/vitest#2540]
### Describe the bug

Hi,
I'm using c8 for test coverage in a Vite/Vue project and encountered an issue when using `import.meta.env`.
Vue project is written in OptionAPI, and `.vue` files import `.ts` files.
When using `import.meta.env` in an imported `.ts` file, coverage report indicate only 1 line, and 100% coverage.
Commenting the line causes the coverage report to display correct values.
(Running test with `istanbul` does not raise this issue.)
(Using script in `.vue` as SFC does not raise this issue.)

**Result**:
Statements   : 100% ( 7/7 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 7/7 )

**Expected Result**:
Statements   : 94.73% ( 18/19 )
Branches     : 50% ( 1/2 )
Functions    : 100% ( 1/1 )
Lines        : 94.73% ( 18/19 )

### Reproduction

Here is a repository to reproduce : https://github.com/Polluux/demo-c8-issues
(Note : This repository contains multiple issues for c8)

### System Info

```shell
System: 
  Ubuntu 22.04.1 LTS x86_64 GNU/Linux
Node:
  v16.15.1
Dependencies:
  "vue": "^3.2.45"
  "@vitejs/plugin-vue": "^4.0.0",
  "@vitest/coverage-c8": "^0.26.0",
  "@vue/test-utils": "2.2.6",
  "c8": "^7.12.0",
  "jsdom": "^20.0.3",
  "typescript": "^4.9.4",
  "vite": "^4.0.2",
  "vitest": "^0.26.0",
  "vue-tsc": "^1.0.14"
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Polluux** [comment]
Using `process.env` instead of `import.meta.env` does not raise this issue neither.

**Comment by AriPerkkio** [comment]
I'm able to reproduce the issue and can fix it by modifying the C8 provider's `map.sourcesContent`. Below on the left side is the fixed case, right one is the original one. @Polluux I guess the left side looks as expected?

![image](https://user-images.githubusercontent.com/14806298/210132953-7db670b6-2920-411f-92f3-3b7587a793c0.png)

Manipulating the `map.sourcesContent` directly does not seem like right solution though. Need to study the root cause in more details.
This is likely causing some of the other reported C8 issues.
