### ISSUE TITLE
Web Worker Message event doesn't have data property  when using happy-dom

### ISSUE THREAD

**Issue by kalvenschraut** [vitest-dev/vitest#2543]
### Describe the bug

Seems the problem is trying to set the data property in the constructor, can see in node REPL that same issue occurs.  JSDOM pollyfills MessageEvent while happy-dom does not.

I could see argument that this is an issue with Node and happy-dom  suggest people pollyfill/get happy-dom to add one.

Wasn't to hard to polyfill myself in the meantime, as all I did was the following in a Setup file
```ts
globalThis.MessageEvent = class MessageEvent extends globalThis.MessageEvent {
  constructor(type, init) { 
    super(type);
    for (const key in init) {
      this[key] = init[key];
    }
  }
};
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-xz2plj?file=package.json,src%2Fworker.ts,test%2Fsuite.test.ts,vite.config.ts&initialPath=__vitest__

### System Info

```shell
used stackblitz
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
We can polifyll this ourselves with a check:

```ts
// Node.js doesn't put properties from initDict on event
function checkMessageEventPolyfill() {
  const event = new MessageEvent('message', { data: {} })
  return !!event.data
}
if (!checkMessageEventPolyfill()) {
  globalThis.MessageEvent = ...
}
```

**Comment by sheremet-va** [comment]
> I could see argument that this is an issue with Node and happy-dom suggest people pollyfill/get happy-dom to add one.

This problem only happens with happy-dom. Node's original `MessageEvent` works fine, even in stackblitz.

**Comment by kalvenschraut** [comment]
Weird I could have sworn it didn't work for me when I did a test using the node REPL, but not that same test is working when I tried now.

Makes this a bit more puzzling since apparently happy dom doesn't do anything with MessageEvent. Will confirm I suppose.

**Comment by capricorn86** [comment]
Hi! :wave: 

David from Happy DOM here. I noticed this bug report.

Happy DOM has implemented [MessageEvent](https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent), together with some related features such as e [Window.postMessage()](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) and iframes now. However, support for workers has not yet been implemented.

I have added this ticket for adding support for it:
https://github.com/capricorn86/happy-dom/issues/839
