### ISSUE TITLE
`structuredClone` is not defined 

### ISSUE THREAD

**Issue by mrm007** [vitest-dev/vitest#2547]
### Describe the bug

Same as #1568 but this time using the right Node.js version

### Reproduction

Create a file containing:

```js
structuredClone({});
```

and run it with `vite-node`.

Result:

```
➜ na vite-node scratch.ts                  
/___/scratch.ts:1
'use strict';async (__vite_ssr_import__,__vite_ssr_dynamic_import__,__vite_ssr_exports__,__vite_ssr_exportAll__,__vite_ssr_import_meta__,require,exports,module,__filename,__dirname)=>{{structuredClone({});
                                                                                                                                                                                         ^

ReferenceError: structuredClone is not defined
    at /___/scratch.ts:1:1
    at ViteNodeRunner.directRequest (file:///___/node_modules/.pnpm/vite-node@0.26.1_@types+node@18.11.17/node_modules/vite-node/dist/client.mjs:287:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ViteNodeRunner.cachedRequest (file:///___/node_modules/.pnpm/vite-node@0.26.1_@types+node@18.11.17/node_modules/vite-node/dist/client.mjs:147:14)
    at ViteNodeRunner.executeFile (file:///___/node_modules/.pnpm/vite-node@0.26.1_@types+node@18.11.17/node_modules/vite-node/dist/client.mjs:124:12)
    at CAC.run (file:///___/node_modules/.pnpm/vite-node@0.26.1_@types+node@18.11.17/node_modules/vite-node/dist/cli.mjs:678:5)
```

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 66.13 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.volta/tools/image/node/18.12.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.19.2 - ~/.volta/tools/image/node/18.12.1/bin/npm
    Watchman: 2022.12.05.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0
    Firefox Developer Edition: 107.0
    Safari: 16.2
  npmPackages:
    vitest: ^0.26.1 => 0.26.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Check your Node environment. ViteNode doesn't polyfill or remove anything.

**Comment by mrm007** [comment]
@sheremet-va you're right. Explanation below:

I am using Volta and `pnpm` was installed on Node.js 16. In Volta, [when you install](https://docs.volta.sh/advanced/packages#pinned-node-version) a tool it's pinned to the version of Node.js you were using at the time.

Changing the original file to this will provide more context:

```js
import { version } from 'process';

console.log('Node version:', version);
console.log('structuredClone:', structuredClone({}));
```

In my case, the output was:

```
Version: v16.16.0
structuredClone({});
^

ReferenceError: structuredClone is not defined
    at /___/scratch.ts:5:1
```

Running with `volta run --node 18 pnpm vite-node scratch.ts` works as expected:

```
Node version: v18.12.1
structuredClone: {}
```
