### ISSUE TITLE
0.26.1 failed to load url of virtual module on Windows

### ISSUE THREAD

**Issue by kingyue737** [vitest-dev/vitest#2548]
### Describe the bug

No such issue for Linux

Clone the repo and run on Windows
```sh
pnpm install
pnpm run test
```

Test will fail with the following error:
```sh
 FAIL  test/pages.test.ts [ test/pages.test.ts ]
Error: Failed to load url D:/webprojects/vitest-pages-bug/@vite-plugin-pages/route-block (resolved id: D:/webprojects/vitest-pages-bug/@vite-plugin-pages/route-block). Does the file exist?
 ❯ loadAndTransform node_modules/.pnpm/vite@4.0.2_@types+node@18.11.17/node_modules/vite/dist/node/chunks/dep-6305614c.js:40425:21
```

### Reproduction

https://github.com/kingyue737/vitest-pages-bug

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
    Memory: 3.67 GB / 15.86 GB
  Binaries:
    Node: 16.15.1 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (108.0.1462.46)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitejs/plugin-vue2: ^2.2.0 => 2.2.0
    vite: latest => 4.0.2
    vitest: latest => 0.26.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by robinlieson92** [comment]
Any update on this issue?

**Comment by sheremet-va** [comment]
> Any update on this issue?

I personally can't work on it until January 2nd. If someone else wants to try and fix it, ho ahead 👍

**Comment by moishinetzer** [comment]
I'm currently having a very similar issue to this! I believe it's something to do with the way files are being resolved in Windows. 

I have pretty much the same config except I have the following in my `vitest.config.ts`:

```ts
plugins: [react(), tsconfigPaths()],
```

For me, when I have the above, none of the tests are resolved / found and the RUN statement returns completely blank. Meaning here is an example full output:

```sh
 RUN  v0.26.2 /home/moishi/projecttest
```

Followed by blank, meaning the default command prompt. 

After commenting out tsconfigPaths, my tests show like this:

```sh
 RUN  v0.26.2 /home/moishi/capply

 ❯ test/unit/services/shipments.test.ts (0)
 ❯ test/unit/services/shipments.test.ts (0)
 ❯ test/unit/services/locations.test.ts (0)
 ❯ test/unit/services/shipments.test.ts (0)
 ❯ test/unit/services/locations.test.ts (0)
 ❯ test/unit/utils/filter-query.test.ts (0)
 ❯ test/unit/services/shipments.test.ts (0)
 ❯ test/unit/services/locations.test.ts (0)
 ❯ test/unit/utils/filter-query.test.ts (0)
 ❯ test/unit/services/shipments.test.ts (0)
 ❯ test/unit/services/locations.test.ts (0)
 ❯ test/unit/utils/filter-query.test.ts (0)
 ❯ test/unit/services/shipments.test.ts (0)
 ❯ test/unit/services/locations.test.ts (0)
 ❯ test/unit/utils/filter-query.test.ts (0)
...

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 34 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/unit/utils/sort-query.test.ts [ test/unit/utils/sort-query.test.ts ]
 FAIL  test/unit/services/currency.test.ts [ test/unit/services/currency.test.ts ]
 FAIL  test/unit/services/shipments/find.test.ts [ test/unit/services/shipments/find.test.ts ]
 FAIL  test/unit/services/organizations/create.test.ts [ test/unit/services/organizations/create.test.ts ]
 FAIL  test/unit/utils/assert.test.ts [ test/unit/utils/assert.test.ts ]
 FAIL  test/unit/utils/order.test.ts [ test/unit/utils/order.test.ts ]
Error: Failed to load url ~test/unit/setup/matchers (resolved id: ~test/unit/setup/matchers). Does the file exist?
 ❯ loadAndTransform node_modules/vite/dist/node/chunks/dep-2285ba4f.js:40373:21

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/34]⎯

 Test Files  34 failed (34)
      Tests  no tests
   Start at  00:17:55
   Duration  13.83s (transform 237ms, setup 0ms, collect 0ms, tests 0ms)
```

Which is what leads me to think it's a weird windows resolve path situation.

This is both happening to me on my Windows machine and funnily enough also on my WSL machine, however on a regular Linux server the project tests 100% ok.
