### ISSUE TITLE
`advanceTimersByTime` is `undefined` in `userEvent.setup`

### ISSUE THREAD

**Issue by AldeonMoriak** [vitest-dev/vitest#2549]
### Describe the bug

I've been trying to use `@testing-library/user-event` and fake timers in a unit test but i get this error message:
```console
TypeError: Cannot read properties of undefined (reading 'advanceTimersByTime')
 ❯ Object.advanceTimersByTime [as advanceTimers] node_modules/vitest/dist/chunk-utils-import.afe2ffde.js:2780:18
```
I created a repo in stackblitz to show this problem and [here](https://stackblitz.com/edit/vitest-dev-vitest-vk61jj?file=src%2FApp.tsx,src%2FApp.test.tsx&initialPath=__vitest__) it is.

unit test:
```js
it.only('should increment count on click', async () => {
    vi.useFakeTimers();
    render(<App />);
    const user = userEvent.setup({ advanceTimers: vi.advanceTimersByTime });
    user.click(screen.getByRole('button'));
    expect(await screen.findByText(/count is: 1/i)).toBeInTheDocument();
  });
```

react component:
```js
import { useCounter } from './hooks/useCounter';
import './App.css';

function App() {
  const { count, increment } = useCounter();
  const add = () => {
    setTimeout(() => {
      increment();
    }, 4000);
  };

  return (
    <div className="App">
      <header className="App-header">
        <p>Hello Vite + React!</p>
        <p>
          <button type="button" onClick={add}>
            count is: {count}
          </button>
        </p>
        <p>
          Edit <code>App.tsx</code> and save to test HMR updates.
        </p>
        <p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
          {' | '}
          <a
            className="App-link"
            href="https://vitejs.dev/guide/features.html"
            target="_blank"
            rel="noopener noreferrer"
          >
            Vite Docs
          </a>
        </p>
      </header>
    </div>
  );
}

export default App;
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-vk61jj?file=src%2FApp.tsx,src%2FApp.test.tsx&initialPath=__vitest__

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (3) x64 Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
    Memory: 1.16 GB / 5.14 GB
  Binaries:
    Node: 14.19.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It uses `this` inside a method. When you pass down a function, it looses its binding. Use `vi.advanceTimersByTime.bind(vi)`
