### ISSUE TITLE
Add support project relative paths

### ISSUE THREAD

**Issue by polRk** [vitest-dev/vitest#2566]
### Clear and concise description of the problem

In monorepositories, tests are run inside packages, and vitest+junit takes a path relative to the launch location.

### Suggested solution

Аdd the ability to specify project root

### Alternative

Rewrite output xml after tests

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Can you elaborate? I have no idea what you want.

**Comment by polRk** [comment]
> Can you elaborate? I have no idea what you want.

My project structure

```
. root
|
. - apps
|  |
|  . - api
|
. - packages
|  | 
|  . - server

```

This is my test junit report in folder `packages/server`

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<testsuites name="vitest tests" tests="5" failures="0" errors="0" time="7.68">
    <testsuite name="src/server.test.ts" timestamp="2022-12-26T07:20:43.666Z" tests="5" failures="0" errors="0" skipped="0" time="0.014">
        <testcase classname="src/server.test.ts" name="Server &gt; should return response" time="0.009">
        </testcase>
        <testcase classname="src/server.test.ts" name="Server &gt; should return 404 if no corresponding route" time="0.002">
        </testcase>
        <testcase classname="src/server.test.ts" name="Server &gt; should log incoming request" time="0">
        </testcase>
        <testcase classname="src/server.test.ts" name="Server &gt; should pass logger bindings" time="0.001">
        </testcase>
        <testcase classname="src/server.test.ts" name="Server &gt; should log middleware start and finish" time="0.001">
        </testcase>
    </testsuite>
</testsuites>
```

testcase has the classname attribute with the relative package value `src/server.test.ts`.
But I want to have an option that records the classname with the relative value of the project `packages/server/server.test.ts`

**Comment by sheremet-va** [comment]
Can't you just use [`root` option](https://vitest.dev/config/#root) for this?

**Comment by polRk** [comment]
> Can't you just use [`root` option](https://vitest.dev/config/#root) for this?

No, for different project we use different configs.

**Comment by sheremet-va** [comment]
> > Can't you just use [`root` option](https://vitest.dev/config/#root) for this?
> 
> No, for different project we use different configs.

And why can't you use the same root in different configs?

**Comment by sheremet-va** [comment]
I think this is part of #256, so closing the issue in favour of it.
