### ISSUE TITLE
[0.26] Mocking default cyclic dependencies hangs

### ISSUE THREAD

**Issue by danez** [vitest-dev/vitest#2567]
### Describe the bug

Since version 0.26 mocking default exports of a cyclic dependency starts hanging the tests suite without any output (Github Actions times out after 6h, see [this PR](https://github.com/reactjs/react-docgen/pull/712))

I already [created a test for this](https://github.com/vitest-dev/vitest/commit/045eb57898084854a3902bae8da21d13f92001af) and tried to debug this, but wasn't successful by now. I can still look further into this, but probably not before january. So I thought I might report it already in case you have an idea about the problem.

I tried with #2560 but that did no change anything.

Happy holidays and thanks for this great tool. 🎉💜🌴

### Reproduction

Either:
https://github.com/vitest-dev/vitest/commit/045eb57898084854a3902bae8da21d13f92001af

Or:

https://github.com/danez-labs/vitest-default-commonjs

npm i 
npm test

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 4.34 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.asdf/installs/nodejs/lts/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Safari: 16.2
  npmPackages:
    vite: 4.0.3 => 4.0.3 
    vitest: 0.26.2 => 0.26.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Thank you for the bug report. Indeed, there was an issue after the rewrite, #2572 should fix this 👍🏻
