### ISSUE TITLE
vitest watch breaks solidjs example

### ISSUE THREAD

**Issue by Takeno** [vitest-dev/vitest#2581]
### Describe the bug

After the first test execution in watch mode, the second render returns wrong content and the test fails.

If you run `vitest run` without watch, everything works properly.

### Reproduction

1. Just copy the example on https://github.com/vitest-dev/vitest/tree/main/examples/solid or fork my repo https://github.com/Takeno/vitest-watch-solidjs-bug
2. `npm install`
3. `npm test` and it should work
4.  Save any file to trigger the watcher and see test failing

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 130.39 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - ~/.nvm/versions/node/v18.11.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.11.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.11.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0.1
    Safari: 16.0
  npmPackages:
    vite: latest => 4.0.3 
    vitest: latest => 0.26.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HeitorMC** [comment]
Hey @sheremet-va, can I work on this one? :smile:

**Comment by sheremet-va** [comment]
> Hey @sheremet-va, can I work on this one? 😄

Sure

**Comment by HeitorMC** [comment]
Hey @sheremet-va, can you help me out?

Here's the thing, I tracked down the bug with vs code debugging terminal, and I got stuck in this file `packages/vitest/src/runtime/worker.ts`.

Before the [run](https://github.com/vitest-dev/vitest/blob/4fc492c61d6e01bc34bc807a6b57197a1914f823/packages/vitest/src/runtime/worker.ts#L110) I forcefully removed the react module from module cache, like this:

```ts
export async function run(ctx: WorkerContext) {
  init(ctx)
  moduleCache.delete('/vitest/examples/solid/components/Hello.jsx')
  const { run } = await startViteNode(ctx)
  return run(ctx.files, ctx.config)
}
```

And solved the problem, which indicates it's related to the `moduleCache` instance. After this point, debugging process gets really hard. Could you help me out with this, or do you have any idea of what could it be?

Also I saw that @antfu wrote big pieces of code here. If he could help us, would be great :smile:!

**Comment by HeitorMC** [comment]
Hey @sheremet-va @antfu, any news? Can you guys help me out with this? :smile:

**Comment by sheremet-va** [comment]
It should be done automatically with invalidates

**Comment by sheremet-va** [comment]
Looks like it's working correctly in the latest version.
