### ISSUE TITLE
Code coverage is not working

### ISSUE THREAD

**Issue by wtchnm** [vitest-dev/vitest#259]
### Describe the bug

The following error is thrown when executing `vitest --coverage`:

`Error: Cannot find module '/home/wtchnm/Documents/Web/Vitamin/node_modules/.pnpm/vitest@0.0.105_1fa977ddae9488c8bb84401f982e9f7f/node_modules/dist/cli.js'`.

If we change from `../../dist/cli.js` to `../dist/cli.js` in the following snippet, it will find the module: https://github.com/vitest-dev/vitest/blob/c6e3ad7da2193322fcce0d03706f959592e921fb/packages/vitest/vitest.mjs#L15

But unfortunately the coverage report will be empty:

![image](https://user-images.githubusercontent.com/37726261/146980418-f032a7d9-262c-4f20-83eb-64182cc56534.png)

_Note: `c8 vitest run` will work just fine_.

### Reproduction

`pnpx -y degit wtchnm/Vitamin#feat/vitest vitest-coverage-bug && cd vitest-coverage-bug && pnpm i && pnpm test:ci`

### System Info

```shell
System:
    OS: Linux 5.15 undefined
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 3.23 GB / 15.60 GB
    Container: Yes
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 16.13.1 - /usr/bin/node
    Yarn: 1.22.15 - ~/.npm-global/bin/yarn
    npm: 8.3.0 - /usr/bin/npm
  Browsers:
    Brave Browser: 96.1.33.106
    Firefox: 95.0.2
  npmPackages:
    @vitejs/plugin-react: 1.1.3 => 1.1.3 
    vite: 2.7.4 => 2.7.4 
    vitest: 0.0.105 => 0.0.105
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Thanks, fixed!

**Comment by wtchnm** [comment]
Thanks!
