### ISSUE TITLE
Unexpected breaking change in v0.24.0

### ISSUE THREAD

**Issue by Exelord** [vitest-dev/vitest#2593]
### Describe the bug

While updating from 0.23.4 to 0.24.0 (and 0.26.3) I have experienced all my tests failing with the same cause. I have went through the changes, but couldn't notice anything that could cause them to break.

My tests are using Solid.js and it looks like not all effects are executed or awaited. Mocking the timers does not help.

### Reproduction

https://github.com/Exelord/solid-proxies/pull/115

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 36.93 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.2
  npmPackages:
    vite: ^4.0.3 => 4.0.3
    vitest: ^0.23.0 => 0.23.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
To be honest, I am not sure why it worked before 🤔 solid always had a problem, because it resolves to two different solid instances. Adding this to you config helps:

```ts
  resolve: {
    conditions: ["browser"],
  },
```

**Comment by Exelord** [comment]
Thank you @sheremet-va, that seams to work!

Would you mind sharing how can I check the resolutions? Also I knew there was a way to dump vitest build, however I coudn't find it in docs. That would be really helpful. I would like to understand the real cause behind it.

You are also right about the `solid-js/server`. Im curious why it was before resolved to to `dev` 🤔
