### ISSUE TITLE
TypeError: 'ownKeys' on proxy: trap returned extra keys but proxy target is non-extensible

### ISSUE THREAD

**Issue by purepear** [vitest-dev/vitest#2596]
### Describe the bug

Happy New Year! 🥳 

I was updating from `0.25.8` to `0.26.3` and some tests started failing with error:
```
TypeError: 'ownKeys' on proxy: trap returned extra keys but proxy target is non-extensible
```

### Reproduction

I managed to create a simplified repro which demonstrates the issue when run **locally** but fails to repro the issue in stackbliz 🤔 
The problem in `0.26.3` occurs when `deps.interopDefault` is `true` (which is the case when `environment` is `jsdom`).

```js
import { test, expect, vi} from 'vitest'
import kebabCase from 'lodash/kebabCase';

vi.mock('lodash/kebabCase');
kebabCase.mockImplementation(str => `mocked-${str}`);

test('example', async () => {
  expect(kebabCase('test')).toBe('mocked-test')
});
```

Note that this is just for repro purposes and affects not just `lodash` but other packages like `algoliasearch` too(probably all CJS deps that are mocked this way).

The repro works fine in `0.25.8`.
The repro works fine if `deps.interopDefault` is `false`.
The repro works fine if I change the mock to:
```js
vi.mock('lodash/kebabCase', () => ({
  default: str => `mocked-${str}`
}))
```

Here's a [link to stackblitz](https://stackblitz.com/edit/vitest-interopdefault-issues-with-mocks?file=example.test.js), please "Download project" locally to test because for some reason the repro doesn't work in stackblitz.

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 526.02 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.volta/tools/image/node/16.19.0/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 8.19.3 - ~/.volta/tools/image/node/16.19.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
    Safari: 16.2
  npmPackages:
    vitest: ^0.26.3 => 0.26.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by datner** [comment]
@sheremet-va 
PR merged, issue closed as completed, but no patch version published.
is there an ETA? 😅

**Comment by yakobe** [comment]
hi @sheremet-va 
Is it possible to get a new release for this? Many thanks for the fix.

**Comment by sheremet-va** [comment]
Vitest 0.27.0 has needed fix.

**Comment by twoBoots** [comment]
I'm still seeing the issue in `v0.27.0` with `sweetalert2`

```
import Swal from 'sweetalert2';
vi.mock('sweetalert2');
```

```
TypeError: 'ownKeys' on proxy: trap returned extra keys but proxy target is non-extensible
```
Let me know if you would prefer me to open this as a new issue.

**Comment by rn4n** [comment]
Any idea which release this fix will be in?

**Comment by purepear** [comment]
Thank you @sheremet-va 🙇
