### ISSUE TITLE
toHaveBeenCalledOnce expects a spy to be called multiple times

### ISSUE THREAD

**Issue by JessicaSachs** [vitest-dev/vitest#260]
### Describe the bug

When I was cutting over jest tests in vueuse to vitest, the assertions on spies for the `useSwipe` composable had issues with the number of calls.

In particular,

```ts
expect(onSwipe).toHaveBeenCalledOnce()
```

was expecting the `onSwipe` spy to have been called twice.

<img width="672" alt="Screen Shot 2021-12-21 at 3 28 53 PM" src="https://user-images.githubusercontent.com/2801156/147000108-3dfd11bb-0d58-4605-9a3c-a08071c4f7e6.png">

### Reproduction

I wasn't able to create a minimum reproducible issue -- the issue has something to do with how the spies are invoked. When the spies are immediately invoked, there is no bug, however within the `useSwipe` example in vueuse, this issue shows up.

When I simply invoke the spies directly _within the `useSwipe` (subject under test)_  method, the calls counter works correctly. Given that, I'm betting the issues have something to do with how `addEventListener` is invoking the spy.

[Here's the PR/branch with a reproduction](https://github.com/JessicaSachs/vueuse/commit/eb4a24586a6ff2581d2a67077179ef8d804df6ba).

1. Check out this repo
2. Run `pnpm install`
3. Run `pnpm vitest --config vitest.config.ts useSwipe`

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 184.71 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome Canary: 99.0.4779.0
    Firefox: 95.0
    Safari: 14.1.1
  npmPackages:
    vite: ^2.7.3 => 2.6.7 
    vitest: ^0.0.105 => 0.0.105
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by patak-dev** [comment]
Apart from this bug, isn't the reported diff inverted? Should it be -1 +2?
```
- expected   1
+ actual     2
```

**Comment by JessicaSachs** [comment]
Right, that's the bug. It's actually trying to expect that there's 2 calls. Whenever you do another call, it increases, so if you copy paste those tests N times, the `expected` value will be N, not 1.

I don't think it's an issue with the test reporter, because the `spy.mock.calls` has the correct length, and because changing the invocation to `spy()` instead of however the `useSwipe` function invokes it causes everything to work correctly.

**Comment by patak-dev** [comment]
It is strange, the assertion is harcoded to expect 1. There is nothing dynamic that would change the expected value here: https://github.com/vitest-dev/vitest/blob/5fa4138415d251d4037b0c32eb1c89ff74acbd41/packages/vitest/src/integrations/chai/jest-expect.ts#L186

**Comment by Smrtnyk** [comment]
> toHaveBeenCalledOnce

well the matcher is called `toHaveBeenCalledOnce` so I guess 1 makes sense, no? 
or maybe I misunderstood what you wanted to say

**Comment by Smrtnyk** [comment]
I tried forking the vue use repo and checking out the branch with repro, to debug using breakpoints, but having a hard time to setup the env.
Cloned and did pnpm install but whichever test script I run it throws errors around

**Comment by JessicaSachs** [comment]
I'm on Discord if you want to discuss. I really tried to get a more minimal reproduction, but it was very hard. @patak-dev was able to reproduce using the example I have, so I'm confident that it's a real issue.

**Comment by Smrtnyk** [comment]
nah it's just me not used to monorepos and pnpm, 
My daily work took a tall at me not being in sync with all new stuff :D
I am sure the issue is real, that is why I wanted to debug it using  old good debugger and walking the callstack.

**Comment by Smrtnyk** [comment]
ok to sum it up
it was an issue with jsdom
test 1 added some event listeners which test 2 invoked, and both tests reused the same event listener
making test do the proper teardown was the way to go
```
it('test 1', (done) => {
    const setup = useSetup(() => {
      useSwipe(target, { threshold, onSwipe, onSwipeEnd })

      mockTouchEvents(target, [[0, 0], [threshold / 2, 0], [threshold, 0], [threshold, 0]])

      expect(onSwipe).toHaveBeenCalledOnce()
      expect(onSwipeEnd).toHaveBeenCalledOnce()
      done()
    })
    setup.unmount()
  })
```

**Comment by JessicaSachs** [comment]
Yeah, I'll close this issue, but I'm concerned with why this teardown is necessary in vitest and not in Jest, so I'll continue exploring that. In the meantime, the manual teardown of the component wrapper causes `useSwipe` to remove its event listeners correctly 👍🏻

**Comment by sheremet-va** [comment]
its possible you have “clearMocks” setting enabled in jest
if so, you can enable it in vitest
this setting is not documented yet xml

**Comment by sheremet-va** [comment]
Oh, I see, you reset them manually. Maybe there is a bug with that

**Comment by Smrtnyk** [comment]
> Oh, I see, you reset them manually. Maybe there is a bug with that

It s not a bug in clearing them, they were cleared properly in `beforeEach`.
The issue was that the test 2 really called event listener twice, and number of calls was correctly 2 instead of expected 1.
Have a look what test 1 and test 2 actually do, they add same event listener onto the same target, and event listener gets called twice in the end in second test.

**Comment by patak-dev** [comment]
Would you open a new issue about the inverted ecpected/actual output?

**Comment by patak-dev** [comment]
The order issue has been fixed in https://github.com/vitest-dev/vitest/pull/265
