### ISSUE TITLE
Severe performance regression when reporter with terminal output is enabled

### ISSUE THREAD

**Issue by adam-te** [vitest-dev/vitest#2602]
### Describe the bug

Problem:
Full test suite performance is 10x slower when enabling a reporter with terminal output (e.g. `default`, `verbose`, `dot`).

Details:
In converting our unit tests (~8000) from karma to vitest I noticed performance of vitest was significantly worse than karma. After a lot of debugging, I came to find that the `wrapAnsi(` function call, used in the vitest `log-update` dependency, was the culprit. This call alone takes ~95% of test execution time.

https://github.com/sindresorhus/log-update/blob/main/index.js#L54

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/47219987/210303708-ac07250b-7d01-4942-80cd-06e51655a70b.png">

Workaround:
Tests run 10-20x faster if the wrapAnsi line in the `vitest/dist/chunk-snapshot-manager.js` file is commented out. Console output continues to look normal and functional with ansi wrapping disabled

Vitest entrypoint into `log-update` dependency:
https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/node/logger.ts#L13

<img width="672" alt="image" src="https://user-images.githubusercontent.com/47219987/210303965-b378bcd4-6687-4471-bfed-17763995c541.png">

Thoughts:
Its bizarre that terminal output logic is reducing test performance by an order of magnitude. Ideally the performance would be optimized here, but perhaps terminal logic can be moved to a worker/sub-process?

### Reproduction
TODO: Will add soon. Should be able to reproduce on any large test suite via enabling/disabling `default` or `dot` reporter though.

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 72.25 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Brave Browser: 108.1.46.140
    Chrome: 108.0.5359.124
    Firefox: 102.3.0
    Safari: 16.1
  npmPackages:
    vite: ^4.0.0 => 4.0.0 
    vitest: ^0.26.3 => 0.26.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by adam-arthur** [comment]
Reproduction:
https://github.com/adam-arthur/vitest-perf-regression

I'm able to reproduce this on a different computer with a barebones project setup. Enabling console reporters seems to introduce some sort of O(n^2) or worse performance profile correlated with the number of tests.

Will edit the initial issue on my other account (adam-te) later today.

**Comment by adam-arthur** [comment]
Looked into this a bit more.

- All console renderers are affected
- DotRenderer updates on a 200ms setInterval ([link](https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/node/reporters/renderers/dotRenderer.ts#L45)) 
- DotRenderer will always iterate over all test cases for each render tick. So moreTests = moreRenderTime
- The more tests you have, the longer the console render takes, which triggers something of a "doom loop" where the test runtime becomes dominated by the console render time. e.g. if console render takes 190ms, there are only 10ms remaining for tests to run before the console re-renders.
- The [chalk/wrap-ansi](https://github.com/chalk/wrap-ansi/blob/main/index.js#L212) code appears to be extremely performance intensive, doing a lot of transforms and iterations in JS

My take:
- Ideally a different and more performant off the shelf rendering library or approach could be swapped in
- Alternatively, console positioning logic should be done in a worker or separate execution context to avoid affecting the test execution thread. This is probably the most obvious and easiest thing to do.
- Renderer setInterval invocation should be delayed by the render time, e.g. variable rendering when rendering is sufficiently slow
- Browsing the `wrap-ansi` code, looks like there's a lot of low hanging fruit for optimization. The code does not appear to be written with a performance sensitive style. Is app level column wrapping even needed? Don't most terminals do this for you anyway?

**Comment by sheremet-va** [comment]
> Alternatively, console positioning logic should be done in a worker or separate execution context to avoid affecting the test execution thread. This is probably the most obvious thing to do

Reporters are running in the main thread, while tests are running in separate workers.

**Comment by adam-arthur** [comment]
> > Alternatively, console positioning logic should be done in a worker or separate execution context to avoid affecting the test execution thread. This is probably the most obvious thing to do
> 
> Reporters are running in the main thread, while tests are running in separate workers.

Well that's odd, because the tests do not appear to continue to run unimpeded when console output is sufficiently slow.

You can replicate it easily with my repo above (at least on macOS with default shell)

Any comment or opinion on the issue generally?

**Comment by sheremet-va** [comment]
> Any comment or opinion on the issue generally?

Does test execution _actually_ slows down, or does reporters shows them like they are slowed down? It's possible RPC is awaited somewhere, when console log is happening, so tests are slowed down, but I'm not sure if this is actually the problem.

**Comment by adam-arthur** [comment]
Well you can clone my repo above and replicate it immediately.

Test execution slows down, yes, and pretty much completely broken performance wise after 5000 tests or so. This is not a minor performance issue

**Comment by sheremet-va** [comment]
> with these reporters.

With your reproduction I don't see significant performance regression in `verbose` and `default` reporter, only `dot` is unbearably slow. Can you confirm this?

**Comment by adam-te** [comment]
It affects all of the reporters that act to clear the terminal/contain layout logic. I'll get numbers for it later, but surprised you didn't observe this

**Comment by adam-arthur** [comment]
Pushed an update to: [](https://github.com/adam-arthur/vitest-perf-regression)

You can now observe that verbose reporter slows down significantly too. The exact slowness of the chosen reporter depends on the structure of the log messages, as slowness is related to layout logic that inspects terminal lines as strings.

So just tweaked the expects to trigger slowness in verbose as well. The other reporters seem fine, though I recall even vitest UI being slow on my work testcases... may have been running it along with a slower console reporter though

**Comment by AriPerkkio** [comment]
In addition to chalk/wrap-ansi#51 some optimization on Vitest side is needed. When there are lots of test cases the `renderTree` will become slow:

https://github.com/vitest-dev/vitest/blob/1fe8286c790cef9063b1f5f8147f6d41fc14bf79/packages/vitest/src/node/reporters/renderers/listRenderer.ts#L163-L165

The `renderTree` is called constantly for task updates and each call can take most of the process execution time:

<details>
  <summary>Video of slow renderTree calls</summary>

https://user-images.githubusercontent.com/14806298/224548243-87e3d646-e917-4294-8a77-5957f3287ca0.mov

</details>

By limiting the `renderTree` to process only the tasks that can fit the current screen the run will execute quickly:

```diff
- renderTree(tasks, options)
+ const rows = process.stdout.rows || 80
+ renderTree(tasks.slice(tasks.length - rows), options)
```

<details>
  <summary>Video of fast reduced renderTree calls</summary>


https://user-images.githubusercontent.com/14806298/224548350-4837dad7-1763-406a-88be-113a8fc08320.mov



</details>


But if we still need to print all tasks to terminal on each `log`, we can limit the amount of work done by `renderTree` by figuring out what tasks have changed. Maybe some kind of `lastChanged: number` property on each task which can be used when deciding whether a cached text for given task could be printed instead of processing it in `renderTree` again? That would prevent duplicate work.

Also maybe the `update()` should not be called here and instead let the `setInterval` call it on every 200ms?

https://github.com/vitest-dev/vitest/blob/1fe8286c790cef9063b1f5f8147f6d41fc14bf79/packages/vitest/src/node/reporters/renderers/listRenderer.ts#L174-L178

<details>
  <summary>Changes for showing the execution time of renderTree in listRenderer.ts</summary>

```ts
export const createListRenderer = (_tasks: Task[], options: ListRendererOptions) => {
  let tasks = _tasks
  let timer: any

  const log = options.logger.logUpdate
  let timeSpentOnUpdate = 0n
  let lastLog = 0n
  let lastRenderTree = 0n

  function update() {
    const rows = process.stdout.rows || 80
    const start = process.hrtime.bigint()

    const tree = renderTree(
      // tasks,
      tasks.slice(tasks.length - rows),
      options,
    )
    lastRenderTree = (process.hrtime.bigint() - start) / 1_000_000n

    log(
      tree,
      '\nTotal time spent on update() calls:', timeSpentOnUpdate.toString(),
      'ms\nLast update() took:', lastLog.toString(),
      'ms\nLast renderTree() took:', lastRenderTree.toString(),
      'ms\nCount of tasks:', tasks.length.toString(),
    )

    lastLog = (process.hrtime.bigint() - start) / 1_000_000n
    timeSpentOnUpdate += lastLog
  }

  return {
```

</details>

**Comment by sheremet-va** [comment]
> By limiting the `renderTree` to process only the tasks that can fit the current screen the run will execute quickly:

Not sure if this is the right solution, but the idea is nice. I don't think we can slice it before passing it down, because it's possible to have more than 1 line for a task. But maybe an early return from a `for` would be enough, when we reach the limit?

**Comment by AriPerkkio** [comment]
> because it's possible to have more than 1 line for a task. But maybe an early return from a `for` would be enough, when we reach the limit?

Using early `break` from the `for` loop looks like more appropriate solution here. After quick testing it seems to preserve output correctly and executes test run quickly - in 6.5 seconds which seems nice compared to the 70 second reference used in https://github.com/vitest-dev/vitest/issues/579#issuecomment-1462503600. 

I'll do some more manual testing and see if the `renderTree` itself could be optimized as well. With 5000 test cases the final test result printing in `stop()` still takes ~1200ms as there we will want all results to be printed no matter what `process.stdout.rows` is.
