### ISSUE TITLE
No Test Suite Found Bug still present

### ISSUE THREAD

**Issue by Kurohyou** [vitest-dev/vitest#2604]
### Describe the bug

#847 is closed, but the issue (or something similar) appears to still be present in Vitest 0.26.3. Have one directory in a repo where tests run fine. Have another directory where even basic pseudo tests won't run:

```
import { describe, expect, it } from 'vitest';

describe('A nascent test',()=>{
  it('Really basic test',()=>{
    expect(true).toBe(true);
  })
});
```
The error I get is:
`Error: No test suite found in file E:/Git/Kurohyou_studios/Roll20-Snippets/test_sheet/source/assets/js/__tests__/gen.test.js`

The actual test I'm trying to run here was working a week ago, so not sure what has changed.

### Reproduction

Repro info above.

### System Info

```shell
Vitest 0.26.3
Windows 10.0.19045 Build 19045
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Please, provide minimal runnable reproduction. I need file structure, installed dependencies, package manager and so on. You code runs fine in example repo.
