### ISSUE TITLE
Import of ES6 dependencies is undefined with 0.26.x

### ISSUE THREAD

**Issue by c100k** [vitest-dev/vitest#2608]
### Describe the bug

With the upgrade to `0.26.x`, tests on classes and functions importing some libraries (i.e. https://github.com/auth0/node-jsonwebtoken) are broken for no apparent reason.

- With `0.25.8` the test passes ✅
- With `0.26.3` the test fails ❌

### Reproduction

https://github.com/c100k/vitest-0.26.x-breaking-changes

### System Info

```shell
N/A
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Did you try enabling `deps.interopDefault`?

**Comment by c100k** [comment]
@sheremet-va Wow good catch ! Indeed, everything passes when this option is enabled. I should have been more careful on the [changelog](https://github.com/vitest-dev/vitest/releases/tag/v0.26.0) of `0.26.0`.
