### ISSUE TITLE
ReferenceError: React is not defined

### ISSUE THREAD

**Issue by fadi-george** [vitest-dev/vitest#261]
### Describe the bug

A React component that uses default React element leads to an error.

### Reproduction

https://stackblitz.com/edit/node-4bms3n?file=test%2Frender.spec.tsx

Here's a basic example:

```
import SomeElement from './someElement';

const SomeComponent = ({ view = <SomeElement /> }) => {
  if (...) return view;
  ...
}
```

leads to ReferenceError: React is not defined.

Also, I noticed that if use material ui Avatar, I get this error:
ReferenceError: Image is not defined

### System Info

```shell
npx envinfo --system --npmPackages '{vitest,vite,@vitejs/*}' --binaries --browsers



  System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 113.84 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Brave Browser: 96.1.33.106
    Chrome: 96.0.4664.110
    Safari: 15.2
  npmPackages:
    @vitejs/plugin-react-refresh: ^1.3.6 => 1.3.6 
    vite: 2.7.5 => 2.7.5 
    vitest: 0.0.107 => 0.0.107
```

### Used Package Manager

npm

### Logs

```shell
For default element value:

ReferenceError: React is not defined

For mui avatar:

ReferenceError: Image is not defined
 ❯ node_modules/@mui/material/Avatar/Avatar.js:100:19
     98|     setLoaded(false);
     99|     let active = true;
    100|     const image = new Image();
       |                   ^
    101| 
    102|     image.onload = () => {
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Can you send your failing case to https://github.com/antfu-sponsors/vitest/blob/15d26b9c8525faadb64eea5e63a42cdb4ca4aebc/test/react so we can have a better look and prevent future regression? Thanks

**Comment by fadi-george** [comment]
It would be something like this but I TypeError: Cannot read properties of undefined (reading 'userAgent'). 

https://stackblitz.com/edit/node-4bms3n?file=test%2Frender.spec.tsx

**Comment by fadi-george** [comment]
Current errors w/ 0.0.139 and '@vitejs/plugin-react':

Default value of `= <div >` seems fine.

But fragments (`= <>...</>`) leads to `Error: Uncaught [ReferenceError: _Fragment is not defined]`

And other components (`= <Spinner />`) leads to `Error: Uncaught [ReferenceError: Spinner is not defined]`

**Comment by antfu** [comment]
It seems like a bug of Vite, we will figure out the fix for upstream.

**Comment by antfu** [comment]
Vite v2.7.11 released
