### ISSUE TITLE
CLI doesn't work

### ISSUE THREAD

**Issue by 1alexvash** [vitest-dev/vitest#2611]
### Describe the bug

App doesn't work

### Reproduction

![image](https://user-images.githubusercontent.com/46556479/210597966-8f6f2c7b-a552-4f42-ab5a-0a061e87f40b.png)

### System Info

```shell
npx vite-node index.ts
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Please, add an actual reproduction. I cannot run command on empty folder.

**Comment by 1alexvash** [comment]
@sheremet-va
npx is supposed to run on the empty folders, right?
![animation](https://user-images.githubusercontent.com/46556479/210601857-9e0be1a4-f60a-4c7b-ad89-e554f37f5563.gif)

**Comment by 1alexvash** [comment]
This one is related to this package:
https://github.com/vitest-dev/vitest/tree/main/packages/vite-node#readme
