### ISSUE TITLE
Vitest throws a reference error when objects are destructured in import statement.

### ISSUE THREAD

**Issue by Minterl** [vitest-dev/vitest#2613]
### Describe the bug

When objects are destructured in an import statement (for some libraries and not others) names are not resolved properly. However, when they are destructered outside of the import statement (as shown in the StackBlitz reproduction), it works correctly.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-y7grzc?file=crypto.ts,test%2Fsuite.test.ts,test%2Fbasic.test.ts&initialPath=__vitest__

### System Info

```shell
System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 11.15 GB / 12.36 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /mnt/c/Users/username/AppData/Roaming/npm/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  npmPackages:
    @vitejs/plugin-react: ^3.0.0 => 3.0.0
    vitest: ^0.26.3 => 0.26.3


NOTE: it may be relevant to note that I am using WSL 2.0 to run Linux.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is not "destructuring", this is "named" exports. Please, read: https://vitest.dev/config/#deps-interopdefault

This is intended change.
