### ISSUE TITLE
ui bug

### ISSUE THREAD

**Issue by hzhoup** [vitest-dev/vitest#2616]
### Describe the bug

run `vitest --ui --api 9528`

can't run default api, must custom `--api`.

the page is empty, and console
![image](https://user-images.githubusercontent.com/109516832/210911195-5317c89f-5f3a-465f-9085-a472e7243764.png)

The source code of the page is the index.html file of the app, where the problem may lie

### Reproduction

```ts
test: {
      globals: true,
      environment: 'jsdom',
      includeSource: ['src/**/*.{js,ts}'],
      transformMode: {
        web: [/.[tj]sx$/]
      },
      coverage: {
        provider: 'c8'
      }
    }
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 3.06 GB / 15.89 GB
  Binaries:
    Node: 16.15.0 - E:\nodejs\node.EXE
    Yarn: 1.22.18 - E:\nodejs\node_global\yarn.CMD
    npm: 9.2.0 - E:\nodejs\npm.CMD
  Browsers:
    Chrome: bookmarks.html
initial_preferences
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-legacy: ^3.0.1 => 3.0.1
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0
    @vitejs/plugin-vue-jsx: ^3.0.0 => 3.0.0
    vite: ^4.0.0 => 4.0.4
    vite-plugin-compression: ^0.5.1 => 0.5.1
    vite-plugin-html: ^3.2.0 => 3.2.0
    vitest: ^0.26.3 => 0.26.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hzhoup** [comment]
sorry, the Package Manager is the pnpm

**Comment by hzhoup** [comment]
the repo https://github.com/hzhoup/gadmin-vue/commit/5297b38d14f7c5639d90647aceb1474c38f43f64

**Comment by factiondavid** [comment]
I'm getting this as well. Empty window opens when running test using happy-dom.

**Comment by sheremet-va** [comment]
This was fixed.
