### ISSUE TITLE
Doc example for how to mock `IntersectionObserver` doesn't pass `instanceof` check

### ISSUE THREAD

**Issue by janosh** [vitest-dev/vitest#2621]
### Describe the bug

Could I'm doing something wrong here but seems like [doc example](https://vitest.dev/guide/mocking.html#globals) for how to mock `IntersectionObserver` doesn't pass `instanceof` check.

### Reproduction

```ts
// from the docs
import { expect, test, vi } from 'vitest'

const MockIntersectionObserver = vi.fn(() => ({
  disconnect: vi.fn(),
  observe: vi.fn(),
  takeRecords: vi.fn(),
  unobserve: vi.fn(),
}))
vi.stubGlobal(`IntersectionObserver`, MockIntersectionObserver)

test(`IntersectionObserver`, () => {
  expect(new IntersectionObserver((entries) => entries)).toBeInstanceOf(
    IntersectionObserver
  )
})
```

> AssertionError: expected { disconnect: [Function spy], …(3) } to be an instance of spy

This `class`-based mock passes the same test:

```ts
import { expect, test, vi } from 'vitest'

class MockIntersectionObserver implements IntersectionObserver {
  root: Document | Element | null = null
  rootMargin: string = ``
  thresholds: readonly number[] = []

  disconnect = vi.fn()
  observe = vi.fn()
  takeRecords = vi.fn()
  unobserve = vi.fn()
}
window.IntersectionObserver = MockIntersectionObserver

test(`IntersectionObserver`, () => {
  expect(new IntersectionObserver((entries) => entries)).toBeInstanceOf(
    IntersectionObserver
  )
})
```

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 49.97 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /opt/homebrew/bin/node
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 108.1.46.153
    Chrome: 108.0.5359.124
    Safari: 16.2
  npmPackages:
    vite: ^4.0.4 => 4.0.4 
    vitest: ^0.26.3 => 0.26.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
In the first example what you are doing is this, which is expected JS behaviour:

```ts
function Spy() { return { disconnect: null } }
const t = new Spy()
t instanceof Spy
// false
```

If you want your instanceof check to pass, you would mock it like this:

```ts
function Spy() {}
Spy.prototype.disconnect = function () {}
const p = new Spy()
p instanceof Spy
// true
```

**Comment by janosh** [comment]
@sheremet-va Thank you very much for the explanation! 👍
