### ISSUE TITLE
/// <reference types="vitest" /> Doesn't work when upgrading to v0.26.3.

### ISSUE THREAD

**Issue by michealroberts** [vitest-dev/vitest#2622]
### Describe the bug

When upgrading to version v0.26.3, my vite.config.ts files are showing type errors:

<img width="519" alt="Screenshot 2023-01-08 at 15 41 44" src="https://user-images.githubusercontent.com/84131395/211205648-f7ee7d16-f4ab-4b61-97c0-f254f6cf9f59.png">

### Reproduction

Can share access to the repo when / if required.

### System Info

```shell
System:
    OS: macOS 12.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 132.13 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 98.0.2
    Firefox Developer Edition: 99.0
    Safari: 15.4
  npmPackages:
    vitest: 0.26.3 => 0.26.3 
```
```


### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Upgrade your Vite package so versions match with Vitest.

**Comment by kitsunekyo** [comment]
for anyone landing here too:

i'm on `"vite": "^4.1.1"` and `"vitest": "^0.28.3"` and my vite config is still broken just like in OPs case.

my lock file says i have `version "4.0.4"` and `version 4.1.1` of vite installed.

`yarn why vite` gives me this:

```
[1/4] Why do we have the module "vite"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "vite@4.1.1"
info Has been hoisted to "vite"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "3.16MB"
info Disk size with unique dependencies: "6.7MB"
info Disk size with transitive dependencies: "7.19MB"
info Number of shared dependencies: 12
=> Found "vitest#vite@4.0.4"
info This module exists because "vitest" depends on it.
info Disk size without dependencies: "3.15MB"
info Disk size with unique dependencies: "6.68MB"
info Disk size with transitive dependencies: "7.17MB"
info Number of shared dependencies: 12
=> Found "vite-node#vite@4.0.4"
info This module exists because "vitest#vite-node" depends on it.
info Disk size without dependencies: "3.15MB"
info Disk size with unique dependencies: "6.68MB"
info Disk size with transitive dependencies: "7.17MB"
info Number of shared dependencies: 12
```

output of `yarn why vitest`:

```
[1/4] Why do we have the module "vitest"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "vitest@0.28.3"
info Has been hoisted to "vitest"
info Reasons this module exists
   - Specified in "dependencies"
   - Hoisted from "@vitest#coverage-istanbul#vitest"
info Disk size without dependencies: "6.98MB"
info Disk size with unique dependencies: "22.93MB"
info Disk size with transitive dependencies: "29.98MB"
info Number of shared dependencies: 53
```

why is vitests dev dependency specified with `^3` but the pnpm override at `^4`?

do the vitest and vite versions again not match? should I create a new issue?

**Comment by sheremet-va** [comment]
> why is vitests dev dependency specified with ^3 but the pnpm override at ^4?

This doesn't matter to the end user.

> do the vitest and vite versions again not match? should I create a new issue?

They do match. Vitest specifies Vite version as "^3.0.0 || ^4.0.0". Yarn sees that you previously had 4.0.4 and doesn't update it when you install Vite 4.1.1, since it matches the version.

**Comment by kitsunekyo** [comment]
thats what i initially assumed, 
but why does typescript then not accept the `test` block in my `vite.config.js`? its identical to the docs: https://vitest.dev/config/

**Comment by sheremet-va** [comment]
> it says Object literal may only specify known properties, and 'test' does not exist in type 'UserConfigExport' so for some reason the tripple slash does not do anything at all.

Because you have two separate versions installed. Vitest depends on the 4.0.4 one and your tsconfig uses 4.1.1, because it's in your dependencies. 

This is how yarn resolved this, I am not sure what Vitest can do to tell the package manager to use your installed version. Specify as "peerDependency"? Most package managers won't install it then, but it's required for projects not using Vite, for example, so 🤷🏻

**Comment by kitsunekyo** [comment]
but that means that vitest@0.28.3 does not work with vite@4.1.0, as it needs vite@4.0.4, right? what i mean is that if the highest version of vite vitest currently works with is @4.0.4, it should be stated somewhere.

edit: i just checked and 4.1.0 and 4.1.1 released today / in the last 3 hours. so it's just bad timing.

**Comment by sheremet-va** [comment]
> but that means that vitest@0.28.3 does not work with vite@4.1.0, as it needs vite@4.0.4, right?

Why do you think that? The current version covers 4.1.1: https://semver.npmjs.com

<img width="347" alt="Screenshot 2023-02-02 at 18 19 50" src="https://user-images.githubusercontent.com/16173870/216396183-93859cb3-dadb-4f63-8b1d-592096b4199f.png">

**Comment by kitsunekyo** [comment]
i did not fully understand your last reply, as it seemed to me that according to my lock file the dependencies should be exactly as they should be. when i had vitest@0.28.3 and vite@4.1.0 installed, i received the mentioned type error on my vite.config. this led to my conclusion that these two package version apparently dont work together.

especially because `yarn why` printed that my installed vite version depended on vite@4.0.4.
```
=> Found "vitest#vite@4.0.4"
info This module exists because "vitest" depends on it.
```

i've now upgraded to vitest@0.28.4 and vite@4.1.1 and somehow yarn has now resolved the dependencies correctly, and removed the dependency to vite@4.0.4. the type error is now gone. but even then I dont understand why I received a type error in the first place. because if I understand your statement correctly, vitest@0.28.4 should work with any vite version in the range  "^3.0.0 || ^4.0.0".

but I've already taken up much of your time, and my issue is resolved. thank you.

**Comment by mcmillion** [comment]
Sorry to bump this, but after upgrading from `vite@4.0.4` / `vitest@0.28.3` to `vite@4.1.1` / `vitest@0.28.4` I'm now getting this error as well. I bumped both of these at the same time.

```
=> Found "vite@4.1.1"
info Has been hoisted to "vite"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "3.16MB"
info Disk size with unique dependencies: "6.59MB"
info Disk size with transitive dependencies: "7.12MB"
info Number of shared dependencies: 10
=> Found "vitest#vite@4.0.4"
info This module exists because "vitest" depends on it.
info Disk size without dependencies: "3.14MB"
info Disk size with unique dependencies: "6.58MB"
info Disk size with transitive dependencies: "7.1MB"
info Number of shared dependencies: 10
=> Found "vite-node#vite@4.0.4"
info This module exists because "vitest#vite-node" depends on it.
info Disk size without dependencies: "3.14MB"
info Disk size with unique dependencies: "6.58MB"
info Disk size with transitive dependencies: "7.1MB"
info Number of shared dependencies: 10
```

**Comment by michealroberts** [comment]
Something feels like this is a VSCode or Typescript engine issue. I see similar issues with Vite and import.meta.env ...
