### ISSUE TITLE
Regression with coverage-c8 in 0.27

### ISSUE THREAD

**Issue by steveoh** [vitest-dev/vitest#2627]
### Describe the bug

with `vitest --silent --coverage --ui --open` I get the following error after the tests complete

```bash
 % Coverage report from c8

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: Cannot read properties of null (reading 'length')
 ❯ node_modules/@vitest/coverage-c8/dist/provider-a555e3a3.js:239:142
 ❯ C8CoverageProvider.reportCoverage node_modules/@vitest/coverage-c8/dist/provider-a555e3a3.js:234:8
 ❯ Vitest.start node_modules/vitest/dist/chunk-snapshot-manager.700322bf.js:10541:35
 ❯ startVitest node_modules/vitest/dist/chunk-snapshot-manager.700322bf.js:11436:5
 ❯ start node_modules/vitest/dist/cli.js:100:17
```

### Reproduction

I upgraded from 0.26.3 to 0.27.0 and got this error in ci

### System Info

```shell
System:
    OS: macOS 11.6.8
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 479.91 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/Library/Caches/fnm_multishells/1232_1673282024346/bin/node
    npm: 9.2.0 - ~/Library/Caches/fnm_multishells/1232_1673282024346/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 105.0.3
    Safari: 15.6.1
  npmPackages:
    @vitejs/plugin-react-swc: ^3.0.1 => 3.0.1 
    vite: ^4.0.4 => 4.0.4 
    vitest: ^0.27.0 => 0.27.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Sounds like a source map has a different structure than the Typescript typings claim it to have. There are some quite strict checks in place here, but still something fails. I guess `sourcesContent` contains a `null` instead of `string` here? 

https://github.com/vitest-dev/vitest/blob/532cc11b0c6f482dfde927c0ea25d62b0cb36706/packages/coverage-c8/src/provider.ts#L85-L90

@steveoh do you have a minimal reproduction case for this so that I could debug it further?

**Comment by cope** [comment]
same here

**Comment by steveoh** [comment]
@AriPerkkio does stackblitz work with coverage-c8? 
https://stackblitz.com/edit/vitest-dev-vitest-ol4ekz
doesn't appear to show coverage.
