### ISSUE TITLE
Hide skipped test lines

### ISSUE THREAD

**Issue by astahmer** [vitest-dev/vitest#2647]
### Clear and concise description of the problem

hey ! could there be any way to get rid of those skipped lines logged ? (as of right now, I don't think so)

![image](https://user-images.githubusercontent.com/47224540/212019401-50056539-981f-4095-8c18-8df1eede5377.png)

when running on a test in the same file as dozens of others with, it's kinda noisy

### Suggested solution

- using a config/CLI option ?
- hide skipped test log when using .only on another test ?
- or the reverse, [when explicitly setting .skip on those tests](https://twitter.com/jarredsumner/status/1612508648940670976) ?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by g4rry420** [comment]
Can I work on this issue ?
