### ISSUE TITLE
HTML test reporter - relative path for assets

### ISSUE THREAD

**Issue by ben-reitz** [vitest-dev/vitest#2651]
### Clear and concise description of the problem

As part of the CI/CD pipeline at our company, we upload the test report folder to a large repository of test reports where the static assets are automatically served on a standard path related to which version of the tests were run. For example:

`https://test-reports-url.com/repo_name/branch_name/build_number/<folder_of_report_assets>`

This approach needs the folder of static assets for the html report to be referenced from the `index.html` with a relative path (`assets/index-21883a1b.js`) rather than the current fixed path (`/__vitest__/assets/index-21883a1b.js`) so they can be served on a URL like the one shown above.

### Suggested solution

When generating the HTML test report, output the paths with the expectation that the HTML report could be served from any URL and don't mandate the fixed `root.com/__vitest__/report` URL format.

### Alternative

Provide a configuration option to choose how the report should be generated.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by mysteryven** [comment]
Since add a new option should be seriously considered, what about just set [`base`](https://vitejs.dev/config/shared-options.html#base) from `'/__vitest__'` to `'./'` in the generated HTML report ?
