### ISSUE TITLE
[0.27.1] Issue with node14: FATAL ERROR: v8::FromJust Maybe value is Nothing.

### ISSUE THREAD

**Issue by belgattitude** [vitest-dev/vitest#2657]
### Describe the bug

Updated to latest 0.27.1 from 0.26.3 and run into this issue (possible regression). Both locally and on [CI](https://github.com/belgattitude/httpx/actions/runs/3911170362/jobs/6684246799) (ubuntu-latest). 

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/259798/212318069-1c43e0c0-5db7-46f0-9c48-57c0ad11b40e.png)

</details>

Only node 14 is affected, 16 and 18 works fine

> PS: I saw a closed related issue (mainly related to windows/macos - https://github.com/vitest-dev/vitest/issues/1191). 

The output

```
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0xa3ac10 node::Abort() [/home/sebastien/.nvm/versions/node/v14.20.0/bin/node]
/home/sebastien/.nvm/versions/node/v14.20.0/bin/node[49081]: ../src/node_file-inl.h:160:node::fs::FSReqPromise<AliasedBufferT>::~FSReqPromise() [with AliasedBufferT = node::AliasedBufferBase<double, v8::Float64Array>]: Assertion `finished_' failed.
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
```

### Reproduction

You can check this repo (confirmed by CI too)

- https://github.com/belgattitude/httpx
- branch: main

```bash
git clone https://github.com/belgattitude/httpx.git
yarn install
cd packages/exception

# For node 14
nvm use 14
yarn vitest run   <-- BREAKS

# For node 16 / 18
nvm use 16
yarn vitest run  <--  Works 

```

Vitest config is located here: https://github.com/belgattitude/httpx/blob/main/packages/exception/vitest.config.ts.

I've tried to remove coverage, etc... but the problem persist

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 1.21 GB / 15.29 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 4.0.0-rc.35 - ~/.nvm/versions/node/v14.20.0/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ibqn** [comment]
I also observe similar behaviour on MacOs starting from versions v0.27.x, where (x=0,1,2)

```shell
pnpm test # which corresponds to `pnpm exec vitest --run`
# tests run succesfull
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 0x1000a60b1 node::Abort() [/usr/local/Cellar/node@14/14.21.2_1/libexec/node]
 2: 0x1000a6233 node::OnFatalError(char const*, char const*) [/usr/local/Cellar/node@14/14.21.2_1/libexec/node]
 3: 0x1001b8988 v8::Utils::ReportApiFailure(char const*, char const*) [/usr/local/Cellar/node@14/14.21.2_1/libexec/node]
 4: 0x1000a8b00 node::fs::FileHandle::CloseReq::Resolve() [/usr/local/Cellar/node@14/14.21.2_1/libexec/node]
 5: 0x1000bac90 node::fs::FileHandle::ClosePromise()::$_0::__invoke(uv_fs_s*) [/usr/local/Cellar/node@14/14.21.2_1/libexec/node]
 6: 0x10213a044 uv__work_done [/usr/local/Cellar/libuv/1.44.2/lib/libuv.1.dylib]
 7: 0x10213d8d5 uv__async_io [/usr/local/Cellar/libuv/1.44.2/lib/libuv.1.dylib]
 8: 0x10214dd9f uv__io_poll [/usr/local/Cellar/libuv/1.44.2/lib/libuv.1.dylib]
 9: 0x10213dcd3 uv_run [/usr/local/Cellar/libuv/1.44.2/lib/libuv.1.dylib]
10: 0x10012f8f8 node::worker::Worker::Run() [/usr/local/Cellar/node@14/14.21.2_1/libexec/node]
11: 0x1001327f0 node::worker::Worker::StartThread(v8::FunctionCallbackInfo<v8::Value> const&)::$_3::__invoke(void*) [/usr/local/Cellar/node@14/14.21.2_1/libexec/node]
12: 0x7ff814b4b4e1 _pthread_start [/usr/lib/system/libsystem_pthread.dylib]
13: 0x7ff814b46f6b thread_start [/usr/lib/system/libsystem_pthread.dylib]
 ELIFECYCLE  Test failed. See above for more details.
zsh: abort      pnpm test
```

**Comment by jgregor5** [comment]
This is happening from v0.27.x, also with Node 16.13.2.

```
FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
 1: 0xb00e10 node::Abort() [node]
 2: 0xa1823b node::FatalError(char const*, char const*) [node]
 3: 0xceddda v8::Utils::ReportApiFailure(char const*, char const*) [node]
 4: 0xafc189 node::fs::FSReqPromise<node::AliasedBufferBase<double, v8::Float64Array, void> >::Resolve(v8::Local<v8::Value>) [node]
 5: 0xb0bef9 node::fs::AfterInteger(uv_fs_s*) [node]
 6: 0x155607d  [node]
 7: 0x155a806  [node]
 8: 0x156cc74  [node]
 9: 0x155b138 uv_run [node]
10: 0xa3dfe5 node::SpinEventLoop(node::Environment*) [node]
11: 0xbc9842 node::worker::Worker::Run() [node]
12: 0xbc9fd8  [node]
13: 0x7f07fc91fb43  [/lib/x86_64-linux-gnu/libc.so.6]
14: 0x7f07fc9b1a00  [/lib/x86_64-linux-gnu/libc.so.6]
Aborted (core dumped)
```

**Comment by sheremet-va** [comment]
> This is also happening from v0.27.x, also with Node 16.13.2, not sure if this is related.
> 
> 
> 
> ```
> 
> FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
> 
>  1: 0xb00e10 node::Abort() [node]
> 
>  2: 0xa1823b node::FatalError(char const*, char const*) [node]
> 
>  3: 0xceddda v8::Utils::ReportApiFailure(char const*, char const*) [node]
> 
>  4: 0xafc189 node::fs::FSReqPromise<node::AliasedBufferBase<double, v8::Float64Array, void> >::Resolve(v8::Local<v8::Value>) [node]
> 
>  5: 0xb0bef9 node::fs::AfterInteger(uv_fs_s*) [node]
> 
>  6: 0x155607d  [node]
> 
>  7: 0x155a806  [node]
> 
>  8: 0x156cc74  [node]
> 
>  9: 0x155b138 uv_run [node]
> 
> 10: 0xa3dfe5 node::SpinEventLoop(node::Environment*) [node]
> 
> 11: 0xbc9842 node::worker::Worker::Run() [node]
> 
> 12: 0xbc9fd8  [node]
> 
> 13: 0x7f07fc91fb43  [/lib/x86_64-linux-gnu/libc.so.6]
> 
> 14: 0x7f07fc9b1a00  [/lib/x86_64-linux-gnu/libc.so.6]
> 
> Aborted (core dumped)
> 
> ```

Update Node 16 to at least 16.17.

**Comment by neymanushka** [comment]
same. ```node v16.10.0``` and ```vitest 0.27.2```
```FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 00007FF62BC7FD2F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112495
 2: 00007FF62BC0EEF6 v8::internal::wasm::WasmCode::safepoint_table_offset+65526
 3: 00007FF62BC0FDAD node::OnFatalError+301
 4: 00007FF62C5413A5 v8::V8::FromJustIsNothing+53
 5: 00007FF62BBF7F43 v8::base::CPU::has_sse+31507
 6: 00007FF62BCE2877 uv_timer_stop+1207
 7: 00007FF62BCDEE4B uv_async_send+331
 8: 00007FF62BCDE5DC uv_loop_init+1292
 9: 00007FF62BCDE77A uv_run+202
10: 00007FF62BCAD885 node::SpinEventLoop+309
11: 00007FF62BB48570 v8::internal::wasm::SignatureMap::Freeze+35776
12: 00007FF62BB43BC8 v8::internal::wasm::SignatureMap::Freeze+16920
13: 00007FF62BCCEF5D uv_poll_stop+557
14: 00007FF62CB024B0 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+146416
15: 00007FFB61727614 BaseThreadInitThunk+20
16: 00007FFB631826A1 RtlUserThreadStart+33
 ELIFECYCLE  Test failed. See above for more details.```

**Comment by sheremet-va** [comment]
> same. node v16.10.0 and vitest 0.27.2

1. Update Node 16 to at least 16.17 according #1191
2. You stack trace is different to the one mention in the issue
3. This issue is only about Node 14
