### ISSUE TITLE
EPERM: operation not permitted, scandir '/Library/Application Support/com.apple.TCC'

### ISSUE THREAD

**Issue by wbiller** [vitest-dev/vitest#2666]
### Describe the bug

Hi all,

I believe someone injected some malware into vitest@0.27.1. After a fresh install I'm greeted with this nice message. vitest@~0.26.0 works.
```
vitest run

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
[Error: EPERM: operation not permitted, scandir '/Library/Application Support/com.apple.TCC'] {
  errno: -1,
  code: 'EPERM',
  syscall: 'scandir',
  path: '/Library/Application Support/com.apple.TCC'
}
```

### Reproduction

```
yarn add --dev vitest@0.27.1
./node_modules/.bin/vitest
```

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 565.36 MB / 32.00 GB
    Shell: 3.6.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.11.0 - ~/.local/share/nvm/v18.11.0/bin/node
    Yarn: 1.22.19 - ~/.local/share/nvm/v18.11.0/bin/yarn
    npm: 8.19.2 - ~/.local/share/nvm/v18.11.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Safari: 16.2
  npmPackages:
    vite: ~4.0.0 => 4.0.4
    vitest: ~0.27.0 => 0.27.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Could you share your `vite.config.ts` as well? There could be a glob pattern or absolute path that accidentally starts from the root of the file system, instead of project root.

I can reproduce the issue by adding `{ test: { root: '/' } }` in configuration. Using `process.cwd()` instead fixes the issue.

```diff
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
-    root: '/',
+    root: process.cwd(),
  },
});
```

Related to https://github.com/vitest-dev/vitest/pull/2637?

**Comment by wbiller** [comment]
Yes, you're right. `root` was set to `'/'`. Thank you very much!
The issue can be closed.
