### ISSUE TITLE
Support jest plugins that use `jest` globals (`jest is not defined`)

### ISSUE THREAD

**Issue by fregante** [vitest-dev/vitest#2667]
### Clear and concise description of the problem

I'm trying to use https://github.com/clarkbw/jest-webextension-mock in Vitest but it fails on load even if I use `globals: true` because the package expects the  `jest` global

```
import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    globals: true,
    setupFiles: [
      "jest-webextension-mock"
    ]
  },
})

```

### Suggested solution

Add `jest` global in dependencies as a tentative compatibility layer, optionally.

### Alternative

Add explicit vitest support to every single package I try using 😰 with productivity going 📉

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by fregante** [comment]
I also tried setting the `jest` global via `setupFiles` but that didn't reach the dependency:

```js
import {defineConfig} from 'vitest/config';

export default defineConfig({
	test: {
		globals: true,
		setupFiles: [
			'./vitest.setup.js',
			'jest-webextension-mock',
		],
	},
});
```

```js
// vitest.setup.js
import {vi} from 'vitest';

global.jest = vi;
```

**Comment by sheremet-va** [comment]
You can add jest global before importing setup file:

```rs
globalThis.jest = vi
import "jest-webextension"
```

**Comment by fregante** [comment]
That won't work because import statements are hoisted.

**Comment by sheremet-va** [comment]
> That won't work because import statements are hoisted.

Try before commenting, please. Import statements are not hoisted in Vitest.

If you are too afraid to break something, you can use „await import“

**Comment by sheremet-va** [comment]
> can that be documented or made it easier as I suggested?

Can be documented, yes.

We will never add `jest` global to Vitest. Other solutions are welcome.

**Comment by fregante** [comment]
How come my previous example didn't work? https://github.com/vitest-dev/vitest/issues/2667#issuecomment-1383071037

I assume setupFiles are meant to create globals among other things

**Comment by sheremet-va** [comment]
> How come my previous example didn't work? https://github.com/vitest-dev/vitest/issues/2667#issuecomment-1383071037
> 
> 
> 
> I assume setupFiles are meant to create globals among other things

Yes. They are running in parallel, not sequential, so it's possible mock resolved before globals were setup.

**Comment by sheremet-va** [comment]
> Since there's `vi.importActual`, could you please clarify plans to support jest plugins that use:
> 
> * `jest.requireActual`

No plans to support requireActual.

**Comment by sheremet-va** [comment]
You can use [`test.sequence.setupFiles: "list"`](https://vitest.dev/config/#sequence-setupfiles) to run setup files one after another. The hack with `global.jest` on the first line will stop working once Vite 4.3 is released as it will follow ESM spec for import hoisting.
