### ISSUE TITLE
Log verbose mode

### ISSUE THREAD

**Issue by jcalfee** [vitest-dev/vitest#2671]
### Clear and concise description of the problem

During development there are times when it is essential to see all of the console log and error messages.  I tried many things and none seem to work in all cases: large outputTruncateLength, using json reporter.  At one point I found it necessary to redirect the npm `debug` package from `process.stdout` because it uses `process.stderr` was suppressed.

I'm glad so much is being done to clean up the output, but I do see an ongoing need, from now on, to by-pass this in the early stages development.

### Suggested solution

Add a verbose-log cli option that ensures messages to `process.stdout` and `process.stderr` always pass-through.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jcalfee** [comment]
Why does maximum truncated output not work?  What is the logic here?

**Comment by sheremet-va** [comment]
Do you have a reproduction? I don't understand your problem.

**Comment by jcalfee** [comment]
It is just stderr.. Stdout seams to always print everything.  I tend to rely on the `debug` package which uses stderr as its default output stream.  But I get into situations under vitest where the stderr is truncated even if I set a large `outputTruncateLength` value.  The only work-around I have is to change code to use stdout.  Sometimes that is easy, but it is not always.

**Comment by sheremet-va** [comment]
> It is just stderr.. Stdout seams to always print everything. I tend to rely on the `debug` package which uses stderr as its default output stream. But I get into situations under vitest where the stderr is truncated even if I set a large `outputTruncateLength` value. The only work-around I have is to change code to use stdout. Sometimes that is easy, but it is not always.

A lot of words but no code. Please, give me something to run

**Comment by jcalfee** [comment]
```js
import {test} from 'vitest'

/** <code>
vitest run --outputTruncateLength 9999 tests/stderr.test.js  # ends at: ,99986,9998
vitest run --outputTruncateLength 9999999 tests/stderr.test.js  # ends at: ,99986,9998
</code>*/
test('stderr', async function() {
  for(let i = 0; i <= 100000; i++) {
    process.stderr.write(i + ',')
  }
})

// Copy and paste the for loop in the node cli, it ends in: 99999,100000,true

// process.stdout is also truncated
```

**Comment by sheremet-va** [comment]
Vitest doesn't truncate anything written via `process.stderr`/`process.stdout`. This is Node.js behavior as far as I understand.
