### ISSUE TITLE
test expect 和 actual 不同，vitest却pass了。 jest 是正常的

### ISSUE THREAD

**Issue by komagic** [vitest-dev/vitest#2673]
### Describe the bug

<img width="307" alt="image" src="https://user-images.githubusercontent.com/13415767/212560313-b00eb36d-1f38-4dac-9247-3c8aa89110c2.png">

### Reproduction

同上

### System Info

```shell
browser
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by komagic** [comment]
https://stackblitz.com/edit/vitest-dev-vitest-nyn1td?file=test%2FusePostMessage.test.ts,vite.config.ts,package.json&initialPath=__vitest__

**Comment by sheremet-va** [comment]
Your error is uncaught - it fails after test finishes, you need to await before the test finishes: 

```ts
describe('usePostMessage', () => {
  it('h2 not equal hello', async () => {
    const ID = 'testFrame';
    const msg = 'hello';
    const frame = window.document.createElement('iframe');
    frame.id = ID;
    window.document.body.appendChild(frame);

    const getData = () => {
      return new Promise((resolve) => {
        frame.contentWindow.addEventListener('message', (e) => {
          resolve(e.data)
        });
      })
    }

    const { result } = renderHook(() => usePostMessage({ iframeId: ID }));
    act(() => {
      result.current.sendToIframe(msg);
    });

    const data = await getData()

    expect(data.message).is.equal('h2');
  });
});
```

**Comment by komagic** [comment]
thanks. but not sure why jest caught the error correctly.

these codes work fine, but in my project, it throw error below:
<img width="1084" alt="image" src="https://user-images.githubusercontent.com/13415767/212854599-094a9fb3-62e9-46b8-8b4c-e1aa7a9266b5.png">

**Comment by komagic** [comment]
thanks
