### ISSUE TITLE
Run only the test with the given name with `-t` and `--testNamePattern`

### ISSUE THREAD

**Issue by remorses** [vitest-dev/vitest#268]
### Clear and concise description of the problem

There is no way to run only a specific test from a file

### Suggested solution

Run only the test with name `x` using `vitest -t x`

### Additional context

This would also make possible to use vitest with the [jest vscode extension](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest) adding `{ "jestrunner.jestPath": "node_modules/vitest/vitest.mjs" }` to vscode settings.json 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
> There is no way to run only a specific test from a file

There is a way! You can use `test.only` for now. But I get the appeal.

**Comment by antfu** [comment]
Actually, `vitest x` would already do 👀

**Comment by remorses** [comment]
But this way there is no way to run a test only on a file with the given name, right? something like `vitest file.test.ts -t testName`

Also, i think it's a bit confusing imo, it would be better to stick to jest cli conventions given that most people are familiar with that

**Comment by antfu** [comment]
Oh ok. PR welcome :)

**Comment by sheremet-va** [comment]
Implemented in [0.0.118](https://github.com/vitest-dev/vitest/releases/tag/v0.0.118)

**Comment by ackmanx** [comment]
> 

I was able to get the `-t` flag to work but your suggestion without the flag worked perfectly
