### ISSUE TITLE
esbuild plugins are ignored

### ISSUE THREAD

**Issue by capaj** [vitest-dev/vitest#269]
### Describe the bug

I am trying to specify an esbuild plugin, but whatever I try it does not get invoked. I am using the same config as found here:
https://github.com/vitejs/vite/pull/2991/files#diff-9d1b5c49a91bfc3b9a10ab850f0bf0281c93350262cc908146dc77da4da4b7ceR17-R32

### Reproduction

check out: https://github.com/capaj/vitest-esbuild-plugin-not-called-example

and run `npx vitest`

Expected result:
```
Hello from an esbuild plugin

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯


- my.spec.ts
Error: No tests found in suite my.spec.ts
 ❯ runSuite node_modules/vitest/dist/entry.js:4116:30
 ❯ async runSuites node_modules/vitest/dist/entry.js:4130:5
 ❯ async startTests node_modules/vitest/dist/entry.js:4135:3
 ❯ async node_modules/vitest/dist/entry.js:4150:7
 ❯ async withEnv node_modules/vitest/dist/entry.js:3946:5
 ❯ async run node_modules/vitest/dist/entry.js:4149:5
 ❯ async file:/home/capaj/oss/vitest-esbuild-plugin-not-called-example/node_modules/tinypool/dist/esm/worker.js:1:1309

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

Test Files  1 failed (1)
     Tests  no tests
      Time  335ms (in thread 0ms, Infinity%)

```

Actual result:

```
 DEV  /home/capaj/oss/vitest-esbuild-plugin-not-called-example

 √ my.spec.ts (3)

 Snapshots  1 written
Test Files  1 passed (1)
     Tests  3 passed (3)
      Time  466ms (in thread 3ms, 16144.17%)

```

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 1.25 GB / 62.75 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Brave Browser: 96.1.33.106
    Chrome: 96.0.4664.110
    Firefox: 95.0.1
  npmPackages:
    vite: ^2.7.6 => 2.7.6 
    vitest: ^0.0.107 => 0.0.107
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Vitest does not run deps optimization. Since it's on the node, it will use node's native import/require whenever possible.

**Comment by capaj** [comment]
@antfu how can I apply esbuild plugin then?

**Comment by antfu** [comment]
This https://vitejs.dev/config/#esbuild ?

**Comment by capaj** [comment]
No, that doesn't allow to configure esbuild plugins. esbuild plugins are only ever defined under the `optimizeDeps`.

**Comment by antfu** [comment]
Please follow https://github.com/vitejs/vite/issues/3124
