### ISSUE TITLE
`google-protobuf` named imports are broken (e.g. `TypeError: Any is not a constructor`)

### ISSUE THREAD

**Issue by ben-xD** [vitest-dev/vitest#2698]
### Describe the bug

_Thanks for maintaining this package. It's nice to run tests when working on applications using Vite._

**Problem:** The named imports from `google-protobuf` don't work **only** when running in Vitest. e.g. `import {Any} from "google-protobuf/google/protobuf/any_pb";`. You'd get an error an error, because the import is undefined.

This issue started showing in vitest `0.25.8`. This was not a problem prior to that. I test my code on latest vitest, `0.27.2`

Example code:
```typescript
// My existing import, which doesn't work with Vitest:
import {Any} from "google-protobuf/google/protobuf/any_pb";

// This import works with Vitest and application
import AnyDefault from "google-protobuf/google/protobuf/any_pb";

describe('Example', () => {
    it('instantiates', () => {
        console.log({Any}) // Undefined when running with vitest, but defined in `index.ts`
        console.log({AnyDefault}) // Defined for both vitest and index.ts

        const any2 = new AnyDefault.Any();
        console.log({any2}) // Works

        const any = new Any() // TypeError: Any is not a constructor
    });
});
```

### Reproduction

https://stackblitz.com/github/ben-xD/vitest-import-issue?file=README.md

https://github.com/ben-xD/vitest-import-issue

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 99.61 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.asdf/installs/nodejs/18.12.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 108.0.2
    Safari: 16.2
  npmPackages:
    vite: ^4.0.4 => 4.0.4
    vitest: ^0.27.2 => 0.27.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
https://github.com/vitest-dev/vitest/releases/tag/v0.26.0:

> If your environment is node, Vitest will not resolve invalid named exports (exports that are on "default" property will not magically appear as named exports), unless deps.interopDefault is enabled, or dependency is in deps.inline. This change doesn't affect jsdom, happy-dom or edge environments.

This will be reverted in the next major, but for now you need to enable `deps.interopDefault` manually.
