### ISSUE TITLE
Docs algolia doesn't jump to search result

### ISSUE THREAD

**Issue by janosh** [vitest-dev/vitest#2700]
### Describe the bug

I was searching for `toHaveBeenCalledWith`.

Used the `cmd + k` shortcut and pasted it in, result came up, I clicked on it and nothing happens. It navigates to https://vitest.dev/api/#tohavebeencalledwith which doesn't exist on that page.

### Reproduction

https://user-images.githubusercontent.com/30958850/212980972-87a8a570-3d91-4f26-a5bb-5656cb6fc1af.mp4

### System Info

```shell
n/a
```

### Used Package Manager

`npm`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
API section was split into separate pages. algolia needs time to index it for the search functionality.

**Comment by janosh** [comment]
I see, I'll close this issue then.
