### ISSUE TITLE
TypeError: Cannot destructure property 'allTestsRun' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by AngelAlexQC** [vitest-dev/vitest#2716]
### Describe the bug

When i try setup vitest & test coverage with c8 i have this error:
![image](https://user-images.githubusercontent.com/9358510/213518409-fb345e23-44c9-40ea-86d1-9498d65aeb29.png)

This error its only with version 0.27.2, when i downgraded to 0.27.1 this works:
![image](https://user-images.githubusercontent.com/9358510/213518793-644dae75-30fa-4b92-bba4-3022fa334461.png)

### Reproduction

![image](https://user-images.githubusercontent.com/9358510/213518879-ec15fe13-c305-42c4-bac0-37871190146f.png)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
    Memory: 3.39 GB / 7.73 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 9.2.0 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
  npmPackages:
    @vitejs/plugin-react: 2.1.0 => 2.1.0 
    vitest: 0.25.8 => 0.25.8
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Do the versions of `vitest` and other `@vitest/` packages have matching versions?

**Comment by AngelAlexQC** [comment]
Oh!, i have a missmatching with deps, i run update and then all works, thanks

**Comment by rn4n** [comment]
How did you fix it? I've created a new project with vue cli and everything was working.
When I added the `--coverage` flag, this error occurs.

```
> vitest --environment jsdom --root src/ --coverage --run


 RUN  v0.25.8 C:/Users/user/Desktop/project/src
      Coverage enabled with c8

 ✓ components/__tests__/HelloWorld.spec.ts (1)

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  22:17:10
   Duration  2.03s (transform 539ms, setup 0ms, collect 223ms, tests 26ms)

 % Coverage report from c8

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: Cannot destructure property 'allTestsRun' of 'undefined' as it is undefined.
```
