### ISSUE TITLE
DataCloneError when using define to add global with multiple properties

### ISSUE THREAD

**Issue by purejgleason** [vitest-dev/vitest#2717]
### Describe the bug

I have the following vitest.config.js 

```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [
    vue(),
  ],
  define: {
    axios: {
      get: () => { },
      post: () => { }
    },
  },
  test: {
    environment: 'happy-dom',
    globals: ['vitest/globals'],
    coverage: {
      reporter: ['lcov'],
    },
  },
})
```

But when I run I see...

```
DataCloneError: () => {
      } could not be cloned.
```

The error is a little different in the StackBlitz but it fails just the same.

Why isn't define working for a nested object

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-yh8ab2?file=vite.config.ts&initialPath=__vitest__

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 20.02 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.2.0 - ~/App/node/node-v19.2.0-darwin-x64/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 9.2.0 - ~/App/node/node-v19.2.0-darwin-x64/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 108.0.2
    Safari: 16.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
For `define` you can only use stringifiable data. It statically replaces your code. If you need to globally add something, you need to add them manually in `test.setupFiles`.

**Comment by purejgleason** [comment]
Understood thank you
