### ISSUE TITLE
How to use polyfills, e.g. reflect-metadata

### ISSUE THREAD

**Issue by LIMPIX31** [vitest-dev/vitest#2723]
### Clear and concise description of the problem

This is not exactly a feature request, but an question that has been ignored in `discussions` and in the discord communities `vite` and `vitest`.

How can I use globally for all tests (including in-source) import polyfill, such as `reflect-metadata` or something that extends `prototype`?

### Suggested solution

I can really just import polyfills into each test file, but what about `in-source` testing when it affects the implementation?

### Additional context

I really hope this is possible in vitest, but if not, it would be a feature request.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Please, stop spamming with this question. If no one answers you, spamming will not help.

**Comment by LIMPIX31** [comment]
> Please, stop spamming with this question. If no one answers you, spamming will not help.

Where did you see the use of spam? I did not violate anything, I read everything that was required before creating the issue. This is the first issue in this repository. 

I apologize if I have repeated the question several times somewhere and it is considered spam.
