### ISSUE TITLE
vue & vitest, data-v-[random-number] attribute being added to html

### ISSUE THREAD

**Issue by ivolkoff** [vitest-dev/vitest#2726]
### Describe the bug

**Introduction**: I am working with vite and vitest, I am doing snapshot tests for components that are 100% template and do not contain any logic

**Problem**: data-v-[random-number] It is being added to the root element of each component and snapshots are always different

**What i want**: Understand why im getting this data-v-[random-number] and if possible, a way to avoid this problem

### Reproduction

BaseText.vue:

```vue
<script setup lang="ts"></script>
<template>
    <span><slot></slot></span>
</template>
```

BaseText.spec.ts:

```ts
import { describe, it, expect } from "vitest";
import { shallowMount } from "@vue/test-utils";
import BaseText from "./BaseText.vue";

describe(name, () => {
    const wrapper = shallowMount(BaseText);
    it("MatchSnapshot", () => {
        expect(wrapper.html()).toMatchSnapshot();
    });
});
```

Error when runing tests:

```
 - Expected   ""<span data-v-25e5131c=""></span>""
 + Received   ""<span data-v-b3462088=""></span>""
```

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 76.22 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 99.0
    Safari: 16.1
  npmPackages:
    vitest: ^0.27.2 => 0.27.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Super-Chama** [comment]
I'm also experiencing the same issue. this wasn't happening in vitest `0.27.1` but recently i did a yarn install and the package has been upgraded to `0.27.3`. Hope this behaviour don't change between versions

**Comment by sheremet-va** [comment]
Vitest doesn't control how Vue renders components. Please, open an issue in [@vue/test-utils](https://github.com/vuejs/test-utils) repo.
