### ISSUE TITLE
Saving file resets filename pattern in watch

### ISSUE THREAD

**Issue by marvinhagemeister** [vitest-dev/vitest#2728]
### Describe the bug

When running `vitest` in watch mode, I typically supply a file pattern so that only one test file is re-run. But whenever I save a file, that pattern is dropped and `vitest` re-runs _all_ tests instead of only the ones that match the supplied pattern.

### Reproduction

1. Create a `foo.ts` file with `export const foo = 2` as content
2. Create two test files `foo.test.ts` and `fail.test.ts` that both import `foo.ts`
3. Start `vitest` in watch mode and use `foo` as the file pattern
4. Edit `foo.ts` and hit save -> Both `foo.test.ts` and `fail.test.ts` are run, despite the `foo` file pattern filter

Stackblitz reproduction: https://stackblitz.com/edit/vitest-dev-vitest-fnc5cv?file=foo.ts,test%2Ffail.test.ts&initialPath=__vitest__

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 81.88 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 109.0
    Safari: 16.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
While looking into this I had trouble to understand when exactly is the filename pattern active - I can imagine users may have same problems as well. 

Maybe the active filename pattern should be shown on terminal? Line 2 in the example below.

![Screenshot 2023-01-26 at 9 00 29](https://user-images.githubusercontent.com/14806298/214775909-52f8a8a3-fea8-436d-a976-df8d45ec52d2.png)

The reported issue itself seems clear. I'll have fix ready soon.
