### ISSUE TITLE
Snapshot tests fail with concurrent execution (Error: Snapshot cannot be used outside of test)

### ISSUE THREAD

**Issue by asdfjkalsdfla** [vitest-dev/vitest#2729]
### Describe the bug

As of 0.27.2, concurrent async tests that use snapshots fail with `Error: Snapshot cannot be used outside of test` message. These tests worked fine under 0.27.1. 

### Related tickets from the past
https://github.com/vitest-dev/vitest/issues/551

### Reproduction

https://stackblitz.com/edit/vitejs-vite-kcqha8?file=package.json,package-lock.json,main.test.jsx&terminal=dev

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    vite: ^4.0.4 => 4.0.4 
    vitest: ^0.27.2 => 0.27.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You need to use "expect" from test context, when using snapshots in concurrent tests:

```js
it("test", ({ expect }) => {
  expect(1).toMatchSnapshot()
})
```

I don't know why it worked for you before, but it shouldn't have, and was never intended to work with global expect.

**Comment by asdfjkalsdfla** [comment]
Interesting. The small case in #551 also uses a global expect vs expect from the test case. Any way to return back to the previous behavior?

**Comment by sheremet-va** [comment]
> Interesting. The small case in #551 also uses a global expect vs expect from the test case. Any way to return back to the previous behavior?

Do you mean the reproduction? It never worked, and couldn't have worked, because snapshot needs to know information about the current test. If you run tests concurrently, you don't have a reliable way to mark the test as "current", because they are running at the same time. To bypass that, you need to use expect from the context.

>  If not, I'm happy to submit an update to the documentation to make this clearer.

Feel free to submit PR with the change using `::: warning` syntax in `toMatchSnapshot`/`toMatchInlineSnapshot` sections

**Comment by asdfjkalsdfla** [comment]
Yeah, I was referring to the reproduction in the original report of #551. That case also worked without issues in 0.27.1 and stopped working in 0.27.2.  

I'll get a PR for the documentation update over. In addition to the snapshot page, I was thinking of updating the concurrent example on the feature page to show it using a context specific expect.
