### ISSUE TITLE
Tests with special characters in the filename are not processed correctly

### ISSUE THREAD

**Issue by jonluca** [vitest-dev/vitest#2731]
### Describe the bug

I have a file in a directory called `__({[ % & $ # @ ` ~ ,)}]__/special-characters.spec.ts`.

The full path to the test is

```
/Users/jonlucadecaro/Documents/Other/json-schema-ref-parser/test/specs/__({[ % & $ # @ ` ~ ,)}]__/special-characters.spec.ts
```

The error is 

```
 FAIL  test/specs/__({[ % & $ # @ ` ~ ,)}]__/special-characters.spec.ts [ test/specs/__({[ % & $ # @ ` ~ ,)}]__/special-characters.spec.ts ]
Error: Failed to load url /Users/jonlucadecaro/Documents/Other/json-schema-ref-parser/test/specs/__({[ % & $ # @ ` ~ ,)}]__/special-characters.spec.ts (resolved id: /Users/jonlucadecaro/Documents/Other/json-schema-ref-parser/test/specs/__({[ % & $ # @ ` ~ ,)}]__/special-characters.spec.ts). Does the file exist?
 ❯ loadAndTransform node_modules/vite/dist/node/chunks/dep-5e7f419b.js:39304:21
```

### Reproduction

Create a test spec in a file directory named:

```
__({[ % & $ # @ ` ~ ,)}]__/special-characters.spec.ts
```

Then try and run the test. The contents of the test do not matter.

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 366.42 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.2.0 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 109.1.47.171
    Chrome: 109.0.5414.87
    Firefox: 108.0.2
    Safari: 16.2
  npmPackages:
    vitest: ^0.27.2 => 0.27.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This seems like a Vite error. Please, create an issue in their repository.

**Comment by jonluca** [comment]
Sounds good, opened https://github.com/vitejs/vite/issues/11784

**Comment by lucaspessivaldo** [comment]
I think the problem is because the path there is spaces between the caracteres, ({[ % & $ # @  ~ ,)}], so that is a invalid path, you need to use backslash \ to scape the spaces.

**Comment by sheremet-va** [comment]
> I think the problem is because the path there are spaces between the caracteres, ({[ % & $ # @  ~ ,)}], so that is a invalid path, you need to use backslash \ to scape the spaces.

Vitest supports spaces in file path

**Comment by so1ve** [comment]
Have you set any alias?

**Comment by sheremet-va** [comment]
Vitest follows Vite rules, and unfortunately it cannot support some special characters: https://github.com/vitejs/vite/issues/11784#issuecomment-1798854088
