### ISSUE TITLE
Snapshots with multiline strings fail on CI but pass locally

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [vitest-dev/vitest#2732]
### Describe the bug

https://github.com/JoshuaKGoldberg/expect-no-axe-violations/blob/52e86e28759ead59924bf8c1bec6bfcd06790c76/src/index.test.ts#L105

These tests run locally, but in CI they fail on what appears to be ... whitespace failures, maybe?

https://github.com/JoshuaKGoldberg/expect-no-axe-violations/actions/runs/3980720022/jobs/6823984107

```plaintext
FAIL  src/index.test.ts > toHaveNoAxeViolations > returns an object when there is a violation
AssertionError: Snapshot `toHaveNoAxeViolations > returns an object when there is a violation 1` mismatched
 ❯ src/index.test.ts:74:5
     72| 
     73|   expect((actual as Exclude<typeof actual, never[]>).message())
     74|    .toMatchInlineSnapshot(`
       |     ^
     75|     "expect(received).toHaveNoViolations(expected)
     76| 

  - Expected  - 5
  + Received  + 5

  - "expect(received).toHaveNoViolations(expected)
  + ""expect(received).toHaveNoViolations(expected)
    
    Expected the HTML found at $('<target />') to have no violations:
    
  - <example />
  + <example />
    
    Received:
    
  - "Example help (abc1[23](https://github.com/JoshuaKGoldberg/expect-no-axe-violations/actions/runs/3980720022/jobs/6823984107#step:4:24))"
  + "Example help (abc123)"
    
  - It's a failure.
  + It's a failure.
    
    You can find more information on this issue here: 
  - https://example.com/""
  + https://example.com/""
```

I tried switching to `toMatchSnapshot()` as well, and the errors were similar.

### Reproduction

https://github.com/JoshuaKGoldberg/expect-no-axe-violations/tree/1d37e5c037d8a4b612645b97c185337141d76ee5

To see that it's passing locally:

```shell
git clone https://github.com/JoshuaKGoldberg/expect-no-axe-violations
cd expect-no-axe-violations
git checkout 52e86e28759ead59924bf8c1bec6bfcd06790c76
pnpm install
pnpm test
```

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M2
    Memory: 263.11 MB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    npm: 8.15.1 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 108.0.2
    Safari: 15.6
  npmPackages:
    vitest: ^0.27.2 => 0.27.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
The `toHaveNoAxeViolations` seems to give different output when `process.env.CI` is present. Your test is giving different text to Vitest snapshot assertion on each run depending on this flag.

This can be reproduced with following addition in local environment by running `CI=true pnpm test` and regular `pnpm test`.

```diff
describe("toHaveNoAxeViolations", () => {
	it("returns an object when there is a violation", () => {
		const violations = [createViolation("abc123")];
		const actual = matchers.toHaveNoAxeViolations({
			violations,
		});

+		writeFileSync(
+			`./snapshot-when-ci-${Boolean(process.env.CI)}`,
+			// @ts-ignore
+			actual.message(),
+			"utf-8"
+		);
```


<details>
  <summary>snapshot-when-ci-true</summary>

```
expect(received).toHaveNoViolations(expected)

Expected the HTML found at $('<target />') to have no violations:

<example />

Received:

"Example help (abc123)"

It's a failure.

You can find more information on this issue here: 
https://example.com
```

</details>

<details>

  <summary>snapshot-when-ci-false</summary>

```
[2mexpect([22m[31mreceived[39m[2m).toHaveNoViolations([22m[32mexpected[39m[2m)[22m

Expected the HTML found at $('<target />') to have no violations:

[90m<example />[39m

Received:

[31m"Example help (abc123)"[39m

[33mIt's a failure.[39m

You can find more information on this issue here: 
[34mhttps://example.com[39m
```

</details>

**Comment by JoshuaKGoldberg** [comment]
OH! That must be `chalk` then. Apologies, user error!

**Comment by JoshuaKGoldberg** [comment]
For anybody else who sees this, my solution was https://github.com/JoshuaKGoldberg/expect-no-axe-violations/pull/3.
