### ISSUE TITLE
Expose CanvasRenderingContext2D via the `canvas` package

### ISSUE THREAD

**Issue by hetsch** [vitest-dev/vitest#274]
### Clear and concise description of the problem

I tried to use vitest in a project where I extensively use `pixi.js` and therefore, the `Canvas` element. As far as I know, `jsdom` does not expose canvas functionality out of the box but it can be emulated by using the `node-canvas` package (https://github.com/jsdom/jsdom/issues/3042). 

### Suggested solution

What I tried was bootstraping the `canvas` package in the `jsdom` environment with the following code 

```js
try {
  const { Context2d } = await importModule("canvas");
  Object.defineProperty(global, "CanvasRenderingContext2D", {
    get() {
      return Context2d
    }
  })
} catch (e) { }
```

inserted somewhere at
https://github.com/vitest-dev/vitest/blob/27d6bcb10d6c00ae678769c6f48422ffe9d7d142/packages/vitest/src/env/jsdom.ts#L28-L30

Not the nicest implementation, but I hope you get the idea.

### Additional context

By the way: Thank's for this awesome package. It was so easy to setup and works damn good!

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
You could set it up with your own setup files. From our standpoint, we can't cover every single browser spec that not provided by `jsdom`, and since we want to avoid introducing too many deps, this might not be the default behavior of Vitest.

**Comment by hetsch** [comment]
Yes, I wholeheartly agree to not bloat Vitest. The thing is, `pixi.js` checks in the moment it is imported via `import { Application } from "pixi.js"` if a CanvasRenderingContext (2d or Webgl) is available. If not, it throws an exception. 

Might it be that my own setup files are loaded too late (after the test file is loaded), so that I'm not getting a chance to patch the `global` object in the `beforeAll` hook? Thank's again!

**Comment by patak-dev** [comment]
@hetsch maybe you could use https://vitest.dev/config/#setupfiles, to execute a script before all the files. Like this https://jestjs.io/docs/configuration#setupfiles-array

**Comment by hetsch** [comment]
Thank you, @antfu and @patak-dev. Was my bad. Putting the code in a setup file works perfectly fine.

**Comment by regenrek** [comment]
@hetsch could maybe share some code how you solved it? Trying to test a [konvajs](https://github.com/konvajs/konva) project where I need `canvas` too. Can't figure it out how to test it with `jsdom` and `vitest`.

**Comment by jagoncalves14** [comment]
Wondering myself the same thing @hetsch.
I tried adding the following on the setup file.
```
HTMLCanvasElement.prototype.getContext = vi.fn()
```

But unfortunately it didn't work 😓

**Comment by leonbloy** [comment]
For those who are also looking for a recipe: 
This one worked for me

https://github.com/hustcc/jest-canvas-mock/issues/88

**Comment by jagoncalves14** [comment]
Thanks @leonbloy, that fix worked perfectly for me!

**Comment by jagoncalves14** [comment]
> For those who are also looking for a recipe: This one worked for me
> 
> [hustcc/jest-canvas-mock#88](https://github.com/hustcc/jest-canvas-mock/issues/88)

Thanks @leonbloy, that fix worked perfectly for me!

**Comment by gromann** [comment]
Hi, I had the same Issue with three.js. 
Mocking with jsdom worked for me, but I had some troubles with it when trying it for the first time. 
[I described here how i did it. ]( https://www.the-koi.com/projects/vitest-how-to-mock-a-canvas/)

**Comment by schirrel** [comment]
I just release vi-canvas-mock based on jest-canvas-mock if it helps https://github.com/schirrel/vi-canvas-mock/tree/1.0.0
