### ISSUE TITLE
Vitest failing with "Error: require() of ES Module" with @visx/scale -package, even when package is inlined

### ISSUE THREAD

**Issue by diginikkari** [vitest-dev/vitest#2742]
### Describe the bug

Running vitest for file including import from `@visx/scale` -package fail with:

```
Error: require() of ES Module /.../node_modules/.pnpm/d3-scale@4.0.2/node_modules/d3-scale/src/index.js from /.../node_modules/.pnpm/@visx+scale@3.0.0/node_modules/@visx/scale/lib/scales/band.js not supported.
Instead change the require of index.js in /.../node_modules/.pnpm/@visx+scale@3.0.0/node_modules/@visx/scale/lib/scales/band.js to a dynamic import() which is available in all CommonJS modules.
```

I added `@visx/scale` to `deps.inline` config, but error still occurs. I have not been able to figure out config which would let me run the tests. Actual building and running of the specified code with vite is working fine.

Perhaps the @visx -packages are somehow wrongly configured, but if those are working fine in dev and production, perhaps there should be way to configure vitest to work with them also?

### Reproduction

https://github.com/diginikkari/visx-scale-esm-issue

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 3.54 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.volta/tools/image/node/16.19.0/bin/node
    Yarn: 3.3.0 - ~/.volta/tools/image/yarn/4.0.0-rc.35/bin/yarn
    npm: 8.19.3 - ~/.volta/tools/image/node/16.19.0/bin/npm
    Watchman: 2022.09.26.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 109.1.47.171
    Chrome: 109.0.5414.87
    Firefox: 108.0.2
    Safari: 16.2
  npmPackages:
    @vitejs/plugin-react: ^3.0.1 => 3.0.1 
    @vitest/coverage-c8: ~0.28.1 => 0.28.1 
    @vitest/ui: ^0.28.1 => 0.28.1 
    vite: ^4.0.4 => 4.0.4 
    vitest: ^0.28.1 => 0.28.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
@visx/scale has an incorrect package.json that resolved package entry always to cjs file. Try adding an `alias` to esm:

```ts
// vitest.config.ts
export default {
  test: {
    alias: [{ find: /^@visx/scale$/, replacement: '@visx/scale/esm/index.js' }]
  }
}
```

**Comment by MarkLyck** [comment]
> @visx/scale has an incorrect package.json that resolved package entry always to cjs file. Try adding an `alias` to esm:
> 
> ```ts
> // vitest.config.ts
> export default {
>   test: {
>     alias: [{ find: /^@visx/scale$/, replacement: '@visx/scale/esm/index.js' }]
>   }
> }
> ```
> 
> Or you can also add "module" field to "resolve.mainFields".

I'm having the same issue on vitest@0.30.1

However adding this alias results in the following error:

```
$ vitest Analytics.test.tsx
✘ [ERROR] Syntax error "c"

    vite.config.ts:37:23:
      37 │       { find: /^@visx/scale$/, replacement: '@visx/scale/esm/index.js' }
```

**Comment by AddictArts** [comment]
> 
>     vite.config.ts:37:23:
>       37 │       { find: /^@visx/scale$/, replacement: '@visx/scale/esm/index.js' }
> ```
> 
> It doesn't seem to parse the regex.

` /^@visx/scale$/` is not a valid regex right? can you see it ..., looks like github possibly removed the escape of `/`, so you want 

` /^@visx\/scale$/`
