### ISSUE TITLE
Environment Variables Mocking not working

### ISSUE THREAD

**Issue by kb-0311** [vitest-dev/vitest#2752]
### Describe the bug

1. the documentation describing env vars mocking does not work.
2. the is no vi.stubEnv anymore.
3. Here is the vite.config.ts for tests-
```
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    coverage: {
      // This tells vitest to include all files from ./src in test coverage.
      all: true,

      // This tells vitest the directory to get coverage for.
      include: ["src/"],

      // This tells vitest the files/directories to exclude from the coverage.
      // This is intentionally done because coverage for these files doesn't
      // provide any meaningful details for coverage report.
      exclude: [
        "src/config",
        "src/models",
        "src/typeDefs",
        "src/types",
        "src/constants.ts",
        "src/db.ts",
        "src/server.ts",
      ],

      // This is used to tell vitest which coverage provider to use. c8 is the newer and
      // recommended coverage provider for node.js applications. You can swap it with
      // istanbul as well.
      provider: "c8",

      // This tells vitest in what format the report will be generated. Here lcov
      // is selected because a file named lcov.info is generated by this reporter which
      // is used in codecov/codecov-action github action for talawa-api.
      reporter: ["text", "json", "html"],
    },

    // Tells vitest the time limit for an individual test block run.
    testTimeout: 30000,
  },
});

```

4. import.meta.env does not work.

### Reproduction

```
import "dotenv/config";
import { Document, Types } from "mongoose";
import {
  Interface_User,
  User,
  Organization,
  Interface_Organization,
  Event,
  Interface_Event,
  Interface_EventProject,
  EventProject,
} from "../../../src/models";
import { nanoid } from "nanoid";
import { connect, disconnect } from "../../../src/db";
import {
  beforeAll,
  afterAll,
  describe,
  it,
  expect,
  vi,
  beforeEach,
} from "vitest";
import {
  USER_NOT_FOUND,
  USER_NOT_AUTHORIZED,
  IN_PRODUCTION,
  EVENT_PROJECT_NOT_FOUND,
  EVENT_PROJECT_NOT_FOUND_MESSAGE,
  EVENT_PROJECT_NOT_FOUND_CODE,
} from "../../../src/constants";
import { updateEventProject } from "../../../src/resolvers/Mutation/updateEventProject";
let testUser: Interface_User & Document<any, any, Interface_User>;
let testOrganization: Interface_Organization &
  Document<any, any, Interface_Organization>;
let testAdminUser: Interface_User & Document<any, any, Interface_User>;
let testEvent: Interface_Event & Document<any, any, Interface_Event>;
let testEventProject: Interface_EventProject &
  Document<any, any, Interface_EventProject>;

  import.meta.env.NODE_ENV
beforeEach(() => {
    vi.stubEnv(NODE_ENV , production)
});

```

### System Info

```shell
vi.stubEnv not defined
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is a perfect example on how not to create an issue.

"System Info" section doesn't have anything useful. The issue template asked you to run a command, and you didn't. You also do not provide actual reproduction. I cannot jus copy-paste it into an empty repo. The issue template asked you to use stackblitz. 

Documentation literally has examples that do not match your reproduction:

<img width="743" alt="Screenshot 2023-01-26 at 09 02 44" src="https://user-images.githubusercontent.com/16173870/214785376-49a16ae5-6a32-4411-a2b9-25944c6c4320.png">

Update your Vitest version.
