### ISSUE TITLE
Multiple async `beforeEach` hooks are not called serially

### ISSUE THREAD

**Issue by yyx990803** [vitest-dev/vitest#2756]
### Describe the bug

When multiple async `beforeEach` hooks are declared for a suite, they should be called serially - i.e. the next hook should not execute until the previous hook is resolved. Currently, they are all called in parallel.

Jest calls these hooks with expected behavior (I noticed this when migrating Vue 3's test suite from Jest).

### Reproduction

```js
beforeEach(async () => {
  await new Promise(r => setTimeout(r, 100))
  console.log(1)
})

beforeEach(async () => {
  console.log(2)
})
```

Expects: 1, 2
Actual: 2, 1

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 88.56 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/Library/Caches/fnm_multishells/65334_1674742292927/bin/node
    Yarn: 1.22.5 - /opt/yarn-v1.22.5/bin/yarn
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/65334_1674742292927/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Chrome Canary: 111.0.5560.0
    Firefox: 106.0.5
    Safari: 14.1.1
  npmPackages:
    vite: ^4.0.4 => 4.0.4
    vitest: ^0.28.2 => 0.28.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It's configurable: https://vitest.dev/config/#sequence-hooks

**Comment by yyx990803** [comment]
Should the default be changed to align with the default behavior of Jest? What is the rationale behind the `parallel` default?

**Comment by sheremet-va** [comment]
> Should the default be changed to align with the default behavior of Jest? What is the rationale behind the `parallel` default?

At the time of release, we didn't want to change the default behavior because it would be a breaking change. Nothing is stopping us from changing the default now, I think.
