### ISSUE TITLE
vitest errors if there are no in-source tests, even with --passWithNoTests

### ISSUE THREAD

**Issue by evanandrewrose** [vitest-dev/vitest#2763]
### Describe the bug

With in-source tests, the recommendation is to change the file path glob to something like `src/*.{ts,js}` as per https://vitest.dev/guide/in-source.html. However, if you do this, you'll get errors for all of your source files that don't have any in-source tests. I would expect to be able to suppress this with `--passWithNoTests`, but I still get the same error.

My temporary hack to get around this is:

```package.json
{
	"scripts": {
		"test:unit": "npx vitest run $(grep -lr 'import.meta.vitest' src/ | tr '\\n' ' ')",
		"test:unit:watch": "npx vitest --ui $(grep -lr 'import.meta.vitest' src/ | tr '\\n' ' ')"
	}
}
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-jtuly9?file=package.json

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 3.02 GB / 7.72 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.local/share/pnpm/node
    npm: 8.19.3 - ~/.local/share/pnpm/npm
  npmPackages:
    vite: ^4.0.4 => 4.0.4
    vitest: ^0.28.3 => 0.28.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`include` is only for test files. `includeSource` is for source files with tests.
