### ISSUE TITLE
Extremely slow for huge snapshots mismatch

### ISSUE THREAD

**Issue by Maxim-Mazurok** [vitest-dev/vitest#2764]
### Describe the bug

I have a huge snapshot (38k lines JS Map), when I run `vitest` in either `dev` or `run` modes - it takes insane amount of time to get response, one might think that it just hangs.

### Reproduction

My test:
```
import { it, describe, expect } from "vitest";

describe("something", () => {
  it("works", () => {
    expect(something()).toMatchSnapshot();
  });
});
```

My snapshot:
```
// Vitest Snapshot v1

exports[`something > works 1`] = `
Map {
  "Cucumber Lebanese" => [
    {
      "amountPerUnit": 5,
      "dateTime": "2020-01-01T01:01:00.000Z",
      "item": {
        "amount": 1,
        "description": "Cucumber Lebanese",
        "onSpecial": false,
        "productSeries": "Cucumber Lebanese",
        "quantity": 1,
      },
    },
    // repeat 3 times
    }
  ],
  // repeat 1000 times
```

When I run tests, I get this:

```
 FAIL  util.spec.ts > something > works
AssertionError: Snapshot `something > works 1` mismatched
 ❯ util.spec.ts:6:42
      4| describe("something", () => {
      5|   it("works", () => {
      6|     expect(something()).toMatchSnapshot();
       |                                          ^
      7|   });
      8| });
```

and then the process keeps on running while using ~10-20% of CPU.

After a long time I think the process fails with non-zero code without showing diff, but I'm not 100% sure about that.

Might be related to https://github.com/vitest-dev/vitest/issues/2008

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900H
    Memory: 32.59 GB / 63.68 GB
  Binaries:
    Node: 19.3.0 - ~\AppData\Local\nvs\node\19.3.0\x64\node.EXE
    npm: 9.2.0 - ~\AppData\Local\nvs\node\19.3.0\x64\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
#2828 should fix this issue, please let me know if it does

**Comment by Maxim-Mazurok** [comment]
It does, see https://github.com/vitest-dev/vitest/pull/2828#issuecomment-1426909884
Thank you, please consider reopening this issue
