### ISSUE TITLE
Console tab in vitest-ui prints console.log output as html

### ISSUE THREAD

**Issue by leonadler** [vitest-dev/vitest#2765]
### Describe the bug

When displaying the "Console" tab in vitest-ui, `console.log` calls that contain a `<` are printed differently depending on how console.log was called. I'm not sure if it is intended (as in, would you sometimes want html printed from console.log as HTML in vitest-ui?) and/or fixable, but it caused some headache so I thought I'd report it.

The repro case below is basically:
```tsx
console.log('A: ', /(?<char>\w)/);
console.log('B: ', /(?<char>\w)/.source);
console.log(`C: ${/(?<char>\w)/}`);
```
(in 3 tests, as the HTML `<char>` corrupts other console logs in the same test)

These 3 statements get output differently:
![image](https://user-images.githubusercontent.com/8845620/215321124-f7eda57a-e363-4876-9595-8219d7f4ec1d.png)

For the first case, an actual `<char>` element is added in vitest-ui.
![image](https://user-images.githubusercontent.com/8845620/215321151-4849f91f-745c-4b27-b2c9-8f7d10270223.png)

Possibly related issue: #1279 - vitest UI doesn't log html correctly in the "console log" tab

### Reproduction

```tsx
import { test } from 'vitest';

const exampleRegex = /(?<char>\w)/;
//                      ^^^^^^ this gets removed in the output

test('console.log with RegExp object', () => {
  console.log('A: ', exampleRegex);
});

test('console.log with source as 2nd argument', () => {
  console.log('B: ', exampleRegex.source);
});

test('console.log with string', () => {
  console.log(`C: ${exampleRegex.source}`);
});
```

### System Info

```shell
System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 12.48 GB / 31.06 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 109.0
    Firefox: 109.0
  npmPackages:
    @vitejs/plugin-react: ^3.0.1 => 3.0.1 
    @vitest/coverage-c8: ^0.28.2 => 0.28.2 
    @vitest/ui: ^0.28.2 => 0.28.2 
    vite: ^4.0.4 => 4.0.4 
    vitest: ^0.28.2 => 0.28.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Fixed by https://github.com/vitest-dev/vitest/pull/4724
