### ISSUE TITLE
Add vitest infrastructure for validating that the correct number of tests pass/fail

### ISSUE THREAD

**Issue by JessicaSachs** [vitest-dev/vitest#277]
### Clear and concise description of the problem

Vitest has good infrastructure to validate that multiple different project types and specs work, however it doesn't look like we have tests for executing failed states and making sure the correct number of tests execute.

Vitest can break by:
1. Exiting with process 0, regardless of any test failures.
2. Not running the correct number of tests.
3. Accidentally skipping tests that were meant to run.

**A lot of these goals are met in our current test infrastructure, but I wanted to share the strategies we use to test a test runner 😄 **

### Suggested solution

We have a layer of testing in Cypress to ensure failures like this are caught, called System Tests.

Some goals of System Tests are:
1. Running suites of tests against various userspace + project configurations (e.g. nuxt vs sveltekit vs vitepress vs React 18/19 etc) and ensuring they all work
2. Ensuring that each suite will fail appropriately or pass appropriately
3. Ensuring that the correct number of failures occurs
4. Ensuring that failing hooks properly fail the spec without running the tests
5. Ensuring the process exits with the proper exit code (when failing or succeeding)
6. Snapshotting the reporter output

https://github.com/cypress-io/cypress/blob/28a912354bf6bb780b1eb180e09a63389395e078/system-tests/README.md#L62

**An Example System Test**
[Link](https://github.com/vitest-dev/vitest/issues/277)
<img width="800" alt="Screen Shot 2021-12-22 at 3 45 30 PM" src="https://user-images.githubusercontent.com/2801156/147153064-f67d7dcf-b35f-4405-8238-dfe94c53054b.png">

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
We have something halfway https://github.com/vitest-dev/vitest/blob/main/test/fails/test/runner.test.ts

**Comment by shiwano** [comment]
> Exiting with process 0, regardless of any test failures.

I think vitest has this problem. I ran the following command in [the official example directory](https://github.com/vitest-dev/vitest/tree/main/examples/react) where I changed a test to fail, but vitest does not seem to close the process with exit code 1.

Because of this problem, we can not use vitest in CI. Does anyone have workaround about it?

```sh
~/code/src/github.com/vitest-dev/vitest/examples/react yarn test                                                                                                                                                                                6s  main
yarn run v1.22.15
$ vitest run && echo 'succeeded'

 RUN  /Users/shiwano/code/src/github.com/vitest-dev/vitest/examples/react

 ❯ test/basic.test.tsx (1)
   × Link changes the class when hovered

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/basic.test.tsx > Link changes the class when hovered
AssertionError: expected { Object (type, props, ...) } to be an instance of Array
 ❯ toJson test/basic.test.tsx:8:17
      6|   const result = component.toJSON()
      7|   expect(result).toBeDefined()
      8|   expect(result).toBeInstanceOf(Array)
       |                 ^
      9|   return result as renderer.ReactTestRendererJSON
     10| }
 ❯ test/basic.test.tsx:16:13

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Snapshots  3 obsolete
            ↳ test/basic.test.tsx
              · Link changes the class when hovered 1
              · Link changes the class when hovered 2
              · Link changes the class when hovered 3

Test Files  1 failed (1)
     Tests  1 failed (1)
      Time  1.35s (in thread 11ms, 11861.58%)

succeeded
✨  Done in 1.93s.
```
