### ISSUE TITLE
Broken links in the search result

### ISSUE THREAD

**Issue by tolacika** [vitest-dev/vitest#2770]
### Describe the bug

See your link from the documentation site: https://vitest.dev/api/#vi-spyon

### Reproduction

Visit the doc site and search for 'spyon'

### System Info

```shell
N/A
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
https://vitest.dev/api/vi.html#vi-spyon

**Comment by tolacika** [comment]
> https://vitest.dev/api/vi.html#vi-spyon

Thanks, this helps me 🙂 
But the bug remains, but now I can share more info about it.

I mean when you search for anything the links are broken in the result list

<img width="862" alt="Screenshot 2023-02-01 at 14 10 26" src="https://user-images.githubusercontent.com/1866861/216053260-2f590345-37de-4ec4-b2aa-20e36b60c7a8.png">

**Comment by sheremet-va** [comment]
It's a known issue, algolia didn't index new pages yet. Just wait.
