### ISSUE TITLE
[Documentation] Difference between vi.spyOn and vi.fn is vague.

### ISSUE THREAD

**Issue by advename** [vitest-dev/vitest#2771]
### Clear and concise description of the problem

From the function [Mocking Example](https://vitest.dev/guide/mocking.html#example):

> ...However spies can only help you spy on functions, they are not able to alter the implementation of those functions.

As a first-time reader, this sounds to me that
- Spies (`vi.spyOn`) only allow you to monitor a method
- Mock functions (`vi.fn`) allow you to alter the implementation of a method + allows restoring the original implementation with [`clearAllMocks`](https://vitest.dev/api/vi.html#vi-clearallmocks)

Then, the following example has these two lines
```js
    spy.mockImplementationOnce(() => 'access-restricted')
    expect(messages.getLatest()).toEqual('access-restricted')
```

Wait, so we can replace or add behaviour to a function using `vi.spyOn`, but also restore the original implementation with [`clearAllMocks`](https://vitest.dev/api/vi.html#vi-clearallmocks)

Mocking and Spying by themselves are already confusing terms in testing, and I would understand as much as

If I'm not mistaken and based on my experience with Jest, I **would assume that**
- [`vi.fn`](https://vitest.dev/api/vi.html#vi-fn) replaces or adds behaviour to a function
- [`vi.spyOn`](https://vitest.dev/api/vi.html#vi-spyon) replaces or adds a behaviour to a function, but allows restoring the original implementation

### Suggested solution

I feel there needs to be a better explanation for the differences between `vi.spyOn` and `vi.fn`.
What exactly are now the differences between `vi.spyOn` and `vi.fn`?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by advename** [comment]
Sorry, but I'm now even more lost. I'm moving from Jest and on the Vitest homepage is read:

> Jest Compatible
> Expect, snapshot, coverage, and more - migrating from Jest is straightforward.

I'm trying to connect the similarities or differences between `jest.fn`/`jest.spyOn` and `vi.fn`/`vi.spyOn`.

Having this method
```js
const myObj = { 
   addNumbers(a, b){
   return a + b;
}}
```

In Jest:
- `jest.fn` mocks a function by overriding it
```js
test('mocks addNumbers using jest.fn', () => {
   const mockAddNumbers = jest.fn();
   mockAddNumbers.mockReturnValue(30);
   myObj.addNumbers = mockAddNumbers;

   expect(myObj.addNumbers(10, 20)).toBe(30);
});
```
- `jest.spyOn` monitors a function, but also allows function mocking while being able to restore the original implementation.
```js
test('mocks addNumbers using jest.spyOn', () => {
   const spy = jest.spyOn(myObj, 'addNumbers');
   spy.mockImplementation(() => 30);

   expect(myObj.addNumbers(10, 20)).toBe(30);
   expect(spy).toHaveBeenCalledTimes(1);

   spy.mockRestore();
});
```

However, it seems like above doesn't apply to vitest methods?

**Comment by sheremet-va** [comment]
> However, it seems like above doesn't apply to vitest methods?

it does. They should function the same way.

**Comment by davpascoal** [comment]
> it does. They should function the same way as they do in Jest.

But apparently they don't.

Let's have a look at these examples:

With Jest:

```js
const intersectionObserverMock = () => ({
  observe: () => null,
  disconnect: () => null,
});
window.IntersectionObserver = jest
   .fn()
   .mockImplementation(intersectionObserverMock);
```

If you create a new IntersectionObserver and you `console.log` it you get:

`observer { observe: [Getter/Setter], disconnect: [Getter/Setter] }`

With Vitest:

```js
const intersectionObserverMock = () => ({
  observe: () => null,
  disconnect: () => null,
});
window.IntersectionObserver = vi
  .fn()
  .mockImplementation(intersectionObserverMock);
```
If you create a new IntersectionObserver and you `console.log` it you get:

`{ ctaObserver: spy {} }`

**Comment by andrewmclagan** [comment]
🤔 ...

**Comment by Steveunouss** [comment]
🤔 ...

**Comment by noelseom** [comment]
+1

**Comment by sheremet-va** [comment]
It's described in documentation: https://vitest.dev/api/mock.html
