### ISSUE TITLE
Type tests pass even when they should fail

### ISSUE THREAD

**Issue by lukaVarga** [vitest-dev/vitest#2773]
### Describe the bug

It seems like type tests do not function. TSC correctly detects type mismatch, but the test succeeds.
It seems to affect all methods - eg. 
```
test('type', () => {
  expectTypeOf(5).toEqualTypeOf<string>();
  assertType<number>('trs');
});
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-ifsb5l?file=test/basic.test.ts

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 6.06 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    npm: 8.19.3 - ~/Desktop/code/skeletonizer/node_modules/.bin/npm
    Watchman: 2022.10.31.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 97.0
    Safari: 16.2
  npmPackages:
    vitest: ^0.28.3 => 0.28.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
The reproduction case is not running `vitest typecheck`. It's also not including the `basic.test.ts` in `test.typecheck.include`.

https://vitest.dev/guide/testing-types.html#testing-types
> By default all tests inside `*.test-d.ts` files are considered type tests, but you can change it with [`typecheck.include`](https://vitest.dev/config/#typecheck-include) config option.

https://vitest.dev/guide/testing-types.html#run-typechecking
> ```json
> "scripts": {
>   "typecheck": "vitest typecheck"
> }
> ```

**Comment by lukaVarga** [comment]
@AriPerkkio right, it looks like I oversimplified the reproduction example, my bad. I've updated the example. 

The actual issue seems to lie in the fact that `typecheck.tsconfig` doesn't do what's supposed to do. So as long as the test files are included in the `tsconfig.json`, the typecheck indeed works fine. If you have a separate tsconfig for test files and the test files are not included in the base `tsconfig.json`, it won't work.

From what I can see, the reason lies here
https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/typecheck/parse.ts#L65

It treats `tsconfig` option as a search path within which `get-tsconfig` attempts to find it, however, it passes the string as-is - it does not transform it into an actual file path. Furthermore, since the 2nd argument `get-tsconfig` accepts is the name of the config itself - and that is undefined - `get-tsconfig` will always attempt to find a `some-path/.../tsconfig.json` (see https://github.com/privatenumber/get-tsconfig/blob/develop/src/get-tsconfig.ts#L10)

A quick and easy fix to this would be to adjust L65 in typecheck/parse.ts to:
```
const tsconfig =  getTsconfigContent(root, config.tsconfig ? config.tsconfig : configName);
```
That would find the closest tsconfig with the name one provides in `typecheck.tsconfig` from current root.

I'm happy to open a PR for it if needed.

**Comment by sheremet-va** [comment]
> A quick and easy fix to this would be to adjust L65 in typecheck/parse.ts to:

I expect tsconfig to be a filepath, from docs:

```
Path to custom tsconfig, relative to the project root.
```

We should probably `resolve` it relative to the root then:

```ts
getTsConfig(resolve(root, config.tsconfig), basename(config.tsconfig))
```

**Comment by kabalage** [comment]
I also experience this issue. With `vitest typecheck` the tests pass, but `vue-tsc` correctly reports the errors. I could not find a way to configure `test.typecheck` in the config to make vitest report the errors.
