### ISSUE TITLE
Alias not being resolved when mocking a module since 0.27.3

### ISSUE THREAD

**Issue by kalvenschraut** [vitest-dev/vitest#2775]
### Describe the bug

![image](https://user-images.githubusercontent.com/30308012/215613600-52607d1a-7871-465c-ac0e-6c60cf4b05e8.png)
For example I use `@` to point to my src directory and instead I have to use `../src/` instead since my tests are in a test dir at the top level.

### Reproduction

broken case on https://stackblitz.com/edit/vitest-dev-vitest-mmdlkp?file=package.json 0.27.3

working case on https://stackblitz.com/edit/vitest-dev-vitest-7vrs2x?file=package.json  0.27.2

Note same test case for both just changed version for your convenience. Its also still broken on the latest version at time of writing this (0.28.3)

### System Info

```shell
repo on stackblitz
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by philipbushnell-valtech** [comment]
It might be bigger than just aliases. I have the following in my `vitest.setup.ts` and it's also stopped working from `0.27.3` onwards (up to `0.28.3`, the latest at time of writing):

```ts
vi.mock('vue-i18n', () => ({
  useI18n: () => ({ t: (key: string) => key }),
}));
```

I had to downgrade to `0.27.2`.

Interestingly, I also have this in my `vitest.setup.ts` and it works just fine:

```ts
vi.mock('nuxt/app', () => ({
  useRuntimeConfig: () => ({
    ...
    public: {
      ...
    },
  }),
}));
```

**Comment by sheremet-va** [comment]
Probably because of this: #2687

We need to revert it

**Comment by jgoux** [comment]
Hello 👋

After investigating my own issue: https://github.com/vitest-dev/vitest/issues/2787 I realized this was caused by the same code!
