### ISSUE TITLE
Documentation for vi.mock is missing.

### ISSUE THREAD

**Issue by yagiz-noonlight** [vitest-dev/vitest#2789]
### Describe the bug

Searching for vi.mock API docs on the website is not working.

### Reproduction

1. Open vitest.dev
2. Press CMD+K
3. Type `vi.mock` (it will take you to `https://vitest.dev/api/#vi-mock`)
4. The documentation is missing.

### System Info

```shell
N/A
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It's a known issue, algolia didn't index new pages yet. Just wait. API section was split into separate articles, and mock documentation is here now: https://vitest.dev/api/vi.html#vi-mock
