### ISSUE TITLE
toMatch output is truncated

### ISSUE THREAD

**Issue by Shinigami92** [vitest-dev/vitest#2791]
### Describe the bug

While using e.g. `toMatch` the expected result is truncated even when setting `outputTruncateLength` to 1000

```node
 FAIL  test/git.spec.ts > git > random seeded tests for seed 3694299162975756 > commitEntry > should return a valid random commitEntry
AssertionError: expected 'Author: Reynold71 <Reynold_Walsh57@ya…' to match /^Author: [\w_\. ]+ \<[\w\.]+@[\w\.]+\>$/
 ❯ test/git.spec.ts:62:30
     60|             expect(parts[5]).toMatch(/^\s{4}.+$/);
     61|           } else {
     62|             expect(parts[1]).toMatch(/^Author: [\w_\. ]+ \<[\w\.]+@[\w\.]+\>$/);
       |                              ^
     63|             expect(parts[2]).toMatch(/^Date: .+$/);
     64|             expect(parts[3]).toBe('');
```

It might be somewhat related to #2448
But there is no expected vs actual comparison/diff, so it's harder here to find the problem of the failing test

### Reproduction

will add if really needed

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 3.49 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.4.0 - ~/.nvm/versions/node/v18.4.0/bin/node
    npm: 8.12.1 - ~/.nvm/versions/node/v18.4.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 16.2
  npmPackages:
    @vitest/coverage-c8: ~0.28.3 => 0.28.3 
    @vitest/ui: ~0.28.3 => 0.28.3 
    vite: ~4.0.4 => 4.0.4 
    vitest: ~0.28.3 => 0.28.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`AssertionError` is always truncated, it's meant to be a short message. You should see expected/actual for the diff.

**Comment by ST-DDT** [comment]
As shown here it is not:

![](https://user-images.githubusercontent.com/1579362/216149536-5fe6aec3-0ce6-41d1-a360-d3f555088f42.png)

**Comment by sheremet-va** [comment]
But I think you can change it with this code:

```ts
import { chai } from 'vitest'
chai.config.truncateThreshold = 100000
```

We might need to add to the config or reuse another truncate flag.

**Comment by Shinigami92** [comment]
> But I think you can change it with this code:
> 
> ```ts
> import { chai } from 'vitest'
> chai.config.truncateThreshold = 100000
> ```
> 
> We might need to add to the config or reuse another truncate flag.

Yes, looks like this is working :+1:

I still would love to have a vitest config pass-through option for that

Maybe even:
```ts
export default defineConfig({
  test: {
    coverage: {
      all: true,
      // ...
    },
    reporters: 'basic',
    // ...
    chaiConfig: {
      truncateThreshold: 10000,
    }
  },
});
```
