### ISSUE TITLE
`UserConfigExport['coverage']['provider']` with a object option did not work at all

### ISSUE THREAD

**Issue by mmis1000** [vitest-dev/vitest#2797]
### Describe the bug

When you defined setting as following

```
const CoverageModule = {
  getProvider: () => { throw 'called' }
}
export default defineConfig({
  test: {
    coverage: {
      provider: CoverageModule
    }
  }
})
```

It always say your provider is `c8`

Note: it is a bug in https://github.com/vitest-dev/vitest/blob/482b72fc5f02da87498a18e0ed844ecb6bc772ca/packages/vitest/src/utils/base.ts#L93-L98

Condition here do no check for `isMergeableObject(target[key])` .
With in this case, cause `deepMerge({ provider: 'c8' }, { provider: CoverageModule })` to result in `{ provider: 'c8' }`

Yet another note:

It would still crash even this fixed because it is unable to send this object to other worker.
This option should probably not be the module instance at first place.

![圖片](https://user-images.githubusercontent.com/2993977/216568578-98d1221f-51f6-4179-ba5a-b486d9204280.png)

Yet Yet another note:

It seems worker is used even I run it with `vitest run --no-threads --coverage --no-isolate`, this can not be right...

### Reproduction

Run `npx vitest --run --coverage` in https://stackblitz.com/edit/vitest-dev-vitest-x4h2tg?file=vite.config.ts

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitest/ui: latest => 0.28.3 
    vite: latest => 4.1.1 
    vitest: latest => 0.28.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Custom coverage providers have been broken for a while. 🙃 
I've planned to track this bug for a while but other things got priority.

> Condition here do no check for ` isMergeableObject(target[key])`

In addition to this bug there is another issue where either Tinypool or brpc throws `DataClone` errors. I haven't debugged that any further, yet.

**Comment by sheremet-va** [comment]
> In addition to this bug there is another issue where either Tinypool or brpc throws DataClone errors. I haven't debugged that any further, yet.

It will throw this error if `ctx.getSerializableConfig` will contain a function.

**Comment by AriPerkkio** [comment]
@mmis1000 following seems to work on the reproduction case:

```ts
import { defineConfig } from 'vitest/config';
import { CoverageProvider, CoverageProviderModule } from 'vitest';

class CoverageModule implements CoverageProviderModule {
  getProvider(): CoverageProvider {
    throw 'called';
  }
};
export default defineConfig({
  test: {
    coverage: {
      enabled: true,
      provider: new CoverageModule(),
    },
  },
});
```

```
❯ npm test
$ vitest
called
```

I'm not sure when exactly this has been fixed - by accident. I've had some tests for custom reporters in separate feature branch and earlier those were not working at all. Now they seem to run nicely. I'll set up PR for those tests later. 

Here's some draft for reference:

<details>
  <summary>custom-coverage-provider.ts</summary>

```ts
import type { CoverageProvider, CoverageProviderModule, ResolvedCoverageOptions, Vitest } from 'vitest'

class CustomCoverageProvider implements CoverageProvider {
  name = 'custom-coverage-provider'

  ctx!: Vitest
  options!: ResolvedCoverageOptions

  initialize(ctx: Vitest) {
    this.ctx = ctx
    this.options = {} as ResolvedCoverageOptions
  }

  clean() {
    console.log('CustomProvider::clean')
  }

  onBeforeFilesRun() {
    console.log('CustomProvider::onBeforeFilesRun')
  }

  onAfterSuiteRun() {
    console.log('CustomProvider::onAfterSuiteRun')
  }

  reportCoverage() {
    console.log('CustomProvider::reportCoverage')
  }

  onFileTransform() {
    console.log('CustomProvider::onFileTransform')
  }

  resolveOptions() {
    return this.options
  }
}

export default class CustomCoverageProviderModule implements CoverageProviderModule {
  getProvider(): CoverageProvider {
    return new CustomCoverageProvider()
  }

  takeCoverage() {}
}
```

</details>


<details>
  <summary>vitest.config.ts</summary>

```ts
import { defineConfig } from 'vitest/config'
import CustomCoverageProviderModule from './custom-coverage-provider'

export default defineConfig({
  test: {
    coverage: {
      enabled: true,
      provider: new CustomCoverageProviderModule(),
    },
  },
})
```

</details>


```sh
$ pnpm test

CustomProvider::clean

 RUN  v0.28.4 /Users/x/y/vitest/test/coverage-test
      Coverage enabled with custom-coverage-provider

CustomProvider::onBeforeFilesRun
CustomProvider::onFileTransform
CustomProvider::onFileTransform
...

 Test Files  3 passed (3)
      Tests  7 passed (7)
   Start at  12:03:47
   Duration  410ms (transform 159ms, setup 15ms, collect 133ms, tests 20ms)

 % Coverage report from custom-coverage-provider
CustomProvider::reportCoverage
```

**Comment by mmis1000** [comment]
> @mmis1000 following seems to work on the reproduction case:
> 
> ```ts
> import { defineConfig } from 'vitest/config';
> import { CoverageProvider, CoverageProviderModule } from 'vitest';
> 
> class CoverageModule implements CoverageProviderModule {
>   getProvider(): CoverageProvider {
>     throw 'called';
>   }
> };
> export default defineConfig({
>   test: {
>     coverage: {
>       enabled: true,
>       provider: new CoverageModule(),
>     },
>   },
> });
> ```
> 
> ```
> ❯ npm test
> $ vitest
> called
> ```
> 
> I'm not sure when exactly this has been fixed - by accident. I've had some tests for custom reporters in separate feature branch and earlier those were not working at all. Now they seem to run nicely. I'll set up PR for those tests later.
> 
> Here's some draft for reference:
> custom-coverage-provider.ts
> vitest.config.ts
> 
> ```shell
> $ pnpm test
> 
> CustomProvider::clean
> 
>  RUN  v0.28.4 /Users/x/y/vitest/test/coverage-test
>       Coverage enabled with custom-coverage-provider
> 
> CustomProvider::onBeforeFilesRun
> CustomProvider::onFileTransform
> CustomProvider::onFileTransform
> ...
> 
>  Test Files  3 passed (3)
>       Tests  7 passed (7)
>    Start at  12:03:47
>    Duration  410ms (transform 159ms, setup 15ms, collect 133ms, tests 20ms)
> 
>  % Coverage report from custom-coverage-provider
> CustomProvider::reportCoverage
> ```

It seems to work because the `enabled` is hardcoded in config? So it does not trigger the buggy path in `deepMerge` util. The config has a default value of `{ enabled: true, provider: 'v8' }` when '--coverage' is written in cli options

**Comment by AriPerkkio** [comment]
Well, there still seems to be a problem when custom provider is used in worker. `takeCoverage` here will be `undefined` as `options.provider` cannot be passed in `WorkerData` since it's not serializable.

https://github.com/vitest-dev/vitest/blob/aa1aa4daa268053bb2c93fefecb8d686ae8ad0ca/packages/vitest/src/integrations/coverage.ts#L29-L34

> This option should probably not be the module instance at first place.

Is there any other option than to change the API for custom providers to be a path where the provider can be loaded from? Then it could be loaded and initialized inside worker.

**Comment by mmis1000** [comment]
> Well, there still seems to be a problem when custom provider is used in worker. `takeCoverage` here will be `undefined` as `options.provider` cannot be passed in `WorkerData` since it's not serializable.
> 
> https://github.com/vitest-dev/vitest/blob/aa1aa4daa268053bb2c93fefecb8d686ae8ad0ca/packages/vitest/src/integrations/coverage.ts#L29-L34
> 
> > This option should probably not be the module instance at first place.
> 
> Is there any other option than to change the API for custom providers to be a path where the provider can be loaded from? Then it could be loaded and initialized inside worker.

I am not sure if the `use path / module name` option even work with typescript file. Does vite-node ever support random string user provided in `import(identifier)`?

Another idea would be use the `vite.config.ts` as input source. And just load the config again there. Then you can get a copy of whatever function user import in main compiler. But I will break any provider that relies on a singleton instance. (Guess it should be fine because the `c8-provider` and `istabul-provider` also have multi instance.

**Comment by sheremet-va** [comment]
> Is there any other option than to change the API for custom providers to be a path where the provider can be loaded from? Then it could be loaded and initialized inside worker.

If you need to use it inside a worker, it should be a path to the module that will be imported inside. Beware that it will always be two different instances.

**Comment by AriPerkkio** [comment]
Inside workers we can safely create/import instances of **CoverageProviderModules**. The `takeCoverageInsideWorker` is explicitly created for this. 

> I am not sure if the `use path / module name` option even work with typescript file. Does vite-node ever support random string user provided in `import(identifier)`?

Currently Vitest supports regular test reporters to be written in Typescript, loaded here:

https://github.com/vitest-dev/vitest/blob/aa1aa4daa268053bb2c93fefecb8d686ae8ad0ca/packages/vitest/src/node/reporters/utils.ts#L8-L11

Now that CoverageProviderModule needs to be imported inside worker while running in `vite-node`, I'm not sure how to do this. 
@sheremet-va any pointers how to import Typescript files in `src/runtime/entry.ts`?

I think that one is started from here?
https://github.com/vitest-dev/vitest/blob/aa1aa4daa268053bb2c93fefecb8d686ae8ad0ca/packages/vitest/src/runtime/worker.ts#L48-L51
