### ISSUE TITLE
Differences in typing for `css` field in docs and the typing file.

### ISSUE THREAD

**Issue by Magiczne** [vitest-dev/vitest#2798]
### Describe the bug

The documentation states that `css` option is `boolean | { include?, exclude?, modules? }`.

But the typings in the `index.d.ts` statees that the actual type is: `css?: CSSOptions;`

### Reproduction

I'm pretty sure not needed.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
    Memory: 13.24 GB / 15.43 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.10.0 - ~/.nvm/versions/node/v18.10.0/bin/node
    Yarn: 3.2.4 - /mnt/c/Program Files/nodejs/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.10.0/bin/npm
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0
    @vitest/coverage-c8: ^0.28.3 => 0.28.3
    @vitest/ui: ^0.28.4 => 0.28.4
    vite: ^4.1.1 => 4.1.1
    vitest: ^0.28.3 => 0.28.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> The documentation states that css option is boolean | { include?, exclude?, modules? }.

Documentation only describes `test` options on the config. All other options are covered by Vite documentation.
