### ISSUE TITLE
Run related tests based on list of source files

### ISSUE THREAD

**Issue by privatenumber** [vitest-dev/vitest#280]
### Clear and concise description of the problem

I use jest with lint-staged + husky so that it only runs relevant tests on the commit hook.

For example: https://github.com/privatenumber/esbuild-loader/blob/be292fa98478590ad71ca01194866f720d3cf648/package.json#L36

Currently, since I can only run Vitest on the commit-hook (without lint-staged passing in changed files), it runs tests on every-change (including changes to just `package.json` or `README.md`).

### Suggested solution

Similarly to jest, a `--find-related-tests` flag that takes in a list of changed files.

### Additional context

Loving Vitest so far! Great work as always :)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I am working on this API 👀

**Comment by sheremet-va** [comment]
Released in [0.0.121](https://github.com/vitest-dev/vitest/releases/tag/v0.0.121)

**Comment by sheremet-va** [comment]
We use CAC as a CLI, so to pass several files, you would need to call vitest like this:

```
vitest --findRelatedTests src/timeout.ts --findRelatedTests src/mockedA.ts
```

Repeat for each file.

**Comment by privatenumber** [comment]
Thanks for the fast implementation!

Passing the changed files in like that might not meet my needs though because I believe [`lint-staged`](https://github.com/okonet/lint-staged) passes all staged files as a list after the command.

For example, this:
```json
{
  "*.js": "eslint --fix"
}
```

would yield `eslint --fix changed-file-a.js changed-file-b.js`.

Instead of treating `findRelatedTests` as a string flag, can it be a boolean flag that reads from CLI arguments if `findRelatedTests` is enabled?

**Comment by sheremet-va** [comment]
Should be in the next release. You can use command `related`:

```
vitest related src/A.ts src/B.ts
```

**Comment by privatenumber** [comment]
Nice API! Thank you @sheremet-va
