### ISSUE TITLE
test.each should pass TestContext to test function

### ISSUE THREAD

**Issue by oliverzy** [vitest-dev/vitest#2803]
### Clear and concise description of the problem

Currently it seems impossible to get test context in test function along with test.each.

### Suggested solution

Maybe we can attach it to “this” for test function

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Yes, it is mentioned in the documentation: https://vitest.dev/api/#test-each

**Comment by oliverzy** [comment]
Aha, glad to see it’s already supported. I just miss it, thanks
