### ISSUE TITLE
Jest compatibility API: expect.toHaveProperty does not support array index

### ISSUE THREAD

**Issue by trivikr** [vitest-dev/vitest#2804]
### Describe the bug

Jest compatibility API: expect.toHaveProperty does not support array index

### Jest
Succeeds in jest@29.4.1
```ts
const obj = { fruits: ["apple", "banana", "orange"] };

test("toHaveProperty", () => {
  expect(obj).toHaveProperty(["fruits", 0], "apple");
})
```
Docs: https://jestjs.io/docs/expect#tohavepropertykeypath-value

### Vitest
Fails with vitest@0.28.4
```ts
import { expect, test } from "vitest";

const obj = { fruits: ["apple", "banana", "orange"] };

test("toHaveProperty", () => {
  expect(obj).toHaveProperty(["fruits", 0], "apple");
})
```

Error thrown:
```console
$  FAIL  example.spec.js > toHaveProperty
TypeError: key.replace is not a function
 ❯ example.spec.js:6:15
      4| 
      5| test("toHaveProperty", () => {
      6|   expect(obj).toHaveProperty(["fruits", 0], "apple");
       |               ^
      7| })

```
Docs: https://vitest.dev/api/expect.html#tohaveproperty

### System Info

```shell
npmPackages:
    vitest: ^0.28.4 => 0.28.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by trivikr** [comment]
This issue was noticed while writing expect comparison tests in vitest-codemod
[trivikr/vitest-codemod@`8f89939` (#76)](https://github.com/trivikr/vitest-codemod/pull/76/commits/8f899396bedf5e959a8ac6ebd0054cd099d2cec8)

**Comment by sheremet-va** [comment]
Does it work with index as a string?

**Comment by trivikr** [comment]
> Does it work with index as a string?

It works with index as a string

```js
import { expect, test } from "vitest";

const obj = { fruits: ["apple", "banana", "orange"] };

test("toHaveProperty", () => {
  expect(obj).toHaveProperty(["fruits", "0"], "apple");
})
```

```console
 DEV  v0.28.4 /Users/trivikram/workspace/test

 ✓ example.spec.js (1)

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  08:53:40
   Duration  197ms (transform 45ms, setup 0ms, collect 5ms, tests 1ms)
```

**Comment by trivikr** [comment]
The bug is on line 283 of jest-expect.ts

https://github.com/vitest-dev/vitest/blob/aa1aa4daa268053bb2c93fefecb8d686ae8ad0ca/packages/expect/src/jest-expect.ts#L283

It assumes all values in the array are strings.

**Comment by trivikr** [comment]
One fix would be coercing key to [String primitive](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#string_primitives_and_string_objects) before running replace on it.

```ts
 args[0] = args[0].map(key => String(key).replace(/([.[\]])/g, '\\$1')).join('.') 
```

**Comment by trivikr** [comment]
> One fix would be coercing key to [String primitive](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#string_primitives_and_string_objects) before running replace on it.

Example fix posted at https://github.com/vitest-dev/vitest/pull/2808
