### ISSUE TITLE
`Cannot destructure property 'AsymmetricMatcher'` with `deps.inline: true`

### ISSUE THREAD

**Issue by Leksat** [vitest-dev/vitest#2806]
### Describe the bug

I found that tests are broken after upgrading `vitest` from 0.27.1 to 0.28.4

```
% pnpm test

> test@ test /Users/alex/work/vitest-AsymmetricMatcher-issue
> vitest run --passWithNoTests


 RUN  v0.28.4 /Users/alex/work/vitest-AsymmetricMatcher-issue


 Test Files  no tests
      Tests  no tests
   Start at  15:04:47
   Duration  794ms (transform 242ms, setup 0ms, collect 0ms, tests 0ms)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: Cannot destructure property 'AsymmetricMatcher' of '__vite_ssr_import_0__.plugins' as it is undefined.
 ❯ node_modules/.pnpm/@vitest+utils@0.28.4/node_modules/@vitest/utils/dist/index.js:22:3
     20|   AsymmetricMatcher
     21| ];
     22| function stringify(object, maxDepth = 10, { maxLength, ...options } = {}) {
       |   ^
     23|   const MAX_LENGTH = maxLength ?? 1e4;
     24|   let result;
 ❯ VitestRunner.directRequest node_modules/.pnpm/vite-node@0.28.4_@types+node@18.11.18/node_modules/vite-node/dist/client.mjs:312:5
 ❯ VitestRunner.cachedRequest node_modules/.pnpm/vite-node@0.28.4_@types+node@18.11.18/node_modules/vite-node/dist/client.mjs:156:14
 ❯ VitestRunner.dependencyRequest node_modules/.pnpm/vite-node@0.28.4_@types+node@18.11.18/node_modules/vite-node/dist/client.mjs:204:14
 ❯ async /Users/alex/work/vitest-AsymmetricMatcher-issue/node_modules/.pnpm/@vitest+runner@0.28.4/node_modules/@vitest/runner/dist/index.js:3:31
 ❯ VitestRunner.directRequest node_modules/.pnpm/vite-node@0.28.4_@types+node@18.11.18/node_modules/vite-node/dist/client.mjs:312:5
 ❯ VitestRunner.cachedRequest node_modules/.pnpm/vite-node@0.28.4_@types+node@18.11.18/node_modules/vite-node/dist/client.mjs:156:14
 ❯ VitestRunner.dependencyRequest node_modules/.pnpm/vite-node@0.28.4_@types+node@18.11.18/node_modules/vite-node/dist/client.mjs:204:14
 ❯ async /Users/alex/work/vitest-AsymmetricMatcher-issue/node_modules/.pnpm/vitest@0.28.4/node_modules/vitest/dist/entry.js:5:31
 ❯ VitestRunner.directRequest node_modules/.pnpm/vite-node@0.28.4_@types+node@18.11.18/node_modules/vite-node/dist/client.mjs:312:5

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
 ELIFECYCLE  Test failed. See above for more details.
```

The error is gone if I comment out the `deps.inline` setting: https://github.com/Leksat/vitest-AsymmetricMatcher-issue/blob/3d77d1d5e4b1e86f49e314234db835656388b0f6/vite.config.ts#L8

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-6a5vwn?file=vite.config.ts (I just added `deps.inline: true` to the standard example)

Or a minimal reproduction:

```
git clone git@github.com:Leksat/vitest-AsymmetricMatcher-issue.git
cd vitest-AsymmetricMatcher-issue
pnpm i
pnpm test
```

### System Info

```shell
% npx envinfo --system --npmPackages '{vitest,@vitest/*,vite,@vitejs/*}' --binaries --browsers

  System:
    OS: macOS 13.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 110.18 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Safari: 16.3
  npmPackages:
    vite: 4.1.1 => 4.1.1
    vitest: 0.28.4 => 0.28.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by treardon17** [comment]
I also have this issue when setting it to `true`, but using an array of packages to inline seems to work. I know that might not fit every use case, but it resolved my issue.

ex:
```javascript
{
  deps: {
    inline: ['vuetify']
  }
}
```

**Comment by Vithanco** [comment]
+1

**Comment by Leksat** [comment]
Found a workaround: inline everything except for vitest deps.
```ts
  test: {
    deps: {
      inline:
        // TODO: Replace with true once https://github.com/vitest-dev/vitest/issues/2806 is fixed.
        [/^(?!.*vitest).*$/],
    },
  },
```

**Comment by Vithanco** [comment]
Actually, I just commented the whole inline out and it works. 
```
  test: {
    // deps: {
    //   inline: true
    // }
  },
```

**Comment by natew** [comment]
Tamagui monorepo stuck on 0.27 due to this, you can pretty easily clone and `yarn up vitest` and then `yarn test` to replicate:

https://github.com/tamagui/tamagui

**Comment by Tanimodori** [comment]
I've tested this issue with various vitest releases and find out that 0.27.3 works while 0.28.0 doesn't. The only possible change made between them is the merge of #2721 done in 482b72fc5f02da87498a18e0ed844ecb6bc772ca , which:

* moves test runner into a separate package
* stops shipping @vitest/* packages along with Vitest
* allows disabling auto inlining of the Vitest package

But the default inlining conifg of `inline: true` doesn't updates with this merge:

https://github.com/vitest-dev/vitest/blob/baf902a20b5fdedc095828c081a32ce2baeb2197/packages/vitest/src/node/config.ts#L15-L22

It should add @vitest/* packages when inlining as @Leksat said:

```diff
const extraInlineDeps = [
  /^(?!.*(?:node_modules)).*\.mjs$/,
  /^(?!.*(?:node_modules)).*\.cjs\.js$/,
  // Vite client
  /vite\w*\/dist\/client\/env.mjs/,
  // Nuxt
  '@nuxt/test-utils',
+  // @vitest packages due to #2721
+  [/^(?!.*vitest).*$/],
]
```

**Comment by sheremet-va** [comment]
> Maybe this regex is too board and need to be narrowed down, but the smoking gun of this issue is here.

I disagree. It should not be needed to inline Vitest at all.

It should not be needed to inline any dependency to be honest. One of the reason why it takes to long to fix is because we will introduce another way to fix dependency issues and this usage of inline will probably be deprecated.

The fact that we allow true as a value was just to align with Vite‘s noExternal and should probably never be actually used.

**Comment by Tanimodori** [comment]
@sheremet-va Sorry for my misunderstanding. So I reorganized timeline which appears to be:

- `deps.inline` is introduced to solve esm-only script issues.
- #2721 is introduced. `inline: true` no longer works as stated above.
- `deps.inline` changed the default to `[]`.
- We will find another way to solve esm script issue so `deps.inline` may become deprecated then.

**Comment by sheremet-va** [comment]
Please, consider using `deps.experimentalOptimizer` instead of `deps.inline`.

`deps.inline` will be deprecated in future versions and will not be shipped in Vitest 1.0.

**Comment by danielroe** [comment]
@sheremet-va We currently need to perform transforms on code within `node_modules` when using `vitest` with Nuxt. (For example, some of the code shipped within `node_modules` is 'runtime' code that references build-time aliases.) What's the best way to configure this using the new `experimentalOptimizer`?

**Comment by sheremet-va** [comment]
> @sheremet-va We currently need to perform transforms on code within `node_modules` when using `vitest` with Nuxt. (For example, some of the code shipped within `node_modules` is 'runtime' code that references build-time aliases.) What's the best way to configure this using the new `experimentalOptimizer`?

optimizer inherits options from `optimizeDeps`, so if it's already there it should work out of the box. But instead of crawling imports, it optimizes _only_ dependencies inside `experimentalOptimizer.include` or `optimizeDeps.include`.

**Comment by danielroe** [comment]
@sheremet-va With 0.32.0, `vitest-environment-nuxt` now fails on imports from virtual files.

I haven't yet dived in to see what the issue is, but it feels like it might be related (?).

**Comment by sheremet-va** [comment]
> fails on imports from virtual files

Do you use `deps.inline: true`?

Your issues is probably because of this: https://github.com/vitest-dev/vitest/pull/3544

**Comment by ant-dep** [comment]
I got TypeError: Unknown file extension ".css for ...node_modules\@react-spectrum\actiongroup\dist\main.css" when running tests that import a component that is importing "@adobe/react-spectrum"

deps.inline doesn't work and I'm almost losing faith after multiple hours of trying either to exclude or inlude this dependency

**Comment by sheremet-va** [comment]
> deps.inline doesn't work and I'm almost losing faith after multiple hours of trying either to exclude or inlude this dependency

`deps.inline` is a simple filepath check. In your case, to include a file, you need to add `@react-spectrum/actiongroup`

**Comment by ant-dep** [comment]
Where do I need to add this ?

**Comment by ant-dep** [comment]
Update: I removed @react-spectrum and change my InputDate with native function. Problem fixed :)

**Comment by mattiaz9** [comment]
I don't use the `inline` option but i still get the error: `Cannot destructure property 'AsymmetricMatcher' of '__vite_ssr_import_0__.plugins' as it is undefined.`

I tried using this trick but it didn't work for me:
```js
  {
    deps: {
      inline:
        // TODO: Replace with true once https://github.com/vitest-dev/vitest/issues/2806 is fixed.
        [/^(?!.*vitest).*$/],
    },
  },
```

I'm not sure if this could be related but I only noticed this error after switching to an Apple Silicon Mac

**Comment by davidmyersdev** [comment]
This can also happen when using the `ssr.noExternal` option in Vite. The following config produced the above error.

```ts
export default defineConfig({
  ssr: {
    noExternal: /.*/,
  },
})
```

I was able to fix it by excluding Vite:

```ts
export default defineConfig({
  ssr: {
    noExternal: /^(?!.*\/vitest\/).*$/,
  },
})
```
