### ISSUE TITLE
Jest compatibility API: mock.contexts is not supported

### ISSUE THREAD

**Issue by trivikr** [vitest-dev/vitest#2810]
### Clear and concise description of the problem

Jest added support for testing function context ("this") in Mock functions in jest@28.x
PR https://github.com/facebook/jest/issues/11235

Docs: https://jestjs.io/docs/mock-function-api#mockfnmockcontexts

It would be useful to have this in vitest too.

### Suggested solution

mock.context is added in vitest, so that the following test code can be written

```js
test("contexts", () => {
  const mockFn = vi.fn();
  expect(mockFn.mock.contexts).toHaveLength(0);

  const bindContext = { x : 1 };
  const boundMockFn = mockFn.bind(bindContext);
  boundMockFn();
  expect(mockFn.mock.contexts).toHaveLength(1);
  expect(mockFn.mock.contexts[0]).toBe(bindContext);

  const callContext = { x : 2 };
  mockFn.call(callContext);
  expect(mockFn.mock.contexts).toHaveLength(2);
  expect(mockFn.mock.contexts[1]).toBe(callContext);

  const applyContext = { x : 3 };
  mockFn.apply(applyContext);
  expect(mockFn.mock.contexts).toHaveLength(3);
  expect(mockFn.mock.contexts[2]).toBe(applyContext);
})
```

### Alternative

Skip adding the support for context.

### Additional context

This issue was noticed while adding support for transformation of jest to vi API in https://github.com/trivikr/vitest-codemod/pull/80

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Looking at the implementation, I'm not sure what is the difference between `instances`? https://github.com/facebook/jest/pull/12601/files#diff-7ae0bd704c3c2789b19abe2bbf94aca3505e2a6b3823d85c7f6b316b216d37c9R644

**Comment by sheremet-va** [comment]
The keyword is `implementation `. They both contain the same values.

**Comment by trivikr** [comment]
> They both contain the same values.

You're right. They both contain same values.

I verified with jest@29.4.1

<details>
<summary>contexts</summary>

```js
test("contexts", () => {
  const mockFn = jest.fn();
  expect(mockFn.mock.contexts).toHaveLength(0);

  const bindContext = { x: 1 };
  const boundMockFn = mockFn.bind(bindContext);
  boundMockFn();
  expect(mockFn.mock.contexts).toHaveLength(1);
  expect(mockFn.mock.contexts[0]).toBe(bindContext);
  expect(mockFn.mock.instances[0]).toBe(bindContext);

  const callContext = { x: 2 };
  mockFn.call(callContext);
  expect(mockFn.mock.contexts).toHaveLength(2);
  expect(mockFn.mock.contexts[1]).toBe(callContext);
  expect(mockFn.mock.instances[1]).toBe(callContext);

  const applyContext = { x: 3 };
  mockFn.apply(applyContext);
  expect(mockFn.mock.contexts).toHaveLength(3);
  expect(mockFn.mock.contexts[2]).toBe(applyContext);
  expect(mockFn.mock.instances[2]).toBe(applyContext);
});
```

</details>

<details>
<summary>instances</summary>

```js
test("instances", () => {
  const mockFn = jest.fn();
  expect(mockFn.mock.instances).toHaveLength(0);

  const a = new mockFn();
  expect(mockFn.mock.instances).toHaveLength(1);
  expect(mockFn.mock.instances[0]).toBe(a);
  expect(mockFn.mock.contexts[0]).toBe(a);

  const b = new mockFn();
  expect(mockFn.mock.instances).toHaveLength(2);
  expect(mockFn.mock.instances[1]).toBe(b);
  expect(mockFn.mock.contexts[1]).toBe(b);
});

```

</details>

**Comment by trivikr** [comment]
The [feature proposal for context](https://github.com/facebook/jest/issues/11235) stated the following:

> It is [currently possible](https://stackoverflow.com/a/52031787/) to test the context with mock.instances, but this doesn't seem to be the intended purpose. According to the [docs](https://jestjs.io/docs/mock-function-api#mockfnmockinstances) mock.instances seems class-related:
>
> > An array that contains all the object instances that have been instantiated from this mock function using new.

**Comment by trivikr** [comment]
There's a bug in `instances` implementation

I posted a bug report at https://github.com/vitest-dev/vitest/issues/2821

**Comment by trivikr** [comment]
The suggestion as of 2023-02-14 is to count `contexts` and `instances` in tinyspy
Refer: https://github.com/tinylibs/tinyspy/issues/29#issuecomment-1430623842
