### ISSUE TITLE
Error when testing through a dependency

### ISSUE THREAD

**Issue by Nojin-dev** [vitest-dev/vitest#2811]
### Describe the bug

"vite": "^4.0.0",
"vitest": "^0.28.4"

HI,

I have a custom library with a dependency on "@reduxjs/toolkit", all tests are successful when testing it. However when I import this library in my app, tests don't pass anymore and I get the following error:

“SyntaxError: Named export 'configureStore' not found. The requested module '@reduxjs/toolkit' is a CommonJS module.”

Context:
- Build library in ESnext
- Library's dependencies aren't included in the build, but resolved through peer dependencies (from the app)
- The app dev/build/preview passes without any problem

I would greatly appreciate any assistance in resolving this issue.

Thank you,

### Reproduction

https://stackblitz.com/edit/vitejs-vite-xrbesw?file=readme.md

### System Info

```shell
### App shell

> pnpm run test


SyntaxError: Named export 'configureStore' not found. The requested module '@reduxjs/toolkit' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@reduxjs/toolkit';
const { configureStore: e } = pkg;


### Lib shell

> pnpm run test

```shell
Test Files  1 passed (1)
```
```


### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You need to inline your dependency (`deps.inline`), or bundle it the way Node wants (don't use named imports on `@redux/toolkit`, since this library cannot be used with named exports inside Node.js).

**Comment by Nojin-dev** [comment]
Hi Sheremet-va
Tks for the feedback. It work on the provided example and also on a more complex use case !

**Comment by rizaldirnm** [comment]
Did you have find solution? @Nojin-dev
