### ISSUE TITLE
Jest compatibility API: mockFn.withImplementation API

### ISSUE THREAD

**Issue by trivikr** [vitest-dev/vitest#2812]
### Clear and concise description of the problem

Jest added mockFn.withImplementation API in v29.1.0
* PR: https://github.com/facebook/jest/pull/13281
* Docs: https://jestjs.io/docs/mock-function-api#mockfnwithimplementationfn-callback

It accepts a function which should be temporarily used as the implementation of the mock while the callback is being executed.

### Suggested solution

Add this API to vitest, if maintainers think it would be helpful to it's users.

### Alternative

Document how `mockImplementation` or `mockImplementationOnce` can be used in these use cases

### Additional context

This issue was noticed while writing vitest-codemod tests for mock API
https://github.com/trivikr/vitest-codemod/pull/80

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by mysteryven** [comment]
I'd like to take this 😀

**Comment by obadakhalili** [comment]
> I'd like to take this PR

I'm sorry @mysteryven but I have already opened a [PR for this](https://github.com/vitest-dev/vitest/pull/2835). I probably should have commented before doing so, but it is my first contribution and I didn't want to make any promises that I might not be able to keep 😅.

Again, sorry for the confusion.

**Comment by trivikr** [comment]
> I'd like to take this PR😀

@mysteryven Thank you for your interest.

I'd created multiple issues with vitest.
You can take https://github.com/vitest-dev/vitest/issues/2831 if you're interested, for example.

Maintainers haven't added `enhancement` label to it yet, but I think they would looking at other compatibility feature requests.

**Comment by mysteryven** [comment]
> Again, sorry for the confusion.

Never mind ! 😛 @obadakhalili 

I am sorry I didn't check the notifications yesterday, I pull my request to my fork for a better commit preview, I will be really happy if it can help you : [with implementation](https://github.com/mysteryven/vitest/pull/5)
