### ISSUE TITLE
Resolution error on export star with .js pointing to .tsx

### ISSUE THREAD

**Issue by itsMapleLeaf** [vitest-dev/vitest#282]
### Describe the bug

When writing an `export * from './file.js'` that points to a `file.tsx` file, there's a resolution error. It seems to work fine with .ts files, just not .tsx. .js extensions are needed when writing code for native ES modules.

### Reproduction

https://stackblitz.com/github/itsMapleLeaf/vitest-export-star-extension

### System Info

```shell
System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 1.82 GB / 15.63 GB
    Container: Yes
    Shell: 3.3.1 - /bin/fish
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Firefox: 95.0.1
  npmPackages:
    vite: ^2.7.6 => 2.7.6 
    vitest: ^0.0.108 => 0.0.108 
```
```


### Used Package Manager

pnpm

### Logs

```shell
- export.test.ts
Error: Failed to resolve import "./component.js" from "test/export.ts". Does the file exist?
 ❯ formatError node_modules/vite/dist/node/chunks/dep-fcec4469.js:42631:46
 ❯ TransformContext.error node_modules/vite/dist/node/chunks/dep-fcec4469.js:42627:19
 ❯ normalizeUrl node_modules/vite/dist/node/chunks/dep-fcec4469.js:81365:26
 ❯ async TransformContext.transform node_modules/vite/dist/node/chunks/dep-fcec4469.js:81505:57
 ❯ async Object.transform node_modules/vite/dist/node/chunks/dep-fcec4469.js:42847:30
 ❯ async doTransform node_modules/vite/dist/node/chunks/dep-fcec4469.js:57918:29
```
```


### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It works if I don't specify extenstion at all. I think this is how Vite module resolution work?

This is a wierd case. Can you give a useful usecase fo this where it works?

**Comment by itsMapleLeaf** [comment]
Actually, I just realized this may be correct behavior :thinking:

To elaborate further, when targeting native ES modules, [file extensions are required](https://nodejs.org/api/esm.html#mandatory-file-extensions) and [TypeScript is firm on not rewriting import sources](https://github.com/Microsoft/TypeScript/issues/16577#issuecomment-754941937), therefore, you need to write the file extensions in your typescript sources as they would be in the compiled output: with JS extensions.

However, the `.tsx` extension is meant to mirror the `.jsx` extension, so I think the correct approach here would be to write `export * from './file.jsx'`, which _does_ work. So I think this issue is invalid

> Can you give a useful usecase fo this where it works?

The use case is for writing portable imports, e.g. if I decide I _don't_ want to bundle my source files, and/or I want to target the browser or deno

**Comment by sheremet-va** [comment]
Closing, since it works with jsx.

If you think it's incorrect, we can try dug deeper.
