### ISSUE TITLE
Unable to update inline snapshots when `vi.mock` is used

### ISSUE THREAD

**Issue by aethr** [vitest-dev/vitest#2822]
### Describe the bug

`vitest` is unable to update inline snapshots when the spec uses `vi.mock`, ie:

```js
import { expect, it, vi } from 'vitest';

vi.mock('vue');

it('updates inline snapshot', () => {
    expect('a').toMatchInlineSnapshot('"b"');
});
```
Trying to update the snapshot in watch mode or using `-u` on the CLI results in the error `Error: EISDIR: illegal operation on a directory, read`:

```sh
$ npm run test -- -u run with-mock

> vitest-snapshot-update@1.0.0 test
> vitest "-u" "run" "with-mock"


 RUN  v0.28.4 /home/linds/Code/vitest-snapshot-update

 · with-mock.spec.js (1)

 Test Files   (1)
      Tests   (1)
   Start at  17:20:26
   Duration  655ms (transform 85ms, setup 0ms, collect 12ms, tests 0ms)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: EISDIR: illegal operation on a directory, read
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
```

Removing the call to `vi.mock` solves the issue:
```js
import { expect, it } from 'vitest';

it('updates inline snapshot', () => {
    expect('a').toMatchInlineSnapshot('"b"');
});
```

This has been an issue for as long as we've used `vitest`, although I only recently discovered that `vi.mock` was the cause.

This also may only be an issue on linux, as I have co-workers on Mac who haven't run into this issue in our codebase.

### Reproduction

- clone https://github.com/aethr/vitest-snapshot-update
- `npm ci`
- `npm run test -- -u run no-mock` # success
- `npm run test -- -u run with-mock` # error

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.59 GB / 30.98 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
  npmPackages:
    vitest: ^0.28.4 => 0.28.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aethr** [comment]
I should mention that I tried to reproduce this in StackBlitz and did not encounter the same error. Everything seemed to work as expected.

https://stackblitz.com/edit/vitest-dev-vitest-xakg2t

**Comment by jack-green** [comment]
I can re-create the issue with the repo locally:

envinfo:
```
System:
    OS: macOS 13.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 66.85 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 108.0
    Safari: 16.1
```

test result:

```
% npm run test -- -u run with-mock

> vitest-snapshot-update@1.0.0 test
> vitest -u run with-mock


 RUN  v0.28.4 /Users/XXXX/Experiments/vitest-snapshot-update

 · with-mock.spec.js (1)

 Test Files   (1)
      Tests   (1)
   Start at  09:01:17
   Duration  622ms (transform 112ms, setup 0ms, collect 14ms, tests 0ms)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: EISDIR: illegal operation on a directory, read
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
```

**Comment by sumcoding** [comment]
I am also seeing this issue when updating a project from jest to vitest. Current solution is to not do any snapshot testing in a file that also requires `vi.mock`. Not great, but was happy to at least find a work around. 

To add I am using a Mac, so I do not think its just a linux issue.

**Comment by sheremet-va** [comment]
This is fixed.
