### ISSUE TITLE
Mocking Modules breaks `instanceof` on Classes

### ISSUE THREAD

**Issue by Jason3S** [vitest-dev/vitest#2824]
### Describe the bug

I think there is a combination of things going on here.

Mocking of modules with classes works with tinyspy `1.0.2` but breaks with tinyspy `1.1.0`.

See: https://github.com/tinylibs/tinyspy/issues/32

Looks like the prototype chain isn't getting preserved.

```ts
import { afterEach, describe, expect, test, vi } from 'vitest';

import { MyClass } from './MyClass.js';
import { create, isMyClass } from './MyClassUtil.js';

vi.mock('./MyClass.js');

const mockedMyClass = vi.mocked(MyClass);

// class MockImplementationMyClass {
//     constructor(readonly name: string) {}
// }

// mockedMyClass.mockImplementation((name) => new MockImplementationMyClass(name));

describe('MyClass', () => {
  afterEach(() => {
    mockedMyClass.mockClear();
  });

  test.each`
    name          | expected
    ${'Atlantic'} | ${'Atlantic'}
    ${'Pacific'}  | ${'Pacific'}
  `('new MyClass $name', ({ name, expected }) => {
    const instance = create(name);
    expect(isMyClass(instance)).toBe(true);  // Breaks here
    expect(instance).toBeInstanceOf(MyClass); // And here
    expect(mockedMyClass).toHaveBeenCalledTimes(1);
    expect(mockedMyClass).toHaveBeenCalledWith(expected);
  });
});
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-dhhorq?file=README.md

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitest/ui: latest => 0.28.4 
    vite: ^4.1.1 => 4.1.1 
    vitest: ^0.26.3 => 0.26.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is fixed in https://github.com/tinylibs/tinyspy/issues/32
