### ISSUE TITLE
Jest compatibility API: replaceProperty

### ISSUE THREAD

**Issue by trivikr** [vitest-dev/vitest#2831]
### Clear and concise description of the problem

Jest introduced API `replaceProperty` in v29.4.0
* PR: https://github.com/facebook/jest/issues/13465
* Docs: https://jestjs.io/docs/jest-object#jestreplacepropertyobject-propertykey-value

This API is also available in sinon
https://sinonjs.org/releases/v14/sandbox/#sandboxreplaceobject-property-replacement

Example code tested with jest@29.4.2:
```js
test("replaceProperty", () => {
  expect(process.env.TEST_ENV_KEY).toBeUndefined();
  jest.replaceProperty(process, 'env', { TEST_ENV_KEY: "test" });  
  expect(process.env.TEST_ENV_KEY).toBe("test");
  jest.restoreAllMocks();
  expect(process.env.TEST_ENV_KEY).toBeUndefined();
});
```

### Suggested solution

Add `vi.replaceProprety` API

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by mysteryven** [comment]
Thanks for your mentioned, I'd like to take this when this PR adds the label !

**Comment by trivikr** [comment]
@sheremet-va Would `replaceProperty` API be helpful to vitest users?

If yes, can you add `enhancement` and `pr welcome` labels?
@mysteryven is interested in implementing it.

**Comment by sheremet-va** [comment]
I do like the API, but I don't like that `restoreAllMocks` affects it. We have a similar API with `stubs` for a global object (`stubGlobal`) and env (`stubEnv`) already. Do we need more?

**Comment by trivikr** [comment]
The APIs [vi.stubGlobal](https://vitest.dev/api/vi.html#vi-stubglobal) and [vi.stubEnv
](https://vitest.dev/api/vi.html#vi-stubenv) are better fit for this requirement.

I verified that those work:
```js
test("stubEnv", () => {
  expect(process.env.TEST_ENV_KEY).toBeUndefined();
  vi.stubEnv("TEST_ENV_KEY", "test");
  expect(process.env.TEST_ENV_KEY).toBe("test");
  vi.unstubAllEnvs();
  expect(process.env.TEST_ENV_KEY).toBeUndefined();
});

test("stubGlobal", () => {
  expect(global.innerWidth).toBeUndefined();

  const mockInnerWidth = 100;
  vi.stubGlobal("innerWidth", 100);
  expect(innerWidth).toBe(mockInnerWidth);
  expect(global.innerWidth).toBe(mockInnerWidth);

  vi.unstubAllGlobals();
  expect(global.innerWidth).toBeUndefined();
});
```

**Comment by trivikr** [comment]
@mysteryven As part of this request, can you add documentation in [migration guide](https://vitest.dev/guide/migration.html) calling out the difference with Jest?

**Comment by trivikr** [comment]
The vitest-codemod will transform replaceProperty with stubEnv for process.env

https://github.com/trivikr/vitest-codemod/issues/126
