### ISSUE TITLE
error with vi.mock('axios')

### ISSUE THREAD

**Issue by jerrywu001** [vitest-dev/vitest#284]
### Describe the bug

error with vi.mock('axios')

### Reproduction

https://stackblitz.com/edit/node-m7f8xj?file=test%2Faxios.test.ts

### System Info

```shell
System:
    OS: Linux undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: Unknown - /bin/jsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    vite: ^2.7.4 => 2.7.4 
    vitest: ^0.0.104 => 0.0.104
```

### Used Package Manager

npm

### Logs

```shell
- axios.test.ts
RangeError: Maximum call stack size exceeded
 ❯ eval node_modules/vitest/dist/entry.js:3973:28
 ❯ serializeError node_modules/vitest/dist/entry.js:3973:20
 ❯ eval node_modules/vitest/dist/entry.js:3974:16
 ❯ serializeError node_modules/vitest/dist/entry.js:3973:20
 ❯ eval node_modules/vitest/dist/entry.js:3974:16
 ❯ serializeError node_modules/vitest/dist/entry.js:3973:20
 ❯ eval node_modules/vitest/dist/entry.js:3974:16
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Uninen** [comment]
I'm running into this same issue. After the recent changes, the error changed from the `Maximum call stack size exceeded` to:

```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^
TypeError [Error]: listeners[i].apply is not a function
    at Socket.emit (node:events:402:35)
    at TCP.<anonymous> (node:net:687:12)
error Command failed with exit code 1.
```

Using Vite 2.7.7 and Vitest 0.0.118.

**Comment by sheremet-va** [comment]
should be fixed in the next release

**Comment by Uninen** [comment]
I get the same exact error message w/ Vitest v0.0.119.

**Comment by jerrywu001** [comment]
> I get the same exact error message w/ Vitest v0.0.119.
> 
> Nevermind -- I had deleted the `__mocks__`-folder. Mocking axios works w/ v0.0.119 when configured properly 👍

Still reporting errors （jsdom  happy-dom node）

**Comment by jerrywu001** [comment]
> I get the same exact error message w/ Vitest v0.0.119.
> 
> Nevermind -- I had deleted the `__mocks__`-folder. Mocking axios works w/ v0.0.119 when configured properly 👍

need __mocks__
