### ISSUE TITLE
`no test suite found` when using vitest from global pnpm

### ISSUE THREAD

**Issue by scarf005** [vitest-dev/vitest#2840]
### Describe the bug

`No test suite found` error will be raised when using vitest from global pnpm and asdf dependency manager.

related issues: #847 #2604
however the issue keeps coming back even after they are closed.

### Reproduction

due to the nature of the issue (global installation and asdf), minimal reproduction is provided in the form of shell script under docker.

1.  `docker run -it ubuntu /bin/bash` 
2. type along following commands:
```sh
apt-get update && apt-get install curl git -y

# intall asdf: https://asdf-vm.com/guide/getting-started.html
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.11.1
. ~/.asdf/asdf.sh

# install nodejs and pnpm
asdf plugin-add nodejs
asdf plugin-add pnpm
asdf install nodejs latest && asdf global nodejs latest
asdf install pnpm latest && asdf global pnpm latest

# setup pnpm
SHELL=/bin/bash pnpm setup
source /root/.bashrc

# install vitest globally
pnpm i -g vitest

# clone test repo
git clone https://github.com/zxch3n/vitest-ext-basic-example.git test
cd test
pnpm i

# make sure global vitest is used
which vitest #=> /root/.local/share/pnpm/vitest

# run vitest
vitest
```
which will result in:
```sh
root@c67ed93135ee:/test# vitest

 DEV  v0.28.4 /test

 ❯ add.test.ts (0)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  add.test.ts [ add.test.ts ]
Error: No test suite found in file /test/add.test.ts
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  no tests
   Start at  16:19:34
   Duration  382ms (transform 75ms, setup 0ms, collect 38ms, tests 0ms)


 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
```

### System Info
result of `pnpm exec envinfo --system --npmPackages '{vitest,@vitest/*,vite,@vitejs/*}' --binaries --browsers` from above docker container:
```shell
  System:
    OS: Linux 5.19 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 5600G with Radeon Graphics
    Memory: 17.93 GB / 30.70 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 19.6.0 - ~/.asdf/installs/nodejs/19.6.0/bin/node
    npm: 9.4.0 - ~/.asdf/plugins/nodejs/shims/npm
  npmPackages:
    vite: ^2.9.9 => 2.9.15 
    vitest: ^0.12.6 => 0.12.10
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest resolves twice, if you use it globally. It's always better to run vitest via node script (scripts field in package.json)

**Comment by FedericoBiccheddu** [comment]
I have the same problem even if I use a script from the `package.json`. Tests were working before, but all of a suddenly they stopped working.

Having the following test:
```ts
import { describe, it, expect } from 'vitest';

describe('sum test', () => {
	it('adds 1 + 2 to equal 3', () => {
		expect(1 + 2).toBe(3);
	});
});
```
and launching the following script `pnpm run test:watch`  which resolves to `vitest --config ./config/vitest.ts watch`:
```sh
 DEV  v0.28.4 /srv/app

 ❯ src/index.test.ts (0)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/index.test.ts [ src/index.test.ts ]
Error: No test suite found in file /srv/app/src/index.test.ts
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  no tests
   Start at  12:12:11
   Duration  2.91s (transform 2.02s, setup 0ms, collect 13ms, tests 0ms)
```


This is `vitest.ts`
```ts
import path from 'node:path'
import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    cache: {
      dir: path.resolve('var', 'cache', 'vitest')
    },
    coverage: {
      reportsDirectory: path.resolve('var', 'coverage')
    },
    include: [
      path.resolve('src', '**', '*.spec.ts'),
      path.resolve('src', '**', '*.test.ts'),
    ],
    watch: false,
  },
})
```

System Info (with `pnpm@7.27.0`):
```
  System:
    OS: Linux 5.15 Alpine Linux
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 10.62 GB / 15.57 GB
    Container: Yes
    Shell: 1.35.0 - /bin/ash
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
  npmPackages:
    @vitest/coverage-c8: 0.28.4 => 0.28.4 
    vitest: 0.28.4 => 0.28.4 
```

**Comment by FedericoBiccheddu** [comment]
Downgrading to `vitest@0.27.3` it works correctly.

**Comment by meduzen** [comment]
I confirm I have the same issue: I switched from npm to pnpm, and v0.27.3 is working while v0.28.x gives the same error.

My project runs Vitest through `package.json` / `scripts` (`"test": "vitest run"`).

**Comment by yarinsa** [comment]
Same here...

**Comment by bartektelec** [comment]
Im having the same problem with one particular test, 
I'm using `0.30.1` and I've tried downgrading to `0.27.3`, `0.28`, `0.29.1`, I also tried both `npm` and `pnpm`.

This only happens to a test where I'm trying to test a `zod` validator.
Eventhough the code is simple and I'm sure it works properly, the moment I try to assert the good answer it prompts "No test found in suite ...", but when I assert a wrong answer it will actually run the test and display what is wrong with it.

See attached screenshots

![image](https://user-images.githubusercontent.com/20260038/233779496-9b84d793-e456-459a-b57c-cf27cde5db30.png)
![image](https://user-images.githubusercontent.com/20260038/233779538-e8ac8a8c-5336-44e8-953a-888b53a868b2.png)

**Comment by sheremet-va** [comment]
> Im having the same problem with one particular test, I'm using `0.30.1` and I've tried downgrading to `0.27.3`, `0.28`, `0.29.1`, I also tried both `npm` and `pnpm`.
> 
> This only happens to a test where I'm trying to test a `zod` validator. Eventhough the code is simple and I'm sure it works properly, the moment I try to assert the good answer it prompts "No test found in suite ...", but when I assert a wrong answer it will actually run the test and display what is wrong with it.
> 
> This happens no matter which matcher I use
> 
> ```
> expect(r.name === 'example').toEqual(true);
> expect(r).toHaveProperty('name', 'example');
> expect(r.name).toEqual('example');
> expect(r.name).toBe('example');
> expect(r).toEqual({name: 'example', age: 69});
> ```
> 
> See attached screenshots
> 
> ![image](https://user-images.githubusercontent.com/20260038/233779496-9b84d793-e456-459a-b57c-cf27cde5db30.png) ![image](https://user-images.githubusercontent.com/20260038/233779538-e8ac8a8c-5336-44e8-953a-888b53a868b2.png)

Your tests should be inside „test“ or „it“ function to be considered tests.

**Comment by bartektelec** [comment]
Shoot that took me long time to try figure it out, thanks man 🙌

**Comment by space-nuko** [comment]
Same error but I want to upgrade vitest so I can fix https://github.com/vitest-dev/vitest/issues/3004, so I'm at a loss. Nothing changed about my tests, and even putting the minimal example in my test suite fails.

**Comment by sheremet-va** [comment]
> Same error but I want to upgrade vitest so I can fix #3004, so I'm at a loss. Nothing changed about my tests, and even putting the minimal example in my test suite fails. I run `vitest` in `package.json` script

Check you have the same version installed globally and inside a package

**Comment by space-nuko** [comment]
I didn't have `vitest` installed globally, installed it and same error. I'm on `0.31.0` and vite `4.3.1`, and use `pnpm` as my package manager everywhere

**Comment by sheremet-va** [comment]
In the next version, Vitest will fail if it encounters a different Vitest instance (for reference #3301).
