### ISSUE TITLE
Add flag to allow setup/teardown global commands to run between test runs in watch mode.

### ISSUE THREAD

**Issue by mikeybinns** [vitest-dev/vitest#2842]
### Clear and concise description of the problem

I'm trying to test a CLI package. The best way I have found to test this package is to use the `npm pack` command to package up a test version, then run the tests against that.

Currently, the setup / teardown commands only run at the start / end of the process, meaning that if I make a change to the code, it doesn't re-pack the code for testing (as it it packed in the setup function).

I realise that this will not be a default as it would add extra time between runs due to needing to run setup/teardown multiple times.

### Suggested solution

I'd like to see an option to specify if setup / teardown runs between watch changes, e.g. `--teardownBetweenRuns`
This would then be the process:
Watcher detects file change > teardown is ran > setup is ran > tests are re-ran, either partially or fully.

### Alternative

We could define a new function which specifically only runs after a watch change but before the tests are re-run, however, this wouldn't be possible using default export.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I think you can just reuse reporter API for this. It has `onWatcherRerun` method that you can  specify.

**Comment by mikeybinns** [comment]
Yep, I tried that today and you're right. Thanks! :)

**Comment by mikeybinns** [comment]
For those coming after me, this is how I did it for my setup. No need to write any new/duplicate code, just export named exports from global setup file and import those functions into your vitest config.

```ts
// file: ./src/test-setup.ts
export async function setup() {
    // setup test environment
}
export async function teardown() {
    // teardown test environment
}
```
```ts
// file: ./vitest.config.ts
import { defineConfig } from "vitest/config";
import { setup, teardown } from "./src/test-setup";

export default defineConfig({
    test: {
        include: ["src/**/*.test.{js,mjs,cjs,ts,jsx,tsx}"],
        watchExclude: ["**/node_modules/**", "**/dist/**"],
        globalSetup: ["./src/test-setup.ts"],
        reporters: ["default", { async onWatcherRerun() {
            await teardown();
            await setup();
        }}]
    },
});
```
