### ISSUE TITLE
Dynamically loaded module in forEach loop is mocked only once

### ISSUE THREAD

**Issue by ElVisPL** [vitest-dev/vitest#2847]
### Describe the bug

When mocking dynamically imported module in forEach loop the module is mocked only once

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-cek1xb?file=test/file.js

See the output - first returned value is mocked instance, the next is original module

![image](https://user-images.githubusercontent.com/3405010/218042047-08dc12f6-538d-45ca-96c1-fb48ba937ae1.png)

### System Info

```shell
Stackblitz environment, latest versions
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
forEach is not awaitable. Your test code finished before the await, so everything is cleared up by the point it reaches the second await.

**Comment by ElVisPL** [comment]
> forEach is not awaitable. Your test code finishes before the await, so everything is cleared up by the point it reaches the second await.

I understand, but if I use `vi.mock` before any execution, then it should mock all future imports no matter how they're used?

**Comment by sheremet-va** [comment]
As I said:

> everything is cleared up by the point it reaches the second await

Your tests **finished** running, there are no mocks outside of your tests.

Rewrite your code to await all Promises:

```ts
await Promise.all(paths.map(() => await import("fs"))
```

**Comment by ElVisPL** [comment]
Oh, I got it. Thank you!
