### ISSUE TITLE
Remove the `vite` dependency

### ISSUE THREAD

**Issue by silverwind** [vitest-dev/vitest#2848]
### Clear and concise description of the problem

`vitest` is currently [22.9 MB](https://packagephobia.com/result?p=vitest), out of which [14.3 MB](https://packagephobia.com/result?p=vite) comes from the `vite` dependency, which among other things depends on `esbuild` which (correct me if wrong) is not even used for `vitest` execution at all.

### Suggested solution

Remove the `vite` dependency and move the parts that are shared between `vitest` and `vite` into a shared module.

This has the benefit that server-side projects which use `vitest` but not `vite` don't need to download the unnecessary dependencies.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Vitest cannot work without Vite.

**Comment by silverwind** [comment]
Why not? Which parts of vite can not be moved out to a shared library?

**Comment by silverwind** [comment]
Also, can you not close this so fast please? I'd like to hear viewpoints from other contributors as well. The "Why Vitest" docs say:

> Vitest aims to position itself as the Test Runner of choice for Vite projects, and as a solid alternative even for projects not using Vite.

So if vitest positions itself for projects that don't use vite, it should not depend on it imho. The package is currently way too heavy in size imho.

**Comment by sheremet-va** [comment]
> Also, can you not close this so fast please? I'd like to hear viewpoints from other contributors as well. The "Why Vitest" docs say:
> 
> 
> 
> > Vitest aims to position itself as the Test Runner of choice for Vite projects, and as a solid alternative even for projects not using Vite.
> 
> 
> 
> So if vitest positions itself for projects that don't use vite, it should not depend on it. The package is currently way too heavy in size imho.

Vite processes paths, files and transforms code. 90% of everything Vitest does is done by Vite.

> So if vitest positions itself for projects that don't use vite, it should not depend on it.

Vite does all the work.

**Comment by silverwind** [comment]
For frontend project, I agree, vite certain does the heavylifting.

But for simple deno/node project where no transpilation is happening, vite is just used as a config resolver, the whole vite transpilation pipeline is not needed.

But I see you're favoring the frontend projects, so deno/node projects should go look somewhere else if they want a lightweight test runner.
