### ISSUE TITLE
Controlling concurrency on a per file basis

### ISSUE THREAD

**Issue by hbgl** [vitest-dev/vitest#2852]
### Clear and concise description of the problem

As a developer using Vitest I want to run specific test files in single-threaded mode so that I can control the performance characteristics of the individual test file.

### Suggested solution

In vitest we already have the ability to control concurrency of test cases by using `test.concurrent` or just regular `test`. The new feature would add a similar mechanism but on a per file basis. A test file could be marked as `serial` which would turn vitest into single-threaded mode during the execution of this test file.

### Alternative

A workaround would be to run multiple instances of vitest, one multi-threaded and one single-threaded:
```bash
npx vitest run --threads=false serial && npx vitest run concurrent
```

### Additional context

My project contains test files that perform relatively heavy weight tasks like rendering pages in headless chrome. Each individual test case needs to complete within a certain time window or else it is considered failed. Running such a test file by itself already generates a high CPU load on all cores because work is offloaded onto the chrome process. I want to run these test files in isolation so they can have full access to system resources and finish as fast as possible.

In the same project there are also other tests files that are not time sensitive and that perform all of their work in a single thread. So naturally, I want to run those tests in parallel to speed them up.

The problem arises when the time sensitive test files run in parallel with other tests because now they are competing for system resources, possibly causing the time sensitive tests to timeout.

---

### Edit:
Something I didn't consider when first writing this issue is that [`maxConcurrency`](https://vitest.dev/config/#maxconcurrency) would also have to be overridable by the individual test files.

---

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
[Workspace](https://vitest.dev/guide/workspace.html) feature provides a way to achieve the same thing using inline workspace config:

```ts
export default defineWorkspace([
  {
    test: {
      include: ['**/serial/*'],
      poolOptions: { threads: { singleFork: true } },
    },
    test: {
      include: ['**/concurrent/*'],
    },
  },
])
```
