### ISSUE TITLE
Jest compatibility: Use colon `:` instead of chevron `>` for snapshots with hints

### ISSUE THREAD

**Issue by trivikr** [vitest-dev/vitest#2853]
### Clear and concise description of the problem

The snapshots are different in Vitest as compared to those in Jest when a hint is passed.

Example test case:
```js
test("toThrowErrorMatchingSnapshot", () => {
  expect(() => {
    throw new Error("error");
  }).toThrowErrorMatchingSnapshot("hint");
});
```

The snapshot content:
* Jest: ```exports[`toThrowErrorMatchingSnapshot: hint 1`] = `"error"`;```
* Vitest: ```exports[`toThrowErrorMatchingSnapshot > hint 1`] = `"error"`;```

This difference applies to `toMatchSnapshot` API too.

This will fail snapshot tests which use hints when migrating from jest to vitest. It's not easy to provide a transformation for this too in vitest-codemod, as the delimiter (`:` or `>`) can be part of test message.

### Suggested solution

Since vitest is not yet 1.0, change the snapshot to use semicolon `:` for when hints are used with snapshots.

Jest already switched to `printBasicPrototype: false` by default in Jest 29 (updated in https://github.com/vitest-dev/vitest/pull/2830), so this is the only difference I saw when writing vitest-codemod tests

### Alternative

No change in code. Just document the differences in https://vitest.dev/guide/snapshot.html#difference-from-jest
Users can always override their snapshots when moving from Vitest to Jest.

### Additional context

Difference was noticed while writing snapshot tests in https://github.com/trivikr/vitest-codemod/pull/103 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Personally, I don't see any reason to change the current implementation. It was made consciously.

**Comment by trivikr** [comment]
Added documentation for this difference in https://github.com/vitest-dev/vitest/pull/2863

**Comment by trivikr** [comment]
> This will fail snapshot tests which use hints when migrating from jest to vitest

Verified that the test when migrating from jest to vitest. It just adds a new snapshot which is not referred to.

Example source:
```js
test("toThrowErrorMatchingSnapshot", () => {
  expect(() => {
    throw new Error("error");
  }).toThrowErrorMatchingSnapshot("hint");
});
```

Snapshot on running with jest:
```console
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`toThrowErrorMatchingSnapshot: hint 1`] = `"error"`;
```

Snapshot on running with vitest:
```console
// Vitest Snapshot v1

exports[`toThrowErrorMatchingSnapshot > hint 1`] = `"error"`;

exports[`toThrowErrorMatchingSnapshot: hint 1`] = `"error"`;
```

User has to update snapshot with `-u` or `--update` to remove the old snapshots.
```console
// Vitest Snapshot v1

exports[`toThrowErrorMatchingSnapshot > hint 1`] = `"error"`;
```

**Comment by trivikr** [comment]
Added documentation for this difference in https://github.com/vitest-dev/vitest/pull/2863
