### ISSUE TITLE
The `stackStr` in `test.result.errors` has ANSI color codes

### ISSUE THREAD

**Issue by roerohan** [vitest-dev/vitest#2868]
### Describe the bug

When creating a [custom reporter](https://github.com/roerohan/vitest-github-action/blob/main/src/GithubReporter.ts), the `test.result.errors[index].stack` and `test.result.errors[index].stackStr` consist of some ANSI color codes (possibly to show color when logged in the console). However, this affects all other custom reporters that do not want to log to the console, for instance, the one I shared in the [link above](https://github.com/roerohan/vitest-github-action).

## TLDR;
Check out [this](https://github.com/roerohan/vitest-github-action/pull/3/files#diff-f467291919ba1b33e77e33a5773c7b3a55c0727ae91092f4746888563cb26899) PR.

## Reproduction

When using the `GithubReporter` from [GithubReporter.ts](https://github.com/roerohan/vitest-github-action/blob/sample-test/src/GithubReporter.ts), when expect failed in a test with `.not.toBeCalled()`, there were ANSI characters in the stack trace, whereas when the expect failed in a test with `expect(a).toBe(b)` there were no ANSI color codes in the stack trace.

P.S. this is reproducible only on the `sample-test` branch of the repository, because there is a regex to filter out ANSI codes from the stack trace on the `main` branch.

```ts
import { defineConfig } from 'vitest/config';
// import { GithubReporter } from 'vitest-github-action';
import { GithubReporter } from './src';

export default defineConfig({
    test: {
        reporters: process.env.GITHUB_ACTIONS
            ? ['default', new GithubReporter()]
            : 'default',
    },
});
```

Test file that has ANSI colors in stack trace when there's an error:
```ts
import {beforeEach, describe, expect, test, vi} from 'vitest';

let sum: () => void;

describe('Given sum() exists', () => {
	beforeEach(() => {
		sum = vi.fn();
	});

	describe('When sum() is called', () => {
		beforeEach(() => {
			sum();
		});

		test('sum() should be called', () => {
			expect(sum).toBeCalled();
		});

		test('sum() should not be called', () => {
			expect(sum).not.toBeCalled();
		});
	});
});
```

Test file that does not have ANSI colors in the stack trace when there's an error:
```ts
import {beforeEach, describe, expect, test} from 'vitest';
import sum from './sum';

function sum(a: number, b: number) {
	return a + b;
}

let val: number;

describe('Given sum() was called', () => {
	describe('When the arguments are 1 and 1', () => {
		beforeEach(() => {
			val = sum(1, 1);
		});

		// Passing test
		test('Then the sum should be 2', () => {
			expect(val).toBe(2);
		});

		// Failing test
		test('Then the sum should be 3', () => {
			expect(val).toBe(3);
		});
	});
});
```

What is weird is that both of these actually show colors when these errors are logged in the console. I'm not sure if that's the vitest reporter, because seemingly, the colors (or colorful error messages, as in the image below) are not there in the stack trace logged in `sum.test.ts`.

![image](https://user-images.githubusercontent.com/42958812/218777503-3b73234d-e132-4a6d-a7f9-06f685bdc181.png)

### System Info

```shell
System:
    OS: Linux 5.19 Manjaro Linux
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 5.55 GB / 14.99 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 19.1.0 - ~/.nvm/versions/node/v19.1.0/bin/node
    npm: 6.14.15 - ~/Documents/Repos/dyte/web-core/node_modules/.bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 109.0.1
  npmPackages:
    @vitest/coverage-c8: ^0.28.3 => 0.28.3 
    vite: 3.0.1 => 3.0.1 
    vitest: ^0.28.5 => 0.28.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Seems like we need to add more checks for displaying colors. I removed picocolors in #2828 (which will probably be extracted into its own PR), and we can do that there.

**Comment by sheremet-va** [comment]
Colors are disabled if `GITHUB_ACTIONS` is present
