### ISSUE TITLE
vi.doMock does not override previous mock

### ISSUE THREAD

**Issue by trivikr** [vitest-dev/vitest#2870]
### Describe the bug

~~vi.resetModules does not reset mocks created with doMock~~
vi.doMock does not override previous mock

### Reproduction

Example source file:
```js
const getToken = () => 'token';

module.exports = { getToken };
```

Example test file:
```js
// beforeEach(() => {
//  vi.resetModules();
// });

test('getToken 1', async () => {
  vi.doMock('./getToken', () => ({
    getToken: () => 'token1',
  }));
  const { getToken } = await import('./getToken');
  expect(getToken()).toBe('token1');
});

test('getToken 2', async () => {
  vi.doMock('./getToken', () => ({
    getToken: () => 'token2',
  }));
  const { getToken } = await import('./getToken');
  expect(getToken()).toBe('token2'); // <-- This should be 'token2'
});
```

Error thrown:
```console
 FAIL  doMock.spec.js > getToken 2
AssertionError: expected 'token1' to be 'token2' // Object.is equality
 ❯ doMock.spec.js:18:22
     16|   }));
     17|   const { getToken } = await import('./getToken');
     18|   expect(getToken()).toBe('token2');
       |                      ^
     19| });

  - Expected   "token2"
  + Received   "token1"
```

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
  Binaries:
    Node: 18.13.0 - ~/Library/Caches/fnm_multishells/65073_1676392486717/bin/node
    Yarn: 3.4.1 - ~/Library/Caches/fnm_multishells/65073_1676392486717/bin/yarn
    npm: 8.19.3 - ~/Library/Caches/fnm_multishells/65073_1676392486717/bin/npm
  npmPackages:
    vitest: ^0.28.5 => 0.28.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by trivikr** [comment]
Documentation for vi.doMock https://vitest.dev/api/vi.html#vi-domock

**Comment by sheremet-va** [comment]
`vi.resetModules` doesn't clear mocks registry by design, as far as I'm aware. Not sure if it was the right decision though 🤷🏻

**Comment by trivikr** [comment]
The documentation for [vi.resetModules](https://vitest.dev/api/vi.html#vi-resetmodules)
> Resets modules registry by clearing cache of all modules.

From the documentation, it looks like it should clear the mock registry.

**Comment by trivikr** [comment]
The documentation for [vi.doMock](https://vitest.dev/api/vi.html#vi-domock)
> The same as [vi.mock](https://vitest.dev/api/vi.html#vi-mock), but it's not hoisted at the top of the file, so you can reference variables in the global file scope. The next import of the module will be mocked.

From the definition, doMock should override previous cache, even if vi.resetModules doesn't clear the mock registry.

**Comment by mysteryven** [comment]
I'd like to take this.
