### ISSUE TITLE
Allow extending `toEqual`

### ISSUE THREAD

**Issue by shun-shobon** [vitest-dev/vitest#2875]
### Clear and concise description of the problem

I would like to make `toEqual` extensible so that I can easily compare objects that contain custom classes. This is a feature that is also [included in Jest](https://jestjs.io/ja/docs/expect#expectaddequalitytesterstesters) and would be very useful if added.

```ts
class Volume {
  constructor(public amount: number, public unit: "L" | "mL") {}

  equals(other: Volume): boolean {
    if (this.unit === other.unit) {
      return this.amount === other.amount;
    } else if (this.unit === "L" && other.unit === "mL") {
      return this.amount * 1000 === other.amount;
    } else {
      return this.amount === other.amount * 1000;
    }
  }
}

it("Object Assertion", () => {
  const obj1 = { volume: new Volume(1, "L") };
  const obj2 = { volume: new Volume(1000, "mL") };

  // Expect to succeed, but we actually fail
  expect(obj1).toEqual(obj2);
  // This is a bit redundant
  assert(obj1.volume.equals(obj2));
});
```

### Suggested solution

Like Jest, it provides an API that allows `toEqual` to be extended. It is not necessary to make everything the same as Jest, but a similar API format would be easier to use.

```ts
function areVolumesEqual(a: unknown, b: unknown): boolean | undefined {
  const isAVolume = a instanceof Volume;
  const isBVolume = b instanceof Volume;

  if (isAVolume && isBVolume) {
    return a.equals(b);
  } else if (isAVolume !== isBVolume) {
    return false;
  } else {
    return undefined;
  }
}

expect.addEqualityTesters([areVolumesEqual]);
```

### Alternative

It is still possible to compare classes using `assert`, but the test becomes redundant if the class is contained in an object or if there are a large number of classes in the object.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by samkevin1** [comment]
Hey! Can I work on this one?

**Comment by sheremet-va** [comment]
> Hey! Can I work on this one?

Sure
