### ISSUE TITLE
No hint where not overwritten, why not show 100% ？

### ISSUE THREAD

**Issue by ChaiMayor** [vitest-dev/vitest#2878]
### Describe the bug

The Uncovered Line no longer exists. Why isn't it 100%?
I don't know what this is, is it a bug or is it normal?
![image](https://user-images.githubusercontent.com/97388975/219282626-d5c2dc81-02e3-455f-a477-e33d9f19620d.png)

### Reproduction

The code can be found in this repository：https://github.com/ChaiMayor/hview-ui/tree/dev
dev branch based.
![image](https://user-images.githubusercontent.com/97388975/219282656-a3d44c4d-3fa7-4e25-a280-2c878cc67bc2.png)

Follow these steps:

1. git clone https://github.com/ChaiMayor/hview-ui.git

2. git checkout dev

3. pnpm i

4. pnpm run test on root dir

5. pnpm run coverage

There is no hint where is not overwritten, so should it be displayed as 100%

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 7.85 GB / 31.81 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: bookmarks.html
initial_preferences
    Edge: Spartan (44.19041.1266.0), Chromium (110.0.1587.41)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
The coverage report seems accurate. All **lines** are covered, but not all **functions**. 

If you open up the HTML report, e.g. with `open packages/coverage/index.html`, you can see the uncovered functions.

<img height="320px" src="https://user-images.githubusercontent.com/14806298/219291548-ca6e0d1b-ca70-4bf4-b3d3-65ee548ecb81.png" />

<img height="320px" src="https://user-images.githubusercontent.com/14806298/219291646-5c3c7c5e-188a-4ab0-9961-3c8f95ccfa1a.png" />

**Comment by ChaiMayor** [comment]
Thank you very much. I see how to solve it😋
