### ISSUE TITLE
@vitest/coverage-istanbul report does not include files with no tests

### ISSUE THREAD

**Issue by tw-eugeneoei** [vitest-dev/vitest#2879]
### Describe the bug

Coverage report does not include files with no tests even though `coverage.all` option has been set to `true`. in the [repo](https://github.com/tw-eugeneoei/conditional-rendering-coverage/tree/with-istanbul), there is an `ExampleView.vue`  file without test and the coverage for this file is not reflected in the report.

![missing-file-coverage-all-true](https://raw.githubusercontent.com/tw-eugeneoei/conditional-rendering-coverage/with-istanbul/images/missing-file-coverage-all-true.jpg)

setting `coverage.include` glob pattern does not seem to work either.

![missing-file-coverage-all-true-with-include](https://raw.githubusercontent.com/tw-eugeneoei/conditional-rendering-coverage/with-istanbul/images/missing-file-coverage-all-true-with-include.jpg)

i have looked at [#680](https://github.com/vitest-dev/vitest/issues/680) which uses `c8` and AriPerkkio mentioned it is working as expected. i have tried using `c8` as well, but files with no tests are still not reflected in the coverage report.

### Reproduction

you can find the reproducible repo [here](https://github.com/tw-eugeneoei/conditional-rendering-coverage/tree/with-istanbul).

### System Info

```shell
System:
  OS: macOS 13.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 77.59 MB / 16.00 GB
  Shell: 5.8.1 - /bin/zsh
npmPackages:
  @playwright/test: ^1.28.1 => 1.30.0 
  @rushstack/eslint-patch: ^1.1.4 => 1.2.0 
  @testing-library/user-event: ^14.4.3 => 14.4.3 
  @testing-library/vue: ^6.6.1 => 6.6.1 
  @types/jsdom: ^20.0.1 => 20.0.1 
  @types/node: ^18.11.12 => 18.13.0 
  @vitejs/plugin-vue: ^4.0.0 => 4.0.0 
  @vitejs/plugin-vue-jsx: ^3.0.0 => 3.0.0 
  @vitest/coverage-c8: ^0.28.5 => 0.28.5 
  @vitest/coverage-istanbul: ^0.28.5 => 0.28.5 
  @vue/eslint-config-prettier: ^7.0.0 => 7.0.0 
  @vue/eslint-config-typescript: ^11.0.0 => 11.0.2 
  @vue/test-utils: ^2.2.6 => 2.2.10 
  @vue/tsconfig: ^0.1.3 => 0.1.3 
  eslint: ^8.22.0 => 8.34.0 
  eslint-plugin-vue: ^9.3.0 => 9.9.0 
  jsdom: ^20.0.3 => 20.0.3 
  npm-run-all: ^4.1.5 => 4.1.5 
  pinia: ^2.0.28 => 2.0.30 
  prettier: ^2.7.1 => 2.8.4 
  typescript: ~4.7.4 => 4.7.4 
  vite: ^4.0.0 => 4.1.1 
  vitest: ^0.25.6 => 0.25.8 
  vue: ^3.2.45 => 3.2.47 
  vue-router: ^4.1.6 => 4.1.6 
  vue-tsc: ^1.0.12 => 1.0.24
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
@tw-eugeneoei update your `vitest` to latest version with `npm install -D vitest@latest`.

```
~/x/conditional-rendering-coverage (with-istanbul) $ npm ls vitest
conditional-rendering-coverage@0.0.0 /x/conditional-rendering-coverage
├─┬ @vitest/coverage-c8@0.28.5
│ └── vitest@0.28.5
├─┬ @vitest/coverage-istanbul@0.28.5
│ └── vitest@0.28.5
└── vitest@0.25.8  // <------------------- Update this

~/x/conditional-rendering-coverage (with-istanbul) $ npm i -D vitest@latest

~/x/conditional-rendering-coverage (with-istanbul) $ npm run test:cov

> conditional-rendering-coverage@0.0.0 test:cov
> vitest --coverage --root src/

 % Coverage report from istanbul
----------------------|---------|----------|---------|---------|-------------------
File                  | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------------------|---------|----------|---------|---------|-------------------
All files             |      30 |       50 |   16.66 |   27.77 |                   
 src                  |       0 |      100 |     100 |       0 |                   
  App.vue             |       0 |      100 |     100 |       0 | 6                 
  main.ts             |       0 |      100 |     100 |       0 | 9-14              
 src/components       |      75 |       50 |       0 |      75 |                   
  ...oWorldHeader.vue |      75 |       50 |       0 |      75 | 7                 
 src/router           |       0 |      100 |       0 |       0 |                   
  index.ts            |       0 |      100 |       0 |       0 | 4-15              
 src/stores           |       0 |      100 |       0 |       0 |                   
  counter.ts          |       0 |      100 |       0 |       0 | 4-11              
 src/utils            |     100 |      100 |     100 |     100 |                   
  calculator.ts       |     100 |      100 |     100 |     100 |                   
 src/views            |     100 |      100 |     100 |     100 |                   
  HomeView.vue        |     100 |      100 |     100 |     100 |                   
----------------------|---------|----------|---------|---------|-------------------

```

These incompatibility issues will be prevented in the next `0.29.0` release:
- https://github.com/vitest-dev/vitest/pull/2836

**Comment by tw-eugeneoei** [comment]
hello @AriPerkkio. thanks so much for the quick response! updating `vitest` to the latest version solved it!

another issue cropped up (let me know if it should be a new issue instead). i tried excluding some files through the `coverage.exclude` option, but that doesnt seem to work. any ideas?

this is how the `config` is defined in `vite.config.ts`

```
export default defineConfig({
  plugins: [vue(), vueJsx()],
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },
  test: {
    globals: true,
    watch: false,
    environment: "jsdom",
    coverage: {
      all: true,
      exclude: ["/src/stores/counter.ts"],
      // exclude: ["/src/stores/*.ts"], // this pattern doesnt work
      // exclude: ["src/router/*"], // this pattern doesnt work
      reportsDirectory: "../coverage",
      provider: "istanbul",
    },
  },
});
```

**Comment by tw-eugeneoei** [comment]
ahhhh. i got it now. thanks so much for your help and quick responses! really appreciate it!

**Comment by corentin35000** [comment]
`import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    environment: 'node',
    coverage: {
      include: ['vitest/unit/**/*.{spec,test}.ts'],
      exclude: [],
      provider: 'c8',
      reportsDirectory: './vitest/unit/test-reports',
    },
  },
})
`

Here is the configuration file of: vitest.config.ts, I also had a lot of trouble recovering the *.ts files during the test report with c8, the exclude: [] property (set to empty) and put the path of folder which include test/spec files in include! A walk for me :)
