### ISSUE TITLE
Vitest crashing randomly

### ISSUE THREAD

**Issue by kefniark** [vitest-dev/vitest#2880]
### Describe the bug

Using vite and vitest on a node project, works fine in dev and in build, but the test suite randomly crash on windows for no apparent reason. Never seen this error in github CI.

Basically when I run vitest, it seem to run all the tests, I can see if the individual tests passing or not.
But at the end just before returning a result, I get the following crash in Rust Land
```sh
vitest --coverage
# ...
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\napi-2.10.4\src\tokio_runtime.rs:61:42
error Command failed with exit code 3221226505.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "test:unit" exited with 3221226505.
```
I can get the errors multiple times in a row, and after a while and many retry it will work.

### Reproduction

Sadly I spend some time trying to reproduce it on platform like stackblitz, but I could not reproduce anything.
I feels like it's something really platform specific and a bit random (it still works ~50% of the time)
I played with lot of vitest flags like `threads` but couldn't find a flag that has any impact on the error.

My vitest config is really simple
```ts
import { defineConfig } from 'vitest/config'
import graphql from '@rollup/plugin-graphql'

export default defineConfig({
  build: {
    target: 'modules'
  },
  test: {
    globals: true,
    coverage: {
      reportsDirectory: './coverage',
      reporter: ['text', 'cobertura', 'html']
    }
  },
  plugins: [graphql()]
})
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 15.74 GB / 31.94 GB
  Binaries:
    Node: 18.4.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 109.0.5414.121
    Edge: Spartan (44.22621.1265.0), Chromium (110.0.1587.46)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> Sadly I spend some time trying to reproduce it on platform like stackblitz, but I could not reproduce anything.

You don't have to use stackblitz for reproductions.
