### ISSUE TITLE
Unexpected message on Worker

### ISSUE THREAD

**Issue by yunsii** [vitest-dev/vitest#2882]
### Describe the bug

I got the unhandled error when I wrote a basic test of crawlee.
![image](https://user-images.githubusercontent.com/18096089/219563758-6faa6474-6607-497a-9475-cc5f38130e32.png)

### Reproduction

https://github.com/yunsii/vitest-crawlee

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 11.85 GB / 19.54 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
  npmPackages:
    @vitest/ui: ^0.28.5 => 0.28.5 
    vite: ^4.1.1 => 4.1.1 
    vitest: ^0.28.5 => 0.28.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You cannot use features that check for `isMainThread` because Vitest runs tests in worker threads by default. To bypass this, you can disable this:

```
// vitest 0.34.6
vitest --no-threads

// vitest 1.0.0
vitest --pool=forks
```
