### ISSUE TITLE
Vite Environment Variables are not the correct type  

### ISSUE THREAD

**Issue by tapoinde** [vitest-dev/vitest#2895]
### Describe the bug

Vite exposes several environment variables, 3 of which should be boolean `import.meta.env.[DEV | PROD | SSR]`. These variables are evaluating as strings while running tests.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-maqvfr?file=test/basic.test.ts

### System Info

```shell
All systems
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Yes, it is mentioned in the documentation: https://vitest.dev/api/vi.html#vi-stubenv

Vitest transforms all `import.meta.env` into `process.env`, which is always a string.
