### ISSUE TITLE
No threads option fail to update snapshot correctly

### ISSUE THREAD

**Issue by KevinYobeth** [vitest-dev/vitest#2896]
### Describe the bug

When using --no-threads option on vitest, all the snapshots are somehow always regenerated, but it is invalid. All the snapshots result are the same to the first snapshot test it ran, even though they are on a different folder.

Project using vite and vitest

### Reproduction

1. Make multiple snapshot test in different folders using vitest
2. Run `vitest run --coverage --no-threads`
3. The tests in different folder will return same snapshot as the first one to be run

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 5600G with Radeon Graphics
    Memory: 14.44 GB / 15.02 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
    Yarn: 1.22.17 - /mnt/c/Users/KevinYobeth/AppData/Roaming/npm/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.2/bin/npm
  Browsers:
    Chromium: 83.0.4103.116
  npmPackages:
    @vitejs/plugin-react: ^3.0.1 => 3.0.1
    @vitest/coverage-istanbul: ^0.28.5 => 0.28.5
    vite: ^4.0.4 => 4.0.4
    vitest: ^0.28.5 => 0.28.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by KevinYobeth** [comment]
I can't seem to reproduce it in a new project :(, and I can't publish the repository as it is a company project. Are you aware any possibility that --no-threads options could cause vitest to generate the same snapshots in different tests / folders?

**Comment by sheremet-va** [comment]
> I can't seem to reproduce it in a new project :(, and I can't publish the repository as it is a company project. Are you aware any possibility that --no-threads options could cause vitest to generate the same snapshots in different tests / folders?

No, it's the first time I hear about such issue

**Comment by KevinYobeth** [comment]
I will keep trying to reproduce it on a new project, since the problem occurred persistently on local and CI and other machine as well. Do you have any idea what could cause such issue perhaps?

**Comment by adriangornypl** [comment]
Do you have concurrent test cases perhaps? We had troubles with snapshot generation when using concurrent test cases - they were simply not generated at all.

**Comment by KevinYobeth** [comment]
No actually, we just migrated our project from create-react-app to vite, and migrated all our tests to vitest as well. We haven't touch vitest concurrent feature yet.

**Comment by meza** [comment]
This commit seems to be the most broken. I'd appreciate some pointers as to what might be causing the weird behaviour with the snapshots:

https://github.com/meza/trance-stack/tree/7079d9694aee924b0e4328a1afda5986229f0738

`vitest --run --update src/components/Login`

Seems like when the snapshots aren't a match, very strange things happen
