### ISSUE TITLE
vitest should be compatible with webpack.definePlugin

### ISSUE THREAD

**Issue by paulgreg** [vitest-dev/vitest#2898]
### Clear and concise description of the problem

I’m migrating from jest to vitest on an existing webpack based project.

The project is generating 2 outputs : one for the browser and one for node.js

It’s using [webpack DefinePlugin](https://webpack.js.org/plugins/define-plugin/) to create a few expressions resolved at compile time, like `__BROWSER__`, set to true for browser output, and false to server output.

Vitest fails when encountering that expression and I wasn’t able to find a way to make it work.

`ReferenceError: __BROWSER__ is not defined`

Note that using `global.__BROWSER__` is not a solution since it won’t be replaced by webpack DefinePlugin.

### Suggested solution

It would be great to allow the definition of some global trough config, like we did with jest : https://jestjs.io/docs/configuration#globals-object

### Additional context

I’ve built a minimal project reproducing the problem here : https://github.com/paulgreg/bug-defineplugin-vitest

You can build it via `npm run build` and run server code via `npm run start` retourning « isBrowser: false ».

It has a simple unit test which will fail launching `vitest` : 

`ReferenceError: __BROWSER__ is not defined`

I’ve also installed jest which will run test fine by overloading globals configuration.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Use `define` option: https://vitejs.dev/config/shared-options.html#define

```ts
// vitest.config.mjs
export default {
  define: {
    __BROWSER__: true
  }
}
```

**Comment by paulgreg** [comment]
Thank you. 
Sorry I’ve missed that in the doc :/
