### ISSUE TITLE
Add CLI command to output a list of tests for better testNamePattern usage

### ISSUE THREAD

**Issue by NullVoxPopuli** [vitest-dev/vitest#2901]
### Clear and concise description of the problem

When using `describe`, it can be hard to narrow tests based on files/describe blocks -- especially when test names within describe blocks / test files may be repeated. 

### Suggested solution

As a debug utility, it could be great to be able to output the list of tests without running them so that folks can better utilize `--testNamePattern`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
What should happen if the test name is dynamic? How can we know the name in that case?

**Comment by NullVoxPopuli** [comment]
> Or should we just run all test files without running test callbacks and output them?

yea, this is what mocha and qunit do

**Comment by sheremet-va** [comment]
So, basically to have a command:

```
vitest list -t "some pattern I have"
```

**Comment by NullVoxPopuli** [comment]
Exactly, yeah

**Comment by NullVoxPopuli** [comment]
depends on output format, I suppose.

For stdout:
```
filename | describe | nested describe | test name
...
```
for json: 
```
[
  { name: 'describe | nested describe | test name', file: 'file path' },
  ...
]
```
