### ISSUE TITLE
Config alias type is not the same as in the doc

### ISSUE THREAD

**Issue by vafanassieff** [vitest-dev/vitest#2906]
### Describe the bug

In the `vitest.config.ts` I have a type issue for [`alias`](https://vitest.dev/config/#alias)

The documentation expect a type `Record<string, string> | Array<{ find: string | RegExp, replacement: string, customResolver?: ResolverFunction | ResolverObject }>`

But it only found the type of `vite` `resolve.alias`  `AliasOptions = readonly Alias[] | { [find: string]: string }`

My custom resolver is used to resolve the subpath import from my monorepo ie `#src` → `<packageroot>/src`

### Reproduction

```javascript
import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

import { defineConfig } from 'vitest/config'

const createCustomResolver = (directory :string) => {}

export default defineConfig({
  test: {
    alias: [
      {
        find: /^#/,
        replacement: '#',
        customResolver: createCustomResolver(
          dirname(fileURLToPath(import.meta.url))
        ),
      },
    ],
    threads: false,
    environment: 'node',
  },
})
```

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 28.49 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Firefox: 110.0
    Firefox Developer Edition: 111.0
    Safari: 16.3
  npmPackages:
    @vitest/coverage-c8: 0.28.5 => 0.28.5 
    vitest: 0.28.5 => 0.28.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
How are the type different? I don't think I understand your problem. Your example has incorrect resolver, after it's fixed I don't have any type errors: 

https://stackblitz.com/edit/vitest-dev-vitest-wa9rur?file=vite.config.ts,node_modules%2Fvitest%2Fdist%2Ftypes-0373403c.d.ts,node_modules%2Fvite%2Fdist%2Fnode%2Findex.d.ts,node_modules%2Frollup%2Fdist%2Frollup.d.ts&initialPath=__vitest__

**Comment by vafanassieff** [comment]
Closing as it seem resolved
