### ISSUE TITLE
Using vitest brings in @types/node in a basic setup

### ISSUE THREAD

**Issue by Faithfinder** [vitest-dev/vitest#2917]
### Describe the bug

All in the title. Repro is the starter Vite project with Vitest installed.

### Reproduction

https://github.com/Faithfinder/vitest-types-node/blob/main/src/App.test.ts

Take a look in the linked file. "Buffer" looks ok to use.
Comment out the vitest import.
Now Buffer is unavailable.

This is true for the whole project (e.g, Buffer could be in any of the files).

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 1.05 GB / 5.79 GB
    Container: Yes
    Shell: 5.0.17 - /usr/bin/bash
  Binaries:
    Node: 18.14.0 - ~/.local/share/pnpm/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 9.3.1 - ~/.local/share/pnpm/npm
  npmPackages:
    @vitejs/plugin-react-swc: ^3.0.0 => 3.2.0 
    vite: ^4.1.0 => 4.1.4 
    vitest: ^0.28.5 => 0.28.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by a1mersnow** [comment]
Come across with same problem, `setTimeout/setInterval...` browser global api are override by `@types/node`.

**Comment by a1mersnow** [comment]
@Faithfinder Have you found some temporary workaround?

**Comment by DreierF** [comment]
We are running into the same issue. I was able to trace it down to [the import in line 2 here](https://www.unpkg.com/browse/vitest@0.29.7/dist/types-fafda418.d.ts):
```
import { UserConfig as UserConfig$1, TransformResult as TransformResult$1, ViteDevServer, CommonServerOptions, DepOptimizationConfig, AliasOptions } from 'vite';
```

and the corresponding `index.d.ts` file in `vite` starts with
```
/// <reference types="node" />
```
which leaks the declarations to the global types space.

It should be possible to fix this by moving the required types in vite into a separate file that does not need the `/// <reference types="node" />` directive, but maybe there is also a less invasive way to solve this.

**Comment by nstepien** [comment]
How can I work around this issue? 🙄 
```
node_modules/@types/node/globals.d.ts:72:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; timeout(milliseconds: number): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.

72 declare var AbortSignal: {
               ~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:2090:13
    2090 declare var AbortSignal: {
                     ~~~~~~~~~~~
    'AbortSignal' was also declared here.
```

**Comment by octogonz** [comment]
> Removing the `/// <reference types="node" />` directive fixes the issue, but it looks not like an easy task to do that as the file is generated by [api-extractor](https://api-extractor.com/pages/tsdoc/declaration_references/#docusaurus_skipToContent_fallback).

My guess is that this "fix" only works if your **tsconfig.json** has `skipLibCheck=true` (a dubious practice that speeds up compilation times by hiding important syntax errors, and should never be used when developing a library that will be published to NPM).

It is correct behavior for API Extractor to emit `/// <reference types="node" />` in the .d.ts rollup, because that file references global APIs from `@types/node`.

The root cause is that vitest is trying to be a test environment for multiple target runtimes, but its own API depends on declarations that are provided by the Node.js runtime.  If this root cause is fixed, then API Extractor should no longer generate a   .d.ts rollup with the `/// <reference types="node" />` directive.

**Comment by sheremet-va** [comment]
This is technically a bug. You should only get this types when you import from `vitest/node`.

**Comment by capricorn86** [comment]
I'm migrating from Jest to Vitest in [Happy DOM](https://github.com/capricorn86/happy-dom).

I only want to use Vitest for testing a Node environment, but it seems like Vitest is importing the Typescript types for the DOM somehow (lib.dom.d.ts).

**Expected**
"window" and other DOM properties to not be part of the global types.

**Actual**
DOM properties is part of the global types.

**To reproduce**
https://stackblitz.com/edit/vitest-dev-vitest-kjoyd7?file=test%2Fbasic.test.ts

**Comment by sheremet-va** [comment]
> I want to use Vitest for testing a Node environment, but it seems like Vitest is importing the Typescript types for the DOM somehow (lib.dom.d.ts).

Running tsc with `--explainFiles` shows it's a default lib reference:

```
node_modules/typescript/lib/lib.d.ts
  Default library for target 'es5'
node_modules/typescript/lib/lib.dom.d.ts
  Library referenced via 'dom' from file 'node_modules/typescript/lib/lib.d.ts'
```

If I empty out `lib` in tsconfig, it removes `"dom"` from references. However this shows a few errors:

1. Looks like `tinybench` depends on `AddEventListenerOptions` types form `dom`
2. esbuild depends on `WebAssembly` global
3. Vite depends on `Worker` global

**Comment by orivainer** [comment]
@a1mersnow did you find a way to overcome it?
We also have the `setTimeout` problem.

**Comment by a1mersnow** [comment]
@orivainer just use full path like `window.setTimeout` & `window.setInterval`...
