### ISSUE TITLE
`No test suite found` on windows for `v0.28.5+`

### ISSUE THREAD

**Issue by xsjcTony** [vitest-dev/vitest#2921]
### Describe the bug

Hey, I'm running `vitest` via `npm scripts` on Windows, which results in `no test suite found` for all test files.

![image](https://user-images.githubusercontent.com/45784210/221447026-86edb5ce-6791-4e5d-92a3-c690f16ad533.png)

It might be related to https://github.com/vitest-dev/vitest/issues/2020 since it's working for me if I run the command in the `docker` environment which is `WSL` (I guess, not sure). But I still want it to be runnable locally. 

Downgrading to `v0.28.4` solves the issue, which means the problem only exists for version `v0.28.5` and later (I suspect some changes caused this in `v0.28.5` release)

Since it's only happening on my local, so I don't think it's reproducible, but I would highly appreciate it if someone can inspect it.

### Reproduction

Unfortunately no reproduction available :( reason described above.

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 16.28 GB / 31.69 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (110.0.1587.56)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitejs/plugin-react-swc: ^3.2.0 => 3.2.0
    @vitest/coverage-c8: ^0.29.1 => 0.29.1
    @vitest/coverage-istanbul: ^0.29.1 => 0.29.1
    @vitest/ui: ^0.29.1 => 0.29.1
    vite: ^4.1.4 => 4.1.4
    vitest: ^0.29.1 => 0.29.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You can provide any reproduction, you don't have to use stackblitz

**Comment by xsjcTony** [comment]
@sheremet-va Hey, I'm sorry that it somehow works again.. even in my original case. I'm so confused😢.

I'll close the issue anyway, but in case it happens again I'll re-open the issue and attach a reproduction. Thanks for that.

**Comment by xsjcTony** [comment]
@sheremet-va Hi, I've encountered the problem again, and here's the reproduction:

https://github.com/xsjcTony/vitest-bug-repord

Please clone and run 
```
npm install
npm run test:unit
```

It will result in
![image](https://user-images.githubusercontent.com/45784210/221730002-09c4fa0f-9073-4e5b-838c-cb06fa8957a7.png)

**Comment by xsjcTony** [comment]
Just FYI, Issue still exists in `v0.29.2`

**Comment by SergioJuniorCE** [comment]
Any updates?
