### ISSUE TITLE
New CLI param: `mode`

### ISSUE THREAD

**Issue by alextompkins** [vitest-dev/vitest#2926]
### Clear and concise description of the problem

It would be helpful to be able to specify the [mode](https://vitejs.dev/guide/env-and-mode.html#modes) which vite-node uses, in order to use different Vite configs for different scripts. 

### Suggested solution

Implement a command-line argument `mode` which allows you to specify the Vite [mode](https://vitejs.dev/guide/env-and-mode.html#modes) used. 

### Additional context

As an example use-case: I'm using vite-node to run a `.ts` script which generates `.env.development.local`. Unfortunately because I validate that all relevant environment variables are present when `vite.config.ts` is loaded in `development` mode, this leads to a bit of a chicken & egg situation: vite-node loads the config, which causes the validation to run, which causes us to exit before we can generate the `.env` file we need (yes, you can blame me for over-zealously validating environment, but it helps when running builds in lots of different modes!). 

If I could use a `mode` argument, I could specify a mode where the validation would be skipped. 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
It is supported since 0.29.0, you can do this:

```ts
vite-node file-name.ts --mode development
```

**Comment by alextompkins** [comment]
Ah my bad! I should've checked release notes more thoroughly, I'm still on 0.28.1. Thanks!
