### ISSUE TITLE
v0.29 shows "The inspector session is already connected" when collecting coverage without isolation

### ISSUE THREAD

**Issue by EvHaus** [vitest-dev/vitest#2928]
### Describe the bug

After upgrading to 0.28.x to 0.29.1 our coverage reports starting failing with the following error:

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: The inspector session is already connected
 ❯ new NodeError node:internal/errors:393:5
 ❯ Session.connect node:inspector:66:13
 ❯ Module.startCoverage ../../node_modules/@vitest/coverage-c8/dist/index.js:5:11
 ❯ startCoverageInsideWorker ../../node_modules/vitest/dist/chunk-integrations-coverage.e0a6acd2.js:33:70
 ❯ run ../../node_modules/vitest/dist/entry.js:245:3
 ❯ run ../../node_modules/vitest/dist/worker.js:63:3
 ❯ ../../node_modules/tinypool/dist/esm/worker.js:109:20
```

What's significant is that we use `isolate: false`. Setting it to `true` makes the errors go away, but it's not desired in our case as we want isolation to be disabled to improve performance.

### Reproduction

Will try create a minimal repro later today. Just wanted to get this issue filed right away in case you happen to already know what might be causing this issue.

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 968.20 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Chrome Canary: 113.0.5620.1
    Firefox: 110.0
    Safari: 16.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
> Will try create a minimal repro later today.

I'm able to reproduce this using the information provided here. Looks like `{ isolate: false, singleThread: true }` triggers the error in Vitest's internal test cases. The test cases are already looping through multiple different configuration variations but this combination was not covered.

**Comment by EvHaus** [comment]
Thanks. Confirming that 0.29.2 works now.
