### ISSUE TITLE
docs wran

### ISSUE THREAD

**Issue by hzhoup** [vitest-dev/vitest#2930]
### Describe the bug

![image](https://user-images.githubusercontent.com/109516832/221721307-f289f2b2-7759-452c-b5f6-81fa5b21e10a.png)

### Reproduction

![image](https://user-images.githubusercontent.com/109516832/221721319-b9120964-1f04-4233-90b3-e024001283e5.png)

### System Info

```shell
https://cn.vitest.dev/guide/features.html
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
CN docs has a separate repo: https://github.com/vitest-dev/docs-cn
