### ISSUE TITLE
c8 ignore reports different coverage for js and ts file

### ISSUE THREAD

**Issue by otakustay** [vitest-dev/vitest#2933]
### Describe the bug

`/* c8 ignore start */` and `/* c8 ignore stop */` comments around `catch` block behaves differently for `.js` and `.ts` file, in `.ts` file it reports incorrect coverage

### Reproduction

1. Checkout https://github.com/otakustay/issues/tree/vitest-c8-ignore using branch `vitest-c8-ignore`
2. `npm install`
3. `npm run test`

I expect the same 100% coverage on both files, however `bar.ts` has uncovered lines:

```
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |     100 |       80 |     100 |     100 |
 bar.ts   |     100 |    66.66 |     100 |     100 | 4
 foo.js   |     100 |      100 |     100 |     100 |
----------|---------|----------|---------|---------|-------------------
```

<img width="295" alt="image" src="https://user-images.githubusercontent.com/639549/221766984-67ab3bcf-746c-4646-8724-61d9c1b10ce4.png">

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 5.05 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/Library/Caches/fnm_multishells/13409_1677563532577/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/13409_1677563532577/bin/yarn
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/13409_1677563532577/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Safari: 16.3
  npmPackages:
    @vitest/coverage-c8: ^0.29.1 => 0.29.1
    vite: ^4.1.4 => 4.1.4
    vitest: ^0.29.1 => 0.29.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by otakustay** [comment]
We use a "line break before else and catch cluase" coding style, for now I have to write code in this style:

```ts
export function bar() {
    try {
        return 1;
        /* c8 ignore start */
    }
    catch (ex) {
        console.error(ex);
    }
    /* c8 ignore stop */
}
```

Even when I disabled line break before `catch`:

```ts
export function bar() {
    try {
        return 1;
        /* c8 ignore start */
    } catch (ex) {
        console.error(ex);
    }
    /* c8 ignore stop */
}
```

Still `start` and `ignore` comments are not aligned verticaly, which is extremely ugly to me.

**Comment by AriPerkkio** [comment]
The root cause is very likely in `v8-to-istanbul` or some of its dependencies.

The reason why these two identical source files give two different results is `esbuild`. It removes all whitespace between `try {}` and `catch`, and places the catch clause on the same line as last bracket of `try`. The executed Javascript is eventually different and V8 coverage report gives a bit different output. `v8-to-istanbul` seems to place branch counter on different line depending whether `catch` is on its own line or not.

I don't think there is anything to do on Vitest's side.
