### ISSUE TITLE
0.29.2 ViteNodeServer times out with `experimentalOptimizer` enabled

### ISSUE THREAD

**Issue by joekrall** [vitest-dev/vitest#2937]
### Describe the bug

Follow-up from #2932. The same error is thrown with much the same stack on 0.29.2:

```

Error: ViteNodeServer: /home/projects/vitejs-vite-j7gysr/node_modules/.vitest/deps/whatwg-fetch.js not found. This is a bug, please report it.
    at Timeout.eval [as _onTimeout] (file://file:///home/projects/vitejs-vite-j7gysr/node_modules/vite-node/dist/server.mjs:322:15)
    at listOnTimeout (https://vitejsvitej7gysr-xk1f.w-credentialless.staticblitz.com/blitz.fc57b779eff411414c7b91114df9b720faaf721b.js:6:306542)
    at processTimers (https://vitejsvitej7gysr-xk1f.w-credentialless.staticblitz.com/blitz.fc57b779eff411414c7b91114df9b720faaf721b.js:6:307365)
    at https://vitejsvitej7gysr-xk1f.w-credentialless.staticblitz.com/blitz.fc57b779eff411414c7b91114df9b720faaf721b.js:15:263678
    at https://vitejsvitej7gysr-xk1f.w-credentialless.staticblitz.com/blitz.fc57b779eff411414c7b91114df9b720faaf721b.js:15:263978
```

On Stackblitz, after the first error is thrown, the following appears:

```
fatal error: too many writes on closed pipe

goroutine 6 [running]:
runtime.throw({0x95c7a, 0x1e})
        runtime/panic.go:1047 +0x3 fp=0x838ee0 sp=0x838eb8 pc=0x122b0003
os.sigpipe()
        runtime/os_js.go:144 +0x2 fp=0x838ef8 sp=0x838ee0 pc=0x139b0002
os.epipecheck(...)
        os/file_unix.go:195
os.(*File).Write(0x80c020, {0x6600c00, 0x18c,
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-j7gysr?file=package.json

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitejs/plugin-react: ^3.1.0 => 3.1.0 
    vite: latest => 4.1.4 
    vitest: ^0.29.2 => 0.29.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest 0.31.4 changes how `experimentalOptimizer` works. Now Vitest only optimizes dependencies inside `experimentalOptimizer.include` (which can be populated by plugins), so this should no longer be a problem.
