### ISSUE TITLE
`console.log` output is never displayed on test rerun in node v18, *sometimes* displayed in node v16 reruns

### ISSUE THREAD

**Issue by chetzof** [vitest-dev/vitest#2938]
### Describe the bug

It's simple: the console.log is sometimes not displayed, other times it is displayed. 
Tested on V18: in not displayed in ~95% of reruns
Tested on V16: in not displayed in ~30% of reruns

### Reproduction

I tried to create a reproduction example on stackblitz but they don't support v18 yet.  But it's basically your standard reproduction template + a console.log usage. I've downloaded the repo from stackblitz to my local environment, see demonstration

https://cln.sh/RRLYzT1k

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 120.92 MB / 16.00 GB
    Shell: 3.6.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.0.0 - ~/Library/Caches/fnm_multishells/11084_1677609775661/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/11084_1677609775661/bin/yarn
    npm: 9.3.1 - ~/Library/Caches/fnm_multishells/11084_1677609775661/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 106.0.5
    Safari: 16.3
  npmPackages:
    @vitest/ui: ^0.29.2 => 0.29.2
    vite: latest => 4.1.4
    vitest: latest => 0.29.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chetzof** [comment]
@AriPerkkio @sheremet-va it seems after merging this change, there is no longer **any** output on test rerun (checked v16/v18). When I downgrade to 0.28 i get the output _sometimes_ like before.

**Comment by AriPerkkio** [comment]
@chetzof the fix has not yet been released. The latest `0.29.2` does not include the fix. 

Please re-test once `0.29.3` or above is released.

**Comment by chetzof** [comment]
Will do, thanks!
