### ISSUE TITLE
0.29.2 "ViteNodeServer: <path> not found. This is a bug, please report it." when using experimentalOptimizer: true 

### ISSUE THREAD

**Issue by lmexo** [vitest-dev/vitest#2940]
### Describe the bug

Running tests issues the following error

```
DEV  v0.29.2 <project-root>

file://<project-root>/node_modules/vitest/node_modules/vite-node/dist/server.mjs:305
        throw new Error(`ViteNodeServer: ${id} not found. This is a bug, please report it.`);
        ^

Error: ViteNodeServer: <project-root>/node_modules/.vitest/deps/vitest-localstorage-mock.js not found. This is a bug, please report it.
    at Timeout._onTimeout (file://<project-root>/node_modules/vitest/node_modules/vite-node/dist/server.mjs:305:15)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

### Reproduction

Setup vitest with `setupFiles: ['./test/setupTests.ts']` and `experimentalOptimizer: true`.

In `test/setupTests.ts` add e.g.

```typescript
import 'vitest-localstorage-mock';

// further setup goes here
```

Then run vitest (assuming you have any tests, of course)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 15.03 GB / 19.54 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.15 - /mnt/c/Program Files/nodejs/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Firefox: 110.0
  npmPackages:
    @vitejs/plugin-react: ^2.0.0 => 2.2.0 
    @vitest/ui: ^0.29.1 => 0.29.1 
    @vitest/web-worker: ^0.29.1 => 0.29.1 
    vite: ^3.0.4 => 3.2.4 
    vitest: ^0.29.2 => 0.29.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marpro200** [comment]
I have the exact same issue with luxon.js:
```
C:\Projekte\ebos\ebosYC>yarn test

RUN  v0.29.2 C:/Projekte/ebos/ebosYC

file:///C:/Projekte/a_CommonBinaries/ThirdParty/Yarn-v2-Global/cache/vite-node-npm-0.29.2-382c31af3c-8.zip/node_modules/vite-node/dist/server.mjs:305
        throw new Error(ViteNodeServer: ${id} not found. This is a bug, please report it.);
        ^

Error: ViteNodeServer: C:/Projekte/ebos/ebosYC/node_modules/.vitest/deps/luxon.js not found. This is a bug, please report it.
    at Timeout._onTimeout (file:///C:/Projekte/a_CommonBinaries/ThirdParty/Yarn-v2-Global/cache/vite-node-npm-0.29.2-382c31af3c-8.zip/node_modules/vite-node/dist/server.mjs:305:15)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)

Node.js v18.7.0
```

My test config looks like this:
`test: {
        environment: "jsdom",
        reporters: "verbose",
        deps: {
            experimentalOptimizer: {
                enabled: true
            }
        }
    }`

I´m using yarn PNP as a package manager

**Comment by jurosh** [comment]
Same problem. It's trying to find `/node_modules/.vitest/deps/ethers.js` but it's def not dependency of Vitest as it's blockchain related library (Instead it's project dependency).

**Comment by joekrall** [comment]
I have left a similar issue: #2937

**Comment by sheremet-va** [comment]
Vitest 0.31.4 changes how `experimentalOptimizer` works. Now Vitest only optimizes dependencies inside `experimentalOptimizer.include` (which can be populated by plugins), so this should no longer be a problem.
