### ISSUE TITLE
Dynamic require of "util/" is not supported when using experimentalOptimizer

### ISSUE THREAD

**Issue by agualis** [vitest-dev/vitest#2941]
### Before
All tests were passing. 

### Added experimental optimizer
```ts
{
   experimentalOptimizer: { enabled: true },
},
```
### After
Error in 58 tests:

<img width="1512" alt="Screenshot 2023-03-01 at 10 07 05" src="https://user-images.githubusercontent.com/1316240/222093636-9b3135c1-f6bb-496a-bbf4-64e4f29f8120.png">

It looks like the problem is related to the usage of [ jest-extended matchers](https://github.com/jest-community/jest-extended).

### Reproduction

This is the branch where we face the issue: 

https://github.com/balancer-labs/frontend-v2/tree/bump-vitest

### System Info

```shell
System:
    OS: macOS 12.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 139.28 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Safari: 16.1
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0
    @vitest/coverage-c8: ^0.25.3 => 0.25.8
    vite: ^4.1.4 => 4.1.4
    vitest: ^0.29.2 => 0.29.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hrmJ** [comment]
Another package that seemed to produce this error for me was msw (https://github.com/mswjs/msw)

**Comment by asdfjkalsdfla** [comment]
I noticed that `@vitest/coverage-c8` was still at ^0.25.3 vs. ^0.29.2. What happens if you update that package to ^0.29.2 as well? In the past, I experienced this same issue when these were mismatched.

**Comment by sheremet-va** [comment]
Vitest 0.31.4 changes how `experimentalOptimizer` works. Now Vitest only optimizes dependencies inside `experimentalOptimizer.include` (which can be populated by plugins), so it should not optimize actual Node.js packages unless specified.
