### ISSUE TITLE
Support Import Assertions

### ISSUE THREAD

**Issue by mmamedel** [vitest-dev/vitest#2952]
### Clear and concise description of the problem

https://github.com/tc39/proposal-import-assertions

`import json from "./foo.json" assert { type: "json" };`

Vite 4 already supports it ootb! ([link](https://github.com/vitejs/vite/issues/4934)) Can we add it to Vitest too?

### Suggested solution

Update to Vite 4

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Just use Vite 4 with Vitest, Vitest doesn't process code by itself
