### ISSUE TITLE
Provide option to disable test case printf truncation

### ISSUE THREAD

**Issue by jasperdunn** [vitest-dev/vitest#2954]
### Clear and concise description of the problem

As a developer using Vitest I want to be able to use `test.each` in a way that helps me to understand what tests are breaking without losing some of the description.

I am using test cases via `test.each` to reduce the amount of test boilerplate code.

However when using `$description` I am getting only a truncated version of the text, which doesn't help determine which test is breaking.

Each test case object has `expected: ReturnType<Fn>` and `description: string` properties;

```
describe('getTimelineRange', () => {
  test('throws error when there are no rows', () => {
    expect(() => getTimelineRange([])).toThrowError();
  });

  test.each(getTimelineRangeCases)('$description', ({rows, expected}) => {
    expect(getTimelineRange(rows)).toEqual(expected);
  });
});
```

I am getting this as my test output:

<img width="387" alt="Screen Shot 2023-03-03 at 10 03 12 am" src="https://user-images.githubusercontent.com/26566353/222594628-fb02bd61-0f31-4bcc-8994-c808aae54fdc.png">

I'd prefer to get the full description, instead of a truncated version.

### Suggested solution

Could a setting be exposed to disable or set the truncation size?

### Alternative

For now I am considering either:

Prefixing a number
<img width="387" alt="Screen Shot 2023-03-03 at 10 11 25 am" src="https://user-images.githubusercontent.com/26566353/222596851-088dad17-d15c-4db6-911e-88a622d2e8a5.png">

or

Returning the entire object as a string via `%s` -> `test.each(getTimelineRangeCases)('%s', ({rows, expected}) => {`
<img width="793" alt="Screen Shot 2023-03-03 at 10 12 26 am" src="https://user-images.githubusercontent.com/26566353/222597086-c8769696-f167-40de-bd41-6cf042b8d4fb.png">

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
This is configurable with chai config: https://github.com/vitest-dev/vitest/issues/2791#issuecomment-1413347800

```ts
import { chai } from 'vitest'
chai.config.truncateThreshold = 100000
```

**Comment by jasperdunn** [comment]
Thanks!
Would love to have this in the vitest config itself :)
