### ISSUE TITLE
Import fails on node 14.16.0, works on node 14.17.0

### ISSUE THREAD

**Issue by danez** [vitest-dev/vitest#2956]
### Describe the bug

On Node.js 14.16.0 some of our tests fail with something similar to:

```
Error: Failed to load url ./path/to.js (resolved id: ./path/to.js) in /home/runner/work/edge-bundler/edge-bundler/node/stage_2.test.ts. Does the file exist?
```

Is vitest/vite not working on 14.16.0? If so should we update the engines field in the next 0.x version? Or should this work?

Failing (14.16.0):
https://github.com/netlify/edge-bundler/actions/runs/4324526320/jobs/7549469085

Working (14.17.0):
https://github.com/netlify/edge-bundler/actions/runs/4324542665/jobs/7549507918

### Reproduction

https://github.com/danez-labs/vitest-node-14

`nvm install 14.16.0 && npm i && npm test`

### System Info

```shell
gitpod /workspace/vitest-node-14 (main) $ npx envinfo --system --npmPackages '{vitest,@vitest/*,vite,@vitejs/*}' --binaries --browsers
npx: installed 1 in 1.117s

  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 AMD EPYC 7B13
    Memory: 10.97 GB / 62.80 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  npmPackages:
    vite: 4.1.4 => 4.1.4 
    vitest: 0.29.2 => 0.29.2 
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Personally, I don't think the version should matter here. Looks like a bug or regression.

**Comment by danez** [comment]
All I found so far is that on 14.16.0 the `id` that vitest/vite is trying to resolve is  `./format/javascript.ts` whereas on node 14.17.0+ this is `/src/format/javascript.ts`. So to me it seems that the transform does something different on these node versions? Is there a transform happening for the imports?

**Comment by sheremet-va** [comment]
> All I found so far is that on 14.16.0 the `id` that vitest/vite is trying to resolve is `./format/javascript.ts` whereas on node 14.17.0+ this is `/src/format/javascript.ts`. So to me it seems that the code transforms do something different on these node versions? Is there a transform happening for the imports?

Yes, Vite preprocesses all files and changes file paths.
