### ISSUE TITLE
Vitest cofig types not working properly

### ISSUE THREAD

**Issue by Llois41** [vitest-dev/vitest#2958]
### Describe the bug

Hi there,

I'm starting a new project and want to give `vitest` a chance for running my tests. However I'm running into some problems concerning the types of the vitest config.

```typescript
// vitest.config.ts
import { defineConfig } from 'vitest/config';
import Vue from '@vitejs/plugin-vue';

export default defineConfig({
    plugins: [Vue()], // TS2322: Type 'Plugin_2' is not assignable to type 'PluginOption'.
    test: {
        globals: true,
        environment: 'jsdom',
    },
});
```

However in my `vite.config.ts` this works fine

```typescript
// vite.config.ts
import { defineConfig } from 'vite';
import Vue from '@vitejs/plugin-vue';

export default defineConfig({
    plugins: [Vue()], // no TS error
});
```

If I switch to importing `defineConfig` from `vite` and add the [triple slash type reference](https://vitest.dev/config/#configuration) in my `vitest.config.ts` the error on the plugin goes away but I still get the following error:

```
TS2345: Argument of type '{ plugins: Plugin_2[]; test: { globals: boolean; environment: string; }; }' is not assignable to parameter of type 'UserConfigExport'.   Object literal may only specify known properties, and 'test' does not exist in type 'UserConfigExport'.
```

Am I missing something obviuos?

### Reproduction

some more files for context

`tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "bundler",
    "outDir": "build/js",
    "noUnusedLocals": true,
    "allowImportingTsExtensions": true,
    "noEmit": true,
    "esModuleInterop": true,
    "types": []
  },
  "include": [
    "**/*.ts",
    "**/*.js",
    "**/.*.js",
    "**/*.mjs",
    "**/*.json",
    "**/*.vue",
  ]
}
```

`package.json`
```
{
  "name": "b-informed",
  "version": "0.0.1",
  "type": "module",
  "packageManager": "yarn@3.3.1",
  "scripts": {
    "test": "vitest"
  },
  "dependencies": {
    "vue": "3.2.47",
    "vue-router": "4.1.6"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "4.0.0",
    "@vue/test-utils": "2.3.0",
    "jsdom": "21.1.0",
    "typescript": "5.0.0-beta",
    "vite": "4.1.4",
    "vitest": "0.29.2"
  }
}
```

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.98 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: 3.3.1 - ~/.nvm/versions/node/v18.14.0/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
  Browsers:
    Safari: 16.3
  npmPackages:
    @vitejs/plugin-vue: 4.0.0 => 4.0.0 
    vite: 4.1.4 => 4.1.4 
    vitest: 0.29.2 => 0.29.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You have several Vite packages installed. Check your package.json

**Comment by Llois41** [comment]
@sheremet-va What do you mean with "several vite packages" exactly? My `package.json` does not really differ from the one in the [examples directory](https://github.com/vitest-dev/vitest/blob/main/examples/vue/package.json).

**Comment by sheremet-va** [comment]
> My package.json does not really differ from the one in the [examples directory](https://github.com/vitest-dev/vitest/blob/main/examples/vue/package.json?rgh-link-date=2023-03-04T11%3A24%3A12Z).

I meant package-lock. Your package manager installed several independent Vite versions, you need to figure out why. You can use `npm why` command for this.

**Comment by Llois41** [comment]
Ah, thanks. After deleting the `yarn.lock` and re-running yarn it works now. Thanks for the quick help. Hope vitest will be as fast ;)
