### ISSUE TITLE
Docs: Reporter Guide

### ISSUE THREAD

**Issue by patak-dev** [vitest-dev/vitest#296]
### Clear and concise description of the problem

See https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/types/reporter.ts

### Suggested solution

A new guide

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by mitchelvanbever** [comment]
Will take a look 👍

**Comment by mitchelvanbever** [comment]
Got sidetracked (with #429), so free to be picked up as we've now got the tap reporter as well 🚀

**Comment by antfu** [comment]
I am not so sure we should document the reporter API, as average users won't touch that. I would think a `Reporters Guide` is more useful than the API docs (as TS already served as a good docs for developers)

**Comment by mitchelvanbever** [comment]
> I am not so sure we should document the reporter API, as average users won't touch that. I would think a Reporters Guide is more useful than the API docs (as TS already served as a good docs for developers)

Yeah I agree, I believe the issue is about making a "guide" covering basic usage (like we have for mocking). 

If we were to add additional information describing the API we would add to the current section in "config" I would assume.
