### ISSUE TITLE
Transform Plugins with `enforce: 'pre'` break stack traces

### ISSUE THREAD

**Issue by alexlafroscia** [vitest-dev/vitest#2960]
### Describe the bug

I am developing Vite plugin that performs some transformations on the source files of our tests. Since introducing this plugin, I have noticed that stack traces for errors in our tests no longer work as expected.

Working with some publicly-available packages and messing with their configuration, I was able to determine the source of the error: it seems like plugins that transform file contents that run with `enforce: 'pre'` will break the stack traces of errors in the tests.

In the attached reproduction project, I have added the official [`@rollup/plugin-strip`](https://github.com/rollup/plugins/tree/bc5cf91a042b88e14a1da9ba25f501d92591ca8a/packages/strip) since it works very similar to my own plugin under-the-hood (and can show the same problem).

If I apply that plugin normally -- where `enforce` is not set at all -- and cause an error in my tests, I see exactly where the exception took place.

<img width="648" alt="CleanShot 2023-03-04 at 14 50 19@2x" src="https://user-images.githubusercontent.com/1645881/222926124-9f8bd3a3-d3d8-44c7-b6cd-5ee5e793a587.png">

If I explicitly set `enforce: 'pre'` on the plugin and run the tests again, however, the pointer to exactly where the error happened disappears. In this case, there's no pointer at all, but in longer files it sometimes shows a pointer to the incorrect location instead. I think it has to do with some kind of source-map offset being applied that, in this case with a small test, ends up outside the bounds of the file altogether, resulting in no pointer at all

<img width="652" alt="CleanShot 2023-03-04 at 14 50 36@2x" src="https://user-images.githubusercontent.com/1645881/222926171-61431bf9-f044-4015-8fcd-8ab8b29726c3.png">

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-7jynzx?file=vite.config.ts

In the `vite.config.ts` the `enforce: 'pre'` configuration can be commented out to demonstrate the affect of the issue; without it, the exception shows the correct pointer to the error. With the line present, though, that pointer breaks.

### System Info

```shell
  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitest/ui: latest => 0.29.2 
    vite: latest => 4.1.4 
    vitest: latest => 0.29.2 
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Plugins are responsible for providing correct source maps.
