### ISSUE TITLE
`No test suite found` on windows for `v0.28.5+`

### ISSUE THREAD

**Issue by xsjcTony** [vitest-dev/vitest#2962]
### Describe the bug

Hey, I'm running vitest via npm scripts on Windows, which results in no test suite found for all test files.

It might be related to https://github.com/vitest-dev/vitest/issues/2020 since it's working for me if I run the command in the docker environment which is WSL (I guess, not sure). But I still want it to be runnable locally, since it's way too slow in the Docker...

Downgrading to `v0.28.4` solves the issue, which means the problem only exists for version `v0.28.5` and later (I suspect some changes caused this in `v0.28.5` release, doubting #2819 or #2858) ***(For screenshots of `v0.28.4` and `v0.28.5` please see below)***

![image](https://user-images.githubusercontent.com/45784210/222996920-527d75bc-f09f-49fc-bc53-9ea46ee4ff83.png)

Just so you know, I don't have administrator privilege in my local environment, I'm not sure if that's causing the issue. In the Docker environment, I have all access and it's working perfectly.

But just like I said, since v0.28.4 is working as expected, there's no reason it's not working after v0.28.5 in the exact same machine and environment, there must be some changes in that release caused this issue :(

Thanks for inspecting that, appreciate it.

### Reproduction

https://github.com/xsjcTony/vitest-bug-repord

Please clone and run

```
npm install
npm run test:unit
```
---

The original issue is #2921 but since it has been marked as "Need Reproduction" and closed automatically, so I have to open a new issue here. Sorry for the inconvience.

### System Info

```shell
  System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 14.60 GB / 31.69 GB
  Binaries:
    Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (110.0.1587.63)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitest/coverage-c8: 0.29.2 => 0.29.2
    @vitest/coverage-istanbul: 0.29.2 => 0.29.2
    @vitest/ui: 0.29.2 => 0.29.2
    vite: ^4.1.4 => 4.1.4
    vitest: 0.29.2 => 0.29.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by xsjcTony** [comment]
Just so you know, I don't have administrator privilege in my local environment, I'm not sure if that's causing the issue. In the Docker environment, I have all access and it's working perfectly.

But just like I said, since `v0.28.4` is working as expected, there's no reason it's not working after `v0.28.5` in the exact same machine and environment, there must be some changes in that release caused this issue :(

Thanks for inspecting that, appreciate it.

**Comment by xsjcTony** [comment]
This is the screenshot for `v0.28.4` (working) and `v0.28.5+` (not working, using `v0.28.5`, but the same applies to any newer versions)

`v0.28.4`
![image](https://user-images.githubusercontent.com/45784210/222997053-e1574742-5c0d-4f57-82e1-6b84709e472b.png)

`v0.28.5`
![image](https://user-images.githubusercontent.com/45784210/222997087-7378e40f-7899-4cdc-98e5-7f14e036bdac.png)

`v0.29.2`
![image](https://user-images.githubusercontent.com/45784210/222997147-0a1707bd-2a31-453d-b48a-cf311d646ce0.png)

**Comment by xsjcTony** [comment]
Any update on this? really need the help... :(

**Comment by xsjcTony** [comment]
@sheremet-va Hey, sorry to bother you as I know you are busy and really appreciate the work done by the Vitest Team.

Is there any chance this could be inspected? As I can see it's still an issue in `v0.29.3`.

This is currently causing big trouble for me to use the latest version of Vitest, and someone else reacted with emojis as well so I guess it's not only me.

Thanks for that.

**Comment by AriPerkkio** [comment]
@xsjcTony I don't have Windows machine available but hopefully we could reproduce this issue on Windows CI. 

Could you try to reduce your minimal setup a bit more:
- Remove usage of `describe.concurrent`
- Remove `test.includes` from `vitest.config.ts`
- Add `test.watch: false` to `vitest.config.ts`
- Remove any unnecessary file, e.g. `public/`, `*.html`, `vite-env.d.ts`

Maybe steps above can narrow down the issue to a specific feature of Vitest.

**Comment by xsjcTony** [comment]
@AriPerkkio I think I've got the cause.

Before I explain, here's my environment.

1. I'm using Windows 11
2. I'm using the `Terminal` App
![image](https://user-images.githubusercontent.com/45784210/225767660-ac469167-2b6f-422e-94ca-9898d6e4abf4.png)

---

So my real test project path is `c:\Dev\test` (focus on this capital `D`)

but if I enter `cd c:\dev\test`, it will also work:
![image](https://user-images.githubusercontent.com/45784210/225767862-0779d32c-27c6-4158-80b2-0b17e3abefe3.png)

And things become weird. I'm not sure if the issue is
- limited to `Vitest` only, OR
- the way `NodeJS` resolves paths, OR
- just a common windows path system issue

As you can see in the screenshot below, the way `Vitest` (or NodeJs under the hood, I'm not sure) resolves the path is case sensitive, but the `Terminal` App itself (or the Windows System) doesn't care about it.

![image](https://user-images.githubusercontent.com/45784210/225768398-1e371276-c713-4847-bc54-c637fce71406.png)
![image](https://user-images.githubusercontent.com/45784210/225768345-ebfecb6d-7db0-4acb-bfc9-d5e6203e0abe.png)

So I think, if `Vitest` relies on `NodeJS`'s native path system to resolve test file paths, then I guess nothing we can do and we can just close this issue, or we can mention to care about this somewhere in the doc.

Otherwise, please inspect.

Thanks

**Comment by xsjcTony** [comment]
I believe using `pathe` in `v0.28.5`'s change likely causes the problem:

 https://github.com/vitest-dev/vitest/blob/d4d04257c0c47f0acd7e508fbac74d0a57330a58/packages/vitest/src/runtime/entry.ts#L3
 
I can't find any documentation about the case sensitivity when this package resolves file path, but since it's the only change regarding to path system from `v0.28.4` to `v0.28.5`, so it might be the issue.

cc @sheremet-va

**Comment by xsjcTony** [comment]
Confirmed the same things happens in Windows 10

**Comment by xsjcTony** [comment]
@sheremet-va Thanks for inspecting. Can you please follow the following steps, as it reproduced the issue for me on three different windows machines:

1. open PowerShell (no matter in Terminal App or not)
2. run `cd c:\users\name\documents\work\vitest-bug-repord` (Please note it's all `lowercase`)
3. run the test

**Comment by sheremet-va** [comment]
> @sheremet-va Thanks for inspecting. Can you please follow the following steps, as it reproduced the issue for me on three different windows machines:
> 
> 1. open PowerShell (no matter in Terminal App or not)
> 2. run `cd c:\users\name\documents\work\vitest-bug-repord` (Please note it's all `lowercase` and please replace `name` with your username I guess)
> 3. run the test

Works for me:

```
PS C:\Users\name> cd c:\users\name\documents\work\vitest-bug-repord
PS C:\users\name\documents\work\vitest-bug-repord> npm run test:unit
```

**Comment by xsjcTony** [comment]
I'm not getting it... :(

![Snipaste_2023-03-18_07-46-10](https://user-images.githubusercontent.com/45784210/226039886-1373205c-6316-40e1-9717-f219c6a05ff1.png)

The node version of my machines which can reproduce this is `v16.18.0` and `v18.14.0`, I'm not sure if this matters, but just to give more details.

If really no one in the team can reproduce it... I guess nothing we can do :((((. Since all I need to do is to make sure the path matches the actual case, although it's a little bit annoying but at least it's not a show stopper.

**Comment by xsjcTony** [comment]
Looks like it's a similar issue, but I've no idea if the root cause can be relevant. https://github.com/vitejs/vite/issues/12923

**Comment by sheremet-va** [comment]
I think it is fixed. If not, feel free to comment to reopen the issue.
