### ISSUE TITLE
vi.doMock seems not to be working at all

### ISSUE THREAD

**Issue by luckylooke** [vitest-dev/vitest#2967]
### Describe the bug

I've created new Vue app by `npm init vue@latest` including ts and vitest, excluding other features, to get clean repo for reproduction, then I take code from `doMock` [docs](https://vitest.dev/api/vi.html#vi-domock), applied it to hello world and it is not called at all (I've put console.log inside).

### Reproduction

https://github.com/luckylooke/vitestDoMockReproduction
reproduction in test file:
https://github.com/luckylooke/vitestDoMockReproduction/blob/main/src/components/__tests__/HelloWorld.spec.ts

### System Info

```shell
System:
    OS: macOS 12.6.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 66.64 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.1/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0.1
    Safari: 16.3
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0 
    vite: ^4.1.4 => 4.1.4 
    vitest: ^0.29.1 => 0.29.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`doMock` mocks imports that are made after it's been called. You don't import anything in your tests, so it's not called. Use `vi.mock`, if you need to mock imports before they are made (like top-level imports). Documentation: https://vitest.dev/api/vi.html#vi-mock

**Comment by luckylooke** [comment]
I can't use `vi.mock` as I need to share some outside context, therefore I need `vi.doMock`.

I have edited example repo, using `increment` import before `vi.doMock` and still no change, not getting mocked.

```ts
import { describe, it, expect, beforeEach, vi } from 'vitest';

import { mount } from '@vue/test-utils';
import HelloWorld from '../HelloWorld.vue';
import { increment } from '../increment';
console.log('using increment', increment(1));

describe('HelloWorld', () => {
  let mockedIncrement = 100;

  beforeEach(() => {
    // you can access variables inside a factory
    vi.doMock('../increment', () => ({ increment: () => {
      console.log('>>>>>>>>>> doMock called?');
      return ++mockedIncrement;
    }}));
  });

  it('renders properly', () => {
    const wrapper = mount(HelloWorld, { props: { msg: 'Hello Vitest' } });
    expect(wrapper.text()).toContain('Hello Vitest');
  });
});
```
output in console:
```cli

 RERUN  src/components/__tests__/HelloWorld.spec.ts x12

stdout | unknown test
using increment 2

stdout | src/components/__tests__/HelloWorld.spec.ts > HelloWorld > renders properly
increment 6
increment 16
increment 26
increment 36

 ✓ src/components/__tests__/HelloWorld.spec.ts (1)

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  08:13:51
   Duration  102ms


 PASS  Waiting for file changes...
       press h to show help, press q to quit
```

**Comment by luckylooke** [comment]
@sheremet-va please reopen, as it still does not work as expected.

**Comment by luckylooke** [comment]
I am really sorry but I still don't understand how one can use doMock to mock dependency of tested module.

I have put import into test to import it again after doMock, but it is already imported inside component HelloWorld which is mounted after doMock call 🤷‍♂️ 

```
  it('renders properly', async () => {
    await import('../increment') // <---- importing again
    const wrapper = mount(HelloWorld, { props: { msg: 'Hello Vitest' } });
    expect(wrapper.text()).toContain('Hello Vitest');
  });
  ```
  
  still not mocked 😞

**Comment by luckylooke** [comment]
I will create same reproduction but in jest to compare results, as I was using jest before and I remember that I was using doMock for mocking component dependencies.

**Comment by sheremet-va** [comment]
You need to import the component "HelloWorld" again and use it. Your top-level imports are already evaluated when you call `vi.doMock`:

```ts
  it('renders properly', async () => {
	const { default: HelloWorld } = await import('./HelloWorld.vue')
    const wrapper = mount(HelloWorld, { props: { msg: 'Hello Vitest' } });
    expect(wrapper.text()).toContain('Hello Vitest');
  });
```

Please, read the documentation about `vi.doMock` and `vi.mock`.

**Comment by luckylooke** [comment]
I have read that already before I have created this issue, but it seems that I have made different assumptions how it works. Thank you for your help and your patience too ❤️
