### ISSUE TITLE
vitest does not inject import.meta.env correctly and makes it undefined when .env file is present

### ISSUE THREAD

**Issue by smeng9** [vitest-dev/vitest#2970]
### Describe the bug

We have a third party dependency package that uses `import.meta.env.VITE_XXX` for some environment variable.

We did not encounter any problem with `vite dev` and `vite build`, however in `vitest`, this variable becomes undefined only for that package.

> test/importmeta.test.tsx
> TypeError: 𝐢𝐦𝐩𝐨𝐫𝐭.meta.env is undefined
> - /https:/vitestdevvitestrrt4y9-fgre.w-corp.staticblitz.com/blitz.50571018ddcbc3a25df8994336c28d766f1073a1.js:15:303697

I have traced down the issue and created a minimal reproducible example. 
When the third party package's `package.json` has a `"type": "module"` field, vitest cannot correctly inject the `import.meta.env` variable
When we remove the `"type": "module"` field, all test cases passes.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-rrt4y9?file=another-package%2Fpackage.json&initialPath=__vitest__

First create a environment variable in .env file,
Then install dependencies and start the test, the test will fail with import.meta.env not defined,

Remove the "type": "module" line,
Then reinstall dependencies and start the test, all tests will pass.

### System Info

```shell
System:
    OS: Linux 5.19 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz
    Memory: 2.57 GB / 7.22 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.12.0 - /usr/bin/node
    Yarn: 3.4.1 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Firefox: 110.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Externalized files are processed by the native Node for performance reasons. If you rely on Vite features in your external packages, you need to inline it using `test.deps.inline` config option.
