### ISSUE TITLE
Crashes with libc++abi: terminating with uncaught exception of type Napi::Error

### ISSUE THREAD

**Issue by olalonde** [vitest-dev/vitest#2972]
### Describe the bug

I've been getting a process crash using vitest when using either bcrypt or argon2 (so I assume it's not a bug with either but something that vitest is doing).

```
libc++abi: terminating with uncaught exception of type Napi::Error
```

I assume it's an issue with tinypool? https://github.com/tinylibs/tinypool/issues/48

Does vitest use multiples processes when threads are disabled?

### Reproduction

I couldn't easily reproduce the issue. I believe it has something to do with multithreading and usage of native libraries like bcrypt or argon2. 

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (8) arm64 Apple M1
    Memory: 111.63 MB / 16.00 GB
    Shell: 5.8 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 19.6.0 - ~/Library/Caches/fnm_multishells/72546_1678121779252/bin/node
    npm: 9.4.0 - ~/Library/Caches/fnm_multishells/72546_1678121779252/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Safari: 15.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> Does vitest use multiples processes when threads are disabled?

Since 0.29.0, Vitest uses Worker Threads by default. If `threads` is `false`, or `--no-threads` flag is passed, it fallbacks to `child_process`.

**Comment by servettonga** [comment]
I had this with bcrypt and finally switched to argon2. But now, I get it while asserting async function to save an entry into mongodb. I will share if I can reproduce it.

**Comment by sheremet-va** [comment]
Use `--pool=forks` if you experience segfaults. Some native packages don't support running in separate threads.
