### ISSUE TITLE
Allow less verbose output

### ISSUE THREAD

**Issue by johtso** [vitest-dev/vitest#2976]
### Clear and concise description of the problem

Currently, if a test fails, I see the error a total of 3 times, one time being a complete serialized representation of the error.

The most problematic of these is the serialized error.

In my use-case, I happen to be using Zod who's Error objects can be very large.

When every test run output ends with a serialized representation of a Zod error, I end up having to scroll up a page or more until I can see the normal vitest output.

This is what the output looks like for me:
<img width="737" alt="Screenshot_2023-03-07 21 18 53_AUmwcy" src="https://user-images.githubusercontent.com/830800/223561587-6a4c7b85-2829-4f30-97b6-ac422fa01314.png">

### Suggested solution

Would it make sense to have a flag making the output less noisy?

This seems to be the offending line: https://github.com/vitest-dev/vitest/blob/18d8019999a74c9b29dd4ec7a0d9e2a473f677d1/packages/vitest/src/node/error.ts#L206

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
> I see the error a total of 3 times

Provide a reproduction for this claim please. Current solution is working correctly and is compatible with how Node.ja prints errors.

**Comment by johtso** [comment]
@sheremet-va See screenshot below. The `error.message` is shown once under "DEV", once under "FAIL", and then the entire serialized error is shown at the end.

> Current solution is working correctly and is compatible with how Node.js prints errors

I'm not saying this is a bug, I'm saying that the current logging behaviour is making it very awkward to use, and I can't find any existing functionality allowing the user to limit the verbosity. My only solution was to jump into `node_modules` and comment out the line.

![image](https://user-images.githubusercontent.com/830800/223575402-4427ceab-94cb-49c6-98bb-f50fba033780.png)

**Comment by leanne1** [comment]
I use Nock and if nock fails to match a request the serialized output across a few failing tests can be so huge it can take half a minute to print it out and it cripples the terminal and i have to close the tab. I would also like to see flag to make this optional.

**Comment by hi-ogawa** [comment]
We could pass `truncate` option for `inspect(errorProperties, { truncate: chaiConfig.truncateThreshold })`, but I'm not sure if we should reuse current default 40 `truncateThreashold` as it gets too small.

https://github.com/vitest-dev/vitest/blob/fee7d8be9d6e6f710270600ae91fa35d861b7075/packages/vitest/src/node/error.ts#L259-L260

I think I understand the annoyance of huge `inspect` output, but no one has provided a reproduction for such worst case yet. It always helps to have a runnable example, so that we can understand and evaluate the issue accurately.

**Comment by timovv** [comment]
Just wanted to add another perspective here: we have a use case where the Error object that gets thrown includes information about the HTTP request that was made that caused the error. This request object can include sensitive information such an access token, which we really don't want showing up in our CI logs. The normal Error toString implementation doesn't show the whole content of the Error object, but this serialized error output dumps the whole content of the object to console, including the sensitive information.

We are looking for a way to suppress this verbose `Serialized Error` output in our pipelines. Some kind of option to disable that would be fantastic.

**Comment by sheremet-va** [comment]
Did you try Vitest 1.6.0?

**Comment by timovv** [comment]
Yeah, I am using 1.6.0. I just saw in the CHANGELOG the new functionality of using `toJSON` to serialize the error, which I assume is what you are referring to? We will investigate overriding that.

**Comment by sheremet-va** [comment]
> Yeah, I am using 1.6.0. I just saw in the CHANGELOG the new functionality of using `toJSON` to serialize the error, which I assume is what you are referring to? We will investigate overriding that.

Yes, we iterate over returned properties now (if it's an object)
