### ISSUE TITLE
Calling Vue exposed method which uses refs

### ISSUE THREAD

**Issue by Ericlm** [vitest-dev/vitest#2979]
### Describe the bug

I'm currently working on a Vue 3 project using Composition API, and I'm having issue with calling a method exposed with the `defineExpose` macro.  
I created a repo with a minimal Vue project where:
- `App.vue` has a `CustomDialog` in is template, and calls the `showDialog` of the `CustomDialog`
- `CustomDialog` exposes the `showDialog` method, which simply calls `showModal` on an `HTMLDialogElement`. This element is made available with a ref.
- `CustomDialog.spec.ts` is accessing the wrapper around the component and tries to call the `showDialog` method. 

The issue is that even if the method `showDialog` can be called within the test, the `showModal` method contained within the `showDialog` is not called ; vitest throws an error saying `TypeError: customDialog.value.showModal is not a function`.

### Reproduction

I created a [repository to trigger the issue.](https://github.com/Ericlm/vitest-refs)

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 350.19 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.asdf/installs/nodejs/18.14.0/bin/node
    npm: 9.3.1 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0.1
    Safari: 16.3
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0 
    vite: ^4.1.4 => 4.1.4 
    vitest: ^0.29.1 => 0.29.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`showModal` is not supported in JSDOM: https://github.com/jsdom/jsdom/issues/3294
