### ISSUE TITLE
import of a cjs library fails

### ISSUE THREAD

**Issue by emilioSp** [vitest-dev/vitest#2987]
### Describe the bug

Hello 👋🏽 

I'm trying to migrate our tests from `jest` to `vitest`, but I'm stuck. 
Before giving up I'd like to report the issue I have experienced.

I have tried something with `moment` but the problem is related to every cjs lib that exports a function. (moment is just an example)

The error I get is
```
TypeError: __vite_ssr_import_0__ is not a function
```

and it is due to the import
```
import * as moment from 'moment'
```

In the repro attached below, it seems that `vitest` doesn't follow the `tsconfig` module code generation directive (which unfortunately is `commonjs`), whereas `jest` does.

For organization constraints I cannot:
- enable `esModuleInterop` in the tsconfig
- rewrite import as require like `const moment = require('moment') as typeof import('moment')`

I tried to disable `interopDefault` in the `vitest.config` but it still fails.

Thanks for your help.

### Reproduction

- https://stackblitz.com/edit/node-i14oxw?file=index.js
- https://github.com/emiliosp/vitest-vs-jest

```
yarn vitest
```

```
yarn jest
```

### System Info

```shell
System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 21.50 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
There is no way to enable this except by using `esModuleInterop`.

`import * as moment from 'moment'` where `moment` is a function is not a valid ESM syntax. This should always be a module object.

**Comment by sheremet-va** [comment]
Vitest uses Vite, which in term uses esbuild to transform TypeScript files. esbuild treats imports as ESM imports, because it doesn't have information about types. (It doesn't know that this package is CJS package with `export =` syntax).

More about that here: https://esbuild.github.io/content-types/#es-module-interop

**Comment by sheremet-va** [comment]
One of the possible solutions is to use other transpilers like [unplugin-swc](https://github.com/egoist/unplugin-swc). I did not test it, but I assume it might treat this differently. You can also create your [own plugin](https://vitejs.dev/guide/api-plugin.html) to transform imports into the ones compatible with Node ESM:

```ts
export default {
  plugins: [
    {
       name: 'moment-inport',
       enforce: 'pre',
       transform(code) {
          if(code.includes('import * as moment') {
            return { code: code.replace("import * as moment from 'moment'", "import * as __moment from 'moment';const moment = __moment.default;") }
          }
       }
     }
  ]
}
```

**Comment by emilioSp** [comment]
ok! thanks!
