### ISSUE TITLE
Mocked default export shows up as <default> element instead of actual mock

### ISSUE THREAD

**Issue by zachbryant** [vitest-dev/vitest#2988]
### Describe the bug

Mocking a default export makes the snapshot of the element show `<default />`. Didn't see anything in the docs on mocking default exports, so I followed the jest pattern.

mock pattern:
```ts
vi.mock("./def.tsx", () => ({
  Def: () => <div>Def</div>,
  default: () => <div>Should not be called default in snapshot</div>,
}));
```
snapshot:

```
// Vitest Snapshot v1, https://vitest.dev/guide/snapshot.html
exports[`matches snapshot 1`] = `
<div>
  <default />
</div>
`;
```

expected:

```
// Vitest Snapshot v1, https://vitest.dev/guide/snapshot.html
exports[`matches snapshot 1`] = `
<div>
  <div>Should not be called default in snapshot</div>
</div>
`;
```

### Reproduction

Here's a minimal repro

Check how the snapshot produced with `yarn test` shows the issue.

https://github.com/zachbryant/vitest-repro

### System Info

```shell
$ npx envinfo --system --npmPackages '{vitest,@vitest/*,vite,@vitejs/*}' --binaries --browsers
npx: installed 1 in 1.827s

  System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD EPYC 7763 64-Core Processor
    Memory: 33.05 GB / 64.00 GB
  Binaries:
    Node: 14.20.1 - ~\AppData\Local\Volta\tools\image\node\14.20.1\node.EXE
    Yarn: 1.22.11 - ~\AppData\Local\Volta\tools\image\yarn\1.22.11\bin\yarn.CMD
    npm: 6.14.17 - ~\AppData\Local\Volta\tools\image\node\14.20.1\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (110.0.1587.57)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitejs/plugin-react: ^3.1.0 => 3.1.0
    vite: ^4.1.4 => 4.1.4
    vitest: 0.29.2 => 0.29.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Isn't it just how ShallowRenderer works? If I remove mocking, it is still not unwrapped.

https://reactjs.org/docs/shallow-renderer.html

**Comment by sheremet-va** [comment]
Seems like it's intended behaviors. If not, feel free to reopen issue.
