### ISSUE TITLE
Support debuggable source maps

### ISSUE THREAD

**Issue by sedlakr** [vitest-dev/vitest#2994]
### Describe the bug

Bug described in webstorm youtrack
https://youtrack.jetbrains.com/issue/WEB-58532

When debugger is placed into test. After breakpoint catch in the IDE (Webstorm, IDEA, VSCode), the imported function cannot be evaulated.
![image](https://user-images.githubusercontent.com/219779/224260666-ff60d3c4-308b-40d2-b38c-d6a91fe1b6ff.png)

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-dvd2yl?file=test/basic.test.ts

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
    Memory: 8.20 GB / 31.79 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (110.0.1587.63)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest doesn't generate source maps or process code on its own. Vite does, so I recommend opening an issue there.

**Comment by sedlakr** [comment]
OK.  Thanks for clarification.

**Comment by closesimple-wl** [comment]
I kind of reported this upstream: https://github.com/vitejs/vite/discussions/12691
