### ISSUE TITLE
type tests (e.g. `expectTypeOf`) are not counted towards assertions

### ISSUE THREAD

**Issue by moltar** [vitest-dev/vitest#3002]
### Describe the bug

Type tests (e.g. `expectTypeOf`) are not counted towards assertions.

Get error:

> Error: expected number of assertions to be 1, but got 0

### Reproduction

```ts
it('should type guard', () => {
  expect.assertions(1);
  expectTypeOf(true).toMatchTypeOf<boolean>();
});
```

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 4.30 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.1 - ~/Library/Caches/fnm_multishells/2710_1677676673645/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.3.1 - ~/Library/Caches/fnm_multishells/2710_1677676673645/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 110.0.1
    Safari: 16.3
  npmPackages:
    vitest: 0.28.4 => 0.28.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
With the current implementation, type tests are not expected to be actually running with runtime tests. You would define a type test in a separate file
