### ISSUE TITLE
Stack trace points to incorrect file on error

### ISSUE THREAD

**Issue by DanHulton** [vitest-dev/vitest#3004]
### Describe the bug

When running tests that encounter an error in a required file, the generated trace does not point to the correct file.

Expected:

```
ReferenceError: boop is not defined
 ❯ test/main.test.js:5:12
 > src/main.js:2:9
      1| export function testFunc(x) {
      2|   return boop(x);
       |          ^
      3| }
```

Actual:

```
ReferenceError: boop is not defined
 ❯ Module.testFunc ../../../../../src/main.js:2:3
 ❯ test/main.test.js:5:12
      3| describe('Main test', () => {
      4|   it('should blow up here', () => {
      5|     expect(testFunc(5)).toBe(10);
       |            ^
      6|   });
      7| });
```

### Reproduction

1) Check out https://github.com/DanHulton/vitest-stack-sourcemap-repro
2) `yarn install`
3) `yarn test`

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 19.44 MB / 32.00 GB
    Shell: 3.5.1 - /usr/local/bin/fish
  Binaries:
    Node: 17.3.0 - /usr/local/bin/node
    Yarn: 3.3.1 - /usr/local/bin/yarn
    npm: 8.16.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 109.0
    Safari: 16.3
  npmPackages:
    vite: latest => 4.1.4
    vitest: latest => 0.29.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by obadakhalili** [comment]
I can handle this one.

**Comment by obadakhalili** [comment]
Yes, I figured this out as well. In fact, this makes sense because it is hard to not notice such an "obvious" bug unless it wasn't very frequent because most people use Vite with Vue (or another framework) and TypeScript.

**Comment by DanHulton** [comment]
Yeah, I'm developing a framework that uses Vue for the frontend, so I didn't notice this for a while, but I also wanted to use Vite for the backend API part of it as well, which is where I started running into this issue, and I was certain for the longest time that it was some configuration issue I had messed up.  Thanks for looking into this.

**Comment by obadakhalili** [comment]
No problem. I'll start working on a solution as soon as possible once I manage to find some time. Which is somewhat hard to do for a full-time student and an engineer 😅.

**Comment by DanHulton** [comment]
I hear ya.  It gets done when it gets done, no worries.

**Comment by obadakhalili** [comment]
❤️
