### ISSUE TITLE
MISSING DEP  Can not find dependency 'vite' on PNPM 7.29.x

### ISSUE THREAD

**Issue by Hurtak** [vitest-dev/vitest#3009]
### Describe the bug

When 
- you only have vitest in the dependencies, and no vite
- use PNPM

Running the tests
- succeeds on PNPM `7.28`
- fails in PNPM `7.29` with `MISSING DEP  Can not find dependency 'vite'`

### Reproduction

https://github.com/Hurtak/vitest-bug-repro

CI on 7.28 (OK) https://github.com/Hurtak/vitest-bug-repro/actions/runs/4413733229/jobs/7734553084
CI on 7.29 (FAIL) https://github.com/Hurtak/vitest-bug-repro/actions/runs/4413733229/jobs/7734552904

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz
    Memory: 5.92 GB / 6.78 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.19.1 - /opt/hostedtoolcache/node/16.19.1/x64/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /opt/hostedtoolcache/node/16.19.1/x64/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Chromium: 110.0.5481.0
    Firefox: 110.0.1
  npmPackages:
    vitest: 0.29.2 => 0.29.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fireairforce** [comment]
It seems that dependencies `vite` for vitest should be move from `"devDependencies"` to `"dependencies"` ?

**Comment by Hurtak** [comment]
@fireairforce That should not matter since I am doing `pnpm i` and not `pnpm i --prod`. I tried it right now to move it into dependencies and the result is the same.

**Comment by Hurtak** [comment]
@fireairforce they seem to be in `dependencies`

![Screenshot 2023-03-14 at 10 15 57](https://user-images.githubusercontent.com/6587821/224953478-a6bf8895-7b70-49d0-9e59-a5e534f6c7f2.png)

**Comment by fireairforce** [comment]
ooo sorry for i misread the `package.json` file for vitest

**Comment by sheremet-va** [comment]
Doesn't seem like this is a Vitest issue.
