### ISSUE TITLE
Invalid Characters in Path

### ISSUE THREAD

**Issue by olafurw** [vitest-dev/vitest#3013]
### Describe the bug

I updated to the new Storybook (v7 that's coming out) and ran my build suite and I got this error message.

Not sure if it's complaining about `virtual:` or `@storybook` but my bet is on `virtual:` since colons in windows paths can be weird. And I don't think storybook is generating that path.

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Path contains invalid characters: [the path to my project]\coverage\virtual:\@storybook\builder-vite
 ❯ checkPath node_modules/make-dir/index.js:16:18
 ❯ module.exports.sync node_modules/make-dir/index.js:108:2
 ❯ FileWriter.writeFile node_modules/istanbul-lib-report/lib/file-writer.js:184:16
 ❯ HtmlReport.onSummary node_modules/istanbul-reports/lib/html/index.js:364:44
 ❯ Visitor.value node_modules/istanbul-lib-report/lib/tree.js:38:38
 ❯ ReportNode.visit node_modules/istanbul-lib-report/lib/tree.js:86:21
 ❯ node_modules/istanbul-lib-report/lib/tree.js:92:19
 ❯ ReportNode.visit node_modules/istanbul-lib-report/lib/tree.js:91:28
 ❯ ReportTree.visit node_modules/istanbul-lib-report/lib/tree.js:127:24

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯Serialized Error: {
  "code": "EINVAL",
}
```

### Reproduction

Install the release candidate of the v7 of Storybook, don't add the generated folder in the `exclude` list and run vitest with `c8` as the coverage reporter.

The workaround is to add the `storybook-static` folder to the `exclude` list. 

### System Info

```shell
Windows 10
VSCode
Svelte project running vite and vitest
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
@olafurw I'm happy to help if you could provide a minimal reproduction case for this. I haven't heard of this kind of issue before and do not know what could be causing it yet.

**Comment by olafurw** [comment]
Been trying for a repo case, on StackBlitz it just sits when running `npm run test` and doesn't stop (let it run for 2 hours) and locally it doesn't happen.

Here's the StackBlitz if you're curious. Just npm run build and storybook:build and then npm run test, but it never finishes.

https://stackblitz.com/edit/vitejs-vite-ynloe9?file=package.json

**Comment by AriPerkkio** [comment]
`c8` does not work on Stackblitz due to web containers limitations. I'm unable to reproduce the issue locally using that project.

**Comment by olafurw** [comment]
Close for now until I have a better repo.
