### ISSUE TITLE
Vitest is scanning the entire directory despite adding include and exclude to config

### ISSUE THREAD

**Issue by abdul-alhasany** [vitest-dev/vitest#3018]
### Describe the bug

I am currently implementing vitest on a large repo (around 9GB of data). I have one test file:

```ts
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { expect, test } from 'vitest';
import packageJson from '../package.json';

test('That package.json contains all the exports from icons folder', () => {
	const filePath = fileURLToPath(import.meta.url);
	const directoryPath = path.dirname(filePath);
	console.log('>>>>>>>>', directoryPath);

	// Get icons folder path
	const iconsPath = path.join(directoryPath, '../icons');

	let icons = fs.readdirSync(iconsPath);
	const { exports } = packageJson;

	icons = icons.map((icon) => {
		return icon.replace('.js', '');
	});

	const exportsKeys = Object.keys(exports).map((key) => {
		return key.replace('./', '');
	});

	icons.forEach((icon) => {
		expect(exportsKeys, `Missing ${icon} in package.json exports`).to.include(icon);
	});
});
```

And this is my vitest.config.ts:
```ts
import { configDefaults, defineConfig } from 'vitest/config';

const updatedConfig = defineConfig({
	test: {
		include: ['test/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}'],
		exclude: [
			...configDefaults.exclude,
			'**/packages/**',
			'packages/**',
			'packages',
			'**/packages',
			'/packages',
		],
	},
});

export default updatedConfig;
```

When running the test it takes about **2minutes** for the the test to complete even though I added include/exclude data. When I remove packages folder (which is the large one). However, when I remove the folder it takes **472ms**. 

Also, when the test is re-run I get this error:
```bash
ATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF71BDB027F node_api_throw_syntax_error+175631
 2: 00007FF71BD35B66 v8::internal::wasm::WasmCode::safepoint_table_offset+63110
 3: 00007FF71BD36F22 v8::internal::wasm::WasmCode::safepoint_table_offset+68162
 4: 00007FF71C7D14C4 v8::Isolate::ReportExternalAllocationLimitReached+116
 5: 00007FF71C7BC822 v8::Isolate::Exit+674
 6: 00007FF71C63E66C v8::internal::EmbedderStackStateScope::ExplicitScopeForTesting+124
 7: 00007FF71C64B94D v8::internal::Heap::PublishPendingAllocations+1117
 8: 00007FF71C6489D7 v8::internal::Heap::PageFlagsAreConsistent+3367
 9: 00007FF71C63B107 v8::internal::Heap::CollectGarbage+2039
10: 00007FF71C651AC3 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath+2099
11: 00007FF71C65236D v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath+93
12: 00007FF71C661BA3 v8::internal::Factory::NewFillerObject+851
13: 00007FF71C353155 v8::internal::DateCache::Weekday+1349
14: 00007FF71C86EB61 v8::internal::SetupIsolateDelegate::SetupHeap+558193
15: 00007FF71C830FC5 v8::internal::SetupIsolateDelegate::SetupHeap+305365
16: 00007FF69CA0637A
```
It seems that vitest scans the folder no matter what the config is.

### Reproduction

https://github.com/abdul-alhasany/vitest-reproduction

Clone the repo and run these commands:
- `pnpm install`
- `pnpm update-submodules` (this step will take a while to download all the submodules)
- `pnpm test`

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5825U with Radeon Graphics
    Memory: 6.56 GB / 15.31 GB
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.41)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitest/coverage-c8: ^0.29.3 => 0.29.3 
    @vitest/ui: ^0.29.3 => 0.29.3 
    vitest: ^0.29.3 => 0.29.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Well, it still needs to scan the folder to see if it needs to be excluded 🤷🏻 You can specify `dir` option to narrow down the number of directories that will be scanned.

**Comment by abdul-alhasany** [comment]
> Well, it still needs to scan the folder to see if it needs to be excluded 🤷🏻 You can specify `dir` option to narrow down the number of directories that will be scanned.

That's what I thought, But given that packages is a top-level directory I assumed it will be ignored early without the need of reading its content.

I tried with `dir: 'test'` and also with adding this pattern `!**/packages` as suggested by [fast-glob](https://github.com/mrmlnc/fast-glob#how-to-exclude-directory-from-reading). Both solutions returned the same results as the first one (~ 2 minutes to process).

**Comment by ChrisPlease** [comment]
May be related: I have unit and integration tests separated: unit tests are next to the source: `/src/foo.ts` and `/src/foo.test.ts`, while integration tests are in their own directory: `/src/tests`.

My unit test config file lists includes:

```ts
include: [
  'src/**/*.test.ts',
  '!src/tests',
],
```

When I run unit tests with the unit test config file: `vitest -c vitest.config.unit.ts`, vitest will still run tests in the tests directory, which fails because integration tests are run in a separate (docker) environment that's not available.

**Comment by sheremet-va** [comment]
> My unit test config file lists includes:

You need to add a wildcard:

```
include: [
  'src/**/*.test.ts',
  '!src/tests/**/*',
],
```

**Comment by ChrisPlease** [comment]
it was something else: I was setting `coverage.include` instead of `include` 🤦

**Comment by abdul-alhasany** [comment]
Thanks for this. I looked at the code and solved the issue by adding `root` pointed to the a specific folder. This way the code only looked for `tsconfig.ts` inside that folder. My project does not have `tsconfig.ts` so it won't matter which folder I used as long as it is not the one with the large data.  This is not ideal but in my case it resolved the issue.
