### ISSUE TITLE
The prototype method `at` of Array is not a function

### ISSUE THREAD

**Issue by Plasticine-Yang** [vitest-dev/vitest#3021]
### Describe the bug

When I want to test the following code which using the `at` method of Array prototype, it is not work.

```ts
describe('happy path', () => {
  test('array at method', () => {
    const arr = [1]
    const el = arr.at(-1)
    expect(el).toBe(1)
  })
})
```

### Reproduction

There is no repositry, just run the simple code in node.

`src/index.test.ts`

```ts
describe('happy path', () => {
  test('array at method', () => {
    const arr = [1]
    const el = arr.at(-1)
    expect(el).toBe(1)
  })
})
```

Run with `npx vitest`

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 12.77 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.2 - ~/.nvm/versions/node/v14.21.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.21.2/bin/yarn
    npm: 9.4.2 - ~/.nvm/versions/node/v14.21.2/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.3
  npmPackages:
    vitest: ^0.23.4 => 0.23.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You are using a Node version that doesn't support `Array.ptototype.at`. Upgrade Node to at least [16.6.0](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at).
