### ISSUE TITLE
Not implemented: HTMLCanvasElement.prototype.getContext

### ISSUE THREAD

**Issue by RamonPessoa** [vitest-dev/vitest#3025]
### Describe the bug

I have a component that uses the canvas html tag, and when I try to run tests on it I get the following error:

Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)

and if i install it I get another error:

Module did not self-register

### Reproduction

use html canvas tag on a component and try to test the component with vitest

### System Info

```shell
System:
    OS: Linux 5.17 Pop!_OS 20.04 LTS
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 19.96 GB / 31.31 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.19.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.74
    Firefox: 108.0.2
  npmPackages:
    @vitejs/plugin-react: 1.3.2 => 1.3.2 
    vite: 2.6.13 => 2.6.13 
    vitest: ^0.29.2 => 0.29.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
See: https://github.com/vitest-dev/vitest/issues/740

Run with `--no-threads`

**Comment by zaalbarxx** [comment]
@sheremet-va Is this really the only possible option ? I assume that `--no-threads` make everything work with single thread making all the tests being much slower to process. I guess it is possible to somehow adress this since with Jest it does seem to work properly ?
