### ISSUE TITLE
mock is cached from test to test

### ISSUE THREAD

**Issue by cerealexx** [vitest-dev/vitest#3027]
### Describe the bug

I'm not sure if it's a bug or if I'm doing something wrong. Declaring a mock for an external module seems to cache its value for the rest of the tests, even if they are declared in isolation inside of each test scope.
I've tried to use `clearAllMocks` and `resetModules` in a `beforeEach` with no luck.

### Reproduction

In this couple of tests, the first works and the second fails because the `reactfire` mock value is cached from the first test and the second declaration doesn't overwrite the first one.
```
function getMockedAuth(type: 'admin' | 'user') {
  return {
    useUser: () => ({
      data: {
        uid: type,
      },
    }),
    useFirebaseApp: () => ({
      auth: () => ({
        currentUser: {
          uid: type,
        },
      }),
    }),
  };
}

beforeEach(() => {
  vi.resetModules();
  vi.clearAllMocks();
  cleanup();
});

describe('DashboardPage', () => {
  test('should render Backlog if user is admin', () => {
    vi.mock('reactfire', () => getMockedAuth('admin'));

    render(<DashboardPage />);

    expect(screen.getByText('Backlog')).toBeTruthy();
  });

  test('should not render Backlog if user is not admin', async () => {
    vi.mock('reactfire', () => getMockedAuth('user'));

    render(<DashboardPage />);

    expect(screen.queryByText('Backlog')).toBeNull();
  });
});
```

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 68.31 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Edge: 111.0.1661.44
    Firefox: 108.0.1
    Safari: 16.3
  npmPackages:
    @vitejs/plugin-react: ^2.1.0 => 2.1.0 
    vite: ^3.1.0 => 3.1.8 
    vitest: ^0.28.4 => 0.28.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`vi.mock` call is hoisted, so only one mock is called

**Comment by cerealexx** [comment]
@sheremet-va So is there something like `isolateModules` to mock different values of the same library? How can this be achieved with vitest?

**Comment by cerealexx** [comment]
Nevermind, I ended up splitting the cases into two files.

**Comment by Kosai106** [comment]
@sheremet-va is there really no other solution than to split the tests into multiple files? This is driving me insane having to get working so I won't have multiple files for what was supposed to be a simple test.

**Comment by cerealexx** [comment]
Lol... that would have been so helpful two months ago 😅

**Comment by Kosai106** [comment]
Couldn't for the life of me get `vi.doMock` to work as you describe @sheremet-va but *finally* got something working.

```tsx
import { useSession } from "@blitzjs/auth"

import HomePage from "pages/index"
import { render, screen } from "test/utils"

vi.mock("@blitzjs/auth", async () => {
  const actual = await vi.importActual<Record<string, unknown>>("@blitzjs/auth")
  return {
    ...actual,
    useSession: vi.fn(),
  }
})

describe("User state", () => {
  beforeEach(() => {
    vi.resetAllMocks()
  })

  test("does not render upload button when logged out", () => {
    ;(useSession as any).mockReturnValue({ userId: null, role: null, isLoading: false })

    render(<HomePage />)

    expect(screen.getByRole("button", { name: /sign up/i })).toBeInTheDocument()
    expect(screen.getByRole("button", { name: /create/i })).not.toBeInTheDocument()
  })

  test("renders upload button when logged in", () => {
    ;(useSession as any).mockReturnValue({ userId: 1, role: "USER", isLoading: false })

    render(<HomePage />)

    expect(screen.getByRole("button", { name: /sign up/i })).not.toBeInTheDocument()
    expect(screen.getByRole("button", { name: /create/i })).toBeInTheDocument()
  })
})
```
