### ISSUE TITLE
Incorrect code coverage reported in Svelte example

### ISSUE THREAD

**Issue by OskarPersson** [vitest-dev/vitest#3033]
### Describe the bug

When running the tests of the [Svelte example](https://github.com/vitest-dev/vitest/tree/main/examples/svelte), the test coverage is incorrectly reported with an uncovered line while simultaneously reporting 100% coverage an all statements, functions and lines:

```
$ yarn coverage
yarn run v1.22.19
$ vitest run --coverage

 RUN  v0.29.3 /home/oskar/git/vitest/examples/svelte
      Coverage enabled with c8

 ✓ test/basic.test.ts (1)
 ✓ test/hello.test.ts (2)

 Test Files  2 passed (2)
      Tests  3 passed (3)
   Start at  17:17:52
   Duration  1.13s (transform 88ms, setup 0ms, collect 342ms, tests 88ms)

 % Coverage report from c8
--------------|---------|----------|---------|---------|-------------------
File          | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
--------------|---------|----------|---------|---------|-------------------
All files     |     100 |        0 |     100 |     100 |
 Hello.svelte |     100 |        0 |     100 |     100 | 6
--------------|---------|----------|---------|---------|-------------------
Done in 1.71s.
```

---

Related to #1893

### Reproduction

``` shell
$ cd examples/svelte
$ yarn coverage
```

### System Info

```shell
System:
    OS: Linux 6.2 Arch Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 24.70 GB / 31.28 GB
    Container: Yes
    Shell: 3.6.0 - /usr/bin/fish
  Binaries:
    Node: 19.7.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Brave Browser: 111.1.49.120
    Firefox: 110.0.1
  npmPackages:
    @vitest/coverage-c8: ^0.29.3 => 0.29.3
    @vitest/ui: latest => 0.29.3
    vite: latest => 4.2.0
    vitest: latest => 0.29.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Svelte will not work properly with code coverage tools. 

When Svelte code is transpiled it includes generated code in the source maps. This generated code is not part of your source codes and causes incorrect code coverage results. `c8` and `istanbul` both rely on source maps. 

This is not an issue of Vitest but Svelte itself:  https://github.com/sveltejs/svelte/issues/7824
