### ISSUE TITLE
Coverage is not being reported when there are no test files

### ISSUE THREAD

**Issue by odockal** [vitest-dev/vitest#3041]
### Describe the bug

I would expect that code coverage is calculated/reported even though there are not test files present. Then it would mean that coverage is zero. Instead, `No test files found, exiting with code 0` warning is printed out. 

### Reproduction

Checkout https://github.com/odockal/zero-coverage-project
Run `npm run build`
Run `npm run test`
ASSERT: no code coverage is provided
Rename `src/test.ts` to `src/test.spec.ts`
Run `npm run test`
ASSERT: Now the coverage is provided (zero).

### System Info

```shell
System:
    OS: Linux 6.1 Fedora Linux 37 (Workstation Edition)
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
    Memory: 20.42 GB / 31.11 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 110.0
  npmPackages:
    @vitest/coverage-c8: ^0.29.5 => 0.29.5 
    vitest: ^0.29.5 => 0.29.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
This request makes sense - especially when `passWithNoTests: true` is used. Other JS test runners seem to behave similarly. Let's add support for this.
