### ISSUE TITLE
Implement module mocking in browser mode

### ISSUE THREAD

**Issue by christian-bromann** [vitest-dev/vitest#3046]
### Describe the bug

The following test:

```ts
import { test, vi } from 'vitest'
import { v4 } from 'uuid'

vi.mock('uuid', () => ({
    v4: 'I am mocked'
}))

test('I live in the browser', () => {
    console.log('YES', window.navigator.userAgent, v4)
})
```

throws an error:

```
 FAIL  tests/browser.test.js [ tests/browser.test.js ]
TypeError: this._mocker.queueMock is not a function
 ❯ VitestUtils.mock http:/localhost:63315/node_modules/.vite/deps/chunk-DGJ3HNQR.js?v=22cddd7a:10193:18
 ❯ http:/localhost:63315/private/tmp/vitestbrowser/tests/browser.test.js?v=1679345265563:4:4
```

### Reproduction

see above

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 420.98 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.7.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  Browsers:
    Brave Browser: 111.1.49.120
    Chrome: 111.0.5563.64
    Firefox: 109.0
    Firefox Nightly: 111.0a1
    Safari: 15.2
  npmPackages:
    @vitest/browser: ^0.29.7 => 0.29.7
    vitest: ^0.29.7 => 0.29.7
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Mocking in the browser is not supported yet.

**Comment by christian-bromann** [comment]
> Mocking in the browser is not supported yet.

Yes, I remember reviewing the original PR that landed the browser runner. My suggestion then would be to throw a more meaningful error for users.

**Comment by lmiller1990** [comment]
@sheremet-va have you got any ideas on how best to support browser ESM mocks? We are working on something similar at Cypress for our `cypress/vite-dev-server`: https://github.com/cypress-io/cypress/issues/22355.

Maybe we can collaborate and solve ESM mocks in the browser for both Vitest and Cypress.

**Comment by lmiller1990** [comment]
Gotcha... this is pretty much in line with what I was expecting for implementing this in Vitest.

> Module mocking is already implemented in webdriverio, as far as I understand.

I haven't seen how they handle this, will take a look.

I saw another non-runner specific way, using [importmaps](https://modern-web.dev/docs/test-runner/writing-tests/mocking/). You then just combine with something like sinon. Also looking to do some exploration around this - a non-runner specific solution sure would be nice.

**Comment by sheremet-va** [comment]
> a non-runner specific solution sure would be nice

It would be nice, but I don't think it's possible to make it work with the same API Vitest has, unfortunately. The general solution is not DX-friendly.

**Comment by marpme** [comment]
**To summarize it:** the current workaround for mocking or spying in vitest with browser mode enabled is to use libraries like `sinon.js` until the official implementation is done.

or do you see any other alternatives to this?

**Comment by sheremet-va** [comment]
> **To summarize it:** the current workaround for mocking or spying in vitest with browser mode enabled is to use libraries like `sinon.js` until the official implementation is done.
> 
> or do you see any other alternatives to this?

`vi.spyOn` and `vi.fn` work as usual. Sinon also cannot spy on module exports (no library can).

**Comment by marpme** [comment]
> > **To summarize it:** the current workaround for mocking or spying in vitest with browser mode enabled is to use libraries like `sinon.js` until the official implementation is done.
> > or do you see any other alternatives to this?
> 
> `vi.spyOn` and `vi.fn` work as usual. Sinon also cannot spy on module exports (no library can).

Fair point, I was under the impression that those functionalities would also be impacted by this missing implementation. Thank you for further clarifying 🥇

**Comment by lmiller1990** [comment]
We looked into this more at Cypress and arrived at a similar conclusion - the whole "ESM mocking" is hard to solve generally. We will solve it for Vite and webpack via a plugins, I will link the code here once we write it, maybe we can collaborate with the Vitest team to build a general `vite-plugin-esm-mocks` plugin, or something to that meaning.

**Comment by kettanaito** [comment]
Just a quick plug here that in ESM, importing modules is fetching them via HTTP, and you can use libraries like MSW to intercept module requests and respond to them with whichever `application/javascript` response you want.

**Comment by sheremet-va** [comment]
> Just a quick plug here that in ESM, importing modules is fetching them via HTTP, and you can use libraries like MSW to intercept module requests and respond to them with whichever `application/javascript` response you want.
> 
> cc @sheremet-va

Hm, this might actually be easier than the current implementation 🤔 The current one also doesn't work if you import original module that imports itself somewhere in the import chain, but we can bypass that with MSW 🤔

**Comment by christian-bromann** [comment]
I've I would would have just known about MSW earlier in my life 😭 this is amazing!

**Comment by kettanaito** [comment]
@sheremet-va, feel free to add me to reviewers if you ever decide to give MSW a shot in module mocking. I will be happy to help you spot mistakes and suggest improvements. 

@christian-bromann, but you've discovered it now, and that all that matters! ❤️

**Comment by sheremet-va** [comment]
> feel free to add me to reviewers if you ever decide to give MSW a shot in module mocking. I will be happy to help you spot mistakes and suggest improvements.

The first version is already implemented (and merged) here: https://github.com/vitest-dev/vitest/pull/5853
It is a bit hard to review without the knowledge of how internals work, but you can give it a look 😄 I did not look into how this would work with custom service workers yet.
