### ISSUE TITLE
Implement playwright browser provider

### ISSUE THREAD

**Issue by benmccann** [vitest-dev/vitest#3056]
### Clear and concise description of the problem

Add built-in support for Playwright alongside the existing webdriver support 

### Suggested solution

Reference https://github.com/vitest-dev/vitest/pull/2999

### Additional context

In SvelteKit we offer Vitest and Playwright as defaults that we automatically setup for the user. It would be nice to have a Playwright browser provider to allow usage of Vitest's browser testing feature without needing to additionally download webdriver.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Aslemammad** [comment]
I'm working on this one.
