### ISSUE TITLE
resetModules does not restore state

### ISSUE THREAD

**Issue by jonathan-graf** [vitest-dev/vitest#3058]
### Describe the bug

When changing the local state of an imported module and using the `resetModules()` function, I am witnessing that the original values of the local state do not get restored.  

I do want to note that this might be a misunderstanding on my part of what defines a "module" and what is meant to represent "local state".   If this is the case, I would appreciate some education here to gain further understanding.

I created a unit test that will add a new property to the first element of the array in the local state of the `bug.data` module.  In the second test, the `newProperty` bleeds into it.
 
I see the following results when executing the unit test below:
```
 FAIL  src/bug.spec.tsx > module has old state
AssertionError: expected true to be undefined // Object.is equality
 ❯ src/bug.spec.tsx:19:49
     17| test('module has old state', async () => {
     18|   const mod = await import('./bug.data');
     19|   expect((mod.data[0] as TestData).newProperty).toBe(undefined);
       |                                                 ^
     20| })
  - Expected   "undefined"
  + Received   "true"
```

### Reproduction

**bug.data.ts**
```
export interface TestData {
  id: number,
  newProperty?: boolean
}

export const data: TestData[] = [
  {
      "id": 44,
  },
  {
      "id": 135,
  },
  {
      "id": 37,
  },
  {
      "id": 23,
  }
]
```

**bug.spec.ts**
```
import { vi } from 'vitest'
import { TestData } from './bug.data'

beforeAll(() => {
  vi.resetModules()
})

test('change state', async () => { 
  const mod = await import('./bug.data');

  expect((mod.data[0] as TestData).newProperty).toBe(undefined);

  (mod.data[0] as TestData).newProperty = true;
  expect((mod.data[0] as TestData).newProperty).toBe(true);
})

test('module has old state', async () => {
  const mod = await import('./bug.data');
  expect((mod.data[0] as TestData).newProperty).toBe(undefined);
})
```

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.77 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 2022.09.12.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 109.0.1
    Safari: 15.3
  npmPackages:
    @vitejs/plugin-react: ^3.0.0 => 3.1.0 
    @vitest/coverage-c8: ~0.25.8 => 0.25.8 
    @vitest/ui: ^0.25.8 => 0.25.8 
    vite: ^4.0.1 => 4.1.1 
    vitest: ^0.29.7 => 0.29.7
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You are calling it in `beforeAll`, and not in `beforeEach`

**Comment by jonathan-graf** [comment]
Thank you!  Would you mind updating the [documentation](https://vitest.dev/api/vi.html#vi-resetmodules) to use `beforeEach`?   I'm not sure what the use case would be to only call this function at the start of the test run?

**Comment by sheremet-va** [comment]
> Thank you! Would you mind updating the [documentation](https://vitest.dev/api/vi.html#vi-resetmodules) to use `beforeEach`? I'm not sure what the use case would be to only call this function at the start of the test run?

PR welcome!

**Comment by jonathan-graf** [comment]
Glad to submit a PR!  I'd just like to get a bit more understanding first, if that's ok:

If I make the `import` a top-level `import`, then the unit test fails:
```
import { vi } from 'vitest'
import { TestData } from './bug.data'
import { data } from './bug.data'

beforeEach(() => {
  vi.resetModules()
})

test('change state', async () => { 
  expect((data[0] as TestData).newProperty).toBe(undefined);

  (data[0] as TestData).newProperty = true;
  expect((data[0] as TestData).newProperty).toBe(true);
})

test('module has old state', async () => {
 expect((data[0] as TestData).newProperty).toBe(undefined);
})
```

I understand now that this behavior is expected.  `resetModules()` will only work for modules that are imported within the function scope. `resetModules()` will not reset top-level modules.  Can you confirm?

The code example in the documentation is clear but, from my perspective, it is not obvious that `resetModules()` does not touch top-level modules.  Would you be ok with me adding more text to the documentation on that point?  Or adding a warning?  Seeking your recommendation here.

**Comment by sheremet-va** [comment]
> The code example in the documentation is clear but, from my perspective, it is not obvious that resetModules() does not touch top-level modules. 

`resetModules` reset the modules registry, not the modules themselves. It means that the next time you import a module, it will be re-evaluated.

Top-level import is evaluated once, there is no way to reevaluate it, you need to import the module again. The only thing that's needed changing is replacing `beforeAll` with `beforeEach`. If you feel the need to specify the behavior, I am not against it.
