### ISSUE TITLE
bug (browser-runner): alert stales test execution

### ISSUE THREAD

**Issue by christian-bromann** [vitest-dev/vitest#3061]
### Describe the bug

Heyho 👋 

since I discovered this edge case in WebdriverIO I thought I would report it in Vitest as well. If `alert` is called, all JS execution is stopped including the communication with the Vite server.

I am thinking about the following options:
- throw an error and advise users to mock this method
- auto mock it as part of the test setup

What do you think? 

### Reproduction

Given the following test:

```ts
import { test } from 'vitest'

test('haha', () => {
    alert("UOOO")
    console.log('Hello World')
})
```

The console command is never executed.

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 711.84 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Brave Browser: 111.1.49.120
    Chrome: 111.0.5563.64
    Firefox: 109.0
    Firefox Nightly: 111.0a1
    Safari: 15.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I assume `confirm` and `prompt` also act the same? 🤔 I guess the immediate solution is to mock them, but isn't there a way to control this with webdriver?

**Comment by Aslemammad** [comment]
What I would suggest is that we mock it but we also show a warning there.

**Comment by Aslemammad** [comment]
I guess instead of giving an example to them, we can redirect them to the docs instead, so we avoid long messages.

**Comment by Aslemammad** [comment]
> Vitest encountered a #{name} call with parameters: #{params}. Vitest cannot handle #{name} by default, so it returned null. If you need to handle this case, you can mock the #{name} call yourself like this:

By avoiding the example I mean only bringing this line.

The reason is I think it'd be better if people see a page where there's more information in that case, instead of a long message where they might not know from where it's coming. And another note, we can also mention the mocking issues in the docs, so it'd be even more informative. 

I prefer the "more information in the right place" in this case, but I am not strict around it and we can take any approach around this.

**Comment by sheremet-va** [comment]
> The reason is I think it'd be better if people see a page where there's more information in that case, instead of a long message where they might not know from where it's coming. And another note, we can also mention the mocking issues in the docs, so it'd be even more informative.

What do you mean by "might not know from where it's coming"?

I think providing extensive error messages is better than just redirecting people to docs. I do think we can explain in detail how it works in the docs in more detail, of course. But a possible fix should still be there, we always try to provide fixes in the error messages in other places. "Something went wrong! Read more here: #link" is not a good error message. 

We should strive for Elm-like error messages (or even jest-like). More explanation for the error is never bad.

**Comment by sheremet-va** [comment]
> I can work on this if you want, let me know.

Sure, you can work on any open browser issue 😄

**Comment by christian-bromann** [comment]
> but isn't there a way to control this with webdriver?

There is but given that the browser is locked the user can't handle the alert within the test. You can totally have the server continuously check for an alert to pop up but I would question the value of allowing them in the first place then.
