### ISSUE TITLE
deps.inline not working for yarn PnP (yarn 2)

### ISSUE THREAD

**Issue by cmark1302** [vitest-dev/vitest#3073]
### Describe the bug

.yarn/cache/d3-scale-npm-4.0.2-d17a53447b-a9c770d283.zip/node_modules/d3-scale/src/index.js:1 seems to be an ES Module but shipped in a CommonJS package. You might want to create an issue to the package "d3-scale" asking them to ship the file in .mjs extension or add "type": "module" in their package.json.

As a temporary workaround you can try to inline the package by updating your config:

// vitest.config.js
export default {
  test: {
    deps: {
      inline: [
        "d3-scale"
      ]
    }
  }
}

### Reproduction

add a nivo

import { ResponsivePie } from '@nivo/pie'

and use legend as well on yarnrc.yml file

  '@nivo/legends@*':
    dependencies:
      'd3-scale': '*'
      '@nivo/colors': '*'
      'prop-types': '*'

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 221.30 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
    Yarn: 3.1.1 - /usr/local/bin/yarn
    npm: 7.21.1 - ~/.nvm/versions/node/v16.9.1/bin/npm
    Watchman: 2023.02.06.00 - /usr/local/bin/watchman
  Browsers:
    Safari: 16.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You need to inline every package that imports the package:

```
export default {
  test: {
    deps: {
      inline: ['@nivo/pie', 'd3-scale']
    }
  }
}
```
