### ISSUE TITLE
mocking a module with relative path alias is not working

### ISSUE THREAD

**Issue by naoki-kiryu-lvgs** [vitest-dev/vitest#3081]
### Describe the bug

# Description

Create a path alias with relative path in `vitest.config.ts`:

```ts:vitest.config.ts
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    alias: {
      '~': './src',
    },
  },
});
```

and mocking a module with path alias:

`src/module.ts`
```ts
export default function () {
  // do something
}
```
`test/basic.test.ts`
```ts
import { vi, assert, expect, test, Mock } from 'vitest';

import mod from '~/module';

// Mock the module. This will be hoisted to the top and `import mod from '~/module' will return a `Mock` object.
vi.mock('~/module');

test('Calling mocked function', () => {
  (mod as Mock).mockImplementation(() => {
    return 'success!';
  });
  expect(mod()).toBe('success!');
});
```

Then run the test, which will result in the following error:

```
 FAIL  test/basic.test.ts > Calling mocked function
TypeError: default.mockImplementation is not a function
 ❯ eval test/basic.test.ts:9:17
      7| 
      8| test('Calling mocked function', () => {
      9|   (mod as Mock).mockImplementation(() => {
       |                 ^
     10|     return 'success!';
     11|   });
```

# Resolution

I struggled for a couple of hours and found that changing the alias to `'~': '/src'` solves this problem.

```diff
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    alias: {
-     '~': './src',
+     '~': '/src',
    },
  },
});
```

# Why this occurs

It seems that the id of aliased module is calculated differently in `requestWithMock` and `mockPath` when using relative path.
Confirm this by inserting some debugging code in `node_modules/vitest/dist/chunk-runtime-mocker.344fec90.js`:

```diff
  async requestWithMock(url, callstack) {
    if (_VitestMocker.pendingIds.length) await this.resolveMocks();
    const id = this.normalizePath(url);
+   console.log(id, this.getMocks());
```

and run the [Stackblitz](https://stackblitz.com/edit/vitest-dev-vitest-vakjkb?file=vite.config.ts), then get output like this:

```
stdout | unknown test
/home/projects/vitest-dev-vitest-vakjkb/node_modules/vitest/dist/index.js {}

stdout | unknown test
/home/projects/vitest-dev-vitest-vakjkb/src/module.ts { 'src/module': null }
```

Here, getting `null` as a mock value is just fine. The problem is that the id calculated in `requestWithMock` (`/home/projects/vitest-dev-vitest-vakjkb/src/module.ts`) does not match the id calculated in `mockPath` (`src/module`).
I don't know if this is an expected behavior or not, but it is definitely the root cause of this problem.

### Reproduction

[Stackblitz (relative module alias, not working)](https://stackblitz.com/edit/vitest-dev-vitest-vakjkb?file=vite.config.ts)
[Stackblitz (module alias with `/` prefix, working)](https://stackblitz.com/edit/vitest-dev-vitest-6b87r2?file=vite.config.ts)

### System Info

```shell
System:
    OS: Linux 6.2 Arch Linux
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900KS
    Memory: 21.05 GB / 31.05 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 16.15.0 - ~/.nodenv/versions/16.15.0/bin/node
    Yarn: 1.22.19 - ~/WorkDir/worx-hr/labor-frontend/node_modules/.bin/yarn
    npm: 8.5.5 - ~/.nodenv/versions/16.15.0/bin/npm
  Browsers:
    Chromium: 110.0.5481.177
    Firefox: 110.0.1
  npmPackages:
    @vitejs/plugin-react: ^3.1.0 => 3.1.0 
    vite: ^4.2.1 => 4.2.1 
    vitest: ^0.29.7 => 0.29.7
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by naoki-kiryu-lvgs** [comment]
As described above, we can avoid this problem by not using relative path for path alias.
But since this is really confusing, this behavior should be either documented or corrected.

**Comment by sheremet-va** [comment]
"module.ts" is not located in the same directory where your test is. If path is relative, it's relative to the current path, so everything works correctly.

**Comment by naoki-kiryu-lvgs** [comment]
OK, so if you say that the module needs to be placed "relative" to the test file, why the module resolution itself succeeds?
Even if in [the not working reproduction](https://stackblitz.com/edit/vitest-dev-vitest-vakjkb?file=vite.config.ts), module is resolved to the `<projectRoot>/src/module` (since we don't get any "module not found" error.)
It means that the relative path `./src` in the config is resolved based on the project root directory.
The module resolution is obviously inconsistent between the `import` and the mocking.
This is why I say it "confusing". (The path resolves successfuly in `import`, but not in the mocking.)

**Comment by sheremet-va** [comment]
> @sheremet-va 
> 
> Have you checked the above? Please reopen this.

The fact that import works is a bug and a side effect of how Vite SSR works, not the other way around. Don't use relative paths in aliases, it's a common sense, the are just replaced and resolved to the current file, not the file they are defined in.

**Comment by naoki-kiryu-lvgs** [comment]
OK, I get what you want to say, but I think that you should explicitly document how to use the `alias` option correctly.
Similar functionalities in the world, like [jest](https://jestjs.io/ja/docs/configuration#modulenamemapper-objectstring-string--arraystring) or [typescript](https://www.typescriptlang.org/tsconfig#paths), includes at least an example configuration in their documentation.
In vitest, there is neither any explanation nor example configuration.
