### ISSUE TITLE
test.each does not work in browser mode

### ISSUE THREAD

**Issue by dospunk** [vitest-dev/vitest#3085]
### Describe the bug

Trying to run a `test.each` or `it.each` test in browser mode fails with the error "import_util.default.format is not a function"

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-gehlnr?file=test/basic.test.ts

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 6.97 GB / 15.78 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (111.0.1661.54)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @vitest/browser: ^0.29.7 => 0.29.7
    @vitest/ui: latest => 0.29.7
    vite: latest => 4.2.1
    vitest: latest => 0.29.7
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Aslemammad** [comment]
Unfortunately, I cannot reproduce this on my linux system! I may need to push a `each` test into the browser for the CI, so maybe it fails on windows?

**Comment by kleinfreund** [comment]
I just tried reproducing this on Windows and can't. The only off thing I noticed is that with the following configuration, the browser is opened with the vitest UI tab **but additionally, the same tab is also opened in the browser I had happened to have open: Firefox**.

package.json

```json
{
  "devDependencies": {
    "@vitest/browser": "^0.32.2",
    "@vitest/ui": "^0.32.2",
    "vitest": "^0.32.2",
    "webdriverio": "^8.11.2"
  }
}
```

vite.config.js

```js
/// <reference types="vitest" />

import { defineConfig } from 'vite'

export default defineConfig({
	test: {
		browser: {
			name: 'chrome',
		},
	}
})
```

test.js

```js
import { expect, test } from 'vitest'

test.each([
	['x', true],
	['y', false],
])('%s is x', (val, expectedResult) => {
	expect(val === 'x').toBe(expectedResult)
})
```

Command

```sh
npx vitest --ui --browser
```
