### ISSUE TITLE
fake timers do not mock AbortSignal.timeout or timers/promises

### ISSUE THREAD

**Issue by everett1992** [vitest-dev/vitest#3088]
### Describe the bug

mock timers do not mock node's [timers/promises](https://nodejs.org/api/timers.html#timers_timers_promises_api) or [AbortSignal.timeout](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout)

There is an open issue in sinon fake-timers to implement these. 
https://github.com/sinonjs/fake-timers/issues/418

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-5rmugo?file=test/basic.test.ts
```
describe('with fake timers', () => {
  beforeAll(() => {
    vi.useFakeTimers();
  });

  test('signal should abort after timeout', () => {
    const signal = AbortSignal.timeout(100);
    expect(signal.aborted).toBe(false);
    
    vi.advanceTimersByTime(200);
    
    // This will fail, aborted is still false.
    expect(signal.aborted).toBe(true);
  });
});
```

### System Info

```shell
stackblitz
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zbyte64** [comment]
Related: https://github.com/sinonjs/fake-timers/issues/418

**Comment by LumaKernel** [comment]
Could mocking module `"timers/promises"` and `"node:timers/promises"` builtin solve the problem? Or waiting shinonJS' decision?

**Comment by everett1992** [comment]
I think we're waiting on sinon. In the mean time I've been mocking timers/promises with an implementation that delegates to global setTimeout so it's correctly mocked by `useFakeTimers`. I'm not sure how accurate my mock is so I won't bother sharing it here.

**Comment by sheremet-va** [comment]
I am closing the issue here since Vitest cannot do anything to resolve this unless happy-dom implements the correct API.
