### ISSUE TITLE
.not.toThrowErrorMatchingInlineSnapshot() doesn't work as expected

### ISSUE THREAD

**Issue by Maxim-Mazurok** [vitest-dev/vitest#3089]
### Describe the bug

I created a failing test using `.not.toThrowErrorMatchingInlineSnapshot()` to demonstrate to my colleague the error that they have to address.
However, when they fixed the error - the test still doesn't pass, because vitest returns `Error: snapshot function didn't throw` for this test.
I expect `.not.toThrowErrorMatchingInlineSnapshot()` to assert that error was either not thrown, or it was thrown but didn't match the snapshot.
Current behaviour is more like `expect().toTrowError.not.matchingInlineSnapshot()`, hope this makes sense!

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-cmmyai?file=test/basic.test.ts

```js
// passes
it("throws", () => {
  expect(() => {
    throw "Bla-bla";
  }).toThrowErrorMatchingInlineSnapshot('"Bla-bla"');
});

// fails with `Error: snapshot function didn't throw`
it("doesn't throw", () => {
  expect(() => {}).not.toThrowErrorMatchingInlineSnapshot('"Bla-bla"');
});
```

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900H
    Memory: 23.12 GB / 31.19 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.110
  npmPackages:
    @vitejs/plugin-vue: ^3.1.2 => 3.2.0 
    @vitejs/plugin-vue-jsx: ^1.3.9 => 1.3.10 
    @vitest/coverage-c8: ^0.29.2 => 0.29.2 
    vite: ^3.1.8 => 3.2.5 
    vitest: ^0.29.2 => 0.29.2 
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
After rereading this, I am not sure it makes sense to support "not" operator. What string should it generate then? Just anything except the current value?
