### ISSUE TITLE
Jetbrains IDE: Error when trying to run specific test with IDE helpers

### ISSUE THREAD

**Issue by gerzitom** [vitest-dev/vitest#3094]
### Describe the bug

This issue was mentioned in #2936 and #2459 but I am currently at version `0.29.0`, but unfortunately this is not working.
Could this be please resolved.

![Screenshot 2023-03-28 at 20 19 16](https://user-images.githubusercontent.com/36927934/228331446-2763c6ee-acef-4218-a187-d85368a59779.png)

### Reproduction

Try to run any test with Jetbrains IDE with play button, that IDE provides

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 112.80 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 16.3
  npmPackages:
    @vitejs/plugin-vue2: ^2.2.0 => 2.2.0 
    @vitest/coverage-c8: ^0.29.0 => 0.29.3 
    @vitest/ui: ^0.29.3 => 0.29.3 
    vite: ^4.0.0 => 4.1.1 
    vitest: ^0.29.0 => 0.29.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest does not influence how Jetbrains IDE runs it.
