### ISSUE TITLE
Support scoping setupFiles to specific sets of files

### ISSUE THREAD

**Issue by kherock** [vitest-dev/vitest#3096]
### Clear and concise description of the problem

I've gone through the discussion here in #256 and it doesn't seem  to cover one of the major features that I need from Jest's `projects` support, which is **the ability to scope setup and teardown functions to specific sets of files**.

My main issue is that in order to migrate from Jest, I have to refactor every test file in an individual package to call setup functions that were previously configured once on the whole package.

### Suggested solution

Augment or expose a new setupFiles property that only runs top-level setup code when the test file matches a certain pattern:

```js
export default defineConfig({
  test: {
    setupFiles: [
      'vitest.setup.ts',
      { path './my-package/vitest.setup.ts', include: './my-package/**/*' }
      { path './my-other-package/vitest.setup.ts', include: './my-other-package/**/*' }
    ],
  },
});
```

### Alternative

It should aslo be possible to implement `beforeEach`, `beforeAll`, etc. functions in userland that conditionally run based on the `context.filepath` property from the [test context](https://vitest.dev/guide/test-context.html).

For example

```js
import { fileURLToPath } from 'url';

const packagePath = fileURLToPath(new URL('..', import.meta.url));

export function beforeEachInPackage(fn) {
  return (context) => {
    if (context.filepath.startsWith(packagePath))
      beforeEach(context);
  }
}
```

I like this solution but it's boilerplate that 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
It is expected to be implemented as part of #256
