### ISSUE TITLE
Proposition of improvement of the execution time

### ISSUE THREAD

**Issue by ALapaque** [vitest-dev/vitest#3099]
### Clear and concise description of the problem

Looks like the tests itself are running really fast but the rendering of the result are taking ages

We're running several tests and the times of runs are always milliseconds but the global run takes way more time

Apparently to run all the tests it should be done in 6.85seconds
![image](https://user-images.githubusercontent.com/46450511/228512332-cc6fbd09-3ddb-4afd-8882-89b37b1473f2.png)

But actually the collect was really long 345.05s
![image](https://user-images.githubusercontent.com/46450511/228512445-c3bed880-c981-46ec-963f-e707f65cd478.png)

So I was wondering is it slow because it needs to refresh to much and to fast ?

### Suggested solution

Could it be possible to generate that end of run report (collect) at the end of the global run ? and not at each finished tests run ?

And if possible allows this option to be used for CI purpose for example

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
What version do you use?

**Comment by ALapaque** [comment]
"vitest": "^0.29.7"

**Comment by ALapaque** [comment]
> What version do you use?

"vitest": "^0.29.7"

**Comment by ALapaque** [comment]
@sheremet-va Unfortunately I can't share with you the actual repo which has 782 tests because it's private

But tbh, there's no real reproduction needed except having a project with some tests

**Comment by sheremet-va** [comment]
Collecting is not rendering. Collecting is importing your tests. It is the accumulative value for each test import. It depends on what Vitest has to transform and import. It might take a lot of time to import a library, for example, and unique for each project.

> But tbh, there's no real reproduction needed except having a project with some tests

This is not true, Vitest has a lot of tests and takes less than 10 seconds to run them.

**Comment by ALapaque** [comment]
> Collecting is not rendering. Collecting is importing your tests. It is the accumulative value for each test import. It depends on what Vitest has to transform and import. It might take a lot of time to import a library, for example, and unique for each project.
> 
> > But tbh, there's no real reproduction needed except having a project with some tests
> 
> This is not true, Vitest has a lot of tests and takes less than 10 seconds to run them.

Oh ok, I see. so I could probably decrease that time by using rollup to split those libs into chunks then ?

**Comment by sheremet-va** [comment]
> Oh ok, I see. so I could probably decrease that time by using rollup to split those libs into chunks then ?

Yes, importing processed files is faster.

> So I was wondering is it slow because it needs to refresh to much and to fast ?

Vitest has a `basic` reporter for this. It is used in CI by default.

**Comment by ALapaque** [comment]
> > Oh ok, I see. so I could probably decrease that time by using rollup to split those libs into chunks then ?
> 
> Yes, importing processed files is faster.
> 
> > So I was wondering is it slow because it needs to refresh to much and to fast ?
> 
> Vitest has a `basic` reporter for this. It is used in CI by default.

Ok cool, I'll have a look then, because i'm actually using a few big libraries "react" "capacitory" "mui"

**Comment by ALapaque** [comment]
Thanks for the info

**Comment by sheremet-va** [comment]
> Ok cool, I'll have a look then, because i'm actually using a few big libraries "react" "capacitory" "mui"

There is an [experimental optimizer](https://vitest.dev/config/#deps-experimentaloptimizer) that might help with that. Currently, it's a bit flawed, because it bundles _every_ dependency, but in the next versions it would be possible to provide the list of dependencies to bundle.

**Comment by ALapaque** [comment]
> > Ok cool, I'll have a look then, because i'm actually using a few big libraries "react" "capacitory" "mui"
> 
> There is an [experimental optimizer](https://vitest.dev/config/#deps-experimentaloptimizer) that might help with that. Currently, it's a bit flawed, because it bundles _every_ dependency, but in the next versions it would be possible to provide the list of dependencies to bundle.

That's an insane feature tbh !  I'll have a look at this one
