### ISSUE TITLE
Modules with alias are not mocked

### ISSUE THREAD

**Issue by BrevAlessio** [vitest-dev/vitest#3105]
### Describe the bug

If I try to mock a module imported by another module, by providing an alias as key, such as `vi.mock('@module-alias')`, the module is **not** mocked as expected. 
If I provide the relative path as key, such as `vi.mock('..src/MyModule')`, the module is mocked as expected.

``` js
// MyInnerModule
export const MyInnerModule = { key: undefined }
```

``` js
// MyModule
import { MyInnerModule } from '@/MyInnerModule'
export const MyModule = { key: MyInnerModule.key }
```

``` js
// MyModule.test
import { MyModule } from '@/MyModule';
import { vi, describe, it, expect } from 'vitest';

// Try with relative path ../src/MyInnerModule, it works
vi.mock('@/MyInnerModule', () => {
  return {
    MyInnerModule: {
      key: 1,
    },
  };
});

describe('MyModule', () => {
  it('should have key', () => {
    expect.assertions(1);
    expect(MyModule.key).toBe(1); // Got undefined
  });
});

```

This issue may be related to https://github.com/vitest-dev/vitest/pull/2777 but it didn't solve my case.

### Reproduction

Stackblitz, follow the instruction on line 4 to switch between non working and working 
https://stackblitz.com/edit/vitest-dev-vitest-qj31uc?file=test/MyModule.test.ts

### System Info

```shell
All the infos are on stackblitz:

  "devDependencies": {
    "@vitest/ui": "latest",
    "vite": "latest",
    "vitest": "0.29.8"
  },
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Don't use relative paths in aliases: https://vitejs.dev/config/shared-options.html#resolve-alias
