### ISSUE TITLE
Suggested .vscode/launch.json requires installing vite

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [vitest-dev/vitest#3112]
### Clear and concise description of the problem

Going through the VS Code debugging guide in https://vitest.dev/guide/debugging.html#vscode, when I run _F5_ on a repo that doesn't have `vite` listed as a dependency:

```plaintext
joshgoldberg ~/repos/template-typescript-node-package $  cd /Users/josh/repos/template-typescript-node-package ; /usr/bin/env 'NODE_OPTIONS=--require "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/ms-vscode.js-debug/src/bootloader
.bundle.js"     --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/var/folders/sr/j__6_9gn0dv557z0xf3p7y8h0000gn/T/node-cdp.67533-14.sock","deferredMode":false,"waitForDebugger":"","execPath":"/Users/josh/.nvm/versions/node/v18.7.0/bi
n/node","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"/var/folders/sr/j__6_9gn0dv557z0xf3p7y8h0000gn/T/node-debug-callback-00402a5d1b51117e"}' /Users/josh/.nvm/versions/node/v18.7.0/bin/node ./node_modules/vitest/vitest.mjs run src/gree
t.test.ts 
Debugger attached.
 MISSING DEP  Can not find dependency 'vite'

? Do you want to install vite? › (y/N)
```

![Screenshot of the first few dozen columns of the previous console log](https://user-images.githubusercontent.com/3335181/229175075-6ac9075a-57d9-4efd-9096-49b18a9a4924.png)

After accepting with `y` (or running `pnpm install vite` manually), the debug command works.

Reproduction:
* Check out https://github.com/JoshuaKGoldberg/template-typescript-node-package/tree/c122ea1aa2e70ed5ead091b345f2b0a424dcd2bb
* `pnpm install`
* Open [`src/greet.test.ts`](https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/c122ea1aa2e70ed5ead091b345f2b0a424dcd2bb/src/greet.test.ts)
* Launch the _Debug Current Test File_ command

### Suggested solution

I don't know why this is happening enough to suggest a solution 😞 sorry. `./vitest.mjs` is the `bin` entry in `node_modules/vitest/package.json`.

### Additional context

Note that `pnpm test` in that repository works _without_ adding `vitest` as a dependency.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
We use `isPackageExists` from [`local-pkg`](https://www.npmjs.com/package/local-pkg) library. I guess it doesn't recognize that `vite` is installed with Vitest 🤔
