### ISSUE TITLE
0.29.8 seems to have broken C8 unit test coverage reporting

### ISSUE THREAD

**Issue by USA-RedDragon** [vitest-dev/vitest#3118]
### Describe the bug

After upgrading to vitest 0.29.8, my workflows utilizing C8 as a coverage provide have started erroring with 

```
$ vitest run --coverage

vite:istanbul> Sourcemaps was automatically enabled for code coverage to be accurate.
 To hide this message set build.sourcemap to true, 'inline' or 'hidden'.
TypeError: coverageModule.getProvider is not a function
    at getCoverageProvider (file:///home/user/project/node_modules/vitest/dist/chunk-integrations-coverage.e0a6acd2.js:26:27)
    at async Vitest.initCoverageProvider (file:///home/user/project/node_modules/vitest/dist/chunk-node-pkg.4e9b4238.js:11669:29)
    at async Vitest.start (file:///home/user/project/node_modules/vitest/dist/chunk-node-pkg.4e9b4238.js:11753:7)
    at async startVitest (file:///home/user/project/node_modules/vitest/dist/chunk-node-pkg.4e9b4238.js:19004:5)
    at async start (file:///home/user/project/node_modules/vitest/dist/cli.js:104:17)
    at async CAC.run (file:///home/user/project/node_modules/vitest/dist/cli.js:77:3)
```

I noticed this change was added, and it seems related: https://github.com/vitest-dev/vitest/pull/3040

### Reproduction

https://github.com/USA-RedDragon/vite-bug-repro-c8-coverage is pulled and stripped from a bigger project which had been previously set up with coverage via this guide: https://vitest.dev/guide/coverage.html

To reproduce with that repo:
```
npm ci # the package-lock.json is present and appropriate
npm run test:unit # equivalent to npx vitest run --coverage
```

### System Info

```shell
Binaries:
  Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.0/bin/yarn
  npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
Browsers:
  Chromium: 111.0.5563.146
  Firefox: 111.0.1
npmPackages:
  @vitejs/plugin-vue: ^4.1.0 => 4.1.0
  @vitest/coverage-c8: ^0.29.8 => 0.29.8
  @vitest/ui: ^0.29.8 => 0.29.8
  vite: ^4.2.1 => 4.2.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by TiagoDiass** [comment]
I am facing the same problem here. 
Just installed @vitest/coverage-c8 in order to get coverage of my files but when I run `vitest run --coverage` it throws the same error as described in the issue.

![image](https://user-images.githubusercontent.com/49597377/229326999-cf5f82c5-ec86-4110-8882-20fa0b001e2e.png)

**Comment by AriPerkkio** [comment]
> After upgrading to vitest 0.29.8

The reproduction case is not using `vitest@0.29.8`. Try updating your `vitest` to latest version. https://github.com/USA-RedDragon/vite-bug-repro-c8-coverage/blob/main/package-lock.json#L3803-L3804

**Comment by dteoh** [comment]
I also reported this issue in the local-pkg repo: https://github.com/antfu/local-pkg/issues/7

**Comment by USA-RedDragon** [comment]
@AriPerkkio was right. Since I didn't have vitest explicitly in my `package.json`, only `@vitest/coverage-c8` and `@vitest/ui` one of my dependencies was resolving vitest 0.29.1. After explicitly installing vitest at 0.29.8, it started working.
