### ISSUE TITLE
Browser mode hanging on blank white screen, failing to load vitest/utils

### ISSUE THREAD

**Issue by ludwigbacklund** [vitest-dev/vitest#3124]
### Describe the bug

When trying to run a test in browser mode (playwright) with a basic example next.js application, the browser window opens but hangs on a blank screen and fails to load vitest/utils in the background.

<img width="1116" alt="Screenshot 2023-04-03 at 21 17 38" src="https://user-images.githubusercontent.com/13007299/229508074-23803bc5-5531-4816-8d9c-090788802a99.png">

### Reproduction

Reproduction repository, based on vitest next.js example: https://github.com/ludwigbacklund/vitest-browser-bug-repro

Just run `yarn test`, it will open a browser window and hang on a white screen. Check the console/network log.

### System Info

```shell
System:
    OS: macOS 13.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 774.77 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nodenv/versions/16.13.1/bin/node
    Yarn: 1.22.15 - ~/.nodenv/versions/16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nodenv/versions/16.13.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Safari: 16.4
  npmPackages:
    @vitejs/plugin-react: latest => 3.1.0 
    @vitest/browser: ^0.29.8 => 0.29.8 
    vitest: latest => 0.29.8
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Aslemammad** [comment]
Nice finding, I'm tracking it in #3100! I guess it's related, since it has the same issue with vitest/utils.

**Comment by ludwigbacklund** [comment]
@Aslemammad Thanks for taking a look at this. I'm still getting the same error though with the latest 0.30.0 version of vitest browser.

`[Error] Unhandled Promise Rejection: TypeError: Importing a module script failed.
	(anonymous function) (index-b8629a79.js:685)`

```
  System:
    OS: macOS 13.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 518.31 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nodenv/versions/16.13.1/bin/node
    Yarn: 1.22.15 - ~/.nodenv/versions/16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nodenv/versions/16.13.1/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Safari: 16.4
  npmPackages:
    @vitejs/plugin-react: latest => 3.1.0 
    @vitest/browser: ^0.30.0 => 0.30.0 
    vitest: ^0.30.0 => 0.30.0 
```

Reproduction: https://github.com/ludwigbacklund/vitest-browser-bug-repro

**Comment by Aslemammad** [comment]
@ludwigbacklund Could you create another issue for this?

**Comment by sheremet-va** [comment]
It's fine to do in the same issue.

**Comment by Aslemammad** [comment]
It's weird because it was resolved for me, I need to check it again soon. Thank you so much.

**Comment by userquin** [comment]
@ludwigbacklund can you try adding this to your Vite config file?
```ts
  optimizeDeps: {
    exclude: ['vitest/utils'],
    include: ['@vitest/utils', 'vitest/browser'],
  },
```

https://github.com/userquin/vitest-browser-vue (not working with Vite 4.3 beta 5, I need to review the dependencies)

![imagen](https://user-images.githubusercontent.com/6311119/231576915-377fb973-5e3a-4598-8d29-23e53b85e798.png)

**Comment by userquin** [comment]
Updated repo adding [vite-4.3 branch](https://github.com/userquin/vitest-browser-vue/tree/vite-4.3) using Vite 4.3.0 beta 5

**Comment by jd-solanki** [comment]
Thanks @userquin for inspecting the issue 🙏🏻 

@ludwigbacklund After adding below tests are runnig:
```ts
  optimizeDeps: {
    exclude: ['vitest/utils'],
    include: ['@vitest/utils', 'vitest/browser'],
  },
```

However, I'm getting unexpected errors like
```[vite] Internal server error: [@vue/compiler-sfc] type argument passed to defineEmits() must be a function type, a literal type with call signatures, or a reference to the above types```

when I runt he test in browser mode with above config, I guess this will get resolved along when we resolve this.

Anyways, @userquin's code snippet does makes tests run, Thanks 😇

**Comment by userquin** [comment]
@jd-solanki I've it working on my local using a hack via [vite-plugin-vue-type-imports](https://github.com/wheatjs/vite-plugin-vue-type-imports) plugin:
- add vite-plugin-vue-type-imports as dev dependency
- import it and wrap it with the code below

```ts
import VueTypeImports from 'vite-plugin-vue-type-imports'

const vueTypes = VueTypeImports()

plugins: [
    {
      name: 'fix-vue-sfc',
      enforce: 'pre',
      apply: (_, env) => env.mode === 'test',
      async resolveConfig(config) {
        await (vueTypes as any).resolveConfig(config)
      },
      async transform(code, id) {
        if (!/\.vue(\?.*)?$/.test(id))
          return

        return await (vueTypes as any).transform(code, id.slice(0, id.lastIndexOf('?')))
      },
    },
    VueMacros({...}),
    ...
],
```

**Comment by userquin** [comment]
@jd-solanki there is no need to include the hack, `vue-macros` has support for it:
```ts
VueMacros({
  betterDefine: {
    include: [/\.vue(\?v=\d+)?$/],
  },
  ...
})
```

**Comment by userquin** [comment]
@ludwigbacklund with your repo I'm getting this error when running the tests (installing vite 4.2.1 and latest vite react plugin):

![imagen](https://user-images.githubusercontent.com/6311119/231836661-2a284d49-8001-47fe-867f-4d302130d1fc.png)

**Comment by Ross-Esmond** [comment]
The exclude-include fix got me past the blank screen, but none of my tests run. Depending on the browser and provider, it either loads forever or just claims there are zero tests. I've tried changing the glob pattern and file names. Testing in node works fine.

**Comment by raythurnevoid** [comment]
> Thanks @userquin for inspecting the issue 🙏🏻
> 
> @ludwigbacklund After adding below tests are runnig:
> 
> ```ts
>   optimizeDeps: {
>     exclude: ['vitest/utils'],
>     include: ['@vitest/utils', 'vitest/browser'],
>   },
> ```
> 
> However, I'm getting unexpected errors like `[vite] Internal server error: [@vue/compiler-sfc] type argument passed to defineEmits() must be a function type, a literal type with call signatures, or a reference to the above types`
> 
> when I runt he test in browser (_without browser mode all tests are passing_) mode with above config, I guess this will get resolved along when we resolve this.
> 
> Anyways, @userquin's code snippet does makes tests run, Thanks 😇

I made it work by adding just

```
	optimizeDeps: {
		exclude: ['vitest/utils'],
		include: ['@vitest/utils']
	},
```

![image](https://user-images.githubusercontent.com/53383860/235380220-60dda87e-01fd-42ee-9066-2221c4637cc3.png)

**Comment by privatenumber** [comment]
After excluding `vitest/utils` from `optimizeDeps`, I get an error that `format` is not exported from `pretty-format`:

> Uncaught (in promise) SyntaxError: The requested module '/node_modules/.pnpm/pretty-format@27.5.1/node_modules/pretty-format/build/index.js?v=f31c97dc' does not provide an export named 'format' (at index.js?v=f31c97dc:3:10)
<img width="1560" alt="Screenshot 2023-05-02 at 5 22 53 PM" src="https://user-images.githubusercontent.com/1075694/235616601-d985ed4c-a73e-4a2d-a8e6-1a4751876da5.png">

Research:

- `format` is a named import in `vitest`:
https://github.com/vitest-dev/vitest/blob/main/packages/utils/src/stringify.ts#L2

- `format` is not a named export in `pretty-format`:
https://github.com/jestjs/jest/blob/main/packages/pretty-format/src/index.ts#L548

**Comment by Ross-Esmond** [comment]
The problem is not fixed for me after upgrading to v31. Has the issue resolved for anyone else?

**Comment by yshrsmz** [comment]
Just adding `@vitest/utils` to devDependencies solved the issue for me. no need for optimizedDeps.
