### ISSUE TITLE
mockRestore doesn't restore spied on properties to their original values

### ISSUE THREAD

**Issue by kherock** [vitest-dev/vitest#3127]
### Describe the bug

When using `vi.spyOn()` to create function mocks, the `spy.mockRestore()`, `vi.mockRestoreAllMocks()` doesn't actually restore the original descriptor of the spied-on object. This can lead to tests being written without ensuring that a method was already mocked, and deviates from [Jest's equivalent behavior](https://jestjs.io/docs/mock-function-api#mockfnmockrestore).

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-csdybj?file=test%2Fbasic.test.ts

```
test('should restore a spy', () => {
  const originalImpl = instance.fn1;
  const spy = vi.spyOn(instance, 'fn1');
  instance.fn1();
  spy.mockRestore();
  expect(instance.fn1).toEqual(originalImpl); // fails
});

test('should fail because it doesn\'t set up a spy', () => {
  instance.fn1();
  expect(instance.fn1).toHaveBeenCalledOnce(); // doesn't throw
});
```

### System Info

```shell
System:
    OS: macOS 12.6.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 88.91 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.local/share/homebrew/bin/node
    Yarn: 3.4.1 - ~/.local/share/homebrew/bin/yarn
    npm: 8.19.3 - ~/.local/share/homebrew/bin/npm
  Browsers:
    Firefox: 102.2.0
    Safari: 16.3
```

envinfo doesn't seem to work with my project's setup (Yarn 3 monorepo), here are my vitest versions:

```
    "vite": "^4.2.1",
    "vitest": "^0.29.8"
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is technically intended behavior. I am not sure if it's the right behavior, but removing a spy breaks module mocking as far as I remember. If someone has time to investigate the consequences of this change, be my guest.

**Comment by adrianbienias** [comment]
[vi.restoreAllMocks docs](https://vitest.dev/api/vi.html#vi-restoreallmocks) says
> Will call [.mockRestore()](https://vitest.dev/api/mock.html#mockrestore) on all spies. This will clear mock history and reset its implementation to the original one.

For me, it doesn't sound correct - spies aren't reset to the original state, they preserve the mocked one (which is not expected).
