### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'every')

### ISSUE THREAD

**Issue by jtuchel** [vitest-dev/vitest#3136]
### Describe the bug

I want to make sure that a configuration parser is able to parse a bunch of sample configurations

```ts
  describe("success cases", () => {
    let configurationFiles: [string, string][];

    beforeEach(async () => {
      const importedConfigurationFiles = await import.meta.glob('./validSampleConfigurations/*.json', { eager: true, as: 'raw' })
      configurationFiles = Object.entries(importedConfigurationFiles);
    })

    it("does things.", () => {
      expect(configurationFiles).toEqual([]);
    });
  });
```

This fails as expected, it knows that `configurationFiles` contains items. But when I try this

```ts
it.each(configurationFiles)(`parses configuration '%s'`, async (filePath, fileContent) => {
  expect(filePath).toBe(fileContent) // for testing purposes
})
```

I get the following error

> TypeError: Cannot read properties of undefined (reading 'every')

```
 17|     it.each(configurationFiles)(`parses configuration '%s'`, async (filePath, fileContent) => {
   |                               ^
 18|       expect(filePath).toBe(fileContent)
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-dt6acr

### System Info

```shell
System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (16) x64 AMD Ryzen 7 5700U with Radeon Graphics
    Memory: 7.19 GB / 19.35 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 19.7.0 - ~/.nvm/versions/node/v19.7.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v19.7.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Firefox: 111.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`configurationFiles` is `undefined`. `beforeEach` is not called, until every test is collected.
