### ISSUE TITLE
Using native decorators (EcmaScript) in TypeScript 5, the context is always undefined.

### ISSUE THREAD

**Issue by souzaadriano** [vitest-dev/vitest#3140]
### Describe the bug

When trying to use the new decorators, the context always comes as undefined and therefore the test fails when validating if the context.kind is the string 'class'.

### Reproduction

Decorator and decorated class `mock.ts`
``` typescript
function exampleDecorator(ClassExample: any, context:ClassDecoratorContext):any {
    if(context.kind !== 'class') throw new Error('not a class to decorate')
    return function(...args: any[]):any {
        return new ClassExample(...args)
    }
}

@exampleDecorator
class Sut {}
```

spect.ts
```typescript
import { describe, expect, it } from "vitest";
import { Sut } from './mock'

describe('module.factory.ts', () => {
        it('should be define a base module', () => {
            
            expect(Sut).toBeDefined()
    })
})
```

Vitest Output
```sh
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/core/module/factories/example.spec.ts [ src/core/module/factories/example.spec.ts ]
TypeError: Cannot read properties of undefined (reading 'kind')
 ❯ exampleDecorator src/core/module/factories/mock.ts:2:16
      1| function exampleDecorator(ClassExample: any, context:ClassDecoratorContext):any {
      2|     if(context.kind !== 'class') throw new Error('not a class to decorate')
       |                ^
      3|     return function(...args: any[]):any {
      4|         return new ClassExample(...args)
 ❯ __decorateClass src/core/module/factories/mock.ts:7:57
 ❯ src/core/module/factories/mock.ts:9:8
 ❯ src/core/module/factories/example.spec.ts:3:31
```

### System Info

```shell
System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz
    Memory: 5.63 GB / 15.40 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Firefox: 111.0.1
  npmPackages:
    vitest: ^0.29.8 => 0.29.8
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I think this is intentional. See more: https://github.com/evanw/esbuild/issues/104

**Comment by transitive-bullshit** [comment]
v0.21 of esbuild has added ES decorator support now that it's a [stage 3 ES feature](https://github.com/microsoft/TypeScript/pull/50820): https://github.com/evanw/esbuild/releases/v0.21.0

It looks like `vitest@2.0.0-beta.3` is still failing to incorporate the latest `esbuild` decorator support somewhere in it's rollup config. Here's some example output using the latest beta which is using `esbuild 0.20.2`:

![CleanShot 2024-05-28 at 18 33 56@2x](https://github.com/vitest-dev/vitest/assets/552829/c6446404-f936-4a2c-9474-7be075040574)

**Comment by hi-ogawa** [comment]
@transitive-bullshit Do you have a repro? Currently Vite hasn't bumped esbuild, so the feature is not coming yet by default (but should come soon https://github.com/vitejs/vite/pull/17290)

In the meantime, it should be still possible to use decorator by setting `overrides` esbuild version and `esbuild.target: "es2022"` to force down-emit the decorator syntax. I made a quick demo here sometime ago https://github.com/hi-ogawa/reproductions/blob/main/vite-esbuild-decorator/src/my-element.ts

**Comment by transitive-bullshit** [comment]
@hi-ogawa this is amazing; repros and is exactly what I was looking for. Thanks! 🙏
