### ISSUE TITLE
Vitest Documentation in Spanish - Documentación de Vitest en español.

### ISSUE THREAD

**Issue by Byron2016** [vitest-dev/vitest#3148]
### Clear and concise description of the problem

There are a big big comunity that speak Spanish, and Spanish is a forgoten language in software comunity
Hay una comunidad muy grande de habla española, y el español es un lenguaje olvidado en la comunidad de software

### Suggested solution

Translate Vitest Documentation to Spanish.
Traducir la documentación de Vitest a español.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by userquin** [comment]
It is there, you only need to expand navbar:
![imagen](https://user-images.githubusercontent.com/6311119/230618790-8777ff40-e1d4-4980-b3b2-927076a99c3b.png)

**Comment by sheremet-va** [comment]
> It is there, you only need to expand navbar:
> 
> ![imagen](https://user-images.githubusercontent.com/6311119/230618790-8777ff40-e1d4-4980-b3b2-927076a99c3b.png)
> 
> 

This is Vite docs, not Vitest

**Comment by userquin** [comment]
upps, sorry, it is vitest

**Comment by userquin** [comment]
@Byron2016 there is some work here: https://github.com/miguelfdezc/vitest-docs-es I don't know the current state, the docs can be found here: https://es-vitest.netlify.app/

**Comment by sheremet-va** [comment]
If you want to support Spanish translation, please join [the Discord](https://discord.gg/tFutWbPz), and let's talk there.
