### ISSUE TITLE
Add an example of vue component testing via browser mode with playwright

### ISSUE THREAD

**Issue by jd-solanki** [vitest-dev/vitest#3154]
### Clear and concise description of the problem

Hi 👋🏻 
I'm building Vue UI framework - [Anu](https://anu-vue.netlify.app/)

I really liked browser mode and I'm eagerly waiting for the stability of this feature. I must say we can't completely test our 
 vue components with jsdom when we build the UI framework and use vitest for testing. Browser mode is a huge encouragement for using vitest but in the early stage I did experience the #3124 and found that adding an example of testing vue component with Playwright's chrome as a browser provider that demonstrates browser API access like `window.getComputedStyle` will be easy for us to adopt and use, Moreover, it will also allow vitest team to quickly identify if there's any bug.

### Suggested solution

n/a

### Alternative

Not writing tests at all 😓 

### Additional context

I'm waiting for browser mode stability to make robust tests for testing vue components. I hope using browser mode will provide the same environment as the real browsers for robustness.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Aslemammad** [comment]
I'm happy you find this feature useful, sure, I think an example would help! Feel free to send a PR if you want. I'm not that experienced in vue.

**Comment by jd-solanki** [comment]
Hey, Thanks for the response. I'm still learning tests so I created this issue for creating example for beginners like me.

**Comment by Aslemammad** [comment]
Ok then, PRs are welcome!

**Comment by lmiller1990** [comment]
Not a direct solution, but I've been working on testing Vue [at Cypress](https://docs.cypress.io/guides/component-testing/vue/overview) - we've got a Vite dev server that works great, this might an alternative (it should all just work out of the box - some other projects I work on use it pretty successfully, like [Vuetify](https://github.com/vuetifyjs/vuetify/tree/master)).

**Comment by Aslemammad** [comment]
@lmiller1990 Why not? If it works, then it'd be good to have those examples. Anyone can send a PR if they want, so feel free to do so. Thank you so much.

**Comment by kingyue737** [comment]
@Aslemammad, I think lmiller mean we can test component with Cypress alone, not with vitest browser mode.

**Comment by lmiller1990** [comment]
Yeah, I meant if you want a client side runner, Cypress might work for your use case. It runs *in* the browser - doing all the execution in the browser makes a lot of sense for components, everything will just work as you'd expect, no need to mess about with jsdom or a Node.js runner shuttling messages back and forth.

**Comment by abernh** [comment]
Meanwhile here is a not a `vue` but general example implementation of how `Playwright` and `browsermode` is expected to work:
https://github.com/vitest-dev/vitest/tree/main/examples/playwright

**Comment by sheremet-va** [comment]
There are now examples in the documentation (https://vitest.dev/guide/browser/#examples).
