### ISSUE TITLE
ReferenceError: AggregateError is not defined on attempting to bump to 0.30.0

### ISSUE THREAD

**Issue by trivikr** [vitest-dev/vitest#3158]
### Describe the bug

The following error is thrown when attempting to bump vitest to `v0.30.0`

```console
⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
ReferenceError: AggregateError is not defined
 ❯ Object.runTests node_modules/vitest/dist/vendor-cli-api.c04eaa34.js:7257:11
 ❯ Object.runTests node_modules/vitest/dist/vendor-cli-api.c04eaa34.js:7396:5
 ❯ async file:/home/runner/work/aws-sdk-js-codemod/aws-sdk-js-codemod/node_modules/vitest/dist/vendor-cli-api.c04eaa34.js:13913:9
 ❯ Vitest.runFiles node_modules/vitest/dist/vendor-cli-api.c04eaa34.js:13927:12
 ❯ Vitest.start node_modules/vitest/dist/vendor-cli-api.c04eaa34.js:13836:5
 ❯ startVitest node_modules/vitest/dist/vendor-cli-api.c04eaa34.js:[20](https://github.com/awslabs/aws-sdk-js-codemod/actions/runs/4652038000/jobs/8232008884?pr=483#step:7:21)784:5
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
 ❯ start node_modules/vitest/dist/cli.js:106:17
```

### Reproduction

GitHub CI failure: https://github.com/awslabs/aws-sdk-js-codemod/actions/runs/4652038000/jobs/8232008884?pr=483

### System Info

The issues happens on macOS as well as GitHub CI.

```shell
  System:
    OS: macOS 13.2.1
    CPU: (8) x64 Apple M1 Pro
    Memory: 40.89 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.3 - ~/Library/Caches/fnm_multishells/74988_1681066077026/bin/node
    Yarn: 3.5.0 - ~/Library/Caches/fnm_multishells/74799_1681066062748/bin/yarn
    npm: 6.14.18 - ~/Library/Caches/fnm_multishells/74988_1681066077026/bin/npm
    Watchman: 2022.08.15.00 - /opt/homebrew/bin/watchman
  npmPackages:
    vitest: ^0.30.0 => 0.30.0 
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by trivikr** [comment]
The line of code which throws error: https://github.com/vitest-dev/vitest/blob/0ce8364e0dd1ad877d29eaad1b8b52b76f7b3298/packages/vitest/src/node/pools/threads.ts#L145

Probably related to https://github.com/vitest-dev/vitest/pull/3103

**Comment by trivikr** [comment]
This could be happening as AggregateError support was added in Node.js 15.x+ with v8 8.6
https://nodejs.org/en/blog/release/v15.0.0#v8-86---35415

Do `thread.ts` need to import AggregateErrorPonyfill from utils? 
```js
import type { AggregateError as AggregateErrorPonyfill } from '../../utils'
```

**Comment by trivikr** [comment]
I replaced `AggregateError` with `Error` and the error changed to:

```console
ReferenceError: performance is not defined
```

The `performance` is not global in Node.js 14.x, and requires import from `perf_hooks`.
Looks like performance was used in vitest source code without import from `perf_hooks` somewhere between versions `0.29.2` and `0.30.0`

**Comment by trivikr** [comment]
This could be related to adding custom `isNodeBuiltin` API call in https://github.com/vitest-dev/vitest/pull/2766

**Comment by trivikr** [comment]
I noticed `performance` is imported from `perf_hooks` in the source code in `vitest` and `vite-node` workspaces.
* https://github.com/vitest-dev/vitest/blob/0ce8364e0dd1ad877d29eaad1b8b52b76f7b3298/packages/vitest/src/node/reporters/base.ts#L1
* https://github.com/vitest-dev/vitest/blob/0ce8364e0dd1ad877d29eaad1b8b52b76f7b3298/packages/vite-node/src/server.ts#L1

And the import was missed in https://github.com/vitest-dev/vitest/pull/3103/files#diff-1dd42957b6a1b54eefc60f69188d482af54ba3cd308a166e2ce9f970ed784b41, in file which contains v8 import from `node:v8`

I posted a fix in https://github.com/vitest-dev/vitest/pull/3159.
Feel free to cherry-pick it, and add tests. I think we'll need a `v0.30.1` release.

**Comment by ST-DDT** [comment]
v0.30.1 fixed the issue for us. Thank you!

- https://github.com/faker-js/faker/pull/2034
