### ISSUE TITLE
Irrelevant suggestion in issue template

### ISSUE THREAD

**Issue by benmccann** [vitest-dev/vitest#316]
### Describe the bug

The issue template has:
> 1. Run `vite` or `vite build` with the `--debug` flag.

I'm guessing this got copied from the Vite issue template because it doesn't quite make sense to me

### Reproduction

https://raw.githubusercontent.com/vitest-dev/vitest/main/.github/ISSUE_TEMPLATE/bug_report.yml

### System Info

```shell
n/a
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
How about just editing it and throwing a PR? Thanks1

**Comment by benmccann** [comment]
I wasn't quite sure what new text would be preferred there

**Comment by patak-dev** [comment]
We should change it to `vitest` or `vitest run`, until we have a debug flag.

Actually, @antfu, should we remove this box? It is optional if a reproduction is provided, and we should always ask for a reproduction... I don't know how useful it is to have these logs in each issue

**Comment by antfu** [comment]
@patak-dev sure, let's remove it for now
