### ISSUE TITLE
Unable to debug vitest tests / source map not recognized

### ISSUE THREAD

**Issue by dreamorosi** [vitest-dev/vitest#3175]
### Describe the bug

When `vitest@^0.30.0` in a TypeScript codebase, I'd like to set breakpoints while debugging.
The debugger doesn't recognize the breakpoints and either skips them or puts them in different lines, as well as returning earlier than expected, suggesting that the debugger is not using the correct source/source map.

See video (repro steps & minimal example below):

https://user-images.githubusercontent.com/7353869/231108700-77fdc7d4-05cb-41af-8f55-29ca7babc73f.mp4

### Reproduction

0. Clone the repo: https://github.com/dreamorosi/vitest-vscode-issue/tree/main (this is a barebones setup with typescript, vitest, and one test+one file)
1. Go to `src/mycode.ts`
2. Place one breakpoint at each line where the comments say it (L7 & L9)
3. Start a debugging session using the Test pane provided by the Vitest VSCode extension
4. See that the debugger doesn't work and jumps to different lines (see video below)

Alternatively, instead of step 3, start a debugging session using the [recommended launch settings in the vitest docs](https://vitest.dev/guide/debugging.html#debugging) and observe the same behavior.

### System Info

```shell
System:
    OS: macOS 12.6.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 77.05 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/Library/Caches/fnm_multishells/71008_1681201429706/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.6.4 - ~/Library/Caches/fnm_multishells/71008_1681201429706/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Safari: 16.4
  npmPackages:
    vitest: ^0.30.0 => 0.30.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dreamorosi** [comment]
Hi @sheremet-va, I see that you have closed the issue as completed with a PR.

Any chance you could share when it will be published to npm?

**Comment by sheremet-va** [comment]
> Hi @sheremet-va, I see that you have closed the issue as completed with a PR.
> 
> Any chance you could share when it will be published to npm?

7 minutes ago

**Comment by dreamorosi** [comment]
I saw, thank you, I edited the comment right after.


Also I confirm that the issue is fixed, thank you for the quick turnaround.
