### ISSUE TITLE
Allow multiple directories to be specified using the cli option --dir

### ISSUE THREAD

**Issue by WtfJoke** [vitest-dev/vitest#3194]
### Clear and concise description of the problem

As a developer using Vitest CLI I want to run tests in different folders but exclude tests in other folder so that I can only run tests in folders I like and dont need to run multiple vitest commands.

Example:
I have three types of test (two folders with fast unit tests and one folder with slow integration tests). When I try to run all fast tests this is currently not possible using the `--dir` option.

In jest I was able to achieve this behaviour using `jest --roots fastTestFolder1 fastTestFolder2`
I might can contribute this if you point me in the right direction.

### Suggested solution

Allow passing multiple directories to `--dir` cli option.

### Alternative

When there is an option to exclude a directory, this would solve my problem as well.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Can't you just use `test.exclude` with a folder?

**Comment by sheremet-va** [comment]
Or with CLI:

```
vitest fastTestFolder1/ fastTestFolder2/
```

**Comment by WtfJoke** [comment]
Thanks @sheremet-va for that fast answer. It works 🎉 
I wasnt aware that you can also specify folders or parts of path like that (I was experimenting with `--testNamePattern` instead🤦. 
Sorry for the noise
