### ISSUE TITLE
multiline strings are not redered in full when toMatchInlineSnapshot fails

### ISSUE THREAD

**Issue by capaj** [vitest-dev/vitest#3201]
### Describe the bug

I have this expect:
```
 expect(replaceNestedFields(test)).toMatchInlineSnapshot(
      '"{ systemInfo {...} me {...} }"'
    )
```

and the message is:
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/server/replaceNestedFields.spec.js > replaceNestedFields > should replace nested fields
Error: Snapshot `replaceNestedFields > should replace nested fields 1` mismatched
 ❯ src/server/replaceNestedFields.spec.js:20:39
     18|     }`
     19| 
     20|     expect(replaceNestedFields(test)).toMatchInlineSnapshot(
       |                                       ^
     21|       '"{ systemInfo {...} me {...} }"'
     22|     )

  - Expected  - 1
  + Received  + 1

  - `"{ systemInfo {...} me {...} }"
  + `"{ ␊
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

  Snapshots  1 failed
 Test Files  1 failed (1)
      Tests  1 failed (1)
   Start at  09:25:16
   Duration  97ms


 FAIL  Tests failed. Watching for file changes...
       press u to update snapshot, press h to show help

```

I'd say it would be better to show the string in full, so the message should be

```
  - `"{ systemInfo {...} me {...} }"
  + `"{ 
      systemInfo  }
      me  }
     }
␊
```

I understand why it is imlemented like this, but maybe in case of single line strings in expected the received could always show the whole string?

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-plicts?file=test%2Fbasic.test.ts&initialPath=__vitest__

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 25.63 GB / 62.72 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Brave Browser: 112.1.50.114
    Chrome: 112.0.5615.49
    Firefox: 112.0
  npmPackages:
    @vitest/coverage-c8: 0.30.1 => 0.30.1 
    vite: ^4.2.1 => 4.2.1 
    vitest: 0.30.1 => 0.30.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cefn** [comment]
Does this issue cover the behaviour I'm experiencing in my pipelines, where I get a notification of a snapshot failure, but no detailed notification of the mismatch, even with `--reporter verbose` ? 

![image](https://github.com/vitest-dev/vitest/assets/159819/32ba29ec-c7b1-4bc2-a60f-9d4e727c36aa)

https://github.com/cefn/watchable/actions/runs/7088197269/job/19290116297?pr=55

**Comment by sheremet-va** [comment]
The bug described in the issue itself was actually fixed. With your example, I think something might be wrong in Vitest parser since snapshots should be added as strings there. Please open a separate issue
