### ISSUE TITLE
bug - NextRouter was not mounteded

### ISSUE THREAD

**Issue by gilhrpenner** [vitest-dev/vitest#3204]
### Describe the bug

Hey there,

I posted this on Clerk's discord support channel and although they are not familiar with Vitest they seem to think this is a vitest issue.

I am trying to write a test for a page that is using Clerk's sdk, when I wrap my test with the `<ClerkProvider />` it throws an error about NextRouter not being monteded.

I created a [repository](https://github.com/gilhrpenner/t3-clerk) that reproduces this error

![image](https://user-images.githubusercontent.com/24423300/232645284-ef8f5310-bbe9-40ec-850f-c731363439aa.png)

I am mocking `next/router` with `next-router-mock`, and this is also my first time working with Vitest so there is a slight change I am screwing it up but haven't found anything in the docs to assist with this issue.

### Reproduction

1. `gh repo clone gilhrpenner/t3-clerk`
2. `cd t3-clerk`
3. `npm i`
4. `npm run test`

### System Info

```shell
System:
  OS: macOS 13.3.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 42.19 GB / 64.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 18.16.0 - ~/Library/Caches/fnm_multishells/2727_1681780709234/bin/node
  Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/2727_1681780709234/bin/yarn
  npm: 9.5.1 - ~/Library/Caches/fnm_multishells/2727_1681780709234/bin/npm
Browsers:
  Brave Browser: 112.1.50.119
  Chrome: 112.0.5615.121
  Edge: 112.0.1722.48
  Safari: 16.4
npmPackages:
  @vitejs/plugin-react: ^3.1.0 => 3.1.0 
  @vitest/coverage-c8: ^0.30.1 => 0.30.1 
  vite: ^4.2.1 => 4.2.1 
  vitest: ^0.30.1 => 0.30.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rnnyrk** [comment]
Exact same issue. Mocking in the same way with `next-router-mock` as you do. No success. Did you by any change find a solution?

**Comment by rnnyrk** [comment]
Seems to have fixed the error by wrapping the mounted component with `import { MemoryRouterProvider } from "next-router-mock/MemoryRouterProvider";` in the react testing lib render.

**Comment by gilhrpenner** [comment]
> Seems to have fixed the error by wrapping the mounted component with `import { MemoryRouterProvider } from "next-router-mock/MemoryRouterProvider";` in the react testing lib render.

I had forgotten about this, will check your solution above, thanks!

**Comment by noelzappy** [comment]
@gilhrpenner were you able to get around this issue? Can you share your solution?

**Comment by gilhrpenner** [comment]
> @gilhrpenner were you able to get around this issue? Can you share your solution?

I don't think so, it's been awhile and tbh I can't remember which repo I was working to check.
Sorry
