### ISSUE TITLE
when use require to load svg file

### ISSUE THREAD

**Issue by szengtal** [vitest-dev/vitest#3212]
### Describe the bug

**I made a simple demo**
// index.test.ts
```
import * as svg2 from './test.svg';
const svg1 = require('./test.svg')
```
with any svg file,for example,here is my 'test.svg'
```
<?xml version="1.0" encoding="UTF-8"?>
<svg width="250px" height="125px" viewBox="0 0 250 125" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
</svg>
```

after that ,when I run command 'yarn test'
![image](https://user-images.githubusercontent.com/8534930/233100022-a789eb99-4f02-4ec7-829c-814cf6e7ea27.png)

Finally, I want to say that in order to reproduce the problem, I provide the simplest demo.The actual project is much more complicated. 
My project references a react component library, which uses require(...svg ). I can't modify the referenced component package, and it works fine by itself.I used some methods, such as alias, vite-plugin-svgr, but none of them worked

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-qcc5y1?file=test%2Fsuite.test.ts

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 235.84 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.10.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Chrome Canary: 114.0.5711.3
    Safari: 16.3
  npmPackages:
    @vitest/coverage-c8: ^0.28.5 => 0.28.5 
    vitest: ^0.28.5 => 0.28.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by justinzpc** [comment]
vite seem not support  use cjs to import, try to use "import.meta.glob" to instead

**Comment by LukeNotable** [comment]
Related: https://github.com/vitest-dev/vitest/issues/748

Same problem, when the `require()` is in a library, what can I do?

**Comment by sheremet-va** [comment]
Vitest doesn't support using `require` to transform files. You can transform it yourself:

```js
import { createRequire } from 'node:module'
const require = createRequire(import.meta.url)
require.extensions['.svg'] = (_, filename) => `module.exports = "${filename}"`
```
