### ISSUE TITLE
experimentalOptimizer: tests only succeed when a cached version of React exists

### ISSUE THREAD

**Issue by kherock** [vitest-dev/vitest#3215]
### Describe the bug

I realize that `experimentalOptimizer` is now disabled in the 0.30 release, but I just wanted to bring attention to this issue since I do need the feature, and I've been unable to find any other reports of it in either the vite or vitest repos.

I currently have a component that transitively depends on a "bad" library that improperly packages its ESM (specifically, `date-fns/locale`). Node.js isn't able to load this, but Vite's resolver can. After enabling `deps.experimentalOptimizer`, everything seems to work! But only after running the test suite twice.

```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

// ^ lots and lots of these

TypeError: Cannot read properties of null (reading 'useState')
 ❯ useState node_modules/react/cjs/react.development.js:1622:21
 ❯ shell/src/components/InputList.tsx:16:35
     14| const InputMain = forwardRef<HTMLInputElement, InputListProps>(
     15|   ({ value = [], onChange, ...props }, ref) => {
     16|     const [current, setCurrent] = useState<string>('');
       |                                   ^
     17| 
     18|     const addInput = (): void => {
 ❯ renderWithHooks shell/node_modules/.vite/deps/chunk-Y7ICMNPM.js:12171:26
 ❯ updateForwardRef shell/node_modules/.vite/deps/chunk-Y7ICMNPM.js:14327:28
 ❯ beginWork shell/node_modules/.vite/deps/chunk-Y7ICMNPM.js:15934:22
 ❯ beginWork$1 shell/node_modules/.vite/deps/chunk-Y7ICMNPM.js:19749:22
 ❯ performUnitOfWork shell/node_modules/.vite/deps/chunk-Y7ICMNPM.js:19197:20
 ❯ workLoopSync shell/node_modules/.vite/deps/chunk-Y7ICMNPM.js:19133:13
 ❯ renderRootSync shell/node_modules/.vite/deps/chunk-Y7ICMNPM.js:19112:15
 ❯ recoverFromConcurrentError shell/node_modules/.vite/deps/chunk-Y7ICMNPM.js:18732:28
```

Basically, what's happening is that there is code in node_modules that depends on and imports React. What happens is that there is something in Vitest that causes code to resolve the original copy of `node_modules/react` before subsequent runs load it from `node_modules/.vite/deps/chunk-XXXX.js`. I've verified this behavior in a debugger by checking the `[[FunctionLocation]]` property from React imports.

Subsequent runs are successful until I either clear `node_modules/.vite/deps` or set `optimizeDeps.force` to `true`.

Based on my understanding of the feature, it should be possible to avoid this duplicate instance of react with the following config

```ts
export default defineProject({
  plugins: [react({ fastRefresh: false })],
  test: {
    deps: {
      experimentalOptimizer: {
        enabled: true,
      },
    },
    environment: 'jsdom',
    globals: true,
  },
  optimizeDeps: {
    exclude: ['react', 'react-dom', 'react-dom/client', 'react-dom/test-utils'],
  },
});
```

however, esbuild yells at me when I try doing that.

```
✘ [ERROR] The entry point "react" cannot be marked as external


⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Build failed with 1 error:
error: The entry point "react" cannot be marked as external
 ❯ failureErrorWithLog node_modules/esbuild/lib/main.js:1636:15
 ❯ node_modules/esbuild/lib/main.js:1048:25
 ❯ runOnEndCallbacks node_modules/esbuild/lib/main.js:1471:45
 ❯ buildResponseToResult node_modules/esbuild/lib/main.js:1046:7
 ❯ node_modules/esbuild/lib/main.js:1058:9
 ❯ requestCallbacks.on-end node_modules/esbuild/lib/main.js:1057:54
 ❯ handleRequest node_modules/esbuild/lib/main.js:723:19
 ❯ handleIncomingPacket node_modules/esbuild/lib/main.js:745:7
 ❯ Socket.readFromStdout node_modules/esbuild/lib/main.js:673:7

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: {
  "errors": [
    {
      "detail": undefined,
      "id": "",
      "location": null,
      "notes": [],
      "pluginName": "",
      "text": "The entry point "react" cannot be marked as external",
    },
  ],
  "warnings": [],
}
```

### Reproduction

I'm having trouble setting up React with the StackBlitz starter. I'll do my best to provide a minimal reproduction on a repo if the problem isn't obvious.

### System Info

```shell
System:
    OS: macOS 12.6.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 93.73 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - /private/var/folders/9f/kl_c86q5651fqmhmzf63jb0x5t_d9j/T/xfs-d5815730/node
    Yarn: 3.4.1 - /private/var/folders/9f/kl_c86q5651fqmhmzf63jb0x5t_d9j/T/xfs-d5815730/yarn
    npm: 8.19.3 - ~/.local/share/homebrew/bin/npm
  Browsers:
    Firefox: 102.2.0
    Safari: 16.3
  npmPackages:
    @vitest/coverage-c8: ^0.30.1 => 0.30.1 
    @vitest/ui: ^0.30.1 => 0.30.1 
    vite: ^4.2.2 => 4.2.2 
    vitest: ^0.30.1 => 0.30.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest 0.31.4 changes how `experimentalOptimizer` works. Now Vitest only optimizes dependencies inside `experimentalOptimizer.include` (which can be populated by plugins).
