### ISSUE TITLE
Workspaces generate inaccurate c8 coverage reports

### ISSUE THREAD

**Issue by kherock** [vitest-dev/vitest#3220]
### Describe the bug

The C8 test coverage provider reports different statistics and inaccurate line numbers when the reporter runs on a workspace. When I preview the HTML report, the code highlighted is about 10 lines offset from where the actual uncovered code is. The column number offset also appear to shift 1 or 2 characters.

### Reproduction

Vitest hangs when generating coverage in StackBlitz - I will provide a reproduction of this on GitHub when I have a chance.

### System Info

```shell
System:
    OS: macOS 12.6.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 112.97 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.local/share/homebrew/bin/node
    Yarn: 1.22.19 - ~/.local/share/homebrew/bin/yarn
    npm: 8.19.3 - ~/.local/share/homebrew/bin/npm
  Browsers:
    Firefox: 102.2.0
    Safari: 16.3
  npmPackages:
    @vitest/coverage-c8: ^0.30.1 => 0.30.1 
    vitest: ^0.30.1 => 0.30.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
There was a clear bug in how `@vitest/coverage-c8` handles sources maps when workspaces are used. The internal test cases of Vitest were enough to reproduce the issue.

**Comment by ocavue** [comment]
Here is a reproduction I created. I hope this reproduce can help to fix and test the bug

Reproduce Steps:


```bash
$ git clone https://github.com/issueset/vitest-workspace-c8-bug
$ cd vitest-workspace-c8-bug
$ pnpm install
$ pnpm run test:c8
$ pnpm run test:istanbul
```

Open the report html files `coverage/c8/index.html` and  `coverage/c8/istanbul.html`. It's clear that `console.log("A3")` should never be covered, but the c8 report shows that this line is been covered.


![CleanShot 2023-04-25 at 17 32 34@2x](https://user-images.githubusercontent.com/24715727/234236076-35a8dd2b-896b-49b6-be98-2e67ea04d925.png)

**Comment by AriPerkkio** [comment]
Thanks @ocavue - this is how the reproduction case looks like with the changes of #3226:

![image](https://user-images.githubusercontent.com/14806298/234237956-4857ec2a-cdae-4ec1-b329-5360336685c3.png)
