### ISSUE TITLE
Feature Compatibility with jest: Fail on CI if snapshots written

### ISSUE THREAD

**Issue by tkalmar** [vitest-dev/vitest#3227]
### Clear and concise description of the problem

When running in an CI environment vitest writes missing snapshots. Jest fails with:
```
New snapshot was not written. The update flag must be explicitly passed to write a new snapshot.
This is likely because this test is run in a continuous integration (CI) environment in which snapshots are not written by default.
```
This is extremly helpfull to determine missing snapshots.

### Suggested solution

vitest should fail if snapshots are written in an CI environment

### Alternative

Add an cli flag to fail on snapshot write

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by fenghan34** [comment]
Had a quick check on this, now Vitest will fail instead of writing new snapshots https://stackblitz.com/edit/vitest-dev-vitest-7sajqh?file=package.json

**Comment by hi-ogawa** [comment]
Thanks for checking. Yeah, it looks working now, so either it's fixed already or maybe OP has specific setup.

**Comment by tkalmar** [comment]
Indeed with newer Version of vitest it fails as expected. Thanks a lot!

**Comment by moltar** [comment]
Any idea which version releases the fix? Thanks.
