### ISSUE TITLE
worker_threads cannot load typescript file

### ISSUE THREAD

**Issue by vafanassieff** [vitest-dev/vitest#3234]
### Describe the bug

Hey thanks for the awesone tool !

I'm new to the typescript world, i'm trying to test a node js app using `node:worker_threads`
It seems `tsx` run the code if i'm passing a `.ts` file to the `new Worker` constructor but i cannot make it work with `vitest` am i missing something ?

Is there a better way to test apps that leverage `node:worker_threads` ?

Best !

```
 DEV  v0.30.1 /Users/afa/code

stderr | src/tmp/index.test.ts > worker > worker
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/afa/code/src/tmp/worker.ts
    at new NodeError (node:internal/errors:399:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

### Reproduction

index.ts

```typescript
import { Worker } from 'node:worker_threads'

export const testWorker = () => {
  const worker = new Worker(new URL('worker.ts', import.meta.url))

  worker.once('error', console.error)
  worker.once('online', () => {
    worker.postMessage('hello from main')
  })
  worker.on('message', console.log)

  return worker
}
```

worker.ts
```typescript
import { parentPort, workerData } from 'node:worker_threads'

console.log(workerData)

parentPort?.on('message', (message) => {
  console.log(message)
  parentPort?.postMessage(message)
})
```

index.test.ts
```typescript
import { describe, test } from 'vitest'

import { testWorker } from './index.js'

describe('worker', () => {
  test('worker', async ({ helpers, dependencies }) => {
    const worker = await testWorker()
    await new Promise((resolve) => setTimeout(resolve, 1000))
  })
})
```
vitest.config.ts
```typescript
import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    singleThread: true,
    threads: false,
    environment: 'node'
  }
})
```

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 14.26 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/Library/Caches/fnm_multishells/16671_1682177604979/bin/node
    npm: 9.5.0 - ~/Library/Caches/fnm_multishells/16671_1682177604979/bin/npm
  Browsers:
    Chrome: 112.0.5615.49
    Firefox: 111.0
    Firefox Developer Edition: 112.0
    Safari: 16.4
  npmPackages:
    @vitest/coverage-c8: 0.30.1 => 0.30.1 
    vitest: 0.30.1 => 0.30.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest doesn't process those and probably won't because of how module resolution works. You can try running Vitest with Node loader manually though:

```ts
node ./node_modules/vitest/vitest.mjs --loader tsx
```

(I did not try this, but something like this should work.)

**Comment by vafanassieff** [comment]
Hello thanks for your quick reply !

The hint for the loader was right, i just need to start the worker thread like this

```typescript
  const worker = new Worker(new URL('worker.ts', import.meta.url), {
      execArgv: process.env.VITEST ? ['--loader', 'tsx'] : undefined,
  })
 ```
