### ISSUE TITLE
Coverage being aggressively cached

### ISSUE THREAD

**Issue by wtchnm** [vitest-dev/vitest#324]
### Describe the bug

The coverage report is not being updated when a test is modified. I tried with the `clean` and `cleanOnRerun` options with no luck.

### Reproduction

1. In the Vitest repository, go to the `test/testing-lib-react` directory.
2. Run `pnpm coverage` and exit after the coverage report is generated.
3. Delete the `src/App.test.tsx` and the `src/components/input.test.tsx` tests.
4. Run `pnpm coverage` again. The coverage report should only include the `src/hooks/useCounter.ts` file, but it looks like the previous one.

### System Info

```shell
System:
    OS: Linux 5.15 undefined
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 6.86 GB / 15.60 GB
    Container: Yes
    Shell: 3.3.1 - /usr/bin/fish
  Binaries:
    Node: 16.13.1 - /usr/bin/node
    Yarn: 1.22.15 - ~/.npm-global/bin/yarn
    npm: 8.3.0 - /usr/bin/npm
  Browsers:
    Brave Browser: 96.1.33.106
    Firefox: 95.0.2
  npmPackages:
    @vitejs/plugin-react: ^1.1.3 => 1.1.3 
    vite: ^2.7.7 => 2.7.7 
    vitest: workspace:* => 0.0.115
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Should be fixed

**Comment by wtchnm** [comment]
It's fixed, thanks @antfu!
