### ISSUE TITLE
When running using 'vitest workspace' the imported module path needs relative to root

### ISSUE THREAD

**Issue by yarinsa** [vitest-dev/vitest#3242]
### Describe the bug

For some reason vi.mock wasn't getting called. 
I thought it's related to this [issue](https://github.com/vitest-dev/vitest/issues/2840#issuecomment-1518602932). 
I [debugged client.mjs](https://github.com/vitest-dev/vitest/blob/main/packages/vite-node/src/client.ts#L262) coming from 'Vite-node'. Which is used by [dependencyRequest](https://github.com/vitest-dev/vitest/blob/f3ba401bd3cfcfc8b89341b4ea32efd273f03784/packages/vitest/src/runtime/execute.ts#L114).. Since vitest is running from the root, it checks if it has mock the declares it in the same way. 

### Reproduction

I was trying to create reproduction but it's a bit complex with stackblitz (as they resolve imports differently), hance there it wasn't working at all. 

[Stackblitz](https://stackblitz.com/edit/vitest-dev-vitest-kp2vyn?file=vitest.workspace.ts,test-2%2Fpackage.json,package.json,test-2%2Ftsconfig.json,test-2%2F__tests__%2Fsuite.test.tsx,test-2%2Fsrc%2FApp.tsx,test-2%2Fsrc%2Fnetwork.ts,test-2%2F.eslintrc.cjs&initialPath=__vitest__)

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (12) arm64 Apple M2 Max
    Memory: 45.95 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    npm: 9.6.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 16.1
  npmPackages:
    vitest: * => 0.30.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You don't have to use stackblitz as a reproduction.

**Comment by sheremet-va** [comment]
Also, your reproduction doesn't even have a workspace project in `test-2`. You only have an inline workspace which always fallbacks root to the root of the project, you would need to define `root` there yourself.

**Comment by yarinsa** [comment]
@sheremet-va Here is a [reproduction](https://stackblitz.com/edit/vitest-dev-vitest-kp2vyn?file=vitest.workspace.ts,test-2%2Fpackage.json,package.json,test-2%2Ftsconfig.json,test-2%2F__tests__%2Fsuite.test.tsx,test-2%2Fsrc%2FApp.tsx,test-2%2Fsrc%2Fnetwork.ts,vitest.config.ts&initialPath=__vitest__) .
I was unable to make it work there as well. So maybe I was wrong in the case of the bug. But still vi.mock dooesn't work so it is a valid reproduction...

**Comment by sheremet-va** [comment]
> @sheremet-va Here is a [reproduction](https://stackblitz.com/edit/vitest-dev-vitest-kp2vyn?file=vitest.workspace.ts,test-2%2Fpackage.json,package.json,test-2%2Ftsconfig.json,test-2%2F__tests__%2Fsuite.test.tsx,test-2%2Fsrc%2FApp.tsx,test-2%2Fsrc%2Fnetwork.ts,vitest.config.ts&initialPath=__vitest__) .
> I was unable to make it work there as well. So maybe I was wrong in the case of the bug. But still vi.mock dooesn't work so it is a valid reproduction...

The filepath in `vi.mock` is relative to the file you define mock in. This was always the case.

**Comment by sheremet-va** [comment]
You don't define root anywhere, you don't define workspace as a glob pattern. What do you expect should happen? I don't understand you issue.

**Comment by yarinsa** [comment]
What do you mean define root? 
I am closing this issue as I can't reproduce this on stackblitz..
