### ISSUE TITLE
Import error when testing file with shebang

### ISSUE THREAD

**Issue by H0R5E** [vitest-dev/vitest#3244]
### Describe the bug

As of the 20th of April, I have been unable to test files that start with a shebang and import the `fileURLToPath` function from the `url` module.

### Reproduction

Given an `index.ts` file at the package root as follows:

```ts
#!/usr/bin/env node

import { fileURLToPath } from 'url'

const __dirname = fileURLToPath(new URL('.', import.meta.url))
```

And a test file at the path `tests/index.test.ts` like so:

```ts

describe('index.ts', () => {
  let test: typeof import('..')

  beforeEach(async () => {
    test = await import('..')
  })

  it('main', async () => {
  })

})
```

Running the command `npx vitest run --reporter verbose .\tests\index.test.ts` gives the following error:

```
 RUN  v0.29.8 E:/Programming/JS/unversioned/vitest_shebang_bug

 ❯ tests/index.test.ts (1)
   ❯ index.ts (1)
     × main
       \ [ beforeEach ]

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  tests/index.test.ts > index.ts > main
SyntaxError: Invalid or unexpected token
 ❯ new Script node:vm:100:7
 ❯ createScript node:vm:265:10
 ❯ Object.runInThisContext node:vm:313:10
 ❯ tests/index.test.ts:6:12
      4|
      5|   beforeEach(async () => {
      6|     test = await import('..')
       |            ^
      7|   })
      8|

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  1 failed (1)
   Start at  10:43:32
   Duration  568ms (transform 73ms, setup 0ms, collect 24ms, tests 15ms)
```

Removing the shebang from `index.ts` allows the tests to pass.

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
    Memory: 7.08 GB / 15.94 GB
  Binaries:
    Node: 18.12.1 - C:\Anaconda3\envs\_bluebox_frontend\node.EXE
    Yarn: 1.22.19 - C:\Anaconda3\envs\_bluebox_frontend\yarn.CMD
    npm: 9.6.2 - C:\Anaconda3\envs\_bluebox_frontend\npm.CMD
  Browsers:
    Edge: Spartan (8.20230424104508.), Chromium (112.0.1722.58), ChromiumDev (Transcript started, output file is C:\Users\Work\Documents\WindowsPowerShell\Transcripts\PowerShell_transcript.JASPER-PRO.AfrLA0Om.20230424104508.txt)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    vitest: ^0.29.7 => 0.29.8
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is a bug with Vite: https://github.com/vitejs/vite/issues/12976

**Comment by H0R5E** [comment]
For reference, using yarn, I am able to pin vite to a working version in my `package.json` using a `resolutions` block, as follows:

```json
{
  "name": "vitest-shebang-bug",
  "description": "Example of bug when testing file with shebang",
  "author": "Mathew Topper <damm_horse@yahoo.co.uk>",
  "version": "0.0.0",
  "type": "module",
  "exports": {
    ".": {
      "types": "./index.d.ts",
      "import": "./index.js"
    },
    "./package.json": "./package.json"
  },
  "types": "./index.d.ts",
  "scripts": {
    "test": "vitest"
  },
  "devDependencies": {
    "typescript": "^4.9.5",
    "vitest": "^0.29.7"
  },
  "resolutions": {
    "vitest/**/vite": "~4.2.0"
  }
}
```
