### ISSUE TITLE
Support shard tests between multiple machines

### ISSUE THREAD

**Issue by Himself65** [vitest-dev/vitest#3246]
### Clear and concise description of the problem

I'm using vitest to replace the playwright, but we have many test cases and I have to separate them into different CI runner.

The playwright support shared tests.

https://playwright.dev/docs/test-parallel#shard-tests-between-multiple-machines

### Suggested solution

```shell
vitest --shared=1/4
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
https://vitest.dev/guide/cli.html#shard
