### ISSUE TITLE
Consider publishing dual format with CommonJS compatibility

### ISSUE THREAD

**Issue by otakustay** [vitest-dev/vitest#325]
### Clear and concise description of the problem

We are moving to `"moduleResolution": "nodenext"` with TypeScript 4.6 nightly build, but for some ecosystem reasons we are unable to introduce `"type": "module"` to our packages.

Although `vite` as a CLI runs without any problem, the `import {expect} from 'vitest'` statement can be errored from TypeScript in IDE: 

```
Module 'vitest' cannot be imported using this construct. The specifier only resolves to an ES module, which cannot be imported synchronously. Use dynamic import instead.ts(1471)
```

This has no actual negative effects to us since we don't transpile `.test.ts`, but a red error is always there whenever we open our tests files.

![image](https://user-images.githubusercontent.com/639549/147439721-9ecbca2e-bb3e-4ba9-9cc9-d4649a35d4a3.png)

### Suggested solution

Consider publish both CJS and ESM formats and having `exports` field in `package.json` also references to CJS files.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by aleclarson** [comment]
Scratch that. Looks like the issue is `"type": "module"` in Vitest's package.json

I can confirm that removing the `type: module` line fixes the TypeScript error. Can we publish Vitest without it, or would that cause problems?
