### ISSUE TITLE
Workspace coverage wrong when a file transforms differently in projects

### ISSUE THREAD

**Issue by AriPerkkio** [vitest-dev/vitest#3251]
### Describe the bug

Writing down the findings from https://github.com/vitest-dev/vitest/pull/3226#discussion_r1173453639 with reproduction case. This affects both `@vitest/coverage-c8` and `@vitest/coverage-istanbul`.

If a single file can transform differently in different workspace projects, the final coverage reported by `@vitest/coverage-<x>` packages will be incorrect. For example:

```
├── vitest.workspace.ts // Declares workspaces ['client', 'server']
├── vitest.config.ts // Enables coverage and sets the options
|
├── client
|  └── test
|     └── user-list.test.js // Imports user-list.js with web/client-side specific transforms
|
├── server
|  └── test
|     └── user-list.test.js // Imports user-list.js with SSR transforms
|
└── shared
   └── user-list.js // Can output both client and server side code depending on environment
```

Here both client and server import `shared/user-list.js` with different code transforms. These produce two different code outputs and source maps.

When generating coverage report the `@vitest/coverage-c8` picks the first source map it finds from project's `vite-node` cache and uses it for both workspace projects. Instead it should be aware of which workspace project the current V8 coverage report belongs to, and use that project's `vite-node` cache.

I haven't yet debugged the `@vitest/coverage-istanbul` case but it's likely picking the first source map it encounters in `istanbul-lib-source-maps` and re-uses that one for both file coverages. Instead it should separate each workspace projects' `coverageMap` completely, and merge them at the end into one.

### Reproduction

- https://github.com/AriPerkkio/vitest/tree/repro/workspace-coverage-with-transforms/test/workspaces
- https://github.com/AriPerkkio/vitest/commit/f9d095cddac68bff6ce9b0233aa0fb7f88c128f6

<details>
  <summary>Source</summary>

```js
export default function run(a = 1, b = 2) {
  //! WORKSPACE_1_REMOVE_START

  // In workspace 1 we remove two functions
  function removedFunctionOne() {
    return 1
  }
  function removedFunctionThree() {
    return 1
  }

  //! WORKSPACE_1_REMOVE_END

  const unusedFunction1 = () => 1
  const unusedFunction2 = () => a ? b : null

  // Coverage of this branch breaks when combined coverage of workspaces is not handled correctly
  if (a === 1000 && b === 1) {
    // This should be uncovered
    return 1001
  }

  //! WORKSPACE_3_REMOVE_START

  // In workspace 3 we remove three branches
  if (a === 100 && b === 1)
    return 101

  if (a === 100 && b === 2)
    return 102

  if (a === 100 && b === 3)
    return 103

  //! WORKSPACE_3_REMOVE_END

  function unusedFunction3() {
    return 1
  }

  // Coverage of this branch breaks when combined coverage of workspaces is not handled correctly
  if (a === 1000 && b === 2) {
    // This should be uncovered
    return 1002
  }

  function unusedFunction4() {
    return 1
  }

  return 'OK'
}
```

</details>

<details>
  <summary>Transformed for workspace 1</summary>

```js
function run(a = 1, b = 2) {
  
  const unusedFunction1 = () => 1;
  const unusedFunction2 = () => a ? b : null;
  if (a === 1e3 && b === 1) {
    return 1001;
  }
  //! WORKSPACE_3_REMOVE_START
  if (a === 100 && b === 1)
    return 101;
  if (a === 100 && b === 2)
    return 102;
  if (a === 100 && b === 3)
    return 103;
  //! WORKSPACE_3_REMOVE_END
  function unusedFunction3() {
    return 1;
  }
  if (a === 1e3 && b === 2) {
    return 1002;
  }
  function unusedFunction4() {
    return 1;
  }
  return "OK";
}
```

</details>

<details>
  <summary>Transformed for workspace 3</summary>

```js
function run(a = 1, b = 2) {
  //! WORKSPACE_1_REMOVE_START
  function removedFunctionOne() {
    return 1;
  }
  function removedFunctionThree() {
    return 1;
  }
  //! WORKSPACE_1_REMOVE_END
  const unusedFunction1 = () => 1;
  const unusedFunction2 = () => a ? b : null;
  if (a === 1e3 && b === 1) {
    return 1001;
  }
  
  function unusedFunction3() {
    return 1;
  }
  if (a === 1e3 && b === 2) {
    return 1002;
  }
  function unusedFunction4() {
    return 1;
  }
  return "OK";
}
```

</details>

### Coverage reports

From left to right: merged broken coverage, workspace 1 coverage, workspace 3 coverage:

The separate workspace specific reports look OK but the merged one is clearly broken.

Istanbul:
<img width="620px" src="https://user-images.githubusercontent.com/14806298/234231357-b523a8b7-c7af-4d5b-ae5b-7873f596397a.png" />
 
C8:
<img width="620px" src="https://user-images.githubusercontent.com/14806298/234231432-dd25c365-84eb-420a-8f80-fed9823525e6.png" />

### System Info

```shell
Vitest `main` + any
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
@sheremet-va, is `WorkspaceProject.getName()` unique enough to identify which project's `fetchCache` should be picked? I'm thinking about passing `projectName: project.getName()` in `WorkerContext` and then pass it as argument to coverage providers when reporting coverage.

**Comment by sheremet-va** [comment]
> is `WorkspaceProject.getName()` unique enough to identify which project's `fetchCache` should be picked?

Yes, they must be unique. The error will be thrown if they are not before tests are running.
