### ISSUE TITLE
Highlight sub_threshold items in coverage html

### ISSUE THREAD

**Issue by herzaso** [vitest-dev/vitest#3253]
### Clear and concise description of the problem

When generating an html coverage, there is no way to distinct items that are above the threshold from those that are below and needs to be fixed.

### Suggested solution

I suggest marking the errors in the table in red or something that will pop up

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
You can use the `watermarks` with `istanbul` provider:
- https://vitest.dev/config/#coverage-watermarks
- https://github.com/istanbuljs/nyc#high-and-low-watermarks

**Comment by herzaso** [comment]
Works great! thanks!
