### ISSUE TITLE
Workspace - all `globalSetup` from all projects are executed when a single test is executed

### ISSUE THREAD

**Issue by StarpTech** [vitest-dev/vitest#3255]
### Describe the bug

I have a workspace file with multiple projects. Every project has a `globalSetup` file. When I debug or run a single test from a single project `vitest run $file or $pattern` all setup files are executed. This should not happen.

```ts
import { defineWorkspace } from 'vitest/config';

export default defineWorkspace([
	{
		root: 'apps/basic1',
		test: {
			globalSetup: 'apps/basic1/test-setup.ts',
		},
	},
        {
		root: 'apps/basic2',
		test: {
			globalSetup: 'apps/basic2/test-setup.ts',
		},
	}
]
```

### Reproduction

See above.

### System Info

```shell
System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 44.57 GB / 62.71 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.165
    Firefox: 112.0.1
  npmPackages:
    vitest: ^0.30.1 => 0.30.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This will probably require a rewrite. Currently, we don't have access to the config until we run a server. And `globalSetup` is basically a plugin that fires up when the server is created. We would need to read the config before running a server and pass it down to `createServer` with `config: false`. This is a major rewrite.

**Comment by StarpTech** [comment]
Thank you for the clarification. This is not good for us because we have a build step before, and it adds significant time to wait to run a single test.

**Comment by StarpTech** [comment]
Can we find a workaround for this?

**Comment by sheremet-va** [comment]
Found a workaround: #4213
