### ISSUE TITLE
workspace with insource test case might interrupt the test

### ISSUE THREAD

**Issue by musicq** [vitest-dev/vitest#3262]
### Describe the bug

When using workspace with insource test, it seems workspace will run every file that matches the glob pattern to detect the insource test cases. But in some cases, such as node, it may take the input from the command line, and should only match a certain case, otherwise will exit the program. see the below code sample

```js
export function run(arg) {
  switch (arg) {
    case 1:
      return 1
    default:
      console.log('never reach')
      process.exit(1)
  }
}
```

caller
```js
run(process.argv[2])
```

in this case, the test will exit even though this file doesn't include any insource tests.

```log
~/projects/vitest-dev-vitest-fqu7ss 4s
❯ npm run test:run
$ vitest run

 RUN  v0.30.1 /home/projects/vitest-dev-vitest-fqu7ss


⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unexpected Exit ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: process.exit called with "1"
 ❯ run packages/a/src/index.js:7:15
      5|     default:
      6|       console.log('never reach')
      7|       process.exit(1)
       |               ^
      8|   }
      9| }
 ❯ eval packages/a/src/index.js:11:1
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-fqu7ss?file=packages/a/src/index.js

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitest/ui: latest => 0.30.1 
    vite: latest => 4.3.2 
    vitest: latest => 0.30.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest runs your file because it is part of the `include`. This pattern defines your _test files_.

**Comment by musicq** [comment]
@sheremet-va Thanks for the explanation, that works!
