### ISSUE TITLE
Tests report does not cover exported function from typescript.

### ISSUE THREAD

**Issue by nicolaefilat** [vitest-dev/vitest#3268]
### Describe the bug

I have a file called `utils.ts` in the folder `src/logic/utils.ts` that has a simple function that adds three numbers.
```ts
export function addThreeNumbers(a: number, b: number, c: number) {
    return a + b + c;
}
```
in the folder `src/__tests__/unit/utils.test.ts` I have a test for this sum function.
```ts
import { describe, it, expect } from 'vitest'
import {addThreeNumbers} from "src/logic/utils";


describe("Sum of three numbers test", () =>{
    it("1 + 2 + 3 = 6",()=>{
        expect(addThreeNumbers(1,2,3)).toBe(6)
    })
})
```

My vitest.config.ts file looks like this
```ts
export default mergeConfig(
    viteConfig,
    defineConfig({
        test: {
            environment: 'jsdom',
            exclude: [...configDefaults.exclude, 'e2e/*'],
            root: fileURLToPath(new URL('./', import.meta.url)),
            coverage: {
                all: true,
                provider: 'c8',
                // move coverage report to ./tests/unit/coverage
                reportsDirectory: './tests/unit/coverage',
                include: ['src/**/*.vue', "src/**/*.ts", "src/**/*.js"],
                exclude: ['src/router', "**/__tests__/**"]
            },
        }
    })
)
```

I run `vitest run --coverage` and I see that `✓ src/__tests__/unit/utils.test.ts (1)` is ran but
in the report `utils.ts` has 0 statements covered.

### Reproduction

I hope the files provided are enough to see if there is either a bug or I have a misconfiguration somewhere.

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5700U with Radeon Graphics
    Memory: 5.40 GB / 15.35 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (112.0.1722.58)
    Internet Explorer: 11.0.22000.120

    "vitest": "^0.30.1" (from packages.json)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Could you try removing the `test.coverage.include` and `test.coverage.exclude` and see if the file ends up in the report? And maybe even the `test.root`?

**Comment by AriPerkkio** [comment]
I can reproduce this now. 

When source file is imported using alias the `vitenode.fetchCache` does not contain full path. This gets filtered out in coverage provider.

```ts
import {addThreeNumbers} from "src/logic/utils";
// fetchCache contains entry for "src/logic/utils"
```

```ts
import {addThreeNumbers} from "../../logic/utils";
// fetchCache contains entry for "/x/y/z/repro/src/logic/utils.ts" - Includes the extension and full path
```

**Comment by AriPerkkio** [comment]
The `vitest.config.ts` is missing `alias`. Add following and coverage report is OK:

```ts
    alias: {
      src: fileURLToPath(new URL("./src", import.meta.url)),
    }
```

Or as alternative import the `utils.ts` with full path instead of relying on project root:

```diff
- import {addThreeNumbers} from "src/logic/utils";
+ import {addThreeNumbers} from "../../logic/utils";
```
