### ISSUE TITLE
location of results.json when use test.root in vite.config.ts

### ISSUE THREAD

**Issue by tung1404** [vitest-dev/vitest#3272]
### Describe the bug

Hi,

When I setup vite.config.ts as below, vitest will output the result to `root_project\src\node_modules\.vitest\results.json`
I think its location is `root_project\node_modules\.vitest\results.json`

```js
/// <reference types="vitest" />
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

// https://vitejs.dev/config/
export default defineConfig({
  define: {
    'import.meta.vitest': 'undefined',
  },
  plugins: [react()],
  test: {
    root: 'src',
    globals: true,
    environment: 'happy-dom',
    setupFiles: ['./test-setup.ts'],
    includeSource: ['**/*.{ts,tsx}'],
    mockReset: true,
    restoreMocks: true,
    css: true,
  },
});
```

### Reproduction

{"version":"0.30.1","results":[[":src/App.test.tsx",{"duration":25,"failed":false}]]}

### System Info

```shell
node 14
npm 6.14
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lyx-jay** [comment]
@sheremet-va 
Hi, I find `test: {root:  }` option cause this problem. 
if your test files are in the src/abc/folder, then you set as below:
```ts
export default defineConfig({
  test: {
    root: './src/abc',
  }
});
```
vitest will output the result to `src\abc\node_modules\.vitest\result.json`.
I want to know what is the correct output path? I plan to fix this problem

**Comment by sheremet-va** [comment]
I think we should deprecate `cache.dir` option and just use Vite's `cacheDir`.
