### ISSUE TITLE
bug: error exception after instance custom promise (with jsdom)

### ISSUE THREAD

**Issue by hairyf** [vitest-dev/vitest#3281]
### Describe the bug

```ts
  // 1. create promise
  let resolve, reject;
  const promise = new Promise((_resolve, _reject) => {
    resolve = _resolve;
    reject = _reject;
  }) as any;
  // add any attributes to promise
  promise.a = 1;
  promise.resolve = resolve;
  promise.reject = reject;

  // 2. use promise callback
  promise.finally(() => {
    console.log('---');
  });

  // TypeError: Cannot create property 'type' on string 'manual-reject'
  expect(promise).rejects.toBe('manual-reject');

  // reject promise
  reject('manual-reject');
```

![image](https://user-images.githubusercontent.com/49724027/235646180-e69a6a65-f581-48e4-8949-ce5caa5bb524.png)

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-og7ted?file=test%2Fbasic.test.ts,vite.config.ts,package.json&initialPath=__vitest__

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 1.49 GB / 15.93 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitejs/plugin-react: ^4.0.0 => 4.0.0 
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0 
    @vitest/coverage-c8: ^0.29.2 => 0.29.2 
    vite: ^4.2.0 => 4.2.0 
    vitest: ^0.30.1 => 0.30.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You need to await expect if you pass a promise (use `rejects`/`resolves`)

**Comment by sheremet-va** [comment]
I see now another issue with your repro, thanks.
