### ISSUE TITLE
"No test suite found in file" Once again

### ISSUE THREAD

**Issue by xania** [vitest-dev/vitest#3296]
### Describe the bug

I've seen the error "No test suite found in file" many times over the course of months and it is reported at least twice before without clear resolution or at least a resolution that is helpful for my case:
- #847 
- #2604

sometimes, the error it disappears, just today I though I understood how to solve it but it appeared again. I am not sure why this happens. I was able to lock it down though to always fail with the code provided in the reproduction info block.

### Reproduction

minimal reproduction code:
https://github.com/xania/view/tree/vitest-no-test-suite-found

> pnpm install

![image](https://user-images.githubusercontent.com/34893682/236072641-e7dd05df-4930-47ce-a564-4ee3ec27ba09.png)

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 17.43 GB / 31.68 GB
  Binaries:
    Node: 19.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.0 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Chrome: 107.0.5304.122
    Edge: Spartan (44.22621.1555.0), Chromium (112.0.1722.68)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vite: ^4.3.4 => 4.3.4
    vitest: ^0.31.0 => 0.31.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
I can reproduce the issue but there seems to be two different versions of Vitest in your monorepo. When you install matching versions of it to both packages, the tests will pass just fine. Note that in `0.x.x` version range the minor versions differentiate matching packages. 

https://github.com/xania/view/blob/61a0572c65ce96b2c2b9384172f66f7591a68c23/package.json#L14

https://github.com/xania/view/blob/61a0572c65ce96b2c2b9384172f66f7591a68c23/packages/vite-plugin-resumable/package.json#L46

Update the `packages/vite-plugin-resumable/packages.json` to have same version of Vitest as root `package.json` has.

**Comment by sheremet-va** [comment]
Should we check the version when collecting tests? Print an error, if the version inside the tests is not the same as the one that imports the test file, and give possible solutions.

**Comment by sheremet-va** [comment]
> Why are different versions used to begin with? Clearly same version must be used. Ideally , vitest should not switch version in the middle of the process

Vitest doesn't control that. Your package manager does.

**Comment by xania** [comment]
Depends on the perspective, I run vitest once from my perspective. the fact that I have a workspace with multiple packages where each controls it's version should (idealy) not matter. 
Why is vitest version for booting testsuites different than the version that collects tests for the same testsuites? If it's only a technical reason than I would like to suggest to improve that part

**Comment by sheremet-va** [comment]
> Depends on the perspective, I run vitest once from my perspective. the fact that I have a workspace with multiple packages where each controls it's version should (idealy) not matter. 
> Why is vitest version for booting testsuites different than the version that collects tests for the same testsuites? If it's only a technical reason than I would like to suggest to improve that part

It doesn't depend on perspective, it's a statement of fact. You run with root Vitest, but use another Vitest in you package. There is nothing to discuss.
