### ISSUE TITLE
variable of module not shared if vi.mock is used in v0.31.0

### ISSUE THREAD

**Issue by freakzlike** [vitest-dev/vitest#3300]
### Describe the bug

After update to `v0.31.0` some tests are failing which rely on exporting a variable which is set within `beforeEach` when `vi.mock` is used:

`basic.test.ts`
```typescript
import { it, expect, vi } from 'vitest';
import { foo } from './set-foo';

// Comment this to make the test work
vi.mock('./somefile');

it('should be 1', () => {
  expect(foo).toBe(1);
});
```

`set-foo.ts`
```typescript
import { beforeEach, afterEach } from 'vitest';

export let foo: number;

beforeEach(() => {
  foo = 1;
});

afterEach(() => {
  foo = 2;
});
```

Running the test will result in `AssertionError: expected undefined to be 1 // Object.is equality`

I have verified that `beforeEach` and `afterEach` are called correctly. Commenting the `vi.mock` will make the test work. Not sure if I've missed something in the change log.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-hcvj1e?file=test/basic.test.ts

`v0.30.1` with `vi.mock` = working
`v0.31.0` without `vi.mock` = working
`v0.31.0` with `vi.mock` = not working

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (5) x64 AMD Ryzen 5 4500U with Radeon Graphics
    Memory: 4.67 GB / 6.78 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  npmPackages:
    @vitejs/plugin-vue: 4.2.1 => 4.2.1
    @vitest/coverage-istanbul: 0.31.0 => 0.31.0
    vite: 4.3.4 => 4.3.4
    vitest: 0.31.0 => 0.31.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest now rewrites your imports into dynamic ones, when you use `vi.mock`. Your code turns into:

```ts
const { it, expect, vi } = await import('vitest');

vi.mock('./somefile');

const { foo } = await import('./set-foo');
```

So because it's destructured, you lose the getter. This is a bug.
