### ISSUE TITLE
The expected and received values ​​seem to be reversed

### ISSUE THREAD

**Issue by btea** [vitest-dev/vitest#3309]
### Describe the bug

```expect(xx).toBe(xx)``` 
When an error occurs, the expected value and received value prompt information seem to be reversed.

vitest

![image](https://user-images.githubusercontent.com/24516654/236593072-73945e38-040b-4bf4-90a0-683797862db5.png)

jest

![image](https://user-images.githubusercontent.com/24516654/236593103-314e22dc-6a16-466a-be91-8d7fd50521ae.png)

### Reproduction

https://stackblitz.com/edit/node-w1fgff?file=package.json

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 2.54 GB / 15.86 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.22.0 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (112.0.1722.68)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitest/coverage-c8: ^0.29.8 => 0.29.8
    vite: ^4.2.1 => 4.2.1
    vitest: ^0.31.0 => 0.31.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
The colors in the tooltip are reversed, yeah.

**Comment by btea** [comment]
So, the correct tooltip might be something like: 
```ts
- Expected -1 (green)
- Received +1 (red)

- 1  (green)
+ 2  (red)
```
