### ISSUE TITLE
Compare Sets values instead of indexes with `toEqual`

### ISSUE THREAD

**Issue by LilaRest** [vitest-dev/vitest#3310]
### Clear and concise description of the problem

When comparing two `Set` objects of the same length with `toEqual`, Vitest successfully compares them in regard of the values they contain. So this expectation passed successfully:
```ts
expect(new Set(["a", "b", "c"])).toEqual(new Set(["c", "a", "b"]));
```

However, if the length of the compared Sets differs, it looks like Vitest starts comparing their values by index, which makes no sense as Set are unordered. 
So this expectation...
```ts
//        just added this
//              vvv
expect(new Set(["d", "a", "b", "c"])).toEqual(new Set(["c", "a", "b"]));
```
...instead of returning that the received Set has one additional value compared to expected one, will return :
```text
  - Expected  - 2
  + Received  + 1

    Set {
  -   'c',
  +   'd',
      'a',
      'b',
  +   'c',
    }
```

### Suggested solution

As I haven't dived into the Vitest code it will be difficult for me to provide a relevant suggested solution.

However, Jest faced the exact same problem in 2017, and here is the [related issue](https://github.com/jestjs/jest/issues/4286) which ended on a [merged PR](https://github.com/jestjs/jest/pull/4303).

### Alternative

Actually, I've quickly written a custom matcher as workaround until this feature is implemented.
It looks like:
```ts
export function toEqualSet<T> (received: Set<T>, expected: Set<T>) {
  const { isNot } = this;

  const missingValues: T[] = [];
  const unwantedValues: T[] = [];

  for (const value of expected) {
    if (!received.has(value)) missingValues.push(value);
  }

  for (const value of received) {
    if (!expected.has(value)) unwantedValues.push(value);
  }

  if (!missingValues.length && !unwantedValues.length) {
    return {
      pass: true,
      message: () => ""
    };
  }
  else {
    let message = "";
    if (missingValues.length) {
      message += `\nThe received Set misses ${missingValues.length} value(s) from the expected one:`;
      for (const value of missingValues) message += "\n- " + value;
      message += "\n";
    }
    if (unwantedValues.length) {
      message += `\nThe received Set contains ${unwantedValues.length} additional value(s) not found in the expected one:`;
      for (const value of unwantedValues) message += "\n- " + value;
      message += "\n";
    }
    return {
      pass: false,
      message: () => message
    };
  }
}
```

With the same Sets than above, this expectation...
```ts
expect(new Set(["d", "a", "b", "c"])).toEqualSet(new Set(["c", "a", "b"]));
```
...will properly returns:
```text
The received Set contains 1 additional value(s) not found in the expected one:
- d
```

### Additional context

This has been the only broken test in my migration from Jest to Vitest. So thanks for this amazing lib ^^

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Vitest uses the same function to compare values as the jest one, but Vitest prints diff with [concordance](https://github.com/concordancejs/concordance) package, so the output is different.

**Comment by LilaRest** [comment]
> Vitest uses the same function to compare values as the jest one, but Vitest prints diff with [concordance](https://github.com/concordancejs/concordance) package, so the output is different.

@sheremet-va Interesting, thanks for your quick answer! 
So this FR would be more relevant in the concordance repo, but concordance seems unmaintained in the last two years. 

Any idea why Vitest relies on this young and unmaintained lib ?

**Comment by sheremet-va** [comment]
> Any idea why Vitest relies on this young and unmaintained lib ?

We liked its output. The maintainer is still around so it's possible to make contributions there.

**Comment by sheremet-va** [comment]
We switched to Jest output some time ago, so this issue can be closed.
