### ISSUE TITLE
Allow setting max-project-concurrency

### ISSUE THREAD

**Issue by stavalfi** [vitest-dev/vitest#3311]
### Clear and concise description of the problem

Well, Vitest is too good to be true for javascript and nodejs ecosystem. Fast and furious.

Example:
```
* test-file1.test.ts: 10 tests (all defined as `it.concurrent(....)`)
* test-file2.test.ts: 20 tests (all defined as `it.concurrent(....)`)
```

When setting `max-project-concurrency=4`:

### Expected Behavior

At most 4 tests will run in all the test files combined.

### Current Behavior of Vitest

8 tests are running at the same time all the time.

### Why This Feature Needed

Well, I have 100+ heavy e2e tests speard over 10+ files. when setting `maxConcurrency=5`,  50 tests are running and my machine is on fire. 

Help my machine not to burn ;D

### Suggested solution

max-project-concurrency=4

### Alternative

maxConcurrency which is very limiting

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
You can set `maxThreads` to 1, so Vitest doesn't start new processes before the test finished.

**Comment by stavalfi** [comment]
thanks. but if i have 4 files with 1 test only, vitest won't use the max available concurrency.

**Comment by sheremet-va** [comment]
> thanks. but if i have 4 files with 1 test only, vitest won't use the max available concurrency.

Vitest doesn’t know how many tests there are in other files. So even if we implemented it it would be just setting max threads to 1.
