### ISSUE TITLE
`rejects` & `resolves` breaks with thenable objects

### ISSUE THREAD

**Issue by Azarattum** [vitest-dev/vitest#3318]
### Describe the bug

Object that implement `then` are considered valid promises by the language. Therefore this works perfectly:
```js
expect(await { then: (r) => r(42) }).toBe(42);
```

However, since https://github.com/vitest-dev/vitest/commit/bdc06dcbc41a9af074e83e0957ae73afd704c145 `.resolves` and `.rejects` syntax is broken because of use of `.finally` in https://github.com/vitest-dev/vitest/blob/9836ccb48c5a39c0999484f55731f53ba494be17/packages/expect/src/utils.ts#L5 which doesn't necessarily has to be implemented to be a valid promise. So,
```js
expect({ then: (r) => r(42) }).resolves.toBe(42);
```
fails with:
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Invalid Chai property: finally
 ❯ Object.proxyGetter [as get] ../../node_modules/.pnpm/chai@4.3.7/node_modules/chai/lib/chai/utils/proxify.js:78:17
 ❯ recordAsyncExpect ../../node_modules/.pnpm/@vitest+expect@0.31.0/node_modules/@vitest/expect/dist/index.js:629:23
 ❯ Proxy.<anonymous> ../../node_modules/.pnpm/@vitest+expect@0.31.0/node_modules/@vitest/expect/dist/index.js:1237:18
```

**Possible Solution**: conditionally call `finally` method only when it exists.

### Reproduction

```js
expect({ then: (r) => r(42) }).resolves.toBe(42);
```

https://stackblitz.com/edit/vitest-dev-vitest-1d2x5n?file=test/basic.test.ts

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 1.02 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    npm: 9.5.1 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 113.1.51.110
    Safari: 16.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> Possible Solution: conditionally call finally method only when it exists.

I don't like this solution, but maybe we can do `try/finally` there.
