### ISSUE TITLE
`repeats` does not work at all

### ISSUE THREAD

**Issue by Shinigami92** [vitest-dev/vitest#3334]
### Describe the bug

There is a v0.31.0 new feature `repeats` #2652 

At "real world" it does not work at all.

There are tests in the code base, but somehow the bundled dist seems not to work

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-kzdmn9?file=test/suite.test.ts

### System Info

```shell
System:
    OS: Linux 6.1 Arch Linux
    CPU: (28) x64 Intel(R) Core(TM) i9-10940X CPU @ 3.30GHz
    Memory: 26.91 GB / 62.48 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Firefox: 112.0.2
  npmPackages:
    @vitest/coverage-c8: ~0.31.0 => 0.31.0 
    @vitest/ui: ~0.31.0 => 0.31.0 
    vite: ~4.3.5 => 4.3.5 
    vitest: ~0.31.0 => 0.31.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It doesn't repeat the code in "describe" block, it repeats _tests_. "describe" just collects and groups tests

**Comment by Shinigami92** [comment]
> It doesn't repeat the code in "describe" block, it repeats _tests_. "describe" just collects and groups tests

Yeah, so it only works right now if
1. it is a describe block, that wraps directly an `it`
2. as you said, only the internal `it`s, but also here the default does not seem to be 5 but 1 if no options are passed at all or the options are empty, so the docs about it is default=5 is also lying :thinking: 

all in all, it feels very clunky and buggy :slightly_frowning_face:

**Comment by Shinigami92** [comment]
> > but also here the default does not seem to be 5 but 1 if no options are passed at all or the options are empty, so the docs about it is default=5 is also lying thinking
> 
> What do you mean? How can default be 5?

![image](https://github.com/vitest-dev/vitest/assets/7195563/1b2887a5-e157-4aa1-8246-d308c933af11)

https://github.com/vitest-dev/vitest/blob/fde628ad3dbcd4f6687072dc4dd60879cd245e59/packages/runner/src/types/tasks.ts#L170-L175

**Comment by sheremet-va** [comment]
> https://github.com/vitest-dev/vitest/blob/fde628ad3dbcd4f6687072dc4dd60879cd245e59/packages/runner/src/types/tasks.ts#L170-L175

Looks like a typo. If tests were running 5 times by default, it would break _a lot of_ stuff.

**Comment by Shinigami92** [comment]
At Faker we now moved to use `.each` in general and don't rely on `repeats` at all
For us this `repeats` feature feels right now quite to buggy and unstable/experimental
Feel free to close this issue or take some other actions

**Comment by sheremet-va** [comment]
> Feel free to close this issue or take some other actions

To close this issue, we need to:

- Change default to 1 in JSDocs
- Inherit describe options
- Clarify that `repeats` will repeat only tests, not test declarations (you will have 1 test running 1000 times, not 1000 tests running once)
