### ISSUE TITLE
filter should exclude `cwd`

### ISSUE THREAD

**Issue by benmccann** [vitest-dev/vitest#3344]
### Describe the bug

I did `cd ~/src` and then did a `git clone` of a Vitest project which has the command `vitest --run src`. Because my project was held in a directory named `src`, the `src` filter matched all files rendering it useless. The filter should work the same regardless of where the user checks out the project because we don't know what the user's directory structure might be and we would otherwise have to list all directory names that they should avoid putting the project into

### Reproduction

```
mkdir src
cd src
git clone git@github.com:sveltejs/kit.git
cd kit/packages/kit
pnpm install
```
Now edit `package.json` and change `"test:unit": "vitest run",` to `"test:unit": "vitest run src",` and do `rm vitest.config.js`. When you run `test:unit` all tests should pass, but it will end up running some that live in the `test` directory because the `src` directory is ignored, so some will fail

### System Info

```shell
System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
  npmPackages:
    vite: ^4.3.0 => 4.3.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
The filter is just `filename.includes(filter)`. If you have a file named `something-src-something` outside of src directory it will run it.

I recommend just adding a slash to it.

**Comment by sheremet-va** [comment]
If you want to specify a directory to run, you can use `--dir` option.

**Comment by AriPerkkio** [comment]
Just to get this right - this issue is about the test name filter being matched against whole path including the current working directory? It should only match against relative path from current working directory.

Small demo:

```
/x/y/vitest-example-project
├── package.json
├── src
├── tests
|  ├── animals.test.ts
|  ├── example.test.ts
|  └── math.test.ts
└── vitest.config.ts
```


```sh
# Runs only test/math.test.ts
$ pnpm run test math

# Runs all tests due to cwd path "/x/y/vitest-example-project"
# Instead should run only test/example.test.ts
$ pnpm run test example
```
