### ISSUE TITLE
process `exit` event never triggered by default

### ISSUE THREAD

**Issue by danez** [vitest-dev/vitest#3357]
### Describe the bug

the exit event is not called in the tests by default. It works when using `--no-threads`.
Not sure if this is a limitation of child_processes or if this is something that vitest can change.

Might be related to https://github.com/vitest-dev/vitest/issues/3023

```ts
process.on('exit', () => {})
```

### Reproduction

https://github.com/danez-labs/vitest-process-exit

1. ni
2. nr test

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 211.13 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.asdf/installs/nodejs/18.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.6 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Safari: 16.4
  npmPackages:
    vite: 4.3.5 => 4.3.5 
    vitest: 0.31.0 => 0.31.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by danez** [comment]
Edit: it seems to be related to tinypool and/or `worker_threads` and not `child_process`

**Comment by AriPerkkio** [comment]
Tinypool starts and terminates the workers from main thread. It stops finished workers with `worker.terminate()`. Looks like this doesn't trigger `process.exit` event inside the worker thread. Here is demonstration of what's happening there:

```js
import { isMainThread, Worker } from "node:worker_threads";
import { fileURLToPath } from "node:url";

if (isMainThread) {
  console.log("[main-thread]: Running");

  const worker = new Worker(fileURLToPath(import.meta.url));
  await new Promise((r) => setTimeout(r, 1500));

  console.log("[main-thread]: Terminating");
  await worker.terminate();
} else {
  console.log("[worker-thread]: Running");

  // This is the test case subsribing to exit event
  process.on("exit", function customExitListener() {
    console.log("[worker-thread]: exit event");
  });

  // Keep thread alive to demonstrates how work is done. 
  // Once tests are run, the worker will wait for next instructions from main thread.
  // If no work is queued, main thread will terminate this.
  setInterval(() => {
    console.log("[worker-thread]: Running forever - someone should stop me");
  }, 500);
}
```

See how `[worker-thread]: exit event` is not logged.

```sh
$ node worker-exit.mjs 
[main-thread]: Running
[worker-thread]: Running
[worker-thread]: Running forever - someone should stop me
[worker-thread]: Running forever - someone should stop me
[main-thread]: Terminating
```

I guess before terminating we could instruct worker to run exit listeners? But how would that behave when workers are re-used (`--no-isolate`).

```js
if (isMainThread) {
  const worker = new Worker(fileURLToPath(import.meta.url));

  // Instruct worker to flush exit listeners
  await new Promise((r) => {
    worker.on("message", (m) => m === "exit-listeners-run" && r());
    worker.postMessage("run-exit-listeners");
  });

  // ... and now terminate it
  await worker.terminate();
} else {
  // Capture these in the beginning before users add their own listeners
  const originalListeners = process.listeners("exit");

  parentPort.on("message", (message) => {
    if (message !== "run-exit-listeners") return;

    process
      .listeners("exit")
      .filter((listener) => !originalListeners.includes(listener))
      .forEach((listener) => listener());

    parentPort.postMessage("exit-listeners-run");
  });

  // ... Tests run here and add `process.on("exit", ...)` listeners
}
```

**Comment by sheremet-va** [comment]
Looks like this is intended. If you need to trigger an `exit` event for some reason, use `child_process` pool.
