### ISSUE TITLE
[vite-node] build error: `__vite_ssr_import_0__.default.Server is not a constructor` (ws package)

### ISSUE THREAD

**Issue by ben-xD** [vitest-dev/vitest#3358]
### Describe the bug

Example code:
```typescript
import ws from "ws";
const wss = new ws.Server();
```
`vite-node src/ws.ts` will fail with an error:

```typescript
pnpm dev2                                                                                                         

> backend@1.0.0 dev2 /Users/ben/repos/app
> vite-node --options.deps.inline=ws src/ws.ts

/Users/ben/repos/app/src/ws.ts:3
const wss = new __vite_ssr_import_0__.default.Server();
            ^

TypeError: __vite_ssr_import_0__.default.Server is not a constructor
    at /Users/ben/repos/app/src/ws.ts:3:13
    at ViteNodeRunner.directRequest (file:///Users/ben/repos/app/node_modules/.pnpm/vite-node@0.31.0_@types+node@18.11.11_sass@1.49.9/node_modules/vite-node/dist/client.mjs:326:5)
    at ViteNodeRunner.cachedRequest (file:///Users/ben/repos/app/node_modules/.pnpm/vite-node@0.31.0_@types+node@18.11.11_sass@1.49.9/node_modules/vite-node/dist/client.mjs:184:14)
    at ViteNodeRunner.executeFile (file:///Users/ben/repos/app/node_modules/.pnpm/vite-node@0.31.0_@types+node@18.11.11_sass@1.49.9/node_modules/vite-node/dist/client.mjs:152:12)
    at CAC.run (file:///Users/ben/app/node_modules/.pnpm/vite-node@0.31.0_@types+node@18.11.11_sass@1.49.9/node_modules/vite-node/dist/cli.mjs:70:5)

Node.js v18.13.0
```

I've also tried a few things:
- `vite-node --options.deps.external='ws' src/ws.ts`
- `vite-node --options.deps.inline='ws' src/ws.ts`
- `interopDefault: true`. This issue reminds me of https://github.com/vitest-dev/vitest/issues/2698, but I'm not sure if how to specify that option (`deps.interopDefault`) for vite-node CLI, so I used the https://www.npmjs.com/package/vite-node#programmatic-usage + setting `new ViteNodeRunner({..., interopDefault: true,})`. That gave the same error

### Reproduction

`pnpm i ws`
```typescript
import ws from "ws";
const wss = new ws.Server();
```

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 73.95 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.2 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Firefox: 112.0.2
    Safari: 16.4
  npmPackages:
    vitest: ^0.27.2 => 0.27.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ben-xD** [comment]
## When using `console.log(ws)`, 

### vite-node outputs
```bash
[class WebSocket extends EventEmitter] {
  CONNECTING: 0,
  OPEN: 1,
  CLOSING: 2,
  CLOSED: 3
}
```

### ts-node outputs
```typescript
[class WebSocket extends EventEmitter] {
  CONNECTING: 0,
  OPEN: 1,
  CLOSING: 2,
  CLOSED: 3,
  createWebSocketStream: [Function: createWebSocketStream],
  Server: [class WebSocketServer extends EventEmitter],
  Receiver: [class Receiver extends Writable],
  Sender: [class Sender],
  WebSocket: [Circular *1],
  WebSocketServer: [class WebSocketServer extends EventEmitter]
}
```

**Comment by sheremet-va** [comment]
In the source code (https://www.npmjs.com/package/ws?activeTab=code) I don't see the `Server` on a default export.

**Comment by AriPerkkio** [comment]
I've ran into this error before and think it's caused by `ws` itself: https://github.com/websockets/ws/pull/2071

I managed to work-around this by temporarily flipping the exports in `node_modules/ws/package.json` but clearly this is not ideal. At least it narrows down the root cause:

```diff
  "exports": {
    ".": {
      "browser": "./browser.js",
-      "import": "./wrapper.mjs",
+      "import": "./index.js",
      "require": "./index.js"
    },
```

**Comment by ben-xD** [comment]
Nice! Thanks for both of your replies. Based on that ws issue, I've switched to the following code, which works:
```
import {WebSocketServer} from "ws";

console.info(WebSocketServer);
const wss = new WebSocketServer();
console.log({wss})
```
