### ISSUE TITLE
Vitest browser mode tests do not run when using workspaces

### ISSUE THREAD

**Issue by jaa134** [vitest-dev/vitest#3363]
### Describe the bug

I have a monorepo and I am taking advantage of Vitest workspaces. One workspace uses browser mode and another workspace does not. When I run tests from the project root, the normal tests run fine, but the process stalls when the browser tests run. The browser tests never execute and the process hangs indefinitely. However, if I run the tests from the individual workspaces instead of the project root, then the tests always execute and succeed. 

### Reproduction

Here is a link to a minimal reproduction StackBlitz: https://stackblitz.com/edit/vitest-browser-mode-bug?file=README.md

### System Info

```shell
- pnpm: v8.4.0
- vitest: ^0.31.0
- playwright: ^1.33.0
- pnpm workspaces
- vitest workspaces

System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.15 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Firefox: 111.0
    Safari: 14.1.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by drewlyton** [comment]
👋 Hey, I know this was closed, but I'm still seeing a similar error with `pnpm` on `v0.31.1`

```
SyntaxError: The requested module '/@fs/Users/drew/Projects/framecrafter/node_modules/.pnpm/pretty-format@27.5.1/node_modules/pretty-format/build/index.js?v=8c92f7e1' does not provide an export named '__vi_inject__'
```

**Comment by christophe-g** [comment]
@drewlyton - do  you have by any chance a `package.json` file or `node_modules` folder in your `public` folder ? This was creating similar problems for me, even under `v0.31.1`

**Comment by drewlyton** [comment]
@christophe-g thanks for commenting! No, I do not have anything other than media files in my public folder. 

Also I think #3434 is the same issue (or similar) as mine 👍
