### ISSUE TITLE
Snapshot diff and legend uses wrong colors

### ISSUE THREAD

**Issue by jschirrmacher** [vitest-dev/vitest#3364]
### Describe the bug

If a snapshot differs, output currently looks like that:

```diff
- Expected  - 1
+ Received  + 1

    <p␊
      data-v-ffea87fb=""␊
    >␊
-     May 12, 2023, ab 1 PM␊
+     May 12, 2023, ab 3 PM␊
    </p>␊
```

But unlike in this Markdown example, in vitest the legend (Expected / Received) colors are swapped:

<img width="419" alt="Bildschirmfoto 2023-05-13 um 00 18 00" src="https://github.com/vitest-dev/vitest/assets/2821879/86907d2a-e9ca-405b-94fa-43121cbdefb0">

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-1cdu7k?file=test/suite.test.ts

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 86.28 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nodenv/versions/18.12.1/bin/node
    npm: 8.19.2 - ~/.nodenv/versions/18.12.1/bin/npm
  Browsers:
    Safari: 16.4
  npmPackages:
    @vitejs/plugin-vue: ^4.2.1 => 4.2.1 
    @vitest/coverage-c8: ^0.31.0 => 0.31.0 
    vite: ^4.3.5 => 4.3.5 
    vitest: ^0.31.0 => 0.31.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Fixed by #3314
