### ISSUE TITLE
Regression in 0.30.0: changing config after `createVitest` no longer supported

### ISSUE THREAD

**Issue by nicojs** [vitest-dev/vitest#3365]
### Describe the bug

Using the node API no longer supports overriding configuration after `createVitest` occurs.

This worked in `vitest@0.29.8`, but no longer since `vitest@0.30.0`:

```js
const vitest = await createVitest("test", {});
vitest.config.setupFiles = ["vitest.setup.js",  ...vitest.config.setupFiles];
await vitest.start([]);
```

It is crucial for frameworks building upon vitest to be able to add `setupFiles` removing the existing `setupFiles`.

### Reproduction

See this git repo: [vitest-setup-files.zip](https://github.com/vitest-dev/vitest/files/11469116/vitest-setup-files.zip)

After `npm i`, you can run `node run-vitest.js` to see the error—after downgrading vitest: `npm i -D vitest@0.29.8` running `node run-vitest.js` works.

### System Info

<details>
<summary>System info</summary>

```shell
  System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 5.58 GB / 15.49 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 110.0.5481.77
  npmPackages:
    vitest: ^0.30.0 => 0.30.0 
```
</details>

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest now has support for workspaces, so you need to update config on `vitest.workspaces[0].config.setupFiles` (there can be more than one)

The config on the root vitest is used only for top level options like reporter, runner and so on.

**Comment by nicojs** [comment]
Thanks for the fast response again @sheremet-va ! 🙏

`vitest.workspaces` doesn't exist, but I can use `vitest.getCoreWorkspaceProject().config.setupFiles `. What is that exactly and would that add the setup file for each workspace in the project?

There is also `vitest.getModuleProjects()`, but it needs an ID.

**Comment by sheremet-va** [comment]
> Thanks for the fast response again @sheremet-va ! 🙏
> 
> `vitest.workspaces` doesn't exist, but I can use `vitest.getCoreWorkspaceProject().config.setupFiles `. What is that exactly and would that add the setup file for each workspace in the project?
> 
> There is also `vitest.getModuleProjects()`, but it needs an ID.

I checked the code and you need to use `vitest.projects`, not `vitest.workspaces`

**Comment by sheremet-va** [comment]
> What is that exactly and would that add the setup file for each workspace in the project?

\*for each project in a workspace. Please, refer to https://vitest.dev/guide/workspace.html for workspace configuration.

**Comment by nicojs** [comment]
Thanks for all the info! This should be enough to get our `@stryker-mutator/vitest-runner` working. 

F.y.i. we're currently using `fs.writeFile` to communicate between the test environment and the plugin. We might want to have a more formal approach (I'm pretty sure the file system is inaccessible when [browser mode](https://vitest.dev/guide/browser.html) is enabled). Let's discuss that further in #3017 in the future.
