### ISSUE TITLE
No context separation for Multiple Describe Blocks

### ISSUE THREAD

**Issue by timbrinded** [vitest-dev/vitest#3367]
### Describe the bug

Context separation works beautifully between files, however it does not work for multiple describe blocks within the same file. 

This means that it can be overly onerous designing test suites, if required to have 1 test per file (due to actions changing state).

### Reproduction

In this [stackblitz](https://stackblitz.com/edit/vitest-dev-vitest-6a8xgb?file=test/suite.test.ts) I have created a simple singleton to represent state. 

- Suite1: :heavy_check_mark: 
- Suite2: :heavy_check_mark: 
- Suite3: :x: 

I would expect that every describe block instantiates a fresh Singleton class due to strict context separation (which is the case for other test runners e.g. mocha)

### System Info

```
shell
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 28.59 GB / 46.84 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 3.2.0 - ~/.yarn/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Brave Browser: 113.1.51.114
    Chrome: 113.0.5672.92
    Firefox: 113.0.1
  npmPackages:
    @vitest/ui: latest => 0.31.0 
    vite: latest => 4.3.5 
    vitest: latest => 0.31.0 
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is by design. Vitest doesn't isolate tests based on the suite, it only isolates test files.

**Comment by timbrinded** [comment]
:cry: ok, thanks for prompt answer @sheremet-va
