### ISSUE TITLE
Make vitest actually bail after the first failure when --bail is set to 1

### ISSUE THREAD

**Issue by gajus** [vitest-dev/vitest#3372]
### Clear and concise description of the problem

At the moment, running tests `vitest run --bail 1 --single-thread` allows tests to continue running after the first (and many more) failures.

```
 Test Files  8 failed | 36 passed (44)
      Tests  33 failed | 82 passed | 2 skipped | 2 todo (119)
   Start at  15:04:35
   Duration  16.44s (transform 179ms, setup 0ms, collect 2.71s, tests 13.04s, environment 1ms, prepare 147ms)
```

### Suggested solution

If `--bail` is set to `1`, vitest should terminate all runners are soon as possible and return information about the first failure.

### Additional context

* I tried `--single-thread` to no different effect
* I tried `--no-threads` to no different effect

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
Please use the bug report issue template for issues that are clearly bugs and not improvement ideas. 

I'm unable to reproduce this bug with this information. It's really difficult to try to guess your environment, tests and settings. Here is example of working setup with `--bail 1 --single-threads`. You can use it as starting point for your reproduction case. https://stackblitz.com/edit/vitest-dev-vitest-mefosk?file=README.md
