### ISSUE TITLE
Print errors when test runner is interrupted

### ISSUE THREAD

**Issue by gajus** [vitest-dev/vitest#3373]
### Clear and concise description of the problem

Currently, if test runner is interrupted with sigint, it just exits without producing useful output.

### Suggested solution

If test runner is interrupted with sigint, then the test runner should print errors before exiting.

```
❯ |@contra/contra-api| src/foo.test.ts (15) 370ms
✓ foo
× bar
· baz
^C
```

After ^C was received, I would expect runner to provide context about `× bar` failure.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
I think this would be useful improvement. 

Maybe we should intercept the `SIGINT` signal sent from CTRL+C and **gracefully** stop the test execution and print the final report - exactly as we do in `--bail` and watch-mode test interruption. But this would mean that CTRL+C wouldn't stop tests immediately. Instead it would wait for currently running tests to finish and then stop execution. If we don't stop test execution gracefully, the final test report will include errors from forcefully terminated workers. 

For `vitest run` it would be something as simple as:

https://github.com/vitest-dev/vitest/blob/c44d99121262d4e9c8f2fe17e91a6a847c8c8e7a/packages/vitest/src/node/cli-api.ts#L80-L81

```diff
  if (process.stdin.isTTY && ctx.config.watch) {
    registerConsoleShortcuts(ctx)
  }
+  else {
+    process.on('SIGINT', async () => {
+      await ctx.cancelCurrentRun('keyboard-input')
+    })
+  }
```

And same for `vitest --watch`:

https://github.com/vitest-dev/vitest/blob/c44d99121262d4e9c8f2fe17e91a6a847c8c8e7a/packages/vitest/src/node/stdin.ts#L31-L33

```diff
    // ctrl-c or esc
    if (str === '\x03' || str === '\x1B' || (key && key.ctrl && key.name === 'c')) {
+     await ctx.cancelCurrentRun('keyboard-input')
      return ctx.exit(true)
    }
```

**Comment by gajus** [comment]
>  But this would mean that CTRL+C wouldn't stop tests immediately.

Do it so that the first SIGINT starts graceful shutdown, but a second SIGINT is received it is forced terminated.

**Comment by AriPerkkio** [comment]
That's great idea, I think it would work perfectly.

After looking at this a while it seems that there are couple of `process.on("SIGINT")` listeners added by dependencies. We may need to overwrite `stdin.on("keypress")` even when not in watch mode for this. Otherwise the listeners set by dependencies will race with the new listener.
