### ISSUE TITLE
`test.each()` infer `const` types

### ISSUE THREAD

**Issue by janosh** [vitest-dev/vitest#3374]
### Clear and concise description of the problem

This test

```ts
test.each([[`_blank`], [`_self`]])(
  `link target=%s`,
  (target) => {
    // next line raises TS error
    const link = new Link({ target: document.body, props: { target } })

    expect(link.target).toBe(target)
  }
)
```

raises a TS error

> Type 'string' is not assignable to type '"_blank" | "_self" | undefined'.ts(2322)

### Suggested solution

Is there a way to infer types passed to `test.each()` as `const`?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Add "as const"

**Comment by janosh** [comment]
You mean this?
```ts
test.each([[`_blank` as const], [`_self` as const]])(
```

Is there a single place to place `as const` in case I have 20 cases?

**Comment by janosh** [comment]
Ah never mind:

```ts
test.each([[`_blank`], [`_self`]] as const)(
```
