### ISSUE TITLE
Using createError in component causes false positives and VITEST_AFTER_ENV_TEARDOWN unhandled error

### ISSUE THREAD

**Issue by Katie-Adams** [vitest-dev/vitest#3376]
### Describe the bug

We're running a Nuxt 3 app and using Vitest with vue-test-utils to create unit tests. Up until now, no problems.
The tests I'm currently writing should catch if there's an issue with an ID we're seeking and, if so, redirect the app to our 404 page. We achieve this using the `createError` function provided by Nuxt. 

By all accounts the test I've written should - and does - pass. However, when I run the test, I get the below error message:
`TypeError: Cannot set properties of undefined (setting 'VITEST_AFTER_ENV_TEARDOWN')`

I can't fathom how to fix this error; the problem seems related to the `createError` function used in my Nuxt app, because when it is commented out, the test passes without the unhandled error.

### Reproduction

Nuxt 3 component, examples of where the createError is used
```javascript
onMounted(async () => {
  if (route.query && route.query.giftId) {
    giftId.value = route.query.giftId.toString()
  } else {
    throw createError({
      statusCode: 404,
      statusMessage: `No Gift ID query parameter at: ${route.fullPath}`,
      fatal: true
    })
  }

  await fetchGiftInformation()
})

```
```javascript
async function fetchGiftInformation() {
  try {
    const result = await axios.get<CustomerGiftingResponseInterface>(
      `${config.BASE_URI}/api/${giftId.value}`
    )
    pending.value = false
    data.value = result.data

    // ...do stuff with response here

  } catch (error: any) {
    pending.value = false

       throw createError({
         statusCode: error.value?.response?.status || 404,
         statusMessage: `An error occurred fetching gift information from path: ${route.fullPath}. MORE INFO: ${error.message}`,
         fatal: true
       })
  }
}
```

Test that cause the error
```javascript
const mocks = vi.hoisted(() => {
  return {
    createError: vi.fn()
  }
})
const TestComponent = defineComponent({
  components: { Suspense, GiftComponent },
  props: {
    blok: Object
  },
  template: '<Suspense><GiftComponent :blok="blok"/></Suspense>'
})

vi.mock('axios')

vi.mock('#imports', () => {
    return {
      default: { defaultKey: vi.fn() },
      createError:  mocks.createError,
      useRuntimeConfig() {
        return mockRuntimeConfig
      },
      useRoute: mocks.useRoute
    }
  })

axios.get.mockResolvedValue({
    data: getData
  })

it('throws error if there is no giftId query', () => {
    //test passes but throwing VITEST_AFTER_ENV_TEARDOWN error
    mocks.useRoute.mockImplementationOnce(() => {
      return {
        query: { testQuery: 'random' }
      }
    })

    const newWrapper = createFullWrapper(TestComponent, {
      props: {
        blok: {
          qrCodeCopy: 'Test data'
        }
      },
      global: {
        components: {
          FlippingCard
        }
      }
    })
  })
```

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 181.16 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Firefox: 105.0.3
    Safari: 16.4
  npmPackages:
    @vitejs/plugin-vue: ^4.1.0 => 4.1.0 
    @vitest/ui: ^0.29.3 => 0.29.8 
    vitest: ^0.31.0 => 0.31.0 
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Did you try updating Vitest first?

**Comment by sheremet-va** [comment]
You need to have at least 0.30.0 for this issue to be fixed.

**Comment by Katie-Adams** [comment]
Well don't I feel like a plonker, thank you for the response. :) Out of curiosity, could you help me find the initial issue that was raised about this? I'm going to look at the changelog now for validation. I feel like I googled _everything_ about this and couldn't find any evidence of it already being fixed in another version so I appreciate the help.

**Comment by sheremet-va** [comment]
> Out of curiosity, could you help me find the initial issue that was raised about this?

It was fixed without an open issue as part of #3103

**Comment by Katie-Adams** [comment]
Upgrading the version seems to have worked but I'm now seeing a different error message for what appears to be the same issue. As before, commenting out `createError` removes the warning. 
`Cannot set properties of undefined (setting 'type')`

I've updated my tests to reflect the new version so they now make use of `vi.hoisted()` too.

**Comment by sheremet-va** [comment]
I have no idea how to run Nuxt components, so I would need a runnable reproduction. In stackblitz or github repo.

**Comment by Katie-Adams** [comment]
I'll do my best to get one spun up now, thanks
