### ISSUE TITLE
Failed to load url history (resolved id: history)

### ISSUE THREAD

**Issue by christianHerrejon** [vitest-dev/vitest#3377]
### Describe the bug

Describe the bug
I receive an import error locally on my machine and on stackblitz. I am using the latest version of vitest `^0.31.0"`

Here is the error:
```
FAIL  src/components/common/Widgets/Allflex/Health/index.test.tsx [ src/components/common/Widgets/Allflex/Health/index.test.tsx ]
Error: Failed to load url history (resolved id: history) in C:/VAS/Morpheus-FE/src/testHelper.jsx. Does the file exist?
 ❯ loadAndTransform node_modules/vite/dist/node/chunks/dep-934dbc7c.js:53340:2
```

### Reproduction

[https://stackblitz.com](https://stackblitz.com/edit/vitest-dev-vitest-x6og2h)

Run` yarn install` and and then `yarn test`

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 16.19 GB / 31.50 GB
  Binaries:
    Node: 16.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.42)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-react: ^3.1.0 => 3.1.0
    @vitest/ui: latest => 0.31.0
    vite: ^4.2.1 => 4.3.5
    vitest: ^0.31.0 => 0.31.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
The `src/testHelper.tsx` is importing `history`:

```ts
6 | import { createMemoryHistory } from 'history';
```

However you have not installed `history` as dependency and it is not even present in `yarn.lock` through possible transitive dependencies. 
Did you forgot to install it, e.g. `yarn add --dev history`?

**Comment by christianHerrejon** [comment]
@AriPerkkio thanks for your support, have a nice day
