### ISSUE TITLE
Loading animation for `beforeAll` & `afterAll`

### ISSUE THREAD

**Issue by AlaaZorkane** [vitest-dev/vitest#338]
### Clear and concise description of the problem

Just started using Vitest and some of my tests have asynchronous preparations and cleanup functions mainly via `beforeAll ` and `afterAll` hooks that may take some time before finish, the testing reporter (or logger) freezes, I had to add console logs but it still isn't as nice as a loading indicator.

### Suggested solution

Loading indicator for `beforeAll` and `afterAll` as an example:
```
 ❯ tests/demo/instructions.test.ts (4)
   ❯ demo instructions (4)
     [L] beforeAll hook
     · tx with echo instruction
     · tx with add instruction
     · tx with transfer instruction
     ↓ tx with donate instruction [skipped]
     · afterAll hook
```

```
 ❯ tests/demo/instructions.test.ts (4)
   ❯ demo instructions (4)
     ✔ beforeAll hook
     ✔ tx with echo instruction
     ✔ tx with add instruction
     ✔ tx with transfer instruction
     ↓ tx with donate instruction [skipped]
     [L] afterAll hook
```

Replace [L] with animated loading indicator

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by MatthewZito** [comment]
@antfu Contribution welcome? This sounds like a good issue to get acquainted with the codebase.

**Comment by Pika-Pool** [comment]
Hey! If this issue is not already taken, can I work on this please? If so, where should I begin in the code?

**Comment by MatthewZito** [comment]
> Hey! If this issue is not already taken, can I work on this please? If so, where should I begin in the code?

I took a brief look at this a few days ago but haven't gotten around to working on it (please, go ahead!). 

You'll want to look at the reporters in the vitest package. `getStateString` and `getStateSymbol` largely handle the stdout formatting. From a cursory glance at the code, I can see that this ticket might be a bit tricky because no metadata about the hooks exists on the task objects that pass through the reporters (such was the case when I looked at the code a few days ago, that is).

**Comment by Pika-Pool** [comment]
I'm not able to understand how different parts of the codebase are interacting with each other. To me, it seems that its an event based architecture, creating worker pools to execute the test files. But not able to understand how the reporters module is able to access the state of these tests.

I've never worked on such a project, so forgive my ignorance. Is there a better/easier way to understand this? Are there certain tools I should know/learn?
