### ISSUE TITLE
In sveltekit, 'No test suite found' when using if block for In-source testing.

### ISSUE THREAD

**Issue by junepark202012** [vitest-dev/vitest#3381]
### Describe the bug

Hi, 
In a sveltekit app, if I use an if block to perform in-source testing, the error below occurs.
(I've set up the app to enable in-source testing as guided in the [docs](https://vitest.dev/guide/in-source.html))
```js
<script>
  import Counter from "./Counter.svelte";
  import welcome from "$lib/images/svelte-welcome.webp";
  import welcome_fallback from "$lib/images/svelte-welcome.png";

  if (import.meta.vitest) {
    describe("sum test", () => {
      it("adds 1 + 2 to equal 3", () => {
        expect(1 + 2).toBe(3);
      });
    });
  }
</script>
```
```shell
Error: No test suite found in file /Users/sejunpark/Documents/IT/vitest-bug/src/routes/+page.svelte
```

I know it's inappropriate, however, if I remove the if block, the error does not appear.
```js
<script>
  import Counter from "./Counter.svelte";
  import welcome from "$lib/images/svelte-welcome.webp";
  import welcome_fallback from "$lib/images/svelte-welcome.png";

  describe("sum test", () => {
    it("adds 1 + 2 to equal 3", () => {
      expect(1 + 2).toBe(3);
    });
  });
</script>
```

I think vitest can't detect the test suite when I use the if block in a sveltekit app.
Maybe it's something about SSR?
I'm a novice and am not sure. Any help would be great.

### Reproduction

[Repo reproduction of bug](https://github.com/junepark202012/vitest-bug.git)

### System Info

```shell
System:
    OS: macOS 12.6.3
    CPU: (8) arm64 Apple M1 Pro
    Memory: 331.77 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 3.2.4 - ~/.nvm/versions/node/v18.12.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Firefox: 113.0.1
    Safari: 16.3
  npmPackages:
    vite: ^4.3.0 => 4.3.6 
    vitest: ^0.25.3 => 0.25.8
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by gtm-nayan** [comment]
You're putting your tests in the instance script section which is called only when the component is rendered. If you want the tests to be detected, put them in the module script (<script context="module">).

**Comment by sheremet-va** [comment]
Yes, seems like your code is not running when the file is just imported (I wasn't able to trigger `console.log` with or without `import.meta.vitest`). I don't think in-source testing is good for component testing to be honest. Putting your code in `<script context="module">` works.

**Comment by junepark202012** [comment]
@gtm-nayan @sheremet-va Thank you all for answering a noob question.
Thanks a lot.
