### ISSUE TITLE
Undocumented changes to top-level `afterAll` call execution

### ISSUE THREAD

**Issue by airandfingers** [vitest-dev/vitest#3383]
### Describe the bug

Updating to `0.31.0` broke a test in which we had an (admittedly unnecessary) top-level call to `afterAll` (before any `describe` calls).

In `0.30.1`, this function was being executed after all the tests in the file. In `0.31.0`, the function is instead executed before all the tests in the file.

It's not clear to me what the correct behavior should be here, since calling `afterAll` in this way isn't standard, but if this is an intentional change, it should be called out in the changelog.

### Reproduction

Working in 0.30.1: https://stackblitz.com/edit/vitest-dev-vitest-muaygk?file=test/basic.test.ts

Broken in 0.31.0: https://stackblitz.com/edit/vitest-dev-vitest-qrvcip?file=test/basic.test.ts

### System Info

```shell
% npx envinfo --system --npmPackages '{vitest,@vitest/*,vite,@vitejs/*}' --binaries --browsers

  System:
    OS: macOS 13.2.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 56.00 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.n/bin/node
    Yarn: 3.4.1 - ~/katoa/node_modules/.bin/yarn
    npm: 8.19.2 - ~/.n/bin/npm
  Browsers:
    Brave Browser: 112.1.50.121
    Chrome: 113.0.5672.92
    Safari: 16.
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It has nothing to do with `afterAll`. Your mock is not working because `vi.mock` AND `vi.unmock` are both hoisted. Use `vi.doUnmock` if you need to call it inside a hook.

Not sure why it was working before, but it looks like it was a bug.

**Comment by airandfingers** [comment]
Oh I see, thanks for explaining!

Might want to call this out in the release notes as a Bug fix then, if only to make it clear that this behavior has changed with the update.
