### ISSUE TITLE
skip coverage when spec runner bails

### ISSUE THREAD

**Issue by capaj** [vitest-dev/vitest#3388]
### Clear and concise description of the problem

When there is a failure and --bail is set to any value the coverage gets generated and in our project always fails to meet thresholds.

### Suggested solution

do not bother with coverage when spec runner bailed

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
Similar as https://github.com/vitest-dev/vitest/issues/2908
