### ISSUE TITLE
Proxy not work in vi.mock or vi.doMock

### ISSUE THREAD

**Issue by JieamI** [vitest-dev/vitest#3394]
### Describe the bug

There is import syntax with wildcard in my source code.

`import * as mod from 'module'`

I want to mock the module, and always return the same value no matter what properties of mod is accessd. So I use proxy to achieve that, but it does not work.
For more detail, see reproduction.

### Reproduction

```
describe('xxx', () => {
  it('xxx', async () => {
    const proxy = new Proxy(
      {},
      {
        get() {
          return 'hello';
        },
      }
    )
    vi.doMock('module', () => proxy)
    const mod = await import('moudle')
    expect(proxy.whatever).toBe('hello') // pass
    expect(mod.whatever).toBe('hello') // fail
  })
})
```

### System Info

```shell
System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 338.63 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
Browsers:
    Chrome: 113.0.5672.92
    Safari: 16.3
Vitest: 0.28.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
1. You did not provide what error you get.
2. Your reproduction doesn't work with the default Vitest setup
3. You have a typo(?) in your reproduction

Is it so hard to provide an actual reproduction? Do you want to resolve the issue or do you want to just through this into the wild?

Anyway, you need to return `true` in `has` method, if the error is to be believed:

```
[vitest] No "whatever" export is defined on the "module" mock. Did you forget to return it from "vi.mock"?
```

**Comment by sheremet-va** [comment]
@JieamI update your proxy to:

```ts
    const proxy = new Proxy(
      {},
      {
        get() {
          return 'hello';
        },
      }
    )
```
