### ISSUE TITLE
Fail to run for `tsconfig` that extends from multiple other configs

### ISSUE THREAD

**Issue by tien** [vitest-dev/vitest#3395]
### Describe the bug

```sh
TypeError: The "path" argument must be of type string. Received an instance of Array
```

### Reproduction

Use 2 different tsconfig

This works fine

```json
{
  "extends": "@tsconfig/esm/tsconfig",
  "compilerOptions": {
    "moduleResolution": "nodenext",
    "declaration": true
  },
  "include": ["src"]
}
```

But this will cause the test to fail

```json
{
  "extends": ["@tsconfig/strictest/tsconfig", "@tsconfig/esm/tsconfig"],
  "compilerOptions": {
    "moduleResolution": "nodenext",
    "declaration": true
  },
  "include": ["src"]
}
```

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 86.25 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.92
    Firefox Developer Edition: 114.0
    Safari: 16.4
  npmPackages:
    vitest: ^0.31.0 => 0.31.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is fixed in the next version (will be released today)
