### ISSUE TITLE
 Cannot read properties of undefined (reading 'config')

### ISSUE THREAD

**Issue by chirastefan** [vitest-dev/vitest#3396]
### Describe the bug

Error while running `vitest --ui`

### Reproduction

 run `vitest --ui`

### System Info

```shell
"@vitest/ui": "^0.31.0",
"vitest": "^0.30.1"
"vite": "4.3.7",

OS: Ventura 13.3.1 (a)
M1 Chip
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Oreku2608** [comment]
Hey there @chirastefan! 👋

I ran into the same problem just this morning. I noticed that the root cause of the error was a version mismatch between @vitest/ui and vite. 🤔 I was getting that exception because I had different versions installed.

Here's what worked for me:

```bash
npm i vitest@latest @vitest/ui@latest -D
```

🛠️

This did the trick! I hope this can help you out as well. Keep coding! 🚀😊

**Comment by chirastefan** [comment]
it worked, though I cannot connect to the ui
![Screenshot 2023-05-18 at 11 57 36](https://github.com/vitest-dev/vitest/assets/16649178/a0910e40-64d7-4b7e-b073-fd621fae0078)
![Screenshot 2023-05-18 at 11 57 23](https://github.com/vitest-dev/vitest/assets/16649178/d1291e20-5abf-4e40-928c-6340918d255b)
![Screenshot 2023-05-18 at 12 00 13](https://github.com/vitest-dev/vitest/assets/16649178/446c27df-c832-4b5e-8112-a9e558c01367)

**Comment by chirastefan** [comment]
it worked, thanks
