### ISSUE TITLE
typecheck.tsconfig not working

### ISSUE THREAD

**Issue by kevinmamaqi** [vitest-dev/vitest#3399]
### Describe the bug

Added a specific tsconfig.test.json for testing purposes.
It doesn't pick the file.
It doesn't throw an error when the path introduced is wrong.

non-existent file: `tsconfig: 'tsconfig.test.jssdfsdon',`

### Reproduction

vitest.config.ts:

```
/// <reference types="vitest" />
// eslint-disable-next-line import/no-extraneous-dependencies
import { defineConfig } from 'vitest/config'
import { config as loadEnv } from 'dotenv'

loadEnv()

export default defineConfig({
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: './__tests__/setup.ts',
    typecheck: {
      tsconfig: 'tsconfig.test.json', // when introducing wrong path, there's no error.
    },
  },
})
```

tsconfig.test.json:
```
{
    "extends": "./tsconfig.json",
    "include": ["__tests__/**/*", "vitest.config.ts"],
    "compilerOptions": {
        "jsx": "react-jsx", // here's the error. In my tsconfig.json it is preserve as Next.js requires and overrides eat.
    },
}
```

This codesandbox: https://codesandbox.io/p/sandbox/funny-river-523gzb can be used as a reference. It requires to be cloned in order to use the terminal and have permissions.

<img width="1890" alt="Screenshot 2023-05-18 at 01 19 25" src="https://github.com/vitest-dev/vitest/assets/972664/25ec983b-d19a-47d1-bb87-b82d9b211842">

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 82.50 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
    Watchman: 2023.05.01.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 113.0.5672.92
    Firefox: 106.0.5
    Safari: 16.4
  npmPackages:
    vitest: 0.31.1 => 0.31.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
What exactly is the issue? Vitest doesn't use `tsconfig` when processing files. `typecheck` option is only used when running `vitest typecheck`. If you need to run react code, use `@vitejs/plugin-react`.

**Comment by kevinmamaqi** [comment]
It doesn't solve the problem, only changing "jsx": "preserve" to jsx-react works.

**Comment by sheremet-va** [comment]
> Tsconfig is what I thought was the problem as changing jsx within the compilerOptions made it work. Probably something else that has to do with next, but I can't figure out what

I was wrong that it is not respected. Some fields are read from there. You can configure it with [`esbuild`](https://vitejs.dev/config/shared-options.html#esbuild) option.

**Comment by kevinmamaqi-90poe** [comment]
@sheremet-va could you take a look at the code sandbox? There's surely an error with `"jsx": "preserve"`. I cannot see the relation between esbuild and this.

In the codesandbox, if you change to "jsx": "react-jsx" it works.

{
  "compilerOptions": {
    "jsx": "preserve" // Doesn't work with preserve, which is the default for next.js
  },
}

**Comment by kevinmamaqi** [comment]
@sheremet-va could you take a look at the code sandbox? There's surely an error with `"jsx": "preserve"`. I cannot see the relation between esbuild and this.

In the codesandbox, if you change to "jsx": "react-jsx" it works.

```
{
  "compilerOptions": {
    "jsx": "preserve" // Doesn't work with preserve, which is the default for next.js
  },
}
```
