### ISSUE TITLE
Unable to deep spy/stub with vitest

### ISSUE THREAD

**Issue by remibremont** [vitest-dev/vitest#3400]
### Describe the bug

Hello,

I'm not really sure it is a bug, a misconfiguration or just a missing feature but I can reproduce what seems to me an issue.

I'm currently moving from mocha/chai/sinon to vitest in a typescript project and I am unable to "deep spy" a module with multiple named exports.

By "deep spy" I mean that I'm spying on a function A which is called by another function B of the same module, both being named export, and when I call B the spy on A is not called.

### userlib.ts:
```
export const fn1 = () => {
  console.log('I would like to be spied');
};

export const fn2 = () => {
  fn1();
};
```

### userlib.spec.ts:
```
import { describe, test, expect } from 'vitest';
import * as userlib from './userlib';

describe('userlib', () => {
  test('spy doesnt work as expected, fn1 stub is not called', () => {
    // fn2() calls fn1()
    const fn1Stub = vi
      .spyOn(userlib, 'fn1')
      .mockImplementation(() =>
        console.log(
          'It should output this and I expect fn1Stub to have been called'
        )
      );
    userlib.fn2();
    expect(fn1Stub).not.toHaveBeenCalled();
  });
});
```

I agree that some module transpilation magic must be involved for this to work but it was working out of the box with mocha tn-node/register and if it's not a bug, I would like to know if/how it is possible to achieve this with vitest.

I'm using yarn in stackblitz but I'm using rush (pnpm) on my private repo.

### Reproduction

Here is a StackBlitz repro of this issue:
[Unable to deep spy with vitest](https://stackblitz.com/edit/vitejs-vite-aisyqk?file=src/userlib.spec.ts)

And the same test working as expected with mocha:
[Able to deep spy with mocha ts-node](https://stackblitz.com/edit/vitejs-vite-rjpgnx?file=src/userlib.spec.ts)

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    vite: ^4.3.2 => 4.3.7 
    vitest: ^0.31.1 => 0.31.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It's not possible to spy on calls done inside the same module since the method is referenced by its name and not on an `exports` object.

Can spy on:

```ts
// file1.js
export const getName = () => {}
// file2.js
import { getName } from './file1.js'
getName()
```

Cannot spy on:

```ts
// file1.js
export const getName = () => {}
getName()
```
