### ISSUE TITLE
Module resolution not the same in monorepo packages.

### ISSUE THREAD

**Issue by messaooudi** [vitest-dev/vitest#3401]
### Describe the bug

In a monorepo setup, I have `packageA` that has a default import from `redux-undo` and a `packageB` who imports a function from `packageA`.

When running tests in both packages, the `redux-undo` default import is correctly interpreted in `packageA` whereas in `packageB` it throws `TypeError: _redux_undo.default is not a function`

### Reproduction

https://stackblitz.com/github/messaooudi/vitest-bug

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 5.00 GB / 31.71 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.19.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.42)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitest: ^0.31.0 => 0.31.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
"correctly" is the wrong word here. The error that is happening is actually the correct behaviour when running in Node.js. Vitest tries to emulate what bundlers would do with the default export. It does it only inside source modules. For performance reasons Vitest doesn't process library code by default, so all "correct" imports are evaluated by Node.js. If you need to tell Vitest to also "fix" imports thee, add your package to `test.deps.inline`:

```
    deps: {
      inline: [/packageA/]
    }
```
