### ISSUE TITLE
Ability to Apply decorator to all tests within block

### ISSUE THREAD

**Issue by mollerhoj** [vitest-dev/vitest#3404]
### Clear and concise description of the problem

Inspired by other test runners, I wish to have the ability to wrap multiple tests in a function.

This differes from (and is more powerful than) using `beforeEach` and `afterEach` because we can use functionality that rely on closures.

Common usecases:

1. Wrapping tests in database transactions (for speed and consistency).
```
decorateEach((runTest) => {
  database.transaction(() => {
    await runTest();
  });
});
```

2. Custom benchmarking of time / memory etc:
```
decorateEach((runTest) => {
  rbenchmark.report(() => {
    await runTest();
  });
});
```

3. Freezing time by mocking Date and Date.now:
```
decorateEach((runTest) => {
  dateMocker.setTime("2023-01-01", () => {
    await runTest();
  });
});
```

I propose that the feature should be implemented such that common decorators can be applied either to all tests, or to all tests within a describe blocks.

If the team agrees the this feature is valuable, I have been allowed by my employer that I can spend work hours implementing it.

### Suggested solution

I propose to use an API such as the one shown above. Suggestions for alternative naming etc are more than welcome.

### Alternative

I know of no good alternative. One could use Typescripts Decorators, but that would require adding in a decorator for every test.

### Additional context

This has also been requested here:
https://github.com/vitest-dev/vitest/discussions/3232

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I think Vitest provides enough API to implement this in user land. For example, task function is described in the docs: https://vitest.dev/advanced/runner.html#your-task-function

A simple implementation for transition:

```ts
import { getCurrentSuite, setFn, createChainable } from 'vitest/suite'

export const withTransaction = createChainable(
  ['concurrent', 'skip', 'only', 'todo', 'fails'],
  function (name, fn) {
    const task = getCurrentSuite().custom.call(this, name)
    const wrapped = (...args) => {
      database.transaction(() => fn(...args))
    }
    setFn(task, wrapped)
  }
 )
```

You can even use `withTransaction.todo` with it.

**Comment by mollerhoj** [comment]
Interesting! So, the custom `withTransaction` tasks gets registered, but how do you set the default test runner to run custom tasks? It seems to only run tasks with type 'test'?

**Comment by sheremet-va** [comment]
> Interesting! So, the custom `withTransaction` tasks gets registered, but how do you set the default test runner to run custom tasks? It seems to only run tasks with type 'test'?

Default test runner runs custom tests by default, if they were called with `getCurrentSuite().custom` and fn is registered with `setFn`

**Comment by mollerhoj** [comment]
That does not seem to be the case. Here is a fresh repo to demonstrate: https://github.com/mollerhoj/vitest-custom-task

**Comment by sheremet-va** [comment]
> Should this be considered a bug?

You are right! It is a bug. It doesn't check for `custom` type:

https://github.com/vitest-dev/vitest/blob/41e11dad39d523af0aa7b50d22b2b9c6dd980a7b/packages/runner/src/run.ts#L330

Weird that we don't have a test for this, but we didn't have a use case for it yet, so 🤷🏻 

Currently, this feature is used by benchmarking, but it has its own runner. Theoretically, this should be handled as a normal `test`.

**Comment by jcfigueiredo** [comment]
Hi, has this been fixed? I'm trying the example above and getting the same behavior.

**Comment by jcfigueiredo** [comment]
As a follow-up, the [example in the official docs](https://vitest.dev/advanced/runner.html#your-task-function) also doesn't work with the latest version (0.34.4).

**Comment by sheremet-va** [comment]
> As a follow-up, the [example in the official docs](https://vitest.dev/advanced/runner.html#your-task-function) also doesn't work with the latest version (0.34.4).

This will be fixed in the next major with an improved API in https://github.com/vitest-dev/vitest/pull/4076

**Comment by jcfigueiredo** [comment]
Awesome! Thanks!
