### ISSUE TITLE
Setup files are cached between runs

### ISSUE THREAD

**Issue by nicojs** [vitest-dev/vitest#3409]
### Describe the bug

Hi, it's me again 😅

When using the programmatic API, setup files are cached between runs. See Reproduction.

### Reproduction

Full example: [setup-caching.zip](https://github.com/vitest-dev/vitest/files/11518268/setup-caching.zip)

```ts
// math.js
export function add(a, b) {
  if (globalThis.mutant === 1) {
    return a - b;
  } else {
    return a + b;
  }
}
```

```ts
// math.spec.js
import { describe, it, expect } from 'vitest';
import { add } from './math';

describe('math', () => {
    it('should be 42 for 40 and 2', () => {
        expect(add(40, 2)).toBe(42);
    })
});
```

```ts
// run-vitest.js
import { createVitest } from "vitest/node";
import { writeFile } from "fs/promises";

const vitest = await createVitest("test", { watch: false });
vitest.projects[0].config.setupFiles = ["vitest.setup.js"];
vitest.projects[0].config.deps.inline.push(/vitest.setup.js/);

await activateMutant();
await vitest.start();

await activateMutant(1);
await vitest.start();

async function activateMutant(mutantId) {
  await writeFile(
    "vitest.setup.js",
    `
import { beforeAll } from 'vitest';
beforeAll(() => {
    globalThis.mutant = ${mutantId};
});
`
  );
}
```

This results in 2 successful runs, while I would expect the second run to fail. I've used the `deps.inline` trick to inline the `vitest.setup.js` file, is there a way to also clear it from cache?

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 2.76 GB / 15.49 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 110.0.5481.77
  npmPackages:
    vitest: ^0.31.1 => 0.31.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Without running a reproduction (which I will do later) I can assume that Vite didn't clear the cache because you have watch mode disabled (so it doesn't reevaluate it on change). You can reevaluate it yourself with this code:

```ts
await activateMutant();
await vitest.start();

const moduleGraph = vitest.projects[0].server.moduleGraph
// invalidate all modules before running tests
moduleGraph.invalidateAll()
// or only setup file
moduleGraph.invalidateModule(moduleGraph.getModuleById('/vitest.setup.js'))

await activateMutant(1);
await vitest.start();
```

**Comment by nicojs** [comment]
Thanks again! This fixes it! ♥

I think -- nay, hope-- this is the final workaround we need 😶
