### ISSUE TITLE
vitest cannot locate modules without file extensions

### ISSUE THREAD

**Issue by qidydl** [vitest-dev/vitest#3411]
### Describe the bug

Vitest does not seem to be able to import modules without specifying a `.js` file extension, from within a separate referenced project as part of a workspace:

```
app\
   Component.test.tsx -> imports Component
   Component.tsx -> imports helper
shared\
   helper.ts -> imports util, but vitest cannot find it
   util.ts
```

### Reproduction

Repository: https://github.com/qidydl/vite-workspace-experiment
Action run showing the error: https://github.com/qidydl/vite-workspace-experiment/actions/runs/5029858368/jobs/9021862682

```
 FAIL  |app| src/App.test.tsx [ app/src/App.test.tsx ]
Error: Cannot find module '/home/runner/work/vite-workspace-experiment/vite-workspace-experiment/shared/dist/client/api' imported from /home/runner/work/vite-workspace-experiment/vite-workspace-experiment/shared/dist/client/useGetLength.js
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: {
  "code": "ERR_MODULE_NOT_FOUND",
}
```

Note how the build works fine, and VS Code has no issues either. The [previous build](https://github.com/qidydl/vite-workspace-experiment/actions/runs/5029834836) worked fine, and [the difference](https://github.com/qidydl/vite-workspace-experiment/commit/a313ac2030cc5ed93fdf35a0c4108cbea4887447) between the two is just removing the `.js` extension from the `import` statement.

### System Info

On my local system:

```shell
  System:
    OS: Linux 5.4 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 8.63 GB / 15.62 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.16.0 - /usr/bin/node
    npm: 9.5.1 - /usr/bin/npm
  Browsers:
    Chromium: 113.0.5672.126
    Firefox: 113.0.1
  npmPackages:
    vitest: ^0.31.1 => 0.31.1 
```
Note that pnpm is version 8.5.0. The GitHub action run includes the same information in logs, it's on a newer Ubuntu but the same node/npm/pnpm versions.

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Reproduction works fine for me.

<img width="807" alt="Screenshot 2023-08-23 at 15 26 31" src="https://github.com/vitest-dev/vitest/assets/16173870/15b6964b-d420-420b-b652-c6d2cedc9605">

The error described in the issue was fixed some time ago (we don't externalize dist folder anymore). If you have another problem please open a new issue with reproduction.
