### ISSUE TITLE
Unhandled promise rejection should be reported after the test finished

### ISSUE THREAD

**Issue by Jack-Works** [vitest-dev/vitest#3412]
### Describe the bug

<img width="1053" alt="image" src="https://github.com/vitest-dev/vitest/assets/5390719/1362f41b-b2cd-4b25-a39c-f53113eca961">

It should mark the test fails if the promise is still unhandled until the test ends.

### Reproduction

```
import { it } from 'vitest'
it('test', async () => {
    const promise = Promise.reject(new Error())

    await new Promise(resolve => setTimeout(resolve, 1000))
    promise.catch(() => {})
})
```

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 1.99 GB / 64.00 GB
    Shell: 7.3.4 - /usr/local/microsoft/powershell/7/pwsh
  Binaries:
    Node: 19.9.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.3 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 113.0.1
    Safari: 16.4
  npmPackages:
    vitest: ^0.30.1 => 0.30.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I don't think it's possible to track what test caused the unhandled error. What if it happened after the test had finished running? Or what is it was caused by a concurrent test and there are several tests running at the same time?

**Comment by tenkiller** [comment]
> I don't think it's possible to track what test caused the unhandled error.

Based on what, specifically? Why?

> What if it happened after the test had finished running? Or what is it was caused by a concurrent test and there are several tests running at the same time?

But, it's not. The test, as written, should await the Promise rejection on line 5. Instead, it's immediately failing on line 3. Why is that? That is unexpected behavior.

Other testing frameworks, e.g. Mocha, handle Promise rejections defined like this, as expected. Vitest doesn't, and I think we want to understand why. Was there a design decision made during Vitest development that makes this type of behavior impossible or impractical?

There are ways to write tests similar to this without using `Promise.reject()` and get the desired behavior. We're just curious why it doesn't work when you do use `Promise.reject()`? Closing the issue without much explanation isn't what @Jack-Works or other devs like myself were expecting.

**Comment by sheremet-va** [comment]
> But, it's not. The test, as written, should await the Promise rejection on line 5. Instead, it's immediately failing on line 3. Why is that? That is unexpected behavior.

I did test a similar code with Mocha a few months ago (a when dealing with a duplicate of this issue), and it wasn't working as you describe. 

Can you show me an example of how you would catch this unhandled rejection with a simple JS code?

**Comment by sheremet-va** [comment]
> But, we had an entire test suite running with Karma and Mocha/Chai using `Promise.reject()` in a lot of places, before we transitioned it over to Vitest and had to refactor them all.

I've added a link to the example of Mocha not marking the test as failed with the code that was provided here, so I am not sure how it was working before for you. Maybe the reproduction is too simplistic?

If you can give an example of how you can track unhandled promise to the function it was called in, we can easily implement it. But unfortunately, I don't know a way to do that in the browser (In Node.js we can probably intercept things with `async_hooks`).

**Comment by tenkiller** [comment]
@sheremet-va I've created an example reproduction [here](https://github.com/tenkiller/promise_rejection). I wrote tests in both the latest versions of `mocha` and `vitest` on Node 20. Both sets of tests assert the same behavior. 

While the Mocha test run executes without issue:

```shell
❯ npm run mocha

> promise_rejection@1.0.0 mocha
> mocha --bail --color test/mocha



  Component
    ✔ should render (503ms)
    ✔ should error


  2 passing (508ms)
```

The Vitest test run throws an exception:

```shell
❯ npm run vitest

> promise_rejection@1.0.0 vitest
> vitest --bail 1 --dir test/vitest run


 RUN  v1.2.2 /Users/brettfincher/dev/tenkiller/promise_rejection

 ✓ test/vitest/component.test.js (2) 506ms
   ✓ Component (2) 505ms
     ✓ should render 504ms
     ✓ should error

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: error
 ❯ test/vitest/component.test.js:13:37
     11|   it('should error', async () => {
     12|     const component = new Component()
     13|     component.work = Promise.reject(new Error('error')) // throws an error
       |                                     ^
     14|     // proper way around this is to either stub the method or enclose the reject in a function
     15|     // component.work = () => Promise.reject(new Error('error'))
 ❯ node_modules/@vitest/runner/dist/index.js:128:14
 ❯ node_modules/@vitest/runner/dist/index.js:59:26
 ❯ runTest node_modules/@vitest/runner/dist/index.js:675:17
 ❯ runSuite node_modules/@vitest/runner/dist/index.js:793:15
 ❯ runSuite node_modules/@vitest/runner/dist/index.js:793:15
 ❯ runFiles node_modules/@vitest/runner/dist/index.js:842:5
 ❯ startTests node_modules/@vitest/runner/dist/index.js:851:3
 ❯ node_modules/vitest/dist/chunks/runtime-runBaseTests.QReNMrJA.js:114:7
 ❯ withEnv node_modules/vitest/dist/chunks/runtime-runBaseTests.QReNMrJA.js:82:5

This error originated in "test/vitest/component.test.js" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 Test Files  1 passed (1)
      Tests  2 passed (2)
     Errors  1 error
   Start at  10:35:54
   Duration  801ms (transform 23ms, setup 0ms, collect 14ms, tests 506ms, environment 0ms, prepare 88ms)
```

To be clear, I'm not actually advocating for `component.work = Promise.reject(new Error('error'))` to **_not_** throw an exception. I'm thinking it probably _should_. Writing it as `component.work = () => Promise.reject(new Error('error'))` seems more correct to me. It's just curious to me why it doesn't throw an exception in Mocha.

**Comment by sheremet-va** [comment]
> It's just curious to me why it doesn't throw an exception in Mocha.

This just looks like a bug in Mocha to me. I don't know if Mocha has a concept of "suite error", but Vitest reports all errors it wasn't able to catch. Maybe adding a `setTimeout` with a long wait will trigger the error message in Mocha (it won't mark the test as failed still), Vitest waits until all async operations are resolved before terminating the worker.

But still, your example doesn't show how you would catch this error and associate it with a test that cause it. Even if we forget about the test runner and try to do it with a simple function call:

```ts
async function reject() {
  Promise.reject(new Error())
}
async function pass() {
  // empty
}
await reject()
await new Promise(resolve => setTimeout(resolve, 1000))
// and here:
await Promise.all(test(),pass())
```

**Comment by tenkiller** [comment]
I think we can agree that assigning `Promise.reject()` directly is an example of what _not_ to do. It's frustrating though that Mocha doesn't seem to think it's a problem. Thanks for looking into the issue further @sheremet-va.
