### ISSUE TITLE
Coverage Report breaks when using ignore option

### ISSUE THREAD

**Issue by ChrisPlease** [vitest-dev/vitest#3414]
### Describe the bug

When providing an ignore pattern for included files, coverage breaks because coverage report is ran on the `coverage` directory resulting in an error and empty coverage report.
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: ENOENT: no such file or directory, open '/coverage/base.css'
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: {
  "code": "ENOENT",
  "errno": -2,
  "path": "/coverage/base.css",
  "syscall": "open",
}
```

Setting up reproduction on StackBlitz made me realize this is caused by the ignore flag in the `test.include`. Commenting out the ignore path `'!src/test/**',` coverage report generates as expected.

Thread on discord: https://discord.com/channels/917386801235247114/1109310035655397387/1109310035655397387

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-po5z4y?file=vite.config.unit.ts

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Memory: 152.46 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v16.18.0/bin/npm
    Watchman: 2023.01.16.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 113.0.1
    Firefox Developer Edition: 114.0
    Firefox Nightly: 114.0a1
    Safari: 16.4
  npmPackages:
    @vitest/coverage-istanbul: ^0.31.1 => 0.31.1
    @vitest/ui: ^0.31.1 => 0.31.1
    vitest: ^0.31.1 => 0.31.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ChrisPlease** [comment]
Moving `test.include: `!src/tests/**/*` to `test.exclude: src/tests/**/*` will fix the issue

**Comment by AriPerkkio** [comment]
This looks like a configuration error and not a bug in Vitest.

When you set `test.include` to `!src/tests` and run watch mode, it will include the generated `./coverage` directory as it matches the pattern. Vitest tries to open the files from `coverage` and use them as test files.

Instead you should define it as `test.exclude`.

**Comment by ChrisPlease** [comment]
@AriPerkkio that kind of makes sense, but that means the first `include` is being superseded rather than narrowing the results?

The bang `!src/tests` supersedes the first include `src/**/*.test.ts`?

**Comment by AriPerkkio** [comment]
The `test.include` describes patterns that are considered as test files. Files are tested against each pattern ony-by-one. The `test.exclude` is then used to exclude files that matched the `include` pattern but should be excluded.

The pattern `include: ['src/**/*.test.ts', '!src/test/**']` would mean that every single file that matches either of the patterns is considered as test file (and that does not match the default value of [`test.exclude`](https://vitest.dev/config/#exclude)).

If you wish to write a single `test.include` pattern that includes `*.test.ts` files from all sub-directories of `src`, but excludes `src/test`, something like this could work: [`src/{!(test),}/*.ts`](https://www.digitalocean.com/community/tools/glob?comments=true&glob=src%2F%7B%21%28test%29%2C%7D%2F%2A.ts&matches=false&tests=src%2Fuser.test.ts&tests=src%2Fcomponents%2Flist.test.ts&tests=src%2Ftest.ts&tests=src%2Ftest%2Fintegration.test.ts&tests=src%2Ftest%2Fend-to-end.test.ts). But I would  still recommend using `test.include: ['src/**/*.test.ts']` with `test.exclude: ['src/test/**']` for readability.
