### ISSUE TITLE
Errors are swallowed in WebStorm when thrown from beforeAll block

### ISSUE THREAD

**Issue by kibertoad** [vitest-dev/vitest#3416]
### Describe the bug

If `beforeAll` block throws for any reason, no useful error messages are provided, instead, `Failure cause not provided for 'simple repro'` is printed.

This works fine with `beforeEach` blocks and `it` blocks.

Might be related to https://github.com/vitest-dev/vitest/issues/3366

When tests are executed from terminal, they work fine.

### Reproduction

```js
describe('TestSuite', () => {
  beforeAll(() => {
    throw new Error('something crashed')
  });
  it('simple repro', () => {
  });
});
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 7700X 8-Core Processor
    Memory: 7.98 GB / 31.15 GB
  Binaries:
    Node: 20.0.0 - C:\software\nodejs\node.EXE
    npm: 9.6.4 - C:\software\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.50)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitest/coverage-c8: ^0.31.1 => 0.31.1
    vitest: ^0.31.1 => 0.31.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest is not affiliated with WebStorm. Please, open an issue in their YouTrack. The error exists on `suite.result.errors` property.

**Comment by kibertoad** [comment]
Thanks!

**Comment by kibertoad** [comment]
If anyone finds this issue while researching same problem, here is the Youtrack issue to track: https://youtrack.jetbrains.com/issue/WEB-61191
