### ISSUE TITLE
mock implemented with doMock doesn't work

### ISSUE THREAD

**Issue by shadow-identity** [vitest-dev/vitest#3420]
### Describe the bug

Hi, and thanks for amazing work!

I'm trying to do implement a `doMock` example from the [docs](https://vitest.dev/api/vi.html#vi-domock), but it doesn't work. 
I simply copied code from docs into stackblitz (and added few missing imports), the rest is the same.
These assertions fails returning "2" instead of "101": 
  ```
expect(mockedIncrement(1)).toBe(101);
```
`mockImplementation` doesn't work either.

I have the same issue in my local code. 

### Reproduction

I reproduced in stackblitz, so it could be easily checked: 

https://stackblitz.com/edit/node-jrqqhh?file=mock.test.ts

### System Info

```shell
Have no idea what do they use on stackblitz :( 
My system has 
    OS: macOS 13.3.1
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by shadow-identity** [comment]
The first issue header was incorrect, sorry.

**Comment by sheremet-va** [comment]
Your reproduction works for me:

![image](https://github.com/vitest-dev/vitest/assets/16173870/41561a17-35b9-45ed-841d-79610c5b469a)

**Comment by shadow-identity** [comment]
That's interesting! I tried it in Chrome (I use Firefox by default) and it really works in Chrome. But not on my FF. And I made it work locally after cleaning node-modules. So it was probably some npm caching issue. I think we can close the issue.
