### ISSUE TITLE
docs: describe vi.setSystemTime string parameter

### ISSUE THREAD

**Issue by aentwist** [vitest-dev/vitest#3432]
### Clear and concise description of the problem

<blockquote>
<h2>vi.setSystemTime</h2>

Type: <code>(date: string | number | Date) => void</code>

Sets current date to the one that was passed.
</blockquote>

https://vitest.dev/api/vi.html#vi-setsystemtime

I see the docs use JS Dates, but I don't want to do that. The API documentation is lacking here. Can we describe the string option please?

As for the number, people with common sense can assume it's a Unix timestamp.
What is the string? ISO 8601? RFC 3339? Date.toString? Most people will probably be thinking ISO 8601, although I am not sure if that is the case. Please confirm.

This is a question or a docs issue. Your call, I'll pull for it.

### Suggested solution

Something like,

> Strings must be ISO 8601 compliant.

> Strings must follow the ISO 8601 <specification|format>

> Strings must be parsable <according to|as specified by> ISO 8601.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
It just passes down values to `new Date`.

**Comment by aentwist** [comment]
Yeah I would *not* have guessed that. Thanks for the answer. So then via [MDN JS Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#date_time_string_format) we have,

<blockquote>
There are many ways to format a date as a string. The JavaScript specification only specifies one format to be universally supported: the <a href="https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-date-time-string-format">date time string format</a>, a simplification of the ISO 8601 calendar date extended format. The format is as follows:
<br><br>
<pre>
YYYY-MM-DDTHH:mm:ss.sssZ
</pre>
</blockquote>

As it turns out this ISO 8601 subset is robust enough and is what I was looking for.

Why was I hoping to circumvent JS Dates. Besides the weak ISO 8601 subset. Well, you can't even escape it in that section of documentation -

> When the time zone offset is absent, date-only forms are interpreted as a UTC time and date-time forms are interpreted as local time. This is due to a historical spec error that was not consistent with ISO 8601 but could not be changed due to web compatibility.

---

So this issue becomes something like,

Change

> Sets current date to the one that was passed.

to

> Sets current date to the `Date` argument or `Date` constructed with the argument.
