### ISSUE TITLE
[Feature]: Expect.soft and soft assertions

### ISSUE THREAD

**Issue by unickq** [vitest-dev/vitest#3435]
### Soft assertions. 
The idea of soft assertions - do not terminate test execution, but mark the test as failed.

Description can be taken from https://github.com/jestjs/jest/issues/13205 and https://github.com/microsoft/playwright/pull/11800.
Playwright currently supports it, which makes its test runner amazing. I think it would be great to have this in vitest

```js
// Make a few checks that will not stop the test when failed...
await expect.soft(page.getByTestId('status')).toHaveText('Success');
await expect.soft(page.getByTestId('eta')).toHaveText('1 day');

// ... and continue the test to check more things.
await page.getByRole('link', { name: 'next page' }).click();
await expect.soft(page.getByRole('heading', { name: 'Make another order' })).toBeVisible();
```

### Suggested solution

https://playwright.dev/docs/test-assertions#soft-assertions
https://github.com/microsoft/playwright/pull/11800

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
There was an idea to implement it as an optional field on a test in #2139, but I agree that `expect.soft` is a better API.
