### ISSUE TITLE
ReferenceError: __vitest__clearMocks__ is not defined

### ISSUE THREAD

**Issue by vidarc** [vitest-dev/vitest#344]
### Describe the bug

Started receiving this not too long ago, it definitely worked fine at one point.

```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

ReferenceError: __vitest__clearMocks__ is not defined
    at VitestUtils.restoreAllMocks (file:///Users/mattailes/Projects/vitest-clearmock/node_modules/.store/vitest-virtual-157fdc30ac/dist/vi-85b65e90.js:1034:5)
    at run (file:///Users/mattailes/Projects/vitest-clearmock/node_modules/.store/vitest-virtual-157fdc30ac/dist/entry.js:3850:8)
    at async file:///Users/mattailes/Projects/vitest-clearmock/node_modules/.store/tinypool-npm-0.0.6-e92d9727a5/dist/esm/worker.js:1:1309
```

### Reproduction

https://github.com/vidarc/vitest-clearmock

`git clone` => `yarn` => `yarn vitest run` should reproduce the issue (at least it does on my machine)

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 525.89 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /usr/local/bin/node
    Yarn: 3.1.1 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Safari: 15.2
  npmPackages:
    vite: ^2.7.7 => 2.7.7 
    vitest: ^0.0.118 => 0.0.118
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You say it worked before, have you changed your setup recently? If I remove this call (`__vitest__clearMocks__`), it adds another error. `yarn` doesn't even run `directRequest` for some reason.

Out of curiosity I run your tests with `pnpm` and it doesn't have these issues.

**Comment by vidarc** [comment]
The issue seems to be either `vitest` or a nested dependency of `vitest`. This is the commit where it all went wrong: https://github.com/vidarc/vitest-clearmock/commit/5b074ac5b62c6213140969d3e107a2f6e837da50

If I checkout the previous commit: https://github.com/vidarc/vitest-clearmock/commit/691862419b1b101c9fa0f317910f99c751a76a5f and run `yarn` => `yarn vitest run` it works, though I do get a message regarding vitest hanging. If I then upgrade to latest `vitest` using `yarn upgrade-interactive`, I then get the undefined issue again

**Comment by sheremet-va** [comment]
Should be fixed in the next release. Yarn stores `vitest` package in `vitest-virtual` folder, so transforming didn't work, since by default we search `vitest/dist` folder.
