### ISSUE TITLE
webp imports do not work in Vitest (but work fine in Vite with the same config)

### ISSUE THREAD

**Issue by kaiyoma** [vitest-dev/vitest#3444]
### Describe the bug

I am migrating to both Vite and Vitest (at the same time) and my UI has components that import `.webp` files. The UI and Vitest are sharing the same config and the UI is working fine, but any tests that indirectly imports a `.webp` is failing:

```
TypeError: Unknown file extension ".webp" for C:\Users\kgetz\Work\event-viewer\lib\geiger-vendor\dist\images\arista\5310-F.webp
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: {
  "code": "ERR_UNKNOWN_FILE_EXTENSION",
}
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
```

### Reproduction

Import a `.webp` file in a component, then include that component in a Vite UI and a Vitest unit test.

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 5.58 GB / 15.71 GB
  Binaries:
    Node: 16.19.1 - C:\Program Files\Node.js\node.EXE
    npm: 9.6.2 - C:\Program Files\Node.js\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.50)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-react: 4.0.0 => 4.0.0
    vite: 4.3.8 => 4.3.8
    vitest: 0.31.0 => 0.31.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kaiyoma** [comment]
@sheremet-va I noticed you started working on a possible fix. Is there any kind of workaround I can employ locally for now? This problem is affecting almost a hundred of my unit test suites and I'd like to make some progress.

**Comment by sheremet-va** [comment]
> @sheremet-va I noticed you started working on a possible fix. Is there any kind of workaround I can employ locally for now? This problem is affecting almost a hundred of my unit test suites and I'd like to make some progress.

You can add your dist directory to `test.deps.inline`:

```
export default defineConfig({
  test: {
    deps: {
      inline: [/package-name\/dist/]
    }
  }
})
```
