### ISSUE TITLE
CLI --coverage.exclude filter throws TypeError

### ISSUE THREAD

**Issue by iliketomatoes** [vitest-dev/vitest#3450]
### Describe the bug

I'm using Vitest in a monorepository (with `vitest.workspace.ts`), and it looks like the only way to provide coverage options is through CLI.

The command I use includes this filter: `--coverage.exclude='**/node_modules/**'`, which causes Vitest to throw this error: 
```sh
TypeError: resolved.coverage.exclude.push is not a function
```

### Reproduction

In a monorepository that leverages [Vitest Workspaces](https://vitest.dev/guide/workspace.html), run this command:

```sh
npx vitest run --coverage.enabled --coverage.lines=50 --coverage.functions=50 --coverage.branches=50 --coverage.statements=50 --coverage.all --coverage.include='packages/**' --coverage.include='apps/**' --coverage.exclude='**/node_modules/**'
```

### System Info

```shell
System:
    OS: macOS 12.6.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.26 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 3.2.3 - ~/.nvm/versions/node/v14.20.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Brave Browser: 109.1.47.171
    Chrome: 113.0.5672.126
    Firefox: 113.0.2
    Safari: 16.3
  npmPackages:
    @vitest/coverage-c8: ^0.31.1 => 0.31.1 
    @vitest/ui: ^0.31.1 => 0.31.1 
    vitest: ^0.31.1 => 0.31.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You can provide coverage options inside a `vitest.config.ts`

**Comment by iliketomatoes** [comment]
> You can provide coverage options inside a `vitest.config.ts`

I thought I was supposed to use `defineProject` (which doesn't support the `coverage` property) even at the root level. Thanks!

**Comment by sheremet-va** [comment]
We should probably guard all possible properties with `toArray` method.
