### ISSUE TITLE
ERROR: Expected identifier but found "const"

### ISSUE THREAD

**Issue by kadiryazici** [vitest-dev/vitest#3458]
### Describe the bug

In our project we are using TypeScrip 5.0 with latest vitest, vue-tsc and vite version. With new `<const T>` generics in TypeScript 5.0 we created some utility functions but vitest throws error for `const generics`.

```bash
 FAIL  src/utils/createChartLimits/createChartLimits.test.js [ src/utils/createChartLimits/createChartLimits.test.js ]
 FAIL  src/utils/getProrationCostPrice/getProrationCostPrice.test.js [ src/utils/getProrationCostPrice/getProrationCostPrice.test.js ]
 FAIL  src/utils/makeEnum/makeEnum.test.js [ src/utils/makeEnum/makeEnum.test.js ]
 FAIL  src/utils/oneOfEnum/oneOfEnum.test.js [ src/utils/oneOfEnum/oneOfEnum.test.js ]
 FAIL  src/components/SdMenu/SdMenuSelectable/SdMenuSelectable.test.js [ src/components/SdMenu/SdMenuSelectable/SdMenuSelectable.test.js ]
Error: Transform failed with 1 error:
/Users/kadiryazici/Desktop/Wope/product-frontend-next/src/utils/makeEnum/index.ts:22:2: ERROR: Expected identifier but found "const"
 ❯ failureErrorWithLog node_modules/vitest/node_modules/esbuild/lib/main.js:1604:15
 ❯ node_modules/vitest/node_modules/esbuild/lib/main.js:837:29
 ❯ responseCallbacks.<computed> node_modules/vitest/node_modules/esbuild/lib/main.js:701:9
 ❯ handleIncomingPacket node_modules/vitest/node_modules/esbuild/lib/main.js:756:9
 ❯ Socket.readFromStdout node_modules/vitest/node_modules/esbuild/lib/main.js:677:7
 ❯ Socket.emit node:events:513:28
```

### Reproduction

Utility function:
```ts
import { type PascalCase, type KebabCase } from 'type-fest';

type ArrayToEnumObject<T extends readonly string[]> = {
  [K in T[number] as K]: KebabCase<K>;
};

export default function makeEnum<
  const T extends readonly string[],
>(keys: T) {
  const enums = {} as ArrayToEnumObject<T>;
  keys.forEach((key: keyof typeof enums) => {
    enums[key] = toKebabCase(key);
  });
  return Object.freeze(enums);
}

```

Test Code:

```ts
import { describe, it, expect } from 'vitest';
import toPascalCase from '@utils/toPascalCase';
import makeEnum, { getKeysAsPascalCase } from '@utils/makeEnum';

describe('Enum tests', () => {
  it('is value of enum member kebab-case', () => {
    const tempEnum = makeEnum(['ButtonIndigo', 'ButtonDisabled']);
    expect(tempEnum.ButtonDisabled).toBe('button-disabled');
    expect(tempEnum.ButtonIndigo).toBe('button-indigo');
  });
});
```

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 160.77 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 109.0.1
    Safari: 16.4
  npmPackages:
    @vitejs/plugin-vue: ^4.1.0 => 4.1.0 
    vite: ^4.3.9 => 4.3.9 
    vitest: ^0.31.1 => 0.31.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
What Vite version do you have installed? Vitest doesn’t specify a version, only a range. Make sure you have the latest Vite installed by your package manager.

**Comment by kadiryazici** [comment]
@sheremet-va you can see in System-info we are using the latest version of vite and vitest.

**Comment by so1ve** [comment]
You are importing a typescript in a javascript file

**Comment by kadiryazici** [comment]
@so1ve TypeScript files are converted to JS so it doesn't matter, in our workspace we are slowly migrating to ts from js and Vite does not give any error about it.

**Comment by moomoolive** [comment]
Just wanted to let you folks know that I'm having the exact same problem as @kadiryazici , vitest fails when parsing typescript code using `const` generics.

This is the piece of code vitest is choking on:

![image](https://github.com/vitest-dev/vitest/assets/63522515/37202a3d-b1ab-4f71-b8e0-3ae383a1fff8)

Error trace: 
![image](https://github.com/vitest-dev/vitest/assets/63522515/b82ba5f5-709f-4279-b4c0-c9ee4d2ae3c8)

PS I'm on the latest version (v0.32.0)

**Comment by gregor-mueller** [comment]
It works for me with 
```json
{
    "vite": "^4.4.9",
    "vitest": "^0.34.4"
}
```
