### ISSUE TITLE
vi.advanceTimersToNextTimer() hangs when timeout is less than 1

### ISSUE THREAD

**Issue by royk** [vitest-dev/vitest#3463]
### Describe the bug

When testing an interval using fakeTimers and vi.advanceTimersToNextTimer(), where the value of the delay is less than 1, the test execution hangs. 

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-4f2kwp?file=test%2Fbasic.test.ts

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
    Memory: 5.04 GB / 15.92 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 113.0.5672.127
    Edge: Spartan (44.22621.1702.0), Chromium (113.0.1774.57)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-vue: ^3.1.2 => 3.2.0
    @vitest/coverage-istanbul: ^0.31.0 => 0.31.1
    vite: ^3.2.4 => 3.2.6
    vitest: ^0.31.1 => 0.31.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Does it work with https://github.com/sinonjs/fake-timers?
