### ISSUE TITLE
Luxon DateTimes are not instanceof DateTime in vitest

### ISSUE THREAD

**Issue by Mojova** [vitest-dev/vitest#3477]
### Describe the bug

Luxon DateTime instances are not `instanceof DateTime` when using vitest. Same test run with Jest succeeds, and it works in a real React application in a browser.

```
import LuxonUtils from "@date-io/luxon";
import {DateTime} from "luxon";

describe('LuxonUtils', () => {
    it('DateTime', () => {
        const utils = new LuxonUtils()
        const datetime = DateTime.now()
        expect(utils.date(datetime).isValid).toBeTruthy()
    });
})
```

I have located the problem to a small diffence between what TypeScript source of the `date` function in LuxonUtils is
vs what their compiled source is.  If I copy their source to my own project and let vite process that the test succeeds.

[Their TypeScript:](https://github.com/dmtrKovalenko/date-io/blob/master/packages/luxon/src/luxon-utils.ts#L60)
```
if (value instanceof DateTime) {
    return value
}
```
Their JavaScript (node_modules/@date-io/luxon/build/index.js:49):
```
if (value instanceof luxon.DateTime) {
    return value
 }
```

When run through vitest, `value` is not an instance of `luxon.DateTime` and the code takes a wrong branch resulting in an
invalid DateTime.

Is this problem a result of my vite/Typescript config, your bug, or a @date-io bug?

@date-io/luxon is an adapter library that standardizes multiple date libraries to the same API. It’s used by e.g. MUI.
The bug doesn’t occur when using DateUtils in a React application in the browser.

### Reproduction

Clone https://github.com/Mojova/vite-luxon-bug and follow README.md.

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 64.95 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 9.6.6 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 113.0.2
    Safari: 16.4
  npmPackages:
    vite: ^4.3.9 => 4.3.9
    vitest: ^0.31.1 => 0.31.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kthompson** [comment]
I have a very similar issue except its with the `GraphQLSchema` type from `graphql` that is referenced from `SchemaComposer` in `graphql-compose` here https://github.com/graphql-compose/graphql-compose/blob/0ab3caf08fae78ac4c346b3a30c08737f4545911/src/SchemaComposer.ts#L131

The instanceof check fails even though this works via normal execution and in Jest

**Comment by kthompson** [comment]
@Mojova Did you find any workaround for this issue?

**Comment by Mojova** [comment]
@kthompson No. I’m still using Jest to run my project’s tests because of this bug.

**Comment by sheremet-va** [comment]
This is not Vitest bug. `luxon` package supports Node.js ESM, so it is imported from ESM entry. `@date-io/luxon` doesn't support Node.js ESM, os it imports `luxon` from CJS entry.

To fix that, you can add both of them to `deps.expertimentalOptimizer.include`.

**Comment by Mojova** [comment]
Thank you for the explanation! Only the resolve method is fixing the issue for me.

Is this a correct config for using experimentalOptimizer?

```javascript
export default defineConfig({
  test: {
    environment: 'jsdom',
    globals: true,
    deps: {
      experimentalOptimizer: {
        web: {
          enabled: true,
          include: ["luxon", "@date-io/luxon"]
        }
      }
    }
  }
})
```

**Comment by Mojova** [comment]
Updating to `@date-io/luxon` 2.17.0 has fixed this issue, so I’m closing it.
