### ISSUE TITLE
RangeError: Maximum call stack size exceeded when a .env file has environment  variable with default values

### ISSUE THREAD

**Issue by hgouveia** [vitest-dev/vitest#3478]
### Describe the bug

if you have a .env file in your project and this has  environment  variable with default values, you will get this error

```shell
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
RangeError: Maximum call stack size exceeded
    at RegExp.exec (<anonymous>)
    at file://test-app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:36830:54
    at Array.reduce (<anonymous>)
    at _interpolate (file://test-app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:36829:18)
    at file://test-app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:36863:15
    at Array.reduce (<anonymous>)
    at _interpolate (file://test-app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:36829:18)
    at file://test-app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:36863:15
    at Array.reduce (<anonymous>)
    at _interpolate (file://test-app/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:36829:18)
 ```
 
 
 this only happened to me in Linux and my ci with docker, this does not happen on windows (my main machine)

### Reproduction

- create a empty project `npm init -y`
- install vitest
- create a `.env` file with this content

```.env
MY_SECRET=${MY_SECRET:-}
```
- run `npx vitest run`

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 29.10 GB / 31.31 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /mnt/d/programas/nodejs/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  npmPackages:
    vitest: ^0.31.2 => 0.31.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This looks like an issue with Vite. I recommend opening an issue in their repo.

**Comment by hgouveia** [comment]
> This looks like an issue with Vite. I recommend opening an issue in their repo.

in my particular case, i am not using Vite or installed it, i just installed `vitest`, is this still applies?

**Comment by sheremet-va** [comment]
> > This looks like an issue with Vite. I recommend opening an issue in their repo.
> 
> in my particular case, i am not using Vite or installed it, i just installed `vitest`, is this still applies?

Yes, Vitest uses Vite internally. It's basically a wrapper around Vite.

**Comment by hgouveia** [comment]
> > > This looks like an issue with Vite. I recommend opening an issue in their repo.
> > 
> > 
> > in my particular case, i am not using Vite or installed it, i just installed `vitest`, is this still applies?
> 
> Yes, Vitest uses Vite internally. It's basically a wrapper around Vite.

thanks, created ticket on : https://github.com/vitejs/vite/issues/13399
