### ISSUE TITLE
Can't serve @vitest/ui report on a subpath

### ISSUE THREAD

**Issue by segevfiner** [vitest-dev/vitest#3481]
### Describe the bug

Upload a vitest/ui generated report  to a subpath in an HTTP server (And make sure the `.gz` file is served with an `Content-Type: application/gzip`, or `Content-Encoding: gzip` which might also work). You will get a blank page. The report only works at the root path of a site, disallowing uploading it somewhere for others to view. (e.g. From CI).

That is, it works when the URL is:
http://somewhere.com/

But fails if it is:
http://somewhere.com/vitest-report/

Such reports are very useful to upload to a shared server for others to easily view from CI, but they need to handle being served from any subpath for this to work properly.

### Reproduction

Generate any @vitest/ui report, and use `caddy run` (Install caddy) with the following `Caddyfile` and the report in a subdirectory.

```caddyfile
http://localhost:8080

@gz {
	path *.gz
}

header @gz Content-Type application/gzip

file_server browse
```

e.g.
* Caddyfile
* report/
    * index.html

And try to access http://localhost:8080/report/, you will get a blank page, no errors in the console.

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 57.72 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v16.20.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Safari: 16.5
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.1.0 
    @vitest/ui: ^0.31.2 => 0.31.2 
    vite: ^4.1.4 => 4.2.1 
    vitest: ^0.31.2 => 0.31.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Hm, interesting 🤔 As far as I know, it should work. All paths are relative 🤔

**Comment by segevfiner** [comment]
Yeah. I can upload a zip with a more complete repro. Maybe it's vue-router that get's confused?

**Comment by minwe** [comment]
+1
