### ISSUE TITLE
Allow to use function and class names for describe and it names

### ISSUE THREAD

**Issue by alfaproject** [vitest-dev/vitest#3493]
### Clear and concise description of the problem

I'm trying to migrate our codebase from Jest to Vitest but now I have to update almost all of our test suites because we use function or class names for the describe names like so:

```ts
describe(VitestService, () => {
  describe(VitestService.prototype.isBroken, () => {
    // ...
  });
});
```

But we get type errors with Vitest ):

### Suggested solution

Allow for function and class names to be used in describe/it/test/etc names

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by JoshuaKGoldberg** [comment]
Looks like this was fixed by #3497 (hooray! 🥳) - can the issue be closed?
