### ISSUE TITLE
Vitest istanbul or c8 coverage cannot resolve vuetify components

### ISSUE THREAD

**Issue by mtrana** [vitest-dev/vitest#3495]
### Describe the bug

When I use a vuetify component and run the coverage I get Warnings. It looks like it cannot resolve vuetify components. Do you know how could I fix this?

### Reproduction

vite.config.js
`export default defineConfig({
  test: {
    deps: {
      inline: ['vuetify'],
    },
    globals: true,
    environment: 'jsdom',
    mockReset: true,
    coverage: {
      provider: 'istanbul',
      reporter: ['text', 'html'],
      reportsDirectory: './tests/unit/coverage'
    },
  },
  plugins: [vue()],
})`

package.json

`{
     ...
    "coverage": "vitest run --coverage",
    "test:unit": "vitest --run --environment jsdom --root"
  },
  "dependencies": {
    "@vitejs/plugin-vue": "^4.2.3",
    "@vue/test-utils": "^2.3.2",
    "jsdom": "^22.1.0",
    "vue": "^3.2.47",
    "vuetify": "^3.3.2"
  },
  "devDependencies": {
    "@vitest/coverage-c8": "^0.31.4",
    "@vitest/coverage-istanbul": "^0.31.4",
    "vite": "^4.3.9",
    "vitest": "^0.31.4"
  }
}`

main.js
`const app = createApp(App);
const vuetify = createVuetify({
  components: components,
  directives: directives,
});

app.use(vuetify);

app.mount('#app')`

Warnings

![image](https://github.com/vitest-dev/vitest/assets/131269449/3b559cb3-788f-4d94-b851-7153559365b5)

### System Info

```shell
System:                                                       
    OS: Windows 10                                  
    Memory: 48.81 GB / 63.73 GB                                 
  Binaries:                                                     
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE            
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD                                         
  npmPackages:                                                  
    @vitejs/plugin-vue: ^4.2.3 => 4.2.3                         
    @vitest/coverage-c8: ^0.31.4 => 0.31.4                      
    @vitest/coverage-istanbul: ^0.31.4 => 0.31.4                
    vite: ^4.3.9 => 4.3.9                                       
    vitest: ^0.31.4 => 0.31.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I don't see how this is related to coverage? Did you define your vuetify plugins in your tests?

**Comment by mtrana** [comment]
Yes I have tried to define vuetify plugin in my tests too. The tests run without warnings I get this warnings only in coverage.
