### ISSUE TITLE
Running test constructed with `data provider` pattern prints out `describe` name for each `it`

### ISSUE THREAD

**Issue by WhereJuly** [vitest-dev/vitest#3501]
### Describe the bug

- **Task**: Running test constructed with `data provider` pattern prints out the test log with `verbose` reporter.

- **Expected**: Running the task prints out `describe` name once and `it` name once per each `it`. Other runners (e.g. jest, ava, phpunit) behave as expected.

- **Actual**: Running the task prints out `describe` and `it` names once per each `it`.

See stackblitz link for reproduction.

``` javascript
'use strict';

import { describe, expect, it } from 'vitest';

describe('DataProviderTest', () => {

    describe.each(dataProvider_inputs_to_outputs())('#check(): Input should equal expected output.', (data) => {
        it(`Case: ${data.name}.`, () => {
            expect(data.input).toEqual(data.expected);
        });
    });

});

function dataProvider_inputs_to_outputs() {
    return [
        { name: 'input: true', input: true, expected: true },
        { name: 'input: false', input: false, expected: false },
        { name: 'input: text', input: 'text', expected: 'text' },
    ];
}
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-bckuyz?file=vite.config.ts

### System Info

```shell
Stackblitz, vitest@latest
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`describe.each` creates 3 suites with 1 test inside of each suite in your case, so everything works as expected.

If you want to have a single suite, put `.each` on `test`:

```ts
    describe('#check(): Input should equal expected output.', () => {
        it.each(dataProvider_inputs_to_outputs())("Case: $name.", (data) => {
            expect(data.input).toEqual(data.expected);
        });
    });
```

**Comment by WhereJuly** [comment]
@sheremet-va 

Thanks for the explanation.

Unfortunately your example does not print out the case name. It prints out `Case: undefined` for all 3 tests. However according to documentation it should have printed `Case: input: true` for the first one, and respectively for the following tests.

Here is stackblitz updated with your example:
https://stackblitz.com/edit/vitest-dev-vitest-bckuyz?file=test%2Fsuite.test.ts
