### ISSUE TITLE
Mocking of typescript interfaces / types

### ISSUE THREAD

**Issue by eratio08** [vitest-dev/vitest#351]
### Clear and concise description of the problem

As a developer using Vitest I want to be able to create mocks of any typescript interface, types or object with full type support so that I do not need to write full stubs for the sake of the type system. 

### Suggested solution

A really nice working solution already exists for `jest` namely [jest-mock-extended](https://github.com/marchaos/jest-mock-extended). In essence this allows the following construct

```typescript
import { mock } from 'jest-mock-extended';

interface PartyProvider {
   getPartyType: () => string;
   getSongs: (type: string) => string[]
   start: (type: string) => void;
}

const mock = mock<PartyProvider>();
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I thinks this is out of Vitest scope 🤔
We don’t use any kind of AST transformation on our side. But it can be enhanced with custom plugins!
So if someone needs it, they can use Vite’s plugin system

**Comment by eratio08** [comment]
@sheremet-va :thinking: maybe I missed the ATS part in the lib, but as far as I understood the lib makes heavy use of `Proxy` like java mocking libs would (e.g https://site.mockito.org). Could you elaborate on this?

**Comment by sheremet-va** [comment]
Oh I haven't look the implementation details. I just assumed they make it like that.

Still the usage is not clear to me. If it's just a mock, why can't you write something like this:

```ts
const mock = {
   getPartyType: vi.fn(), // or vi.fn<[], string>()
   getSongs: vi.fn(), // or vi.fn<[string], string[]>()
   start: vi.fn(), // or vi.fn<[string], void>()
}
```

**Comment by eratio08** [comment]
This will become very tedious for larger interfaces / classes with many fields. The nice thing I found with the lib was that you can provide a partial stubs. This makes it really nice for writing dependency injected mocks with our need every.
```typescript
interface PartyProvider {
   getPartyType: () => string;
   getSongs: (type: string) => string[]
   start: (type: string) => void;
   label: string;
   nested: SomeClass;
}

const mock = mock<PartyProvider>({ label: 'SomeLabel', nested: mock<SomeClass>({}) });
```

**Comment by sheremet-va** [comment]
But was is the actual test example here? So it returns mocks on calling. How is it useful if it's not related to actual code?

Can you give a real life test example?

**Comment by eratio08** [comment]
I have used in a Vue 3 project in cases like the following: 

```typescript
import { DatadogRum } from '@/data-dog' // is a type
import { Env } from '@/env' // is a type
import { createGlobalErrorHandler } from '@/global-error-handler'
import { NStore } from '@/store' // is an interface
import { PLogger } from '@/use-hooks' // is a type
import { mock } from 'jest-mock-extended'

describe('global-error-handler', () => {
	describe('createGlobalErrorHandler', () => {
		it('should create the global error handler', () => {
			//given
			const logger = mock<PLogger>()
			const nStore = mock<NStore>()
			const env = mock<Env>()
			const datadogRum = mock<DatadogRum>()

			//when
			const globalErrorHandler = createGlobalErrorHandler(logger, nativeStore, env, datadogRum)

			//then
			expect(globalErrorHandler).not.toBeNull()
		})
	})
       it('should log unclassified errors if not prod', () => {
		//given
		const logger = mock<PLogger>({ error: jest.fn() })
		const nStore = mock<NStore>()
		const version = 'test'
		const env = mock<Env>({ PROD: false, VITE_VERSION: version })
		const datadogRum = mock<DatadogRum>()
		const globalErrorHandler = createGlobalErrorHandler(logger, nStore, env, datadogRum)
		const error = new Error('error')
		const instance = null
		const info = ''

		//when
		globalErrorHandler(error, instance, info)

		//then
		expect(logger.error).toBeCalledWith(error, { logger: 'GlobalErrorHandler', instance, info, version })
	})
 ...
})
```

**Comment by Namchee** [comment]
Maybe we can do something similar to this? https://www.npmjs.com/package/ts-auto-mock

**Comment by sheremet-va** [comment]
Since we have a community solution, I think we can close this issue.
