### ISSUE TITLE
`vi.importMock` initializes another mock copy, other than the one by the "module under test"

### ISSUE THREAD

**Issue by Bnaya** [vitest-dev/vitest#3510]
### Describe the bug

I'm testing a module that importing 3td party dependency (lets say it's "semver")

I'm mocking it with 
```
vi.mock('semver', function mockFactory(...
```
And then importing it using  ```vi.importMock('semver')```

My module-under-test is importing `semver` using regular esm import ```import { cmp } from 'semver';```

But my module under test and my test `vi.importMock` call are getting a different mocked instance!
And my mock factory is called twice.

You can see it in the following repro repo:
https://stackblitz.com/edit/vitest-dev-vitest-8kcfej?file=test%2FmyModule.ts,test%2Fsuite.test.ts&initialPath=__vitest__/

I've done some debugging and it seems that in the internal vitest modules cache,
the import from the module-under-test is cached under the key: `mock:/PATH/TO/SEMVER/INNODENODULES`  but the `importMock('semver')` is having a key without the `mock` prefix

Related discord discord discussion   
https://discord.com/channels/917386801235247114/1114896459297476648/1114896459297476648

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-8kcfej?file=test%2FmyModule.ts,test%2Fsuite.test.ts,package-lock.json&initialPath=__vitest__/

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @vitest/ui: latest => 0.31.4 
    vite: latest => 4.3.9 
    vitest: latest => 0.31.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This was fixed at some point.
