### ISSUE TITLE
`vi.mock()` + Vue's `inject` failing in 0.31.0

### ISSUE THREAD

**Issue by posva** [vitest-dev/vitest#3517]
### Describe the bug

When importing a function from (in this case vue) a module, it doesn't seem to keep any spied-on function from `vi.mock()`. It was working on 0.30.0

This seems similar to https://github.com/vitest-dev/vitest/issues/3300 or #3510 

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-e5rxrc?file=vite.config.ts,test%2Fsuite.test.ts&initialPath=__vitest__/

- The test should pass but instead, it complains of `inject()` not being a spy

### System Info

```shell
n/a
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Your reproduction seems weird. `vi.unmock` is always hoisted, so you mock vue and then immediately unmock it. Is it intended? You can use `vi.doUmock` to unmock it without hoisting.

**Comment by posva** [comment]
You are right, I didn't know it was hoisted. In my real scenario I have a nested `describe()` where I want to apply the spy so I thought I would _unmock_ there to let other tests within the file use the regular module 😅
