### ISSUE TITLE
Introduce `server` option to pass down options for Vite Node instead of `deps.inline`/`deps.exclude`

### ISSUE THREAD

**Issue by sheremet-va** [vitest-dev/vitest#3522]
### Clear and concise description of the problem

Currently, all options to Vite Node are passed down through different options. If someone uses Vite Node as their primary runtime, it is easier to pass down its options via a single entry. To close #3521, we also need a separate option that can be used for Vite Node initialization for those who use Vite Node as their primary runtime tool.

### Suggested solution

Add a `server` option to Vitest config that is equal to `ViteNodeServerOptions`:

https://github.com/vitest-dev/vitest/blob/15253890e6b1876b3de330d64c9b3f51c4642fc9/packages/vite-node/src/types.ts#L91

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by fenghan34** [comment]
Hi @ sheremet-va, I would like to know if I can try to create a PR for this. 😀

**Comment by sheremet-va** [comment]
> Hi @ sheremet-va, I would like to know if I can try to create a PR for this. 😀

Sure
