### ISSUE TITLE
Add more examples with enabled `deps.optimizer`

### ISSUE THREAD

**Issue by sheremet-va** [vitest-dev/vitest#3523]
### Clear and concise description of the problem

Since `deps.inline` is deprecated (#3521), we should change our existing examples that rely on it like Solid.js to use optimizer instead.

### Suggested solution

Enable `deps.optimizer` in JSDOM/happy-dom examples. Since Node.js tests don't usually benefit from it, we can ignore them if they already don't rely on `deps.inline`. 

We should also add examples where optimizer helps with alias incompatibility like preact (#3502).

This PR should also remove experimental status from `deps.experimentalOptimizer`.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by eryue0220** [comment]
Can I pick it up？

**Comment by sheremet-va** [comment]
> Can I pick it up？

Sure
