### ISSUE TITLE
[vite-node] fails on `@storybook/react`

### ISSUE THREAD

**Issue by layershifter** [vitest-dev/vitest#3525]
### Describe the bug

I am using `vite-node` to evaluate some of our code to get values from it. Using the base setup from [README](https://github.com/vitest-dev/vitest/tree/main/packages/vite-node).

The snippet is following:

```tsx
import { storiesOf } from '@storybook/react';
import * as React from 'react';

storiesOf('Avatar Converged', module)
  .addDecorator((story) => <div style={{ display: 'flex' }}>{story()}</div>)
  .addStory('basic', () => (
    <div style={{ display: 'flex', gap: '24px', padding: '24px' }}>
      <div />
    </div>
  ));
```

Execution is fails with:

  ```
  Error: Cannot read properties of undefined (reading 'location')
      at ESMLoader.import (https://stackblitzstartersw8bzdo-ywrm.w-credentialless.staticblitz.com/blitz.1df59e15.js:35:1312912)
      at i.loadESM (https://stackblitzstartersw8bzdo-ywrm.w-credentialless.staticblitz.com/blitz.1df59e15.js:35:315882)
      at handleMainPromise (https://stackblitzstartersw8bzdo-ywrm.w-credentialless.staticblitz.com/blitz.1df59e15.js:35:1079791)
  ```

It fails on `document.location` and other accesses to `document`, for example: https://github.com/storybookjs/storybook/blob/d8a18a9642ea43c7d70ed6c762caf2822a643aa0/code/lib/preview-api/src/modules/preview-web/UrlStore.ts#L25

The question is tricky, should `vite-node` handle such cases? What is the expectation?

### Reproduction

- Open https://stackblitz.com/edit/stackblitz-starters-w8bzdo
- Run `node index.mjs`
- 💥
  ```
  Error: Cannot read properties of undefined (reading 'location')
      at ESMLoader.import (https://stackblitzstartersw8bzdo-ywrm.w-credentialless.staticblitz.com/blitz.1df59e15.js:35:1312912)
      at i.loadESM (https://stackblitzstartersw8bzdo-ywrm.w-credentialless.staticblitz.com/blitz.1df59e15.js:35:315882)
      at handleMainPromise (https://stackblitzstartersw8bzdo-ywrm.w-credentialless.staticblitz.com/blitz.1df59e15.js:35:1079791)
  ```

### System Info

```shell
Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    vite: ^4.3.9 => 4.3.9 
    vite-node: ^0.31.4 => 0.31.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
ViteNode doesn't come with DOM environment. It runs code with regular globals.
