### ISSUE TITLE
Vitest benchmark stopped working since 0.31.2

### ISSUE THREAD

**Issue by jrouviere** [vitest-dev/vitest#3538]
### Describe the bug

Vitest benchmarks works with Vitest 0.31.1 but gets an exception with 0.31.2+.
The exception occurs on 0.32.0 as well.

### Reproduction

https://github.com/jrouviere/vitest-bench-bug
Just a simple minimal benchmark file, tested with Node v18.16.0:
vitest 0.31.1 works:
`npm install -D vitest@0.31.1 && npx vitest bench --watch false`

vitest 0.31.2 gets an exception:
`npm install -D vitest@0.31.2 && npx vitest bench --watch false`

```
DataCloneError: () => {
  var n;
  return typeof ((n = globalThis.process) == null ? void 0 : n.hrtime) == "function" ? P(Numbe...<omitted>...
} could not be cloned.
 ❯ new DOMException node:internal/per_context/domexception:53:5
 ❯ post node_modules/vitest/dist/worker.js:48:16
 ❯ node_modules/vitest/dist/vendor-index.5037f2c0.js:132:11
 ❯ sendCall node_modules/vitest/dist/vendor-index.5037f2c0.js:129:16
 ❯ node_modules/vitest/dist/vendor-rpc.4d3d7a54.js:50:18
```

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (12) arm64 Apple M2 Pro
    Memory: 919.44 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.90
    Safari: 16.5
  npmPackages:
    vitest: ^0.31.2 => 0.31.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by gyhyfj** [comment]
Same problem 
- Operating System: Linux
- Node Version:     v18.16.0
- Package Manager:  pnpm@8.5.1
