### ISSUE TITLE
Navigating to vitest.dev/guide (no trailing slash) combines the guide and homepage

### ISSUE THREAD

**Issue by Alex-Mastin** [vitest-dev/vitest#3541]
### Describe the bug

Noticed this issue with the official docs.

If you navigate to the guide page without a trailing slash, it combines the homepage and guide into one. It does add the trailing slash to the URL, but it just mashes everything together. All navigation works, but it fails to properly swap what is displayed for a given route. 

### Reproduction

Navigate here: https://vitest.dev/guide

And you should see this:
![image](https://github.com/vitest-dev/vitest/assets/19769539/abd3d69f-42ef-4a9d-a6d2-99d3d0b9c224)

---
Navigate here: https://vitest.dev/guide/

And you should see this:
![image](https://github.com/vitest-dev/vitest/assets/19769539/9978f62f-abda-4afc-8709-585fc3d63851)

### System Info

```shell
Chrome 114.0.5735.90
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This should be fixed when Vitest 1.3.0 is released.
