### ISSUE TITLE
Allow filtering tests by project in workspace

### ISSUE THREAD

**Issue by lucasthevenet** [vitest-dev/vitest#3542]
### Clear and concise description of the problem

Currently AFAIK there isn't any way to filter tests on a workspace in a way that we can select to run only one project.

For example: I have a workspace with 3 defined projects ['api', 'core', 'ui'].

If I run `vitest run api`, it doesn't actually run the tests under the api project, because it doesn't take into account the projects root folder name.

### Suggested solution

One solution could be making the filtering function take into account the project's root folder name as part of the tests path, so that tests inside path 'packages/ui/**/*.test.ts' could be run by calling `vitest run ui`, or if I wanted to run multiple projects at the same time `vitest run ui,core`.

### Alternative

Another possible implementation that could solve this issue without conflicting with the normal filtering method is adding a new flag '--workspace' (or maybe another name since it may be confused with -w/--watch)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I feel like this is similar to #3255 because it requires the same solution (read config before starting the server).

**Comment by ITenthusiasm** [comment]
Agree that this would be great to have. It's really helpful to be able to run only a specific project's tests.

[jest-watch-select-projects](https://www.npmjs.com/package/jest-watch-select-projects) only kicked in after jest was started in watch mode. And it allowed tests to be run only for a specific project (or group of projects). For this, we were given the uppercase `P` character in between test runs (just like right now, we can filter by filename by typing lowercase `p`).

Maybe their implementation could be of help? (I haven't seen it.)

---

Being able to run tests by project(s) would probably be something good to have at the CLI level and at the watch-mode level, though.

**Comment by sheremet-va** [comment]
You can already do `vitest packages/ui/` and it will run all tests inside the ui folder. I am not sure if we just need to document it better? Vitest just does `.includes` check on arguments it receives.

To run several projects:

```
vitest packages/ui packages/api
```

**Comment by sheremet-va** [comment]
> I wouldn't be stuck with testing only the packages that were initially specified in the command.

You can update the arguments by pressing `p` and entering a new option (as far as I know, you can only enter one for now).

**Comment by ITenthusiasm** [comment]
Oh, interesting. I'll try that out soon.

**Comment by sheremet-va** [comment]
You can pass down `--project=api`. If you need several projects, repeat the argument: `--project=api --project=core`.
