### ISSUE TITLE
`expect.toBe` can't handle large enough objects

### ISSUE THREAD

**Issue by zumm** [vitest-dev/vitest#3558]
### Describe the bug

I'm trying to do:
```ts
expect(object).toBe(null)
```
Where `object` has [this value](https://pastebin.com/SLM1nvBL) (dump from debugger).

`Vitest` freezes for a few minutes and fails with `RangeError: Invalid string length` error:
![image](https://github.com/vitest-dev/vitest/assets/10081538/b8c72bab-6d72-4e79-b33a-607c2db754f5)

If i use smaller `object` like [this](https://pastebin.com/JfGsfpBj) (actually same object, but without some circular refs) it works fine.

### Reproduction

-

### System Info

```shell
System:
    OS: Windows Server 2016 10.0.14393
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 4.37 GB / 15.93 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Internet Explorer: 11.0.14393.2007
  npmPackages:
    vitest: ^0.31.4 => 0.31.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
We no longer use concordance so this is not a problem in the latest version.
