### ISSUE TITLE
Mocking fails if test imports JSON file

### ISSUE THREAD

**Issue by christian-bromann** [vitest-dev/vitest#3559]
### Describe the bug

If a vitest imports a JSON file, e.g. `import pkg from '../package.json' assert { type: 'json' }` and accesses the `pkg` object, then for some reason the whole mocking system fails.

This was very hard to debug. While you get this:
```
Cannot parse /home/projects/vitest-dev-vitest-xhy2bv/test/suite.test.ts:
Unexpected token (3:34)
```
the line doesn't really match with the test file.

### Reproduction

See: https://stackblitz.com/edit/vitest-dev-vitest-xhy2bv?file=test%2Fsuite.test.ts

If you comment out line 15 (`expect(pkg.name).eq('@vitest/example-test');`) I assume the import gets removed since the variable is not used and the test starts passing.

### System Info

```shell
System:
    OS: macOS 13.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 771.63 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 9.7.1 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Brave Browser: 113.1.51.118
    Chrome: 114.0.5735.106
    Chrome Canary: 116.0.5827.0
    Firefox Nightly: 114.0a1
    Safari: 16.4
  npmPackages:
    @vitejs/plugin-react: ^4.0.0 => 4.0.0
    @vitejs/plugin-vue: ^4.2.3 => 4.2.3
    @vitest/coverage-v8: ^0.32.0 => 0.32.0
    vitest: ^0.32.0 => 0.32.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This was an error in Vite that was fixed some time ago (cannot find the issue). It is no longer an issue here. Also, `assert` was deprecated and it's now required to use `with` instead.

The reproduciton works correctly on the latest version.
