### ISSUE TITLE
Support case-insensitive path matching in cli

### ISSUE THREAD

**Issue by nstepien** [vitest-dev/vitest#3567]
### Clear and concise description of the problem

When running the vitest cli with a path argument, vitest requires the path to match the casing of the test file.
```
> npx vitest run dropdown

 RUN  v0.32.0 D:/repos/my-repo
      Running tests with seed "1686657842950"

filter:  dropdown
include: **/__tests__/**/*.?(c|m)[jt]s?(x), **/?(*.){test,spec}.?(c|m)[jt]s?(x)
exclude:  **/node_modules/**, **/dist/**, **/cypress/**, **/.{idea,git,cache,output,temp}/**, **/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*
watch exclude:  **/node_modules/**, **/dist/**

No test files found, exiting with code 1

> npx vitest run DropDown

 RUN  v0.32.0 D:/repos/my-repo
      Running tests with seed "1686657848457"

filter:  DropDown
include: **/__tests__/**/*.?(c|m)[jt]s?(x), **/?(*.){test,spec}.?(c|m)[jt]s?(x)
exclude:  **/node_modules/**, **/dist/**, **/cypress/**, **/.{idea,git,cache,output,temp}/**, **/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build}.config.*
watch exclude:  **/node_modules/**, **/dist/**

No test files found, exiting with code 1

> npx vitest run Dropdown

 RUN  v0.32.0 D:/repos/my-repo
      Running tests with seed "1686657851716"

 ✓ src/components/DropdownMenu/DropdownMenu.test.tsx (2) 472ms
 ✓ src/components/Button/DropdownButton.test.tsx (1) 588ms

 Test Files  2 passed (2)
      Tests  3 passed (3)
   Start at  13:04:11
   Duration  3.00s (transform 501ms, setup 482ms, collect 1.31s, tests 1.06s, environment 757ms, prepare 374ms)
```

### Suggested solution

Vitest should support case-insensitive path matching.

### Additional context

Coming from Jest, which matches path case-insensitively, having to remember the exact casing can be rather frustrating.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by IanVS** [comment]
@sheremet-va would you accept a PR making this change?

**Comment by sheremet-va** [comment]
> @sheremet-va would you accept a PR making this change? I see a "question" label but I'm not sure what other information you need.

Yes, PR welcome.

**Comment by tigranmk** [comment]
@IanVS Are you working on this, or I can pick it ?

**Comment by IanVS** [comment]
I haven't had a chance, feel free to go for it, thanks for asking.
