### ISSUE TITLE
When vite-node runs the script, the parameters should be passed transparently

### ISSUE THREAD

**Issue by rxliuli** [vitest-dev/vitest#3571]
### Describe the bug

For example, the following is the behavior of `node/tsx/ts-node/vite-node` four clis running a script. I think the behavior of vite-node should be consistent with others

```sh
> vite-node-execute-demo@1.0.0 start /Users/rxliuli/code/web/demo/vite-node-execute-demo
> pnpm start-node && pnpm start-tsx && pnpm start-ts-node && pnpm start-vite-node


> vite-node-execute-demo@1.0.0 start-node /Users/rxliuli/code/web/demo/vite-node-execute-demo
> node hello.js -h

[
  '/usr/local/bin/node',
  '/Users/rxliuli/code/web/demo/vite-node-execute-demo/hello.js',
  '-h'
]

> vite-node-execute-demo@1.0.0 start-tsx /Users/rxliuli/code/web/demo/vite-node-execute-demo
> tsx hello.js -h

[
  '/usr/local/bin/node',
  '/Users/rxliuli/code/web/demo/vite-node-execute-demo/hello.js',
  '-h'
]

> vite-node-execute-demo@1.0.0 start-ts-node /Users/rxliuli/code/web/demo/vite-node-execute-demo
> ts-node hello.js -h

[
  '/Users/rxliuli/code/web/demo/vite-node-execute-demo/node_modules/ts-node/dist/bin.js',
  '/Users/rxliuli/code/web/demo/vite-node-execute-demo/hello.js',
  '-h'
]

> vite-node-execute-demo@1.0.0 start-vite-node /Users/rxliuli/code/web/demo/vite-node-execute-demo
> vite-node hello.js -h

vite-node/0.32.0

Usage:
  $ vite-node [...files]

Commands:
  [...files]  

For more info, run any command with the `--help` flag:
  $ vite-node --help

Options:
  -v, --version        Display version number 
  -r, --root <path>    Use specified root directory 
  -c, --config <path>  Use specified config file 
  -m, --mode <mode>    Set env mode 
  -w, --watch          Restart on file changes, similar to "nodemon" 
  --script             Use vite-node as a script runner 
  --options <options>  Use specified Vite server options 
  -h, --help           Display this message 
```

hello.js

```js
console.log(process.argv)
```

### Reproduction

1. git clone https://github.com/rxliuli/vite-node-execute-demo
2. cd vite-node-execute-demo
3. pnpm i
4. pnpm start

### System Info

```shell
System:
    OS: macOS 13.3
    CPU: (12) arm64 Apple M2 Max
    Memory: 16.86 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
    Watchman: 2023.03.27.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 114.0.5735.106
    Firefox: 114.0
    Safari: 16.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Please, open a new PR that specifies the changes in the README. "consistent with node" is not a change - please, reference all breaking changes that you introduced and how to migrate.
