### ISSUE TITLE
Add option to make `describe.concurrent` a default, instead of `describe`

### ISSUE THREAD

**Issue by o-alexandrov** [vitest-dev/vitest#3573]
### Clear and concise description of the problem

Instead of setting `describe.concurrent`, it'd be great to have an option to set it as a default.

### Suggested solution

Add config option `--concurrent`

### Additional context

Currently, if a project wants to enforce use of `concurrent` for all tests, it's practically impossible to do so, because:
- `vitest` doesn't have a config option to set it globally
- if a project adds a wrapper and asks developers to use this wrapper everywhere, there could still be instances when a developer would forget to do so by importing a `describe` from `vitest` or use a globally provided `describe`
- there is no such ESLint rule in [eslint-plugin-vitest](https://www.npmjs.com/package/eslint-plugin-vitest)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by o-alexandrov** [comment]
Great, thank you @sheremet-va

**Comment by fenghan34** [comment]
I'm working on it.

**Comment by o-alexandrov** [comment]
Thank you @fenghan34 for the change and @sheremet-va for reviewing it.
There's one case users would probably miss:
- when setting `--sequence.concurrent`, there's no way to override this behavior for an individual `describe` suite
  - for example, we have `describe.concurrent` now to set the sequence.concurrent behavior for an individual describe, but if a user would set `.concurrent` by default, there's no way to add a sequential override for an individual `describe`
