### ISSUE TITLE
TypeError: window.addEventListener is not a function

### ISSUE THREAD

**Issue by lixiaofa** [vitest-dev/vitest#3585]
### Describe the bug

pnpm test  error
![image](https://github.com/vitest-dev/vitest/assets/23230215/b7b2bc67-f383-4b4b-a5c9-b72a21c47929)

### Reproduction

https://github.com/lixiaofa/fast-plus

### System Info

```shell
"vitest": "0.12.6",
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
The code runs after Vitest teardowns its environment. The problem is in the code, not in Vitest.
