### ISSUE TITLE
TypeError: Unknown file extension ".css"  and Inline does not work

### ISSUE THREAD

**Issue by lixiaofa** [vitest-dev/vitest#3588]
### Describe the bug

![image](https://github.com/vitest-dev/vitest/assets/23230215/3be25c39-f6e5-4552-9754-bb91c06c686b)
Inline does not work

### Reproduction

https://github.com/lixiaofa/fast-plus

### System Info

```shell
"vitest": "^0.32.0",
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
deps.inline is test.server.deps.inline, it’s not in the root of the config
