### ISSUE TITLE
spyOn not working as in Jest

### ISSUE THREAD

**Issue by robbash** [vitest-dev/vitest#3592]
### Describe the bug

Thanks for the great work of Vitest and the effort to make migration from Jest as easy as possible. I have taken on the task to switch over one of our repositories to Vitest but hit some blockers when trying to convert the tests from Jest to Vitest.

I'm trying to spy on and mock a function in a module, which is used by another function in that module. In Jest, it works fine.

```ts
// my-module.ts
export const getToken = async () => Promise.resolve("a token");

export const sendRequest = async () => {
  const token = await getToken();

  console.warn(
    `Using the token >>> ${token} <<< to send my authenticated request`
  );

  return true;
};
```

From the test file

```ts
const spy = vi
  .spyOn(myModule, "getToken")
  .mockResolvedValue("the mocked token");
```

Please see linked repository for details.

### Reproduction

**Test repo**
https://github.com/robbash/vitesttest

**Jest comparison branch**
https://github.com/robbash/vitesttest/tree/jest

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) x64 Apple M1 Max
    Memory: 46.00 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.21.2 - ~/.nvm/versions/node/v14.21.2/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.6.4 - ~/.nvm/versions/node/v14.21.2/bin/npm
  Browsers:
    Brave Browser: 114.1.52.122
    Chrome: 114.0.5735.133
    Firefox: 114.0.1
    Safari: 16.2
  npmPackages:
    vitest: ^0.32.1 => 0.32.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is not meant to work. It works for you only because you see ts-jest which incorrectly transforms files, not because you use jest. This code does not work without `ts-jest`.
