### ISSUE TITLE
`ecosystem-ci` for Vitest

### ISSUE THREAD

**Issue by sheremet-va** [vitest-dev/vitest#3595]
### Clear and concise description of the problem

Vitest has some examples to test how different frameworks work. However, it is not sufficient enough in cases where the error can happen because of a publishing issue or when error cannot be reproduced in a linked environment because of the way Vite handles deps optimization.

### Suggested solution

Implement ecosystem-ci repo, like:

- https://github.com/vitejs/vite-ecosystem-ci
- https://github.com/vuejs/ecosystem-ci

It should contain at the very least browser tests.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by nickmccurdy** [comment]
Would tests for specific testing tools (like Testing Library) also fit?

**Comment by sheremet-va** [comment]
> Would tests for specific testing tools (like Testing Library) also fit?

I think so.

**Comment by nickmccurdy** [comment]
Cool, feel free to ping me if I can help with that.

**Comment by AriPerkkio** [comment]
Repository created: https://github.com/vitest-dev/vitest-ecosystem-ci

**Comment by sheremet-va** [comment]
@nickmccurdy we have some tests [already set up](https://github.com/vitest-dev/vitest-ecosystem-ci/tree/main/tests), feel free to open a PR for testing-library.
