### ISSUE TITLE
Clear terminal in watch mode

### ISSUE THREAD

**Issue by gkiely** [vitest-dev/vitest#3608]
### Describe the bug

When using large amounts of text the terminal does not clear on save using macOS.

See https://github.com/vitest-dev/vitest/issues/1183 for details.

### Reproduction

See instructions from: https://github.com/vitest-dev/vitest/issues/1183

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 244.83 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.volta/tools/image/node/20.2.0/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 9.6.6 - ~/.volta/tools/image/node/20.2.0/bin/npm
    Watchman: 2023.04.10.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 112.1.50.119
    Chrome: 114.0.5735.133
    Edge: 114.0.1823.51
    Firefox: 114.0
    Safari: 15.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
@gkiely this happens only on MacOS's built-in Terminal application, right? Any other terminal works fine at least based on my testing at https://github.com/vitest-dev/vitest/issues/1183#issuecomment-1573201532.

If I add following to the reproduction script, the terminal is cleared correctly:

```diff
// repro.mjs
const message = "Hello World";

await new Promise((r) => setTimeout(r, 1000));
Array(200).fill(0).forEach((_, i) => console.log(`Row ${i}`));
console.log("Scroll up now");

await new Promise((r) => setTimeout(r, 3000));
+ console.log("\x1b[2J\x1b[3J\x1b[H");
console.log(`\x1Bc${message}`); // Vitest's logger.clearFullScreen
console.log("Testing");
```

This is something that could probably be added here:

https://github.com/vitest-dev/vitest/blob/f427f0047712bf7719f1a84a69633cc923b63470/packages/vitest/src/node/logger.ts#L46

```diff
+   this.console.log('\u001B[2J\u001B[3J\u001B[H')
    this.console.log(`\x1Bc${message}`)
```

This seems to work at least on my machine but I'm not really familiar with raw ANSI-codes. I picked the sequence from here: https://github.com/sindresorhus/ansi-escapes/issues/25#issuecomment-832640048.

**Comment by gkiely** [comment]
> this happens only on MacOS's built-in Terminal application, right?

Yes

**Comment by AriPerkkio** [comment]
> Jest clears the scrollbar and terminal where vitest does not.
> https://github.com/vitest-dev/vitest/issues/1183#issuecomment-1568986417

Jest seems to indeed be using different ANSI codes than Vitest. We should try to change Vitest to use the same `\x1B[2J\x1B[3J\x1B[H` and do extensive testing with different terminals on different OS's:

- https://github.com/jestjs/jest/blob/f4172f5bc0ca1eaffad417135222d2102aeab7f2/packages/jest-util/src/specialChars.ts#L18
- https://github.com/jestjs/jest/blob/f4172f5bc0ca1eaffad417135222d2102aeab7f2/packages/jest-core/src/watch.ts#L283
