### ISSUE TITLE
Allow to interrupt test running in watch mode

### ISSUE THREAD

**Issue by sethreidnz** [vitest-dev/vitest#3612]
### Clear and concise description of the problem

Currently if I have thousands of tests to run and want to use the watch feature to filter only say one test, or test file, then I have to wait until the entire test suite runs to then press "h" and do that. This takes a lot of time and also is different to how Jest works where you can interrupt the test running and do filtering.

### Suggested solution

Pressing enter, or any of the keys like "h" or whatever should interrupt the current run. That way I could start the watch, press enter, then start filtering to the tests I care about. This is how Jest works and it would be great if Vite did similar.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
This should already be implemented by https://github.com/vitest-dev/vitest/pull/3163. When you press `c`, space or any other key that Vitest registers in watch mode, the test run should be interrupted. Exactly as in Jest. 

The `h` key is not used by Vitest at all. 
https://github.com/vitest-dev/vitest/blob/1e8760ab2b4ae02288ebaf0ab27f9ed314d41980/packages/vitest/src/node/stdin.ts#L7-L16

https://github.com/vitest-dev/vitest/blob/1e8760ab2b4ae02288ebaf0ab27f9ed314d41980/packages/vitest/src/node/stdin.ts#L50-L54

**Comment by sethreidnz** [comment]
> This should already be implemented by #3163. When you press `c`, space or any other key that Vitest registers in watch mode, the test run should be interrupted. Exactly as in Jest.
> 
> The `h` key is not used by Vitest at all.
> 
> https://github.com/vitest-dev/vitest/blob/1e8760ab2b4ae02288ebaf0ab27f9ed314d41980/packages/vitest/src/node/stdin.ts#L7-L16
> 
> https://github.com/vitest-dev/vitest/blob/1e8760ab2b4ae02288ebaf0ab27f9ed314d41980/packages/vitest/src/node/stdin.ts#L50-L54

Oh cool. Will have to see when at the computer when I get there if we are on an older version but wasn’t working for me today and very recently migrated. Although that PR looks like it’s pretty newly merged so maybe I’m not on that version. 

And yeah it does use “h” it’s what it says at the end when you’ve finished running tests. Something like press “h” for help.

**Comment by AriPerkkio** [comment]
> it does use “h” it’s what it says at the end when you’ve finished running tests

Oh right, sorry, you are correct. The #3618 adds `h` key for cancelling watch mode too.
