### ISSUE TITLE
EADDRINUSE

### ISSUE THREAD

**Issue by jdion84** [vitest-dev/vitest#3617]
### Describe the bug

When running `vite-node` in `watch` mode, after making file changes, I get the following error in the terminal:

```console
[vite-node] Failed to execute file: 
 Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1774:16)
    at listenInCluster (node:net:1822:12)
    at Server.listen (node:net:1910:7)
    at Function.listen (/Users/jdion84/Sites/framework/node_modules/express/lib/application.js:635:24)
    at /Users/jdion84/Sites/framework/my_modules/skele/app.jsx:33:5
    at ViteNodeRunner.directRequest (file:///Users/jdion84/Sites/framework/node_modules/vite-node/dist/client.mjs:334:5)
    at ViteNodeRunner.cachedRequest (file:///Users/jdion84/Sites/framework/node_modules/vite-node/dist/client.mjs:190:14)
    at ViteNodeRunner.executeId (file:///Users/jdion84/Sites/framework/node_modules/vite-node/dist/client.mjs:166:12)
    at async Promise.all (index 0) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 3000
}
```

I have tried using recommended solutions involving `import.meta.hot` and they do not resolve the issue:

```js
import express from 'express'

const app = express()

const port = 3000

app.get('/', (req, res) => {
    res.render('Home')
})

const server = app.listen(port, () => {
    console.log(`App listening on http://localhost:${port}`)
})

if (import.meta.hot) {
    import.meta.hot.accept(() => {
        server.close()
    })

    import.meta.hot.on("vite:beforeFullReload", () => {
        server.close()
    })

    import.meta.hot.dispose(() => {
        server.close()
    })
}
```

### Reproduction

See bug description.

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 440.97 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    npm: 9.5.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Safari: 16.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You need to await `server.close`.
