### ISSUE TITLE
Module '"util"' has no default export.

### ISSUE THREAD

**Issue by fubhy** [vitest-dev/vitest#3622]
### Describe the bug

When enabling lib checks in a consuming application or library that uses vitest, but doesn't allow synthetic default imports you'll currently run into this error:

```
@vitest/utils/dist/index.d.ts(5,8): error TS1192: Module '"util"' has no default export
```

### Reproduction

I think the issue is obvious but let me know if you think otherwise and I'm happy to produce a reproduction repo.

### System Info

```shell
System:
    OS: Linux 5.19 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
    Memory: 20.47 GB / 31.20 GB
    Container: Yes
    Shell: 3.6.1 - /usr/bin/fish
  Binaries:
    Node: 20.2.0 - ~/.asdf/installs/nodejs/20.2.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/shims/yarn
    npm: 9.6.6 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 113.0.5672.126
    Chromium: 114.0.5735.106
    Firefox: 113.0.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fubhy** [comment]
I opened #3621

**Comment by curran** [comment]
I'm experiencing this as well.

**Comment by curran** [comment]
Workaround for now until that change gets released - exclude the test files from type checking:

`tsconfig.json`
```
{
  "//": "gets rid of the error:  'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.'",
  "compilerOptions": {
    "jsx": "react-jsx"
  },
  "include": ["src/**/*"],
  "exclude": ["src/**/*.test.tsx", "src/**/*.test.ts"]
}
```
