### ISSUE TITLE
Breaking changes introduced in minor version updates

### ISSUE THREAD

**Issue by lsarrazi** [vitest-dev/vitest#3623]
### Describe the bug

As described in the semver specification, breaking changes should be only introduced in major updates; Althought 0.31.0 do introduce breaking changes while being a minor update.

https://semver.org/

We did a bump of vitest on our repo without testing it (cause we expected it to be retrocompatible) and our CI did break and we had to reverse commit the change.

BTW : https://github.com/vitest-dev/vitest/issues/2593 (may be not relevant)

### Reproduction

-

### System Info

```shell
-
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
> 4. Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.
> https://semver.org/#spec-item-4

In 0.x versions breaking changes may happen. Vitest has been using minor versions for breaking change releases. After 1.0.0 breaking changes are introduced only in major releases.

**Comment by sheremet-va** [comment]
@AriPerkkio explained it perfectly

**Comment by lsarrazi** [comment]
Thank you for your answer @AriPerkkio , I did not know this fact
