### ISSUE TITLE
timeout error when testing fetch with nock

### ISSUE THREAD

**Issue by rburgst** [vitest-dev/vitest#3624]
### Describe the bug

when mocking network requests with `nock` then vitest produces a timeout where jest works without problems.
Any help would be appreciated

### Reproduction

https://replit.com/@rburgst/vitest-nock-problem?v=1
https://stackblitz.com/edit/vitest-dev-vitest-khkmge?file=test%2Fnock.test.ts

1. on the right hand side choose the "Shell" tab
2. run `npm install`
3. run `npm test`

## expected

the test should succeed and log the fetch result

## actual

the test times out after 5s

### System Info

```shell
System:
    OS: Linux 5.19 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 AMD EPYC 7B12
    Memory: 34.90 GB / 62.79 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.12.1 - /nix/store/dj805sw07vvpbxx39c8g67x8qddg0ikw-nodejs-18.12.1/bin/node
    Yarn: 1.22.19 - /nix/store/zdcnqq55qi214j46zgw2qa1jp4dpdf2m-yarn-1.22.19/bin/yarn
    npm: 8.19.2 - /nix/store/dj805sw07vvpbxx39c8g67x8qddg0ikw-nodejs-18.12.1/bin/npm
  npmPackages:
    vite: ^4.3.9 => 4.3.9 
    vitest: ^0.32.2 => 0.32.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rburgst** [comment]
anyone home?

**Comment by VelizarDemirev** [comment]
It would be nice to see some response here

**Comment by AriPerkkio** [comment]
Could you convert the repl.it repro to Github repository or Stackblitz?

**Comment by panzerdp** [comment]
Unfortunately having the same problem. Some details can be found [here](https://github.com/nock/nock/issues/2200).

**Comment by PiotrBryla** [comment]
I have the same problem.

**Comment by hi-ogawa** [comment]
I'm not familiar with `nock` but it looks like they don't have a stable support with `fetch` yet:
- https://github.com/nock/nock/issues/2397

With the latest stable (13.5.4), it doesn't timeout but it looks like an error from `nock`:
https://stackblitz.com/edit/vitest-dev-vitest-khkmge?file=test%2Fnock.test.ts

Then, I tested with beta (14.0.0-beta.4) and this one looks working for me:
https://stackblitz.com/edit/vitest-dev-vitest-htb8gx?file=test%2Fnock.test.ts

I'm not sure how Jest has made it work, but I don't think there's anything actionable from Vitest for this issue.
Please provide a reproduction if you see something different from the above examples I made on stackblitz.

**Comment by rburgst** [comment]
@hi-ogawa was kind enough to do that: https://stackblitz.com/edit/vitest-dev-vitest-khkmge?file=test%2Fnock.test.ts

**Comment by hi-ogawa** [comment]
@rburgst I think this error is simply due to `nock`'s limitation in v13. That's why I wrote that there's nothing actionable from Vitest side. Can you try v14 (beta) to see if it works for you?
