### ISSUE TITLE
 "TypeError: vi_esm_1.default.default is not a function" error when an expect assertion failed on browser mode

### ISSUE THREAD

**Issue by Bnaya** [vitest-dev/vitest#3625]
### Describe the bug

There's a wacked "TypeError: vi_esm_1.default.default is not a function" error when an expect assertion  failed  on browser mode

Run this code in browser mode:
```ts
describe("vitest browser mode lets see", function () {
  test("lalla", async () => {
    expect(1).toBe(1);
    expect(1).toBe(2); // <- Failed assertion
  });
});

```

### Reproduction

Not working on stackblitz!
https://stackblitz.com/edit/vitest-dev-vitest-cupgmf

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 5.30 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.volta/tools/image/node/18.14.0/bin/node
    Yarn: 3.2.0 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.3.1 - ~/.volta/tools/image/node/18.14.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Chrome Canary: 116.0.5841.0
    Firefox: 112.0.2
    Safari: 16.5
  npmPackages:
    vitest: ^0.32.0 => 0.32.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by atmosbear** [comment]
Hi there, I'm still getting this issue: `TypeError: __vi_esm_1__.default.default is not a function`

Is it fully fixed? If it is I'll do some testing and start over from scratch to see if I need to make a new issue

**Comment by sheremet-va** [comment]
Fix is not released yet

**Comment by atmosbear** [comment]
Aww man. Is there a way to build it myself so that I can use it? It's really hard to do browser testing with it haha

**Comment by Bnaya** [comment]
> Aww man. Is there a way to build it myself so that I can use it? It's really hard to do browser testing with it haha

If you are very inpatient, I would recommend using some form of package patching and not deal with publishing
