### ISSUE TITLE
Vitest Can't Mock Sequelize Models

### ISSUE THREAD

**Issue by nrsrh-asyh** [vitest-dev/vitest#3630]
### Describe the bug

When trying to mock `sequelize classes` using `vi.mock` (from https://vitest.dev/guide/mocking.html#cheat-sheet), this error is returned:

`Error: Specified type of property 'firstName' cannot be automatically resolved to a sequelize data type. Please define the data type manually`

![Screenshot 2023-06-20 at 5 08 47 PM](https://github.com/vitest-dev/vitest/assets/116047727/0b3602f0-669a-4283-a90a-56a9a2bc52bc)

Error is assumed to be due to the usage of `emitDecoratorMetadata` in `tsconfig.json` that is needed by `sequelize-typescript` (https://github.com/sequelize/sequelize-typescript)

Expected Vitest to be able to mock `sequelize models` via `vi.mock`

### Reproduction

I made a GitHub repo to reproduce this issue:

https://github.com/nrsrh-asyh/vitest-sequelize

Clone and run `npm test`

### System Info

```shell
Any
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest uses Vite that uses esbuild to process TypeScript files. Esbuild just leaves decorators as is: https://github.com/evanw/esbuild/issues/104

See similar issues:
- https://github.com/vitest-dev/vitest/issues/3140
- https://github.com/vitest-dev/vitest/issues/708
