### ISSUE TITLE
Document `onConsoleLog`

### ISSUE THREAD

**Issue by sheremet-va** [vitest-dev/vitest#3632]
### Clear and concise description of the problem

Vitets supports `onConsoleLog` since the very first version basically. But it was never documented.

### Suggested solution

We should add documentation about `onConsoleLog` field. Here is a brief description of the method from the current JSDoc:

```
Custom handler for `console.log` in tests.

Return `false` to ignore the log.

onConsoleLog?: (log: string, type: 'stdout' | 'stderr') => false | void
```

Documentation should have a description, TypeScript type, and an example.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by eddie0329** [comment]
@sheremet-va  I would love to work on this!

**Comment by sheremet-va** [comment]
> @sheremet-va I would love to work on this!

You don't need to announce this :)
