### ISSUE TITLE
Vitest Coverage fails with dynamic modules

### ISSUE THREAD

**Issue by vekunz** [vitest-dev/vitest#3646]
### Describe the bug

With the new coverage package `@vitest/coverage-v8` the generation of the coverage report fails.

Our code dynamically generates JavaScript modules code. In the Unit Tests, we parse this code and check the resulting module. This is a simplified example:

```js
const module = await importFromString('export const TEST = "test";');
expect(module.TEST).toEqual('test');
```

For parsing we use the npm package `module-from-string`.

The test itself works fine, but the code coverage report fails with an error:

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: ENOENT: no such file or directory, open '....\vitest-coverage-error\src\xTjqsFWnSh1l4K9-fi-w1.js'
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: {
  "code": "ENOENT",
  "errno": -4058,
  "path": "....\vitest-coverage-error\src\xTjqsFWnSh1l4K9-fi-w1.js",
  "syscall": "open",
}

```

### Reproduction

I created a minimal reproduction repo https://github.com/vekunz/vitest-coverage-error

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz   
    Memory: 7.41 GB / 31.79 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 114.0.5735.134
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.51)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitest/coverage-v8: 0.32.2 => 0.32.2
    vitest: 0.32.2 => 0.32.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
We should add a check into `@vitest/coverage-v8` for checking that files in V8 reports actually exist. All files that are ran will end up in the V8 report. 

Maybe some where around here:

https://github.com/vitest-dev/vitest/blob/158c4bb056417828833088508b43e6917d65d23f/packages/coverage-v8/src/provider.ts#L103

**Comment by sheremet-va** [comment]
> We should add a check into `@vitest/coverage-v8` for checking that files in V8 reports actually exist

Does it mean it's not possible to see the coverage for these files?

**Comment by AriPerkkio** [comment]
Yes, it is possible to show coverage for those. And maybe we should keep showing them. But when coverage is inspected in HTML report, the reported will display `ENOENT` error. Below is one example:

<details>

```js
import { existsSync, rmSync, writeFileSync } from "node:fs";

test("dynamic file", async () => {
  const filename = new URL("./dynamic-file.mjs", import.meta.url).pathname;

  writeFileSync(
    filename,
    `
// File created by test/coverage-test/src/dynamic-files.ts

export function run() {
  return "Import works"
}

function another() {}
  `.trim(),
    "utf-8"
  );

  const { run } = await import(filename);
  run();

  rmSync(filename);
});
```

```
 % Coverage report from v8
------------------|---------|----------|---------|---------|-------------------
File              | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
------------------|---------|----------|---------|---------|-------------------
All files         |   66.66 |      100 |      50 |   66.66 |                   
 dynamic-file.mjs |   66.66 |      100 |      50 |   66.66 | 7-9               
------------------|---------|----------|---------|---------|-------------------

=============================== Coverage summary ===============================
Statements   : 66.66% ( 6/9 )
Branches     : 100% ( 1/1 )
Functions    : 50% ( 1/2 )
Lines        : 66.66% ( 6/9 )
================================================================================
```

</details>

But in the case of `module-from-string` it seems that it actually calls `require()` on the created file: https://github.com/exuanbo/module-from-string/blob/78ea0561bfede38a87b8f63ae8ea0dcc2b155536/src/import.ts#L60. It also transforms the code to CJS.

If it used `import`, as in the minimal example above, it would work. I guess the file is in import cache when report is generated.

@vekunz I would recommend here to use `module-from-string`'s `filename` option and add that filename into the `coverage.exclude`.

**Comment by vekunz** [comment]
> @vekunz I would recommend here to use `module-from-string`'s `filename` option and add that filename into the `coverage.exclude`.

Thank you, this works fine!

**Unit Test:**
```js
const module = await importFromString('export const TEST = "test";', {filename: 'dynamicFile.ignore.js'});
expect(module.TEST).toEqual('test');
```

**vitest config:**
```js
export default defineConfig({
  test: {
    // ...
    coverage: {
      // ...
      exclude: ['**/dynamicFile.ignore.js']
    }
  }
});
```

**Comment by AriPerkkio** [comment]
We should still check whether the crash could be avoided in Vitest's codebase. I think it's currently coming from somewhere around here:

https://github.com/vitest-dev/vitest/blob/158c4bb056417828833088508b43e6917d65d23f/packages/coverage-v8/src/provider.ts#L220-L224

But I don't think it's possible to show actual coverage for these files as source maps and sources are not available.
