### ISSUE TITLE
Make tests fail when there is a warning

### ISSUE THREAD

**Issue by cyan-berg** [vitest-dev/vitest#3653]
### Clear and concise description of the problem

As a developer using Vitest I want to have tests fail when there are warnings so that warnings do not get pushed into my repo by accident.

### Suggested solution

CLI option: --warnings-as-errors

### Alternative

Or vitest config option Boolean.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
What warnings?

**Comment by cyan-berg** [comment]
> Ones made with console.warn for example, like Vue warnings.

Ones made with console.warn for example, like Vue warnings.

**Comment by sheremet-va** [comment]
I don't think Vitest should have it built in. The same goes for `console.error`. This is just a function call, not an assertion.

You can use packages to achieve the same or right it yourself by spying on `console.warn`.

**Comment by cyan-berg** [comment]
Hey.. spying on console.warn.. That's a good idea! 💡 

I still think it would be a cool Vitest option (eg: failOnConsoleWarn). However I understand and respect that you view it as out of scope.

Thanks Vladimir.

**Comment by userquin** [comment]
@cyan-berg https://elk.zone/m.webtoo.ls/@lukastaegert/110525513598937367
