### ISSUE TITLE
`watch` + `--changed` is unreliable with unexpected DX

### ISSUE THREAD

**Issue by o-alexandrov** [vitest-dev/vitest#3666]
### Describe the bug

Running `vitest` with `--changed` is unreliable and produces unexpected developer experience.

### Reproduction

When running the command below, there are two different bugs:
```sh
vitest watch --changed
```
### Case 1 (no changes initially)

You'll see `No test files found, exiting with code 0`
- however, since the cmd is `watch`, shouldn't the script continue to watch all files that it compared against that were initially checked if there are any changes?
  - in other words, imho, `watch` shouldn't exit if there are no changes, it should keep running so when a change happens, it reacts to the file

### Case 2 (file X was changed)

The file X would be tested.
Then, if you change file Y, `vitest` wouldn't run tests in file Y.

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 56.77 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Edge: 112.0.1722.39
    Firefox: 114.0.2
    Safari: 16.5
  npmPackages:
    vite: ^4.3.9 => 4.3.9
    vitest: 0.32.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HendrikPetertje** [comment]
dealing with this as well, we migrated an existing project from jest to vitest. our project has several thousand tests, waiting for the initial test run takes around 3 minutes. I'd like Vitest to only test what was changed when i boot it up and then keep watching for further changes that i make as I make them.

I'm currently working around this with a little `testWatch.mjs`, feel free to use it if you are in the same situation as me.

```
import { watch } from 'fs';
import { spawn } from 'child_process';
import readline from 'readline';

let timeout = null;
let isBusy = false;
let ls;

function watchHandler () {
  if (timeout) clearTimeout(timeout);
  // Debounce the event, since multiple events can be emitted on save
  timeout = setTimeout(async () => {
    isBusy = true;
    await new Promise((resolve) => {
      console.clear();
      let ls = spawn('yarn', ['test', 'run', '--changed'], { stdio: [0, 1, 2]});

      ls.on('exit', resolve);
    });

    isBusy = false;
    ls = null;
    console.log('watching for new changes')
  }, 200)
}

const options = { persistent: true }

console.log('watching for changes')
const watcher = watch('src/', options, watchHandler)

// windows
if (process.platform === "win32") {
  var rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  rl.on("SIGINT", function () {
    watcher.close();
    if (ls) ls.kill();
    process.emit("SIGINT");
  });
}

// Unix
process.on("SIGINT", function () {
  //graceful shutdown
  watcher.close();
  if (ls) ls.kill();
  process.exit();
});
```

**Comment by sheremet-va** [comment]
`--changed` is meant for CI or a quick run before pushing. You don't need this flag to rerun tests that you changed while `vitest watch` was running.

**Comment by o-alexandrov** [comment]
@sheremet-va 
> --changed is meant for CI or a quick run before pushing.

There are 2 whys about this statement. Why is `--changed` allowed for `vitest watch` then? And why should `vitest` have a different behavior to `jest`? (imho, there's no benefit in having a different behavior)

> You don't need this flag to rerun tests that you changed while vitest watch was running.

Is it irrational for the user to want to start tests for the changed tests only?
In other words, by `you don't need` would you like to state: the tests should always run for all existing tests
- don't you think it's the opposite? `You need` to run tests for the changed files when you run `vitest watch`; otherwise, in large codebases, you'd be forced after `vitest watch` to always cancel, so the `watch` then waits for the changes

**Comment by sheremet-va** [comment]
@o-alexandrov I can see your point. The behavior will change in the next version:

- If no affected test files are found and watch mode is enabled, it will wait for file changes
- If no affected test files are found and watch mode is disabled, it will exit with code 0
- If another file that didn't have any effect on tests previously is changed, Vitest will rerun all affected tests
