### ISSUE TITLE
Dependency semver vulnerable to Regular Expression Denial of Service

### ISSUE THREAD

**Issue by boy-incerta** [vitest-dev/vitest#3669]
### Describe the bug

`yarn audit` showed a vulnerability message in versions of the package semver before 7.5.2. Vitest is relating on that via vitest > @vitest/utils > concordance > semver

More info https://www.npmjs.com/advisories/1092310

### Reproduction

Any `npm/yarn install` of the current version of vitest in package. And then run `yarn/npm audit`

### System Info

```shell
System:
    OS: macOS 12.5.1
  Binaries:
    Node: 18.15.0
    Yarn: 1.22.19
    npm: 9.7.1 
    Watchman: 2023.02.13.00
  npmPackages:
    @vitejs/plugin-basic-ssl: 1.0.1 => 1.0.1
    @vitejs/plugin-react: 4.0.1 => 4.0.1
    vite: 4.3.9 => 4.3.9
    vitest: 0.30.1 => 0.30.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Duplicate of https://github.com/vitest-dev/vitest/issues/3668
