### ISSUE TITLE
SFC in-source testing

### ISSUE THREAD

**Issue by andredewaard** [vitest-dev/vitest#3672]
### Clear and concise description of the problem

would't be nice to test Vue sfc's in-source also? just like the Vitest in-source testing on normal javascript/typescript functions? 

### Suggested solution

Add an extra `<script lang="ts" test>` tag or something to write the unit tests about that specific component.

### Alternative

No idea how this could be implemented, But though that this could be nice to have.

### Additional context

```vue
<script setup lang="ts">
defineProps<{
  msg: string
}>()
</script>

<template>
  <p>{{ msg }}</p>
</template>

<script lang="ts" test>
import { mount } from '@vue/test-utils'
import { describe, it, expect } from 'vitest'

describe('test.vue', () => {
  it('renders properly', () => {
    const wrapper = mount(/* Somehow get the right component here */ HelloWorld, { props: { label: 'Hello Vitest' } })
    expect(wrapper.text()).toContain('Hello Vitest')
  })
})
</script>
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I don't think this is something to discuss in this repo. I would recommend opening an issue in `@vue/test-utils` project to discuss how this can be implemented (with a simple Vite plugin, for example). This will definitely be implemented as a core Vitest feature though.
