### ISSUE TITLE
It looks like this change may have caused the output in `@vitest/ui` to print ANSI escape codes.

### ISSUE THREAD

**Issue by wycats** [vitest-dev/vitest#3675]
I commented on #3582 but realized I should probably open a new issue:

It looks like something in #3582 may have caused the output in `@vitest/ui` to print ANSI escape codes.

![image](https://github.com/vitest-dev/vitest/assets/4/1796ee0b-b476-4bf8-a2ff-5ec6cb1de720)

I'm not sure what the root cause is, but I'm sure it started after I upgraded vitest this week.

_Originally posted by @wycats in https://github.com/vitest-dev/vitest/issues/3582#issuecomment-1605079741_

**Comment by silverwind** [comment]
Not sure if desirable, but you could use https://github.com/drudru/ansi_up to render ansi codes into HTML.

**Comment by wycats** [comment]
Isn't this a pretty serious bug? Is there something I'm doing that makes it happen to me, but not to others?

**Comment by so1ve** [comment]
👀 I'm going to work on this issue, but I'm not sure how to test @vitest/ui :(

**Comment by sheremet-va** [comment]
> 👀 I'm going to work on this issue, but I'm not sure how to test @vitest/ui :(

You can run `test/core` tests with `--ui` flag for example: 

```
cd test/core
pnpm test --ui
```
