### ISSUE TITLE
instanceof checks are failing after updating to the latest version

### ISSUE THREAD

**Issue by gajus** [vitest-dev/vitest#3676]
### Describe the bug

After updating to the latest version, our `instanceof` checks started to fail, e.g.

```ts
expect(
  services.paidProjectAnalytics.logFirstPaymentReceivedEvent,
).toHaveBeenCalledWith({
  paidProjectId,
  paidProjectTerms: expect.any(PaidProjectTerms),
});
```

While previously this was working, now it is failing with:

```diff
-     "paidProjectTerms": Any<PaidProjectTerms>,
+     "paidProjectTerms": PaidProjectTerms {
```

From the error it seems like they both share the same constructor.

However, checking the referenced object indeed confirms that the property is not an instance of `PaidProjectTerms`.

```ts
services.paidProjectAnalytics.logFirstPaymentReceivedEvent.mock
          .calls[0][0].paidProjectTerms instanceof PaidProjectTerms
// false
```

```ts
console.log(
  '>>>',
  services.paidProjectAnalytics.logFirstPaymentReceivedEvent.mock
    .calls[0][0].paidProjectTerms.constructor,
  services.paidProjectAnalytics.logFirstPaymentReceivedEvent.mock
    .calls[0][0].paidProjectTerms.constructor instanceof PaidProjectTerms,
  PaidProjectTerms,
  services.paidProjectAnalytics.logFirstPaymentReceivedEvent.mock
    .calls[0][0].paidProjectTerms.constructor === PaidProjectTerms,
);
// >>> [class PaidProjectTerms] false [class PaidProjectTerms] false
```

### Reproduction

I am unclear as to how to debug this further or how to reproduce it in isolation.

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.05 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.9.0 - ~/.nvm/versions/node/v19.9.0/bin/node
    npm: 9.6.3 - ~/.nvm/versions/node/v19.9.0/bin/npm
    Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 114.0.5735.133
    Edge: 114.0.1823.43
    Firefox: 113.0.2
    Safari: 16.3


  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.01 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.9.0 - ~/.nvm/versions/node/v19.9.0/bin/node
    npm: 9.6.3 - ~/.nvm/versions/node/v19.9.0/bin/npm
    Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 114.0.5735.133
    Edge: 114.0.1823.43
    Firefox: 113.0.2
    Safari: 16.3
  npmPackages:
    vitest: ^0.32.2 => 0.32.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by gajus** [comment]
This does have a smell of https://github.com/vitest-dev/vitest/issues/2824

```
devDependencies:
vitest 0.32.2
├─┬ @vitest/expect 0.32.2
│ └─┬ @vitest/spy 0.32.2
│   └── tinyspy 2.1.1
└─┬ @vitest/spy 0.32.2
  └── tinyspy 2.1.1
vitest-mock-extended 1.1.3
└─┬ vitest 0.32.2 peer
  ├─┬ @vitest/expect 0.32.2
  │ └─┬ @vitest/spy 0.32.2
  │   └── tinyspy 2.1.1
  └─┬ @vitest/spy 0.32.2
    └── tinyspy 2.1.1
```

CC @sheremet-va

**Comment by sheremet-va** [comment]
And why does it use different dependencies there? 🤷🏻

**Comment by gajus** [comment]
> And why does it use different dependencies there? 🤷🏻 Maybe deleting/reinstalling helps? Or lockfile is wrong?

Where do you see different dependencies?

As far as I can tell, they are all the same version.

**Comment by gajus** [comment]
I don't see how to repro this in StackBlitz.

**Comment by sheremet-va** [comment]
You don't have to use stackblitz

**Comment by gajus** [comment]
The last working version is v0.31.1 to v0.31.2

v0.31.1 is the last version where it is still working.

Tagging contributors to v0.31.2

@ghiscoding @PCreations @jcbhmr @fenghan34 @gtm-nayan @ghry5 @dammy001 @Dunqing @fooddilsn @rxliuli @btea @rluvaton @sheremet-va @AriPerkkio

Trying to look at what changed in the code between those versions.

**Comment by gajus** [comment]
It is definitely vitest related change. I removed all other changes from our PR and isolated just to dependency update, and it breaks all `instanceof` checks.

**Comment by sheremet-va** [comment]
Please, provide reproduction.

**Comment by sheremet-va** [comment]
Please, provide a reproduction.

**Comment by gajus** [comment]
Just for added context, this is a breaking change in monorepos where your directory structure is something like:

```
./apps/...
./packages/...
```
