### ISSUE TITLE
404 when trying to install vitest-environment-happydom

### ISSUE THREAD

**Issue by StefanBilliet** [vitest-dev/vitest#3679]
### Describe the bug

Whenever I try to install vitest-environment-happydom, I get a 404. I also can't seem to find that package on NPM.
<img width="871" alt="image" src="https://github.com/vitest-dev/vitest/assets/2368922/08ad1984-73e6-4111-9e42-fe3e42c775e0">

### Reproduction

npm install -D vitest-environment-happydom

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 636.50 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - /opt/homebrew/bin/node
    npm: 9.6.6 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Safari: 16.5.1
  npmPackages:
    @vitejs/plugin-react: 4.0.1 => 4.0.1
    vite: 4.3.9 => 4.3.9
    vitest: 0.32.2 => 0.32.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It's `happy-dom`

**Comment by StefanBilliet** [comment]
Happy-dom itself is already installed, but then I get this warning:
Can not find dependency 'vitest-environment-happydom'
and it suggests to try and install it.

**Comment by sheremet-va** [comment]
You incorrectly use `happydom` environment instead of `happy-dom`

**Comment by StefanBilliet** [comment]
Oh dear lord, I'm sorry, thank you 😅
