### ISSUE TITLE
Partial Mocking with `importActual` hanging the tests

### ISSUE THREAD

**Issue by ad1992** [vitest-dev/vitest#3680]
### Describe the bug

Hi I am trying to migrate Excalidraw tests currently using Jest to Vitest in https://github.com/excalidraw/excalidraw/pull/6713 and running to issues when mocking 

```
jest.mock("../../scene/export", () => ({
  __esmodule: true,
  ...jest.requireActual("../../scene/export"),
  exportToSvg: jest.fn(),
}));
```
For this equivalent `vite` I am using

```
vi.mock("../../scene/export", async (actual) => {
  const orig = await actual();
  //@ts-ignore
  return { __esmodule: true, ...orig, exportToSvg: vi.fn() };
});
```
It is getting mocked which I can confirm by adding `console.log` after the mock but as soon as I am using another module where this mocked function is being called, the tests just hang, I don't see any error so I have to again stop the tests are rerun and its the same result.
For reference this is the file where its being used - https://github.com/excalidraw/excalidraw/blob/master/src/packages/utils.ts#L1 and as you can see the first line imports are what is being mocked above

```
import {
  exportToCanvas as _exportToCanvas,
  exportToSvg as _exportToSvg,
} from "../scene/export";
```

Probably it could be related to https://github.com/vitest-dev/vitest/issues/546 so my guess is when I am using the mocked module in some other file, it just goes in to a recursion loop and hangs the tests. 

I have also tried `doMock`, `importActual`, `hoisted` and none of them work.
Any help would really be appreciated.
Thank you!

### Reproduction

its the same issue mentioned above and reproducible in my PR https://github.com/excalidraw/excalidraw/pull/6713

This is the file where I am trying to mock it https://github.com/excalidraw/excalidraw/blob/master/src/tests/packages/utils.test.ts#L6

Unfortunately the codesandbox integration with repo isn't working rn so I am not able to attach the link here, as soon as thats fixed, I can link here as well. 
If there is any info which you need please let me know

### System Info

```shell
#
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ad1992** [comment]
After debugging and trying out various approaches I am using spy + mockImplementation to achieve the same and thats working for now

**Comment by sheremet-va** [comment]
This was fixed some time ago (cannot find PR) and should work correctly in the latest Vitest version.
