### ISSUE TITLE
UI not working

### ISSUE THREAD

**Issue by oferitz** [vitest-dev/vitest#3686]
### Describe the bug

I Don't know why and haven't seen any other issues about it but since version 0.30.x the Vitest UI has stopped working for me. I Can see the tests running in the terminal but when trying to access `http://localhost:51204/__vitest__/` i get blank page. I tried different ports, and different browsers but it didn't help.

<img width="1139" alt="Screenshot 2023-06-28 at 0 00 06" src="https://github.com/vitest-dev/vitest/assets/1668687/a81b5436-1319-4ba5-a88a-506d0164512e">

<img width="1143" alt="Screenshot 2023-06-28 at 0 01 02" src="https://github.com/vitest-dev/vitest/assets/1668687/e7db688a-d908-44eb-b4e1-0bb2d834c9f2">

Tests are running in the console:
<img width="798" alt="Screenshot 2023-06-28 at 0 01 48" src="https://github.com/vitest-dev/vitest/assets/1668687/61147784-b31f-4628-a3eb-b3c148397c18">

### Reproduction

vitest --ui 

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 58.80 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.3 - /usr/local/bin/npm
    pnpm: 8.3.1 - ~/Library/pnpm/pnpm
    Watchman: 2023.05.01.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 114.0.5735.133
    Edge: 114.0.1823.55
    Safari: 16.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by oferitz** [comment]
Update: I found the root cause. in my `vite.config.ts` i have a custom server config:
```json
    server: {
      https: true,
      host: 'local.foo.bar',
      port: 3000
    }
 ```
 If i comment it out Vitest UI is working as expected.
 Here is the [reproduction link](https://stackblitz.com/edit/vitest-dev-vitest-gihat3?file=vite.config.ts)

**Comment by mnik01** [comment]
+1
but i don't have custom server in config

**Comment by sheremet-va** [comment]
> Can see the tests running in the terminal but when trying to access http://localhost:51204/__vitest__/ 

Why are you trying to access it on `http://localhost:51204/__vitest__/ ` instead of `https://local.foo.bar:3000/__vitest__`?

**Comment by oferitz** [comment]
`https://local.foo.bar:3000/__vitest__` takes you to the app itself. why should it work?
BTW as a reference we are using a project name [ladle](https://ladle.dev/) which is also Vite based and also starting a local server based on `vite.config` and with this project everything works as expected, so i wonder what they do different in the local server config.

**Comment by sheremet-va** [comment]
> why should it work?

I guess because it's a dev server? I am not sure how it's configured in your system, so I cannot really understand what is the expectation here. Should Vitest ignore the default server config and only use `--api`?

**Comment by oferitz** [comment]
Problem solved in Vite 5. this is no longer an issue.
