### ISSUE TITLE
Support customized junit report format 

### ISSUE THREAD

**Issue by InfiniteXyy** [vitest-dev/vitest#3691]
### Clear and concise description of the problem

Currently, when using `reporters: ["junit"]`, only `testsuites` is configurable, could we also make `classNameTemplate` and`titleTemplate` comfigurable, so that I can use custom seperator between classname and title, or remove classname totally.

https://github.com/vitest-dev/vitest/blob/f91da4849ffafd52b0969c21927873a87c47222a/packages/vitest/src/node/reporters/junit.ts#L167-L169

### Suggested solution

In `jest-junit` there are some configurable env values, like `JEST_JUNIT_CLASSNAME`

and we also have `VITEST_JUNIT_SUITE_NAME` in vitest, we could add more env variables to help config the junit output

### Additional context

The configratuion for `jest-junit` documentation:
https://github.com/jest-community/jest-junit#configuration

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
Instead of supporting environment variables we should open an API for providing reporter options. The coverage reporters already support this kind of API:

https://github.com/vitest-dev/vitest/blob/726a57e71c94b8b1a281e2079e3f2ce7d712d65a/docs/config/index.md?plain=1#L786-L800

This is something that 3rd party custom reporters could also utilize.

**Comment by InfiniteXyy** [comment]
I created a simple PR to solve my own usecase (to remove the filepath in className), would it be OK to merge that PR first?
https://github.com/vitest-dev/vitest/pull/3808
