### ISSUE TITLE
Vitests resolves node:test to test

### ISSUE THREAD

**Issue by nohehf** [vitest-dev/vitest#3693]
### Describe the bug

I have to use `node:test` along with vitest (as we use mocks outside of vitest testing, and vitest won't allow this).
However, when I `import { mock } from 'node:test';` vitest runner will throw the following error:
```
Error: Failed to load url test (resolved id: test). Does the file exist?
```

### Reproduction

Here is a minimal reproduction file:
```TS
import { describe, expect, it } from 'vitest';
import { mock } from 'node:test';

describe('mock issue reproduction', () => {
  it('should pass', () => {
    mock.fn(() => {});
    expect(true).toBe(true);
  });
});
```

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 49.69 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.volta/tools/image/node/20.2.0/bin/node
    Yarn: 3.4.1 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.6.6 - ~/.volta/tools/image/node/20.2.0/bin/npm
    pnpm: 6.26.1 - ~/.volta/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
```

For some reason envinfo won't give me the npm package versions so here you go:
```
"vitest": "^0.32.2"
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`node:test` is not supported by Vitest.

**Comment by nohehf** [comment]
> `node:test` is not supported by Vitest.

Why is that? How does it differ from any other node standard libraries (`node:url` works just fine for instance)
