### ISSUE TITLE
(docs): Users should be allowed to choose the theme(light or dark).

### ISSUE THREAD

**Issue by ryanmoyo** [vitest-dev/vitest#370]
### Clear and concise description of the problem

Currently the site's theme is chosen automatically based on the system, but inevitably some people don't want that.
For example, I prefer the Vitest document in light theme.

### Suggested solution

Just like sites like Windicss docs, give the user a button to toggle.
I can help if you need help.

### Additional context

I'm recently writing my graduation design component library, about unit testing I chose Vitest, I really like this library, it happens to be still in the learning phase, I want to synchronize the translation of this repository, I contacted @QC-L seniors to help sync the English docs, it just so happens that I saw in the document repository that this is also your todo content, please let me know if you would like that, thanks.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by patak-dev** [comment]
We are going to use the new VitePress theme for our docs once it is released, and this feature is included in it.
You can see a preview in https://staging.vuejs.org/ and in https://new-theme.vueuse.org/
