### ISSUE TITLE
Vite-node uses undeclared export `vite/types/hot`

### ISSUE THREAD

**Issue by just-boris** [vitest-dev/vitest#3704]
### Describe the bug

This line uses an undeclared export:

https://github.com/vitest-dev/vitest/blob/a96bc2247323159ac413a3ac0a1b27999a9efbfa/packages/vite-node/src/types.ts#L1

When running typescript with `"moduleResolution": "bundler"`, it fails compilation with undeclared exports.

The allowed vite exports can be found here: https://github.com/vitejs/vite/blob/126e93e6693474a038a5053b7cefb99295f21eb5/packages/vite/package.json#L21-L32

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-spzqkv?file=package.json,tsconfig.json&initialPath=__vitest__/

### System Info

```shell
n/a
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Maxim-Mazurok** [comment]
My temporary workaround using patch-package:
```patch
diff --git a/node_modules/vite-node/dist/server.d.ts b/node_modules/vite-node/dist/server.d.ts
index a21e596..80b6bd2 100644
--- a/node_modules/vite-node/dist/server.d.ts
+++ b/node_modules/vite-node/dist/server.d.ts
@@ -1,3 +1,4 @@
+//@ts-expect-error
 import { TransformResult, ViteDevServer } from 'vite';
 import { E as EncodedSourceMap } from './types.d-7442d07f.js';
 import { g as DebuggerOptions, D as DepsHandlingOptions, f as ViteNodeServerOptions, F as FetchResult, e as ViteNodeResolveId } from './types-e8623e9c.js';
diff --git a/node_modules/vite-node/dist/types-e8623e9c.d.ts b/node_modules/vite-node/dist/types-e8623e9c.d.ts
index dfe926f..ac99fe8 100644
--- a/node_modules/vite-node/dist/types-e8623e9c.d.ts
+++ b/node_modules/vite-node/dist/types-e8623e9c.d.ts
@@ -1,3 +1,4 @@
+//@ts-expect-error
 import { ViteHotContext } from 'vite/types/hot';
 import { E as EncodedSourceMap } from './types.d-7442d07f.js';
 
```
