### ISSUE TITLE
dynamic import of `conventional-changelog-angular` throws Promise `then` incompatible receiver object module

### ISSUE THREAD

**Issue by ghiscoding** [vitest-dev/vitest#3705]
### Describe the bug

Calling `await import('conventional-changelog-angular')` works fine in real world usage, that is in [Lerna-Lite](https://github.com/lerna-lite/lerna-lite/), but throws an error when running unit test with Vitest. I have Renovate running once a week on the repo, here's the failing PR [job](https://github.com/lerna-lite/lerna-lite/actions/runs/5194419667/jobs/9366058308)

To give a little bit of a background, I maintain [Lerna-Lite](https://github.com/lerna-lite/lerna-lite) (a fork of Lerna but rewritten as ESM) and the latest version of `conventional-changelog-angular` (which is a breaking version), that came out a few weeks ago, migrated from the Q library to pure Promise (see their v6 [changelog](https://github.com/conventional-changelog/conventional-changelog/releases/tag/conventional-changelog-angular-v6.0.0)). 

The code and library works fine in real world usage (I previewed a release in Lerna-Lite and it works fine and I added console logs to make sure of it), so it only fails in Vitest but not outside of it.

### Reproduction

Here's a Stackblitz repro:
https://stackblitz.com/edit/vitest-dev-vitest-conventional?file=test%2Fbasic.test.ts

Calling this simple test

```ts
test('conventional-changelog-angular', async () => {
  let config = await import('conventional-changelog-angular');
  expect(config).toBeTruthy();
});
```

will throw

> TypeError: Method Promise.prototype.then called on incompatible receiver [object Module]

or in some cases it throws this other but similar error

> TypeError: Promise.prototype.then called on incompatible Proxy

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz  
    Memory: 18.79 GB / 31.93 GB
  Binaries:
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD 
    npm: 7.0.11 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: 114.0.5735.199
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.58)
  npmPackages:
    @vitest/coverage-v8: ^0.32.2 => 0.32.2
    vitest: ^0.32.2 => 0.32.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
For your case, you can just disable [`deps.interopDefault`](https://vitest.dev/config/#deps-interopdefault). But I will look into it more

**Comment by ghiscoding** [comment]
Thanks for the quick hack, that did the trick and I can confirm that it works in this Lerna-Lite [PR 666](https://github.com/lerna-lite/lerna-lite/pull/666)... I wonder if I should merge it though since `666` is the number of the beast (demon) 👿 haha
