### ISSUE TITLE
Update docs workflow

### ISSUE THREAD

**Issue by sheremet-va** [vitest-dev/vitest#3707]
### Clear and concise description of the problem

We release new documentation before the feature is actually released. It would be a good idea to update documentation after the feature is in production.

At the same time, when developing new features it is a good idea to provide some level of documentation to maintainers and developers that rely on these new features.

### Suggested solution

- Update the workflow for publishing documentation for the main branch to publish it to `main.vitest.dev` (we need a subdomain from @antfu for this)
- Add a workflow to update regular documentation when the new release is happening (https://github.com/vitest-dev/vitest/issues/3706)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
https://main.vitest.dev/ set up. Which branch should vitest.dev point to?

**Comment by sheremet-va** [comment]
> [main.vitest.dev](https://main.vitest.dev/) set up. Which branch should `vitest.dev` points to?

Now that is an interesting question that I am not sure I can answer to. Maybe we should have a `stable` branch that automatically pulls commits from `main` when a release is happening? I guess we won't need a separate workflow to publish it then.

**Comment by antfu** [comment]
Ok, I created the `release` branch, and added the script to auto sync on release, d77f712f480be18407f5c089eee7bcb95bcd0964. And now https://vitest.dev should be derived by the `release` branch.

Does that fit what you expected?

**Comment by sheremet-va** [comment]
> Ok, I created the `release` branch, and added the script to auto sync on release, [d77f712](https://github.com/vitest-dev/vitest/commit/d77f712f480be18407f5c089eee7bcb95bcd0964). And now [vitest.dev](https://vitest.dev) should be derived by the `release` branch.
> 
> Does that fit what you expected?

Yes, thank you 👍🏻
