### ISSUE TITLE
Get the error useState is not defined in Nuxt 3

### ISSUE THREAD

**Issue by Sensey19** [vitest-dev/vitest#3708]
### Describe the bug

I have composable file **state.ts**:
```
const useCounter = () => useState('counter', () => 0);
export default useCounter;
```

and I use this **useCounter** in **index.vue**, so when I test this component I get the error: **useState is not defined**
**It's my index.test.ts:**
```
import { describe, expect, test, beforeEach } from 'vitest';
import { mount } from '@vue/test-utils';
import HomePage from '~/pages/index.vue';
import useCounter from '~/composables/states';

describe('Home page', () => {
let wrapper;
beforeEach(() => {
wrapper = mount(HomePage);
});

test('is a Vue instance', () => {
expect(wrapper.vm).toBeTruthy();
});

test('initializes with a default value of 0', () => {
const counter = useCounter();
expect(counter.value).toBe(0);
});
});
```

I've tried a lot of ways and nothing works. Could someone encounter this issue while testing?

### Reproduction

https://stackblitz.com/edit/nuxt-starter-hwb5wz?file=tests%2Funit%2Fpages%2Findex.test.ts
**run test:** npm run test

### System Info
#

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Reproduction is something that I can just run. I cannot run your blob of text

**Comment by sheremet-va** [comment]
I don't see you defining `useState` globally anywhere. Vitest is not Nuxt and it doesn't support this sort of thing out of the box. Please, follow [nuxt-vitest](https://github.com/danielroe/nuxt-vitest) development.
