### ISSUE TITLE
Per-directory coverage thresholds

### ISSUE THREAD

**Issue by lcswillems** [vitest-dev/vitest#3709]
### Clear and concise description of the problem

I cannot set coverage thresholds globally and also for a specific directory.

### Suggested solution

Something similar to coverageThreshold of Jest: https://jestjs.io/docs/configuration#coveragethreshold-object

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
Now that `@vitest/coverage-c8` is being deprecated, we can implement this for both coverage providers. I think it would be breaking change though, as option structure would change.

**Comment by adriengibrat** [comment]
> I think it would be breaking change though, as option structure would change.

does not have to introduce Breaking change, "coverageThreshold" could be an alternative property like it is implemented in jest.

**Comment by AriPerkkio** [comment]
The current option format would be replaced with new one.

These options:

```js
{
  test: {
    coverage: {
      branches: 100,
      lines: 100,
      statements: 100,
      functions: 100,
    }
  }
}
```

would be replaced with these ones:

```js
{
  test: {
    coverage: {
      threshold: {
        global {
          branches: 100,
          lines: 100,
          statements: 100,
          functions: 100,
        },
        "./src/utils/**": {
          lines: 80,
        }
      }
    }
  }
}
```

But sure, it doesn't have to be a breaking change at first. The `coverage['lines'|'branches'|'statements'|'functions']` could be used as fallback for `coverage.threshold.global` before they are completely removed from configuration API.
