### ISSUE TITLE
CLI output flips actual and expected in diff

### ISSUE THREAD

**Issue by aklinker1** [vitest-dev/vitest#3717]
### Describe the bug

For the following test, the actual value is printed as the `- Expected` green text, when it should be printed as the `+ Received` red text.

```ts
import { expect, test } from "vitest";

const getText = () => "actual text";

test("demo", () => {
  const expected = "expected text";
  const actual = getText();

  expect(actual).toBe(expected);
});
```

![Screenshot 2023-07-02 at 3 06 55 PM](https://github.com/vitest-dev/vitest/assets/10101283/37ec4096-12c4-468e-89bf-f82685a6365d)

After some debugging, it appear to have been broken in `v0.32.1` with the new text diff that is used, likely introduced in https://github.com/vitest-dev/vitest/pull/3582

<details>
<summary>Version differences</summary>

![Screenshot 2023-07-02 at 3 18 19 PM](https://github.com/vitest-dev/vitest/assets/10101283/c0c1cf79-7810-4592-84b7-b41c3d9cd17e)

![Screenshot 2023-07-02 at 3 17 37 PM](https://github.com/vitest-dev/vitest/assets/10101283/c3b32f6d-991e-455f-82aa-fdfbff9e9d42)

</details>

### Reproduction

Here's the project with the above test in it. [repro.zip](https://github.com/vitest-dev/vitest/files/11931278/Archive.zip)

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 258.06 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.asdf/installs/nodejs/lts/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/lts/.npm/bin/yarn
    npm: 8.15.0 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 7.15.0 - ~/.asdf/installs/nodejs/lts/.npm/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    vitest: ^0.32.2 => 0.32.2 
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It's fixed, but the fix is not released yet

**Comment by sheremet-va** [comment]
It's fixed, but the fix is not released yet
