### ISSUE TITLE
Mock function `vi.fn` loses implementation when called inside a function with he config mockReset: true,

### ISSUE THREAD

**Issue by joseph-hanvy-sophos** [vitest-dev/vitest#3724]
### Describe the bug

When a mocked function is called inside another function it loses the implementation and just returns `undefined` if the config option `mockReset: true,` is configured.

### Reproduction

Here's a link: https://codesandbox.io/p/sandbox/bold-cdn-72p89j?file=%2Fvite.config.ts%3A13%2C4

The test:
```
import { assert, expect, test, vi } from "vitest";
import { inFunction } from "./basic";

vi.mock("uuid", () => ({ v4: vi.fn().mockImplementation(() => "uuid-v4") }));

test("mock use in function", () => {
  inFunction();
});

```
The implementation:
```
import { v4 } from "uuid";

console.log("in root", v4());

export function inFunction() {
    const result = v4();
    console.log("in function", result);
    return result;
}
```
With:
```
export default defineConfig({
  test: {
    mockReset: true,
  },
});
```
You get the output:
```
stdout | unknown test
in root uuid-v4

stdout | test/basic.test.ts > mock use in function
in function undefined
```
Remove `mockReset: true` and you get the expected:
```
stdout | unknown test
in root uuid-v4

stdout | test/basic.test.ts > mock use in function
in function uuid-v4
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 4.39 GB / 31.73 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1848.0), Chromium (114.0.1823.67)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-react: ^4.0.0 => 4.0.0
    @vitest/coverage-v8: ^0.32.2 => 0.32.2
    vite: ^4.0.0 => 4.3.9
    vitest: ^0.32.3 => 0.32.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
The Vitest version is too old in your reproduction (check package-lock). Please create a reproduction with the latest version

**Comment by joseph-hanvy-sophos** [comment]
@sheremet-va  no problem, here's it reproduced with the linked StackBlitz with the lock showing 0.32.4:

https://stackblitz.com/edit/vitest-dev-vitest-5zp5zy?file=vite.config.ts

**Comment by sheremet-va** [comment]
> @sheremet-va no problem, here's it reproduced with the linked StackBlitz with the lock showing 0.32.4:
> 
> [stackblitz.com/edit/vitest-dev-vitest-5zp5zy?file=vite.config.ts](https://stackblitz.com/edit/vitest-dev-vitest-5zp5zy?file=vite.config.ts)

reset works as expected: https://vitest.dev/api/mock.html#mockreset The implementation is reset to the original one, which is no implementation in your case because you did not provide it to `vi.fn()`
