### ISSUE TITLE
Default include is being ignored when coverage is provided

### ISSUE THREAD

**Issue by posva** [vitest-dev/vitest#3727]
### Describe the bug

- run `vitest --coverage`
- See that a module that isn't a test file is being scanned for tests and thus errors

Workaround: add an explicit include to `test`.

This was working on version 0.31.1

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-w6dj3h?file=vite.config.ts

### System Info

```shell
Stackblitz
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
The default include was changed in 0.32.0 (every file inside `__test__` is a test now). You can say your opinion there: https://github.com/vitest-dev/vitest/issues/3530
