### ISSUE TITLE
Functions with parameters cant find import.meta.env

### ISSUE THREAD

**Issue by Omnicpie** [vitest-dev/vitest#3735]
### Describe the bug

When testing a function that has parameters and also utilises import.meta.env, the test will always fail as `import.meta.env` is undefined. This problem does not exist for functions that take no arguments and they resolve `import.meta.env` to an object which can be edited via `vi.stubEnv`. 

### Reproduction

This problem is very easy to reproduce. All that is needed is two functions, one take takes an argument and returns an object with the argument and some `import.meta.env` value, and one that simply has the `import.meta.env` value. This is the simple example I use to demonstrate the issue: 

```javascript
export const getDefaults = () => ({ process: '', name: 'some name', mode: import.meta.env.MODE });

export const getDefaultsWithParam = (process: string) => ({
  process,
  name: 'some name',
  mode: import.meta.env.MODE,
});
```

This needs to be tested. Create a file that covers both these functions and for each of them test that when the function is called, it returns an object that contains the correct values. For each of them have 1 attempt that does NOT stub the environment variable and one that does. 

A full working example of this can be found on [StackBlitz](https://stackblitz.com/edit/vitest-dev-vitest-fccwec?file=test%2Fexample.test.ts)

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 462.12 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.11.0 - ~/.nvm/versions/node/v18.11.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.11.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.11.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Edge: 114.0.1823.51
    Firefox: 114.0.2
    Firefox Developer Edition: 100.0
    Safari: 16.5
  npmPackages:
    @vitejs/plugin-react: ^3.1.0 => 3.1.0 
    @vitest/coverage-c8: ^0.24.5 => 0.24.5 
    @vitest/coverage-v8: ^0.32.0 => 0.32.0 
    @vitest/ui: latest => 0.32.0 
    vite: ^4.2.1 => 4.2.2 
    vitest: ^0.32.0 => 0.32.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest replaces all `import.meta.env` calls with `process.env`, so it fails in your case because you have your local process variable.

We should probably replace it with `__vite_ssr_import_meta__.env` that references a proxy to `process.env`, but has certain rules for boolean values (to fix a separate issue with `import.meta.env.DEV` being boolean in dev, but string in test).
