### ISSUE TITLE
Test never ends when user call non existing function on Assertion

### ISSUE THREAD

**Issue by 11joselu** [vitest-dev/vitest#374]
### Describe the bug

Hello :)

I start migrating a React application who use `@testing-library/react` using the next `vite.config.js`

```javascript
/// <reference types="vitest" />

import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  test: {
    global: true,
    environment: 'jsdom',
    deps: {
      inline: ['@testing-library/user-event'],
    },
  },
});

```

In my test code I was using `.toBeVisble()` function this caused to Vitest to never finish his execution (inside stackblitz throws an exception).

Then if you remove one of the tests case, then vitest throws an error telling that function does not exist

### Reproduction

https://stackblitz.com/edit/node-z4bqpv?devtoolsheight=33&file=test/errorRecursive.test.ts

### System Info

```shell
System:
    OS: Linux 5.13 Linux Mint 20.2 (Uma)
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 15.83 GB / 30.78 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node
    npm: 7.11.2 - ~/.nvm/versions/node/v16.1.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0.1
  npmPackages:
    @vitejs/plugin-react: ^1.0.7 => 1.1.3 
    vite: ^2.7.2 => 2.7.10 
    vitest: ^0.0.124 => 0.0.124
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JoostK** [comment]
Ah, this might explain my observation when updating from `0.0.109` to `0.0.118`. With 109 my tests completed as expected but had failures for the usage of `.rejects`/`.resolves` expectations, whereas in 118 the runner stalls at some moment and never completes. Just tested with `0.0.124` and it still stalls (although I believe that `.rejects`/`.resolves`) API was recently added.

**Comment by JoostK** [comment]
After some more investigation, this seems to reproduce for me if **at least two** tests fail with a `TypeError` because some `expect` API is not available (but any ordinary `TypeError` should suffice, I reckon).

Changing the following logic:

https://github.com/vitest-dev/vitest/blob/4b26368502718ed059adc635cbb7ea1cc70d4ca7/packages/vitest/src/runtime/error.ts#L29-L31

as

```patch
+ const clone = {};
  Object.keys(val).forEach((key) => { 
-   var[key] = serializeError(val[key], seen) 
+   clone[key] = serializeError(val[key], seen) 
 })
+ var = clone 
```

prevents the test from stalling. I haven't yet figured out why this happens, it seems as if the prototype of the object or perhaps some non-enumerable properties wreak havoc when the object is eventually passed over the `MessagePort`. I am particularly surprised by the fact that it requires two tests to fail, not just one 🤷‍♂️

**Comment by antfu** [comment]
The fix makes sense, PR welcome

**Comment by 11joselu** [comment]
I was debugging it and I see found that inside `packs` are duplicated items.

https://github.com/vitest-dev/vitest/blob/9193638de9e4df7884e264dfa182bbe9de19667d/packages/vitest/src/runtime/run.ts#L39

That's means, sometimes (I see it only with `TypeError` or `Error`objects using reproduction example) where there are duplicated items with circular references.

![Screenshot from 2022-01-02 00-22-26](https://user-images.githubusercontent.com/8685132/147862484-c1f4f625-1efa-4da2-9f8b-638c57dd572d.png)

@antfu Maybe we can cleanup `tasks` **array removing duplication before send it**?

Something like:

```typescript
const tmp: string[] = []

const _packs = packs.filter((v) => {
  if (!tmp.includes(v.toString())) {
    tmp.push(v.toString())
    return v
  }

  return false
})

console.log({_packs, packs})

const p = rpc().onTaskUpdate(_packs)
```

Orders matters too?

**Comment by JoostK** [comment]
@11joselu Ah, interesting! Does pruning the duplicates also fix the problem?

I just opened #403 which ended up being a bit more convoluted than my initial experiment, which was needed to get all tests green and to cover certain edge cases. It still feels like a non-root-cause fix so I'd be interested to learn about an issue that could be the actual root cause.

**Comment by antfu** [comment]
> I was debugging it and I see found that inside packs are duplicated items.

Emm interesting. I think we should find the root cause of that duplication instead of doing the dedupe.

**Comment by MatthewZito** [comment]
> > I was debugging it and I see found that inside packs are duplicated items.
> 
> Emm interesting. I think we should find the root cause of that duplication instead of doing the dedupe.

I was curious about this, too. I see that `runTest` is calling `updateTask` twice - [once](https://github.com/vitest-dev/vitest/blob/758c8ba6e546c99ea153350f72b15159d234da64/packages/vitest/src/runtime/run.ts#L54) after setting the task result state to 'run', and a [second](https://github.com/vitest-dev/vitest/blob/758c8ba6e546c99ea153350f72b15159d234da64/packages/vitest/src/runtime/run.ts#L111) time after updating the task result state. `updateTask` adds the task id / result tuple into `packs`, and it ends up getting duplicated.

Seems like `updateTasks` should first check for an existing task id and update the tuple before adding. I'll open a PR :)

**Comment by 11joselu** [comment]
> @11joselu Ah, interesting! Does pruning the duplicates also fix the problem?
> 
> I just opened #403 which ended up being a bit more convoluted than my initial experiment, which was needed to get all tests green and to cover certain edge cases. It still feels like a non-root-cause fix so I'd be interested to learn about an issue that could be the actual root cause.

Yes, pruning solves the problem.

Maybe @MatthewZito solution may work because fix the root problem

**Comment by 11joselu** [comment]
Solved by https://github.com/vitest-dev/vitest/pull/406

**Comment by JoostK** [comment]
Some more data points: I was trying to manually go through a serialization cycle ([here](https://github.com/vitest-dev/vitest/blob/f7bdb905143946ad9a64d760d343248e23dfff1f/packages/vitest/src/node/pool.ts#L142)) for the message when it contains the duplicate `Task.result` data:

```js
require('v8').deserialize(require('v8').serialize(v.a[0]))
```

this errors out with the following:

```
node:v8:345 Uncaught Error: Unable to deserialize cloned data.
```

That is likely what causes the message to never be received, without any observable error. I added a `messageerror` event listener:

```ts
  port.on('messageerror', (error) => {
    console.error(error)
    throw error
  })
```

And that does indeed surface the same error.

I suspect that `Error`/`TypeError`/... have some special serialization behavior that introduces an issue when objects are deduplicated in the serialization output ([reference](https://github.com/v8/v8/blob/17a99fec258bcc07ea9fc5e4fabcce259751db03/src/objects/value-serializer.cc#L516-L522)) . That seems like a v8 bug to me, but I couldn't spot exactly where it occurs when browsing the code on GH.
