### ISSUE TITLE
Mocking doesn't work (continuing the discussion from #1988)

### ISSUE THREAD

**Issue by f1am3d** [vitest-dev/vitest#3748]
Mocking doesn't work.

> But I have a grip on the situation again and am gonna try some more stuff.

You should be able to, if you have at the top:

```ts
vi.mock('node:fs', () => {
  return {
    existsSync: vi.fn(),
  };
});
```

_Originally posted by @sheremet-va in https://github.com/vitest-dev/vitest/issues/1988#issuecomment-1238056239_

Actual code:
```ts
vi.mock('node:fs', async () => {
  const actual = await vi.importActual('node:fs');

  return {
    ...actual,
    existsSync: vi.fn().mockReturnValue('test'),
  };
});

it('should mock fs module', async () => {
  expect(fs.existsSync()).toEqual('test');
});
```

ERROR:
```
 FAIL  |server| src/controllers/employees.test.ts > should mock fs module
AssertionError: expected false to deeply equal 'test'

- Expected:
false

+ Received:
"test"
```

**Comment by ghiscoding** [comment]
@f1am3d you should probably rename the title if you want more view, because at it is now it looks like spam 😁

**Comment by VSymonenko** [comment]
I think that depends on the module system. Try to use named import in your tests:

```diff
- import fs from 'node:fs'
+ import * as fs from 'node:fs'
```

**Comment by sheremet-va** [comment]
Previously `node:fs` and `fs` weren't interchangeable, this was fixed in Vitest 2. There is also an FS mocking guide now: https://vitest.dev/guide/mocking.html#file-system
