### ISSUE TITLE
Wrong coverage report

### ISSUE THREAD

**Issue by Nisgrak** [vitest-dev/vitest#375]
### Describe the bug

The coverage doesn't make sense with the actual code

![image](https://user-images.githubusercontent.com/19597708/147768540-917662df-dbfa-477b-ae63-44b8a5b9f6b9.png)
![image](https://user-images.githubusercontent.com/19597708/147768572-9e216122-4f53-418a-8481-22623c9b4b9e.png)
![image](https://user-images.githubusercontent.com/19597708/147768711-0d0907c5-b569-4b5a-a79d-d8313b2fdd69.png)

### Reproduction

Github repo: https://github.com/Nisgrak/vitest-coverage-bug

Execute `pnpm i && pnpm test:unit`

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
    Memory: 1.24 GB / 24.56 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.volta/tools/image/node/16.13.1/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.1.2 - ~/.volta/tools/image/node/16.13.1/bin/npm
  Browsers:
    Firefox: 95.0.1
  npmPackages:
    vite: ^2.7.2 => 2.7.10 
    vitest: ^0.0.124 => 0.0.124
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by bompus** [comment]
I'm seeing the same issue. Running via c8 instead of using --coverage displays the correct uncovered line numbers.

Related #371

**Comment by Nisgrak** [comment]
The html report is good with `c8 vitest`, the text shows the line + 1 (its the 149 but shows the 150), so yes, isn't that bad

Upper `vitest --coverage`, lower `c8 vitest`
![image](https://user-images.githubusercontent.com/19597708/147875157-7e6ea5c9-ac96-43e9-b364-b8a8b58f9189.png)
![image](https://user-images.githubusercontent.com/19597708/147875165-d4f90d8a-ef1c-4bab-ae51-a466e914e8b3.png)
![image](https://user-images.githubusercontent.com/19597708/147875168-002484d0-07e6-433d-b4f1-871bc9d5a983.png)
![image](https://user-images.githubusercontent.com/19597708/147875173-40ac4529-9183-49ee-9aa4-71248fba453d.png)
![image](https://user-images.githubusercontent.com/19597708/147875176-debe10a9-e452-4db4-b039-25dde4981c51.png)

**Comment by Demivan** [comment]
@Nisgrak, try it now with Vitest v0.2.0

**Comment by Nisgrak** [comment]
Not very accurated. It improved but i think continues wrong. 

I update the repo example so can try!

![image](https://user-images.githubusercontent.com/19597708/150680824-6883d5ec-160f-48a4-8de9-f23b0aeef325.png)
![image](https://user-images.githubusercontent.com/19597708/150680829-3707f6fc-4c90-4be8-a185-8e0bc041f7c4.png)

**Comment by Demivan** [comment]
@antfu When `vite-node` package was moved out, `visitedFilesMap` updates where removed. So now source-map data it missing - `visitedFilesMap` is always empty.

**Comment by cexbrayat** [comment]
I suppose this is the same root cause that @Demivan is mentioning, but Vue files aren't popping up in the report.
See with the provided example running in Stackblitz: https://stackblitz.com/edit/vitest-dev-vitest-ilb2yu?file=vitest.config.ts when you run `npm run coverage` with the `all` option:

```
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
```

Adding a new TS file in `components` with no test does show up in the coverage though, so it looks like it is specific to Vue files
