### ISSUE TITLE
Mismatched JSDOM version?

### ISSUE THREAD

**Issue by AnatoleLucet** [vitest-dev/vitest#3756]
### Describe the bug

I've been struggling to load a `<script />` with `defer` enabled. Turns out this was a bug in JSDOM which has been fixed in the latest version by this PR https://github.com/jsdom/jsdom/pull/3489.
But I'm still facing the issue when trying to load a script with `defer` using the global JSDOM instance provided by Vitest.
If I instantiate JDOM manually and do the same operations on this instance, the script loads.

### Reproduction

https://stackblitz.com/edit/node-zfcpbe?file=test%2Fbasic.test.ts,package.json,vitest.config.ts,package-lock.json

see in `basic.test.ts` how the `setTimeout` logs `object` for the first test, and `undefined` for the other.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.3 - /usr/local/bin/pnpm
  npmPackages:
    vite: ^4.4.2 => 4.4.2 
    vitest: ^0.33.0 => 0.33.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
The injected `script` and the test have different global contexts. This is just how Vitest works by default.

You can use `pool: 'vmForks'` or `pool: 'vmThreads'` to change that.
