### ISSUE TITLE
Broken Types: Argument of type 'UserProjectConfigExport' is not assignable to parameter of type 'UserWorkspaceConfig | Promise<UserWorkspaceConfig>'

### ISSUE THREAD

**Issue by jviall** [vitest-dev/vitest#3759]
### Describe the bug

I've been using a workspace setup, following the docs to create a workspace at the root, and a shared base config that my individual projects can import and merge with any overrides. However, since upgrading my `vitest`/`vite` versions, the types are broken. 

```
Argument of type 'UserProjectConfigExport' is not assignable to parameter of type 'UserWorkspaceConfig | Promise<UserWorkspaceConfig>'
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-uk4kgh?file=vite.config.ts

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 12.78 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/Library/Caches/fnm_multishells/22781_1678232715369/bin/node
    npm: 9.5.1 - ~/Library/Caches/fnm_multishells/22781_1678232715369/bin/npm
    pnpm: 8.6.7 - ~/Library/Caches/fnm_multishells/22781_1678232715369/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    @vitest/coverage-v8: 0.33.0 => 0.33.0
    @vitest/ui: 0.33.0 => 0.33.0
    vite: 4.4.3 => 4.4.3
    vitest: 0.33.0 => 0.33.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I don't see how this is related to Vitest?

**Comment by jviall** [comment]
> I don't see how this is related to Vitest?

what else would it be related to?

**Comment by sheremet-va** [comment]
> > I don't see how this is related to Vitest?
> 
> what else would it be related to?

all functions are imported from vite, not vitest

**Comment by jviall** [comment]
Looks like there's an issue with an open PR to solve this with Vite: https://github.com/vitejs/vite/pull/13792#pullrequestreview-1526308900
