### ISSUE TITLE
The import of modules in node_modules is replaced by the alias of vitest.config.ts

### ISSUE THREAD

**Issue by asnow-c** [vitest-dev/vitest#3761]
### Describe the bug

When I install a module into a project using `pnpm link`, the alias configuration of vitest.config replaces the url of the import statement in that module

### Reproduction

1. **Create two packages**

    ```shell
    mkdir ~/pkga
    mkdir ~/proj
    ```

    **pkga directory:**

    ~/pkga/package.json:

    ```json
    {
        "name": "pkga",
        "type": "module",
        "imports": {
            "#rt/*": "./out/*"
        }
    }
    ```

    ~/pkga/index.js:

    ```javascript
    import { Cat } from "#rt/cat.js"; //imports have been defined in the package.json
    console.log(Cat);
    export { Cat };
    ```

    ~/pkga/out/cat.js

    ```javascript
    export class Cat {}
    ```

    **proj directory:**

    ~/proj/package.json:

    ```json
    {
        "name": "proj",
        "type": "module",
        "devDependencies": {
            "vitest": "^0.33.0"
        }
    }
    ```

    ~/proj/vitest.config.ts:

    ```typescript
    import { defineConfig } from "vitest/config";
    export default defineConfig({
        test: {
            alias: {
                "#rt/": __dirname + "/src/", //Pay attention here
            },
        },
    });
    ```

2. **Link modules using [pnpm link](https://pnpm.io/cli/link)**

```shell
cd ~/pkga
pnpm link -g

cd ~/proj
pnpm install
pnpm link pkga -g
```

3. **Add a test file `~/proj/mod.test.ts:`**

```typescript
import { Cat } from "pkga";
import { expect, test } from "vitest";
test("mod test", function () {
    expect(Cat).not.toBeUndefined();
});
```

4. **Execute a command `pnpm vitest`**

#### Expected

Pass the test

#### Actual

```
Error: Failed to load url /src/cat.js (resolved id: /src/cat.js) in /Users/asnow/pkga/index.js. Does the file exist?
```

**The test passed when I copied pkga directly to `~/proj/node_modules` instead of using `pnpm link`**

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 15.09 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.4.0 - ~/Library/pnpm/node
    npm: 9.7.2 - ~/Library/pnpm/npm
    pnpm: 8.6.5 - ~/Library/pnpm/pnpm
  Browsers:
    Edge: 114.0.1823.79
    Safari: 16.3
  npmPackages:
    vitest: ^0.33.0 => 0.33.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
If the module is not external, an alias is preferred. To externalize a module, use `deps.external` with a regexp. Or use `deps.moduleDirectories` to specify where your packages are located.

**Comment by asnow-c** [comment]
> If the module is not external, an alias is preferred. To externalize a module, use `deps.external` with a regexp. Or use `deps.moduleDirectories` to specify where your packages are located.

In the example above, pkga should be the external module. It's soft-linked to node_modules by pnpm, and its real directory is `~/pkga`.
But I modified `vitest.config.ts`:
```typescript
import { defineConfig } from "vitest/config";
export default defineConfig({
    test: {
        alias: {
            "#rt/": __dirname + "/src/",
        },
        deps: {
            external: ["**/node_modules/**", "**/pkga/**"],
        },
    },
});

```

It still says that the module cannot be loaded.
I don't know why

**Comment by sheremet-va** [comment]
External doesn't support glob pattern. I specifically said regexp in my message. It will be checked against the full path, not the package name.

**Comment by asnow-c** [comment]
I just looked at the vitest documentation and I thought I could use glob pattern
<img width="1069" alt="image" src="https://github.com/vitest-dev/vitest/assets/73151139/c8dcb7ad-113b-47b2-99c8-ecfa784dce72">


Thank you very much. That issues is solved.
