### ISSUE TITLE
toEqual output is truncated

### ISSUE THREAD

**Issue by PupoSDC** [vitest-dev/vitest#3762]
### Describe the bug

This is a follow up to https://github.com/vitest-dev/vitest/issues/2448 Since I simply don't understand the solution being proposed. 

> When running a test to check the equality of two objects, the output is truncated if there are more than 2 properties.
> 
> I.e. the output looks like this:
> 
> ```
> AssertionError: expected { hello: 'world', …(3) } to deeply equal { hello: 'world', …(2) }
> ```
> 
> Which means it's not possible to establish what was wrong.
> 
> I wondered if setting [this](https://github.com/vercel/satori/pull/47/files) might help but it doesn't seem to make a difference here.

Here is the output i see on my console:

<img width="1113" alt="image" src="https://github.com/vitest-dev/vitest/assets/9625304/137a43df-fac1-4f0d-88a1-fed604b50d11">

Here is the output from Jest, which is more or less what I was expecting to see:

<img width="696" alt="image" src="https://github.com/vitest-dev/vitest/assets/9625304/912067c0-deec-42ef-93e0-b4ee71d2e712">

How can i make it so that the full diff between the provided and expected value is shown on the console?

### Reproduction

In [this](https://github.com/rcoundon/vitest-axios) repo there's a test called it demonstrates toEqual output is truncated in ApiCaller.test.ts that shows the problem.

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 3.56 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/Library/Caches/fnm_multishells/54988_1688995060872/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/54988_1688995060872/bin/yarn
    npm: 9.5.1 - ~/Library/Caches/fnm_multishells/54988_1688995060872/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Linked reproduction prints the output

![Screenshot 2023-07-12 at 10 17 41](https://github.com/vitest-dev/vitest/assets/16173870/621c4c10-9c8f-4488-b430-1b0741e0d7d7)

**Comment by PupoSDC** [comment]
Thank you for your reply. Our setup was missing the following config on `vite.config.js`:

```ts
export default defineConfig(() => {
  return test {
      outputTruncateLength: 10000,
      outputDiffLines: 100000,
  }
}
```

It appears that by default no diff is generated. 

Thank you!

**Comment by PupoSDC** [comment]
So what Options should I set? These 2 seem to work on `vitest: 0.33.0`. 

Which is supposed to be the correct set of options for this version? 
And where can i find the docs for them?

**Comment by sheremet-va** [comment]
> So what Options should I set? These 2 seem to work on `vitest: 0.33.0`.
> 
> Which is supposed to be the correct set of options for this version? And where can i find the docs for them?

There are no options for diff. It should just work, and it works without any options in linked reproduction.

**Comment by Mouvedia** [comment]
![Capture d’écran 2023-07-13 à 12 14 49](https://github.com/vitest-dev/vitest/assets/208817/d2084e66-8cef-4113-9879-dec1faf8676c)

**Comment by PupoSDC** [comment]
@Mouvedia Check if you are running the latest vite (`0.33` at this date) that was the issue for me. 
On this version the settings flag `outputTruncateLength`, `outputDiffLines` are indeed not needed.

**Comment by Mouvedia** [comment]
I am using version 0.33.0.
