### ISSUE TITLE
When using vi.doMock from vitest, I found that imports cannot be called ahead of time in JavaScript files,

### ISSUE THREAD

**Issue by lrsoy** [vitest-dev/vitest#3763]
### Describe the bug

When using vi.doMock in vitest, I found that the import cannot be called ahead of time in the JavaScript file, causing vi.doMock to fail. Normally, I can use vi.doMock to mock a function or module, but calling it before the import statement doesn't seem to have an effect. I'd like to know how to fix this so that I can use vi.doMock correctly in JavaScript files.，

But I don't have any problems in ts, it can run completely and get the correct result

In the screenshot below, I took the sample code of vi.doMock from the vitest document, and he couldn’t run it in the end. Although ts is the most commonly used, this problem will occur when I use js when I’m learning.

Forgive me for not being able to post the code and only show it by screenshots, so I hope that you can try it yourself when you see this problem, this problem does exist

### my development environment
pnpm 8.4.0
vitest  0.33.0
node  16.x

### Reproduction

![99e00d7e636cd1d7d109cae7e850768](https://github.com/vitest-dev/vitest/assets/69709362/4288bd04-d6b7-4b14-b580-04d49a10032e)

### System Info

```shell
FAIL  increment.spec.js > 官方文档案例vi.doMock > importing the next module imports mocked one
AssertionError: expected 100 to be 101 // Object.is equality

- Expected
+ Received

- 101
+ 100

 ❯ increment.spec.js:24:32


⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  1 failed (1)
   Start at  18:38:39
   Duration  398ms (transform 49ms, setup 0ms, collect 36ms, tests 12ms, environment 0ms, prepare 147ms)


 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is not a reproduction, it is a screenshot

**Comment by sheremet-va** [comment]
But even in the screenshot, you can see that `vi.doMock` works correctly. If it didn't, you would get `2` and not `100`. The only bug here is the mocked implementation - it should use `++` at the start and not after `mockedIncrement`.

**Comment by lrsoy** [comment]
Sorry for my mistake, I put the specific code on stackblitz, you can see how the specific implementation is, I wrote two versions, one ts and one js, you can distinguish them by distinguishing the folder name , but it is true that ts can run through, but js can't run through, I really don't understand why this is

link address： https://stackblitz.com/edit/vitest-dev-vitest-7kveii?file=test%2Fincrement-js%2Fincrement.spec.js&initialPath=__vitest__/

**Comment by lrsoy** [comment]
> 但即使在屏幕截图中，您也可以看到它`vi.doMock`工作正常。如果没有，你会得到`2`而不是`100`。这里唯一的错误是模拟实现 - 它应该`++`在开始时使用，而不是在之后使用`mockedIncrement`。

**Comment by sheremet-va** [comment]
Vitest automatically removes unused imports in TypeScript files, so your example works correctly in ts files. 

Modules are cached. `vi.doMock` clears the cache for specified modules, but doesn't clear the cache for modules that import it, you need to do it yourself by calling `vi.resetModules`:

```ts
beforeEach(() => {
  vi.resetModules()
})
```

**Comment by lrsoy** [comment]
Thanks

**Comment by lrsoy** [comment]
thanks, this is very helpful for me
