### ISSUE TITLE
playwright 1.36 issue

### ISSUE THREAD

**Issue by dk1a** [vitest-dev/vitest#3764]
### Describe the bug

when using the new `playwright@1.36.0` with vitest, I get `TypeError: this.customTesters is not iterable`
with `1.35.1` the same test passes

### Reproduction

https://github.com/dk1a/vitest-playwright-example

### System Info

```shell
System:
    OS: Linux 5.19 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (5) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 2.57 GB / 7.75 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 8.6.7 - ~/.local/share/pnpm/pnpm
  Browsers:
    Brave Browser: 108.1.46.144
    Chrome: 114.0.5735.198
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Fahl-Design** [comment]
+1

**Comment by IuriiManivKuna** [comment]
+1
