### ISSUE TITLE
Fail message annotation points to the wrong line

### ISSUE THREAD

**Issue by davemfish** [vitest-dev/vitest#3766]
### Describe the bug

Console annotations of test failures -- specifically the red `^` -- often appears on the wrong line and at the wrong character. 
![Capture](https://github.com/vitest-dev/vitest/assets/4071255/3caa58ed-e248-494d-94d5-54af0c75ad4a)

In my real code I was tricked into thinking the earlier assertions were passing when they were not.

The behavior seems to be a function of the number of lines in the test file. For example, in my repro, note the ~10 lines preceding the test. If these are reduced to 1 or 2 lines, the annotation ends up in the correct place. 

### Reproduction

```
git clone https://github.com/davemfish/repro-vitest-annotation
cd repro-vitest-annotation
yarn test
```

### System Info

```shell
λ npx envinfo --system --npmPackages '{vitest,@vitest/*,vite,@vitejs/*}' --binaries --browsers
npx: installed 1 in 2.539s

  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor
    Memory: 12.73 GB / 31.95 GB
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 114.0.5735.199
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.79)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mcavigelli** [comment]
I test the following function (powershell, windows)

```typescript
export const getDouble = () : number => {
    throw new Error("Today not possible");   
}
```

Given the function is at the very top of the file, I get the following message on the console:
```console
 ❯ Module.getDouble test/matte.ts:2:11
      1| export const getDouble = () : number => {
      2|     throw new Error("Today not possible");
       |            ^
      3| }
```

Given I insert *10* blank lines, the red indicator moves 10 chars to the right:
```console
 ❯ Module.getDouble test/matte.ts:12:11
      1| export const getDouble = () : number => {
      2|     throw new Error("Today not possible");
       |                      ^
      3| }
```

Given I insert *31* blank lines, the red indicator moves 31 chars to the right:
```console
 ❯ Module.getDouble test/matte.ts:33:11
     31|
     32| export const getDouble = () : number => {
     33|     throw new Error("Today not possible");
       |                                           ^
     34| }
```

**Comment by mcavigelli** [comment]
Seems to be a **line ending** problem.

* In the tests above, the module had the windows line ending, ie CRLF.
* when changing to LF as in unix, the red indicator points always to the same character ("n" in "new"):

```console
Module.getDouble test/matte.ts:33:11
   31|
   32| export const getDouble = () : number => {
   33|     throw new Error("Today not possible");
     |           ^
   34|  }
```
