### ISSUE TITLE
Jsdom does not properly simulate the browser environment

### ISSUE THREAD

**Issue by UnrilWever** [vitest-dev/vitest#3770]
### Describe the bug

![image](https://github.com/vitest-dev/vitest/assets/75024633/bab246f0-2672-49d5-8344-9333380b6496)
when use Object.prototype.toString to get the type of window and process.
The result:
![image](https://github.com/vitest-dev/vitest/assets/75024633/53697a88-ece7-47c4-b9f0-fb4eaf323697)
but in the real browser environment,it sound be window and undefined.
It's there any methods to handle this problem right now?

### Reproduction

demo:https://stackblitz.com/edit/vitest-dev-vitest-iyikma?file=test%2Fexample.test.ts

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (6) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.3 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: latest => 0.33.0 
    vite: latest => 4.4.3 
    vitest: latest => 0.33.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
We have to provide `process`, otherwise most pf the dependencies don't work

**Comment by sheremet-va** [comment]
> > We have to provide `process`, otherwise most pf the dependencies don't work
> 
> understood,but how do i test the func to get the actual browser environment

Run tests in the browser 😄

Vitest has experimental support: https://vitest.dev/guide/browser.html

**Comment by UnrilWever** [comment]
> > > We have to provide `process`, otherwise most pf the dependencies don't work
> > 
> > 
> > understood,but how do i test the func to get the actual browser environment
> 
> Run tests in the browser 😄
> 
> Vitest has experimental support: https://vitest.dev/guide/browser.html

OK,thanks,i will try it
