### ISSUE TITLE
vitest run on SvelteKit project but no test found

### ISSUE THREAD

**Issue by xenogew** [vitest-dev/vitest#3774]
### Describe the bug

I've build and created my project for a while and decided to start add Unit Test into my project, and when I run `vitest` on project, even the `.test.ts` are existing under `src` folder, there still error because it couldn't find the test files.

```bash
 DEV  v0.25.8 /Users/ts-wangaphi.nattasan/sandbox/sw-society


 Test Files  no tests
      Tests  no tests
   Start at  18:47:46
   Duration  536ms (transform 24ms, setup 0ms, collect 0ms, tests 0ms)

⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯

Vitest caught 2 unhandled errors during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯
Error: Failed to load url tinyspy (resolved id: tinyspy). Does the file exist?
 ❯ loadAndTransform node_modules/.pnpm/vite@4.4.4_@types+node@20.4.2_less@4.1.3/node_modules/vite/dist/node/chunks/dep-abb4f102.js:54840:21
 ❯ ViteNodeServer._transformRequest node_modules/.pnpm/vitest@0.25.8_jsdom@22.1.0_less@4.1.3/node_modules/vitest/dist/chunk-vite-node-externalize.b9495318.js:7059:16
 ❯ ViteNodeServer._fetchModule node_modules/.pnpm/vitest@0.25.8_jsdom@22.1.0_less@4.1.3/node_modules/vitest/dist/chunk-vite-node-externalize.b9495318.js:7038:17


⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯
Error: Failed to load url tinyspy (resolved id: tinyspy). Does the file exist?
 ❯ loadAndTransform node_modules/.pnpm/vite@4.4.4_@types+node@20.4.2_less@4.1.3/node_modules/vite/dist/node/chunks/dep-abb4f102.js:54840:21
 ❯ ViteNodeServer._transformRequest node_modules/.pnpm/vitest@0.25.8_jsdom@22.1.0_less@4.1.3/node_modules/vitest/dist/chunk-vite-node-externalize.b9495318.js:7059:16
 ❯ ViteNodeServer._fetchModule node_modules/.pnpm/vitest@0.25.8_jsdom@22.1.0_less@4.1.3/node_modules/vitest/dist/chunk-vite-node-externalize.b9495318.js:7038:17

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

https://github.com/xenogew/sw-society/tree/develop
branch: **develop**

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 663.56 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    npm: 9.6.6 - ~/.nvm/versions/node/v18.13.0/bin/npm
    pnpm: 8.6.7 - ~/Library/pnpm/pnpm
  Browsers:
    Brave Browser: 114.1.52.122
    Chrome: 114.0.5735.198
    Safari: 16.5.2
  npmPackages:
    vite: ^4.4.4 => 4.4.4
    vitest: ^0.25.8 => 0.25.8
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
The reproduction case is using 7 months old release of Vitest. Please update to latest version and check if issue still exists.

**Comment by xenogew** [comment]
@AriPerkkio 
It was solved after upgrade version, thanks for you point out the issue.
And sorry for trouble your time.
