### ISSUE TITLE
import .node file not work?

### ISSUE THREAD

**Issue by southorange0929** [vitest-dev/vitest#3775]
### Describe the bug

Now i hava a node addon which is `.node` file and  import directly with test case.In jest framework, it works, but not work with vitest.And get some error info.
<img width="1239" alt="image" src="https://github.com/vitest-dev/vitest/assets/32590310/9450ba9e-126c-4309-be85-e36470c0d340">

I tried to add `assetInclude`,not work and get another error info.
<img width="1017" alt="image" src="https://github.com/vitest-dev/vitest/assets/32590310/a4a27b80-34b4-4538-a9d1-f4daac2b2335">

Any suggesions?Thanks.

### Reproduction

~

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 9.15 GB / 32.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.20.1 - ~/.volta/tools/image/node/16.20.1/bin/node
    npm: 8.19.4 - ~/.volta/tools/image/node/16.20.1/bin/npm
    pnpm: 8.6.7 - ~/.volta/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.2
  npmPackages:
    vitest: ^0.33.0 => 0.33.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Looks like a bug, Vitest should just externalized all .node files by default

**Comment by sheremet-va** [comment]
`.node` files cannot be imported. Vitest treats every "import" as ESM import, it doesn't look how it will be compiled because we don't support CJS tests by default (Vitest module resolution is async). To import `.node` file, you need to use `createRequire`:

```ts
import { createRequire } from 'node:module'
const require = createRequire(import.meta.url)
const { parse } = require('./path/to/.node/file')
```
