### ISSUE TITLE
'No test found in suite' failure with `passWithNoTests` enabled

### ISSUE THREAD

**Issue by alexbostock** [vitest-dev/vitest#3779]
### Describe the bug

- I have a test suite with no tests, similar to

```
describe('My feature', () => {
  describe('my test suite', () => {
    // no tests here
  });
});
```

- I am testing with `passWithNoTests` enabled (full command is `vitest run --passWithNoTests --logHeapUsage`)

- My test suite fails:

```
 FAIL  tests/suite.test.ts > My feature > my test suite
Error: No test found in suite my test suite
```

- I expected the test suite to pass.

I might be able to open a PR if you agree this should be changed.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-dubrh2?file=test%2Fsuite.test.ts

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-1235U
    Memory: 2.16 GB / 7.62 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  npmPackages:
    @vitest/coverage-v8: ^0.33.0 => 0.33.0 
    vitest: ^0.33.0 => 0.33.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is intended behavior. All test _files_ should contain at least one test.

This option just makes it so your tests don't fails if there are no test files matching filters.
