### ISSUE TITLE
Coverage issue using v8 instead of c8.

### ISSUE THREAD

**Issue by Polluux** [vitest-dev/vitest#3783]
### Describe the bug

There is a difference between the `@vitest/coverage-c8` coverage provider and the `@vitest/coverage-v8` coverage provider.
V8 highlights wrong lines as not covered (and misses some others), while C8 does its job correctly.
(Coverage reports, screenshots and explainations in the github repository).

### Reproduction

https://github.com/Polluux/demo-v8-coverage-issues

### System Info

```shell
System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 6.61 GB / 15.48 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 9.6.2 - ~/.nvm/versions/node/v18.13.0/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Chromium: 114.0.5735.198
    Firefox: 115.0.1
  npmPackages:
    @vitejs/plugin-vue: ^4.2.3 => 4.2.3 
    @vitest/coverage-c8: ^0.33.0 => 0.33.0 
    @vitest/coverage-v8: ^0.33.0 => 0.33.0 
    vite: ^4.4.0 => 4.4.4 
    vitest: ^0.33.0 => 0.33.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
This is likely happening only on Vue projects. Istanbul and c8 providers seems to work OK, v8 provider has some padding issues.

Thanks for clear reproduction case @Polluux! I'll need to find some time to debug this further. These heavily compiled languages like Vue are quite difficult to handle.
