### ISSUE TITLE
关于SyntaxError: Cannot use import statement outside a module问题

### ISSUE THREAD

**Issue by wangzhongl** [vitest-dev/vitest#3792]
### Describe the bug

 报错FAIL  src/EworldForm/index.test.tsx [ src/EworldForm/index.test.tsx ]
SyntaxError: Cannot use import statement outside a module
 ❯ Object.compileFunction node:vm:360:18
 ❯ Object.<anonymous> node_modules/.pnpm/form-render@2.2.13_antd@5.7.0_react-dom@18.2.0_react@18.2.0/node_modules/form-render/lib/form-core/index.js:8:1

Module D:/ewan/eworld-library/node_modules/.pnpm/antd@5.7.0_react-dom@18.2.0_react@18.2.0/node_modules/antd/es/button/style/index.js:1 seems to be an ES Module but shipped in a CommonJS package. You might want to create an issue to the package "antd" asking them to ship the file in .mjs extension or add "type": "module" in their package.json.

As a temporary workaround you can try to inline the package by updating your config:

// vitest.config.js
export default {
  test: {
    deps: {
      inline: [
        "antd"
      ]
    }
  }
}

![image](https://github.com/vitest-dev/vitest/assets/103638520/de497006-d9fd-4dd6-bbf6-f6c001264819)
加入配置后还是报错 好像是关于引入form-render组件的报错 请问该如何解决

### Reproduction

1

### System Info

```shell
1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by timesp** [comment]
I have the same problems, Is there any solutions?

**Comment by qc-z** [comment]
metoo

**Comment by wangzhongl** [comment]
@sheremet-va 请问有解决方法嘛
