### ISSUE TITLE
[OTHER] Update the Code of Conduct

### ISSUE THREAD

**Issue by Panquesito7** [vitest-dev/vitest#3793]
### Clear and concise description of the problem

The current Code of Conduct is the v1.4 version, which is one of the oldest versions.
Newer versions have been released, and it's best to always use the latest one.

### Suggested solution

Update the Code of Conduct to v2.1, the [latest one](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) as of now.

### Alternative

Keep it as-is or create an original code of conduct.

### Additional context

If this idea sounds good to you, I'd like to work on this.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
We are just using Vite's CoC.

**Comment by Panquesito7** [comment]
Hmm. I see it's thee Contributor Covenant CoC that is being used.
If Vite has its own CoC, we should probably link to it in the file.

**Comment by sheremet-va** [comment]
> Hmm. I see it's thee Contributor Covenant CoC that is being used. If Vite has its own CoC, we should probably link to it in the file.

We'd like to keep our COC in sync with Vite.
