### ISSUE TITLE
Different test coverage reports on different computers

### ISSUE THREAD

**Issue by pkolt** [vitest-dev/vitest#3805]
### Describe the bug

Hi! It seems to me that this bug appeared in one of the new versions. Because before the update to 0.33 everything worked without errors. Different computers produce different test coverage results.

<img width="1134" alt="" src="https://github.com/vitest-dev/vitest/assets/478905/434d7b09-9647-4c89-be42-040a4874e80f">
<img width="793" alt="" src="https://github.com/vitest-dev/vitest/assets/478905/cec36cef-c190-4311-9ee9-1b5522b302de">

Here the problem is not in CircleCI, I tried to run coverage on another Linux computer, the result was also different from coverage on a Macbook.

### Reproduction

```bash
TZ=UTC vitest --bail=1 --coverage.enabled --coverage.reporter='text-summary' --coverage.reporter='html' --reporter=junit --outputFile=./reports/junit/test-results.xml
```

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 392.42 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.6.6 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.102
    Safari: 16.5.2
    Safari Technology Preview: 17.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
The `0.33.0` release shouldn't change anything coverage related. And it looks like you are using `@vitest/coverage-istanbul` which hasn't had any big changes recently. 

Without being able to reproduce this issue I have no idea what could cause it.
