### ISSUE TITLE
ReferenceError Occurring After Updating Vitest: Is 'glob' or 'path' Affected?

### ISSUE THREAD

**Issue by naoki-kubota110** [vitest-dev/vitest#3815]
### Describe the bug

I have the following configuration in the setupFiles of vitest:

```typescript
import { globSync } from 'glob';
import { resolve } from 'path';

const appDir = resolve(__dirname, '../src/app');

// **/api.ts
globSync(`${appDir}/**/api.ts`).forEach((path) => {
  vi.mock(path, () => ({ default: {} }));
});

// **/*.graphql
globSync(`${appDir}/**/*.graphql`).forEach((path) => {
  vi.mock(path, () => ({ default: {} }));
});
```

After updating vitest from 0.28.5 to 0.33.0, I received the following error:
```
ReferenceError: path is not defined
```

What could be the cause of this?
Does updating vitest affect 'glob' or 'path'?

### Reproduction

1. `npm install vitest@0.33.0`
2. Replace the setupFiles configuration in the Vitest config with the following code snippet...
3. Run the test suite using the command...
4. See error "ReferenceError: path is not defined"

### System Info

```shell
- OS: macOS Big Sur 11.2.3
- Vitest version: 0.33.0
- Node.js version: 14.15.1
- NPM/Yarn version: 6.14.8/1.22.10
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`vi.mock` is hoisted, you cannot call it like this.

If you define dynamic mocks, use `vi.doMock`
