### ISSUE TITLE
Add `excludeAfterRemap` option for c8 coverage

### ISSUE THREAD

**Issue by RebeccaStevens** [vitest-dev/vitest#3818]
### Clear and concise description of the problem

The option [--exclude-after-remap](https://github.com/bcoe/c8#exclude-after-remap) can't currently be set in `vite.config.ts`.

### Suggested solution

Add `excludeAfterRemap` as an option to the `test.coverage` config for provider `v8`.

### Alternative

Use the `c8` provider or run vitest as `c8 vitest run` and a `.c8rc.json` config file.

### Additional context

The `c8` provider currently supports `excludeAfterRemap` but TypeScript complains about it not being a valid option.

Also: #3813

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
The `@vitest/coverage-c8` package has been removed and won't be receiving any updates from now.  See https://github.com/vitest-dev/vitest/pull/3614.

**Comment by AriPerkkio** [comment]
The `@vitest/coverage-v8` and `@vitest/coverage-istanbul` both remap the coverage results back to source files using `istanbul-lib-source-maps`. Without source map remapping users who are using Typescript, Vue, React, Svelte, or any compiled language/feature would be unable to see coverage of their source files.

Doesn't `coverage.exclude` achieve everything that `excludeAfterRemap` could provide? After reading https://github.com/vitest-dev/vitest/discussions/3813 I'm not really sure what your use case is.

**Comment by RebeccaStevens** [comment]
This is the `vite.config.ts` that works for my currently:

```ts
// ...

export default defineConfig({
  plugins: [tsconfigPaths()],

  test: {
    include: [testFilePattern],
    coverage: {
      provider: "c8",
      include: ["src/**/*.ts"],
      exclude: ["src/util/conditional-imports/**/*.ts"],
      // @ts-expect-error -- Untyped option.
      excludeAfterRemap: true,
      clean: true,
      reporter: ["lcov", "text"],
      watermarks: {
        lines: [80, 95],
        functions: [80, 95],
        branches: [80, 95],
        statements: [80, 95],
      },
    },
  },
});
```

With this config, the coverage result look like this:

![image](https://github.com/vitest-dev/vitest/assets/7224206/236ca40d-46bd-4918-9611-d4bd06069e13)

If I remove `excludeAfterRemap`, the remapping doesn't work properly and I get:

![image](https://github.com/vitest-dev/vitest/assets/7224206/d3eea906-4e47-4bab-8ff0-34593388bc16)

Here's what I get if I also remove the `include` and `exclude` options so we can see all the coverage:

![image](https://github.com/vitest-dev/vitest/assets/7224206/c1b3702e-ad9d-4935-9ec7-56fd7627a84e)

**Comment by RebeccaStevens** [comment]
`excludeAfterRemap` is also an option for nyc

https://github.com/istanbuljs/nyc/blob/ab7c53b2f340b458789a746dff2abd3e2e4790c3/index.js#L439

**Comment by AriPerkkio** [comment]
This was accidentally locked by the bot. 

Sorry for forgetting this feature request @RebeccaStevens! I didn't understand the issue completely earlier. I've now run into this same issue myself and see what you meant.

Let's add support for this. As the globbing might be slow, and people who don't bundle their source files for tests do not need this feature, let's make this opt-in and disabled by default. Exactly as `c8` does.
