### ISSUE TITLE
Configuration option to allow empty test suites to pass (re-post)

### ISSUE THREAD

**Issue by RebeccaStevens** [vitest-dev/vitest#3820]
### Clear and concise description of the problem

When working with dynamically created tests, and tests that only run under certain environmental conditions, it's possible to generate test suites with no tests in them. These then cause the whole test task to fail which isn't desirable.

When working with 3rd party libraries that create the test for you, you can also get into this situation.

I'm currently facing this issue using [@typescript-eslint/rule-tester](https://www.npmjs.com/package/@typescript-eslint/rule-tester) where it is creating all the tests and suites for me.

### Suggested solution

Add option `passSuitesWithNoTests` configuration option to allows Vitest to pass if no tests are found in a suite.

### Alternative

Modify the configuration of the existing `passWithNoTests` option to support `boolean | 'suite' | 'all'`.

### Additional context

Essentially a reopening of #1780 as that one is lock and was closed by author when they no longer needed the functionality.

Other people seem to want this behavior too based on issues like: #3779

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Don't wrap tests in ifs. Use `test.runIf`/`test.skipIf`. You shouldn't have empty suites by design.

**Comment by RebeccaStevens** [comment]
> You shouldn't have empty suites by design.

I understand that, but I don't have direct control over the `suite` and `it` commands. What I can provide are code samples and expected outputs. The tests are then dynamically created from these.

My issue comes when I want to essentially split a suite into multiple parts, some of those parts may end up empty and become incorporated as test-less suites.

For example: I have code samples written in `es5` with valid and invalid tests cases. I then want to extend these tests with further invalid tests written in `es2015`, but there are no more valid tests cases that the `es5` tests don't already cover; thus I end up with the `es2015 valid suite` being empty. I can work around this by just adding a dummy test or retesting all of the `es5` valid tests, but this is kind of redundant.

**Comment by sheremet-va** [comment]
Don't generate a suite if there are no tests inside then.

I don't really see why this should be implemented on Vitest side. We provide enough functionality to write your own generators, I don't see why this incorrect usage should be covered by core functionality.
