### ISSUE TITLE
Error: Cannot find package 'vitest' imported from /node_modules/@vitest/coverage-v8/dist/provider.js

### ISSUE THREAD

**Issue by MERCMS** [vitest-dev/vitest#3822]
### Describe the bug

After attempting to migrate from coverage-c8 to coverage-v8, I get the above errror when running `npm run test`. As `npm ls vitest` shows, vitest is installed:

        abc-fe@0.0.1-SNAPSHOT /var/www/abc-fe
        └─┬ @abc-fe/shared@1.4.0-SNAPSHOT -> ./packages/shared
          └── vitest@0.33.0

### Reproduction

Follow migration guide at https://github.com/vitest-dev/vitest/pull/3339

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 47.58 GB / 50.00 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
    pnpm: 8.6.10 - ~/.nvm/versions/node/v16.19.0/bin/pnpm
  npmPackages:
    @vitejs/plugin-vue: 3.2.0 => 3.2.0
    vite: 3.2.4 => 3.2.4
    vitest: 0.33.0 => 0.33.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MERCMS** [comment]
Creating a reproduction on StackBlitz will be difficult to say the least, because we use several npm workspaces with quite a few dependencies, and I cannot give access to the company's repository.

**Comment by AriPerkkio** [comment]
There's no need to use StackBlitz if it causes issues. As the message above says, feel free to create a normal Github repository if it's easier. Without being able to reproduce this I don't think we can do anything.

In the System Info section above your environment doesn't seem to use any `@vitest/coverage-*` packages. Start by checking that every `package.json` that has both `vitest` and `@vitest/covearge-v8` in `devDependencies`.

**Comment by MERCMS** [comment]
Thanks for your feedback. The issue was related to a version conflict with vitest. Different packages had different versions of it installed. After resolving this the error went away.
