### ISSUE TITLE
Vitest Globals not Working in VSCode?

### ISSUE THREAD

**Issue by mzietlow** [vitest-dev/vitest#3835]
### Describe the bug

In all my projects with vitest, the globals option does not work in vscode.

As long as I don't use explicit imports, e.g., `import { test } from 'vitest';` vscode keeps telling me:

``` text
Cannot find name 'test'. 
Do you need to install type definitions for a test runner? 
Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.ts(2582)
```

The tests run without any issues though. `npx vitest` results in

``` text
Test Files  1 passed (1)
``` 

### Reproduction

https://github.com/mzietlow/vitest-vscode-globals-bug

Open `app.test.ts`.

VSCode will complain about `test`:

``` text
Cannot find name 'test'. 
Do you need to install type definitions for a test runner? 
Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.ts(2582)
```

But when running `npx vitest` the test will pass just fine.

### System Info

```shell
I am using 

- "vitest": "^0.33.0"
- "react": "^18.2.0"
- VSCode@1.80.2
- Windows Server 2019@1809
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Try moving the `types` inside `compilerOptions`:

- https://github.com/mzietlow/vitest-vscode-globals-bug/blob/79a27c093cec6b2fe2c3ab2c2d3b6c64615e0738/tsconfig.json#L24
- https://vitest.dev/config/#globals
- https://www.typescriptlang.org/tsconfig#types

**Comment by mzietlow** [comment]
Ah yes, thats the obvious mistake, thank you for pointing out!

I have another repository at work that produces the same error, but does not have the same cause (`types` is inside `compilerOptions` there already).

I'll adjust the minimal example tomorrow (CET) and keep you posted

**Comment by mzietlow** [comment]
I have traced the error back to the addition of `compilerOptions.typeRoots` in the `tsconfig` of my other project. 

That is, adding:

``` json
"typeRoots": [
    "./node_modules/@types",
    "./node_modules/@microsoft"
]
```

leads to the error

``` text
Cannot find name 'test'. 
Do you need to install type definitions for a test runner? 
Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.ts(2582)
```

The error can be fixed by adding a type root to `./node_modules`.

``` json
"typeRoots": [
    "./node_modules/@types",
    "./node_modules/@microsoft",
    "./node_modules"
],
``` 

This seems to be related to https://github.com/microsoft/TypeScript/issues/54629 and https://devblogs.microsoft.com/typescript/announcing-typescript-5-1/#explicit-typeroots-disables-upward-walks-for-node_modules-types.

I have updated the repository accordingly, including both the introduction of the problem and the solution.
