### ISSUE TITLE
compilerOptions.plugins from tsconfig are not respected

### ISSUE THREAD

**Issue by tukanFrozen** [vitest-dev/vitest#3837]
### Describe the bug

Hello, firstly, thanks for the great testing library.

I've run into an issue where vitest doesn't respect `compilerOptions.plugins` from `tsconfig`

I'm trying to use [typia](https://github.com/samchon/typia) validation library, which requires adding transform plugin into `tsconfig.json`

```json
{
 "plugins": [
    {
      "transform": "typia/lib/transform"
    }
  ]
}
```

But tests are failing, saying that transform plugin is not added

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-1cgcdh?file=test/basic.test.ts&initialPath=__vitest__/

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 108.17 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.6.9 - ~/.nvm/versions/node/v18.16.0/bin/pnpm
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.5.2
    Safari Technology Preview: 17.0
  npmPackages:
    @vitest/coverage-v8: ^0.33.0 => 0.33.0 
    @vitest/ui: ^0.33.0 => 0.33.0 
    vitest: ^0.33.0 => 0.33.0
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
tsconfig largely is ignored. Vitest uses Vite which uses esbuild to transform typescript files. And esbuild has its own plugin system: https://esbuild.github.io/plugins/
