### ISSUE TITLE
Mocking in non-test files, behavior change in different versions of Vite

### ISSUE THREAD

**Issue by robokozo** [vitest-dev/vitest#3839]
### Describe the bug

In version of 4.2.3 of vite I was able to manage mocks in files outside of test files. Imagine this contrived example:

```
// setupMock.ts
export function setupMock(thing: any, path: string) {
  thing?.mock(path);
}

```

And the following would work successfully: 

```
// double.test.ts
import { vi, test, expect, type Mock } from "vitest";

import { setupMock } from "./setupMock";

setupMock(vi, "./sum");
import { sum } from "./sum";
const sumMock = sum as Mock;

import { double } from "./double";

test("should work", () => {
	sumMock.mockReturnValue(10);

	const response = double(3);

	expect(response).toEqual(10);
});

```

However in vite 4.3.0 (and above) the code crashes and the test fails. The mock doesn't appear to be respected.

![image](https://github.com/vitest-dev/vitest/assets/1719221/247fa48f-34b9-47f0-ba5d-d0a62c10ae83)

### Reproduction

In the terminal run `npm test` to see the different outputs in each example

Working example: https://stackblitz.com/edit/vitejs-vite-3edd1n
Not working example: https://stackblitz.com/edit/vitejs-vite-ofvkif

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.3 - /usr/local/bin/pnpm
  npmPackages:
    vite: 4.2.3 => 4.2.3 
    vitest: ^0.33.0 => 0.33.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This expected behavior since import statement is hoisted. Please, refer to vi.mock documentation for explanation: https://vitest.dev/api/vi.html#vi-mock

**Comment by robokozo** [comment]
@sheremet-va Do you have any suggestions with how to use vi.hoisted with the given use case? I'm struggling with it atm and could use some help.

Based on how I understood it, I wanted the following to work
```
import { setupMock } from "./setupMock";

vi.hoisted(async () => {
    setupMock(vi, "./sum")
})
```

But it doesnt
