### ISSUE TITLE
on Windows vitest logs "unknown test" when running async tests in each in concurrent

### ISSUE THREAD

**Issue by raythurnevoid** [vitest-dev/vitest#3845]
### Describe the bug

On Windows it logs "unknown error"
![image](https://github.com/vitest-dev/vitest/assets/53383860/cca6754d-180f-4f90-b2a8-d763321c36a9)

On WebContainer (Stackblitz) it put the logs in the wrong tag
![image](https://github.com/vitest-dev/vitest/assets/53383860/31e27bec-c5cd-4bd7-9d9a-d406bbcf0b67)

### Note
i'm aware of #3366, this is another issue and according to my tests it happens only on windows.
I've tested on:
- My PC (WIndows)
- Stackblitz (WebContainer)

This is where stuff start to get wrong:
https://github.com/vitest-dev/vitest/blob/c9647072d549ba2991d3fa08d00812758d1800e0/packages/runner/src/run.ts#L287

### Reproduction

https://github.com/raythurnevoid/vitest-each-with-async-logs-unknown-test
https://stackblitz.com/edit/vitejs-vite-a2txxt
`npm i && npm run dev`

### System Info

My PC:
```shell
  System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 9 4900H with Radeon Graphics
    Memory: 13.11 GB / 31.42 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
```

StackBlitz:
```shell
  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.3 - /usr/local/bin/pnpm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is expected behaviors. It's not possible to know the test that called `console.log` if it's running concurrently.

**Comment by sheremet-va** [comment]
it now prints the location of the log.
