### ISSUE TITLE
Vitest reports invalid coverage if `isolate` is false

### ISSUE THREAD

**Issue by remcohaszing** [vitest-dev/vitest#3846]
### Describe the bug

If the `isolate` option is false, Vitest semi-randomly marks branches / statements as uncovered.

### Reproduction

https://github.com/remcohaszing/monaco-languageserver-types

To reproduce the issue, run:

```sh
git clone https://github.com/remcohaszing/monaco-languageserver-types.git
cd monaco-languageserver-types
npm install
npm test
```

Remove `isolate: false` from `vitest.config.ts` and rerun the tests to uncover that the project actually has 100% test coverage. However, the tests run significantly slower.

### System Info

```shell
System:
    OS: Linux 6.2 Pop!_OS 22.04 LTS
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 23.55 GB / 31.05 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.17.0 - /usr/bin/node
    Yarn: 1.22.19 - ~/.local/bin/yarn
    npm: 9.8.1 - ~/.local/bin/npm
    pnpm: 8.2.0 - ~/.local/bin/pnpm
  Browsers:
    Chrome: 115.0.5790.110
    Chromium: 83.0.4103.116
  npmPackages:
    @vitest/coverage-v8: ^0.33.0 => 0.33.0 
    vitest: ^0.33.0 => 0.33.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Could you try to narrow down the reproduction case to a smaller one? Ideally to a setup with just a one source file and one test file.

In Vitest's test cases we are running coverage tests with multiple different configuration combinations. Both `isolate` values are being tested. 

https://github.com/vitest-dev/vitest/blob/c9aeac4cf2ac92f51d6cc246aefcb10bf6beef0a/test/coverage-test/testing.mjs#L47-L49

**Comment by remcohaszing** [comment]
No, sorry. I tried removing tests from that repo, but eventually the issue seemingly goes away. It also doesn’t help that the issue occurs randomly.

Some additional notes:

- Removing `node_modules/.vitest` before the test run, reduces how often the issue appears, but doesn’t fully resolve it.
- Adding new code increases how much the issue occurs.
- Most consistently, [these lines in `lib/monaco.ts`](https://github.com/remcohaszing/monaco-languageserver-types/blob/main/lib/monaco.ts#L11-L13) are reported as uncovered. This function is called by every test file once, but that line is only actually covered by one test.

I get the idea that somehow Vitest sometimes overwrites coverage instead of adding it up when combining coverage generated by multiple test files. This sounds like a race condition somewhere. However, I’m not familiar at all with the vitest internals.

**Comment by AriPerkkio** [comment]
Maybe this comes up when multiple test files are testing a single source file. In Vitest's internal test cases I don't think we have those that much.

**Comment by remcohaszing** [comment]
By a pure coincidence I found out that adding `threads: false` resolves the problem.

**Comment by neo-antonio-canabrava** [comment]
Apparently `threads: false` does not seem to be the actual solution, I tried in one of our projects, both `threads: true|false` didn't change the output

**Comment by neo-antonio-canabrava** [comment]
And we don't have a scenario that multiple test files test a single source file.

**Comment by neo-antonio-canabrava** [comment]
The issue appears to happen only when using instanbul as provider. When switched to v8, the coverage returned to the original values

**Comment by AriPerkkio** [comment]
Can this be reproduced with latest Vitest `1.4.0`? `threads: false` was removed before v1.

**Comment by TbabmBarry** [comment]
This still can be reproduced with `1.6.0`. As @neo-antonio-canabrava mentioned, this happened when multiple test files test a single source file.

**Comment by AriPerkkio** [comment]
It would be great if someone could set up a **minimal** reproduction case. That's the first step to fix this.

**Comment by neo-antonio-canabrava** [comment]
@AriPerkkio I'll create a project for that 👍

**Comment by lfsaestrella** [comment]
> The issue appears to happen only when using Istanbul as provider. When switched to v8, the coverage returned to the original values.

I've experienced this issue with the v8 provider.

**Comment by AriPerkkio** [comment]
Continues in https://github.com/vitest-dev/vitest/issues/6736
