### ISSUE TITLE
Make module graph stable in UI while on the same file

### ISSUE THREAD

**Issue by patak-dev** [vitest-dev/vitest#386]
### Clear and concise description of the problem

Right now switching tabs (between module graph and others) when looking in a given test file will reset the graph and it will be recreated in a new randomized positioned

### Suggested solution

We could generate a seed at startup and keep it for each file, I imagine that D3 is prepared to receive a stable seed. Or we could keep the current randomized scheme, but avoid destroying the module graph component when switching tabs until the user clicks on another file (that I think it is better if we allow the user to move nodes around, so they can switch tabs and get back to the same graph)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DerYeger** [comment]
I'm the author of the graph library used. It does not have any diffing/seeding logic, so that part would have to be handled in the component.
Not destroying the component would probably work much better and would be a simpler solution as well.

**Comment by DerYeger** [comment]
#389 somewhat alleviates this issue.
