### ISSUE TITLE
Error when using process.env.NODE_ENV with jsdom and @vitest/coverage-istanbul

### ISSUE THREAD

**Issue by devpeerapong** [vitest-dev/vitest#3860]
### Describe the bug

When running `vitest` with coverage `@vitest/coverage-istanbul` and `jsdom`
If the code is using the `process.env.NODE_ENV`, it will throw this error.

```bash
FAIL  index.test.ts [ index.test.ts ]
Error: Parse failure: Unexpected token (30:59)
At file: /env.ts
Contents of line 30:       sourcesContent: ["export const env = {\n  NODE_ENV: "test",\n};\n"],
```

In this error, you can see that the double quote of the `process.env.NODE_ENV` is not escaped.

This error is gone after we remove the `jsdom` from the test environment.

I try it with `v0.33` and there's no error.

### Reproduction

here's the minimal reproduction https://github.com/devpeerapong/vitest-034-jsdom-coverage-bug

1. install `vitest`, `jsdom`, `@vitest/coverage-istanbul`
2. create `vitest.config.test` with this configuration
```ts
import { UserConfigExport, defineConfig } from "vitest/config";

// https://vitejs.dev/config/
export default defineConfig({
  test: {
    environment: "jsdom",
    coverage: { provider: "istanbul" },
  },
} as UserConfigExport);
```
3. create `index.ts`
```ts
export function getNodeEnv() {
  return process.env.NODE_ENV;
}
```
4. create `indext.test.ts`
```ts
import { test, expect } from "vitest";
import { getNodeEnv } from "./index";

test("getNodeEnv() should return test", () => {
  expect(getNodeEnv()).toBe("test");
});
```
5. Run `vitest --coverage`. You will see the error.
 
*If you comment out the `environment: "jsdom"` in `vitest.config.ts` or downgrade `vitest` to `v0.33`, it will work.

### System Info

```shell
System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 138.20 MB / 16.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.17.0 - ~/Library/Caches/fnm_multishells/3207_1690965709901/bin/node
    Yarn: 3.2.1 - ~/Library/Caches/fnm_multishells/3207_1690965709901/bin/yarn
    npm: 9.6.7 - ~/Library/Caches/fnm_multishells/3207_1690965709901/bin/npm
    pnpm: 8.6.9 - ~/Library/Caches/fnm_multishells/3207_1690965709901/bin/pnpm
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.6
  npmPackages:
    @vitejs/plugin-react: ^4.0.4 => 4.0.4 
    @vitest/coverage-istanbul: ^0.34.1 => 0.34.1 
    vitest: ^0.34.1 => 0.34.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Istanbul instrumented code contains the source map where `process.env` is in source map:

```js
function cov_zu6h2qi9v() {
  var coverageData = {
    path: "/Users/ari/Git/vitest/test/coverage-test/src/process-env.ts",
    branchMap: { },
    inputSourceMap: {
      sourcesContent: ["export function getNodeEnv() {\n  return process.env.NODE_ENV\n}\n"],
      // ...
    },
  }
}

cov_zu6h2qi9v();
export function getNodeEnv() {
  cov_zu6h2qi9v().f[0]++;
  cov_zu6h2qi9v().s[0]++;
  return "test";
}
```

When `process.env` is replaced, it injects double quotes to string which breaks the JS object.

```diff
  inputSourceMap: {
-    sourcesContent: ["export function getNodeEnv() {\n  return process.env.NODE_ENV\n}\n"],
+    sourcesContent: ["export function getNodeEnv() {\n  return "test"\n}\n"],
```

**Comment by sheremet-va** [comment]
> This bug was introduced by #3491.

Yes, `process.env.NODE_ENV` is always replaced by Vite. This is intentional change, we just need to find a workaround.

**Comment by AriPerkkio** [comment]
> we just need to find a workaround

As the `sourcesContent` contains all source code in a single line, I think we could replace all `process.env`'s from that line with regexp after instrumenting that file. And before remapping the coverage results back to sources, change it back.

**Comment by fireairforce** [comment]
meet the same problem when i upgrade from `0.29.1` to `0.33.0`..

**Comment by alexvarney** [comment]
This isn't a proper fix, but the best solution I've found to resolve this issue right now is to add all your `process.env` references to a single config file that re-exports the values, and then add that file to the excluded test files in `vite.config.ts`.

**Comment by AriPerkkio** [comment]
Updating Vitest to `0.34.2` should fix this.
