### ISSUE TITLE
Invalid hook call when executing with `@vitest-ui`

### ISSUE THREAD

**Issue by nwi-di** [vitest-dev/vitest#3861]
### Describe the bug

Executing tests with UI will lead to invalid hook calls (`TypeError: Cannot read properties of null (reading 'useState')`). Executing tests without UI will pass.

### Reproduction

- Reproduction repo: https://github.com/nwi-di/vitest-invalid-hook-call
- Clone repo and install dependencies
- Run `npm run test-ui`(will execute `vitest` with `ui` flag)

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 307.59 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
    Watchman: 2023.06.26.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.5.2
  npmPackages:
    @vitejs/plugin-react: ^4.0.3 => 4.0.4 
    @vitest/ui: ^0.34.1 => 0.34.1 
    vite: ^4.4.5 => 4.4.8 
    vitest: ^0.34.1 => 0.34.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SamuelAlev** [comment]
Can you try downgrading `vitest` and `@vitest/ui` to `0.33.0`, `0.34.0` seems to have broken it.

**Comment by lpillonel** [comment]
I am facing the same issue, but I actually can get it working with the latest vitest version; issue seems to be actually related to the latest happy-dom version for me.

**Comment by nwi-di** [comment]
> Can you try downgrading `vitest` and `@vitest/ui` to `0.33.0`, `0.34.0` seems to have broken it.

Downgrading works as a workaround. Seems to be related to latest version of either `vitest` or `@vitest-ui` (guess `@vitest-ui` as tests running without ui will pass)

**Comment by mschnee** [comment]
Error also occurs using:
```
vitest --api 9527
```

... which impacts testing UIs such as the vscode vitest extension.

Downgrading `vitest` and `@vitest/ui` both to `0.33.0` works in these cases as well.

**Comment by Karganyan** [comment]
@SamuelAlev i love u

**Comment by nathpaiva** [comment]
> Can you try downgrading `vitest` and `@vitest/ui` to `0.33.0`, `0.34.0` seems to have broken it.

Thank you, @SamuelAlev the downgrading worked here 👋

**Comment by lpillonel** [comment]
`0.34.2` release from yesterday solves the issue 🙂

**Comment by sheremet-va** [comment]
Another workaround for now. Add this to your config to disable occasional optimizer. Looks like there is a bug in the implementation that causes inconsistencies when `--api` or `--ui` is enabled.

```ts
      deps: {
        optimizer: {
          web: {
            enabled: false,
          },
        },
      },
```
