### ISSUE TITLE
eperimentalVmThreads and vi.useFakeTimers() with jsdom environment

### ISSUE THREAD

**Issue by cexbrayat** [vitest-dev/vitest#3863]
### Describe the bug

Using `vi.useFakeTimers()` throws when the test is run with `--experimental-vm-threads` in jsdom environment in v0.34.1

```
TypeError: Cannot set properties of undefined (setting 'hadOwnProperty')
 ❯ test/basic.test.ts:6:6
      4|
      5| test('Math.sqrt()', () => {
      6|   vi.useFakeTimers()
```

### Reproduction

https://github.com/cexbrayat/vitest-repro-experimental-vm-threads

```
yarn
yarn test
```

The repro is the basic test calling `vi.useFaketimer()` and `environment: "jsdom"`.

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 34.05 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.volta/tools/image/node/18.16.0/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 9.7.1 - ~/.volta/tools/image/npm/9.7.1/bin/npm
    pnpm: 8.6.9 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.5.2
  npmPackages:
    vite: 4.4.8 => 4.4.8
    vitest: 0.34.1 => 0.34.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
While I am trying to figure out the exact issue, you can add this to your config to temporarily fix this:

```ts
export default {
  test: {
    fakeTimers: { toFake: undefined }
  }
}
```
