### ISSUE TITLE
Failed to load url error when using sveltekit and jsdom environment (0.34.1)

### ISSUE THREAD

**Issue by EugeneDraitsev** [vitest-dev/vitest#3866]
### Describe the bug

I have "Failed to load url" error when using sveltekit and jsdom environment for `setupFiles` file. It works fine with vitest 0.33, this error appear only in vitest 0.34.1

### Reproduction

1. Create empty sveltekit project with vitest `npm create svelte@latest my-app` or clone my repo with all dependencies and files: https://github.com/EugeneDraitsev/vitest-setup-files-bug
2. Add jsdom to dependencies, add empty `setupTest.ts` and use following `vite.config.ts`
```ts
export default defineConfig({
	plugins: [sveltekit()],
	test: {
		include: ['src/**/*.{test,spec}.{js,ts}'],
		environment: 'jsdom',
		setupFiles: './setupTest.ts'
	}
});
```
3. Run `yarn test` and see "Failed to load url" error

If you comment `environment: 'jsdom',` or downgrade vitest to `0.33.0`, then it will work fine

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700KF
    Memory: 13.58 GB / 31.82 GB
  Binaries:
    Node: 18.15.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.22.19 - ~\scoop\apps\yarn\current\bin\yarn.CMD
    npm: 9.5.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (115.0.1901.188)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Previously Vitest was running in SSR mode even if environment was JSDOM.

Vite doesn't allow accessing files outside of the root folder [by default](https://vitejs.dev/config/server-options.html#server-fs-allow). Since 0.34.0, Vitest uses `web` mode to load all files inside a test suite, and because of this Vite fallbacks to `fs.allow` rules. You need to allow files outside of root to be served manually:

```ts
export default defineConfig({
	plugins: [sveltekit()],
	test: {
		include: ['src/**/*.{test,spec}.{js,ts}'],
		environment: 'jsdom',
		setupFiles: './setupTest.ts'
	},
	server: {
		fs: {
			allow: ['./setupTest.ts']
		}
	}
});
```

**Comment by EugeneDraitsev** [comment]
Thank you for explanation! It works fine with `server` configuration
