### ISSUE TITLE
allowExternal option for v8 coverage provider

### ISSUE THREAD

**Issue by vojvodics** [vitest-dev/vitest#3867]
### Clear and concise description of the problem

Since the @vitest/coverage-c8 is removed in favor of @vitest/coverage-v8 (https://github.com/vitest-dev/vitest/pull/3339) and coverage-v8 doesn't provide the allowExternal option this will break coverage reports when upgrading to the latest vitest version (and switching providers).

### Suggested solution

Implement the allowExternal option (as suggested in the above-mentioned PR). I'd be happy to provide the implementation (LMK if you have any inputs/suggestions on how to do this)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
This should also be implemented to `@vitest/coverage-istanbul`. They both use the same `test-exclude` dependency which I think provides this in `c8`: https://github.com/bcoe/c8/blob/a13584d5be5259ebb6a00455d352c3e8b16006de/lib/report.js#L48-L52.

>  I'd be happy to provide the implementation

PR is welcome! Here is one PR for reference to show which files, tests and documentation needs changes when adding new coverage options: https://github.com/vitest-dev/vitest/pull/3453.
Let me know if you need any help.

**Comment by vojvodics** [comment]
@AriPerkkio I drafted a PR for this, can you check it out? https://github.com/vitest-dev/vitest/pull/3894 

I actually would need help with writing good tests for this feature. I added some tests but I don't think they do what they should do. Please check out the comments in the PR 🙏
