### ISSUE TITLE
Jest replaceProperty has no equivalent

### ISSUE THREAD

**Issue by tkrotoff** [vitest-dev/vitest#3884]
### Description of the problem

 [Jest `replaceProperty`](https://jestjs.io/docs/jest-object#jestreplacepropertyobject-propertykey-value) has no complete equivalent in Vitest (`replaceProperty` is broader than `vi.stubEnv` and `vi.stubGlobal`).

There is no equivalent to this: https://stackoverflow.com/a/75271718

```TypeScript
// config.js
export default {
   foo: 'bar'
}

// whatever.test.js
import config from './config';

test('whatever', () => {
  jest.replaceProperty(config, 'foo', 'zed');

  ...
});
```

Original issue: https://github.com/vitest-dev/vitest/issues/2831 (which is locked)

### Suggested solution

Add the equivalent to [Jest `replaceProperty`](https://jestjs.io/docs/jest-object#jestreplacepropertyobject-propertykey-value)

Should be generic and cover all needs:

```TypeScript
vi.replaceProperty(process, 'env', {HOSTNAME: 'localhost'});
vi.replaceProperty(globalThis, 'innerWidth', 100);
vi.replaceProperty(config, 'foo', 'zed');
```

And then deprecate/remove specific `vi.stubGlobal`, `vi.stubEnv` functions.

**Comment by sheremet-va** [comment]
> In the [Jest migration guide](https://vitest.dev/guide/migration.html#migrating-from-jest) you claim that `vi.stubEnv` replaces [Jest `replaceProperty`](https://jestjs.io/docs/jest-object#jestreplacepropertyobject-propertykey-value).

This is not true. The migration guide specifies that you can replace "replaceProperty" with "stubEnv" **IF** you need to change env. It doesn't mention that they are interchangeable.

Personally, I don't see any use for this API. You can do the same with `vi.spyOn`.

**Comment by tkrotoff** [comment]
> IF you need to change env

true, I've modified the issue description

> I don't see any use for this API. You can do the same with `vi.spyOn`

How do you do that https://stackoverflow.com/a/75271718 with `vi.spyOn`?

**Comment by sheremet-va** [comment]
> How do you do that [stackoverflow.com/a/75271718](https://stackoverflow.com/a/75271718) with `vi.spyOn`?

```ts
vi.spyOn(config, 'foo', 'get').mockImplementation(() => 'zed')
```

**Comment by tkrotoff** [comment]
```TypeScript
vi.spyOn(config, 'foo', 'get').mockImplementation(() => 'zed')
                         ↑↑↑
                         This is smart!
```

Didn't think it was possible, thanks!

Then why `stubEnv` and `stubGlobal`? `spyOn` already supports those 2 cases (I've tested and everything work):

```TypeScript
vi.spyOn(process, 'env', 'get').mockReturnValue({ HOSTNAME: "localhost" });
vi.spyOn(globalThis, 'innerWidth', 'get').mockReturnValue(100);
```

**Comment by sheremet-va** [comment]
> Then why `stubEnv` and `stubGlobal`? `spyOn` already supports those 2 cases (I've tested and everything work):

1. Semantics. These are two the most popular objects for mocking, and it's easier to understand for new developers
2. Vitest supports `import.meta.env` syntax which is hard to grasp for some people, so it's easier to just call `vi.stubEnv`
3. Initially in Vitest `globalThis` and `window` were different objects, so this method mocked them on both
