### ISSUE TITLE
Use Gherkin feature file in unit tests with vitest

### ISSUE THREAD

**Issue by amiceli** [vitest-dev/vitest#3892]
### Clear and concise description of the problem

In my company we use [jest-cucumber](https://github.com/bencompton/jest-cucumber) to run our unit tests with our Gherkin feature file.

It allow to run unit tests checking if we missed a Scenario or a Scenario step like **When**.

Currently we moved to vitest in some project but we don't have a **hest-cucumber** alternative.

### Suggested solution

I've created a repository [vitest-cucumber](https://github.com/amiceli/vitest-cucumber) with we can run unit tests using our Gherkin feature file.

It provides same method like jest-cucumber : `Scenario`, `When` etc

So when we run unit test it check if we forgot a Scenario, or type a bad etc.

### Additional context

I also publish [vitest-cucumber](https://github.com/amiceli/vitest-cucumber) on npm `@amiceli/vitest-cucumber`.

I would like to have your opinion.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I am not sure what this issue is about. The choice of testing style in Vitest is deliberate and we do not plan to add different styles - this is left to the community to figure out and publish their own solutions (like you did).

**Comment by amiceli** [comment]
I'm OK with you. maybe I misspoke.
It's just a project that I want to share with Vitest community like [vitest-cucumber-plugin](https://github.com/samuel-ziegler/vitest-cucumber-plugin).

And have some feedback about this project ;).
I close this issue ?

**Comment by sheremet-va** [comment]
Regular people rarely read issues. If you want to tell about your project, I would recommend discord. Link should be in the docs header.
