### ISSUE TITLE
Can't run all `.each` tests using `--testNamePattern`

### ISSUE THREAD

**Issue by rluvaton** [vitest-dev/vitest#3896]
### Describe the bug

we can't run `--testNamePattern` to run all `.each` test (I can't change to only as I'm writing an automated tool and not the code runner)

### Reproduction

If we have this for example:
```ts
import { it } from 'vitest';

it.each([1])('test this %s', (s) => {
    console.log(s);
});
```

and use `npx vitest run --testNamePattern "test this %s"` than no tests will be ran (if I set the pattern to be `"test this 1"` it will work)

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 28.14 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.5.2
  npmPackages:
    vitest: ^0.34.1 => 0.34.1 
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This expected behavior. Test name is not the same as test name template

**Comment by rluvaton** [comment]
so how would I run all each tests/describe?

**Comment by sheremet-va** [comment]
> so how would I run all each tests/describe?

```
vitest -t "test this "
```
