### ISSUE TITLE
Spy lose reference when declare multiple time

### ISSUE THREAD

**Issue by darkychin** [vitest-dev/vitest#3901]
### Describe the bug

When declaring same spy with `spyOn` and with different mock implementation on a test file for two time in each `describe` along with `resetAllMocks`, the first declared spy loses its reference and its mock implementation.

But after relocating the spy declaration to a higher level, the bug solve itself.

### Test functions
``` typescript
// test.ts
export const sum = () => {
  const { a, b } = testUtil.getValue()
  return a + b
}

export const getValue = () => ({
  a: 5,
  b: 5,
})

export const testUtil = {
  getValue,
}
```

### Test Cases Bug Example
``` typescript
// test.spec.ts with issues
import { beforeEach, describe, expect, it, vi } from "vitest"
import { sum, testUtil } from "@/utils/test"

describe("sum", () => {
  const getValueSpy = vi.spyOn(testUtil, "getValue")

  beforeEach(() => {
    vi.resetAllMocks()
  })

  it("10 + 20", () => {
    getValueSpy.mockReturnValue({ a: 10, b: 20 })

    const value = sum()
    console.log(value)

    expect(value).toBe(30)
  })
})

describe("sum2", () => {
  const getValueSpy = vi.spyOn(testUtil, "getValue")

  beforeEach(() => {
    vi.resetAllMocks()
  })

  it("20 + 3", () => {
    getValueSpy.mockReturnValue({ a: 20, b: 3 })

    const value = sum()

    expect(value).toBe(23)
  })
})

```
Error Message screenshot
<img width="1098" alt="image" src="https://github.com/vitest-dev/vitest/assets/12773418/38e699ff-467a-4628-8f76-530383684ad6">

### Working Test Cases Example with higher spy declaration

``` typescript
// test.spec.ts without issues when moving the spy to higher level
import { beforeEach, describe, expect, it, vi } from "vitest"
import { sum, testUtil } from "@/utils/test"

const getValueSpy = vi.spyOn(testUtil, "getValue")

describe("sum", () => {
  beforeEach(() => {
    vi.resetAllMocks()
  })

  it("10 + 20", () => {
    getValueSpy.mockReturnValue({ a: 10, b: 20 })

    const value = sum()
    console.log(value)

    expect(value).toBe(30)
  })
})

describe("sum2", () => {
  beforeEach(() => {
    vi.resetAllMocks()
  })

  it("20 + 3", () => {
    getValueSpy.mockReturnValue({ a: 20, b: 3 })

    const value = sum()

    expect(value).toBe(23)
  })
})

```

### System Info

```shell
System:
    OS: macOS 12.6.8
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 20.88 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.17.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.6
  npmPackages:
    @vitejs/plugin-vue: ^4.1.0 => 4.2.3 
    @vitest/coverage-istanbul: ^0.29.8 => 0.29.8 
    @vitest/ui: ^0.27.3 => 0.27.3 
    vitest: ^0.29.8 => 0.29.8
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is correct behavior. Method is spied on module `exports` and will only track calls when called directly

**Comment by darkychin** [comment]
Sorry, i don't quite get what you mean.
In both test case examples, they are calling it the same way but just different spy declaration placement causing the result to be varied...
