### ISSUE TITLE
Asymmetric matcher message is not printed

### ISSUE THREAD

**Issue by jagoral** [vitest-dev/vitest#3908]
### Describe the bug

Given a custom matcher, when assertion fails, I expect to see the message which I've set up. Currently it's not present. 

```ts
expect.extend({
  maybeAny(received, constructor) {
    if (received === null) {
      return {
        pass: true,
        message: () => 'Received value is equal to null',
      };
    }

    try {
      expect(received).toEqual(expect.any(constructor));
      return {
        pass: true,
        message: () => `Received value matches ${constructor} constructor`,
      };
    } catch {
      return {
        pass: false,
        message: () => 'Some custom message',
      };
    }
  },
});
```

<img width="658" alt="CleanShot 2023-08-07 at 23 27 26@2x" src="https://github.com/vitest-dev/vitest/assets/26148834/998922e6-6edc-434d-b2db-71a8509ef87e">

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-f9qkgy?file=vitest.setup.ts

// when I try to run it in stackblits, I get an error `Error: For a percentage based memory limit a percentageReference must be supplied`, however on my machine it works fine

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 94.03 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.8.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.5.2
  npmPackages:
    @vitest/ui: latest => 0.34.1
    vite: latest => 4.4.9
    vitest: latest => 0.34.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
The behavior looks consistent to Jest (jest has better diff):

```
 FAIL  test/basic.test.ts
  ✕ Prints custom message (4 ms)

  ● Prints custom message

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 0

      Object {
        "a": Any<Number>,
    -   "b": maybeAny<function Number() { [native code] }>,
      }

      19 |   expect({
      20 |     a: 1
    > 21 |   }).toEqual({
         |      ^
      22 |     a: expect.any(Number),
      23 |     b: expect.maybeAny(Number),
      24 |   })

      at Object.toEqual (test/basic.test.ts:21:6)
```

The message is meant for actual matchers.
