### ISSUE TITLE
vite-node v0.34 can not import esm with .js properly

### ISSUE THREAD

**Issue by jameschenjav** [vitest-dev/vitest#3910]
### Describe the bug

Simply import anything from AWS sdk, it works with v0.33.x. I have tried 0.34.0 and 0.34.1, both are broken. 

```ts
import { GetObjectCommand } from '@aws-sdk/client-s3';

console.log(new GetObjectCommand({ Bucket: 'foo', Key: 'bar' }));
```

```txt
❯ pnpm vite-node tmp/test.ts
(node:25865) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/home/james/repos/hestia/oracle-db-ts/node_modules/.pnpm/@aws-sdk+util-user-agent-node@3.378.0/node_modules/@aws-sdk/util-user-agent-node/dist-es/is-crt-available.js:1
export const isCrtAvailable = () => {
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.17.0
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-i9fkvq

### System Info

```shell
System:
    OS: Linux 6.4 Fedora Linux 38 (Workstation Edition)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 16.47 GB / 30.97 GB
    Container: Yes
    Shell: 3.6.1 - /usr/bin/fish
  Binaries:
    Node: 18.17.0 - ~/.volta/tools/image/node/18.17.0/bin/node
    Yarn: 1.22.19 - ~/.local/share/pnpm/yarn
    npm: 9.8.1 - ~/.volta/tools/image/npm/9.8.1/bin/npm
    pnpm: 8.6.12 - ~/.local/share/pnpm/pnpm
  npmPackages:
    vite: ^4.4.9 => 4.4.9
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Looks like it's [a bug](https://github.com/unjs/mlly/issues/186) in `mlly` package. As a workaround, you can inline @aws-sdk yourself:

```shell
vite-node --options.deps.inline=/@aws-sdk/ main.ts
```

**Comment by klausbadelt** [comment]
The mentioned is merged in https://github.com/unjs/mlly/pull/187. So we don't have to pin to 0.33, do you have plans to upgrade your dependency anytime soon? Thank you!

**Comment by sheremet-va** [comment]
Actually, we stopped using mlly some time ago and this should just work now.
