### ISSUE TITLE
TypeError: $setup.testFunc is not a function

### ISSUE THREAD

**Issue by hzferrari** [vitest-dev/vitest#3911]
### Describe the bug

Hello!
I encountered a problem and tried many methods but could not solve it.

I used Vue3 to build my project. There's a function definded in <script setup>  and be called inside HTML template. Then I run vitest and an error happened. 

![image](https://github.com/vitest-dev/vitest/assets/18616675/51429d4b-d7bf-474c-923a-567133626766)

My demo code is below. How can this problem be avoided?

Thank you!

### Reproduction

```
<script setup>
import { ref, watchEffect } from "vue";

function testFunc(str) {
	return str;
}
</script>

<template>
	<div>
		{{ testFunc("hello") }}
	</div>
</template>

```

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-1240P
    Memory: 1.30 GB / 15.64 GB
  Binaries:
    Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (114.0.1823.82), ChromiumDev (111.0.1660.14)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitest/ui: ^0.33.0 => 0.33.0
    vite: ^3.2.4 => 3.2.4
    vitest: ^0.33.0 => 0.33.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Please, open a pull request to the tool that you use for rendering Vue. Vitest doesn't provide anything out of the box, so this issue is out of our scope.

**Comment by hzferrari** [comment]
> Please, open a pull request to the tool that you use for rendering Vue. Vitest doesn't provide anything out of the box, so this issue is out of our scope.

Sorry, but I don't quite understand what you mean. 
I did not use any third-party tools for rendering Vue. I believe the sample code I provided uses the very common Vue3 syntax.
