### ISSUE TITLE
Missing "." specifier in package

### ISSUE THREAD

**Issue by ciscoheat** [vitest-dev/vitest#3913]
### Describe the bug

The `sveltekit-flash-message` package doesn't (and shouldn't) have a top-level export, and from vitest 0.34.1 this breaks the testing. It looks related to https://github.com/vitejs/vite/issues/4425 but I cannot find a solution there.

### Reproduction

https://github.com/ciscoheat/vitest-34-breaking

It's a default SvelteKit installation. Install and run with `pnpm vitest`. The following error should appear:

```
Error: Failed to resolve entry for package "sveltekit-flash-message". The package may have incorrect main/module/exports specified in its package.json: Missing "." specifier in "sveltekit-flash-message" package
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 49.00 GB / 63.93 GB
  Binaries:
    Node: 18.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.11 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.183)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is because Svelte automatically adds this package to optimized dependencies. Vitest doesn't control that

**Comment by ciscoheat** [comment]
Ok, so why does it work with the same Svelte/SvelteKit version when going back to vitest 0.33?

**Comment by sheremet-va** [comment]
> Ok, so why does it work with the same Svelte/SvelteKit version when going back to vitest 0.33?

Because Vitest didn't respect optimized dependencies in 0.33

**Comment by ciscoheat** [comment]
All right, is it possible to fix this without having to instruct users to modify their configuration files? Will adding an empty top-level export be enough?

**Comment by ciscoheat** [comment]
It worked when adding a top-level export, so I'm leaving it there even though I don't understand the details.
