### ISSUE TITLE
Run child `describe`s/`suite`s concurrently

### ISSUE THREAD

**Issue by Bas950** [vitest-dev/vitest#3914]
### Clear and concise description of the problem

```ts
import { describe, test } from "vitest";

describe.concurrent("Testing", () => {
	describe.sequential("01", () => {
		let count = 0;
		test("A - Should run concurrently with C", async ({ expect }) => {
			count++;
			await new Promise(resolve => setTimeout(resolve, 1000));
			expect(count).toBe(1);
		});

		test("B - Should run concurrently with D", async ({ expect }) => {
			count++;
			await new Promise(resolve => setTimeout(resolve, 1000));
			expect(count).toBe(2);
		});
	});

	describe.sequential("02", () => {
		let count = 0;
		test("C - Should run concurrently with A", async ({ expect }) => {
			count++;
			await new Promise(resolve => setTimeout(resolve, 1000));
			expect(count).toBe(1);
		});

		test("D - Should run concurrently with B", async ({ expect }) => {
			count++;
			await new Promise(resolve => setTimeout(resolve, 1000));
			expect(count).toBe(2);
		});
	});
});
```

I have around 90 describes where each test within them needs to run sequential but the describes could run concurrently, this would save a lot of time.

### Suggested solution

`describe.concurrent` doesn't only affect `test`s

### Alternative

A setting within the describe (`describe.concurrent("name", () => {}, {setting: "foo"});`)

### Additional context

I know the issue https://github.com/vitest-dev/vitest/issues/661 exists but I would like to reopen the discussion.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Put your tests in a separate non-nested `describe` then. This is a problem of structuring your tests, not a Vitest issue.
