### ISSUE TITLE
Run tests NOT in random order - unshuffle

### ISSUE THREAD

**Issue by ziimakc** [vitest-dev/vitest#3922]
### Clear and concise description of the problem

When global tests configuration `shuffle` is set to `true` to ensure tests isolation there is no way to run some specific test suite in non-random order.

This is required when you have long integration test which is split in multiple blocks, for example:

```
describe('long auth test with sequential order', ()=>{
   it('test 1 register', ()=>{})
   it('test 2 login', ()=>{})
   it('test 3 logout', ()=>{})
})
```

This is similar to [#3731](https://github.com/vitest-dev/vitest/issues/3731)

### Suggested solution

Add option `describe.unshuffle` to run specific test block in non-shuffled order

### Alternative

Add logic to existing `describe.sequential` to run specific test block in non-shuffled order

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by JesusTheHun** [comment]
Same here. I want to shuffle by default, but when I use `describe.sequential(...)` I expect the suite to run sequentially.
In many cases, the behaviour described inside `vitest.config.ts` can be overwritten locally : `timeout`, `hookTimeout`, `repeats`, `retry`, they can all set in situ.

**Comment by sheremet-va** [comment]
You can disable shuffle in a single file or next describe block with `vi.setConfig({ sequence: { shuffle: false } })`

And to undo this you can call `vi.resetConfig`
