### ISSUE TITLE
CommonJs not imported correctly on Windows

### ISSUE THREAD

**Issue by leopsidom** [vitest-dev/vitest#393]
### Describe the bug

Import CommonJs module results in undefined on windows. More specifically:

`import { highlight, languages } from 'prismjs';`

results in `languages` and `highlight` being `undefined` since it relies on the following exports:

```
if (typeof module !== 'undefined' && module.exports) {
    module.exports = Prism;
}
```

However `module.exports` is `undefined` when running the test on windows.

### Reproduction

https://stackblitz.com/edit/node-vqbbph?file=test/example.test.ts.

Reproduce steps:
1. Download the project to a windows machine;
2. run `npm install && npm run test`

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 956.45 MB / 15.80 GB
  Binaries:
    Node: 15.6.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.19.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.62)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @vitejs/plugin-vue: ^2.0.1 => 2.0.1
    vite: ^2.7.10 => 2.7.10
    vitest: ^0.0.125 => 0.0.125
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
The same thing as: https://github.com/vitest-dev/vitest/issues/379

We have to wait for a fix: https://github.com/unjs/mlly/pull/28

**Comment by sheremet-va** [comment]
For now you can add this to your `test` config:

```
deps: {
  external: [/prismjs/],
},
```

**Comment by leopsidom** [comment]
@sheremet-va Thanks. This works but it creates another issue:

> TypeError: Unknown file extension ".css" for ".../prism.css"

I think it's because I have to directly import the css file in my component:

`import "prismjs/themes/prism.css";`

**Comment by sheremet-va** [comment]
try `/\/prismjs\//`

**Comment by sheremet-va** [comment]
> try `/\/prismjs\//`

well it wont work either
I believe you can come with regexp that suites you!

**Comment by sheremet-va** [comment]
Maybe something like this?

```
deps: {
  external: [/prismjs\/(?!theme)/],
},
```

**Comment by leopsidom** [comment]
Ahh, nice that worked. `/prismjs\/prism.js/` worked too. I didn't know we need to specify the path in `external` instead of the import syntax used, and so was trying something along `/prismjs"$/` which obviously didn't work.

**Comment by sheremet-va** [comment]
> Ahh, nice that worked. `/prismjs\/prism.js/` worked too. I didn't know we need to specify the path in `external` instead of the import syntax used, and so was trying something along `/prismjs"$/` which obviously didn't work.

Yeah, maybe we need to document that 👀 Full paths to file are needed.

**Comment by sheremet-va** [comment]
Fixed in https://github.com/vitest-dev/vitest/releases/tag/v0.0.139
