### ISSUE TITLE
Headless mode is not working for WebDriverIO

### ISSUE THREAD

**Issue by twinprime** [vitest-dev/vitest#3930]
### Describe the bug

The current [code for setting the headless option for WebDriverIO is not working](https://github.com/vitest-dev/vitest/blob/f4e6e99fa3a81fd7a97fb9b435da367dddba7fa4/packages/vitest/src/node/browser/webdriver.ts#L61), i.e. the option is ignored and browser still opens:

```
      capabilities: {
        'browserName': this.browser,
        'wdio:devtoolsOptions': { headless: options.headless },
      },
```

Based on [current WebDriverIO documentation](https://webdriver.io/docs/capabilities/#run-browser-headless), it is now dependent on the browser selected. For example, for Chrome, it should be 

```
'goog:chromeOptions': {
    args: ['headless', 'disable-gpu']
}
```

I verified by modifying the code in the node_module/vitest/dist/vendor-node.caa511fc.js of my project and it works after the change.

### Reproduction

None

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 45.28 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - /usr/local/opt/node@18/bin/node
    npm: 9.5.1 - /usr/local/opt/node@18/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Edge: 115.0.1901.203
    Safari: 16.5.2
  npmPackages:
    @vitejs/plugin-react: ^4.0.1 => 4.0.3
    @vitest/browser: ^0.34.1 => 0.34.1
    @vitest/coverage-istanbul: ^0.34.1 => 0.34.1
    @vitest/ui: ^0.34.1 => 0.34.1
    vite: ^4.4.0 => 4.4.7
    vitest: ^0.34.1 => 0.34.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lsim** [comment]
My CI is failing with the same issue - webdriverio now attempts to start graphical chrome in a headless environment
