### ISSUE TITLE
Unexpected output when logging HTML in @vitest/ui

### ISSUE THREAD

**Issue by Tahul** [vitest-dev/vitest#3934]
### Describe the bug

Happened while writing tests for a Vite plugin load hook, using `fs.readFileSync`.

I was reading a Vue basic component, and the `<template>` turned into an HTML fragment, from a console.log in the Vitest UI.

This is the output when displaying it in Vitest UI:
![image](https://github.com/vitest-dev/vitest/assets/1385263/fb15bb60-f35c-42b5-bbb4-560f2099bba3)

Running the same `readFileSync` from Node:
![image](https://github.com/vitest-dev/vitest/assets/1385263/c4b96031-dd03-4f67-aa96-8a125098b182)

Where Vitest UI turns it into an HTML fragment:
![image](https://github.com/vitest-dev/vitest/assets/1385263/25a3de58-a125-4224-8e8b-2f16e3235acd)

Let me know if you need any further explanations.

Also, if you can give me guidelines, I can most likely help to solve this via a PR!

Thanks again for Vitest! 🙏

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-zhysj6?file=test/basic.test.ts&initialPath=__vitest__/

Run `test:run` to see proper output in console.

Run `test:ui` to see wrong output in side-panel of the test.

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 163.50 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.volta/tools/image/node/18.16.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.5.1 - ~/.volta/tools/image/node/18.16.0/bin/npm
    pnpm: 8.6.1 - ~/.volta/bin/pnpm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Fixed by https://github.com/vitest-dev/vitest/pull/4724
