### ISSUE TITLE
Blank lines cause wrong line to be highlighted in vitest output

### ISSUE THREAD

**Issue by FeldrinH** [vitest-dev/vitest#3943]
### Describe the bug

Having blank lines in test code causes the highlighted line with the failing test to show the wrong part of the code.

### Reproduction

```javascript
import { expect, test } from 'vitest';





























test('example', () => {
    expect(false).toBeTruthy();
});
// a
// b
// c
// d

```

gives this output:

![image](https://github.com/vitest-dev/vitest/assets/5256211/3bc2fbde-eb99-4be9-9723-48ee7bd5532c)

(Note that the line number shown after the file name is correct, but the highlighted line is wrong.)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i5-13600KF
    Memory: 22.04 GB / 31.83 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.2.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    N/A
  npmPackages:
    vitest: ^0.34.1 => 0.34.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Fixed by #3855, but not released yet
