### ISSUE TITLE
ReferenceError: XPathEvaluator is not defined

### ISSUE THREAD

**Issue by mLiGuangYuan** [vitest-dev/vitest#3946]
### Describe the bug

If I use the XPathEvaluator method in the ts file, it will not work,  the error msg is:
> ReferenceError: XPathEvaluator is not defined

### Reproduction

---demo
> XpathTransformParser.ts
```ts
const evaluator = new XPathEvaluator()
export const parser = (element, path: string) => {
   return evaluator.evaluate(path, element, null, XPathResult.ORDERED_NODE_ITERATOR_TYPE)
}
```

> spec.ts
```spec.ts
import { parser } from './XpathTransformParser';
import { describe, it, expect } from "vitest";
describe('XpathTransformParser', () => {
  it('parser', () => {
      expect(parser(document, '//div'))
  })
})
```

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 224.80 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.volta/tools/image/node/18.16.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 9.5.1 - ~/.volta/tools/image/node/18.16.0/bin/npm
    pnpm: 8.6.12 - ~/.volta/bin/pnpm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.5
  npmPackages:
    vite: ^4.4.9 => 4.4.9 
    vitest: ^0.34.1 => 0.34.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Use jsdom environment. Vitest doesn't provide browser compatible globals: https://github.com/jsdom/jsdom/issues?q=is%3Aissue+is%3Aopen+xpath+sort%3Aupdated-desc
