### ISSUE TITLE
Regression (0.33.0 -> 0.34.0) tests completely break when using jsdom or happy-dom with SvelteKit

### ISSUE THREAD

**Issue by LorenzoBloedow** [vitest-dev/vitest#3953]
### Describe the bug

So basically after updating to 0.34.0 from 0.33.0 I get the following error message (redacted):
```
Error: Failed to load url [REDACTED]/tests/unit/DarkModeSwitch.test.ts (resolved id: [REDACTED]/tests/unit/DarkModeSwitch.test.ts). Does the file exist?
```

Contrary to what the error message suggests, the file does exist.
I believe this is due to #3491 as it does work when using node instead of `jsdom` or `happy-dom`, suggesting the use of the `web` transform mode instead of `ssr` is what's causing this.

Note: 0.34.1 doesn't fix the issue.

### Reproduction

Open the following StackBlitz and run `npm run test`
https://stackblitz.com/edit/sveltejs-kit-template-default-fwbgpv

### System Info

```shell
System:
  OS: Linux 5.0 undefined
  CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 0 Bytes / 0 Bytes
  Shell: 1.0 - /bin/jsh
Binaries:
  Node: 16.20.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 9.4.2 - /usr/local/bin/npm
  pnpm: 8.6.10 - /usr/local/bin/pnpm
npmPackages:
  vite: ^4.4.2 => 4.4.9 
  vitest: ^0.34.1 => 0.34.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
File is outside root. Try disabling `server.fs.strict`.

**Comment by sheremet-va** [comment]
> File is outside root. Try disabling `server.fs.strict`.

Indeed the problem is with this. While we are working on fixing this, you can disable strict in test mode or add a tests folder to `server.fs.allow`

**Comment by LorenzoBloedow** [comment]
Thank you.
I was under the impression the root directory was where the configuration file lives.

As you suggested, adding the following to `vite.config.ts` fixes the problem:
```
server: {
  fs: {
    allow: [".."]
  }
}
```

**Comment by sheremet-va** [comment]
> I was under the impression the root directory was where the configuration file lives.

Svelte does some magic to `fs.allow` values, so the root is not included. In the next Vitest version we populate `fs.allow` ourselves.
