### ISSUE TITLE
command line flags don't override config file

### ISSUE THREAD

**Issue by castarco** [vitest-dev/vitest#3962]
### Describe the bug

As a tool user, I usually have a set of expectations respect to the precedence order of certain ways to set configuration values for the tools I use. One of these typical rules is that the order of application is similar to:

1. config files
2. environment variables
3. command line options/flags

where the later overrides the former (in case it is present).

In the case of Vitest, I'm finding that this is not the case when it comes to coverage related settings. For example, when I have the following config file:
```typescript
import { defineConfig } from 'vitest/config'

export default defineConfig({
	test: {
		coverage: {
			include: ['src/*.{ts,tsx}'],
			exclude: ['src/**/*.test.{ts,tsx}', 'src/stories/**/*'],
			thresholdAutoUpdate: true,
			branches: 50,
			lines: 50,
			functions: 50,
			statements: 50,
		},
	},
})
```

but I call `vitest` with `vitest run --coverage.enabled=true --coverage.thresholdAutoUpdate=false`, the later flag is not being applied, giving more importance to the one inside the config file (and as a consequence, if my coverage is higher, the config file is auto-updated to reflect the new coverage values).

### Reproduction

The previous description is enough. We just need a test with high enough coverage, and set the thresholds in our config to be below that if we want to see how the command line flag is not taking precedence over the config file value.

### System Info

```shell
System:
    OS: macOS 13.5
    CPU: (24) arm64 Apple M2 Ultra
    Memory: 14.52 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.1.0 - ~/Library/Caches/fnm_multishells/14573_1692095309449/bin/node
    Yarn: 3.6.1 - ~/Library/Caches/fnm_multishells/14573_1692095309449/bin/yarn
    npm: 9.6.4 - ~/Library/Caches/fnm_multishells/14573_1692095309449/bin/npm
    pnpm: 8.6.12 - ~/Library/Caches/fnm_multishells/14573_1692095309449/bin/pnpm
  Browsers:
    Chrome: 115.0.5790.170
    Edge: 114.0.1823.82
    Safari: 16.6
  npmPackages:
    @vitest/coverage-v8: ^0.34.1 => 0.34.1 
    vitest: ^0.34.1 => 0.34.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by castarco** [comment]
If other devs from vite/vitest agree with me that this is an issue, I'm open to contribute the fix (I just don't want to jump straight to it before confirming that we agree on this).

**Comment by AriPerkkio** [comment]
The value passed from CLI is overriding the configuration file value. The type is just wrong. This is a bug.

```js
export default defineConfig({
  test: {
    coverage: {
      thresholdAutoUpdate: true,
      lines: 1,
    },
  },
});
```

```sh
pnpm run test --coverage.enabled=true --coverage.thresholdAutoUpdate=false
```

```js
// provider.ts
console.log({ 
  "this.options.thresholdAutoUpdate": this.options.thresholdAutoUpdate,
  "typeof this.options.thresholdAutoUpdate": typeof this.options.thresholdAutoUpdate
})
```

```
{
  'this.options.thresholdAutoUpdate': 'false', <-- should be false, not 'false'
  'typeof this.options.thresholdAutoUpdate': 'string' <-- should be boolean
}
```
