### ISSUE TITLE
Support shared authentication fixture for api testing 

### ISSUE THREAD

**Issue by viveleroi** [vitest-dev/vitest#3963]
### Clear and concise description of the problem

We're using supertest to write our API tests. We were really hoping to use vitest as the test running because we're already using it for component tests. It would extremely useful for our developers to have only one test runner/assertion lib.

However, in order to test our API we need:

1. To run an authentication test before any other test 
2. A way to share the supertest "agent" with cookies/session info with all other tests

We sadly can't find any way to do these with vitest currently. Because of how tests are run we can't find an easy way to run the authentication before all other tests run, but only once. We also can't share the supertest agent because how tests are run in different processes etc. We've tried to play with `isolate` and other settings but nothing works.

I *believe* including the auth test first and then a glob for all other tests helps set the order, but the other tests shouldn't be executed until the first one is done. 

We could use the setup.ts file but it's called again for each process/thread not once for the entire test suite.

Since we can't seem to get this working, we probably need to use mocha and chai (and ts-node etc) and those are extra layers we really prefer to avoid.

### Suggested solution

Provide a way to run a setup test/fixture first, and then a way to share the agent with other tests.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
You can already do that with setup file.

It runs for every test file because every test file runs in isolation and doesn't have access to other test contexts.

If you disable isolation, you can just mark (by assigning a global variable for example) that you already logged in and don't run it again.

**Comment by viveleroi** [comment]
Ok so I've gotten closer, but the key seems to be this has to run with `singleThread: false`
```js
// vite.config.js has:
test: {
  isolate: false,
  include: ['./tests/api/**/*.spec.ts'],
  setupFiles: './tests/api/setup.ts',
  singleThread: true
}
```

```js
// setup.ts has:
if (!globalThis.isAuthorized) {
  console.log('setup running')

  const { USERNAME, PASSWORD } = process.env

  // This is really only needed to typescript, it doesn't know expect() is narrowing
  if (!USERNAME || !PASSWORD) {
    throw new Error('Invalid username or password.')
  }

  await agent.post('/login').field('username', USERNAME).field('password', PASSWORD).expect(200)

  globalThis.isAuthorized = true
}
```

```
// vitest output (with singleThread: true):
stdout | unknown test
setup running

stdout | unknown test
setup running

 ✓ tests/api/logbook/log-properties.spec.ts (1) 966ms
 ✓ tests/api/me.spec.ts (2)

 Test Files  2 passed (2)
      Tests  3 passed (3)
   Start at  14:45:41
   Duration  6.97s (transform 35ms, setup 11.72s, collect 33ms, tests 977ms, environment 0ms, prepare 194ms)
```

Without singleThread the setup file is called multiple times before the login process can complete, so each time the global var is undefined.
