### ISSUE TITLE
`command` property when calling defineConfig is set to "serve" for `vitest run`

### ISSUE THREAD

**Issue by jroru** [vitest-dev/vitest#3977]
### Describe the bug

The `command` property when calling `defineConfig` is set to "serve" for `vitest run`

### Reproduction

When running `vitest run`:

```ts
export default defineConfig(({ command }) => {
    console.log(command); // -> "serve"
    return {
      foo: command === "serve" ? 1 : 2,
    };
});
```

I expected vitest's "run" to be differentiated from vite's "serve". Is this as expected?

### System Info

```shell
System:
    OS: macOS 13.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    npm: 9.6.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
  Packages:
    Vite: 4.4.9
    Vitest: 0.31.0
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is expected. command can only be serve or build.
