### ISSUE TITLE
v0.34.0 "URL is not defined" failure when using `isolate: false`

### ISSUE THREAD

**Issue by EvHaus** [vitest-dev/vitest#3984]
### Describe the bug

After upgrading from `vitest` version 0.33.0 to 0.34.0 I'm seeing this failure in any tests which rely on the `URL` global:

```
ReferenceError: URL is not defined
```

I'm guessing this is related to the change in:
- #3828

What's interesting is that my failure only occurs when `isolate: false` is used. Setting `isolate: true` makes the problem go away. The error also doesn't happen when focusing on specific tests in watch mode. It only shows up when running my entire test suite.

Rolling back to 0.33.0 fixes the issue.

### Reproduction

I haven't been able to reproduce via StackBlitz in a minimal scenario yet, so it's possible it's caused by some interplay between other tests, or perhaps the order in which tests run?

Any advice on what the issue might be? Maybe I can give it another try.

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 79.16 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - ~/.nvm/versions/node/v20.5.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.0 - ~/.nvm/versions/node/v20.5.1/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Chrome Canary: 118.0.5956.0
    Edge: 114.0.1823.55
    Firefox: 116.0.2
    Safari: 16.5.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kjetilod** [comment]
I also see this error with Node 18.6.0, but upgrading to 18.17.1 fixes it.

**Comment by kjetilod** [comment]
> I also see this error with Node 18.6.0, but upgrading to 18.17.1 fixes it.

After some more testing, I still get this error on 18.17.1 some times. Seems pretty random from run to run if tests run ok or fail with this error.
