### ISSUE TITLE
Fake timers don't work for `performance.now()`

### ISSUE THREAD

**Issue by satelllte** [vitest-dev/vitest#4004]
### Describe the bug

Hi 👋

I'm not sure if this a bug or not, but I noticed that [Vitest fake timers](https://vitest.dev/api/vi.html#vi-usefaketimers) don't work with [High precision timing Web API](https://developer.mozilla.org/en-US/docs/Web/API/Performance_API/High_precision_timing), specifically for `performance.now()`. 

Is it possible to support it?

#### Code snippet:

https://github.com/satelllte/adsr/pull/46

#### Stdout example:

```
> npm run test -- fakeTimers.test.ts

stdout | fakeTimers.test.ts > fake timers > works for performance.now?
(before) performance.now() [1] |  1802.5662189722061
(before) performance.now() [2] |  1803.9706729650497
(before) performance.now() [3] |  1804.0636450052261
(after) performance.now() [1] |  1804.601235985756
(after) performance.now() [2] |  1804.7059119939804
(after) performance.now() [3] |  1804.8976829051971
```

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8557U CPU @ 1.70GHz
    Memory: 151.96 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
  Browsers:
    Chrome: 116.0.5845.96
    Chrome Canary: 118.0.5963.0
    Safari: 16.5.2
  npmPackages:
    vitest: 0.34.1 => 0.34.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It doesn't do this by default yet, but you can enable it with fake timers config:

```ts
import { configDefaults } from 'vitest/config'
export default {
  test: {
    toFake: [...configDefaults.toFake, 'performance']
  }
}
```

**Comment by satelllte** [comment]
@sheremet-va amazing, thank you so much!

It works now with this config in my particular case (100% TypeScript):

```ts
/* vitest.config.ts */
import {defineConfig, configDefaults} from 'vitest/config';

export default defineConfig({
  test: {
    fakeTimers: {
      toFake: [...(configDefaults.fakeTimers.toFake ?? []), 'performance'],
    },
  },
});
```

Reference: https://github.com/satelllte/adsr/pull/46/commits/aceb6e1e0ed96e5da50802c483bce1a9191700e2

Stdout:
```sh
(before) performance.now() [1] |  0
(before) performance.now() [2] |  0
(before) performance.now() [3] |  0
(after) performance.now() [1] |  5000
(after) performance.now() [2] |  5000
(after) performance.now() [3] |  5000
```

**Comment by gautelo** [comment]
This one really got me as well. Apparently, while the vitest documentation for `toFake` does mention that it omits `nextTick()` and `queueMicrotask()`, it doesn't mention that it also omits 'performance'. Nor does it mention any of the other methods included by fake timers by default. If you have a look the `FakeMethod` type it's showing 15 method names, yet vitest's `toFake` defaults to using only 7 of them.

Leaves me uneasy knowing you're not passing through defaults, but using your own and not documenting discrepancies appropriately. Like, how can I trust any defaults after this? :(

**Comment by hi-ogawa** [comment]
It looks like there is a slight difference with jest about what's faked by default:
https://jestjs.io/docs/jest-object#jestusefaketimersfaketimersconfig

> Fake timers will swap out Date, performance.now(), queueMicrotask(), setImmediate(), clearImmediate(), setInterval(), clearInterval(), setTimeout(), clearTimeout() with an implementation that gets its time from the fake clock.
> 
> In Node environment process.hrtime, process.nextTick() and in JSDOM environment requestAnimationFrame(), cancelAnimationFrame(), requestIdleCallback(), cancelIdleCallback() will be replaced as well.

while Vitest has:

https://github.com/vitest-dev/vitest/blob/7d18233c13fc61b73a8e4d8caf4dd5c136faeb64/packages/vitest/src/defaults.ts#L52-L60

I don't think we can just suddenly align this with jest (also `nextTick` issue), so probably adding documentation + jsdoc is the best we can do.

**Comment by gautelo** [comment]
Vite and vitest is opinionated. That's a fine choice, but it does require that the opinions are well documented, so clearing this up in the docs would be good, and sufficient.

**Comment by sheremet-va** [comment]
> (Probably new API like `performance` gets added after this default is defined in #1261?)

Actually, the reason why we define those keys as default is because this was specified as the default in fake-timers README. We never intended to be opinionated.

**Comment by gautelo** [comment]
Always hard knowing where the flakiness starts and ends in the JS ecosystem, unfortunately.. :( Sorry to direct my frustration at you if indeed the issue started in fake-timers readme and not here.
