### ISSUE TITLE
Vitest incorrectly imports variables from sass modules

### ISSUE THREAD

**Issue by dyabol** [vitest-dev/vitest#4005]
### Describe the bug

If you have a sass module and export variables, vitest seems to access them as if they were classnames.

In Vars.module.sass
```sass
:export {
  test: 10px;
}
```
In TS file

```ts
import Vars from './Vars.module.scss';
Vars.test // value is _test_1b545c instead 10px
```

Css modules work correctly, only SASS modules not.

### Reproduction

https://stackblitz.com/edit/github-w9fjy7-qvlb6f?file=src%2FApp.test.tsx

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 412.36 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.0 - /usr/local/bin/node
    Yarn: 3.4.1 - /usr/local/bin/yarn
    npm: 9.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 116.0.5845.110
    Firefox: 113.0.2
    Safari: 16.1
    Safari Technology Preview: 16.4
  npmPackages:
    @vitejs/plugin-react: ^3.1.0 => 3.1.0 
    @vitejs/plugin-react-swc: ^3.3.2 => 3.3.2 
    vite: 4.2.3 => 4.2.3 
    vitest: ^0.34.2 => 0.34.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
CSS processing is disabled by default. Enable it if you don't want to see mocks there.
