### ISSUE TITLE
Get $RefreshSig$ error when testing React.js custom hook

### ISSUE THREAD

**Issue by LizardLiang** [vitest-dev/vitest#4012]
### Describe the bug

I have updated vitest to version `0.34.2`
and building Electron app with React.js

When I try to test my React custom hook with environment equal to jsdom, I get `$Refrehsig$` is not defined every time
After I downgrade vitest to `0.25.8` the issue is no longer exist.

The error message is pasted below

```
 FAIL  tests/useCustomHook.test.ts [ tests/useCustomHook.test.ts ]
ReferenceError: $RefreshSig$ is not defined
 ❯ src/utils/useCustomHook.tsx:1:10
      1| import { useToast } from '@chakra-ui/react';
       |          ^
      2| import { useState } from 'react';
      3|
 ❯ tests/useCustomHook.test.ts:15:28

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  no tests
   Start at  11:35:19
   Duration  1.62s (transform 222ms, setup 249ms, collect 0ms, tests 0ms, environment 552ms, prepare 316ms)


 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
```

Here is the vite.config.js file I use when testing

```ts
export default defineConfig({
  resolve: {
    alias: {
      '@': path.join(__dirname, 'src'),
      public: path.join(__dirname, 'public'),
      styles: path.join(__dirname, 'src/assets/styles'),
    },
  },
  plugins: [
    react(),
    electron({
      main: {
        entry: 'electron/main/index.ts',
        vite: withDebug({
          build: {
            outDir: 'dist/electron/main',
          },
        }),
      },
    }),
    EnvironmentPlugin('all'),
  ],
  server: {
    host: pkg.env.VITE_DEV_SERVER_HOST,
    port: pkg.env.VITE_DEV_SERVER_PORT,
  },
  build: {
    minify: true,
  },
  test: {
    globals: true,
    environment: 'jsdom',
    exclude: [...configDefaults.exclude],
    deps: {
      registerNodeLoader: false,
    },
    server: {
      deps: {
        fallbackCJS: true,
      },
    },
    setupFiles: 'tests/setup.ts',
    // coverage: { reporter: ['text', 'json', 'html'] },
  },
});

```

### Reproduction

Install vitest with version 0.34.2, and use environment with jsdom, 
react version is 18.2.8, 
@testing-library/react@14.0.0, 
@vitejs/plugin-react@2.2.0

implement a react custom hook 
test the custom hook

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 12.29 GB / 31.80 GB
  Binaries:
    Node: 16.18.1 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    npm: 8.19.2 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    pnpm: 8.6.12 - ~\scoop\shims\pnpm.EXE
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.54)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-react: ^2.0.1 => 2.2.0
    vite: ^4.4.9 => 4.4.9
    vitest: ^0.34.2 => 0.34.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Update your react plugin to the latest version

**Comment by sawadyecma** [comment]
In my case, it has been solved through updating @vitejs/plugin-react. 

@sheremet-va 
Thx!
