### ISSUE TITLE
deps.optimizer appears broken in 0.34.3

### ISSUE THREAD

**Issue by thebanjomatic** [vitest-dev/vitest#4020]
### Describe the bug

This is new behavior for me starting in 0.34.3. 0.34.2 works correctly for me.

If I pass dependencies to deps.optimizer.web.includes, it appears to usually work the first time, but then it fails to save the dependencies with the following error:
```
[vite] error while updating dependencies:
Error: ENOENT: no such file or directory, rename 'C:\source\test-project\node_modules\.vitest\deps_temp_c61dd53a' -> 'C:\source\test-project\node_modules\.vitest\deps'
```

And then on subsequent runs, there is a long delay before timing out and producing the following error:

```
file:///C:/source/test-project/node_modules/vite-node/dist/server.mjs:310
        throw new Error(`ViteNodeServer: ${id} not found. This is a bug, please report it.`);
        ^

Error: ViteNodeServer: C:/source/test-project/node_modules/.vitest/deps/vue.js not found. This is a bug, please report it.
    at Timeout._onTimeout (file:///C:/source/test-project/node_modules/vite-node/dist/server.mjs:310:15)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

### Reproduction

Doesn't actually appear to reproduce in stackblitz, but does reproduce for me on windows:
https://stackblitz.com/edit/vitest-dev-vitest-ycqdpe?file=vite.config.ts

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12800H
    Memory: 13.28 GB / 31.64 GB
  Binaries:
    Node: 20.5.1 - ~\AppData\Local\Volta\tools\image\node\20.5.1\node.EXE
    Yarn: 3.6.1 - ~\AppData\Local\Volta\tools\image\yarn\1.22.19\bin\yarn.CMD
    npm: 9.8.0 - ~\AppData\Local\Volta\tools\image\node\20.5.1\npm.CMD
    pnpm: 8.6.12 - ~\AppData\Local\Volta\tools\image\pnpm\8.6.12\bin\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (115.0.1901.200)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-vue2: ^2.2.0 => 2.2.0
    vite: ^4.0.4 => 4.4.4
    vitest: 0.34.3 => 0.34.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I think this might happen because we run optimizer for each workspace project. Maybe if we specify different cache folder, it might work better

**Comment by thebanjomatic** [comment]
Thanks for the insight here. I'll try first bypassing the workspace to confirm, and then submit a PR to update the cache directly if that works

**Comment by thebanjomatic** [comment]
If move the test config into the vite.config.ts file, things behave a little more stable, but there are still intermittent issues.
Even when the build succeeds, I sometimes experience:

```
[vite] error while updating dependencies:
Error: ENOENT: no such file or directory, rename 'C:\source\test-project\node_modules\.vitest\deps_temp_60ca75f1' -> 'C:\source\test-project\node_modules\.vitest\deps'
```

Sometimes:
```
8:51:38 AM [vite] error while updating dependencies:
Error: ENOENT: no such file or directory, rename 'C:\source\test-project\node_modules\.vitest\deps_temp_603b7296' -> 'C:\source\test-project\node_modules\.vitest\deps'      
8:51:38 AM [vite] error while updating dependencies:
TypeError: Cannot read properties of undefined (reading 'browserHash')
    at commitProcessing (file:///C:/source/test-project/node_modules/vitest/node_modules/vite/dist/node/chunks/dep-abb4f102.js:45147:116)
    at async runOptimizer (file:///C:/source/test-project/node_modules/vitest/node_modules/vite/dist/node/chunks/dep-abb4f102.js:45170:17)
```

And other times:
```
8:59:10 AM [vite] error while updating dependencies:
Error: EPERM: operation not permitted, rename 'C:\source\test-project\node_modules\.vitest\deps_temp_be08813d' -> 'C:\source\test-project\node_modules\.vitest\deps'
```

**Comment by thebanjomatic** [comment]
I'm not seeing those above logs currently after upgrading vite from 4.4.4 to 4.4.9 and the linked PR fixes the problem that I was running into here.
