### ISSUE TITLE
Runner is unresponsive after detaching debugger

### ISSUE THREAD

**Issue by gtm-nayan** [vitest-dev/vitest#4022]
### Describe the bug

When running Vitest with a debugger, pausing on any breakpoint/debugger statement and then detaching the debugger will make it go unresponsive, even to key presses that are supposed to kill it.

### Reproduction

https://github.com/gtm-nayan/vitest-debugger-repro

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (8) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 374.05 MB / 7.69 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.5.1 - ~/.local/share/pnpm/node
    Yarn: 1.22.19 - ~/.local/share/pnpm/yarn
    npm: 9.8.0 - ~/.local/share/pnpm/npm
    pnpm: 8.6.11 - ~/.local/share/pnpm/pnpm
  npmPackages:
    vite: ^4.4.5 => 4.4.9 
    vitest: ^0.34.3 => 0.34.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
I'm unable to reproduce this using Chrome dev tools. Could you write some reproduction steps for this?

**Comment by gtm-nayan** [comment]
Hmm, Chrome dev tools doesn't seem to stop at the debugger statement for some reason.

I used the VSCode debugger through Javascript Debug Terminal.
Steps:
1) Run `pnpm vitest run` through the debug terminal
2) Once it hits the debugger statement in the add function, detach the debugger


<details>
<summary>I've attached a video if it helps:</summary>

https://github.com/vitest-dev/vitest/assets/50981692/4143bd85-c937-4dea-b132-d34ccacbd260
</details>

**Comment by AriPerkkio** [comment]
> Hmm, Chrome dev tools doesn't seem to stop at the debugger statement for me for some reason.

Did you check debugging guide at https://vitest.dev/guide/debugging.html#node-inspector-e-g-chrome-devtools?

**Comment by gtm-nayan** [comment]
Ahh, okay yeah doesn't happen for me with Chrome's debugger either but the issue still persists with single threaded mode on the VSCode debugger.

**Comment by AriPerkkio** [comment]
I'm able to reproduce this using VSCode. `--threads` and `--single-thread` use `node:worker_threads` and get stuck. `--no-threads` uses `node:child_process` and doesn't get stuck.

**Comment by sheremet-va** [comment]
> `--no-threads` uses `node:child_process` and doesn't get stuck.

I also just want to point out that in child_process case we forcefully exit the process:

https://github.com/vitest-dev/vitest/blob/e691a9ca229dd84765a4b40192761ffc1827069c/packages/vitest/src/runtime/child.ts#L110

**Comment by sheremet-va** [comment]
The solution here is to always use `--pool=forks` when debugging using VSCode debugger.
