### ISSUE TITLE
spyOn not working

### ISSUE THREAD

**Issue by sureshvv** [vitest-dev/vitest#4023]
### Describe the bug

==== example.js ====

function sub1() {
  return 'hello'
}
function main1() {
  return sub1()
}
export { sub1, main1 }

==== example.test.js ====

import { describe, expect, it, vi } from "vitest";
import * as api from './example'

describe('main', () => {
  it("example", () => {
    const spy1 = vi.spyOn(api, 'sub1')
    api.main1()
    expect(spy1).toHaveBeenCalledTimes(1)
  })
})

### Reproduction

https://gist.githubusercontent.com/sureshvv/3c9825040be95692ae50181f537c9b39/raw/c89abc6009896acf69db0664824ca75ef94107cf/gistfile1.txt

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i5-3470T CPU @ 2.90GHz
    Memory: 10.85 GB / 15.52 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
  npmPackages:
    @vitejs/plugin-vue: ^4.1.0 => 4.2.3 
    @vitest/coverage-v8: ^0.33.0 => 0.33.0 
    vite: ^4.3.9 => 4.3.9 
    vitest: ^0.33.0 => 0.33.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You literally commented on an issue that explains why this doesn't work: #3733

**Comment by sureshvv** [comment]
> You literally commented on an issue that explains why this doesn't work: #3733

In my example function sub1 is exported. Your response in #3733 suggests that if the function is exported, it should be possible to spyOn. Please explain.

**Comment by sheremet-va** [comment]
> > You literally commented on an issue that explains why this doesn't work: #3733
> 
> In my example function sub1 is exported. Your response in #3733 suggests that if the function is exported, it should be possible to spyOn. Please explain.

My explanation suggests you can only spy on exported calls, not calls within the same module because it's essentially the example I gave (exported or not, its usage references original declaration)

**Comment by sureshvv** [comment]
1. sub1() is exported.

2. Are you saying each function needs to be in a module of its own?

**Comment by sheremet-va** [comment]
Yes, they need to be exported in a separate module. This is how it works in jest even, if you don't use ts-node.

**Comment by sureshvv** [comment]
Seems like a major limitation that every method that needs to be spied on has to reside on its own module.

**Comment by sheremet-va** [comment]
This is how javascript works. I don't know what you mean about vi.mock.

**Comment by sureshvv** [comment]
https://vitest.dev/api/vi.html#vi-mock
