### ISSUE TITLE
setupFiles error 

### ISSUE THREAD

**Issue by Diboby** [vitest-dev/vitest#4024]
### Describe the bug

Hello,

When ever I use the `setupFiles` option in my test configuration, all tests failed with the error `Error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.`

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-6jwltw?file=vite.config.ts,test%2Fconfig%2Fvitest.setup.ts&initialPath=__vitest__/

It doesn't matter what I put in the `vitest.setup.ts` file. Even if it's empty, I still get the same error. However, when I comment out either the Vue macros plugin or the setupFiles line, the error disappears.

### System Info

```shell
System:
    OS: Linux 5.19 Ubuntu 22.10 22.10 (Kinetic Kudu)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.66 GB / 15.26 GB
    Container: Yes
    Shell: 5.2.2 - /bin/bash
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
    pnpm: 8.6.12 - ~/.nvm/versions/node/v16.19.1/bin/pnpm
    Watchman: 4.9.0 - /usr/bin/watchman
  Browsers:
    Chrome: 116.0.5845.96
  npmPackages:
    vitest: ^0.34.2 => 0.34.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
testTransformMode accepts a glob pattern, not file extensions

**Comment by sheremet-va** [comment]
Disabling `VueMacros` helps to fix the issue, so I would recommend opening an issue in their repo.

**Comment by Diboby** [comment]
The fix https://github.com/vue-macros/vue-macros/issues/490#issuecomment-1695816034

**Comment by Diboby** [comment]
The fix https://github.com/vue-macros/vue-macros/issues/490#issuecomment-1695816034
