### ISSUE TITLE
beforeEach return fn doesn't receive context that afterEach receives

### ISSUE THREAD

**Issue by luixo** [vitest-dev/vitest#4030]
### Describe the bug

Consider code:
`test1.spec.ts`
```ts
import { test as originalTest } from 'vitest';

type Fixture = { foo: number };

const test = originalTest.extend<Fixture>({
  foo: async ({}, use) => {
    await use(1);
  },
});
beforeEach<Fixture>(({ foo })=> {
  console.log(`beforeEach ${foo}`);
});
afterEach<Fixture>(({ foo }) => {
  console.log(`afterEach ${foo}`);
});
```

In this case we'll get not data in beforeEach as expected, but afterEach can access the data.
```
beforeEach undefined
afterEach 1
```

Consider pretty similar case
`test2.spec.ts`
```ts
import { test as originalTest } from 'vitest';

type Fixture = { foo: number };

const test = originalTest.extend<Fixture>({
  foo: async ({}, use) => {
    await use(1);
  },
});
beforeEach<Fixture>(({ foo })=> {
  console.log(`beforeEach ${foo}`);
  return ({ foo: afterFoo }) => {
    console.log(`afterEach ${foo} / ${afterFoo}`);
  };
});
```

This code will throw on `beforeEach` callback (effectively an analogue to `afterEach`), I would expect to actually see:
```
beforeEach undefined
afterEach undefined / 1
```

### Reproduction

See above

### System Info

```shell
Not applicable
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This looks like a bug, but I would expect it to work like `test.beforeEach` because you can define separate contexts at the top level
