### ISSUE TITLE
Crash when parallelizing tasks

### ISSUE THREAD

**Issue by leonheess** [vitest-dev/vitest#4038]
### Describe the bug

After updating our lerna-based mono repo from v0.34.2 to v0.34.3 we encounter the following issue:

```
> vitest run --coverage --silent
    →    Executing 8/8 remaining tasks in parallel...
⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
Error: Port 3002 is already in use
    at Server.onError (file:////xxx/xxx/xxx/node_modules/.pnpm/vite@4.4.9_@types+node@18.16.18/node_modules/vite/dist/node/chunks/depdf561101.js:54741:28)ortal-dashboard:test:ci
    at Server.emit (node:events:513:28)st:ci
    at emitErrorNT (node:net:1767:8):ci
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

 ELIFECYCLE  Command failed with exit code 1.
```
### Relevant config

```
server: {
  host: '127.0.0.1',
  port: 3002,
  strictPort: true,
  hmr: {
    clientPort: 3002,
    overlay: false,
  },
},
preview: {
  port: 3002,
},
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 102.22 GB / 127.21 GB
  Binaries:
    Node: 18.14.2 - ~\AppData\Local\Volta\tools\image\node\18.14.2\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\Volta\tools\image\yarn\1.22.19\bin\yarn.CMD
    npm: 9.5.0 - ~\AppData\Local\Volta\tools\image\node\18.14.2\npm.CMD
    pnpm: 8.7.0 - ~\AppData\Local\Volta\bin\pnpm.EXE
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.200)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-vue: 4.3.3 => 4.3.3
    @vitest/coverage-v8: 0.34.3 => 0.34.3
    vite: 4.4.9 => 4.4.9
    vitest: 0.34.3 => 0.34.3
```

### Used Package Manager

pnpm

**Comment by leonheess** [comment]
I'll just keep using v0.34.2. I reported it because it probably makes sense to check the changes made to parallelization in v0.34.3. I tried those two versions extensively and could only reproduce it on the latter.

**Comment by sheremet-va** [comment]
> I'll just keep using v0.34.2. I reported it because it probably makes sense to check the changes made to parallelization in v0.34.3. I tried those two versions extensively and could only reproduce it on the latter.

There were no changes to "parallelization". I suspect you have a workspace with configs with hardcoded ports, but we can't do anything without a reproduction.

**Comment by leonheess** [comment]
Sorry, I can't find the time to set up a reproduction this week or next week. I added my vite config to the issue tho, hope that helps.

**Comment by vollmerr** [comment]
Is this maybe the same as my issue (https://github.com/vitest-dev/vitest/issues/4052)? Looks like it is trying to serve the dev server when you already have it running on that port.

**Comment by leonheess** [comment]
@vollmerr I think it is!! And because of a mono repo with lerna task parallelization it is clashing!!
