### ISSUE TITLE
happy dom environmentoptions in vite.config.ts don't work

### ISSUE THREAD

**Issue by Fallsleep** [vitest-dev/vitest#4040]
### Describe the bug

since https://github.com/vitest-dev/vitest/pull/3972 fixed `pass environmentOptions to happy-dom integration`,  set url by adding annotation before test file works well, but set url by `environmentoptions` in `vite.config.ts` file still has no effect.

It cause `window.location.href` to be the default `http://localhost:3000/`, and `document.cookie` is empty even  cookie was setting by `msw`

### Reproduction

https://stackblitz.com/edit/vitest-happy-dom-environmentoptions-test?file=test%2Fglobal.test.ts

`global.test.ts` failed, `annotation.test.ts` passed.

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 3.18 GB / 15.92 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - D:\nodejs\node_global\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 116.0.5845.97
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-legacy: ^2.1.0 => 2.1.0
    @vitejs/plugin-vue: ^3.1.0 => 3.1.0
    @vitejs/plugin-vue-jsx: ^2.0.1 => 2.0.1
    @vitest/coverage-v8: ^0.34.3 => 0.34.3
    @vitest/ui: ^0.34.3 => 0.34.3
    vite: ^3.1.0 => 3.1.0
    vitest: ^0.34.3 => 0.34.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It should be `happyDom` in the config, but even then it didn't work for me.

**Comment by Dunqing** [comment]
> It should be `happyDom` in the config, but even then it didn't work for me.

Should it be `happyDOM`? I tested it with `happyDOM` and all test cases passed

https://github.com/vitest-dev/vitest/blob/c48fef540ac685dee331df0330814042fc856580/packages/vitest/src/integrations/env/happy-dom.ts#L8

**Comment by sheremet-va** [comment]
> Should it be happyDOM? I tested it with happyDOM and all test cases passed

Yes, sorry. JS name is consistent with how happyDOM names it in its js API
