### ISSUE TITLE
Find a way to initialise optimizer without starting a server

### ISSUE THREAD

**Issue by sheremet-va** [vitest-dev/vitest#4042]
### Clear and concise description of the problem

Currently, we call `server.listen` to initialize a web optimizer - unfortunately, this has many side effects (like _starting a literal server_) that we do not need and might cause a loss in performance.

### Suggested solution

Investigate if it's possible to initialize optimizer without starting a Vite server.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by grigor-minasyan** [comment]
Just wanted to check what is the priority on this one, we ended up downgrading to `0.34.2` for the same reason, not sure why we need to start the server when testing, it also starts the server on the same port that the actual dev server is using, causing it to break the actual running server

**Comment by oldguan** [comment]
> Just wanted to check what is the priority on this one, we ended up downgrading to `0.34.2` for the same reason, not sure why we need to start the server when testing, it also starts the server on the same port that the actual dev server is using, causing it to break the actual running server

remove "server.strictPort: true"
works for me
