### ISSUE TITLE
vitest v0.34.3 tries to spawn browser

### ISSUE THREAD

**Issue by wyardley** [vitest-dev/vitest#4044]
### Describe the bug

Updating `vitest` to `v0.34.3`, running tests locally now seems to open a local browser window on port 3000, where previous versions did not. Is this an expected behavior change on a patch release?

edit: I did confirm that setting
```typescript
  server: {
    open: !process.env.CI,
  },
```
should avoid the problem, after noticing that the CLI docs have `!process.env.CI` as the default for the `--open` flag. (`    open: mode === 'development',` also will work).

However, I'm still not sure whether `vitest` should be reading the `server` flags and whether this behavior was expected to change on a patch update. It would also be super nice if `--open` had a negative option via `--no-open` or `--open=false` - if someone would be interested in implementing that, more than happy to open a feature request as a separate issue.

When running in CI, it's unable to do that, and spits out this error

```
node:events:492
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://localhost:3000/' ]
}

Node.js v18.17.1
```

### Reproduction

None provided at present - will see if we can come up with a generic repro.

in `vite.config.ts`:
```
  server: {
    open: true,
    host: 'localhost',
    port: 3000,
  },
```

### System Info

```shell
local:


  System:
    OS: macOS 13.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 346.38 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - /opt/homebrew/bin/node
    npm: 9.8.1 - ~/git/client-web/node_modules/.bin/npm
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 16.6
  npmPackages:
    @vitejs/plugin-react: 4.0.4 => 4.0.4 
    vite: 4.4.9 => 4.4.9 
    vitest: 0.34.2 => 0.34.2 
```

in CI env (CircleCI)
```
  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (36) x64 Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
    Memory: 50.90 GB / 68.57 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - ~/project/node_modules/.bin/npm
    pnpm: 8.7.0 - /usr/local/bin/pnpm
  npmPackages:
    @vitejs/plugin-react: 4.0.4 => 4.0.4 
    vite: 4.4.9 => 4.4.9 
    vitest: 0.34.3 => 0.34.3 
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Is this duplicate of https://github.com/vitest-dev/vitest/issues/4019?

**Comment by wyardley** [comment]
Thank you, yes, I did look, but somehow didn't come across that one. Appears to be a duplicate of #4019
