### ISSUE TITLE
`getTaskFullName()` includes leading space, breaking `testNamePattern`

### ISSUE THREAD

**Issue by jaswrks** [vitest-dev/vitest#4045]
### Describe the bug

The `getTaskFullName()` function injects a leading space when it detects a suite. However, a suite itself includes a `suite` property with an empty name, and therefore it runs twice on a suite. The end result is that every test inside a suite ends up with a full task name that has a leading single-space indentation, which breaks regular expression patterns like this:

```
--testNamePattern '^my-suite-prefix:'
```

I did finally get it working, by using this to account for the leading space.

```
--testNamePattern '^\s*my-suite-prefix:'
```

### Reproduction

```
--testNamePattern '^my-suite-prefix:'
```

Will not match a suite like this:

```
describe('my-suite-prefix:', () => { ... });
```

### System Info

```shell
Vitest 0.34.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jaswrks** [comment]
Problematic line:

https://github.com/vitest-dev/vitest/blob/0d0f35f6930c98e034bcf61a53ce21d3b63fdec2/packages/runner/src/utils/collect.ts#L49

**Comment by sheremet-va** [comment]
@segrey would you be ok with reintroducing #4071? Is Webstorrm ready for this change?
