### ISSUE TITLE
 vitest does not use typescript source for self-references or sub path imports #296 

### ISSUE THREAD

**Issue by everett1992** [vitest-dev/vitest#4046]
### Describe the bug

Subpath and self-reference imports are resolved to their literal values rather than the TypeScript source file.

```
  // package.json
  "name": "subpath-exports",
  "exports": {
    "./sub": "./dist/sub.js"
  },
  "imports": {
    "#sub": "./dist/sub.js"
  },
  ```
  
```
// src/index.ts
import "./sub.js"
import "subpath-exports/sub"
import "#sub"
```

`vitest` will resolve `#sub` and `subpath-exports/sub` to `./dist/sub.js`, not `./src/sub.ts`. This can cause module not found errors if dist has not been produced, or unexpected behavior if the dist/ is out of date and doesn't match the other source.

### Reproduction

https://github.com/everett1992/subpath-exports

### System Info

```shell
vitest@0.34.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by everett1992** [comment]
same bug in esbuild and tsx
https://github.com/evanw/esbuild/issues/3358

**Comment by sheremet-va** [comment]
How is this a bug? it's literally what you wrote in `package.json`. If you want different resolution, you can add a development condition for example:

```json
{
  "imports": {
    "#sub": {
       "development": "./src/sub.ts",
       "default": "./dist/sub.js"
     }
  }
}
```

**Comment by everett1992** [comment]
I'm not convinced. We also write `import './_.js'` and vitest will import `_.ts`. TypeScript resolves the self-references and sub path imports to typescript file. The algorithm it uses is simple - if a file is in outDir, replace outDir with srcDir and look for ts files.

**Comment by everett1992** [comment]
The development condition works for sub path imports in vitest, but does not work for self references.

```
  "exports": {
    "./sub": {
      "development": "./src/sub.ts",
      "default": "./dist/sub.js"
    }
  },
  "imports": {
    "#sub": {
      "development": "./src/sub.ts",
      "default": "./dist/sub.js"
    }
  },
```

```
describe('test sub-path imports', () => {
  it('relative', () => import('./sub.js'))
  it('imports', () => import('#sub'))
  it('self-reference', () => import('subpath-exports/sub'))
})
```

```
 ❯ src/index.test.ts (3)
   ❯ test sub-path imports (3)
     ✓ relative
     ✓ imports
     × self-reference

 FAIL  src/index.test.ts > test sub-path imports > self-reference
Error: Failed to load url subpath-exports/sub (resolved id: subpath-exports/sub) in /home/ANT.AMAZON.COM/calebev/github/subpath-exports/src/index.test.ts. Does the file exist?
 ❯ loadAndTransform node_modules/vite/dist/node/chunks/dep-df561101.js:
```

**Comment by sheremet-va** [comment]
> Where are the `development` condition, or the conditions vitest uses documented?

Vitest inherits Vite configuration: https://vitejs.dev/config/shared-options.html#resolve-conditions

> We also write `import './_.js'` and vitest will import `_.ts`. 

This is much easier to resolve since this is a relative import.

> TypeScript resolves the self-references and sub path imports to typescript file. The algorithm it uses is simple - if a file is in outDir, replace outDir with srcDir and look for ts files.

Vite doesn't use tsconfig for resolving paths. Vitest doesn't override Vite's implementation as it will create inconsistencies.

> The development condition works for sub path imports in vitest, but does not work for self references.

"subpath-exports/sub" is an import relative to the current file. Vite doesn't use tsconfig for module resolution by default.

As I said before, if you rely on tsconfig to resolve paths, use [vite-tsconfig-paths](https://github.com/aleclarson/vite-tsconfig-paths). If you want to have this built-in, open (or find already existing) an issue in Vite repo.

**Comment by everett1992** [comment]
> "subpath-exports/sub" is an import relative to the current file. 

No, it's a self reference import. It's like importing a package from node_modules and uses the `exports` map.
https://nodejs.org/api/packages.html#packages_self_referencing_a_package_using_its_name
