### ISSUE TITLE
Plugins: [react()] in defineConfig cause error Type 'PluginOption[]' is not assignable to type 'PluginOption'.

### ISSUE THREAD

**Issue by rickvian** [vitest-dev/vitest#4048]
### Describe the bug

i have vite.config.ts initially includes plugin: [react()]
but when i change it to use defineConfig from `vitest/config`
it shows squiggle error:

 Type 'PluginOption[]' is not assignable to type 'PluginOption'.

![Screen Shot 2023-08-30 at 17 03 12](https://github.com/vitest-dev/vitest/assets/8034141/9ecebdb7-52ec-4dd2-93a3-47927f6f9a0d)

### Reproduction

create vite app with react + SWC
install vitest,

change the import from  "vite" to "vitest/config"

```
/// <reference types="vitest" />
import react from "@vitejs/plugin-react-swc";
import { configDefaults, defineConfig } from "vitest/config";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    port: 3000,
  },
  base: "/order",
  build: {
    outDir: "./build",
  },
  resolve: {
    alias: {
      "@src": "/src",
    },
  },
});
```

### System Info

```shell
"@vitejs/plugin-react-swc": "^3.3.2",
    "vite": "^4.4.5",
    "vitest": "^0.34.1",
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Your package manager resolved your global Vite and Vitest Vite to different versions. Check your lockfile and resolve it.

**Comment by rickvian** [comment]
ok thanks, ill look into it

but i wonder why its happened in the first place? its a fresh create vite app and vitest setup

**Comment by rickvian** [comment]
hi @sheremet-va , i haven't look into resolving the version
but instead i split the config into `vite.config.ts` and `vitest.config.ts`

with this i wont type error (because defineConfig are different for test and vite config)

is this approach alright?

```

// vite.config.ts
import react from "@vitejs/plugin-react-swc";
import { defineConfig } from "vite";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    port: 3000,
  },
  ....
});
```

```
// vitest.config.ts
/// <reference types="vitest" />
import { configDefaults, defineConfig } from "vitest/config";

// https://vitejs.dev/config/
export default defineConfig({
  test: {
    //... some test config...
  },
});
```

**Comment by sheremet-va** [comment]
> is this approach alright?

Vitest config doesn't inherit Vite config, so you will need to merge it yourself.

**Comment by simon-abbott** [comment]
Just ran into this myself. In my case it was due to having `vitest` installed at the root of our monorepo and trying to install `@vitejs/plugin-react` inside one of the packages. Hoisting `@vitejs/plugin-react` to the root as well fixed the issue.

**Comment by giovannivocale-molar** [comment]
I get the same error on:
- `vitest@0.34.5`
- `vitest@0.34.4`

The error disappear if i downgrade to:
- `vitest@0.34.3`

I do not have `vite` in package.json. I'm on a Next Js app.

Thanks!

**Comment by noyoikw** [comment]
I avoided the warning this way.

```ts
/// <reference types="vitest" />

import react from "@vitejs/plugin-react";
import { UserConfig, defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [react()] as UserConfig["plugins"],
  ...
});
```

**Comment by sheremet-va** [comment]
This issue is always cause by the package manager installing different versions of Vite package. Make sure there are no multiple versions installed by running dedupe command for example (in pnpm it is `pnpm dedupe`). On Vitest side we cannot do anything unfortunately.
