### ISSUE TITLE
Workspace read project `vite.config.ts` files but not apply config to that project

### ISSUE THREAD

**Issue by cncolder** [vitest-dev/vitest#4050]
### Describe the bug

Vitest has read the `vite.config.ts` file under each projects. However, these configuration files did not take effect.

### Reproduction

Repo: https://github.com/cncolder/vitest-workspace-demo/tree/main

There are two projects `a` and `b` under workspace. Vite define `__DEV__` constant. If you run vitest in each projects. The test cases will passed.

If you run vitest in the root of workspace. You will find the `vite.config.ts` is loaded. But not used for replace the `__DEV__` constant.

### System Info

```shell
System:
    OS: macOS 13.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 346.25 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.asdf/installs/nodejs/lts/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/lts/bin/yarn
    npm: 9.6.7 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 7.18.1 - ~/.asdf/installs/nodejs/lts/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.110
    Edge: 116.0.1938.62
    Safari: 16.6
    Safari Technology Preview: 17.0
  npmPackages:
    vite: ^4.4.9 => 4.4.9 
    vitest: ^0.34.3 => 0.34.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Looks like it just doesn't pick up `defines` 🤔 Everything else is respected.
