### ISSUE TITLE
cannot run tests without opening broken dev server

### ISSUE THREAD

**Issue by vollmerr** [vitest-dev/vitest#4052]
### Describe the bug

After upgrading from vitest `^0.33.0` to `^0.34.3` when running any tests the dev server now opens, and in that dev server that is opened it fails to load the files.

Have tried setting the vite config to have test.open to false but still opens (which shows as default of true in the typedef file but false in https://vitest.dev/config/#open)

### Reproduction

https://codesandbox.io/p/sandbox/gallant-ptolemy-fjnjwr

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900HK
    Memory: 14.30 GB / 31.68 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-react: ^4.0.4 => 4.0.4
    @vitest/coverage-c8: ^0.33.0 => 0.33.0
    @vitest/ui: ^0.34.3 => 0.34.3
    vite: ^4.4.9 => 4.4.9
    vitest: ^0.34.3 => 0.34.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by donkeykong91** [comment]
I'm having the same problem.

**Comment by leonheess** [comment]
Same issue here!! We are blocked from upgrading because of this.

**Comment by jultabary** [comment]
Same here !

**Comment by CookedApps** [comment]
Same here after upgrading from `0.34.2` to `0.34.3`. We noticed that our CI pipelines kept failing because vitest always tries to open the browser (even tho the `CI` env variable is set). It also opens the browser every time on my local machine, despite setting various options to disable it.

**Comment by Dunqing** [comment]
I'm wondering if this problem is limited to Windows. i'm using macos and it doesn't happen.

**Comment by donkeykong91** [comment]
I'm using Windows; though, when I run this though a pipeline, the same error happens because it tries to open a browser during the pipeline run. We use RedHat Linux images.

**Comment by fh-igor-serko** [comment]
Chiming in, that this impacts me locally on MacOS as well as CI running Linux.
Downgrading to either `0.34.2` or `0.33.0` solved the problem.

Here's a portion of my `vite.config.ts`. If I comment out `server.open` the `vitest` will *not* open a browser window.
Something tells me vitest shouldn't be reading the `server` portion of the config, should it?

```
    ... snip ...
    server: {
        proxy: {
            "^/api": {
                target: "http://localhost:8080",
                changeOrigin: false,
                secure: false,
            },
        },
        strictPort: true,
        open: "http://localhost:8080",
    },
    test: {
        globals: true,
        environment: "jsdom",
        coverage: {
            reporter: ["text", "html"],
            exclude: [
                "node_modules/",
            ],
        },
    },
    ... snip ...
```

**Comment by vollyimnetz** [comment]
@fh-igor-serko thank you for investigating:

so a quick-and-dirty-fix for the old behaviour is:
```
//in vite.config.js
...
server: {
    port: 8080,
    open: process.env.NODE_ENV === 'test' ? false : true,
    ...
},
test: {
  ...
}

**Comment by Dunqing** [comment]
Thanks, guys, I was able to successfully reproduce the issue, and I'm currently working on a solution. I'll be submitting a PR to fix the issue soon
