### ISSUE TITLE
Typescript 5.1..6 - (node:40864) DeprecationWarning

### ISSUE THREAD

**Issue by ninichki** [vitest-dev/vitest#4055]
### Describe the bug

When I use Typescript 5.1.6

I get folowing warnings:

(node:40864) DeprecationWarning: The 'typeParameters' property is deprecated on CallExpression nodes. Use 'typeArguments' instead. See https://typescript-eslint.io/linting/troubleshooting#the-key-property-is-deprecated-on-type-nodes-use-key-instead-warnings

### Reproduction

Use typescript 5.1.6

### System Info

```shell
npmPackages:
    @vitejs/plugin-react: 4.0.4 => 4.0.4
    vite: ^4.4.9 => 4.4.9
    vitest: ~0.34.3 => 0.34.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
We don't have anything eslint-related. Are you sure this is caused by Vitest?

**Comment by ninichki** [comment]
Ok, now the deprecation warning moved away.
I've putted test config from vite.config.ts to vitest.config.test
But I don't know why.

Sorry for your circumstances

**Comment by Kamahl19** [comment]
@ninichki I suppose you are using `vite-plugin-checker`

Just do 
```
mode !== 'test' && checker()
```

**Comment by ninichki** [comment]
Yes I do, thanks for the inforamtion

**Comment by thraizz** [comment]
For me, it was the `vite-plugin-eslint` which was enabled in test mode, too.

Changed my config to:
```js
export default defineConfig((env) => ({
  // ...
  plugins: [
    env.mode !== "test" && eslint(), 
    // ...
    ],
  ```

The output is now without deprecation warnings.
