### ISSUE TITLE
Built-in waitFor and waitUntil

### ISSUE THREAD

**Issue by sheremet-va** [vitest-dev/vitest#4061]
### Clear and concise description of the problem

There are situations when it's not obvious when assertion will succeed because there is no way to track it (async operation performed inside a sync one). For this situation, community has come up with different solutions:

- https://www.npmjs.com/package/wait-for-expect
- https://www.npmjs.com/package/async-wait-until

### Suggested solution

I think it would be nice to provide these kinds of helpers in the core. 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
This would be really useful. I'm often writing `waitFor` utility when using Vitest in new project. 

Might want to look into https://github.com/testing-library/web-testing-library/issues/3 while implementing this.

**Comment by Dunqing** [comment]
I am interested in this. In which package should I add it?

**Comment by sheremet-va** [comment]
> I am interested in this. In which package should I add it?

It should probably be exposed on vi object.
