### ISSUE TITLE
Vitest 0.34.3 reports type errors for autoimported Vue functions

### ISSUE THREAD

**Issue by Ragura** [vitest-dev/vitest#4074]
### Describe the bug

Since upgrading from `0.34.2` to `0.34.3` all our tests fail due to type errors related to built-in Vue functions that are normally auto-imported.

[Minimal reproduction](https://stackblitz.com/edit/vitejs-vite-depxyd?file=src%2Fcomponents%2FHelloWorld.vue)
Simply run `pnpm vitest`.

Full description of the issue in our project:
The bug is triggered when a test imports a Vue component, for example:
```ts
import TheCounter from './TheCounter.vue'
```
It never even gets to the test code in the test file, the import alone is enough to trigger the error.

The error reads as follows: `TypeError: defineComponent is not a function`.
This also happens with all other Vue components, but the error can differ, for example: `TypeError: ref is not a function` or like in the reproduction: `createTextVNode is not a function`. There are variations of this depending on what is present in the template.

I have the following packages installed that might be relevant (are also installed in the reproduction):
```
"unplugin-auto-import": "^0.16.6",
"unplugin-vue-components": "^0.25.2",
"vue-tsc": "^1.8.8",
"@vue/test-utils": "^2.3.2",
"@pinia/testing": "^0.1.2",
"@testing-library/vue": "^7.0.0",
"typescript": "5.2.2",
"jsdom": "^22.1.0",
```

This is our `tsconfig.json` as part of a monorepo setup:
```
{
  "compilerOptions": {
    "module": "ESNext",
    "target": "ESNext",
    "moduleResolution": "bundler",
    "lib": [
      "DOM",
      "ESNext",
      "DOM.Iterable"
    ],
    "rootDir": ".",
    "types": [
      "vite/client",
      "unplugin-icons/types/vue",
      "@intlify/unplugin-vue-i18n/messages"
    ],
    "isolatedModules": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "jsx": "preserve",
    "jsxImportSource": "vue",
    "resolvePackageJsonExports": false,
    "strict": true,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "strictPropertyInitialization": true,
    "forceConsistentCasingInFileNames": true,
    "verbatimModuleSyntax": true,
    "useDefineForClassFields": true,
    "noErrorTruncation": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "composite": true,
  },
"include": [
    "vite.config.ts",
    "auto-imports.d.ts",
    "components.d.ts",
    "vite.config.ts",
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.vue",
    "typed-router.d.ts"
  ],
  "exclude": [
    "dist",
    "node_modules"
  ],
  "paths": {
    "@apps/*": [
      "apps/*/src"
    ],
    "@packages/*": [
      "packages/*/src"
    ]
  },
}
```

Hopefully this has provided enough information to resolve the issue. If not, let me know what you need and I'll test it!

### Reproduction

https://stackblitz.com/edit/vitejs-vite-depxyd?file=src%2Fcomponents%2FHelloWorld.vue

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 386.95 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.140
    Safari: 16.5
  npmPackages:
    @vitejs/plugin-vue: ^4.3.4 => 4.3.4 
    @vitest/ui: ^0.31.4 => 0.31.4 
    vite: ^4.4.9 => 4.4.9 
    vitest: 0.34.3 => 0.34.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You can add `vue` to `optimize.exclude` to bypass that for now:

```ts
export default defineConfig({
  test: {
    deps: {
      optimizer: {
        web: {
          exclude: ['vue'],
        },
      },
    },
  },
})
```

**Comment by filipgutica** [comment]
I'm getting the same errors on all minor versions of `0.34.x` 
Seeing `computed is not a function` if I reference these vue functions.
![image](https://github.com/vitest-dev/vitest/assets/6026470/387f7a1a-6b20-4d8f-a29a-345d7a880ff7)

Downgrading to v0.33.0 works for me.

**Comment by adamdehaven** [comment]
@antfu or @sheremet-va is there a way to prioritize this issue? It's blocking any upgrade of `vitest` after `0.34.2`

**Comment by oktaykaypak** [comment]
is there an update for this problem?

**Comment by sheremet-va** [comment]
There is a workaround in https://github.com/vitest-dev/vitest/issues/4074#issuecomment-1711558865

You can also disable optimizers for tests for now:

```ts
export default defineConfig({
  test: {
    deps: {
      optimizer: {
        web: {
          enabled: false,
        },
      },
    },
  },
})
```

**Comment by sheremet-va** [comment]
Cannot reproduce the error on the latest version. Feel free to create a new issue with another reproduction if you have a similar bug.
