### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by zerosrat** [vitest-dev/vitest#4079]
### Describe the bug

![image](https://github.com/vitest-dev/vitest/assets/8179987/117a91d4-6e16-4a27-97cd-553fad631a00)

I tried to add `deps.inline` but it did not work.

```
 deps: {
  inline: [
    "@sgfe/empower-app-context"
  ]
}
```

It is common that 3rd part lib use import ES Module in CommonJS package. As a result, it is common that developers encounter `SyntaxError: Unexpected token 'export'`.

I wander it there any way to avoid this problem.

### Reproduction

-

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.25 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.21.3/bin/yarn
    npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
  Browsers:
    Chrome: 116.0.5845.140
    Edge: 116.0.1938.69
    Safari: 16.5
  npmPackages:
    @vitejs/plugin-react: ^4.0.3 => 4.0.3 
    @vitest/coverage-v8: ^0.33.0 => 0.33.0 
    @vitest/ui: ^0.33.0 => 0.33.0 
    vite: ^4.4.7 => 4.4.7 
    vitest: ^0.33.0 => 0.33.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
The problem here is with the library that imports this (I don't know which one). Try inlining it instead.

**Comment by zerosrat** [comment]
@sheremet-va 
I update vitest to 0.34.2.
I find `@sgfe/use-permission` uses `require("@sgfe/empower-app-context")` to load `@sgfe/empower-app-context`. Therefore I inline both lib and the config is as below.

```js
test: {
    ...
    server: {
        deps: {
            inline: [
                '@sgfe/empower-app-context',
                '@sgfe/use-permission',
            ],
        },
    },
}
```


But the problem is still here.
![image](https://github.com/vitest-dev/vitest/assets/8179987/f3623a92-eea9-4845-80b6-9c3614d3c78b)

**Comment by sheremet-va** [comment]
1. Do you import `@sgfe/use-permission` directly? Does it bundle ESM entry? Is it in `exports` field?
2. Why does `@sgfe/use-permission` uses `require` syntax if it publishes ESM?

I have a feeling that you control this dependency. It is clearly bundled incorrectly - because it uses `require` to import ESM dependency. I would recommend looking into what code is produced.

**Comment by zerosrat** [comment]
You are correct. The bundle has been incorrectly packaged; this is a private bundle developed by my team.
If vitest doesn't support mixed bundled packages, all of the incorrectly bundled packages need to be fixed. The workload is relatively large, and I am concerned about the impact of changing the packaging method.

**Comment by sheremet-va** [comment]
1. There is 0 reason to bundle CJS that imports ESM - it just not meant to work, you shoot yourself in the foot
2. You can try adding your packages to `deps.optimizer.web.include`, but again you need to have the whole chain of packages that import each other there

**Comment by zerosrat** [comment]
Thanks sheremet, there is another question as followed.

<img width="1153" alt="image" src="https://github.com/vitest-dev/vitest/assets/8179987/df376a6f-fd1f-4686-8bbc-ebecb99b6c23">

The problem is `@sfe/wand`(commonjs) loads `lodash-es`(esm).

`@sfe/wand` is also a private package. We can see vitest loads it using commonjs. However the package is also builded with esm and vitest load the lib folder not esm folder.

<img width="200" alt="image" src="https://github.com/vitest-dev/vitest/assets/8179987/9716257f-4047-438e-ad4b-56f73c29f132">

And the main and module field of package.json is:
```json
  "main": "lib/index.js",
  "module": "es/index.js",
  "typings": "es/index.d.ts",
```

I wonder what the logic of loading package is -- using esm or  cjs. And is there any problem with `@sfe/wand`?

**Comment by sheremet-va** [comment]
> And the main and module field of package.json is:

I recommend using this tool to check if your package has the correct package.json: https://publint.dev

From your example, it looks like you use the "module" field which is not supported by Node.js. You should use `exports` field to map entry points. Another potential issue is the wrong extension. Node.js doesn't support both extensions at the same time - you need to have a package.json with `{"type":"module"}` for Node.js to correctly load a module. Vitest bypasses it if the package is imported directly, but it will not work if package is loaded by another package.

**Comment by zerosrat** [comment]
@sheremet-va Thanks for your reply, sheremet. I wonder are there any similar probs in Jest?

**Comment by sheremet-va** [comment]
> @sheremet-va Thanks for your reply, sheremet. I wonder are there any similar probs in Jest?

Jest runs in Node.js, so yes.
