### ISSUE TITLE
The position of a variable caused the test run to fail, which is strange

### ISSUE THREAD

**Issue by hengshanMWC** [vitest-dev/vitest#4100]
### Describe the bug

[project](https://github.com/hengshanMWC/pkgs/commits/fix-agent)
npm run test
commit: 8416bbe585cf90db80520fb1d30e9adb2b6a0d37
<img width="483" alt="image" src="https://github.com/vitest-dev/vitest/assets/45714422/31e82003-a840-4180-9014-7d32fa98631c">

switch to
commit: 37810d1e6576aa10673def6654a4727da4d41d91
Normal performance

Adjusting the location of the **enum Agent** from **src/constant.ts** to **src/command/type**. ts will result in an error, which is unimaginable. Let's explore it
<img width="1409" alt="image" src="https://github.com/vitest-dev/vitest/assets/45714422/f0f5d55f-64ec-468c-ae9f-143bff068682">

### Reproduction

[project](https://github.com/hengshanMWC/pkgs/commits/fix-agent)

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (8) arm64 Apple M1
    Memory: 238.84 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 9.7.1 - ~/.nvm/versions/node/v18.12.1/bin/npm
    pnpm: 7.21.0 - ~/.nvm/versions/node/v18.12.1/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.179
    Safari: 14.1.1
  npmPackages:
    @vitest/coverage-v8: ^0.32.0 => 0.32.0 
    vite: ^4.3.9 => 4.3.9 
    vitest: ^0.32.0 => 0.32.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hengshanMWC** [comment]
I don't know why this problem arises

**Comment by sheremet-va** [comment]
This is probably caused by the cyclic dependencies. Check that you don't have any cyclic imports, this is an issue with how vite-node runs the code.
