### ISSUE TITLE
Support `--env-file` flag

### ISSUE THREAD

**Issue by MatanYadaev** [vitest-dev/vitest#4102]
### Clear and concise description of the problem

As a developer using Vitest I want to set environment variables in a `.env` file without using third-party packages like `dotenv`.

### Suggested solution

A `--env-file`/`envFile` flag that tells Vitest which file to import environment variables from. It's a built-in feature in [Node v20.6.0](https://nodejs.org/en/blog/release/v20.6.0#built-in-env-file-support).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
We already support reading from .env: https://vitejs.dev/config/shared-options.html#envdir
