### ISSUE TITLE
Tree Shaking not supported for MUI components

### ISSUE THREAD

**Issue by gsriram24** [vitest-dev/vitest#4105]
### Describe the bug

While running tests in a project containing MUI, for some reason the test cases were being very slow. 

Digging deeper using a chrome profiler, I found out that even for tests that import only one or two components from MUI/MUI Icons, the entire library is imported. And this takes over 50% of the test execution time. 

Would it be possible to support treeshaking and import the components that are only being used in the given file? 

If I convert the imports to default imports instead of names imports, the test cases are much faster. (2-3x)

Eg. 
`import { LoadingButton } from "@mui/lab"; //Test cases are very slow. Entire @mui/lab is imported` 
`import LoadingButton from "@mui/lab/LoadingButton"; //Test cases are much faster. Only LoadingButton is imported and not the entire package` 

### Reproduction

Any vite project with `@mui` installed.

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz
    Memory: 5.85 GB / 15.61 GB
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-react: ^4.0.1 => 4.0.1
    @vitest/coverage-v8: ^0.33.0 => 0.33.0
    @vitest/ui: ^0.33.0 => 0.33.0
    vite: ^4.3.9 => 4.4.9
    vitest: ^0.33.0 => 0.33.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Tree Shaking is a bundler feature, it is impossible to do in runtime (if you looks at the response in the browser from Vite dev server, you will also see that it's not tree shaken). This is a famous foot gun.

Use "package/sub-path" syntax or add the package in question to `deps.optimizer.web.include` to bundle the whole package into a single file.
