### ISSUE TITLE
Since v0.34.4 Yarn installs two different versions of Vite.

### ISSUE THREAD

**Issue by jgerigmeyer** [vitest-dev/vitest#4112]
### Describe the bug

[This PR](https://github.com/vitest-dev/vitest/pull/4015) in v0.34.4 introduced a union operator (`||`) for the Vite dependency to include support for Vite v5.0. Because of [how Yarn handles union operators](https://github.com/yarnpkg/yarn/issues/8243), this means that any Yarn project specifying a dependency on Vite v4 and Vitest v0.34.4 will end up with two different versions of Vite installed.

In other words, this `package.json`:

```json
{
  "dependencies": {
    "vite": "^4.4.9"
  },
  "devDependencies": {
    "vitest": "^0.34.4"
  }
}
```

Results in this output from `yarn why vite`:

```
➜ yarn why vite
├─ root-workspace-0b6124@workspace:.
│  └─ vite@npm:4.4.9 [dc3fc] (via npm:^4.4.9 [dc3fc])
│
├─ vite-node@npm:0.34.4
│  └─ vite@npm:4.4.9 [dc3fc] (via npm:^4.4.9 [dc3fc])
│
├─ vitest@npm:0.34.4
│  └─ vite@npm:5.0.0-beta.1 (via npm:^3.1.0 || ^4.0.0 || ^5.0.0-0)
│
└─ vitest@npm:0.34.4 [dc3fc]
   └─ vite@npm:5.0.0-beta.1 [1bd26] (via npm:^3.1.0 || ^4.0.0 || ^5.0.0-0 [1bd26])
```

### Reproduction

https://github.com/jgerigmeyer/vitest-vite-version

### System Info

```shell
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 112.77 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.0.0 - ~/.nvm/versions/node/v20.0.0/bin/node
    Yarn: 3.6.3 - ~/.yarn/bin/yarn
    npm: 9.6.4 - ~/.nvm/versions/node/v20.0.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.179
    Chrome Canary: 119.0.6002.0
    Firefox: 115.0.2
    Safari: 16.6
  npmPackages:
    vite: ^4.4.9 => 4.4.9
    vitest: ^0.34.4 => 0.34.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by belgattitude** [comment]
Could see as well (yarn 4rc50) although it doesn't break my tests.

```json
    "vite": "4.4.9",
    "vitest": "0.34.4",
```

```
yarn why vite

├─ vite-node@npm:0.34.4
│  └─ vite@npm:4.4.9 [df6da] (via npm:^3.0.0 || ^4.0.0 [df6da])
│
├─ vitest@npm:0.34.4
│  └─ vite@npm:5.0.0-beta.1 (via npm:^3.1.0 || ^4.0.0 || ^5.0.0-0)
│
├─ vitest@npm:0.34.4 [5f667]
│  └─ vite@npm:5.0.0-beta.1 [f68a6] (via npm:^3.1.0 || ^4.0.0 || ^5.0.0-0 [f68a6])
│
└─ web@workspace:.
   └─ vite@npm:4.4.9 [5f667] (via npm:4.4.9 [5f667])

```

**Comment by pongells** [comment]
yeah, it's been happening for a while, seemingly random... very annoying.. as a workaround you can fix the version of vite via `resolutions` 

```
  "resolutions": {
    "vite": "4.4.9"
  },
```

**Comment by sheremet-va** [comment]
I am honestly not sure how package managers resolve this, but since this is the correct semver string, I would assume they support it.

I am open to any changes that would fix this problem.

**Comment by sheremet-va** [comment]
Vitest doesn't use `||` in the version anymore.
