### ISSUE TITLE
Fails to run tests with federated module

### ISSUE THREAD

**Issue by artem-tarasenko** [vitest-dev/vitest#4121]
### Describe the bug

Hey folks, I found a problem that I don't know how to solve. I'm using module federation (@originjs/vite-plugin-federation) to get a remote module with routes for the react router and since I've added config my tests a failing,

Here is my config:

```  
    federation({
            name: 'host',
            remotes: {
                remote: `https://domain.com/community/assets/community-feed.js`,
            },
            shared: ['react', 'react-router-dom'],
    }),
```
and when I run the tests I got this error: 
```
Error: Failed to load url https://domain.com/community/assets/community-feed.js (resolved id: https://domain.com/community/assets/community-feed.js). Does the file exist?
 ❯ loadAndTransform node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21
```

One more thing to mention is that I do not use lazy loading to get the remote module since it has route configs that I use in the parent router. If I switch to lazy loading and mock imported module tests are okay (but I cannot use that approach).

Normally I'm mocking network requests with MSW but this request seems to be out of reach.
Needless to say, the remote entry file is accessible.

So is there any way to work around it and get my test working?

### Reproduction

-

### System Info

```shell
"vitest": "^0.34.1"
"Node.js": v18.16.1
"vite": "^4.4.9",
"@originjs/vite-plugin-federation": "^1.2.3",
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Can't help without a reproduction. Do you use separate configs? Do you have something (a plugin) to process external imports?
