### ISSUE TITLE
Vite fails to handle `tmp`

### ISSUE THREAD

**Issue by innocenzi** [vitest-dev/vitest#413]
### Describe the bug

I was trying to test a file that uses [`tmp`](https://github.com/raszi/node-tmp), and ran into the following issue:

```
- test/resolve.test.ts [ test/resolve.test.ts ]
TypeError: Object.defineProperty called on non-object
 ❯ ../../node_modules/.pnpm/tmp@0.2.1/node_modules/tmp/lib/tmp.js:763:8
 ❯ directRequest ../../../../../../../file:/D:/Code/projects/preset/preset/node_modules/.pnpm/vitest@0.0.112_vite@2.7.10/node_modules/vitest/dist/worker.js:9471:11
 ❯ async cachedRequest ../../../../../../../file:/D:/Code/projects/preset/preset/node_modules/.pnpm/vitest@0.0.112_vite@2.7.10/node_modules/vitest/dist/worker.js:9500:12
 ❯ async src/resolve.ts:5:31
      3| import tmp from 'tmp'
      4| import git from 'simple-git'
      5| import type { LocalDirectoryPreset, RepositoryPreset, ApplyOptions, LocalFilePreset } from './types'
       |                               ^
      6| import { debug } from './utils'
      7| 
 ❯ async directRequest ../../../../../../../file:/D:/Code/projects/preset/preset/node_modules/.pnpm/vitest@0.0.112_vite@2.7.10/node_modules/vitest/dist/worker.js:9471:5
 ❯ async cachedRequest ../../../../../../../file:/D:/Code/projects/preset/preset/node_modules/.pnpm/vitest@0.0.112_vite@2.7.10/node_modules/vitest/dist/worker.js:9500:12
 ❯ async test/resolve.test.ts:5:31
```

The issue is that [`tmp`](https://github.com/raszi/node-tmp) has the following snippet, which fails because `module.exports` is not what Vitest expects: 

```js
Object.defineProperty(module.exports, 'tmpdir', {
  enumerable: true,
  configurable: false,
  get: function () {
    return _getTmpDir();
  }
});
```

Multiple notes here: 
- I couldn't reproduce on StackBlitz (the test passes apparently)
- The trace doesn't point to the right line of code
- Locally, I am on a `pnpm` monorepository
- **When I run `vitest` with `--no-threads`, I don't even have an error, the file is completely ignored. If I use `--threads`, I get the error I pasted above.** I have no idea why, at first I thought there was an issue with my filter.

I think that last point should be an issue on its own.

### Reproduction

I couldn't reproduce on StackBlitz but if required I'll host my code on GitHub and link it.

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 7.64 GB / 15.93 GB
  Binaries:
    Node: 16.13.1 - D:\Programmes\Laragon\bin\nodejs\node-v16.13.1\node.EXE
    Yarn: 1.22.17 - D:\Programmes\Laragon\bin\nodejs\node-v16.13.1\yarn.CMD
    npm: 8.1.2 - D:\Programmes\Laragon\bin\nodejs\node-v16.13.1\npm.CMD
  Browsers:
    Chrome: 96.0.4664.110
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.62)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    vite: ^2.7.10 => 2.7.10
    vitest: ^0.0.125 => 0.0.125
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Same as this: https://github.com/vitest-dev/vitest/issues/393

**Comment by sheremet-va** [comment]
Fixed it https://github.com/vitest-dev/vitest/releases/tag/v0.0.139

No workaround is necessary.
