### ISSUE TITLE
Importing toMatchImageSnapshot together with browser mode crashes

### ISSUE THREAD

**Issue by jnsmalm** [vitest-dev/vitest#4147]
### Describe the bug

The test immediately crashes/fails when importing 'toMatchImageSnapshot' from 'jest-image-snapshot'.

### Reproduction

*mytest.test.ts*
```
import { test } from 'vitest'

// Uncomment this line and the test passes
import { toMatchImageSnapshot } from 'jest-image-snapshot' 

declare module 'vitest' {
  interface Assertion<T> {
    toMatchImageSnapshot(): T
  }
}

test('should not crash', () => {
  //
})
```

*vite.config.ts*
```
import { defineConfig } from 'vite'

export default defineConfig({
  test: {
    browser: {
      enabled: true,
      name: 'chrome',
    },
  }
})
```

### System Info

```shell
System:
    OS: macOS 13.5.2
    CPU: (8) arm64 Apple M1
    Memory: 298.13 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Why wouldn't it? `jest-image-snapshot` uses Node.js-specific APIs.

Is the problem that you don't see the error or?

**Comment by jnsmalm** [comment]
I see, I didn't realise that it was Node.js API.

Is there any other way I can take a snapshot in the browser? I need the browser to do some WebGL rendering, then I want to compare that rendered image to a snapshot, possible?
