### ISSUE TITLE
Allow to exclude test files with cli

### ISSUE THREAD

**Issue by jonatan-zint-tfs** [vitest-dev/vitest#4148]
### Clear and concise description of the problem

I have the following use case for an exclude flag in the vitest cli:

We have a codebase with some unit tests using vitest in `./src/`
Alongside this code base there are some integration tests sharing the dto interfaces from `./src/`. The integration tests are in `./tests/api/` and use their own vitest config in `./tests/api/vitest.config.ts`.

We use `lint-staged` to execute relevant tests with `vite related` like the [docs suggest](https://vitest.dev/guide/cli.html#vitest-related).

However - those integration tests should not run in our commit hook due to their fragile nature. So I'd like to pass an exclude flag like so `vitest related --exclude './tests/api/**'`.

I couldn't find a solution with the already available CLI options. `-t` will only work on test names, but I want to exlude *files*.

### Suggested solution

Introduce an `--exclude` that'll exclude all tests matching a regex pattern in this CLI run. It'll override any exclude/include pattern from the vitest config files.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Namchee** [comment]
@sheremet-va , may I tackle this issue?
