### ISSUE TITLE
vitest/ui coverage page have invalid iframe url when running on preview mode (pre-generated report)

### ISSUE THREAD

**Issue by akcyp** [vitest-dev/vitest#4149]
### Describe the bug

UI converage page works well in "test development mode", but fails to load on generated report (after running `vite preview --outDir html`).
Root cause: https://github.com/vitest-dev/vitest/blob/main/packages/ui/client/composables/navigation.ts#L22

![image](https://github.com/vitest-dev/vitest/assets/67923777/6f8545d7-b579-4c08-a01f-249b5500f3e8)

Another minor issue:
`CI=true vitest --ui` should **not** open browser

### Reproduction

```ts
import { defineConfig } from "vitest/config";
export default defineConfig({
  test: {
    coverage: {
      enabled: true,
      reporter: ['html'],
      reportsDirectory: 'html/coverage',
      provider: 'istanbul',
      all: true,
    },
    reporters: ['html'],
  },
});
```
```json
# package.json
{
  "scripts": {
    "test": "vitest",
    "preview": "vite preview"
  }
}
```

```sh
CI=true bun run test --ui
bun run preview --outDir html
```

Also it would be nice to have iframe url somehow obtained from `coverage.reportsDirectory`, for example if `coverage.reportsDirectory` is located under `<rootDir>/html` (vitest html reporter root dir), then relative url is calculated.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
    Memory: 5.32 GB / 7.63 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
  npmPackages:
    @vitest/browser: ^0.34.4 => 0.34.4 
    @vitest/coverage-istanbul: ^0.34.4 => 0.34.4 
    @vitest/ui: ^0.34.4 => 0.34.4 
    vite: ^4.4.5 => 4.4.9 
    vitest: ^0.34.4 => 0.34.4 
```

### Used Package Manager

bun

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kitsun-ho** [comment]
I'm having the same problem as you.
When executing `vitest --ui`, the port of vitest ui  !=  the port of iframe, after I corrected the iframe port in F12, it can be displayed, but I don't know how to fix it in setting.

![截圖 2023-11-01 上午11 39 11](https://github.com/vitest-dev/vitest/assets/50700283/8719c74b-ee98-48a0-9d9e-8af3c2fb8f53)

```typescript
// vite.config.ts

test: {
  include: ['**/*.{test,spec}.?(c|m)[jt]s?(x)'],
  environment: 'jsdom',
  globals: true,
  alias: {
    '@': fileURLToPath(new URL('./src', import.meta.url)),
  },
  coverage: {
    provider: 'istanbul',
    enabled: true,
    reportOnFailure: true,
    perFile: true,
  },
},
``` 
```json
// package.json

"scripts": {
  "test:unit-ui": "vitest --ui",
  "test:unit": "vitest",
  "test:unit-report": "vitest run --coverage"
},
```

**Comment by kitsun-ho** [comment]
I think I found a solution, setting `test.api`, It look like the port is occupied.
```typescript
// vite.config.ts

test: {
  include: ['**/*.{test,spec}.?(c|m)[jt]s?(x)'],
  environment: 'jsdom',
  globals: true,
  api: 51205,
  alias: {
    '@': fileURLToPath(new URL('./src', import.meta.url)),
  },
  coverage: {
    provider: 'istanbul',
    enabled: true,
    reportOnFailure: true,
    perFile: true,
  },
},
```
