### ISSUE TITLE
Pass context from test/it to beforeEach

### ISSUE THREAD

**Issue by vim-daniel** [vitest-dev/vitest#4153]
### Clear and concise description of the problem

When writing tests usually you have some setup logic in the beforeEach that you want to run for each test,

For example, in this test i want each test to provide a different width, height to the url
```
beforeEach((context) => {
    jsdom = new JSDOM(
      html`
        <!DOCTYPE html>
        <html>
          <body>
            <div id="root"></div>
          </body>
        </html>
      `,
      {
        url: `http://localhost:3000/launch-button.html?width=${context.width }&height=${context.height}`,
      },
    );
```

### Suggested solution

If it could be possible to do something like this:
```
it.extend({ width: 200, height: 200 })(
    'when height & width are big should render with large class',
    async () => {
        ...
    });
```

That the `beforeEach` context will contain the context from the `it.extend`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Vitest will start passing down context from `it.extend` in the next version #4065
