### ISSUE TITLE
Including tests from different directories is broken in vitest 0.34.*

### ISSUE THREAD

**Issue by NicolasFrossard** [vitest-dev/vitest#4157]
### Describe the bug

Hello, and thank you for reading.

I have been using vitest `0.33.0` with the `happy-dom` environment. 

- I have a multi-projects structure, every project containing tests.
- One of the projects is running the tests of all the other projects. This project contains the `vite.config.ts` with the following `include` to ensure running all tests: `include: [...configDefaults.include, '../**/*.test.ts']`

It's working great, but as soon as I upgrade to vitest `0.34.0` or higher it doesn't work.

I have read the doc and the release notes, but I don't see why it stopped working. 

### Reproduction

- `npm init vue@3` to generate a base project (say "No" to all, except for vitest tests)
- Set `vitest` to version `0.34.5`
- Create a new simple test to an **external directory**, for example `../SimpleTest.spec.js`:

```
import {expect, test} from 'vitest'

test('simpleTest', async () => {
  expect(1).toEqual(1)
})
```

- In `vitest.config.js`, add `include` to target specifically this test:

```
defineConfig({
    test: {
      ...
      include: ['../SimpleTest.spec.js']
    }
  })
```

- `npm run test:unit`

**Expected results**

The test is successfully executed.  This is the case if I downgrade `vitest` to the version `0.33.0` OR if I set `environment: 'node'`. In `jsdom` or `happy-dom` environments, the test fails (see below).

**Actual results**

```
 DEV  v0.34.5 /Users/nico/sandbox/vitest-bug-2/test

 ❯ ../SimpleTest.spec.js (0)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  ../SimpleTest.spec.js [ ../SimpleTest.spec.js ]
Error: Failed to load url /Users/nico/sandbox/vitest-bug-2/SimpleTest.spec.js (resolved id: /Users/nico/sandbox/vitest-bug-2/SimpleTest.spec.js). Does the file exist?
 ❯ loadAndTransform node_modules/vite/dist/node/chunks/dep-df561101.js:54939:21

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  no tests
   Start at  17:32:08
   Duration  350ms (transform 13ms, setup 0ms, collect 0ms, tests 0ms, environment 222ms, prepare 49ms)


 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
Cancelling test run. Press CTRL+c again to exit forcefully.

```

Note: the file path indicated in the error message is valid (the file does exist).

### System Info

```shell
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 480.17 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 117.0.5938.88
    Safari: 16.6
  npmPackages:
    @vitejs/plugin-vue: ^4.3.4 => 4.3.4
    vite: ^4.4.9 => 4.4.9
    vitest: ^0.34.5 => 0.34.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
All tests that use browser API also have limited access to the file system. Vitest allows files in the same directory the config is by default. You can disable this with `server.fs.strict: false` or add your directory to `server.fs.allow`:

```ts
export default defineConfig({
  server: {
    fs: {
      // either or
      strict: false,
      allow: ['../']
    }
  }
})
```

**Comment by NicolasFrossard** [comment]
Thanks a lot @sheremet-va! Now I understand and the issue is fixed.
