### ISSUE TITLE
vi.mock and await import('...') do not seem isolated from tests in the same file

### ISSUE THREAD

**Issue by Hideman85** [vitest-dev/vitest#4161]
### Describe the bug

I am having the issue to have quite some small tests in one file importing the same json even doing a copy before modifying the data but the modification impact all the tests in the same file.

I have no clue if I am doing something wrong or I did miss a concept, I even try to reset mocks/modules but without chance. from my side it seem to be a test isolation issue and feel free to correct me if I'm wrong 🙏

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-jbytfs?file=test%2Fbasic3.test.ts

### System Info

```shell
╰─ npx envinfo --system --npmPackages '{vitest,@vitest/*,vite,@vitejs/*}' --binaries --browsers

  System:
    OS: Linux 6.2 Ubuntu 23.04 23.04 (Lunar Lobster)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 12.09 GB / 31.13 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - /usr/bin/node
    Yarn: 3.2.1 - /usr/bin/yarn
    npm: 9.6.7 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  Browsers:
    Chrome: 117.0.5938.88
  npmPackages:
    @vitest/coverage-v8: ~0.34.3 => 0.34.4 
    @vitest/ui: ~0.34.3 => 0.34.4 
    vitest: ~0.34.3 => 0.34.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`vi.mock` is hoisted, so only one your mock is executed: https://vitest.dev/api/vi.html#vi-mock
