### ISSUE TITLE
Vitest/Electron - mocking Electron with `doMock` fails, but `mock` succeeds

### ISSUE THREAD

**Issue by DoodleBobBuffPants** [vitest-dev/vitest#4166]
### Describe the bug

If I mock the `electron` module using `doMock` as in the code snippet below, it doesn't work, and the exports are all undefined

```typescript
vi.doMock("electron", () => ({
  app: {
    isPackaged: true
  }
}));

// import something that imports app from electron for testing
```

If I try using `app`, it is undefined

If I use `vi.mock` instead however, it works. Whilst it's there as a workaround, I'd like to not use it and stick to `doMock`, as hoisting comes with its own drawbacks (cannot use variables, and there's some additional cognitive load associated with hoisting)

### Reproduction

Reproduction is zipped below (there were issues with using electron in StackBlitz). Instructions are in the `README.md`

[vitest-electron-mocking-bug.zip](https://github.com/vitest-dev/vitest/files/12701702/vitest-electron-mocking-bug.zip)

### System Info

```shell
System:
  OS: Windows 10 10.0.22621
  CPU: (24) x64 12th Gen Intel(R) Core(TM) i7-12850HX
  Memory: 17.11 GB / 31.69 GB
Binaries:
  Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
  npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.36)
npmPackages:
  vite: 4.4.9 => 4.4.9
  vitest: 0.34.5 => 0.34.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
The difference between `vi.mock` and `vi.doMock` is described in the documentation: https://vitest.dev

`vi.mock` is hoisted automatically and executed BEFORE your imports. `vi.doMock` is not hoisted, so you need to use `await import` syntax. If you want to use `doMock`, you need to import `./source` using `await import` because all static imports are hoisted and executed before user code even if you put it before.

**Comment by sheremet-va** [comment]
If you rely on variables outside of the scope, you can use `vi.hoisted` which is hoisted even higher than `vi.mock`:

```ts
const value = vi.hoisted(() => vi.fn())
vi.mock('./path', () => {
  return { method: value }
})
```

**Comment by DoodleBobBuffPants** [comment]
> The same as [vi.mock](https://vitest.dev/api/vi.html#vi-mock), but it's not hoisted at the top of the file, so you can reference variables in the global file scope. The next import of the module will be mocked. This will not mock modules that were imported before this was called.

What you said is fair, but perhaps the docs could be clearer about them _needing_ to be `await import`

**Comment by sheremet-va** [comment]
It says:

> The next import of the module will be mocked. This will not mock modules that were imported before this was called.

All imports are hoisted and executed before anything else - this is just how ESM works. Are you having problems with this specifically? PR is welcome to improve documentation.

**Comment by DoodleBobBuffPants** [comment]
The problem is that this used to work, hence why I've not raised a PR to improve the docs yet - after changing the versions of `vite` and `vitest` in the `package.json` in the ZIP to:

```json
"vite": "4.1.4",
"vitest": "0.34.3"
```

The same test will pass if you use a regular `import` and not `await import`

**Comment by sheremet-va** [comment]
This used to work in old Vite version due to a bug. It now follows ESM spec correctly.

**Comment by DoodleBobBuffPants** [comment]
That's fair, though it is a breaking change. For now I think it might make sense to update the docs for `vi.doMock` to mention that it affects dynamic imports just to be clearer
