### ISSUE TITLE
paths (typescript config) don't get resolved

### ISSUE THREAD

**Issue by mendlero** [vitest-dev/vitest#4171]
### Describe the bug

I have configered paths in tsconfig.json to match @/* to ./src/*

I have a test file in <code>src/tests/test1.test.ts</code>, it imports "@/file1"

I get this error:
<code>Failed to load url @/file1 (resolved id: @/file1) in /home/projects/vitest-dev-vitest-mqzngc/src/tests/test1.test.ts. Does the file exist?</code>

### Reproduction

[Reproduction Link](https://stackblitz.com/edit/vitest-dev-vitest-mqzngc)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
    Memory: 2.53 GB / 7.91 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.7.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (117.0.2045.36)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-react: ^4.0.4 => 4.0.4
    vitest: ^0.34.5 => 0.34.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vite doesn't use tsconfig for paths resolution. If you rely on it, use npm package vite-tsconfig-paths

**Comment by mendlero** [comment]
thanks to @sheremet-va for addresing this issue and bringing to my attention the vite-tsconfig-paths npm package.
