### ISSUE TITLE
vitest get error by get-func-name@2.0.1  . require() of ES Module error

### ISSUE THREAD

**Issue by ONLY-yours** [vitest-dev/vitest#4182]
### Describe the bug

vitest error
![image](https://github.com/vitest-dev/vitest/assets/52664827/691ccee5-8b2a-4e1c-9d90-134dd52158a2)
 does some one was error by this？

link: https://github.com/chaijs/get-func-name/issues/42

### Reproduction

no link

### System Info

```shell
vitest
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dergunovs** [comment]
Same error

**Comment by kainstar** [comment]
Same error.
I have a temporary solution, use [`overrides`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) to lock `get-func-name`'s version to "2.0.0", then vitest works well.

**Comment by aleksi-magner** [comment]
Moreover, if you do not clear the dependency cache, then there is no error and all tests pass. If you install dependencies from scratch, then there is an error.

**Comment by ONLY-yours** [comment]
they are rebase it and public 2.0.2
https://github.com/chaijs/get-func-name/commit/83ce12db3bd4e892b4c8fc9443988e1385cf0667

looks fixed

**Comment by ONLY-yours** [comment]
fixed by https://github.com/chaijs/get-func-name/issues/42
