### ISSUE TITLE
ReferenceError: Image is not defined in both jsdom and happy-dom environments

### ISSUE THREAD

**Issue by rasmusvhansen** [vitest-dev/vitest#419]
### Describe the bug

I have added `environment: 'jsdom'` to vite test config section, and would expect `new Image()` to succeed.
I get the same result using happy-dom.

Am I missing some option to properly configure jsdom or happy-dom, or is this a bug?
The same code runs in jest/jsdom without errors.
See Stackblitz for minimal reproduction.

### Reproduction

https://stackblitz.com/edit/node-eyadys?file=test%2Fbasic.test.ts&view=editor

### System Info

```shell
System:
    OS: Linux undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: Unknown - /bin/jsh
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    vite: ^2.7.10 => 2.7.10 
    vitest: ^0.0.123 => 0.0.123
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rasmusvhansen** [comment]
I found a workaround here: https://github.com/konvajs/react-konva/issues/76

I added this to my test, and now it runs:

```typescript
import { JSDOM } from 'jsdom';
global.document = new JSDOM('') as any;
global.window = document.defaultView as any;
global.Image = window.Image;
```

Feels a bit dirty though.

**Comment by sheremet-va** [comment]
Happy-dom doesn't support `Image` API on global.

You can do this in `setupFile` with JSDOM:

```ts
global.Image = window.Image
```
