### ISSUE TITLE
spyOn does not detect method call from a curried class method

### ISSUE THREAD

**Issue by MatthewWid** [vitest-dev/vitest#4190]
### Describe the bug

When calling a class method that is being spied on with `vi.spyOn`, if we pass it as an argument to a curried method and then call it from within that curried method, no calls are recorded by the spy.

---

For example (taking from the reproduction repo I have provided), if we create a curried function that takes a single function as an argument and then simply calls when run:

```typescript
const createCaller = (toCall: () => void) => () => {
        toCall();
};
```

And then in our class we pass our method to it that we intend to spy on:

```typescript
class MyClass {
        callee = () => {
                console.log("callee called");
        };

        caller = createCaller(this.callee);
}
```

If we assert that the spied-on method `MyClass#callee` is called when invoking `MyClass#caller`:

```typescript
test("callee is called", () => {
        const mine = new MyClass();

        const calleeSpy = vi.spyOn(mine, "callee");

        mine.caller();

        expect(calleeSpy).toHaveBeenCalled();
});
```

The test will fail, citing that `MyClass#callee` was never called, despite it clearly being called as `"callee called"` is logged to the console when the test runs.

### Reproduction

[MatthewWid/vitest-bug-spyon-curried-method-call](https://github.com/MatthewWid/vitest-bug-spyon-curried-method-call)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 5.56 GB / 7.71 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 20.7.0 - ~/n/bin/node
    Yarn: 1.22.19 - ~/n/bin/yarn
    npm: 10.1.0 - ~/n/bin/npm
    pnpm: 8.8.0 - ~/n/bin/pnpm
  npmPackages:
    vitest: ^0.34.5 => 0.34.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
When you did `new MyClass`, caller already accessed `callee`, so when you do `vi.spyOn` you spy on the calls to `mine.callee`:

```ts
const mine = new MyClass(); // mine.caller is created, it references detached mine.callee
const calleeSpy = vi.spyOn(mine, "callee");
mine.caller() // calles detached mine.callee
// mine.callee === callee inside mine.caller, but spying only spies on calls to mine.callee, not just callee
```

What you did is essentially the same as:

```ts
const callee = () => {
        console.log("callee called");
};

class MyClass {
        callee = callee

        caller = createCaller(this.callee);
}
```

And then you expect to track `callee` call (not just `MyClasss#callee`). Again, this is not possible because to "spy" on something, you need an object that has the method because spying is essentially reassigning a method to track its calls.

Spying only tracks direct calls, but you lost the reference here. There is no mechanism in JavaScript to do what you want to do with a provided example.

**Comment by MatthewWid** [comment]
@sheremet-va Ah yes you're correct. My fault here - sorry!
