### ISSUE TITLE
toBe not working with some strings?

### ISSUE THREAD

**Issue by AndreiTS** [vitest-dev/vitest#4192]
### Describe the bug

I was creating a test for a function that returns a string. The function is returning the same string specified in the test, but vitest says that the strings are not equal.

![image](https://github.com/vitest-dev/vitest/assets/13489837/a3514e77-5475-467f-b222-9c276e2e2c67)
![image](https://github.com/vitest-dev/vitest/assets/13489837/4fa2e7ab-d60a-41e6-9296-a0a48e904d44)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ebu4xx?file=src%2Fa.test.ts&terminal=dev

### System Info

```shell
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 7.19 GB / 15.45 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.7.0 - ~/.nvm/versions/node/v20.7.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.7.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.7.0/bin/npm
    pnpm: 8.7.3 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 117.0.5938.92
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You probably have a non breaking space there: https://en.m.wikipedia.org/wiki/Non-breaking_space

**Comment by AndreiTS** [comment]
yep
![image](https://github.com/vitest-dev/vitest/assets/13489837/4ada780e-3f43-46a1-9ea0-1a0ab0143d18)
