### ISSUE TITLE
`fetch` is `undefined` with `experimentalVmThreads: true`

### ISSUE THREAD

**Issue by nstepien** [vitest-dev/vitest#4199]
### Describe the bug

Without `experimentalVmThreads`, our JSDOM tests can use [Node's `fetch` implementation](https://nodejs.org/dist/latest-v20.x/docs/api/globals.html#fetch) in our tests.
When `experimentalVmThreads` is enabled, the global `fetch` is missing.

### Reproduction

`vite.config.js`:
```js
import { defineConfig } from 'vite';

export default defineConfig({
  test: {
    experimentalVmThreads: true,
    environment: 'jsdom'
  }
});
```

test file:
```js
import { test, expect } from 'vitest';

test('global fetch', () => {
  expect(globalThis.fetch).toBeDefined();
});
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (64) x64 AMD Ryzen Threadripper 3970X 32-Core Processor
    Memory: 23.16 GB / 31.88 GB
  Binaries:
    Node: 20.8.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (117.0.2045.43)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-react: ^4.1.0 => 4.1.0
    @vitest/coverage-v8: ^0.34.5 => 0.34.5
    vite: ^4.4.9 => 4.4.9
    vitest: ^0.34.5 => 0.34.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
JSDOM doesn't provide `fetch` on `window` object, so it's not there. VM mode is more strict and uses actual context instead of patching global variables, so you should have environment close to what you have in the browser.

I'm not against patching it by extending the context with `fetch`/`Request`/`Response` in https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/integrations/env/jsdom.ts

**Comment by nstepien** [comment]
Yes that'd be nice!
I wonder if there are additional web globals provided by Node that need to be patched in. 🤔
