### ISSUE TITLE
Vitest hangs with PostCSS

### ISSUE THREAD

**Issue by robertu7** [vitest-dev/vitest#4201]
### Describe the bug

Vitest hangs if the PostCSS config is in [`package.json`](https://github.com/thematters/matters-web/blob/5951659928d091af4a0e89296e61888951ed9685/package.json#L219-L252). 

Also, it throws errors if use `postcss.config.js` w/o the `require` shape (which is [not supported by Next.js](https://nextjs.org/docs/messages/postcss-shape#common-errors), so I cannot make Vitest and Next.js work together):

```
⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯
Failed to load PostCSS config: Failed to load PostCSS config (searchPath: /home/runner/work/matters-web/matters-web): [TypeError] Invalid PostCSS Plugin found at: plugins[0]

(@/home/runner/work/matters-web/matters-web/postcss.config.js)
TypeError: Invalid PostCSS Plugin found at: plugins[0]
```

### Reproduction

1. Pull the [repo](https://github.com/thematters/matters-web/tree/5951659928d091af4a0e89296e61888951ed9685) (commit: 5951659928d);
2. `npm install`;
3. `npm run test:unit`;
4. vitest is hanging;

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 267.38 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.7.0 - /opt/homebrew/bin/npm
    pnpm: 6.11.0 - /usr/local/bin/pnpm
  Browsers:
    Brave Browser: 115.1.56.20
    Chrome: 116.0.5845.96
    Edge: 114.0.1823.51
    Safari: 17.0
  npmPackages:
    @vitejs/plugin-react: ^4.1.0 => 4.1.0 
    vitest: ^0.34.6 => 0.34.6 
```
```


### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by robertu7** [comment]
**Update:** Found a workaround, can be fixed by changing the `postcss.config.js` to `postcss.config.json`: https://github.com/thematters/matters-web/blob/646564c151e8bf731c7a0f22d9db90f403265328/postcss.config.json

**Comment by Manish3323** [comment]
https://github.com/thematters/matters-web/blob/646564c151e8bf731c7a0f22d9db90f403265328/postcss.config.json

not related to this issue, but a heads up, you have pushed prod env to this **public git repo.** https://github.com/thematters/matters-web/

**Comment by sheremet-va** [comment]
If this is still an issue, I would recommend opening an issue in the Vite repository instead since we don't control this in any way.
