### ISSUE TITLE
Vitest doesn't recognize es2023 array functions (toSorted, with, etc.)

### ISSUE THREAD

**Issue by kszucher** [vitest-dev/vitest#4203]
### Describe the bug

Even though with Vite dev, I am able to use these functions, and according to doc, Vitest uses Vite for config,
running a test using Vitest fails when using array functions toSorted, with (and potentially other es2023 array functions) 

### Reproduction

Try to run any test which uses these array functions

### System Info

```shell
"vite": "^4.4.9",
"vitest": "^0.34.6"
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest doesn't polyfill anything. Either find a polyfill or use latest Node.js version that supports these features (v20 and higher).
