### ISSUE TITLE
`.not` assertion is not recognized by TypeScript

### ISSUE THREAD

**Issue by kosgdk** [vitest-dev/vitest#4218]
### Describe the bug

Looks like [4209](https://github.com/vitest-dev/vitest/pull/4209) broke types for `not` assertion:

![image](https://github.com/vitest-dev/vitest/assets/16893004/3d14ceb7-8e32-4de0-b960-841782f5c9a6)

### Reproduction

https://github.com/kosgdk/vitest-example

### System Info

```shell
System:
    OS: Windows 10 10.0.17763
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz
    Memory: 12.97 GB / 31.74 GB
  Binaries:
    Node: 18.17.1 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.3.1 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Internet Explorer: 11.0.17763.2989
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kosgdk** [comment]
Thanks a lot for a quick fix.
When is it going to be released?

**Comment by sheremet-va** [comment]
Today
