### ISSUE TITLE
`mockRestore` does not restore original function

### ISSUE THREAD

**Issue by joselcvarela** [vitest-dev/vitest#4219]
### Describe the bug

On previous versions and as stated on documentation `mockRestore` should restore original function:
https://vitest.dev/api/mock.html#mockrestore:~:text=restores%20inner%20implementation%20to%20the%20original%20function

Although on this PR: https://github.com/vitest-dev/vitest/pull/3518 this behaviour was changed in order for mocked function return undefined instead of original function.

I would expect `mockRestore` to keep restoring the original function since it is what documentation states plus this is now breaking some of our tests and there's no breaking change report.

### Reproduction

```ts
import { example } from './example.js';
...
vi.mock('./example.js');
...
test(
...
  example(); // Expected mock function to be called
  vi.mocked(example).mockRestore();
  example(); // Expected original function to be called
...
```

### System Info

```shell
npmPackages:
    @vitest/coverage-c8: ^0.23.4 => 0.23.4
    vite: ^4.4.9 => 4.4.9
    vitest: ^0.34.5 => 0.34.5
```

As workaround I am now doing the following (but it's quite verbose):
 ```ts
vi.mocked(example)
  .mockReset()
  // @ts-ignore
  .mockImplementation(undefined);
 ```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Technically automocking doesn't wrap your module. It recreates a similarly shaped object and shouldn't hold the reference to the original method.

**Comment by joselcvarela** [comment]
Humm, interesting.
If we want to check how many times the function was called but also want to call the real function, what would be the recommended way to achieve that?
`mockImplementation(undefined)` restores function to call the real one, but not sure if that's the best way to do so.

**Comment by sheremet-va** [comment]
> If we want to check how many times the function was called but also want to call the real function, what would be the recommended way to achieve that?

I would recommend using `vi.spyOn` instead:

```ts
import * as example from './example.js'
const spyExample = vi.spyOn(example, 'example').mockImplementation(() => true)
spyExample.mockRestore()
```

**Comment by joselcvarela** [comment]
Thank you. I finally had the opportunity to test this way and it solved.
