### ISSUE TITLE
Browser mode does not take --testNamePattern into account.

### ISSUE THREAD

**Issue by Reductions** [vitest-dev/vitest#4226]
### Describe the bug

When I set an arbitrary --testNamePattern such as "this text will not match anything" in --browser mode, all defined tests run no matter if they match the pattern.

### Reproduction

- Go to vitest/examples/basic
- Change the package.json to:
```
{
  "name": "@vitest/example-test",
  "type": "module",
  "private": true,
  "license": "MIT",
  "main": "index.js",
  "scripts": {
    "test": "vitest",
    "test:ui": "vitest --ui",
    "test:run": "vitest run",
    "test:browser": "vitest run --browser"
  },
  "devDependencies": {
    "@vitest/browser": "latest",
    "@vitest/ui": "latest",
    "playwright": "latest",
    "vite": "latest",
    "vitest": "latest"
  },
  "stackblitz": {
    "startCommand": "npm run test:ui"
  }
}
```
- Change the vite.config.ts test configuration to: 
```
import { defineConfig } from 'vitest/config';

export default defineConfig({
    test: {
        testNamePattern: 'something that does not match,
        browser: {
            provider: 'playwright',
            headless: true,
            name: 'chromium',
        },
    },
});
```
- Install packages
- Run the tests using test or test:browser scripts

### System Info

```shell
System:
    OS: Linux 5.15 openSUSE Leap 15.5
    CPU: (13) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 17.81 GB / 20.52 GB
    Container: Yes
    Shell: 4.4.23 - /bin/bash
  Binaries:
    Node: 18.15.0 - ~/.local/share/pnpm/nodejs/18.15.0/bin/node
    npm: 9.5.0 - ~/.local/share/pnpm/npm
    pnpm: 8.8.0 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chromium: 117.0.5938.88
  npmPackages:
    vitest: ^0.34.4 => 0.34.4
```

### Used Package Manager

pnpm
npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
I can reproduced this on Vitest repo:

```sh
# browser mode
$ pnpm exec vitest basic.test.ts --testNamePattern 'x is x' 

 DEV  v1.1.3 /home/hiroshi/code/others/vitest/test/browser
      Browser runner started at http://localhost:5173

 ✓ test/basic.test.ts (4)
   ✓ basic
   ✓ basic 2
   ✓ x is x
   ✓ y is x

...

# non-browser mode
$ pnpm exec vitest basic.test.ts --testNamePattern 'x is x' --no-browser.enabled

 DEV  v1.1.3 /home/hiroshi/code/others/vitest/test/browser

 ✓ test/basic.test.ts (4)
   ↓ basic [skipped]
   ↓ basic 2 [skipped]
   ✓ x is x
   ↓ y is x [skipped]

....
```

It looks like `testNamePattern: RegExp` is not (de)serialized properly when passing to browser via RPC as https://github.com/WebReflection/flatted doesn't support it.

Probably there was a similar situation for child/forks pool's `v8.serialize/deserialize` and it is workarounded by custom encoding `$$vitest:(testNamePattern)`. 

https://github.com/vitest-dev/vitest/blob/c50028832f5313793d8b9cbd97896dda9ecf6f2d/packages/vitest/src/node/pools/child.ts#L144-L147

Browser pool could do something similar to fix this. Or maybe replacing `flatted` with alternative serialization library such as  https://github.com/Rich-Harris/devalue/ to handle `RegExp` automatically might be also an option.
