### ISSUE TITLE
vi.stubEnv does not change on exported variables

### ISSUE THREAD

**Issue by tauthomas01** [vitest-dev/vitest#4232]
### Describe the bug

In a test, mocking a custom `env` variables with `stubEnv` does not change the behaviour on exported variables. However, it works on exported function.

```
// vitest.config.ts
export default defineConfig({
  plugins: [react(), tsconfigPaths()],
  test: {
    globals: true,
    environment: 'happy-dom',
    setupFiles: ['./test/setup-test-env.ts'],
    include: ['./app/**/*.test.[jt]s?(x)'],
  },
});

// setup-test-env.ts
process.env.USE_MOCKS = 'true';
```

This does not work when testing a `const`:

```
// component.ts
export const isUseMocks = process.env.USE_MOCKS === 'true' ?? false;

// test.ts
test("isUseMocks should return false when env var is set", () => {
  vi.stubEnv("USE_MOCKS", "false")
    
  // This fails as it returns "true" from the "setup-test-env.ts" config
  expect(isUseMocks).toBe(false);
})
```

The following works if I switch from a `const` to a function:

```
// component.ts
export const isUseMocks = () => {
  return process.env.USE_MOCKS === 'true' ?? false;
};

// test.ts
test("isUseMocks should return false when env var is set", () => {
  vi.stubEnv('USE_MOCKS', 'false');

  // process.env.USE_MOCKS is picking up from my vi.stubEnv
  expect(isUseMocks()).toBe(false);
})
```

### Reproduction

I've included test cases for both `const` and function. See `basic.test.ts`

StackBlitz: https://stackblitz.com/edit/vitest-dev-vitest-ogsahf?file=test%2Fbasic.test.ts

### System Info

```shell
System:
    OS: macOS 13.5.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 295.91 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.0 - /opt/homebrew/bin/node
    npm: 9.6.7 - /opt/homebrew/bin/npm
    Watchman: 2023.06.08.00 - /opt/homebrew/bin/watchman
  Browsers:
    Safari: 16.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Of course, it doesn't. The variable is defined when the file is imported, you cannot override it, the variable doesn't depend on `process.env.USE_MOCKS` anymore.

You need to import the file again dynamically:

```ts
vi.stubEnv('USE_MOCKS', true)
await import('./constants.js')
```

If it still doesn't work, make sure the file is not cached by calling `vi.resetModules()`.
