### ISSUE TITLE
Chaijs/get-func-name vulnerable to ReDoS     

### ISSUE THREAD

**Issue by lritter79** [vitest-dev/vitest#4234]
### Describe the bug

vitest > @vitest/expect > @vitest/utils > loupe has get-func-name  version 2.0.0 as a dependency, which has a vulnerability. 

### Reproduction

Run `yarn audit` in a project with vitest 

### System Info

```shell
│ high          │ Chaijs/get-func-name vulnerable to ReDoS                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ get-func-name                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.0.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ vitest                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ vitest > @vitest/expect > @vitest/utils > loupe >            │
│               │ get-func-name                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1094228                     │
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Use the latest version
