### ISSUE TITLE
Failed to load custom environment from JS file

### ISSUE THREAD

**Issue by paescuj** [vitest-dev/vitest#4237]
### Describe the bug

The documentation at https://vitest.dev/guide/environment.html#custom-environment states that since v0.34.0 a custom environment can be a valid JS file (instead of a `vitest-environment-${name}` package).

However, with a configuration like the following
```js
export default defineConfig({
  test: {
    environment: './custom.js',
  },
});
```

it still tries to load the custom environment from a package:

```console
 MISSING DEP  Can not find dependency 'vitest-environment-./custom.js'
 ```

The resolve logic seems to differentiate correctly here:
https://github.com/vitest-dev/vitest/blob/22181f0209992aa4e054dd18cab045007186aa48/packages/vitest/src/integrations/env/index.ts#L55-L57

So I'd guess there's an issue in the loader used at the next line:
https://github.com/vitest-dev/vitest/blob/22181f0209992aa4e054dd18cab045007186aa48/packages/vitest/src/integrations/env/index.ts#L58

---

Also – at least with the package setup – it seems like the file is preprocessed again, despite the statement from [v0.34.0](https://github.com/vitest-dev/vitest/releases/tag/v0.34.0):
> Custom environment now should be processed before Vitest can consume it. It means that you cannot specify a path to a TS file or use import paths that should be processed by Vite.

For example, a setup like this works fine: https://github.com/vitest-dev/vitest/blob/main/test/env-custom/vitest-environment-custom/package.json

Related to https://github.com/vitest-dev/vitest/pull/4196?

If this is indeed supported again and once this issue here has been addressed, could the documentation be updated to `specify a path to a valid JS/TS file`?

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-uefbmr

### System Info

```shell
System:
    OS: macOS 13.5.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 9.84 GB / 32.00 GB
    Shell: 5.2.15 - /usr/local/bin/bash
  Binaries:
    Node: 18.18.0 - /usr/local/opt/node@18/bin/node
    npm: 10.1.0 - /usr/local/bin/npm
    pnpm: 8.8.0 - /usr/local/bin/pnpm
  npmPackages:
    vitest: 0.34.6 => 0.34.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Looks like `resolvePath` fails here.

> Also – at least with the package setup – it seems like the file is preprocessed again

Yes, the behaviour was reverted, but I forgot to update documentation it looks like. This was intended change.
