### ISSUE TITLE
Document "assert"

### ISSUE THREAD

**Issue by sheremet-va** [vitest-dev/vitest#4242]
### Clear and concise description of the problem

Vitest exports `assert` method which is not documented anywhere. It is just reexport of https://www.chaijs.com/api/assert/

### Suggested solution

Make our own documentation of this method.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by developer-bandi** [comment]
@sheremet-va  Can I work on this issue?

**Comment by sheremet-va** [comment]
> @sheremet-va Can I work on this issue?

Yes, you can work on this. Please don't ask again if you see there is no assignees.

**Comment by willieho** [comment]
Hi @developer-bandi , I just happened to work on this yesterday and ready to open a draft PR, would you mind let me initiate the PR first then maybe you can work based on it?

**Comment by developer-bandi** [comment]
@willieho of course. Please open PR and let me know!

**Comment by willieho** [comment]
@developer-bandi Thank you, PR #5124 is opened!
