### ISSUE TITLE
A Node API to get testing results from the Vitest instance

### ISSUE THREAD

**Issue by Jinjiang** [vitest-dev/vitest#4257]
### Clear and concise description of the problem

I'm trying to integrate Vitest into my own project via Node APIs. Basically, we need to filter testing files from somewhere in the file system, pass them into Vitest, and display the testing results. The whole process has to be connected and finished as Node APIs.

Now I understand we already have some [Node APIs](https://vitest.dev/advanced/api.html) to create or start a Vitest instance. However, there is no way to get testing results from the Vitest instance.

I made a reproduction to walk around by a inline reporter, however, it's not easy to use. I feel it would be great if we could have a Node API on Vitest instance to get the testing results.

https://github.com/Jinjiang/reproductions/tree/vitest-node-apis-20231006

### Suggested solution

Some new API on Vitest instances like:

```js
const results = await vitest.getResults()
```

https://github.com/Jinjiang/reproductions/blob/vitest-node-apis-20231006/node-apis/run-test.mjs#L49

### Alternative

Just for ref: some similar APIs exist in Jest community
https://medium.com/web-developers-path/how-to-run-jest-programmatically-in-node-js-jest-javascript-api-492a8bc250de

```js
const result = await runCLI(jestConfig as any, [projectRootPath]);
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
You can already do `vitest.state.getFiles()` which is equivalent to what you get in `onFinished`.

**Comment by Jinjiang** [comment]
@sheremet-va Oh glad to know that. Thanks!
Btw, I feel it deserves a mention on the docs.🙂
