### ISSUE TITLE
Support environment variables for configuration

### ISSUE THREAD

**Issue by DMartens** [vitest-dev/vitest#4261]
### Clear and concise description of the problem

There are some options regarding the CLI which are developer dependent, such as `reporter`, which should be set differently by each developer in a team (e.g. some prefer the `basic` reporter, other the `dot` reporter).
Other potential options: `bail`, `retry`, `onConsoleLog`, `diff`, `cache`
Other potential CLI arguments: `--ui`, `--open`

### Suggested solution

Support an environment variable, e.g. `VITEST_REPORTER` which is preferred over the reporter in the configuration but overridden by providing a `--reporter` CLI argument.
The value would be the same as the `--reporter` CLI argument.
This would allow to set it once in the shell configuration and not have to set it for every invokation and would work with npm scripts.

### Alternative

These options are more powerful as all options may be set but also increase complexity:
- `VITEST_CONFIG`: another environment variable pointing to an additional configuration value which is merged with project config 
- load and merge a config file from the XDG config folder (e.g. form `/home/developer/.config/vitest/config.js`)

### Additional context

I am willing to provide a PR for this feature.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
You could set the values in configuration file using environment variables, e.g.

```ts
{ 
  test: {
    reporter: process.env.VITEST_REPORTER || '<some default>',
   }
}
```

**Comment by DMartens** [comment]
Sure this is possible as is creating a CLI wrapper always specifying the option but the focus of this proposal is developer experience.
As this requires an edit of the config file, this is not a feasible solution when contributing to another project.
To clarify my point: it could be enough to only have a `--config` option and no `--reporter` option by writing a CLI wrapper which merges the option in.
I took the reporter as the example but as listed in the proposal there are further fields which I think are dependent on the preferences of the individual developer.
If you think the current solution is enough, feel free to close this issue.

**Comment by sheremet-va** [comment]
I personally don't like this idea because environment variables can be set globally which means every test will refer to the same value even if it's in another project which is kind of unexpected and can lead to confusion.

I think that if your team has a preference, you can use environment variables manually just like @AriPerkkio mentioned.
