### ISSUE TITLE
expect type export broken in 1.0.0

### ISSUE THREAD

**Issue by embiem** [vitest-dev/vitest#4273]
### Describe the bug

While testing version 1.0.0-beta.1, I now get lots of type errors like:

`This expression is not callable. Type 'ExpectStatic' has no call signatures.`

And my previous `expect.extend` call now results in `Property 'extend' does not exist on type 'ExpectStatic'`.

I am importing expect as usual: `import { expect } from 'vitest'`.

My previously used vitest version was 0.34.5. There, the ExpectStatic interface in @vitest/expect/dist was:
```
interface ExpectStatic extends Chai.ExpectStatic, AsymmetricMatchersContaining {
    <T>(actual: T, message?: string): Assertion<T>;
    unreachable(message?: string): never;
    soft<T>(actual: T, message?: string): Assertion<T>;
    extend(expects: MatchersObject): void;
    assertions(expected: number): void;
    hasAssertions(): void;
    anything(): any;
    any(constructor: unknown): any;
    getState(): MatcherState;
    setState(state: Partial<MatcherState>): void;
    not: AsymmetricMatchersContaining;
}
```

With the beta version, the type is:
```
interface ExpectStatic {
    addSnapshotSerializer(plugin: Plugin_2): void;
}
```

### Reproduction

- have tests using `expect` api on vitest version 0.34.5
- update vitest to the 1.0.0 beta version
- run a typecheck, like `tsc`

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900K
    Memory: 16.81 GB / 31.79 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.2283.0), Chromium (117.0.2045.47)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-react: ^4.1.0 => 4.1.0
    @vitest/coverage-v8: ^1.0.0-beta.1 => 1.0.0-beta.1
    vite: ^4.4.9 => 4.4.9
    vitest: ^1.0.0-beta.1 => 1.0.0-beta.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Dunqing** [comment]
<img width="898" alt="image" src="https://github.com/vitest-dev/vitest/assets/29533304/c160d9ff-0d78-490d-9565-93d002eb18f4">

Looks like everything is fine, did you try to clean and re-install the `node_modules`?

**Comment by sheremet-va** [comment]
> shows this module declaration

This just augments your types, the types themselves are inside `@vitest/expect` package which should also be the latest version

**Comment by sheremet-va** [comment]
> Looks like everything is fine, did you try to clean and re-install the `node_modules`?

Did you try npm instead of pnpm?

**Comment by sheremet-va** [comment]
> This includes the incorrect `@vitest/expect` module types as I posted above.

These types are correct.

**Comment by Dunqing** [comment]
> Did you try npm instead of pnpm?

I tested it and works fine

**Comment by alexhanga** [comment]
Have the same problem with `yarn v3` (node-modules linker) setup. 1.0.0-beta.2, TypeScript 5.2.2

**Comment by sheremet-va** [comment]
Should _probably_ be fixed by this PR: https://github.com/vitest-dev/vitest/pull/4322

You can manually update files to see if it does it for you.

**Comment by alexhanga** [comment]
Yes. It works
