### ISSUE TITLE
Specify mulitple browsers in config to run in-browser tests in

### ISSUE THREAD

**Issue by hamza1311** [vitest-dev/vitest#4274]
### Clear and concise description of the problem

I would like to run tests in multiple browsers. I use Playwright for testing and it supports this feature as [test projects](https://playwright.dev/docs/test-projects).

Vitest, on the other hand, does not allow specifying multiple browsers. [`test.browser`](https://vitest.dev/config/#browser) in the config is an object, not an array.

### Suggested solution

Pass the config along to playwright and let it handle running in browsers

### Alternative

Invoking vitest multiple times with a script, passing different --browser each time

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Vitest supports inline workspace configuration which is the same as `projects`: https://vitest.dev/guide/workspace.html

**Comment by sheremet-va** [comment]
This is a design decision to have a separate file for this.

**Comment by hamza1311** [comment]
For a single-workspace project, there's no way to define more than one browser to run tests in? That seems like an odd limitation

**Comment by hamza1311** [comment]
Right, I misunderstood the playwright config
