### ISSUE TITLE
Add typeahead to watch mode filename filter

### ISSUE THREAD

**Issue by IanVS** [vitest-dev/vitest#4275]
### Clear and concise description of the problem

When filtering watch mode to a filename pattern, I would like vitest to present a list of files that match what I have typed so far, that I can choose from if desired.

### Suggested solution

Ideally, this would be similar to https://www.npmjs.com/package/jest-watch-typeahead

### Alternative

If it's too much work to provide options to choose from, vitest could at least show the files that are matched, so the user knows when they can stop typing.  This is not as useful as the full implementation as shown by jest-watch-typeahead, but would be a small improvement to DX.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by bonyuta0204** [comment]
Can I have a try for this?

**Comment by dsvgl** [comment]
I dearly miss this since we migrated to vitest from jest

**Comment by IanVS** [comment]
@bonyuta0204 it says `pr welcome` so I think you should feel free to give it a shot.
