### ISSUE TITLE
JSON test report should include `coverageMap`

### ISSUE THREAD

**Issue by rlaferla** [vitest-dev/vitest#4276]
### Describe the bug

vitest should include the coverage map in the coverage report but instead puts them in separate files.

The report should contain a key for the coverage map

e.g.

`vitest run --coverage --outputFile=report.json --reporter=json
`

```
"coverageMap": {
  "/src/test.ts": {
    "path": "/src/test.ts",
    "statementMap": {
       "0": {
         "start": {
           "line": 1,
           "column": 0
         },
         "end": {
           "line": 1,
           "column": 44
         }
       }
    }
  }
}
```

Instead it puts the coverage map in a separate file:

`coverage/coverage-final.json
`

### Reproduction

If you run:

`% vitest run --coverage --outputFile=report.json --reporter=json

Both of these searches will not return any results:

```
% grep coverageMap report.json
% grep statementMap report.json
```

while this will return a result indicating that the json file is the coverage map.

`% grep statementMap coverage/coverage-final.json`

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M2
    Memory: 685.72 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 116.1.57.47
    Chrome: 117.0.5938.149
    Safari: 17.0
  npmPackages:
    @vitest/coverage-v8: ^0.34.6 => 0.34.6 
    vite: ^4.4.11 => 4.4.11 
    vitest: ^0.34.6 => 0.34.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
> vitest should include the coverage map in the coverage report but instead puts them in separate files.

I'm not sure if I'm understanding this correctly. The `vitest --reporter=json --outputFile=report.json` will generate `report.json` that contains information about the test run. The `vitest --coverage.enabled ---coverage.reporter=json` will generate a `coverage/coverage-final.json` which contains information about the code coverage. Do you want coverage report to be included in the test report as well? If so, why? Do other tools do this?

**Comment by sheremet-va** [comment]
> Do other tools do this?

Looks like jest does, but we didn't implement it at the time (since there was no coverage yet):

https://github.com/vitest-dev/vitest/blob/eac7776521bcf4e335771b1ab4f823f40ad9c4ff/packages/vitest/src/node/reporters/json.ts#L59

**Comment by AriPerkkio** [comment]
I can't find any documentation from Jest on this, but it's there on the source code. I guess we can add this to be more compatible with Jest.
