### ISSUE TITLE
Docs: Getting Started - links to examples are broken

### ISSUE THREAD

**Issue by LeUser111** [vitest-dev/vitest#428]
### Describe the bug

The Examples section of the Getting Started guide contains broken links:

Sections on component testing have apparently been moved from _main/test_ to _main/examples_:

- Vue
-- Is: https://github.com/vitest-dev/vitest/tree/main/test/vue
-- Should be: https://github.com/vitest-dev/vitest/tree/main/examples/vue
- React
-- Is: https://github.com/vitest-dev/vitest/tree/main/test/react
-- Should be: https://github.com/vitest-dev/vitest/tree/main/examples/react
- Svelte
-- Is: https://github.com/vitest-dev/vitest/tree/main/test/svelte
-- Should be: https://github.com/vitest-dev/vitest/tree/main/examples/svelte
- Lit
-- Is: https://github.com/vitest-dev/vitest/tree/main/test/lit
-- Should be: https://github.com/vitest-dev/vitest/tree/main/examples/lit
- Vitesse
-- Is: https://github.com/vitest-dev/vitest/tree/main/test/vitesse
-- Should be: https://github.com/vitest-dev/vitest/tree/main/examples/vitesse

### Reproduction

Go to https://vitest.dev/guide/#examples and click on any link other than _Unit Testing_

### System Info

```shell
not system dependent
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by patak-dev** [comment]
Would you like to PR the needed changes?

**Comment by LeUser111** [comment]
I've never done a PR before - sorry! I'm a complete noob in that regard -.-

**Comment by patak-dev** [comment]
No worries, thanks for the report! I'll check the links now
For another time, to do a PR you'll fork this repo to your user (there is a button at the top of the page). You'll clone that fork in your local machine. [Install, build, check the tests are running](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md). Create a branch (see `git branch`), edit the files that need to be changed, and push that branch to your fork. A big green button will then appear at the top in the repo that gives you a similar form to the one for creating issues to send the PR
