### ISSUE TITLE
Docs: sidebar navigation structure

### ISSUE THREAD

**Issue by mitchelvanbever** [vitest-dev/vitest#429]
### Clear and concise description of the problem

Currently the flow when you land on the docs and click on getting started you navigate to the guide page which can be pretty overwhelming to grasp by looking at the sidebar. I think the problem is lies in the following aspects;

* Navigation structure is inconsistent between pages
* Duplicate information because of lack of an easy to navigate structure (guide specific, mocks for example) 
* API and Config options are not sorted alphabetically at the moment

### Suggested solution

I'm proposing to overhaul the docs a little bit to start with a clear base where everyone can build upon by implementing the following changes:

General:
* Make navigation consistent between Config and API
* Sort all the things alphabetically (if the order isn't there for a reason)

-------------------

Guide:
* Rework structure into the following;
```
- Guide
  - Why Vitest?
  - Comparisons
  - Getting Started
  - Features 
     - ...
    - Mocking
       - Functions
       - Modules
       - ...
```

-------------------

To ensure consistency between the config and API pages we should consider to

Either:
* remove "Configuring Vitest" title from config

Or:
* add another title on top of the api page

-------------------
_Up for discussion_:
* Clean up nav by adding icons for social links

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by mitchelvanbever** [comment]
Will create a draft PR later today to have a link preview with my suggested changes 👍

**Comment by patak-dev** [comment]
Awesome, please also check https://github.com/vitest-dev/vitest/issues/279

About the structure of the sidebar, we already discussed with @sheremet-va about having all the mocking guides on the same page so it is easier to search with regular browser tools when reading it (and also helps with the sidebar)

I don't know if it is a formatting error in your description, but I was thinking on something like:
```
- Guide
  - Why Vitest?
  - Comparisons
  - Getting Started
  - Features 
    - ...
  - Mocking
    - Functions
    - Modules
    - ...
```
Maybe we could first do this and check how it works?

+1 for making the order consistent!

**Comment by mitchelvanbever** [comment]
> Awesome, please also check #279

Will keep #279 in mind. It's more of a general issue on the docs but good to keep referencing it in all docs issues 🙂 

> About the structure of the sidebar, we already discussed with @sheremet-va about having all the mocking guides on the same page so it is easier to search with regular browser tools when reading it (and also helps with the sidebar)
> 
> I don't know if it is a formatting error in your description, but I was thinking on something like:
> 
> ```
> - Guide
>   - Why Vitest?
>   - Comparisons
>   - Getting Started
>   - Features 
>     - ...
>   - Mocking
>     - Functions
>     - Modules
>     - ...
> ```
> 
> Maybe we could first do this and check how it works?

Ah I didn't know it was a conscious decision, it wasn't a formatting error on my side as I saw a section on mocking nested inside the features section. So I thought it would be good to keep them there as well. Do we wanna that section about mocking features to the index of the "new" mocking section? Or do you wanna keep it as is?

Will roll with your suggested structure change for now, we can always discuss further to see if something else makes more sense 👍

**Comment by patak-dev** [comment]
Until now, we were trying to follow the structure of https://vitejs.dev/ (but the mocking sections didn't follow it). 
The idea is that the Features guide works like a quick reference for people to get an idea of everything that is possible, and it links to other guides where each topic can be expanded and explained at length, and to the API and Config reference
We can check later if this is a good structure though
