### ISSUE TITLE
Vitest cannot handle files that have an exported function named `then`

### ISSUE THREAD

**Issue by wmertens** [vitest-dev/vitest#4291]
### Describe the bug

Apparently, Vite considers any module exporting `then` as a promise and it will call the function.

### Reproduction

then.test.js
```ts
export const then = (...args) => {
  console.log(...args);
  throw new Error('then should not be called');
};
```
Results in the above error.

When you put this export in another file and just import it, it will also throw the error.

### System Info

```shell
System:
    OS: Linux 6.1 NixOS 23.11 (Tapir) 23.11 (Tapir)
    CPU: (8) x64 Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
    Memory: 5.68 GB / 15.20 GB
    Container: Yes
    Shell: 5.2.15 - /run/current-system/sw/bin/bash
  Binaries:
    Node: 18.17.1 - /nix/store/1l03gdg4w3cvkygvbxsq9i19flnp1p3y-nodejs-18.17.1/bin/node
    npm: 9.6.7 - /nix/store/1l03gdg4w3cvkygvbxsq9i19flnp1p3y-nodejs-18.17.1/bin/npm
    pnpm: 8.9.0 - ~/bin/pnpm
  npmPackages:
    vite: ^4.4.11 => 4.4.11 
    vitest: ^0.34.6 => 0.34.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Please look into https://github.com/vitest-dev/vitest/issues/1767

**Comment by wmertens** [comment]
Thank you, that was very hard to find :)

**Comment by sheremet-va** [comment]
Yeah, github search is very bad
