### ISSUE TITLE
Add config option for mocking process.nextTick

### ISSUE THREAD

**Issue by rbrewington** [vitest-dev/vitest#4292]
### Clear and concise description of the problem

In an update to vitest fake timers, the default behavior of mocking process.nextTick has been removed (I found this info in the [docs](https://vitest.dev/api/vi.html#vi-usefaketimers)). This is causing multiple unit tests in my project to timeout with no error message. I confirmed that adding the toFake argument to the vi.useFakeTimers call fixes the issue, but I don't want to have to do this for every use of fake timers.

vitest version: 0.34.6
vite version: 4.4.11

### Suggested solution

Could there be an option added to the test configuration to enable this behavior for all uses of fakeTimers? 

something like:
```
defineConfig({
  ...restConfig,
  test: {
    timers: {
       toFake: ['nextTick'],
    },
  },
})
```

For now my workaround is to overwrite the global function with one that passes this argument every time, but that isn't ideal.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
There is already an option in the config called `fakeTimers` (didn't find documentation for it tho for some reason)

**Comment by rbrewington** [comment]
> There is already an option in the config called `fakeTimers` (didn't find documentation for it tho for some reason)

Wow. You're totally right. I didn't look for it since I couldn't find it in the docs. Oops... Works like a charm! Thanks!
