### ISSUE TITLE
Show "latest" documentation site rather than beta documentation site

### ISSUE THREAD

**Issue by deriegle** [vitest-dev/vitest#4293]
### Clear and concise description of the problem

As a developer using Vitest, when I visit `vitest.dev`, I want the documentation to show the "latest" non-beta documentation available. I expect the documentation to match the latest published version available, so when the documentation is pointed at the beta release, it is confusing.

I'm open to helping out with this issue.

### Suggested solution

Only publish the documentation site for the latest non-beta release. Do not publish when releasing a beta version. This makes the documentation site very confusing since it is pointing at the 1.0.0 beta release and most people are on a pre-1.0.0 version right now.

### Alternative

Show multiple versions on the documentation site, so you can pick an older version. This would be more future-proof as security fixes, etc are added to an older version.

We could add options to this dropdown. I was expecting it to allow me to pick the latest documentation.

<img width="252" alt="image" src="https://github.com/vitest-dev/vitest/assets/20227290/c19b6c07-dae7-4967-9930-c4dad9779dbe">

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
We are out of the beta period so this issue can be closed. We will discuss having a separate doc for each release as part of [#1110](https://github.com/vitest-dev/vitest/issues/1110)
