### ISSUE TITLE
cannot find pure cjs module

### ISSUE THREAD

**Issue by HomyeeKing** [vitest-dev/vitest#4294]
### Describe the bug

I want to test a funtion of `react-dev-utils` which is pure CJS module, but can't `import` since it doesn't have `main/module` entry

so I try to use `require`, but got `cannot find module "react-dev-utils"` error

### Reproduction

https://github.com/HomyeeKing/vitest-repo

```
pnpm i 

pnpm run test -- test/foo.test.ts

```

### System Info

```shell
System:
    OS: macOS 13.6
    CPU: (8) arm64 Apple M1
    Memory: 40.09 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 117.0.5938.149
    Safari: 16.6
  npmPackages:
    vitest: ^0.34.6 => 0.34.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HomyeeKing** [comment]
how to spy on this function call in other modules?   I want to use `spyOn`, but it's just a function

**Comment by sheremet-va** [comment]
Examples of mocking are here: https://vitest.dev/guide/mocking.html#cheat-sheet

You can spy on `default` export. You cannot spy with `require`, only with `import` in Vitest.

**Comment by HomyeeKing** [comment]
just record for anybody who meet the same issue like me

![image](https://github.com/vitest-dev/vitest/assets/49113249/3c46dd9c-d7b4-49ca-97b3-14a8053e09e5)

can't use `spyOn` in this situation, but can work around with `mock` , see https://github.com/aelbore/esbuild-jest/issues/26#issuecomment-936845773

```ts
import ob from 'react-dev-utils/openBrowser';
import { expect, it, vi } from 'vitest';

vi.mock('react-dev-utils/openBrowser', () => {
  return {
    default: vi.fn(),
  };
});

it('test', () => {
  ob('https://www.google.com');
  expect(ob).toHaveBeenCalledTimes(1);
  expect(ob).toHaveBeenCalledWith('https://www.google.com');
});


```
