### ISSUE TITLE
Does not report TypeScript compilation errors

### ISSUE THREAD

**Issue by lawrence-forooghian** [vitest-dev/vitest#4295]
### Describe the bug

A `.ts` test file which contains a TypeScript type error does not report any errors.

### Reproduction

See [this StackBlitz](https://stackblitz.com/edit/vitest-dev-vitest-gt8kgc?file=test%2Fbasic.test.ts). Note line 5 of `basic.test.ts`, which contains a type error:

```typescript
const foo: string = 10;
```

The tests run fine. I would have expected vitest to report some sort of compilation error.

### System Info

As in StackBlitz.

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Can you provide fully runnable reproduction? There is even no typecheck command in the provided stackblitz project.

**Comment by dim0627** [comment]
Same here

@sheremet-va 
Is this what you want one?
https://stackblitz.com/edit/vitest-dev-vitest-s3v46d?file=package.json

**Comment by lawrence-forooghian** [comment]
> Can you provide fully runnable reproduction? There is even no typecheck command in the provided stackblitz project.

I am referring to the `npm run test:ui` command that the Stackblitz project runs when you open the web page, which reports all of the tests as passing. I am surprised that a test file that contains TypeScript errors is considered to have all of its tests passing; I would have thought that vitest would

1. report a TypeScript compilation error
2. not run the tests in that file
3. report that file as in some sense "failed"

**Comment by sheremet-va** [comment]
Running type tests is a separate command. Please, refer to documentation https://vitest.dev/guide/testing-types.html
