### ISSUE TITLE
More Jest Expect compactible APIs

### ISSUE THREAD

**Issue by antfu** [vitest-dev/vitest#43]
https://jestjs.io/docs/expect

https://github.com/antfu/vitest/blob/26648739e1c288e217641f8b6a1f73f0c86ae5f5/src/integrations/chai/jest-expect.ts
https://github.com/antfu/vitest/blob/2ff3d68d16acd91d46a1844520729ed56987d5fe/src/index.ts#L19-L42

**Comment by kirillgroshkov** [comment]
The only thing missing for us to migrate from jest is `.rejects` support.

Awesome work! 👏  Can't wait to migrate from Jest to Vitest!

**Comment by sheremet-va** [comment]
Most of the APIs are done. Only missing:

```
 expect.addSnapshotSerializer(serializer)
 .toThrowErrorMatchingSnapshot(hint?)
 .toThrowErrorMatchingInlineSnapshot(inlineSnapshot)
```

**Comment by EvHaus** [comment]
`not.toBeDefined()` is currently not working properly (in 0.0.120).

To reproduce try:

```js
# Passes in Jest, but fails in Vitest
expect(undefined).not.toBeDefined();
```

**Comment by sheremet-va** [comment]
> `not.toBeDefined()` is currently not working properly (in 0.0.120).
> 
> To reproduce try:
> 
> ```js
> # Passes in Jest, but fails in Vitest
> expect(undefined).not.toBeDefined();
> ```

Fixed in next release!

**Comment by EvHaus** [comment]
Also noticed an incompatible behavior with `toHaveBeenCalledWith`, if used with `immutable` (or I'm guessing any custom object).

```js
import immutable from 'immutable'; // npm install immutable@4.0.0-rc.12

const onToggle = jest.fn();
onToggle(Immutable.List(['1'])

// Passes in Jest, but fails in Vitest
expect(onToggle).toHaveBeenCalledWith(Immutable.List(['1']);
```

**Comment by sheremet-va** [comment]
> Also noticed an incompatible behavior with `toHaveBeenCalledWith`, if used with `immutable` (or I'm guessing any custom object).
> 
> ```js
> import immutable from 'immutable'; // npm install immutable@4.0.0-rc.12
> 
> const onToggle = jest.fn();
> onToggle(Immutable.List(['1'])
> 
> // Passes in Jest, but fails in Vitest
> expect(onToggle).toHaveBeenCalledWith(Immutable.List(['1']);
> ```

Can you make a separate issue? This example works with the latest version for me.

**Comment by sheremet-va** [comment]
Everything is implemented. Any incompatabilities should be resolved in new issies. Thank you everyone for participating 🎉
