### ISSUE TITLE
Support old browsers in @vitest/browser

### ISSUE THREAD

**Issue by edoardocavazza** [vitest-dev/vitest#4304]
### Clear and concise description of the problem

Right now, the `@vitest/browser` is built using default vite targets. Since the client library is served through a sirv middleware, it does not get transpiled by the vite server during tests. This lead old browsers without optional chaining support to a syntax error.

### Suggested solution

Would you consider to build `@vitest/browser` using the lowest esbuild target available?

### Alternative

Is it possibile to make vite to serve the client library without sirv?

### Additional context

I am building a provider for Saucelabs browsers.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Should be fine as long as they support import syntax.

**Comment by sheremet-va** [comment]
Actually, `@vitest/browser` assets are now served by the Vite server, not `sirv` so they follow the Vite target.
