### ISSUE TITLE
v0.34.7 is not the latest version

### ISSUE THREAD

**Issue by himself65** [vitest-dev/vitest#4305]
### Describe the bug

<img width="781" alt="image" src="https://github.com/vitest-dev/vitest/assets/14026360/85a55084-7db6-40ea-9b68-282260526c12">

[0.34.7](https://www.npmjs.com/package/@vitest/ui/v/0.34.7) should be the latest version but it's 0.34.6

And I didn't see the release in github page

### Reproduction

https://www.npmjs.com/package/@vitest/ui?activeTab=versions

### System Info

```shell
No need
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
0.34.6 is the correct latest version. 0.34.7 is an empty release.
