### ISSUE TITLE
--coverage.100 crashes with TypeError

### ISSUE THREAD

**Issue by lydell** [vitest-dev/vitest#4307]
### Describe the bug

`vitest run --coverage.100` appears to be broken – it immediately crashes with `TypeError: Cannot read properties of undefined (reading 'push')`.

### Reproduction

```
❯ npx -y vitest run --coverage.100
TypeError: Cannot read properties of undefined (reading 'push')
```

### System Info

```shell
System:
    OS: macOS 13.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.06 GB / 32.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.5.0 - ~/.local/share/nvm/v20.5.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.0 - ~/.local/share/nvm/v20.5.0/bin/npm
    pnpm: 8.8.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 118.0.5993.70
    Safari: 16.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
As work-around you can use `--coverage.enabled --coverage.100`. We'll still need to fix the crash though.

**Comment by marcelobotega** [comment]
Hi @AriPerkkio, 
I tried to fix the bug, but it seems to be from CAC and not from vitest.
The [parse](https://github.com/vitest-dev/vitest/blob/4293e1b15111316b8ef622d04f4e5d8b70ad9474/packages/vitest/src/node/cli.ts#L84) method is not handling the dot options when it's a number.
Also, the work-around only works when putting the enabled before the 100.
I may be missing something here, if someone can double-check it I would be happy =)

Here are the tests (using something different from `--coverage.` also throws the same error)
```
"test": "vitest run --coverage.100",
examples/basic test: After CAC parse {
examples/basic test:   '--': [],
examples/basic test:   segfaultRetry: 0,
examples/basic test:   color: true,
examples/basic test:   bail: 0,
examples/basic test:   retry: 0,
examples/basic test:   coverage: [ <100 empty items>, true ],
examples/basic test:   allowOnly: true,
examples/basic test:   run: true,
examples/basic test:   watch: false
examples/basic test: }

"test": "vitest run --coverage.a100",
examples/basic test: After CAC parse {
examples/basic test:   '--': [],
examples/basic test:   segfaultRetry: 0,
examples/basic test:   color: true,
examples/basic test:   bail: 0,
examples/basic test:   retry: 0,
examples/basic test:   coverage: { a100: true },
examples/basic test:   allowOnly: true,
examples/basic test:   run: true,
examples/basic test:   watch: false
examples/basic test: }

"test": "vitest run --coverage.enabled --coverage.100",
examples/basic test: After CAC parse {
examples/basic test:   '--': [],
examples/basic test:   segfaultRetry: 0,
examples/basic test:   color: true,
examples/basic test:   bail: 0,
examples/basic test:   retry: 0,
examples/basic test:   coverage: { '100': true, enabled: true },
examples/basic test:   allowOnly: true,
examples/basic test:   run: true,
examples/basic test:   watch: false
examples/basic test: }

"test": "vitest run  --coverage.100 --coverage.enabled",
examples/basic test: After CAC parse {
examples/basic test:   '--': [],
examples/basic test:   segfaultRetry: 0,
examples/basic test:   color: true,
examples/basic test:   bail: 0,
examples/basic test:   retry: 0,
examples/basic test:   coverage: [ <100 empty items>, true, enabled: true ],
examples/basic test:   allowOnly: true,
examples/basic test:   run: true,
examples/basic test:   watch: false
examples/basic test: }
```

**Comment by AriPerkkio** [comment]
`cac` has caused quite many CLI argument parsing issues. Does it help when specifying `coverage.100` for CAC configuration like done here: https://github.com/vitest-dev/vitest/pull/3983/files#diff-c322bc45ad914ffa25dc80a6918be23a154d9a5e28c7776c662fcb776b430f05R57.

Or if it's passed as default argument in `--coverage` here:

https://github.com/vitest-dev/vitest/blob/4293e1b15111316b8ef622d04f4e5d8b70ad9474/packages/vitest/src/node/cli.ts#L28

Something like this:

```ts
.option('--coverage', 'Enable coverage report', { default: { enabled: false, 100: false } })
```
