### ISSUE TITLE
The output of `defineProject` can't be used as an argument in `mergeConfig`

### ISSUE THREAD

**Issue by matchai** [vitest-dev/vitest#4316]
### Describe the bug

Reproducing the configuration [provided in the docs](https://vitest.dev/guide/workspace.html#configuration), TS surfaces a type error:

```ts
import { defineProject, mergeConfig } from 'vitest/config'
import configShared from '../vitest.shared.js'

export default mergeConfig(
  configShared,
  defineProject({  << Argument of type 'UserProjectConfigExport' is not assignable to parameter of type 'UserWorkspaceConfig | Promise<UserWorkspaceConfig>'.
    test: {
      environment: 'jsdom',
    }
  })
)
```

### Reproduction

Reproduction with relevant TS error:
https://stackblitz.com/edit/vitest-dev-vitest-bfmggz?file=packages%2Fexample%2Fvitest.config.ts

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M2
    Memory: 496.63 MB / 24.00 GB
    Shell: 3.6.1 - /run/current-system/sw/bin/fish
  Binaries:
    Node: 20.7.0 - ~/Library/Caches/fnm_multishells/13490_1696999864522/bin/node
    npm: 10.1.0 - /opt/homebrew/bin/npm
    pnpm: 8.8.0 - ~/Library/pnpm/pnpm
    Watchman: 2023.08.14.00 - /Users/matchai/.nix-profile/bin/watchman
  Browsers:
    Brave Browser: 109.1.47.171
    Chrome: 118.0.5993.70
    Safari: 17.0
  npmPackages:
    @vitest/coverage-v8: ^0.34.6 => 0.34.6
    vitest: 1.0.0-beta.2 => 1.0.0-beta.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Nic-S** [comment]
I have same TS error

**Comment by christowiz** [comment]
I also have the same error

**Comment by aiekseu** [comment]
using `defineConfig` solves the issue, like so

```
import { **defineConfig**, mergeConfig } from 'vitest/config'
import configShared from '../vitest.shared.js'

export default mergeConfig(
  configShared,
  **defineConfig**({ 
    test: {
      environment: 'jsdom',
    }
  })
)
```
