### ISSUE TITLE
Can't mock virtual modules without testTransformMode.ssr after 0.34

### ISSUE THREAD

**Issue by carlossluzala** [vitest-dev/vitest#4326]
### Describe the bug

After 0.34 mocking virtual modules is not possible without set testTransformMode.ssr to ``["**/*]``

```tsx
import App from './App';
import { render, screen } from '@testing-library/react';

vi.mock('external/AnyComponent', () => ({
  AnyComponent: () => <div>AnyComponentMocked</div>,
}));

describe('Simple working test', () => {
  it('mock component correctly', () => {
    render(<App />);
    expect(screen.getByText(/AnyComponentMocked/i)).toBeInTheDocument();
  });
});
````

![image](https://github.com/vitest-dev/vitest/assets/124888612/02cc8e19-94ee-4523-ab85-22815daab0be)

### Reproduction

See: https://stackblitz.com/edit/vitest-dev-vitest-pbn9uq?file=vite.config.ts,src%2FApp.tsx,package.json,src%2FApp.test.tsx

### System Info

```shell
n/a
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Yep, this is how Vite works in the browser. You need to define those files in a plugin:

```ts
export default {
  plugins: [
    { resolveId: (id) => id.startsWith("external/") ? "virtual:" + id : undefined }
  ]
}
```

**Comment by carlossluzala** [comment]
Thanks @sheremet-va!

So  it is trying to optimize that dep or what? Can you explain a little bit how it works?

**Comment by oskarols** [comment]
@sheremet-va This seems like a rather big departure that it's seemingly required to actually map the virtual file to an _actual file_. Is there some alternative approach if we don't want to do this, and just want to supply a mock?

We're having to use global mocks defined via `resolve` for this which is not ideal.

**Comment by sheremet-va** [comment]
> @sheremet-va This seems like a rather big departure that it's seemingly required to actually map the virtual file to an _actual file_. Is there some alternative approach if we don't want to do this, and just want to supply a mock?

You don't need to have a file, you just need to tell Vite that the ID is resolvable.

**Comment by sheremet-va** [comment]
> So it is trying to optimize that dep or what? Can you explain a little bit how it works?

Vite throws an error because it cannot resolve the import. It doesn't fail in SSR because it expects this to be handled by the runtime.

Usually, you also need to provide `load` plugin hook to let Vite know the source file, but if you are using `vi.mock`, the `load` hook is never called because Vitest intercepts the request and returns the factory result. Vitest cannot intercept it if Vite throws a resolution error during the parsing phase (which is happening in this issue).
