### ISSUE TITLE
updating the mock

### ISSUE THREAD

**Issue by guptstagram** [vitest-dev/vitest#4327]
### Describe the bug

Here's my react component

```typescript
const LosingOrdersViewsBanner: FC = () => {
    const { subtab } = useIPPTabCount();

    console.log('A________', subtab);

    return (
        <InfoBanner
            icon={
                <InfoFilled
                    color={ThemeColors.yellowAction}
                    height={18}
                    width={18}
                />
            }
            message={
                subtab === SUBTABS_KEYS[1]
                    ? LOSING_BANNER_TEXTS.LOSING_VIEWS
                    : LOSING_BANNER_TEXTS.LOSING_ORDERS
            }
            severity="info"
        />
    );
};
``` 

Test File
```typescript
describe('LosingOrdersViewsBanner', () => {
    it('should render the banner with the correct message for the orders subtab', () => {
        vi.mock('@store/actionCreators/IPPHooks/useIPPTabCount', () => ({
            default: vi.fn().mockReturnValue({ subtab: 'lorders' }),
        }));
        render(<LosingOrdersViewsBanner />);
        expect(
            screen.getByText(LOSING_BANNER_TEXTS.LOSING_ORDERS)
        ).toBeInTheDocument();
    });

    it('should render the banner with the correct message for the views subtab', async () => {
        vi.mock('@store/actionCreators/IPPHooks/useIPPTabCount', () => ({
            default: vi.fn().mockReturnValue({ subtab: 'lviews' }),
        }));
        render(<LosingOrdersViewsBanner />);
        expect(
            screen.getByText(LOSING_BANNER_TEXTS.LOSING_VIEWS)
        ).toBeInTheDocument();
    });
});
``` 

I am trying to get different values from a mock for two different test cases.

my component is using the value of subtab from hook useIPPTabCount `const { subtab } = useIPPTabCount();`

now for my first test case, I want the value of the subtab to be `lorders` and `lviews` for the second and maybe so on for further test cases but in vitest once I mock the module, it returns the same value for each test case.

### Reproduction

NA

### System Info

```shell
NA
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is a question, not an issue: https://github.com/vitest-dev/vitest/discussions/4328
