### ISSUE TITLE
Error when importing an ESM package via a CJS package

### ISSUE THREAD

**Issue by betabandido** [vitest-dev/vitest#4332]
### Describe the bug

I have created an ESM package (parent) that imports a CJS package (child), which in turn imports an ESM-only package ([es-cookie](https://www.npmjs.com/package/es-cookie)).

When running vitest on the parent package I get the following error:

```
│ Error: require() of ES Module /home/runner/vitest-cjs/node_modules/.pnpm/es-cookie@1.4.0/node_modules/es-cookie/src/es-cookie.js from /home/runner/vite…
│ Instead change the require of es-cookie.js in /home/runner/vitest-cjs/packages/child/dist/cjs/index.js to a dynamic import() which is available in all …
│  ❯ async /home/runner/vitest-cjs/packages/parent/src/index.ts:1:31
│  ❯ async /home/runner/vitest-cjs/packages/parent/src/index.test.ts:2:31
```

When the child package is ESM instead of CJS, tests run as expected, though. Yet, we do not have control over this child package, so we cannot convert it to ESM. I have tried inlining `es-cookie`, but the issue did not resolve. This issue is preventing us from moving from jest to vitest.

### Reproduction

I have created an environment that reproduces the error here: https://replit.com/@betabandido/vitest-cjs (I just realized a StackBlitz environment was requested, but hopefully the Replit one is good too; if that's not the case, please let me know, and I'll move it to StackBlitz).

To build and test both packages, run:

```shell
pnpm -r build
pnpm -r test
```

The second command should fail with the error described above.

### System Info

```shell
System:
    OS: Linux 6.2 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Xeon(R) CPU @ 2.20GHz
    Memory: 42.94 GB / 62.79 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.12.1 - /nix/store/dj805sw07vvpbxx39c8g67x8qddg0ikw-nodejs-18.12.1/bin/node
    Yarn: 1.22.19 - /nix/store/zdcnqq55qi214j46zgw2qa1jp4dpdf2m-yarn-1.22.19/bin/yarn
    npm: 8.19.2 - /nix/store/dj805sw07vvpbxx39c8g67x8qddg0ikw-nodejs-18.12.1/bin/npm
    pnpm: 8.9.2 - ~/vitest-cjs/.config/npm/node_global/bin/pnpm
  npmPackages:
    vitest: ^0.34.6 => 0.34.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is expected behavior. You cannot use require (whenever it is) to import ES module.
