### ISSUE TITLE
Be able to customize WebdriverIO capabilities

### ISSUE THREAD

**Issue by thomasjm** [vitest-dev/vitest#4335]
### Clear and concise description of the problem

At the moment, the WebdriverIO capabilities are hardcoded here:

https://github.com/vitest-dev/vitest/blob/80a706a1686741ff3c3772cb8e0c515c83ddefe4/packages/vitest/src/node/browser/webdriver.ts#L59-L62

This prevents me from customizing them. For example, I'd like to be able to change the Chrome and chromedriver binaries, as described [here](https://webdriver.io/docs/driverbinaries/#customizing-the-level-of-automation), since I want to provide them myself.

### Suggested solution

I'd like to be able to configure things in the Vite test options, in the same place where I select the `webdriverio` provider. Perhaps a function that allows me to transform the default capabilities:

```javascript
  test: {
    browser: {
      enabled: true,
      name: "chrome",
      provider: "webdriverio",

      // New option
      transformWebdriverIOCapabilities: (caps) => {
        caps['goog:chromeOptions'] = {
          binary: "/my/chrome/binary",
          args: ['headless', 'disable-gpu']
        };
      }
    },
    ...
  },
```

One could also extend the `provider` attribute, perhaps

```javascript
  test: {
    browser: {
      enabled: true,
      name: "chrome",

      // Modified provider field
      provider: {
        name: "webdriverio",
        transformCapabilities: (caps) => ...,
      }
  }

```

### Alternative

I tried putting options in the `wdio.conf.ts` file as described in the WebDriverIO docs, but these options seem to be ignored.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
There is an open PR for this, but the author stopped working on it seems like: https://github.com/vitest-dev/vitest/pull/3758

**Comment by sheremet-va** [comment]
This is supported since #4364.

**Comment by FL33TW00D** [comment]
To anyone that may be running headless tests with configuration from a file, you can do the following:
```js
//vite.config.js
import config from "./webdriver.json";
export default defineConfig({
  test: {
    browser: {
      enabled: true,
      headless: true,
      name: "chrome",
      providerOptions: {
        capabilities: config, 
      }
    },
    testTimeout: 30000,
  },
});

//webdriver.json
{
  "goog:chromeOptions": {
    "args": [
        "--no-sandbox",
    ]
  }
}
```
It should just work!

Thanks for implementing @sheremet-va ❤️
