### ISSUE TITLE
The requested module '/node_modules/util/util.js' does not provide an export named

### ISSUE THREAD

**Issue by nazarhussain** [vitest-dev/vitest#4337]
### Describe the bug

While investigating an issue, I found out a simple code base which works with `0.34.6` is not working with `1.0.0-beta.2` and `1.0.0-beta.1` and throwing following error **only in browser mode**

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
SyntaxError: The requested module '/node_modules/util/util.js?v=ee30bd84' does not provide an export named '__vi_inject__'
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

```

### Reproduction

**src/format.js**
```js
import * as util from "node:util";

export function format(value) {
  return util.format('%s:%s', value, value);
}
```

**test/format.test.js**
```js
import { expect, test } from 'vitest'
import { sum, format } from '../src/format.js'

test('format', () => {
  expect(format("a")).toBe("a:a")
})
```
**command**
```bash
yarn vitest --run --browser chrome
```

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 2.03 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.7.0 - ~/.asdf/installs/nodejs/20.7.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/installs/nodejs/20.7.0/bin/yarn
    npm: 10.1.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Brave Browser: 118.1.59.117
    Chrome: 118.0.5993.88
    Safari: 17.0
  npmPackages:
    @vitest/browser: 0.34.6 => 0.34.6 
    vitest: 0.34.6 => 0.34.6
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nazarhussain** [comment]
@AriPerkkio Thanks for pointing out. Would you also suggest how to add the polyfills with `1.0.0-beta.2` ?

**Comment by AriPerkkio** [comment]
How are you polyfilling that for your production build? Surely `node:util` doesn't run in browser in your production build either.

Previously Vitest was using https://npmjs.com/package/modern-node-polyfills - you could use that one I guess.

**Comment by nazarhussain** [comment]
> Third party plugins like https://www.npmjs.com/package/vite-plugin-node-polyfills should work.

Thanks that worked. 

Problem was with my understanding that `vite` plugins are not related to `vitest`.

**Comment by sheremet-va** [comment]
> Would be nice if we document this clearly in the vitest docs, such polyfills are very common tasks for modern applications.

Documentation mention that you can use any Vite options:

https://vitest.dev/config/#options

> In addition to the following options, you can also use any configuration option from [Vite](https://vitejs.dev/config/). For example, define to define global variables, or resolve.alias to define aliases.
