### ISSUE TITLE
Warn if environment in environmentMatchGlobs isn't found

### ISSUE THREAD

**Issue by hornta** [vitest-dev/vitest#4348]
### Clear and concise description of the problem

Reporting of missing environment could improve troubleshooting why no tests are matched. This if my config file:

```ts
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environmentMatchGlobs: [["./src/**", "missing-env"]],
  }
});
```

### Suggested solution

Output something like this when tests are running
`warn: environment "missing-env" isn't found`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I am not sure what you mean. It should already throw an error, no? Of course, only if there are any tests.

**Comment by hornta** [comment]
I didnt get an error so that's why I created this.

**Comment by sheremet-va** [comment]
I get an error: https://stackblitz.com/edit/vitest-dev-vitest-ugmjpl?file=vite.config.ts,test%2Fbasic.test.ts&initialPath=__vitest__/

**Comment by hornta** [comment]
Ah now I see, the error only seems to be hidden if `setupFiles: ["./src/test/setup.ts"],` is included in the config file

**Comment by sheremet-va** [comment]
> The error only seems to be hidden if `setupFiles: ["./src/test/setup.ts"],` is included in the config file, which is what I had in my vitest.config.ts but I excluded it from this issue because I didn't think it had anything to do with the error output.

I still get an error if I have a setup file: https://stackblitz.com/edit/vitest-dev-vitest-6v8fgr?file=vite.config.ts,setup.ts&initialPath=__vitest__/

**Comment by hornta** [comment]
I hope I got this right now: https://stackblitz.com/edit/vitest-dev-vitest-v1dwqz?file=vite.config.ts
![image](https://github.com/vitest-dev/vitest/assets/4553604/23598cba-ce7c-498f-af7d-253499ca6ebe)

**Comment by sheremet-va** [comment]
I still see errors in the console 🤔 

![image](https://github.com/vitest-dev/vitest/assets/16173870/6b209ccb-5b71-4dc7-98c3-14e27b270af7)

**Comment by hornta** [comment]
This is the exact config which gives me zero errors. I forgot to include `threads: false`
```ts
/// <reference types="vitest" />

// Configure Vitest (https://vitest.dev/config/)

import { defineConfig } from 'vite';

export default defineConfig({
  test: {
    environmentMatchGlobs: [['**/*', 'missing-env']],
    /* for example, use global to avoid globals imports (describe, test, expect): */
    // globals: true,
    setupFiles: ["./src/test/setup.ts"],
    threads: false,
  },
});
```

**Comment by hornta** [comment]
![19b34c5f-6a7f-41ba-8e31-cda43084815d](https://github.com/vitest-dev/vitest/assets/4553604/d09eec8b-10ba-4371-90d8-10cf1b5a64e7)

**Comment by sheremet-va** [comment]
Now I can reproduce it, thank you.

**Comment by hi-ogawa** [comment]
`threads: false` option doesn't exist anymore and I couldn't reproduce a similar issue with new options such as `pool` or `isolate`:

https://stackblitz.com/edit/vitest-dev-vitest-beh3u9?file=vite.config.ts
