### ISSUE TITLE
Vitest fails when using vite-plugin-ruby

### ISSUE THREAD

**Issue by timgoeller** [vitest-dev/vitest#436]
### Describe the bug

Based on this issue in the `vite-plugin-ruby` repo: https://github.com/ElMassimo/vite_ruby/issues/170

When using `vite-plugin-ruby`, the execution of Vue Component Tests does not work. It fails with `Error: failed to load /vite-development/@vite/client`. @ElMassimo mentioned, that it is probably related to the use of `base` (https://github.com/ElMassimo/vite_ruby/issues/170#issuecomment-1004716873). 

### Reproduction

https://stackblitz.com/edit/node-sr8dj2?file=vite.config.js

### System Info

```shell
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 79.82 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.asdf/installs/nodejs/16.13.1/bin/node
    Yarn: 1.22.17 - ~/.asdf/installs/nodejs/16.13.1/.npm/bin/yarn
    npm: 8.1.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0.2
    Safari: 14.1.1
    Safari Technology Preview: 14.2
  npmPackages:
    @vitejs/plugin-vue: ^2.0.1 => 2.0.1 
    vite: ^2.7.0 => 2.7.10 
    vitest: ^0.0.131 => 0.0.131
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
The reproduction you provided fails with other error. I also downloaded your repo and it doesn't fail at all.

Did you mean to issue this error: `Cannot read properties of undefined (reading 'userAgent')`?

**Comment by timgoeller** [comment]
@sheremet-va My bad, the repo worked because `publicOutputDir` in `vite.json` was set to `""` to check if the issue actually has something to do with `base`. I've changed it to values one would actually use, and it should fail now. 

The message `Cannot read properties of undefined (reading 'userAgent')` is the desired state on stackblitz, since it shows the test ran.
