### ISSUE TITLE
Custom matchers are not added to the local `expect`

### ISSUE THREAD

**Issue by joelmukuthu** [vitest-dev/vitest#4360]
### Describe the bug

When a custom matcher is added via `expect.extend`, it becomes available on the global `expect` but not the `expect` in the test  context:

```js
import { describe, expect, it } from 'vitest';

expect.extend({
  foo() {
    return {
      pass: true,
      message: () => `foo`,
    };
  },
});

it('global `expect`', () => {
  expect.foo(); // passes
});

it('local `expect`', ({ expect }) => {
  expect.foo(); // fails
});
```

Is this a bug or is it working as expected?

PS: I can work-around this by calling `expect.extend` inside a `beforeEach`.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-vcvflq?file=test%2Fbasic.test.ts or code snippet above.

### System Info

```shell
Vitest: v0.34.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I feel like it should be added even to local `expects`, but I am not sure why it already doesn't do this.

**Comment by hi-ogawa** [comment]
Expanding on OP's example, it seems that non-working case is only when it is used as "asymmetric matcher".

```tsx
describe('custom matcher inherited from global to local', () => {
  expect.extend({
    toFooTest() {
      return {
        pass: true,
        message: () => `foo`,
      }
    },
  })

  it('basic', ({ expect: localExpect }) => {
    // as assertion
    expect(expect('test')).toHaveProperty('toFooTest')
    expect(expect.soft("test")).toHaveProperty('toFooTest')
    expect(localExpect('test')).toHaveProperty('toFooTest')
    expect(localExpect.soft('test')).toHaveProperty('toFooTest')

    // as asymmetric matcher
    expect(expect).toHaveProperty('toFooTest')
    expect(localExpect.not).toHaveProperty('toFooTest')

    // TODO: not working
    expect(localExpect).toHaveProperty('toFooTest')
  })
})
```

Still an early investigation, but the code below might be related.
Custom asymmetric matcher is defined via `Object.defineProperty` but somehow this might not be properly inherited by local context's "expect".

https://github.com/vitest-dev/vitest/blob/42b4101e759649b38c35262e04a04d9b88e01da0/packages/expect/src/jest-extend.ts#L111-L116
