### ISSUE TITLE
Migrate coverage from v8 to c8

### ISSUE THREAD

**Issue by aentwist** [vitest-dev/vitest#4366]
### Clear and concise description of the problem

The latest stable version of vitest 0.34.6 uses v8 for that flavor of coverage. However, from [v8](https://www.npmjs.com/package/v8-coverage),

<blockquote>
<h3>This package has been deprecated</h3>

Author message:
<code>This tool was built when [c8](https://github.com/bcoe/c8) package wasn't ready to be used, c8 has now more functionality and works better that this module. So you should really use c8.</code>
</blockquote>

### Suggested solution

Go back to c8

### Alternative

Suggest to install c8, but use c8 or v8 - whichever one is available (allow choice via manual installation)

Edit: after reading more I guess this is literally 2x the effort to maintain so it isn't possible

### Additional context

Pull request that includes the motivation for moving from c8 to v8 https://github.com/vitest-dev/vitest/pull/3339

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by aentwist** [comment]
Workaround: pin vitest version to 0.31

**Comment by sheremet-va** [comment]
Vitest never used that package. To use v8 coverage, install `@vitest/coverage-v8`.
