### ISSUE TITLE
Support tap reporter

### ISSUE THREAD

**Issue by patak-dev** [vitest-dev/vitest#437]
### Clear and concise description of the problem

Implement tap reporter https://node-tap.org/tap-protocol/, to give users access to the tap ecosystem of converters. See for example https://www.npmjs.com/package/tap-junit (@Demivan)

Note [From Koko in Vitest Dev](https://discord.com/channels/917386801235247114/918057929670811708/923871623818403850)
> The one thing to keep in mind about TAP is that the official, spec-complient TAP output doesn't support indents on nested tests, which is bad UI imo. Some runner like zora or node-tap implement the TAP spec but with indents 
> https://github.com/TestAnything/Specification/issues/2
> So if TAP is going to be implemented in core, this is a feature most of users would want I guess

### Suggested solution

Add a new `tap` option to the built in reporters

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Demivan** [comment]
I will work on this

**Comment by Demivan** [comment]
https://github.com/vitest-dev/vitest/pull/445 - it done done
But it is not compatible with https://www.npmjs.com/package/tap-junit as tap-junit does not support nested tests. But https://github.com/tapjs/tap-mocha-reporter works great.

**Comment by patak-dev** [comment]
Closed by #445, awesome work @Demivan 🎉
