### ISSUE TITLE
`vi.mock`'s `importOriginal` stuck on circular imports 

### ISSUE THREAD

**Issue by AriPerkkio** [vitest-dev/vitest#4373]
### Describe the bug

When a test imports file that contains circular imports and also mocks some of these files, `vi.mock`'s `importOriginal` does not resolve. Whats worse is that `vite-node` silently hangs and doesn't log any timeout errors. Even `birpc` doesn't timeout here for some reason.

```js
import '../src/module-1';

vi.mock('../src/module-2', async (importOriginal) => {
  console.log('Start importOriginal');
  await importOriginal();
  //    ^^^ Never resolves

  console.log('Done importOriginal');

  return { default: () => {} };
});
```

```
$ DEBUG=vite-node:* pnpm run test tests/cyclic-imports.test.ts 

> example-project@1.0.0 test /<path>/vitest-example-project
> vitest run "tests/cyclic-imports.test.ts"


 RUN  v1.0.0-beta.2 /<path>/vitest-example-project

  vite-node:server:request /@vite/env +0ms
2023-10-25T18:22:43.172Z vite-node:client:execute /@vite/env
2023-10-25T18:22:43.174Z vite-node:client:native /<path>/vitest/packages/vitest/dist/spy.js
2023-10-25T18:22:43.200Z vite-node:client:native /<path>/vitest/packages/vitest/dist/runners.js
  vite-node:server:request /<path>/vitest-example-project/tests/cyclic-imports.test.ts +42ms
2023-10-25T18:22:43.210Z vite-node:client:execute /<path>/vitest-example-project/tests/cyclic-imports.test.ts
2023-10-25T18:22:43.211Z vite-node:client:native /<path>/vitest/packages/vitest/dist/index.js
  vite-node:server:request /src/module-1.ts +11ms
2023-10-25T18:22:43.215Z vite-node:client:execute /<path>/vitest-example-project/src/module-1.ts
  vite-node:server:request /<path>/vitest-example-project/src/module-2.ts +28ms
stdout | tests/cyclic-imports.test.ts:3:11
Start importOriginal

2023-10-25T18:22:43.244Z vite-node:client:execute /<path>/vitest-example-project/src/module-2.ts
  vite-node:server:request /src/module-3.ts +3ms
2023-10-25T18:22:43.246Z vite-node:client:execute /<path>/vitest-example-project/src/module-3.ts
  vite-node:server:request /src/module-4.ts +3ms
2023-10-25T18:22:43.248Z vite-node:client:execute /<path>/vitest-example-project/src/module-4.ts

# Stuck here, CTRL+C terminates process correctly
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-8gzjhq?file=test%2Fcyclic-import.test.mjs

### System Info

```shell
Stackblitz

- Vitest v1 beta and 0.3x.x releases
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by transfer1992** [comment]
Very frustrating, especially because it is completely silent. Spent few hours on this.

**Comment by mcclayton** [comment]
This issue appears to be related to:
https://github.com/vitest-dev/vitest/issues/4026

I ultimately fixed this by addressing the circular dependencies (using the eslint rule: https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-cycle.md#when-not-to-use-it)

However, it was incredibly difficult to determine that it was ultimately the circular dependencies since vitest just hung without any error output or timeout. Hope these issues can get visibility for others stuck with this.

**Comment by AriPerkkio** [comment]
I ran into this issue again - this time caused by circular dependency coming from a barrel file. By using the `VITE_NODE_DEBUG_RUNNER=true` it's possible to see the modules that are stuck loading. From those logs I could figure out the root cause. 

https://github.com/vitest-dev/vitest/blob/039814bd0eb9ed7b7f6e649a1c3def38d5174a5d/packages/vite-node/README.md?plain=1#L152-L158

**Comment by sheremet-va** [comment]
I found the culprit, PR incoming.

**Comment by dlvhdr** [comment]
How can I test this fix?
I have a yarn v1 monorepo and can't figure out how to test this change.
I tried using the `"vitest": "file:/Users/dlvhdr/code/misc/vitest/packages/vitest"` syntax, as well as running vitest from the build artifacts.
For the first - yarn doesn't know what I mean
For the latter - I get a weird `error:0909006C:PEM routines:get_name:no start line` error.

**Comment by dlvhdr** [comment]
Ok I managed to make it work and this does fix the issue. I just had to remove the `packageManager` entry from the `package.json`.
