### ISSUE TITLE
@vitest/coverage-v8 has an improper peer dependency in 1.0.0-beta.2

### ISSUE THREAD

**Issue by mpodwysocki** [vitest-dev/vitest#4374]
### Describe the bug

Currently published @vitest/coverage-v8 has an improper peer dependency and will fail to install with vitest 1.0.0-beta.2.

The `package.json` currently published is the following with the [npm code view](https://www.npmjs.com/package/@vitest/coverage-v8/v/1.0.0-beta.2?activeTab=code)

```json
  "peerDependencies": {
    "vitest": ">=0.32.0 <1"
  },
```

This causes pnpm to fail to install.

### Reproduction

Updating using pnpm where we do not allow strict peer dependencies to fail.

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M2
    Memory: 189.48 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.0.0 - ~/.nvm/versions/node/v21.0.0/bin/node
    npm: 10.2.0 - ~/.nvm/versions/node/v21.0.0/bin/npm
    pnpm: 8.9.2 - /opt/homebrew/bin/pnpm
  Browsers:
    Brave Browser: 118.1.59.122
    Chrome: 118.0.5993.117
    Safari: 17.0
    Safari Technology Preview: 17.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Fixed by https://github.com/vitest-dev/vitest/pull/4299.

**Comment by mpodwysocki** [comment]
@AriPerkkio When do we expect the fix to be published?

**Comment by AriPerkkio** [comment]
https://github.com/vitest-dev/vitest/releases/tag/v1.0.0-beta.3
