### ISSUE TITLE
not matching snapshot affects console.log functionality when mocked

### ISSUE THREAD

**Issue by luckylooke** [vitest-dev/vitest#4381]
### Describe the bug

When snapshot don't match (inline or file), console stop working. I am using a mock replacement for one test to document/show debug mode of my implementation. I don't want to use spy as I don't want to have polluted test runner console.

I know that this seems to be edge case, but anyway, it should not be affected 😬 

### Reproduction

Working code:
```ts

     function someMethod(options?: { debug: boolean }) {
        if (options?.debug) console.log('some debug info');
      }
      it('has debug mode issue', () => {
        const logMethod = console.log.bind(console);
        console.log = vi.fn();

        // calling method without debug mode
        someMethod();

        // no debug info yet as debug is false by default
        expect((console.log as Mock).mock.calls).toMatchInlineSnapshot('[]');

        // calling method with debug mode
        someMethod({ debug: true });

        expect((console.log as Mock).mock.calls).toMatchInlineSnapshot(`
        [
          [
            "some debug info",
          ],
        ]
      `);

        console.log = logMethod; // set back original method
      });

      function otherMethod() {
        console.log('some temporary console.log debug info');
      }
      it('has debug mode issue other', () => {
        expect(otherMethod()).toBeUndefined();
      });
      
```
It will log 'some temporary console.log debug info' into test runner console. Which is correct.. it used for debugging code.

but now try to change 'some debug info' in `if (options?.debug) console.log('some debug info');` so snapshots don't match now.. 'some temporary console.log debug info' is not logged anymore, preventing code to be debugged via console logs while snapshot does not match

### System Info

```shell
System:
    OS: macOS 12.6.8
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 32.83 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 118.0.5993.117
    Firefox: 116.0.3
    Safari: 16.6
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0 
    @vitest/coverage-c8: ^0.28.1 => 0.28.1 
    @vitest/coverage-v8: ^0.32.2 => 0.32.2 
    vite: ^4.0.0 => 4.0.4 
    vitest: ^0.34.6 => 0.34.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by luckylooke** [comment]
Voila https://stackblitz.com/edit/vitest-dev-vitest-jftnew?file=test%2Fsuite.test.ts thanks 🙏

**Comment by sheremet-va** [comment]
This is expected behavior. `expect` throws an error, so code after it is not executed. You need to better structure your tests: you can restore `console.log` in `afterEach` hook or use `vi.spyOn` instead and enable [`test.restoreMocks`](https://vitest.dev/config/#restoremocks) in config file.
