### ISSUE TITLE
Allow more execArgv flags to be passed to workers

### ISSUE THREAD

**Issue by adriencaccia** [vitest-dev/vitest#4382]
### Clear and concise description of the problem

I need to pass execution flags to the workers to fully support `vitest` on CodSpeed (more details below). At this time, execution flags are all filtered out except `--cpu-prof` and `--heap-prof`.
The flags are described here: https://github.com/CodSpeedHQ/codspeed-node/blob/707a076f6178125fa1042f4a4decd51d11b03b56/packages/core/src/introspection.ts#L5-L21

### Suggested solution

It is a touchy subject that can lead to bugs as already stated in the code comment below and in https://github.com/vitest-dev/vitest/pull/2702.
I would propose some kind of escape hatch for library authors where we can remove the filtering entirely. Using a specific env variable for example.

The change would need to be done in https://github.com/vitest-dev/vitest/blob/29299f3ce247c92c2042bb69f75dd1712df39f13/packages/vitest/src/node/pool.ts#L63-L67

### Alternative

Expose an option directly in `vitest` config, to specify the flags to be passed to the workers. 

### Additional context

I am working on adding first class `vitest` support to CodSpeed, I started the work at https://github.com/CodSpeedHQ/codspeed-node/pull/26. In order to have automated flame graphs with each benchmark, we need to pass a few additional v8 args to the workers.
I managed to get it working with a [patch of `vitest` removing the filtering](https://github.com/CodSpeedHQ/codspeed-node/pull/26/commits/87634da94916fa1c6773a51a9ea944a5ed708b43).

With `pool: 'forks'`, all the flags needed by CodSpeed are working, as this job is working https://github.com/CodSpeedHQ/codspeed-node/actions/runs/6668657521/job/18124687199.

However, I tested it with the default `pool: 'threads'` and got an error because one of the flags was not supported, highlighting that allowing all flags for every pool method is definitely not the way to go.

I would gladly do a PR if and when we agree on what API to expose 😃 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Maybe we can expose a way to pass down `execArgs` in `poolOptions.{threads,forks,vmThreads}`?

**Comment by adriencaccia** [comment]
Yep that would work for me!
