### ISSUE TITLE
Upgrading to 1.0.0-beta.3 causes browser failures

### ISSUE THREAD

**Issue by mpodwysocki** [vitest-dev/vitest#4384]
### Describe the bug

Upgrading from 1.0.0-beta.3 from 1.0.0-beta.2 causes browser test failures.  Previously worked in beta 2, however, upgrading caused the following bug in our code:

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
SyntaxError: The requested module '/@fs/Users/matthewp/git/azure-sdk-for-js-copy/common/temp/node_modules/.pnpm/loupe@2.3.7/node_modules/loupe/loupe.js?v=75aa2813' does not provide an export named '__vi_inject__'
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 Test Files  no tests
      Tests  no tests
     Errors  1 error
   Start at  12:44:49
   Duration  6.98s (transform 0ms, setup 0ms, collect 0ms, tests 0ms, environment 0ms, prepare 0ms)
```

Testing in Node is unaffected by this upgrade.

### Reproduction

Current package json which has our relevant dependencies:

```json
    "@types/node": "^18.11.9",
    "@types/trusted-types": "^2.0.0",
    "@vitest/browser": "1.0.0-beta.3",
    "eslint": "^8.0.0",
    "prettier": "^3.0.3",
    "rimraf": "^5.0.5",
    "tshy": "^1.7.0",
    "typescript": "~5.0.0",
    "vitest": "1.0.0-beta.3",
    "webdriverio": "^8.20.4"
```

Our current configuration for the browser:

```typescript
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    reporters: ["basic", "junit"],
    outputFile: {
      junit: "test-results.browser.xml",
    },
    browser: {
      enabled: true,
      headless: true,
      name: "chrome",
      provider: "webdriverio",
    },
    fakeTimers: {
      toFake: ["setTimeout"],
    },
    watch: false,
    include: ["./dist-test/browser/**/*.spec.js"],
  },
});
```

PR which worked in 1.0.0-beta.2, now does not work in beta 3: [Upgrade Core to ESM](https://github.com/Azure/azure-sdk-for-js/commit/435492a4b2c44d30f282a5fd7ab18768984c9330)

### System Info

```shell
System:
    OS: macOS 14.1
    CPU: (8) arm64 Apple M2
    Memory: 73.33 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.0.0 - ~/.nvm/versions/node/v21.0.0/bin/node
    npm: 10.2.0 - ~/.nvm/versions/node/v21.0.0/bin/npm
    pnpm: 8.9.2 - /opt/homebrew/bin/pnpm
  Browsers:
    Brave Browser: 118.1.59.124
    Chrome: 118.0.5993.117
    Safari: 17.1
    Safari Technology Preview: 17.4
  npmPackages:
    @vitest/browser: 1.0.0-beta.3 => 1.0.0-beta.3
    vitest: 1.0.0-beta.3 => 1.0.0-beta.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Disabling [`test.browser.slowHijackESM`](https://vitest.dev/config/#browser-slowhijackesm) should temporarily help.

**Comment by mpodwysocki** [comment]
@sheremet-va That creates another error of:

```
SyntaxError: The requested module '/@fs/Users/matthewp/git/azure-sdk-for-js-copy/common/temp/node_modules/.pnpm/loupe@2.3.7/node_modules/loupe/loupe.js?v=795ab5f5' does not provide an export named 'inspect'
```

**Comment by sheremet-va** [comment]
> That creates another error of:

This error is much better!

**Comment by AriPerkkio** [comment]
There might be something specific in the project's setup that's causing this. I have one project using browser testing and it works fine with the latest version. It's also using `pnpm`: https://github.com/AriPerkkio/aria-live-capture/actions/runs/6672595464/job/18136819032

**Comment by AriPerkkio** [comment]
I'm unable to reproduce this on fresh project. @mpodwysocki could you re-check your lock-file. Why are there two version of `@vitest/browser` installed?

**Comment by mpodwysocki** [comment]
@AriPerkkio updated @azure/abort-controller to use beta 3 and the error is still happening

**Comment by AriPerkkio** [comment]
Versions in lockfile look better now. But still I'm unable to reproduce this in minimal setup. Not sure what is triggering the condition in your project.

**Comment by mpodwysocki** [comment]
Updated more of the projects and still having the same issue: https://github.com/Azure/azure-sdk-for-js/tree/feat/core-modulear

I wonder if there's a force we can do for the loupe version or if it's some other weird module resolution.  I also need to figure out how to get the [lockfile-explorer](https://github.com/microsoft/rushstack/tree/main/apps/lockfile-explorer) to work properly as well.

**Comment by mpodwysocki** [comment]
Updated to Node types 18 and getting TypeScript across the board and it got past the original issue.  However, I'm now getting the following:

```
Error: Module "node:perf_hooks" has been externalized for browser compatibility. Cannot access "node:perf_hooks.performance" in client code.  See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
```

@AriPerkkio and @sheremet-va what do I need to do here?

**Comment by sheremet-va** [comment]
> @AriPerkkio and @sheremet-va what do I need to do here?

This is a bug with Vitest, it is fixed in main, but you need to wait for a release

**Comment by mpodwysocki** [comment]
Ok, cool, then I'll close the issue from my side.
