### ISSUE TITLE
TypeScript error when using Yarn PnP

### ISSUE THREAD

**Issue by wojtekmaj** [vitest-dev/vitest#4391]
### Error

The following error may appear while type checking, if using Yarn PnP:
```
yarn tsc             
.yarn/unplugged/vitest-virtual-635245b105/node_modules/vitest/dist/reporters-5f784f42.d.ts:15:25 - error TS2307: Cannot find module 'rollup' or its corresponding type declarations.

15 import * as rollup from 'rollup';
                           ~~~~~~~~

Found 1 error in .yarn/unplugged/vitest-virtual-635245b105/node_modules/vitest/dist/reporters-5f784f42.d.ts:15
```

### Why this happens:

`vitest` imports `rollup`, while not declaring it as its dependency. This is illegal in Yarn PnP, and works "by miracle" in non-PnP setups.

Here's why.

Imagine `vitest` relies on `foo@1.0.0` which in turn relies on `bar`. `foo`'s maintainer finds a way to get rid of `bar` dependency without changing its public API. Releases this improvement as a non-breaking version, righfully so.

Now, if you relied on `foo` to provide `vitest` with `bar`, everything falls apart.

In fact, with Vite plans to replace `rollup` with `rolldown` the above is EXACTLY what might happen.

### What we can do about it

Declare `rollup` as `vitest`'s dependency.

### Reproduction

n/a

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 5.44 GB / 15.85 GB
  Binaries:
    Node: 20.9.0 - ~\AppData\Local\Temp\xfs-515b5efc\node.CMD
    Yarn: 4.0.0 - ~\AppData\Local\Temp\xfs-515b5efc\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (118.0.2088.76)
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wojtekmaj** [comment]
Can confirm that adding:

```
packageExtensions:
  "vitest@*":
    dependencies:
      rollup: ^3.25.2
```

to `.yarnrc.yml` fixes the issue, which proves the suggested fix would have worked.

**Comment by sheremet-va** [comment]
Yeah, I wonder why it worked before. I noticed a rogue `rollup` import in types a few days ago - I wonder if it was added during the last update.

Vitest doesn't _depend_ on rollup directly, Vite does, so I don't think we can specify it. However, this should change with #4368 when we upgrade to rollup 4 and have to use `rollup/parseAst`. I guess, we need to specify it as a `peerDependency` now.

**Comment by sheremet-va** [comment]
Can confirm, this is just what `rollup` bundles are because it's externalized when building Vitest: `WorkspaceProject.prototype.getSourceMapModuleById` returns (without an annotation) `rollup.SourceMap`. If vite decides to move away from rollup, this will be changed when Vitest is rebundled.

For now, we can just make the same interface manually and return it there, I guess.

**Comment by wojtekmaj** [comment]
> I wonder if it was added during the last update.

0.33.0 didn't have it as far as I can see. 0.34.0 added the import in `types-3c7dbfa5.d.ts`.
