### ISSUE TITLE
Coverage with v8 provider fails although tests are all successfull

### ISSUE THREAD

**Issue by antonio-masotti** [vitest-dev/vitest#4397]
### Describe the bug

When updating the package @vitest/coverage-v8 to:
- @vitest/coverage-v8: `^1.0.0-beta.2` and `^1.0.0-beta.3` 

the coverage script in a React project fails, although all tests are successful. 

The issue is not present in the last stable release `0.34.6.`

Error message (2 of many, all identical):

~~~bash
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Invalid transform mode: undefined
 ❯ V8CoverageProvider.onAfterSuiteRun node_modules/@vitest/coverage-v8/dist/provider.js:218:13
 ❯ Proxy.onAfterSuiteRun node_modules/vitest/dist/vendor-node.a7c48fe1.js:7143:57
 ❯ MessagePort.<anonymous> node_modules/vitest/dist/vendor-index.b271ebe4.js:59:29
 ❯ [nodejs.internal.kHybridDispatch] node:internal/event_target:757:20
 ❯ exports.emitMessage node:internal/per_context/messageport:23:28

This error originated in "<my test file path>" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Invalid transform mode: undefined
 ❯ V8CoverageProvider.onAfterSuiteRun node_modules/@vitest/coverage-v8/dist/provider.js:218:13
 ❯ Proxy.onAfterSuiteRun node_modules/vitest/dist/vendor-node.a7c48fe1.js:7143:57
 ❯ MessagePort.<anonymous> node_modules/vitest/dist/vendor-index.b271ebe4.js:59:29
 ❯ [nodejs.internal.kHybridDispatch] node:internal/event_target:757:20
 ❯ exports.emitMessage node:internal/per_context/messageport:23:28

This error originated in "<my test file path>" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
~~~

### Reproduction

Minimal project example here: https://github.com/antonio-masotti/vitest-coverage-failing-example 

- Update (using yarn v. 4 in my case) all @vitest/* packages to `^1.0.0-beta.2` or `^1.0.0-beta.3`  
- Run coverage (`vitest coverage`)

### System Info

```shell
~~~sh
  System:
    OS: macOS 14.0
    CPU: (12) arm64 Apple M2 Pro
    Memory: 1.43 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 4.0.1 - ~/.nvm/versions/node/v18.18.0/bin/yarn
    npm: 10.2.0 - ~/.nvm/versions/node/v18.18.0/bin/npm
  Browsers:
    Brave Browser: 118.1.59.122
    Chrome: 118.0.5993.117
    Safari: 17.0
    Safari Technology Preview: 17.4
  npmPackages:
    @vitejs/plugin-react: ^4.1.0 => 4.1.0 
    @vitest/coverage-v8: ^1.0.0-beta.3 => 1.0.0-beta.3 
    @vitest/ui: ^1.0.0-beta.3 => 1.0.0-beta.3 
    vite: ^4.5.0 => 4.5.0 
    vitest: ^0.34.6 => 0.34.6 
~~~
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`@vitest/coverage-v8` and `vitest` version should be the same. In your case, `vitest` is pre-beta, but you use beta coverage package.

**Comment by antonio-masotti** [comment]
> `@vitest/coverage-v8` and `vitest` version should be the same. In your case, `vitest` is pre-beta, but you use beta coverage package.

Thanks @sheremet-va !
