### ISSUE TITLE
`env.mode` is not set to `benchmark` when running `vitest bench`

### ISSUE THREAD

**Issue by adriencaccia** [vitest-dev/vitest#4398]
### Describe the bug

When running `vitest bench`, the `env.mode` variable is set to `test`, where we expect it is set to `benchmark` as explained in the docs:
> Use process.env.VITEST or mode property on defineConfig (will be set to test/benchmark if not overridden) to conditionally apply different configuration in vite.config.ts

### Reproduction

Running `vitest bench` with the following `vitest.config.ts` will log `mode: test`

```typescript
import { defineConfig } from 'vitest/config'

export default defineConfig((env) => {
  console.log('mode:', env.mode)
  // ...
})
```

I found two possible culprits, the first one being https://github.com/vitest-dev/vitest/blob/00e81122e2d61ef32c2550c383873c9a49a806b6/packages/vitest/src/node/create.ts#L26-L27

I think `mode` should be put ahead of `process.env.NODE_ENV`, since it is the computed mode. This is the change I made in the linked PR.

Another possible way of fixing it would be to change https://github.com/vitest-dev/vitest/blob/fc51ad0441bb299b1be323cd90475d6fcd976cbb/packages/vitest/src/node/cli-api.ts#L31

And use `process.env.NODE_ENV ??= options.mode || mode || 'test'` instead. However I do not think that setting `NODE_ENV` to `benchmark` is such a good idea, as where are in a `test` environment, and more often that not users will expect their benchmark code to be executed with `NODE_ENV=test`.

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 63.02 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/Library/Caches/fnm_multishells/74906_1698658724643/bin/node
    npm: 9.5.0 - ~/Library/Caches/fnm_multishells/74906_1698658724643/bin/npm
  Browsers:
    Chrome: 118.0.5993.117
    Firefox: 119.0
    Safari: 17.0
  npmPackages:
    vite: latest => 4.5.0 
    vitest: workspace:* => 1.0.0-beta.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> I think `mode` should be put ahead of `process.env.NODE_ENV`, since it is the computed mode. This is the change I made in the linked PR.

This doesn't make sense because `mode` is always defined. (On the other hand, it looks like `NODE_ENV` is also always defined).

The expectation should be that `NODE_ENV` and `mode` are always the same. I would change it in `cli-api` instead.

**Comment by adriencaccia** [comment]
Got it.
However, not changing `packages/vitest/src/node/create.ts` and only relying on `NODE_ENV` inside would make the `createVitest` API not work, since `NODE_ENV` would most likely be set to something else than `benchmark`.

To ensure that everything works, how about changing the two places?

**Comment by sheremet-va** [comment]
I would rather re-evaluate the usage of `NODE_ENV` altogether. I think we set it because Vite processes it somehow:

https://github.com/vitejs/vite/blob/788145790e7652d715575d7a0bc33a825b49d566/packages/vite/src/node/config.ts#L413
https://github.com/vitejs/vite/blob/788145790e7652d715575d7a0bc33a825b49d566/packages/vite/src/node/config.ts#L565

I think it can only be `development` or `production` 🤔

**Comment by adriencaccia** [comment]
It can also be `test`, as it is done in `jest`. A lot of people really on this value to execute or not some test code.

What about removing all the references to `NODE_ENV` when trying to infer vitest's `mode`?
So changing the two places I outlined, and adding https://github.com/vitest-dev/vitest/blob/3b58487ba0c48bc75dffae467d65737621af75d5/packages/vitest/src/node/workspace.ts#L45 and https://github.com/vitest-dev/vitest/blob/29299f3ce247c92c2042bb69f75dd1712df39f13/packages/vitest/src/node/pool.ts#L78?

**Comment by sheremet-va** [comment]
We should do what Vite does. 

- If `NODE_ENV` is set, then don't touch it
- `NODE_ENV` doesn't change `mode` value, only `--mode` can do that, or it can be changed in the config
- If `NODE_ENV` is not set, set it to `test`

**Comment by adriencaccia** [comment]
> * If `NODE_ENV` is set, then don't touch it
> * `NODE_ENV` doesn't change `mode` value, only `--mode` can do that, or it can be changed in the config
> * If `NODE_ENV` is not set, set it to `test`

I updated #4399 with this!
