### ISSUE TITLE
Consider open up console/stdin input actions so other processes like editors can control what tests to run

### ISSUE THREAD

**Issue by Lilja** [vitest-dev/vitest#4404]
### Clear and concise description of the problem

I run neovim and put my editor in one tmux window and vitest in watch mode in another. Sometimes, when debugging a test, I want to isolate a particular test case meaning I don't want to run all tests just a specific one. What I currently do is to put `test.only` and hope me writing to the source file does not trigger any other files.

But to properly chose which test to run, I need to change the test selection inside of Vitest's console, type `t` then select a name in the prompt.

I understand this might sound like a non-issue. But I believe that if I'm right there in the code, with my cursor just under the test. It should be fairly easy to send this information through a socket or something.

### Suggested solution

I poked around in `packages/vitest/src/node/stdin.ts` and saw that most of the code that does this is already here.
What if we made vitest open up a socket during the watch mode that accepted instructions for what tests to run? Essenially do everything that the `stdin.ts` does except that it gets that information from a socket.

Then I could easily write a plugin in lua for neovim that sends theses instructions sourced from the editor itself.

I would be up for submitting a PR of this.

### Additional context

I stumbled upon this feature by noticing that `.only` does not run only the test the whole codebase, only in that particular file.
I chatted with Vladimir about this [here](https://discord.com/channels/917386801235247114/1168217658777423932/1168217658777423932)
To which I came up with this idea.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Vitest already opens up a socket connection if you provide --api flag. You can control it with @vitest/ws-client package

**Comment by Lilja** [comment]
I looked at that package briefly and concluded that it probably doesn't work in the way that I would want? Looking at the source it has code for [managing test results/on canel/on finish events](https://github.com/vitest-dev/vitest/blob/main/packages/ws-client/src/index.ts#L52-L74)?
I could be wrong though.

**Comment by sheremet-va** [comment]
These are events it receives, you need to look at WebsocketHandlers to see the methods you can call.

**Comment by Lilja** [comment]
Looks like you are right. You can probably write a plugin with that. Closing.
