### ISSUE TITLE
There are X handle(s) keeping the process running; FILEHANDLE

### ISSUE THREAD

**Issue by gajus** [vitest-dev/vitest#4415]
### Describe the bug

This might be not a bug, but where does one even start debugging this?

```
contra-api:test:vitest: There are 6601 handle(s) keeping the process running
contra-api:test:vitest: 
contra-api:test:vitest: # FILEHANDLE
contra-api:test:vitest: node:internal/async_hooks:202
contra-api:test:vitest: 
contra-api:test:vitest: # FILEHANDLE
contra-api:test:vitest: node:internal/async_hooks:202
contra-api:test:vitest: 
contra-api:test:vitest: # Tinypool
contra-api:test:vitest: node:internal/async_hooks:202                                                                                                                         
contra-api:test:vitest: node:internal/async_hooks:505                                                                                                                         
contra-api:test:vitest: file:///home/github/actions-runner/_work/gaia/gaia/node_modules/.pnpm/tinypool@0.7.0/node_modules/tinypool/dist/esm/index.js:36                       
contra-api:test:vitest: file:///home/github/actions-runner/_work/gaia/gaia/node_modules/.pnpm/tinypool@0.7.0/node_modules/tinypool/dist/esm/index.js:57                       
contra-api:test:vitest: file:///home/github/actions-runner/_work/gaia/gaia/node_modules/.pnpm/tinypool@0.7.0/node_modules/tinypool/dist/esm/index.js:799                      
contra-api:test:vitest: file:///home/github/actions-runner/_work/gaia/gaia/node_modules/.pnpm/vitest@0.34.5_jsdom@21.1.1/node_modules/vitest/dist/vendor-node.81dd929c.js:7314
contra-api:test:vitest: file:///home/github/actions-runner/_work/gaia/gaia/node_modules/.pnpm/vitest@0.34.5_jsdom@21.1.1/node_modules/vitest/dist/vendor-node.81dd929c.js:7676
contra-api:test:vitest: 
contra-api:test:vitest: # FILEHANDLE
contra-api:test:vitest: node:internal/async_hooks:202
```

### Reproduction

Running our entire test suite.

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 955.88 MB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 21.1.0 - ~/.nvm/versions/node/v21.1.0/bin/node
    Yarn: 1.22.19 - ~/Library/pnpm/yarn
    npm: 10.2.0 - ~/.nvm/versions/node/v21.1.0/bin/npm
    pnpm: 8.9.0 - ~/.nvm/versions/node/v21.1.0/bin/pnpm
  Browsers:
    Brave Browser: 116.1.57.64
    Chrome: 118.0.5993.117
    Edge: 114.0.1823.43
    Safari: 16.3
  npmPackages:
    vitest: ^0.34.5 => 0.34.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
> ### Reproduction
> Running our entire test suite.

Happy to look into this bug we need a reproduction case.

**Comment by gajus** [comment]
> > ### Reproduction
> > Running our entire test suite.
> 
> Happy to look into this but we need a reproduction case.

I wouldn't even know where to start. This happens in our large repository with thousands of tests, and doesn't happen every time.

**Comment by AriPerkkio** [comment]
Seeing Tinypool in the listed resources indicates that some test file is preventing it from shutting down. Without `hanging-process` reporter, do you see errors indicating which file that is? In #3031 there's an example of such error logging. 

What's the reason why you are using `hanging-process` reporter in the first place? What errors do you see without it?

**Comment by gajus** [comment]
> What's the reason why you are using hanging-process reporter in the first place? What errors do you see without it?

Without it it just occasionally times out. The test suite never completes.

It is not a single file. Keeps popping up on random files, e.g.

```
contra-api:test:vitest: close timed out after 10000ms
contra-api:test:vitest: Failed to terminate worker while running /home/github/actions-runner/_work/gaia/gaia/apps/contra-api/testV2/integration/contraMagic/generateContraMagicOneLinerSuggestions.test.ts.
contra-api:test:vitest: Tests closed successfully but something prevents Vite server from exiting
```

```
contra-api:test:vitest: close timed out after 10000ms
contra-api:test:vitest: Failed to terminate worker while running /home/github/actions-runner/_work/gaia/gaia/apps/contra-api/test/contra-api/integration/queries/productizedServiceById.test.ts.
contra-api:test:vitest: Tests closed successfully but something prevents Vite server from exiting
```

I am trying to replicate this issue locally.

I installed `why-is-node-running` and running this test suite on repeat:

```bash
while [ true ]; do vitest run queries/productizedServiceById.test.ts; done
```

But so far nothing.

**Comment by gajus** [comment]
Is it at all possible that this is somehow hardware/OS specific?

These tests have ran now at least 50 times on my machine without a single hitch.

On CI I keep seeing them fail every other build.

**Comment by AriPerkkio** [comment]
Without seeing the test cases, dependencies and Vitest configuration it's impossible to point out the root cause. But here's some things to try at least:

- Replace NodeJS `fetch` with `node-fetch`: https://github.com/vitest-dev/vitest/issues/3077
- Read https://github.com/vitest-dev/vitest/issues/2008 for more solutions, e.g. removing certain Vite plugins during testing
- Use `--no-threads` or v1-beta's `--pool=forks`

**Comment by gajus** [comment]
Starting to suspect that we are hitting this https://github.com/nodejs/undici/issues/2026

**Comment by AriPerkkio** [comment]
You could try if using `node-fetch` fixes the issue. Something like this should be enough: https://github.com/dfinity/feedback/pull/151/files#diff-84f6be72ed45f1bf4cdbd441d0bd824e38270a7599bd4eac2981b05eb7ad9d29R8-R14

**Comment by gajus** [comment]
ah, literally just did this a second ago.

**Comment by mcollina** [comment]
Note that you could be hitting https://github.com/nodejs/node/issues/49344.

**Comment by gajus** [comment]
> Note that you could be hitting [nodejs/node#49344](https://github.com/nodejs/node/issues/49344).

This would be only an issue if coverage is enabled, right?

We have coverage explicitly disabled in our tests.

**Comment by mcollina** [comment]
Something more to try, set UV_USE_IO_URING=0.

**Comment by AriPerkkio** [comment]
> Note that you could be hitting [nodejs/node#49344](https://github.com/nodejs/node/issues/49344).

Vitest moved from using `NODE_V8_COVERAGE` to use `node:inspector` directly a while ago. It was causing test hangs as described in the linked node issue. 
- https://github.com/vitest-dev/vitest/pull/2786
