### ISSUE TITLE
Fixture "task" is not available anymore

### ISSUE THREAD

**Issue by luixo** [vitest-dev/vitest#4418]
### Describe the bug

According to [test extension guide](https://vitest.dev/guide/test-context.html#extend-test-context), we can create a test fixture like this:
```ts
import { test } from 'vitest'

export const myTest = test.extend({
  logTaskId: async ({ task }, use) => {
    console.log('Task id', task.id);
  },
})
```

Unfortunately, this doesn't work since `v0.34.5`, probably because something happened [here](https://github.com/vitest-dev/vitest/pull/4065/files#diff-6369508b83fbd1a9f8bf15f3f8853925b397d175f2367a987cbf25e66dbebc70L46-L72).
In a version before this change context passed to the function included `task` (and other default fixtures), currently it included only user-added fixtures.

Also, at `v1.0.0-beta.0` the types changed to mirror the change which is incorrect as well.

### Reproduction

```ts
import { test } from 'vitest'

export const myTest = test.extend({
  logTaskId: async ({ task }, use) => {
    console.log('Task id', task.id);
  },
})
```

Expected: running `logTaskId` in a test will log task id
Actual: failed with error in the console

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 388.06 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: 3.6.2 - ~/.nvm/versions/node/v20.2.0/bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 17.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Did you try the latest beta? Works fine for me including types

**Comment by luixo** [comment]
Do you mean `v1.0.0-beta.3`? It is the latest beta.

**Comment by luixo** [comment]
Seems like types are actually fixed!

Eventually, I found a bug in a [latest commit](https://github.com/vitest-dev/vitest/commit/9021e8b84bec120e5c7546d6e0aed88db3b60f3c) so far as well.

Add this to a `fixture-concurrent.test.ts` and run `pnpm test`:
```ts
beforeEach(async ({ task }) => {
  console.log('task id', task.id);
});
```

Expected to have logged task id, got type error:
```
TypeError: Cannot destructure property 'isFn' of 'fixture' as it is undefined.
```

**Comment by dsyddall** [comment]
> ```
> TypeError: Cannot destructure property 'isFn' of 'fixture' as it is undefined.
> ```

The error seems to occur when the test is extended with fixtures but the fixtures are unused in the test.
Reproduction here: https://stackblitz.com/edit/vitest-dev-vitest-bdohnv?file=test%2Funused-fixtures.test.ts

This PR should fix it: https://github.com/vitest-dev/vitest/pull/4419
