### ISSUE TITLE
Vitest doesn't ignore webstorm / vscode folders

### ISSUE THREAD

**Issue by davidmeirlevy** [vitest-dev/vitest#442]
### Describe the bug

The runner doesn't ignore the `.idea` folder.

The defalt value mentioned by the documentation (['**\/node_modules\/**', '**\/dist/**']) is wrong. if I'm setting this value - the runner crashes after the first run.

### Reproduction

The defalt value mentioned by the documentation (['**\/node_modules\/**', '**\/dist/**']) is wrong. if I'm setting this value - the runner crashes after the first run.

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 316.45 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 7.13.0 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: 2021.10.18.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 57.0.4
    Safari: 15.2
  npmPackages:
    @vitejs/plugin-vue: ^2.0.0 => 2.0.1 
    vite: ^2.7.2 => 2.7.10 
    vitest: ^0.0.131 => 0.0.131
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
What file under `.idea` caused the crash? Can you provide more info?

**Comment by davidmeirlevy** [comment]
Workspaces.xml

**Comment by DerYeger** [comment]
Could you post a log of the crash?

I'm using Vitest and Webstorm together without any issues.

**Comment by davidmeirlevy** [comment]
it's not crashing, it's just re-run the tests when my workspace.xml is changing (which is happening every time webstorm is calculating everything..)

![image](https://user-images.githubusercontent.com/6875922/148250011-5f9144e6-1fb1-4f68-8ec8-86ca4e063a18.png)

**Comment by antfu** [comment]
I will need a minimal reproduction repo.

**Comment by davidmeirlevy** [comment]
https://github.com/davidmeirlevy/demo-vue-vitest

Run it on Webstorm in order to create the `.idea` folder.

**Comment by sheremet-va** [comment]
> The defalt value mentioned by the documentation (['**/node_modules/**', '**/dist/**']) is wrong. if I'm setting this value - the runner crashes after the first run.

I guess the docs are wrong, since default value is this right now:

```ts
[
  '**/node_modules/**', 
  '**/dist/**', 
  '**/cypress/**', 
  '**/.{idea,git,cache,output,temp}/**'
]
```

Maybe we need to update docs

**Comment by davidmeirlevy** [comment]
@sheremet-va i think that the best approach is to ignore everything that is mentioned at the gitignore file.

**Comment by Demivan** [comment]
Ignoring watching all files in .gitignore will not work for everyone. I saw multiple projects that have tests importing code from the dist folder.
