### ISSUE TITLE
TS2769: No overload matches this call.

### ISSUE THREAD

**Issue by lixiaofa** [vitest-dev/vitest#4424]
### Describe the bug

![image](https://github.com/vitest-dev/vitest/assets/23230215/898088f2-3d57-4229-8e35-19d3475822b7)

`import { defineConfig } from 'vitest/config'
import Vue from '@vitejs/plugin-vue'
import VueJsx from '@vitejs/plugin-vue-jsx'
import VueMacros from 'unplugin-vue-macros/vite'

export default defineConfig({
  plugins: [
    VueMacros({
      setupComponent: false,
      setupSFC: false,
      plugins: {
        vue: Vue(),
        vueJsx: VueJsx(),
      },
    }),
  ],
  optimizeDeps: {
    disabled: true,
  },

  test: {
    transformMode: {
      web: [/\.[jt]sx$/],
    },
    clearMocks: true,
    environment: 'jsdom',
    setupFiles: ['./vitest.setup.ts'],

    deps: {
      inline: ['vant'],
    },
  },
})
`

### Reproduction

https://github.com/lixiaofa/fast-plus/blob/dev/vitest.config.ts

### System Info

```shell
"vitest": "^0.34.6",
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`transformMode` options was removed in [0.34.0](https://github.com/vitest-dev/vitest/releases/tag/v0.34.0)

**Comment by lixiaofa** [comment]
> `transformMode` option was removed in [0.34.0](https://github.com/vitest-dev/vitest/releases/tag/v0.34.0)

There is still writing on the document
![image](https://github.com/vitest-dev/vitest/assets/23230215/20ae0fb1-5b5b-4ba8-90ff-034287e37cbe)
@sheremet-va

**Comment by sheremet-va** [comment]
CN docs has a separate repository: https://github.com/vitest-dev/docs-cn

**Comment by lixiaofa** [comment]
> CN docs has a separate repository: https://github.com/vitest-dev/docs-cn

What I mean is that the document is not up-to-date, transformMode option was removed in [0.34.0](https://github.com/vitest-dev/vitest/releases/tag/v0.34.0)

**Comment by sheremet-va** [comment]
> > CN docs has a separate repository: [vitest-dev/docs-cn](https://github.com/vitest-dev/docs-cn)
> 
> What I mean is that the document is not up-to-date, transformMode option was removed in [0.34.0](https://github.com/vitest-dev/vitest/releases/tag/v0.34.0)

1. English documentation is up-to-date
2. `transformMode` in your screenshot is mention in example, the actual name is `testTransformMode` (in your screenshot)

**Comment by lixiaofa** [comment]
> 2\. `transformMode` in your screenshot is mention in example, the actual name is `testTransformMode` (in your screenshot)

Thank you
