### ISSUE TITLE
`testFileDir` always matches 

### ISSUE THREAD

**Issue by timbrinded** [vitest-dev/vitest#4425]
### Describe the bug

Given the tree:
```
.
├── tests1
│   └── test.spec.ts
├── tests11
│   └── test.spec.ts
└── tests2
    └── test.spec.ts
```

Vitest will match `tests1` & `tests11` when supplied with filter `tests1/`. 

Whilst i recognise that you can use the `include` option or even specifying direct filenames, that is a very heavyhanded and hardcoded approach which doesn't fit large test repositories (in my case i have 400+ test files in nested directories). 

Instead it would be less-surprising for it to match based on inputs such as `tests1/` to only use that directory. A regex `\b` would also be acceptable. 

### Reproduction

Using this [StackBlitz](https://stackblitz.com/edit/vitest-dev-vitest-grbmeo?file=package.json) you can execute the following scripts that illustrates a plausible scenario:
- `pnpm test:all` : ✅
- `pnpm test:1` : ❌ - Runs tests for both `folder1` and `folder11`
- `pnpm test:2` : ✅
- `pnpm test:11` : ✅

> [!IMPORTANT]  
> In reality, most scenarios wouldn't be matching based on numbers, but i've got into weird scenarios where expressions collide with each other: `test_blocks` and `test_blockscope`

### System Info

```shell
all
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Yes, the filter is just `string.includes()`

**Comment by timbrinded** [comment]
if you see the repro, the filter contains the `/` but it is being ignored

**Comment by timbrinded** [comment]
@sheremet-va did you see the comment above? The defect appears valid to me.

**Comment by ibuibu** [comment]
I challenge to contribute.
