### ISSUE TITLE
`vitest typecheck` does not find test files in `typecheck.include`

### ISSUE THREAD

**Issue by unicornware** [vitest-dev/vitest#4432]
### Describe the bug

Test files specified in `typecheck.include` are no longer found when running `vitest typecheck --run`.

This seems to be a regression of some sort, given that this is **not** an issue in previous versions (`<=1.0.0-beta.2`).

### Reproduction

https://stackblitz.com/edit/vitest-typecheck-bug?file=vitest.config.ts

### System Info

```shell
System:
    OS: macOS 13.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 47.54 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
    Yarn: 4.0.0 - ~/.yarn/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 16.6
  npmPackages:
    @vitest/coverage-v8: 1.0.0-beta.3 => 1.0.0-beta.3 
    @vitest/expect: 1.0.0-beta.3 => 1.0.0-beta.3 
    vite: 5.0.0-beta.14 => 5.0.0-beta.14 
    vitest: 1.0.0-beta.3 => 1.0.0-beta.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
There is no such command anymore. Typechecking runs alongside normal tests now, but you need to pass down --typecheck

**Comment by unicornware** [comment]
@sheremet-va 

ok. is there a way to make this clear to users? given what you said, i would have expected `vitest typecheck` to give a different error. the current error makes this seems like a bug, rather than a need for users to review the docs / update their project setups.

**Comment by sheremet-va** [comment]
This is mentioned in documentation. "typecheck" is a valid filter. I guess, we can throw an error until 2.0 🤔
