### ISSUE TITLE
Constructing a Request for a relative URL fails

### ISSUE THREAD

**Issue by micha149** [vitest-dev/vitest#4434]
### Describe the bug

I'm using vitest with happy-dom. In my application code I want to instanciate a Request from a relative URL like `new Request('/api/foo')`. From my perspective this should work and in my browser all works fine as expected. But creating the instance im my tests fails with:

```
TypeError: Invalid URL
 ❯ new URL node_modules/happy-dom/src/url/URL.ts:8:15
 ❯ Module.get src/data/api/common.ts:59:21
 ❯ src/data/api/common.test.ts:35:30
```

I digged a bit into the problem but can't really figure out whats going wrong. Something I noticed is that there is the `Request` constructor from `node:internal` instead of `happy-dom` when I print a stack trace from the URL constructor:

```
at new URL (file:///*******/node_modules/happy-dom/lib/url/URL.js:9:22)
at new _Request (node:internal/deps/undici/undici:5055:25)
at Module.get (/*******/src/data/api/common.ts:59:21)
at /*******/src/data/api/common.test.ts:35:30
at file:///*******/node_modules/@vitest/runner/dist/index.js:135:14
at file:///*******/node_modules/@vitest/runner/dist/index.js:58:26
at runTest (file:///*******/node_modules/@vitest/runner/dist/index.js:663:17)
at runSuite (file:///*******/node_modules/@vitest/runner/dist/index.js:782:15)
at runSuite (file:///*******/node_modules/@vitest/runner/dist/index.js:782:15)
at runSuite (file:///*******/node_modules/@vitest/runner/dist/index.js:782:15)
```

Switching to `jsdom` does not solve the issue. As well as creating a standalone script which uses `happy-dom` to create a Request works fine. So I think the problem lies in the integration into vitest.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-8gdvjz?file=test%2Frequest.test.ts

### System Info

```shell
System:
    OS: macOS 13.6.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 14.14 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - /opt/homebrew/bin/npm
    pnpm: 8.10.0 - /opt/homebrew/bin/pnpm
    bun: 1.0.7 - /opt/homebrew/bin/bun
    Watchman: 2023.10.23.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 118.1.59.124
    Chrome: 116.0.5845.179
    Edge: 116.0.1938.69
    Safari: 17.1
  npmPackages:
    @vitejs/plugin-react-swc: 3.4.0 => 3.4.0
    vite: 4.5.0 => 4.5.0
    vitest: 0.34.6 => 0.34.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is just how node works:

```shell
> node
new Request('/api/foo')
// TypeError: Invalid URL
```

**Comment by micha149** [comment]
Sure. But using a browser-like environment in my tests should behave as a browser, not like node?!

**Comment by sheremet-va** [comment]
You don't use any environment in your reproduction. If you _are_ using any environment, then Vitest doesn't control what variables are exposed and how they work.

**Comment by micha149** [comment]
My bad. I **updated the reproduction** to represent more my setup. And btw using the following solves my current issue:

```
import { Request as HappyRequest } from 'happy-dom';

// @ts-expect-error This is only a temporary fix
global.Request = HappyRequest;
```
