### ISSUE TITLE
When `global` is false, failed to import `@testing-library/jest-dom`

### ISSUE THREAD

**Issue by floratmin** [vitest-dev/vitest#4449]
### Describe the bug

Reopening bug from [1504](https://github.com/vitest-dev/vitest/issues/1504).
```
 FAIL  src/index.spec.js [ src/index.spec.js ]
ReferenceError: expect is not defined
 ❯ node_modules/.pnpm/@testing-library+jest-dom@6.1.4_vitest@0.34.6/node_modules/@testing-library/jest-dom/dist/index.mjs:12:1
 ❯ vitest.jsdom.config.js:1:31
      1| import '@testing-library/jest-dom';
       |                               ^
      2| 

```
 When uncommenting the line `globals: true` in the file `vite.config.js` the test works as expected.

### Reproduction

 I created a minimal reproduction under [bug-vitest-testing-library-jest-dom](https://github.com/floratmin/bug-vitest-testing-library-jest-dom).

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 11.43 GB / 30.73 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
    pnpm: 8.10.2 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 119.0.6045.105
  npmPackages:
    vite: ^4.5.0 => 4.5.0 
    vitest: ^0.34.6 => 0.34.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I don't see how this is a bug. Vitest is not jest, you manually disabled globals for a package that expects a global expect. Even more so, the package has a separate entry for Vitest: [`@testing-library/jest-dom/vitest`](https://www.npmjs.com/package/@testing-library/jest-dom#with-vitest).

Closing the issue.
