### ISSUE TITLE
Error: Not implemented: navigation (except hash changes)

### ISSUE THREAD

**Issue by ManucherKM** [vitest-dev/vitest#4450]
### Describe the bug

Hello. relatively recently I started using Vitest to write tests for my project, and everything would be fine but I encountered a rather strange problem `Error: Not implemented: navigation (except hash changes)`. I have searched for solutions to this problem on the net, but all available solutions are mostly for Jest. I tried to apply them, but nothing worked. All the explanations of how to solve this problem, basically boiled down to the fact that you need to mock window.location and so on. But the most interesting thing is that I don't use this method, neither in the test, nor in the function itself. I will also draw your attention to the fact that the tests themselves are successful, i.e. no red warning appears and so on, but when you get the result of the tests, scrolling in the terminal a little higher, you will see the error. [My tests](https://github.com/ManucherKM/cloud-storage/blob/react/src/utils/downloadFileFromBuffer/downloadFileFromBuffer.test.ts), [Function](https://github.com/ManucherKM/cloud-storage/blob/react/src/utils/downloadFileFromBuffer/downloadFileFromBuffer.ts), [Vitest config](https://github.com/ManucherKM/cloud-storage/blob/react/vitest.config.ts).

### Reproduction

Demo (https://stackblitz.com/edit/vitest-dev-vitest-n3nst8?initialPath=__vitest__/)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-3632QM CPU @ 2.20GHz   
    Memory: 10.13 GB / 15.89 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.3570.0), Chromium (119.0.2151.44)
    Internet Explorer: 11.0.19041.3570
  npmPackages:
    @vitejs/plugin-react: ^4.0.3 => 4.0.4
    vite: ^4.4.5 => 4.4.9
    vitest: ^0.34.6 => 0.34.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by spiroka** [comment]
I would say this is expected as you are clicking on an anchor tag, but `jsdom` doesn't implement navigation.
I'm not a fan of this solution, but you could try mocking the click method of anchor elements like this: https://stackoverflow.com/a/68038982/13163721

**Comment by ManucherKM** [comment]
This fixed my error. Thank you.
