### ISSUE TITLE
Mock does not work with `allowSyntheticDefaultImports`

### ISSUE THREAD

**Issue by floratmin** [vitest-dev/vitest#4454]
### Describe the bug

I try to mock `Pool` from `pg`.

When I set in the file `tsconfig.json` `allowSyntheticDefaultImports` to `true` and transform the code with `vite`, the only way to make the code run with node is with the following import statement:
```js
import pg from 'pg';
const {Pool} = pg;
```

But with this import statement I can not mock `Pool`. The spy on `Pool` does not get called. I get the error:
```bash
AssertionError: expected "spy" to be called 1 times, but got 0 times
```
The tests work with the following import statements:
```js
import * as pg from 'pg';
const {Pool} = pg;
```
or
```js
import {Pool} from 'pg';
```

But both do not allow the first import statement in the `index.ts` file.

### Reproduction

[vitest-allowSyntheticDefaultImports](https://github.com/floratmin/vitest-allowSyntheticDefaultImports)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 12.86 GB / 30.73 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.8.0 - ~/.nvm/versions/node/v20.8.0/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.8.0/bin/npm
    pnpm: 8.10.2 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 119.0.6045.105
  npmPackages:
    vite: ^4.5.0 => 4.5.0 
    vitest: ^0.34.6 => 0.34.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`vi.mock` factory returns an exports object. In your fist example you access `Pool` on default export, in your second and third example you access `Pool` via an exports binding.

The first example doesn't work because you mock the `Pool` export instead of the Pool property on a default object:

```ts
vi.mock('pg', () => {
  return { default: { Pool: vi.fn() } }
})
```

Then you would need to import `Pool` the same way you import it in your source code:

```ts
import pg from 'pg'
const { Pool } = pg
```

Or also return `Pool` from a factory that _you_ __fully__ control:

```ts
vi.mock('pg', () => {
  const Pool = vi.fn()
  return { Pool, default: { Pool } } // vi.fn() references the same Pool in exports and default export
})
```

**Comment by sheremet-va** [comment]
This article explains how ES Modules in JavaScript work: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules
