### ISSUE TITLE
globals configuration not work with workspace?

### ISSUE THREAD

**Issue by southorange0929** [vitest-dev/vitest#4455]
### Describe the bug

I try to use vitest with monorepo.And i created a config file with `vitest.workspace.ts`
```ts
import { defineWorkspace } from "vitest/config";

export default defineWorkspace(['packages/*',{
  test: {
    globals: true,
    include: ['packages/**/*.test.ts'],
  },
}]);
```

Test case without import vitest:
```ts
import { flatNestData } from "./dataSet";

describe("DataSet tool Test", () => {
  it("flatNestData should be success", () => {
    const NestData = {
      a: "1",
      b: ["2", "3", "4"],
      c: {
        a: "5",
      },
    };
    const flatData = [];
    flatNestData(NestData, flatData);
    expect(flatData.length).not.toBe(0);
    expect(flatData).toEqual([
      ["a", "1"],
      ["b", "2"],
      ["b", "3"],
      ["b", "4"],
      ["a", "5"],
    ]);
  });
});

```

Sub package get some error:
<img width="961" alt="image" src="https://github.com/vitest-dev/vitest/assets/32590310/82e49479-e862-4d83-8a89-94bcda758697">

Any suggestion? Thanks.

### Reproduction

-

### System Info

```shell
System:
    OS: macOS 14.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 108.98 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.volta/tools/image/node/16.20.2/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.19.4 - ~/.volta/tools/image/node/16.20.2/bin/npm
    pnpm: 8.10.2 - ~/.volta/bin/pnpm
    bun: 1.0.2 - ~/.bun/bin/bun
  Browsers:
    Chrome: 119.0.6045.123
    Safari: 17.1
  npmPackages:
    vitest: 1.0.0-beta.3 => 1.0.0-beta.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You created a workspace project for each packages folder that uses a default config (without globals), and you created inline project that uses config with globals (it's not applied to other projects of course).

If you don't want to create new configs everywhere, you can call Vitest with `--globals` flag.
