### ISSUE TITLE
Configuration option to allow empty test suites to pass

### ISSUE THREAD

**Issue by tkrotoff** [vitest-dev/vitest#4457]
#### Provide an option to allow empty test suites

Be able to have test files that don't contain tests (on purpose), even if it sounds bad at first.

#### Use-case:
I have a script that ensures every source code file has a matching test file (i.e MyComponent.tsx <=> MyComponent.test.tsx).
It's pretty common: https://twitter.com/housecor/status/1446087469494059016

But there are some exceptions to this rule:
- the component is already tested in another way or file
- the component is very hard to unit test, it doesn't worth it
- ...

In such cases, I like to comment why I don't test the component.
And what better place to document this than comments in the test file:

```JS
// File MyComponent1.test.tsx

// There is no tests here because the component is already tested in this file: xxx.test.ts
```

```JS
// File MyComponent2.test.tsx

// There is no tests here because the component is very hard to test for no added value
```

I cannot do that because Vitest reports `Error: No test found in suite MyComponent.test.tsx` + `Error: No test suite found in file MyComponent.test.tsx` and I cannot bypass this error.

Related issues (all locked):
- https://github.com/vitest-dev/vitest/issues/3820
- https://github.com/vitest-dev/vitest/issues/1780
- https://github.com/vitest-dev/vitest/issues/3779

**Comment by sheremet-va** [comment]
If you don't have an empty describe inside a test, `--passWithNoTests` should work just fine

**Comment by tkrotoff** [comment]
With option `--passWithNoTests`, it fixes `Error: No test suite found in file MyComponent.test.tsx` but a second error   kicks in: `Error: No test found in suite MyComponent.test.tsx`.

Related source code: https://github.com/vitest-dev/vitest/blob/v0.34.6/packages/runner/src/run.ts#L334-L341

<br><br>

Here the patch I apply to `@vitest/runner` to make all this work:

```JSON
"pnpm": {
  "patchedDependencies": {
    "@vitest/runner@0.34.6": "patches/@vitest__runner@0.34.6.patch"
  }
}
```

```diff
diff --git a/dist/index.js b/dist/index.js
index a0412d8081a8e244cc5d0a0687ce743e281b6225..3c935653496f89c0cdd0f17a4c189021a87ce6f8 100644
--- a/dist/index.js
+++ b/dist/index.js
@@ -795,12 +795,14 @@ async function runSuite(suite, runner) {
     }
     if (suite.mode === "run") {
       if (!hasTests(suite)) {
-        suite.result.state = "fail";
-        if (!suite.result.error) {
-          const error = processError(new Error(`No test found in suite ${suite.name}`));
-          suite.result.error = error;
-          suite.result.errors = [error];
-        }
+        // FIXME https://github.com/vitest-dev/vitest/issues/4457
+        suite.result.state = "skip";
+        // suite.result.state = "fail";
+        // if (!suite.result.error) {
+        //   const error = processError(new Error(`No test found in suite ${suite.name}`));
+        //   suite.result.error = error;
+        //   suite.result.errors = [error];
+        // }
       } else if (hasFailed(suite)) {
         suite.result.state = "fail";
       } else {
```
