### ISSUE TITLE
"Vitest caught 1 unhandled error" for error in TransformStream

### ISSUE THREAD

**Issue by cdauth** [vitest-dev/vitest#4461]
### Describe the bug

I'm running the following test:
```typescript
import { ReadableStream, TransformStream } from "stream/web";

test("test", async () => {
	const stream1 = new ReadableStream<string>({
		start(controller) {
			controller.error(new Error("Test"));
		}
	});

	const stream2 = new TransformStream<string, string>();
	stream1.pipeTo(stream2.writable);

	await expect(async () => {
		await stream2.readable.getReader().read();
	}).rejects.toThrow("Test");
});
```

It causes vitest to raise the following error:
```
Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.
```

I first suspected an error in the Node.js ReadableStream implementation (as I found a similar bug for [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1561911)). But running the same code as a plain node script does not cause the same error.

An unhandled rejection handler using `process.on('unhandledRejection')` will trigger when running the code through Vitest, but it will not trigger when running the code in plain Node.js.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-xlcrfv?file=test%2Fbasic.test.ts

To test the same code in plain NodeJS, run `node test.js`.

### System Info

```shell
System:
    OS: Linux 6.5 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz
    Memory: 6.37 GB / 23.11 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 21.1.0 - /usr/bin/node
    Yarn: 3.6.3 - /usr/bin/yarn
    npm: 10.2.3 - /usr/bin/npm
    pnpm: 8.10.2 - /usr/bin/pnpm
  Browsers:
    Brave Browser: 118.1.59.117
    Chromium: 119.0.6045.105
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> To test the same code in plain NodeJS, run `node test.js`.

This is not the same code. The same code would be to wrap it inside `try/catch`:

```js
process.on('unhandledRejection', () => {
  console.log('unhandled rejection');
});

const stream1 = new ReadableStream({
  start(controller) {
    controller.error(new Error('Test'));
  },
});

const stream2 = new TransformStream();

stream1.pipeTo(stream2.writable);

try {
  await stream2.readable.getReader().read();
} catch {}
```

This way, Node.js also triggers `unhandledRejection`

**Comment by cdauth** [comment]
Thanks for the investigation! I hadn't been able to find a way to reproduce it with a plain Node.js script.

I have now reported this as nodejs/node#50707.
