### ISSUE TITLE
Github CI hangs

### ISSUE THREAD

**Issue by luixo** [vitest-dev/vitest#4471]
### Describe the bug

Hello,
I updated Vitest from `v0.34.1` to `v1.0.0-beta.4` and the PR with the update hangs (though the logs show all the tests did pass). Github CI kills the process after 6 hours.

### Reproduction

Unfortunately, this reproduces 3/3 times in the [PR with all test active](https://github.com/luixo/receipt-app/actions/runs/6813181675/job/18570385862), but doesn't reproduce 0/3 in [a PR with just few tests active](https://github.com/luixo/receipt-app/actions/runs/6827641324?pr=26).

The same test set [in a base commit](https://github.com/luixo/receipt-app/actions/runs/6812428417/job/18527204340) works just fine.

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 645.84 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: 3.6.2 - ~/.nvm/versions/node/v20.2.0/bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
  Browsers:
    Chrome: 119.0.6045.123
    Safari: 17.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Could you try to narrow down the root cause a bit:

- Check which exact Vitest versions causes this. Is it there on 0.34.2 or v1-beta.0 already?
- Try to disable features like coverage
- Try if changing `pool` options make any difference. It his `node:worker_threads` related issue only?

And of course it would be great to be able to reproduce this locally without CI.

**Comment by luixo** [comment]
> Check which exact Vitest versions causes this. Is it there on 0.34.2 or v1-beta.0 already?

I'll do the bisection, though it will take some time as there was a [problem](https://github.com/vitest-dev/vitest/issues/4418) that did prevent my update to an earlier 1.0.0 beta. I could try to run it with a local patch though.

> Try to disable features like coverage

If it will work without the coverage it could signal either that the fault was in coverage as well as that it was just the last drop for getting in a hang state.

> Try if changing pool options make any difference. Is this node:worker_threads related issue only?

Surely will do that.

> And of course it would be great to be able to reproduce this locally without CI.

Actually, I got a problem that could be the case in the CI locally (though happening once in 4-5 runs). Tests got to the point of reporting coverage after the main phase and then I got this error:
```
file:///<redacted>/node_modules/tinypool/dist/esm/index.js:532
    const timer = timeout ? setTimeout(() => reject(new Error("Failed to terminate worker")), timeout) : null;
                                                    ^

Error: Failed to terminate worker
    at Timeout._onTimeout (file:///<redacted>/node_modules/tinypool/dist/esm/index.js:532:53)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

Node.js v20.2.0
```
And it just hangs. SIGINT (Ctrl+C) doesn't work on it, killing via system monitoring helped (probably other signals would work too).

**Comment by luixo** [comment]
After changing a way to get dumps for my snapshots I can't reproduce the problem anymore.
Not sure what happened.
I'll reopen if something else changes.
