### ISSUE TITLE
Run subset of tests concurrently

### ISSUE THREAD

**Issue by misterjoshua** [vitest-dev/vitest#4475]
### Clear and concise description of the problem

I have 9,150 tests to run. The process of running these tests takes five minutes in GitHub actions. I want a better way to distribute the running of tests for a given commit among a greater number of workers so I can decrease the testing time for a large project.

### Suggested solution

I'd like to partition the test suites into five groups that I can run independently and concurrently in five different GitHub actions so I can reduce the total test time.

For instance, if I had five different test-running workers, I'd want to run five different commands in five different GitHub actions jobs, each that ran only 1/5 of the test suites:

- `vitest --run --strategy=modulus --num-workers 5 --worker 0`
- `vitest --run --strategy=modulus --num-workers 5 --worker 1`
- `vitest --run --strategy=modulus --num-workers 5 --worker 2`
- `vitest --run --strategy=modulus --num-workers 5 --worker 3`
- `vitest --run --strategy=modulus --num-workers 5 --worker 4`

### Alternative

I suppose I could create a vitest config file that runs only `*.test.${n}.ts` files given an environment variable, but this is super complex.

### Additional context

N/A

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Can't you just use [`--shard`](https://vitest.dev/guide/cli.html#shard)? 
```
vitest --shard=1/5
vitest --shard=2/5
vitest --shard=3/5
vitest --shard=4/5
vitest --shard=5/5
```

**Comment by misterjoshua** [comment]
Thank you - I may have missed that in the documentation!

**Comment by misterjoshua** [comment]
Looks like --shard in combination with GitHub actions matrix strategy works perfectly! Thank you @sheremet-va
