### ISSUE TITLE
Vitest uses ESBuild even when esbuild is set to `false`

### ISSUE THREAD

**Issue by matthew-dean** [vitest-dev/vitest#4479]
### Describe the bug

I'm attempting to set up Typia, which relies on `ts-patch` to allow transform plugins. I followed [these instructions](https://typia.io/docs/setup/#vite), which failed in my tests. The reason it failed is because TypeScript files were getting transformed _before_ they got to the TypeScript Rollup plugin, meaning `esbuild` was still active, even when set to `false`.  At first, I thought this was a Vite issue, but when I went to reproduce, it worked in Vite.

So then I went to repro for Vitest, and I discovered that Vitest ignores the `esbuild` setting from the Vite config, and always transforms.

In the reproduction, the TypeScript annotations would/should fail with `esbuild: false`, as TypeScript annotations wouldn't be runnable in a Node environment. Instead, tests continue to pass.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-de2cnr?file=vite.config.ts,tsconfig.json&initialPath=__vitest__/

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 45.73 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/Library/Caches/fnm_multishells/47748_1699638513910/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/47748_1699638513910/bin/yarn
    npm: 8.19.3 - ~/Library/Caches/fnm_multishells/47748_1699638513910/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.5.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
TS plugin is a separate thing from `esbuild` config in Vite. Vitest doesn't change anything how it's processed. You can see that TS files are processed in Vite project: https://stackblitz.com/edit/vitejs-vite-demjsb?file=main.ts,index.html&terminal=dev

Can you provide a reproduction with an actual issue that you have?

**Comment by sheremet-va** [comment]
> TS plugin is a separate thing from `esbuild` config in Vite as far as I can tell. Vitest doesn't change anything how it's processed. You can see that TS files are processed in Vite project: https://stackblitz.com/edit/vitejs-vite-demjsb?file=main.ts,index.html&terminal=dev
> 
> Can you provide a reproduction with an actual issue that you have?

Wait, scrap that! I had config misconfigured. You are correct, Vitest modified esbuild config value, instead it should keep it false if it was set to `false`:

https://github.com/vitest-dev/vitest/blob/cc19117d303ad0a36721ddee01c14f04812245ae/packages/vitest/src/node/plugins/index.ts#L67
