### ISSUE TITLE
Typescript Error with mock function calls

### ISSUE THREAD

**Issue by matt-clarson** [vitest-dev/vitest#448]
### Describe the bug

There's a bug with the typings for the jest integration of tinyspy, that causes typescript to complain about what should be a valid use of a mock function - it looks like the `calls` array on the mock function uses the type of the return value for the mocked function rather than the arguments.

The error message I get in VSCode:
<img width="769" alt="VSCode Screenshot - TS error Element implicitly has an 'any' type because expression of type '0' can't be used to index type 'void'. Property '0' does not exist on type 'void'." src="https://user-images.githubusercontent.com/45913991/148250553-84dc30ac-f5df-47e6-bf46-a9d0ed58dc6e.png">

It looks like the error comes from the definition for [`JestMockCompatContext`](https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/integrations/jest-mock.ts#L20) - the generics are the wrong way round:

```typescript
export interface JestMockCompatContext<T, Y> {
  calls: Y[] // <- this should be T[]
  instances: T[]
  // TODO: doesn't work
  invocationCallOrder: number[]
  results: MockResult<T>[] // <- this should be Y[]
}
```
I'm happy to open a PR with the change if that's ok

### Reproduction

1. Create a new Vite app `pnpm init vite@latest bug-demo` (then `cd bug-demo && pnpm install`)
2. Install vitest `pnpm add -D vitest`
3. Add the following code to a new file `src/main.spec.ts`:
```typescript
import { expect, it, vi } from "vitest";

const myObj = { f(_x: unknown): void {} };

it("replicate mock calls bug with vitest", () => {
  const spy = vi.spyOn(myObj, "f");

  myObj.f(1);

  expect(spy.mock.calls).toStrictEqual([[1]]);
  expect(spy.mock.calls[0][0]).toBe(1);
});
```
4. Typescript will report the error automatically in VSCode, or you can run `pnpm tsc`

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 1.15 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - /opt/homebrew/bin/node
    npm: 8.1.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 96.0
    Safari: 15.1
  npmPackages:
    vite: ^2.7.2 => 2.7.10 
    vitest: ^0.0.133 => 0.0.133
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Demivan** [comment]
Pending fix: https://github.com/vitest-dev/vitest/pull/447
