### ISSUE TITLE
Incosistent prepare phase in CI (probably, coverage initialization)

### ISSUE THREAD

**Issue by luixo** [vitest-dev/vitest#4493]
### Describe the bug

I've been migrating a way to diff my DB changes.
A CI run in PR with that change suddenly increased vitest tests time from ~1:10 to ~3:10.

A deep dive on the problem found that "prepare" phase of the tests increrased 3 fold while others are in a tolerable difference range (not more than 10-15%). Logging the phase down I found that [initializing coverage](https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/runtime/entry-vm.ts#L47) was responsible for about 90% of "prepare" phase time*.

Eventually, I found that the prepare phase was pretty unstable varying times 3 fold.
As an example, I got [two attempts of the same run](https://github.com/luixo/receipt-app/actions/runs/6852274827/job/18630734145) with first attempt in 1:06 and second in 3:03 (all the phases are consistent but prepare).
I believe that is a bug that such a variety is present in a test framework.

* I added coverage perf timing around given function, the result can be found [here](https://github.com/luixo/receipt-app/actions/runs/6851986895/job/18629480098) (see "prepare" and "including coverage" results in a report).

### Reproduction

The two attempts can be found here: https://github.com/luixo/receipt-app/actions/runs/6852274827/job/18630734145.
Unfortunately, local runs seem consistent.

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 220.64 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: 3.6.2 - ~/.nvm/versions/node/v20.2.0/bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
  Browsers:
    Chrome: 119.0.6045.123
    Safari: 17.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
> I found that [initializing coverage](https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/runtime/entry-vm.ts#L47) was responsible for about 90% of "prepare" phase time*.

That doesn't sound right. All that this line does is:

- It imports the coverage provider npm package, e.g. `await import('@vitest/coverage-v8')`

https://github.com/vitest-dev/vitest/blob/87b5bdbbfd9248c3baf6b379a1d3e96704566969/packages/vitest/src/integrations/coverage.ts#L19

- Set's up V8 profiler connection using [`node:inspector`](https://nodejs.org/dist/latest-v18.x/docs/api/inspector.html):

https://github.com/vitest-dev/vitest/blob/87b5bdbbfd9248c3baf6b379a1d3e96704566969/packages/coverage-v8/src/takeCoverage.ts#L12-L17

Could you do some logging around each of the lines shown above to figure out what exactly is taking the time. Log the time of `loader.executeId` and each of those `session.<>` calls.

**Comment by luixo** [comment]
Sorry for neglecting this issue.
Running `1.2.2` seems pretty consistent in GH Actions.
