### ISSUE TITLE
React is not defined in test environment.

### ISSUE THREAD

**Issue by yesmar12** [vitest-dev/vitest#4509]
### Describe the bug

I get invalid hook errors when I'm running my tests but not when running the application itself.  

```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

 ❯ src/App.test.tsx (1)
   × test

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/App.test.tsx > test
TypeError: Cannot read properties of null (reading 'useState')
 ❯ Proxy.useState node_modules/react/cjs/react.development.js:1622:21
 ❯ Module.App [as default] src/App.tsx:6:29
```

I get the impression that this is a simple config error I'm overlooking and the errors are insuffcient for me to figure it out on my own. Thanks for helping!

Similar issues: 
https://github.com/vitest-dev/vitest/issues/4032 - similar error message but not related
https://stackoverflow.com/questions/70519656/referenceerror-react-is-not-defined-migrating-from-cra-to-vite-and-nx - potentially related, but all the solutions listed here I was already doing. 

### Reproduction

https://codesandbox.io/p/sandbox/mutable-hill-ymsg8h

### System Info

```shell
System:
    OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD EPYC
    Memory: 391.68 MB / 2.01 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.1.0 - /usr/local/bin/npm
  npmPackages:
    @vitejs/plugin-react-swc: ^3.4.1 => 3.4.1 
    vite: ^4.5.0 => 4.5.0 
    vitest: 0.34.6 => 0.34.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by spiroka** [comment]
I think in your test you should be rendering your app like this: `render(<App />)` not by calling App like a function.
