### ISSUE TITLE
JUNIT reporter doesn't mark test as failed if the `beforeAll` throws error

### ISSUE THREAD

**Issue by jonatan-zint-tfs** [vitest-dev/vitest#4516]
### Describe the bug

When a beforeAll hook throws an error, the generated JUNIT report will report all tests in that describe block as without failiure, ergo succeeded.

That doesn't seem right to me.

### Reproduction

I set up a minimal example in this stackblitz:

https://stackblitz.com/edit/vitest-dev-vitest-brpfrz

### System Info

```shell
See the stackblitz example
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
What is your expectation here? Do you expect all tests to have the same error? I am not actually sure what JUNIT spec defines this situation

**Comment by jonatan-zint-tfs** [comment]
Reading [this](https://www.ibm.com/docs/de/developer-for-zos/14.1?topic=formats-junit-xml-format#junitschema__table_junitmap) it seems junit allows only failed testcases, not suites.

However not reporting the failiures at all does seem worse to me instead of reporting the same failiure to each testcase affecte by the bad `beforeAll`. That is also the behaviour if `beforeEach` throws an error.

**Comment by sheremet-va** [comment]
> However not reporting the failiures at all does seem worse to me instead of reporting the same failiure to each testcase affecte by the bad `beforeAll`. That is also the behaviour if `beforeEach` throws an error.

I do agree that we need to show them, I am just not sure how. Maybe jest has an answer.

**Comment by hi-ogawa** [comment]
It looks like a failure in `afterAll` doesn't make relevant test cases as failed. I made a repro to compare all four cases of 
 `afterAll/afterEach/beforeAll/beforeEach`.

https://stackblitz.com/edit/vitest-dev-vitest-m7bw4w?file=junit.xml
