### ISSUE TITLE
Jest Compat: add `expect.addEqualityTesters` API

### ISSUE THREAD

**Issue by sheremet-va** [vitest-dev/vitest#4520]
### Clear and concise description of the problem

Since jest [29.4.0](https://github.com/jestjs/jest/releases/tag/v29.4.0), you can use `expect.addEqualityTesters` API to extend default testers used in `equals` function check. I suggest we reimplement it to support broader ecosystem of jest packages that might rely on this.

From [jest docs](https://jestjs.io/docs/expect#custom-equality-testers-api):

> Custom testers are functions that return either the result (true or false) of comparing the equality of the two given arguments or undefined if the tester does not handle the given objects and wants to delegate equality to other testers (for example, the builtin equality testers).

> Custom testers are called with 3 arguments: the two objects to compare and the array of custom testers (used for recursive testers, see the section below).

PR that implemented this functionality: https://github.com/jestjs/jest/pull/13654

### Suggested solution

To fully implement this feature, we need to:

- Add `expect.addEqualityTesters` API
- Return `customTesters` inside matcher context
- Make sure `customTesters` are stored in `globalThis[JEST_MATCHERS_OBJECT]` to be compatible with jest's implementation
- Add enough tests to cover functionality
- Add documentation

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by eryue0220** [comment]
Can I have a try for this?

**Comment by sheremet-va** [comment]
> Can I have a try for this?

Sure

**Comment by hi-ogawa** [comment]
Closed by https://github.com/vitest-dev/vitest/pull/4880
