### ISSUE TITLE
 Vitest browser mode tests not working when running in a sub directory

### ISSUE THREAD

**Issue by nicojs** [vitest-dev/vitest#4522]
### Describe the bug

Similar to #3363, vitest's browser mode doesn't work when run from a subdirectory.

For example, this directory tree:

```
.
├── package-lock.json
├── package.json
└── test-resources
    └── browser-project
        ├── node_modules
        ├── package.json
        ├── src
        │   ├── heading.component.spec.ts
        │   └── heading.component.ts
        └── vitest.config.js
```

And you cd into `test-resources/browser-project` and run `npx vitest`, you get this error (or similar):

> TypeError: Failed to fetch dynamically imported module: http://localhost:5173/@id/vitest/utils

### Reproduction

See this reproduction repo.

1. Run `npm i`
1. `cd` into test-resources/browser-project
1. Run `npx vitest`

[browser-project.zip](https://github.com/vitest-dev/vitest/files/13380716/browser-project.zip)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 5.18 GB / 15.49 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.0/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: 8.9.2 - ~/.nvm/versions/node/v18.18.0/bin/pnpm
  Browsers:
    Chrome: 118.0.5993.117
  npmPackages:
    @vitest/browser: ^0.34.6 => 0.34.6 
    vitest: ^0.34.6 => 0.34.6 
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This error should be fixed in the next beta release (already merged), it's not about a subdirectory

**Comment by nicojs** [comment]
Thanks @sheremet-va. I've noticed beta5 got released yesterday and tried it on this example. It seems to work now 🎉

However, I now notice another issue when implementing browser mode inside StrykerJS's mono repo. The browser opens and seems to redirect infinitely; see the animated gif below. You can find the source code for this example here: https://github.com/stryker-mutator/stryker-js/tree/feat/vitest-browser-mode/packages/vitest-runner/testResources/browser-project

![vitest-infinite-reload](https://github.com/vitest-dev/vitest/assets/1828233/a8b8143d-3e4f-4182-9e37-eb26db487c43)

**Comment by nicojs** [comment]
I've found the cause for this last error and created a new issue: #4570. Closing this one
