### ISSUE TITLE
There are X handle(s) keeping the process running

### ISSUE THREAD

**Issue by lannuttia** [vitest-dev/vitest#4526]
### Describe the bug

This bug causes vitest to sporadically hang. In my experience it happens more frequently in my large project that uses vitest than it does in a smaller project but it will still appear in smaller projects.

```
 RUN  v0.34.6 /home/alannutt/Projects/lannuttia/recreate-vitest-hang
      Coverage enabled with v8

 ✓ src/app/shared/hooks/context/useToastContext.test.ts  (1 test) 43ms
 ✓ src/app/shared/hooks/useDispatchToast.test.tsx  (1 test) 353ms
 ✓ src/app/components/hoc/withTooltip.test.tsx  (5 tests) 926ms
 ✓ src/app/components/hoc/withModal.test.tsx  (5 tests) 1041ms
 ✓ src/app/components/hoc/withToast.test.tsx  (2 tests) 1469ms
 ✓ src/app/components/hoc/withDangerToast.test.tsx  (2 tests) 1495ms
 ✓ src/app/components/hoc/withSuccessToast.test.tsx  (2 tests) 1466ms
 ✓ src/app/components/providers/ToastAlertProvider.test.tsx  (20 tests) 3740ms

 Test Files  8 passed (8)
      Tests  38 passed (38)
   Start at  13:16:16
   Duration  16.49s (transform 505ms, setup 7.57s, collect 9.81s, tests 10.53s, environment 9.57s, prepare 3.82s)

 % Coverage report from v8
--------------------------|---------|----------|---------|---------|-------------------
File                      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
--------------------------|---------|----------|---------|---------|-------------------
All files                 |   97.21 |    91.37 |      95 |   97.21 |                   
 app                      |     100 |      100 |     100 |     100 |                   
  store.ts                |     100 |      100 |     100 |     100 |                   
 app/components/hoc       |    97.4 |    83.33 |     100 |    97.4 |                   
  withDangerToast.tsx     |     100 |      100 |     100 |     100 |                   
  withModal.tsx           |   95.12 |    81.81 |     100 |   95.12 | 42-43,69-70       
  withSuccessToast.tsx    |     100 |      100 |     100 |     100 |                   
  withToast.tsx           |   96.22 |       60 |     100 |   96.22 | 45-46             
  withTooltip.tsx         |     100 |      100 |     100 |     100 |                   
 app/components/providers |     100 |      100 |     100 |     100 |                   
  ToastAlertProvider.tsx  |     100 |      100 |     100 |     100 |                   
 app/shared/context       |   88.23 |      100 |       0 |   88.23 |                   
  toast-context.ts        |   88.23 |      100 |       0 |   88.23 | 13-14             
 app/shared/hooks         |     100 |      100 |     100 |     100 |                   
  useDispatchToast.ts     |     100 |      100 |     100 |     100 |                   
 app/shared/hooks/context |     100 |      100 |     100 |     100 |                   
  useToastContext.ts      |     100 |      100 |     100 |     100 |                   
 app/shared/utils         |   96.22 |      100 |     100 |   96.22 |                   
  test-utils.tsx          |   96.22 |      100 |     100 |   96.22 | 69-72             
 features/api             |     100 |      100 |     100 |     100 |                   
  emptySplitApi.ts        |     100 |      100 |     100 |     100 |                   
 i18n                     |      90 |      100 |     100 |      90 |                   
  config.ts               |      90 |      100 |     100 |      90 | 19-20             
 mocks                    |   91.66 |       80 |     100 |   91.66 |                   
  server.ts               |   91.66 |       80 |     100 |   91.66 | 17-18             
--------------------------|---------|----------|---------|---------|-------------------
There are 70 handle(s) keeping the process running

# Tinypool
node:internal/async_hooks:202                                                                                      
node:internal/async_hooks:504                                                                                      
file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/tinypool/dist/esm/index.js:36           
file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/tinypool/dist/esm/index.js:57           
file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/tinypool/dist/esm/index.js:799          
file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/vitest/dist/vendor-node.a7c48fe1.js:7314
file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/vitest/dist/vendor-node.a7c48fe1.js:7676

# WORKER
node:internal/async_hooks:202                                                                                      
node:internal/worker:195                                                                                           
file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/tinypool/dist/esm/index.js:536          
file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/tinypool/dist/esm/index.js:521          
file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/tinypool/dist/esm/index.js:506          
file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/tinypool/dist/esm/index.js:804          
file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/vitest/dist/vendor-node.a7c48fe1.js:7314
file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/vitest/dist/vendor-node.a7c48fe1.js:7676

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202

# FILEHANDLE
node:internal/async_hooks:202
close timed out after 10000ms
Failed to terminate worker while running /home/alannutt/Projects/lannuttia/recreate-vitest-hang/src/app/components/hoc/withModal.test.tsx.
Tests closed successfully but something prevents Vite server from exiting
You can try to identify the cause by enabling "hanging-process" reporter. See https://vitest.dev/config/#reporters
```

### Reproduction

An example of how to reproduce the issue can be found [here](https://github.com/lannuttia/recreate-vitest-hang).

Since this issue is sporadic it can take ~10 attempts in my experience to get it to happen. I get this to happen by running the following and waiting until eventually a run hangs.

```sh
npm ci;
for i in {1..100}; do                                                                                         
  echo "Attempt: $i";
  CI=true npm run test;
done
```

### System Info

```shell
System:
  OS: Linux 6.5 Fedora Linux 39 (Workstation Edition)
  CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
  Memory: 16.84 GB / 30.84 GB
  Container: Yes
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
  Yarn: 1.22.21 - ~/.nvm/versions/node/v18.18.2/bin/yarn
  npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
  pnpm: 8.10.5 - ~/.nvm/versions/node/v18.18.2/bin/pnpm
Browsers:
  Chrome: 121.0.6115.2
npmPackages:
  @vitejs/plugin-react: ^4.0.0 => 4.2.0 
  @vitest/browser: ^0.34.6 => 0.34.6 
  @vitest/coverage-v8: ^0.34.6 => 0.34.6 
  @vitest/ui: ^0.34.6 => 0.34.6 
  vite: ^4.2.1 => 4.5.0 
  vitest: ^0.34.6 => 0.34.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Is this same as https://github.com/vitest-dev/vitest/issues/3077? Redux toolkit seems to use `fetch`: https://redux-toolkit.js.org/rtk-query/api/fetchBaseQuery.

Does replacing `fetch` with `node-fetch` help? Or `--no-threads` or `--pool=forks`?

**Comment by lannuttia** [comment]
It might be the same issue? I created a new issue because most of the things I'm seeing from the `hanging-process` reporter appears to be coming from `node:internal:async_hooks` and not `node:child_process` or `node:worker_threads`.  I have tried using `--no-threads` and that did not help. As for using `--pool=forks`, the repository that I linked to is currently configured to use forks instead of threads. As for replacing the native node `fetch` with `node-fetch`, that is not something that is possible in projects that are using MSW 2.0 since [MSW 2.0 will not support polyfilling fetch](https://mswjs.io/blog/introducing-msw-2.0/#polyfills).

I'll be honest, I don't really know where exactly the actual issue is but if anyone has an idea of where it is and getting it fixed is just an issue of no one having time, I don't necessarily mind doing some leg work myself to try and get this fixed. I think `vite`, `vitest`, and `msw` are all fantastic tools that I would love to continue using. This issue is going to cause serious problems as people try to adopt all of these tools and unfortunately the current set of workarounds that exist don't really work for people using these tools in their software stack.

Again, I really appreciate all of the work that is being done here and don't mind doing some leg work myself to try and get this issue fixed if that's what it takes. I just actually don't know where to even start looking to try and fix this; or if people even already know that this issue exists and are working on a fix.

**Comment by AriPerkkio** [comment]
> the repository that I linked to is currently configured to use forks instead of threads

`pool` options are available only in v1-beta releases. Your project is still using 0.34.x releases:
- https://github.com/lannuttia/recreate-vitest-hang/blob/a02172d1e3ebf0a5566ba63dc2e877940f4ff5a9/vite.config.js#L14
- https://github.com/lannuttia/recreate-vitest-hang/blob/a02172d1e3ebf0a5566ba63dc2e877940f4ff5a9/package.json#L76

Run `npm install --save-dev vitest@beta @vitest/browser@beta @vitest/coverage-v8@beta @vitest/ui@beta` and see if `pool: 'forks'` helps.

**Comment by AriPerkkio** [comment]
This is same issue as in https://github.com/vitest-dev/vitest/issues/3077. 

I can reproduce the bug locally using the provided setup. After upgrading to Vitest v1-beta and using `pool: 'forks'` the issue does not reproduce anymore.

**Comment by raegen** [comment]
> ### Describe the bug
> This bug causes vitest to sporadically hang. In my experience it happens more frequently in my large project that uses vitest than it does in a smaller project but it will still appear in smaller projects.
> 
> ```
>  RUN  v0.34.6 /home/alannutt/Projects/lannuttia/recreate-vitest-hang
>       Coverage enabled with v8
> 
>  ✓ src/app/shared/hooks/context/useToastContext.test.ts  (1 test) 43ms
>  ✓ src/app/shared/hooks/useDispatchToast.test.tsx  (1 test) 353ms
>  ✓ src/app/components/hoc/withTooltip.test.tsx  (5 tests) 926ms
>  ✓ src/app/components/hoc/withModal.test.tsx  (5 tests) 1041ms
>  ✓ src/app/components/hoc/withToast.test.tsx  (2 tests) 1469ms
>  ✓ src/app/components/hoc/withDangerToast.test.tsx  (2 tests) 1495ms
>  ✓ src/app/components/hoc/withSuccessToast.test.tsx  (2 tests) 1466ms
>  ✓ src/app/components/providers/ToastAlertProvider.test.tsx  (20 tests) 3740ms
> 
>  Test Files  8 passed (8)
>       Tests  38 passed (38)
>    Start at  13:16:16
>    Duration  16.49s (transform 505ms, setup 7.57s, collect 9.81s, tests 10.53s, environment 9.57s, prepare 3.82s)
> 
>  % Coverage report from v8
> --------------------------|---------|----------|---------|---------|-------------------
> File                      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
> --------------------------|---------|----------|---------|---------|-------------------
> All files                 |   97.21 |    91.37 |      95 |   97.21 |                   
>  app                      |     100 |      100 |     100 |     100 |                   
>   store.ts                |     100 |      100 |     100 |     100 |                   
>  app/components/hoc       |    97.4 |    83.33 |     100 |    97.4 |                   
>   withDangerToast.tsx     |     100 |      100 |     100 |     100 |                   
>   withModal.tsx           |   95.12 |    81.81 |     100 |   95.12 | 42-43,69-70       
>   withSuccessToast.tsx    |     100 |      100 |     100 |     100 |                   
>   withToast.tsx           |   96.22 |       60 |     100 |   96.22 | 45-46             
>   withTooltip.tsx         |     100 |      100 |     100 |     100 |                   
>  app/components/providers |     100 |      100 |     100 |     100 |                   
>   ToastAlertProvider.tsx  |     100 |      100 |     100 |     100 |                   
>  app/shared/context       |   88.23 |      100 |       0 |   88.23 |                   
>   toast-context.ts        |   88.23 |      100 |       0 |   88.23 | 13-14             
>  app/shared/hooks         |     100 |      100 |     100 |     100 |                   
>   useDispatchToast.ts     |     100 |      100 |     100 |     100 |                   
>  app/shared/hooks/context |     100 |      100 |     100 |     100 |                   
>   useToastContext.ts      |     100 |      100 |     100 |     100 |                   
>  app/shared/utils         |   96.22 |      100 |     100 |   96.22 |                   
>   test-utils.tsx          |   96.22 |      100 |     100 |   96.22 | 69-72             
>  features/api             |     100 |      100 |     100 |     100 |                   
>   emptySplitApi.ts        |     100 |      100 |     100 |     100 |                   
>  i18n                     |      90 |      100 |     100 |      90 |                   
>   config.ts               |      90 |      100 |     100 |      90 | 19-20             
>  mocks                    |   91.66 |       80 |     100 |   91.66 |                   
>   server.ts               |   91.66 |       80 |     100 |   91.66 | 17-18             
> --------------------------|---------|----------|---------|---------|-------------------
> There are 70 handle(s) keeping the process running
> 
> # Tinypool
> node:internal/async_hooks:202                                                                                      
> node:internal/async_hooks:504                                                                                      
> file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/tinypool/dist/esm/index.js:36           
> file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/tinypool/dist/esm/index.js:57           
> file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/tinypool/dist/esm/index.js:799          
> file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/vitest/dist/vendor-node.a7c48fe1.js:7314
> file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/vitest/dist/vendor-node.a7c48fe1.js:7676
> 
> # WORKER
> node:internal/async_hooks:202                                                                                      
> node:internal/worker:195                                                                                           
> file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/tinypool/dist/esm/index.js:536          
> file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/tinypool/dist/esm/index.js:521          
> file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/tinypool/dist/esm/index.js:506          
> file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/tinypool/dist/esm/index.js:804          
> file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/vitest/dist/vendor-node.a7c48fe1.js:7314
> file:///home/alannutt/Projects/lannuttia/recreate-vitest-hang/node_modules/vitest/dist/vendor-node.a7c48fe1.js:7676
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> 
> # FILEHANDLE
> node:internal/async_hooks:202
> close timed out after 10000ms
> Failed to terminate worker while running /home/alannutt/Projects/lannuttia/recreate-vitest-hang/src/app/components/hoc/withModal.test.tsx.
> Tests closed successfully but something prevents Vite server from exiting
> You can try to identify the cause by enabling "hanging-process" reporter. See https://vitest.dev/config/#reporters
> ```
> 
> ### Reproduction
> An example of how to reproduce the issue can be found [here](https://github.com/lannuttia/recreate-vitest-hang).
> 
> Since this issue is sporadic it can take ~10 attempts in my experience to get it to happen. I get this to happen by running the following and waiting until eventually a run hangs.
> 
> ```shell
> npm ci;
> for i in {1..100}; do                                                                                         
>   echo "Attempt: $i";
>   CI=true npm run test;
> done
> ```
> 
> ### System Info
> ```shell
> System:
>   OS: Linux 6.5 Fedora Linux 39 (Workstation Edition)
>   CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
>   Memory: 16.84 GB / 30.84 GB
>   Container: Yes
>   Shell: 5.9 - /bin/zsh
> Binaries:
>   Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
>   Yarn: 1.22.21 - ~/.nvm/versions/node/v18.18.2/bin/yarn
>   npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
>   pnpm: 8.10.5 - ~/.nvm/versions/node/v18.18.2/bin/pnpm
> Browsers:
>   Chrome: 121.0.6115.2
> npmPackages:
>   @vitejs/plugin-react: ^4.0.0 => 4.2.0 
>   @vitest/browser: ^0.34.6 => 0.34.6 
>   @vitest/coverage-v8: ^0.34.6 => 0.34.6 
>   @vitest/ui: ^0.34.6 => 0.34.6 
>   vite: ^4.2.1 => 4.5.0 
>   vitest: ^0.34.6 => 0.34.6
> ```
> 
> ### Used Package Manager
> npm
> 
> ### Validations
> * [x]  Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
> * [x]  Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
> * [x]  Read the [docs](https://vitest.dev/guide/).
> * [x]  Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
> * [x]  Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
> * [x]  The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

So, in our case, we're using happy-dom and happy-dom's implementation of fetch is based on and quite close to node-fetch and the issue is still present. What is quite funny though, is that the incidence rate (~10%) is strikingly similar to what you're experiencing xD
