### ISSUE TITLE
Mocking doesn't work properly with ESM modules

### ISSUE THREAD

**Issue by EvHaus** [vitest-dev/vitest#453]
### Describe the bug

Given the following code:

```js
// index.ts
import child_process from 'child_process';
import util from 'util';

export default function main () {
    child_process.exec('test');
}

// index.test.ts
describe('test', () => {
    it('check', () => {
        vi.mock('child_process');

const mockedExec = vi
      .spyOn(child_process, 'exec')
      .mockImplementation((command, callback) => {
        callback();
      });

exec('test');

expect(mockedExec).toHaveBeenCalledWith('test');
    });
});
```

Everything in the mocking works fine, and the spy is able to get attached.

However, if we:

- Change the first line to `import {exec} from 'child_process';`
- And change the `main` function to `exec('test')`

Then mocking fails to get installed. Jest handles this behaviour, but Vitest doesn't.

### Reproduction

https://stackblitz.com/edit/node-hgmz55?file=index.test.ts

Note how `index.test.ts` has two identical tests but for 2 different files.

File `works.test.ts` works fine, but `fails.test.ts` doesn't. The only difference is the way the import statement is defined.

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 139.89 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2022.01.03.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 96.0.4664.110
    Chrome Canary: 99.0.4807.0
    Firefox: 95.0
    Safari: 15.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`vi.mock` doesn't work with node internals at the moment. Your first test passes because you use `vi.spyOn`. If you remove `vi.mock` it will still pass.

Will look into it today.

**Comment by sheremet-va** [comment]
Turns out it was pretty easy to fix. Will be in the next version by https://github.com/vitest-dev/vitest/commit/9c119ad1e06c0bd635b76b7de18e18ae723d8667

**Comment by sheremet-va** [comment]
Actually I was wrong! It is already working, but you mock it incorrectly, see https://stackblitz.com/edit/node-ebcpim?file=index.test.ts

You don't need `spyOn` at all. `exec` should already be a spy. Does jest works with the same setup? Maybe we have another bug when we put spy on top of another

**Comment by EvHaus** [comment]
You're right, it's not required in this simplified example, but in my real world app I want the explicit `spyOn` in each `it()` test because I want to have different mocked implementations for that function.

**Comment by sheremet-va** [comment]
> You're right, it's not required in this simplified example, but in my real world app I want the explicit `spyOn` in each `it()` test because I want to have different mocked implementations for that function.

It is already a spy, so you can just use `vi.mocked(exec).mockImplementation(() => ...)`

**Comment by EvHaus** [comment]
Hmm. It's not working consistently for me. Even in your attached [stackblitz](https://stackblitz.com/edit/node-ebcpim?file=index.test.ts), the first case is failing with:

`TypeError: [Function: exec] is not a spy or a call to a spy!`

And if I try to do `vi.mocked(exec).mockImplementation(() => ...)` I get:

```
__vite_ssr_import_0__.exec.mockImplementation is not a function
```

**Comment by sheremet-va** [comment]
I've managed to fix auto mocking for Node builtins, but I'm not sure if behaviour described in issue can be supported.

You see, `exec` is located on a different object:

```ts
import cp from 'child_process'
// exec is on `cp.default.exec`
import { exec } from 'child_process'
// exec is on `cp.exec`
```

This concept doesn't exist in CJS, so maybe that's why it's supported in Jest.  



> And if I try to do `vi.mocked(exec).mockImplementation(() => ...)` I get:
> 
> ```
> __vite_ssr_import_0__.exec.mockImplementation is not a function
> ```

This was a bug, bc automocking didn't work for Node builtins. You can use `mock factory` for now.

**Comment by sheremet-va** [comment]
Should be fixed in the latest version. Can you confirm?

**Comment by EvHaus** [comment]
Works great now, thank you!

**Comment by Codex-** [comment]
Stumbled upon this issue after a few hours of digging around why my mocking of `node:child_process` wasn't working, it was the same deal of the import style.

Would be great to have this as a note in the docs somewhere even if it is a bit specific, just as a "have you tried blah" 

Working great for me now too :)
