### ISSUE TITLE
Stricter types (no any)

### ISSUE THREAD

**Issue by romeerez** [vitest-dev/vitest#4543]
### Clear and concise description of the problem

Using the strict eslint plugin [plugin:@typescript-eslint/strict-type-checked](https://typescript-eslint.io/linting/configs/#strict-type-checked) does a great job of catching `any` types and forcing us to do something about it.

```ts
// ESLint error: unsafe assignment of `any` value.(@typescript-eslint/no-unsafe-assignment)
const anyString = expect.any(String)
```

I can fix it by adding `as unknown`:

```ts
const anyString = expect.any(String) as unknown
```

But it's an unpleasant distraction when writing tests.

### Suggested solution

Is there a reason why it's `any` and not `unknown` or something specific?

It would be awesome if `vitest` could ship an additional `d.ts` with `unknown` instead of `any`. So for existing codebases nothing will change, and for those who struggle with strict eslint errors, we could add "vitest/strict-types" to `types` in tsconfig similarly to how `vitest/globals` are added here.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
It is any because this code is valid:

```ts
type User = { name: string }

const expected: User = {
  name: expect.any(String)
}
expect({ name: 'romeerez' }).toEqual(expected)
```

If it was `unknown`, then you wouldn't be able to use this assertion.

**Comment by romeerez** [comment]
My example was simplified, I use it like this:

```ts
expect(actual).toEqual({
  foo: 'foo',
  bar: 'bar',
  someString: expect.any(String),
  createdAt: expect.any(Date),
})
```

**Comment by cloud-walker** [comment]
I quote @romeerez and the problem is extended to other expect functions, like `objectContaining` or `stringMatching`

**Comment by sheremet-va** [comment]
This was already discussed in Jest extensively. Having `any` here is better for developer experience overall. If you have eslint rule, you can disable it in your test files.

- https://github.com/jestjs/jest/issues/13812
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62831#issuecomment-1302241904
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63151

**Comment by romeerez** [comment]
I agree that the best way here is to disable strict rules for tests. And that supporting additional configs with type overrides wouldn't bring much value for Vitest.

Adding this to .eslintrc:

```js
{
  overrides: [
    {
      // disable `any` checks in tests
      files: ["src/**/*.test.ts"],
      rules: {
        "@typescript-eslint/no-unsafe-assignment": "off",
        "@typescript-eslint/no-unsafe-member-access": "off",
        "@typescript-eslint/no-unsafe-argument": "off",
      },
    },
  ],
}
```
