### ISSUE TITLE
Set order to run tests

### ISSUE THREAD

**Issue by aghArdeshir** [vitest-dev/vitest#4555]
### Clear and concise description of the problem

Ideally, tests should not depend on any order and should be isolated and that's all good. :heavy_check_mark: 

Testing frameworks also should not have any control over in what order tests are run. :heavy_check_mark: 

But! The problem begins when a bad test is in the codebase already. Scenario:
- Developer A writes a new unit test file
- The tests pass locally, and they pass in CI
- The branch is merged to master and the tests pass on main branch
- A few other branches are merged to main branch
- Suddenly the tests fail (for hard-to-debug reasons)
- We revert the last merged branch and they still fail (for the same hard-to-debug reason)
- We retry the test stage in CI several times and sometimes they pass, sometimes they fail

In this scenario we have a flaky hard-to-debug and hard-to-reproduce test. (The tests fail on CI, but pass on Dev's machines)

Turns out it only happens when the tests are run in a particular order and because on every run the order is changed, its hard to track down the issue.

### Suggested solution

Although its a bad practice to rely on test execution order, its a good idea to be able to control execution order from time to time, specially for debugging purpose like in the scenario above. So in the scenario above, I can copy the order in which tests are run in CI, and try to run them locally in the same order to easier pinpoint which test is causing the issue.

The interface/API I have in mind is vitest search and run the test files in the same order the search terms in command line is given. (with a flag to opt-in execution ordcer)

Example:
```
npx vitest shortcut button utils --order --no-threads
```

Should result in:
```
:heavy_check_mark: shortcut-accessibility.test.js
:heavy_check_mark: shortcut-performance.test.js
:heavy_check_mark: shortcut-sidebar.test.js
:heavy_check_mark: primary0button.test.js
:heavy_check_mark: secondary-button.test.js
:heavy_check_mark: utils-events.test.js
:heavy_check_mark: utils-math.test.js
```

But if I run:
```
npx vitest utils button shortcut --order --no-threads
```

I should get:
```
:heavy_check_mark: utils-events.test.js
:heavy_check_mark: utils-math.test.js
:heavy_check_mark: primary0button.test.js
:heavy_check_mark: secondary-button.test.js
:heavy_check_mark: shortcut-accessibility.test.js
:heavy_check_mark: shortcut-performance.test.js
:heavy_check_mark: shortcut-sidebar.test.js
```

That bad-named `--order` is a flag to tell vitest I'm expecting tests to be run in order I gave them in input. Because its generally a bad practice, it should be a opt-in falg. The `--no-threads` I specified to make sure the tests run one by one, but it should work without the `--no-threads` too. (Maybe with a warning indicating `:warning: Running in **threads** mode with `--order` on may not give the expected result.`

### Alternative

The current way of debugging such a scenario for me is to remove test files one by one to find out when tests pass, but that's also hard for two reasons:
1) Because tests are flaky they may not show you easily if removal of a test file made the tests pass or not
2) If the order in CI is a particular order for some reasons, we have to push and wait every time

### Additional context

The API I explained above was only a top-of-my-head suggestion. For sure people can suggest better APIs.

This is similar to https://github.com/vitest-dev/vitest/issues/3922 but describes different use case for this feature (among files, not among tests of the same test suite)

And there is this `describe concurrent` feature which again, is similar, but is not the same thing.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
> Turns out it only happens when the tests are run in a particular order and because on every run the order is changed, its hard to track down the issue.

Order is not changed on every run. By default, Vitest runs failed tests first, then long tests, and then short ones. If there is no cache, it runs larger files first.


> Although its a bad practice to rely on test execution order, its a good idea to be able to control execution order from time to time

You can already do that: https://vitest.dev/config/#sequence-sequencer

**Comment by aghArdeshir** [comment]
Thank you very much :heart: Indeed :+1: Did not use the correct search terms to look in docs. Thanks
