### ISSUE TITLE
Testing Form Input Value

### ISSUE THREAD

**Issue by Gil3co** [vitest-dev/vitest#4558]
### Describe the bug

I have a form, with `input` and `textarea` components, but when I want to check their values inside tests (that they are rendered properly, for example), I can't find the values.
Using `svelte`, `@testing-library/svelte` and `vitest`.

Not sure if this is related to the way `@testing-library/svelte` is rendering, or the way `vitest` is running the test.
If you believe it's related to `@testing-library/svelte`, I apologize and I will close this

### Reproduction

I created a very minimal reproduction repo: https://github.com/Gil3co/form-test-values
Steps to reproduce:
1. Clone the repo.
2. Run `npm i`.
3. Run `npm run test`.

See that the text (`12`) is not found.
If you run `npm run dev` you will see the text in the browser.

Any help is appreciated

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 68.69 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    npm: 9.7.2 - ~/.nvm/versions/node/v18.16.1/bin/npm
    bun: 1.0.8 - ~/.bun/bin/bun
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 16.2
  npmPackages:
    vite: ^4.4.2 => 4.5.0 
    vitest: ^0.34.0 => 0.34.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by spiroka** [comment]
Have you tried with `getByDisplayValue`? https://testing-library.com/docs/queries/bydisplayvalue
I think that query method is more appropriate here.

**Comment by Gil3co** [comment]
That did return two results! Which means it works. Thanks!
Could you explain why?
I've used `getByText` with React and RTL (not Vitest, mind you).
Do you think the difference is Svelte, or Jest/Vitest?

**Comment by spiroka** [comment]
These queries are both part of testing library's core API, I don't think there is a difference in their behaviour across these frameworks/test runners. The reason it didn't work initially is because `byText` queries are looking at the textContent of elements. To find elements by input value you should use the `byDisplayValue` queries.

**Comment by Gil3co** [comment]
I get it now, thanks a lot!
