### ISSUE TITLE
1.0.0-beta.5 version, the coverage table cannot be generated and the program terminates

### ISSUE THREAD

**Issue by arianshirepublik** [vitest-dev/vitest#4560]
### Describe the bug

1.0.0-beta.5 version, the coverage table cannot be generated and the program terminates

### Reproduction

When I run the command: yarn run test --coverage,

The desired test case has been executed but no test report or coverage table has been generated, and then the program stops here.

My config:

```
test: {
      setupFiles: './src/test/setup.ts',
      globals: true,
      environment: 'jsdom',
      coverage: {
        reporter: ['text', 'json-summary', 'json'],
        thresholds: {
          100: true,
          perFile: true,
          autoUpdate: true,

          // Thresholds for all files
          lines: 100,
          functions: 100,
          branches: 100,
          statements: 100,
        },
      },
    }

```
<img width="1158" alt="image" src="https://github.com/vitest-dev/vitest/assets/133647949/32487d16-c80a-466a-a132-a2327f2c8c0b">

I can't see this table:

<img width="1396" alt="image" src="https://github.com/vitest-dev/vitest/assets/133647949/87d3cef3-2ffb-4337-aa91-d17c9b1af021">

### System Info

```shell
Chrome: Version 119.0.6045.159 (Official Build) (arm64)
Vitest: v1.0.0-beta.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
What versions do you have in your `package.json`? The System Info of bug report is missing required information. 

Try if `coverage.all: false` helps also.

**Comment by arianshirepublik** [comment]
Hi @AriPerkkio 
I changed config

```
 test: {
      globals: true,
      setupFiles: './src/test/setup.ts',
      environment: 'jsdom',
      coverage: {
        all: false,
        reporter: ['text', 'json-summary', 'json'],
        thresholds: {
          perFile: true,
          lines: 100,
          functions: 100,
          branches: 100,
          statements: 100,
          './src/components/atoms/Avatar/Avatar.tsx': {
            branches: 100,
            functions: 100,
            lines: 100,
            statements: 100,
          },
          './src/services/user.ts': {
            branches: 100,
            functions: 100,
            lines: 100,
            statements: 100,
          },
          './src/services/rewards.ts': {
            branches: 100,
            functions: 100,
            lines: 100,
            statements: 100,
          },
          './src/lib/hooks/useGetAvatar': {
            branches: 100,
            functions: 100,
            lines: 100,
            statements: 100,
          },
          './src/lib/hooks/useUserInfo': {
            branches: 100,
            functions: 100,
            lines: 100,
            statements: 100,
          },
          './src/lib/hooks/useFetchMentions': {
            branches: 100,
            functions: 100,
            lines: 100,
            statements: 100,
          },
          './src/utils': {
            branches: 100,
            functions: 100,
            lines: 100,
            statements: 100,
          },
        },
      },
    },
```

**Comment by AriPerkkio** [comment]
Does this help?

```diff
-'./src/utils': {
+'./src/utils.ts': {
```

**Comment by arianshirepublik** [comment]
> Does this help?
> 
> ```diff
> -'./src/utils': {
> +'./src/utils.ts': {
> ```
Thank you.
Our directory looks like this：

<img width="456" alt="image" src="https://github.com/vitest-dev/vitest/assets/133647949/126f2920-1b3c-4e5d-bdd1-bc8c8e5f530d">

**Comment by AriPerkkio** [comment]
For `utils` directory you'll need `**/utils/**` glob. I would recommend to try https://www.digitalocean.com/community/tools/glob when configuring globs.

**Comment by arianshirepublik** [comment]
> For `utils` directory you'll need `**/utils/**` glob. I would recommend to try https://www.digitalocean.com/community/tools/glob when configuring globs.

So weird， I used **/utils/** but it still doesn’t work.

```
test: {
      globals: true,
      setupFiles: './src/test/setup.ts',
      environment: 'jsdom',
      coverage: {
        all: false,
        reporter: ['text', 'json-summary', 'json'],
        thresholds: {
          perFile: true,
          lines: 100,
          functions: 100,
          branches: 100,
          statements: 100,
          './src/components/atoms/Avatar/Avatar.tsx': {
            branches: 100,
            functions: 100,
            lines: 100,
            statements: 100,
          },
          './src/services/user.ts': {
            branches: 100,
            functions: 100,
            lines: 100,
            statements: 100,
          },
          './src/services/rewards.ts': {
            branches: 100,
            functions: 100,
            lines: 100,
            statements: 100,
          },
          './src/lib/hooks/useGetAvatar': {
            branches: 100,
            functions: 100,
            lines: 100,
            statements: 100,
          },
          './src/lib/hooks/useUserInfo': {
            branches: 100,
            functions: 100,
            lines: 100,
            statements: 100,
          },
          './src/lib/hooks/useFetchMentions': {
            branches: 100,
            functions: 100,
            lines: 100,
            statements: 100,
          },
          '**/utils/**': {
            branches: 100,
            functions: 100,
            lines: 100,
            statements: 100,
          },
        },
      },
    },

```
![image](https://github.com/vitest-dev/vitest/assets/133647949/ce385ae6-db04-4d9e-be00-ae5411972a1c)

**Comment by AriPerkkio** [comment]
Please add minimal reproduction that can be run, e.g. Stackbliz project or Github repository. 
I'm still not sure which versions you have specified in `package.json`.

**Comment by arianshirepublik** [comment]
> Please add minimal reproduction that can be run, e.g. Stackblitz project or Github repository. I'm still not sure which versions you have specified in `package.json`.

Hi @AriPerkkio 
https://stackblitz.com/edit/vitest-dev-vitest-9mezcf?file=vite.config.ts

**Comment by AriPerkkio** [comment]
Update your `@vitest/coverage-istanbul` to use the beta release.

```diff
- "@vitest/coverage-istanbul": "latest"
+ "@vitest/coverage-istanbul": "1.0.0-beta.5"
```

The `latest` tag points to `0.x.x` releases.

**Comment by arianshirepublik** [comment]
> Update your `@vitest/coverage-istanbul` to use the beta release.
> 
> ```diff
> - "@vitest/coverage-istanbul": "latest"
> + "@vitest/coverage-istanbul": "1.0.0-beta.5"
> ```
> 
> The `latest` tag points to `0.x.x` releases.

OK, here:  https://stackblitz.com/edit/vitest-dev-vitest-9mezcf?file=package.json

Do you have issues with processing folders multiple times?

<img width="1496" alt="image" src="https://github.com/vitest-dev/vitest/assets/133647949/d8be35fe-10d9-406e-9ced-f496a30cdf30">

**Comment by AriPerkkio** [comment]
The reproduction case has no source files in `utils/` directory. It's full of test files. 😕 

Here is working example: https://stackblitz.com/edit/vitest-dev-vitest-ozwcg6?file=utils%2Fsome-source.ts

```
 % Coverage report from istanbul
-----------------|---------|----------|---------|---------|-------------------
File             | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------------|---------|----------|---------|---------|-------------------
All files        |   66.66 |       50 |      50 |     100 |                   
 src             |      50 |      100 |       0 |     100 |                   
  basic.ts       |      50 |      100 |       0 |     100 |                   
 utils           |     100 |       50 |     100 |     100 |                   
  some-source.ts |     100 |       50 |     100 |     100 | 2                 
-----------------|---------|----------|---------|---------|-------------------
ERROR: Coverage for branches (50%) does not meet "**/utils/**" threshold (100%)
```

**Comment by arianshirepublik** [comment]
> The reproduction case has no source files in `utils/` directory. It's full of test files. 😕
> 
> Here is working example: https://stackblitz.com/edit/vitest-dev-vitest-ozwcg6?file=utils%2Fsome-source.ts
> 
> ```
>  % Coverage report from istanbul
> -----------------|---------|----------|---------|---------|-------------------
> File             | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
> -----------------|---------|----------|---------|---------|-------------------
> All files        |   66.66 |       50 |      50 |     100 |                   
>  src             |      50 |      100 |       0 |     100 |                   
>   basic.ts       |      50 |      100 |       0 |     100 |                   
>  utils           |     100 |       50 |     100 |     100 |                   
>   some-source.ts |     100 |       50 |     100 |     100 | 2                 
> -----------------|---------|----------|---------|---------|-------------------
> ERROR: Coverage for branches (50%) does not meet "**/utils/**" threshold (100%)
> ```

Hi @AriPerkkio 
Thank you. Can you check @vitest/coverage-v8 lib?

**Comment by AriPerkkio** [comment]
> Can you check @vitest/coverage-v8 lib?

It works fine as well.
