### ISSUE TITLE
expectTypeOf passes every test regardless of the types contrary to the expectation

### ISSUE THREAD

**Issue by maximilianfixl** [vitest-dev/vitest#4565]
### Describe the bug

The example from the [Vitest documentation](https://vitest.dev/api/expect-typeof.html) exists in version 1.0.0-beta.5, as well as in 0.34.6 every test. At this point, it does not matter which types are passed to the function.

```javascript
test(`should fail, because it shouldn't be constructible`, () => {
    const a = null
    expectTypeOf(a).toBeConstructibleWith({a: 1}) // Test passed
})
```

Another example behaves in the same way:

```javascript
test(`should fail because hasn't equal type`, () => {
    expectTypeOf({ a: '1', b: 1 }).toEqualTypeOf<{ a: number }>() // Test passed
})
```

It would be expected that both tests would fail.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-zpaufp?file=test%2Fexample.test.ts

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor            
    Memory: 15.80 GB / 31.91 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.72)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-vue: ^4.3.3 => 4.5.0 
    vite: ^5.0.0 => 5.0.1 
    vitest: ^1.0.0-beta.5 => 1.0.0-beta.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by maximilianfixl** [comment]
Thanks for the quick feedback! 👌
The tests are still passed with the following configurations:

CLI
```shell
vitest --typecheck.enabled
```

or

vitest.config.ts
```javascript
export default defineConfig({
    test: {
        typecheck: {
            enabled: true,
        },
        environment: 'happy-dom',
        setupFiles: 'vitest-setup.ts',
        include: [
            'src/**/*.{test,spec}.{js,mjs,cjs,ts,mts,cts,jsx,tsx}',
        ],
    }
}
```

I was able to determine that the configuration appears to be taken into account by the info message appearing on the console:

```
Testing types with tsc and vue-tsc is an experimental feature.
Breaking changes might not follow semver, please pin Vitest's version when using it.
```

**Comment by sheremet-va** [comment]
1. Vitest correctly shows failed errors in Stackblitz from what I can see
2. By default, type tests are located in `*.test-d.ts` files: https://vitest.dev/guide/testing-types.html#testing-types

**Comment by maximilianfixl** [comment]
@sheremet-va thank you very much for your comments and supporting me with my issue. And thanks for maintaining and developing the project.
At the moment, the configuration effort seems too high to use this part of the framework. I hope that Vitest continues to progress so well in the future.

Best! 😊
