### ISSUE TITLE
 Cannot find module 'rollup/parseAst' after vite 5 got released

### ISSUE THREAD

**Issue by kibertoad** [vitest-dev/vitest#4567]
### Describe the bug

After vite 5.0 got released, all of my repos and all repos of my company that use vitest got broken, and started throwing an error `Cannot find module 'rollup/parseAst'`. Looks like there is insufficient version pinning somewhere inside vitest, as it shouldn't pick up vite 5 by default.

Pinning vite to "4.5.0" explicitly resolves the error.

### Reproduction

See this as an example of CI relying on vitest being broken: https://github.com/kibertoad/layered-loader/actions/runs/6946566647/job/18898360944?pr=286

You can easily reproduce it by simply running `npm install` + `npm run build` on the repo.

### System Info

```shell
Error is reproducible both with vitest 0.34.6 and 1.0.0-beta5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
https://github.com/vitejs/vite/discussions/12466#discussioncomment-7596971

**Comment by kibertoad** [comment]
@sheremet-va That doesn't sound like a particularly great option for backend services, which more often than not, use CommonJS. Switching to anything else is likely to break other things. Is vitest 1.0.0+ going ESM-only?

**Comment by sheremet-va** [comment]
I don't see how this affects CommonJS? Correct `moduleResolution` only helps with this. Vitest doesn't go ESM-only, but Vite does give a warning if the config file is not an ESM file.

**Comment by kibertoad** [comment]
Let me test it and see if it works with CommonJS!

**Comment by kibertoad** [comment]
@sheremet-va It doesn't work. moduleResolution "node16" requires module "node16". And that effectively requires project to adhere to ESM conversion requirements, e. g. explicitly specify extensions. See https://github.com/kibertoad/layered-loader/actions/runs/6947595065/job/18901715045?pr=287

So yes, this is an extremely breaking change and won't fly well in CommonJS backend services.

**Comment by sheremet-va** [comment]
> And that effectively requires project to adhere to ESM conversion requirements, e. g. explicitly specify extensions.

That is not true. Module `node16` just follows the rules of Node 16+: https://www.typescriptlang.org/docs/handbook/modules/theory.html#the-module-output-format If you are not producing ESM build, you don't need to follow ESM rules. `CommonJS` module value was deprecated some time ago as you can see in the documentation:

> The only correct module settings for projects that intend to run in Node.js are `node16` and `nodenext`. While the emitted JavaScript for an all-ESM Node.js project might look identical between compilations using esnext and nodenext, the type checking can differ.

The error that you are seeing is correct - you cannot use `require` to import `toad-cache` because TypeScript thinks it will fail at runtime. It thinks so because `toad-cache` provides only a single "types" file for ESM, and not for CommonJS. This is a bug in `toad-cache` package, and not in Vitest or Vite: https://arethetypeswrong.github.io/?p=toad-cache%403.3.0

**Comment by sheremet-va** [comment]
I do agree that it makes things harder for existing users, so if you want this to be resolved, I'd suggest discussing it in Vite discussions at https://github.com/vitejs/vite/discussions/12466#discussioncomment-7596971

One of the possible solutions would be to create a small wrapper-file `parseAst.d.ts` in rollup package that sits at the root that re-exports `./dist/parseAst.js`

**Comment by kibertoad** [comment]
thanks, I'll explore options for fixing upstream, e.g. at toad-cache level

rollup fix would be awesome

**Comment by sheremet-va** [comment]
Link to the issue in rollup repo: https://github.com/rollup/rollup/issues/5199
