### ISSUE TITLE
Failed on node API call with custom root + environment: jsdom

### ISSUE THREAD

**Issue by Jinjiang** [vitest-dev/vitest#4568]
### Describe the bug

When:
1. call vitest in Node APIs
2. the root is out of the current project (e.g. `resolve('../bar')`)
3. the environment is `jsdom`

The test would fail as "Error: Failed to load url ... Does the file exist?"

### Reproduction

https://github.com/Jinjiang/reproductions/tree/vitest-node-20231122

core implementation:

```js
import { startVitest } from 'vitest/node';

const viteConfig = {
  configFile: false,
  envFile: false,
  test: {
    globals: true,
    // NOTE: disable this would be back to normal
    environment: 'jsdom',
    root: resolve('../bar'),
    watch: false,
    include: [
      '*.spec.js'
    ]
  }
}

startVitest('test', undefined, undefined, viteConfig);
```

### System Info

```shell
System:
    OS: macOS 14.2
    CPU: (8) arm64 Apple M1
    Memory: 70.97 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.1.0 - ~/.asdf/installs/nodejs/20.1.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/shims/yarn
    npm: 9.6.4 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.8.0 - ~/Library/pnpm/pnpm
  Browsers:
    Safari: 17.2
  npmPackages:
    vitest: ^0.34.6 => 0.34.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You need to specify the `root` in the top level configuration as well:

```ts
const viteConfig = {
  root: resolve('../bar'),
  configFile: false,
  envFile: false,
  test: {
    globals: true,
    // NOTE: disable this would be back to normal
    environment: 'jsdom',
    root: resolve('../bar'),
    watch: false,
    include: [
      '*.spec.js'
    ]
  }
}
```

The error is correct since it replicates what Vite would do in the browser (`jsdom` environment assumes it will be executed on the "web"). It happens because you cannot import files outside of root for security reasons. You can also disable this with `server.fs.strict: false`

**Comment by Jinjiang** [comment]
Gotcha. It works. And glad to know the reason behind.

Maybe one last question: do you think the error message could be improved? :-)
e.g. "Does the file exist?" -> "Does the file exists and is allowed to be read"

**Comment by sheremet-va** [comment]
Vite throws an error, not Vitest, so we can't do anything about it.
