### ISSUE TITLE
Vitest does not resolve extension in require.resolve

### ISSUE THREAD

**Issue by sagargurtu** [vitest-dev/vitest#4569]
### Describe the bug

When using `require.resolve()`, `.js` extensions are not resolved.

`.ts` extensions work but they become part of the tsc output.

Not sure if this should be considered a Vitest issue or a TypeScript issue (or no issue at all).

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-panq2b?file=src%2Fbasic.ts

### System Info

```shell
System:
- OS: Linux 5.0 undefined
- CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
- Memory: 0 Bytes / 0 Bytes
- Shell: 1.0 - /bin/jsh
Binaries:
- Node: 18.18.0 - /usr/local/bin/node
- Yarn: 1.22.19 - /usr/local/bin/yarn
- npm: 9.4.2 - /usr/local/bin/npm
- pnpm: 8.10.5 - /usr/local/bin/pnpm
npmPackages:
- @vitest/ui: latest => 0.34.6 
- vite: latest => 5.0.0 
- vitest: latest => 0.34.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest follows Node.js rules and doesn't intercept "require" in any way. This is expected behavior.
