### ISSUE TITLE
flag --typecheck is not recognized by vitest

### ISSUE THREAD

**Issue by jhonderquintero** [vitest-dev/vitest#4574]
### Describe the bug

Trying to implement `typecheck.tsconfig` (https://vitest.dev/config/#typecheck-tsconfig) to select a custom `tsconfig` for tests. According to the documentation, to use typechecking is needed to add the flag `--typecheck` when running `vitest` command, but it seems that vitest doesn't recognize that flag: 

<img width="707" alt="Screenshot 2023-11-22 at 3 19 15 PM" src="https://github.com/vitest-dev/vitest/assets/29804068/e157ae15-afb4-46b4-8d9d-fb73c4956d32">

### Reproduction

1. Add flag --typecheck in vitest script
<img width="444" alt="Screenshot 2023-11-22 at 3 19 41 PM" src="https://github.com/vitest-dev/vitest/assets/29804068/aad0b456-f5fa-45d8-a386-eb1851c09960">

2. Run: `vitest run --passWithNoTests  --typecheck`
<img width="707" alt="Screenshot 2023-11-22 at 3 19 15 PM" src="https://github.com/vitest-dev/vitest/assets/29804068/e157ae15-afb4-46b4-8d9d-fb73c4956d32"> (Throw this error)

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M2
    Memory: 623.83 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.18.1/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
  Browsers:
    Brave Browser: 110.1.48.171
    Chrome: 119.0.6045.159
    Firefox: 118.0.1
    Safari: 16.2
  npmPackages:
    vitest: 0.34.2 => 0.34.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
--typecheck works only in Vitest 1.0, for previous version use `vitest typecheck [...filters]`

**Comment by jhonderquintero** [comment]
@sheremet-va how can I specify using `vitest typecheck [...filters]` the tsconfig path to use in tests?

**Comment by sheremet-va** [comment]
You cannot do that in Vitest 0.36.4

**Comment by jhonderquintero** [comment]
I just tried with the latest version and still not working the `--typecheck` flag. Can you explain to me what does that typecheck, and how to use those` [...filters]`? please
