### ISSUE TITLE
[v1.0.0-beta5] Using Yarn PnP results in "MISSING DEP  Can not find dependency 'vite'" error.

### ISSUE THREAD

**Issue by Unnoen** [vitest-dev/vitest#4575]
### Describe the bug

Using Yarn 4.0.2 with [PnP](https://yarnpkg.com/features/pnp) mode causes Vitest to error with `MISSING DEP  Can not find dependency 'vite'`

Vitest v0.34.6 works in the same environment with PnP mode.

### Reproduction

https://github.com/Unnoen/Vitest-1.0-Yarn-PnP-Reproduction

### System Info

```shell
System:
  OS: Windows 11 10.0.22631
  CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900K
  Memory: 22.18 GB / 63.78 GB
Binaries:
  Node: 20.8.1 - C:\Program Files\nodejs\node.EXE
  Yarn: 4.0.2 - C:\Program Files\nodejs\yarn.CMD
  npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
  Edge: Chromium (119.0.2151.72)
  Internet Explorer: 11.0.22621.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wojtekmaj** [comment]
I am too facing this issue, on vitest@1.0.1.

It seems to be related to #4413, #899 as it's ultimately local-pkg which results in incorrect outcomes being produced. This has been reported in https://github.com/antfu/local-pkg/issues/2 but it's been stuck for 1.5 years now 🤷‍♂️
