### ISSUE TITLE
vitest with happy-dom: window.CSS.supports is undefined

### ISSUE THREAD

**Issue by dr2009** [vitest-dev/vitest#4576]
### Describe the bug

```js
// environment: 'happy-dom'
console.log(CSS); // { escape: [Function: cssEscape] }
expect(CSS.escape).toBeDefined(); // ok
expect(CSS.supports).toBeDefined(); // not ok
```

becuase happy-dom depends `css.escape`, it will change global.CSS to { escape: cssEscape } when import it

https://github.com/mathiasbynens/CSS.escape/blob/master/css.escape.js#L97-L101

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-12tbkc?file=vite.config.ts,test%2Fsuite.test.ts,test%2Fbasic.test.ts&initialPath=__vitest__/

### System Info

```shell
System:
    OS: macOS 13.2
    CPU: (8) arm64 Apple M1
    Memory: 155.31 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/Library/Caches/fnm_multishells/15709_1700617114296/bin/node
    npm: 10.1.0 - ~/Library/Caches/fnm_multishells/15709_1700617114296/bin/npm
    pnpm: 8.10.5 - ~/Library/Caches/fnm_multishells/15709_1700617114296/bin/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 119.0.6045.159
    Edge: 116.0.1938.76
    Safari: 16.3
    Safari Technology Preview: 16.4
  npmPackages:
    @vitest/coverage-v8: 1.0.0-beta.4 => 1.0.0-beta.4 
    vitest: 1.0.0-beta.4 => 1.0.0-beta.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
If happy-dom doesn't provide a global variable, open an issue in happy-dom repository.

**Comment by dr2009** [comment]
> If happy-dom doesn't provide a global variable, open an issue in happy-dom repository.

happy-dom provide the global variable: CSS
but vitest populateGlobal lost it
https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/integrations/env/happy-dom.ts#L50C33-L50C47
win.CSS ok, but global.CSS  { escape: [Function: cssEscape] }


becuase happy-dom depends css.escape, it will change global.CSS to { escape: cssEscape } when import it

getWindowKeys 
https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/integrations/env/utils.ts#L10

**Comment by sheremet-va** [comment]
You are right, sorry for closing the issue.
