### ISSUE TITLE
Workspace configuration works only with inline configuration

### ISSUE THREAD

**Issue by ascariandrea** [vitest-dev/vitest#4577]
### Describe the bug

Hi there, I'm having an issue with _workspace_ configuration in my project. Basically, it runs all the tests only when configurations are defined _inline_, while it runs only the first matched when defined with the _glob_ pattern.

In the reproduction I've defined the `vitest.workspace.ts` with both configurations (the _glob_ pattern one is commented) so you can check this properly.

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-qrhqud?file=vitest.workspace.ts

### System Info

```shell
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 4.10 GB / 15.34 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
    npm: 9.7.1 - ~/.nvm/versions/node/v16.20.0/bin/npm
    bun: 1.0.3 - ~/.bun/bin/bun
  Browsers:
    Chrome: 119.0.6045.159
  npmPackages:
    @vitest/coverage-v8: ^0.34.5 => 0.34.6 
    @vitest/ui: ^0.34.6 => 0.34.6 
    vitest: ^0.34.5 => 0.34.6
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest filters only a single config per folder at the moment

**Comment by ascariandrea** [comment]
Thanks for the quick reply @sheremet-va, did I miss this point in the documentation or is not highlighted at all?

**Comment by sheremet-va** [comment]
It's not highlighted, and looks like a bug to be honest.

**Comment by Lewenhaupt** [comment]
Also encountered this when I tried to add a config file for unit tests and one for integration tests in the same folder

**Comment by ascariandrea** [comment]
@sheremet-va yes, the correct implementation I expect would filter out the `vite(st).config` keeping all the others matching the glob pattern.

**Comment by sheremet-va** [comment]
The workspace resolution was rewritten in 2.1.
