### ISSUE TITLE
`new Date() instance of Date` should be true when using setSystemTime

### ISSUE THREAD

**Issue by spiroka** [vitest-dev/vitest#4579]
### Describe the bug

When using setSystemTime, Date objects will not be instances of (the now mocked) Date.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-uwiefu?file=index.test.js

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Xeon(R) Gold 6248R CPU @ 3.00GHz
    Memory: 10.69 GB / 32.00 GB

  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD

  Browsers:
    Edge: Spartan (44.19041.3570.0), Chromium (119.0.2151.72)
    Internet Explorer: 11.0.19041.3570

  npmPackages:
    @vitejs/plugin-react: ^4.1.1 => 4.1.1
    @vitest/coverage-v8: ^0.34.6 => 0.34.6
    @vitest/ui: ^0.34.6 => 0.34.6
    vite: 4.5.0 => 4.5.0
    vitest: ^0.34.6 => 0.34.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Workaround:

```ts
vi.useFakeTimers()
vi.setSystemTime('2023-11-22');
expect(new Date()).toBeInstanceOf(Date);
```
