### ISSUE TITLE
Test fails on CI, reproduced locally with --no-threads

### ISSUE THREAD

**Issue by guytepper** [vitest-dev/vitest#4580]
### Describe the bug

When running Vitest + `@testing-library/react` on my CI, my tests failing constantly.

Related issues: #270, #1207, #1251

#1207 had the same issue as mine: 
> - By using `--no-threads` I was able to reproduce this locally, but not sure it's the same cause as the CI.
> - When running only one test (yarn test --no-threads src/One in the repro), everything works as expected but when running all the tests (yarn test --no-threads), only the first one succeeds and the rest will fail.

However, it was resolved with no clear solution provided.

### Reproduction

Referencing the repro from #1207 for convenience:
https://github.com/vjee/vitest-and-testing-library-issue

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 58.06 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    Watchman: 2023.09.18.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 119.0.6045.123
    Safari: 17.1
  npmPackages:
    @vitejs/plugin-react: ^1.3.0 => 1.3.1
    vite: ^2.9.5 => 2.9.6
    vitest: ^0.10.0 => 0.10.0 (tried both on 0.34.6 and 1.0.0-beta.5)
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
>  my tests failing constantly.

What is the error?

> for convenience

Convenient to whom? `--no-threads` flag has changed its semantics since 0.10.0 two times already, this reproduction doesn't reference code from _this year_ even.

Vitest has several examples with `@testing-library/react` and none is failing at the moment.

**Comment by ajnozari** [comment]
I'm also seeing this issue.  Strangely I noticed it works fine on Node 16 but as soon as I upgrade/run on any system with node 18+ I begin to have tests fail.

**Comment by guytepper** [comment]
The repro with latest versions installed indeed worked fine, I missed the versions mismatch, sorry @sheremet-va.

Eventually I figured that the issue was with the CI running in a self-hosted environment, and its configuration was interfering with Vitest. Changing the CI to run on Github's hosted `ubuntu-latest` made the tests pass.
