### ISSUE TITLE
CLI error for `vitest --ui`

### ISSUE THREAD

**Issue by JesusTheHun** [vitest-dev/vitest#4589]
### Describe the bug

```
⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯
file:///Users/jonathan/IdeaProjects/couchnode/node_modules/vitest/dist/chunks/install-pkg.ORGzQeqb.js:5
import execa from 'execa';
       ^^^^^
SyntaxError: The requested module 'execa' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```

### Reproduction

Executing `vitest --ui` without having `@vitest/ui` installed leads to the error.

```bash
npm i -D vitest@1.0.0-beta.5
vitest --ui
```

https://stackblitz.com/edit/vitest-dev-vitest-i4krdj?file=package.json

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 18.47 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.1/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    pnpm: 7.29.1 - ~/.nvm/versions/node/v18.16.1/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.159
    Edge: 119.0.2151.72
    Safari: 17.1
  npmPackages:
    vitest: 1.0.0-beta.5 => 1.0.0-beta.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
This is an upstream issue in `install-pkg`:

- https://github.com/antfu/install-pkg/commit/1bdfe3dfe3c203cadf159aad478c960b7ba70944#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L41
- https://github.com/sindresorhus/execa/releases/tag/v6.0.0

**Comment by AriPerkkio** [comment]
Looks like `install-pkg` is actually correct. It's just Vitest's build that ends up using default export: https://unpkg.com/browse/vitest@1.0.0-beta.5/dist/chunks/install-pkg.ORGzQeqb.js

Maybe this is caused by Vitest depending on execa@8 and install-pkg@0.1x.
