### ISSUE TITLE
Images not loding in "Browser Mode"

### ISSUE THREAD

**Issue by Andrew-web-coder** [vitest-dev/vitest#4598]
### Describe the bug

Since Vite supports assets like images out of the box, vitest should support them too. But, all I can get is 404 error. I could not find anything about handling assets in the docs.

### Reproduction

Upload image, try to access from the browsers, observe 404 error.

### System Info

```shell
I believe it does not matter, just following the clean setup from docs.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Andrew-web-coder** [comment]
@sheremet-va Sorry, I was not able to create a demo, because it just does not work, see https://stackblitz.com/edit/vitest-dev-vitest-oibcm9?file=test%2Fbasic.test.ts,package.json&initialPath=__vitest__/

Also, I found that images are loading correctly when not using "Browser Mode", sorry about that.

**Comment by sheremet-va** [comment]
> @sheremet-va Sorry, I was not able to create a demo, because it just does not work, see [stackblitz.com/edit/vitest-dev-vitest-oibcm9?file=test%2Fbasic.test.ts,package.json&initialPath=__vitest__](https://stackblitz.com/edit/vitest-dev-vitest-oibcm9?file=test%2Fbasic.test.ts,package.json&initialPath=__vitest__/)
> 
> Also, I found that images are loading correctly when not using "Browser Mode", sorry about that.

You can use a GitHub repository to create a demo.

**Comment by Andrew-web-coder** [comment]
To be honest, I do not care about Vitest anymore, because it just does not work as expected and therefore is not usable to me.
First, headless mode is not working at all (and my issue about that was ignored), browser mode do not serve any file and this issue is also ignored.
