### ISSUE TITLE
vi.mock breaks live bindings

### ISSUE THREAD

**Issue by nathanmmiller** [vitest-dev/vitest#4604]
### Describe the bug

If vi.mock is used in a test module, live bindings break. I've included an example reproduction below, using "latest" version of vitest.

It doesn't matter what format you do the vi.mock in or if it mocks another module or an external package.

I've tried (using file-saver as an example):
- vi.mock('file-saver');
- vi.mock('file-saver', () => ({}));
- vi.mock('file-saver', async (importOriginal) => {
  const mod = await importOriginal();
    return mod;
    });
- ...etc. All to the same effect

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-bq5brv?file=test%2Fbasic.test.ts

Simply comment out line 5 in basic.test.ts to see the tests pass, then uncomment it and one test (the live bindings one) will fail because the live binding no longer works.

### System Info

```shell
Stackblitz, but this is reproducible elsewhere as well.
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Yeah, it's a known issue. There is an open issue already, but I can't find for now.

**Comment by nathanmmiller** [comment]
@sheremet-va yikes! That impacts me pretty significantly (I provided a tiny repro, but essentially I rely on live binding all over my tests for a number of reasons). Is there any kind of expectation of when this could be fixed, or should I stick with jest for the time being?

**Comment by sheremet-va** [comment]
Workaround is described here: https://github.com/vitest-dev/vitest/issues/3300
