### ISSUE TITLE
vi.spyOn(module, 'function') doesn't work for nested calls

### ISSUE THREAD

**Issue by Gena888** [vitest-dev/vitest#4610]
### Describe the bug

Hi there, 

I faced an issue trying to mock one function that is called by another function in the same file. 
Could you please help me to resolve that issue or suggest me a better approach to that case? 
I'm attaching screenshots of my setup and console.

My expectations:  
- I want `expect(function2()).toEqual(101);` to be truthful
- I want ` console.log('🦄 function1: ', function1);` while running the test - to be something like: 
`[Function: mockConstructor] { _isMockFunction: true, ....`

constraints: 
- I don't want to split my functions into 2 different files in order to mock the full file for testing needs. 
- I don't want to pass a function as a param finally using currying 

<img width="972" alt="image" src="https://github.com/vitest-dev/vitest/assets/74081058/c0583d7c-8748-44d5-adbb-eed86811af0d">

What I've also tried: 
<img width="465" alt="image" src="https://github.com/vitest-dev/vitest/assets/74081058/c59dc208-c91f-42f3-afa6-bffd5b058593">
<img width="457" alt="image" src="https://github.com/vitest-dev/vitest/assets/74081058/101a30fa-ca78-4ef4-937c-1f27bb44bac2">
<img width="388" alt="image" src="https://github.com/vitest-dev/vitest/assets/74081058/05c9d194-c2d6-44f9-b926-815c0ed01ca2">

### Reproduction

Place those 2 files in one folder and run the Vitest. 

test.ts file: 

```
export const function1 = () => {
    return 10;
};

export const function2 = () => {
    console.log('🦄 function1: ', function1);
    return function1() + 1;
};
```

test.test.ts file: 

```
import { describe, expect, it, vi } from 'vitest';
import { function2 } from './test';
import * as testModule from './test';

vi.spyOn(testModule, 'function1').mockReturnValue(100);

describe('function2 tests', () => {
    it('should return 11', () => {
        expect(function2()).toEqual(101);
    });
});
```

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 111.20 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 10.1.0 - /opt/homebrew/bin/npm
    pnpm: 8.10.2 - ~/Library/pnpm/pnpm
    Watchman: 2023.10.02.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 17.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`vi.spyOn` spies on a module object but in your example you are referencing `function1` by its original reference, so it's not intercepted. What you are trying to do is not possible to achieve with JavaScript. There was a bug in `ts-jest` that allowed a similar behaviour, but it's not achievable even in Jest. For reference:

- https://github.com/vitest-dev/vitest/issues/4190
- https://github.com/vitest-dev/vitest/issues/3733
- https://github.com/vitest-dev/vitest/issues/3592

**Comment by Gena888** [comment]
Gotcha, thank you so much. Here is a sandbox with proofs
https://stackblitz.com/edit/node-xrl7pq?file=src%2Ftest.test.js,src%2Ftest.js 

But maybe you know of any possible solutions for Vitest? Maybe any additional libs/packages that could help me to achieve my goals? 🤔

**Comment by sheremet-va** [comment]
I can only recommend refactoring.
