### ISSUE TITLE
Test coverage drops when component props are updated

### ISSUE THREAD

**Issue by Stadly** [vitest-dev/vitest#4612]
### Describe the bug

I have a very simple component that has 100% test coverage. If I update the component prop in my test, the branch coverage drops to 0%.

My expectation is that updating the component prop should not reduce the test coverage.

### Reproduction

Consider the following component:

```svelte
<script lang="ts">
    export let messages: string[] = [];
</script>

<ul>
    {#each messages as message}
        <li>{message}</li>
    {/each}
</ul>
```

and test file:
```ts
import { render } from "@testing-library/svelte";
import { it } from "vitest";
import Conversation from "./Conversation.svelte";

const messages = [
    "Hello, I'm looking for some information about Norway.",
    "Hi, I can help you with that. What would you like to know?",
    "What are some of the most popular tourist attractions in Norway?",
    "Some of the most popular tourist attractions in Norway are the Norwegian fjords, the Northern Lights, the Viking Ship Museum, and the Holmenkollen Ski Jump.",
];

it("should render the messages correctly", () => {
    const { component } = render(Conversation, {
        messages: messages.slice(0, 1),
    });

    // Uncomment the next line and branch coverage goes from 100% to 0%.
    // component.$set({ messages });
});
```

This generates the following test coverage:
```
 % Coverage report from v8
---------------------|---------|----------|---------|---------|-------------------
File                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
---------------------|---------|----------|---------|---------|-------------------
All files            |     100 |      100 |     100 |     100 |                   
 Conversation.svelte |     100 |      100 |     100 |     100 |                   
---------------------|---------|----------|---------|---------|-------------------
```

If I uncomment `component.$set({ messages });` in the test file, I get the following test coverage:
```
---------------------|---------|----------|---------|---------|-------------------
File                 | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
---------------------|---------|----------|---------|---------|-------------------
All files            |     100 |        0 |     100 |     100 |                   
 Conversation.svelte |     100 |        0 |     100 |     100 | 7                 
---------------------|---------|----------|---------|---------|-------------------
```

This is the generated report:
![image](https://github.com/vitest-dev/vitest/assets/7263579/f164d729-eb14-4c3d-a9a7-802bcb7c4e42)

Link to GitHub repo reproducing the issue: https://github.com/Stadly/VitestSvelteTestCoverageV8

### System Info

```shell
System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 7.61 GB / 15.50 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.18.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
  npmPackages:
    @vitest/coverage-v8: ^0.34.6 => 0.34.6 
    vite: ^4.4.2 => 4.5.0 
    vitest: ^0.34.0 => 0.34.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
This is same as https://github.com/vitest-dev/vitest/issues/1893. The root cause is described here: https://github.com/sveltejs/svelte/issues/7824.

#1893 is about Istanbul provider, but V8 provider relies on source maps as well.
