### ISSUE TITLE
Literal check for fields not in Property Matcher.

### ISSUE THREAD

**Issue by Ghislain89** [vitest-dev/vitest#4617]
### Clear and concise description of the problem

When using Snapshots with Jest, any fields that are not provided with property matchers will be checked literally. See [here](https://jestjs.io/docs/snapshot-testing#property-matchers). In the example, property matchers are only provided for createdAt and id, while the name field is checked literally. 

As far as I could tell, once you provide a property matcher, you're required to provide the **entire** snapshot otherwise comparison wil fail. This behaviour can also be seen in [this commit](https://github.com/vitest-dev/vitest/commit/f27d2d6#diff-9bd5063394102bde0c9c7f35646d193589760fb667a2c01fd9027ca61e550fe9R81)

### Suggested solution

Match behaviour with Jest so that any value that is not provided as a PropertyMatcher will be checked with it's literal value.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
> any value that is not provided as a PropertyMatcher will be checked with it's literal value.

@Ghislain89 Could you clarify what's the expected/actual behavior with concrete code?
I might be missing what you're trying to point out, but from quick comparison, "checked with it's literal value" seems to be working. Here is what I tested on stackblitz:

- Vitest https://stackblitz.com/edit/vitest-dev-vitest-bkbkdw?file=test%2Frepro.test.ts
- Jest https://stackblitz.com/edit/jest-example-adgseb?file=repro.test.js

<details><summary>show example code</summary>

```ts
test('fail', () => {
  const user = {
    createdAt: new Date(),
    id: Math.floor(Math.random() * 20),
    name: 'NOT LeBron James',
  };

  expect(user).toMatchInlineSnapshot(
    {
      createdAt: expect.any(Date),
      id: expect.any(Number),
    },
    `
{
  "createdAt": Any<Date>,
  "id": Any<Number>,
  "name": "LeBron James",
}`
  );
});
```

- Vitest failure log

```
Error: Snapshot `fail 1` mismatched

- Expected
+ Received

  {
    "createdAt": Any<Date>,
    "id": Any<Number>,
-   "name": "LeBron James",
+   "name": "NOT LeBron James",
  }

 ❯ eval test/repro.test.ts:31:16
     29|   };
     30| 
     31|   expect(user).toMatchInlineSnapshot(
       |                ^
     32|     {
     33|       createdAt: expect.any(Date),
```

- Jest failure log

```
    expect(received).toMatchInlineSnapshot(properties, snapshot)

    Snapshot name: `fail 1`

    - Snapshot  - 1
    + Received  + 1

      {
        "createdAt": Any<Date>,
        "id": Any<Number>,
    -   "name": "LeBron James",
    +   "name": "NOT LeBron James",
      }
```

</details>

**Comment by Ghislain89** [comment]
Interesting, Trying out the behaviour in stackblitz indeed gives me my expected behaviour. I've updated your stackblitz with an example that is a little bit more complex:

see https://stackblitz.com/edit/vitest-dev-vitest-ex4ruj?file=test%2Frepro.test.ts.

Even when leaving out specific fields, this appears to work. I'll retry locally and report back.

**Comment by Ghislain89** [comment]
I believe I may have found where I've messed things up yesterday.  I like full control over when I run my tests so when usually don't use watch mode. 

Running `npx vitest run -u` doesn't apparently update the snapshot. It's likely that my snapshot wasn't updating yesterday which caused me to believe it wasn't working.
