### ISSUE TITLE
vi.mock makes vi.spyOn  to fail

### ISSUE THREAD

**Issue by hadson172** [vitest-dev/vitest#4619]
### Describe the bug

My code looks like this:
```
//vi.mock(("anything???!!!!"))
describe('tests', () => {

    it("this works but fails when i uncomment vi.mock, why", () => {
        vi.spyOn(Module, 'moduleFunction')
        expect(moduleFunction).not.toHaveBeenCalled()
    })

    it("this works as well", () => {
        const spy = vi.spyOn(Module, 'moduleFunction')
        expect(spy).not.toHaveBeenCalled()
    })
});
```
In short, in jest everything it is working, in vitest first case it is failing when i add any call to vi.mock.
It would be nice to have any documentation about this issue or explanation in migration guide.

### Reproduction
Edit: https://stackblitz.com/edit/vitest-dev-vitest-t5pdkp?file=test%2Fsuite.test.ts,src%2Fbasic.ts&initialPath=__vitest__/

```
//vi.mock(("anything???!!!!"))
describe('tests', () => {

    it("this works but fails when i uncomment vi.mock, why", () => {
        vi.spyOn(Module, 'moduleFunction')
        expect(moduleFunction).not.toHaveBeenCalled()
    })

    it("this works as well", () => {
        const spy = vi.spyOn(Module, 'moduleFunction')
        expect(spy).not.toHaveBeenCalled()
    })
});
```

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 293.77 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - /usr/local/bin/node
    npm: 9.8.1 - /usr/local/bin/npm
    pnpm: 8.10.5 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.199
    Safari: 17.1
  npmPackages:
    @vitejs/plugin-react: ^4.2.0 => 4.2.0 
    vite: ^5.0.0 => 5.0.2 
    vitest: ^0.34.6 => 0.34.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> In short

Are you describing an issue or telling a joke?

**Comment by hadson172** [comment]
> > In short
> 
> Are you describing an issue or telling a joke?

Yes, that's exactly what I meant. Was it funny ? 

https://stackblitz.com/edit/vitest-dev-vitest-t5pdkp?file=test%2Fsuite.test.ts,src%2Fbasic.ts&initialPath=__vitest__/

**Comment by mikhin** [comment]
bug confirmed
