### ISSUE TITLE
Unknown option --threads when run vitest with --no-threads option

### ISSUE THREAD

**Issue by adequatica** [vitest-dev/vitest#4620]
### Describe the bug

Hello,

I run test with disabled multi-threading (it works fine on `0.34.6`):

```
vitest run --no-threads
```

After switch on `1.0.0-beta.5` and then `1.0.0-beta.6`, the same command leads to the error:

```
file:///Users/my-username/my-repo-name/node_modules/cac/dist/index.mjs:400
          throw new CACError(`Unknown option \`${name.length > 1 ? `--${name}` : `-${name}`}\``);
                ^

CACError: Unknown option `--threads`
    at Command.checkUnknownOptions (file:///Users/my-username/my-repo-name/node_modules/cac/dist/index.mjs:400:17)
    at CAC.runMatchedCommand (file:///Users/my-username/my-repo-name/node_modules/cac/dist/index.mjs:598:13)
    at CAC.parse (file:///Users/my-username/my-repo-name/node_modules/cac/dist/index.mjs:537:12)
    at file:///Users/my-username/my-repo-name/node_modules/vitest/dist/cli.js:71:7
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async main (file:///Users/my-username/my-repo-name/node_modules/vitest/dist/cli-wrapper.js:45:5)

Node.js v21.2.0
```

Reinstalling packages don't help. Rollback to `0.34.6` fix the problem ⇒ I'm making an assumption that something is wrong with beta version.

### Reproduction

Node.js 21.2.0
TypeScript: 5.2.2

1. https://github.com/adequatica/api-vitesting
2. Change `"vitest": "1.0.0-beta.6"`
3. `npm install`
4. Run `npm test`

### System Info

```shell
System:
  OS: macOS 13.6.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 7.51 GB / 32.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 21.2.0 - ~/.nvm/versions/node/v21.2.0/bin/node
  npm: 10.2.3 - ~/.nvm/versions/node/v21.2.0/bin/npm
Browsers:
  Safari: 17.1
npmPackages:
  vitest: 1.0.0-beta.6 => 1.0.0-beta.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`--threads` was removed in beta 0 and replaced with `--pool=threads`: https://github.com/vitest-dev/vitest/releases/tag/v1.0.0-beta.0

**Comment by adequatica** [comment]
Ah, thanks a lot, look forward for 1.0 release and documentation updates.
