### ISSUE TITLE
More explicit message for the "first argument must use object destructuring pattern"

### ISSUE THREAD

**Issue by magnaar** [vitest-dev/vitest#4621]
### Clear and concise description of the problem

I tried to build a `fixture` or a `beforeEach`, but sometimes I get this message:

> Error: the first argument must use object destructuring pattern

(even if I use the destructuring pattern)

Sometimes, it's when I import something, sometimes it's something else.
It makes this library quite unreliable for what I want to do.

This message is so generic, it doesn't even tell what line provoked this and where this error came from.

### Suggested solution

Either providing the line and file that provoked the raised of this error (or the stacktrace if possible).

### Alternative

Revert some changes that occured with the 0.34.4+ which enforce the use of the destructuring pattern.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by magnaar** [comment]
I'm not really sure if it's a bug or not. Because I probably tried something twisted.
But the fact remain, the error message doesn't help a lot.
I have a shared project that defines some stuff for my tests, and when I imported it in another, I had this error (I fixed it for my use case, but I did something even more twisted compared to the older vitest version (`0.32.2/3`, now, I'm trying the `v1.0.0-beta.6`, but since `beforeEach` and `afterEach` have changed (they don't expose the `TestContext/SuiteContext` as easily now), I had to change my stuff)).

To be more explicit of what I was trying to do, it's just to build an object in the beforeEach, and pass it to my tests as a `fixture` (a test context that contains my default inputs (default parameters, default mocks, for my test file))
I don't like to have a global variable in my test file, too prone to forget about it or to have it modified by two tests when a promise takes too long to complete (had this issue with Jest, I didn't try if it was the case with vitest), so I prefer that each test has their own references.

So one thing that cause the error is:
```
beforeEach(context => {
    // This is executed
})
// And after we get the error, which is already weird
```
For this, I understand why I got the error, but not why my code is still executed.

But it's not the weirdest thing and not what I was talking about in the first post.
I will try to make an example, but I have to check before if it's because of typescript or not.

My only concern here, it's just to have a more explicit error message, because if you import a file with fixtures, finding the one that caused this is quite a pain.

**Comment by thopiddock** [comment]
On a related note, I'm finding that fixtures are not saving their values within a suite context, but only when you are extending `test` 
 to add functionality to your fixtures. Static values work okay without unwrapping, but only if your suite hasn't been affected by a `test.extend` in the process, and oddly enough it *will* do it on a describe block passed `it` function if you expose the extend to it in TypeScript when using the wrapped fixture.

[Reproduction on Stackblitz](https://stackblitz.com/edit/vitest-dev-vitest-6emczr?file=test%2Fexample.test.ts).

Hopefully this helps shed some light on this? I've found that the only way around it is to destructure it but use an object to wrap the values you're storing as values for the fixtures.

**Comment by sheremet-va** [comment]
This shouldn't be a problem anymore.
