### ISSUE TITLE
Importing from $app/forms fails in tests - SvelteKit

### ISSUE THREAD

**Issue by Gil3co** [vitest-dev/vitest#4630]
### Describe the bug

When I import something from `$app/forms`, like `enhance` in one of my components, `vitest` tests fail.
Even when I try to mock `$app/forms`, it fails, without even reaching my mock.

Thank you!

### Reproduction

https://github.com/Gil3co/app-forms-test-fail
To reproduce:

1. Clone the repo and run `npm i`.
2. Run `npm run test` and see the test fails.

This is the error:
`Error: Failed to resolve import "$app/forms" from "src/routes/Component.svelte". Does the file exist?`

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 86.83 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    npm: 9.7.2 - ~/.nvm/versions/node/v18.16.1/bin/npm
    bun: 1.0.8 - ~/.bun/bin/bun
  Browsers:
    Chrome: 119.0.6045.159
    Safari: 16.2
  npmPackages:
    vite: ^4.4.2 => 4.5.0 
    vitest: ^0.34.0 => 0.34.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Bluzzi** [comment]
I have the same problem, my import alias are not resolved.

It works when I install version `4.5` of Vite, but with version `5` I get this error:
```ts
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    setupFiles: ["dotenv/config"],
    include: ["**/*.test.ts"],
    environment: "happy-dom"
  },
  resolve: {
    alias: {
      "#/": "./src/"
    }
  }
});
```

**Comment by Gil3co** [comment]
@sheremet-va Thank you very much for this answer!
I've tried it, and it still doesn't.
Here is my config:
```
import { dirname, resolve } from 'path';
import { defineConfig } from 'vitest/config';
import { svelte } from '@sveltejs/vite-plugin-svelte';
import { fileURLToPath } from 'url';

export default defineConfig({
  plugins: [svelte({ hot: !process.env.VITEST })],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: 'vitest-setup.ts',
    include: ['src/**/*.test.ts'],
    alias: [
      {
        find: /$app\/forms/,
        replacement: resolve(
          fileURLToPath(dirname(import.meta.url)),
          '/.empty.js',
        ),
      },
      { find: '@app', replacement: resolve(__dirname, './src/routes') },
      { find: '@mocks', replacement: resolve(__dirname, './src/__mocks__') },
      { find: '$lib', replacement: resolve(__dirname, './src/lib') },
    ],
  },
});
```

Is something still wrong here?

**Comment by Gil3co** [comment]
Changing the `find` value to `$app/forms`, as a string and not as a regex made it work, thanks!
