### ISSUE TITLE
Vitest always writes snapshot files on Windows 10 with Node 18.17.1

### ISSUE THREAD

**Issue by christoph-schlumpf** [vitest-dev/vitest#4653]
### Describe the bug

On Windows 10 with Node 18.17.1, vitest always writes the snapshot files when running the tests, even if there are no changes in the snapshot. This leads to unnecessary writes and changed files in the repo.

Reason for this issue is this code:
https://github.com/vitest-dev/vitest/blob/eca25dc9b3a952b87a07bd4063ed92f0d81e3914/packages/snapshot/src/env/node.ts#L39

`readSnapshotFile `always reads an empty string ("") on Windows. Additionally, many repos on windows have git config autocrlf enabled.

I fixed it with the following patch:
```
const readSnapshotFile = async (filepath) => {
    if (!existsSync(filepath)) {
        return null;
    }
    return promises
        .readFile(filepath, { encoding: "utf-8" })
        .then((content) => (process.platform === "win32" ? content.replace(/\r\n|\r/g, "\n") : content));
}; 
```

### Reproduction

Can be reproced on any Windows machine with Node 18.17.1 and vitest with snapshots.

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 25.88 GB / 47.71 GB
  Binaries:
    Node: 18.17.1 - C:\eplatform\mytools\node\node.EXE
    npm: 9.6.7 - C:\eplatform\mytools\node\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (119.0.2151.58)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @vitejs/plugin-react: ~4.0.0 => 4.0.4
    @vitest/coverage-istanbul: ^0.34.6 => 0.34.6
    @vitest/ui: ~0.32.0 => 0.32.4
    vite: ~4.3.9 => 4.3.9
    vitest: 0.34.6 => 0.34.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
We don't think this should be built-in, but we can expose an option to override the default behaviour: #5449

**Comment by christoph-schlumpf** [comment]
Hi @sheremet-va Thank you for the information. we will try out the override solution.
