### ISSUE TITLE
Unable to access input field in vitest dom

### ISSUE THREAD

**Issue by MananSoniDechea** [vitest-dev/vitest#4666]
### Describe the bug

Hi, I am using skeleton UI with sveltekit and writing test cases using vitest
I am trying to test click on skeleton tree view component which has an input element which receives the click event
But when writing the test I am unable to find it, and upon investigation I found out that the testing dom does not have the input field at all.

![bug1](https://github.com/vitest-dev/vitest/assets/107920583/91b16325-2dcc-49a9-9d54-772b8f97f7ff)
![bug2](https://github.com/vitest-dev/vitest/assets/107920583/5a16536a-5bd0-4514-b1cf-fe59084b7912)

### Reproduction

schema tree component
```
<RecursiveTreeView
	disabled
	indent="ml-9"
	nodes={schemaTreeNodes}
	selection
	multiple
	relational
	bind:checkedNodes={$syncOptions}
	class="p-2 {$syncOptionsError
		? '[&_.tree-item-checkbox]:border-error-400 [&_.tree-item-checkbox]:bg-error-50'
		: ''}"
/>
```
test case
```
describe('schema tree', () => {
	it('is in sync with syncOptions', async () => {
		schema.set({
			Collection: [
				{
					name: 'collection1'
				},
				{
					name: 'collection2'
				}
			]
		});
		const { container, getByTestId } = render(SchemaTree);
		console.log(container);
	});
});
```
You can see in the container there is no input tag

### System Info

```shell
System:
    OS: Linux 6.1 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD EPYC 7B13
    Memory: 28.15 GB / 62.79 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.10.5 - ~/.nvm/versions/node/v20.9.0/bin/pnpm
  npmPackages:
    vite: ^4.4.9 => 4.5.0 
    vitest: ^0.34.6 => 0.34.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
1. Please, use the latest Vite and Vitest version
2. Vitest is not responsible for rendering your code - please open an issue with sufficient reproduction in Svelte repo
