### ISSUE TITLE
Istanbul Coverage: "Error: Invalid file coverage object, missing keys"

### ISSUE THREAD

**Issue by DotCoyote** [vitest-dev/vitest#4668]
### Describe the bug

When running tests, the tests succeed, but I get an error which causes the pipeline to fail:

```bash
Error: Invalid file coverage object, missing keys, found:/_git/vitest-coverage-issue/src/types/category-nodes.ts
```

This is the configuration:

```ts
/// <reference types="vitest" />
/// <reference types="vite/client" />
import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
// @ts-ignore
import path from 'path';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      fs: require.resolve('rollup-plugin-node-builtins'),
      '@': path.resolve(__dirname, './'),
    },
  },
  test: {
    globals: true,
    environment: 'jsdom',
    coverage: {
      reporter: ['text', 'json', 'html', 'cobertura'],
      provider: 'istanbul', // or 'c8',
      exclude: [path.resolve(__dirname, '../test-utils')],
    },
    setupFiles: path.resolve(__dirname, 'setup-tests.ts'),
  },
});
```

It seems to be an istanbul-related issue, though. With c8 at least there's no error.

### Reproduction

https://github.com/DotCoyote/vitest-coverage-issue

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 208.70 MB / 32.00 GB
    Shell: 5.9 - /opt/homebrew/bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.10.5 - /opt/homebrew/bin/pnpm
    bun: 1.0.13 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 119.1.60.118
    Chrome: 119.0.6045.199
    Edge: 119.0.2151.97
    Safari: 17.1
    Safari Technology Preview: 17.4
  npmPackages:
    @vitejs/plugin-react: 4.2.1 => 4.2.1 
    @vitest/coverage-istanbul: 1.0.1 => 1.0.1 
    @vitest/coverage-v8: ^1.0.1 => 1.0.1 
    @vitest/ui: 1.0.1 => 1.0.1 
    vitest: 1.0.1 => 1.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
I can reproduce this with the provided setup. However after generating new lockfile this issue does not happen. Maybe some transitive dependency had a bug and is already fixed?

@DotCoyote could you try following in your environment:

- `rm -rf yarn.lock node_modules`
- `yarn`
- `yarn test`

**Comment by DotCoyote** [comment]
That  did it, thank you! 🙌
