### ISSUE TITLE
vitest freezes when extending a test and testTimeout occurs

### ISSUE THREAD

**Issue by emcell** [vitest-dev/vitest#4669]
### Describe the bug

vitest freezes when I extend a test like this:

```typescript
import { describe, test } from 'vitest';

interface TestContext {
  context: {
    hello: string;
  };
}

const myTest = test.extend<TestContext>({
  context: async ({}, use) => {
    const context: TestContext['context'] = {
      hello: 'world',
    };
    await use(context);
  },
});

```

and a test timeout occurs:

```typescript
describe('extended test', () => {
  myTest('test-1', async ({ context }) => {
    console.log(context.hello);
    await new Promise<void>((resolve) => setTimeout(resolve, 7000));
  });
});

```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-zgzzy9?file=test%2Fsuite.test.ts

```shell
npm run test:run
```

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: latest => 1.0.1 
    vite: latest => 5.0.5 
    vitest: latest => 1.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by emcell** [comment]
Removing the `await` from the `use(context)` statement solves this issue. 

https://stackblitz.com/edit/vitest-dev-vitest-tzqky9?file=test%2Fsuite.test.ts


But the examples in the docs also await the call of `use()`. https://vitest.dev/guide/test-context.html#test-extend

**Comment by sheremet-va** [comment]
1. `use` should be awaited
2. Why is there a Promise that causes a timeout? If I remove it, everything works fine for me

**Comment by emcell** [comment]
> 1. `use` should be awaited
Ok

> 2. Why is there a Promise that causes a timeout? If I remove it, everything works fine for me
This is my minimal example. I faced the issue caused by a test that didn't finish in 5 seconds. 

My assumption is, that if a test does not finish in time `vitest run` will finish with an error. Instead of this, it freezes forever.

**Comment by JesusTheHun** [comment]
I'm facing the same issue.
In my case I'm using some third-party NAPI so I have little control over the pending operations and their timeout.

**Comment by sheremet-va** [comment]
> My assumption is, that if a test does not finish in time `vitest run` will finish with an error. Instead of this, it freezes forever.

I see now, you reproduction also freezes it for me. Looks like something is up with fixtures resolution when test is failing due to a timeout
