### ISSUE TITLE
Vitest 1.0.1 breaks mocked constructors due to unmocked getters

### ISSUE THREAD

**Issue by matanui159** [vitest-dev/vitest#4676]
### Describe the bug

Calling a constructor that has been auto-mocked with `vi.mock` will access all its getters, which will fail if the getters depend on anything from the constructor (which is not run due to being mocked).

This seems to have been caused by https://github.com/vitest-dev/vitest/pull/4564 since the mocked constructor now makes a copy of all properties, which will access getters. This seems to stem from the fact that `vi.mock` will not mock getters, which was a problem in previous versions, but now mocked constructors are completely broken unless you manually mock out every getter using `spyOn`.

### Reproduction

I have made a repo to reproduce the issue here: https://github.com/matanui159/vitest-bug
Run `yarn test` to see this error:
```
 FAIL  src/bar.spec.js > Bar
TypeError: Cannot read properties of undefined (reading 'length')
 ❯ t.get nameLength [as nameLength] src/foo.js:3:26
      1| export class Foo {
      2|     get nameLength() {
      3|         return this.name.length;
       |                          ^
      4|     }
      5| 
 ❯ new Bar src/bar.js:5:20
 ❯ src/bar.spec.js:7:5
```

### System Info

```shell
System:
    OS: macOS 14.1.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 14.17 GB / 64.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.16.1 - ~/Library/pnpm/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/Library/pnpm/npm
    pnpm: 8.6.10 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 119.0.6045.199
    Chrome Canary: 121.0.6167.0
    Edge: 119.0.2151.97
    Safari: 17.1.2
  npmPackages:
    vitest: ^1.0.1 => 1.0.1 
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Hi, thanks for reporting the issue and providing a repro!
Indeed, this could be a quite bad regression. I made a PR here https://github.com/vitest-dev/vitest/pull/4677 and hopefully this will be fixed soon.
