### ISSUE TITLE
Yarn PnP (`nodeLinker: pnp`) throws an error of `MISSING DEP  Can not find dependency 'vite' `

### ISSUE THREAD

**Issue by cmark1302** [vitest-dev/vitest#4678]
### Describe the bug

yarn run vitest

Noticing below error although I added vite as devDependency

MISSING DEP  Can not find dependency 'vite'

### Reproduction

yarn run vitest (with 1.0.1)

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 201.78 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 3.6.0 - /usr/local/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    Watchman: 2023.02.06.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 119.0.6045.199
    Edge: 119.0.2151.97
    Safari: 17.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by eunsukimme** [comment]
Same issue here. Downgrading vitest to `0.34.6` was worked for me.

**Comment by AriPerkkio** [comment]
How do I reproduce this? Tried with following steps without failures:

```sh
$ mkdir yarn-repro
$ cd yarn-repro/

$ yarn -v
3.6.0
$ node -v
v18.17.1

$ yarn init -y
$ yarn add --dev vitest

$ mkdir tests
$ echo -e "import { test } from 'vitest';\n\ntest('repro', () => {});\n" > tests/repro.test.ts

$ open package.json
# Modify manually
+  "scripts": {
+    "test": "vitest"
+  }


$ yarn test
>  DEV  v1.0.1 /x/repro/yarn-repro
> 
>  ✓ tests/repro.test.ts (1)
>    ✓ repro
> 
>  Test Files  1 passed (1)
>       Tests  1 passed (1)
>    Start at  09:44:13
>    Duration  131ms (transform 17ms, setup 0ms, collect 12ms, tests 1ms, environment 0ms, prepare 34ms)
> 
> 
>  PASS  Waiting for file changes...
>        press h to show help, press q to quit
```

**Comment by koistya** [comment]
Downgrading to `~1.0.0-beta.4` — the last working version for me.

**Comment by cmark1302** [comment]
@AriPerkkio I was able to reproduce this issue with yarn PnP. 

`nodeLinker: pnp`

**Comment by cmark1302** [comment]
possible fix https://github.com/vitest-dev/vitest/pull/4657

**Comment by AriPerkkio** [comment]
@cmark1302 does the latest `1.0.2` fix this issue for you?

**Comment by AriPerkkio** [comment]
Fixed by https://github.com/vitest-dev/vitest/pull/4657
