### ISSUE TITLE
unhandled error with browser tests and modified `base`

### ISSUE THREAD

**Issue by alexdulin** [vitest-dev/vitest#4686]
### Describe the bug

Browser testing does not work when using a non-default `base` setting. When the `base` value is modified, the following error occurs using a minimal `vitest.config.ts`

```ts
import { defineConfig } from 'vitest/config';

export default defineConfig({
  base: '/example/',
  test: {
    browser: {
      enabled: true,
      headless: true,
      name: 'firefox',
      provider: 'playwright',
    }
  }
})
```

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Reload Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Vitest failed to load "vitest/utils" after 10 retries.
 ❯ ../../../../../__vitest_browser__/index-JmUxqpfn.js:958:36
 ❯ async* ../../../../../__vitest_browser__/index-JmUxqpfn.js:950:4

Caused by: TypeError: error loading dynamically imported module: http://localhost:5173/@id/vitest/utils
```

Removing the `base` setting, or setting it to an empty string, makes the error no longer occur.

### Reproduction

This minimal example demonstrates the issue. Run `npm install; npm test` to cause the error. Remove the `base` configuration option in `vitest.config.ts` to make the error go away.
 
[vitest-browser-base-bug.zip](https://github.com/vitest-dev/vitest/files/13587872/vitest-browser-base-bug.zip)

### System Info

```shell
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 56.16 GB / 62.63 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.5.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.2.2 - ~/.npm-packages/bin/npm
  Browsers:
    Chrome: 120.0.6099.62
  npmPackages:
    @vitest/browser: ^1.0.1 => 1.0.1 
    vite: ^5.0.6 => 5.0.6 
    vitest: ^1.0.1 => 1.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mbland** [comment]
@alexdulin Beat me to this today...I've got the root cause:

- https://github.com/vitejs/vite/pull/5657 made Vite reject URLs outside of config.base.
- This change became part of [Vite 5.0.0-beta.8](https://github.com/vitejs/vite/commits/v5.0.0-beta.8)
- Vitest's dependency on Vite was bumped to ^5.0.0-beta.15 as part of https://github.com/vitest-dev/vitest/pull/4368
- This change became part of [Vitest 1.0.0-beta.5](https://github.com/vitest-dev/vitest/commits/v1.0.0-beta.5)

I've just posted the repo with my minimal demo and notes on how to reproduce these findings: https://github.com/mbland/vitest-utils-browser-import

And FWIW, I went through the steps outlined in the above repo to pinpoint this _after_ reproducing the problem in one of my other projects on:

- macOS: Safari, Chrome, Firefox
- Linux: Chromium, Firefox
- Windows 11: Chrome, Firefox, Edge
- GitHub Actions + Linux: Chrome

I'm happy to try to take a stab at a PR myself in the next day or two, if I'm able to figure out a good way to fix it before anyone else does.

**Comment by sheremet-va** [comment]
> I'm happy to try to take a stab at a PR myself in the next day or two, if I'm able to figure out a good way to fix it before anyone else does.

I think we just need to pass down `base` to `importId`:

https://github.com/vitest-dev/vitest/blob/640881a5942892636aaaeef3b5844a25d9932878/packages/browser/src/client/utils.ts#L1

**Comment by mbland** [comment]
> I think we just need to pass down `base` to `importId`:
> 
> https://github.com/vitest-dev/vitest/blob/640881a5942892636aaaeef3b5844a25d9932878/packages/browser/src/client/utils.ts#L1

Cool. I'd traced through the code and wondered if passing `base` there was the right approach, so I'll give that a try.

**Comment by hi-ogawa** [comment]
I wonder if using `base` config is genuinely required to run Vitest in your current setup.
If `base` config is simply coming from the shared `vite.config.ts` used for main Vite app and disabling it during Vitest is acceptable, then using `process.env.VITEST` to change this option might be a quick workaround, for example:

```ts
export default defineConfig({
  base: process.env.VITEST ? undefined : '/example/',
  test: {
    browser: {
      enabled: true,
      headless: true,
      name: 'firefox',
      provider: 'playwright',
    }
  }
})
```

**Comment by mbland** [comment]
FWIW, I've also updated the test in my demo showing how the workaround will timeout when opening a local page prefixed with `config.base`: https://github.com/mbland/vitest-utils-browser-import/blob/87eb6a278b9a732da6f3d70f9ec64796d66d0c37/demo.test.js#L1-L12
