### ISSUE TITLE
Suddenly can't run tests: "Error: Cannot merge config in form of callback"

### ISSUE THREAD

**Issue by oasjohn** [vitest-dev/vitest#4687]
### Describe the bug

I've been running tests and builds for months, but haven't modified vite, vitest, or any written tests since my last build/release cycle. Today, I started getting this error when running npm run test:all, which is just a script that calls "vitest --run".

Actual builds and debug builds still work and operate fine. But vitest is choking. Note 'xxxxxx\xxxxxx' is just my obfuscated project path.

```
failed to load config from D:\Projects\xxxxxx\xxxxxx\vitest.config.js

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Cannot merge config in form of callback
    at mergeConfig (D:\Projects\xxxxxx\xxxxxx\node_modules\vite\dist\node-cjs\publicUtils.cjs:3487:15)
    at Object.<anonymous> (D:\Projects\xxxxxx\xxxxxx\vitest.config.js:98:58)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object._require.extensions.<computed> [as .js] (file:///D:/Projects/xxxxxx/xxxxxx/node_modules/vite/dist/node/chunks/dep-68d1a114.js:66347:24)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at loadConfigFromBundledFile (file:///D:/Projects/xxxxxx/xxxxxx/node_modules/vite/dist/node/chunks/dep-68d1a114.js:66355:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

My vitest.config.js looks like this:

```
import { mergeConfig } from 'vite'
import { resolve } from 'path'
import { defineConfig } from 'vitest/config'
import Vue from '@vitejs/plugin-vue'
import viteConfig from './vite.config'

export default mergeConfig(viteConfig, defineConfig({
  plugins: [Vue()],
  test: {
    globals: true,
    environment: 'jsdom',
    coverage: {
      all: true,
      skipFull: true
    },
    threads: false
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
      '@@': resolve(__dirname, './src/components'),
      vue: 'vue/dist/vue.esm-bundler.js',
      '@vue/runtime-dom': '@vue/runtime-dom/dist/runtime-dom.esm-bundler.js'
    }
  }
}))

```

This is all on Windows, and I suspect something system-wide as I can even roll back to earlier code versions and they all fail with the same error, even though they have been previously tested and released.

The other wrinkle to this is that vitest fails with the same error when I use github actions to build and test. So it fails on their servers, too.

I've tried downgrading node as well. No joy.
Any suggestions would be appreciated.

### Reproduction

I have no idea how to reproduce this.

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 3950X 16-Core Processor
    Memory: 34.04 GB / 63.94 GB
  Binaries:
    Node: 16.20.2 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.97)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-vue: ^4.0 => 4.5.1
    @vitest/coverage-c8: ^0.25.7 => 0.25.8
    @vitest/ui: ^0.26.2 => 0.26.3
    vite: ^4.0 => 4.5.1
    vitest: ^0.25.2 => 0.25.8
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Looks like your `vite.config` returns a function (so config is defined in the form of `defineConfig(() => {})`). Documentation has an example on how to handle it (https://vitest.dev/config/#configuration):

```
import { defineConfig, mergeConfig } from 'vitest/config'
import viteConfig from './vite.config'

export default defineConfig(configEnv => mergeConfig(
  viteConfig(configEnv),
  defineConfig({
    test: {
      exclude: ['packages/template/*'],
    },
  })
))
```
