### ISSUE TITLE
`coverage.thresholds.autoUpdate` fails when defineConfig takes a function

### ISSUE THREAD

**Issue by wjperkins** [vitest-dev/vitest#4695]
### Describe the bug

When using `coverage.thresholds.autoUpdate` in a config defined with a function, as shown in https://vitejs.dev/config/#conditional-config, e.g:
```
export default defineConfig((config) => {
  // do something with config...

  return {
    test: {
      coverage: {
        enabled: true,
        provider: 'istanbul',
        thresholds: {
          lines: 50,
          autoUpdate: true,
        },
      },
    },
  };
});
```
The tests run successfully, and the coverage report is generated. However, it fails to update the coverage threshold and returns an unhandled error `MagicastError: Casting "ArrowFunctionExpression" is not supported`. 

If the config is defined with a simple object rather than a function, the autoUpdate behaviour works as expected.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-zwszje?file=vite.config.ts

### System Info

```shell
System:                                                      
    OS: Windows 10 10.0.19045                                  
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 5.18 GB / 15.39 GB                                 
  Binaries:                                                    
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE            
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (119.0.2151.97)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @vitejs/plugin-react: ^4.2.1 => 4.2.1
    @vitest/coverage-v8: ^1.0.1 => 1.0.1
    @vitest/ui: ^1.0.1 => 1.0.1
    vite: ^5.0.6 => 5.0.6
    vitest: ^1.0.1 => 1.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Magicast doesn't support arrow functions: https://github.com/unjs/magicast/issues/37. We'll need to add those first.

```js
import { parseModule } from "magicast";

const mod = parseModule(`
import { defineConfig } from "vitest/config";

export default defineConfig((config) => ({
  test: {
    coverage: {
      enabled: true,
      provider: "istanbul",
      thresholds: {
        autoUpdate: true,
        lines: 1,
      },
    },
  },
}));
`);

console.log(mod.exports.default.$args[0]);
```

```js
> file:///root/repro/node_modules/.pnpm/magicast@0.3.2/node_modules/magicast/dist/index.mjs:8529
>       throw new MagicastError(`Casting "${node.type}" is not supported`, {
>             ^
> 
> MagicastError: Casting "ArrowFunctionExpression" is not supported
> 
>   2 | import { defineConfig } from "vitest/config";
>   3 | 
>   4 | export default defineConfig((config) => ({
>                                   ^
>   5 |   test: {
>   6 |     coverage: {
>   7 |       enabled: true,
> 
>     at proxify (file:///root/repro/node_modules/.pnpm/magicast@0.3.2/node_modules/magicast/dist/index.mjs:8529:13)
>     at Object.get (file:///root/repro/node_modules/.pnpm/magicast@0.3.2/node_modules/magicast/dist/index.mjs:8286:18)
>     at Object.get (file:///root/repro/node_modules/.pnpm/magicast@0.3.2/node_modules/magicast/dist/index.mjs:8036:26)
>     at file:///root/repro/magicast-repro.mjs:20:38
```
