### ISSUE TITLE
Browser Mode: error when importing types into JS files

### ISSUE THREAD

**Issue by gruhn** [vitest-dev/vitest#4704]
### Describe the bug

TypeScript allows importing types into JS files to reference them in comments:

```ts
// ./my-type.ts
export type ImportedType = number
```
```js
// ./basic.js
import { ImportedType } from './my-type'

/**
 * @param {ImportedType} n
 * @return {ImportedType}
 */
export const squared = (n) => n * n
```
This is useful as an intermediate step of a TypeScript migration. When testing `squared` now, Vitest usually does not complain. However, in browser mode I get an error: 
```
  ✘ [ERROR] No matching export in "src/my-type.ts" for import "ImportedType"

    src/basic.js:1:9:
      1 │ import { ImportedType } from './my-type'
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-ct3gzh?file=vite.config.ts

I changed the default StackBlitz setup only in a few ways:

 * rename `basic.ts` to `basic.js` and add `import { ImportedType } from './my-type'`
 * add config options `allowJs: true` to `tsconfig.json`
 * enable browser mode in `vite.config.ts` (tests pass without errors if you disable browser mode)

### System Info
It's just the output I get on StackBlitz:

```shell
  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/browser: ^1.0.2 => 1.0.2 
    @vitest/ui: latest => 1.0.2 
    vite: latest => 5.0.6 
    vitest: latest => 1.0.2 
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Oh, ok, I see that it is a js file, you can't use `import type` there. I am not sure where it's stated that you can use static imports to import TS types, but as far as I know, you need to use dynamic import in comments to do that (example in [SvelteKit](https://github.com/sveltejs/kit/blob/master/packages/kit/src/exports/node/index.js)):

```ts
/**
 * @param {import('./my-type').ImportedType} n
 * @return {import('./my-type').ImportedType}
 */
```

I think to remove duplication you can do something like this:

```ts
/**
 * @typedef {import('./my-type').ImportedType} ImportedType
 */
```

And reference `ImportedType` as usual.

**Comment by gruhn** [comment]
> I am not sure where it's stated that you can use static imports to import TS types

Not sure where it's explicitly stated either, but it seems to be supported by editors. Including StackBlitz:

<img width="500" alt="Screenshot 2023-12-08 at 16 02 33" src="https://github.com/vitest-dev/vitest/assets/26570572/bd4dce6e-ec73-46da-a032-f5ef86390808">

<img width="500" alt="Screenshot 2023-12-08 at 16 02 50" src="https://github.com/vitest-dev/vitest/assets/26570572/f6c0a8b1-22de-479e-8c37-925f66e5a628">

Also as I said, in non-browser-mode Vitest does not complain.

**Comment by sheremet-va** [comment]
> it seems to be supported by editors

The editor doesn't know what runtime you will be using. It expects your code to be transformed and run somewhere according to your tsconfig (it means that your tsconfig is not correctly configured). In this particular case, it expects that this import will be just stripped during processing because tsc knows it's a type-only import (but esbuild doesn't know that because it doesn't do type analysis). There is a billion different combinations that I will not explain here.

> Also as I said, in non-browser-mode Vitest does not complain.

This is a bug, Vitest should complain there. And it will throw an error when we get back to it.

I already explained how Vitest expects you to write this use case, so I am closing the issue. I wish you a great day!
