### ISSUE TITLE
safaridriver.start() conflicts with webdriverio.remote()

### ISSUE THREAD

**Issue by mbland** [vitest-dev/vitest#4706]
### Describe the bug

safaridriver.start() maintains a static reference to a safaridriver instance, and will fail with the following message if start() is called again before stop():

```text
Error: There is already a Safaridriver instance running on port undefined!
```

packages/browser/node/providers/webdriver.ts calls safaridriver.start() directly, and then immediately imports and calls webdriverio.remote(). This call also eventually calls safaridriver.start(), producing the above error.

I already have a tested fix ready to turn into a PR here: https://github.com/mbland/vitest/commit/64b9bbda2f71620e20c26dc38872712042da131a

### Reproduction

On macOS:

```sh
git clone https://github.com/vitest-dev/vitest.git
cd vitest
git reset --hard v1.0.2
pnpm i
pnpm build
cd test/browser
npx vitest --run --browser.name=safari
```

You'll see the stack trace pointing to the webdriverio.remote() call leading to the second safaridriver.start() call:

```text
Error: There is already a Safaridriver instance running on port undefined!
 ❯ start ../../node_modules/.pnpm/safaridriver@0.1.0/node_modules/safaridriver/dist/index.js:26:15
 ❯ startWebDriver ../../node_modules/.pnpm/@wdio+utils@8.22.0/node_modules/@wdio/utils/build/node/startWebDriver.js:66:25
 ❯ process.processTicksAndRejections node:internal/process/task_queues:95:5
 ❯ WebDriver.newSession ../../node_modules/.pnpm/webdriver@8.22.1/node_modules/webdriver/build/index.js:18:31
 ❯ remote ../../node_modules/.pnpm/webdriverio@8.22.1_typescript@5.2.2/node_modules/webdriverio/build/index.js:45:22
 ❯ WebdriverBrowserProvider.openBrowser ../../packages/browser/dist/providers.js:81:26
     79|     }                                                                  
     80|     const { remote } = await import('webdriverio');
     81|     this.cachedBrowser = await remote({
       |                          ^
     82|       ...this.options,
     83|       logLevel: "error",                                               
 ❯ WebdriverBrowserProvider.openPage ../../packages/browser/dist/providers.js:109:29
 [ ...snip... ]
```

### System Info

```shell
System:
    OS: macOS 14.1.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 8.75 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nodenv/versions/20.10.0/bin/node
    npm: 10.2.3 - ~/.nodenv/versions/20.10.0/bin/npm
    pnpm: 8.11.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.71
    Safari: 17.1.2
  npmPackages:
    @vitest/browser: workspace:* => 1.0.2
    vitest: workspace:* => 1.0.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> I already have a tested fix ready to turn into a PR here: https://github.com/mbland/vitest/commit/64b9bbda2f71620e20c26dc38872712042da131a

I don't see an open PR in this repo 🤔

**Comment by mbland** [comment]
@sheremet-va Just rebased to the most recent `main` and filed #4863.
