### ISSUE TITLE
Yarn workspaces - unable to "yarn test" without watch enabled

### ISSUE THREAD

**Issue by UTGuy** [vitest-dev/vitest#4708]
### Describe the bug

Works... no watch mode

```shell 
yarn vitest run
```

Doesn't work  - watch mode enabled (see setup below)
```shell
yarn test
```

### Reproduction

Set `package.json`

```json
{
  "scripts": {
    "test": "vitest run"
  }
}
```

```shell
yarn test
```

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (12) arm64 Apple M2 Pro
    Memory: 34.19 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - /private/var/folders/tl/rmg6cf7s50g32zy16r9zcfyw0000gp/T/xfs-9fef2698/node
    Yarn: 4.0.2 - /private/var/folders/tl/rmg6cf7s50g32zy16r9zcfyw0000gp/T/xfs-9fef2698/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Browsers:
    Chrome: 120.0.6099.62
    Safari: 17.0
```

### Used Package Manager

yarn (berry)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Hi, I tested `yarn test` with very simple setup on stackblitz and I couldn't reproduce the issue:

https://stackblitz.com/edit/vitest-dev-vitest-pbtrfk?file=package.json

```sh
❯ yarn test
yarn run v1.22.19
$ vitest run

 RUN  v1.0.4 /home/projects/vitest-dev-vitest-pbtrfk

 ✓ test/suite.test.ts (3)
 ✓ test/basic.test.ts (3)

 Test Files  2 passed (2)
      Tests  6 passed (6)
   Start at  13:22:08
   Duration  2.61s (transform 62ms, setup 0ms, collect 93ms, tests 7ms, environment 0ms, prepare 423ms)

✨  Done in 8.29s.
```

I suppose the behavior might be different due to the use of workspaces. Can you provide a reproduction to make investigation easier for maintainers?

**Comment by hi-ogawa** [comment]
Good catch. I'm not familiar with yarn, so I would still appreciate if you can provide an example repo (package.json? corepack? etc...). Also I noticed you didn't include Vitest version. At least, that would be probably important information for maintainers.

I've downloaded stackblitz repro locally and tested with corepack/yarn and it looks working on my side. Could this be still missing some crucial reproduction steps?

```sh
$ corepack use yarn@4
Installing yarn@4.0.2 in the project...

➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: · Done with warnings in 0s 213ms

$ yarn --version
4.0.2

$ yarn test

 RUN  v1.0.4 /home/hiroshi/Downloads/vitest-yarn-test

 ✓ test/suite.test.ts (3)
 ✓ test/basic.test.ts (3)

 Test Files  2 passed (2)
      Tests  6 passed (6)
   Start at  23:22:28
   Duration  969ms (transform 38ms, setup 1ms, collect 47ms, tests 8ms, environment 0ms, prepare 246ms)
```

**Comment by UTGuy** [comment]
Yeah, I tried setting this up but was unable to reproduce it myself... the crazy part is I rebuild my (dev) Container and today its working?? 

Here was my [test example](https://codesandbox.io/p/devbox/m5h43x?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq0zv90m00063b6jrguz6sm4%2522%252C%2522sizes%2522%253A%255B64.42934782608695%252C35.57065217391305%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq0zv90m00023b6jw0l4soec%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq0zv90m00033b6jiq8c28nd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq0zv91k000i3b6jjkiletpd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq0zv90m00023b6jw0l4soec%2522%253A%257B%2522id%2522%253A%2522clq0zv90m00023b6jw0l4soec%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clq0zv90m00033b6jiq8c28nd%2522%253A%257B%2522id%2522%253A%2522clq0zv90m00033b6jiq8c28nd%2522%252C%2522activeTabId%2522%253A%2522clq0zw5xp00843b6jylmk7g1l%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq0zw5xp00843b6jylmk7g1l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clq0zw5zf000mefer8nngf733%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clq0zxk6700co3b6jwpglkn0h%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clq0zv91k000i3b6jjkiletpd%2522%253A%257B%2522id%2522%253A%2522clq0zv91k000i3b6jjkiletpd%2522%252C%2522tabs%2522%253A%255B%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) if you're curious
