### ISSUE TITLE
@rollup/rollup-linux-x64-gnu module not found in Linux environment

### ISSUE THREAD

**Issue by zhaoyueer** [vitest-dev/vitest#4726]
### Describe the bug

I am currently using vitest version 0.34.4 and encountering an issue where the @rollup/rollup-linux-x64-gnu module cannot be found in a Linux environment. An hour ago, rollup released version 4.8.0, which seems to be related to this issue.

### Reproduction

-

### System Info

```shell
"vitest": "^0.34.4"
"@vitest/ui": "^0.34.6"
Linux
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nickytonline** [comment]
Upgrading to vitest 1.0.4 fixed the issue for me. I was getting the error with 1.0.3.

**Comment by immutable-pro** [comment]
1.0.4 is still causing the issue for me.

**Comment by sheremet-va** [comment]
I don't think this is something we can fix on our side. Please, open an issue in [rollup repository](https://github.com/rollup/rollup) if your platform is not support by rollup.
