### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'split') - filename is "undefined"

### ISSUE THREAD

**Issue by SDanDyS** [vitest-dev/vitest#4727]
### Describe the bug

My coverage file has files which are named "undefined.vue". I am debugging to find out which file this could be and whether the problem is something known to vitest or that it's simply my project which is causing this bug. There is a solution to resolve this problem which would be in `node_modules/@vitest/coverage-istanbul/dist/provider.js`. This way we can remove files which for some reason end up with undefined/null filenames.

![image](https://github.com/vitest-dev/vitest/assets/38207747/942d3212-46bd-4cd3-9eb7-2c3323bc5d5b)

The following function can resolve this error (the function already exists, I merely added a check):

```
function removeQueryParameters(filename) {
    if (filename) {
        return filename.split("?")[0];
    }
}
```

### Reproduction

-

### System Info

```shell
System:
    OS: Linux 6.2 Alpine Linux
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-1235U
    Memory: 4.54 GB / 15.30 GB
    Container: Yes
    Shell: 1.36.1 - /bin/ash
  Binaries:
    Node: 18.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
  npmPackages:
    @vitest/coverage-istanbul: 0.34.1 => 0.34.1 
    vitest: 0.33.0 => 0.33.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You need to use the same version of Vitest for the coverage package.

**Comment by SDanDyS** [comment]
Hi!

I tried upgrading both to 0.34.1 (and 0.33.0), unfortunately the error remained the same. I have done some research and concluded it's because SourceMap.sources is empty.

```
SourceMap {
  version: 3,
  mappings: '',
  names: [],
  sourceRoot: undefined,
  sources: [],
  sourcesContent: [],
  file: '/usr/src/app/path/placeholder.vue'
} 
```

Any idea on why this could be the case? Excluding it in the vitest.config.ts doesn't work either.

**Comment by sheremet-va** [comment]
Sorry, we don't support older versions. The reason can be anything.

**Comment by sheremet-va** [comment]
Latest version is 1.0.4

**Comment by sheremet-va** [comment]
Yes, correct. I don't know if other packages you listed support Vitest 1.0, so I cannot help with that.

**Comment by SDanDyS** [comment]
Still the same error. Unfortunately I do not know how to create a reproducable problem since I do not know _why_ the file sources remain empty. Hopefully someone stumbles across this question and can provide more insight.
