### ISSUE TITLE
pretty-format dependency missing

### ISSUE THREAD

**Issue by sbaechler** [vitest-dev/vitest#473]
### Describe the bug

When I run the tests I am getting the error:

```
node_modules/vitest/dist/index.d.ts:1:41 - error TS2307: Cannot find module 'pretty-format' or its corresponding type declarations.

1 import { OptionsReceived, Plugin } from 'pretty-format';
```

The module `pretty-format` is used in the library but it is only included in the package.json as a dev dependency.

### Reproduction

`pretty-format` is used in these locations:

https://github.com/vitest-dev/vitest/search?q=pretty-format

This is the package.json:
https://github.com/vitest-dev/vitest/blob/main/packages/vitest/package.json

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 199.36 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Brave Browser: 96.1.33.106
    Firefox: 90.0.2
    Safari: 15.1
  npmPackages:
    @vitejs/plugin-react: ^1.0.7 => 1.1.4 
    vite: ^2.7.2 => 2.7.10 
    vitest: ^0.0.124 => 0.0.124
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
https://github.com/vitest-dev/vitest/pull/474#issuecomment-1007450272

**Comment by sbaechler** [comment]
Ok, now it worked. I did update the dependency before creating the issue which did not help but after removing node_modules and reinstalling it worked.

Thanks for the quick reply.
