### ISSUE TITLE
Vitest 1.0.2 broke happy-dom with msw + axios

### ISSUE THREAD

**Issue by marioleed** [vitest-dev/vitest#4730]
### Describe the bug

I upgraded vitest to latest version, 1.0.2, and my tests using msw started to crash with the following message:

>⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
>
>Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.
>
>⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
>TypeError: response.body.getReader is not a function
 ❯ XMLHttpRequestController.respondWith node_modules/.pnpm/@mswjs+interceptors@0.25.13/node_modules/@mswjs/interceptors/lib/node/chunk-V3QPQ45S.mjs:452:36
 ❯ xhrRequestController.onRequest node_modules/.pnpm/@mswjs+interceptors@0.25.13/node_modules/@mswjs/interceptors/lib/node/chunk-V3QPQ45S.mjs:727:39
>
>This error originated in "tests/tests.test.ts" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
The latest test that might've caused the error is "request is ok". It might mean one of the following:
>- The error was thrown, while Vitest was running this test.
>- This was the last recorded test before the error was thrown, if error originated after test finished its execution.
>⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Same error using latest version 1.0.4.

It seems to have something to do with #4671.
Also https://github.com/mswjs/msw/issues/1816 seems to be similar.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-wlzbz8?view=editor

Try it with vitest 1.0.1 - ✅ works
Try it with vitest >1.0.2 - ❌ breaks

### System Info

```shell
Latest package versions (though vitest breaks from 1.0.2).

My local environment:

  System:
    OS: macOS 14.1.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.51 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.2.5 - /opt/homebrew/bin/npm
    pnpm: 8.12.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Brave Browser: 120.1.61.100
    Chrome: 119.0.6045.159
    Safari: 17.1.2
  npmPackages:
    @vitejs/plugin-basic-ssl: 1.0.2 => 1.0.2 
    @vitejs/plugin-react: 4.2.1 => 4.2.1 
    @vitest/coverage-v8: 1.0.4 => 1.0.4 
    vite: 5.0.7 => 5.0.7 
    vitest: 1.0.4 => 1.0.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This happens because Vitest now respects happy-dom's `Request` and `Response`, and it uses Node.js `Readable` stream for a body that doesn't support `getReader`.

I'd say this is an error on happy-dom side and not Vitest.

**Comment by marioleed** [comment]
Ok, I'll open an issue at happy-dom. Thanks.
