### ISSUE TITLE
Make it possible to override pool and poolOptions per workspace

### ISSUE THREAD

**Issue by ArtemZag** [vitest-dev/vitest#4731]
### Clear and concise description of the problem

As a developer I would like to have possibility to customize the following configuration parameters per each workspace:
- singleFork
- singleThreads
- pool
- poolOptions

Actually pools implementation already assumes it can be configured differently, it's just needed to pass it down correctly.

### Suggested solution

Extend list of configuration parameters supported by workspace level.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
> * poolOptions (including "threads.isolate")

This cannot be inherited because for performance reasons the pool is initiated for Vitest process, not a workspace project (it's the whole reason why we have workspace support). This is how it worked since workspaces were introduced.

The only config options that _can_ be inherited:

- pool
- poolOptions.forks.singleFork
- poolOptions.threads.singleThread

**Comment by sheremet-va** [comment]
I think it is a bug. To me, this sounds like we missed this in the review, I did not expect that the mentioned options were not inherited.

**Comment by AriPerkkio** [comment]
Looks like `pool` is already supported on workspace project level:
- https://stackblitz.com/edit/vitest-dev-vitest-z1zwko?file=vitest.workspace.ts

But is `pool` ignored when it's defined on root level? https://stackblitz.com/edit/vitest-dev-vitest-jyrgtp?file=vite.config.ts

**Comment by sheremet-va** [comment]
> But is `pool` ignored when it's defined on root level? https://stackblitz.com/edit/vitest-dev-vitest-jyrgtp?file=vite.config.ts

Yes, this is consistent with [the documentation](https://vitest.dev/guide/workspace.html#configuration): 

> None of the configuration options are inherited from the root-level config file

**Comment by sheremet-va** [comment]
> I would have expected it to be used similarly as `reporters` or `coverage` as it was ignored on workspace project level.
> 
> 
> 
> Does this eventually mean that when using workspaces, it is not possible to configure `poolOptions.<pool>.isolate` at all? Not at project level, not at root level?

Isolate is initiated only on root level because pool is looking only at root level config. But singleFork/singleThread is taken from project config because it is accessed during tests run, not during pool initialization (it's accessed both there, but it's arguably more important during tests run).

**Comment by AriPerkkio** [comment]
Just to confirm one last time - configuration below is the goal, @sheremet-va?

```ts
import { defineWorkspace } from "vitest/config";

export default defineWorkspace([
  {
    test: {
      name: "First",
      pool: "threads", // or forks, vmThreads
      poolOptions: {
        threads: {
          singleThread: true,
        },
        forks: {
          singleFork: true,
        },
        vmThreads: {
          singleThread: true,
        }
      },
    },
  },
]);
```

**Comment by sheremet-va** [comment]
Yes, these are the only options that are affected as far as I know. (Maybe except `vmThreads`?)

**Comment by AriPerkkio** [comment]
Supporting `pool` is easy. `singleThread/singleFork` however is a bit tricky. We need to be careful when initializing Tinypool in "single thread" mode. Currently it is done based on root project configuration. But if there's any project that disables single threading, the pool cannot run it in multiple threads as pool was already configured to use a single thread. 

When configuring Tinypool we'll need to check root level configuration and each project's configuration. Something like:

```ts
// Pool can be configured as "single thread" only if every project is configured as single thread
const isRootSingleThread = ctx.config.poolOptions?.threads?.singleThread
const isAllProjectsSingleThread = ctx.projects.every(project => project.config.poolOptions?.threads?.singleThread)
const singleThread = // ummm...

...

if (singleThread) {
  options.concurrentTasksPerWorker = 1
  options.maxThreads = 1
  options.minThreads = 1
}
```

**Comment by sheremet-va** [comment]
> Supporting `pool` is easy. `singleThread/singleFork` however is a bit tricky. We need to be careful when initializing Tinypool in "single thread" mode. Currently it is done based on root project configuration. But if there's any project that disables single threading, the pool cannot run it in multiple threads as pool was already configured to use a single thread.
> 
> When configuring Tinypool we'll need to check root level configuration and each project's configuration. Something like:

Not really, we don't need to do that. `singleThread` in Vitest does two things - it makes it so there is only a single worker process and every test is running inside that process one after one. For the usecase described in the issue what people want is to have 4 workers: 3 workers running one test at a time, and the fourth one running several tests at the time with only a module isolation (no context isolation).

**Comment by AriPerkkio** [comment]
Then I think this is actually working already. Typings do not support it but it still works. Also runtime worker/child-process has incorrect pool and poolOptions in its state/ctx, but everything runs fine. Fixing those is quite simple.

Pool name is already resolved from project: 
https://github.com/vitest-dev/vitest/blob/217910bb4f60614fde2843ab84a99bd7fdc00325/packages/vitest/src/node/pool.ts#L61

Single thread is also:

https://github.com/vitest-dev/vitest/blob/217910bb4f60614fde2843ab84a99bd7fdc00325/packages/vitest/src/node/pools/threads.ts#L139

Tested this all with following:
```ts
// <root>/vitest.config.ts
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    pool: "vmThreads",
  },
});

// <root>/vitest.workspace.ts
import { defineWorkspace } from "vitest/config";

export default defineWorkspace([
  {
    test: {
      name: "First",
      include: ["tests/space-rockets.test.ts"],

      pool: "threads",
      poolOptions: {
        threads: { singleThread: true },
      },
    },
  },
  {
    test: {
      name: "Second",
      include: ["tests/math.test.ts"],

      pool: "forks",
      poolOptions: {
        forks: { singleFork: true },
      },
    },
  },
]);
```

Then place loggers here:

https://github.com/vitest-dev/vitest/blob/217910bb4f60614fde2843ab84a99bd7fdc00325/packages/vitest/src/node/pools/threads.ts#L139-L140

https://github.com/vitest-dev/vitest/blob/217910bb4f60614fde2843ab84a99bd7fdc00325/packages/vitest/src/node/pools/child.ts#L159-L160

And we get:

```
 RUN  v1.0.4 /Users/x/vitest-example-project

{
  pool: 'forks',
  singleFork: [
    [
      [WorkspaceProject],
      '/Users/x/vitest-example-project/tests/math.test.ts'
    ]
  ],
  multipleForks: []
}
{
  pool: 'threads',
  singleThreads: [
    [
      [WorkspaceProject],
      '/Users/x/vitest-example-project/tests/space-rockets.test.ts'
    ]
  ],
  multipleThreads: []
}

 ✓ |Second| tests/math.test.ts (2)
 ✓ |First| tests/space-rockets.test.ts (1)

 Test Files  2 passed (2)
      Tests  3 passed (3)

```

**Comment by sheremet-va** [comment]
> Then I think this is actually working already. Typings do not support it but it still works. Also runtime worker/child-process has incorrect pool and poolOptions in its state/ctx, but everything runs fine. Fixing those is quite simple.

Actually, I remembered that we can also have module isolation inside the worker:

https://github.com/vitest-dev/vitest/blob/217910bb4f60614fde2843ab84a99bd7fdc00325/packages/vitest/src/runtime/entry.ts#L36

This worked before the migration, and we should probably make sure it still works now.
