### ISSUE TITLE
Support for async test condition

### ISSUE THREAD

**Issue by JesusTheHun** [vitest-dev/vitest#4740]
### Clear and concise description of the problem

Some suites require some -time consuming- setup and some don't.
One can use `describe.runIf(condition)` to check if the suite should be ran. 

Unfortunately the condition is checked for its truthiness even if it's a function.

```ts
describe.runIf(false)('test name', fn); // OK : won't run.
describe.runIf(() => false)('test name', fn); // KO : will run, because a value of type `function` is truthy.
describe.runIf(async () => false)('test name', fn); // KO : same reason.
```

### Suggested solution

If the condition is a function, call it and use the return value as the run/skip value. If it's a promise, await it.

### Alternative

Right now I have to create a constant that awaits the function in a setup file.
But this means the call is done even when we want to run a single test that does not depend on this condition. And since this call checks a docker database, it means the container has to be up and running even for an independent unit test.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Even if we support a function, it can't support async function because it's just a shorthand for this:
```ts
if (condition) {
  test(...)
} else {
  test.todo(...)
}
```

So you would have to call it like this:

```ts
await describe.runIf(async () => true)(...)
```

**Comment by JesusTheHun** [comment]
What if the collector promisify the suite function and rejects it with a well-known error ?

```ts
describe.runIf(async () => false)('suite name', suiteFn);

// pseudo code for the collector internals
const userCondition = /* () => true */;
const testFunction = new Promise((res, rej) => {
  try {
    const conditionResult = typeof userCondition === 'function' ? await userCondition() : userCondition;
    if (conditionResult === true) {
      res();
      return;
    }

    rej(new SuiteConditionFalse('Condition result is false'));
  } catch (err) {
    rej(new SuiteConditionError('Error during condition function', err));
  }
})

// down the line vitest awaits the collector `testFunction` and run or skip the tests depending on the Promise resolution or rejection
```

**Comment by sheremet-va** [comment]
I don't think this makes any sense to be honest. This function will be called immediately, - you can just do it yourself:

```ts
describe.runIf(await heavyOperation())('...')
```

**Comment by sheremet-va** [comment]
> What if the collector promisify the suite function and rejects it with a well-known error ?

This would also not be possible because collector is sync unless describe function is async and awaited.

**Comment by JesusTheHun** [comment]
> I don't think this makes any sense to be honest. This function will be called immediately, - you can just do it yourself:
> 
> ```ts
> describe.runIf(await heavyOperation())('...')
> ```

This is not what I suggested. This is an IIFE. What I suggested is: 

```ts
describe.runIf(heavyOperation)('...') // We pass the function without invoking it
```

> > What if the collector promisify the suite function and rejects it with a well-known error ?
> 
> This would also not be possible because collector is sync unless describe function is async and awaited.

While not optimal, I don't think this should be view as a blocker.
Also I think it is possible: the `collect` function returns a `Promise<Suite>`. The said promise could resolve once the condition function is settled.

**Comment by sheremet-va** [comment]
>  We pass the function without invoking it

What I am saying is that it will be invoked in place anyway. This is called during test collection.

**Comment by JesusTheHun** [comment]
> > We pass the function without invoking it
> 
> What I am saying is that it will be invoked in place anyway. This is called during test collection.

I understand that, but I fail to see how it is a problem. 

When I execute : `vitest featA --run`, it will only collect the suites involved. If those do not have a condition function that requires the heavy operation, then this heavy function will not occur.

**Comment by sheremet-va** [comment]
> When I execute : `vitest featA --run`, it will only collect the suites involved.

`featA` is a file name, it will only run test files that have this string in their file path. It will collect all tests in those files. If you have heavy operations there in `runIf` (even with proposed idea), it will run them.
