### ISSUE TITLE
Support named export in a CommonJS module in node_modules

### ISSUE THREAD

**Issue by Jinjiang** [vitest-dev/vitest#4745]
### Clear and concise description of the problem

Please don't mind me creating this issue from a discussion https://github.com/vitest-dev/vitest/discussions/1360 to keep on track.

Reproduction
https://github.com/Jinjiang/reproductions/tree/vitest-apollo-20231214

The package in my case is `@apollo/client`. In source code `import { ... } from ...` works. However, when it's written in a file inside `node_modules`, it doesn't work unless using the `import pkg ...` statement.

```ts
// THIS DOESN'T WORK NOW
import { gql } from '@apollo/client';

// THIS WORKS
import pkg from '@apollo/client';
const { gql } = pkg;
```

### Suggested solution

Support named export in CJS package like `@apollo/client`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
This is expected behaviour, this is how Node.js works. To bypass this, you can use [`server.deps.inline`](https://vitest.dev/config/#server-deps-inline) to inline all dependencies in the dependency chain that imports this file.

**Comment by Jinjiang** [comment]
I see. I did a quick trial. Seems adding `server: { deps: { inline: true } }` to the `test` config doesn't help. Not sure what is the proper config to bypass. May I double check that with you? Thanks.

Error log:

```
$ pnpm test

> reproduce@ test /xxx/reproductions
> vitest


 RUN  v1.0.4 /xxx/reproductions


⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Failed to load url @vitest/expect (resolved id: @vitest/expect). Does the file exist?
 ❯ loadAndTransform node_modules/.pnpm/vite@5.0.8/node_modules/vite/dist/node/chunks/dep-uAHLeuC6.js:49374:21
 ❯ ViteNodeServer._transformRequest node_modules/.pnpm/vite-node@1.0.4/node_modules/vite-node/dist/server.mjs:393:16
 ❯ ViteNodeServer._fetchModule node_modules/.pnpm/vite-node@1.0.4/node_modules/vite-node/dist/server.mjs:359:17
 ❯ MessagePort.<anonymous> node_modules/.pnpm/vitest@1.0.4/node_modules/vitest/dist/vendor/index.cAUulNDf.js:60:20

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 Test Files  no tests
      Tests  no tests
     Errors  1 error
   Start at  21:32:25
   Duration  304ms (transform 35ms, setup 0ms, collect 0ms, tests 0ms, environment 0ms, prepare 0ms)

 ELIFECYCLE  Test failed. See above for more details.
```

**Comment by sheremet-va** [comment]
You need to add a dependency that imports `@apollo/client`:

```ts
export default {
  test: {
    server: {
      inline: ['foo']
    }
  }
}
```

**Comment by sheremet-va** [comment]
> It works with the config you provided. Thanks so much.
> 
> May I have one more last question if you don't mind 😅 ? Why it failed with error about `@vitest/expect` when I set `server.deps.inline` as `true`? What happened behind?

https://github.com/vitest-dev/vitest/issues/2806
