### ISSUE TITLE
Allow wildcards in `--project` option

### ISSUE THREAD

**Issue by fubhy** [vitest-dev/vitest#4747]
### Clear and concise description of the problem

When running tests with the `--project` filter option, it'd be great to be able to pass wildcards (e.g. run all test environments for a monorepo package):

```sh
vitest --project effect:*
```

### Suggested solution

Allow simple minimatch patterns in the `--project` option

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Not sure this is a good idea. You can pass down several projects by providing this flag several times already: `--project nameA --project nameB`.

I don't see a world where there are too many projects that you can't pass them down.

**Comment by fubhy** [comment]
I am currently setting up vitest workspaces for our future monorepo for the `effect` organization (https://github.com/Effect-TS/effect)

Since this is essentially a runtime & standard lib that is supposed to run flawlessly in all environments (browsers, edge, node, bun, deno, etc.), we intend to configure it in a way where the same packages are covered by multiple project configs.

For instance:

```sh
// effect package:
effect:node
effect:chromium
effect:edge
...

// @effect/schema package:
@effect/schema:node
@effect/schema:chromium
@effect/schema:edge
...
```

... etc.

I think this illustrates how, with e.g. 10+ packages within the monorepo at some point in the near future, this'd already blow up quite a bit.

With a wildcard, we could then easily run the full test environment range for a single project.

e.g. `vitest --project "@effect/schema:*"`

**Comment by sheremet-va** [comment]
> e.g. `vitest --project "@effect/schema:*"`

Ok, I think we can support this.
