### ISSUE TITLE
Feature Request: `stringMatching(x)` should not return `any` 

### ISSUE THREAD

**Issue by jasonkuhrt** [vitest-dev/vitest#4753]
### Describe the bug

![CleanShot 2023-12-14 at 11 31 39@2x](https://github.com/vitest-dev/vitest/assets/284476/f5158ac8-8723-4f06-a9d0-830848a5dc6b)

### Reproduction

I haven't tried but assume this is how it is on a fresh hello world project.

### System Info

We are TS 5.3.2 right now, and indeed maybe (but I doubt it) the issue is fixed on TS 5.4...

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
https://github.com/vitest-dev/vitest/issues/4543
