### ISSUE TITLE
ESM package export  with wildcards `"./*/*"` errored with "`Failed to load url <package_name>/<some directory>/<module>`"

### ISSUE THREAD

**Issue by xeho91** [vitest-dev/vitest#4761]
### Describe the bug

Hi awesome `vitest` contributors!

Firstly - very important, a token of gratitude and appreciation for this awesome open-source testing tool. You guys are the best. **Kudos** ❤️ 

---

## Description

I am hacking around by setting up a template monorepo _(using pnpm workspace)_ for a back-end project.

I have a separate library Node.js internal ESM package for the database, and has the following setup in the `package.json`:

```json
{
	"type": "module",
	"name": "@package/database",
	"engines": {
		"node": ">=20"
	},
	"files": [
		"/lib"
	],
	"exports": {
		"./*": {
			"types": "./lib/*.d.ts",
			"import": "./lib/*.js"
		},
		"./*/*": {
			"types": "./lib/*/*.d.ts",
			"import": "./lib/*/*.js"
		}
	}
}
```

I'm trying to use the wildcard pattern in `exports` field - which technically _(AFAIK!)_ **is a valid pattern**. At least it works for compiling with `tsc`, and importing from other packages. No problem encountered so far.

Meanwhile, in another binary Node.js package, also internal and with the following `package.json` setup:

```json
{
	"type": "module",
	"name": "@app/api",
	"engines": {
		"node": ">=20"
	},
	"files": [
		"/dist"
	]
}
```

So, I have a normal test file for testing the health check route `/health, with a code:

```ts
import { StatusCodes } from "http-status-codes";
import { describe, it } from "vitest";

import { APP } from "../../app.js";

describe("/health", () => {
	it("returns ", async ({ expect }) => {
		const response = await APP.inject({
			method: "GET",
			url: "/health",
		});
		expect(response.statusCode).toBe(StatusCodes.OK);
	});
});
```

Executing command to run test at the root of the workspace as well at the root of package `@app/api`:

```sh
vitest run --dir=\"./src\" --passWithNoTests
```

Outputs the following error:

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  |api| src/routes/health/index.test.ts [ apps/api/src/routes/health/index.test.ts ]
Error: Failed to load url @package/database/clients (resolved id: @package/database/clients) in /<redacted>/template-project/apps/api/src/hooks.ts. Does the file exist?
 ❯ loadAndTransform ../../node_modules/.pnpm/vite@5.0.4_@types+node@20.10.0/node_modules/vite/dist/node/chunks/dep-4RECYSE1.js:48937:21
```

To display where the Vitest has problem with loading the url _(as the error message says)_, this is the code of `apps/api/src/hooks.ts`:

```ts
import { initDatabaseConnection } from "@package/database/clients";
import { log } from "@package/utils/log";
import closeWithGrace from "close-with-grace";
import type { onCloseAsyncHookHandler, onReadyAsyncHookHandler } from "fastify";

// Redacted, because not relevant to the issue
```

The issue is in the first line of code, the import of package `@package/database/clients`.

### Reproduction

I tried my best to describe in details. If you still require to have the minimal reproduction, then by the end of weekend I'll publish the template I worked on to hack around.

---

## Workaround

What I found  out that if I define more explicitly the modules in the `package.json` for a package `@package/database` it works. Example below:

```json
{
    	"exports": {
		"./*": {
			"types": "./lib/*.d.ts",
			"import": "./lib/*.js"
		},
		"./errors/*": {
			"types": "./lib/errors/*.d.ts",
			"import": "./lib/errors/*.js"
		}
	},
}
```

But, I would like to avoid the necessity of describing every new module directory in the `exports` field. If that's possible.

I am also not sure if this a **valid** pattern, because I can't confirm it via [official Node.js documentation for package subpath patterns](https://nodejs.org/docs/latest-v20.x/api/packages.html#subpath-patterns).

I was not sure either if this issue should be reported to upstream `vite` either, so I would appreciate any guidance. I am happy to help contribute as well on the fix, if this is confirmed as bug by someone more knowledgeable than me.

### System Info

```shell
System:
    OS: macOS 14.2
    CPU: (8) arm64 Apple M2
    Memory: 70.86 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.cache/fnm_multishells/68392_1702709845169/bin/node
    npm: 10.1.0 - ~/.cache/fnm_multishells/68392_1702709845169/bin/npm
    pnpm: 8.12.0 - /opt/homebrew/bin/pnpm
    bun: 1.0.17 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 117.1.58.124
    Safari: 17.2

vitest: 1.0.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Is 2nd one `./*/*` necessary? I think it might be redundant since first `./*` seems to already support directory-nested paths according to  https://nodejs.org/api/packages.html#subpath-patterns

Also, I happened to remember this issue on typescript, which suggests multiple `*` pattern is invalid according to node spec:
- https://github.com/microsoft/TypeScript/issues/56343

**Comment by xeho91** [comment]
> Is 2nd one `./*/*` necessary? I think it might be redundant since first `./*` seems to already support directory-nested paths according to https://nodejs.org/api/packages.html#subpath-patterns
> 
> Also, I happened to remember this issue on typescript, which suggests multiple `*` patterns are invalid in NodeJS (and typescript's behavior is not compliant to spec):
> 
> * [Two or more asterisks in subpath specifiers resolve in TS but never resolve at runtime in Node microsoft/TypeScript#56343](https://github.com/microsoft/TypeScript/issues/56343)

You are right, the 2nd one wasn't necessary.

I should have paid better attention to the documentation, because I didn't see clearly what the second example shows:

```js
import featureY from 'es-module-package/features/y/y.js';
// Loads ./node_modules/es-module-package/src/features/y/y.js
```

Is actually nested, `./y/y`. I wish someone wrote two different letters than two `y`, this got me. 😅 

And to quote the documentation:

> **`*` maps expose nested subpaths as it is a string replacement syntax only**.
>
> All instances of * on the right hand side will then be replaced with this value, **including if it contains any / separators**.

Eh, a note to myself. Don't read twice or however many times. Read _slowly_. 😮‍💨 

Thank you @hi-ogawa ❤️  , for clarifying things and linking me to TypeScript issue. I'm going to close this issue. Have a nice time!
