### ISSUE TITLE
watchExclude option doesn't work for code in node_modules in some cases

### ISSUE THREAD

**Issue by Jinjiang** [vitest-dev/vitest#4785]
### Describe the bug

From what I tried so far, the `watchExclude` for code in `node_modules` option doesn't work when:

- the environment is `node`.
- the environment is `jsdom` and
  - the first time you edit the main file of a node module, or
  - every time you edit a non-main file of a node module

More discussion info: https://github.com/vitest-dev/vitest/discussions/4772#discussioncomment-7896620

### Reproduction

https://github.com/Jinjiang/reproductions/tree/vitest-watch-node_modules-20231220

```
pnpm install

# you can switch environment between 'node' (default value) and 'jsdom'
pnpm test

# in 'node' environment:
#
# modify any code in node_modules
# - the test is not re-run

# in 'jsdom' environment:
#
# modify code in node_modules/foo-cjs/index.js or node_modules/foo-esm/index.js
# - when you first time modify it, the test is not re-run
# - when you further modify it, the test is re-run
#
# modify code in node_modules/foo-cjs/foo.js or node_modules/foo-esm/foo.js
# - the test is not re-run
```

The expected behavior is that the test is always re-run when any code in `node_modules/foo-cjs` and `node_modules/foo-esm` is modified whatever the environment is.

### System Info

```shell
System:
    OS: macOS 14.3
    CPU: (8) arm64 Apple M1
    Memory: 88.61 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.1.0 - ~/.asdf/installs/nodejs/20.1.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/shims/yarn
    npm: 9.6.4 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.12.0 - ~/Library/pnpm/pnpm
  Browsers:
    Safari: 17.3
  npmPackages:
    vite: ^5.0.10 => 5.0.10 
    vitest: ^1.0.4 => 1.0.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
In https://github.com/Jinjiang/reproductions/tree/vitest-watch-node_modules-20231220 when using `jsdom` environment, Vitest reruns changed `node_modules` file without any changes.
