### ISSUE TITLE
Flaky since migrating to Vite 5

### ISSUE THREAD

**Issue by C0ZEN** [vitest-dev/vitest#4790]
### Describe the bug

After the migration to Vite 5, I started having flaky failing tests, but only on the CI (GitHub actions).

```shell
Error:  ⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯
Error: 
Error:   FAIL  src/shared/components/safety-problem-icon/safety-problem-icon.component.test.tsx [ src/shared/components/safety-problem-icon/safety-problem-icon.component.test.tsx ]
Error:  Error: Cannot find module '/home/runner/actions-runner/_work/quality-linqueo-back/quality-linqueo-back/front/node_modules/.vitest/deps/react_jsx-runtime.js' imported from /home/runner/actions-runner/_work/quality-linqueo-back/quality-linqueo-back/front/node_modules/vite-node/dist/client.mjs
Error:  ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error:  Serialized Error: { code: 'ERR_MODULE_NOT_FOUND' }
Error:  ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
```

Note that I use Nx to run the tests.

### Reproduction

I don't see home come I can provide a reproduction.

### System Info

```shell
GitHub Actions
Both failing with vitest 0.X and 1.X.
Vite 5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Try disabling optimizer:

```ts
export default defineConfig({
  test: {
    deps: {
      optimizer: {
        web: { enabled: false }
      }
    }
  }
})
```

**Comment by C0ZEN** [comment]
I think it's OK now, thank you @sheremet-va.
Though now I also have these kinds of errors:

```shell
Error:  
⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
Error:  Error: ENOENT: no such file or directory, open '/home/runner/actions-runner/_work/x/.tmp/coverage-9.json'
Error:  ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error:  Serialized Error: { errno: -2, code: 'ENOENT', syscall: 'open', path: '/home/runner/actions-runner/_work/x/.tmp/coverage-9.json' }
Error:  
```

Any idea?

**Comment by sheremet-va** [comment]
This looks like an issue with coverage
