### ISSUE TITLE
Some plugins can break Vitest coverage report

### ISSUE THREAD

**Issue by Sec-ant** [vitest-dev/vitest#4794]
### Describe the bug

When using the plugin [vite-plugin-conditional-compile](https://github.com/KeJunMao/vite-plugin-conditional-compile) and adding `// #v-ifdef DEV` and `// #v-endif` comments in my code, Vitest marks all code as 100% covered (istanbul).

This also happens if I use its upstream plugin [unplugin-preprocessor-directives](https://github.com/KeJunMao/unplugin-preprocessor-directives) (vite-plugin-conditional-compile is a wrapper of this upstream plugin) and adding `// #if` and `// #endif` in my code.

![image](https://github.com/KeJunMao/vite-plugin-conditional-compile/assets/10386119/223eb544-8875-43ed-ad61-1d7b0e3a27af)

If I remove the directives, the coverage works again:

![image](https://github.com/KeJunMao/vite-plugin-conditional-compile/assets/10386119/add405ef-13f8-4d87-9117-8ea8d6325e46)

Similar issues can be found at:

1. https://github.com/unplugin/unplugin-vue-components/issues/333
2. https://github.com/unplugin/unplugin-vue-components/issues/219 (maybe related, this is mentioned in the previous link)

This issue is also filed here: https://github.com/KeJunMao/vite-plugin-conditional-compile/issues/9

I'm not sure if this is a bug in the plugin or Vitest itself, but I'm wondering if someone can pin down the cause of this problem?

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-4tlh7n?file=src%2Findex.ts

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 7 4800U with Radeon Graphics
    Memory: 5.08 GB / 7.44 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.6.1 - ~/.nvm/versions/node/v20.6.1/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v20.6.1/bin/yarn
    npm: 10.1.0 - ~/trie/node_modules/.bin/npm
    pnpm: 8.12.1 - ~/.local/share/pnpm/pnpm
  npmPackages:
    @vitest/browser: ^1.1.0 => 1.1.0 
    @vitest/coverage-istanbul: ^1.1.0 => 1.1.0 
    @vitest/ui: ^1.1.0 => 1.1.0 
    vite: ^5.0.10 => 5.0.10 
    vitest: ^1.1.0 => 1.1.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Any plugin that breaks source maps will break code coverage. There's nothing to do on Vitest's side. Plugin developers should add source map support to their plugins.

**Comment by Sec-ant** [comment]
@AriPerkkio I see, thanks for the explanation. I'm closing this now.

**Comment by Sec-ant** [comment]
@AriPerkkio Hey sorry to bother again but may I ask a silly question? Is there a way to prevent the coverage provider from source mapping to the original source code? i.e. I want the coverage provider to display the transformed code after all plugins but before sending into Vitest?

**Comment by Sec-ant** [comment]
> I can instruct how to debug the source maps and transformed code before Vitest's coverage providers handle it, if that's what you are looking for.

I'm very thankful for the offer. But I think I've found the problem which is this plugin is using `magic-string` to transform the source and generate sourcemaps, in which, if I understand correctly, all language information is lost and that's why the coverage provider can not do a proper mapping.

To get a valid coverage report, my first thought was making the code transformed by this plugin be treated as the original source, thus my previous question.

But now I think I can just switch to an AST transformation plugin that can properly generate sourcemaps and I'll implement the logic myself.

**Comment by AriPerkkio** [comment]
> the plugin I mentioned is using `magic-string` to transform the source and generate sourcemaps, in which, if I understand correctly, all language information is lost and that's why the coverage provider can not do a proper mapping.

We have some test cases where we use `magic-string` to modify sources and then check coverage report is correct. It's easily reproducible there that if we don't handle source maps correctly in the plugin, the test cases of coverage will fail. These test cases use `@ampproject/remapping` to merge source maps of earlier transform steps.

https://github.com/vitest-dev/vitest/blob/039814bd0eb9ed7b7f6e649a1c3def38d5174a5d/test/coverage-test/vitest.config.ts#L12-L37

The third party Vite plugins should output source maps correctly.
