### ISSUE TITLE
UI Summary Screen 

### ISSUE THREAD

**Issue by patak-dev** [vitest-dev/vitest#480]
### Clear and concise description of the problem

When you enter the UI, instead of a big black void, we could have a summary of how many tests passed, skipped, failed. Same info as the summary in the console.

Then you can focus on a test, and a button on the top of the left sidebar can be added to go back to the summary (using home icon?)

### Suggested solution

Implement a fancy summary, maybe later it could have interactive bits and graphs?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by userquin** [comment]
I'm working on this, one video on discord server on ui room.

**Comment by edimitchel** [comment]
This can be considered as resolved no ?

**Comment by antfu** [comment]
Yes, could leave the improvements for future
