### ISSUE TITLE
Cannot use method decorators in test files (Error: Unexpected token `@`)

### ISSUE THREAD

**Issue by alex-eliot** [vitest-dev/vitest#4809]
### Describe the bug

Vitest cannot correctly parse method decorators inside test files.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-cfhcld?file=src%2Fbasic.ts

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: latest => 1.1.0 
    vite: latest => 5.0.10 
    vitest: latest => 1.1.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest uses Vite that uses esbuild to process TypeScript files. Esbuild just leaves decorators as is: https://github.com/evanw/esbuild/issues/104

See similar issues:
- https://github.com/vitest-dev/vitest/issues/3140
- https://github.com/vitest-dev/vitest/issues/708

**Comment by alex-eliot** [comment]
Thanks for the helpful direction. I was able to make it work thanks to [this comment's](https://github.com/vitest-dev/vitest/issues/708#issuecomment-1045201786) temporary solution.
