### ISSUE TITLE
Mocking is lost when `threads: false` is set

### ISSUE THREAD

**Issue by EvHaus** [vitest-dev/vitest#482]
### Describe the bug

I'm seeing a strange behavior with `threads: false` which might be related to #468 and #294. When you mock modules, the mocking works on initial run, but mocks are reset to `undefined` when watch mode refreshes, or the when another suite runs.

### Reproduction

Use this tiny repro suite where I mock the `ora` package: https://stackblitz.com/edit/node-72ecu4?file=index.ts

To reproduce the problem, run the stackblits as normal. You'll notice the initial run works without any issues.

Then make any edit to any file (ie. add some white space) to trigger watch mode to re-run the tests. You'll see that the tests now fail with:

```
TypeError: Cannot read properties of undefined (reading 'start')
```

This is because the `ora` mock somehow becomes `undefined`.

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 32.75 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2022.01.03.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 97.0.4692.71
    Chrome Canary: 99.0.4813.0
    Firefox: 95.0
    Safari: 15.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is kinda an experimental fix. I remember why we added that line, but locally all is fine after removing it.

Let me know if it adds new issues :S

**Comment by EvHaus** [comment]
Seems to be working well for me. Thank you!
