### ISSUE TITLE
How to use plugin in vitest

### ISSUE THREAD

**Issue by wmy0320** [vitest-dev/vitest#4821]
### Describe the bug

when l  import a file needed to be tested, a error occur as followed:
```
[Vue warn]: Failed to resolve component: SvgIcon
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
  at <Index ref="VTU_COMPONENT" >
  at <VTUROOT>
```
But when il found in Documentation, the useage of plugin is very little
![image](https://github.com/vitest-dev/vitest/assets/128336909/543189ab-1420-42ec-942e-be9c8e32d66b)

### Reproduction

Is there someone could add useage of plugin to vitest document?

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
    Memory: 3.18 GB / 31.70 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (120.0.2210.91)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @vitejs/plugin-vue: ^3.1.0 => 3.2.0
    vite: ^3.1.8 => 3.2.7
    vitest: ^1.0.4 => 1.1.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
https://vitejs.dev/guide/using-plugins.html
