### ISSUE TITLE
New `HTMLInputElement` under `jsdom` env reports ` Invalid constructor, the constructor is not part of the custom element registry`

### ISSUE THREAD

**Issue by jindong-zhannng** [vitest-dev/vitest#4840]
### Describe the bug

When call `new HTMLInputElement()` in a test file, with config `environment: 'jsdom'`, it will report
```
TypeError: Invalid constructor, the constructor is not part of the custom element registry
 ❯ HTMLConstructor ../../node_modules/.pnpm/jsdom@22.1.0/node_modules/jsdom/lib/jsdom/living/helpers/html-constructor.js:20:11
 ❯ new HTMLInputElement ../../node_modules/.pnpm/jsdom@22.1.0/node_modules/jsdom/lib/jsdom/living/generated/HTMLInputElement.js:102:14
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-2mbbpv?file=test%2Fbasic.test.ts

### System Info

```shell
I can't print info in my machine (why?), but the issue can be reproduced well by above link.
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You can't do that in the browser. Works as expected.
