### ISSUE TITLE
Unable to resolve correctly for `node_moduels` soft links on Windows

### ISSUE THREAD

**Issue by JounQin** [vitest-dev/vitest#4841]
### Describe the bug

```log
→ Failed to load plugin 'mdx' declared in 'BaseConfig': Cannot find module 'D:\a\eslint-mdx\eslint-mdx\node_modules\eslint-plugin-mdx\lib\index.js'. Please verify that the package.json has a valid "main" entry
```

### Reproduction

https://github.com/mdx-js/eslint-mdx/actions/runs/7378053284/job/20072722711?pr=508

https://github.com/mdx-js/eslint-mdx/tree/build/yarn_v4

### System Info

Windows on CI

local:

```log
  System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 12.77 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/Library/Caches/fnm_multishells/89034_1703864877615/bin/node
    Yarn: 4.0.2 - ~/Library/Caches/fnm_multishells/89034_1703864877615/bin/yarn
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/89034_1703864877615/bin/npm
    bun: 1.0.20 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 120.1.61.109
    Chrome: 120.0.6099.129
    Safari: 17.2.1
  npmPackages:
    @vitest/coverage-istanbul: ^1.1.1 => 1.1.1 
    vitest: ^1.1.1 => 1.1.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I don't understand what is the problem here. From what I can see the error happens in `@eslint/eslintrc/lib/shared/relative-module-resolver.js`, why is this a Vitest error?

**Comment by sheremet-va** [comment]
From what I can see it uses `require`:

https://github.com/coderaiser/eslintrc/blob/99adbac4fec25a50e466946833677351eb8794b9/lib/shared/relative-module-resolver.js#L23

Vitest never supported and will never support intercepting `require`.

**Comment by JounQin** [comment]
Well, the error only occurs on Windows.

**Comment by JounQin** [comment]
> why is this a Vitest error?

I'm migrating from jest, there is no such issue when using jest.
