### ISSUE TITLE
`expect(...).toSatisfy(matcher)` is typed incorrectly

### ISSUE THREAD

**Issue by Ragnar-Oock** [vitest-dev/vitest#4845]
### Describe the bug

When using `expect(...).toSatisfy(matcher)`, the type of the matchers' parameter is not resolved correctly.

This most likely comes from how the signatre of the method is declared :
```ts
interface Assertion<T = any> extends VitestAssertion<Chai.Assertion, T>, JestAssertion<T> {
    toSatisfy<E>(matcher: (value: E) => boolean, message?: string): void;
    // [...]
}
```
for it to infer the signature of the matcher correctly it should use the same generic type as the interface (i.e. T) :
```ts
interface Assertion<T = any> extends VitestAssertion<Chai.Assertion, T>, JestAssertion<T> {
    toSatisfy(matcher: (value: T) => boolean, message?: string): void;
    // [...]
}
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-erayjg?file=test%2Fsuite.test.ts

### System Info

```shell
System:                                                
    OS: Windows 10 10.0.19045                            
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 16.96 GB / 31.81 GB                          
  Binaries:                                              
    Node: 18.16.1 - C:\Program Files\nodejs\node.EXE     
    npm: 9.2.0 - C:\Program Files\nodejs\npm.CMD         
  Browsers:                                              
    Edge: Chromium (120.0.2210.91)                       
    Internet Explorer: 11.0.19041.3636                   
  npmPackages:                                           
    @vitest/coverage-v8: ^1.0.4 => 1.0.4                 
    @vitest/ui: ^1.0.4 => 1.0.4                          
    vitest: ^1.0.4 => 1.0.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is intentional. Satisfy doesn't have to accept only types that expect is receiving. Throwing a runtime error is correct behavior in that case.
