### ISSUE TITLE
Read thread ID inside a test

### ISSUE THREAD

**Issue by danilofuchs** [vitest-dev/vitest#4848]
### Clear and concise description of the problem

Our tests rely on a shared database connection, with `--no-isolate` and `--no-threads` as they may have side effects.

To speed it up, we want to run them in parallel, setting up multiple databases, one for each vitest thread.

### Suggested solution

A field inside `ctx.task` that identifies the thread ID, so we can choose a different database.

### Alternative

Run tests with `--shard` and use an environment variable for each shard.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
There are already two variables:

https://vitest.dev/guide/migration.html#envs

1. `VITEST_WORKER_ID` is incremented for every new worker spawned
2. `VITEST_POOL_ID` is the number of worker (`>= minWorkers && <=maxWorkers`)
