### ISSUE TITLE
`--ui` attempts to load `.vue` files unrelated to test

### ISSUE THREAD

**Issue by DerYeger** [vitest-dev/vitest#485]
### Describe the bug

Attempting to open the use the UI with `--ui` causes Vitest to load `.vue` files unrelated to the tests (from the docs in particular).

The following errors are printed:

```
error: No loader is configured for ".vue" files: demo/components/App.vue
```

```
[
    {
      detail: undefined,
      location: {
        column: 16,
        file: 'demo/main.ts',
        length: 25,
        line: 1,
        lineText: "import App from 'demo/components/App.vue'",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No loader is configured for ".vue" files: demo/components/App.vue'
    }
],
```

`demo/main.ts` is not referenced in the source code or any test.

### Reproduction

Repository with reproduction: https://github.com/DerYeger/d3-graph-controller

Can be reproduced by running the test with `yarn test:watch --ui`.

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor            
    Memory: 16.04 GB / 31.92 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 7.20.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (96.0.1054.62)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitejs/plugin-vue: 2.0.1 => 2.0.1 
    vite: 2.7.10 => 2.7.10 
    vitest: 0.0.139 => 0.0.139
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by edimitchel** [comment]
Hi, is that issue still a problem?

**Comment by DerYeger** [comment]
Yes. Running `yarn test:watch --ui` in the repository linked above results in the same error.
I tried it with v0.2.3 without success.

**Comment by edimitchel** [comment]
Ok, I'll try to see what is going wrong.

**Comment by sheremet-va** [comment]
Is it still happening?

**Comment by DerYeger** [comment]
> Is it still happening?

Yes, just tested it with v0.4.2.

**Comment by DerYeger** [comment]
It's seemingly related to the file naming.

After renaming `demo/main.ts` the error no longer occurs.
However, the UI still doesn't work. I also renamed `src/main.ts`, but that didn't help.
There's no error, but the UI does open either.

**Comment by DerYeger** [comment]
I just noticed the v0.5.0 release.

After updating to that version, I do get the message that the UI was started, but the UI still is a 404.

**Comment by sheremet-va** [comment]
So, this happens because:

By default, Vite will crawl all your .html files to detect dependencies that need to be pre-bundled (ignoring node_modules, build.outDir, __tests__ and coverage). If build.rollupOptions.input is specified, Vite will crawl those entry points instead.

- https://vitejs.dev/config/#optimizedeps-entries

We had it disabled, but removed some time ago - #641 🤔

**Comment by sheremet-va** [comment]
> We had it disabled, but removed some time ago - #641 🤔

Turns out `optimizeDeps: undefined` doesn't disable optimization, I guess thats why this patch was made. But `optimizeDeps: { entries: [] }` does disable it, opened a PR #1104
