### ISSUE TITLE
Cannot call `import.meta.glob` from `node_modules`

### ISSUE THREAD

**Issue by briandunn** [vitest-dev/vitest#4851]
### Describe the bug

Trying to use the router created by [generouted](https://github.com/oedotme/generouted) in a vitest test.

Requiring the router causes an exception like

```
TypeError: 𝐢𝐦𝐩𝐨𝐫𝐭.meta.glob is not a function
 ❯ eval node_modules/@generouted/react-router/dist/index-lazy.js:29:35
 ❯ _0x2e26db._evaluate ../../../blitz.a2aabdd9.js:352:376700
 ```
 
 I think this is a vitest bug, because calling `glob` from `node_modules` _is_ supported in dev and production in vite. So to match that behavior vitest would also need to allow `glob` calls from `node_modules.`

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-5fnvms?file=package.json,test%2Fbasic.test.ts&initialPath=__vitest__/

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1
    Memory: 93.52 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.asdf/installs/nodejs/18.18.2/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Brave Browser: 120.1.61.104
    Chrome: 120.0.6099.129
    Safari: 17.2.1
    Safari Technology Preview: 17.4
  npmPackages:
    @vitejs/plugin-react: ^4.2.0 => 4.2.0 
    vite: ^5.0.5 => 5.0.5 
    vitest: ^1.1.1 => 1.1.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
To support `import.meta.glob` in files that are not considered source code, you need to inline the dependency:

```ts
export default defineConfig({
  test: {
    server: {
      deps: {
        inline: ['generouted']
      }
    }
  }
})
```
