### ISSUE TITLE
Named Export Bug

### ISSUE THREAD

**Issue by charlieforward9** [vitest-dev/vitest#4852]
### Describe the bug

```
SyntaxError: Named export 'Sha256' not found. The requested module '@aws-crypto/sha256-js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@aws-crypto/sha256-js';
``` 

I am getting this issue in a testing file that has no direct dependency on aws amplify or aws-crypto, in any way. Can I please get a pointer or explanation as to how to work around this issue?

It is now showing up on tests that worked earlier, but after upgrading the amplify, vite, vitest versions, there are what seems to be irreversable issues with this module import. I have tried downgrading everything (except amplify) back to its original state when I got it working but nothing has clicked yet.

### Reproduction

My config
```ts
export default defineConfig({
  plugins: [comlink(), react()],
  worker: {
    plugins: () => [comlink()],
  },
  server: {
    port: 3000,
  },
  test: {
    environment: "jsdom",
    deps: {
      inline: ['@aws-crypto/sha256-js'] //Added to try to fix, no change
    },
    setupFiles: ["src/mocks/setup.ts"],
  },
});
```

Setup isnt really relevant but ill include it as a section
<details>
import { beforeAll, afterAll, afterEach } from "vitest";
import { server } from "./handlers";
beforeAll(() => server.listen({ onUnhandledRequest: "warn" }));
afterAll(() => server.close());
afterEach(() => server.resetHandlers());
</details>

Working on reproduction, see https://github.com/vitest-dev/vitest/discussions/1360 for similar

### System Info

```shell
System:
    OS: macOS 12.7.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 57.82 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.9.2 - ~/Documents/Github/Agroview2.0/node_modules/.bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 17.2.1
  npmPackages:
    @vitejs/plugin-react: ^4.0.4 => 4.2.1 
    @vitejs/plugin-react-swc: ^3.0.0 => 3.5.0 
    @vitest/coverage-v8: ^0.34.6 => 0.34.6 
    vite: latest => 5.0.10 
    vitest: ^1.0.0-beta.3 => 1.1.1
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Jinjiang** [comment]
I think this is the same issue: https://github.com/vitest-dev/vitest/issues/4745

**Comment by charlieforward9** [comment]
@Jinjiang I added my config file https://github.com/vitest-dev/vitest/issues/4852#:~:text=Reproduction-,My%20config,-export%20default%20defineConfig (comment) to the description. I tried using that one.

**Comment by sheremet-va** [comment]
You need to inline the file that _imports_ `@aws-crypto/sha256-js`, not necessarily `@aws-crypto/sha256-js` itself.

**Comment by charlieforward9** [comment]
@sheremet-va I do not import that file anywhere in my codebase directly. Additionally, I added the test file and all the files that the test file depends on and it still does not work as expected. To be double-sure I did it correct, I added the paths to two locations in the config:

```ts
/// <reference types="vitest" />
import react from "@vitejs/plugin-react";
import { comlink } from "vite-plugin-comlink";
import { defineConfig } from "vite";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [comlink(), react()],
  worker: {
    plugins: () => [comlink()],
  },
  server: {
    port: 3000,
  },
  test: {
    environment: "jsdom",
    server: {
      deps: {
        inline: [
          "src/features/auth/service.ts",
          "src/core/service/providers/test/providerManager.test.ts",
          "src/core/service/providers/providerManager.ts",
          "src/models/index.d.ts",
        ],
      },
    },
    deps: {
      optimizer: {
        web: {
          include: [
            "src/features/auth/service.ts",
            "src/core/service/providers/test/providerManager.test.ts",
            "src/core/service/providers/providerManager.ts",
            "src/models/index.d.ts",
          ],
        },
      },
    },
    setupFiles: ["src/mocks/setup.ts"],
  },
});
```

**Comment by sheremet-va** [comment]
> @sheremet-va I do not import that file anywhere in my codebase directly

I know. If you did, then you wouldn't have this problem 😄 

What you added to `deps.inline` doesn't have any effect because it's for your dependencies (the name `deps` refers to that). If it's a string, Vitest will check `/node_modules/${name}`. You need to add a dependency that imports `@aws-crypto/sha256-js` there. Alternatively, you can also try adding the same dependency to `optimizer`, but these two options cancel each other out with `optimizer` having a larger priority.
