### ISSUE TITLE
Vitest can't resolve import '#imports'(Nuxt3, vitest)

### ISSUE THREAD

**Issue by gyofeel** [vitest-dev/vitest#4853]
### Describe the bug

Hello, I am using Vitest for testing on Nuxt3, vite env.
Due to our team's convention, the configuration uses 'autoImport: false'.(For an explicit declaration) So when importing Nuxt's built-in items (useRoute, nextTick, computed, etc.) we use import '#imports'.

When I run Vitest, the following error occurs:

Error: Failed to resolve import "#imports" from "[file path]". Does the file exist?
How do I solve this? help.
Is this something that needs to be fixed in Nuxt?
(https://github.com/vitest-dev/vitest/discussions/4353)

Below is my vitest.config.js
```javascript
import path from 'path';
import vue from '@vitejs/plugin-vue';

export default {
    plugins: [vue()],
    test: {
        globals: true,
        environment: 'jsdom'
    },
    resolve: {
        alias: {
            '@': path.resolve(__dirname, './src')
        }
    }
};

``` 
Thanks.

### Reproduction

https://stackblitz.com/edit/nuxt-starter-rx4vx2?file=package.json,testUtils.js,testUtils.test.js

you can run test command below.
```
npm test
``` 

### System Info

```shell
ENV
os: Darwin
nodejs: 20.9.0
nuxt: 3.8.1
@nuxt/test-utils: 3.8.1
vitest: 1.1.1
yarn: 1.15.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Your config doesn't define what `#imports` or nuxt is, so this is expected behavior. You already got your answer in https://github.com/nuxt/nuxt/issues/25021 from the Nuxt team to use https://github.com/nuxt/test-utils/ for testing your Nuxt applications.
