### ISSUE TITLE
vitest imports file from cwd directy instead of node module if the names are identical

### ISSUE THREAD

**Issue by ValentinGurkov** [vitest-dev/vitest#4860]
### Describe the bug

In the first example below you will see a test file that imports the `tsoa` library and `console.log`s everything inside it.
Due to a `tsoa.json` existing at the root, the file is read instead and its' contents logged into the console instead of the package's contents.

In the second example `tsoa.json` is renamed to `tsoa.config.json`. Since the names are no longer identical, the package contents are logged instead of JSON files.

https://github.com/vitest-dev/vitest/issues/2788 already reported something similar but was closed by the author.

For what it's worth, I'm migrating from `jest` and the same scenario is not reproducible there.

### Reproduction

With identical name

1. Visit https://stackblitz.com/edit/vitejs-vite-tj9sr8
2. Execute `npm run test` in the terminal
3. Observe the "tsoa" console log - it is not outputting the library, so the import does not ask expected.

When the names are not identical

1. Visit https://stackblitz.com/edit/vitejs-vite-zhvhps
2. Execute `npm run test` in the terminal
3. Observe the "tsoa" console log - it imports the library as expected.

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 5.23 GB / 31.21 GB
  Binaries:
    Node: 20.10.0 - C:\program files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\program files\nodejs\yarn.CMD
    npm: 10.2.3 - C:\program files\nodejs\npm.CMD
    pnpm: 8.14.0 - C:\program files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.91)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitest/coverage-v8: ^1.1.1 => 1.1.1
    vitest: ^1.1.1 => 1.1.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is an issue with how Vite resolves modules. I opened an issue at https://github.com/vitejs/vite/issues/15500

**Comment by sheremet-va** [comment]
After more investigation, I didn't find any errors: `tsoa` is correctly resolved - https://stackblitz.com/edit/vitejs-vite-tgveho?file=src%2Fmain.js,vitest.config.js

It prints:

```js
tsoa {
  Deprecated: [Getter],
  Example: [Getter],
  Body: [Getter],
  BodyProp: [Getter],
...
```

**Comment by ValentinGurkov** [comment]
> After more investigation, I didn't find any errors: `tsoa` is correctly resolved - https://stackblitz.com/edit/vitejs-vite-tgveho?file=src%2Fmain.js,vitest.config.js
> 
> It prints:
> 
> ```js
> tsoa {
>   Deprecated: [Getter],
>   Example: [Getter],
>   Body: [Getter],
>   BodyProp: [Getter],
> ...
> ```

I've also run this again and the issue did not reproduce. 
Thanks for spending some of your time on this but I will close the issue and see if I'll be able to reproduce this again in a small repo.
