### ISSUE TITLE
Allow passing --include on the CLI?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [vitest-dev/vitest#4861]
### Clear and concise description of the problem

Right now, there's no documented way I could find to specify the [`include` config option](https://vitest.dev/config/#include) with the CLI. Would the project be open to adding an `--include` CLI option?

### Suggested solution

Being able to run `vitest --include 'some/globs'`.

`--exclude` support was added in #4148 -> #4279. I suppose this proposal is roughly the same idea.

### Alternative

In the meantime, we can `-t` to specify on _test_ names. But it'd be nice to go by _file_ name.

### Additional context

My use case is a project that has a few end-to-end tests defined with Vitest. Each of those tests runs a lot of commands and modifies the current directory. So being able to run e.g. `pnpm run test:e2e:create` that calls `vitest --include 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Can't you just pass it down as a filter? The terminal usually handles it before Vitest ever needs to.

```
vitest **/some-glob.ts
```

**Comment by JoshuaKGoldberg** [comment]
Ah, that makes sense. I don't know why I didn't think of that as an implicit `--include`. Thanks! 😄

**Comment by sheremet-va** [comment]
`vitest **/some-glob.ts` will limit the filter to files inside `include` and `exclude` patterns, so this is not a full replacement. See: https://github.com/vitest-dev/vitest/discussions/5348#discussioncomment-8718122

**Comment by sheremet-va** [comment]
We believe that it's better to use a [workspace feature](https://vitest.dev/guide/workspace.html) to organize your Vitest configuration:

```js
import { defineWorkspace } from 'vitest/config'

export default defineWorkspace([
  {
    test: {
      include: ['tests/**/*.unit.test.ts'],
      name: 'unit',
      environment: 'happy-dom',
    }
  },
  {
    test: {
      include: ['tests/**/*.e2e.test.ts'],
      name: 'e2e',
      environment: 'node',
    }
  }
])
```

You can then run it as `vitest --project=e2e`.

For that reason, as a team, we decided that it's better to wait until there is more demand for this feature (CLI `--include`).
