### ISSUE TITLE
A Node API to catch deps installation prompts and handle it on the user's own

### ISSUE THREAD

**Issue by Jinjiang** [vitest-dev/vitest#4864]
### Clear and concise description of the problem

This issue is from discussion: https://github.com/vitest-dev/vitest/discussions/4772#discussioncomment-7892803

The background is we are integrating Vitest in Node APIs into [Bit](https://bit.dev/) workflow. However, Bit CLI doesn't use npm/yarn/pnpm to install dependencies directly. Instead we have `bit install`.

In some cases, Vitest will prompt in terminal asking for installing dependencies like vitest ui, vitest coverage, jsdom etc. Then the logic would be out of control from Bit CLI.

### Suggested solution

It would be great if we can catch them by a Node.js API and hand it over to `bit install`.

The new API could be an API, an option, or any kinds of event handlers which can be fired when any dependency is missing and let user decides whether to install it by Vitest or leave the job to user.

Pseudo code:

```js
startVitest(..., async function (dep, installFn) {
  if (needInstallByBit(dep)) {
    // bit install the dep
  } else {
    await installFn(dep)
  }
}
```

### Alternative

Just provide an option to fail the tests when any external deps not found.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
I think this auto-install feature is provided from https://github.com/antfu/install-pkg, so it might be better to ask for bit cli support there?

https://github.com/vitest-dev/vitest/blob/70e8a3897319dc879749308505d977f0fd8a88ea/packages/vitest/src/node/pkg.ts#L42

But, It might be still nice for Vitest to provide a way to opt-out of this auto-install via environment variable or something since currently this can be skipped only on CI or non-TTY stdout.

https://github.com/vitest-dev/vitest/blob/70e8a3897319dc879749308505d977f0fd8a88ea/packages/vitest/src/node/pkg.ts#L27-L32

**Comment by hi-ogawa** [comment]
Maybe it's too dirty or it doesn't even work, but it just came to my mind.

Would it be a viable "API" to control auto installation by something like `process.env.VITEST_INSTALL_PKG` variable in a following way?

```ts
// somewhere in the current `ensurePackageInstalled` (packages/vitest/src/node/pkg.ts)
// ...

if (process.env.VITEST_INSTALL_PKG === "false") {
  return false;
}

if (process.env.VITEST_INSTALL_PKG) {
  // VITEST_INSTALL_PKG should point to import-able js module with { default: () => Promise<void> }
  const customInstallPkg = await import(process.env.VITEST_INSTALL_PKG);
  await customInstallPkg.default(dependency)
  return true;
}

// otherwise fallback to current `import("@antfu/install-pkg")` 
// ...
```

**Comment by sheremet-va** [comment]
> Would it be a viable "API" to control auto installation by something like `process.env.VITEST_INSTALL_PKG` variable in a following way?

I would prefer updating `startVitest` signature
