### ISSUE TITLE
expect.getState().currentTestName incompatible with Jest

### ISSUE THREAD

**Issue by programmer24601** [vitest-dev/vitest#4874]
### Describe the bug

When calling `expect.getState().currentTestName` Jest will return a string in the format:
```
`${describeTitle} ${testTitle}`
```
Whereas Vitest will produce:
```
`{filePath} > ${describeTitle} > ${testTitle}`
```

Although I prefer what Vitest produces, the inconsistency is causing issue with a jest matcher library `jest-image-snapshot` which relies on this API for generating filenames for snapshot image files. Migrating from jest to vitest is breaking my tests as the filenames being generated are too long resulting in a `ENAMETOOLONG` error.

My proposal would be to make this API consistent with Jest, and offer this richer output on a separate API (e.g. `currentTestFullName`).

Finally, I'm raising this as a bug as Vitest advertises itself as "Jest Compatible". This is an example that clearly breaks that contract.

---

Relates to https://github.com/vitest-dev/vitest/discussions/297

### Reproduction

Reproduction not necessary.

### System Info

```shell
vitest 1.1.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> Finally, I'm raising this as a bug as Vitest advertises itself as "Jest Compatible".

We have the whole migration page in docs for people moving away from Jest, we are compatible to the point it makes sense for us. It's been two ears since the API you mentioned was implemented (and it's used in reporters, for example) and it might break other libraries that Vitest users rely on.

I'd say this qualifies as a separate section in the migration guide.

**Comment by programmer24601** [comment]
Thanks for the quick response. I've just spotted another discrepancy: if a dollar variable is used in test title (e.g. `test.each`) jest would return the variable name (minus the dollar), whilst vitest returns `undefined`.

**Comment by programmer24601** [comment]
It looks like there's been some improvement here such that my custom snapshot identifier is no longer needed as vitest 2 is now producing shorter snapshot filenames.

It's still incompatible with jest (hence documentation needs to point out this incongruity), but it's no longer producing `ENAMETOOLONG` errors.
