### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by lifeiscontent** [vitest-dev/vitest#4884]
### Describe the bug

when using mocks, tests fail unexpectedly

```⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 2 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/routes/api/articles.test.ts > GET /articles route > should return a 200 response
 FAIL  lib/src/routes/api/articles.test.js > GET /articles route > should return a 200 response
RangeError: Maximum call stack size exceeded
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/2]⎯
```

### Reproduction

the following line in this test fails unexpectedly: https://github.com/lifeiscontent/fastify-realworld/blob/d837b90a0a749703379d9dd714d7f7df74769457/src/routes/api/articles.test.ts#L98

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 7.69 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - /opt/homebrew/opt/node@18/bin/node
    npm: 9.8.1 - /opt/homebrew/opt/node@18/bin/npm
    pnpm: 8.12.1 - /opt/homebrew/opt/node@18/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.199
    Edge: 120.0.2210.121
    Safari: 17.2.1
  npmPackages:
    vite: 5.0.10 => 5.0.10 
    vitest: 1.1.0 => 1.1.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Did this code ever actually worked? Or did it stop working?

**Comment by lifeiscontent** [comment]
@sheremet-va if there's something I'm blatantly doing wrong, I'm happy to change the test, but this is the first test I've written for this project.

**Comment by sheremet-va** [comment]
The test shouldn't work, but the error is weird. It doesn't work because `vi.mock` is hoisted so you don't have access to variables that you use there: https://vitest.dev/api/vi.html#vi-mock

**Comment by sheremet-va** [comment]
I cannot reproduce the error myself with your repository.
