### ISSUE TITLE
Custom headers for `@vitest/browser`

### ISSUE THREAD

**Issue by DenizUgur** [vitest-dev/vitest#4888]
### Describe the bug

When using `@vitest/browser` custom response headers in `server.headers` are not respected.

### Reproduction

Try to use `SharedArrayBuffer`, without correct [headers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#security_requirements) it's not possible to get a reference to that object.

### System Info

```shell
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (32) x64 Intel(R) Core(TM) i9-14900K
    Memory: 54.10 GB / 62.57 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
  Browsers:
    Chrome: 120.0.6099.129
  npmPackages:
    @vitejs/plugin-react: ^4.2.1 => 4.2.1 
    @vitest/browser: ^1.1.3 => 1.1.3 
    @vitest/coverage-v8: ~1.1.1 => 1.1.1 
    @vitest/ui: ~1.1.1 => 1.1.1 
    @vitest/web-worker: ^1.1.3 => 1.1.3 
    vite: ^5.0.10 => 5.0.10 
    vitest: ~1.1.1 => 1.1.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
I think your issue is same as https://github.com/vitest-dev/vitest/issues/3743

Currently it should be possible to achieve `crossOriginIsolated` by using custom middleware plugin with `enforce: "pre"` as suggested in https://github.com/vitest-dev/vitest/issues/3743

I haven't thought about using `server.headers` https://vitejs.dev/config/server-options.html#server-headers but maybe ideally that should work as well. Let me check.

**Comment by DenizUgur** [comment]
Yup, custom plugin solution works without a problem. It feels a bit hacky when we already have `server.headers`. It's just semantics though.

**Comment by hi-ogawa** [comment]
Good point. I wasn't aware of `server.headers` but I think Vitest browser mode should support that as well.

Currently main html document (which is where coop/coep headers are meant to be) is served by its own static middleware, so it's skipping Vite's normal processing to inject `server.headers`. Probably Vitest can copy those headers manually here.

https://github.com/vitest-dev/vitest/blob/a73c1c2ca3a3ca93b317657b9328889434c36344/packages/browser/src/node/index.ts#L25-L32
