### ISSUE TITLE
Dependency optimization does not work in SSR transform mode

### ISSUE THREAD

**Issue by kherock** [vitest-dev/vitest#4910]
### Describe the bug

Vite lazily initializes the SSR deps optimizer when [`ViteDevServer.ssrLoadModule` is called for the first time](https://github.com/vitejs/vite/blob/8ccf7222e9ffaa5e97bd0797de101c8bc6ca8d41/packages/vite/src/node/server/index.ts#L473-L475).
 
Vitest/vite-node does not seem to ever call this method, so the optimizer never ends up being initialized into the [devSsrDepsOptimizerMap](https://github.com/vitejs/vite/blob/8ccf7222e9ffaa5e97bd0797de101c8bc6ca8d41/packages/vite/src/node/optimizer/optimizer.ts#L831), which Vite uses to resolve the appropriate optimizer.

### Reproduction

I'm currently running Vitest 0.34 with Vite 4, but I was able to recreate the issue with the latest Vitest and Vite 5:
https://stackblitz.com/edit/vitest-dev-vitest-1flfpv?file=test%2Fweb.test.ts

### System Info

```shell
System:
    OS: macOS 13.6.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 103.50 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - /opt/homebrew/bin/npm
    pnpm: 7.9.5 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.199
    Edge: 120.0.2210.121
    Safari: 17.2.1
  npmPackages:
    @vitest/coverage-v8: ^0.34.6 => 0.34.6 
    vitest: ^0.34.6 => 0.34.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Interesting... I was also wondering how `ssr.optimizeDeps` (pre-bundling) is supposed to work (though my use case was directly using vite-node without Vitest).

As you mentioned, it looks like calling `ssrLoadModule` is necessary to trigger deps optimization. It's a very sketchy workaround, but doing so in a plugin seems to suffice for my use case:

```tsx
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [
    {
      name: 'force-ssr-optimize-deps',
      configureServer(server) {
        return async () => {
          console.log('[ssrLoadModule to trigger ssr pre-bundling]');
          await server.ssrLoadModule('/dummy-module.js');
        };
      },
    },
  ],
});
```

I tested this on your repro as well though probably Vitest is supposed to handle this somehow eventually:

https://stackblitz.com/edit/vitest-dev-vitest-8wf26p?file=vite.config.ts

**Comment by patak-dev** [comment]
Created a PR to Vite to move the SSR dev optimization to the server init here. I think we should merge this for Vite 5.1:
- https://github.com/vitejs/vite/pull/15561

**Comment by hi-ogawa** [comment]
I verified that Vite 5.1.0-beta.0 fixed the issue without hacky "force-ssr-optimize-deps'" plugin.  I used npm's `overrides` in this stackblitz:
https://stackblitz.com/edit/vitest-dev-vitest-phpqaa?file=package.json

I also verified the fix in my project as well. Thanks @patak-dev!

**Comment by sheremet-va** [comment]
I think we can close this. Vitest doesn't support versions before 1.0, so the recommendation is to update to the latest version. You can also use a workaround provided by @hi-ogawa.
