### ISSUE TITLE
[browser] Provide access to Playwright's Keyboard classes in browser mode

### ISSUE THREAD

**Issue by motss** [vitest-dev/vitest#4918]
### Clear and concise description of the problem

The experimental browser mode currently allows users to choose a list of providers (Webdriver.io, Playwright) to run their tests on various browsers supported by their chosen provider.

However, there isn't a way to reference the current page context in a test suite to call some of the API classes offered by Playwright, e.g. the Playwright's [Keyboard class](https://playwright.dev/docs/api/class-keyboard) allows users to simulate keyboard inputs as if they were generated from a real keyboard.

### Suggested solution

1. To provide access to the current page context for API classes provided by Playwright
2. To provide an API to send commands to Playwright, e.g. [sendKeys](https://modern-web.dev/docs/test-runner/commands/#send-keys) command from web-test-runner

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
Thanks for the feature request.

To make sure I understand this better, can you elaborate on what kind of tests you are intending to write on Vitest browser mode if such API is available? Providing some examples with your hypothetical API might help.


> there isn't a way to reference the current page context in a test suite to call some of the API classes offered by Playwright

One important difference between Vitest's browser mode and Playwright is that "test suite" itself is executed on the browser on Vitest browser mode. It might be obvious, just in case, to give a concrete example:

```ts
// vitest browser mode
test("test", () => {
  expect(typeof window).toBe("object")
})

// playwright
test("test", async ({ page }) => {
  expect(typeof window).toBe("undefined")
  expect(await page.evaluate(() => typeof window)).toBe("object")  // page API is the interface to the browser
})
```

I think the better analogy would be that it's jsdom-like test environment but it's actually the real browser. So, it might make more sense to bring something like testing-library ecosystem https://testing-library.com/docs/ for selector, event utility etc... (actually I've never tried, but I feel it makes sense).

**Comment by sheremet-va** [comment]
The idea is that people use solutions that are already provided by third-party packages. Eventually, Vitest should provide a set of utilities that are better addressed natively (like clicking - it's not possible to emulate the order of all events on the micro-task level specified by the spec). The API for this is not decided yet - I feel like we should make the runner more stable before starting with this.

**Comment by sheremet-va** [comment]
I do like the `web-test-runner` implementation. I have this sort of API in my mind to have a similar feature:

```ts
import { sendKeys } from '$page'

await sendKeys({ type: 'hello world' })
```

On the server side, we can implement some kind of API to get this virtual module from testing providers:

```ts
interface VirtualBrowserPage {
  sendKeys(options): void
}

interface BrowserProvider {
  getVirtualPageMethods() {
    return { sendKeys: this.sendKeys }
  }
}
```

And the virtual module is generated based on the returned keys:

```ts
const plugin = {
  load(id) {
    if(id === '\0$page') {
      const page = provider.getVirtualPageMethods()
      const methods = Object.keys(page)
      return `
		const rpc = () => __vitest_worker__.rpc
		${methods.map(method => `export const ${method} = (...args) => rpc('$page', ${method}, ...args)`}
      `
    }
  }
}
```
