### ISSUE TITLE
Native GitHub Annotations support when run on CI

### ISSUE THREAD

**Issue by fregante** [vitest-dev/vitest#4919]
### Clear and concise description of the problem

I'd like errors to automatically appear in the Files tab on on GitHub PRs, like when using Jest:

https://jestjs.io/blog/2022/04/25/jest-28#github-actions-reporter

![28-gh-actions-reporter-1ee03f15b770cc9e04bb15ad1a532e1d](https://github.com/vitest-dev/vitest/assets/1402241/d637bd55-f436-4c91-8f96-3fb66eb6f7ea)

### Suggested solution

Unlike Jest's setup, I think Vitest could just detect and automatically output comments to enable these annotations. It's relatively little code, see https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message

```
::error file={name},line={line},endLine={endLine},title={title}::{message}
```

But actually you should be able to add a single matcher instead, so that GHA automatically picks up your own reporter (however this would only work with the native reporter)

https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md

### Alternative

This is already possible via 3rd party reporters

https://github.com/sapphi-red/vitest-github-actions-reporter

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Does jest actually have it out-of-the box? I'm sure bun has it.

I think it would be nice to support this if it comes without additional dependencies.

**Comment by fregante** [comment]
> Does jest actually have it out-of-the box? I'm sure bun has it.

Yep, I just used it in https://github.com/pixiebrix/pixiebrix-extension/pull/7315, you can see them in https://github.com/pixiebrix/pixiebrix-extension/pull/7315/commits/89e05e1cd5ca6e7231d948af154c1109517653f1
