### ISSUE TITLE
Exclude setting in vitest config doesn't work with file paths that contain parentheses/brackets

### ISSUE THREAD

**Issue by maurer2** [vitest-dev/vitest#4940]
### Describe the bug

Hello, I noticed that the exclude-option in `vitest.config.ts` doesn't work for file paths that contain parentheses/brackets, e.g. file paths like `src/(test)/file.spec.ts`. Normally, this wouldn't be an issue as parentheses/brackets in are rarely used for file paths, but in Next13/14, folders in parentheses/brackets are used for [route grouping](https://nextjs.org/docs/app/building-your-application/routing/route-groups). At the moment, tests in route groups can't be disabled.

### Reproduction

I created an example repo [here](https://github.com/maurer2/vitest-brekkies-in-path-issue-example).

```ts
// vitest.config.ts
import react from '@vitejs/plugin-react';
import { defineConfig } from 'vitest/config';
import { configDefaults } from 'vitest/config';

export default defineConfig({
  plugins: [react()],
  test: {
    exclude: [
      ...configDefaults.exclude,
      'src/tests/(with-parentheses)/test.spec.ts', // is not excluded
      'src/tests/without-parentheses/test.spec.ts', // is excluded
    ],
  },
});
```

When running vitest via `npm run test` "src/tests/(with-parentheses)/test.spec.ts" is still executed, even tho it is disabled, while "src/tests/without-parentheses/test.spec.ts" is not executed, which is intended.

### System Info

```shell
vitest: 1.1.3,
node: 20
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
It might not be documented properly but Vitest uses fast-glob/micromatch and it looks like they support double backslash `\\` to escape special characters.
- https://github.com/mrmlnc/fast-glob?tab=readme-ov-file#advanced-syntax

I tested this on stackblitz https://stackblitz.com/edit/github-4hjjeo?file=vitest.config.ts

**Comment by maurer2** [comment]
Hello, that seems to be the fix. Thanks!

**Comment by sheremet-va** [comment]
> It might not be documented properly but Vitest uses fast-glob/micromatch

I am not sure how it can be more obvious (from the docs):

> Files to exclude from the test run, using glob pattern.

Do we need to add a link to how glob pattern works?

**Comment by hi-ogawa** [comment]
Does Vitest doc mention exact library it uses (namely `fast-glob` and `micromatch`)? I was kinda comparing with Vite documentation, which explicitly mentions `picomatch` with a link to picomatch's README in a few places, for example https://vitejs.dev/config/server-options.html#server-fs-deny

**Comment by sheremet-va** [comment]
> Does Vitest doc mention exact library it uses

No, we don't mention what library is used. And I'd say it is a bad idea to mention implementation details like that. Glob pattern is a standard and it shouldn't depend on what implementation we use.

**Comment by maurer2** [comment]
Perhaps a small hint like, "Please be aware, that certain characters like () need to be escaped" would suffice?
