### ISSUE TITLE
`await vi.hoisted` not hoisted when used alone

### ISSUE THREAD

**Issue by hi-ogawa** [vitest-dev/vitest#4941]
### Describe the bug

Test file:

```ts
import { test, vi } from 'vitest';

import {} from './hello';

await vi.hoisted(async () => {
  console.log('async hoisted?');
});

test('ok', () => {});
```

`VITE_NODE_DEBUG_DUMP` output:

```ts
const __vite_ssr_import_0__ = await __vite_ssr_import__('vitest', {
  importedNames: ['test', 'vi'],
});
const __vite_ssr_import_1__ = await __vite_ssr_import__('/test/hello.ts');

await __vite_ssr_import_0__.vi.hoisted(async () => {
  console.log('async hoisted?');
});
__vite_ssr_import_0__.test('ok', () => {});
```

It looks like alone `await vi.hoisted` managed to escape from this regular expression:

https://github.com/vitest-dev/vitest/blob/9ec3f743edfd0a5996a4c6eced35bbf95cf1604e/packages/vitest/src/node/hoistMocks.ts#L61-L62

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-gtq5a4?file=debug-copy%2Fdump%2F_home_projects_vitest-dev-vitest-gtq5a4_test_repro_test_ts--609867655.js

### System Info

```shell
(stackblitz)

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: latest => 1.1.3 
    vite: latest => 5.0.11 
    vitest: latest => 1.1.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Thanks for the investigation. Just improving detecting regexp should be enough.
