### ISSUE TITLE
No such file or directory for coverage files

### ISSUE THREAD

**Issue by C0ZEN** [vitest-dev/vitest#4943]
### Describe the bug

After the migration to Vite 5, I started having flaky failing tests due to unfound coverage files, but only on the CI (GitHub actions).

```shell
Error:  
⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
Error:  Error: ENOENT: no such file or directory, open '/home/runner/actions-runner/_work/x/.tmp/coverage-9.json'
Error:  ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error:  Serialized Error: { errno: -2, code: 'ENOENT', syscall: 'open', path: '/home/runner/actions-runner/_work/x/.tmp/coverage-9.json' }
Error:  
```

Note that I use Nx to run the tests.

### Reproduction

N/A

### System Info

```shell
GitHub Actions
Vitest 1
Vite 5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
I can reproduce this on watch mode. If test re-run is triggered while current run is looping through coverage results, the next run will remove the files and earlier run will cause this error. 

In browser mode this is easily reproducible by opening Vitest UI in multiple tabs.

**Comment by AriPerkkio** [comment]
After testing multiple different solutions for this, I think the best option is to make coverage providers aware of earlier runs. They should keep similar `runningPromise` reference as Vitest's `core.ts` does. In `CoverageProvider.clean()` we would check if `runningPromise` is still defined, `await` it if it is, and only after that allow `clean()` to continue. In `CoverageProvider.reportCoverage()` the `runningPromise` would be resolved at the end. After some testing this solution seems to work the best.

In `clean()` there could even be a warning logged if `runningPromise` is defined. Something like `'Warning: Trying to start new coverage collection before earlier run ended. Waiting for earlier run to finish before starting.'`.

I've also tried to implement some kind of cancelling mechanism to abort earlier runs. Not sure if that's needed.
