### ISSUE TITLE
Cannot import from external URLs

### ISSUE THREAD

**Issue by sagargurtu** [vitest-dev/vitest#4949]
### Describe the bug

Vitest is not able to export from external URLs.

### Reproduction

Working Vite Example: https://stackblitz.com/edit/vitejs-vite-krutmh
Nonworking Vitest Example: https://stackblitz.com/edit/vitest-dev-vitest-fn6bpu?file=src%2Fbasic.js

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: latest => 1.2.0 
    vite: latest => 5.0.11 
    vitest: latest => 1.2.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Thanks for the repro. I remembered Vite's SSR doesn't seem to support network imports yet:
- https://github.com/vitejs/vite/issues/15143

Interestingly, the issue on Vitest (vite-node) might be actually different. Vite seems to get error during `ssrLoadModule` (while `transformRequest` seems to be working fine) but Vite-node doesn't use this API and also the stack trace suggests Vitest is failing during `loadAndTransform`.

**Comment by sagargurtu** [comment]
Thank you for providing the workaround. Will it become the official solution, or will Vitest incorporate this logic internally?

**Comment by hi-ogawa** [comment]
I think users should be still responsible for enabling `--experimental-network-imports` (unless you're using Vitest browser mode), but the other part `external: [/^https:/]` could be handled by Vitest (vite-node) automatically just like `data:...` is always treated as external:

https://github.com/vitest-dev/vitest/blob/0b28f30153bce95e26cd343ad7a6a6f0c22518a2/packages/vite-node/src/externalize.ts#L97-L100
