### ISSUE TITLE
Latest vitest and happy-dom with useFakeTimers - Test runner is stuck forever

### ISSUE THREAD

**Issue by aversini** [vitest-dev/vitest#4951]
### Describe the bug

Test runner is stuck with the most recent versions of both Vitest (1.2.x) and HappyDom (13.x). If one of the version is reduced (Vitest to 1.1.3 or HappyDom to 12.x), then the test is running fine.

### Reproduction

- Install vitest 1.2.x
- Install happy-dom 13.x
- Use "vi.useFakeTimers()"
- Run the test (vitest run)
- The test is stuck and never return to the command line

Repo to reproduce the issue: https://stackblitz.com/edit/vitest-dev-vitest-bhbpda?file=src%2Findex.ts

This issue may have been introduced by this recent PR: https://github.com/vitest-dev/vitest/pull/4931
I tried to play around with this PR, and by just changing [this line](https://github.com/vitest-dev/vitest/pull/4931/files#diff-735bd96f189ba7a0e6aad1ddb67c2329a44f320fb62aa3e0a7fa30847ab8cbeaR6),
from 
```js
await win.happyDOM.abort()
```
to
```js
win.happyDOM.abort()
```
it does lift the block... however win.happyDOM.abort returns a Promise, so it does not seem right.

cc @capricorn86 

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 102.05 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 4.0.2 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
  Browsers:
    Chrome: 120.0.6099.216
    Edge: 120.0.2210.133
    Safari: 17.2.1
    Safari Technology Preview: 17.4
  npmPackages:
    @vitest/coverage-v8: 1.2.0 => 1.2.0
    @vitest/ui: 1.2.0 => 1.2.0
    vitest: 1.2.0 => 1.2.0
    happy-dom: 13.0.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by capricorn86** [comment]
This seem to be related to `vi.useFakeTimers()`. Removing that statement makes the tests run through.

`await win.happyDOM.abort()` is trying to abort ongoing timers, but perhaps it collides with the internal logic inside Vitest.

**Comment by capricorn86** [comment]
I have found the issue and will soon have a fix in Happy DOM.

Task https://github.com/capricorn86/happy-dom/issues/1210 created.

**Comment by capricorn86** [comment]
@aversini this has been fixed now in the latest version of Happy DOM:
https://github.com/capricorn86/happy-dom/releases/tag/v13.0.7

**Comment by aversini** [comment]
@capricorn86 the issue is indeed gone with your recent fix, thanks for the speedy attention and the amazing work you do on Happy DOM ✨

**Comment by capricorn86** [comment]
Thank you @aversini!
