### ISSUE TITLE
Playwright-style automatic fixtures

### ISSUE THREAD

**Issue by jakebiesinger-storyhealth** [vitest-dev/vitest#4953]
### Clear and concise description of the problem

Playwright has a notion of [automatic fixtures](https://playwright.dev/docs/test-fixtures#automatic-fixtures), where the fixture is executed even if it is not part of the fixture dependency list in a test. This enables test writers to implicitly set up fixtures that are common to all tests of a type.

I would like to use *automatic* fixtures in vitest to establish database connections in my integration tests rather than having to explicitly specify `{ testDb }` as a fixture dependency in all of my tests.

### Suggested solution

Playwright has a nice API for this, where you pass a tuple of `[fixtureBody, config]` instead of directly passing only the fixture body, something like:

```ts
export const myTest = test.extend({
  testDb: [

    async ({}, use) => { await setUpDb(); await use(); await tearDownDb(); },

    { auto: true } // <-- config object

  ],
 someOtherFixture: ...
})
```

It looks like the idea of fixture config [was also present](https://github.com/larsthorup/vitest-fixture/blob/main/doc/api.md#fixture-scope) in the original `vitest-fixtures` package, but may have only been for fixture scope.

This aligns nicely with playwright's API and gives a path for future expansions of fixture-specific config (scopes, etc as playwright does).

### Alternative

Maybe we could expose a way to access the fixtures themselves, and then wrap our tests / before* calls in some helper method that calls the fixtures manually, but this seems like it'd be very confusing.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
Is this essentially equivalent to having `beforeEach(({ testDb }: any) => {})` for each file? I made small example here:

https://stackblitz.com/edit/vitest-dev-vitest-zkknqx?file=test%2Ffixture.test.ts

It might be still clumsy to do for each test file, but I guess it's less tedious than doing so in each test with `{ testDb }`.

**Comment by jakebiesinger-storyhealth** [comment]
Yeah that's a good point @hi-ogawa. The timing is a bit different since fixtures generally all complete before the `beforeEach` or `it` calls that rely on them, but you can get pretty far with a `beforeEach` in the test or the `vitest.setup.ts` file.
