### ISSUE TITLE
JUnit reporter sometimes adds ansi colors to the report

### ISSUE THREAD

**Issue by AmirTugi** [vitest-dev/vitest#4958]
### Describe the bug

Hey, from time to time the JUnit reporter adds ansi colors to my report (not sure what's the rule), and this makes the report unreadable in places like the CircleCI's test results which doesn't show ansi colors.

This is how it looks like:
<img width="1321" alt="image" src="https://github.com/vitest-dev/vitest/assets/8065975/6ee3bfc2-37d1-4c01-b7c0-08c1354d4440">

I used to have a `NO_COLOR`/`--no-color` flag, but it applies to both reporters
How can I configure the junit reporter to strip the colors?

### Reproduction

I will add a stackblitz once I manage to reproduce it in a standalone environment.
Right now I am experiencing this in my local machine.
I'll add a reproduction once I manage to create one 💪🏼 

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (12) x64 Apple M2 Max
    Memory: 23.80 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.volta/tools/image/node/20.10.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 10.2.3 - ~/.volta/tools/image/node/20.10.0/bin/npm
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 17.2.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
In your case, color highlight is probably added by testing-library (e.g. `@testing-library/react`, `@testing-library/dom`, etc...) and it looks like they adopted a little unusual convention to turning off color by `COLORS=false` https://github.com/testing-library/dom-testing-library/pull/1166

I tested an example here. Would this help use case?

https://stackblitz.com/edit/vitest-dev-vitest-8sqonh?file=src%2Fcomponents%2Finput.test.tsx

**Comment by hi-ogawa** [comment]
> I used to have a NO_COLOR/--no-color flag, but it applies to both reporters. How can I configure the junit reporter to strip the colors?

I mis-understood the request slightly. I suppose you still want to keep the color of other reporter, but just strips ansi code only from junit output. I think always stripping off from junit sounds okay to me. Maybe we can provide an option to switch if there's a strong need of preserving the color there.
