### ISSUE TITLE
Import of CSS file in lib causes tests to fail

### ISSUE THREAD

**Issue by robcaldecott** [vitest-dev/vitest#496]
### Describe the bug

Using `vitest@0.0.139` if I include a dependency that in turn tries to load CSS files then the tests will fail with `SyntaxError: Invalid or unexpected token`.

I'm guessing those CSS files (which are font imports) are not being transformed.

The library in question is an internal company React component lib that is published as both ESM and CJS. The `package.json` differentiates between CJS/ESM like this:

```
"main": "cjs/index.js",
"module": "esm/index.js",
```

`vitest` is trying to import the CJS version which includes the following code that generates the error:

```
require("@fontsource/ibm-plex-sans/300.css");
require("@fontsource/ibm-plex-sans/400.css");
require("@fontsource/ibm-plex-sans/500.css");
require("@fontsource/ibm-plex-sans/700.css");
```

I have tried adding this package to both `deps.external` and `deps.inline` but I get the same error. Is there a way to have `vitest` use the ESM version of this lib and apply the necessary loaders?

I guess the bigger picture is to not load CSS files like this as `require` is `webpack` specific? Any guidance is welcome.

### Reproduction

https://github.com/robcaldecott/vitest-css-issue

```
pnpm install
pnpm build
pnpm test
```

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 789.83 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 95.0
    Safari: 14.1.2
  npmPackages:
    @vitejs/plugin-react: ^1.1.3 => 1.1.4 
    vite: ^2.7.10 => 2.7.10 
    vitest: 0.0.139 => 0.0.139
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by robcaldecott** [comment]
Please note that `deps.inline` works fine with this lib in `0.0.137`

**Comment by robcaldecott** [comment]
```
resolve: {
    mainFields: ["module", "jsnext:main", "jsnext"],
  },
```

This fixes it (effectively reverting some recent changes I guess.)

**Comment by antfu** [comment]
Yes, that would be a workaround. But generally, I think requiring a .css file is not a good idea since it's not a valid Node.js code, which breaks the module to run on node / server-side.  	`require` is sync, but the transformation in Vite is async, which means we can't easily hijack the call to use Vite to resolve.

**Comment by robcaldecott** [comment]
@antfu I managed to knock up a sample:

https://github.com/robcaldecott/vitest-css-issue

```
pnpm install
pnpm build
pnpm test
```

I realise this isn't the best idea and `mainFields` works around this but shouldn't `deps.inline` have worked?

**Comment by Demivan** [comment]
https://github.com/robcaldecott/vitest-css-issue/pull/1 another solution is to use `exports` field in package.json

**Comment by sheremet-va** [comment]
> [robcaldecott/vitest-css-issue#1](https://github.com/robcaldecott/vitest-css-issue/pull/1) another solution is to use `exports` field in package.json

This is the solution.
