### ISSUE TITLE
The method "toHaveBeenCalledTimes" is not counting mock calls in a map with an async function, when there is at least 2 different functions

### ISSUE THREAD

**Issue by MaxenceGazeau** [vitest-dev/vitest#4975]
### Describe the bug

Hello everyone,

The method `expect(...).toHaveBeenCalledTimes` is not counting mock calls in a map with an async function as parameter, even though the mock is called as expected.
Interestingly, the first call in the map function is working fine, but not the second, regardless of what the function is or does. 
The map function and the two functions called in it must be async to reproduce the issue.

Thanks in advance for looking up this issue

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-aylpvy?file=README.md

`mainFunc` is the function tested. It maps on the array `[0,1]` and concatenates each number with the result of `func1` and `func2`.
`mainFunc` works as expected, as the `console.log` shows.
Mocking with `mockImplementation` functions `func1` and `func2` is also working as their `console.log` shows.
But the `func2` calls are not counted for the method `expect(mock2).toHaveBeenCalledTimes(2)`, only `func1` is.

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 9.68 GB / 15.82 GB
  Binaries:
    Node: 20.10.0
    npm: 10.2.3
  Browsers:
    Edge: Chromium (120.0.2210.133)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is correct behaviour. `func1` is called before the event queue is finished, but it returns result only after microtask queue is flushed which happens after the test is finished running (so when `await mainFunc` is finished, `func2` did not run yet - you can add `console.log` before assertions to confirm it). You need to await all Promises correctly to register all calls: 

```ts
await Promise.all(await mainFunc())
```

**Comment by MaxenceGazeau** [comment]
Indeed, thanks for quick response !
