### ISSUE TITLE
Method getUnhandledErrors called on RPC, but does not exist and throws error

### ISSUE THREAD

**Issue by enjikaka** [vitest-dev/vitest#4983]
### Describe the bug

Running my tests in vitest browser mode with Playwright throws an error inside the vitest JS-bundle.

<img width="1048" alt="Skärmavbild 2024-01-16 kl  20 01 04" src="https://github.com/vitest-dev/vitest/assets/877455/3afd30c0-fa3c-4be6-b485-1386ad31e458">

<img width="1297" alt="Skärmavbild 2024-01-16 kl  20 01 16" src="https://github.com/vitest-dev/vitest/assets/877455/3e543505-5be8-4eec-b980-7422a504c1bc">

https://github.com/vitest-dev/vitest/blob/39814357024e96b81546ec22d6aaf777b8db6cef/packages/ui/client/composables/client/index.ts#L79

### Reproduction

- git clone https://github.com/enjikaka/rutabaga-failing-vitest
- run `npm test`

### System Info

```shell
System:
    OS: macOS 12.7.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 2.76 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.nvm/versions/node/v18.18.2/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.2/bin/npm
    bun: 1.0.22 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 120.1.61.109
    Chrome Canary: 122.0.6249.0
    Safari: 17.1.2
  npmPackages:
    @vitest/browser: ^1.2.0 => 1.2.0
    vite: ^5.0.11 => 5.0.11
    vitest: ^1.1.3 => 1.1.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You have a version mismatch in your dependencies. Vitest and vitest/browser should be the same version - maybe that's the problem?

**Comment by enjikaka** [comment]
> You have a version mismatch in your dependencies. Vitest and vitest/browser should be the same version - maybe that's the problem?

Syncing the versions helped! Thanks.

I suppose the peerDependencies of `@vitest/browser` should be updated to 1.2.0 and not allow lower version then?

**Comment by sheremet-va** [comment]
Yes, it should be!

**Comment by enjikaka** [comment]
Made a PR!

**Comment by AriPerkkio** [comment]
I think correct way to solve this would be to conditionally use `getUnhandledErrors` and not crash when older version of `vitest` is used with latest `@vitest/browser`.

**Comment by sheremet-va** [comment]
> I think correct way to solve this would be to conditionally use `getUnhandledErrors` and not crash when older version of `vitest` is used with latest `@vitest/browser`.

Can you explain why you think this would be better?
