### ISSUE TITLE
vite+ts+vitest，安装了echarts，jsdom，测试echarts.setOption会失败退出进程，没有任何报错提示

### ISSUE THREAD

**Issue by shenxiang216** [vitest-dev/vitest#4990]
### Describe the bug

vite+ts+vitest，安装了echarts，jsdom，测试echarts.setOption会失败退出进程，没有任何报错提示

### Reproduction

vite+ts+vitest，安装了echarts，jsdom，测试echarts.setOption会失败退出进程，没有任何报错提示

### System Info

```shell
vite+ts+vitest，安装了echarts，jsdom，测试echarts.setOption会失败退出进程，没有任何报错提示
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I don't understand a word.

**Comment by shenxiang216** [comment]
现在解决了，需要在vite.config.ts的test字段增加experimentalVmThreads: true,原因未知

**Comment by shenxiang216** [comment]
> I don't understand a word.我一个字也听不懂。

我描述一下我的问题：我现在要为一个使用echarts的项目用vitest写单元测试，echarts的绘制方法：echarts.setOption(),vitest执行到这里就会退出进程，没有任何提示。现在我解决了，方法是在vite.config.ts的test字段增加experimentalVmThreads: true,想问下原因是什么？

**Comment by sheremet-va** [comment]
Please, use English when describing an issue.

**Comment by shenxiang216** [comment]
> Please, use English when describing an issue.描述问题时请使用英语。

Wǒ miáoshù yīxià wǒ de wèntí: Wǒ xiànzài yào wéi yīgè shǐyòng echarts de xiàngmù yòng vitest xiě dānyuán cèshì,echarts de huìzhì fāngfǎ:Echarts.SetOption(),vitest zhíxíng dào zhèlǐ jiù huì tuìchū jìnchéng, méiyǒu rènhé tíshì. Xiànzài wǒ jiějuéle, fāngfǎ shì zài vite.Config.Ts de test zìduàn zēngjiā experimentalVmThreads: True, xiǎng wèn xià yuányīn shì shénme?
展开
​
171 / 5,000
翻译结果
翻译结果
Let me describe my problem: I am now going to use vitest to write a unit test for a project that uses echarts. The drawing method of echarts: echarts.setOption(), vitest will exit the process after executing it here without any prompt. Now I have solved the problem by adding experimentalVmThreads: true in the test field of vite.config.ts. I would like to ask what is the reason?

**Comment by sheremet-va** [comment]
> The drawing method of echarts: echarts.setOption(), vitest will exit the process after executing it here without any prompt. Now I have solved the problem by adding experimentalVmThreads: true in the test field of vite.config.ts. I would like to ask what is the reason?

I don't know, I don't think it is related. Vitest also doesn't have `experimentalVmThreads` flag since 1.0, please use the latest supported version before submitting an issue.
