### ISSUE TITLE
File filter is being ignored when using `--typecheck` and passing the filter using `npm run <command> -- <filter>`

### ISSUE THREAD

**Issue by murolem** [vitest-dev/vitest#4998]
### Describe the bug

When running the `test` npm command (with the command being `vitest --typecheck`) using `npm run` with passthrough file filter argument `npm run test -- foo.test.ts`, the file filter `foo.test.ts` is being ignored, resulting in all tests running.

> ![image](https://github.com/vitest-dev/vitest/assets/20380250/c8418b36-20a7-47b8-8ef4-26e76f185a96)

### Reproduction

Minimal repo: https://github.com/murolem/vitest-issue-typecheck-ignores-file-filter

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 10.16 GB / 31.93 GB
  Binaries:
    Node: 21.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.133)
  npmPackages:
    vite: ^5.0.11 => 5.0.11
    vitest: ^1.2.1 => 1.2.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Not ideal but to workaround this issue, using `--typecheck.enabled` instead of `--typecheck` should achieve what you're probably intend to do.

**Comment by murolem** [comment]
> Not ideal but to workaround this issue, using `--typecheck.enabled` instead of `--typecheck` should achieve what you're probably intending to do. Also, setting `typecheck: { enabled: true }` is also possible if you want to enable type-checking for any `vitest` run.

Thanks!

I resolved it by the setting the config option, but still wanted to report the issue.
