### ISSUE TITLE
Typecheck checking types in files not related to test files

### ISSUE THREAD

**Issue by murolem** [vitest-dev/vitest#4999]
### Describe the bug

Typecheck is checking ALL the types in the project (specified by the `tsconfig`), but I would expect it to only check the types that are related to the test files: test files themselfs and the file hierarchy of the imported files.

`ignoreSourceErrors` option just ignores all non-test files, which is undesirable.

### Reproduction

Minimal repo: https://github.com/murolem/vitest-issue-typecheck-checks-types-outside-of-desired-range

You can check this behavior by running these commands: `test:fn-with-type-errors` and `test:fn-without-type-errors`:
- First tests an imported function with a type error in its source file.
- Second tests an imported function without any type errors in its source file.

You can also observe the changes in behavior by switching on and off the `ignoreSourceErrors` option in the vite config.

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 10.15 GB / 31.93 GB
  Binaries:
    Node: 21.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.133)
  npmPackages:
    vite: ^5.0.11 => 5.0.11 
    vitest: ^1.2.1 => 1.2.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is expected behavior. Typechecker runs `tsc --noEmit` under the hood and reports all errors.

**Comment by sheremet-va** [comment]
It already analyses it. 

There are test files and there is source code. If the error happens in the source code, it is treated as a source error, not a test error. This is intentional because there is no guarantee that the error is connected to the test (what if it's inside a function that you didn't call in your test?) since it's analyzed statically. There are no immediate plans to change that but there are plans to improve the feature by using another tool (not just running `tsc --noEmit`) for this.
