### ISSUE TITLE
json-summary output messed json file when use shard argument to split test task

### ISSUE THREAD

**Issue by Marckon** [vitest-dev/vitest#5012]
### Describe the bug

I am using json-summary reporter to generate coverage-summary.json file. When split my test task by adding `shard` argument in cli, the output file is wrong, which is messed json string. like below:
![image](https://github.com/vitest-dev/vitest/assets/24504081/abf711c0-2167-4553-817b-7a6fac2cd26a)

### Reproduction

command line is:
```bash
$ TEST_ENV=unittest vitest  -- --no-watch --shard 1/2  --minWorkers 2 --no-color --maxWorkers 4 --coverage
```
config is:
```
export default defineConfig({
  test: {
    coverage: {
      reporter: ['text', 'json', 'html', 'json-summary'],
      include: ['framework/**', 'plugins/**'],
      exclude: ['**/*.vitest.{js,ts}', '**/src/index.ts'],
    },
```

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 221.02 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/work/doc/node_modules/.bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.9.0/bin/yarn
    npm: 10.2.3 - ~/work/doc/node_modules/.bin/npm
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 17.2.1
    Safari Technology Preview: 17.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Are you running multiple `vitest` commands at the same time? It could be that both of those processes are writing into same file at the same time.

**Comment by Marckon** [comment]
> Are you running multiple `vitest` commands at the same time? It could be that both of those processes are writing into same file at the same time.
yes. I know this could be the reason. However, html output is correct.
