### ISSUE TITLE
Coverage Report Path in Browser Mode Does Not Consider "reportsDirectory"

### ISSUE THREAD

**Issue by oscarmarina** [vitest-dev/vitest#5013]
### Describe the bug

Hello,

I am experiencing an issue with the coverage report in Vitest when using Browser Mode with a web component built with Lit. When I run the tests and try to view the coverage, the page is blank. It seems that the coverage report is looking for the folder at the root of the project, not taking into account the reportsDirectory setting in my vite.config.js file.

`  reportsDirectory: `./test/coverage/`,`

<img width="1187" alt="reportsDirectory " src="https://github.com/vitest-dev/vitest/assets/3649029/9ff05558-4160-4dd6-9943-999273c7905f">

==

I would like to suggest an improvement for the LCOV reporter. Currently, the LCOV reporter generates the same files as the HTML reporter. However, I believe the LCOV reporter could be improved by creating a separate folder for its output. This would keep everything more organized, instead of leaving all the files in the root of the /coverage folder. Furthermore, when the Vitest UI is activated, the LCOV reporter is "equated" to the HTML reporter for generating the report view.

### Reproduction

You can reproduce this issue by downloading the repository from my GitHub or viewing it on Stackblitz.

https://github.com/oscarmarina/lit-vitest-testing-comparison

https://stackblitz.com/github/oscarmarina/lit-vitest-testing-comparison

```bash
npm i && npm run test
```

### System Info

```shell
System:
    OS: macOS 12.7.2
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
    Memory: 17.82 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.3.0 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.6.5 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
  Browsers:
    Chrome Canary: 122.0.6257.0
    Safari: 17.2.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Has this been working with earlier versions of Vitest?

I think this part of the UI is the root cause. For some reason the `reportsDirectory` is sliced from the last `/`, so your `./test/coverage` becomes just `/coverage`.

https://github.com/vitest-dev/vitest/blob/7314857559ebff0e5b5fe19cfc6615c88e33389e/packages/ui/client/composables/navigation.ts#L15-L30

> I would like to suggest an improvement for the LCOV reporter. Currently, the LCOV reporter generates the same files as the HTML reporter.

These built-in reporters are provided by Istanbul. Changes for them should be requested at https://github.com/istanbuljs/istanbuljs.

But it sounds like you should rather use `lcovonly` reporter if you have `html` reporter enabled:

> ## `lcov`
> Same as `lcovonly`, but also generates a HTML report you can view in your browser
>
> https://istanbul.js.org/docs/advanced/alternative-reporters/#lcov

**Comment by oscarmarina** [comment]
Hi @AriPerkkio, this is the first time I use vitest, I don't know if it worked before, sorry.

>  I explained poorly about lcov, what I was suggesting is to be able to use lcov to activate the coverage tab

<img width="740" alt="lcov-active" src="https://github.com/vitest-dev/vitest/assets/3649029/4e41f9e6-8712-43d0-9ebc-44ba79002d14">

**Comment by hi-ogawa** [comment]
I think currently there's a difference between "vitest:browser" middleware plugin and "vitest:ui" plugin. "vitest:browser" only serves its own html/js assets but "vitest:ui" also serves generated coverage html: 

https://github.com/vitest-dev/vitest/blob/d53b85805d2a893276aaf19c9e746d13ad5174f2/packages/browser/src/node/index.ts#L25-L28

https://github.com/vitest-dev/vitest/blob/d53b85805d2a893276aaf19c9e746d13ad5174f2/packages/ui/node/index.ts#L20

This "server side" code might also need to be adjusted for coverage preview on (headed) browser mode.

**Comment by oscarmarina** [comment]
Hi, I've set up a branch using `provider: 'playwright'`, just as a helpful reference.

- https://github.com/oscarmarina/lit-vitest-testing-comparison/tree/feature/playwright

**Comment by userquin** [comment]
On my Windows laptop I can see this weird error when running the reproduction:

![imagen](https://github.com/vitest-dev/vitest/assets/6311119/a806ebd4-cb65-47d9-af4b-3e3381ed05ba)

**Comment by userquin** [comment]
The problem seems to be here: https://github.com/oscarmarina/lit-vitest-testing-comparison/blob/main/index.html#L8

If I change previous line using absolute path `/demo/index.html`, the coverage folder showing the example:

![imagen](https://github.com/vitest-dev/vitest/assets/6311119/8d9772de-71c4-4865-8640-469e44533cd7)

**Comment by userquin** [comment]
Vitest getting this error:
![imagen](https://github.com/vitest-dev/vitest/assets/6311119/3d00fa53-a875-49b5-a1a9-7b1c88990851)

**Comment by userquin** [comment]
`@vitest/ui` plugin not being included since ui is false and browser package not including coverage logic, so #5056 seems to be fine.

**Comment by oscarmarina** [comment]
hi @userquin 
the [istanbul HTML report](https://istanbul.js.org/docs/advanced/alternative-reporters/) looks like this:

<img width="1409" alt="image" src="https://github.com/vitest-dev/vitest/assets/3649029/6813eaa2-f1de-496e-8168-1ed755384e1e">

====
When you remove this line the "coverage" folder is created in the root of the project that's when it works fine

<img width="646" alt="image" src="https://github.com/vitest-dev/vitest/assets/3649029/56e0e0b7-c8e5-44c8-aedc-2e308508fd45">

**Comment by userquin** [comment]
It works (when removing the directory option) because it is on the root, once you include the report directory the client will request `/coverage/index.html` and since there is no middleware to serve `/coverage/` requests from the `test/coverage` directory, it fails, there is no `coverage` folder in root.

IIRC I did the original PR to include coverage in the ui :sweat_smile:
