### ISSUE TITLE
Vitest hangs when running a typecheck for a test file with nested `describe` and another `test`/`describe` adjacent

### ISSUE THREAD

**Issue by murolem** [vitest-dev/vitest#5021]
### Describe the bug

Vitest hangs when running a test file in typecheck mode, when the file contains:
-  a `describe` nested in another `describe`. Any tests inside the latter don't matter.
- a `test`/`describe` adjacent to the first `describe`.

The terminal also becomes unresponsive, only help is closing it. 

Interestingly, if the nested `describe` is replaced with a `test`, everything works is expected. Also, adding a `test` instead of replacing it seems to help too.

### Reproduction

**Repo:** https://github.com/murolem/vitest-issue-typecheck-test-hangs-on-nested-describe

**Steps:**
1. Run `npm run test`.
2. Observe the issue. Comment/uncomment different `test`s and `describe`s to see the changes in behaviour.

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 6.54 GB / 31.93 GB
  Binaries:
    Node: 21.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.144)
  npmPackages:
    vite: ^5.0.11 => 5.0.11 
    vitest: ^1.2.1 => 1.2.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Reproduction case is getting stuck here:

https://github.com/vitest-dev/vitest/blob/36bc6997c41e6b7aacc05c3d75f391d2bdcd2b77/packages/vitest/src/typecheck/collect.ts#L103-L104

**Comment by hi-ogawa** [comment]
Probably same issue https://github.com/vitest-dev/vitest/issues/4964? though your reproduction is more concise

**Comment by murolem** [comment]
> Probably same issue #4964? though your reproduction is more concise

Seems like it.
