### ISSUE TITLE
Problem with apollo client

### ISSUE THREAD

**Issue by Xa3lis** [vitest-dev/vitest#503]
### Describe the bug

Hello, i've a bug with `@apollo/client/core` in my project where i cannot launch any test (Works on jest tho)

I have a file where I import and create the Apollo client :

![image](https://user-images.githubusercontent.com/8726129/148987290-629d65ba-c630-4ea3-9845-22b1c549a964.png)

And a file where I use the client :

![image](https://user-images.githubusercontent.com/8726129/148987423-eebdf13a-b975-4cdc-8c06-57edf4ac080a.png)

In my test I try to use that `getCurrentUser` function as mock

![image](https://user-images.githubusercontent.com/8726129/148987662-3e8d9d7d-5a29-4ee2-bd1a-e0c5ebec5556.png)

But when I launch a `vitesse run` i got a weird error...

![image](https://user-images.githubusercontent.com/8726129/148987923-fdbb37df-2853-4d9f-97f1-83e384c1212c.png)

Any idea ?

Thank's

### Reproduction

Check screens in the description

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 601.49 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    npm: 8.1.3 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Browsers:
    Brave Browser: 97.1.34.80
    Chrome: 97.0.4692.71
    Firefox: 89.0.2
    Firefox Developer Edition: 88.0
    Safari: 15.1
  npmPackages:
    @vitejs/plugin-vue: ^1.10.2 => 1.10.2 
    vite: ^2.7.10 => 2.7.10 
    vitest: ^0.0.132 => 0.0.132
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Can you provide a reproduction with stackblitz please? It will speed up fixing your problem 👀

**Comment by Xa3lis** [comment]
[Here](https://stackblitz.com/edit/node-7pqfrx?file=apollo/client.ts)

But the only thing i got is `unexpected token '}'` from @apollo...

When I build my project with vite, everything works, but i think CommonJS (Apollo still have some CJS module) doesn't works well with Vitest...

**Comment by Xa3lis** [comment]
In my local, i have the error shown upper

**Comment by Xa3lis** [comment]
Problem solved adding 

```
deps: {
      inline: ['@apollo/client', 'ts-invariant'],
      interpretDefault: true,
    }
```
