### ISSUE TITLE
Importing mocks causes "unexpected eof" error

### ISSUE THREAD

**Issue by SheldonWBM** [vitest-dev/vitest#5033]
### Describe the bug

This error occurs after bumping vitest from 1.2.0 to 1.2.1
"Unexpected eof"

### Reproduction

I have a file `myMockedFunction.ts` with the following:
```
import myComponent from 'the-component-package';
import { vi } from 'vitest';

export default vi.mock('the-component-package', async () => {
  const actual: typeof myComponent =
    await vi.importActual('the-component-package');
  return {
    ...actual,
    theProperty: vi.fn(),
    theSecondProperty: vi.fn(),
  };
});
```

In `myTest.test.tsx` I have
```
import '../myMockedFunction'
describe('MyComponent', () => {
  beforeEach(() => {
  ...
  })
  it('Does stuff', async () => {
  ...
  })
})

```
I tried using a named import and putting it in `beforeEach`. I also tried using `vi.mocked`

This worked until 1.2.1 when I had to move the imported mocks to be used directly in the *.test.tsx files.
For mocks that get used in multiple places, I like to keep them in dedicated files. 

### System Info

```shell
Docker container.
FROM node:lts-alpine
react: 18.2.0
vite: 5.0.12
vitest: 1.2.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Removing `export default` should help. `vi.mock` doesn't return anything so there is no need to export it. Vitest should throw the same error it does for `vi.hoisted`

**Comment by SheldonWBM** [comment]
Thank you @sheremet-va, that works  :100:
