### ISSUE TITLE
Absolute paths doesn't work in test.include[] config on Windows

### ISSUE THREAD

**Issue by Jinjiang** [vitest-dev/vitest#5038]
### Describe the bug

The absolute path like `'C:\\Users\\zhaoj\\code\\reproductions\\**\\*.spec.*'` in [`test.include[]`](https://vitest.dev/config/#include) doesn't work, however `**/*.spec.*` works as expected.

For some reasons, we have to specify the test.include in absolute paths on Windows. And the project is actually migrated from jest which works with them. Now our Windows users can not run the tests locally.

### Reproduction

https://github.com/Jinjiang/reproductions/tree/vitest-win-20240124

on Windows, run `pnpm install` and then `pnpm test`

### System Info

```shell
(Not able to run it on Windows prompt)
Node version: v20.11.0
Windows 11 prompt
"vite": "^5.0.12",
"vitest": "^1.2.1"
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`test.include` uses [fast-glob](https://www.npmjs.com/package/fast-glob). And it doesn't support backslashed for Windows: https://www.npmjs.com/package/fast-glob#how-to-write-patterns-on-windows

**Comment by Jinjiang** [comment]
It works. Thanks a lot!
