### ISSUE TITLE
defineWorkspace does not allow configs to be specified as functions

### ISSUE THREAD

**Issue by jbms** [vitest-dev/vitest#5040]
### Describe the bug

defineWorkspace does not allow individual project configurations to be specified as a function.

For example, in `vitest.workspace.mts`:

```typescript
export define defineWorkspace([
  configEnv => ({ ... }),
});
```

While the typescript types permit it, it fails at runtime.

The problem occurs here:
https://github.com/vitest-dev/vitest/blob/cfd06118730098b9a15540d609d2fa2b598c866e/packages/vitest/src/node/core.ts#L310

The `options` variable is bound to the function specified as a member of the array passed to `defineWorkspace`, and then an error is thrown by `mergeConfig`.

### Reproduction

n/a

### System Info

```shell
n/a
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Thanks for raising an issue with pointers to the code. 

I made a reproduction just in case https://stackblitz.com/edit/vitest-dev-vitest-rdnavt?file=vitest.workspace.ts

```
Error: Cannot merge config in form of callback
```

From the quick look, I'm not sure if it's possible to support function config, but if that's the case, Vitest needs to adjust typing.

**Comment by sheremet-va** [comment]
I think it should be possible to support a function config, we just need to await the function.

**Comment by hi-ogawa** [comment]
I wonder what is the use case to control config using `(configEnv) => { ... }` since `vitest.workspace.ts` is loaded by vitest. Out of these four, I think `env.mode: "test" | "benchmark"` is the only thing potentially matters.

@jbms Can you maybe clarify your use case with function config?

```tsx
import { defineWorkspace } from 'vitest/config'

export default defineWorkspace([
  (env) => {
    env.mode; // "test" or "benchmark"
    env.command; // "serve"
    env.isPreview; // false
    env.isSsrBuild; // false
    return {};
  }
])
```

**Comment by sheremet-va** [comment]
> Out of these four, I think `env.mode: "test" | "benchmark"` is the only thing potentially matters.

It is possible to override it with `--mode` CLI flag. Another possible use case is reusing the main config since it's not enabled by default:

```ts
import viteConfig form './vite.config'
export default [viteConfig, { root: './another-config' }]
```
