### ISSUE TITLE
benchmarks don't work with browser runner

### ISSUE THREAD

**Issue by jbms** [vitest-dev/vitest#5041]
### Describe the bug

Benchmark fails with:

```
Test function is not found. Did you add it using `setFn`?
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-qvjudf?file=package.json

### System Info

```shell
n/a
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vekexasia** [comment]
Just happened to me as well. Any news on this?

**Comment by jacomyal** [comment]
It would be so great to have such a simple tool for benchmarking scripts in a browser environment! Any news on this?

**Comment by jacomyal** [comment]
That is so awesome, thank you very much :heart:
