### ISSUE TITLE
support reporter options

### ISSUE THREAD

**Issue by hi-ogawa** [vitest-dev/vitest#5042]
### Clear and concise description of the problem

Spinned off from https://github.com/vitest-dev/vitest/pull/5007#issuecomment-1902094894

To allow customizing reporter in a general manner (and also as Jest compatibility), Vitest should support reporter options. 

### Suggested solution

I think it's possible to support the same thing as Jest:
- https://jestjs.io/docs/configuration#reporters-arraymodulename--modulename-options
  - `reporters: [ ["name", { ...option }], ... ]`
- https://jestjs.io/docs/configuration#custom-reporters
  - option is passed via constructor

Currently Vitest doesn't assume anything about constructor arguments, so probably introducing this feature is not a breaking change:

https://github.com/vitest-dev/vitest/blob/cfd06118730098b9a15540d609d2fa2b598c866e/packages/vitest/src/node/reporters/utils.ts#L30-L37

### Alternative

Currently minor customization can be provided by environment variable
- https://github.com/vitest-dev/vitest/pull/3808

Or by using custom field in `test` config:
- https://github.com/AriPerkkio/vitest-sonar-reporter/tree/main?tab=readme-ov-file#silent

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
@hi-ogawa did you start any work on this? I think I could work on this next. I have got some feature requests related to this on my custom reporter:
- https://github.com/AriPerkkio/vitest-sonar-reporter/issues/153
- https://github.com/AriPerkkio/vitest-sonar-reporter/issues/62

**Comment by hi-ogawa** [comment]
@AriPerkkio No, I haven't made any code yet. Fell free to take it. Thanks!
