### ISSUE TITLE
The test coverage rate is not displayed in UI mode

### ISSUE THREAD

**Issue by kingcwt** [vitest-dev/vitest#5048]
### Describe the bug

I have configured the corresponding parameters in vitest.config.ts, but when running UI mode to check the test coverage, nothing is displayed

### Reproduction

<img width="1379" alt="image" src="https://github.com/vitest-dev/vitest/assets/29888469/053c45d3-e79c-4a8b-8aa3-ca40e053d26b">

<img width="1726" alt="image" src="https://github.com/vitest-dev/vitest/assets/29888469/a9b27be4-c3c1-4b72-a9c9-8abb8e371c3d">

--
Another issue is that when I remove the include attribute, although it can be displayed, it is not displayed at all__ Test__ Provide relevant successful data below

<img width="1499" alt="image" src="https://github.com/vitest-dev/vitest/assets/29888469/c3f29eb6-01ca-4284-8030-80e4d1206f98">

<img width="1714" alt="image" src="https://github.com/vitest-dev/vitest/assets/29888469/106b51f8-0d1e-4991-8e19-82fcc4c0d868">

就很奇怪

### System Info

```shell
Could you please help me take a look? Thank you
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kingcwt** [comment]
https://stackblitz.com/edit/vitest-dev-vitest-j2p5e4?file=vite.config.ts
This is also true. Why is it clear that it has already passed? The coverage rate is empty

Boss, help me take a look

<img width="1409" alt="image" src="https://github.com/vitest-dev/vitest/assets/29888469/ce6f6ed7-efab-4a1b-8d60-4755fa9b3a21">

**Comment by AriPerkkio** [comment]
In your reproduction case you have defined **test files** in `test.coverage.includes`. It should rather list **source files**. I think in the project of the picture you should rather use `test: { coverage: include: ['src/pages/**'] }`.

In general:
- `test.coverage.includes` contains list of **source files** which should be included in coverage report. For example `coverage: { include: ['src/pages/**', 'src/utils/**'] }`.
- `test.includes` contains list of **test files** that should be run. For example `test: { includes: ['src/pages/**/__tests__/**'] }` will only run tests that match this pattern.

**Comment by kingcwt** [comment]
Thank you, big shot
