### ISSUE TITLE
Coverage report should be refreshed in the UI when tests are re-run

### ISSUE THREAD

**Issue by balazsorban44** [vitest-dev/vitest#5057]
### Clear and concise description of the problem

This is re-opening #3504 since from my experience, it has not been fully addressed yet.

I'll leave the original author's description here:

When running vitest with the `--ui` and `--coverage` options, there is no convenient way to see changes to the coverage report through the UI.

I saw the related PRs, and they sound like potentially helping, but when I am looking at a certain file's coverage, re-running the test (in dev/watch mode), they don't update. Refreshing the page drops you back to the dashboard, as the coverage view is not synced to the URL.

It would be very convenient to not needing to re-navigate each time a change has been made.

---

From https://github.com/vitest-dev/vitest/issues/3504#issuecomment-1579461113

> if you're on the coverage page, it will not refresh, I'll try to reload coverage page once re-run finish...

And https://github.com/vitest-dev/vitest/issues/3504#issuecomment-1579459584

> undoing changes, re-running tests and selecting again the coverage works: myabe we can send the user to dashboard when re-running all or some tests forcing the user to select coverage again.

I did not quite understand this. The latter comment mentions you need to re-run tests, and reselect coverage manually. So the OP's request is not possible? Ie.: You are looking at a test coverage of a file, you update a related test, and the coverage auto-refreshes, without any interaction from the user's part.

---

Further note: This might be a user (me) issue, so please correct me, but if a test fails, suddenly the entire coverage is gone, it's just an empty page. It only comes back again if I make all tests pass. Is this expected? Or am I missing a config option?

### Suggested solution

It would be great if the coverage report was refreshed every time it's updated, just like the test results are, without user intervention.

### Alternative

Alternatively, the currently open report could be synced to the URL. That way the user can refresh the window and not have to navigate back to the report they were looking at earlier, but this still requires user intervention.

### Additional context

The way it currently works, I'd rather have a new tab open when I click on the coverage button on the UI, rather than show an iframe that doesn't automatically refresh or stay synced with the URL. Being able to have this behavior could also be a potential solution.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
If we server the coverage without caching in an iframe, maybe it is possible to just reload the iframe.
