### ISSUE TITLE
Inline snapshot race conditions with vmThreads

### ISSUE THREAD

**Issue by j4k0xb** [vitest-dev/vitest#5058]
### Describe the bug

When running vitest with `--pool=vmThreads` it should update the correct inline snapshots, but instead the edits happen at a different inline snapshot or other unrelated line.
It depends on the order of tests and how many there are, works again when deleting e.g. the first 4 tests

Current output:
```ts
  expect(`
    b();
    a = c();
  `).toMatchInlineSnapshot(`
  "
      b();
      a = c();
    "
``
      "
          console.log(a = (b(), c()));
        "
    `);

  expect(`
    console.log(a = (b(), c()));
  `).toMatchInlineSnapshot();
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-rufvf3?file=test%2Fbasic.test.ts

Only affects node, don't run it in StackBlitz
1. download project
2. npm install
3. npm test

### System Info

```shell
System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 5.11 GB / 15.50 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.14.1 - /usr/bin/pnpm
  Browsers:
    Brave Browser: 120.1.61.120
  npmPackages:
    @vitest/ui: latest => 1.2.2 
    vite: latest => 5.0.12 
    vitest: latest => 1.2.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Thanks for reporting an issue.

The way the bug manifested in inline snapshots is very bizarre, but the actual cause seems to be a sourcemap/stacktrace issue on `vmThreads`. For example, this simple one doesn't work either.

```
import { expect, test } from 'vitest';

test('hi', () => {
  expect('hi').toMatchInlineSnapshot();
});
```

It's likely a regression from https://github.com/vitest-dev/vitest/pull/4441 and `installSourcemapsSupport` is forgotten for vm pools. I confirmed the issue doesn't exists before Vitest v1.2.0.
