### ISSUE TITLE
expect().toThrow() unable to read `this` in class instance

### ISSUE THREAD

**Issue by saphewilliam** [vitest-dev/vitest#5060]
### Describe the bug

I'm trying to validate an error message that is thrown from within a class. The error message contains content from variables that are in the class, read from `this`. However, when I use the `toThrow` assertion, `this` seems to be set to `undefined` somehow.

I appreciate any help!

### Reproduction

```ts
import { expect, test } from 'vitest';

class Test {
  value: string;

  constructor(value: string) {
    this.value = value;
  }

  throws() {
    throw new Error(`hello ${this.value}`);
  }
}

const t = new Test('world');

test('it throws the correct message', () => {
  t.throws();
});

test('vitest cannot access `this`', () => {
  expect(t.value).toBe('world');
  expect(t.throws).toThrow('hello world');
});

```

Output:

FAIL  file.spec.ts > it throws the correct message
Error: hello world

FAIL  file.spec.ts > vitest cannot access `this`
AssertionError: expected [Function throws] to throw error including 'hello world' but got 'Cannot read properties of undefined (reading 'value')'

### System Info

```shell
System:
    OS: Linux 5.15 Linux Mint 20.2 (Uma)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 7.30 GB / 15.31 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: 8.7.6 - ~/.local/share/pnpm/pnpm
  Browsers:
    Chrome: 120.0.6099.71
  npmPackages:
    @vitest/coverage-v8: 1.2.2 => 1.2.2 
    vite: 5.0.12 => 5.0.12 
    vitest: 1.2.2 => 1.2.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`this` in JavaScript depends on how the function is called: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#bound_methods_in_classes

In your example it looses its context. You can wrap your example in an anonymous function:

```ts
 expect(() => t.throws()).toThrow('hello world');
```

**Comment by william-ford-rq** [comment]
Thank you that worked!
