### ISSUE TITLE
add type exports to the JSON reporter

### ISSUE THREAD

**Issue by david-morris** [vitest-dev/vitest#5068]
### Clear and concise description of the problem

I want to summarize json vitest output in my CI using typescript.  I want to import types for IDE functionality and the ability to type-check my summary script.

### Suggested solution

Export the existing types so that they could be imported from "vitest/reporters".

### Alternative

Factor a helper out of logTasks method of JsonReporter so that we can use indexed types for the JSON contents

### Additional context

This change would make it possible to type-check for any changes to the json format affecting an automated system reading that json output.

Keep in mind that there's no "vitest/reporters/json" because of the build step.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
Exposing the type sounds like a nice addition to me.

For the time being, I think you can manually copy-paste types from here https://github.com/vitest-dev/vitest/blob/315325eabc7e45856f2162cfb157c71c90993151/packages/vitest/src/node/reporters/json.ts#L13-L63

Example https://stackblitz.com/edit/vitest-dev-vitest-6eyewm?file=example.ts
