### ISSUE TITLE
Problem with import lodash

### ISSUE THREAD

**Issue by pionxzh** [vitest-dev/vitest#507]
### Describe the bug

After upgrate to v0.0.141, I found that `import { isString } from 'lodash'` will get `isString  === undefined`
and I try to check and debug the code, looks like this issue was introduced by the fix of #479 

Minimal reproduction code:
```
import { expect, test, assert } from 'vitest';
import { isString } from 'lodash';

test('lodash', () => {
  expect(typeof isString).toBe('function');
});
```

### Reproduction

[https://stackblitz.com/edit/vitest-lodash-issue?devtoolsheight=33&file=test/basic.test.ts](https://stackblitz.com/edit/vitest-lodash-issue?devtoolsheight=33&file=test/basic.test.ts)

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 12.70 GB / 31.89 GB
  Binaries:
    Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.14 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.55)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @vitejs/plugin-legacy: ^1.6.4 => 1.6.4
    @vitejs/plugin-vue: ^2.0.0 => 2.0.0
    vite: ~2.7.10 => 2.7.10
    vitest: 0.0.141 => 0.0.141
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jiby-aurum** [comment]
@antfu I can reproduce with vitest '0.25.2', when lodash is in `ssr.noExternal`. Minimal repo => https://stackblitz.com/edit/vitest-lodash-issue-uvdn9b?file=package.json

**Comment by sheremet-va** [comment]
> @antfu I can reproduce with vitest '0.25.2', when lodash is in `ssr.noExternal`. Minimal repo => https://stackblitz.com/edit/vitest-lodash-issue-uvdn9b?file=package.json

Please, open new issue with reproduction
