### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'transformMode')

### ISSUE THREAD

**Issue by MichaelBrandt4994** [vitest-dev/vitest#5071]
### Describe the bug

When executing vitest we receive the following error
```
⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯
TypeError: Cannot read properties of null (reading 'transformMode')
 ❯ getTransformMode node_modules/vitest/dist/vendor/execute.edwByI27.js:405:31
 ❯ Object.fetchModule node_modules/vitest/dist/vendor/execute.edwByI27.js:421:30
 ❯ VitestExecutor.directRequest node_modules/vite-node/dist/client.mjs:250:65
 ❯ VitestExecutor.cachedRequest node_modules/vite-node/dist/client.mjs:187:28
 ❯ VitestExecutor.dependencyRequest node_modules/vite-node/dist/client.mjs:233:23
 ❯ VitestExecutor.dependencyRequest node_modules/vitest/dist/vendor/execute.edwByI27.js:576:18
```

Sometimes the error doesn't show up and our tests are passing.

Here is our vitest.config.ts
```
import { fileURLToPath, URL } from "node:url"

import vue from "@vitejs/plugin-vue"
import vueJsx from "@vitejs/plugin-vue-jsx"
import VueMacros from "unplugin-vue-macros"
import { defineConfig } from "vitest/config"

export default defineConfig({
  appType: "spa",
  plugins: [VueMacros.vite({ plugins: { vue: vue(), vueJsx: vueJsx() } })],
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
      "./runtimeConfig": "./runtimeConfig.browser",
    },
  },
  envPrefix: "VUE_",
  test: {
    environment: "jsdom",
    transformMode: {
      web: [/.[tj]sx$/],
    },
  },
})
```

### Reproduction

-

### System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 16.05 GB / 30.97 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 21.6.0 - ~/.nvm/versions/node/v21.6.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.0/bin/npm
  npmPackages:
    @vitejs/plugin-vue: ^5.0.3 => 5.0.3 
    @vitejs/plugin-vue-jsx: ^3.1.0 => 3.1.0 
    @vitest/coverage-v8: ^1.2.1 => 1.2.1 
    vite: ^5.0.12 => 5.0.12 
    vitest: ^1.2.1 => 1.2.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MichaelBrandt4994** [comment]
will try a reproduction until friday

**Comment by mahdibx** [comment]
I have the same issue, I think the test is not tearing down correctly because there are unfinished promises.

I have a very simple react component with two simple tests, the only particularity is there is an image with a source svg supposed to be in the public folder : ```<img src="logo.svg" />```

It's very hard to conclude what the exact issue is because the error occurs very rarely.

Also the error only happens when running with other test suits in parallel, and I'm using ``` pool: 'forks' ``` in the conf.

**Comment by axel7083** [comment]
We are experiencing the same issue, makes our CI tests flaky, as we are not able to make a fully reproducible example

**Comment by MichaelBrandt4994** [comment]
It seems for us it was a problem of how we were mocking the vue-router in some unit tests.

In some components we were using `router-link` and we were testing if the `push` function was called. We assumed that we mocked it correctly, but it seems we were not :smile:. Currently we removed the test cases where we checked, if the `push` function was called and we are stubbing now the `router-link` from `vue-router`. 

All tests are now successfull even after multiple retries.

What helped me, was setting the retry to 1, then i saw in our tests a warning related to the vue-router, which i didn't saw before. Maybe the warning was not printed out, because it failed directly.

In the end it seems to be a problem of how we were testing. But still, on the version `1.1.3` we never had problems.

**Comment by axel7083** [comment]
> It seems for us it was a problem of how we were mocking the vue-router in some unit tests.
> 
> In some components we were using `router-link` and we were testing if the `push` function was called. We assumed that we mocked it correctly, but it seems we were not 😄. Currently we removed the test cases where we checked, if the `push` function was called and we are stubbing now the `router-link` from `vue-router`.
> 
> All tests are now successfull even after multiple retries.
> 
> What helped me, was setting the retry to 1, then i saw in our tests a warning related to the vue-router, which i didn't saw before. Maybe the warning was not printed out, because it failed directly.
> 
> In the end it seems to be a problem of how we were testing. But still, on the version `1.1.3` we never had problems.

We are not using vue-router, so it is probably not specific to this library

**Comment by tdebooij** [comment]
Can confirm that I no longer have this issue after updating to 1.3.0 👍
