### ISSUE TITLE
Mock history is not cleared when running with `concurrent`

### ISSUE THREAD

**Issue by Juneezee** [vitest-dev/vitest#5072]
### Describe the bug

Given a `basic.ts` file:

```typescript
import { randomUUID } from 'crypto';

export function genUUID() {
  return randomUUID();
}

export function noop() {}
```

and the `basic.test.ts` test:

```typescript
import { describe, expect, it, vi, afterEach } from 'vitest';
import { genUUID, noop } from './basic.js';
import { randomUUID } from 'crypto';

vi.mock('crypto', () => ({ randomUUID: vi.fn() }));

// doesn't work
describe.concurrent('concurrent', () => {
  describe('noop', () => {
    it('noop 1', () => {
      noop();
    });

    it('noop 2', () => {
      noop();
    });

    it('noop 3', () => {
      noop();
    });
  });

  describe('genUUID', () => {
    afterEach(() => {
      // None of the following works
      vi.clearAllMocks();
      vi.resetAllMocks();
      vi.restoreAllMocks();
    });

    it('genUUID 1', () => {
      genUUID();
      expect(randomUUID).toHaveBeenCalledOnce();
    });

    it('genUUID 2', () => {
      genUUID();
      // AssertionError: expected "spy" to be called once, but got 2 times
      expect(randomUUID).toHaveBeenCalledOnce();
    });

    it('genUUID 3', () => {
      genUUID();
      expect(randomUUID).toHaveBeenCalledOnce();
    });
  });
});

// works
describe('serial', () => {
  describe('noop', () => {
    it('noop 1', () => {
      noop();
    });

    it('noop 2', () => {
      noop();
    });

    it('noop 3', () => {
      noop();
    });
  });

  describe('genUUID concurrent', () => {
    afterEach(() => {
      vi.clearAllMocks();
      vi.resetAllMocks();
      vi.restoreAllMocks();
    });

    it('genUUID 1', () => {
      genUUID();
      expect(randomUUID).toHaveBeenCalledOnce();
    });

    it('genUUID 2', () => {
      genUUID();
      expect(randomUUID).toHaveBeenCalledOnce();
    });

    it('genUUID 3', () => {
      genUUID();
      expect(randomUUID).toHaveBeenCalledOnce();
    });
  });
});
```

All 3 `vi.clearAllMocks`, `vi.resetAllMocks`, and `vi.restoreAllMocks` do not clear the mock history as expected when the tests are run with `concurrent`.

```shell
 RUN  v1.2.2 /home/projects/vitest-dev-vitest-34zo9k

 ❯ src/basic.test.ts (12)
   ❯ concurrent (6)
     ✓ noop (3)
       ✓ noop 1
       ✓ noop 2
       ✓ noop 3
     ❯ genUUID (3)
       ✓ genUUID 1
       × genUUID 2
       ✓ genUUID 3
   ✓ serial (6)
     ✓ noop (3)
       ✓ noop 1
       ✓ noop 2
       ✓ noop 3
     ✓ genUUID (3)
       ✓ genUUID 1
       ✓ genUUID 2
       ✓ genUUID 3

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/basic.test.ts > concurrent > genUUID > genUUID 2
AssertionError: expected "spy" to be called once, but got 2 times
 ❯ eval src/basic.test.ts:39:26
     37|       genUUID();
     38|       // AssertionError: expected "spy" to be called once, but got 2 times
     39|       expect(randomUUID).toHaveBeenCalledOnce();
       |                          ^
     40|     });
     41| 

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  1 failed | 11 passed (12)
   Start at  02:13:20
   Duration  2.05s (transform 103ms, setup 0ms, collect 91ms, tests 10ms, environment 0ms, prepare 262ms)
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-34zo9k?file=src%2Fbasic.ts,src%2Fbasic.test.ts&initialPath=__vitest__/

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  npmPackages:
    vite: latest => 5.0.12 
    vitest: latest => 1.2.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
They are called at the same time, how would you expect them to be cleared? If you rely on a state outside of the test function, don't use concurrency.

**Comment by sheremet-va** [comment]
Sorry, I am not sure what should be mentioned. Since tests are running at the same time, it would make sense that test hooks are also running at the same time, what other implementations are possible?

**Comment by Juneezee** [comment]
> Sorry, I am not sure what should be mentioned. Since tests are running at the same time, it would make sense that test hooks are also running at the same time, what other implementations are possible?

@sheremet-va To provide some context, my motivation for raising this issue come from helping [atlowChemi/vite-svg-2-webfont](https://github.com/atlowChemi/vite-svg-2-webfont) with upgrading their Vite and Vitest to the latest version.

One of their test cases, which is nearly identical to the sample code in the issue description, as you can see here: https://github.com/atlowChemi/vite-svg-2-webfont/blob/031a17fcd12d0514cbff8253dd3bf3f75ff36478/src/optionParser.test.ts#L29-L64. The test uses `concurrent` but `toHaveBeenCalledOnce()` works as expected. This functioned correctly with Vitest 0.26.3.

However, upgrading Vitest to 1.2.2 caused the test to fail, as shown in https://github.com/atlowChemi/vite-svg-2-webfont/pull/14#discussion_r1470543936.

I then tried each Vitest version from 0.26.3, and found that the test starts failing since 0.27.2. Despite examining the changes between, [0.27.1...0.27.2](https://github.com/vitest-dev/vitest/compare/v0.27.1...v0.27.2), I couldn't pinpoint the exact change causing `afterEach` to malfunction compared to previous versions. This led me to question if there have been any undocumented changes to the interaction between `concurrent` and [Setup and Teardown functions](https://vitest.dev/api/#setup-and-teardown).

**Comment by Juneezee** [comment]
> Maybe it works sometimes, but not always?

I rerun the test for a dozen times, it seems like it always works in 0.26.3

https://github.com/vitest-dev/vitest/assets/20135478/c54e5519-82c8-4cbe-8c6d-f84121b0554b
