### ISSUE TITLE
Large diffs on snapshots are not truncated

### ISSUE THREAD

**Issue by kernelwhisperer** [vitest-dev/vitest#5073]
### Describe the bug

I'm using `expect(result).toMatchSnapshot()` on a large array resulting in a 45.000 line snapshot.

The issue is that it takes a very long time for the test runner to display the diff inside the terminal.

I was expecting the output to be truncated, using the default value of `chaiConfig.truncateThreshold`, but the full diff is printed instead.

I've also tried using `chaiConfig: { showDiff: false }` which seems to have no effect.

### Reproduction

Is this really needed?

I've went searching through the issues, my hunch is that snapshot diffing works differently and it ignores `chaiConfig`.

### System Info

```shell
WSL 2 Ubuntu - vitest 1.2.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kernelwhisperer** [comment]
The whole snapshot is different, yes. 

Perhaps this is a feature request then, rather than a bug, correct?

**Comment by sheremet-va** [comment]
I guess we can add an option to truncate diff patches somehow. It should be disabled by default though.

**Comment by willieho** [comment]
> I guess we can add an option to truncate diff patches somehow. It should be disabled by default though.

I'd like to take a shot at this enhancement/feature. After tracing the codebase, I think we can add a configuration option in `DiffOptions` so that we could have a more general control over diff truncation, instead of being specific to `toMatchSnapshot()`. Does it sound reasonable?
