### ISSUE TITLE
#4980 caused a regression in vite-plugin-vue tests

### ISSUE THREAD

**Issue by sodatea** [vitest-dev/vitest#5084]
### Describe the bug

#4980 somehow broke [this test case](https://github.com/vitejs/vite-plugin-vue/blob/2c68a7c901a9ef70b46f8befa3599ed86a453982/playground/vue/__tests__/vue.spec.ts#L33-L35) in vite-plugin-vue.
The test case tests the production bundling of a vue file by setting `process.env.NODE_ENV` to `production` in vitest `globalSetup` https://github.com/vitejs/vite-plugin-vue/blob/2c68a7c901a9ef70b46f8befa3599ed86a453982/playground/vitestGlobalSetup.ts#L12-L14
Somehow, it's no longer respected after #4980

### Reproduction

https://github.com/vitejs/vite-plugin-vue/pull/332

```
git clone https://github.com/vitejs/vite-plugin-vue.git
cd vite-plugin-vue
git switch renovate/all-minor-patch
pnpm i
pnpm build
pnpm test-build
```

### System Info

```shell
System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 224.03 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/Library/Caches/fnm_multishells/36806_1706432535433/bin/node
    Yarn: 1.22.21 - ~/Library/Caches/fnm_multishells/36806_1706432535433/bin/yarn
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/36806_1706432535433/bin/npm
    pnpm: 8.15.1 - ~/Library/Caches/fnm_multishells/36806_1706432535433/bin/pnpm
    bun: 1.0.3 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.234
    Chrome Canary: 123.0.6269.0
    Safari: 17.3
  npmPackages:
    @vitejs/release-scripts: ^1.3.1 => 1.3.1
    vite: ^5.0.10 => 5.0.10
    vitest: ^1.2.2 => 1.2.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Global setup is called after the server is created, so `isProduction` is already set. Did you try setting it in the config file for example? I am not sure how it worked before since we never actually used dev/prod conditions before.

**Comment by sodatea** [comment]
Thanks! Moving the assignment to the config file worked.
