### ISSUE TITLE
Junit reporter doesn't include project root in output

### ISSUE THREAD

**Issue by jrnail23** [vitest-dev/vitest#5088]
### Describe the bug

As originally reported in #2566, but not quite resolved in #256 as anticipated, in a monorepo / multi-workspace setup, the Junit reporter does not include the project root in its output (see example below)

Here, this testsuite is in... well... damn, I don't know which project it's in, because the testsuite.name attribute is relative.  It should be something like `packages/my-package/tests/index.test.ts`.

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<testsuites name="vitest tests" tests="67" failures="0" errors="0" time="1.636">
    <testsuite name="test/index.test.ts" timestamp="2024-01-31T22:24:19.411Z" hostname="MacBook-Pro-M1.local" tests="1" failures="0" errors="0" skipped="0" time="0.016">
```

### Reproduction

(no repro -- reporting a previously closed bug)

### System Info

```shell
System:
    OS: macOS 13.6.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 213.03 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.asdf/installs/nodejs/18.16.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2023.12.04.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 121.0.6167.85
    Firefox: 122.0
    Safari: 16.6
  npmPackages:
    @vitest/coverage-v8: ^1.2.2 => 1.2.2 
    vitest: ^1.2.2 => 1.2.2 
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I see what you mean. I guess it should be relative to the root config instead of a project one.

**Comment by jrnail23** [comment]
If it's any help, I'm also using `vitest-sonar-reporter`, and that one uses the root properly.
