### ISSUE TITLE
Vitest UI is not loading, gives blank page error

### ISSUE THREAD

**Issue by ademyalcin27** [vitest-dev/vitest#5098]
### Describe the bug

Hello,

Vitest --ui is not working in local, I made reproduction in stack blitz that is working. so interesting. 

Do you have any solution ?

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-jqfwhj?file=vitest.config.ts

### System Info

```shell
System:
    OS: macOS 14.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 2.24 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 121.0.6167.139
    Safari: 17.3
  npmPackages:
    @vitejs/plugin-vue: 5.0.3 => 5.0.3 
    @vitest/browser: ^1.2.2 => 1.2.2 
    @vitest/coverage-istanbul: ^1.2.1 => 1.2.2 
    @vitest/ui: ^1.2.1 => 1.2.2 
    vite: ^5.0.12 => 5.0.12 
    vitest: 1.2.1 => 1.2.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
reproductions are supposed to show a bug.
