### ISSUE TITLE
Vitest API does not return expected/actual fields with assertion errors when using `Effect`

### ISSUE THREAD

**Issue by evelant** [vitest-dev/vitest#5109]
### Describe the bug

Vitest API does not return expected/actual fields with assertion errors when assertion is inside an `Effect`.  https://github.com/Effect-TS/effect 

They are `undefined` even though the message and the full text output appears to be correct.

Works fine with async functions
![image](https://github.com/vitest-dev/vitest/assets/858965/71b46fcf-fac3-48f3-8330-1f28d66948bc)

Missing expected/actual when using `Effect`
![image](https://github.com/vitest-dev/vitest/assets/858965/c3efd267-4794-4e13-b966-fde7237279f5)

Confirmed by debugging the [vitest extension](https://github.com/MilanKovacic/vitest-visual-studio-code-extension) that the expected/actual fields are `undefined` coming from the vitest api and not an issue with the plugin.

### Reproduction

https://github.com/evelant/effect-vitest-bug

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 51.72 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - /etc/profiles/per-user/imagio/bin/node
    Yarn: 1.22.21 - /etc/profiles/per-user/imagio/bin/yarn
    npm: 10.2.3 - /etc/profiles/per-user/imagio/bin/npm
    pnpm: 8.12.0 - /etc/profiles/per-user/imagio/bin/pnpm
    bun: 1.0.25 - ~/.bun/bin/bun
    Watchman: 2023.08.14.00 - /etc/profiles/per-user/imagio/bin/watchman
  Browsers:
    Brave Browser: 121.1.62.156
    Chrome: 121.0.6167.139
    Safari: 17.2.1
  npmPackages:
    vitest: 1.2.2 => 1.2.2 
```
```


### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest doesn't modify errors. If it doesn't work, the effect API doesn't forward the error with those properties.

**Comment by evelant** [comment]
Thanks, it does appear to be a problem with effect not forwarding the properties
