### ISSUE TITLE
Unexpected test errors when `threads: false` is used

### ISSUE THREAD

**Issue by EvHaus** [vitest-dev/vitest#511]
### Describe the bug

I found another `threads: false` related issue. This one is really weird -- I hope you like puzzles.

In my test suite when I disable threads, `vitest` fails with this error:

```
Error: Transform failed with 1 error:
/home/projects/node-mrpcnw/src/commands/publish/b.test.ts:1:10: error: Expected ";" but found ":"
 ❯ failureErrorWithLog node_modules/esbuild/lib/main.js:1493:15
 ❯ eval node_modules/esbuild/lib/main.js:1282:29
 ❯ eval node_modules/esbuild/lib/main.js:629:9
 ❯ handleIncomingPacket node_modules/esbuild/lib/main.js:726:9
 ❯ Socket.readFromStdout node_modules/esbuild/lib/main.js:596:7
 ❯ Socket.EventEmitter.emit https:/node-mrpcnw.w.staticblitz.com/blitz.528f704493b63b14b6f9ee36935eead8382e8395.js:6:126633
 ❯ addChunk https:/node-mrpcnw.w.staticblitz.com/blitz.528f704493b63b14b6f9ee36935eead8382e8395.js:6:516009
 ❯ readableAddChunk https:/node-mrpcnw.w.staticblitz.com/blitz.528f704493b63b14b6f9ee36935eead8382e8395.js:6:515730
 ❯ Socket.Readable.push https:/node-mrpcnw.w.staticblitz.com/blitz.528f704493b63b14b6f9ee36935eead8382e8395.js:6:516397
 ❯ _0x1bb005.onStreamRead [as onread] https:/node-mrpcnw.w.staticblitz.com/blitz.528f704493b63b14b6f9ee36935eead8382e8395.js:6:543527
```

If I enable threads, the error goes away and the tests are just fine.

### Reproduction

It took me nearly 4 hours to get down to the most minimal repro suite, but I think I got it. The StackBlitz is here: https://stackblitz.com/edit/node-mrpcnw?file=README.md&view=editor

To reproduce this you need:
- `threads: false` in vitest config. If you set to `true` -- the error goes away.
- At least 3 files with `*.test.ts` naming. Even if those files are mostly empty, you must have 3 or more. If you delete one of the files -- the error goes away. For example try deleting or renaming `c.test.ts`.
- The following spy must be defined in one of your test files:
```
vi.spyOn(fs.promises, 'readFile').mockImplementation(() =>
    Promise.resolve('{"version": "1.2.3"}')
);
```

When all these conditions are met, you get the error posted above. If you change any of those pieces, the error goes away. Super weird... At first I thought maybe there was some problem with the `fs.promises` spy, but then why would removing an unrelated test file cause the problem to go away?

I'm at a loss...

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 31.00 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2022.01.03.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 97.0.4692.71
    Chrome Canary: 99.0.4824.0
    Firefox: 95.0
    Safari: 15.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I'm guessing it has something to do with rollup reading files, it expects js outbut, but gets JSON. Since we are running it in the same context, this mock stays for every file.

I would recommend restoring all mocks (with `vi.restoreAllMocks`) after each test.

**Comment by EvHaus** [comment]
Hmm. `afterEach(() => vi.restoreAllMocks())` does indeed fix the issue here. Alright. Moving on.
