### ISSUE TITLE
Vitest test failed: Error: require() of ES Module /Users/xiangyanxia/fuxi/zb/zhongbao/node_modules/export-from-json/dist/umd/index.js from

### ISSUE THREAD

**Issue by xiayanxiang** [vitest-dev/vitest#5110]
### Describe the bug

I am using vitest test my vite project, and require an npm package in my test file, then failed.
`
Error: require() of ES Module /Users/xiangyanxia/fuxi/zb/zhongbao/node_modules/export-from-json/dist/umd/index.js from /Users/xiangyanxia/fuxi/zb/zhongbao/packages/manage/test/component/TaskDataSetting/parse.test.ts not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/xiangyanxia/fuxi/zb/zhongbao/node_modules/export-from-json/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
`
It seems that require('export-from-json') is forbidden but I am sure export-from-json is umd and can use require, then I check the export-from-json package,find that in package.json file, a type="module" , and after I delete the type field, vitest success! 
but I cant change to import('export-from-json') because this npm is imported from another npm

### Reproduction
because the npm package I am using is an internal package, I cannot  directly it, but I know the export-from-json package is the package that cause problem(I am sorry that not good at English)
just adding `require('export-from-json')` to your test.ts file

### System Info

```shell
$ npx envinfo --system --npmPackages '{vitest,@vitest/*,vite,@vitejs/*}' --binaries --browsers

  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 97.05 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.7.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
  Browsers:
    Chrome: 121.0.6167.85
    Edge: 121.0.2277.98
    Firefox: 117.0
    Safari: 16.3
  npmPackages:
    @vitejs/plugin-basic-ssl: ^1.0.1 => 1.0.1 
    @vitejs/plugin-legacy: ^5.2.0 => 5.2.0 
    @vitejs/plugin-react-swc: ^3.3.0 => 3.3.2 
    vite: ^5.0.2 => 5.0.2 
    vitest: ^1.2.1 => 1.2.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
As you've already figured it out, the issue is in https://github.com/zheeeng/export-from-json, so it's better to be reported there. Sharing this with the author might help https://publint.dev/export-from-json@1.7.4.

Btw, the same error happens on plain NodeJS and `export-from-json` is looking like esm-only package even though that's probably not intended.

https://stackblitz.com/edit/vitest-dev-vitest-lpsjhw?file=repro.cjs

```
const lib = require('export-from-json');
console.log(lib);

// node repro.cjs
// Error [ERR_REQUIRE_ESM]: require() of ES Module /home/projects/vitest-dev-vitest-lpsjhw/node_modules/export-from-json/dist/umd/index.js from /home/projects/vitest-dev-vitest-lpsjhw/repro.cjs not supported.
// index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
// Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/projects/vitest-dev-vitest-lpsjhw/node_modules/export-from-json/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
```

**Comment by xiayanxiang** [comment]
thank you! 
I thought this were some solutions with vitest before，but now I have some ideas to solve it。
