### ISSUE TITLE
Move test and describe configuration options to be a second parameter

### ISSUE THREAD

**Issue by sheremet-va** [vitest-dev/vitest#5121]
### Clear and concise description of the problem

Currently, Vitest exposes `test` and `describe` options as the last parameter:

```ts
test('renders component', () => {
  //
}, { retries: 5 })
```

This makes it hard to see at first glance what options are used, especially if the body of a test is too long. Also, some code formatters like prettier can format this code in a weird way like so:

```js
test(
  'renders component',
  () => {}
  { retries: 5 }
)
```

This happens because prettier is hardcoded to treat `test` functions differently when the second parameter is an options object. In this case it is formatted like this:

```ts
test('renders component', { retries: 5 }, () => {
  //
})
```

### Suggested solution

I propose:

- Deprecate passing down an options object in the last argument (show a console warning)
- Support passing down an options object in the second argument
- Still support passing down a number for timeout as the last argument, but also expose `timeout` option in the second argument

In the next major we can remove support for options as the last parameter.

### Additional context

I think this can also be a start of using `describe('name', { #flag: true }` instead of `describe.{flag}`. Specifically for situations like this: https://github.com/vitest-dev/vitest/issues/3922

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
> prettier is hardcoded to treat `test` functions differently

Is it only for `test` or does it support `it` too?

> Deprecate passing down an options object in the last argument (show a console warning)

Is it common practice to add new deprecation warnings without major version bump? It doesn't feel right to me but I think it's still allowed in semver.

**Comment by sheremet-va** [comment]
> Is it only for test or does it support it too?

They are the same function, so yes. Also `describe` is `suite` 😄 

> Is it common practice to add new deprecation warnings without major version bump? It doesn't feel right to me but I think it's still allowed in semver.

This is what Vite does in its minors.

**Comment by AriPerkkio** [comment]
> They are the same function, so yes. Also `describe` is `suite` 😄

I guess these are the detected function names. https://github.com/prettier/prettier/blob/4a72d43a0eefd525637cb280192f9052d72757fe/src/language-js/utils/index.js#L340-L364
Looks like `it` is there too. 👍 

> This is what Vite does in its minors.

Sounds good, let's follow Vite's approach.
