### ISSUE TITLE
Vitest gets stuck during build of `actor` 3rd party library (named export `then`)

### ISSUE THREAD

**Issue by RobertPechaCZ** [vitest-dev/vitest#5122]
### Describe the bug

This library is deep dependency in our monorepo and we are unable to run any test if this package is imported into our source code. I created reproduction where I imported only this library to `test` function in index.ts file and I wrote simple test for this function. When I use Vite for building code it works. But when I try to run `npm run test` command that runs Vitest it gets stuck forever.

<img width="1038" alt="image" src="https://github.com/vitest-dev/vitest/assets/31454051/4f79c849-6980-4ef9-99cf-2b7cc0267598">

### Reproduction

https://github.com/RobertPechaCZ/vite-actor-repro

### System Info

```shell
"dependencies": {
    "actor": "^2.3.1",
    "typescript": "^5.3.3",
    "vite": "^5.0.12",
    "vitest": "^1.2.2"
  }
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
This might be the same issue as
- https://github.com/vitest-dev/vitest/issues/4635
- https://github.com/rescript-lang/rescript-compiler/issues/6503

I see `actor` also has `export const then = ...` and this could break dynamic import in NodeJS environment.

https://github.com/Gozala/actor/blob/2031efc36ff112c0a43404a5f76b3b078f5c3c21/src/lib.js#L448

**Comment by hi-ogawa** [comment]
I guess one obvious way to "fix" is to patch `export const then = ...` into `const then =...` but this assumes no one uses `then` export.

> This library is nested dependency of one 3rd party client

Actually in this scenario (i.e. not importing `actor` directly in your source code), Vitest doesn't rewrite it into dynamic import by default, so I thought it should work. Maybe you happen to have `noExternal` or something in the vite config? (cf. https://vitest.dev/config/#server-deps-external)

It would be great if you can create reproduction to match your actual use case.

**Comment by hi-ogawa** [comment]
Created an upstream issue https://github.com/vitejs/vite/issues/18328

**Comment by hi-ogawa** [comment]
Caveat on `then` export seems well-known and mentioned on MDN as well https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import

> Warning: Do not export a function called then() from a module. This will cause the module to behave differently when imported dynamically than when imported statically.

We think this should be better handled by user/package side, so closing as wontfix.
