### ISSUE TITLE
vi.setSystemTime() sets system time only when component is rendered

### ISSUE THREAD

**Issue by pkawula** [vitest-dev/vitest#5154]
### Describe the bug

does vi.setSystemTime() shouldn't set a system time for test evaluation?

### Reproduction

Component code:

```typescript react
import { useState } from "react";  
import dayjs from "dayjs";

const initialFilters = {
     startDate: dayjs().format("YYYY-MM-DD"),
     endDate: dayjs().add(7, "days").format("YYYY-MM-DD")
}

export const Component = () => {
    const [filters, setFilters] = useState(initialFilters)
    
    ...
}
```

Test:
```typescript react
import ShallowRenderer from "react-test-renderer/shallow";
import { Component } from "../Component";

describe("Component", () => {
	beforeEach(() => {
		vi.setSystemTime(new Date(2024, 1, 1, 8, 0));
	});

	afterEach(() => {
		vi.useRealTimers();
	});

	it("snapshot matches", () => {
		const renderer = ShallowRenderer.createRenderer();

		const tree = renderer.render(<Component />);
		expect(tree).toMatchSnapshot();
	});
});
```

And the snapshot fails since the `setSystemTime` sets the time for usage inside component and since `initialFilters` is defined outside of component it gets current date.

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 2.22 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/Projects/talixo/Talixo/frontend/packages/next-actions-modals/node_modules/.bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.6.12 - ~/Library/pnpm/pnpm
    bun: 1.0.13 - ~/.bun/bin/bun
  Browsers:
    Chrome: 121.0.6167.139
    Safari: 17.2.1
  npmPackages:
    @vitejs/plugin-react-swc: ^3.3.2 => 3.3.2
    vite: ^4.4.0 => 4.4.7
    vitest: ^1.2.2 => 1.2.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You called `dayjs` in the global scope before calling `vi.setSystemTime` (when importing the file). Either import the fail after you called `vi.setSystemTime` or call `vi.setSystemTime` inside [`vi.hoisted`](https://vitest.dev/api/vi.html#vi-hoisted-0-31-0).
