### ISSUE TITLE
Unable to deep spy/stub with vitest

### ISSUE THREAD

**Issue by Yalhu** [vitest-dev/vitest#5159]
https://github.com/vitest-dev/vitest/issues/3400#issue-1715808380

```js
export const fn1 = () => {
  console.log('I would like to be spied');
};

export const fn2 = () => {
  fn1();
};

fn2();

```
`except(fn1).toHaveBeenCalled()` , But not.
Is there any way to resolve the case ??

**Comment by sheremet-va** [comment]
This issue doesn’t follow the template. The link you mentioned already explains why you cannot do this. Here is another link: https://vitest.dev/guide/mocking.html#mocking-pitfalls

It is NOT possible and it’s the end if the story.
