### ISSUE TITLE
Code coverage: cannot cover type of express request

### ISSUE THREAD

**Issue by wataruian** [vitest-dev/vitest#5161]
### Describe the bug

I have a simple `nestjs` controller that I am testing that accepts `express` - `request` as its param.

I achieved almost 100% code coverage except:

<img width="627" alt="Screenshot 2024-02-09 at 5 07 10 PM" src="https://github.com/vitest-dev/vitest/assets/32057659/f4faa8a5-04e9-4e19-9b64-34d6df2ad6c2">

I cannot cover the type of `Request` from code coverage. I am using `vitest-mock-express` to mock the request object passed to the controller. I also tried `node-mocks-http` and had the same result.

`vitest-mock-express`:
```
import { getMockReq } from 'vitest-mock-express';
const request = getMockReq();
```

`node-mocks-http`:
```
import { createRequest } from 'node-mocks-http';
const request = createRequest();
```

The following test cases should cover all of the code:

```
describe('/', () => {
      it('should succeed', async () => {
        const response = await controller.index();
        expect(response).toStrictEqual({ status: 'ok' });
      });
});

describe('/csrf', () => {
      it('should succeed', async () => {
        const { res } = getMockRes();
        request.res = res;
        const response = await controller.csrf(request as Request);
        expect(response).toStrictEqual({ success: true });
      });

      it('should fail', async () => {
        const response = await controller.csrf(request as Request);
        expect(response).toStrictEqual({ success: false });
      });
});
```

Coverage result:
<img width="866" alt="Screenshot 2024-02-09 at 5 15 29 PM" src="https://github.com/vitest-dev/vitest/assets/32057659/2c846afe-7a87-44d3-83b7-de4c9569d176">

I have a repo for reproduction at: https://github.com/wataruian/vitest-nestjs-repro

### Reproduction

https://github.com/wataruian/vitest-nestjs-repro

### System Info

```shell
System:
    OS: macOS 13.5.2
    CPU: (10) arm64 Apple M2 Pro
    Memory: 84.00 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.asdf/installs/nodejs/18.15.0/bin/node
    Yarn: 1.22.21 - ~/.asdf/installs/nodejs/18.15.0/bin/yarn
    npm: 9.5.0 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.11.0 - ~/.asdf/installs/nodejs/18.15.0/bin/pnpm
    Watchman: 2023.09.25.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 121.1.62.156
    Safari: 16.6
  npmPackages:
    @vitest/coverage-v8: ^1.1.3 => 1.2.2
    vitest: ^1.1.3 => 1.2.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
When Typescript transpiles the decorators it adds generated code that is included in source maps. There's a `typeof Request` check which is only partially covered, [https://evanw.github.io/source-map-visualization/#MjEzNgBmdW5j...](https://evanw.github.io/source-map-visualization/#MjEzNgBmdW5jdGlvbiBfdHNfZGVjb3JhdGUoZGVjb3JhdG9ycywgdGFyZ2V0LCBrZXksIGRlc2MpIHsKICAgIHZhciBjID0gYXJndW1lbnRzLmxlbmd0aCwgciA9IGMgPCAzID8gdGFyZ2V0IDogZGVzYyA9PT0gbnVsbCA/IGRlc2MgPSBPYmplY3QuZ2V0T3duUHJvcGVydHlEZXNjcmlwdG9yKHRhcmdldCwga2V5KSA6IGRlc2MsIGQ7CiAgICBpZiAodHlwZW9mIFJlZmxlY3QgPT09ICJvYmplY3QiICYmIHR5cGVvZiBSZWZsZWN0LmRlY29yYXRlID09PSAiZnVuY3Rpb24iKSByID0gUmVmbGVjdC5kZWNvcmF0ZShkZWNvcmF0b3JzLCB0YXJnZXQsIGtleSwgZGVzYyk7CiAgICBlbHNlIGZvcih2YXIgaSA9IGRlY29yYXRvcnMubGVuZ3RoIC0gMTsgaSA+PSAwOyBpLS0paWYgKGQgPSBkZWNvcmF0b3JzW2ldKSByID0gKGMgPCAzID8gZChyKSA6IGMgPiAzID8gZCh0YXJnZXQsIGtleSwgcikgOiBkKHRhcmdldCwga2V5KSkgfHwgcjsKICAgIHJldHVybiBjID4gMyAmJiByICYmIE9iamVjdC5kZWZpbmVQcm9wZXJ0eSh0YXJnZXQsIGtleSwgciksIHI7Cn0KZnVuY3Rpb24gX3RzX21ldGFkYXRhKGssIHYpIHsKICAgIGlmICh0eXBlb2YgUmVmbGVjdCA9PT0gIm9iamVjdCIgJiYgdHlwZW9mIFJlZmxlY3QubWV0YWRhdGEgPT09ICJmdW5jdGlvbiIpIHJldHVybiBSZWZsZWN0Lm1ldGFkYXRhKGssIHYpOwp9CmZ1bmN0aW9uIF90c19wYXJhbShwYXJhbUluZGV4LCBkZWNvcmF0b3IpIHsKICAgIHJldHVybiBmdW5jdGlvbih0YXJnZXQsIGtleSkgewogICAgICAgIGRlY29yYXRvcih0YXJnZXQsIGtleSwgcGFyYW1JbmRleCk7CiAgICB9Owp9CmltcG9ydCB7IENvbnRyb2xsZXIsIEdldCwgUmVxIH0gZnJvbSAnQG5lc3Rqcy9jb21tb24nOwppbXBvcnQgXyBmcm9tICdsb2Rhc2gnOwppbXBvcnQgeyBnZW5lcmF0ZVRva2VuLCB0b2tlbkNvb2tpZU5hbWUgfSBmcm9tICcuL2NvbW1vbi9jc3JmJzsKZXhwb3J0IGNsYXNzIEFwcENvbnRyb2xsZXIgewogICAgYXN5bmMgY3NyZihyZXEpIHsKICAgICAgICBsZXQgc3VjY2VzcyA9IGZhbHNlOwogICAgICAgIHRyeSB7CiAgICAgICAgICAgIGNvbnN0IGNzcmZUb2tlbiA9IGdlbmVyYXRlVG9rZW4ocmVxLCByZXEucmVzLCB0cnVlKTsKICAgICAgICAgICAgcmVxLnJlcz8uY29va2llKHRva2VuQ29va2llTmFtZSwgY3NyZlRva2VuLCB7CiAgICAgICAgICAgICAgICBodHRwT25seTogdHJ1ZSwKICAgICAgICAgICAgICAgIHNhbWVTaXRlOiAnc3RyaWN0JywKICAgICAgICAgICAgICAgIHNlY3VyZTogXy5nZXQocHJvY2Vzcy5lbnYsICdJTlNFQ1VSRV9DT09LSUUnLCAnZmFsc2UnKS50b0xvd2VyQ2FzZSgpICE9PSAndHJ1ZScKICAgICAgICAgICAgfSk7CiAgICAgICAgICAgIHN1Y2Nlc3MgPSB0cnVlOwogICAgICAgIH0gY2F0Y2ggIHsKICAgICAgICAgICAgc3VjY2VzcyA9IGZhbHNlOwogICAgICAgIH0KICAgICAgICByZXR1cm4gewogICAgICAgICAgICBzdWNjZXNzCiAgICAgICAgfTsKICAgIH0KICAgIGFzeW5jIGluZGV4KCkgewogICAgICAgIHJldHVybiB7CiAgICAgICAgICAgIHN0YXR1czogJ29rJwogICAgICAgIH07CiAgICB9Cn0KX3RzX2RlY29yYXRlKFsKICAgIEdldCgnY3NyZicpLAogICAgX3RzX3BhcmFtKDAsIFJlcSgpKSwKICAgIF90c19tZXRhZGF0YSgiZGVzaWduOnR5cGUiLCBGdW5jdGlvbiksCiAgICBfdHNfbWV0YWRhdGEoImRlc2lnbjpwYXJhbXR5cGVzIiwgWwogICAgICAgIHR5cGVvZiBSZXF1ZXN0ID09PSAidW5kZWZpbmVkIiA/IE9iamVjdCA6IFJlcXVlc3QKICAgIF0pLAogICAgX3RzX21ldGFkYXRhKCJkZXNpZ246cmV0dXJudHlwZSIsIFByb21pc2UpCl0sIEFwcENvbnRyb2xsZXIucHJvdG90eXBlLCAiY3NyZiIsIG51bGwpOwpfdHNfZGVjb3JhdGUoWwogICAgR2V0KCksCiAgICBfdHNfbWV0YWRhdGEoImRlc2lnbjp0eXBlIiwgRnVuY3Rpb24pLAogICAgX3RzX21ldGFkYXRhKCJkZXNpZ246cGFyYW10eXBlcyIsIFtdKSwKICAgIF90c19tZXRhZGF0YSgiZGVzaWduOnJldHVybnR5cGUiLCBQcm9taXNlKQpdLCBBcHBDb250cm9sbGVyLnByb3RvdHlwZSwgImluZGV4IiwgbnVsbCk7CkFwcENvbnRyb2xsZXIgPSBfdHNfZGVjb3JhdGUoWwogICAgQ29udHJvbGxlcigpCl0sIEFwcENvbnRyb2xsZXIpOwoxNzE0AHsidmVyc2lvbiI6Mywic291cmNlcyI6WyJhcHAuY29udHJvbGxlci50cyJdLCJzb3VyY2VzQ29udGVudCI6WyJpbXBvcnQgdHlwZSB7IFJlcXVlc3QgfSBmcm9tICdleHByZXNzJztcblxuaW1wb3J0IHsgQ29udHJvbGxlciwgR2V0LCBSZXEgfSBmcm9tICdAbmVzdGpzL2NvbW1vbic7XG5pbXBvcnQgXyBmcm9tICdsb2Rhc2gnO1xuXG5pbXBvcnQgeyBnZW5lcmF0ZVRva2VuLCB0b2tlbkNvb2tpZU5hbWUgfSBmcm9tICcuL2NvbW1vbi9jc3JmJztcblxuQENvbnRyb2xsZXIoKVxuZXhwb3J0IGNsYXNzIEFwcENvbnRyb2xsZXIge1xuICBAR2V0KCdjc3JmJylcbiAgYXN5bmMgY3NyZihAUmVxKCkgcmVxOiBSZXF1ZXN0KSB7XG4gICAgbGV0IHN1Y2Nlc3MgPSBmYWxzZTtcbiAgICB0cnkge1xuICAgICAgY29uc3QgY3NyZlRva2VuID0gZ2VuZXJhdGVUb2tlbihyZXEsIHJlcS5yZXMsIHRydWUpO1xuXG4gICAgICByZXEucmVzPy5jb29raWUodG9rZW5Db29raWVOYW1lLCBjc3JmVG9rZW4sIHtcbiAgICAgICAgaHR0cE9ubHk6IHRydWUsXG4gICAgICAgIHNhbWVTaXRlOiAnc3RyaWN0JyxcbiAgICAgICAgc2VjdXJlOlxuICAgICAgICAgIF8uZ2V0KHByb2Nlc3MuZW52LCAnSU5TRUNVUkVfQ09PS0lFJywgJ2ZhbHNlJykudG9Mb3dlckNhc2UoKSAhPT1cbiAgICAgICAgICAndHJ1ZScsXG4gICAgICB9KTtcblxuICAgICAgc3VjY2VzcyA9IHRydWU7XG4gICAgfSBjYXRjaCB7XG4gICAgICBzdWNjZXNzID0gZmFsc2U7XG4gICAgfVxuXG4gICAgcmV0dXJuIHtcbiAgICAgIHN1Y2Nlc3MsXG4gICAgfTtcbiAgfVxuXG4gIEBHZXQoKVxuICBhc3luYyBpbmRleCgpIHtcbiAgICByZXR1cm4ge1xuICAgICAgc3RhdHVzOiAnb2snLFxuICAgIH07XG4gIH1cbn1cbiJdLCJuYW1lcyI6WyJDb250cm9sbGVyIiwiR2V0IiwiUmVxIiwiXyIsImdlbmVyYXRlVG9rZW4iLCJ0b2tlbkNvb2tpZU5hbWUiLCJBcHBDb250cm9sbGVyIiwiY3NyZiIsInJlcSIsInN1Y2Nlc3MiLCJjc3JmVG9rZW4iLCJyZXMiLCJjb29raWUiLCJodHRwT25seSIsInNhbWVTaXRlIiwic2VjdXJlIiwiZ2V0IiwicHJvY2VzcyIsImVudiIsInRvTG93ZXJDYXNlIiwiaW5kZXgiLCJzdGF0dXMiXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7O0FBRUEsU0FBU0EsVUFBVSxFQUFFQyxHQUFHLEVBQUVDLEdBQUcsUUFBUSxpQkFBaUI7QUFDdEQsT0FBT0MsT0FBTyxTQUFTO0FBRXZCLFNBQVNDLGFBQWEsRUFBRUMsZUFBZSxRQUFRLGdCQUFnQjtBQUcvRCxPQUFPLE1BQU1DO0lBQ1gsTUFDTUMsS0FBSyxBQUFPQyxHQUFZLEVBQUU7UUFDOUIsSUFBSUMsVUFBVTtRQUNkLElBQUk7WUFDRixNQUFNQyxZQUFZTixjQUFjSSxLQUFLQSxJQUFJRyxHQUFHLEVBQUU7WUFFOUNILElBQUlHLEdBQUcsRUFBRUMsT0FBT1AsaUJBQWlCSyxXQUFXO2dCQUMxQ0csVUFBVTtnQkFDVkMsVUFBVTtnQkFDVkMsUUFDRVosRUFBRWEsR0FBRyxDQUFDQyxRQUFRQyxHQUFHLEVBQUUsbUJBQW1CLFNBQVNDLFdBQVcsT0FDMUQ7WUFDSjtZQUVBVixVQUFVO1FBQ1osRUFBRSxPQUFNO1lBQ05BLFVBQVU7UUFDWjtRQUVBLE9BQU87WUFDTEE7UUFDRjtJQUNGO0lBRUEsTUFDTVcsUUFBUTtRQUNaLE9BQU87WUFDTEMsUUFBUTtRQUNWO0lBQ0Y7QUFDRjs7SUE5QkdwQixJQUFJO0lBQ09DLGFBQUFBOzs7ZUFBVyxtQ0FBQTs7O0dBRlpJOztJQXlCVkw7Ozs7R0F6QlVLO0FBQUFBO0lBRFpOO0dBQ1lNIn0=).

![image](https://github.com/vitest-dev/vitest/assets/14806298/c56e0ebc-6771-4c5e-938e-05718ab0cfd6)

Ideally Typescript should not include this in source maps. Then code coverage tools would not consider it as your source code, and they would exclude it from the report automatically.

`ts-jest` used to have hacky solution for this where they add ignore hint above the transpiled decorator: https://github.com/kulshekhar/ts-jest/pull/488. Maybe Vitest could try to do something similar. There's already similar approach used for Vite's generated code:

https://github.com/vitest-dev/vitest/blob/4e179426399dfcf105eaa558fe061d4ab1951b21/packages/coverage-v8/src/provider.ts#L363-L385

**Comment by AriPerkkio** [comment]
It actually looks like the `ts_decorate` part is coming from SWC: https://github.com/search?q=repo%3Aswc-project%2Fswc%20_ts_decorate&type=code

Could you try if disabling SWC helps?

**Comment by AriPerkkio** [comment]
Ok, disabling SWC is not an option as decorator metadata support of esbuild doesn't seem to work with NestJs.

I did some testing here https://github.com/AriPerkkio/vitest/commit/42e1e1ba4b58e220a867f406ecb0a837b69fd470 and it seems to work on the minimal reproduction. I'll need to look into `@vitest/coverage-istanbul` later.
