### ISSUE TITLE
Don't hardcode edgedriver version

### ISSUE THREAD

**Issue by sheremet-va** [vitest-dev/vitest#5187]
### Clear and concise description of the problem

Currently we hardcode edgedriver because of this bug: https://github.com/webdriverio-community/node-edgedriver/issues/239

### Suggested solution

Don't hardcode it after the issue is resolved

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by christian-bromann** [comment]
@sheremet-va I started working on https://github.com/webdriverio-community/node-edgedriver/issues/239
