### ISSUE TITLE
add JSDoc to Vitest code

### ISSUE THREAD

**Issue by yukulele** [vitest-dev/vitest#5191]
### Clear and concise description of the problem

Vitest functions have little or no documentation in the code, making them difficult to use and adopt.

This is what the editor shows me:
![Screenshot_20240213_110246](https://github.com/vitest-dev/vitest/assets/347244/09c8660b-6bb9-4935-990a-868f320235b1)

and this is what I hope to see:
![Screenshot_20240213_105833](https://github.com/vitest-dev/vitest/assets/347244/0d47ab1d-0d8e-4dcd-9758-d237e01ce032)

### Suggested solution

add JSDoc to Vitest code

### Alternative

I have to go to [the documentation](https://vitest.dev/api/expect#tocontain) every time I'm not sure how to use a function :/

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by geeksilva97** [comment]
hey folks, I'd like to take a look on it to get familiarized with the project. would you guys have any clue?

**Comment by hi-ogawa** [comment]
You can add jsdoc to the type definition here
https://github.com/vitest-dev/vitest/blob/f969fb0f9f0247a7daa2afee8f70de25ea5e123f/packages/expect/src/types.ts#L116-L164

For example,

```ts
  /**
   * write something...
   * @example
   *   expect("xxx").toEqual("xxx") // OK
   */
  toEqual: <E>(expected: E) => void
```

![image](https://github.com/vitest-dev/vitest/assets/4232207/ee1541fa-730a-4bf0-bfc8-b43907b7ca6a)

**Comment by geeksilva97** [comment]
Thanks a lot man!
