### ISSUE TITLE
Donating Funds to Vitest

### ISSUE THREAD

**Issue by Lfada** [vitest-dev/vitest#5207]
### Clear and concise description of the problem

Hi Vitest maintainers. I'm Lucas, a core contributor to the Drips project (https://www.drips.network/). I help recipients of donations through their learning and onboarding process.

[WAGMI](https://www.drips.network/app/projects/github/wevm/wagmi?exact), [Viem](https://github.com/wevm/viem) and [Abitype](https://www.drips.network/app/projects/github/wevm/abitype?exact) maintainers have been using https://github.com/vitest-dev/vitest. It's in fact one of their most critical dependencies!

WAGMI core contributors appreciate the work you all do and want to make sure that you are all well-funded to keep doing it. For that reason, they have decided to donate some funds to your project through [Drips](https://www.drips.network/).

Who can I talk to about it?

### Suggested solution

Talk to one of the core-maintainers: @antfu @sheremet-va @AriPerkkio @patak-dev 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Hello! I see that @antfu added some kind of a [drips config](https://github.com/vitest-dev/vitest/commit/aa72740a61228c4c2cf0bd26f7ee8a63b38954cd) to the Vitest repo, maybe he already has some info about this.

You can contact the team on Discord: https://chat.vitest.dev/

**Comment by Lfada** [comment]
Hi @sheremet-va thanks for getting back to me. Just saw Vitest claimed, which is great. 

Something for the future, that you all might want to consider if not 100% of the funds are needed is to split to your critical dependencies. 

A great example is Ethers.js, which is splitting 40% of all incoming funds to their dependencies as you can see [here](https://www.drips.network/app/projects/github/ethers-io/ethers.js).
