### ISSUE TITLE
vitest doesn't report coverage on external packages within an Nx package-based monorepo

### ISSUE THREAD

**Issue by ahayes91** [vitest-dev/vitest#5218]
### Describe the bug

I'm trying to figure out if I can get vitest to report on coverage provided by the tests in `package-A` on dependent code in `package-B`. 
The reproduction repository below shows that when `is-odd` depends on the `is-even` package, and a test runs in `is-odd`, no coverage is reported on the files in `is-even` even though they are being implicitly covered by those tests. 

I've tried a few settings from Vitest config like https://vitest.dev/config/#coverage-allowexternal and https://vitest.dev/config/#server-deps-external but I can't seem to crack it. 

Is this possible to achieve?

![Screenshot 2024-02-16 at 09 39 32](https://github.com/vitest-dev/vitest/assets/8914051/12593efd-931f-4a50-abe3-6523595267ae)

Thank you!

### Reproduction

https://github.com/ahayes91/vitest-coverage-bug

### System Info

```shell
System:
    OS: macOS 13.6.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 20.42 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.10.5 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
    Watchman: 2023.07.10.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 17.3
  npmPackages:
    @vitest/coverage-v8: latest => 1.2.2 
    @vitest/ui: latest => 1.2.2 
    vite: latest => 5.1.2 
    vitest: latest => 1.2.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Does `coverage.allowExternal` help?

**Comment by AriPerkkio** [comment]
I the `is-even` loaded through Vite? If you change the import coverage works fine:

```diff
-import { isEven } from 'is-even';
+import { isEven } from '../is-even/index';
```

**Comment by AriPerkkio** [comment]
This could also help:


```diff
-    deps: {
-      moduleDirectories: ['node_modules', path.resolve('../../packages')],
-    },
-    server: {
-      deps: {
-        external: ['is-even'],
-      }
-    }
+    alias: {
+      "is-even": path.resolve('./packages/is-even/index')
+    },
```

**Comment by ZackDeRose** [comment]
Hey @ahayes91 - I believe this may be due to the way your package.json is setup.

With the setup you have in your example, your `is-odd` isn't importing from the index.ts file from `is-even`, it's actually importing from `packages/is-even/dist/index.js`.

I'm not sure what your desired outcome is exactly - you _could_ change the `main` of your` package.json for `is-even` from `dist/index.js` to `index.ts` and this will show the proper coverage, but this is actually changing your build strategy away from an incremental build which you currently have.

**Comment by ahayes91** [comment]
Thank you folks! 

@ZackDeRose - would using an [integrated Nx monorepo](https://nx.dev/getting-started/tutorials/integrated-repo-tutorial) help with this problem? https://nx.dev/getting-started/tutorials/integrated-repo-tutorial#local-linking-of-packages seems to indicate that the local linking would allow projects to point to the src of their dependencies, but https://nx.dev/getting-started/tutorials/integrated-repo-tutorial#task-dependencies seems to indicate that a built `dist` folder is still required for `is-odd` to work.

When I look at Lerna's [getting started example](https://github.com/lerna/getting-started-example) it seems to me like it would have the same issue as the Nx package-based example here (because the packages `main` attributes still reference `dist`).

And then from a `vitest` point of view - this issue kind of makes me wonder what the point of running `vitest` from the root of the monorepo would be, if not to help report on coverage across all packages of the repo. What are the other use cases for `vitest` monorepo support (maybe sharing config is one I could think of...)?

**Comment by AriPerkkio** [comment]
> And then from a `vitest` point of view - this issue kind of makes me wonder what the point of running `vitest` from the root of the monorepo would be, if not to help report on coverage across all packages of the repo. What are the other use cases for `vitest` monorepo support (maybe sharing config is one I could think of...)?

Vitest's coverage works fine in monorepos, as long as Vite/Vitest is instructed to load those packages through Vite and not externalize them. Using `alias` as shown in https://github.com/vitest-dev/vitest/issues/5218#issuecomment-1948541599 works well.

**Comment by ahayes91** [comment]
Confirming that `alias` solution works for this example! 

I've also reached out on the [Nx Discord server](https://discord.com/channels/1143497901675401286/1208016102312124486/1210202923045486632) to see if an integrated Nx monorepo might better support coverage this way too. 

Thanks folks!
