### ISSUE TITLE
`vite` SSR module error when importing isomorphic library within `globalSetup` file

### ISSUE THREAD

**Issue by bhvngt** [vitest-dev/vitest#522]
### Describe the bug

I was trying out this feature and came across this peculiar issue. I am using an isomorphic library [supabase-js](https://github.com/supabase/supabase-js). When I import it in a file that is sourced by `globalSetup`, it throws following error.

```
21:38:19 [vite] Error when evaluating SSR module /node_modules/@supabase/supabase-js/dist/main/index.js:
ReferenceError: exports is not defined
    at eval (/node_modules/@supabase/supabase-js/dist/main/index.js:17:23)
    at instantiateModule (/home/projects/node-3cxxqh/node_modules/vite/dist/node/chunks/dep-76613303.js:60094:15)
21:38:19 [vite] Error when evaluating SSR module ./test/globalSetup.ts:
ReferenceError: exports is not defined
    at eval (/node_modules/@supabase/supabase-js/dist/main/index.js:17:23)
    at instantiateModule (/home/projects/node-3cxxqh/node_modules/vite/dist/node/chunks/dep-76613303.js:60094:15)
(node:6) UnhandledPromiseRejectionWarning: ReferenceError: exports is not defined
    at eval (/node_modules/@supabase/supabase-js/dist/main/index.js:17:23)
    at instantiateModule (/home/projects/node-3cxxqh/node_modules/vite/dist/node/chunks/dep-76613303.js:60094:15)
```

When I import the same in a normal test file it works fine.

### Reproduction

Here's the [playground](https://stackblitz.com/edit/node-3cxxqh) where the error is reproduced.

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Memory: 75.13 MB / 16.00 GB
    Shell: 3.3.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.13.1 - /var/folders/n0/qyzlydqj6cv8qt68qd6dbprh0000gn/T/fnm_multishells/47821_1641998710149/bin/node
    npm: 8.1.2 - /var/folders/n0/qyzlydqj6cv8qt68qd6dbprh0000gn/T/fnm_multishells/47821_1641998710149/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Chrome Canary: 99.0.4826.0
    Edge: 96.0.1054.43
    Firefox: 95.0.2
    Safari: 15.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dominikg** [comment]
To setup client connections please use [setupFiles](https://vitest.dev/config/#setupfiles) with `beforeAll`. 
Setup global would be a place to ensure your local supabase service is started.

You cannot share data or exports directly from globalSetup to test files.

In regards to the error it looks like supabase-js may be packaged in a way that vite.ssrLoadModule tries to load its cjs entry as esm

**Comment by bhvngt** [comment]
My understanding is that `beforeAll` runs at the beginning of every test file run. Hence, it ends up running `x` number of times  for `x` test files. I was looking at setting something up before the entire test run (for all files). For this use case, is `globalSetup` way to go?

[supabase-js](https://github.com/supabase/supabase-js/blob/master/package.json) is exporting `main(commonjs)`, `module(esm)` and `umd` builds. I am not very sure if this is `supabase` packaging issue or is this an issue with `vitejs`.

**Comment by bhvngt** [comment]
I am facing somewhat similar issue when I import `fetch` from [cross-fetch](https://github.com/lquixada/cross-fetch) in a `globalSetup` file.

```
13:15:13 [vite] Error when evaluating SSR module /node_modules/cross-fetch/dist/node-ponyfill.js:
ReferenceError: require is not defined
    at /node_modules/cross-fetch/dist/node-ponyfill.js:1:19
```

I have updated the [playground](https://stackblitz.com/edit/node-3cxxqh?file=test%2FglobalSetup.ts) for easy reproduction.

**Comment by dominikg** [comment]
supabase only declares a "module" field in package.json, not an exports map and it also use .js extension for both cjs and mjs instead of using explict .mjs. From a node perspective, supabase is a commonjs package. (module field is only a convention for bundlers, nothing official by node)

cross-fetch seems to be cjs too, you may get around that one by using node-fetch (v3 is esm) directly.

This seems to be a bug or implementation error that prevents working with cjs packages in globalSetup,

I'd like to learn more about your usecase/intentions. The way you're using isomorphic packages in globalSetup - which is only ever run in a node environment - still makes me wonder if you're trying to do something it is not meant for.

**Comment by bhvngt** [comment]
Thanks @dominikg for your reply. 

About my use case - I am setting up few fixtures in the database before my test runs begin. I am fetching some of the data from other services using fetch.  I would like to do this before any test is run and would like to dismantle them once all tests have run to keep the state cleaned up.

**Comment by bhvngt** [comment]
> supabase only declares a "module" field in package.json, not an exports map and it also use .js extension for both cjs and mjs instead of using explict .mjs. From a node perspective, supabase is a commonjs package. (module field is only a convention for bundlers, nothing official by node)

hmm. Will raise this as an issue to supabase team

**Comment by bhvngt** [comment]
> cross-fetch seems to be cjs too, you may get around that one by using node-fetch (v3 is esm) directly.

I tried [node-fetch](https://www.npmjs.com/package/node-fetch) (3.1.0) in my [playground](https://stackblitz.com/edit/node-3cxxqh?file=test%2FglobalSetup.ts) and got following error.

```
16:16:15 [vite] Error when evaluating SSR module /node_modules/fetch-blob/streams.cjs:
ReferenceError: require is not defined
    at /node_modules/fetch-blob/streams.cjs:22:19
    at instantiateModule (/home/projects/node-3cxxqh/node_modules/vite/dist/node/chunks/dep-76613303.js:60094:15)
16:16:15 [vite] Error when evaluating SSR module /node_modules/fetch-blob/index.js:
ReferenceError: require is not defined
    at /node_modules/fetch-blob/streams.cjs:20:19
    at instantiateModule (/home/projects/node-3cxxqh/node_modules/vite/dist/node/chunks/dep-76613303.js:60094:15)
16:16:15 [vite] Error when evaluating SSR module /node_modules/node-fetch/src/body.js:
ReferenceError: require is not defined
    at /node_modules/fetch-blob/streams.cjs:20:19
    at instantiateModule (/home/projects/node-3cxxqh/node_modules/vite/dist/node/chunks/dep-76613303.js:60094:15)
16:16:15 [vite] Error when evaluating SSR module /node_modules/node-fetch/src/index.js:
ReferenceError: require is not defined
    at /node_modules/fetch-blob/streams.cjs:20:19
    at instantiateModule (/home/projects/node-3cxxqh/node_modules/vite/dist/node/chunks/dep-76613303.js:60094:15)
16:16:15 [vite] Error when evaluating SSR module ./test/globalSetup.ts:
ReferenceError: require is not defined
    at /node_modules/fetch-blob/streams.cjs:20:19
    at instantiateModule (/home/projects/node-3cxxqh/node_modules/vite/dist/node/chunks/dep-76613303.js:60094:15)
```

**Comment by bhvngt** [comment]
I am just wondering why both `supabase` and `cross-fetch` works when run within the test files and breaks only when run within `globalSetup`.

**Comment by tirli** [comment]
I'm getting the same error even for simple server startup, like here:
``` js
import { createServer } from 'vite'

export async function globalSetup() {
  const server = await createServer({
    root: resolve(__dirname, '..'),
    server: {
      port: 3000,
    },
  })

  await server.listen()

  return async () => {
    await server.close()
  }
}
```

So probably not related to isomorphic libs?

**Comment by dominikg** [comment]
It is related to cjs. Even though vite itself is primarily working with es modules, it is itself distributed as cjs.


https://github.com/vitejs/vite/blob/3fb4118026e2745140894afb9755298656750f43/packages/vite/package.json#L10

dist/node/index.js
```js
'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var build = require('./chunks/dep-f5552faa.js');
require('fs');
```

related bug in vite repo: https://github.com/vitejs/vite/issues/2579

**Comment by Demivan** [comment]
As a workaround you can use `createRequire` to create a `require` function that can import CommonJs modules.
```js
import { createRequire } from 'module'
const require = createRequire(import.meta.url)
```

**Comment by dominikg** [comment]
i had implemented it with dynamic import before changing it to ssrLoadModule, there are also issues with that approach and using vite has the benefit of builtin ts support

**Comment by dominikg** [comment]
@bhvngt  @tirli  globalSetup should work with external modules now. Please let me know if you're still experiencing issues.

**Comment by bhvngt** [comment]
@dominikg its working pretty well. Here's the [playground](https://stackblitz.com/edit/node-3cxxqh?file=test%2FglobalSetup.ts) where it is working. 

When I run `vitest --ui`, `globalSetup` seems to be running twice. However, in `vitest run` `globalsetup` runs only once. Could this be due to the way `stackblitz` is setup? 

In general, is it expected to run once per entire test suite or will it run per thread run?

**Comment by dominikg** [comment]
once per run

**Comment by dominikg** [comment]
can confirm that with --ui globalSetup is executed twice, thats a different issue though.

**Comment by dominikg** [comment]
reported as https://github.com/vitest-dev/vitest/issues/679
