### ISSUE TITLE
/v RegExp flag is not recognized in Vitest

### ISSUE THREAD

**Issue by Y3drk** [vitest-dev/vitest#5220]
### Describe the bug

When writing a TypeScript (version 5.3.3) library I need a function using RegExp, which has to use the **/v** flag (trimmed example in test reproduction). 

According to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicodeSets) it should be supported in node 20.0.0+

The function on its own works all right, but when I want to test it with Vitest I receive an error:
```
 FAIL  tests/index.test.ts [ tests/index.test.ts ]
Error: Unknown regular expression flags.
 ❯ error node_modules/rollup/dist/es/shared/parseAst.js:337:30
 ❯ parseError node_modules/rollup/dist/es/shared/parseAst.js:972:9
 ❯ convertNode node_modules/rollup/dist/es/shared/parseAst.js:2057:12
 ❯ convertProgram node_modules/rollup/dist/es/shared/parseAst.js:965:12
 ❯ parseAstAsync node_modules/rollup/dist/es/shared/parseAst.js:2108:12
 ❯ ssrTransformScript node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:54036:15
 ❯ loadAndTransform node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:53632:11
```

### Reproduction

In a function use regex with **/v** flag: 
```
export function showcaseVFlag(name: string): string[] {
    const regexp = /(?:\p{RGI_Emoji})|(?:\P{Mark}(?:\p{Mark}*))/gv;
    return [...name.matchAll(regexp)].flat();
}
```
Then test it with Vitest:
```
describe("showcaseVFlag", () => {
    it("should separate graphemes correctly", () => {
       expect(showcaseVFlag("Hello 🌍! 👋")).toStrictEqual(["H", "e", "l", "l", "o", " ", "🌍", "!", " ", "👋"]);
    });
 });
```

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 4600H with Radeon Graphics
    Memory: 2.52 GB / 15.37 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.1.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.9.2 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.128)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vite: ^5.1.3 => 5.1.3
    vitest: ^1.2.2 => 1.2.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Interesting, it looks like this is such a new stuff and ecosystem hasn't caught up with it. Probably this needs to reported to upstream somewhere:

- [rollup](https://rollupjs.org/repl/?version=4.12.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQSUyMiUyMiUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJjb2RlJTIyJTNBJTIyY29uc29sZS5sb2coJTJGZm9vbyUyRnYpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiU3RCU3RCU3RA==) (error)
- [swc](https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA0vOzyvOz0nVy8lP19BPy8%2FP1y%2FTBABaTTA6FAAAAA%3D%3D&config=H4sIAAAAAAAAA1VPOw7DIAzdOQXy3KFi6NA79BCIOhERAYQdqSjK3QsJpM1mv4%2Ff8yqkhIkMPOVaxrJEnQjTuReEsmf9KQhwjkgm2chw6yxTpQbtCHdoOxhgnUbk6kJSd6WaA1wIhN3RsNl6O%2BT%2FTBPmmJDoKqxS7UeH10TRUmEO72Un2y%2B179HgAT9RDzsPg6VXd3JaUGxfBMLf3xcBAAA%3D) (error)
- [esbuild](https://esbuild.github.io/try/#dAAwLjIwLjAAAGNvbnNvbGUubG9nKC9mb29vL3Yp) (just pass through?)

One relevant issue I found is typescript's lib.d.ts
- https://github.com/microsoft/TypeScript/issues/57055

**Comment by AriPerkkio** [comment]
Did Rollup v4 switch to SWC's parser? 

- https://github.com/swc-project/swc/issues/8462
- https://github.com/swc-project/swc/blob/9ac304be9e3948e2d723afb80a8ff6cc9811d1a9/crates/swc_ecma_parser/src/parser/expr.rs#L343

**Comment by djstrong** [comment]
The `v` flag works in `jest`.

**Comment by hi-ogawa** [comment]
Nice, I didn't know sapphi-red already reported there :+1:
I don't know the detail but Rollup v4 uses swc internally https://github.com/rollup/rollup/pull/5073
