### ISSUE TITLE
createTaskCollector behaves differently when using .each in version 1.3.0

### ISSUE THREAD

**Issue by gudleik** [vitest-dev/vitest#5231]
### Describe the bug

Using createTaskCollector, the argument order is different in version 1.3.0 when using test.each() and test().
From custom.test.ts in the reproduction example (see link below):

```ts
// copied from https://vitest.dev/advanced/runner.html#your-task-function
export const test = createTaskCollector(function (
  this: any,
  name,
  fn,
  options
) {
  console.dir(
    {
      name,
      fn,
      options,
    },
    { showHidden: true, depth: null }
  );

  getCurrentSuite().task(name, {
    ...this, // so "todo"/"skip"/... is tracked correctly
    meta: {
      customPropertyToDifferentiateTask: true,
    },
    handler: async (...args: any[]) => {
      return fn.apply(this, args);
    },
    options,
  });
});

test('test', () => {
  expect(true).toBe(true);
});

test.each([true, false] as const)('test.each', (bool) => {
  expect(bool).toBe(bool);
});
```

The output from console.dir:

```js
{
  name: 'test',
  fn: [Function (anonymous)] { [length]: 0, [name]: '' },
  options: undefined
}
{
  name: 'test.each',
  fn: {},
  options: [Function (anonymous)] { [length]: 0, [name]: '' }
}
{
  name: 'test.each',
  fn: {},
  options: [Function (anonymous)] { [length]: 0, [name]: '' }
}
```

This works fine in version 1.2.2

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-gxa45z?file=test%2Fcustom.test.ts

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: 1.3.0 => 1.3.0 
    vite: latest => 5.1.3 
    vitest: 1.3.0 => 1.3.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JCMais** [comment]
so, any change was made to keep this on the same order? 🤔
