### ISSUE TITLE
Collector fails with very large test counts (>> 100000)

### ISSUE THREAD

**Issue by DerYeger** [vitest-dev/vitest#5234]
### Describe the bug

When a suite contains a huge number of tests (>> 100000), the collector's usage of the spread operator results in a "Maximum call stack size exceeded error".

### Reproduction

Include a huge number of tests (e.g., using `it.each`).
See https://stackblitz.com/edit/vitest-dev-vitest-pf19qj?file=test%2Fsuite.test.ts.

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M1
    Memory: 124.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/Library/Caches/fnm_multishells/20993_1708352067405/bin/node
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/20993_1708352067405/bin/npm
    pnpm: 8.15.1 - ~/Library/Caches/fnm_multishells/20993_1708352067405/bin/pnpm
    bun: 1.0.24 - ~/.bun/bin/bun
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 17.3.1
  npmPackages:
    @vitest/coverage-v8: 1.2.2 => 1.2.2
    @vitest/ui: 1.2.2 => 1.2.2
    vitest: 1.2.2 => 1.2.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DerYeger** [comment]
See https://github.com/vitest-dev/vitest/blob/e191e658d5052cb335ffe163a045ed294238d341/packages/runner/src/utils/tasks.ts#L20

**Comment by hi-ogawa** [comment]
Interesting find. It looks like this limitation is coming from runtime and people have especially have seen this when using `Math.max(...)` etc... https://stackoverflow.com/a/30834687

Just quick experiment on repl:

```sh
$ node
Welcome to Node.js v20.11.0.
Type ".help" for more information.
> [].push(...Array(1000000))
Uncaught RangeError: Maximum call stack size exceeded
> Math.max(...Array(1000000))
Uncaught RangeError: Maximum call stack size exceeded
> (() => {})(...Array(1000000))
Uncaught RangeError: Maximum call stack size exceeded
> [...Array(1000000)]
[
  undefined, undefined, undefined, undefined, undefined, undefined,
  ...
]
```

I think it would nice if we can avoid it, but there might be a few more places doing `push(...someArray)` where the size of `someArray` is proportional to the number of tests.
