### ISSUE TITLE
@vitest/coverage-v8@1.3.1 hangs indefinitely with Nestjs

### ISSUE THREAD

**Issue by noahw3** [vitest-dev/vitest#5252]
### Describe the bug

Using the `@vitest/coverage-v8` package with the latest version hangs while mocking a project using nestjs. Output prints `JUNIT report written to [path]/coverage/unit/junit.xml` and then the process does not exit, with no coverage report being output. This does not occur as of version 1.3.0. I'm guessing that it has something to do with the changes made to decorators in https://github.com/vitest-dev/vitest/pull/5206, as Nest makes heavy use of decorators.

### Reproduction

Technically this version does resolve after hanging for ~30 seconds, but hopefully that should be enough to highlight the issue.

https://github.com/noahw3/vitest/tree/main/examples/basic

### System Info

```shell
We also observed this in our CI environment, though it also reproduced locally.

  System:
    OS: macOS 14.1.2
    CPU: (10) arm64 Apple M1 Pro
    Memory: 623.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    pnpm: 8.10.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 17.1.2
  npmPackages:
    @vitest/coverage-v8: 1.3.1 => 1.3.1 
    vitest: 1.3.1 => 1.3.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Does it hang with `@vitest/coverage-istanbul` or without coverage?

**Comment by AriPerkkio** [comment]
I can reproduce the hang. Something as simple as removing `,` from this regexp fixes the issue. Look's like Regexr is also reporting this as slow matcher: https://regexr.com/7salk

https://github.com/vitest-dev/vitest/blob/4ff7159049e4dd63501cdf512aea3366b55691cf/packages/coverage-v8/src/provider.ts#L54

```diff
-const DECORATOR_METADATA_PATTERN = /_ts_metadata\("design:paramtypes"(\s|.)+?]\),/g
+const DECORATOR_METADATA_PATTERN = /_ts_metadata\("design:paramtypes"(\s|.)+?]\)/g
```

Could you @noahw3 or @wataruian try if that fixes the hangs in real world Nestjs project by modifying the `node_modules/@vitest/covearge-v8`.

**Comment by noahw3** [comment]
Yes, can confirm that adjusting the regex no longer hangs in my full project.
