### ISSUE TITLE
TypeScript vite.config.ts error after following docs: no overload matches this call

### ISSUE THREAD

**Issue by vladinator1000** [vitest-dev/vitest#5256]
### Describe the bug

Hi folks, I was following [the docs](https://vitest.dev/config/file.html):

> Using defineConfig from vite you should follow this:
```ts
/// <reference types="vitest" />
import { defineConfig } from 'vite'

export default defineConfig({
  test: {
    // ... Specify options here.
  },
})
```

...but when I open it in VSCode, there is a type error:
```
No overload matches this call.
  The last overload gave the following error.
    Object literal may only specify known properties, and 'test' does not exist in type 'UserConfigExport'.
```
the stack trace mentions the `node_modules/vite/dist/node/index.d.ts`

Looks like I'm not the only one having this issue: https://stackoverflow.com/questions/77153736/troubleshooting-vitest-setup-in-vite-config-js-with-react-ts-template#comment136927620_77655981

I'm not sure how to fix it because I don't understand TypeScript reference types.

### Reproduction

Open this `vite.config.ts` in VSCode

```ts
/// <reference types="vitest" />

import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  base: 'https://yupty.live',
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: [
      '@testing-library/jest-dom/extend-expect',
      './client/setUpTests.ts',
    ],
  },
})
```

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 9.66 GB / 15.59 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 21.6.1 - ~/.nvm/versions/node/v21.6.1/bin/node
    Yarn: 1.22.18 - /c/Program Files (x86)/Yarn/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.1/bin/npm
    bun: 1.0.0 - ~/.bun/bin/bun
  npmPackages:
    @vitejs/plugin-react: ^4.2.0 => 4.2.0 
    vite: ^5.0.4 => 5.0.4 
    vitest: ^1.3.1 => 1.3.1 
    typescript: 5.2.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fenghan34** [comment]
It should work well, I cannot reproduce the issue with the latest version at https://stackblitz.com/edit/vitest-dev-vitest-mj4mwf?file=vite.config.ts, as of that I would suggest 
- Check if Vitest is properly installed.
- Restart the TypeScript Server or reopen the editor.

**Comment by MiroslavPetrik** [comment]
I have the same issue. 
![image](https://github.com/vitest-dev/vitest/assets/38855190/8807ce4d-dcdc-40e5-bf2e-5cc6952cb1ef)

my `setup.ts` has 1 line
```
import "@testing-library/jest-dom/vitest";
```

Not only I get the `no overload matches...` on the `test` config property, but also on the jest matchers:

```
Property 'toBeInTheDocument' does not exist on type 'Assertion<HTMLElement>'.
```

Originally, I had `vitest.config.mts`, where the type mismatch is on plugins:
![image](https://github.com/vitest-dev/vitest/assets/38855190/9149f703-432a-4b50-87df-427ed5035d89)

I tried the `vite.config.mts` in hope that it will resolve this plugin type mismatch, but it only brought me here.

**Comment by jkbach** [comment]
I had this issue (`tsc` was failing), and it was resolved by including the two lines in the StackOverflow solution linked in the original issue:
```
/// <reference types="vitest" />
/// <reference types="vite/client" />
```

The `vitest` documentation[^1] only includes the first line, but both were necessary to satisfy the TS compiler in my case.

[^1]: https://vitest.dev/guide/#configuring-vitest
