### ISSUE TITLE
SyntaxError: ':focus-within' is not a valid selector

### ISSUE THREAD

**Issue by tiborpino** [vitest-dev/vitest#5258]
### Describe the bug

I use the matches selector with the value :focus-within.
`const hasSelectWrapperFocusWithin: boolean = iSelectWrapperRef.value?.matches(':focus-within') || false`

When I run an unit test with that code logic I am getting error `SyntaxError: ':focus-within' is not a valid selector`.

### Reproduction

Utilize the matches method from the HTMLElement interface with the value ':focus-within'.

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 159.44 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.21.3 - ~/.nvm/versions/node/v14.21.3/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 6.14.18 - ~/.nvm/versions/node/v14.21.3/bin/npm
  Browsers:
    Safari: 17.3.1
    Safari Technology Preview: 17.4
  npmPackages:
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0 
    vite: ^4.0.4 => 4.5.1 
    vitest: ^0.27.3 => 0.27.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
I cannot tell without a reproduction, but I think you might be hitting this jsdom issue:
- https://github.com/jsdom/jsdom/issues/3055
