### ISSUE TITLE
Can't update inline snapshot in Browser Mode

### ISSUE THREAD

**Issue by BenoitZugmeyer** [vitest-dev/vitest#5263]
### Describe the bug

I am reopening an issue for the previously closed issue https://github.com/vitest-dev/vitest/issues/2327.

When using vitest in Browser Mode, an error occurs when updating inline snapshots.

I believe this is because:
* in Browser Mode, `vite:resolve` is using the `browser` entry point to resolve dependencies
* `magic-string` ([this file](https://unpkg.com/browse/magic-string@0.30.7/dist/magic-string.es.mjs)) is loaded as a `module`
* it imports `@jridgewell/sourcemap-codec`, which has an UMD bundle as `browser` entry point (see [its `package.json`](https://unpkg.com/browse/@jridgewell/sourcemap-codec@1.4.15/package.json))

Importing an UMD bundle from an ES module doesn't work, hence the error.

### Reproduction

```bash
git clone https://gist.github.com/BenoitZugmeyer/a93d80dbbbadc9e4173a55d82874a875 repro
cd repro
npm ci
npm test -- -u --run
```
Output:
```
> test
> vitest -u --run


 RUN  v1.3.1 /home/alk/tmp/repro-vitest-error/repro
      Browser runner started at http://localhost:5173/


⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯

Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯
SyntaxError: The requested module '/node_modules/@jridgewell/sourcemap-codec/dist/sourcemap-codec.umd.js?v=15cdcfd9' does not provide an export named 'encode'
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 Test Files   (1)
      Tests   (1)
     Errors  1 error
   Start at  23:53:31
   Duration  2.22s (transform 0ms, setup 0ms, collect 7ms, tests 0ms, environment 0ms, prepare 0ms)
```

### System Info

```shell
System:
    OS: Linux 6.7 Arch Linux
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 21.55 GB / 31.14 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.2 - /usr/bin/node
    npm: 10.4.0 - /usr/bin/npm
  Browsers:
    Chromium: 122.0.6261.39
  npmPackages:
    @vitest/browser: ^1.3.1 => 1.3.1
    vitest: ^1.3.1 => 1.3.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Thanks for the concise reproduction and investigation! I put up a PR to fix this, but I think you can also do the same from your configuration as a temporary workaround:

```ts
import { defineConfig } from "vitest/config"

export default defineConfig({
  optimizeDeps: {
    include: ["vitest > @vitest/snapshot > magic-string"],
  },
  test: {
    browser: {
      enabled: true,
      name: "chrome",
    },
  },
});
```
