### ISSUE TITLE
TypeError: reports.create(...).execute is not a function

### ISSUE THREAD

**Issue by AIopsGeek** [vitest-dev/vitest#5264]
### Describe the bug

Getting below error while running `vitest run --coverage` :

 % Coverage report from v8

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: reports.create(...).execute is not a function
 ❯ V8CoverageProvider.reportCoverage node_modules/@vitest/coverage-v8/dist/provider.js:291:10
 ❯ Vitest.reportCoverage node_modules/vitest/dist/vendor/cac.wWT9ELdg.js:11918:7
 ❯ Vitest.runFiles node_modules/vitest/dist/vendor/cac.wWT9ELdg.js:11713:12
 ❯ Vitest.start node_modules/vitest/dist/vendor/cac.wWT9ELdg.js:11604:7
 ❯ startVitest node_modules/vitest/dist/vendor/cac.wWT9ELdg.js:18766:5
 ❯ start node_modules/vitest/dist/vendor/cac.wWT9ELdg.js:19516:17
 ❯ CAC.run node_modules/vitest/dist/vendor/cac.wWT9ELdg.js:19497:3

### Reproduction

Getting below error while running `vitest run --coverage` :

 % Coverage report from v8

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: reports.create(...).execute is not a function
 ❯ V8CoverageProvider.reportCoverage node_modules/@vitest/coverage-v8/dist/provider.js:291:10
 ❯ Vitest.reportCoverage node_modules/vitest/dist/vendor/cac.wWT9ELdg.js:11918:7
 ❯ Vitest.runFiles node_modules/vitest/dist/vendor/cac.wWT9ELdg.js:11713:12
 ❯ Vitest.start node_modules/vitest/dist/vendor/cac.wWT9ELdg.js:11604:7
 ❯ startVitest node_modules/vitest/dist/vendor/cac.wWT9ELdg.js:18766:5
 ❯ start node_modules/vitest/dist/vendor/cac.wWT9ELdg.js:19516:17
 ❯ CAC.run node_modules/vitest/dist/vendor/cac.wWT9ELdg.js:19497:3

### System Info

```shell
windows, node V 21.x, @vitest/coverage-v8": "^1.2.2" and  "vitest": "^1.2.2"
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Check your `coverage.reporter` configuration.

**Comment by AIopsGeek** [comment]
@AriPerkkio What exactly I should check?Below is my vitest config file:



import { defineConfig } from "vitest/config";
import { fileURLToPath, URL } from "url";

export default defineConfig({
    test: {
        coverage: {
            enabled: true,
            reporter: ["junit", "text", "json", "html", "lcov", "clover", "cobertura"],
            
        },
      
        setupFiles: ["./src/tests/setupTests.ts", "./src/tests/mocks/server.ts"],
        

      
        environment: "jsdom",
     
        include: ["./src/**/*.{test,spec}.{js,ts,jsx,tsx}"],
    },
    resolve: {
        alias: {
            "@": fileURLToPath(new URL("./src", import.meta.url)),
        },
    },

**Comment by AIopsGeek** [comment]
@AriPerkkio It worked. Thank you so much for your help!

**Comment by AIopsGeek** [comment]
@AriPerkkio - It worked. Thank you so much for your help!
