### ISSUE TITLE
Can't use global changes w/ a module (webcrypto-jwt)

### ISSUE THREAD

**Issue by fadi-george** [vitest-dev/vitest#528]
### Describe the bug

`jsonwebtoken` is not something that can be used with Vite and so I have to use an alternative package like `webcrypto-jwt` for signing jwts. For testing, I get the error `Error: crypto.subtle not found`.  So w/ Jest, I had to set that property in my setup test file, e.g. 

```
Object.defineProperty(global, 'crypto', {
  value: {
    subtle: {
      importKey: () => Promise.resolve(''),
      sign: () => Promise.resolve(''),
    },
  },
  writable: true,
});
```

But with vitest, this doesn't work.

### Reproduction

I have an example here:
https://stackblitz.com/edit/node-htxtbj?file=test%2FsomeActions.spec.tsx

But for whatever reason, this works in Stackblitz but downloading and running the project locally, it errors.

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 89.92 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Brave Browser: 97.1.34.80
    Chrome: 97.0.4692.71
    Safari: 15.2
  npmPackages:
    @vitejs/plugin-react: ^1.1.4 => 1.1.4 
    vite: 2.7.11 => 2.7.11
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fadi-george** [comment]
@sheremet-va thanks, that works.

**Comment by sheremet-va** [comment]
> @sheremet-va thanks, that works! Maybe we should have a similar behavior to jest (just a consideration).

We cannot run code similar to jest right now before of the poor ESM support (I am talking about `vm` module). So, right now the best way is to use `vi.stubGlobal` helper.

**Comment by macmillen** [comment]
@sheremet-va Somehow when using `vi.stubGlobal` it only works when I'm adding the mock directly into the source code file and not just the test file.

``` ts
const cryptoMock = { randomUUID: vi.fn(() => Math.random()) };
vi.stubGlobal("crypto", cryptoMock);
```

**Comment by sheremet-va** [comment]
> @sheremet-va Somehow when using `vi.stubGlobal` it only works when I'm adding the mock directly into the source code file and not just the test file.

Maybe you are trying to stub after you import a module that uses it? That way module will already be evaluated with original crypto.

**Comment by macmillen** [comment]
> > @sheremet-va Somehow when using `vi.stubGlobal` it only works when I'm adding the mock directly into the source code file and not just the test file.
> 
> Maybe you are trying to stub after you import a module that uses it? That way module will already be evaluated with original crypto.

You are right, thank you! :pray:  

But now my imports look like this:
``` ts
import { vi } from "vitest";
const cryptoMock = { randomUUID: vi.fn(() => Math.random()) };
vi.stubGlobal("crypto", cryptoMock);

import { createBlockStore } from "./block.store";
```

I guess there is no prettier way of doing this until `jsdom` supports `randomUUID`.

**Comment by sheremet-va** [comment]
> But now my imports look like this:

You can use `setupFiles` in your config to stub crypto, they are called before tests.

**Comment by macmillen** [comment]
> You can use `setupFiles` in your config to stub crypto, they are called before tests.

Awesome, thank you! :ok_hand:
