### ISSUE TITLE
TypeError: Unknown file extension ".css" 

### ISSUE THREAD

**Issue by JKannekens** [vitest-dev/vitest#5283]
### Describe the bug

I am gettting a unknown file extension on the React spectrum package. I read through some older issues where using the deps optimizer was mentioned but that still results in a error. The only things that were working for me was settings server.deps.inline to true but that doesn't sound right performance wise. Maybe I am missing something, but I cant figure it out based on the current documentation.

`TypeError: Unknown file extension ".css" for /home/projects/react-unit-test-practice-ovgqas/node_modules/@react-spectrum/color/dist/main.css`

### Reproduction

https://stackblitz.com/edit/react-unit-test-practice-ovgqas?file=vite.config.ts

Running vitest will fail the beginner.test.tsx where I added a depedency.

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 57.25 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
  Browsers:
    Chrome: 122.0.6261.69
    Safari: 17.2.1
  npmPackages:
    @vitejs/plugin-react-swc: ^3.6.0 => 3.6.0 
    @vitest/coverage-v8: ^1.3.0 => 1.3.0 
    vite: ^5.1.3 => 5.1.3 
    vitest: ^1.2.2 => 1.3.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Could you update your reproduction? It looks like it's using older versions different from your "System Info". I'm seeing this on stackblitz:

```
$ npx envinfo --system --npmPackages '{vitest,@vitest/*,vite,@vitejs/*}' --binaries --browsers
  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  npmPackages:
    @vitejs/plugin-react: ^1.3.2 => 1.3.2 
    @vitest/ui: latest => 0.19.1 
    vite: ^2.9.9 => 2.9.14 
    vitest: latest => 0.19.1
```

**Comment by yjrhgvbn** [comment]
I've run into a similar situation, you can add a configuration to solve it
```
 server: {
      deps: {
        inline: [/@react-spectrum.*/],
      },
    }
```
The problem is because `@react-spectrum` uses `import "./main.css"` in the .mjs file, and vitest is a direct introduction of `@react-spectrum` using the native `import` method.

I thought maybe vitest could do something automatic for this situation, like doing a content scan to automatically set it to inline

**Comment by JKannekens** [comment]
Oh excuse me! I updated the deps on the stackblitz. And i also added the server deps inline but it is still giving an error.

**Comment by hi-ogawa** [comment]
Thanks for updating a reproduction.
It looks like they got one more different namespace `@spectrum-icons`:

```
❯ npm ls @react-spectrum/icon
@vitest/example-testing-lib-react@ /home/projects/react-unit-test-practice-3czi7s
`-- @react-spectrum/color@3.0.0-beta.32
  `-- @react-spectrum/label@3.16.4
    `-- @spectrum-icons/ui@3.6.5
      `-- @react-spectrum/icon@3.7.11
```

so you need to add it to `server.deps.inline` too. Would this work for you? https://stackblitz.com/edit/react-unit-test-practice-3czi7s?file=vite.config.ts

**Comment by JKannekens** [comment]
Perfect! Thank you
