### ISSUE TITLE
Snapshot assertion APIs failed to work with `not`

### ISSUE THREAD

**Issue by fenghan34** [vitest-dev/vitest#5287]
### Describe the bug

When I was trying to address #3089, I found that not only `toThrowErrorMatchingInlineSnapshot()` but also other snapshot assertion APIs like `toMatchInlineSnapshot()` do not seem to work with `not`. 

Not sure if Vitest should support all of them, but at least a note in the documentation would be better.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-bqujvz?file=test%2Fbasic.test.ts

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: latest => 0.29.7 
    vite: latest => 4.2.1 
    vitest: latest => 0.29.7
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
As I said in https://github.com/vitest-dev/vitest/issues/3089#issuecomment-1962853661 I don't think we can support this. Snapshots are generated based on the input. If we use `.not`, then we cannot generate a snapshot because we don't know the input.

**Comment by sheremet-va** [comment]
Closed by https://github.com/vitest-dev/vitest/pull/5294
