### ISSUE TITLE
ReferenceError: Can't find variable: localStorage

### ISSUE THREAD

**Issue by aslan0402** [vitest-dev/vitest#5296]
### Describe the bug

Trying to mock API fn with localStorage inside and getting the error.

### Reproduction

```
export const getAuthFromLS = (key: string): string | null => {
  const auth = localStorage.getItem("auth");

  if (auth === null) {
    return null;
  }

  let obj;

  try {
    obj = JSON.parse(auth);
  } catch (error) {
    console.error(error);
    return null;
  }

  return obj[key];
};

```

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.23 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.11.0/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
    pnpm: 8.10.2 - ~/.nvm/versions/node/v20.11.0/bin/pnpm
    bun: 1.0.25 - ~/.bun/bin/bun
    Watchman: 2023.09.25.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 122.0.6261.69
    Safari: 17.2.1
  npmPackages:
    @vitejs/plugin-vue: ^5.0.4 => 5.0.4
    @vitest/coverage-istanbul: ^1.2.2 => 1.2.2
    vite: ^5.1.3 => 5.1.3
    vitest: ^1.2.2 => 1.2.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Local storage is not a Node API. You'll need to use `jsdom` or `happy-dom` environment: https://vitest.dev/config/#environment
