### ISSUE TITLE
Docs website bug - resets scroll to top of page

### ISSUE THREAD

**Issue by ardunster** [vitest-dev/vitest#5302]
### Describe the bug

Frequently, and annoyingly, when I have opened a page in Vitest's website docs, after several seconds (usually just when I found what I was looking for), the page will spontaneously reset the scroll to the top of the page. The most recent time, I noticed something in the page URL;  I was attempting to look at `https://vitest.dev/config/#pool`, but the address when the scroll reset was `https://vitest.dev/config/#pool-1-0-0` instead.  This makes me think the issue is with something automatically parsing the heading and accidentally including the version number in the expected hash tag, which is incorrect.

<img width="562" alt="Screenshot 2024-02-26 at 3 01 06 PM" src="https://github.com/vitest-dev/vitest/assets/61255483/2429e70f-8061-46f7-83b1-12be4d12189c">
<img width="272" alt="Screenshot 2024-02-26 at 3 01 16 PM" src="https://github.com/vitest-dev/vitest/assets/61255483/004862e6-0430-43c4-b74d-ff4cf916d51b">

### Reproduction

Search google for something like "vitest pool". Click on the "Configuring Vitest" result. Scroll until you see "pool" in the right hand navigation, click it, start reading about pool configuration.  Page often will reset to top. 

Doesn't seem to be every time, so I don't know if I'm just hitting the pool link before something else has finished running, or what exactly the problem is. 

### System Info

```shell
This is browsing in Brave Version 1.62.165 Chromium: 121.0.6167.184 (Official Build) (x86_64). My development setup is not relevant to this issue.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ardunster** [comment]
I'm not sure. I've observed this behavior multiple times in the past couple months since our team resumed working on the project that has vitest in it, but I couldn't tell you when it started.  It doesn't look like the links include the `-1-0-0` part either, but like I said, it doesn't happen when I click the link; it happens 15-30 seconds later, just after I've scrolled a bit down from the anchor and found what I am looking for, typically 😂   I'll keep an eye out for anything consistent next time it happens or see if I can get any useful data from the page.

**Comment by ardunster** [comment]
I just had this happen on https://vitest.dev/guide/mocking.html .   I opened the page from a google search, did command-F to find "variable", 15 seconds later as I was trying to use the example to write my code the page reset scroll to the top.

**Comment by sheremet-va** [comment]
The error is not reproducible in Vitest docs and any Vitepress docs, we don't have any special handling for the scroll behaviour. Maybe you have some extensions that cause this? I would recommend disabling extensions one by one to find the one responsible.

Closing this issue for now. Feel free to reopen it if this still happens without extensions.
