### ISSUE TITLE
[browser] Isolation through multiple ports

### ISSUE THREAD

**Issue by DenizUgur** [vitest-dev/vitest#5303]
### Clear and concise description of the problem

I'm using vitest's browser environment exclusively to test WebAssembly and Origin Private File System. By nature of both technologies, origin isolation is important. Since one test could modify the OPFS while other was reading it. As far as I know, there is no Atomic operations outside Web Workers so syncronisation might be tricky or unreliable. IndexedDB could be useful but that might interfere with user's code in an unpreditcable way.

### Suggested solution

I suggest to deploy a reverse proxy with the test runner. For every test file that could be parellelised can run on a different port and on a seperate tab. Providing origin isolation and global context isolation at the same time.

### Alternative

AFAIK, there is no other way create new origin on localhost without seperate ports.

### Additional context

For my use case, disabling `isolate` and `fileParallelisim` solved the syncronisation issue (duh...). It's not ideal but I'm using this workaround right now.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
> It's not ideal but I'm using this workaround right now.

I'd say this is not a workaround, but the solution for this type of testing you perform. Still, we will discuss this proposal with a team.

**Comment by sheremet-va** [comment]
The team thinks that disabling the parallelism is a solution here, we are not planning on changing how tests run in parallel.

**Comment by DenizUgur** [comment]
I understand that changing a fundamental part of the test runner might be troublesome or not worth it at all.

Please note that under some circumstances where IndexedDB, OPFS, or WebAssembly is being tested, test runners stability is questionable. It might be related to how I write my tests but having a clean slate everytime another test file is being tested would've been nice.

Different ports is one solution. Sending [`Clear-Site-Data`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data) is another (only on HTTPS though). Essentially, there should be a way to ensure the tests are run without any artifacts from prior tests.
