### ISSUE TITLE
Browser mode showing blank page

### ISSUE THREAD

**Issue by guansss** [vitest-dev/vitest#5308]
### Describe the bug

When using browser mode, the browser window pops up with a blank page regardless of the test status.

![image](https://github.com/vitest-dev/vitest/assets/46285865/913cf92c-37bd-4e9d-a8cb-c21477b68a65)

I guess it's because the iframe's `src` assignment was removed [in this PR](https://github.com/vitest-dev/vitest/pull/5036/files#diff-00ad3349d154afc9394578cd831054bc7f8cae7432715a6908353649d25aa18aL198-L199)?

### Reproduction

It's just a basic setup so I'm just pasting the files here:

```json
{
  "name": "vitest-ui-bug",
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "test": "vitest"
  },
  "devDependencies": {
    "vitest": "^1.3.1"
  }
}
```

```js
import { test, expect } from 'vitest';

test('foo', () => {
  expect(window.innerWidth).toBeGreaterThan(0);
});
```

```sh
npx vitest --browser=chrome
```

The test passed normally.

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 3.48 GB / 15.80 GB
  Binaries:
    Node: 18.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\scoop\apps\yarn\current\bin\yarn.CMD
    npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.128)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    vitest: ^1.3.1 => 1.3.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Did you try passing down `--ui` flag?

**Comment by GeuntaBuwono** [comment]
same here, got 404 on `.js` file on coverage. 

![image](https://github.com/vitest-dev/vitest/assets/25718928/4e4b0259-4773-4223-9e5a-98785c7ef2a3)

**Comment by guansss** [comment]
I just tried and it opened the UI in my default browser (Edge), this might not be the expected behavior because in previous Vitest 
 versions the UI would be opened in the same browser that runs tests.

Previously I was using Vitest v1.0.1 and it worked fine without passing the `--ui` flag.

**Comment by luin** [comment]
Hope I will have time later to provide more information, but the current issue is that after upgrading from 1.1.3 to 1.3.1, sometimes the blank screen issue occurs. It seems there are no errors in the console, but the body is empty.

**Comment by jaens** [comment]
I am guessing this _might_ be because 4f40177e06d57787394e1da5ceb0355d67acd6aa changed the position where the test container is rendered, so it is always _after_ the UI iframe (previously it was just rendered... wherever, I suppose).

cc @sheremet-va

**Comment by SongYuWong** [comment]
![code](https://github.com/vitest-dev/vitest/assets/152368829/9a82e762-bb31-4b5e-b711-029e20d431e4)
I looked into it, and does the final packaging relate to this 'index.html' file? Can it be adjusted?
