### ISSUE TITLE
ERR_MODULE_NOT_FOUND in dependency without .js in import

### ISSUE THREAD

**Issue by simonmeyerrr** [vitest-dev/vitest#5309]
### Describe the bug

I get `ERR_MODULE_NOT_FOUND` when running vitest, but I don't have any issue when using `ts-node` on my code.

I don't know if the error is specific to the library I use, but in it there is a `table-client.js` and `table-client.d.ts` in the dist directory of the library so I don't see any issue in it if it works with `ts-node`.

I found a similar issue on stackoverflow without any response: https://stackoverflow.com/questions/76052852/vitest-does-not-find-file-of-dependency

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-buvhpm?file=src%2Fbasic.ts

- Installed and import `@hexlabs/dynamo-ts` 
- `npm run test` generate this error:

```
Error: Cannot find module '/home/projects/vitest-dev-vitest-sa1w6n/node_modules/@hexlabs/dynamo-ts/dist/table-client' imported from /home/projects/vitest-dev-vitest-sa1w6n/node_modules/@hexlabs/dynamo-ts/dist/index.js
 ❯ __node_internal_ ../../../blitz.c9a8a620.js:36:5406
 ❯ new <anonymous> ../../../blitz.c9a8a620.js:36:4168
 ❯ ../../../blitz.c9a8a620.js:114:12002
 ❯ ../../../blitz.c9a8a620.js:114:12159
 ❯ defaultResolve ../../../blitz.c9a8a620.js:114:12167
 ❯ nextResolve ../../../blitz.c9a8a620.js:248:2120
 ❯ ESMLoader.resolve ../../../blitz.c9a8a620.js:248:7556
 ❯ ESMLoader.getModuleJob ../../../blitz.c9a8a620.js:248:4387
 ❯ ../../../blitz.c9a8a620.js:181:932
 ❯ _0x15be0c.link ../../../blitz.c9a8a620.js:352:381954
 ❯ ../../../blitz.c9a8a620.js:181:893

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { code: 'ERR_MODULE_NOT_FOUND' }
```

### System Info

```shell
System:
    OS: Windows 10
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.11.0 - C:\Program Files\nodejs\pnpm.CMD
  npmPackages:
    vitest: 1.2.2 => 1.2.2 (Some issue with 1.3.1)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Does it work if you add the package in `deps.optimizer.ssr.include`?

```ts
deps: {
  optimizer: {
    ssr: {
      enabled: true,
      include: ["@hexlabs/dynamo-ts"],
  }
 }
}
```

You might want to report `@hexlabs/dynamo-ts` that their package doesn't work in ESM with following reproduction:

```js
// index.mjs
import { TableDefinition } from "@hexlabs/dynamo-ts";
console.log(TableDefinition);
```

```sh
$ node index.mjs 
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/x/node_modules/.pnpm/@hexlabs+dynamo-ts@6.0.182_@aws-sdk+client-dynamodb@3.523.0/node_modules/@hexlabs/dynamo-ts/dist/table-client' imported from /x/node_modules/.pnpm/@hexlabs+dynamo-ts@6.0.182_@aws-sdk+client-dynamodb@3.523.0/node_modules/@hexlabs/dynamo-ts/dist/index.js
```

https://nodejs.org/api/esm.html#mandatory-file-extensions

**Comment by simonmeyerrr** [comment]
> ```ts
> deps: {
>   optimizer: {
>     ssr: {
>       enabled: true,
>       include: ["@hexlabs/dynamo-ts"],
>   }
>  }
> }
> ```

Worked for me, thank you very much ! I will forward it to the package maintainer.
