### ISSUE TITLE
Test after retry should check the same snapshot, not create a new one

### ISSUE THREAD

**Issue by itsgdpierzchalski** [vitest-dev/vitest#5312]
### Describe the bug

If I add retry to the test and for some reason it didn't match the snapshot on the first loop, it shouldn't create a new snapshot and passing the test, but check the same snapshot again.

### Reproduction

_test.spec.js_

```
import { test, expect } from 'vitest';

const foo = {
  bar: 1,
  bar2: 'test',
};

test('foo', { retry: 1 }, () => {
  expect(foo).toMatchSnapshot();
});
```

_test.spec.js.snap_

```
// Vitest Snapshot v1, https://vitest.dev/guide/snapshot.html

exports[`foo 1`] = `
{
  "bar2": "test",
}
`;
```

```
npx vitest run src/test.spec.js
```

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700K
    Memory: 18.34 GB / 31.76 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.52)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitejs/plugin-vue: 4.2.3 => 4.2.3
    @vitest/ui: 1.3.1 => 1.3.1
    vite: 5.0.10 => 5.0.10
    vitest: 1.3.1 => 1.3.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Thanks for raising an issue. Not sure if it's possible to support this but it looks like a weird bug. I made a reproduction on stackblitz with comments to explain the issue:
https://stackblitz.com/edit/vitest-dev-vitest-pcvtxp?file=test%2Ffile.test.ts

```tsx
import { test, expect } from 'vitest';

test('file', { retry: 1 }, () => {
  //
  // Initially
  //   expect('first').toMatchSnapshot();
  ///
  // which will create snapshot file with:
  //   exports[`file 1`] = `"first"`;
  //
  // Changing it to "second" will create a following snapshot
  //   exports[`file 1`] = `"first"`;
  //   exports[`file 2`] = `"second"`;
  //
  // After that, running "u" (update snapshot) cannot remove the first one.
  //
  expect('second').toMatchSnapshot();
});
```

**Comment by itsgdpierzchalski** [comment]
I found something similar in the jest repo:
https://github.com/jestjs/jest/issues/7493

**Comment by hi-ogawa** [comment]
Interesting, maybe we can borrow some ideas. Thanks for the pointer!

**Comment by sheremet-va** [comment]
We need to rewrite how the snapshot client works to make this work. Since #4796 there is only a single snapshot state per file, so we cannot rollback changes depending on the _test_ state (in jest, the state is per test, but it's also a singleton which doesn't support `concurrent` retriable tests).

I think we need to have a map of states based on the test ID (or the combination of `filepath` + `name`) and reset it in the `onBeforeTryTask` hook:

https://github.com/vitest-dev/vitest/blob/bc4b6073c68ae98751d86fb3b8b6de3e2cd45ce9/packages/vitest/src/runtime/runners/test.ts#L122

Then, the global test state can aggregate all results from smaller states inside itself.

**Comment by Rihyx** [comment]
Is there a way to make `vitest` throw errors if snapshots do not exist? And not to create a new one?

**Comment by sheremet-va** [comment]
> Is there a way to make `vitest` throw errors if snapshots do not exist? And not to create a new one?

You can run Vitest with `--no-update` flag.

**Comment by Rihyx** [comment]
> > Is there a way to make `vitest` throw errors if snapshots do not exist? And not to create a new one?
> 
> You can run Vitest with `--no-update` flag.

As I understand this flag will not prevent creating a new snapshot. For example, there can be a case when there is a function which got refactored and changed the name and if the function name is in the test then the old snapshot will get obsolete. In the CI the test will not fail because a new snapshot will be created. But there is a high possibility of the code being broken.

**Comment by sheremet-va** [comment]
> > > Is there a way to make `vitest` throw errors if snapshots do not exist? And not to create a new one?
> > 
> > 
> > You can run Vitest with `--no-update` flag.
> 
> As I understand this flag will not prevent creating a new snapshot. For example, there can be a case when there is a function which got refactored and changed the name and if the function name is in the test then the old snapshot will get obsolete. In the CI the test will not fail because a new snapshot will be created. But there is a high possibility of the code being broken.

Did you run Vitest with this flag before reporting this?

**Comment by sheremet-va** [comment]
`--no-update` should be after the test file filter

**Comment by sheremet-va** [comment]
> `--no-update` should be after the test file filter, or you need to do `--update=false`

I did check it here and it indeed doesn't work as expected: https://stackblitz.com/edit/vitest-dev-vitest-2kw17c?file=package.json&initialPath=__vitest__/

Vitest shouldn't create snapshot files in CI (update is false there by default) - this is a bug, it didn't work like that before.

**Comment by Rihyx** [comment]
> > `--no-update` should be after the test file filter, or you need to do `--update=false`
> 
> I did check it here and it indeed doesn't work as expected: https://stackblitz.com/edit/vitest-dev-vitest-2kw17c?file=package.json&initialPath=__vitest__/
> 
> Vitest shouldn't create snapshot files in CI (update is false there by default) - this is a bug, it didn't work like that before.

Thanks for verifying. Yeah this has to be fixed :(

**Comment by sheremet-va** [comment]
> Thanks for verifying. Yeah this has to be fixed :(

I also checked with `CI=true` and it did throw an error correctly, so it looks like it's just an issue with `--update` flag

**Comment by sheremet-va** [comment]
@Rihyx Ok, I checked the implementation. `--no-update` only affects if snapshots are updated - they will always be created in a non-CI environment (there is no flag to disable this) - you can also use `UPDATE_SNAPSHOT` env, by the way (needs to be truthy). Please create a separate issue regarding this behaviour if you want it changed - this issue is unrelated.

**Comment by Rihyx** [comment]
> @Rihyx Ok, I checked the implementation. `--no-update` only affects if snapshots are updated - they will always be created in a non-CI environment (there is no flag to disable this) - you can also use `UPDATE_SNAPSHOT` env, by the way (needs to be truthy). Please create a separate issue regarding this behaviour if you want it changed - this issue is unrelated.

All right, thanks a lot. I will create a separate issue for that.

**Comment by jimmyn** [comment]
I'm experiencing the same issue. When I set the `retry` parameters, new snapshots are created with each run.
