### ISSUE TITLE
Rename `vi.mock` to `vi.hoistedMock`

### ISSUE THREAD

**Issue by EdgarOrtegaRamirez** [vitest-dev/vitest#5313]
### Clear and concise description of the problem

As a developer using Vitest I want to clearly know that `vi.mock` is hoisted so that I don't forget this mock is hoisted automatically by Vitest.

### Suggested solution

Rename `vi.mock` to `vi.hoistedMock` or `vi.mockHoisted` or similar

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
This is one of those times when you should just know. I would recommend reading the documentation or JSDOC before using any function without assuming how it works. We mention the fact that it's hoisted in both documentation and JSDOC.
