### ISSUE TITLE
Filter ambiguities

### ISSUE THREAD

**Issue by pboguslawski** [vitest-dev/vitest#5315]
### Describe the bug

One cannot use [filter](https://vitest.dev/guide/cli.html#vitest) that matches vitest command, i.e. when trying to run tests with `run` in path with
```
vitest run
```
`run` is interpreted as command not `filter`.

Consider moving filter to separate option i.e. `--testPathContain` to avoid ambiguity.

### Reproduction

Try to run all tests with `run` in their path with filter.

### System Info

```shell
any
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
I think this tends to happen in any cli tools with top level command and sub commands.
I guess quick workaround is to use the sub command version of top level command, for example, `vitest watch run` would keep `run` as filename filter. This would be actually shorter than `vitest --testPathContain run`, so maybe this is good enough for you?

**Comment by pboguslawski** [comment]
> I think this tends to happen in any cli tools with top level command and sub commands.

Issue is about misleading mixing subcommand and option on same position. Think of problems when one day vitest decides to introduce subcommad like `reportAllMySecretsToThem` or `testButForceSuccess` and someone is using it now as filter...

> I guess quick workaround is to use the sub command version of top level command

Workaround seems to work but does not resolve ambiguity.

> This would be actually shorter than vitest --testPathContain run

Syntax should be simple but not misleading nor error-prone. If `--testPathContain` is too much, maybe first vitest argument, if present, should be always interpreted as subcommand not filter.

**Comment by sheremet-va** [comment]
I am personally fine with how it works right now, but let's discuss this within the team before making a final decision.

**Comment by sheremet-va** [comment]
As a team, we want to keep the current shortcuts. In the future, we won't introduce new shortcuts, instead they will be exposed as `--flags`.
