### ISSUE TITLE
onConsoleLog should be typed `false | undefined` or `boolean | undefined`

### ISSUE THREAD

**Issue by ST-DDT** [vitest-dev/vitest#5317]
### Clear and concise description of the problem

According to @bradzacher in https://github.com/typescript-eslint/typescript-eslint/issues/8576#issuecomment-1971733783 the current typing of the method is flawed. As the current `void` part of the method would indicate that you shouldn't care about the result.

### Suggested solution

Change the return signature of `onConsoleLog` to `false | undefined` or `boolean | undefined`.

The later variant especially would allow for ternaries or simple return expressions like:

````ts
onConsoleLog(type) {
  return type != 'stderr';
}
````

### Additional context

https://vitest.dev/config/#onconsolelog

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
Good point. I don't think restricting it to `false` makes much sense. Probably it was just a small oversight and the similar one just below already have `boolean | void`, so probably we can do the same for `onConsoleLog`.

https://github.com/vitest-dev/vitest/blob/a14b648d354bd2e2ea2114c5d744a42ee1ced90c/packages/vitest/src/types/config.ts#L583-L591
