### ISSUE TITLE
Different import techniques with global setup in a workspace environment

### ISSUE THREAD

**Issue by luixo** [vitest-dev/vitest#5318]
### Describe the bug

Hello,
I plan to migrate my tests - previously in one directory - to a workspaces setup.

I have a global setup file that spins up a server to manage mock DBs for my tests.
I have two options now:
- spin up a server for each project (setting `globalSetup` individually in `projects/a/vitest.config.ts`)
- spin up a single server for all projects (settings `globalSetup` in `<root>/vitest.config.ts`)

For the second choice there is a problem - I run `vitest` with `vite-tsconfig-paths` to help resolving path aliases. It works great, but global setup files are not affected by paths resolution.

I guess, using `globalSetup` for a single project should be the same as using it in "all-project" config file: either both should fail on importing or both should resolve.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-tkkynz

### System Info

```shell
System:
    OS: macOS 14.2
    CPU: -
    Memory: -
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    Yarn: 3.6.2 - ~/.nvm/versions/node/v20.10.0/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
  Browsers:
    Chrome: -
    Safari: -
  npmPackages:
    vitest: ^1.2.2 => 1.2.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Your reproduction doesn't have `plugins: [tsconfigPaths()]` in the root config, so I think it's expected that `~setup/setup` won't be resolved. 

It looks working after adding the plugin. Could you confirm?
https://stackblitz.com/edit/vitest-dev-vitest-ja1xw3?file=vitest.config.ts

**Comment by luixo** [comment]
Oh, that does actually make sense and it worked perfectly in my local setup.
Thank you!
