### ISSUE TITLE
Custom query suffix imports are tripping up vite:import-analysis in browser tests

### ISSUE THREAD

**Issue by haywirez** [vitest-dev/vitest#5330]
### Describe the bug

For some custom [query suffix import](https://vitejs.dev/guide/features.html#import-with-query-suffixes) plugins such as [vite-plugin-arraybuffer](https://github.com/tachibana-shin/vite-plugin-arraybuffer), the vite:import-analysis stage gets tripped up, but seemingly only in browser tests - CLI works fine.

```js
import wasmBuffer from './test.wasm?arraybuffer'
```

```error
[vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .wasm?arraybuffer file format, or if it's an asset, add "**/*.wasm?arraybuffer" to `assetsInclude` in your configuration.
```

This shouldn't be the case, as the transform returns valid JS.

### Reproduction

Here's a simple example with no issues running tests in CLI mode, using vite + vitest:
[codesandbox.io/p/devbox/frosty-paper-f738ps](https://codesandbox.io/p/devbox/frosty-paper-f738ps)

Once you add the @vitest/browser package etc, it fails import-analysis:
[codesandbox.io/p/devbox/hopeful-oskar-rpdw7j](https://codesandbox.io/p/devbox/hopeful-oskar-rpdw7j)

### System Info

```shell
Not relevant
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
I think you might be hitting this https://vitest.dev/config/file.html

> Create `vitest.config.ts`, ... - it means all options in your `vite.config` will be __ignored__

Could you try adding the same `plugins` to `vitest.config.ts`? Or alternatively you can remove `vitest.config.ts` and add `test: { browser: ... }` to `vite.config.ts`.

**Comment by haywirez** [comment]
Yes that was it! Thank you for the tip.
