### ISSUE TITLE
Vitest workspace not detecting tests in monorepo

### ISSUE THREAD

**Issue by programmer24601** [vitest-dev/vitest#5336]
### Describe the bug

When attempting to run the test suite from the root directory of a monorepo which is structured:
```
./packages/backend/src/...
./packages/backend/package.json
./packages/backend/vitest.config.ts

./packages/frontend/src/...
./packages/frontend/package.json
./packages/frontend/vite.config.ts

./package.json
./vitest.workspace.ts
```

Vitest returns:
```
 DEV  v1.3.1 /vitest-monorepo

 ❯ |backend| src/hello-world.test.ts (0)
 ❯ |frontend| src/App.test.tsx (0)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 2 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  |frontend| src/App.test.tsx [ packages/frontend/src/App.test.tsx ]
Error: No test suite found in file /vitest-monorepo/packages/frontend/src/App.test.tsx
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/2]⎯

 FAIL  |backend| src/hello-world.test.ts [ packages/backend/src/hello-world.test.ts ]
Error: No test suite found in file /vitest-monorepo/packages/backend/src/hello-world.test.ts
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[2/2]⎯
```

However `cd`ing into each package and running the test suite succeeds. The vitest/vscode extension also does not present any buttons to run the tests.

### Reproduction

https://stackblitz.com/~/github.com/programmer24601/vitest-monorepo

`npm ci` in the following directories:
```
./<root>
./packages/backend
./packages/frontend
```

Then `npm run test` in root.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Memory: 17.26 GB / 31.16 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.11.1 - ~/.asdf/installs/nodejs/20.11.1/bin/node
    npm: 10.2.4 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.15.4 - ~/.asdf/shims/pnpm
  Browsers:
    Chrome: 121.0.6167.160
  VS Code Extensions:
    Vitest v0.4.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
This might be because you have a different copy of `vitest` at the root `node_modules/vitest` and each project `packages/frontend/node_modules/vitest`.

One way to fix this would be to remove `vitest` dependencies from `packages/frontend` and `packages/backend`, so that it always picks up the one at the `node_modules/vitest`.
It looks like `vitest-dom` also pulls in `vitest`, so you might want to move it to root `package.json`.

Or maybe have you considered using npm workspaces https://docs.npmjs.com/cli/v7/using-npm/workspaces ? This will probably deduplicate `vitest `properly, so that's another way.

**Comment by programmer24601** [comment]
Excellent advice @hi-ogawa, thank you. I was able to get all the issues resolved simply by enabling npm workspaces, as you suggested. See branch here: https://github.com/programmer24601/vitest-monorepo/tree/npm_workspace
