### ISSUE TITLE
Injecting polyfills for vitest browser

### ISSUE THREAD

**Issue by edoardocavazza** [vitest-dev/vitest#5347]
### Clear and concise description of the problem

Vitest for browser ships with a polyfill-free policy, which is good. Sometimes we need to run tests across older browsers (such as Safari 14) that does not support features like `BroadcastChannel`.

### Suggested solution

Add a sort of setup file for the runner to inject in index.html and tester.html files, in order to polyfill some features.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by edoardocavazza** [comment]
Nope, they are loaded after `BroadcastChannel` initialization, so the polyfill won't work.

**Comment by sheremet-va** [comment]
If `BroadcastChannel` channel is not supported by [compatible versions](https://vitejs.dev/guide/build.html#browser-compatibility) (we use the same compatibility table that Vite Dev server uses) then we should rewrite it to use something else.

**Comment by sheremet-va** [comment]
As a team, we decided that the Vitest browser mode only supports browsers that implement `BroadcastChannel`, this is now documented.

**Comment by edoardocavazza** [comment]
It is reasonable that vitest wont support old browsers out of the box. I was just asking if you would consider to support scripts injection in order to let developers to load polyfills themselves 🙂

**Comment by sheremet-va** [comment]
We did another round of discussion and decided it would be a good idea to expose an option to inject a script into html

**Comment by edoardocavazza** [comment]
Thank you so much!
