### ISSUE TITLE
Benchmark with `json` reporter and `outputFile` causes OOM crash

### ISSUE THREAD

**Issue by BeeeQueue** [vitest-dev/vitest#5349]
### Describe the bug

When trying to get the output of benchmarks as JSON and written using `outputFile` vitest crashes due to OOM.

Reproduced both locally and in CI.

### Reproduction

See the CI steps for [this failed run](https://github.com/BeeeQueue/node-cli-colors-benchmark/actions/runs/8182172724/job/22373106447).

Clone the project and run it

### System Info

```shell
Basic GH Actions runner,

Local:
  System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 11.46 GB / 31.92 GB
  Binaries:
    Node: 21.7.0 - ~\AppData\Local\nvm-rust\versions\21.7.0\node.EXE
    npm: 10.5.0 - ~\AppData\Local\nvm-rust\versions\21.7.0\npm.CMD
    pnpm: 8.15.4 - ~\AppData\Local\nvm-rust\versions\21.7.0\pnpm.CMD
    bun: 1.0.30 - ~\bin\bun.EXE
  Browsers:
    Edge: Chromium (122.0.2365.66)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    vitest: 1.3.1 => 1.3.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
It looks like generated json file is very huge due to all `samples` and `JSON.stringify` makes all double floating point to ascii strings, so it'll gets bigger in memory.

I'm not sure if `samples` are something users can consume, so maybe we need to make it opt-in to output this.

https://github.com/vitest-dev/vitest/blob/c3eb8deb768f6ef1adff8e6644ce99de58fd8b01/packages/vitest/src/node/reporters/benchmark/json.ts#L35-L36

https://github.com/vitest-dev/vitest/blob/c3eb8deb768f6ef1adff8e6644ce99de58fd8b01/packages/vitest/src/node/reporters/benchmark/json.ts#L53

```sh
$ ls -lh examples/basic/out.json 
-rw-r--r-- 1 hiroshi hiroshi 399M Mar  7 12:31 examples/basic/out.json
```

```json
{
  "numTotalTestSuites": 1,
  "numTotalTests": 1,
  "testResults": {
    "": [
      {
        "name": "foo",
        "rank": 1,
        "rme": 0.5177719116201918,
        "samples": [
          0.00002999999992425728,
          0.00002999999992425728,
          ...
```

**Comment by sheremet-va** [comment]
Let's close this in favour of #5297.
