### ISSUE TITLE
mock fs doesn't work as expected after upgrade from 0.29.8 to 1.3.1

### ISSUE THREAD

**Issue by await-ovo** [vitest-dev/vitest#5351]
### Describe the bug

When we upgraded from Vitest `v0.29.8` to `v1.3.1`, `vi.mock('fs', () => {})` was not working, here's the code:

``` 
import { assert, expect, it, describe, vi, beforeAll, afterAll } from 'vitest';
import { readContent } from '../src/index';

describe('test-mock', () => {
  beforeAll(() => {
    vi.mock('fs', () => {
      return {
        readFileSync(path: string) {
          if (path.endsWith('example.html')) {
            return 'some-mock-text';
          }
          return `/** ${path} **/`;
        },
      };
    });
  });

  it('test 1', () => {
    const res = readContent();
    expect(res).toBe('some-mock-text');
  });
  afterAll(() => {
    vi.unmock('fs');
  });
});

```

### Reproduction

Here is the stackbliz repo to reproduce this problem: 

* v0.29.8: https://stackblitz.com/edit/stackblitz-starters-vqwtgb?file=test%2Findex.test.ts

   you can see that the fs mock worked as expected:

![image](https://github.com/vitest-dev/vitest/assets/41503212/07eab169-0514-4c57-97fa-f062b9299fe9)

* v1.3.1: https://stackblitz.com/edit/stackblitz-starters-43ldmt?file=test%2Findex.test.ts

   you will see that test failed as below:
   
![image](https://github.com/vitest-dev/vitest/assets/41503212/e9fa6bb5-60e0-4392-bcc8-ba5cecd8bda7)

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    vitest: 1.3.1 => 1.3.1 
```
```


### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`vi.mock` and `vi.unmock` are hoisted: https://vitest.dev/api/vi.html#vi-mock

There is zero effect of calling them inside `beforeAll`/`afterAll` hooks - they are moved to the top of the file and executed before imports. In your example you mock and unmock the same module, so there is no effect. Move `vi.mock` outside of `beforeAll` and remove `vi.unmock` and everything will work as expected.

The fact that it worked somehow before is a bug.
