### ISSUE TITLE
missing documentation or examples on how to run vitest --typecheck with custom tsconfig in some file path

### ISSUE THREAD

**Issue by estebanabaroa** [vitest-dev/vitest#5356]
### Describe the bug

missing documentation or examples on how to run vitest --typecheck with custom tsconfig in some file path

### Reproduction

not relevant

### System Info

```shell
not relevant
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Did you try this one `typecheck.tsconfig` https://vitest.dev/config/#typecheck-tsconfig?

**Comment by estebanabaroa** [comment]
> Did you try this one `typecheck.tsconfig` https://vitest.dev/config/#typecheck-tsconfig?

I tried `vitest run --config config/vitest.config.ts --typecheck.enabled --typecheck.tsconfig config/tsconfig.json` and it didn't seem to check types.

**Comment by hi-ogawa** [comment]
Thanks for trying it out. If it's not working then that could be a bug. Can you provide a reproduction?
As written at the top https://vitest.dev/config, it might need to be written in config since not all options are supported via cli flags:

```ts
// vite.config.ts or vitest.config.ts

defineConfig({
  test: {
    typecheck: {
      tsconfig: "..."
    }
  }
})
```

**Comment by estebanabaroa** [comment]
> Thanks for trying it out. If it's not working then that could be a bug. Can you provide a reproduction? As written at the top https://vitest.dev/config, it might need to be written in config since not all options are supported via cli flags:
> 
> ```ts
> // vite.config.ts or vitest.config.ts
> 
> defineConfig({
>   test: {
>     typecheck: {
>       tsconfig: "..."
>     }
>   }
> })
> ```
i 
I had also tried that and it didn't seem to check types, I dont have time to investigate it more right now but maybe later
