### ISSUE TITLE
`vi.mock` does not use provided mock implementation

### ISSUE THREAD

**Issue by leanne1** [vitest-dev/vitest#5358]
### Describe the bug

Using `vi.mock` to create a factory of mocked named exports, if i provide a default mock implementation to a named export it does not work.  Instead, I have to manually set a mock implementation in every test. Is this a expected behaviour and I have misunderstood how the mocks work, or is this a bug?

### Reproduction

```ts
// bar.ts - this is the module to be mocked
export function barFn() {
  return {
    bar: 2,
  };
}
```
```ts
// foo.ts - this is the module under test
import { barFn } from './bar';

export function fooFn() {
  const { bar } = barFn();
  return bar;
}
```

```ts
// test.test.ts - this is what i would EXPECT to pass the test
// However the test fails: TypeError: Cannot destructure property 'bar' of 'barFn(...)' as it is undefined.
import { fooFn } from './foo';

vi.mock('./bar', () => ({
  barFn: vi.fn(() => ({ bar: 3 })),
}));

// FAILS
describe('test', () => {
  it('should return mocked bar', () => {
    const actual = fooFn();
    expect(actual).toBe(3);
  });
});
```

```ts
// test.test.ts - this is the only way i an get the mock to pass - if I specifically 
// define a mockReturnValue in the test
import { barFn } from './bar';
import { fooFn } from './foo';

vi.mock('./bar', () => ({
  barFn: vi.fn(),
}));

// PASSES
describe.only('test', () => {
  it('should return mocked bar', () => {
    barFn.mockReturnValue({ bar: 3 });
    const actual = fooFn();
    expect(actual).toBe(3);
  });
});
```

```ts
// test.test.ts - this also passes but then barFn is not a mock so i cannot change its 
// implementation per test
import { barFn } from './bar';
import { fooFn } from './foo';

vi.mock('./bar', () => ({
  barFn: () => ({ bar: 3 }),
}));

describe.only('test', () => {
 // PASSES
  it('should return mocked bar', () => {
    const actual = fooFn();
    expect(actual).toBe(3);
  });

 // FAILS - barFn is not a mock
 it('should also return mocked bar', () => {
    // TypeError: barFn.mockReturnValue is not a function
    barFn.mockReturnValue({ bar: 4 });
    const actual = fooFn();
    expect(actual).toBe(4);
  });
});

```

### System Info

```shell
Mac M1 Sonoma 14.3

Vitest:
├─ @vitest/coverage-v8@0.34.6
├─ @vitest/expect@1.2.2
├─ @vitest/runner@1.2.2
├─ @vitest/snapshot@1.2.2
├─ @vitest/spy@1.2.2
├─ @vitest/utils@1.2.2
└─ vitest@1.2.2

typescript@5.3.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> // test.test.ts - this is what i would EXPECT to pass the test

The test passes:

https://stackblitz.com/edit/vitest-dev-vitest-2pstgd?file=test%2Fbar.ts,test%2Fmocks.test.ts,vite.config.ts,test%2Ffoo.ts&initialPath=__vitest__/

**Comment by leanne1** [comment]
@sheremet-va Thanks for the Stackblitz - this is exactly how I expected it would work. I have delved more deeply into my setup and have discovered the issue. In my global test config I had `mockReset: true`. This was clearing all mocks before each test and [resetting them back to an empty function](https://vitest.dev/config/#mockreset), hence why the initial mocks were not working. Now that is removed my tests work as expected. I will now close this issue
