### ISSUE TITLE
Whitespaces are never equal: `' ' !== ' '`

### ISSUE THREAD

**Issue by e-kucheriavyi** [vitest-dev/vitest#5360]
### Describe the bug

Trying to compare strings always fail: `' ' !== ' '`.

Expected behavior: `' ' === ' '`

### Reproduction

```
expect(' ').toBe(' ') // fails
expect(' ').toEqual(' ') // fails
expect(' ').toStrictEqual(' ') // fails
expect(' ' === ' ').toBeTruthy() // fails
```

### System Info

```shell
System:
    OS: Linux 6.6 Manjaro Linux
    CPU: (12) x64 AMD Ryzen 5 5600H with Radeon Graphics
    Memory: 17.37 GB / 30.74 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.1 - ~/.nvm/versions/node/v20.8.1/bin/node
    Yarn: 4.0.2 - ~/Projects/rentu/vue-3-frontend/node_modules/.bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.8.1/bin/npm
  Browsers:
    Chromium: 122.0.6261.111
  npmPackages:
    @vitejs/plugin-vue: ^4.2.3 => 4.5.0 
    vite: ^5.1.4 => 5.1.4 
    vitest: ^1.3.1 => 1.3.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I don't see it failing: https://stackblitz.com/edit/vitest-dev-vitest-q8midr?file=test%2Fbasic.test.ts&initialPath=__vitest__/

Are you sure you are not using non-break space? https://en.wikipedia.org/wiki/Whitespace_character

**Comment by e-kucheriavyi** [comment]
> I don't see it failing: https://stackblitz.com/edit/vitest-dev-vitest-q8midr?file=test%2Fbasic.test.ts&initialPath=__vitest__/
> 
> Are you sure you are not using [non-breaking space](https://en.wikipedia.org/wiki/Non-breaking_space)?

You're right, it's not a vitest bug.

```
>> const value = new Intl.NumberFormat('ru-RU').format(1234)
>> value
< '1 234'
>> value === '1 234'
< false
```
