### ISSUE TITLE
`crypto.subtle.digest` throws `TypeError` when using JSDOM environment

### ISSUE THREAD

**Issue by nolanlawson** [vitest-dev/vitest#5365]
### Describe the bug

When using `crypto.subtle.digest` with the JSDOM environment, an error is thrown at runtime.

The minimal repro is:

```js
const buffer = new ArrayBuffer(8)
await crypto.subtle.digest('SHA-1', buffer)
```

The error is thrown by Node.js itself [here](https://github.com/nodejs/node/blob/b241a1d0aeaad5dd672cd74cb9f2c023592105bd/lib/internal/crypto/webidl.js#L205-L209) (using Node.js v20). The error is:

```
TypeError: Failed to execute 'digest' on 'SubtleCrypto': 2nd argument is not instance of ArrayBuffer, Buffer, TypedArray, or DataView.
```

The proximate cause seems to be `jsdom-keys.ts`. If I comment out this line in `vitest/dist/vendor/index.*.js`, then the test passes:

https://github.com/vitest-dev/vitest/blob/6d1b145118d42b14bc0739820c4ce9e17fbd45dd/packages/vitest/src/integrations/env/jsdom-keys.ts#L176

This also does not repro with the happy-dom or default Node environment.

### Reproduction

[Here is a minimal GitHub repro](https://gist.github.com/nolanlawson/fc45b836755c9c198b5f76ad45bc3d8c).

You can repro by doing:

```sh
git clone https://gist.github.com/nolanlawson/fc45b836755c9c198b5f76ad45bc3d8c repro
cd repro
npm i
npm test
```

### System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: <omitted>
    Memory: <omitted>
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.11.1 - ~/.volta/tools/image/node/20.11.1/bin/node
    Yarn: 4.0.2 - ~/.volta/tools/image/yarn/4.0.2/bin/yarn
    npm: 10.5.0 - ~/.volta/tools/image/npm/10.5.0/bin/npm
  Browsers:
    Chromium: 122.0.6261.94
  npmPackages:
    vitest: ^1.3.1 => 1.3.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is expected behavior: https://github.com/vitest-dev/vitest/issues/4043
