### ISSUE TITLE
Api to run just one test of a single file

### ISSUE THREAD

**Issue by albertodeago** [vitest-dev/vitest#5374]
### Clear and concise description of the problem

In Mocha, the `.only` works differently, when you specify `.only` in a test only that test of only that file runs.
Currently I know this is possible in vitest in two steps:
- add `.only` in one test
- run vitest filtering for that file, e.g. `vitest my-test-file`

This is a bit annoying sometimes, for example when you want to work on a file at the time, everytime you want to run a single test on a new file you need to change the command in the shell / npm script

### Suggested solution

I see two possibilities that I would like here:
- add a new api like `.onlyThis` (or `.unique`) that will make all the other testfiles not run, like mocha does
- add a new config flag to specify how the `.only` should work, like `onlyMode: 'mocha' | 'jest'`, this would make possible to choose the behaviour on the `.only`

### Additional context

I saw that something like this was already asked multiple times (e.g. https://github.com/vitest-dev/vitest/issues/1811), so maybe it's worth adding it as an option somehow?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Mocha runs tests in a single thread. Vitest runs tests in isolation so we can't know what tests to ignore until all of them collect tests. To introduce this feature, we would have to disable parallel execution which tanks the performance significantly.

I don't think this feature can be implemented in a way that satisfies the team.

**Comment by sheremet-va** [comment]
> ook makes sense, thanks anyway for considering it @sheremet-va <3. Out of curiosity, would it be possible to write a plugin that actually implement this (considering that in the config the user turn off the parallelism)?

No, I don't think it's possible even with disabled parallelism, Vitest collects and runs tests always one by one, otherwise, coverage doesn't work correctly.
