### ISSUE TITLE
Using vitest with jsdom causes an infinite loop in `atob`

### ISSUE THREAD

**Issue by darlanalves** [vitest-dev/vitest#5378]
### Describe the bug

Note: this is not a duplicate.
Issue #4602 reported the same issue before. It was closed an locked, but I can still reproduce it.

The issue was previously fixed with an upgrade to JSDom 23.x, but it still happens with JSDom 24. Either is a regression or the test coverage does not run with jsdom@24

Related [JSDom issue](https://github.com/jsdom/jsdom/issues/3628)

### Reproduction

```ts
// index.test.ts
import { describe, expect, it } from "vitest";

describe("atob recursion", () => {
  it("should convert a base64 string", () => {
    expect(atob("SGVsbG8=")).toBe("Hello");
  });
});
```

```bash
npm i jsdom@24 vitest@0.34.6
vitest run --environment jsdom --single-thread --dir .
```

### System Info

```shell
System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.93 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.0 - [redacted]/node
    npm: 8.19.1 - [redacted]/npm
  Browsers:
    Chrome: 122.0.6261.112
    Safari: 17.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
The fix is in 1.0.0.
