### ISSUE TITLE
it/test blocks stop after the first failed expect

### ISSUE THREAD

**Issue by rolandleth** [vitest-dev/vitest#5379]
### Describe the bug

Having any `expect` fail in an `it/test` block exits that block, as if it crashes.

<img width="1207" alt="2024-03-13 at 3 04 29 PM" src="https://github.com/vitest-dev/vitest/assets/1858700/f1c239d2-6569-40a6-86f7-a685f1538d77">
<img width="565" alt="2024-03-13 at 3 02 11 PM" src="https://github.com/vitest-dev/vitest/assets/1858700/9258e8e3-b3fd-4df4-9567-3466ada2847f">

Same happens without `describe` blocks.

Am I doing something wrong?

### Reproduction

- Created a remix.run app with `npx create-remix@latest --template remix-run/remix/templates/vite`
- created a spec file and nothing else
- added some basic tests
- tried various settings in `vite.config.ts`
- ran `yarn vitest` or `yarn vitest run`
- attached screenshot.

### System Info

```shell
System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 73.78 MB / 16.00 GB
    Shell: 3.6.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 21.2.0 - ~/.nvm/versions/node/v21.2.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v21.2.0/bin/npm
  Browsers:
    Chrome: 121.0.6167.160
    Firefox: 113.0.1
    Safari: 17.4
  npmPackages:
    vite: ^5.1.0 => 5.1.6 
    vitest: ^1.3.1 => 1.3.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
All assertions throw an error if they fail. If you need to make several assertions, you can use [`expect.soft` API](https://vitest.dev/api/expect.html#soft):

```js
test('expect.soft test', () => {
  expect.soft(1 + 1).toBe(3)
  expect.soft(1 + 2).toBe(4)
})
```

**Comment by rolandleth** [comment]
Thanks for the quick answer, @sheremet-va. Is there any way to make `expect` behave like that? Maybe I'm writing tests wrong, but I usually have more than one `expect` per test block, it'd be a bit annoying to write `expect.soft` everywhere.

**Comment by sheremet-va** [comment]
This has been the convention in at least JavaScript tooling for years now.
