### ISSUE TITLE
"vitest run --watch" does not work correctly.

### ISSUE THREAD

**Issue by liuqiang1357** [vitest-dev/vitest#5381]
### Describe the bug

It should work in watch mode, but it doesn't.

### Reproduction

Just run the command: `npx vitest run --watch`

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 203.06 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.volta/tools/image/node/20.11.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 10.2.4 - ~/.volta/tools/image/node/20.11.1/bin/npm
    pnpm: 8.15.3 - ~/Library/pnpm/pnpm
    bun: 1.0.18 - ~/.bun/bin/bun
    Watchman: 2021.11.01.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 17.2.1
  npmPackages:
    vitest: ^1.2.1 => 1.3.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Maybe you're aware, but `npx vitest` by default provides watch mode (unless in CI environment), so usually you wouldn't need to write `vitest run --watch`. Do you have any specific case you want to add `run` and `--watch` together?

**Comment by sheremet-va** [comment]
You cannot call `vitest run --watch` because run is the same as `--no-watch`. Just use `vitest` or `vitest --watch`.
