### ISSUE TITLE
Browser mode fails with `SyntaxError: Failed to construct 'WebSocket'`

### ISSUE THREAD

**Issue by kossnocorp** [vitest-dev/vitest#5382]
### Describe the bug

After upgrading Vitest in the date-fns codebase (`vitest@0.34.6` -> `vitest@1.3.1` & `@vitest/browser@0.34.6` -> `@vitest/browser@1.3.1`) I started getting many of these errors:

```
SyntaxError: Failed to construct 'WebSocket': The URL 'ws://localhost:undefined/' is invalid.
❯ setupWebSocket /@vite/client:505:20
❯ fallback /@vite/client:484:22
❯ WebSocket.<anonymous> /@vite/client:520:13
```

As the result `npx vitest run --browser` hangs forever, even though the tests pass when I open it with `--ui`.

### Reproduction

```
git clone git@github.com:date-fns/date-fns.git
cd date-fns
npm install
npm install -D @vitest/ui
npx vitest --browser --ui
```

It will open the browser where you can see the errors:

![image](https://github.com/vitest-dev/vitest/assets/52201/217c8569-aaa4-4f0c-ba44-73a3f25fc17f)

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 15.01 GB / 31.31 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.asdf/installs/nodejs/20.10.0/bin/node
    Yarn: 1.22.21 - ~/.asdf/installs/nodejs/20.10.0/bin/yarn
    npm: 10.2.3 - ~/.asdf/plugins/nodejs/shims/npm
    bun: 1.0.25 - ~/src/date-fns/date-fns/node_modules/.bin/bun
  Browsers:
    Chrome: 103.0.5060.114
  npmPackages:
    @vitest/browser: ^1.3.1 => 1.3.1 
    @vitest/coverage-v8: ^1.3.1 => 1.3.1 
    vitest: ^1.3.1 => 1.3.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
I tested locally and I can reproduce. I'm not really sure yet but maybe spwaning too many iframes is causing some problems.

I tweaked some config and `isolate: false` seems to work but `fileParallelims: false` doesn't seem to help.
If no isolation is acceptable, then you may use `npx vitest --browser --no-isolate` instead for now.

**Comment by kunokareal** [comment]
a similar issue seems to be happening on an smaller number of tests (~1k) when running in firefox, but works fine in chrome. `isolate: false` does help

![image](https://github.com/vitest-dev/vitest/assets/163348146/88a559b9-5dec-4952-a5db-9845350952a0)

**Comment by underoot** [comment]
Also reproduced issue, noticed that it's begins only when number of files larger than 127
https://github.com/underoot/vitest-large-file-list-issue
