### ISSUE TITLE
queueMicrotask and mocked functions

### ISSUE THREAD

**Issue by ABashkirtseva** [vitest-dev/vitest#5389]
### Describe the bug

If I have queueMicrotask, spy calls are not recorded.

### Reproduction

```
  test('Allow to encode and decode data', () => {
    vi.useFakeTimers();

    const mock = vi.fn();
    queueMicrotask(() => {
      mock(1);
    });

    vi.advanceTimersToNextTimer();
    vi.advanceTimersByTime(2000);

    expect(mock).toHaveBeenCalledWith(1);
  });
  ```
  
 **Expected behaviour:**
 expect should be passed 
 
 **Actual behaviour:**
 expect are failed with error:
 -- AssertionError: expected "spy" to be called with arguments: [ 1 ] 

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 282.95 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Brave Browser: 120.1.61.120
    Chrome: 122.0.6261.129
    Firefox: 117.0.1
    Safari: 17.1
  npmPackages:
    vite: ^5.1.6 => 5.1.6 
    vitest: ^1.3.1 => 1.3.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Does this work?

```ts
import { vi, expect, test } from 'vitest'

test('Allow to encode and decode data', async () => {
  vi.useFakeTimers();

  const mock = vi.fn();
  queueMicrotask(() => {
    mock(1);
  });

  await vi.runAllTimersAsync()

  expect(mock).toHaveBeenCalledWith(1);
});
```

**Comment by hi-ogawa** [comment]
`queueMicrotask` is not mocked by default, so I think you would need to add it to `vi.useFakeTimers({ toFake: ['queueMicrotask'] })` https://vitest.dev/api/vi.html#vi-usefaketimers

**Comment by AriPerkkio** [comment]
Minimal reproduction works when `toFake` is defined as instructed above.

https://stackblitz.com/edit/vitest-dev-vitest-nvum37?file=test%2Fbasic.test.ts.

```diff
import { vi, expect, test } from 'vitest';

test('Allow to encode and decode data', () => {
-  vi.useFakeTimers();
+  vi.useFakeTimers({ toFake: ['queueMicrotask'] });

  const mock = vi.fn();
  queueMicrotask(() => {
    mock(1);
  });

  vi.advanceTimersToNextTimer();
  vi.advanceTimersByTime(2000);

  expect(mock).toHaveBeenCalledWith(1);
});
```
