### ISSUE TITLE
When testNamePattern is set, tests nested in a describe block will still run even if the test name does not match

### ISSUE THREAD

**Issue by cuddlecake** [vitest-dev/vitest#539]
### Describe the bug

When I set an arbitrary `testNamePattern` such as `"this text will not match anything"`, then any test that is nested with describe will still run.

### Reproduction

- Go to `vitest/examples/basic`
- Change the `vite.config.ts` test configuration to contain `testNamePattern: "this should not match anything"`
- Run the tests using `test` or `test:run` scripts

Output looks like:

```
 RUN  /Users/asw/Development/vitest/examples/basic

 √ test/basic.test.ts (2)
 √ test/suite.test.ts (3)

Test Files  2 passed (2)
     Tests  3 passed | 2 skipped (5)
      Time  1.22s (in thread 5ms, 22813.95%)
```

Would expect 0 tests to pass and 5 to be skipped, but the tests in `test/suite.test.ts` are not skipped.

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 323.29 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.volta/tools/image/node/14.18.1/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 6.14.15 - ~/.volta/tools/image/npm/6.14.15/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 96.0
    Safari: 15.2
  npmPackages:
    vite: latest => 2.7.12
    vitest: latest => 0.1.14
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ajaest** [comment]
I am having the same issue, but with the command line parameter:

```
$> npm exec -- vitest run -r src/data -c __tests__/vitest.config.ts  -t '.*audience.*'

 RUN  /home/ajaest/Code/geographica/iniative/initiative-vision/www/src/data

 ❯ __tests__/taxonomy.test.ts (4)
   ❯ TaxonomyDataService (4)
     ❯ .list (4)
       √  works with no arguments 482ms
       √  returns a dictionary/tree whe providing no format 626ms
       √  returns a dictionary/tree whe providing format=tree 493ms
       ⠙  returns a list when providing format=plain
 ❯ __tests__/audience.test.ts (4)
   ❯ AudienceDataService (4)
     √ .list (1) 794ms
     ❯ list filters (3)
       ⠧  filters by type
       ·  filters by fulltext
       ·  filters by taxonomies
 ❯ __tests__/region.test.ts (3)
   ❯ RegionDataService (3)
     √ .list (1) 623ms
     ❯ list filters (2)
       √  filters by type 1319ms
       ⠙  filters by fulltext
```

Apart from that, I thing documentation is not very explanatory, which kind of pattern type do this option support? js? glob? perl-like?. An example would be appreciated.

**Comment by yaegassy** [comment]
@ajaest It seems to be REGEX.

https://github.com/vitest-dev/vitest/blob/7a05775dee3bd5ac3ce5f431e3a8a7545c48896c/packages/vitest/src/node/config.ts#L87-L91

**Comment by ajaest** [comment]
> > Apart from that, I thing documentation is not very explanatory, which kind of pattern type do this option support? js? glob? perl-like?. An example would be appreciated.
> 
> @ajaest It seems to be REGEX.
> 
> https://github.com/vitest-dev/vitest/blob/7a05775dee3bd5ac3ce5f431e3a8a7545c48896c/packages/vitest/src/node/config.ts#L87-L91

But what does it match? test file names (like `__tests__/my.tests.ts`)? full `describe`/`it`/`test` test phrases?

**Comment by DerYeger** [comment]
I can reproduce this issue and will investigate.

**Comment by DerYeger** [comment]
> > > Apart from that, I thing documentation is not very explanatory, which kind of pattern type do this option support? js? glob? perl-like?. An example would be appreciated.
> > 
> > 
> > @ajaest It seems to be REGEX.
> > https://github.com/vitest-dev/vitest/blob/7a05775dee3bd5ac3ce5f431e3a8a7545c48896c/packages/vitest/src/node/config.ts#L87-L91
> 
> But what does it match? test file names (like `__tests__/my.tests.ts`)? full `describe`/`it`/`test` test phrases?

It matches `it` and `test` phrases.
I added the following test:

```ts
import { assert, describe, it } from 'vitest'

it('does include root test', () => {
  assert.equal(Math.sqrt(4), 2)
})

it('does not include test that is root and unmatched', () => {
  assert.fail('unmatched test was included')
})

describe('testNamePattern', () => {
  it('does include test in describe', () => {
    assert.equal(Math.sqrt(4), 2)
  })

  it('does not include test that is in describe and unmatched', () => {
    assert.fail('unmatched test was included')
  })

  describe('nested describe', () => {
    it('does include nested test', () => {
      assert.equal(Math.sqrt(4), 2)
    })

    it('does not include test that is nested and unmatched', () => {
      assert.fail('unmatched test was included')
    })
  })
})
```

With the `testNamePattern` `^((?!does not include test that).)*$` it works with the changes of my PR #633.

**Comment by ajaest** [comment]
Nice, thanks, I will try
