### ISSUE TITLE
1.2.0+ causes "Cannot read properties of null (reading 'Symbol(Last check for pointer-events)')" errors with @testing-library/user-event

### ISSUE THREAD

**Issue by EvHaus** [vitest-dev/vitest#5392]
### Describe the bug

> [!WARNING]
> _This bug is **REALLY** weird as it requires several obscure conditions to be met to reproduce_

After upgrading from `vitest` version `1.1.3` to `1.2.0` many of my projects are running into failures when I run Vitest tests on my CI environment. The failures all show this stacktrace:

```
index.test.tsx > my test: node_modules/@testing-library/user-event/dist/esm/utils/pointer/cssPointerEvents.js#L33
TypeError: Cannot read properties of null (reading 'Symbol(Last check for pointer-events)')
 ❯ checkPointerEvents node_modules/@testing-library/user-event/dist/esm/utils/pointer/cssPointerEvents.js:33:30
 ❯ Module.hasPointerEvents node_modules/@testing-library/user-event/dist/esm/utils/pointer/cssPointerEvents.js:12:36
 ❯ Object.leave node_modules/@testing-library/user-event/dist/esm/system/pointer/pointer.js:56:43
 ❯ PointerHost.move node_modules/@testing-library/user-event/dist/esm/system/pointer/index.js:50:79
 ❯ pointerAction node_modules/@testing-library/user-event/dist/esm/pointer/index.js:71:39
 ❯ Object.pointer node_modules/@testing-library/user-event/dist/esm/pointer/index.js:39:15
 ❯ Object.asyncWrapper node_modules/@testing-library/react/dist/pure.js:88:22
 ❯ index.test.tsx:56:3
```

The failures comes from inside `@testing-library/user-event` which is included in my tests as:

```ts
import userEvent from '@testing-library/user-event';
```

The issue is still occuring on the latest `1.4.0` version of Vitest as well. However, the issue does NOT occur when rolling back to `1.1.3`.

After working through creating a minimal repro I've tracked the problem down to the following criteria. **ALL** of these must be met for the errors to occur.

1. Vitest must be executed with `--poolOptions.threads.isolate=false`
  a. Enabling isolation by removing that config value makes the error go away
2. You need as many test files as Vitest threads being used
  a. Have 2 test files and run it on GitHub Actions CI (which is single-threaded), or set `--poolOptions.threads.maxThreads=1`
3. At least 1 test file must be importing `@testing-library/user-event` and using its event API
  a. Using regular `fireEvent` API from `@testing-library/react` works fine
4. Use Vitest `1.2.0` or greater
  a. Rolling back to `1.1.3` makes the problem go away

This bug has been blocking me from upgrading to the latest Vitest versions for a while now. I'm hoping there's a solution the Vitest team can investigate. Thank you!

### Reproduction

A minimal repro can be found in this repository: https://github.com/EvHaus/vitest-pointer-events-bug

And you can see the failure occur on the latest GitHub Actions run in that repo: https://github.com/EvHaus/vitest-pointer-events-bug/actions/runs/8306158878/job/22733896538

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 28.15 GB / 31.32 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 21.1.0 - ~/.nvm/versions/node/v21.1.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v21.1.0/bin/yarn
    npm: 10.2.0 - ~/.nvm/versions/node/v21.1.0/bin/npm
    pnpm: 8.10.2 - ~/.local/share/pnpm/pnpm
    bun: 1.0.30 - ~/.bun/bin/bun
  Browsers:
    Chrome: 120.0.6099.109
  npmPackages:
    vitest: 1.4.0 => 1.4.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
This commit seems to break when using local Vitest with the reproduction: 4bc59f505f0125c4763b513b0e87153fff048570. Anything before that works well. 

@EvHaus the reproduction case works when you install `happy-dom@12`. Could you confirm this as well?

**Comment by EvHaus** [comment]
Confirmed. Using `happy-dom` 12.10.3 makes this issue go away as well.

**Comment by sheremet-va** [comment]
Since the issue is with happy-dom, I think this can be closed. If this is not the case, feel free to comment and I will reopen the issue.

**Comment by EvHaus** [comment]
Confirming that this is no longer an issue with `vitest` 2.1.2 + `happy-dom` 15.7.4
