### ISSUE TITLE
Istanbul Cobertura output?

### ISSUE THREAD

**Issue by AcidRaZor** [vitest-dev/vitest#5396]
### Describe the bug

Whenever I run code coverage with Istanbul or v8, it only generates coverage-*.json files in a .tmp directory. I'd like the XML output in cobertura format (which istanbul supports) but it simply doesn't generate although multiple stackoverflow's and even here says it will?

### Reproduction

Not sure how to reproduce. I'm new to Vue 3 + Vite

### System Info

```shell
defineConfig({
		test: {
			environment: 'jsdom',
			coverage: {
				enabled: true,
				reporter: ['cobertura'],
				provider: 'istanbul', // or 'v8'
				reportsDirectory: './reports/coverage'
			},
			exclude: [...configDefaults.exclude, '**/e2e/**'],
			root: fileURLToPath(new URL('./', import.meta.url))
		}
	})
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
> Not sure how to reproduce

Here is example reproduction case using your configuration where `cobertura` report is successfully generated: https://stackblitz.com/edit/vitest-dev-vitest-mkaweu?file=vite.config.ts.

**Comment by AcidRaZor** [comment]
Thanks, I'll try and repro it but so far no luck on getting it to work on my side, sorry to bother
