### ISSUE TITLE
A check to see if all the mock functions are asserted for all the call it recieved with expected params. This check can be configured as warn and error mode.

### ISSUE THREAD

**Issue by paramadeep** [vitest-dev/vitest#5399]
### Clear and concise description of the problem

This is a practice I want to enforce on my team. There is no automated way to ensure the mocks are done properly. 
I can give an instance for this. It is a test for controller method. My team didn't even added a request body to the test. Since we are not asserting params passed to the downstream mocked service, they have just returned the expected response. 

### Suggested solution

we could add a check to see if all the mock functions are asserted for all the call it received with expected parameters. This check can be set  as off, warn and error mode through config. 
MockIt to have similar feature. It will fail the test, if any of the mock is not used in the test. Though it doesn't check if all mocks function params are asserted, java enforce using params while setting mocks. 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
> we could add a check to see if all the mock functions are asserted for all the call it received with expected parameters. 

I couldn't grasp the concept from the description. Can you provide sample code where you want to make it error/warn? Links to how other frameworks do this would also help.

**Comment by sheremet-va** [comment]
Since this issue hasn't been discussed for half a year, I believe it's safe to close it.
