### ISSUE TITLE
Ability to specify benchmarks that should run synchronously

### ISSUE THREAD

**Issue by peterHakio** [vitest-dev/vitest#5412]
### Clear and concise description of the problem

In cases where the code is not only js, but is using a shared resource such as a database benchmarks are difficult to run in isolation. 

Example: we are currently testing prisma vs kysely and have written these tests. But since they are using a shared resourse  it is not optimal to run them in parrallel. 

Here is one of the tests

```ts

describe("Prisma vs Kysely 1000 objects", () => {
  bench("Prisma", async () => {
    await prisma.forecast.findMany({
      take: 1000,
    })
  })
  bench("Kysely", async () => {
    await db.selectFrom("Forecast").selectAll().limit(1000).execute()
  })
  bench("Prisma Raw SQL", async () => {
    await prisma.$queryRaw`
      SELECT
        *
      FROM
        "Forecast"
      LIMIT
        1000;
    `
  })

  bench("Kysely Raw SQL", async () => {
    await sql`
      SELECT
        *
      FROM
        "Forecast"
      LIMIT
        1000;
    `.execute(db)
  })
})

```

### Suggested solution

An ability to run `vitest bench --synchronous` where all promises are awaited and the benchmark tests are performed synchronous.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
It looks like multiple `describe` are running at the same time:

https://github.com/vitest-dev/vitest/blob/6eda473f30c4670ec72a06bd3b083a724712ae2a/packages/vitest/src/runtime/runners/benchmark.ts#L38-L39

However, multiple `bench` inside single `describe` are executed sequentially, so your sample code with four `bench` inside single `describe` shouldn't interfere each other. Can you check if you have multiple `describe`?

Though I'm not familiar with the field of benchmarking, but I would feel everything should run sequentially by default and that probably gives better stability. Maybe we can check with what other benchmark framework does in general.

I'm playing with examples like this. Multiple bench files also run in parallel by default, but it can be made sequential by `fileParallelism = false`:

https://stackblitz.com/edit/vitest-dev-vitest-cdshc4?file=test.log

<details>

```ts
import { bench, describe } from "vitest"
import fs from "node:fs";

const sleep = (ms: number) => new Promise(resolve => setTimeout(resolve, ms))

describe("suite1", () => {
  let i = 0;
  bench("bench1", async () => {
    await fs.promises.appendFile("test.log",`file1, suite1, bench1 = ${i++}\n`)
    await sleep(500);
  }, { time: 0, iterations: 0 })

  let j = 0;
  bench("bench2", async () => {
    await fs.promises.appendFile("test.log",`file1, suite1, bench2 = ${j++}\n`)
    await sleep(500);
  }, { time: 0, iterations: 0 })
})

describe("suite2", () => {
  let i = 0;
  bench("bench1", async () => {
    await fs.promises.appendFile("test.log",`file1, suite2, bench1 = ${i++}\n`)
    await sleep(500);
  }, { time: 0, iterations: 0 })
})
```

</details>

**Comment by peterHakio** [comment]
Thank you very much. We did what you suggested and it worked fine.

We made implimented it in the vite.config.js like this. Such that we still could have our tests run in parallel

```
import { defineConfig } from 'vitest/config';

export default defineConfig(({mode})=>({
  test: {
    fileParallelism: mode!=="benchmark",
  },
}));

```

**Comment by sheremet-va** [comment]
> Though I'm not familiar with the field of benchmarking, but I would feel everything should run sequentially by default and that probably gives better stability.

I do agree with that. I think we should flatten all benchmarks and use the suite just for reporting.
