### ISSUE TITLE
在使用vitest编写单测模块时，抛出错误模块与编写模块不一致

### ISSUE THREAD

**Issue by XiaoDaiGua-Ray** [vitest-dev/vitest#5413]
### Describe the bug

在使用 `vitest` 编写单测模块时，发现抛出错误模块与编写模块不一致问题。

截图如下；

<img width="895" alt="image" src="https://github.com/vitest-dev/vitest/assets/51957438/d2ac19d7-49ad-496c-9d0d-eda861445827">
<img width="995" alt="image" src="https://github.com/vitest-dev/vitest/assets/51957438/732ad6aa-350b-4190-b77e-6ce7bd62e0aa">
<img width="871" alt="image" src="https://github.com/vitest-dev/vitest/assets/51957438/fb96217a-59db-428d-8083-74adc45c2602">

### Reproduction

暂时无法提供最小复现。

### System Info

```shell
vite: 5.1.6
vitest: 1.4.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by XiaoDaiGua-Ray** [comment]
这边补充了一个最小复现：https://stackblitz.com/edit/vitest-dev-vitest-sge3ny?file=test%2FuseDemo.test.ts

**Comment by AriPerkkio** [comment]
```
 RERUN  test/useDemo.test.ts x4

 ❯ test/useDemo.test.ts (0)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  test/useDemo.test.ts [ test/useDemo.test.ts ]
Error: Failed to load url ../../src/hooks/index.js (resolved id: ../../src/hooks/index.js) in /home/projects/vitest-dev-vitest-sge3ny/test/useDemo.test.ts. Does the file exist?
 ❯ loadAndTransform node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:53881:21

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed (1)
      Tests  no tests
   Start at  07:39:39
   Duration  0ms


 FAIL  Tests failed. Watching for file changes...
       press h to show help, press q to quit
```

```diff
// useDemo.test.ts
- import { useDemo } from '../../src/hooks/index.js';
+ import { useDemo } from '../src/hooks/index.js';
```


```
 RERUN  test/useDemo.test.ts x3

 ✓ test/useDemo.test.ts (1)
   ✓ useDemo

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  07:40:57
   Duration  19ms


 PASS  Waiting for file changes...
       press h to show help, press q to quit
```

**Comment by XiaoDaiGua-Ray** [comment]
不好意思，在我这个复杂的项目里用了很多类似的別名，目前不能复现出来。我按照官网配置也暂时不能解决，我已经定位出问题所在（别名解析问题），我应该如何在我的项目里解决这个问题呢？

**Comment by sheremet-va** [comment]
Please use English to communicate. Seems like Ari already provided the fix for you problem.
