### ISSUE TITLE
toHaveBeenNthCalledWith does not check call times

### ISSUE THREAD

**Issue by Takeno** [vitest-dev/vitest#5417]
### Describe the bug

The assertion of `toHaveBeenNthCalledWith` compares the arguments but doesn't check if the spy has been called Nth times. Doing this, the assertion error is about the mismatch between arguments instead of the number of invocations.

```
 FAIL  index.test.js > should work
AssertionError: expected 3rd "spy" call to have been called with [ 'fail' ]

- Expected: 
Array [
  "fail",
]

+ Received: 
undefined
```

For reference, the jest output:
```
n: 3
Expected: "fail"
Received
       2: "baz"

Number of calls: 2
```

### Reproduction

Here is a repository to check jest vs vitest outputs: https://github.com/Takeno/vitest-toHaveBeenNthCalledWith

To reproduce the test:
```javascript
import { expect, test, vi } from 'vitest';

test('should work', () => {
  const f = vi.fn();

  f('foo');
  f('baz');

  expect(f).toHaveBeenNthCalledWith(1, 'foo');
  expect(f).toHaveBeenNthCalledWith(2, 'baz');
  expect(f).toHaveBeenNthCalledWith(3, 'fail');
});
```

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 69.88 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.18.0/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: 8.15.0 - ~/Library/pnpm/pnpm
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 123.0.6312.58
    Safari: 16.5.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Thanks for the issue with reproduction. Yeah, Vitest's error message is not really clear, but I'm not sure Jest's output does so much better either.

The call arguments (array) are checked against `undefined`, so I don't think this will make assertions to pass when it should fail. Probably, we can just tweak the error message to append something like this:

- expected 3rd "spy" call to have been called with [ 'fail' ], __but only called 2 times.__
