### ISSUE TITLE
toMatchFileSnapshot does not use custom snapshot serializer

### ISSUE THREAD

**Issue by dangmai** [vitest-dev/vitest#5426]
### Describe the bug

When `.toMatchFileSnapshot` is used together with a custom snapshot serializer, the serializer doesn't seem to be used at all.

### Reproduction

https://github.com/dangmai/vitest-file-snapshot-serializer

You can run the following commands after cloning the repo:
```
npm ci
npm test
```

Observe that `.toMatchInlineSnapshot` correctly uses the custom serializer (it prints out `hi`), while `.toMatchFileSnapshot` does not (it prints out `hello` in the snapshot file).

### System Info

```shell
System:
    OS: macOS 14.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 199.86 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.asdf/installs/nodejs/18.12.1/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 123.0.6312.58
    Safari: 17.4
  npmPackages:
    vitest: 1.4.0 => 1.4.0 
```
```


### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
I think this is because the main use case is to just dump string directly to a file, so serialization is skipped for raw string input:

https://github.com/vitest-dev/vitest/blob/fee7d8be9d6e6f710270600ae91fa35d861b7075/packages/snapshot/src/port/state.ts#L242-L244

Otherwise default string serializer would write quoted `"hello"` instead of `hello` to the file by default.

Actually if the input is not a raw string like `expect({ hello: "world" }).toMatchFileSnapshot()`, then serializers (including custom ones) will be applied.

If you happen to have a specific use case to apply custom serializer for raw string. If that's the case, could you share the motivation? Maybe we can suggest some okay-ish workaround.

**Comment by dangmai** [comment]
My use case is that I'm using `vitest` to make sure that Kubernetes manifests generated by `helm` haven't changed when new versions are released. However, those manifests do contain the version numbers which are expected to change, and I want to use a custom serializer to swap out those version numbers for static strings (so that the tests don't fail).

I will try using an object instead of just a raw string to see if it serves my case, thank you for suggesting it.

**Comment by hi-ogawa** [comment]
Thanks for providing the detail. Btw, did you try `toMatchSnapshot`? https://vitest.dev/api/expect.html#tomatchsnapshot This uses a single file `__snapshots__/some-file.test.ts.snap` to write all the snapshots for each test file, so I would assume it hinders readability for your use case, but just in case.

**Comment by dangmai** [comment]
Yeah that's my workaround for now. The downside is that the snapshot file is ~40,000 lines and GitHub has trouble showing the diff when something changes 😂

In any case, if you think this issue won't be fixed please feel free to close it. I figure it's better to open this issue so that other folks can search for it if they run into the same thing.

**Comment by dangmai** [comment]
By the way, for my specific use case, your suggestion of switching from raw string to an object did work - I use a YAML parser to turn the raw string into an object for comparison, and `toMatchFileSnapshot` does invoke my custom serializer when I do that, so thank you for the suggestion!

**Comment by hi-ogawa** [comment]
Yeah, probably it's not actionable for Vitest for now. Nonetheless, thanks for raising an issue with a concise reproduction.

Btw, one more limitation of `toMatchFileSnapshot`. As explained in the following issue, it cannot automatically delete obsolete snapshot files.
- https://github.com/vitest-dev/vitest/issues/5094

If you have many files to manage, then you might need to write your own script or something to make sure "helm files" and "helm snapshot files" correspond to each other.
