### ISSUE TITLE
Watch dynamically imported files not detected automatically and cached

### ISSUE THREAD

**Issue by timotheeguerin** [vitest-dev/vitest#5429]
### Describe the bug

When dynamically importing JS or TS files (`await import` with a resolved value) vitest watch doesn't pickup on change automatically and in the case of JS files that are in the `dist` directory it won't reload at all(Keeps the original code).
The same also happen when working in a vitest workspace and trying to dynamically import JS files from another dependency `dist` folder.

### Reproduction

[Stackbliz url](https://stackblitz.com/edit/vitest-dev-vitest-nbjepw?file=test%2Fsuite.test.ts)

1. Start a separate terminal and run `npm run watch` to also build the TS -> JS in `dist` dir. 
2. All the test should pass
3. Update foo.ts so the test doesn't pass e.g.  `export const test = (n: number) => n * 4;`
4. Watch didn't run automatically (That is the first problem)
5. Press enter in the watch window
6. Test are now rerunning but only the `TS` import ones seems to be reloaded. JS files are not even though I reconfigured the `exclude` to not exclude `dist` folder. If you change so that TS output dir is `customDist` instead of `dist` then the JS files do get reloaded correctly.

### System Info

```shell
System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 47.03 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 8.15.4 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
    bun: 1.0.11 - ~/.bun/bin/bun
  Browsers:
    Edge: 123.0.2420.53
    Safari: 17.4
  npmPackages:
    @vitest/coverage-v8: ^1.4.0 => 1.4.0 
    @vitest/ui: ^1.4.0 => 1.4.0 
    vitest: ^1.4.0 => 1.4.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Thanks for the concise reproduction. It might look surprising, but I think it's mostly working as intended. Let me check one by one.

> 3. Update foo.ts ...
> 4. Watch didn't run automatically (That is the first problem)

This looks like because of "too dynamic" dynamic import, which is not statically analyzed by Vite/Vitest, so module graph cannot track "test file -> foo.ts" dependency to trigger auto re-run.

I made a quick example to show the difference here.
https://stackblitz.com/edit/vitest-dev-vitest-giqgmf?file=test%2Fdynamic-ok.test.ts

Given these two tests, `bar.ts` only triggers re-running `dynamic-ok.test.ts`:

```ts
// dynamic-ok.test.ts
await import('../src/bar');

// dynamic-not-ok.test.ts
await import(String('../src/bar'));  
```

> 6. ... JS files are not even though I reconfigured the exclude to not exclude dist folder. If you change so that TS output dir is customDist instead of dist then the JS files do get reloaded correctly.

This one looks weird, but maybe a different issue, something related to deprecated `test.watchExclude` option and Vite side `server.watch.ignored` https://github.com/vitest-dev/vitest/pull/5171, which picks up `build.outDir: "dist"` automatically as ignored.

Actually this might be a bug, so this needs to be investigated further.

---

Regarding point 4, do you actually use this "too dynamic" form of dynamic import? I think supporting this is out-of-scope for now. But depending on the use case, there might be a workaround, for example, using Vite's import glob `import.meta.glob("/dist/*.js")`, which can probably keep track module graph correctly.

**Comment by timotheeguerin** [comment]
Thanks for the quick reply, we do actually use a lot of those dynamic loading but only directly to JS for now(I could get into the details but not sure this is really relevant, let me know if you want to), not having the auto rerun of `vitest watch` is unfortunate but not the end of the world. The main issue I have is it looks like the new vitest extension preview depends on watch and rerunning the test doesn't reload the the dynamically loaded JS files. However that might just be the 2nd issue that you said sounds like a bug.

I'll look into `import.meta.glob("/dist/*.js")` I didn't know this was a thing thanks!

**Comment by AriPerkkio** [comment]
Does `forceRerunTriggers` work here? https://vitest.dev/config/#forcereruntriggers

**Comment by timotheeguerin** [comment]
It doesn't surprisingly not even in the TS case, I updated the repro abvoe with 
```json
    forceRerunTriggers: ['src/**'],
```

**Comment by AriPerkkio** [comment]
I thought that would work... Weirdly it looks like it's not possible to make Vite's watcher to look for changes in `**/dist/**`.

Even something like this doesn't work:

```ts
export default defineConfig({
  server: {
    watch: {
      ignored: ["**/node_modules/**"],
    },
  },
  test: {
    watchExclude: ["**/node_modules/**"],
    forceRerunTriggers: ["**/dist/**"],
  },
});
```

The watcher here still has some hardcoded values in `ignored`:

https://github.com/vitest-dev/vitest/blob/0ec4d0e0530b2d949838b7166e073790b2a39696/packages/vitest/src/node/core.ts#L742

```
[
  '**/.git/**',
  '**/node_modules/**',
  '**/test-results/**',
  '/x/y/vitest-dist-rerun/node_modules/.vite/**',
  '**/node_modules/**',
  '**/node_modules/**',
  '/x/y/vitest-dist-rerun/dist/**'
]
```

**Comment by timotheeguerin** [comment]
I see so if I add this to the config then the js reloads fine
```js
  build: {
    outDir: 'dummy',
  },
```

also noticed that `forceRerunTriggers: ['src/**'],` actually makes things worse as now the TS doesn't get reloaded when you press ENTER.
