### ISSUE TITLE
Debugger Segmentation fault when a file contains 6 functions

### ISSUE THREAD

**Issue by Zombobot1** [vitest-dev/vitest#543]
### Describe the bug

I set up debugger as the documentation guides. When I place a breakpoint inside a file that contains more than 5 functions debugger crashes with segmentation fault.

### Reproduction

```ts
// test.ts

import { foo } from './parser'

describe('parser', () => {
  it.only('works', () => {
    const f = foo()
  })
})

// parser.ts
function bar() {}
export function bar2() {}
export function bar3() {}
export function bar4() {}
// export const bar4 = () => {}

export function foo() {
  const a = 1 // breakpoint is here
}

//zsh: segmentation fault  /usr/bin/env   /usr/local/bin/node ./node_modules/vitest/vitest.mjs run 
```

Note: If I replace a function by arrow function debugger works without a crash

### System Info

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
    Memory: 269.11 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.9.1 - /usr/local/bin/node
    npm: 7.21.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Safari: 14.1.2
  npmPackages:
    @vitejs/plugin-react-refresh: ^1.3.6 => 1.3.6 
    vite: ^2.7.12 => 2.7.12 
    vitest: ^0.1.16 => 0.1.16
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DerYeger** [comment]
I'm not sure if this is related, but [my tests](https://github.com/DerYeger/d3-graph-controller/runs/4830712709?check_suite_focus=true) suddenly started failing with a seg fault as well.

**Comment by ajaest** [comment]
I am also suffering random segmentation faults (sometimes it works, sometimes not) while using the debugger with vitest. 

I appreciated that, when I tried to record the issue with OBS (that is, when I have the processor with a higher load) segmentation faults are less prone. I assume then it seems to be some kind of race condition, which is also compatible with @Zombobot1's issue.

```
$> ~/.config/nvm/versions/node/v17.3.0/bin/node --inspect-brk=42855 ~/my-project/www/node_modules/vitest/vitest.mjs --run --threads false -r src/data -c __tests__/vitest.config.ts __tests__/audience.test.ts
Debugger listening on ws://127.0.0.1:42855/bf20dc67-c771-437d-af4d-46b9a58979e6
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

 RUN  ~/my-project/www/src/data


Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

**Comment by sheremet-va** [comment]
Not reproducible anymore. All segmentation issues should be reported as separate issues. Thank you!
