### ISSUE TITLE
Source code missing in reporters on error, when certain line width is reached, very inconsistent

### ISSUE THREAD

**Issue by jkavalec** [vitest-dev/vitest#5431]
### Describe the bug

Using Vitest Basic and Default reporters, there is issue where source showing code where error occurred is not displayed upon reaching certain width (this happens also when error line is short, but subsequent line is long enough).

Another issue is that this behavior is not consistent, as for instance string assertion with around 150 chars shows (breaks at 152), while array literal assertion breaks before 80

### Reproduction

I tried it on Vitest examples Basic example, just inserting following assertions, using Default and Basic reporters
```ts
  // long assertion works
  expect('test test test test test test test test test test test test test test test test test test test test test test test test test').toBe('test')
  
  // until caret at end of line is at position 152 in this case
  expect('test test test test test test test test test test test test test test test test test test test test test test test test test t').toBe('test')

  // it starts working when assertion clause is moved to next line
  expect('test test test test test test test test test test test test test test test test test test test test test test test test test t')
  .toBe('test')

  // here inconsistency shows, as array literal like this works
  expect([{prop: 7}, {prop: 7}, {prop: 7}]).toBe([{another: 8} ])

  // yet it stops working when it is significantly shorter than long string assertion example no.1
  // here failing even before reaching column 80
  expect([{prop: 7}, {prop: 7}, {prop: 7}, {prop: 7}]).toBe([{another: 8} ])

  // working again when line-break is inserted
  expect([{prop: 7}, {prop: 7}, {prop: 7}, {prop: 7}])
  .toBe([{another: 8} ])
  expect(
    [{prop: 7}, {prop: 7}, {prop: 7}, {prop: 7}]
    ).toBe([{another: 8} ])
```

### System Info

```shell
tried Vitest 1.3.1 and 1.4.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
It looks like this is because of the following `200` limit is checked again highlighted code, which includes ANSI color codes and the amount such code depends on the code. For example, your array example switches colors more often than simple string, so the ANSI code length adds up quickly.

https://github.com/vitest-dev/vitest/blob/fee7d8be9d6e6f710270600ae91fa35d861b7075/packages/vitest/src/node/error.ts#L292-L294
