### ISSUE TITLE
Unexpected istanbul code coverage

### ISSUE THREAD

**Issue by sagargurtu** [vitest-dev/vitest#5438]
### Describe the bug

For v1.4.0, istanbul shows exported string constants as not covered. This is a deviation from v0.34.6 where it correctly skips string constants in code coverage.

Is this an expected change in behavior? Or a bug?

### Reproduction

See terminal for coverage results:

- v1.4.0 https://stackblitz.com/edit/vitest-dev-vitest-dy65uu
- v0.34.6 https://stackblitz.com/edit/vitest-dev-vitest-sxb7gh

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (3) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/coverage-istanbul: 0.34.6 => 0.34.6 
    vite: ^5 => 5.2.6 
    vitest: 0.34.6 => 0.34.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
In Vitest v1 we enabled `coverage.all` by default:
- github.com/vitest-dev/vitest/pull/4265

Add this option in your `v0.34.6` and you should see the same results. Or disable it in the `v1.4.0` reproduction.

**Comment by sagargurtu** [comment]
I see. Thanks for the info! Will close this issue.

However, is it valid for coverage to be collected for an exported string constant (or an exported number or boolean)? Would the recommendation be to write a test that checks if the value is as expected 🤔? I just wanted to export a public constant from my package and it feels weird to write a test to check its value.

**Comment by AriPerkkio** [comment]
> However, is it valid for coverage to be collected for an exported string constant (or an exported number or boolean)?

Looks like Istanbul does add a statement counter there: [https://evanw.github.io/source-map-visualization/#MTMzOQB...](https://evanw.github.io/source-map-visualization/#MTMzOQBmdW5jdGlvbiBjb3ZfMWR0a3FiZWJxZCgpIHsKICB2YXIgcGF0aCA9ICIvVXNlcnMvYXJpL0dpdC92aXRlc3QtZXhhbXBsZS1wcm9qZWN0L3NyYy91bnRlc3RlZC50cyI7CiAgdmFyIGhhc2ggPSAiOTIxNjY4ODc1NzAwODFhYWZhY2NhZWI1YTY1OTQwZDBjZDk4N2FkNCI7CiAgdmFyIGdsb2JhbCA9IGdsb2JhbFRoaXM7CiAgdmFyIGdjdiA9ICJfX1ZJVEVTVF9DT1ZFUkFHRV9fIjsKICB2YXIgY292ZXJhZ2VEYXRhID0gewogICAgcGF0aDogIi9Vc2Vycy9hcmkvR2l0L3ZpdGVzdC1leGFtcGxlLXByb2plY3Qvc3JjL3VudGVzdGVkLnRzIiwKICAgIHN0YXRlbWVudE1hcDogewogICAgICAiMCI6IHsKICAgICAgICBzdGFydDogewogICAgICAgICAgbGluZTogMSwKICAgICAgICAgIGNvbHVtbjogMjMKICAgICAgICB9LAogICAgICAgIGVuZDogewogICAgICAgICAgbGluZTogMSwKICAgICAgICAgIGNvbHVtbjogMzYKICAgICAgICB9CiAgICAgIH0KICAgIH0sCiAgICBmbk1hcDoge30sCiAgICBicmFuY2hNYXA6IHt9LAogICAgczogewogICAgICAiMCI6IDAKICAgIH0sCiAgICBmOiB7fSwKICAgIGI6IHt9LAogICAgaW5wdXRTb3VyY2VNYXA6IHsKICAgICAgdmVyc2lvbjogMywKICAgICAgc291cmNlczogWyIvVXNlcnMvYXJpL0dpdC92aXRlc3QtZXhhbXBsZS1wcm9qZWN0L3NyYy91bnRlc3RlZC50cyJdLAogICAgICBzb3VyY2VzQ29udGVudDogWyJleHBvcnQgY29uc3QgbWVzc2FnZSA9IFwiSGVsbG8gd29ybGRcIiBhcyBjb25zdDtcbiJdLAogICAgICBtYXBwaW5nczogIkFBQU8sYUFBTSxVQUFVOyIsCiAgICAgIG5hbWVzOiBbXQogICAgfSwKICAgIF9jb3ZlcmFnZVNjaGVtYTogIjFhMWMwMWJiZDQ3ZmMwMGEyYzM5ZTkwMjY0ZjMzMzA1MDA0NDk1YTkiLAogICAgaGFzaDogIjkyMTY2ODg3NTcwMDgxYWFmYWNjYWViNWE2NTk0MGQwY2Q5ODdhZDQiCiAgfTsKICB2YXIgY292ZXJhZ2UgPSBnbG9iYWxbZ2N2XSB8fCAoZ2xvYmFsW2djdl0gPSB7fSk7CiAgaWYgKCFjb3ZlcmFnZVtwYXRoXSB8fCBjb3ZlcmFnZVtwYXRoXS5oYXNoICE9PSBoYXNoKSB7CiAgICBjb3ZlcmFnZVtwYXRoXSA9IGNvdmVyYWdlRGF0YTsKICB9CiAgdmFyIGFjdHVhbENvdmVyYWdlID0gY292ZXJhZ2VbcGF0aF07CiAgewogICAgLy8gQHRzLWlnbm9yZQogICAgY292XzFkdGtxYmVicWQgPSBmdW5jdGlvbiAoKSB7CiAgICAgIHJldHVybiBhY3R1YWxDb3ZlcmFnZTsKICAgIH07CiAgfQogIHJldHVybiBhY3R1YWxDb3ZlcmFnZTsKfQpjb3ZfMWR0a3FiZWJxZCgpOwpleHBvcnQgY29uc3QgbWVzc2FnZSA9IChjb3ZfMWR0a3FiZWJxZCgpLnNbMF0rKywgIkhlbGxvIHdvcmxkIik7MzAwAHsidmVyc2lvbiI6MywibmFtZXMiOlsibWVzc2FnZSIsImNvdl8xZHRrcWJlYnFkIiwicyJdLCJzb3VyY2VzIjpbIi9Vc2Vycy9hcmkvR2l0L3ZpdGVzdC1leGFtcGxlLXByb2plY3Qvc3JjL3VudGVzdGVkLnRzIl0sInNvdXJjZXNDb250ZW50IjpbImV4cG9ydCBjb25zdCBtZXNzYWdlID0gXCJIZWxsbyB3b3JsZFwiIGFzIGNvbnN0O1xuIl0sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQUFPLGFBQU1BLE9BQUEsSUFBQUMsY0FBQSxHQUFBQyxDQUFBLE9BQVUifQ==). 

You can use [ignore hints](https://vitest.dev/guide/coverage.html#ignoring-code) or [`coverage.exclude`](https://vitest.dev/config/#coverage-exclude) for this. Personally I think I would add test case for the file that actually imports this file. Then it would become covered automatically.
