### ISSUE TITLE
Incompatibility for type-checking with bun

### ISSUE THREAD

**Issue by hulla-dev** [vitest-dev/vitest#5441]
### Describe the bug

Vitest exposes some really useful util helpers for testing types. These work very nicely with most bundlers (`npm`, `yarn`, `pnpm`). 

There however is an issue with bun, causing an incompatibility.

> ⚠️  Note: the issue template dropdown allows only selection between npm, yarn and pnpm, but the package manager used is infact `bun`

### Reproduction

1. Initialize a bun project `bun init`
2. Add vitest `bun add -D vitest`
3. Create a node script: 

```json
package.json
{
 "scripts": {
     "test": "vitest --typecheck"
  }
}
```

4. Create a simple test

```ts
// index.test.ts
import { test, expectTypeOf } from 'vitest'
test('example', () => {
  expectTypeOf(1).toEqualTypeOf<number>()
})
```

5. Run test via `bun test`

Following the steps you should get the following error:

<img width="814" alt="image" src="https://github.com/vitest-dev/vitest/assets/17268815/84b07a30-4151-47cd-82d9-4c13a6e97aa2">

> TypeError: expectTypeOf is not a function. (In 'expectTypeOf(1)', 'expectTypeOf' is undefined)
      at /Users/samuel/Coding/api/tests/core/request.test.ts:109:3
✗ example [2.29ms]

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M1
    Memory: 75.23 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.7.0 - ~/.volta/tools/image/node/20.7.0/bin/node
    bun: 1.0.26 - /opt/homebrew/bin/bun
  npmPackages:
    vitest: ^1.4.0 => 1.4.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
bun overwrites "vitest" module, there is zero code from this repository present when you run `bun test`.

**Comment by hulla-dev** [comment]
@sheremet-va Okay, makes sense, wasn't aware of the over-write. That being said, there should probably be a tidbit in docs about running test with bun. given even the official '`Getting Started`' section in docs mentions `bun` as a package manager option and even provides a command for installing vitest with bun.
