### ISSUE TITLE
Support specifying a line number when filtering tests

### ISSUE THREAD

**Issue by sheremet-va** [vitest-dev/vitest#5445]
### Clear and concise description of the problem

Right now it's quite cumbersome to filter out tests when using a Vitest CLI. You need to know the name and the file:

```
vitest test/basic.test.ts -t "some-name"
```

It fails if there are multiple tests that have the same pattern, so you are forced to use the full name manually:

```
vitest test/basic.test.ts -t "test full some-name"
```

### Suggested solution

Vitest 1.4.0 introduced [`includeTaskLocation`](https://vitest.dev/config/#includeTaskLocation) option that adds a `location` property to every test. With this information, we can filter tests by the line number:

```
vitest test/basic.test.ts:20
```

### Additional context

I am not sure what should happen when the line doesn't exist or there is no test at that line. Currently, we only know the location of a test, and we don't know when the body of a test ends, so it's tricky to implement a range support.

I think we should:

- Only run a test if the line is exactly equal to a location line
- If there is no test at that location, throw an error
- If range is used, throw an error (`test/basic.test.ts:20-30`)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by LostKobrakai** [comment]
> I am not sure what should happen when the line doesn't exist or there is no test at that line. Currently, we only know the location of a test, and we don't know when the body of a test ends, so it's tricky to implement a range support.

In elixir it'll run the test, which starts the closest above the supplied line. That's less brittle in the context of line changes (e.g. removing an `include` at the top).

**Comment by mzhubail** [comment]
I'm interested in picking this up.

I've looked around in the codebase.  What I have in mind is to add the filtering in [`packages/vitest/src/node/workspace.ts`](https://github.com/vitest-dev/vitest/blob/95f0203f27f5659f5758638edc4d1d90283801ac/packages/vitest/src/node/workspace.ts#L331-L354);  and to use `getTests()` from `packages/runner/src/utils/tasks.ts` to access the tests in each files and the position.

It might take a bit of time till I bring about a PR.  Just wanted to chime in and see if I'm on the right track, and if anyone has an notes or any pointers.  :eyes:

**Comment by sheremet-va** [comment]
The implementation in #6411 only supports tests, it would be nice to also support filtering suites:

```ts
describe('suite', () => {
  test('nested 1')
  test('nested 2')
})
```

```ts
vitest example.test.ts:1
```
