### ISSUE TITLE
Vitest workspace run doesn't pick .env from individual projects

### ISSUE THREAD

**Issue by semoal** [vitest-dev/vitest#5448]
### Describe the bug

I have a monorepo with different projects in `packages/*`, when we run `vitest` inside of this packages the .env.{mode} it's picked correctly, but when running in the root of the monorepo, 0 variables are caught. 

We have a `vitest.workspace.mts` file in the root with the following:

```mts
export default ["packages/*", "apps/*"];
```

We define the `vitest.config.ts` in the packages/ like this:
```ts
import tsconfigPaths from "vite-tsconfig-paths";
import { defineProject } from "vitest/config";

export default defineProject({
  envPrefix: ["SHERPAS_", "DATABASE_", "FLY_", "PRIMARY_"],
  plugins: [
    tsconfigPaths({
      root: "../..",
    }),
  ],
  test: {
    hookTimeout: 20_000,
    exclude: [
      "node_modules",
      "dist",
      ".idea",
      ".git",
      ".cache",
      "src/tests/**/*.{ts,tsx}",
    ],
    environment: "jsdom",
  },
});

```

Initially created as discussion here: #5446 

### Reproduction

[stackblitz.com/edit/vitest-dev-vitest-pxuer9?file=packages%2Flib1%2F.env.test](https://stackblitz.com/edit/vitest-dev-vitest-pxuer9?file=packages%2Flib1%2F.env.test)

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M2 Pro
    Memory: 72.27 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/Library/Caches/fnm_multishells/70491_1711450154965/bin/node
    npm: 10.2.4 - ~/Library/Caches/fnm_multishells/70491_1711450154965/bin/npm
    pnpm: 8.15.5 - ~/Library/pnpm/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 123.0.6312.86
    Safari: 17.0
  npmPackages:
    vitest: ^1.4.0 => 1.4.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by semoal** [comment]
I've tried to fix it but no luck.. there's one moment that env empties and couldn't follow where is deleted/lost.
While this issue gets fixed -- no hurry. There' a workaround using `dotenv-flow`:

In the `vitest|vite.config.m|ts` file just put that, and will load the variables correctly from the root or inside the package.
```ts
import dotenvFlow from "dotenv-flow";
const env = dotenvFlow.config({ path: import.meta.dirname });
```

**Comment by hi-ogawa** [comment]
The underlying issue might be same as https://github.com/vitest-dev/vitest/issues/5016. Manually loading dotenv should be a good workaround.

To avoid mixing different environment variables from multiple projects, it might be better to load it during `setupFiles`, which is what I suggested in https://github.com/vitest-dev/vitest/discussions/5003#discussioncomment-8187275
