### ISSUE TITLE
Unable to resolve a dependency of a dependency using alias

### ISSUE THREAD

**Issue by simjoeweb** [vitest-dev/vitest#5452]
### Describe the bug

The vitest configuration "alias" will not resolve a dependency of a dependency. Therefore, I get this error when running the tests:

`Error: Cannot find package '@some-component/react' imported from /Users/xxxxx/WebstormProjects/xxxx/node_modules/@another-component/design-system/dist/component.mjs`

"@another-component/design-system" is a dependency is my package.json. However, "@some-component/react" is a dependency of this dependency. It is also not in my node_modules, as it is supposed to be resolved by the alias.

Note that it works when running and building the project, just not when running the tests.

### Reproduction

vite.config.ts:
![image](https://github.com/vitest-dev/vitest/assets/47310519/d9907b5f-a68c-42a5-b9df-079b83607607)

vitest.config.ts:
![image](https://github.com/vitest-dev/vitest/assets/47310519/c22e8531-9ae9-4856-a29f-47b8cba2b337)

In this example, "@some-component/react" is a dependency of a dependency that I have in my package.json.

### System Info

```shell
System:
    OS: macOS 14.1.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 28.45 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.1.0 - ~/.nvm/versions/node/v20.1.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.4 - ~/.nvm/versions/node/v20.1.0/bin/npm
  Browsers:
    Chrome: 123.0.6312.86
    Safari: 17.1
  npmPackages:
    @vitejs/plugin-react: ^4.2.1 => 4.2.1 
    vite: ^5.2.0 => 5.2.6 
    vitest: ^1.4.0 => 1.4.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Aliases of imports inside external packages are not supported. You need to inline the package using [`test.server.deps.inline`](https://vitest.dev/config/#server-deps-inline) option:

```ts
export default defineConfig({
  resolve: {
    alias: {
      '@some-component/react': 'react',
    }
  },
  test: {
    server: {
      deps: {
        inline: ['@another-component/design-system']
      }
    }
  }
})
```

**Comment by simjoeweb** [comment]
Thanks a lot for your answer! 

It works in this 2 level hierarchy case, but if we add a new layer, for example "@higher-component/charts" which depends on "@another-component/design-system", then it doesn't work. Any ideas?

Example:

```js
export default defineConfig({
  resolve: {
    alias: {
      '@some-component/react': 'react',
    }
  },
  test: {
    server: {
      deps: {
        inline: ['@another-component/design-system', '@higher-component/charts']
      }
    }
  }
})
```

**Comment by hi-ogawa** [comment]
Regardless of hierarchy, `server.deps.inline` is expected to work. We would need a reproduction to investigate the issue further.

Also just in case, could you confirm you are talking about cases like this?

```sh
## alias doesn't work for @some-component/react
$ npm ls @some-component/react
your-project
  -> @higher-component/charts
    -> @another-component/design-system
      -> @some-component/react

## alias works for @some-component/react
$ npm ls @some-component/react
your-project
  -> @another-component/design-system
    -> @some-component/react
```
