### ISSUE TITLE
importActual hanging with mocked import (recursion?)

### ISSUE THREAD

**Issue by arpowers** [vitest-dev/vitest#546]
### Describe the bug

Hey there, 
It appears there is an issue with mocking and `importActual` hanging. 

I believe it is because there is some form of import recursion happening, but haven't been able to narrow it down to a specific modality yet. 

The code looks like this: 

```ts
import { assert, expect, test, vi } from "vitest"
import * as srv "../user/serverUser"

vi.mock("../user/serverUser", async () => {
  const actual = await vi.importActual("../user/serverUser")

  return actual
})

```

Which is similar to your example, however, the only difference is that "serverUser" is imported by some other files in the package. 

As for now, the test doesn't hang if I just create of copy of the `serverUser` module and try it with that. Therefore the issue here is the imports in other files.  

(Note, I don't think there are any circular dependencies in my app so its not that)

I'll be back with a reproduction or additional clarifications; but wanted to start the issue in case the problem is obvious.

### Reproduction

[Reproduction via Github](https://github.com/arpowers/vitest-mocking)

### System Info

```shell
#
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Need reproduction. `importActual` bypasses `requestWithMock`, so I doubt it has anything to do with `vi.mock`.

**Comment by arpowers** [comment]
Ok I've duplicated the issue, appears its an inadvertent (and undetected) circular dependency via wildcard exports.

I realize this is bad practice and we've fixed it but it technically works elsewhere (which is why we didn't catch it)...

This repo has the bug: 
https://github.com/arpowers/vitest-mocking

@sheremet-va @antfu 

Close this as won't fix if out of scope.

**Comment by sheremet-va** [comment]
Using `importActual` is fixed when used inside `vi.mock` here: https://github.com/vitest-dev/vitest/pull/560

**Comment by fadi-george** [comment]
Yes I ran into this. A quick fix as mention to avoid grabbing from the same alias e.g.

someFolder
index.ts
a.ts
b.ts
...

// index.ts
export * from './a';
export * from './b';
...

// a.ts
import {somethingFromB} from 'someFolder';

You would need to update this to be:

// a.ts
import {somethingFromB} from './b';

or

import {somethingFromB} from 'someFolder/b';

**Comment by sheremet-va** [comment]
Reproduction works fine on the latest version. @arpowers, can you confirm the issue if fixed? If so, feel free to close the issue.

**Comment by arpowers** [comment]
Yes is fixed now

**Comment by purepear** [comment]
Hey 👋 , I'm having trouble with some circular dependencies which were previously working with Jest. 
Vitest is hanging when I try to partially mock a module (`vi.mock()` used with `vi.importActual()`).
Here is a repro https://stackblitz.com/edit/vitest-circular-deps-repro?file=main.test.js 🙏

**Comment by MingruiZhang** [comment]
I don't think this issue if fixed? I can reproduce it in 0.27.2

**Comment by alexlafroscia** [comment]
I'm being bitten by this in `0.29.7` as well; in my case, the dependencies chain between the modules is quite deep, but I was ultimately able to track Vitest hanging during my test run down to circular dependencies between modules and an `importActual` call in a mock that, ultimately, loads the module that we're in the process of trying to mock.

**Comment by cjroebuck** [comment]
I'm seeing this too. I'm using `vi.importActual` inside of a `vi.doMock`. 

Tracked it down to import of circular dependencies (that are also being mocked by vitest). 

Workaround i'm using is to modify the import alias in one of the files by passing something unique in a query param e.g. 
```
import { updateUser } from "../apis/accountService?fixme=whenvitestworkswithcirculars";
```
This allows the test run to proceed.. Thanks to @fadi-george for the hint about import alias.
