### ISSUE TITLE
Defining `Object` in module breaks vitest

### ISSUE THREAD

**Issue by jasonkuhrt** [vitest-dev/vitest#5463]
### Describe the bug

If a user does something like so:

```
export const Object = 1
```

Vitest will throw an error of:

```
TypeError: Object.defineProperty is not a function
```

I consider this bug because user could should not be able to crash Vitest like this.

### Reproduction

As described

### System Info

```shell
Doesn't matter
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is a bug in Vite: https://github.com/vitejs/vite/issues/15485

**Comment by hi-ogawa** [comment]
This is already tracked on Vitest too https://github.com/vitest-dev/vitest/issues/4829, so can we close?
