### ISSUE TITLE
Serialized Error: { code: 'ERR_REQUIRE_ESM' }

### ISSUE THREAD

**Issue by sangeetha321** [vitest-dev/vitest#5472]
Serialized Error: { code: 'ERR_REQUIRE_ESM' } 

<img width="957" alt="issue" src="https://github.com/vitest-dev/vitest/assets/14287834/4928ad3c-adc5-4a47-b222-b38eec584e76">

### Reproduction

node_modules/package/dist/index.d.ts

`export { default as Accordion, AccordionItem } from './Accordion';
`

vite config
  ```
 test: {
      globals: true,
      pool: 'forks', 
      globalSetup: "./src/test-globals.ts",
      environment: "jsdom",
      threads: true,
      setupFiles: "./src/setupTests.ts",
      coverage: {
        reporter: ["cobertura", "text"],
        exclude: ["node_modules/", "src/setupTests.ts"],
      },
    
    },
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz
    Memory: 5.50 GB / 15.75 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.5.0 - ~\TSI\TSI-Web-Customer-Portal\node_modules\.bin\npm.CMD
    pnpm: 8.9.2 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.65)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @vitejs/plugin-react-swc: ^3.5.0 => 3.6.0
    @vitest/coverage-v8: ^1.3.1 => 1.4.0
    vite: ^5.0.8 => 5.2.6
    vitest: ^1.3.1 => 1.4.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
I think you could try `server.deps.inline: ["@your/package"]` in config, something like https://github.com/vitest-dev/vitest/issues/5283#issuecomment-1962781471

**Comment by sangeetha321** [comment]
I have one private  component libray.

> This is the package.json of the library

```
{
    "name": "@components/react",
    "version": "1.1.0",
    "description": "components React library",
    "main": "./dist/components-react.js",
    "types": "./dist/index.d.ts",
    "sideEffects": [
      "**/*.scss"
    ],
    "scripts": {
      "build": "webpack --config webpack.dev.js",
```

> node_modules/@components\react\dist\index.d.ts

```
export { useToggle } from './_hooks';
export { default as Accordion, AccordionItem } from './Accordion';
export { default as ActionButton } from './ActionButton';
export { default as ActionButtonValidation } from './ActionButtonValidation';
export { default as ActionList, ActionListItem } from './ActionList';
export { default as Breadcrumb } from './Breadcrumb';
export { default as Breadcrumbs } from './Breadcrumbs';
export { default as Card } from './Card';
```

I was geting below error when I run the vitest
![image](https://github.com/vitest-dev/vitest/assets/14287834/5c66f81c-0d96-4d51-8a09-783157cc2065)


> To solve that I updated the vite config as below

```
alias: {
    '@components/react': fileURLToPath(
        new URL("src/components.ts", import.meta.url)
      ),
  },
```

> 
And my components.ts is

`export * as default from '@components/react';`

Now test cases are running succesfully, all the components path is correct. But the hook useToggle is not working. 
It gives me below error


**TypeError: useToggle is not a function or its return value is not iterable**


<img width="659" alt="Untitled" src="https://github.com/vitest-dev/vitest/assets/14287834/6f71748c-802c-441e-bee2-345f38ed0c89">


How can we resolve this?
