### ISSUE TITLE
Allow disabling file watchers for vite-node

### ISSUE THREAD

**Issue by danieldiekmeier** [vitest-dev/vitest#5488]
### Clear and concise description of the problem

I have a few `.ts` scripts that I run on my server. They are scripts that run through and then exit, so I don't need file watching. Of course, it wouldn't matter either way, but I started getting this error when the files in my project increased:

```
ENOSPC: System limit for number of file watchers reached
```

My limit was set to the default of 8192. This is already weird, because I only have ~604 files in my project, but whatever.

### Suggested solution

I propose a flag like `--no-watch` that disables file watchers for cases where you don't need them.

### Alternative

I'm currently solving this by setting `server.watch: null` in a dedicated `vite-node.config.js` to disable the watcher: https://vitejs.dev/config/server-options.html#server-watch

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
Actually `server.watch: null` is introduced for Vitest https://github.com/vitejs/vite/pull/14208 and already used in some places

**Comment by dominictobias** [comment]
I thought that `run` is supposed to run without watching but fails in Buildkit 🤔

```
$ vitest run --coverage
  | The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
  | Vitest  "deps.inline" is deprecated. If you rely on vite-node directly, use "server.deps.inline" instead. Otherwise, consider using "deps.optimizer.web.include"
  |  
  | RUN  v1.6.0 /var/lib/buildkite-agent/builds/buildkite-node20-builder-<redacted>/<redacted>
  | Coverage enabled with istanbul
  |  
  |  
  | ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
  | Error: ENOSPC: System limit for number of file watchers reached, watch '/var/lib/buildkite-agent/builds/buildkite-node20-builder-<redacted>/<redacted>/node_modules/<redacted>/charting_library/bundles/id_ID.5652.afa01acb54a69426de69.js'
  | ❯ FSWatcher.<computed> node:internal/fs/watchers:247:19
  | ❯ Object.watch node:fs:2491:36
  | ❯ createFsWatchInstance node_modules/chokidar/lib/nodefs-handler.js:119:15
  | ❯ setFsWatchListener node_modules/chokidar/lib/nodefs-handler.js:166:15
  | ❯ NodeFsHandler._watchWithNodeFs node_modules/chokidar/lib/nodefs-handler.js:331:14
  | ❯ NodeFsHandler._handleFile node_modules/chokidar/lib/nodefs-handler.js:395:23
  | ❯ NodeFsHandler._addToNodeFs node_modules/chokidar/lib/nodefs-handler.js:637:21
  |  
  | ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
  | Serialized Error: { errno: -28, syscall: 'watch', code: 'ENOSPC', path: '/var/lib/buildkite-agent/builds/buildkite-node20-builder-<redacted>/<redacted>/node_modules/<redacted>/charting_library/bundles/id_ID.5652.afa01acb54a69426de69.js', filename: '/var/lib/buildkite-agent/builds/buildkite-node20-builder-<redacted>/<redacted>/node_modules/<redacted>/charting_library/bundles/id_ID.5652.afa01acb54a69426de69.js' }
```

**Comment by wmertens** [comment]
I'd like to add that exclude nor negative include seem to prevent this from happening. If you have a lot of files under your repo on Linux, you'll hit this.

The include/exclude should do early cutoff so that it doesn't descend into ignored directories.
