### ISSUE TITLE
TypeError: actual.match is not a function

### ISSUE THREAD

**Issue by ShooTeX** [vitest-dev/vitest#5513]
### Describe the bug

Pre `1.4.0` we were testing promises that were rejected with `Error` using:

`await expect(rejectedPromise).rejects.toMatch(/invalid/);`

but now it's throwing:

`TypeError: actual.match is not a function`

Using `toThrow()` instead fixes the issue.
I'm not sure if the error is expected but the message is not really helpful.

This is probably related to #5267.

### Reproduction

[v1.4.0](https://stackblitz.com/edit/vitest-dev-vitest-rxbti7?file=test%2Fbasic.test.ts)

[v1.3.1](https://stackblitz.com/edit/vitest-dev-vitest-n7aga4?file=test%2Fbasic.test.ts)

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 4.16 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.2 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - /etc/profiles/per-user/*/bin/yarn
    npm: 10.5.0 - /opt/homebrew/bin/npm
    pnpm: 8.15.5 - /etc/profiles/per-user/*/bin/pnpm
    bun: 1.0.35 - /etc/profiles/per-user/*/bin/bun
  Browsers:
    Chrome: 123.0.6312.107
    Safari: 17.4.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ShooTeX** [comment]
sorry, for some reason I didn't see #5428 is this possibly already fixed?

**Comment by sheremet-va** [comment]
> sorry, for some reason I didn't see #5428 is this possibly already fixed?
> 
> edit: The fix seems to be a more descriptive error, but for our case it is a breaking change since the test was passing in `1.3.1`. Not sure if intended.

Yeah, this was fixed but not released yet. 1.5.0 should be released this week.
