### ISSUE TITLE
__mocks__ folder doesn't work

### ISSUE THREAD

**Issue by fadi-george** [vitest-dev/vitest#552]
### Describe the bug

`__mocks__` is a common way (with Jest) to mock node-modules (and something helpers). But currently it doesn't seem to work. It works for my regular Jest setup that uses `vite-tsconfig-paths`. 

### Reproduction

https://stackblitz.com/edit/node-b3r6jj?file=src%2FSomeComponent.spec.tsx

I tried `vite-tsconfig-paths` (similar to my own setup), as well as Vite's own resolve alias config. Neither work.

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 82.06 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Brave Browser: 97.1.34.80
    Chrome: 97.0.4692.71
    Safari: 15.2
  npmPackages:
    @vitejs/plugin-react: ^1.1.4 => 1.1.4 
    vite: 2.7.12 => 2.7.12 
    vitest: 0.1.17 => 0.1.16
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Try naming it as a file, not a folder.

**Comment by sheremet-va** [comment]
Also we dont (and won't) support automocking. You need to manually call vi.mock("path")

**Comment by sschneider-ihre-pvs** [comment]
What about paths like `@composable/useSomething` will that be resolved in `vi.mock` ?

**Comment by sschneider-ihre-pvs** [comment]
Ok, that doesn't work also :)
is there a debugging possibility to inspect where `vi.mock('@composable/useSomething')` is looking for the mock?

**Comment by sheremet-va** [comment]
No debugging option available at the moment. You can look into `examples/mocks` in the repo.

**Comment by sschneider-ihre-pvs** [comment]
I tried it out in the stackblitz repo
