### ISSUE TITLE
Vitest do no respect the `"type": "commonjs"` in package.json

### ISSUE THREAD

**Issue by zanminkian** [vitest-dev/vitest#5522]
### Describe the bug

When the project is commonjs,

```json
{
  "private": true,
  "type": "commonjs",
  "scripts": {},
  "devDependencies": {
    "vitest": "^1.4.0"
  }
}

```

Vitest still import the node_modules dependencies as esm

### Reproduction

https://github.com/zanminkian/bug-report/tree/vitest-module-bug

Clone this repo and checkout to the `vitest-module-bug` branch. See the readme file to reproduce.

### System Info

```shell
System:
    OS: Linux 6.4 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) arm64 unknown
    Memory: 1.62 GB / 5.79 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.19.1 - ~/.local/state/fnm_multishells/35759_1712863486372/bin/node
    Yarn: 1.22.21 - ~/.local/state/fnm_multishells/35759_1712863486372/bin/yarn
    npm: 10.2.4 - ~/.local/state/fnm_multishells/35759_1712863486372/bin/npm
    pnpm: 8.15.4 - ~/.local/state/fnm_multishells/35759_1712863486372/bin/pnpm
  npmPackages:
    vitest: ^1.4.0 => 1.4.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`tsx` transforms your `imports` into `require` calls under the hood.

When you use `import`, the `import` export condition is used even if your package has a commonjs type. Vitest doesn't support `require` intentionally and assumes every file is a valid isolated ES module.

**Comment by zanminkian** [comment]
Not only `tsx`. Running `pnpm tsc && node dist/app.js` will print `from cjs` too. That means `tsx` and `typescript` respect node rules. They are standard. Vitest behave different, which is hacky and unpredictable for typescript commonjs project, e.g. nestjs projects.

Many backend node project use typescript and compile source code to cjs. They running cjs code in production, but running esm code in unit test. It's unacceptable. That's why I created [typed-jest](https://github.com/zanminkian/typed-jest) for cjs typescript projects.

**Comment by sheremet-va** [comment]
We cannot assume how you will bundle your application. What if you use `tsup` to create `.mjs` files?

Anyway, Vitest will not support loading modules with `require`. You can use any other tool including the [built-in test runner](https://nodejs.org/api/test.html).

**Comment by zanminkian** [comment]
Many backend node project, like nestjs projects, do not bundle, just `tsc` compile the source code.

Built-in test runner is the next next generation. Mock and stub is inconvenient. I will continue use Jest in cjs project. In esm project, Viest is the best choice currently as Jest do not support esm very well.
