### ISSUE TITLE
Execute `onTestFinished` handlers in the reverse order they are scheduled in

### ISSUE THREAD

**Issue by nvie** [vitest-dev/vitest#5529]
### Clear and concise description of the problem

Currently, it looks like `onTestFinished` runs as a FIFO queue:

```ts
onTestFinished(() => console.log("foo"));
onTestFinished(() => console.log("bar"));
```

Output after test:
```
foo
bar
```

However, it seems to be more useful if those registrations are run in the **reverse order** they were scheduled in, so you can colocate setup and teardown code and never have to worry about the order of execution here:

```ts
// Suppose this code lives in a `getDb()` helper
const db = setupDb();
onTestFinished(() => db.teardown());

// And this code lives in a `getTable()` helper
const table = db.createTable();
onTestFinished(() => db.dropTable(table.name));
```

Right now, `db.teardown()` gets called before `db.dropTable()`, which causes an issue.

### Suggested solution

If the order the teardown functions are run in is reversed, this class of problems will disappear.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I think they are actually called in parallel.

**Comment by sheremet-va** [comment]
Ideally, they should follow [`sequence.hooks`](https://vitest.dev/config/#sequence-hooks) option. So this is a bug at the very least.

**Comment by nvie** [comment]
Oh yeah, if `sequence.hooks: "stack"` could be used, that'd be great 👍
