### ISSUE TITLE
Problems with Vue components; but only when using web UI

### ISSUE THREAD

**Issue by yankeeinlondon** [vitest-dev/vitest#553]
### Describe the bug

I have a set of tests that leverage Vue3 and Vue3's testing library. When I run them with **Vitest** in the console they all pass:

<img width="384" alt="image" src="https://user-images.githubusercontent.com/980757/149718128-2c782282-7cfe-44d2-a4ac-d0e7aab5d738.png">

When I run and load the very nice Web UI, the tests which interact with Vue Components fail:

<img width="559" alt="image" src="https://user-images.githubusercontent.com/980757/149718193-166935dd-4cf7-48e1-bd95-ff86bdcae49a.png">

### Reproduction

Unfortunately the repo I'm discussing is not open source so I attempted to create a minimal reproduction: https://stackblitz.com/edit/vitest-dev-vitest-fsvsdz?devtoolsheight=33&file=test/reproduction.test.ts

However, this is currently unable to boot up VueJS with an error about needing to install `@vitejs/plugin-vue` but of course I **do** have it installed. Maybe i'm just too tired atm but I've looked it over several times and not making progress.

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (28) x64 Intel(R) Xeon(R) W-2170B CPU @ 2.50GHz
    Memory: 39.71 MB / 128.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 97.1.34.80
    Chrome: 97.0.4692.71
    Firefox: 96.0
    Safari: 15.2
  npmPackages:
    @vitejs/plugin-vue: ^2.0.1 => 2.0.1 
    vite: ^2.7.12 => 2.7.12 
    vitest: ^0.1.17 => 0.1.17
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ksnyde** [comment]
I have also put this repo into Github at: https://github.com/ksnyde/vitest-issue

**Comment by anbraten** [comment]
Same issue for my setup. Would be nice to extend the [vue sample](https://github.com/vitest-dev/vitest/tree/main/examples/vue) with a none `setup` component:

```vue
<script lang="ts">
const props = defineProps<{ promise: Promise<void> }>()
await props.promise

import { defineComponent } from 'vue'

export default defineComponent({
  props: {
   // [...]
  },

  setup() {
    // [...]
  },
});
</script>

<template>
  <div>resolved</div>
</template>
```

**Comment by bonabrian** [comment]
same issue here
```
<script lang="ts">
import { computed, defineComponent, PropType, ref } from 'vue'

export default defineComponent({
  name: 'VIcon',
  props: {
    name: {
      type: String,
      default: '',
    },
    size: {
      type: [String, Number] as PropType<string | number>,
      default: 16,
    },
    fill: {
      type: String,
      default: 'none',
    },
    animation: {
      type: String,
      default: null,
      validator: (val: string) => {
        return ['spin', 'pulse'].includes(val)
      },
    },
    animationSpeed: {
      type: String,
      default: null,
      validator: (val: string) => {
        return ['slow', 'fast'].includes(val)
      },
    },
  },
  setup(props) {
    const iconRef = ref(null)
    const fallbackIcon = 'help-circle'
    const computedIcon = computed(() => {})

    return { iconRef, computedIcon }
  },
})
</script>
```

**Comment by edimitchel** [comment]
I'll try to create a Vue sample with a non-setup component, and then try to fix the problem!

**Comment by sheremet-va** [comment]
Adding this to config helps:

```js
  optimizeDeps: {
    exclude: mode === 'test' ? ["vue"] : [],
  }
```

We merged a fix that adds `entries: []`, but it is still not enough for all usecases. @patak-dev wanted to make a more well-around solution in Vite by specifying `optimizeDeps: false`, so i guess in the meantime we are waiting.
