### ISSUE TITLE
V8 Coverage fails

### ISSUE THREAD

**Issue by digitalkaoz** [vitest-dev/vitest#5532]
### Describe the bug

```
❯ pnpm test:coverage

> app@0.0.0 test:coverage /path/to/app
> vitest run --coverage src/


 RUN  v1.5.0 /path/to/app
      Coverage enabled with v8

 Test Files  35 passed (35)
      Tests  420 passed | 3 skipped (423)
   Start at  10:27:11
   Duration  5.02s (transform 2.91s, setup 21.06s, collect 12.65s, tests 1.29s, environment 4.48s, prepare 2.21s)


⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: requires Node.js >=10.12.0
 ❯ node_modules/.pnpm/@vitest+coverage-v8@1.5.0_vitest@1.5.0/node_modules/@vitest/coverage-v8/dist/provider.js:1803:21
 ❯ ModuleJob.run node:internal/modules/esm/module_job:222:25
 ❯ ModuleLoader.import node:internal/modules/esm/loader:323:24
 ❯ Object.getProvider node_modules/.pnpm/@vitest+coverage-v8@1.5.0_vitest@1.5.0/node_modules/@vitest/coverage-v8/dist/index.js:49:36
 ❯ Vitest.initCoverageProvider node_modules/.pnpm/vitest@1.5.0_@types+node@20.12.7_@vitest+ui@1.5.0_happy-dom@14.7.1_less@4.2.0/node_modules/vitest/dist/vendor/cac.qnW6GNL2.js:11651:29
 ❯ Vitest.start node_modules/.pnpm/vitest@1.5.0_@types+node@20.12.7_@vitest+ui@1.5.0_happy-dom@14.7.1_less@4.2.0/node_modules/vitest/dist/vendor/cac.qnW6GNL2.js:11665:7
 ❯ startVitest node_modules/.pnpm/vitest@1.5.0_@types+node@20.12.7_@vitest+ui@1.5.0_happy-dom@14.7.1_less@4.2.0/node_modules/vitest/dist/vendor/cac.qnW6GNL2.js:18863:5
 ❯ start node_modules/.pnpm/vitest@1.5.0_@types+node@20.12.7_@vitest+ui@1.5.0_happy-dom@14.7.1_less@4.2.0/node_modules/vitest/dist/vendor/cac.qnW6GNL2.js:19645:17
 ❯ CAC.run node_modules/.pnpm/vitest@1.5.0_@types+node@20.12.7_@vitest+ui@1.5.0_happy-dom@14.7.1_less@4.2.0/node_modules/vitest/dist/vendor/cac.qnW6GNL2.js:19626:3




 ELIFECYCLE  Command failed with exit code 1.
```

as you can see the tests are fine.

### Reproduction

coverage is working perfectly fine with istanbul

from @ejexxeffer : https://stackblitz.com/~/github.com/ejexxeffer/datepickertest

### System Info

```shell
environment (also fails in CI):

❯ pnpm --version
8.15.5
❯ node --version
v21.7.2
❯ vite --version
vite/5.2.8 darwin-arm64 node-v21.7.2
```

versions:

```
{
  "name": "app",
  "version": "0.0.0",
  "type": "module",
  "dependencies": {
    "vue": "^3.4.21",
    "vue-i18n": "^9.12.0",
    "vue-router": "^4.3.0",
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.4",
    "@vitest/coverage-v8": "^1.5.0",
    "@vitest/ui": "^1.5.0",
    "@vue/test-utils": "^2.4.5",
    "@vue/tsconfig": "^0.5.1",
    "happy-dom": "^14.7.1",
    "typescript": "^5.4.5",
    "vite": "^5.2.8",
    "vitest": "^1.5.0",
    "vue-tsc": "^2.0.13"
  },
  "engines": {
    "node": ">=20",
    "pnpm": ">=8.6"
  }
}
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Without reproduction setup it's difficult to say what's going on here. Are your tests mocking `fs`?

https://github.com/istanbuljs/v8-to-istanbul/blob/fcc2e35891f9034ba5d283477e6da15336cb7372/lib/v8-to-istanbul.js#L11-L18

**Comment by digitalkaoz** [comment]
Mh, will check, it worked with the latest 0.x vitest release and v8-coverage

Ari Perkkiö ***@***.***> schrieb am So., 14. Apr. 2024, 16:36:

**Comment by digitalkaoz** [comment]
Mh, no, no mocking of FS can be found :/

Robert Schönthal ***@***.***> schrieb am So., 14. Apr.
2024, 19:29:

**Comment by ejexxeffer** [comment]
I have the same problem. And here is simple reproduction on stackblitz: https://stackblitz.com/~/github.com/ejexxeffer/datepickertest

**Comment by digitalkaoz** [comment]
then it wont work in vite5 (which defaults to ESM now)
