### ISSUE TITLE
v.1.5.0 can't pass filters with leading/trailing slashes to CLI

### ISSUE THREAD

**Issue by diegohaz** [vitest-dev/vitest#5534]
### Describe the bug

Before v1.5.0, I could pass filters with leading/trailing slashes like so:

```sh
vitest /basic
```

This would ensure tests with files beginning with `basic` run, but `something-basic` wouldn't.

Now, this filter doesn't work anymore.

### Reproduction

Open https://stackblitz.com/edit/vitest-dev-vitest-ggq36j?file=package.json and check the logs.

It will first run `vitest run /basic` with v1.5.0, where the filter doesn't work. Then, it will install v1.4.0 and run the same command. Now the filter works.

### System Info

```shell
StackBlitz stats:

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: latest => 1.5.0 
    vite: latest => 5.2.8
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
It looks like the handling of leading slash has changed and probably supporting you example makes sense, so I made a PR for the fix.

You also mentioned trailing slash, but I'm not sure about that part. Can you elaborate what's the issue with trailing slash?

**Comment by diegohaz** [comment]
@hi-ogawa Thank you for looking into this.

Trailing slash would follow the same logic: `basic/` matches a _folder_ `basic` and `something-basic`, but not `basic-something`.
