### ISSUE TITLE
Extend mocking

### ISSUE THREAD

**Issue by sheremet-va** [vitest-dev/vitest#554]
- [x] `vi.unmock` is not getting hoisted
- [x] we need `doMock`/`doUnmock` that are not getting hoisted
- [x] support calling `vi.mock` inside `setupFiles` to simulate automocking
- [ ] migration guide for mocking
- [x] refactor to make it easily testable
- [x] calling `vi.doMock` will mock a module if called inside library

**Comment by Demivan** [comment]
Suggestion: make `vi.mock` return mocked module if possible. So there it no need to import module in tests.
This will fix the Typescript hacks like this:
https://github.com/vitest-dev/vitest/blob/c927e2eea47454f662a6f2049f0a684c59225bab/test/core/test/mocked.test.ts#L2-L3
When type of mocked module is not the same as the real one.
https://github.com/vitest-dev/vitest/blob/c927e2eea47454f662a6f2049f0a684c59225bab/test/core/test/mocked.test.ts#L9-L11

**Comment by sheremet-va** [comment]
We will need to make it async then

**Comment by Demivan** [comment]
Maybe another function then? Not having access to global variables and having wrong type in Typescript is annoying.
It makes it hard to make a module mock that you can control from a test. In the example above it is hard to change `timeout` property if you need a different value in different tests.
Or maybe I'm missing something?

**Comment by sheremet-va** [comment]
> Maybe another function then? Not having access to global variables and having wrong type in Typescript is annoying. 

You can use `vi.mocked` helper to give it proper types. For example, if method is a spy, it will be typed as such.

> It makes it hard to make a module mock that you can control from a test. In the example above it is hard to change timeout property if you need a different value in different tests.

If you need a different value in different test, you will mock it as a different value, no? Mocks are bound to test files, they are not shared.

> Or maybe I'm missing something?

You can also use `vi.importMock<typehint>('path')`

**Comment by Demivan** [comment]
> If you need a different value in different test, you will mock it as a different value, no? Mocks are bound to test files, they are not shared.

I wanted to change mocked value in the same test file. I have multiple tests for the same module but with different inputs.

> Also you can use vi.spyOn(module, 'timeout', 'get').mockReturnValue(1000), if you need a different value in a test.

This is what I needed, thanks. Need to add this to docs :slightly_smiling_face:
