### ISSUE TITLE
Vitest browser hangs for more than 127 test files

### ISSUE THREAD

**Issue by underoot** [vitest-dev/vitest#5550]
### Describe the bug

If you launch Vitest browser with more than 127 files, Vitest prints error somewhere in the middle:
```
SyntaxError: Failed to construct 'WebSocket': The URL 'ws://localhost:undefined/' is invalid.
 ❯ setupWebSocket ../../../../@vite/client:509:20
 ❯ fallback ../../../../@vite/client:488:22
 ❯ WebSocket.<anonymous> ../../../../@vite/client:524:13
```

If file parallelisation disabled situation becomes even worse. You don't see any error for some time, Vitests stucks in the end and after a while you see error:
```
Error: Cannot connect to the server in 60 seconds
 ❯ ../../../../__vitest_browser__/rpc-slP7oy1q.js:551:16
```

### Reproduction

https://github.com/underoot/vitest-large-file-list-issue

Run `npm run run:bad` for launch with created 128 files
Run `npm run run:good` for launch with created 127 files

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.05 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.19.0/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v18.19.0/bin/npm
  Browsers:
    Chrome: 123.0.6312.123
    Chrome Canary: 125.0.6420.0
    Safari: 17.2.1
  npmPackages:
    @vitest/browser: ^1.5.0 => 1.5.0
    vitest: ^1.5.0 => 1.5.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Similar issues related to the number of test files are reported here:
- https://github.com/vitest-dev/vitest/issues/5382
