### ISSUE TITLE
When upgrading from 1.4.0 to 1.5.0, an error related to CommonJS modules appears.

### ISSUE THREAD

**Issue by rayhomie** [vitest-dev/vitest#5555]
### Describe the bug

<img width="972" alt="image" src="https://github.com/vitest-dev/vitest/assets/63136891/6046087d-b568-4e7e-8db1-b82464d08014">

 FAIL  tests/alipay/_util/__tests__/useHandleCustomEvent.spec.ts [ tests/alipay/_util/__tests__/useHandleCustomEvent.spec.ts ]
SyntaxError: Named export 'render' not found. The requested module './node_modules/preact-render-to-string/dist/index.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from './node_modules/preact-render-to-string/dist/index.js';
const { render: serverRender } = pkg;

### Reproduction

https://github.com/ant-design/ant-design-mini/actions/runs/8686918943/job/23819371194

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 101.98 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - /usr/local/bin/node
    npm: 10.2.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 123.0.6312.124
    Safari: 17.1.2
  npmPackages:
    @vitest/coverage-istanbul: ^1.1.1 => 1.5.0 
    vitest: ^1.5.0 => 1.5.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Can you provide smaller reproduction? With that size of repo and without English, we cannot take any actions on your issues.

**Comment by rayhomie** [comment]
> Can you provide smaller reproduction? With that size of repo and without English, we cannot take any actions on your issues.

https://github.com/rayhomie/vitest-bug-report

clone this repo, and read README.md

**Comment by hi-ogawa** [comment]
This error is probably due to this change:
- https://github.com/vitest-dev/vitest/pull/5416

To get the previous behavior, can you try `server.deps.inline`?
https://stackblitz.com/edit/github-ocsroc?file=vite.config.ts

```ts
{
  test: {
    server: {
      deps: {
        inline: [/functional-mini/],
      },
    }
  }
}
```

The underlying issue seems to be that you package re-exports preact somewhere, but the way it's done doesn't seems to be NodeJS esm compliant.

```ts
// node repro.mjs
import { alipayComponent } from 'functional-mini/component';
console.log(alipayComponent);
```

```
file:///home/projects/github-ocsroc/node_modules/functional-mini/dist/esm/3rd-party/preact.js:5
export { render as serverRender } from './node_modules/preact-render-to-string/dist/index.js';
         ^^^^^^
SyntaxError: The requested module './node_modules/preact-render-to-string/dist/index.js' does not provide an export named 'render'
    at ModuleJob._instantiate (https://githubocsroc-4qyz.w-credentialless-staticblitz.com/blitz.7dbe22a9.js:181:1509)
    at async ModuleJob.run (https://githubocsroc-4qyz.w-credentialless-staticblitz.com/blitz.7dbe22a9.js:181:2327)
```
