### ISSUE TITLE
Incompatible with with Comlink Workers

### ISSUE THREAD

**Issue by charlieforward9** [vitest-dev/vitest#5571]
### Describe the bug

I was testing my code that uses a [Comlink web worker](https://github.com/mathe42/vite-plugin-comlink). I followed the [Testing with Web Workers instructions](https://github.com/vitest-dev/vitest/tree/main/packages/web-worker#readme).

**Error prior to `@vitest/web-worker`config**
```
ReferenceError: Worker is not defined
```

**Error after putting `@vitest/web-worker` into setupFiles config**
```
[vitest] `importScripts` is not supported in Vite workers. Please, consider using `import` instead
```

My service worker is used as such, this is the only please a worker is used across/referenced the entire application.
```ts
const instance = new ComlinkWorker<typeof import("../service")>(new URL("../service", import.meta.url));
instance.doWork()
```

My understanding of service workers is still quite limited. 

### Reproduction

TODO ( about to 💤 on it and get back to in the AM)

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M2
    Memory: 77.75 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 123.0.6312.124
    Safari: 17.3.1
  npmPackages:
    @vitejs/plugin-react: ^4.0.4 => 4.2.1 
    @vitest/coverage-v8: ^1.4.0 => 1.4.0 
    @vitest/web-worker: ^1.5.0 => 1.5.0 
    vite: ^5.1.3 => 5.1.3 
    vitest: ^1.4.0 => 1.4.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
```[tasklist]
### Tasks
```

**Comment by sheremet-va** [comment]
We cannot support `importScripts` because importing is asynchronous, but this API is synchronous. I would recommend using the [browser mode](https://vitest.dev/guide/browser.html) instead.

**Comment by charlieforward9** [comment]
@sheremet-va  Thank you. Is this something potentially worth working on within the Comlink library? Or is browser mode a good workaround to avoid this additional work?

**Comment by charlieforward9** [comment]
I am still curious about this issue. As my last comment is coming up on the 3 day mark, I am adding an additional one to prevent any automatic action from taking place, and also to add that I will be writing the tests for this module at the beginning of next week, so I hope to be adding a reproducible sample here within the next 3 days.

**Comment by sheremet-va** [comment]
I don't think the comlink library can do anything to support `@vitest/web-worker` - it is meant to be used with the default Vite's worker handling.

Supporting `importScripts` is out of scope for Vitest, I would recommend testing your code in a real browser.
