### ISSUE TITLE
ES module import fails with v1.5.0 (but works up to v1.4.0)

### ISSUE THREAD

**Issue by NiasSt90** [vitest-dev/vitest#5573]
### Describe the bug

> $ yarn run vitest --run --reporter basic  --environment jsdom src/App.test.tsx
yarn run v1.22.21
warning ../../package.json: No license field
$ /home/user/projekte/bvo-portal-ui/node_modules/.bin/vitest --run --reporter basic --environment jsdom src/App.test.tsx
> 
> RUN  v1.5.0 /home/user/projekte/bvo-portal-ui
>
> ❯ src/App.test.tsx  (0 test)
>
>⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
>
> FAIL  src/App.test.tsx [ src/App.test.tsx ]
>Error: Directory import '/home/user/projekte/bvo-portal-ui/node_modules/@mui/x-date-pickers/AdapterDateFns' is not >supported resolving ES modules imported from /home/user/projekte/bvo-portal-ui/node_modules/@intentus/bvo->theme-react/dist/esm/index.js
>Did you mean to import @mui/x-date-pickers/node/AdapterDateFns/index.js?
>⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯>⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯>⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
>Serialized Error: { url: 'file:///home/user/projekte/bvo-portal-ui/node_modules/@mui/x-date-pickers/AdapterDateFns', >code: 'ERR_UNSUPPORTED_DIR_IMPORT' }
>⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯>⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯>⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

`@mui/x-date-pickers` is a peerDependency from `@intentus/bvo-theme-react` (a bundled ESM library).

Until vitest=v1.4.0 everything worked fine. 
With v1.5.0 it crashes every time a test (or the production code from this test) uses an import of the `@intentus/bvo-theme-react` library.

### Reproduction

Currently i don't know how to create an reproducer.

The (esm) module `@intentus/bvo-theme-react`  is not public available.

### System Info

```shell
Debian/Bookworm 

$ node --version
v20.5.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by FranciscoKloganB** [comment]
Facing a similar issue with `react/testing-library`.

```bash
SyntaxError: '*[role~="heading"],h1,h2,h3,h4,h5,h6' is not a valid selector
 ❯ emit node_modules/.pnpm/nwsapi@2.2.8/node_modules/nwsapi/src/nwsapi.js:557:17
 ❯ Object._querySelectorAll [as select] node_modules/.pnpm/nwsapi@2.2.8/node_modules/nwsapi/src/nwsapi.js:1501:9
 ❯ HTMLDivElementImpl.querySelectorAll node_modules/.pnpm/jsdom@22.1.0/node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:78:26
 ❯ HTMLDivElement.querySelectorAll node_modules/.pnpm/jsdom@22.1.0/node_modules/jsdom/lib/jsdom/living/generated/Element.js:1119:58
 ❯ queryAllByRole node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/queries/role.js:121:31
 ❯ node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/query-helpers.js:74:17
 ❯ node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/query-helpers.js:52:17
 ❯ node_modules/.pnpm/@testing-library+dom@9.3.4/node_modules/@testing-library/dom/dist/query-helpers.js:95:19
 ❯ src/pages/accounts/verify/AccountVerifyPage.spec.tsx:303:43
    301|         expect(dialog).toBeVisible()
    302| 
    303|         const alertTitle = within(dialog).getByRole('heading', {
       |                                           ^
    304|           name: /translated_error/i,
    305|         })
```

**Comment by qraynaud** [comment]
Same here. Cannot make a repro for the moment. But `1.5.0` is also broken on my side.

**Comment by qraynaud** [comment]
I don’t think this is it. I can import the dep using standard node:
```bash
node << EOF
(async() => console.log(await import("module")))()
EOF
```
do work.

**Comment by qraynaud** [comment]
But the problem could be related to the provided patch though. I do have both `"type": "module"` and `esm/` in my path. So before the patch, my codebase returned `false` and now it returns `true`. But it seems it is breaking things to do so later on.

**Comment by NiasSt90** [comment]
> This could be relevant if your dependency uses a path like `dist/esm/index.js`.
> 
> * [When upgrading from 1.4.0 to 1.5.0, an error related to CommonJS modules appears. #5555 (comment)](https://github.com/vitest-dev/vitest/issues/5555#issuecomment-2062855818)
> 
> I see it as a packaging issue since NodeJs cannot probably import such deps either. So, the workaround is to use `server.deps.inline` as suggested in the comment above.

thanks, that looks exactly like the cause of my problem.
And the suggested workaround 
`		server: {
			deps: {
				inline:["@intentus/bvo-theme-react"]
			},
		},
`
in my vite.config.ts works.

Now i'm trying to understand what is wrong with our library ;)
