### ISSUE TITLE
Vitest not working with uwebsockets.js

### ISSUE THREAD

**Issue by chanon** [vitest-dev/vitest#5576]
### Describe the bug

Just calling uwebsocket's `App()` will terminate the test and Vitest will not show results of any tests.

I have tried looking through the Vitest documentation to see what the problem could be, but did not find anything.

### Reproduction

Complete minimal reproduction in github repo:
https://github.com/chanon/vitest-uws/

The test code in `tests/minimal.test.ts`:
```
import { test } from "vitest"
import { App } from 'uWebSockets.js'

test("test it", async () => {
	try {
		console.log('before App()')
		// try commenting out the App() call
		App()
		console.log('after App()')
	}
	catch (e) {
		console.log(e)
	}
})
```

Run 
```
pnpm install
pnpm vitest
```

Result:

![image](https://github.com/chanon/vitest-uws/assets/357737/d31ac65f-367d-4059-93f6-eed65266dc9a)

Comment `App()` call and run again.

Result:

![image](https://github.com/chanon/vitest-uws/assets/357737/b4f83297-e2fd-40b6-976f-488544185cb9)

### System Info

```shell
(Relevant info:)

 System:
    OS: Windows 10 
  Binaries:
    Node: 20.9.0
    pnpm: 9.0.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Tested this on Github Codespaces and it works fine there. Does `vitest --pool=forks` make this work better on Windows?

**Comment by chanon** [comment]
Aha! yes. That works. I somehow missed that in the docs.

**Comment by AriPerkkio** [comment]
The `uWebSockets.js` seems to be native node addon. Those have some compatibility issues with Vitest's default pool. In the next major we'll be defaulting to `pool: 'forks'` so that this kind of issues would not come up: https://github.com/vitest-dev/vitest/pull/5047
