### ISSUE TITLE
Sort file alphabetically with vitest --ui

### ISSUE THREAD

**Issue by zeid0ne** [vitest-dev/vitest#5585]
### Clear and concise description of the problem

When i run my test with vitest --ui, they are all displayed in a random order.

![image](https://github.com/vitest-dev/vitest/assets/38461940/8aa0ad79-776e-4116-b459-c742e0adf2f5)

Sometime i want to re run the tests for one file, but if i have a large number of them, it's long to find the line corresponding to the file. If they were sorted alphabetically, i'll could do it faster. I thinks it's also more "beautifull".

### Suggested solution

Sort the files alphabetically.

### Alternative

Specify file order manually.

### Additional context

https://github.com/vitest-dev/vitest/discussions/5583

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
Fixed by https://github.com/vitest-dev/vitest/pull/5652
