### ISSUE TITLE
Add timeout argument to CLI

### ISSUE THREAD

**Issue by cjoecker** [vitest-dev/vitest#5586]
### Clear and concise description of the problem

When I'm debugging, I use the CLI to run the tests. 
If I have a stop point I'm analyzing and I continue to the next line, the test throws a timeout error. This is because debugging takes me longer than the default 5s timeout. 

### Suggested solution

I would like to have a `--timeout` argument in the CLI to temporarily increase all the default timeouts of my tests.

### Alternative

An `env` variable like `VITEST_TIMEOUT` would be also a good option for debugging.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
It's already exposed https://vitest.dev/config/#testtimeout

**Comment by cjoecker** [comment]
@sheremet-va thanks for the fast answer.

I would then add it to the [CLI docs](https://vitest.dev/guide/cli#options) since I didn't find it there.

**Comment by sheremet-va** [comment]
> @sheremet-va thanks for the fast answer.
> 
> I would then add it to the [CLI docs](https://vitest.dev/guide/cli#options) since I didn't find it there.

Fixed by #5588
