### ISSUE TITLE
Allow coverage report to be done on all project files

### ISSUE THREAD

**Issue by Xa3lis** [vitest-dev/vitest#559]
### Clear and concise description of the problem

For now the --coverage only cover file that are currently tested, giving wrong coverage since when only one file is fully tested it give us a 100% coverage when 99% of the project files remain untested

### Suggested solution

implementation of the `--all` from c8 could be great

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Demivan** [comment]
You can already pass options to c8. This is my config for example.
```js
test: {
  environment: 'jsdom',
  coverage: {
    include: '*/src/**/*.js',
    all: true
  }
}
```

**Comment by Xa3lis** [comment]
Property `all` is not defined in the `C8Options` typescript interface

**Comment by Demivan** [comment]
It should still work. Will fix type error in a moment

**Comment by Xa3lis** [comment]
Dirty fixed for now be doing 

```js
coverage: {
      include: ['src/**/*.{ts,vue}'],
      all: true,
    } as any
```
