### ISSUE TITLE
Multiple async beforeEach hooks registered at the same scope aren't run serially

### ISSUE THREAD

**Issue by its-lee** [vitest-dev/vitest#5599]
### Describe the bug

(Jump to the reproduction for more clarity than here!)

There's no documentation on the order of `beforeEach` execution though there it is implicit from the Jest docs on which vitest is based (https://jestjs.io/docs/setup-teardown). Even with async callbacks, `beforeEach` hooks at the global level are run to completion before those in relevant `describe` blocks are. However it's a different story with multiple `beforeEach` hooks registered at the same scope:

---

#### With synchronous hooks at the same scope:

```ts
beforeEach(() => console.log('first'));

beforeEach(() => console.log('second'));
```

In this situation the callbacks run in the expected order, emitting 'first' and then 'second'.

---

#### With async hooks at the same scope:

```ts
beforeEach(async () => {
  console.log('Starting first global beforeEach');
  await new Promise((r) => setTimeout(r, 1000));
  console.log('Ended first global beforeEach');
});

beforeEach(async () => {
  console.log('Starting second global beforeEach');
  await new Promise((r) => setTimeout(r, 1000));
  console.log('Ended second global beforeEach');
});
```

In this case you get the following output:
```
Starting first global beforeEach
Starting second global beforeEach
Ended first global beforeEach
Ended second global beforeEach
```

Indicative of the first callback not being awaited on until completion before the second is started.

If this block were in the describe callback, it would not be run until after the first Promise above completes.

There's an argument that multiple beforeEach hooks registered at the same scope (e.g. globally or within the same describe callback) should be run serially - i.e. awaiting the completion of the first before running the second. I'd argue that this would be implicit in using `await` in the first beforeEach hook as you're indicating that there's logic which should be awaited upon before the hook completes. If you didn't want it to block later code, you could avoid using `await` and chaining off it differently if needed.

---

#### Why would this be valuable to resolve?

Either resolving by documenting so people don't architect their tests based on a faulty assumption that these hooks aren't run serially as they would be if moved into describe blocks or not having to.

**Multiple async beforeEach hooks registered at the same scope aren't run serially - but they would be if they were moved into `describe` blocks - so that's the justification for the bug being unintuitive.**

The inciting issue that led me to find this issue was: 
- a global `beforeEach` hook registered in my setup file which ensured some directories were deleted using rm from `node:fs/promises`
- a global `beforeEach` hook in a spec file which created a file in one of those directories using writeFile from `node:fs/promises`

Around 1/10 times locally I'd get test errors as the deletion would happen *after* the file creation due to the lack of synchronisation even though the `beforeEach` hooks are being registered in the correct order. To work around it I had to use sync versions of `node:fs` functions (e.g. rmSync).

---

#### Wrap up (as there's a lot above!)

So essentially I'm asking if this is expected behaviour (and if so can it be clearly documented so it can be relied upon), or is it a bug (and if so can we address it.. and again document it so it can be relied upon!)

PS: The same issue is likely true with other lifecycle hooks, e.g. `afterAll`.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-hd217x?file=test%2Fbasic.test.ts

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 46.30 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    pnpm: 8.9.2 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 124.0.6367.62
    Safari: 17.2.1
  npmPackages:
    @vitest/coverage-v8: ^1.5.0 => 1.5.0 
    vitest: ^1.5.0 => 1.5.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> There's no documentation on the order of `beforeEach` execution though there it is implicit from the Jest docs on which vitest is based

There is a documentation mentioning the difference: https://vitest.dev/guide/migration.html#hooks

> In Jest hooks are called sequentially (one after another). By default, Vitest runs hooks in parallel. To use Jest's behavior, update [sequence.hooks](https://vitest.dev/config/#sequence-hooks) option:

```ts
export default defineConfig({
  test: {
    sequence: { 
      hooks: 'list', 
    } 
  }
})
```

**Comment by its-lee** [comment]
Heyyy thank you - great answer!
