### ISSUE TITLE
Use unique package names for workspaces

### ISSUE THREAD

**Issue by fdc-viktor-luft** [vitest-dev/vitest#5607]
### Clear and concise description of the problem

I set up a workspace with roughly 50 workspace packages, but I could not run all tests of the workspace because I ran into the following issue:

```
Error: Project name "client" is not unique. All projects in a workspace should have unique names.
```

A big project benefits from having similar structures in different parts of a big monorepo. So it is not surprising that packages with similar purpose end up having the same directory names.

### Suggested solution

Why not following rather the same uniqueness restrictions that already exist for package managers and hence will guarantee unique names?

The vitest workspace should identify workspace packages by the "name" property of the `package.json`.

Additionally: This will also reduce e.g. the nesting level seen in vitest VSCode plugin in the "Testing" panel.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
You can add a name property to the config. I don't know if we can use `package.json` to get the name since workspace file supports any folder, not just packages.

**Comment by fdc-viktor-luft** [comment]
Ohh. Thank you. Didn't know that. I would have liked this to be the default, but with that info I can work around my issue.

Feel free to close the issue, if there are good reasons to prefer the dir names instead of the package names.
