### ISSUE TITLE
Regression in v1.5.1: TypeError: Invalid value used as weak map key

### ISSUE THREAD

**Issue by ddolcimascolo** [vitest-dev/vitest#5613]
### Describe the bug

Lots of my tests now fail with 

```
TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at file:///data/dev/cmdb/frontend/node_modules/@vitest/expect/dist/index.js:389:24
    at Array.every (<anonymous>)
    at file:///data/dev/cmdb/frontend/node_modules/@vitest/expect/dist/index.js:384:33
    at Object.subsetEquality (file:///data/dev/cmdb/frontend/node_modules/@vitest/expect/dist/index.js:399:37)
    at eq (file:///data/dev/cmdb/frontend/node_modules/@vitest/expect/dist/index.js:166:49)
    at equals (file:///data/dev/cmdb/frontend/node_modules/@vitest/expect/dist/index.js:129:10)
    at Proxy.<anonymous> (file:///data/dev/cmdb/frontend/node_modules/@vitest/expect/dist/index.js:931:18)
    at Proxy.<anonymous> (file:///data/dev/cmdb/frontend/node_modules/@vitest/expect/dist/index.js:797:17)
    at Proxy.methodWrapper (/data/dev/cmdb/frontend/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
```

### Reproduction

Not entirely sure, but I suspect a `toMatchObject` with an object with null keys. Like in `expect(x).toMatchObject({ aNullKey: null })`

### System Info

```shell
System:
    OS: Linux 6.5 Linux Mint 21.3 (Virginia)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 2.26 GB / 15.34 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 8.12.1 - ~/.nvm/versions/node/v20.9.0/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.60
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ruicsh** [comment]
yes, reproducible with objects with `null` values:

`expect(actual).toMatchObject({ foo: null })`

it works with 1.5.0, breaks with 1.5.1

**Comment by sheremet-va** [comment]
Fixed in https://github.com/vitest-dev/vitest/commit/ce368457236cdf35ac152e078e88907fa990a0f4

**Comment by ddolcimascolo** [comment]
Thx for fixing @sheremet-va. Will you release a new version soon, or deprecate v1.5.1? The problem seems quite severe to me...
