### ISSUE TITLE
1.5.1 TypeError: WeakMap key null must be an object or an unregistered symbol

### ISSUE THREAD

**Issue by pheidt** [vitest-dev/vitest#5617]
### Describe the bug

In version 1.5.1, passing an object with `null` or `undefined` properties to `toMatchObjectContaining` causes a type error. The same code works as expected in version 1.5.0.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-atxdxf?file=test%2Fbasic.test.ts

```
test('breaks in 1.5.1', () => {
  expect({ a: null, b: 'b' }).toMatchObject({ a: null });
});

test('still works in 1.5.1', () => {
  expect({ a: null, b: 'b' }).toEqual(expect.objectContaining({ a: null }));
});
```

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 311.91 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.12.2/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 8.10.0 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
    bun: 1.0.29 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 124.1.65.114
    Chrome: 124.0.6367.80
    Edge: 124.0.2478.51
    Safari: 17.4.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Thanks for the report. The fix has been already merged but not released yet https://github.com/vitest-dev/vitest/issues/5613
