### ISSUE TITLE
Link to "React Testing with MSW" is broken

### ISSUE THREAD

**Issue by EstebanBorai** [vitest-dev/vitest#562]
### Describe the bug

The [following documentation](https://vitest.dev/guide/mocking.html#example-3) on using Mock Service Worker with Vitest contains a broken link to an example.
The link points to: https://github.com/vitest-dev/vitest/tree/main/test/react-testing-lib-msw.

### Reproduction

Visit https://vitest.dev/guide/mocking.html#example-3 and try to open the link to the React Example.

### System Info

```shell
N/A
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by patak-dev** [comment]
The link should be https://github.com/vitest-dev/vitest/tree/main/examples/react-testing-lib-msw, would you like to send a PR to fix this?

**Comment by Demivan** [comment]
I checked it and it is fixed in main. But looks like it is not deployed.

**Comment by NaincyKumariKnoldus** [comment]
Hey @patak-dev and @EstebanBorai I would like to do this. Can I Please?

**Comment by patak-dev** [comment]
@NaincyKumariKnoldus seems it is fixed already but not deployed, I'll publish now 👍🏼
