### ISSUE TITLE
Object Properties are ignored in expect when there is a Symbol.iterator

### ISSUE THREAD

**Issue by mikearnaldi** [vitest-dev/vitest#5620]
### Describe the bug

When there is a `Symbol.iterator` inside an object vitest fails to check for other properties

### Reproduction

The following test should fail:

```ts
import { describe, expect, it } from "vitest"

describe("Vitest Issue", () => {
  it("compares", () => {
    const a = {
      value: 0,
      [Symbol.iterator]: [0, 1, 2][Symbol.iterator]
    }
    const b = {
      value: 1,
      [Symbol.iterator]: [0, 1, 2][Symbol.iterator]
    }
    expect(a).toStrictEqual(b)
  })
})
```

### System Info

```shell
independent from system
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mikearnaldi** [comment]
Note that also the iterator is ignored, the following keeps passing:

```ts
import { describe, expect, it } from "vitest"

describe("Vitest Issue", () => {
  it("compares", () => {
    const a = {
      value: 0,
      [Symbol.iterator]: [0, 1, 2, Math.random()][Symbol.iterator]
    }
    const b = {
      value: 1,
      [Symbol.iterator]: [0, 1, 2, Math.random()][Symbol.iterator]
    }
    expect(a).toStrictEqual(b)
  })
})
```

**Comment by sheremet-va** [comment]
Looks like this was fixed in Jest after we migrated the equality check: https://github.com/jestjs/jest/pull/8359

**Comment by hi-ogawa** [comment]
> Note that also the iterator is ignored, the following keeps passing: ...

This one might be some `this/bind` issue?

```node
> x = { [Symbol.iterator]: ["a", "b"][Symbol.iterator] }
{ [Symbol(Symbol.iterator)]: [Function: values] }
> x[Symbol.iterator]().next()
{ value: undefined, done: true }

> y = { [Symbol.iterator]: () => ["a", "b"][Symbol.iterator]() }
{ [Symbol(Symbol.iterator)]: [Function: [Symbol.iterator]] }
> y[Symbol.iterator]().next()
{ value: 'a', done: false }
```

**Comment by hi-ogawa** [comment]
Closed by https://github.com/vitest-dev/vitest/pull/5621

**Comment by sheremet-va** [comment]
The fix should be in https://github.com/vitest-dev/vitest/releases/tag/v1.5.3

I checked and `effect` repo is [now failing](https://github.com/vitest-dev/vitest-ecosystem-ci/actions/runs/8891542131/job/24413717932) - are these errors expected?
