### ISSUE TITLE
TypeError: Cannot redefine property after upgrading to v1.5.0

### ISSUE THREAD

**Issue by testrobpoc** [vitest-dev/vitest#5625]
### Describe the bug

Hello, I'm facing an issue when I tried to upgrade vitest version from `1.4.0` to `1.5.0`. No code was changed, and now on `v1.5.0` I'm getting `TypeError: Cannot redefine property:` error on some of my unit tests.

![Screenshot 2024-04-26 at 11 57 11](https://github.com/vitest-dev/vitest/assets/43346644/982af950-fee7-4a1f-92d6-9be3a4b32ef8)

It works fine on `v1.4.0`
It dosn't work on `v1.5.0`, `v1.5.1`, `v1.5.2`

### Reproduction

https://stackblitz.com/edit/vitejs-vite-pq9gts?file=package.json,src%2Fapp%2FAuthGuard.tsx,src%2Fapp%2FAuthGuard.test.tsx

NOTE: if you downgrade vitest to `v.1.4.0` it should work fine.

### System Info

```shell
"@vitest/ui": "1.5.0",
"vitest": "1.5.0",
"react": "^18.2.0",
"react-dom": "^18.2.0"

Node version: v20.11.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This happens because `react-oidc-context` is now imported as an ES module which doesn't support spying. You need to add it to `server.deps.inline` for Vitest to patch the module:

```ts
export default defineConfig({
  test: {
    server: {
      deps: {
        inline: ['react-oidc-context']
      }
    }
  }
})
```

**Comment by testrobpoc** [comment]
Amazing, thank you @sheremet-va all good  now!
