### ISSUE TITLE
Function calls that doesn't match signatures result in test success

### ISSUE THREAD

**Issue by treeindev** [vitest-dev/vitest#5628]
### Describe the bug

I have noticed that writing a test case which contains a call to a method or function with invalid parameters, does not result in a test failure. Consider the following example using Typescript:

```
// test.test.ts
import { test, expect, vi } from "vitest";

const function2 = vi.fn((a, b) => {})
const function1 = (param1: number, param2: number) => {
  function2(param1, param2);
  return "done";
}

test("That calls that don't match signatures are detected.", () => {
  const result = function1();
  
  expect(result).toBe("done");
  expect(function2).toHaveBeenCalledOnce();
});
```
![example2](https://github.com/vitest-dev/vitest/assets/20767411/a48ff4dc-49dd-4d40-82fd-52c762902fa8)

In this scenario, `function1()` requires two parameter of type number that will be sent over to `function2()`. As its internal logic does directly interact with the parameters, no exceptions are thrown during executor. So both `expect` are a success and the test case passes.

I understand in plain JS, `function1` would receive both parameters as undefined. But this being a TypeScript file, wouldn't the internal test compiler throw an error that result in a test failure? 

The error is indeed highlighted is you use an IDE that supports TS checks:

![example](https://github.com/vitest-dev/vitest/assets/20767411/894a7fe8-5327-41f9-a22f-badb1c688006)

IMO the use of an invalid method signature should not result in a valid test case.

### Reproduction

See description above with example.

### System Info

```shell
Using vitest 1.2.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
How would you detect function arguments in Javascript?

I would recommend to use `toHaveBeenCalledWith` in addition here. Or even combine them into `toHaveBeenNthCalledWith(1, ...)`.

**Comment by treeindev** [comment]
@AriPerkkio I think the argument detection should happen when the TypeScript code gets transpiled to JS. In this scenario, if a `.ts` file contains any invalid syntax the whole test suit described on that file could be marked as failure.

I agree with you that using `toHaveBeenCalledWith` and `toHaveBeenNthCalledWith` can be used for the case of my example. But the issue I mentioned can be reproduced, i.e., while creating a new class instance and not sending the correct parameters to the constructor.

**Comment by AriPerkkio** [comment]
Vite doesn't do Typechecking. It uses ESBuild which simply strips out the types. 

Sounds like you would want to run `tsc` against the test files.

**Comment by treeindev** [comment]
@AriPerkkio If it's expected for Vite not to check types, then this issue can be closed.
Thanks for your replies!
