### ISSUE TITLE
Exclude {test,spec}-d files from coverage by default

### ISSUE THREAD

**Issue by sagargurtu** [vitest-dev/vitest#5630]
### Clear and concise description of the problem

https://stackblitz.com/edit/vitest-dev-vitest-rrhq6a

Currently, {test,spec}-d files need to be manually added to `coverage.exclude`.

### Suggested solution

Regular test files are excluded from coverage by default. Similarly, it will be helpful to add {test,spec}-d file pattern to `coverageConfigDefaults.exclude`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by opiredev** [comment]
@nabby27 created a $50.00 using [Opire](https://opire.dev) 
 <details><summary>How to earn this reward?</summary>

Since this project does not have Opire bot installed yet 😞 you need to go to [Opire](https://app.opire.dev) and claim the rewards through your programmer's dashboard once you have your PR ready 💪</details>

**Comment by MindfulPol** [comment]
👋🏿 Hi @sagargurtu,

I've modified an existing glob pattern to additionally take into account the ''-d'' flag. Let me know if that's fine. 👍🏿  
Btw, found this through Opire. Cool software 😄

**Comment by opiredev** [comment]
🔥 The user @MindfulPol has claimed all rewards for this issue using [Opire](https://opire.dev).
🎯 You can see the PR [here](https://github.com/vitest-dev/vitest/pull/5634)
💰 @nabby27 you can pay the related rewards [here](https://app.opire.dev/dashboard/creator/rewards?platform=GitHub&platformId=2266867161)

**Comment by opiredev** [comment]
🥳 @nabby27 completed the payment of $50.00 in rewards for this issue 💰
The rewarded user is @MindfulPol - congratulations and thanks for your effort! 🎉
