### ISSUE TITLE
Mocking dependencies of pnpm monorepo packages doesn't work as expected

### ISSUE THREAD

**Issue by ffilipovicc98** [vitest-dev/vitest#5633]
### Describe the bug

I'm encountering an issue with mocking dependencies in a pnpm monorepo setup. Specifically, I'm attempting to mock the `writeContract` function from the `wagmi/actions` package in order to test the `approve` function. These tests are running within the app workspace.

Directory structure preview:
```
monorepo
└── apps/
    └── test-app/
└── packages/
    ├── business-logic/
    └── wallet-conection/
```

When I implement the `approve` function within the `app` workspace itself and write tests for it, mocking `wagmi/actions` works as expected (`apps/test-app/src/service/approve.test.ts`). However, when I attempt to move the implementation of the `approve` function to the `business-logic` package within the monorepo, the mocks fail and the tests break (`apps/test-app/src/service/external-approve.test.ts`).

This issue seems to persist regardless of which package I attempt to mock, such as `axios`. To help diagnose the problem, I've prepared a minimal reproduction scenario on StackBlitz. I've thoroughly investigated potential configuration options but haven't been able to find a solution on my own.

I'd greatly appreciate any assistance or guidance on how to resolve this issue. Thank you!

### Reproduction

Stackblitz: https://stackblitz.com/~/github.com/ffilipovicc98/vitest-issue-with-mocks-in-monorepo

Github repo: https://github.com/ffilipovicc98/vitest-issue-with-mocks-in-monorepo

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 88.14 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 21.6.1 - ~/.nvm/versions/node/v21.6.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.1/bin/npm
    pnpm: 8.9.0 - ~/.nvm/versions/node/v21.6.1/bin/pnpm
  Browsers:
    Chrome: 124.0.6367.92
    Safari: 15.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
It looks like this is due to a dual package of `wagmi/actions`, so your `test-app` and `business-logic` are importing different `wagmi` packages.

One thing I verified is that adding `resolve.dedupe` seems to help:
https://stackblitz.com/edit/github-eu6282?file=apps%2Ftest-app%2Fvite.config.ts

```ts
export default defineConfig({
  resolve: {
    dedupe: ['wagmi', 'wagmi/chains', 'wagmi/actions', 'wagmi/connectors'],
  },
})
```

Probably this is due to some intricate pnpm (peer dep?)  resolution difference. I'm not sure if this is something pnpm should deal with better or your `package.json` is not constraining dependencies properly.

```ts
$ ls node_modules/.pnpm | grep wagmi
@rainbow-me+rainbowkit@2.0.0_react-dom@18.2.0_react@18.2.0_viem@2.4.1_wagmi@2.6.0
wagmi@2.6.0_@tanstack+react-query@5.0.5_react-dom@18.2.0_react-i18next@13.5.0_react-native@0._edlfwmpxc7bzgch5lkqwmvdd5m
wagmi@2.6.0_@tanstack+react-query@5.0.5_react-i18next@13.5.0_react-native@0.74.0_react@18.2.0_viem@2.4.1_zod@3.23.4
wagmi@2.6.0_@tanstack+react-query@5.0.5_@types+react@18.3.1_react-dom@18.2.0_react-i18next@13_mo3joycr3hzwa34i3w7spnsol4
@wagmi+cli@2.1.4_typescript@5.3.3
@wagmi+connectors@4.2.0_@types+react@18.3.1_@wagmi+core@2.7.0_react-dom@18.2.0_react-i18next@_53ntc43pgeagayvf5lgyrm6qau
@wagmi+connectors@4.2.0_@wagmi+core@2.7.0_react-dom@18.2.0_react-i18next@13.5.0_react-native@_ziihsyxwsv5dgpqz566z7hsjre
@wagmi+connectors@4.2.0_@wagmi+core@2.7.0_react-i18next@13.5.0_react-native@0.74.0_react@18.2.0_viem@2.4.1_zod@3.23.4
@wagmi+core@2.7.0_react@18.2.0_typescript@5.3.3_viem@2.4.1_zod@3.23.4
@wagmi+core@2.7.0_@types+react@18.3.1_react@18.2.0_typescript@5.3.3_viem@2.4.1
```

To see how they are resolved, I ran `VITE_NODE_DEBUG_DUMP=1 pnpm -C apps/test-app test external` and this is what I saw in `.vite-node/dump`:

```ts
// /home/hiroshi/code/tmp/vitest-issue-with-mocks-in-monorepo/apps/test-app/src/service/external-approve.test.ts
...
const __vi_import_0__ = await __vite_ssr_dynamic_import__("/@fs/home/hiroshi/code/tmp/vitest-issue-with-mocks-in-monorepo/node_modules/.pnpm/wagmi@2.6.0_@tanstack+react-query@5.0.5_@types+react@18.3.1_react-dom@18.2.0_react-i18next@13_mo3joycr3hzwa34i3w7spnsol4/node_modules/wagmi/dist/esm/exports/actions.js")
```

```ts
// /home/hiroshi/code/tmp/vitest-issue-with-mocks-in-monorepo/packages/business-logic/src/service/approve/approve.ts
const __vite_ssr_import_0__ = await __vite_ssr_import__("/@fs/home/hiroshi/code/tmp/vitest-issue-with-mocks-in-monorepo/node_modules/.pnpm/wagmi@2.6.0_@tanstack+react-query@5.0.5_react-i18next@13.5.0_react-native@0.74.0_react@18.2.0_viem@2.4.1_zod@3.23.4/node_modules/wagmi/dist/esm/exports/actions.js", {"importedNames":["writeContract"]});
...
```

**Comment by ffilipovicc98** [comment]
@hi-ogawa Your help is much appreciated. It solved the issue I mentioned.

This makes our app safer and gives us more confidence in its accuracy. 🚀
