### ISSUE TITLE
Only setting `CI=1` prints the stdout

### ISSUE THREAD

**Issue by peterbe** [vitest-dev/vitest#5636]
### Describe the bug

Our `vitest.config.ts` looks like this:
```js
export default {
  test: {
    globalSetup: './src/tests/vitest.setup.ts',
  },
}
```
and `vitest.setup.ts` looks like this:
```js
export async function setup() {
  server = await main()
}

export async function teardown() {
  if (server) server.close()
}
```
All is well. The server is a simple Express server. The tests mostly do `await fetch('http://localhost:3000/'  + somePathToTest)`. 

The problem is that any `console.log(...)` is never seen on the command line. 

For example, one of my Express middleware handlers looks like this:
```
export default async function manifestJson(req, res) {
  console.log('HI THERE!')
  ...
```
But when I run tests, all I see is:
```
❯ vitest src/frame/tests/manifest.js

 RUN  v1.5.0 ...

app running on http://localhost:4000
 ❯ src/frame/tests/manifest.js (1)
   ❯ manifest (1)
 ✓ src/frame/tests/manifest.js (1) 603ms
   ✓ manifest (1) 603ms
     ✓ download manifest from HTML and check content 603ms

 Test Files  1 passed (1)
      Tests  1 passed (1)
   Start at  10:00:11
   Duration  9.02s (transform 681ms, setup 0ms, collect 511ms, tests 603ms, environment 0ms, prepare 127ms)

```
No mention of `HI THERE!` anywhere. 
I have two ways to "solve" this:
```diff
-  console.log('HI THERE!')
+  console.log('HI THERE!' .repeat(100))
```
and 
```diff
-❯ vitest src/frame/tests/manifest.js
+❯ CI=1 vitest src/frame/tests/manifest.js
```

I was hoping that there could be something like `--clearScreen=false` or something like that but it's not helping. 
Our reporter is whatever the default is. 

### Reproduction

- `git clone https://github.com/peterbe/vitest-ts-and-http.git`
- `cd vitest-ts-and-http`
- `git checkout show-consolelog-hidden`
- `npm install`
- `cat src/server.ts | grep console`
- `vitest --run`

### System Info

```
  System:
    OS: macOS 14.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 346.04 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.1 - ~/Library/Caches/fnm_multishells/3693_1714399508057/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.5.0 - ~/Library/Caches/fnm_multishells/3693_1714399508057/bin/npm
    pnpm: 8.6.9 - /usr/local/bin/pnpm
    bun: 1.1.3 - ~/.bun/bin/bun
    Watchman: 2024.04.08.00 - /usr/local/bin/watchman
  Browsers:
    Safari: 17.4.1
  npmPackages:
    vitest: 1.5.0 => 1.5.0
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://vitest.dev/guide/).
- [x] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Does it help if you `await` the `main()` call? 

https://github.com/peterbe/vitest-ts-and-http/blob/0a29689c5282234d4cd31b09c4f2a3eabbb5075c/src/start.ts#L2

**Comment by AriPerkkio** [comment]
Right, that wasn't on the original reproduction case I think. 

This logging happens on the main thread as it's coming from setup file. It also happens during the test run. If it was coming from the test files, Vitest would be able to intercept it and show it correctly in the logs. I'm not sure if we even can capture logs that are coming outside test files. 🤔 

You could use `--reporter basic` here to force CI's reporter. That one doesn't clear screen during test run.

**Comment by peterbe** [comment]
Hmm.. `--reporter basic` is pretty good. It's kinda like setting `CI=1`. 

*Without*

![Vitest run](https://github.com/vitest-dev/vitest/assets/26739/5604a3fa-0231-484d-8c8f-d2d4edf081ec)

*With `--reporter basic`*



![Vitest run](https://github.com/vitest-dev/vitest/assets/26739/3866d5bd-d3bd-4242-b5c1-2227c6185f3e)

(This demonstrates the `console.log` happening within the handlers of the server started by vitest)

I guess it's not so basic after all. It's got color. It has a neat table. 

It makes me wonder, why did I not try `--reporter basic`? And why did `--clearScreen=false` not work?
Perhaps there's nothing to do here but be aware that `--reporter=basic` might be the right solution for others in the similar situation.
