### ISSUE TITLE
Document how to mock a class, an instance, a method in a class

### ISSUE THREAD

**Issue by weedySeaDragon** [vitest-dev/vitest#5638]
### Clear and concise description of the problem

The documentation explains [how to mock modules, functions, etc.,](https://vitest.dev/guide/mocking.html#) but never explains how to mock **classes** and their related entities. There are many approaches out on the web; a developer has to wade through different approaches and test each of them to determine if they are correct or not.

### Suggested solution

The documentation should have verified explanations and examples for mocking:
- [ ] an entire class
- [ ] an instance of a class
- [ ] a single method from a class
- [ ] other related entities that should also be included

This will likely mean some extended discussions in order to agree on _correct_ approaches.  (And perhaps only one of many valid approaches is shown, with pointers or a brief explanation for others.)
Discussion(s) could take place in....  [the discussions ](https://github.com/vitest-dev/vitest/discussions).

Related: #4001 [Utility to auto mock class instance](https://github.com/vitest-dev/vitest/issues/4001)

I'm quite interested in this and ~~can~~ will kick-off a discussion.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Doesn't "Mock exported class implementation" on the same page you listed already cover it?

**Comment by weedySeaDragon** [comment]
I'm proposing that the _documentation_ be updated to include examples of how to mock not just an instance of a class, but a single method, or a static method, or all instances of a class, etc., to cover all of the OO/class things can be mocked.

(And sorry for the delay in responding. I appreciate that you responded quickly. :-) )
