### ISSUE TITLE
require() of ES Module not supported.

### ISSUE THREAD

**Issue by JoeBrighton** [vitest-dev/vitest#564]
### Describe the bug

![image](https://user-images.githubusercontent.com/17567353/149814163-401d3ca9-6d93-4a2a-b1f9-74827dbcf426.png)

There might be a way around this that I'm just not familiar with, but vitest appears to fail when any of your node dependencies use require, which I feel is untenable. 

### Reproduction

Importing Adaptable in any class and then running a test which tests this class.

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Xeon(R) W-10855M CPU @ 2.80GHz
    Memory: 13.22 GB / 31.71 GB
  Binaries:
    Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.71
    Edge: Spartan (44.19041.1266.0), Chromium (97.0.1072.62)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @vitejs/plugin-react-refresh: ^1.3.6 => 1.3.6
    vite: ^2.7.2 => 2.7.12
    vitest: ^0.1.18 => 0.1.18
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I am not familliar with this package. Can you give a proper reproduction?

**Comment by JoeBrighton** [comment]
Here you are: https://github.com/JoeBrighton/Vitest-Adaptable-Bug.git

**Comment by JoeBrighton** [comment]
Any update on this?

**Comment by Demivan** [comment]
I have checked is briefly. Not sure what is wrong in this particular case but `@adaptabletools/adaptable` package is just really messed up.
Both `main` and `typings` fields are incorrect in `package.json`. Library is in CommonJs format and imports from ESM package using require. https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c - here is the explanation why ESM packages cannot be required. So I can only assume there is something wrong with their build.

**Comment by sheremet-va** [comment]
> Not sure what is wrong in this particular case but `@adaptabletools/adaptable` package is just really messed up.

Yes, their `Adaptable.js` is CJS module that uses `require` to load ESM module, which is not supported by native Node.
