### ISSUE TITLE
vitest --ui fails to run on Windows 11 ARM64

### ISSUE THREAD

**Issue by fasterinnerlooper** [vitest-dev/vitest#5644]
### Describe the bug

When running the `vitest --ui` command from the command line on a Windows 11 ARM64 machine, the command fails with the following output:
```
0 pwsh> pnpm exec vitest --ui

 DEV  v0.21.1 C:/Users/shafiq.jetha/source/repos/Versaic/bVenus/Rovensys.bVenus/Rovensys.bVenus.Web/BenevityFlex
      UI started at http://localhost:51204/__vitest__/

node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn undefined\System32\WindowsPowerShell\v1.0\powershell ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn undefined\\System32\\WindowsPowerShell\\v1.0\\powershell',
  path: 'undefined\\System32\\WindowsPowerShell\\v1.0\\powershell',
  spawnargs: [
    '-NoProfile',
    '-NonInteractive',
    '–ExecutionPolicy',
    'Bypass',
    '-EncodedCommand',
    'UwB0AGEAcgB0ACAAIgBgACIAYwA6AFwAVQBzAGUAcgBzAFwAcwBoAGEAZgBpAHEALgBqAGUAdABoAGEAXAAuAHYAcwBjAG8AZABlAFwAYwBsAGkAXABzAGUAcgB2AGUAcgBzAFwAUwB0AGEAYgBsAGUALQBlADEANwAwADIANQAyAGYANwA2ADIANgA3ADgAZABlAGMANgBjAGEAMgBjAGMANgA5AGEAYgBhADEANQA3ADAANwA2ADkAYQA1AGQAMwA5AFwAcwBlAHIAdgBlAHIAXABiAGkAbgBcAGgAZQBsAHAAZQByAHMAXABiAHIAbwB3AHMAZQByAC4AYwBtAGQAYAAiACIAIAAtAEEAcgBnAHUAbQBlAG4AdABMAGkAcwB0ACAAIgBgACIAaAB0AHQAcAA6AC8ALwBsAG8AYwBhAGwAaABvAHMAdAA6ADUAMQAyADAANAAvAF8AXwB2AGkAdABlAHMAdABfAF8ALwBgACIAIgA='
  ]
}
```

### Reproduction

1. Run a machine with Windows ARM64
2. Install Vitest anywhere on the machine
3. Attempt to run `vitest --ui`
4. See the error message shown above

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (4) x64 Apple Silicon
    Memory: 1.28 GB / 7.99 GB
  Binaries:
    Node: 16.20.2 - C:\Program Files (x86)\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\nodejs\yarn.CMD
    npm: 8.19.4 - C:\Program Files (x86)\nodejs\npm.CMD
    pnpm: 8.6.11 - C:\Program Files (x86)\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (124.0.2478.51)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vitest/ui: ~0.21.1 => 0.21.1
    vite: ~2.9.14 => 2.9.14
    vitest: ~0.21.0 => 0.21.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Can you try after upgrading your dependencies to the latest?

```
  Binaries:
    Node: 16.20.2 - C:\Program Files (x86)\nodejs\node.EXE
 ...
  npmPackages:
    @vitest/ui: ~0.21.1 => 0.21.1
    vite: ~2.9.14 => 2.9.14
    vitest: ~0.21.0 => 0.21.1
```

**Comment by fasterinnerlooper** [comment]
Thanks @hi-ogawa. The issue was described and resolved in this comment: https://github.com/vitest-dev/vitest/issues/1870#issuecomment-1501140251.
I was able to follow the instructions and resolved the issue, so I'm going to close this.
Thanks again for your help.
