### ISSUE TITLE
Add a reason parameter in expect

### ISSUE THREAD

**Issue by MisterLight** [vitest-dev/vitest#5645]
### Clear and concise description of the problem

Just a little message can help to document the thing under test, thats why in some testing libraries is possible to supply a custom message for a given expectation.

Coming from Jest I was capable of doing this thanks to this library:

[jest-expect-message](https://www.npmjs.com/package/jest-expect-message)

But I think it would be great if vitest come with it natively

### Suggested solution

Using the same code from the mentioned library before:
```
test('returns 2 when adding 1 and 1', () => {
  expect(1 + 1, 'Woah this should be 2!').toBe(3);
});
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
It already has one.
