### ISSUE TITLE
Mocking changes returned promises

### ISSUE THREAD

**Issue by miguel-leon** [vitest-dev/vitest#5647]
### Describe the bug

A promise returned by a mocked function or methods, changes a returned promise.
i.e., saving the promise in a variable before returning it and then comparing it to what's returned outside the function with `===` evaluates to false.

I can't find documentation for this and it doesn't happen with jest, so I suppose it's unintended.

Code from the StackBlitz link just in case:
```typescript
class Foo {
	x?: Promise<void>;

	bar() {
		return this.x = Promise.resolve();
	}
}

Foo.prototype.bar = vi.fn(Foo.prototype.bar);


test('should work', async () => {
	const foo = new Foo();
	const y = foo.bar();
	expect(foo.x === y).toBe(true); // errors
});
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-zkjejn?file=src%2Fbasic.ts

### System Info

```shell
irrelevant
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is a documented difference from Jest: https://github.com/vitest-dev/vitest/issues/3634

I am open to discuss the change to how it works.

**Comment by miguel-leon** [comment]
Oh I couldn't find it in the [mocking](https://vitest.dev/guide/mocking.html) [docs](https://vitest.dev/api/mock). I wasn't doing a migration and didn't look there, I just mentioned Jest to constrast.
Although it took me some time to find out it was the mock changing the expected behavior of the function.
Perhaps consider adding a warning in the mocking guide?

Heeding your openness to discussion,
My use case is that If I have (due to user interaction) subsequent async calls (fetch), besides doing stuff with all awaited values, I also have to, say, update the UI **_only_** in response of the **_user's last interaction_**.
I accomplish this by saving the last promise, and **_after awaiting_**, compare the awaited promise with the last saved.
This ensures doing the work on the last interaction even if earlier promises resolve later.

I was testing this UI update and it wasn't happening due to the promises being changed by a mock.

In order for these kind of tests to work with vitest, the developer would have to carefully consider what to mock/spy, or to extract parts of the implementation returning promises into unmocked functions.

**Comment by miguel-leon** [comment]
I just read the migration guide [Accessing the Return Values of a Mocked Promise](https://vitest.dev/guide/migration.html#accessing-the-return-values-of-a-mocked-promise), but I think even after reading that I would have not been able to extrapolate that it means Vitest would change the returned promise of a mocked function.

I understand it is perhaps a rare case to check up and compare promises directly (instead of await/then), but it feels like if the framework is changing the behavior of the code, it should be very explicit about it.

Thanks for understanding.
