### ISSUE TITLE
Add "file" attribute to vitest JUnit reporter test case XML elements

### ISSUE THREAD

**Issue by blytheaw** [vitest-dev/vitest#5648]
### Clear and concise description of the problem

GitLab CI/CD pipelines allow uploading a JUnit formatted XML file as a test report, and they have a UI that displays the results. One column of this UI is populated by the "file" attribute on each "testcase" element in JUnit xml report. The vitest junit reporter is not currently populating this attribute, so this data is empty in GitLab when using vitest and the default junit reporter.

### Suggested solution

Add the  "file" attribute with the filename to testcase elements in the Junit XML report output

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
Interesting. Actually the first PR from 2 years ago has screenshots with "Filename" blank https://github.com/vitest-dev/vitest/pull/534

Looking at jest-junit's issue https://github.com/jest-community/jest-junit/issues/198, it looks like `file` is not on par with some spec and they have opt-in `addFileAttribute` flag, so we can probably do the same.
