### ISSUE TITLE
Silent option for JUnit reporter

### ISSUE THREAD

**Issue by andrii-nastenko** [vitest-dev/vitest#5657]
### Clear and concise description of the problem

When you have `silent: true` globally - it doesn't seem to have effect on JUnit reporter.
I still get console.logs in my xml reports.

### Suggested solution

Would be nice to have 'silent' option for JUnit reporter:

`['junit', {outputFile: './test-results/results.xml', silent: true}]`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
It looks like jest-junit has `includeConsoleOutput` option https://github.com/jest-community/jest-junit/?tab=readme-ov-file#configuration so we can do the same (though it's opt-in in their case).

Btw, assuming you're using Circle CI from the screenshot in the last issue https://github.com/vitest-dev/vitest/issues/5603, can you show how it looks on their UI?  I'm wondering whether the console output in junit is too bothering in general.

**Comment by andrii-nastenko** [comment]
> It looks like jest-junit has `includeConsoleOutput` option https://github.com/jest-community/jest-junit/?tab=readme-ov-file#configuration so we can do the same (though it's opt-in in their case).
> 
> Btw, assuming you're using Circle CI from the screenshot in the last issue #5603, can you show how it looks on their UI? I'm wondering whether the console output in junit is too bothering in general.

Hi. 
Thank you for fixing previous issue with serialized errors, now it works fine!

<img width="1531" alt="Screenshot 2024-05-03 at 11 02 25" src="https://github.com/vitest-dev/vitest/assets/40956346/628f310b-2d59-4645-a6d7-af925270343b">

And few examples with unwanted console.logs in JUnit report (CircleCI)

<img width="1531" alt="Screenshot 2024-05-03 at 12 03 08" src="https://github.com/vitest-dev/vitest/assets/40956346/587df9f8-dddd-482c-a2dd-3661230073a5">
<img width="1531" alt="Screenshot 2024-05-03 at 12 07 43" src="https://github.com/vitest-dev/vitest/assets/40956346/ac43a007-d2c5-429a-93b2-f0301db34554">
