### ISSUE TITLE
Type 'ExpectStatic' has no call signatures

### ISSUE THREAD

**Issue by aryzing** [vitest-dev/vitest#5670]
### Describe the bug

Tests using the global `expect` function have the following type error,

```
This expression is not callable.
  Type 'ExpectStatic' has no call signatures. ts(2349)
```

### Reproduction

Install latest version of vitest and write a test containing a call to `expect()`.

[See repro repo](https://github.com/aryzing/repro-vitest-expect).

### System Info

```shell
System:
    OS: Linux 6.5
    CPU: (8) x64 AMD
    Memory: 15 GB / 16 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.19.1 - ~/.nvm/versions/node/v18.19.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v18.19.1/bin/npm
    bun: 1.1.5 - ~/.bun/bin/bun
  npmPackages:
    vite: 5.2.11 => 5.2.11 
    vitest: 1.6.0 => 1.6.0
```

### Used Package Manager

bun

^ please add bun to this section of the issue template, I had to manually edit it.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aryzing** [comment]
Inside the vitest `dist` folder there's a `reporters-yx5ZTtEV.d.ts` file overriding the `@vitest/expect` module on line 2834,

``` 
declare module '@vitest/expect' {
    interface MatcherState {
        environment: VitestEnvironment;
        snapshotState: SnapshotState;
    }
    interface ExpectStatic {
        addSnapshotSerializer: (plugin: Plugin_2) => void;
    }
```

**Comment by sheremet-va** [comment]
> Other files inside dist don't have a hash/id in their name, so this one stands out -- is it meant to be there?

Yes.

**Comment by aryzing** [comment]
Added a [repro](https://github.com/aryzing/repro-vitest-expect), thanks

**Comment by sheremet-va** [comment]
I don' see any type errors in your reproduction. Try reinstalling your dependencies.

**Comment by aryzing** [comment]
Reinstalling only worked after clearing bun's cache, `bun pm cache rm`. Thanks for the suggestion!
