### ISSUE TITLE
Mock module with `import(path)` to be resistant to file renaming

### ISSUE THREAD

**Issue by zirkelc** [vitest-dev/vitest#5671]
### Clear and concise description of the problem

Traditional file imports like `import { foo } from '../bar'` or `const foo = await import('../bar')` have the advantage, that when the file `bar` is being renamed or moved to a different folder, TypeScript automatically renames the path on all import occurrences.

Mocking with `vi.mock('../bar')` doesn't get the same renaming support. When you rename/move the file `bar`, the import statements are updated but the mocks are not. That means suddenly, the tests fail and it may not be obvious why.

Here is a short video in case it's not clear:

https://github.com/vitest-dev/vitest/assets/950244/0c9cd864-ab90-4e0b-8f96-7a0f46c1ffac

Another disadvantage, although less important, is the navigation feature that editors provide for import statements. On macOS with CMD+mouse click you can easily navigate to the source file.

### Suggested solution

If it were possible to provide a dynamic import to mock like `vi.mock(import("./bar"))` so we would get the auto-renaming from TypeScript. Then, the Vitest could apply a similar logic to `vi.mock()` like it does for `vi.hoisted()`. It could rewrite all mocks to replace the `vi.mock(import("./bar"))` with the old `vi.mock("./bar")`. Maybe it is also possible to work with the Promise from `import()` directly inside `vi.mock` and it is not even necessary to rewrite all mock statements.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Interesting proposal. One of the benefits would be is typed `importOriginal`:

```ts
vi.mock(import('./mod'), (importOriginal) => {
  const mod = await importOriginal() // type of import('./mod'), right now it's "unknown"
})
```
