### ISSUE TITLE
[jsdom setup] Global APIs not matching

### ISSUE THREAD

**Issue by raulfdm** [vitest-dev/vitest#5685]
### Describe the bug

Hey folks 👋 

I recently opened an issue on JSDOM about some weird behaviour I was having while using a JWT library (jose) when implementing unit tests.

https://github.com/jsdom/jsdom/issues/3711

Long story short, when I try to run the unit tests only with the environment set to be `jsdom`, I have this:

```
TypeError: payload must be an instance of Uint8Array
 ❯ new FlattenedSign node_modules/jose/dist/node/esm/jws/flattened/sign.js:14:19
 ❯ new CompactSign node_modules/jose/dist/node/esm/jws/compact/sign.js:5:27
 ❯ SignJWT.sign node_modules/jose/dist/node/esm/jwt/sign.js:12:21
 ❯ Module.generateJWT src/generate-jwt.js:20:6
     18|     .setProtectedHeader({ alg: "RS256" })
     19|     .setExpirationTime("5m") // 5 minutes from now
     20|     .sign(privateKey);
       |      ^
     21|
     22|   return jwt;
 ❯ src/generate-jwt.test.js:13:17
 ```

Changing the environment to `happy-dom` or even `node` works without a problem.

Luckily, the JSDOM folks closed my PR because they only accept self-contained code, which forces me to get vitest away to reproduce the bug, and well... it isn't their fault. In a vanilla JSDOM environment, the problem never happens.

After some debugging, I found the issue within the vitest jsdom setup. Because of the global objects manipulation, the following condition is never met: 

```js
describe("TextEncoder return", () => {
  it("returns an Uint8Array", () => {
    const encoder = new TextEncoder();
    const encoded = encoder.encode("Hello, world!");
    expect(encoded).toBeInstanceOf(Uint8Array);
  });
});
```

And it should match. `encode` returns an `Uint8Array`.

I was able to track the problem down, and the problem is that Vitest jsdom setup is "populating" the global object with some existing APIs:

https://github.com/vitest-dev/vitest/blob/bcccce6df63b7c0408c6d14978e7cde82f1c90ca/packages/vitest/src/integrations/env/jsdom.ts#L141

One of the touched global APIs is indeed `Uint8Array`:

https://github.com/vitest-dev/vitest/blob/bcccce6df63b7c0408c6d14978e7cde82f1c90ca/packages/vitest/src/integrations/env/jsdom-keys.ts#L167

If you comment out, the assertion mentioned before will simply pass.

## Question

Now, I don't have any context as to why we need such global manipulation in JSDOM but not in happy-dom, for example. Could we, somehow, stop playing with the global APIs? What problem exactly are we trying to solve with this approach? Is this something we could align with JSDOM to not be necessary?

I'm asking this because this is a so nested side-effect that most people will have and never guess why it's failing. 

Also, for my specific setup I can't move to `happy-dom`, meaning that I cannot touch my JWT function in tests.

### Reproduction

https://github.com/devraul/vitest-jsdom-issue

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 159.20 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/Library/pnpm/node
    npm: 10.2.4 - ~/Library/pnpm/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
    bun: 1.1.6 - ~/.bun/bin/bun
    Watchman: 2024.03.25.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 124.0.6367.119
    Edge: 121.0.2277.128
    Safari: 17.4.1
  npmPackages:
    vitest: 1.6.0 => 1.6.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
The mentioned issue: https://github.com/vitest-dev/vitest/issues/4043

I already explained why this happens and why there is no solution: https://github.com/vitest-dev/vitest/issues/4043#issuecomment-1742028595

If you need fully isolated environment, you can also use `--pool=vmThreads` where only JSDOM globals exist.

**Comment by panva** [comment]
@sheremet-va given the precedent of global manipulation is present, have you tried utilizing `Symbol.hasInstance` to get the often utilized `instanceof` operands to work?
