### ISSUE TITLE
Tests start failing when upgrading from 1.5.2 to 1.5.3

### ISSUE THREAD

**Issue by osmestad** [vitest-dev/vitest#5688]
### Describe the bug

For our code base a lot of tests start failing when upgrading from 1.5.2 to 1.5.3 or 1.6.0. It seems to relate to deep object comparison where we use Immutable.js. I'm guessing, but maybe related to this change: #5621?

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-qtcox7?file=test%2Fim.test.ts

### System Info

```shell
Any? at least on Macs and Linux and Stackblitz :-)
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
I checked the repro and they have different `_tail.ownerID`, so that's now caught by https://github.com/vitest-dev/vitest/pull/5621.

Just tried a simpler repro and I got this
https://stackblitz.com/edit/vitest-dev-vitest-tybjr1?file=test%2Fim.test.ts

```ts
import { expect, test } from 'vitest';
import * as im from 'immutable';

test('repro', () => {
  const x = im.List([{ x: 1 }]);
  const y = im.List([1]).map(i => ({ x: i }));
  console.log("[x._tail]", x._tail); // [x._tail] VNode { array: [ { x: 1 } ], ownerID: undefined }
  console.log("[y._tail]", y._tail); // [y._tail] VNode { array: [ { x: 1 } ], ownerID: OwnerID {} }
  expect(x).toEqual(y);
});
```

Since message says "Compared values have no visual difference.", probably we need to do something special for immutable js for iterator checks too. Perhaps we can check how Jest is dealing with this.

**Comment by osmestad** [comment]
Thanks for the quick fix!
