### ISSUE TITLE
JUnit and tap reporter use method, that is not available in node 14

### ISSUE THREAD

**Issue by dbohn** [vitest-dev/vitest#569]
### Describe the bug

The newly introduced JUnit reporter (#534 ) uses the `String.prototype.replaceAll` method. This is only available from node 15 onwards according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll), so the vitest fails with the following exception on node 14, which is, according to the docs, a supported node version:

```
(node:69289) UnhandledPromiseRejectionWarning: TypeError: String(...).replaceAll is not a function
    at escapeXML (file:///PATH-REDACTED/node_modules/vitest/dist/create-3bc3fb6a.js:8173:24)
    at JUnitReporter.writeElement (file:///PATH-REDACTED/node_modules/vitest/dist/create-3bc3fb6a.js:8198:29)
    at JUnitReporter.<anonymous> (file:///PATH-REDACTED/node_modules/vitest/dist/create-3bc3fb6a.js:8279:20)
    at JUnitReporter.writeElement (file:///PATH-REDACTED/node_modules/vitest/dist/create-3bc3fb6a.js:8202:20)
    at async JUnitReporter.onFinished (file:///PATH-REDACTED/node_modules/vitest/dist/create-3bc3fb6a.js:8277:5)
    at async Promise.all (index 0)
    at async Vitest.report (file:///PATH-REDACTED/node_modules/vitest/dist/create-3bc3fb6a.js:8864:5)
    at async file:///PATH-REDACTED/node_modules/vitest/dist/create-3bc3fb6a.js:8724:7
    at async Vitest.runFiles (file:///PATH-REDACTED/node_modules/vitest/dist/create-3bc3fb6a.js:8728:12)
    at async Vitest.start (file:///PATH-REDACTED/node_modules/vitest/dist/create-3bc3fb6a.js:8672:5)
```

### Reproduction

Reproduction of this issue is, at least for me, not possible using StackBlitz. The terminal in the StackBlitz environment shows Node version 14.16.0, but the `replaceAll` method is still available, when I run node there, thus the reproduction is not failing there. On the other hand, when I run the same on a local node installation with the exact same node version, the method is not present, which matches the availability information for this method on MDN. So I created a dedicated [minimal reproduction repository](https://github.com/dbohn/vitest-reporter-repro)

### System Info

```shell
System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 202.82 MB / 15.26 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 96.0
  npmPackages:
    vite: ^2.7.12 => 2.7.12
    vitest: ^0.1.20 => 0.1.20
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Demivan** [comment]
My bad. Will fix in a moment.

**Comment by dbohn** [comment]
Wow, that was fast! Thank you very much :-)
