### ISSUE TITLE
Unhandled uncaught error fails test run, no stack trace present 

### ISSUE THREAD

**Issue by Kanishk-Anand** [vitest-dev/vitest#5698]
### Describe the bug

Vitest fails with a error message of `Vitest caught X unhandled errors during the test run.` but there is no meaningful error trace. Moreover, the test run failure in intermittent. It passes if the test suite is triggered multiple times. We do have error handling in most of the cases, but the chance where there isn't, Vitest should atleast be able to pinpoint to the problematic test case(s). 

Attaching the screenshot of the error. 

<img width="811" alt="Screenshot 2024-05-09 at 8 16 44 PM" src="https://github.com/vitest-dev/vitest/assets/17198067/3d0de72d-3ab7-41a7-b0f9-afb73f2f1561">

### Reproduction

There is no definitive way to reproduce the issue, since, vitest itself isn't consistent in the report. It often fails, but then succeeds when ran multiple times. It causes unnecessary dev effort to check whether there is a meaningful test failure or this "unhandled errors" getting reported. 

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 80.78 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
  Browsers:
    Brave Browser: 122.1.63.174
    Chrome: 124.0.6367.119
    Safari: 17.0
  npmPackages:
    @vitejs/plugin-react: ~4.0.0 => 4.0.4
    @vitest/coverage-v8: ^0.32.0 => 0.32.0
    @vitest/ui: ~0.32.0 => 0.32.4
    vite: ~4.3.9 => 4.3.9
    vitest: ~0.32.0 => 0.32.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Please, try the latest version first.
