### ISSUE TITLE
Missing input elements from Form event in Submit handler

### ISSUE THREAD

**Issue by ldm-acn** [vitest-dev/vitest#5699]
### Describe the bug

Testing a component that contains a form with Vitest and React Testing Library in a Next project leads to a submit event that doesn't contain the input elements that are part of the form itself.

### Reproduction

I recreated the issue with a minimal example [here](https://stackblitz.com/edit/stackblitz-starters-dklgcu?file=components%2FLogin.test.tsx)

If you try to interact with the form from the ui preview you should see the input field content be printed to the console.

If you try to run `npm run test` you'll see an error because `event.currentTarget` doesn't contain an element called "field".

### System Info

```shell
System:
  OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U
  Memory: 5.91 GB / 7.58 GB
  Container: Yes
  Shell: 5.2.15 - /bin/bash
Binaries:
  Node: 22.1.0 - /usr/local/bin/node
  npm: 10.7.0 - /usr/local/bin/npm
  pnpm: 9.1.0 - /usr/local/bin/pnpm
npmPackages:
  @vitejs/plugin-react: ^4.2.1 => 4.2.1 
  vitest: ^1.6.0 => 1.6.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
This looks like a jsdom issue since it works on happy-dom. You would probably need to report it there to see if this is supported.
https://stackblitz.com/edit/stackblitz-starters-mzb5tx?file=components%2Fhappy-dom.test.tsx

```
stdout | components/jsdom.test.tsx > repro jsdom
[handleSubmit] field.value =  undefined

stdout | components/happy-dom.test.tsx > repro happy-dom
[handleSubmit] field.value =  abc123
```

**Comment by sheremet-va** [comment]
Link to the happy-dom issue: https://github.com/jsdom/jsdom/issues/3715

Closing this as I don't see any reason to keep this open in Vitest.
