### ISSUE TITLE
Type safe assertions

### ISSUE THREAD

**Issue by krzkaczor** [vitest-dev/vitest#5702]
### Clear and concise description of the problem

Right now it's possible to construct assertions (let's say using expect api) that will always fail because they compare values of different types, yet there are not type errors.

Consider this:

```typescript
expect(123).toBe('123')
```

This is obviously a mistake that will fail in runtime but will pass happily in compile time. 

Having type safe assertions becomes very handy during refactorings when compiler can guide the developer through all required changes. Consider slightly more complex example:

```typescript
const returnValue = functionCall()
expect(returnValue).toEqual({ a: 1, b: 2 })
```

Once `functionCall` return type changes in the future, TypeScript type checker would point the developer to all assertions that need to be updated. Right now this has to be done by executing tests which results in worse DX.

In bun test runner same code will result in a type error in a compile time, clearly visible to developer.

<img width="1114" alt="image" src="https://github.com/vitest-dev/vitest/assets/1814312/bb840b26-afcf-4915-b332-55dbcf0740b1">

### Suggested solution

I propose making assertions api type safe. This can be done by parameterizing matchers by a type represented by actual value. Most likely due to various edge cases in comparison of complex TS objects that would be a breaking change.

### Additional context

In the past I created earl which takes this idea to extreme: https://github.com/l2beat/earl#example

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
Is this essentially same as https://github.com/vitest-dev/vitest/issues/2883?

**Comment by krzkaczor** [comment]
https://github.com/vitest-dev/vitest/issues/2883 is a little bit different because it's about type narrowing ie. changing a type of a variable after a given statement, in this example ensuring that something is truthy. From my experience with earl this is really hard with expect style API, on the other hand, having type-safe assertions is doable. 

In the original issue I mention only `toBe` and `toEqual` cases but you can imagine this working for all different matchers.

```typescript
expect(false).toBeTruthy(); // type error because false is can never be truthy
```

**Comment by AriPerkkio** [comment]
While this could definitely be nice in some cases, it could also make tests hard to work on. Discussion from earlier mentioned Bun: https://github.com/oven-sh/bun/issues/6934

This could likely be solved by third party package that overwrites the typings to more strict ones. Making the built-in default ones strict would break Jest compatibility as well.

**Comment by sheremet-va** [comment]
The team doesn't think this is something that we want to pursue in the Vitest core due to the edge case that will be introduced with this change (see https://github.com/oven-sh/bun/issues/6934).

`expect` types are also provided in a way when it is currently impossible to implement type assertions because the argument is in another function. Having a helper `expectToBeDefined` is a valid user-land solution.
