### ISSUE TITLE
Text reporter still creates an empty coverage folder

### ISSUE THREAD

**Issue by xixixao** [vitest-dev/vitest#5722]
### Describe the bug

Run
```sh
npx vitest run --coverage --coverage.reporter=text
```
You will get an empty `coverage` folder

### Reproduction

1. Use the default playground: https://stackblitz.com/fork/github/vitest-dev/vitest/tree/main/examples/basic?initialPath=__vitest__/
2. Quit the watcher
3. Run the command
4. Observer the folder

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/coverage-v8: ^1.6.0 => 1.6.0 
    @vitest/ui: latest => 1.6.0 
    vite: latest => 5.2.11 
    vitest: latest => 1.6.0 

(it reproes on my mac too)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
During test run Vitest needs to create `coverage/.tmp` where raw coverage results from tests are stored. After the coverage report has been generated it removes the `.tmp` directory.

I think we could check if `coverage` directory is completely empty after that, and then delete that one as well.

**Comment by xixixao** [comment]
That's a good solution. It might be even better to store the .tmp in node_modules so the `coverage` folder doesn't pop into and out of existence in people's editors.

**Comment by AriPerkkio** [comment]
I think we would like to keep these results close to coverage report directory so using `node_modules` by default might not work. 

Though that's already possible from userland with `npx vitest run --coverage --coverage.reporter=text --coverage.reportsDirectory=node_modules/.vitest-coverage` for example.
