### ISSUE TITLE
get error "Could not parse CSS stylesheet" when CSS file contains nested rules

### ISSUE THREAD

**Issue by mvolkmann** [vitest-dev/vitest#5738]
### Describe the bug

When testing a component that imports a CSS file that contains nested CSS rules, I get the error "Could not parse CSS stylesheet". Support for nested CSS rules is fairly new, so maybe the parser that vitest uses to parse CSS just doesn't support nested rules yet.

### Reproduction

Here is a simple example of CSS that will trigger this error:

```css
.foo {
  .bar {
    color: red;
  }
}
```

### System Info

```shell
System:
    OS: macOS 14.2
    CPU: (10) x64 Apple M1 Pro
    Memory: 47.48 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.1 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 7.30.1 - /opt/homebrew/bin/pnpm
    bun: 1.1.6 - ~/.bun/bin/bun
    Watchman: 2024.01.22.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 124.0.6367.208
    Edge: 118.0.2088.46
    Safari: 17.2
    Safari Technology Preview: 17.4
  npmPackages:
    @vitejs/plugin-react-swc: ^3.6.0 => 3.6.0
    @vitest/coverage-v8: ^1.4.0 => 1.5.1
    vite: ^5.2.6 => 5.2.10
    vitest: ^1.4.0 => 1.5.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Not sure if I missed something, but I couldn't reproduce https://stackblitz.com/edit/vitest-dev-vitest-mdakvj?file=test%2Frepro.css

Can you provide a runnable example?
