### ISSUE TITLE
restoreAllMocks doesn't restore mocks

### ISSUE THREAD

**Issue by fritz-trawa** [vitest-dev/vitest#5748]
### Describe the bug

I have a suite with two tests, and I setup a different mock a function before each run. I expect the previous mock to be replaced. When I comment out the other test and I run only one, it works. But when I run both, the mock leak from one test to the next. How am I supposed to do it? Thanks

### Reproduction

```
// /cdk-config.js
export const fetchCdkConfig = async (): Promise<CdkConfig> => {
  const params = await configClient.getFromSsm('cdk');

  return envSchema.parse(params);
};

export const envSchema = z
  .object({
    STAGE_NAME: z.enum(['staging', 'production']),
    // etc
  })
```

```
// test file
import { generateMock } from '@anatine/zod-mock';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { envSchema, fetchCdkConfig } from './cdk-config.js';

describe('cdk-config', () => {
  describe('fetchCdkConfig', async () => {
    afterEach(() => {
      vi.restoreAllMocks(); // <- reset all mocks
    });


    // on its own, it works
    it('returns a valid envSchema object', async () => {
      vi.mock('./config-client.js', () => {
        const ConfigClient = vi.fn();
        ConfigClient.prototype.getFromSsm = vi.fn(() =>
          generateMock(envSchema)
        );
        return { ConfigClient };
      });

      const actual = await fetchCdkConfig();
      expect(envSchema.safeParse(actual).success).toBe(true);
      vi.restoreAllMocks();
    });

    // on its own, it works
    it('breaks if it gets an invalid envSchema object', async () => {
      vi.mock('./config-client.js', () => {
        const ConfigClient = vi.fn();
        ConfigClient.prototype.getFromSsm = vi.fn(() => {
          return { name: 'home', catchphrase: 'doh' };
        });
        return { ConfigClient };
      });

      const sut = async () => await fetchCdkConfig();
      expect(sut).rejects.toThrow();
      vi.restoreAllMocks();
    });
  });
});
```

### System Info

```shell
vitest/1.6.0 darwin-arm64 node-v20.12.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`vi.mock` is hoisted, so your code is only actually called once. Please refer to the documentation: https://vitest.dev/api/vi.html#vi-mock

**Comment by sheremet-va** [comment]
Inconveniently named `restoreAllMocks` is not related to `vi.mock`, so it doesn't mention the `vi.mock` behaviour in the documentation.

> So is there no way to have different mocks for different test / suites?

There are several ways you can achieve it. `vi.mock` is called only once, but you can setup a hoisted spy that can be changed in different tests: 

```ts
import { envSchema, fetchCdkConfig } from './cdk-config.js'

const getFromSsm = vi.hoisted(() => vi.fn())

vi.mock('./config-client.js', () => {
  const ConfigClient = vi.fn();
  ConfigClient.prototype.getFromSsm = getFromSsm
  return { ConfigClient };
})

test('returns a valid envSchema object', () => {
  getFromSssm.mockReturnValue(generateMock(envSchema))
  const actual = await fetchCdkConfig();
  expect(envSchema.safeParse(actual).success).toBe(true);
})

test('breaks if it gets an invalid envSchema object', async () => {
  getFromSssm.mockReturnValue({ name: 'home', catchphrase: 'doh' })
  const sut = async () => await fetchCdkConfig();
  await expect(sut).rejects.toThrow(); // make sure you await it
})
```

You can also just spy on methods without mocking the class:

```ts
import { envSchema, fetchCdkConfig } from './cdk-config.js'
import { ConfigClient } from './config-client.js'

const getFromSsm = vi.fn()
ConfigClient.prototype.getFromSsm = getFromSsm

// same code for tests
```

If you really want to mock several times, there is `vi.doMock` API: https://vitest.dev/api/vi.html#vi-domock
but make sure that you import from `./cdk-config.js` inside of every test again as it only mocks the _next_ import:

> The next [dynamic import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) of the module will be mocked.

**Comment by fritz-trawa** [comment]
Very helpful, thank you very much for the explanation!
