### ISSUE TITLE
There's no console.log output from 'beforeAll' and 'afterAll' when running tests via Webstorm / Aqua IDE

### ISSUE THREAD

**Issue by andrii-nastenko** [vitest-dev/vitest#5754]
### Describe the bug

There's no console.log output from 'beforeAll' and 'afterAll' hooks when running tests via Webstorm / Aqua IDE built-in interface.

### Reproduction

Use Webstorm or Aqua IDE.

Make .spec file with following structure:

```
describe('qwerty', () => {
  beforeAll(() => {
    console.log('log 1');
  });

  beforeEach(() => {
    console.log('log 2');
  });

  afterEach(() => {
    console.log('log 3');
  });

  afterAll(() => {
    console.log('log 4');
  });

  it('test console logs', () => {
    expect(1).toEqual(1);
  });
});
```

Run .spec file (whole describe block or a specific test - it doesn't matter) from built-in interface from Webstorm or Aqua and check console logs.
As a result - missing console logs from beforeAll / afterAll hooks.
<img width="634" alt="Screenshot 2024-05-20 at 14 49 59" src="https://github.com/vitest-dev/vitest/assets/40956346/2b24c8d6-69c7-4df8-80d5-0e0481ca0a52">

### System Info

```shell
macOS Sonoma 14.1.1
vitest 1.6.0 / typescript & esm (vitest.config.mts)
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
We don't control what IDEs output there, it's not Vitest CLI output
