### ISSUE TITLE
Add support for Node.js 20 `--env-file` flag

### ISSUE THREAD

**Issue by fellipeutaka** [vitest-dev/vitest#5756]
### Clear and concise description of the problem

With the release of Node.js 20 LTS, the platform now supports a native [`--env-file`](https://nodejs.org/dist/latest-v20.x/docs/api/cli.html#--env-fileconfig) flag that allows environment variables to be loaded from a file without the need for third-party packages like `dotenv` or `dotenv-cli`. This is a significant improvement for developers as it simplifies the process of managing environment variables.

However, Vitest does not currently support the [`--env-file`](https://nodejs.org/dist/latest-v20.x/docs/api/cli.html#--env-fileconfig) flag, meaning developers who upgrade to Node.js 20 cannot take advantage of this new feature when running their tests. This lack of support necessitates the continued use of third-party packages for managing environment variables, which undermines the benefits provided by the new Node.js 20 feature.

### Suggested solution

To fully leverage the capabilities of Node.js 20, it would be highly beneficial for Vitest to add support for the `--env-file` flag. Here is a proposed solution:

1. **Detection of Node.js Version:** Implement a check within Vitest to detect if the running version of Node.js is 20 or higher.
2. **Env-File Handling:** If the detected Node.js version supports the `--env-file` flag, allow users to specify an environment file directly through Vitest configuration or command-line options.
3. **Documentation Update:** Update the Vitest documentation to guide users on how to use the `--env-file` flag with Vitest when running on Node.js 20 and higher. Provide examples and best practices to facilitate easy adoption.

### Alternative

Currently, I only could use `--env-file` flag creating a file for running [`startVitest` function](https://vitest.dev/advanced/api).
```ts
// run-e2e.ts
import tsconfigPaths from "vite-tsconfig-paths";
import { startVitest } from "vitest/node";

const vitest = await startVitest(
  "test",
  [],
  {
    dir: "./src/http",
  },
  {
    plugins: [tsconfigPaths()],
  },
);

await vitest?.close();
```

```json
{
  "name": "example",
  "type": "module",
  "scripts": {
    "test:e2e": "tsx --env-file=.env run-e2e.ts"
  },
  "devDependencies": {
    "tsx": "^4.10.5",
    "typescript": "^5.4.5",
    "vite-tsconfig-paths": "^4.3.2",
    "vitest": "^1.6.0"
  }
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
> However, Vitest does not currently support the `--env-file` flag, meaning developers who upgrade to Node.js 20 cannot take advantage of this new feature when running their tests. 

If it's a Node CLI flag, it should be supported as usual. Try passing that flag to Node when running Vitest:

```diff
- tsx --env-file=.env run-e2e.ts
+ node --env-file=.env ./node_modules/vitest/vitest.mjs
```

If you wish to pass it only to test runners and not have it available in main thread (`vitest.config.ts`, global setup), pass it in configuration:

```ts
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    poolOptions: {
      threads: { execArgv: ["--env-file=.env"] },

      // Or another pool:
      forks: { execArgv: ["--env-file=.env"] },
    },
  },
});
```

**Comment by fellipeutaka** [comment]
> > However, Vitest does not currently support the `--env-file` flag, meaning developers who upgrade to Node.js 20 cannot take advantage of this new feature when running their tests.
> 
> If it's a Node CLI flag, it should be supported as usual. Try passing that flag to Node when running Vitest:
> 
> ```diff
> - tsx --env-file=.env run-e2e.ts
> + node --env-file=.env ./node_modules/vitest/vitest.mjs
> ```
> 
> If you wish to pass it only to test runners and not have it available in main thread (`vitest.config.ts`, global setup), pass it in configuration:
> 
> ```ts
> import { defineConfig } from "vitest/config";
> 
> export default defineConfig({
>   test: {
>     poolOptions: {
>       threads: { execArgv: ["--env-file=.env"] },
> 
>       // Or another pool:
>       forks: { execArgv: ["--env-file=.env"] },
>     },
>   },
> });
> ```

Thanks! I just tested, but only the first solution using `node --env-file=.env ./node_modules/vitest/vitest.mjs` worked. But I keep wondering why the Vitest CLI doesn't accept this Node.js flag if `tsx` does.

**Comment by sheremet-va** [comment]
`tsx` forwards all options to `node` because it's basically a Node wrapper. Vitest is a standalone application, so we accept only relevant options.

> This lack of support necessitates the continued use of third-party packages for managing environment variables, which undermines the benefits provided by the new Node.js 20 feature.

This is not true because you can use `loadEnv` from `vite` which always comes with Vitest: https://vitejs.dev/guide/api-javascript.html#loadenv

**Comment by fellipeutaka** [comment]
> Vitest also loads env automatically if you follow the convention: https://vitejs.dev/guide/env-and-mode.html#env-variables-and-modes

In my case, I'm creating a Fastify app, so when I try to access `import.meta.env`, I get the following error:
`Property 'env' does not exist on type 'ImportMeta'.`
Even if I declare a new global type like this:
```ts
declare global {
  interface ImportMeta {
    readonly env: z.infer<typeof envSchema>;
  }
}
```

I still can't use `import.meta.env` because it return `undefined`

**Comment by sheremet-va** [comment]
> I still can't use `import.meta.env` because it return `undefined`

Vitest supports `process.env`, it is equal to `import.meta.env` in tests

In any way, you can use `loadEnv` from `vite` already without any additional packages: https://vitejs.dev/guide/api-javascript.html#loadenv

**Comment by fellipeutaka** [comment]
> Vitest supports `process.env`, it is equal to `import.meta.env` in tests
> 
> In any way, you can use `loadEnv` from `vite` already without any additional packages: https://vitejs.dev/guide/api-javascript.html#loadenv

Great! So I'm gonna use `loadEnv` from `vite`. Thank you!
