### ISSUE TITLE
vitest fails to load typescript worker code in node (but does so correctly in browser mode)

### ISSUE THREAD

**Issue by andreashuber69** [vitest-dev/vitest#5757]
### Describe the bug

As already asked [here](https://github.com/vitest-dev/vitest/discussions/3419), I'm looking for a way to execute tests in node while using `node:worker_threads`. Equivalent code works just fine in browser mode.

### Reproduction

https://github.com/andreashuber69/vitest-repro

The following commands work as expected:

- `npm run test-browser`
- `npm run test-node-js`

The following doesn't work:

- `npm run test-node-ts`

Apparently under node, test code isn't compiled to js first (as in browser mode), which is why the above produces the following error:

`Error: Cannot find module '.../src/nodeWorker.js'`

Attempts at importing `tsx` (see commented out code in [./src/nodeWorker.spec.ts](https://github.com/andreashuber69/vitest-repro/blob/b5735bcd5de503f634302013322a05ebae8d63c4/src/nodeWorker.spec.ts#L35)) have failed with the following error:

`TypeError: Unknown file extension ".ts" for .../src/nodeWorker.ts`

(presented as a solution in [this issue](https://github.com/vitest-dev/vitest/issues/3234) but apparently doesn't work any longer)

How can I use vitest with typescript code that uses `node:worker_threads`?

### System Info

```shell
System:
    OS: Linux 6.8 Pop!_OS 22.04 LTS
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 24.06 GB / 31.20 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.12.1 - /usr/local/bin/node
    npm: 10.5.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 125.1.66.110
    Chrome: 125.0.6422.60
  npmPackages:
    @vitest/browser: ^1.5.0 => 1.5.0 
    @vitest/coverage-istanbul: ^1.5.0 => 1.5.0 
    vitest: ^1.5.0 => 1.5.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Browser mode is a totally different thing and it just happens that Vite's web worker support makes it work, but that doesn't naturally transfer to node worker threads. It's unlikely to have some magical feature on Vitest out-of-the-box as noted in https://github.com/vitest-dev/vitest/issues/3234#issuecomment-1518887878

Regarding tsx loader failing on `Worker` constructor, this seems like a well-known issue as current Node loader limitation:
- https://github.com/privatenumber/tsx/issues/354
- https://github.com/nodejs/node/issues/47747

The tsx issue suggests one workaround https://github.com/privatenumber/tsx/issues/354#issuecomment-1806081815 and that would probably work.

**Comment by sheremet-va** [comment]
The equivalent cannot work just fine in the browser mode because the browser mode doesn't support `node:worker_threads` module. 

If you are testing web worker, the recommendation is to use [@vitest/web-worker](https://www.npmjs.com/package/@vitest/web-worker) package.

**Comment by andreashuber69** [comment]
> The equivalent cannot work just fine in the browser mode because the browser mode doesn't support node:worker_threads module.

With _equivalent code_ I meant code implemented in terms of web worker, see [`test-browser`](https://github.com/andreashuber69/vitest-repro/blob/405f7da80f62999aedbf09959e1db05b544c6171/package.json#L28) script.

**Comment by andreashuber69** [comment]
For anyone landing here looking for a solution: I didn't get it to work. I tried with the following line
```
        const tsx = new URL("../node_modules/tsx/dist/cli.mjs", import.meta.url);
        const worker = new Worker(tsx, { env: SHARE_ENV, argv: ["./src/nodeWorker.ts"] });
```

Both `cli.mjs` and `nodeWorker.ts` are found, but apparently the message posted on the main thread never makes it to the worker.

**Comment by hi-ogawa** [comment]
Oh right, `tsx` probably spawns extra process in between, so Node's out-of-the-box worker communication doesn't work.

Just reading back the original Node issue https://github.com/nodejs/node/issues/47747#issuecomment-2110589610, it might be that the fix is near in Node 22, but I just double checked it still doesn't work (and it actually breaks more for some use cases).

For the workaround on Node 20, I think you can use `tsx/esm/api` like this to wrap your worker. I just tested this approach here https://github.com/hi-ogawa/reproductions/blob/main/vitest-5757-ts-worker/src/ts-worker/index.mjs


```ts
import { Worker } from "node:worker_threads";

class TsWorker extends Worker {
	constructor(filename, options = {}) {
		options.workerData ??= {};
		options.workerData.__ts_worker_filename = filename.toString();
		super(new URL("./worker.mjs", import.meta.url), options);
	}
}

const worker = new TsWorker(new URL("./nodeWorker.ts", import.meta.url));
```

```ts
// worker.mjs
import { tsImport } from "tsx/esm/api";
import { workerData } from "node:worker_threads";

tsImport(workerData.__ts_worker_filename, import.meta.url);
```

**Comment by andreashuber69** [comment]
> For the workaround on Node 20, I think you can use `tsx/esm/api` like this to wrap your worker.

Indeed, that works. I've modified the [vitest-repro](https://github.com/andreashuber69/vitest-repro) accordingly and adapted the instructions for the reproduction to check out the original code.

Thank you very much!

**Comment by daniel-nagy** [comment]
If you don't want the stain of a non-typescript file on your filesystem (or just want to avoid the extra file)

```ts
import { type WorkerOptions, Worker } from "node:worker_threads";

const worker = /* JavaScript */ `
  import { createRequire } from "node:module";
  import { workerData } from "node:worker_threads";

  const filename = "${import.meta.url}";
  const require = createRequire(filename);
  const { tsImport } = require("tsx/esm/api");
  
  tsImport(workerData.__ts_worker_filename, filename);
`;

export class TsWorker extends Worker {
  constructor(filename: string | URL, options: WorkerOptions = {}) {
    options.workerData ??= {};
    options.workerData.__ts_worker_filename = filename.toString();
    super(new URL(`data:text/javascript,${worker}`), options);
  }
}

```
