### ISSUE TITLE
Additional type definitions are ignored

### ISSUE THREAD

**Issue by voxelstack** [vitest-dev/vitest#5760]
### Describe the bug

Extra type definitions specified on `tsconfig` through `"compilerOptions": { "types": [...] }` are ignored by the type checker.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-jbppb2?file=test%2Fbasic.test.ts

### System Info

```shell
System:
    OS: Linux 6.1 SteamOS
    CPU: (8) x64 AMD Custom APU 0932
    Memory: 1.80 GB / 14.47 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 22.1.0 - ~/.nvm/versions/node/v22.1.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v22.1.0/bin/npm
    pnpm: 9.1.0 - ~/.local/share/pnpm/pnpm
  npmPackages:
    vitest: ^1.6.0 => 1.6.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Everything works correctly. `GPUShaderStage` is not implemented in Node.js or JSDom. Types are just types, they don't affect runtime, it's the other way around - they explain how the runtime works.

You can inject this value yourself in the `setupFile`:

```ts
globalThis.GPUShaderStage = {
 VERTEX: 1 
}
```

But I think if you rely on these primitives it is better to run code in the environment that supports WebGPU like the [Browser Mode](https://vitest.dev/guide/browser/).
