### ISSUE TITLE
Second (Custom Message) Argument Breaks expect().toBeVisible()

### ISSUE THREAD

**Issue by jwalkerinterpres** [vitest-dev/vitest#5761]
### Describe the bug

In normal testing libraries, it's a documented feature that you can influence the expectation failure message with a second argument, eg.

     expect('bar', 'Foo!').toEqual('foo'); // 'bar' !== 'foo' so it throws error with "Foo!" in it

In vitest, it's an undocumented "secret" feature (https://vitest.dev/api/expect.html has no mention of it):

     expect('bar', 'Foo!').toEqual('foo'); // AssertionError: Foo!: expected 'bar' to deeply equal 'foo'

However, that undocumented secret feature doesn't work with the `toBeVisible` assertion:

    expect(someEl, 'Foo!').toBeVisible(); // received value must be an HTMLElement or an SVGElement.

As you can see from the error message, the second argument is _not_ being treated as a message, but as another element to validate.  Thus, trying to provide a custom error message breaks the expectation.

Since custom messages are as useful on `toBeVisible` as they are anywhere else, it seems like `toBeVisible` should validate only the first arg (and if it really needs to take multiple elements, maybe take an array of them?).  It should then treat the second arg the same as other expectations, and include it in the message.

(And also, the second argument _really_ should be documented on https://vitest.dev/api/expect.html ... but that's a separate ticket.)

### Reproduction

     expect(someElementOrNullOrWhatever, 'Foo!').toBeVisible();

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 52.81 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.2.0 - /usr/local/bin/node
    Yarn: 1.22.21 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 125.0.6422.61
    Edge: 125.0.2535.51
    Safari: 17.5
  npmPackages:
    @vitejs/plugin-react: ^4.2.0 => 4.2.0 
    @vitest/coverage-v8: ^0.34.6 => 0.34.6 
    vite: ^5.0.3 => 5.0.3 
    vitest: ^0.34.6 => 0.34.6
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
`toBeVisible` is an assertion provided by testing-library https://github.com/testing-library/jest-dom/blob/main/src/to-be-disabled.js, so you might need to raise the issue there.

Also please provide a reproduction as I cannot tell how you actually setup testing-library. Also, you have old Vitest v0.34.6, so please check with latest version.
