### ISSUE TITLE
Missing link in Documentation mocking requests 

### ISSUE THREAD

**Issue by rcuching** [vitest-dev/vitest#5762]
### Describe the bug

https://vitest.dev/guide/mocking.html#requests

Documentation of mocking requests references an example of using recommended MSW which looks like it was removed a number of weeks ago in https://github.com/vitest-dev/vitest/commit/959247e90fe5bcfa8be781c9b9109c32404e0a2d

It looks like the justification was that react was just over represented but I wouldnt mind the example being preserved and just relocated into the react directory as additional examples. 

### Reproduction

N/A. Documentation.

### System Info

```shell
N/A. Documentation.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Fixed in https://github.com/vitest-dev/vitest/commit/ee27e4873381e96ff8a97e231c65278779b68ab3

You can find examples in MSW docs.
