### ISSUE TITLE
vi.stubEnv documentation and typing differ from each other

### ISSUE THREAD

**Issue by fvanderwielen** [vitest-dev/vitest#5763]
### Describe the bug

I hope this is the proper way to report issues with the documenation and/or typing.

The documentation of vi.stubEnv does not mention typing differences for specifically 'PROD' 'DEV' or 'SSR' vars, making this behavior/typing unexpected. 
See the actual typing from vi.stubEnv here: https://github.com/vitest-dev/vitest/blob/a4ec583191e7576b0272e5cbbea691e3cc1d2ca8/packages/vitest/src/integrations/vi.ts#L307
See the docs here: https://github.com/vitest-dev/vitest/blob/ee27e4873381e96ff8a97e231c65278779b68ab3/docs/api/vi.md?plain=1#L448

I think the docs would improve by describing this specific behavior as well.

### Reproduction

non-applicable: not a bug in the running code.

### System Info

```shell
non-applicable: not a bug in the running code.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This was fixed at some point but the issue wasn't closed: https://vitest.dev/api/vi.html#vi-stubenv
