### ISSUE TITLE
`MY_ENV=abc vitest` exposes `import.meta.env.MY_ENV === "abc"`

### ISSUE THREAD

**Issue by hi-ogawa** [vitest-dev/vitest#5764]
### Describe the bug

We discussed this shouldn't happen, but it looks like it's happening on Vitest.
Actually I'm not sure if this is really a bug or a convenient feature.

```ts
// MY_ENV=abc vitest

import { test, expect } from 'vitest';

test('import.meta.env', () => {
  expect(import.meta.env.MY_ENV).toMatchInlineSnapshot(`"abc"`);
  expect(import.meta.env.HOME).toMatchInlineSnapshot(`"/home"`);
});

test('process.env', () => {
  expect(process.env.MY_ENV).toMatchInlineSnapshot(`"abc"`);
});
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-j5abrx?file=test%2Frepro.test.ts

### System Info

```shell
(stackblitz)

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    vite: latest => 5.2.11 
    vitest: latest => 1.6.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It is fine to expose this as long as it's not loaded from a `env` file

**Comment by hi-ogawa** [comment]
Yeah, this seems alright and I think I misunderstood the issue of https://github.com/vitest-dev/vitest/issues/5624. I don't think OP is concerned with `import.meta.env` but it's about `process.env` and `.env` file. I'll follow up with the OP later.

FYI, here is an updated repro:

```ts
import { test, expect } from 'vitest';

test('import.meta.env', () => {
  expect(import.meta.env.MY_ENV).toMatchInlineSnapshot(`"abc"`);
  expect(import.meta.env.VITE_ENV).toMatchInlineSnapshot(`"yay"`);

  expect(import.meta.env.MY_DOT_ENV).toMatchInlineSnapshot(`undefined`);
  expect(import.meta.env.VITE_DOT_ENV).toMatchInlineSnapshot(`"yay"`);

  expect(import.meta.env.HOME).toMatchInlineSnapshot(`"/home"`);
});
```
