### ISSUE TITLE
Invalid coverage report for Typescript Member Visibility Keywords (V8)

### ISSUE THREAD

**Issue by kevinkasper** [vitest-dev/vitest#5774]
### Describe the bug

Typescript member visibility keywords (public, protected and private) are displayed incorrectly as covered within the coverage report.

If the async keyword is also used, the Typescript Member Visibility Keyword is also correctly displayed as uncoverd.

Below is a screenshot for the minimal reproducible example:

![image](https://github.com/vitest-dev/vitest/assets/9140462/90bd9410-fb79-4cfd-bfe1-900dd90d2c60)

Many thanks in advance!

### Reproduction

Clone minimal reproducible example:

https://github.com/kevinkasper/vitest-coverage-mre

1. `yarn install`
2. `yarn vitest --coverage --ui`
3. Open vitest UI
4. Display coverage report

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M2
    Memory: 3.75 GB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.2.0 - ~/.nvm/versions/node/v22.2.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v22.2.0/bin/npm
    bun: 1.1.9 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 125.0.6422.112
    Safari: 17.4.1
  npmPackages:
    @vitest/coverage-v8: ^1.6.0 => 1.6.0 
    @vitest/ui: ^1.6.0 => 1.6.0 
    vitest: ^1.6.0 => 1.6.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Thanks for great minimal reproduction setup. 👍 

ESBuild removes those keywords during transform: [https://esbuild.egoist.dev/#W1siaW5kZ...](https://esbuild.egoist.dev/#W1siaW5kZXgudHMiLHsiY29udGVudCI6ImV4cG9ydCBjbGFzcyBGb28ge1xuICBwdWJsaWMgcHVibGljRm9vKCk6IHZvaWQge1xuICAgIHRocm93IG5ldyBFcnJvcihcIk5vdCBpbXBsZW1lbnRlZFwiKTtcbiAgfVxuXG4gIHB1YmxpYyBhc3luYyBwdWJsaWNCYXIoKTogUHJvbWlzZTx2b2lkPiB7XG4gICAgdGhyb3cgbmV3IEVycm9yKFwiTm90IGltcGxlbWVudGVkXCIpO1xuICB9XG5cbiAgcHJvdGVjdGVkIHByb3RlY3RlZEZvbygpOiB2b2lkIHtcbiAgICB0aHJvdyBuZXcgRXJyb3IoXCJOb3QgaW1wbGVtZW50ZWRcIik7XG4gIH1cblxuICBwcm90ZWN0ZWQgYXN5bmMgcHJvdGVjdGVkQmFyKCk6IFByb21pc2U8dm9pZD4ge1xuICAgIHRocm93IG5ldyBFcnJvcihcIk5vdCBpbXBsZW1lbnRlZFwiKTtcbiAgfVxuXG4gIHByaXZhdGUgcHJpdmF0ZUZvbygpOiB2b2lkIHtcbiAgICB0aHJvdyBuZXcgRXJyb3IoXCJOb3QgaW1wbGVtZW50ZWRcIik7XG4gIH1cblxuICBwcml2YXRlIGFzeW5jIHByaXZhdGVCYXIoKTogUHJvbWlzZTx2b2lkPiB7XG4gICAgdGhyb3cgbmV3IEVycm9yKFwiTm90IGltcGxlbWVudGVkXCIpO1xuICB9XG59XG4ifV0sWyJlc2J1aWxkLmNvbmZpZy5qc29uIix7ImNvbnRlbnQiOiJ7XG4gIFwiZm9ybWF0XCI6IFwiZXNtXCIsXG4gIFwidGFyZ2V0XCI6IFwiZXNuZXh0XCIsXG4gIFwibWluaWZ5XCI6IGZhbHNlLFxuICBcImNkblVybFwiOiBcImh0dHBzOi8vY2RuLnNreXBhY2suZGV2XCIsXG4gIFwic291cmNlbWFwXCI6IFwiaW5saW5lXCJcbn0ifV0sWyJzdW0udHMiLHsiY29udGVudCI6ImV4cG9ydCBjb25zdCBzdW0gPSAoYTogbnVtYmVyLCBiOiBudW1iZXIpID0+IGEgKyBiIn1dXQ==). As they are not part of the source maps, code coverage tools cannot mark them as covered. We know that there is a function, but don't know that it has `public`/`protected` prefix as it was removed during transform. 

On the right side is the code that Vitest ends up executing: [https://evanw.github.io/source-map-visualization/#MjAzMABjbG](https://evanw.github.io/source-map-visualization/#MjAzMABjbGFzcyBGb28gewogIHB1YmxpY0ZvbygpIHsKICAgIHRocm93IG5ldyBFcnJvcigiTm90IGltcGxlbWVudGVkIik7CiAgfQogIGFzeW5jIHB1YmxpY0JhcigpIHsKICAgIHRocm93IG5ldyBFcnJvcigiTm90IGltcGxlbWVudGVkIik7CiAgfQogIHByb3RlY3RlZEZvbygpIHsKICAgIHRocm93IG5ldyBFcnJvcigiTm90IGltcGxlbWVudGVkIik7CiAgfQogIGFzeW5jIHByb3RlY3RlZEJhcigpIHsKICAgIHRocm93IG5ldyBFcnJvcigiTm90IGltcGxlbWVudGVkIik7CiAgfQogIHByaXZhdGVGb28oKSB7CiAgICB0aHJvdyBuZXcgRXJyb3IoIk5vdCBpbXBsZW1lbnRlZCIpOwogIH0KICBhc3luYyBwcml2YXRlQmFyKCkgewogICAgdGhyb3cgbmV3IEVycm9yKCJOb3QgaW1wbGVtZW50ZWQiKTsKICB9Cn0KT2JqZWN0LmRlZmluZVByb3BlcnR5KF9fdml0ZV9zc3JfZXhwb3J0c19fLCAiRm9vIiwgeyBlbnVtZXJhYmxlOiB0cnVlLCBjb25maWd1cmFibGU6IHRydWUsIGdldCgpeyByZXR1cm4gRm9vIH19KTsKCi8vIyBzb3VyY2VNYXBwaW5nU291cmNlPXZpdGUtbm9kZQovLyMgc291cmNlTWFwcGluZ1VSTD1kYXRhOmFwcGxpY2F0aW9uL2pzb247Y2hhcnNldD11dGYtODtiYXNlNjQsZXlKMlpYSnphVzl1SWpvekxDSnRZWEJ3YVc1bmN5STZJa0ZCUVU4c1RVRkJUU3hKUVVGSk8wRkJRVUVzUlVGRFVpeFpRVUZyUWp0QlFVTjJRaXhWUVVGTkxFbEJRVWtzVFVGQlRTeHBRa0ZCYVVJN1FVRkJRU3hGUVVOdVF6dEJRVUZCTEVWQlJVRXNUVUZCWVN4WlFVRXlRanRCUVVOMFF5eFZRVUZOTEVsQlFVa3NUVUZCVFN4cFFrRkJhVUk3UVVGQlFTeEZRVU51UXp0QlFVRkJMRVZCUlZVc1pVRkJjVUk3UVVGRE4wSXNWVUZCVFN4SlFVRkpMRTFCUVUwc2FVSkJRV2xDTzBGQlFVRXNSVUZEYmtNN1FVRkJRU3hGUVVWQkxFMUJRV2RDTEdWQlFUaENPMEZCUXpWRExGVkJRVTBzU1VGQlNTeE5RVUZOTEdsQ1FVRnBRanRCUVVGQkxFVkJRMjVETzBGQlFVRXNSVUZGVVN4aFFVRnRRanRCUVVONlFpeFZRVUZOTEVsQlFVa3NUVUZCVFN4cFFrRkJhVUk3UVVGQlFTeEZRVU51UXp0QlFVRkJMRVZCUlVFc1RVRkJZeXhoUVVFMFFqdEJRVU40UXl4VlFVRk5MRWxCUVVrc1RVRkJUU3hwUWtGQmFVSTdRVUZCUVN4RlFVTnVRenRCUVVOR08ybElRVUZCSWl3aWJtRnRaWE1pT2x0ZExDSnBaMjV2Y21WTWFYTjBJanBiWFN3aWMyOTFjbU5sY3lJNld5SjBjeTF5WlhCeWJ5NTBjeUpkTENKemIzVnlZMlZ6UTI5dWRHVnVkQ0k2V3lKbGVIQnZjblFnWTJ4aGMzTWdSbTl2SUh0Y2JpQWdjSFZpYkdsaklIQjFZbXhwWTBadmJ5Z3BPaUIyYjJsa0lIdGNiaUFnSUNCMGFISnZkeUJ1WlhjZ1JYSnliM0lvWENKT2IzUWdhVzF3YkdWdFpXNTBaV1JjSWlrN1hHNGdJSDFjYmx4dUlDQndkV0pzYVdNZ1lYTjVibU1nY0hWaWJHbGpRbUZ5S0NrNklGQnliMjFwYzJVOGRtOXBaRDRnZTF4dUlDQWdJSFJvY205M0lHNWxkeUJGY25KdmNpaGNJazV2ZENCcGJYQnNaVzFsYm5SbFpGd2lLVHRjYmlBZ2ZWeHVYRzRnSUhCeWIzUmxZM1JsWkNCd2NtOTBaV04wWldSR2IyOG9LVG9nZG05cFpDQjdYRzRnSUNBZ2RHaHliM2NnYm1WM0lFVnljbTl5S0Z3aVRtOTBJR2x0Y0d4bGJXVnVkR1ZrWENJcE8xeHVJQ0I5WEc1Y2JpQWdjSEp2ZEdWamRHVmtJR0Z6ZVc1aklIQnliM1JsWTNSbFpFSmhjaWdwT2lCUWNtOXRhWE5sUEhadmFXUStJSHRjYmlBZ0lDQjBhSEp2ZHlCdVpYY2dSWEp5YjNJb1hDSk9iM1FnYVcxd2JHVnRaVzUwWldSY0lpazdYRzRnSUgxY2JseHVJQ0J3Y21sMllYUmxJSEJ5YVhaaGRHVkdiMjhvS1RvZ2RtOXBaQ0I3WEc0Z0lDQWdkR2h5YjNjZ2JtVjNJRVZ5Y205eUtGd2lUbTkwSUdsdGNHeGxiV1Z1ZEdWa1hDSXBPMXh1SUNCOVhHNWNiaUFnY0hKcGRtRjBaU0JoYzNsdVl5QndjbWwyWVhSbFFtRnlLQ2s2SUZCeWIyMXBjMlU4ZG05cFpENGdlMXh1SUNBZ0lIUm9jbTkzSUc1bGR5QkZjbkp2Y2loY0lrNXZkQ0JwYlhCc1pXMWxiblJsWkZ3aUtUdGNiaUFnZlZ4dWZWeHVJbDBzSW1acGJHVWlPaUl2YzNKakwzUnpMWEpsY0hKdkxuUnpJbjA9CjEwNjEAeyJ2ZXJzaW9uIjozLCJtYXBwaW5ncyI6IkFBQU8sTUFBTSxJQUFJO0FBQUEsRUFDUixZQUFrQjtBQUN2QixVQUFNLElBQUksTUFBTSxpQkFBaUI7QUFBQSxFQUNuQztBQUFBLEVBRUEsTUFBYSxZQUEyQjtBQUN0QyxVQUFNLElBQUksTUFBTSxpQkFBaUI7QUFBQSxFQUNuQztBQUFBLEVBRVUsZUFBcUI7QUFDN0IsVUFBTSxJQUFJLE1BQU0saUJBQWlCO0FBQUEsRUFDbkM7QUFBQSxFQUVBLE1BQWdCLGVBQThCO0FBQzVDLFVBQU0sSUFBSSxNQUFNLGlCQUFpQjtBQUFBLEVBQ25DO0FBQUEsRUFFUSxhQUFtQjtBQUN6QixVQUFNLElBQUksTUFBTSxpQkFBaUI7QUFBQSxFQUNuQztBQUFBLEVBRUEsTUFBYyxhQUE0QjtBQUN4QyxVQUFNLElBQUksTUFBTSxpQkFBaUI7QUFBQSxFQUNuQztBQUNGO2lIQUFBIiwibmFtZXMiOltdLCJpZ25vcmVMaXN0IjpbXSwic291cmNlcyI6WyJ0cy1yZXByby50cyJdLCJzb3VyY2VzQ29udGVudCI6WyJleHBvcnQgY2xhc3MgRm9vIHtcbiAgcHVibGljIHB1YmxpY0ZvbygpOiB2b2lkIHtcbiAgICB0aHJvdyBuZXcgRXJyb3IoXCJOb3QgaW1wbGVtZW50ZWRcIik7XG4gIH1cblxuICBwdWJsaWMgYXN5bmMgcHVibGljQmFyKCk6IFByb21pc2U8dm9pZD4ge1xuICAgIHRocm93IG5ldyBFcnJvcihcIk5vdCBpbXBsZW1lbnRlZFwiKTtcbiAgfVxuXG4gIHByb3RlY3RlZCBwcm90ZWN0ZWRGb28oKTogdm9pZCB7XG4gICAgdGhyb3cgbmV3IEVycm9yKFwiTm90IGltcGxlbWVudGVkXCIpO1xuICB9XG5cbiAgcHJvdGVjdGVkIGFzeW5jIHByb3RlY3RlZEJhcigpOiBQcm9taXNlPHZvaWQ+IHtcbiAgICB0aHJvdyBuZXcgRXJyb3IoXCJOb3QgaW1wbGVtZW50ZWRcIik7XG4gIH1cblxuICBwcml2YXRlIHByaXZhdGVGb28oKTogdm9pZCB7XG4gICAgdGhyb3cgbmV3IEVycm9yKFwiTm90IGltcGxlbWVudGVkXCIpO1xuICB9XG5cbiAgcHJpdmF0ZSBhc3luYyBwcml2YXRlQmFyKCk6IFByb21pc2U8dm9pZD4ge1xuICAgIHRocm93IG5ldyBFcnJvcihcIk5vdCBpbXBsZW1lbnRlZFwiKTtcbiAgfVxufVxuIl0sImZpbGUiOiIvc3JjL3RzLXJlcHJvLnRzIn0=).

Now the coverage reports cannot mark those keywords as uncovered as they are not present in the source maps:

```json
{
  "scriptId": "272",
  "url": "file:///x/examples/packages/vitest-example/src/ts-repro.ts",
  "functions": [
    {
      "functionName": "protectedFoo",
      "ranges": [{ "startOffset": 325, "endOffset": 385, "count": 0 }],
      "isBlockCoverage": false
    },
```

```js
   protectedFoo() {
// ^ 325, uncovered part starts from here
    throw new Error("Not implemented");
   }
// ^ 385, uncovered part stops here
```

Now it's remapped back to sources, and source maps point here:

```ts
    protected protectedFoo(): void {
//            ^^^^^^^^^^^^^^^^^^^^^^
      throw new Error("Not implemented");
//    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    }
//  ^
```

**Comment by AriPerkkio** [comment]
As the `protected`/`public` keywords are type-only information I think this is currently working correctly. Types are not present in runtime code so it's not possible to cover them.
