### ISSUE TITLE
Error: Expected a single value for option `--exclude <glob>`, received `["a/*", "b/*"]`

### ISSUE THREAD

**Issue by fregante** [vitest-dev/vitest#5779]
### Clear and concise description of the problem

Until Vitest 1.2 I was able to use two `--exclude` globs, but this feature some inexplicably removed. I'm using this to split certain tests on CI so these globs cannot be part of the static configuration.

The command I'm running is:

```sh
vitest --run --exclude build/features* --exclude **/selectors*
```

### Suggested solution

Please restore the ability to call `--exclude` multiple times

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
Probably this got unintentionally broken when cli parsing is reworked. We can put back `array: true` somewhere like this
- https://github.com/vitest-dev/vitest/pull/5265
