### ISSUE TITLE
module mock will not work with yarn workspaces mode

### ISSUE THREAD

**Issue by uuau99999** [vitest-dev/vitest#578]
### Describe the bug

My project use yarn workspaces mode. So some node_modules will hoist to the project root node_modules directory.
However, when I use vi.mock to mock a module which hoisted to the root it didnot work as expected.
`// in test.spec.ts`
`vi.mock('some-package');`
`// in index.ts`
`import { someFn } from 'some-package'; // someFn still not mocked`
But when mocking a module not hoisted to the root node_modules it works as expected.

In this case to fix that, I have to use relateive path while mocking such module:
`
vi.mock('../some_path_to_root_dir/node_modules/some-package');
`
Which is pretty tricky. Hope that vi.mock can resolve the correct module path.
Thanks.

### Reproduction

1. Use yarn workspaces mode in package.json:
   `"workspaces": [
    "packages/**"
  ],`
2. create a sub project which path is like: root/packages/app1 and in this dir use yarn to install any package like axios.
3. mock axios in test code like: `vi.mock('axios')` under the dir root/packages/app1;
4. mock will not succeed.

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 319.96 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Demivan** [comment]
Is this still happening? I just tried to reproduce it and it works fine. Was able to mock hoisted axios package.
Please, provide a reproduction if this it still happening.

**Comment by NMinhNguyen** [comment]
I have a repro: https://codesandbox.io/s/festive-goldstine-ysjbf?file=/packages/a/index.test.js I can mock an external package like `lodash-es` but I can't mock a workspace package (`@minh/b`)

**Comment by Demivan** [comment]
@NMinhNguyen Thanks for repro, this makes more sense then not being able to mock `axios`.

You can use `resolve.alias` config to mimic yarn workspaces: https://codesandbox.io/s/ecstatic-margulis-liqjb?file=/packages/a/vite.config.js

Will investigate if it is possible to resolve `yarn` workspace references.

**Comment by NMinhNguyen** [comment]
> Will investigate if it is possible to resolve `yarn` workspace references.

I've updated the repro to make use of `require.resolve` and it's able to do so without any Yarn-specific configuration, so I'm not sure why Vitest wouldn't be able to resolve? Take a look at https://codesandbox.io/s/festive-goldstine-ysjbf?file=/packages/a/test-resolve.js:0-206

**Comment by sheremet-va** [comment]
I found the issue, will make a PR in a few hours.

**Comment by sheremet-va** [comment]
I tested #712 on your reproduction, and everything worked 🎆

**Comment by NMinhNguyen** [comment]
> I tested #712 on your reproduction, and everything worked 🎆 

Great, thank you for fixing this!

**Comment by uuau99999** [comment]
Thanks!

**Comment by koistya** [comment]
@sheremet-va could you check please if this is somehow related to this issue #3426
