### ISSUE TITLE
Allow augmentation of `env` in the `InlineConfig` interface for type-safe env vars, 

### ISSUE THREAD

**Issue by danwithabox** [vitest-dev/vitest#5780]
### Clear and concise description of the problem

I want to pass down a config-defined env var via a global setup file to test files with `provide()`, and have it be type-safe all the way through.
`provide()` can be made type safe via `ProvidedContext`, but `InlineConfig.env` cannot be.

When writing
```ts
// vitest.config.ts
export default defineConfig({
    test: {
        env: {
            MY_CUSTOM_ENV: "foo",
        }
    },
}),
```
and
```ts
// globalSetup.ts
import type { GlobalSetupContext } from "vitest/node"

export default function setup({ config, provide, }: GlobalSetupContext) {
    const myCustomEnv = config.env.MY_CUSTOM_ENV;
    provide('myCustomEnv', myCustomEnv);
}

declare module "vitest" {
    export interface ProvidedContext {
        myCustomEnv: "foo" | "bar", // or, I guess, could be InlineConfig["env"]["MY_CUSTOM_ENV"]
    }
}
```

I would like `MY_CUSTOM_ENV` to be type-safe and have autocompletion in:
- `defineConfig()`'s `test.env`
- `globalSetup.ts`'s `config.env`

I attempted to augment the `InlineConfig` interface:
```ts
// vitest.d.ts
declare module "vitest" {
    export interface InlineConfig {
        // Error: ts(2717)
        env?: {
            MY_CUSTOM_ENV: "foo" | "bar",
        },
    }
}
export {};
```

but as expected, this results in:
```
Subsequent property declarations must have the same type.  Property 'env' must be of type 'Record<string, string> | undefined', but here has type '{ MY_CUSTOM_ENV: "foo" | "bar"; } | undefined'.ts(2717)
```

Considering I'm used to [overriding `import.meta.env` in Vite](https://vitejs.dev/guide/env-and-mode#intellisense-for-typescript), and since declaration-merging `ProvidedContext` works great as well, I'd like the same capability for `InlineConfig`.

### Suggested solution

Instead of
```ts
interface InlineConfig {
    // (...)
    env?: Record<string, string>;
    // (...)
}
```
`env` should have its own augmentable interface, similar to how `ProvidedContext` works, e.g.
```ts
interface InlineConfigEnv {
}
interface InlineConfig {
    // (...)
    env?: InlineConfigEnv;
    // (...)
}
```

Also, it seems `.env` is not documented at all over at https://vitest.dev/config/, even though it looks like part of the stable public API, has JSDoc and everything.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I guess we can set it to `Partial<NodeJS.ProcessEnv>` to allow augmentation

**Comment by danwithabox** [comment]
Blinded by my need to just abuse this as a way to pass data from config to tests, I didn't even think of `NodeJS.ProcessEnv`, but that makes prefect sense and would be happy with it 😄
