### ISSUE TITLE
Range.compareBoundaryPoints should throw error

### ISSUE THREAD

**Issue by mozesstumpf** [vitest-dev/vitest#5788]
### Describe the bug

`Range.compareBoundaryPoints` should throw error if the compared ranges' boundary-point's are in different tree.

Documentation: [Range.compareBoundaryPoints](https://dom.spec.whatwg.org/#dom-range-compareboundarypoints)
2nd point:
> If [this](https://webidl.spec.whatwg.org/#this)’s [root](https://dom.spec.whatwg.org/#concept-range-root) is not the same as sourceRange’s [root](https://dom.spec.whatwg.org/#concept-range-root), then [throw](https://webidl.spec.whatwg.org/#dfn-throw) a "[WrongDocumentError](https://webidl.spec.whatwg.org/#wrongdocumenterror)" [DOMException](https://webidl.spec.whatwg.org/#idl-DOMException).

### Reproduction

Repo to reproduce: [compare-boundary-points-error](https://github.com/mozesstumpf/vitest-compareBoundaryPoints-error)

```
	const text1 = document.createElement("text");
	const text2 = document.createElement("text");

	const range = new Range();
	range.setStart(text1, 0);

	const sourceRange = new Range();
	sourceRange.setStart(text2, 0);

	const position = range.compareBoundaryPoints(
		Range.START_TO_START,
		sourceRange,
	); // shoud throw an error, since the text1 and text2 are in the different tree

	console.log(position); // -1
```

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 5600 6-Core Processor
    Memory: 19.36 GB / 31.89 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    bun: 1.1.10 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (125.0.2535.51)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @vitest/coverage-v8: ^1.6.0 => 1.6.0
    vite: ^5.2.10 => 5.2.10
    vitest: ^1.6.0 => 1.6.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
The reproduction works fine in jsdom and chrome+browser mode. Both throw `WrongDocumentError` as expected.

**Comment by mozesstumpf** [comment]
The issue is only reproducible in happy-dom, it works fine in jsdom.

It looks like that the issue is rather related to the happy-dom than vitest, even though I'm not sure whether the Range API was implemented by vitest or happy-dom.

**Comment by AriPerkkio** [comment]
As it works on jsdom and browser mode, but not on happy-dom, I would say that this is an issue on their side. Vitest itself doesn't do anything related to these APIs. 

I would recommend to open an issue on happy-dom.

**Comment by sheremet-va** [comment]
Link to the happy don issue: https://github.com/capricorn86/happy-dom/issues/1462

Closing this as I don't see any reason to keep this open in Vitest.
