### ISSUE TITLE
Browser mode: 'X-Frame-Options': 'DENY' breaks tests

### ISSUE THREAD

**Issue by IanVS** [vitest-dev/vitest#5789]
### Describe the bug

I try to set up my vite headers as close to production as possible, and therefore set CSP headers, including `'X-Frame-Options': 'DENY',`.  However, this breaks vitest in browser mode, which apparently runs tests inside an iframe.  

### Reproduction

https://github.com/IanVS/reproduction-vitest-browser-frame

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 294.08 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/Library/Caches/fnm_multishells/15320_1716989283011/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/15320_1716989283011/bin/yarn
    npm: 9.5.1 - ~/Library/Caches/fnm_multishells/15320_1716989283011/bin/npm
    pnpm: 8.8.0 - ~/Library/Caches/fnm_multishells/15320_1716989283011/bin/pnpm
  Browsers:
    Safari: 17.4.1
  npmPackages:
    @vitest/browser: ^1.6.0 => 1.6.0
    @vitest/ui: latest => 1.6.0
    vite: latest => 5.2.12
    vitest: latest => 1.6.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
What we can do is remove `X-Frame-Options` during tests. Otherwise what you want to do is incompatible with how the browser mode works.

**Comment by IanVS** [comment]
Yes, that's the only thing I could think of that you could do as well, and I think it would be a reasonable approach.
