### ISSUE TITLE
Add init command for browser tests

### ISSUE THREAD

**Issue by sheremet-va** [vitest-dev/vitest#5793]
### Clear and concise description of the problem

Currently, enabling browser mode is not a very straightforward process. As a user who just wants to try it, I need to:

- enable `browser` in the config
- run `vitest`, see `@vitest/browser` is not installed
- install `@vitest/browser`
- see `webdriverio` is not installed
- ask yourself what `webdriverio` is, install it
- run `vitest`, see I forgot the browser name
- add browser name to the config

### Suggested solution

1. We need to improve documentation on how the browser mode works internally
2. Add `vitest init-browser-mode` (name TBD) command that asks what provider should be installed and what browser, then it scaffolds files to enable the browser mode integration:
	a. installs the `@vitest/browser` + provider package + adds `@vitest/browser/providers/{name}` to `tsconfig`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by MatanBobi** [comment]
This one is extremely funny for me because I just bumped into every step mentioned 😅
At least in the meantime I think we should add installation page. I'd love to help with that if needed.

**Comment by sheremet-va** [comment]
> This one is extremely funny for me because I just bumped into every step mentioned 😅 At least in the meantime I think we should add installation page. I'd love to help with that if needed.

The PR is welcome 😄

**Comment by MatanBobi** [comment]
Thanks @sheremet-va, I've created https://github.com/vitest-dev/vitest/pull/5799 in the meanwhile to clarify installation and configuration steps :)
