### ISSUE TITLE
Support testing the unhandled promise rejection

### ISSUE THREAD

**Issue by kibertoad** [vitest-dev/vitest#5796]
### Clear and concise description of the problem

Currently vitest fails a test run if it detects an unhandled rejection having been thrown:

```
Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.
```

However, sometimes this is a desireable behaviour, especially when we are testing global unhandled rejection handlers.

### Suggested solution

Several options are possible:
* Only report as a problem unhandled rejections that were not handled during the test execution (e. g. if there is no `process.on('unhandledRejection' handler that would consume the event);
* Make it possible to mark tests as expecting the unhandled rejections (e. g. syntax similar to `expect.assertions(1)` - `expect.unhandledRejections(1)`)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by fregante** [comment]
I'm interested in this as well. With event handlers and callbacks in general, errors don't always make it back to the original call site, so they're thrown and uncaught/unhandled.

It'd be great if Vitest had an easy way "expect" these. 

Last time I needed this I had to register my own unhandled rejection listener, probably breaking Vitest's own.

**Comment by sheremet-va** [comment]
> Last time I needed this I had to register my own unhandled rejection listener, probably breaking Vitest's own. Example:

I think this is what I would expect from the test to be honest. 

I am not against having a built-in assertion for this. What API would you prefer? It would have to be async.

**Comment by fregante** [comment]
I'm not sure of what kind of API would make sense for this, honestly. The closest one would be `expect(process).toThrow()` but it's not an exact match

**Comment by kibertoad** [comment]
@sheremet-va It's perfectly fine to expect user to register their own unhandedRejection handler, key problem is that it doesn't seem possible at the moment, vitest reports the test as failed anyway
