### ISSUE TITLE
docs(vitepress): pending tasks

### ISSUE THREAD

**Issue by userquin** [vitest-dev/vitest#580]
To support dark/light theme and add some new cool features using `@vue/theme`

These tasks have been moved from #573 since `@vue/theme` has breaking changes for `vitest` docs:

- [x] add `@vue/theme`: dark/light switcher, scrollable menu spy support, fixed navbar on scroll, previous and next page on footer, social icons...
- [x] add algolia search: maybe including `@vue/theme` will work adding the key on the configuration
- [ ] `a11y` : review color contrast
- [ ] fix LCP and CLS
- [ ] fix PWA: it is broken

**Comment by sheremet-va** [comment]
I feel like this can be closed. What do you think, @userquin?
