### ISSUE TITLE
Crashes under Windows

### ISSUE THREAD

**Issue by Demivan** [vitest-dev/vitest#582]
### Describe the bug

Adding this here so we don't forget to fix it

### Reproduction

https://github.com/vitest-dev/vitest/runs/4868391749?check_suite_focus=true

### System Info

```shell
Windows
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
we don't forget it, just check the pull requests ;)

**Comment by sheremet-va** [comment]
I have a theory: https://github.com/vitest-dev/vitest/pull/583

**Comment by Demivan** [comment]
@sheremet-va Cool, lets run github actions few times :)

**Comment by sheremet-va** [comment]
All five attempts are passing https://github.com/vitest-dev/vitest/actions/runs/1718747096

**Comment by userquin** [comment]
let me check on my windows machine

**Comment by userquin** [comment]
nopes, still failing:
```shell
examples/mocks test:  1: 00007FF60F6E013F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112495
examples/mocks test:  2: 00007FF60F66F396 DSA_meth_get_flags+65526
examples/mocks test:  3: 00007FF60F67024D node::OnFatalError+301
examples/mocks test:  4: 00007FF60FFAA455 v8::V8::ToLocalEmpty+53
examples/mocks test:  5: 00007FF60F667208 DSA_meth_get_flags+32360
examples/mocks test: 14: 00007FF60F72F36D uv_poll_stop+557
examples/mocks test: 15: 00007FF610540C60 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+146416
examples/mocks test: 16: 00007FFF01D37034 BaseThreadInitThunk+20
examples/mocks test: 17: 00007FFF02102651 RtlUserThreadStart+33
examples/mocks test: Failed
undefined
F:\work\projects\quini\GitHub\antfu\vitest-clean\examples\mocks:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @vitest/test-lit@ test: `vitest`
Exit status 134
examples/react-mui test$ vitest
 ```

**Comment by sheremet-va** [comment]
Too soon

**Comment by sheremet-va** [comment]
I was hoping this issues were related, but I guess we need a to dig deeper!

**Comment by userquin** [comment]
I'll check something, there the local changes, I think I have include all changes on your PR:

![imagen](https://user-images.githubusercontent.com/6311119/150173142-a95ebce0-8513-4fe4-888b-c9b244f5d880.png)

**Comment by Demivan** [comment]
I think we had two different crashes under Windows. I saw different node stack traces sometimes.

**Comment by userquin** [comment]
@Demivan it is really strange, I have 2 or 3 distinct stack traces, from `cmd.exe`  chash to `v8` null pointer (next 3 errors from 3 consecutive `pnpm run test:all` once built):

<details>
<summary><strong>null pointer</strong></summary>

```shell
examples/mocks test: FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
examples/mocks test:  1: 00007FF60F6E013F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112495
examples/mocks test:  2: 00007FF60F66F396 DSA_meth_get_flags+65526
examples/mocks test:  3: 00007FF60F67024D node::OnFatalError+301
examples/mocks test:  4: 00007FF60FFAA455 v8::V8::ToLocalEmpty+53
examples/mocks test:  5: 00007FF60F667208 DSA_meth_get_flags+32360
examples/mocks test:  6: 00007FF60F65984E v8::base::CPU::has_sse+36718
examples/mocks test:  7: 00007FF60F742C87 uv_timer_stop+1207
examples/mocks test:  8: 00007FF60F73F25B uv_async_send+331
examples/mocks test:  9: 00007FF60F73E9EC uv_loop_init+1292
examples/mocks test: 10: 00007FF60F73EB8A uv_run+202
examples/mocks test: 11: 00007FF60F70DC95 node::SpinEventLoop+309
examples/mocks test: 12: 00007FF60F5A8660 v8::internal::wasm::SignatureMap::Freeze+35776
examples/mocks test: 13: 00007FF60F5A3CB8 v8::internal::wasm::SignatureMap::Freeze+16920
examples/mocks test: 14: 00007FF60F72F36D uv_poll_stop+557
examples/mocks test: 15: 00007FF610540C60 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+146416
examples/mocks test: 16: 00007FFF01D37034 BaseThreadInitThunk+20
examples/mocks test: 17: 00007FFF02102651 RtlUserThreadStart+33
examples/mocks test: Failed
undefined
F:\work\projects\quini\GitHub\antfu\vitest-clean\examples\mocks:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @vitest/test-lit@ test: `vitest`
Exit status 134
 ELIFECYCLE  Command failed with exit code 1.
```
</details>

<details>
<summary><strong>serialization problem</strong></summary>

```shell
examples/mocks test: FATAL ERROR: v8::FromJust Maybe value is Nothing.
examples/mocks test:  1: 00007FF60F6E013F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112495
examples/mocks test:  2: 00007FF60F66F396 DSA_meth_get_flags+65526
examples/mocks test:  3: 00007FF60F67024D node::OnFatalError+301
examples/mocks test:  4: 00007FF60FF8C2F5 v8::V8::FromJustIsNothing+53
examples/mocks test:  5: 00007FF60F6583E3 v8::base::CPU::has_sse+31491
examples/mocks test:  6: 00007FF60F742C87 uv_timer_stop+1207
examples/mocks test:  7: 00007FF60F73F25B uv_async_send+331
examples/mocks test:  8: 00007FF60F73E9EC uv_loop_init+1292
examples/mocks test:  9: 00007FF60F73EB8A uv_run+202
examples/mocks test: 10: 00007FF60F70DC95 node::SpinEventLoop+309
examples/mocks test: 11: 00007FF60F5A8660 v8::internal::wasm::SignatureMap::Freeze+35776
examples/mocks test: 12: 00007FF60F5A3CB8 v8::internal::wasm::SignatureMap::Freeze+16920
examples/mocks test: 13: 00007FF60F72F36D uv_poll_stop+557
examples/mocks test: 14: 00007FF610540C60 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+146416
examples/mocks test: 15: 00007FFF01D37034 BaseThreadInitThunk+20
examples/mocks test: 16: 00007FFF02102651 RtlUserThreadStart+33
examples/mocks test: Failed
undefined
F:\work\projects\quini\GitHub\antfu\vitest-clean\examples\mocks:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @vitest/test-lit@ test: `vitest`
Exit status 134
examples/react-mui test$ vitest
 ELIFECYCLE  Command failed with exit code 1.
```
</details>

<details>
<summary><strong>cmd.exe error</strong></summary>

```shell
examples/mocks test: C:\WINDOWS\system32\cmd.exe  - pnpm  run test:all[2712]: c:\ws\src\node_file-inl.h:160: Assertion `finished_' failed.
examples/lit test: Done
examples/react-enzyme test$ vitest
examples/mocks test:  1: 00007FF60F6E013F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+112495
examples/mocks test:  2: 00007FF60F66F396 DSA_meth_get_flags+65526
examples/mocks test:  3: 00007FF60F66F751 DSA_meth_get_flags+66481
examples/mocks test:  4: 00007FF60F658B9E v8::base::CPU::has_sse+33470
examples/mocks test:  5: 00007FF60F65A076 v8::base::CPU::has_sse+38806
examples/mocks test:  6: 00007FF60F742C87 uv_timer_stop+1207
examples/mocks test:  7: 00007FF60F73F25B uv_async_send+331
examples/mocks test:  8: 00007FF60F73E9EC uv_loop_init+1292
examples/mocks test:  9: 00007FF60F73EB8A uv_run+202
examples/mocks test: 10: 00007FF60F70DC95 node::SpinEventLoop+309
examples/mocks test: 11: 00007FF60F5A8660 v8::internal::wasm::SignatureMap::Freeze+35776
examples/mocks test: 12: 00007FF60F5A3CB8 v8::internal::wasm::SignatureMap::Freeze+16920
examples/mocks test: 13: 00007FF60F72F36D uv_poll_stop+557
examples/mocks test: 14: 00007FF610540C60 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+146416
examples/mocks test: 15: 00007FFF01D37034 BaseThreadInitThunk+20
examples/mocks test: 16: 00007FFF02102651 RtlUserThreadStart+33
examples/mocks test: Failed
undefined
F:\work\projects\quini\GitHub\antfu\vitest-clean\examples\mocks:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @vitest/test-lit@ test: `vitest`
Exit status 134
examples/react-mui test$ vitest
 ELIFECYCLE  Command failed with exit code 1.
```
</details>

**Comment by sheremet-va** [comment]
If you remove `process.exit`, it still crashes?

**Comment by sheremet-va** [comment]
The last error is `Assertion `finished_' failed` which should have been fixed it the pr 🤔

**Comment by sheremet-va** [comment]
They all include `CodeObjectRegistry+112495`.

Maybe we don't event need to exit 🤔

**Comment by userquin** [comment]
ok, testing it

**Comment by userquin** [comment]
@sheremet-va it seems to be the `process.exit`, now the `fails` tests are running ok, before removing the exit line always failing, just doing a few runs more also with `test:ci`...

**Comment by Demivan** [comment]
@sheremet-va, We should just make so that process.exit is only called on timeout

**Comment by userquin** [comment]
`nr ci` + 6 consecutive `test:all` ok, testing now also `test:ci`.

I add an `await` to the `Promise.race`, this is the code that works, must I try removing the `await` add?:

![imagen](https://user-images.githubusercontent.com/6311119/150179719-ff043307-e6b9-49c2-9a8b-bd91c6ad86d3.png)

**Comment by userquin** [comment]
ok, another 5 consecutive runs with `test:ci` ok, running last test: `nr ci && pnpm run test:all && pnpm run test:ci`

**Comment by sheremet-va** [comment]
> `nr ci` + 6 consecutive `test:all` ok, testing now also `test:ci`.
> 
> I add an `await` to the `Promise.race`, this is the code that works, must I try removing the `await` add?:

Not sure if `await` does anything here to fix it tbh

**Comment by userquin** [comment]
ok it seems without the `process.exit` works again

**Comment by Demivan** [comment]
Problem right now is that `this.close` promise resolves, and that resolves `Promise.race` so we call `process.exit()` but not everything was cleaned up.

We should call `process.exit()` only if Vitest locked up somewhere and needs to be killed.

**Comment by Demivan** [comment]
@userquin Can you test this? https://github.com/vitest-dev/vitest/pull/588

**Comment by Demivan** [comment]
@sheremet-va I'm not a contributor, so don't have permissions to restart workflow. Can you rerun #588 few times?

**Comment by userquin** [comment]
@Demivan @sheremet-va the changes on #588 works on my windows machine, no error reported

**Comment by Demivan** [comment]
https://github.com/vitest-dev/vitest/runs/4879873202?check_suite_focus=true still have one crash
