### ISSUE TITLE
vitest runner defaultSuite always empty

### ISSUE THREAD

**Issue by DecathectZero** [vitest-dev/vitest#5834]
### Describe the bug

This is monitor pet-peeve that's been really bothering me.
When I run the tests I notice there's always this "ghost" suite at the top of the `ancestorTitles` stack that leads to the test name having a space in front of it, and the ancestor with an empty array item:
```
[
  {
    ancestorTitles: [ '' ],
    fullName: ' test',
    status: 'passed',
    title: 'test',
    duration: 0,
    failureMessages: []
  }
]
```

You can see it here with `testResults.assertionResults.ancestorTitles`:
https://vitest.dev/guide/reporters#json-reporter

The reason behind this is in this code:
https://github.com/vitest-dev/vitest/blob/e99451cf49a548066f463af3f7653b79c50c662a/packages/runner/src/suite.ts#L43-L47
It just generates an empty suite. If there was some way to pass a prop to it for it to take the name of the currently running file, it would be much more clear.

### Reproduction

`vitest version`: 1.6.0

`test.test.ts`:
```
import { it, expect } from 'vitest';

it('test', async () => {
  expect(true).toBe(true);
});

```

`run.js`:
```
import { startVitest } from 'vitest/node';
import { JsonReporter } from 'vitest/reporters';

class RunReporter extends JsonReporter {
  async writeReport(report) {
    this.report = JSON.parse(report);
  }
}

const reporter = new RunReporter({});

(async () => {
  await startVitest('test', undefined, undefined, {
    test: {
      reporters: [reporter],
      include: ['**/test.test.ts'], // use any test here
      testTimeout: 1000,
    },
  });

  reporter.report?.testResults.forEach((result) => {
    console.log(result.assertionResults);
  });
})();
```

`node run.js`

### System Info

```shell
N/A
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It was removed in Vitest 2.0 - #5435. You can test the changes by installing the latest beta version of Vitest.
