### ISSUE TITLE
Ability to import source scripts in IFrames

### ISSUE THREAD

**Issue by ashubham** [vitest-dev/vitest#5838]
### Clear and concise description of the problem

Consider this kind of a test:

```javascript
test("sendMessage Iframe", async () => {
    const iframe = document.createElement('iframe');
    iframe.srcdoc = `
        <script type="module">
            import { sendMessage, onMessage } from '../index.js';
            // now use sendMessage and onMessage
        </script>`;

    document.body.appendChild(iframe);
```

### Suggested solution

I should be able to import the source scripts inside of an iframe.

### Alternative

Expose the library on the window, and consume from within the iframe. But that suffers from limitations.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Iframes are handled by jsdom/happy-dom, Vitest doesn't control it.

You can however tun tests in [Browser Mode](https://github.com/vitest-dev/vitest/discussions/5828).

**Comment by ashubham** [comment]
For anyone else stumbling on this one, this one can be fixed by changing your code to:

```javascript
test("sendMessage Iframe", async () => {
    const iframe = document.createElement('iframe');
    iframe.srcdoc = `
        <script type="module">
            import { sendMessage, onMessage } from '/index.js';
            // now use sendMessage and onMessage
        </script>`;

    document.body.appendChild(iframe);
```

Basically use absolute paths from the root to reference to the source files.

@sheremet-va This is not documented, or atleast I couldn't find it.
