### ISSUE TITLE
vitest 1.6.0 and axios tests fails with error `DataCloneError: function transformRequest` 

### ISSUE THREAD

**Issue by lcharlois-neotys** [vitest-dev/vitest#5848]
### Describe the bug

Hello,

After upgrading to `vitest` 1.6.0 we started to face some weird errors during test execution.
Same tests was working and are still working fine with version 1.5.0.

It looks that the issue occurs when an AxiosError is thrown by the test.

When this error occurs vitest stops executing other test but doesn't really report a failure.
The vitest worker looks to crash and to not execute other tests in the same file.

The error looks like the following:
```shell
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 2 unhandled errors during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
DataCloneError: function transformRequest(data, headers) {
    const contentType = headers.getContentType() || '';
    const ha...<omitted>... } could not be cloned.
 ❯ new DOMException node:internal/per_context/domexception:53:5
 ❯ post node_modules/vitest/dist/vendor/utils.0uYuCbzo.js:10:12
 ❯ node_modules/vitest/dist/vendor/index.8bPxjt7g.js:48:11
 ❯ sendCall node_modules/vitest/dist/vendor/index.8bPxjt7g.js:33:16
 ❯ node_modules/vitest/dist/vendor/rpc.joBhAkyK.js:79:18

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { code: 25, INDEX_SIZE_ERR: 1, DOMSTRING_SIZE_ERR: 2, HIERARCHY_REQUEST_ERR: 3, WRONG_DOCUMENT_ERR: 4, INVALID_CHARACTER_ERR: 5, NO_DATA_ALLOWED_ERR: 6, NO_MODIFICATION_ALLOWED_ERR: 7, NOT_FOUND_ERR: 8, NOT_SUPPORTED_ERR: 9, INUSE_ATTRIBUTE_ERR: 10, INVALID_STATE_ERR: 11, SYNTAX_ERR: 12, INVALID_MODIFICATION_ERR: 13, NAMESPACE_ERR: 14, INVALID_ACCESS_ERR: 15, VALIDATION_ERR: 16, TYPE_MISMATCH_ERR: 17, SECURITY_ERR: 18, NETWORK_ERR: 19, ABORT_ERR: 20, URL_MISMATCH_ERR: 21, QUOTA_EXCEEDED_ERR: 22, TIMEOUT_ERR: 23, INVALID_NODE_TYPE_ERR: 24, DATA_CLONE_ERR: 25 }
This error originated in "apps/api-e2e/src/test-executions/post2.spec.ts" test file. It doesn't mean the error was thrown inside the file itself, but while it was running.
The latest test that might've caused the error is "Created nominal case". It might mean one of the following:
- The error was thrown, while Vitest was running this test.
- If the error occurred after the test had been completed, this was the last documented test before it was thrown.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
{
  stackStr: 'DataCloneError: function transformRequest(data, headers) {\n' +
    "    const contentType = headers.getContentType() || '';\n" +
    '    const ha...<omitted>... } could not be cloned.\n' +
    '    at new DOMException (node:internal/per_context/domexception:53:5)\n' +
    '    at post (file:///.../node_modules/vitest/dist/vendor/utils.0uYuCbzo.js:10:12)\n' +
    '    at file:///.../node_modules/vitest/dist/vendor/index.8bPxjt7g.js:48:11\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at sendCall (file:///..../node_modules/vitest/dist/vendor/index.8bPxjt7g.js:33:16)\n' +
    '    at file:///.../node_modules/vitest/dist/vendor/rpc.joBhAkyK.js:79:18',
  nameStr: 'DataCloneError',
  expected: 'undefined',
  actual: 'undefined',
  type: 'Unhandled Error',
  stacks: [
    {
      method: 'new DOMException',
      file: '/node:internal/per_context/domexception',
      line: 53,
      column: 5
    },
    {
      method: 'post',
      file: '/node_modules/vitest/dist/vendor/utils.0uYuCbzo.js',
      line: 10,
      column: 12
    },
    {
      method: '',
      file: '/node_modules/vitest/dist/vendor/index.8bPxjt7g.js',
      line: 48,
      column: 11
    },
    {
      method: 'sendCall',
      file: '/node_modules/vitest/dist/vendor/index.8bPxjt7g.js',
      line: 33,
      column: 16
    },
    {
      method: '',
      file: '/node_modules/vitest/dist/vendor/rpc.joBhAkyK.js',
      line: 79,
      column: 18
    }
  ]
}
 ❯ new DOMException node:internal/per_context/domexception:53:5
 ❯ post node_modules/vitest/dist/vendor/utils.0uYuCbzo.js:10:12
 ❯ node_modules/vitest/dist/vendor/index.8bPxjt7g.js:48:11
 ❯ sendCall node_modules/vitest/dist/vendor/index.8bPxjt7g.js:33:16
 ❯ node_modules/vitest/dist/vendor/rpc.joBhAkyK.js:79:18

```

### Reproduction

Here is a stackblitz allowing to reproduce the bug: https://stackblitz.com/edit/vitest-dev-vitest-henjam?file=test%2Fsuite.test.ts

### System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 14.62 GB / 31.01 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.14.0 - /usr/bin/node
    Yarn: 1.22.21 - /usr/bin/yarn
    npm: 10.7.0 - /usr/bin/npm
  Browsers:
    Chrome: 125.0.6422.141
  npmPackages:
    @vitejs/plugin-react-swc: 3.5.0 => 3.5.0 
    @vitest/coverage-v8: 1.6.0 => 1.6.0 
    @vitest/ui: 1.6.0 => 1.6.0 
    vite: 5.0.12 => 5.0.12 
    vitest: 1.6.0 => 1.6.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Crispy-rw** [comment]
Had the same error Today

**Comment by sheremet-va** [comment]
Looks like axios's `toJSON` doesn't return json-compatible object. Looks like we still need to proicess it:

https://github.com/vitest-dev/vitest/blob/c238072fdf27816511c3a9261bb05ebf5992988a/packages/utils/src/error.ts#L48

Like here:

https://github.com/vitest-dev/vitest/blob/c238072fdf27816511c3a9261bb05ebf5992988a/packages/utils/src/error.ts#L40

**Comment by lcharlois-neotys** [comment]
@sheremet-va If the change is to apply the same logic at line 48 than line 40, I guess I can do it.
By the way, is there a chance to have this fix in a 1.6.x or more genreally on 1.x version?
And if yes is there something special to do?

**Comment by sheremet-va** [comment]
> @sheremet-va If the change is to apply the same logic at line 48 than line 40, I guess I can do it. By the way, is there a chance to have this fix in a 1.6.x or more genreally on 1.x version? And if yes is there something special to do?

The change is applying the logic and adding a test.

**Comment by lcharlois-neotys** [comment]
Do you have an idea on how to write a such test?

**Comment by sheremet-va** [comment]
Just call the function with previously failing parameters here: 

https://github.com/vitest-dev/vitest/blob/c238072fdf27816511c3a9261bb05ebf5992988a/test/core/test/serialize.test.ts#L6

**Comment by lcharlois-neotys** [comment]
Hello, I took a look unfortunately I don't know how to write a test the fails with the current implementation.

**Comment by eddienubes** [comment]
Also faced this issue testing axios clients.

**Comment by lcharlois-neotys** [comment]
Hello @sheremet-va ,

Do you know if it is planned to releas a 1.6.1 or a 1.7.0 version with this fix?

**Comment by sheremet-va** [comment]
> Hello @sheremet-va ,
> 
> Do you know if it is planned to releas a 1.6.1 or a 1.7.0 version with this fix?

The next release is 2.0. If this bug is bothering you, you can stay at 1.5.3.
