### ISSUE TITLE
Vitest should install correct ui/browser package versions via CLI

### ISSUE THREAD

**Issue by yannbf** [vitest-dev/vitest#5855]
### Describe the bug

When running tests with specific flags which the project is not ready for, e.g. --ui or --browser, the CLI detects the need to install such dependencies:

<img width="497" alt="image" src="https://github.com/vitest-dev/vitest/assets/1671563/f15c73c9-7015-449f-8a5a-a5b6fe6f0783">

However, the dependencies don't follow the version of the CLI. In my project, I'm using `vitest: 2.0.0-beta.9` and when prompted to install `@vitest/browser`,  I end up getting latest (1.6.0). This causes further issues as the packages won't play nicely if they differ in versions, especially major versions.

It would be nice if the code which installs dependencies, if such dependencies are vitest ones e.g. `@vitest/browser` or `@vitest/ui`, that they use the same version of the installed Vitest CLI:
https://github.com/vitest-dev/vitest/blob/52d545bf9ccb49bba1e090bbb69cfc5228288bd5/packages/vitest/src/node/packageInstaller.ts#L43

### Reproduction

- Create any vitest project using a specific, non-latest version
- Run vitest --browser
- Get prompted, see the installed version being different than the Vitest CLI

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
This is also an issue with code coverage packages. As we (intentionally) require all Vitest packages to be on same version, it's not guaranteed that `vitest@1.2.0` and `@vitest/<package>@1.5.0` work together. When auto-installing prompted coverage packages while running older versions of Vitest, you may end up in a situation where newer version `@vitest/coverage-*` is installed.
