### ISSUE TITLE
Async context is not passed into tests from fixtures

### ISSUE THREAD

**Issue by mdnorman** [vitest-dev/vitest#5858]
### Describe the bug

I'm trying to use `AsyncLocalStorage` to provide context code running under test, but wrapping `AsyncLocalStorage.run` around the fixture's `use` function doesn't work because the async context gets lost before the test runs.

### Reproduction

The first test below fails but it should pass:

```typescript
import { AsyncLocalStorage } from "node:async_hooks";
import { v4 as uuid } from "uuid";
import { TestAPI, test as baseTest, describe, expect } from "vitest";

// assume this is in some other files
const localStorage = new AsyncLocalStorage<string>();

const withContext = async <T>(fn: (value: string) => Promise<T>) => {
  const currentValue = localStorage.getStore();
  if (!currentValue) {
    const value = uuid();
    return localStorage.run(value, async () => await fn(value));
  }

  return fn(currentValue);
};

const usesContext = async () =>
  withContext(async (value) => {
    console.log(value);
    return value;
  });
// end external code

// create a test context with a custom local context
interface IssueTestContext {
  customContext: string;
}

export const addIssueTestContext = <T>(test: TestAPI<T>) => {
  return test.extend<IssueTestContext>({
    // eslint-disable-next-line no-empty-pattern
    customContext: async ({}, use) => {
      const context = "custom context";

      await localStorage.run(context, async () => {
        await use(context);
      });
    },
  });
};

const test = addIssueTestContext(baseTest);

// now use the test context in a test
describe("asyncLocalStorageIssue", () => {
  test("should have custom context", async ({ customContext }) => {
    const result = await usesContext();
    expect(result).toEqual(customContext);
  });

  test("should not have custom context", async () => {
    const result = await usesContext();
    expect(result).not.toEqual("custom context");
  });

  test("should have my context", async () => {
    await withContext(async (expectedValue) => {
      const result = await usesContext();
      expect(result).toEqual(expectedValue);
    });

    await localStorage.run("my context", async () => {
      const result = await usesContext();
      expect(result).toEqual("my context");
    });
  });
});

```

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.42 GB / 64.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    pnpm: 8.15.8 - ~/.nvm/versions/node/v20.13.1/bin/pnpm
  Browsers:
    Chrome: 125.0.6422.142
    Safari: 17.4.1
  npmPackages:
    @vitest/coverage-v8: 1.6.0 => 1.6.0 
    @vitest/ui: 1.6.0 => 1.6.0 
    vite: 5.2.12 => 5.2.12 
    vitest: 1.6.0 => 1.6.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Fixture implementation (namely `await use()`) doesn't create function call nesting, so `AsyncLocalStorage` doesn't work unfortunately.
Fixture is initialized only once which can happen in `beforeEach` but not in `test`, so the use case you're imagining with  `AsyncLocalStorage` might be actually a bit different conceptually.

Maybe this feature request is something similar in a spirit https://github.com/vitest-dev/vitest/issues/5728 and in the thread, you can find some alternative approach to wrap your `test` function.

**Comment by sheremet-va** [comment]
This is intentional. Fixtures initialization runs separately from test execution. I'd suggest following the discussion at #5728
