### ISSUE TITLE
No console logs/debugs/errors in tests or component

### ISSUE THREAD

**Issue by MarcoPasta** [vitest-dev/vitest#5887]
### Describe the bug

When i use console.log/debug/error in either the component or the tests itself i get no logs printed to the console, the terminal or in the ui. The project runs on Angular 17, i migrated to vitest using this guide: https://analogjs.org/docs/features/testing/vitest

My config:
```mts
/// <reference types="vitest" />

import angular from '@analogjs/vite-plugin-angular';

import { defineConfig } from 'vite';

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  return {
    plugins: [
      angular(),
    ],
    test: {
      globals: true,
      environment: 'happy-dom',
      setupFiles: ['./src/test-setup.ts'],
      include: ['**/*.spec.ts'],
      reporters: ['default'],
    },
    define: {
      'import.meta.vitest': mode !== 'production',
    },
  };
});
```

I tried several methods using --silent=false, --disableConsoleIntercept, ----inspect-brk etc but non of them seemed to work. I installed jest alongside and console.logs are working here..

![image](https://github.com/vitest-dev/vitest/assets/63001199/b520bab7-f929-4fb5-b599-01f13745609c)
![image](https://github.com/vitest-dev/vitest/assets/63001199/722e1135-20a6-416e-adbe-9b75eaa33999)

### Reproduction

- Setup angular 17 standalone project
- Follow this guide https://analogjs.org/docs/features/testing/vitest
- set test environment to happy-dom
- use any console.log/debug/error in either a component or test

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M3 Pro
    Memory: 350.92 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
  IDEs:
    IntelliJ: 2024.1.2
  Browsers:
    Chrome: 126.0.6478.57
  npmPackages:
    @analogjs/platform: ^1.4.0 => 1.4.0 
    @analogjs/vite-plugin-angular: ^1.2.0 => 1.4.0 
    @nx/vite: ~18.0.0 => 18.0.8 
    @vitest/ui: ^1.6.0 => 1.6.0 
    happy-dom: ^14.12.0 => 14.12.0 
    jsdom: ^22.0.0 => 22.1.0 
    vite-tsconfig-paths: ^4.2.0 => 4.3.2 
    vitest: ^1.3.1 => 1.6.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dulimarta** [comment]
I am facing a similar issue (but for a Vue3 project, not an Angular). To show console output from the test, I had to use

```
vitest --disableConsoleIntercept=false
```

the following option (without `false` did not work)

```
vitest --disableConsoleIntercept
```

However, disabling this option only shows console output in my test, but not console output from my Vue components

**Comment by sheremet-va** [comment]
I don't think this is related to Vitest. I need an actual reproduction (a repository) that I can run without additional packages on top of it (like `nx`).

**Comment by MarcoPasta** [comment]
I tried to create a minimal reproduction project with only installing the @analogjs/platform package and running 
`ng g @analogjs/platform:setup-vitest --project [your-project-name]
` and it threw me the error that the @nx/devkit package is missing. 
After installing the missing package i was able to run the tests with this result: 

![image](https://github.com/vitest-dev/vitest/assets/63001199/00642233-cc37-49f4-904f-a6e6c33bd112)

I tried setting it up in another minimal way but unfortunately i can't get it to run - can anyone help me out here?
