### ISSUE TITLE
[CI=true] toMatchFileSnapshot always mismatched if empty file

### ISSUE THREAD

**Issue by gterras** [vitest-dev/vitest#5891]
### Describe the bug

Following https://github.com/vitest-dev/vitest/discussions/5890: 

`toMatchFileSnapshot(EMPTY_FILE)` will consistently fail when `CI=true`. 

As pointed out by @hi-ogawa: 

> Vitest probably got confused by empty snapshot file and tries to create a new snapshot, but that's not allowed on CI environment (i.e. it's treated as error by default).

### Reproduction

https://github.com/gterras/repro-vitest-snapshot
- `npm run test` => OK
- `npm run test:ci` => KO

### System Info

```shell
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
  npmPackages:
    vitest: ^1.6.0 => 1.6.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Thanks for the repro. Normal run always showing "Snapshots  1 written" is also wrong probably for the same reason.

```sh
$ npm run test

 RUN  v1.6.0 /home/projects/kkviakplg.github

 ✓ test/repro.spec.ts (2)
   ✓ Repro (2)
     ✓ should pass with non-empty snapshot
     ✓ should pass with empty snapshot

  Snapshots  1 written  //// <<--- this also shows up always
 Test Files  1 passed (1)
      Tests  2 passed (2)
````
