### ISSUE TITLE
Vitest UI: Add a dropdown that allows me to expand and minimize the test suites when working with hundreds of test suites in a test file

### ISSUE THREAD

**Issue by jazimabbas** [vitest-dev/vitest#5896]
### Clear and concise description of the problem

I have hundreds of test cases in my test file. I refactored those tests into a nicely organized describe wrapper, but it would be great to have a dropdown where I can expand and minimize the tests. This way, I can quickly check the status without having to scroll to the bottom of the page. You get the idea, right?

### Suggested solution

There must be some kind of dropdown where we can expand and minimize the tests.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
There is already a dropdown in the latest beta. Please, update both `vitest` and `@vitest/ui` packages to confirm if this is what you want. (The performance might be quite bad, but we have a PR to fix that)

**Comment by jazimabbas** [comment]
Thanks. I'll check that. I am closing this issue right now.
