### ISSUE TITLE
No such file or directory for coverage files

### ISSUE THREAD

**Issue by C0ZEN** [vitest-dev/vitest#5903]
### Describe the bug

I have flaky failing tests due to unfound coverage files, but only on the CI (GitHub actions).  
I previously created a [bug ticket](https://github.com/vitest-dev/vitest/issues/4943) that was supposedly [fixed](https://github.com/vitest-dev/vitest/pull/5022), yet I'm still having the same issues.

```
⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯
Error:  Error: ENOENT: no such file or directory, open '/home/runner/actions-runner/_work/x/.tmp/coverage-9.json'
Error:  ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error:  Serialized Error: { errno: -2, code: 'ENOENT', syscall: 'open', path: '/home/runner/actions-runner/_work/x/.tmp/coverage-9.json' }
````

Note that I use Nx to run the tests.

### Reproduction

Complicated to reproduce.

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 97.91 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.asdf/installs/nodejs/20.12.2/bin/node
    npm: 10.5.0 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 8.15.6 - /opt/homebrew/bin/pnpm
  Browsers:
    Brave Browser: 124.1.65.126
    Chrome: 125.0.6422.176
    Safari: 17.5
  npmPackages:
    @vitejs/plugin-react: 4.3.1 => 4.3.1 
    @vitest/coverage-v8: 1.6.0 => 1.6.0 
    @vitest/ui: 1.6.0 => 1.6.0 
    vite: 5.3.1 => 5.3.1 
    vitest: 1.6.0 => 1.6.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by C0ZEN** [comment]
FYI @AriPerkkio, please let me know if there is something that I can do/test to help.

**Comment by AriPerkkio** [comment]
We'll need a setup that can reproduce this issue.

**Comment by AriPerkkio** [comment]
> Note that I use Nx to run the tests.

Is it possible that Nx is running multiple `vitest` commands at the same time? Having more than one parallel Vitest runs could conflict in a way that other test run cleans up the coverage reports from previous run. You would need to make sure [`coverage.reportsDirectory`](https://vitest.dev/config/#coverage-reportsdirectory) is unique between the parallel test runs.
