### ISSUE TITLE
Watch mode: Skip initial test run

### ISSUE THREAD

**Issue by Flonk** [vitest-dev/vitest#5908]
### Clear and concise description of the problem

I would like to run vitest in watch mode to develop tests, but I would like to not have to wait until all tests have ran.

### Suggested solution

Add a `--skip-initial` flag to `vitest watch`.

### Alternative

I am aware that one can use filters to run a single test spec for instance, but having to restart vitest to change the filter in my case implies restarting a heavy docker container.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
There is [`--standalone`](https://vitest.dev/guide/cli.html#options) flag that does this.
