### ISSUE TITLE
[Bug]: `vitest` tries to run Playwright tests

### ISSUE THREAD

**Issue by hamirmahal** [vitest-dev/vitest#5927]
### Describe the bug

`vitest` tries to run Playwright tests.

### Reproduction

https://github.com/hamirmahal/vitest-playwright

### System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 22.11 GB / 31.03 GB
    Container: Yes
    Shell: 5.1.16 - /usr/bin/bash
  Binaries:
    Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.9.0/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
    pnpm: 9.4.0 - ~/.local/bin/pnpm
  Browsers:
    Brave Browser: 124.1.65.133
  npmPackages:
    vitest: ^1.6.0 => 1.6.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hamirmahal** [comment]
https://github.com/microsoft/playwright/issues/31348 is related.

**Comment by hamirmahal** [comment]
To clarify, [the Playwright test passes without any issue](https://github.com/hamirmahal/vitest-playwright/actions/runs/9586231036/job/26433752478).

**Comment by hamirmahal** [comment]
[It's the `vitest` check that fails](https://github.com/hamirmahal/vitest-playwright/actions/runs/9586231036/job/26433752719#step:4:7).

**Comment by sheremet-va** [comment]
`test/responsiveness.spec.ts` matches the default [include](https://vitest.dev/config/#include): `'**/*.{test,spec}.?(c|m)[jt]s?(x)'`

**Comment by hamirmahal** [comment]
Is it worth opening a feature request for `vitest` to automatically skip Playwright tests?

**Comment by hamirmahal** [comment]
It'd be nice if `vitest` could automatically skip a file if it sees

```ts
import ... from "@playwright/test";
```

at the top or something.

**Comment by sheremet-va** [comment]
No, it is the developer's responsibility to organize their tests, we cannot assume how other tools work.
