### ISSUE TITLE
[Doc] examples/image-snapshot link is unavailable

### ISSUE THREAD

**Issue by LiaoJimmy** [vitest-dev/vitest#5930]
### Describe the bug

In Vitest Doc > Snapshot > Image Snapshots
https://vitest.dev/guide/snapshot.html#image-snapshots
The link examples/image-snapshot is unavailable
Current wrong link URL is https://github.com/vitest-dev/vitest/blob/main/examples/image-snapshot
![image](https://github.com/vitest-dev/vitest/assets/11155585/930cb885-11af-43a8-a42d-e956a4ff0841)

By the way, there is no link in doc markdown.
I think the website should be updated?
https://github.com/vitest-dev/vitest/blob/main/docs/guide/snapshot.md#image-snapshots
![image](https://github.com/vitest-dev/vitest/assets/11155585/f9a9fc42-c249-4457-a533-2c8d92dd1a18)

### Reproduction

Go to Vitest Doc > Snapshot > Image Snapshots
And click the The link examples/image-snapshot

### System Info

```shell
macOS 13.6.7 
Chrome 126.0.6478.62
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> By the way, there is no link in doc markdown.
> I think the website should be updated?

The fix will be released with Vitest 2.0.
