### ISSUE TITLE
The html reporter allows viewing the current use case code

### ISSUE THREAD

**Issue by wll8** [vitest-dev/vitest#5931]
### Clear and concise description of the problem

![image](https://github.com/vitest-dev/vitest/assets/28223260/96336c8c-d356-4993-83bc-deaf1f7837d8)

I hope that when I click on a use case, I can view the test code of the use case. It can bring the following benefits:

- It is equivalent to a usage example for users to refer to.
- It is equivalent to a code snippet, which helps developers quickly locate problems.
- Use cases are usage examples, which reduces the work of repeatedly writing sample code.

### Suggested solution

Suppose there is a use case `a`. When you click on the use case `a`, there is a parameter in the url, such as `?it=a`, which is used to mark the current use case. And you can view its corresponding code on the right.

I can paste the url link to other places, such as the usage document. When others click on this url, they can view the relevant information of the corresponding use case.

Even simply displaying the toString result of the test case function (ignoring other functions referenced within the function) is sufficient for participating in the example.

### Additional context

Its functionality is similar to [mochawesome](https://www.npmjs.com/package/mochawesome).

Test case code:

![image](https://github.com/vitest-dev/vitest/assets/28223260/93a7faaa-820b-48f8-bcbc-0f367bd7ae3c)

UI test results:

![image](https://github.com/vitest-dev/vitest/assets/28223260/36e306c9-6e29-4d87-94b7-f6d57ec6abf7)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Is it html reporter or dynamic Vitest UI? There is usually a `Code` tab already.

**Comment by wll8** [comment]
It is html report: `npx vite preview --outDir html`;
Not dynamic ui: `npx vitest --ui`;

And the existing `Code` tab shows the code of the entire `*.test.js` file, not the code of the current test case.

![image](https://github.com/vitest-dev/vitest/assets/28223260/dacda830-6047-4675-b53b-61237b3c0957)

**Comment by sheremet-va** [comment]
I don't really see any reason to add a separate tab to show just a small part of the code when we already show full code. The #5948 PR adds a way to scroll to the test line, - it should be enough to close this issue.

**Comment by wll8** [comment]
reason:
> I hope that when I click on a use case, I can view the test code of the use case. It can bring the following benefits:
>
> - It is equivalent to a usage example for users to refer to.
> - It is equivalent to a code snippet, which helps developers quickly locate problems.
> - Use cases are usage examples, which reduces the work of repeatedly writing sample code.

I'm not sure if that PR has the ability to view the code for the current use case (rather than the code for the entire file) in the html report.

There are more reasons to allow viewing of only the current use case, for example:

- [HTML anchor link, Based on it, people created single-page applications.](https://www.rapidtables.com/web/html/link/html-anchor-link.html)
- [mocha ui (weekly downloads over a million) reports only show the current use case code by default](https://github.com/adamgruber/mochawesome/blob/HEAD/docs/marge-report-1.0.1.png?raw=true)
- [markdown has the function of navigating by chapter](https://github.com/vitest-dev/vitest/assets/28223260/efe6882d-4c23-4e68-b49a-b39e30a95903)
- [vscode/github provides the function of navigating functions when viewing code](https://code.visualstudio.com/docs/editor/editingevolved#_go-to-symbol)
- [Chrome provides the ability to navigate to a text location](https://support.google.com/chrome/answer/10256233)

These features clearly demonstrate the usefulness of allowing navigation to a certain content.
