### ISSUE TITLE
Parallelism options don't work when run in workspace mode.

### ISSUE THREAD

**Issue by niba** [vitest-dev/vitest#5933]
### Describe the bug

I have monorepo and in one of my packages I have this configuration vitest.config.integration.ts

```ts
export default defineConfig({
  test: {
    environment: "node",
    name: `${packageJson.name}_integration`,
    ... some more options
    sequence: {
      hooks: 'list',
    },
    maxWorkers: 1,
    minWorkers: 1,
    fileParallelism: false,
    maxConcurrency: 1,
  },
  plugins: [swc.vite()],
});

```

when I run it using `vitest` from the root of monorepo using vite.workspaces (scan packages/*/vitest.config.integration.ts and also vitest.config.unit.ts) then disabling fileParallelism doesn't work (i'm not sure about other settings).

when I use `vitest --config path-to-config` then it respects the above options and don't do any parallelism.

### Reproduction

Should I prepare reproduction for this case?

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 51.61 MB / 32.00 GB
    Shell: 3.7.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 20.10.0 - ~/Library/Caches/fnm_multishells/40574_1718863130062/bin/node
    Yarn: 3.3.1 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/40574_1718863130062/bin/npm
    pnpm: 9.4.0 - ~/Library/pnpm/pnpm
    bun: 1.0.27 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 118.1.59.117
    Edge: 126.0.2592.61
    Safari: 17.3.1
  npmPackages:
    @vitest/ui: 1.6.0 => 1.6.0 
    vitest: 1.6.0 => 1.6.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`maxWorkers`, `minWorkers` and `fileParallelism` are not supported in a workspace project config. Documentation needs to be updated to mention that.

**Comment by oberbeck** [comment]
I was running into the same issue. Do we have a workaround for this?
