### ISSUE TITLE
Reporter live output for chess Perft scores

### ISSUE THREAD

**Issue by KevinDoughty** [vitest-dev/vitest#5967]
### Clear and concise description of the problem

This is the problem: “When all tests have finished running, the final terminal output will display a summary of results and details of any failed tests”.

Perft scores are a type of test for chess engines. An example of a single test looks like this:
```
r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1 ;D1 48 ;D2 2039 ;D3 97862 ;D4 4085603 ;D5 193690690 ;D6 8031647685
```
From a position written in FEN (Forsyth Edwards Notation), the number of cumulative valid moves at a certain depth are checked. In this example, at depth 6, there are 8,031,647,685 valid moves. It takes time.

### Suggested solution

It would be nice to have a progress indicator in the form of real-time feedback as each one of these passes, outputting the FEN string, not just real-time output as any fail as is supposedly the case with --reporter=basic, or just hanging there until the very end.

### Additional context

Related:
https://github.com/vitest-dev/vitest/issues/3732
https://github.com/vitest-dev/vitest/issues/3549
https://github.com/vitest-dev/vitest/issues/4339

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by KevinDoughty** [comment]
I ended up pulling out the non-UI chess rules and move validation code into a separate module, and rolled my own basic tests not using Vite or VItest. I plan to use Vite, and maybe Vitest, with the UI code later.

**Comment by sheremet-va** [comment]
I don't understand what you want here. Do you want to print the test error with a stack trace immediately? `basic` reporter prints only the error message I think

**Comment by KevinDoughty** [comment]
I wanted to see the output, in real time, including passing tests. One test passes then outputs the test name or something, maybe in green, while more tests still remain to be run. A workaround was not using Vitest and rolling my own given my requirements were very basic.

Sorry to bother you, I will undoubtedly use Vitest in the future.
