### ISSUE TITLE
Add option to exclude all files and folders mentioned in `.gitignore`

### ISSUE THREAD

**Issue by charludo** [vitest-dev/vitest#5969]
### Clear and concise description of the problem

Git-ignored files will often (usually?) not need to be tested. At the same time however, they can lead to errors when included in vitest.

### Suggested solution

Add a configurable option to consume and respect `.gitignore`.

### Additional context

I've seen the discussion in #442, and am not suggestiong to enable this by default. It would just be a useful feature to have and use when you need it.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
What exactly is the use case for this? 

- Do you have test files that are listed in `.gitignore` and Vitest keeps running those tests?
- Do you have source files that are listed in `.gitignore` and also imported by tests or other sources files, and changing those ignored files ends up re-running the tests?

**Comment by sheremet-va** [comment]
If you want to have all files from `.gitignore` not be considered a test file ([`exclude`](https://vitest.dev/config/#exclude) option only affects test file glob matching), you can use `parse-gitignore` package:

```ts
import { configDefaults, defineConfig } from 'vitest/config'
import gitignore from 'parse-gitignore'
import { readFileSync } from 'node:fs'

export default defineConfig({
  test: {
    exclude: [
      ...configDefaults, 
      ...parse(readFileSync('.gitignore', 'utf-8')),
    ],
  }
})
```

**Comment by charludo** [comment]
> What exactly is the use case for this?
> 
>     * Do you have test files that are listed in `.gitignore` and Vitest keeps running those tests?
> 
>     * Do you have source files that are listed in `.gitignore` and also imported by tests or other sources files, and changing those ignored files ends up re-running the tests?

The situation that prompted me to open this issue was that files inside `.direnv` are picked up by vitest. I'm not super familiar with direnv, but it appears that source files get linked/mirrored within it.

So instead of just testing
```
src/static/js/__tests__/my-file.test.ts`
```
vitest will also attempt to test
```
.direnv/flake-inputs/sidsuihfuefhb/src/static/js/__tests__/my-file.test.ts`
```

Since the direnv is already in `.gitignore`, it would have been nice if the folder got excluded automatically as well.

**Comment by charludo** [comment]
> If you want to have all files from `.gitignore` not be considered a test file ([`exclude`](https://vitest.dev/config/#exclude) option only affects test file glob matching), you can use `parse-gitignore` package:
> 
> ```ts
> import { configDefaults, defineConfig } from 'vitest/config'
> import gitignore from 'parse-gitignore'
> import { readFileSync } from 'node:fs'
> 
> export default defineConfig({
>   test: {
>     exclude: [
>       ...configDefaults, 
>       ...parse(readFileSync('.gitignore', 'utf-8')),
>     ],
>   },
> })
> ```

Oh, good idea, thank you!

**Comment by sheremet-va** [comment]
`.gitignore` is not related to testing, so I don't think we can have a built-in switch. You can still use custom solutions as I mentioned.
