### ISSUE TITLE
Relative Coverage Path

### ISSUE THREAD

**Issue by yracnet** [vitest-dev/vitest#5973]
### Describe the bug

When publishing the `/target directory` (output directory for tests and coverage) to GitHub Pages, the site appears to function correctly. However, when clicking on the coverage link, it directs to an absolute path instead of the expected relative path within the same server.

### Reproduction

On the site https://yracnet.github.io/ci01-uargm/, the coverage link points to https://yracnet.github.io/coverage instead of the correct path https://yracnet.github.io/ci01-uargm/coverage/.

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 6800H with Radeon Graphics
    Memory: 19.86 GB / 31.25 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    bun: 1.1.7 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @vitejs/plugin-react-swc: ^3.5.0 => 3.7.0 
    @vitest/coverage-v8: ^1.6.0 => 1.6.0 
    @vitest/ui: ^1.6.0 => 1.6.0 
    vite: ^5.2.0 => 5.3.1 
    vitest: ^1.6.0 => 1.6.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
We'll need to see the `vitest.config.ts` in order to debug this. It's not present on https://github.com/yracnet/ci01-uargm/tree/main and the UI reporter is not used at all.

This should have been fixed in https://github.com/vitest-dev/vitest/pull/4717 but without seeing the used configuration I'm not sure if this is still a valid bug.
