### ISSUE TITLE
iTerm2 clear screen does not clear the screen properly

### ISSUE THREAD

**Issue by kxalex** [vitest-dev/vitest#5977]
### Describe the bug

iTerm2 does not clear the screen properly when vitest is running in watch mode.

### Reproduction

Use iTerm2 under Mac.

Run vitest on any project and on re-run not whole screen was cleared, there are some leftovers from previous run.

vitest currently uses to clear the screen and erase scrollback.
```
this.console.log(`${CLEAR_SCREEN}${ERASE_SCROLLBACK}${message}`)
```

iTerm2 reacts properly on that sequence, although clear screen sequence leaves 1 page visible and erase scrollback removes the history leaving this not-cleared page.

By flipping the sequence iTerm2 behaves properly.
```
this.console.log(`${ERASE_SCROLLBACK}${CLEAR_SCREEN}${message}`)
```

I've added changes in this PR against 1.6.0 version. Although I'm still using 1.5.3 due to cloudflare limitations.

https://github.com/vitest-dev/vitest/pull/5978/files

The erase scrollback and clear screen can be tested in shell using
```
printf '\e[3J' && printf '\x1Bc' # does not clear all screen
printf '\x1Bc' && printf '\e[3J' # clears everything
```
This was also tested on default macos terminal and it works fine too.

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M2 Pro
    Memory: 65.22 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.2.0 - /opt/homebrew/bin/node
    npm: 10.7.0 - /opt/homebrew/bin/npm
    pnpm: 9.4.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Brave Browser: 125.1.66.118
    Chrome: 126.0.6478.116
    Safari: 17.5
  npmPackages:
    @vitest/monorepo:  1.5.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
This issue also came up during https://github.com/vitest-dev/vitest/issues/1183#issuecomment-1573201532 and it also happens on Jest https://github.com/vitest-dev/vitest/pull/3661#issuecomment-1610761904.

**Comment by AriPerkkio** [comment]
I'm unable to reproduce this issue anymore at all. Please include a minimal test case that could be used to reproduce this issue.

**Comment by kxalex** [comment]
@AriPerkkio 

Here's repo https://github.com/kxalex/young-hill-9b37
cloudflare supports 1.5.3 for now, but you can change to 1.6.0 and will get the same result.

Also adding demo video where the half of the screen is not-cleared because those values needs to be flipped.

https://github.com/vitest-dev/vitest/assets/284411/f1cd25fb-2ebf-461a-be9c-7e6b8a2476cd

**Comment by AriPerkkio** [comment]
Thanks for the setup, I can reproduce the issue now.

Also worth to note that this issue seems to only come up in iTerm2. Mac's default Terminal and VSCode's terminal seem to work just fine.
