### ISSUE TITLE
Random tests failing due to "Fail to parse source" error

### ISSUE THREAD

**Issue by esivan-cloudinary** [vitest-dev/vitest#5979]
### Describe the bug

Some random tests are failing with the error:
```
Error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
```
![image](https://github.com/vitest-dev/vitest/assets/110837677/d594db2d-073a-4d48-96e1-7546b804057a)

There is no reference to the file that actually was vitest failed to parse (a file that has `.js` format instead of `.jsx`).
This is the file that was failed:
![image](https://github.com/vitest-dev/vitest/assets/110837677/91388b5a-b1ca-43a1-a80b-1b9b7fb73b2d)

I spent a few hours understanding the actual error and tracking the file, it would be really helpful if the error could be referenced.

### Reproduction

Just follow the same scenario as in the description

### System Info

```shell
System:
    OS: macOS 13.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 62.52 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.6.1 - ~/.nvm/versions/node/v20.6.1/bin/node
    npm: 9.8.1 - ~/.nvm/versions/node/v20.6.1/bin/npm
    pnpm: 9.4.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.116
    Chrome Canary: 128.0.6556.2
    Safari: 16.6
  npmPackages:
    @vitejs/plugin-react: ^4.1.0 => 4.1.0 
    vitest: ^1.0.0-beta.3 => 1.0.0-beta.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Wizzel1** [comment]
@esivan-cloudinary did you find a solution. I am getting the same error just by importing .ts files into my tests...
