### ISSUE TITLE
there is no file coverage if there are no tests for it

### ISSUE THREAD

**Issue by bad4iz** [vitest-dev/vitest#5991]
### Describe the bug

there is no file coverage if there are no tests for it. 

in my example there is a file src/new-file.ts, there are no tests for it. when I change it or create a new file for which there are no tests. These files are not included in the coverage. Should be covered though.

Using the command `yarn vitest --coverage.enabled=true --changed` or `yarn vitest --coverage.enabled=true --changed=develop`

### Reproduction

https://stackblitz.com/~/github.com/bad4iz/vitest-dev-vitest-fpwn6e?file=src/new-file.ts&initialPath=/__vitest__/

https://github.com/bad4iz/vitest-dev-vitest-fpwn6e

### System Info

```shell
yarn test:coverage

yarn vitest --coverage.enabled=true --changed
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by bad4iz** [comment]
Strangely, it works now

**Comment by AriPerkkio** [comment]
> Strangely, it works now

Great! This is exactly why we ask for minimal reproductions.
