### ISSUE TITLE
can't inline commonjs module when it's a sub-dependency

### ISSUE THREAD

**Issue by HomyeeKing** [vitest-dev/vitest#5994]
### Describe the bug

in my reproduce repo, I import `rax-compat` at `src/index.ts` and the test file will import it to run test:

```ts
// src/index.ts

import RaxCompat from 'rax-compat';
console.log('RaxCompat', RaxCompat);


export const testFn = () => {
  console.log('import.meta.a ', import.meta.a);
  console.log('global.ddd', global.ddd);
  return import.meta.a === 1;
};

```

```ts
// test/foo.test.ts
import { testFn } from '@/index';
import { expect, it, vi } from 'vitest';

it('test', () => {
  testFn()
  expect(true).toBe(true);
});
```
after doing `pnpm run test`, vitest warn the `@ice/appear`(which is dependent on `rax-compat`) is a commonjs module
![image](https://github.com/vitest-dev/vitest/assets/49113249/0f03a827-6f23-4aa5-9122-53223c04eadc)

but the inline option not works.

one way to get pass is mock the source import, 
```ts
vi.mock('rax-compat',()=>{
  return {
    default:vi.fn()
  }
})
```
so TWO questions:
- why inline not works
- why can only mock `rax-compat` not `@ice/appear`

### Reproduction

https://github.com/HomyeeKing/vitest-repo/tree/rax-compat

### System Info

```shell
System:
    OS: macOS 14.4
    CPU: (8) arm64 Apple M1
    Memory: 210.02 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 9.9.2 - ~/.nvm/versions/node/v16.19.0/bin/npm
  Browsers:
    Chrome: 126.0.6478.127
    Edge: 126.0.2592.81
    Safari: 17.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> * why inline not works

`rax-compat` is externalized which means it leaves the Vitest context execution (this makes its dependencies unable to be inlined), so you need to also inline it manually.

> * why can only mock rax-compat not @ice/appear

Same reason.
