### ISSUE TITLE
Documentation comment test like Rust

### ISSUE THREAD

**Issue by aprosail** [vitest-dev/vitest#6004]
### Clear and concise description of the problem

Rust's documentation comment test, aka `doctest`, is really good for guaranteeing documentation accuracy and improving code maintainabilities. And I suggest to introduce such features into `vitest`.

### Suggested solution

For example:

```ts
/*
 * ```ts
 * import {it, expect} from 'vitest'
 * import {add} from 'xxx'
 * 
 * it('add', () => {
 *   expect(add()).toBe(0)
 *   expect(add(1)).toBe(1)
 *   expect(add(1, 2, 3)).toBe(6)
 * })
 * ```
 */
export function add(...args: number[]) {
  return args.reduce((a, b) => a + b, 0)
}
```

And when running vitest, it will test all code inside the documentation. In that case, the accuracy of the code example inside documentation comments will be guaranteed, and once reading the doc, people can easily understand how the function works, according to the example code rather than unnecessary descriptions written in natural languages (such as English).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
The team already gave our thoughts here: https://github.com/vitest-dev/vitest/issues/3035#issuecomment-2051246359
