### ISSUE TITLE
true coverage at launch --change

### ISSUE THREAD

**Issue by bad4iz** [vitest-dev/vitest#6020]
### Clear and concise description of the problem

when I launch vitest coverage --change=develop . I want there to be a true coverage of those files that are shown in the coverage. Now the dependency files that have not been changed do not correctly show the coverage. It is worth 0 in functions. If you run the full coverage, then there is not 0.

![image](https://github.com/vitest-dev/vitest/assets/16918043/058a0ebe-21ee-4e94-9b36-e4de3193746c)

![image](https://github.com/vitest-dev/vitest/assets/16918043/12b62cb8-6a90-4461-b368-14a39f288cb1)

### Suggested solution

I can't say exactly how to do it, but it may be worth running tests for those files that are included in the coverage statistics so that the coverage is true.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
To fix this we'll need to make major changes to `--changed`. https://github.com/vitest-dev/vitest/issues/5237#issuecomment-1962300345

That would change what files are run with `--changed` flag, depending whether `--coverage` flag was also run. I don't think any other test runner has implemented this. Jest works similar as Vitest does now.

**Comment by AriPerkkio** [comment]
The team decided that this is not something that we will be implementing. By implementing this users would very likely run into cases where most tests of the code base end up running due to file dependencies. For example if your new test is testing file that imports a common utility package, this change would make Vitest run all the test files that depend on that utility package in any way. It eventually ends up matching test run without `--changed` flag.

This is also something that Jest does not implement so alignment is OK.

**Comment by bad4iz** [comment]
can then show coverage only for changed files? only for those for which tests are run?

**Comment by AriPerkkio** [comment]
Using `--changed` will run only the files that are related to the changed files. Using `--coverage` with `--changed` will show coverage that those files covered. In https://github.com/vitest-dev/vitest/issues/5237 we added support for `coverage.all` to limit it's scope only to the related files.

If the test files that `--changed` flag picks are covering unchanged files, those will show up in the report as well. You can use `--coverage.include` and/or `--coverage.exclude` to limit those.

**Comment by bad4iz** [comment]
@AriPerkkio how do I automatically generate a list --coverage.include=file_name from the modified files of the feature and develop branch ?

**Comment by AriPerkkio** [comment]
That sounds like something `git` could provide for you.
