### ISSUE TITLE
Partially mocked function returning actual implementation

### ISSUE THREAD

**Issue by chrismooreajbell** [vitest-dev/vitest#6024]
### Describe the bug

In the repro example I have partially mocked the method `generateGetters`.

When I run my test I can see that in `getters.spec.ts` the `generateGetters` method returns  the `stageTasks` method as a mock (`getters.spec.ts` line 20).

However when I log `generateGetters` from `generateVuexCompatibleGetters` it's returning the actual `stageTasks` implementation (`getters.ts` line 22).

I would expect `generateGetters` from `generateVuexCompatibleGetters` to return the mock function.

Thanks in advance for any assistance you are able to offer.

### Reproduction

https://stackblitz.com/edit/node-icdcpa

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    vite: ^2.7.1 => 2.7.1 
    vitest: ^1.6.0 => 1.6.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is expected behavior: https://vitest.dev/guide/mocking.html#mocking-pitfalls
