### ISSUE TITLE
[Feature]: Allow Callbacks Passed to `before*`/`after*` to Return Anything

### ISSUE THREAD

**Issue by ITenthusiasm** [vitest-dev/vitest#6033]
### Clear and concise description of the problem

Right now, I have an `async` function that I use to create and start a server:

```ts
async function startServer(port) {
  // ...
}
```

Within a test file, I have a setup that looks something like this

```ts
describe("Description", () => {
  let server: Awaited<ReturnType<typeof startServer>>;

  beforeAll(async () => {
    server = await startServer(port);
  });

  afterAll(() => {
    server.close();
  });

  // ...
});
```

For brevity, I'd like to write my code like this instead:
```ts
describe("Description", () => {
  let server: Awaited<ReturnType<typeof startServer>>;

  beforeAll(async () => (server = await startServer(port)));
  afterAll(() => server.close());
  // ...
});
```

But I can't, because the current types for `before*`/`after*` forbid returning an actual value.

### Suggested solution

It would be great if these return types (for `before*` and `after*`) could be updated so that developers could shorthand their setup/teardown blocks. For simple setup/teardown steps, this would reduce the lines of code by 2 per function call (assuming a formatter like `Prettier` is being used).

### Alternative

Currently, developers can circumvent the problem by using [`void`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void). But the appearance of this operator in a codebase is usually considered a smell.

### Additional context

I _think_ that this change would make Vitest "more compatible" with Jest users (from a TypeScript perspective). However, I noticed from the [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void) that `beforeAll` accepts a cleanup function. So if this feature request was accepted, there'd probably need to be a proper `typeof` check put in place. (There might already be one in place.)

---

Search Words: `before after promise`
Related Issues: #2149

I can understand the reasoning for restricting `before*`, but I think it would still be nice if `after*` could be looser in its type (assuming that its return value is not operated on outside of a `Promise` check). Note: The `after*` consideration is why I'm keeping this issue separate instead of commenting on the old one.

<details>
  <summary>However, if I may plead my case:</summary>

> I think it's better to be strict in this case, because hooks implementation differs from jest, and if we don't throw for non-functions, users might wrongly think it is the same, and accidentally return a teardown function.

There are already footguns like this in Vitest. For example, the way that Vitest handles `Promise`s returned from mock functions is different from what Jest does. I consider the difference a _significant_ improvement, but it results in some tripping for developers migrating from Jest. At the end of the day, devs can't avoid reading the migration docs if they're coming from Jest.

If convenience can be afforded to developers by permitting 1-line arrow functions in all cases, I think it's potentially worth allowing the accident.

> TypeScript types also don't allow anything but a void/undefined/null/function.

I think for this, the types could just be updated, correct? But that hinges on the previous concern.
</details>

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
>  For example, the way that Vitest handles Promises returned from mock functions is different from what Jest does. I consider the difference a significant improvement, but it results in some tripping for developers migrating from Jest.

Vitest 2 actually doens't do that anymore: https://main.vitest.dev/guide/migration.html#accessing-resolved-mock-results

**Comment by ITenthusiasm** [comment]
Ah, I didn't realize V2 already had migration docs. That's helpful to know. (Thanks for still giving us access to both the original `Promise` and the settled result though! 🙏🏾)

**Comment by MoeNeuron** [comment]
@sheremet-va I would like to help out here. Could I get assigned to me?
