### ISSUE TITLE
Vitest UI 2.0 has broken peer dependencies

### ISSUE THREAD

**Issue by Fryuni** [vitest-dev/vitest#6050]
### Describe the bug

```
packages/modular-station
└─┬ @vitest/ui 2.0.0
  └─┬ vue-virtual-scroller 2.0.0-beta.8
    ├── ✕ missing peer vue@^3.2.0
    ├─┬ vue-resize 2.0.0-alpha.1
    │ └── ✕ missing peer vue@^3.0.0
    └─┬ vue-observe-visibility 2.0.0-alpha.1
      └── ✕ missing peer vue@^3.0.0
Peer dependencies that should be installed:
  vue@">=3.2.0 <4.0.0-0"
```

`@vitest/ui` depends on `vue-virtual-scroller` but not on `vue`.

### Reproduction

Run `pnpm upgrade -L` to get the latest version

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (4) x64 Intel(R) Core(TM) i3-1000NG4 CPU @ 1.10GHz
    Memory: 118.36 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
    pnpm: 9.5.0 - ~/.nvm/versions/node/v20.15.0/bin/pnpm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
It should not depend on any browser package 🤔
