### ISSUE TITLE
Cannot find module - PNPM, Monorepo

### ISSUE THREAD

**Issue by javeoff** [vitest-dev/vitest#6055]
### Describe the bug

I have pnpm packages in monorepo, and when I am using `latest` or `*` version overwise `workspace:*` for my workspace packages, I have an error.

FAIL  lib/tests/createTransaction.test.ts [ lib/tests/createTransaction.test.ts ]
Error: Cannot find module '/Users/bondarev/projects/cryptoscan-pro/node_modules/.pnpm/@cryptoscan+solana-send-transaction@0.1.3_bufferutil@4.0.8_typescript@5.5.3_utf-8-validate@5.0.10/node_modules/@cryptoscan/solana-send-transaction/dist/createConnection' imported from /Users/bondarev/projects/cryptoscan-pro/node_modules/.pnpm/@cryptoscan+solana-send-transaction@0.1.3_bufferutil@4.0.8_typescript@5.5.3_utf-8-validate@5.0.10/node_modules/@cryptoscan/solana-send-transaction/dist/index.js

### Reproduction

change package to `latest` or `*` version overwise `workspace:*` in monorepo

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 65.66 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
    pnpm: 9.4.0 - ~/.nvm/versions/node/v18.17.0/bin/pnpm
  Browsers:
    Safari: 16.3
  npmPackages:
    @vitest/ui: ^1.6.0 => 1.6.0
    vitest: ^1.6.0 => 1.6.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by javeoff** [comment]
I made reproduction and saw that problem is not in vitest.

**Comment by szedelenyi** [comment]
@javeoff can you share how did you solve it? We are facing a similar `Error: Cannot find module` issue in our monorepo upon upgrading vitest

**Comment by javeoff** [comment]
> @javeoff can you share how did you solve it? We are facing a similar `Error: Cannot find module` issue in our monorepo upon upgrading vitest

You need to change your app to node16 format, because some dependencies has error with interacting with classic format

```
                 "module": "node16",
		"moduleResolution": "node16",
		"moduleDetection": "force",
		"target": "ES2022",
```

I could be wrong. But many opensource have node16 compiler and have '*.js' in imports

**Comment by szedelenyi** [comment]
@javeoff Thanks, we solved it by adding the following lines for `vite.config.mts`' `test` section for each project depending on the problematic dependency:
```
    server: {
      deps: {
        inline: [/name-of-the-dependency-mentioned-in-the-error/],
      },
    }
```
