### ISSUE TITLE
@vitest/coverage-istanbul runs excluded files

### ISSUE THREAD

**Issue by MKhasib** [vitest-dev/vitest#6058]
### Describe the bug

I am migrating from jest to vitest in a private repo where I used the following config
```
defineConfig({
test:{
    exclude: ['**/*.vue'],
    coverage: {
      all: false,
      provider: 'istanbul',
      exclude: [
        '**/*.vue',
      ],
      include: [
        '**/*.js'
       ]
```
However, coverage-istanbul instrument picks up vue files used inside the `.js` test files and adds it to the total coverage report
Is there a way to exclude all vue files used inside .js tests from getting into the final coverage report?

### Reproduction

import any .vue file inside a test .js file

### System Info

```shell
    "@vitest/coverage-istanbul": "^1.6.0",
    "vitest": "^1.6.0",
    "vite": "^5.2.11",
    "vite-plugin-istanbul": "^5.0.0",

```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by MKhasib** [comment]
@AriPerkkio Do you have any ideas on how to fix this issue? Thanks!
Ps: I read all vitest docs, debugged inside vitest instrumenting libs but with no luck

**Comment by kwojcik** [comment]
try including the default exclusions

```
import { coverageConfigDefaults } from "vitest/config";

...

      exclude: [
        '**/*.vue',
         ...coverageConfigDefaults.exclude
      ],
```

**Comment by AriPerkkio** [comment]
The (partial) configuration shown in description is enough to solve this. Only `**/*.js` files should appear in coverage report. The `exclude` part is not needed, as `include: ['**/*.js']` already excludes `*.vue`.

**Comment by AriPerkkio** [comment]
What's `vite-plugin-istanbul` doing there? It's not a package that Vitest maintains. It's likely causing this issue as it doesn't use `vitest.config.ts` at all.

**Comment by MKhasib** [comment]
@AriPerkkio Thanks for the quick response, I tried creating a reproducible repo but it seemed vitest included in coverage is working as expected just in the new repo. I am investigating why it doesn't on the private repo(actually it does exclude some files but not all)

I will close this issue for now, thank you soo much for the help!
