### ISSUE TITLE
Vitest UI doesn't render tests initially

### ISSUE THREAD

**Issue by rothsandro** [vitest-dev/vitest#6065]
### Describe the bug

Starting Vitest with the `--ui` parameter will open the Vitest UI and run all tests, but the UI doesn't show any tests. I have to reload the UI in the browser to see the tests. This only happens after updating to Vitest UI 2.x

![image](https://github.com/vitest-dev/vitest/assets/16229645/4ff0fc24-55be-429f-9ed4-46e405375e32)

### Reproduction

Can be reproduced with the StackBlitz demo you provide: https://stackblitz.com/edit/vitest-dev-vitest-q9metk?file=README.md&initialPath=__vitest__/

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: latest => 2.0.1 
    vite: latest => 5.3.3 
    vitest: latest => 2.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
The ui is faster than server logic, we need to include files if not loaded on initial ws connection

**Comment by devbucket** [comment]
Maybe it's only me, but I do not understand this answer.
I am facing the same issue, as the UI is not showing any tests. Only when refreshing the browser, does it. But still, then it does not automatically update when the tests are still running.

**Comment by sheremet-va** [comment]
> Maybe it's only me, but I do not understand this answer.
> 
> I am facing the same issue, as the UI is not showing any tests. Only when refreshing the browser, does it. But still, then it does not automatically update when the tests are still running.

This is a bug. Expect a fix in the next version
