### ISSUE TITLE
vitest browser mode does not work with Rush monorepo manager

### ISSUE THREAD

**Issue by cuberoot** [vitest-dev/vitest#6071]
### Describe the bug

Vitest's browser mode does not seem to be compatible with Rush. When I try to run vitest in browser mode in one of my Rush monorepo's, I get errors like this in the console:
```
GET http://localhost:5173/__vitest_browser__/orchestrator-x0A1t8rC.js net::ERR_ABORTED 404 (Not Found)
```

When I take the same package and use vanilla pnpm instead, it works fine. Something about the Rush environment must interfere with vitest somehow.

### Reproduction

- Install rush `npm install -g @microsoft/rush`
- clone [my example repo](https://github.com/cuberoot/rush-vitest-browser) `git clone git@github.com:cuberoot/rush-vitest-browser.git`
- `cd rush-vitest-browser`
- `rush install`
- `cd libraries/my-controls`
- `rushx test`

This should open up a blank white browser window. If you look in the dev tools console, you will see an error like:

```
GET http://localhost:5173/__vitest_browser__/orchestrator-x0A1t8rC.js net::ERR_ABORTED 404 (Not Found)
```

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 116.17 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 9.5.0 - ~/.nvm/versions/node/v18.16.0/bin/pnpm
    bun: 1.1.4 - ~/.bun/bin/bun
  Browsers:
    Chrome: 126.0.6478.127
    Chrome Canary: 128.0.6586.0
    Firefox Nightly: 127.0a1
    Safari: 17.5
    Safari Technology Preview: 17.4
  npmPackages:
    @vitest/browser: ~2.0.1 => 2.0.1 
    vitest: ~2.0.1 => 2.0.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AttilaBognar91** [comment]
We have the same problem with yarn so probably not an issue with rush.

**Comment by sheremet-va** [comment]
It looks like this is an issue with `fs.allow` in `rush` specifically - because of the structure of `node_modules`, Vite thinks it's outside of the root. We should be able to fix this on Vitest side, but for now, you can try disabling `fs.strict` in the config: https://vitejs.dev/config/server-options.html#server-fs-allow
