### ISSUE TITLE
userEvent.keyboard always releases pressed key with playwright provider

### ISSUE THREAD

**Issue by edoardocavazza** [vitest-dev/vitest#6082]
### Describe the bug

I am trying to use the new Interactive API to test the behavior of a button.
It seems that every keyboard command [is automatically released](https://github.com/vitest-dev/vitest/blob/a169d25a922936fabb603173337455ed6d59e86f/packages/browser/src/node/commands/keyboard.ts#L100) even when using the `{Enter>}` syntax.

### Reproduction

https://github.com/edoardocavazza/vitest-keyboard

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 261.33 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 8.6.3 - ~/Library/pnpm/pnpm
    bun: 1.0.30 - ~/.bun/bin/bun
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.2.1
  npmPackages:
    @vitest/browser: ^2.0.1 => 2.0.1 
    vitest: ^2.0.1 => 2.0.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Hmm, you are right. It should only be released in `.type`:

https://github.com/testing-library/user-event/blob/main/src/utility/type.ts#L40

**Comment by edoardocavazza** [comment]
Hi @sheremet-va, thanks for the fix!
I have investigated why the second part of the test wont work even with the original user-event library.
I have found out that using the direct api (e.g. `userEvent.keyboard()`) will create a new context for each call, so it loses the pressed keys state.

It works as expected when using the `setup()` method:
```
const device = userEvent.setup();
await userEvent.keyboard('{Enter>}');
// triggers the keyup event
await userEvent.keyboard('{Enter/}');
```
Any plan to support the `setup` method?

**Comment by edoardocavazza** [comment]
Alternatively, IMHO it would be better if vitest kept the state of pressed keys. Since the interaction using playwright/webdriver is not emulated, the key actually reamains unreleased forever 😅

**Comment by sheremet-va** [comment]
Interesting! I didn't know how `userEvent` keeps this under the hood, but it might be hard to replicate this specific behavior since it's done server side (maybe we can return the state somehow).

I agree it should work more like `userEvent.setup().keyboard()`

> Any plan to support the setup method?

Currently `setup` just returns the same `userEvent`, not sure how we can support it fully and if we really need to.

**Comment by sheremet-va** [comment]
I think what happens with `.setup` is that this line is called:

https://github.com/testing-library/user-event/blob/d0362796a33c2d39713998f82ae309020c37b385/src/keyboard/index.ts#L30

In Vitest currently it's scoped to the same `keyboard` call:

https://github.com/vitest-dev/vitest/blob/99a12aec2bb3baf361bf15afb2a9df9b0938518b/packages/browser/src/node/commands/keyboard.ts#L76
