### ISSUE TITLE
The simplified `MockInstance<T>` type does not work with function overloads

### ISSUE THREAD

**Issue by xsjcTony** [vitest-dev/vitest#6085]
### Describe the bug

It won't work with function overloads, refer to the reproduction.

### Reproduction

type error in `v2`
https://stackblitz.com/edit/vitest-dev-vitest-hlq3zj?file=test%2Fbasic.test.ts

No type error in `v1`, but seems the other overload signature is being ignored
https://stackblitz.com/edit/vitest-dev-vitest-cayu3q?file=test%2Fbasic.test.ts

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 7.79 GB / 31.69 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.5.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Thanks for the report. I haven't thought about this case.

Similar code on Jest has no type errors, but it looks like it still has some limitations with function overloads.

```ts
test("overload", () => {
  // they have dedicated `Spied` type to align `spyOn` return type.
  // so assignment works fine
  let spy: jest.Spied<Element["scrollTo"]>
  spy = jest.spyOn(Element.prototype, "scrollTo");

  // but only 2nd overload argument types
  spy.mock.calls satisfies [x: number, y: number][];

 
  // for `Mock`, probably Vitest and Jest work same.
  let mockFn: jest.Mock<Element["scrollTo"]>;
  mockFn = jest.fn(Element.prototype.scrollTo);
  
  mockFn(0, 1); // 2nd overload ok
  
  // @ts-expect-error
  mockFn({ top: 0 }); // 1st overload error
})
```

Probably this comes down to `Parameters` picking up only one of the overload 

```ts
type OverloadFn = {
  (x: number, y: number): void;
  (someOptions?: { top?: number }): void;
}

// this becomes `[x: number, y: number]`
type OverloadArgs = Parameters<Element["scrollTo"]>
```

**Comment by xsjcTony** [comment]
That's true. Like I provided above, even in `v1`, because that I'm using `Parameters<T>` manually, hence there's no type error because only 1 overload is picked up, but truly it is the limitation, since `.mockImplementation()` won't support another overload in that case.

**Comment by xsjcTony** [comment]
Seems like a hard limitation there, emmm,..... 🤦‍♀️
![image](https://github.com/vitest-dev/vitest/assets/45784210/8f7e3456-5bb7-43d2-974a-330a0c29a587)

**Comment by xsjcTony** [comment]
But I think at least we should try to find a way to avoid the type error there, and maybe document the TS limitation on function overloads

**Comment by hi-ogawa** [comment]
This type mismatch is probably because we split types here `MockInstance<(this: R, ...args: A) => R>`. If we can somehow preserve it as` MockInstance<T[M]>`, then typescript won't probably complain.

https://github.com/vitest-dev/vitest/blob/99a12aec2bb3baf361bf15afb2a9df9b0938518b/packages/spy/src/index.ts#L401-L408
