### ISSUE TITLE
cannot mock spyOn namespace import in browser mode

### ISSUE THREAD

**Issue by kwojcik** [vitest-dev/vitest#6099]
### Describe the bug

If you use `spyOn` on a namespace import you get this error `TypeError: Cannot redefine property:`. This seems to work fine in `jsdom` environment, but not browser mode.

Workaround that still gives you the behavior of `spyOn` if you need a "default call original" behavior:
```
import { expect, it, vi } from "vitest";
import { one } from "./basic.js";

vi.mock("./basic.js", async (importActual) => {
  const actual = await importActual<typeof import("./basic.js")>();
  return {
    ...actual,
    one: vi.fn().mockImplementation(actual.one),
  };
});
it("test", () => {
  vi.mocked(one).mockReturnValue(2);
  expect(one()).toBe(2);
});
```

### Reproduction

```
import { expect, it, vi } from "vitest";
import * as thing from "./basic.js";

it("test", () => {
  vi.spyOn(thing, "one").mockReturnValue(2);
  expect(thing.one()).toBe(2);
});
```

basic.js
```
export function one() {
  return 1;
}
```

```
 FAIL  test/basic.test.tsx > test
TypeError: Cannot redefine property: one

Failure screenshot:
  - test/__screenshots__/basic.test.tsx/test-1.png

 ❯ test/basic.test.tsx:5:5
      3|
      4| it("test", () => {
      5|   vi.spyOn(thing, "one").mockReturnValue(2);
       |     ^
      6|   expect(thing.one()).toBe(2);
      7| });
```

### System Info

```shell
System:
    OS: macOS 13.6.7
    CPU: (12) arm64 Apple M2 Max
    Memory: 4.92 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.asdf/installs/nodejs/18.18.2/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 6.32.8 - /opt/homebrew/bin/pnpm
    Watchman: 2024.04.01.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 126.0.6478.127
    Firefox Nightly: 127.0
    Safari: 16.6
  npmPackages:
    @vitest/browser: 2.0.2 => 2.0.2
    @vitest/ui: 2.0.2 => 2.0.2
    vite: latest => 5.3.2
    vitest: 2.0.2 => 2.0.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest Browser Mode (called `slowHijackESM`) previously had a mode when it was possible, but it made the runner slower and introduced subtle bugs that were hard to find. We effectively had to maintain a separate ESM environment. In the release version, we removed this flag in favor of using `vi.mock`.

Just calling `vi.mock` doesn't replicate the behavior because it overrides the implementation, but maybe we can add a flag to wrap the methods instead of overriding them:

```ts
vi.mock("./basic.js", { spy: true })
```

**Comment by kwojcik** [comment]
I'm not necessarily requesting this feature (since there is a workaround), just encountered it while moving to browser mode. If you decide against this then just having a nice error message that says it's not supported and suggestion of what to do instead would be great.
