### ISSUE TITLE
Cannot find type definition file for 'vitest/global'

### ISSUE THREAD

**Issue by beefchimi** [vitest-dev/vitest#610]
### Describe the bug

I am using `vite + vitest` in a small TypeScript project: [`socialite`](https://github.com/beefchimi/socialite)

It has been working great until today. I shipped a quick PR with some dependency bumps:
https://github.com/beefchimi/socialite/pull/42

In that PR, I bumped `vitest` from `"^0.1.19"` to `"^0.1.27"`. Ever since doing so, when I `build` my project, I get the following error:

```sh
error TS2688: Cannot find type definition file for 'vitest/global'.
  The file is in the program because:
    Entry point of type library 'vitest/global' specified in compilerOptions

  tsconfig.json:6:15
    6     "types": ["vitest/global"],
                    ~~~~~~~~~~~~~~~
    File is entry point of type library specified here.


Found 1 error.
```

### Reproduction

I recommend cloning and testing against my project, `Socialite`:

```sh
git clone git@github.com:beefchimi/socialite.git
cd socialite
npm install
npm run build
```

That _should_ produce the error I referenced above. You can then try downgrading `vitest` to `0.1.19` and see what happens.

### System Info

```shell
System:
  OS: Linux 5.13 Zorin OS 16
  CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Memory: 5.05 GB / 31.23 GB
  Container: Yes
  Shell: 5.8 - /usr/bin/zsh

Binaries:
  Node: 17.3.0 - ~/.nvm/versions/node/v17.3.0/bin/node
  Yarn: 1.22.15 - ~/.nvm/versions/node/v17.3.0/bin/yarn
  npm: 8.3.0 - ~/.nvm/versions/node/v17.3.0/bin/npm

Browsers:
  Brave Browser: 97.1.34.81
  Firefox: 96.0

npmPackages:
  vite: ^2.7.13 => 2.7.13 
  vitest: ^0.1.27 => 0.1.27
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It's renamed to `vitest/globals`
