### ISSUE TITLE
Ability to mimic spyOn default behavior with module mock

### ISSUE THREAD

**Issue by kwojcik** [vitest-dev/vitest#6100]
### Clear and concise description of the problem

When using vi.spyOn, the default behavior if no implementation or mock return value is provided is that it calls the original.

To mimic that with module mocking is verbose
```
vi.mock('...', async (importActual) => {
  const actual = await importActual<typeof import('...')>();
  return {
    ...actual,
    thingToSpyOn: vi.fn().mockImplementation(actual.thingToSpyOn)
  }
})
```

### Suggested solution

Add a new method to `MockInstance` that will call the original function, like `callOriginal` (name inspiration from rspec https://www.rubydoc.info/gems/rspec-mocks/RSpec%2FMocks%2FMessageExpectation:and_call_original). So that a module mock becomes more like
```
vi.mock('...', () => ({
  thingToSpyOn: vi.fn().callOriginal()
})
```

### Alternative

Implement `spyOn` on namespace imports in browser mode https://github.com/vitest-dev/vitest/issues/6099

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
`callOriginal` doesn't really make sense because that's what `mockRestore` does. The problem here is that `mockRestore` behaves differently with automocked modules specifically. I proposed another solution in #6099, so let's keep the discussion there.
