### ISSUE TITLE
@vitest/browser fails in Yarn PnP environment due to missing Vite dependency

### ISSUE THREAD

**Issue by SaeWooKKang** [vitest-dev/vitest#6101]
### Describe the bug

When using @viteest/browser in a `yarn pnp` environment, an error occurs that vite could not be found.

If you change nodeLinker to node-modules, it works fine, so I think this is due to one of the pnp functions, [Ghost dependencies protection](https://yarnpkg.com/features/pnp#ghost-dependencies-protection). Actually, when you check the code, package.json doesn't have a vite, but there is a code that you import and use from the vite. I think if you specify dependencies, it will work out. Actually, I cloned the project, specified dependencies, and tested it using npm link, and confirmed that it works fine.

### Reproduction

stackBlitz does not support yarn berry and replaces it with the command.

``` 
mkdir bug 

cd ./bug

yarn init -2

yarn add -D vitest

yarn exec vitest init browser // (all press Enter)

yarn test:browser
```

An error occurs.

```
Error: @vitest/browser tried to access vite, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 311.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    Yarn: 4.3.1 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
    Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Fixed in 35655419feb3bf77c137bf404d1882f7afc8b1f2

**Comment by SaeWooKKang** [comment]
@sheremet-va Thank you for the quick correction 👍 
It seems that one import path has not been changed. Is it okay?

https://github.com/vitest-dev/vitest/blob/bd83f6cadcf2f719f8b23dc0e26f83229173e596/packages/browser/src/client/vite.config.ts#L3

**Comment by sheremet-va** [comment]
Yes, it's not published.
