### ISSUE TITLE
module mock failure on react-router-dom in browser mode

### ISSUE THREAD

**Issue by kwojcik** [vitest-dev/vitest#6105]
### Describe the bug

When mocking `react-router-dom` in multiple test files, in browser mode, the mocks occasionally break and you get an error like `TypeError: [Function redirect2] is not a spy or a call to a spy!`. At least in the case of the repro below, this seems to happen nearly 100% of the time with `fileParallelism` set to false after the first test run, but rarely with `fileParallelism` set to true. But in my real app, `fileParallelism` doesnt seem to affect it and the mocks will break on the first test run (instead of after the first). Seems like there is some state leakage between test files in browser mode.

### Reproduction

Nearly 100% failure rate on this branch on test *reruns*

https://github.com/kwojcik/vitestsourcemapbug/tree/mockReactRouterDom

```
git checkout mockReactRouterDom
npm install
npm run test # press r to rerun, it only triggers after first try
```

### System Info

```shell
System:
    OS: macOS 13.6.7
    CPU: (12) arm64 Apple M2 Max
    Memory: 4.48 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.2 - ~/.asdf/installs/nodejs/18.18.2/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - ~/.asdf/plugins/nodejs/shims/npm
    pnpm: 6.32.8 - /opt/homebrew/bin/pnpm
    Watchman: 2024.04.01.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 126.0.6478.127
    Firefox Nightly: 127.0
    Safari: 16.6
  npmPackages:
    @vitest/browser: 2.0.2 => 2.0.2
    @vitest/ui: 2.0.2 => 2.0.2
    vite: latest => 5.3.2
    vitest: 2.0.2 => 2.0.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This looks like a race condition, but I cannot figure out why MSW doesn't intercept it the first time

**Comment by sheremet-va** [comment]
This is how request looks like in Chrome:

Fails:
<img width="855" alt="Screenshot 2024-07-12 at 16 17 32" src="https://github.com/user-attachments/assets/d92c891c-b3ab-4f4f-9625-a2248857468d">

Mocks:
<img width="863" alt="Screenshot 2024-07-12 at 16 17 36" src="https://github.com/user-attachments/assets/8670e596-2ffb-42c2-afdb-5a3cef5b6b64">
