### ISSUE TITLE
expect(...).toMatchSnapshot has typescript error since v2 of vitest 

### ISSUE THREAD

**Issue by zeid0ne** [vitest-dev/vitest#6114]
### Describe the bug

![image](https://github.com/user-attachments/assets/6dd1344a-e738-4f97-9260-90c1f445ffc3)
![image](https://github.com/user-attachments/assets/1369f6af-8c3b-4600-a94b-20084de50967)

### Reproduction

1) create a project with typescript (v5.3.3) and this tsconfig content :

```
{
    "compilerOptions": {
        "module": "commonjs",
        "emitDecoratorMetadata": true,
        "esModuleInterop": true,
        "experimentalDecorators": true,
        "allowSyntheticDefaultImports": true,
        "target": "es6",
        "noImplicitAny": true,
        "moduleResolution": "node",
        "sourceMap": true,
        "outDir": "dist",
        "baseUrl": ".",
        "paths": {
            "*": [
                "node_modules/*"
            ]
        }
    }
}

2) create a new test file with vitest v2.0.2

3) write expect(false).toMatchSnapshot() for example

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 8.27 GB / 15.85 GB
  Binaries:
    Node: 22.0.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - ~\AppData\Roaming\npm\npm.CMD
    pnpm: 9.1.2 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @vitest/ui: ^2.0.2 => 2.0.2
    vitest: ^2.0.2 => 2.0.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Try deleting node_modules and installing it again. This seems like a typescript issue, not Vitest one.

**Comment by zeid0ne** [comment]
that solved it thank you
