### ISSUE TITLE
`@vitest/web-worker` didn't transform `.wasm?url` in worker import

### ISSUE THREAD

**Issue by Zxilly** [vitest-dev/vitest#6118]
### Describe the bug

While test a WebWorker which imports wasm file with the syntax `.wasm?url`, the fetch in the WebWorker will finally get a raw path of wasm file.

![image](https://github.com/user-attachments/assets/89b42947-50b5-47c7-8af6-f1b09b4cd53e)

### Reproduction

```
git clone https://github.com/Zxilly/go-size-analyzer
cd go-size-analyzer/ui/
pnpm i

# remove the skip in worker/help.test.ts

vitest
```

Will got a `Error: Failed to parse URL from /gsa.wasm`

Here's the required wasm file. [gsa.zip](https://github.com/user-attachments/files/16201901/gsa.zip)

Should be placed under the /ui folder.

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor              
    Memory: 6.84 GB / 31.93 GB
  Binaries:
    Node: 22.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 4.1.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.8.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.4.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Chrome: 126.0.6478.127
    Edge: Chromium (126.0.2592.102)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @vitejs/plugin-react-swc: ^3.7.0 => 3.7.0 
    @vitest/coverage-istanbul: ^2.0.2 => 2.0.2 
    @vitest/web-worker: ^2.0.2 => 2.0.2 
    vite: ^5.3.3 => 5.3.3 
    vitest: ^2.0.2 => 2.0.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
`@vitest/web-worker` is only a web worker emulation on node runtime, so it doesn't deal with Vite client `?url` convention.

You might have a better chance running that with Vitest browser mode instead https://vitest.dev/guide/browser/

If you really need to test wasm binding on node (i.e. non browser mode), then it might require some restructuring like I suggested previously in a different issue https://github.com/vitest-dev/vitest/issues/5704#issuecomment-2126085518

**Comment by Zxilly** [comment]
I search the issue previously, seems the browser mode won't collect the coverage for the worker?

**Comment by hi-ogawa** [comment]
Right, I think you're referring this issue and coverage is not supported https://github.com/vitest-dev/vitest/issues/4899#issuecomment-1885288810

**Comment by Zxilly** [comment]
I created a hack to import the wasm in the normal test file and mock it to the worker, please see https://github.com/Zxilly/go-size-analyzer/commit/45149d986beb03bf9846a5adc6b166bc43cbfb4a

**Comment by Zxilly** [comment]
But I don't understand why in this case worker.ts is still not covered by coverage.

**Comment by Zxilly** [comment]
After switch to v8 coverage provider things got resolved.

**Comment by sheremet-va** [comment]
`?url` actually resolves the file as an absolute `pathname` (this is Vite feature, not Vitest). To make it a valid file you still need an origin like `http://localhost` - but since in Node.js there is no origin, you should probably resolve it to a `file://` yourself somehow.

Closing this as it's working as expected.

**Comment by Zxilly** [comment]
As `https://vitest.dev/guide/why.html` suggested

>  A test runner that uses the same configuration of your App (through ), sharing a common transformation pipeline during dev, build, and test time.

I think keep this behavior same between the vite and vitest is meaningful.

**Comment by sheremet-va** [comment]
This is why we keep the behaviour :) 

Vite and Vitest resolve the same value of import, but as I said in the previous comment, the environment where it runs is different and doesn't depend on Vite.

**Comment by sheremet-va** [comment]
> Vite and Vitest resolve the same value of import, but as I said in the previous comment, the environment where it runs is different, so how you use the value depends on your use case.

In your code you pass the value to `fetch` - in the browser, it resolves the URL relative to the server origin (`http://localhost`), but on the server `fetch` doesn't have this information and it requires a full URL :)

**Comment by Zxilly** [comment]
I understand that, maybe need to setup a transformer for node environment. Thanks.
