### ISSUE TITLE
correct type for `import { defineConfig } from 'vitest/config';` with `"type": "commonjs"`

### ISSUE THREAD

**Issue by Max10240** [vitest-dev/vitest#6129]
### Describe the bug

if you have a project with `"type": "commonjs"`, and configure `tsconfig.json` as follows:
// package.json
```json
{
  "name": "@vitest/example-test",
  "type":"commonjs"
}
```

// tsconfig.json
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "nodenext",
    "moduleResolution": "nodenext",
    "strict": true,
    "declaration": true,
    "declarationMap": true,
    "sourceMap": true,
    "noEmit": true,
    "skipLibCheck": true
  },
  "include": ["vitest.config.ts"],
  "exclude": ["node_modules"]
}
```

Now, you have a `vitest.config.ts`:
```tsx
/*
error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("vitest/config")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to '/home/projects/vitest-dev-vitest-izjvkc/package.json'.
*/
import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {},
});

```
Then you can see this error:
![image](https://github.com/user-attachments/assets/cf50628f-cb54-421f-98e4-5b44a5f23aff)

### Reproduction

[minimal reproduction](https://stackblitz.com/edit/vitest-dev-vitest-izjvkc?file=vitest.config.ts)

I try to solve it locally like this:
1. `cp node_modules/vitest/dist/config.d.ts node_modules/vitest/dist/config.d.cts`
2. modify `node_modules/vitest/package.json`:
![image](https://github.com/user-attachments/assets/8ff2a046-d2d6-40a0-a03d-41c019afb1b7)

it works, so it would be great if vitest could fix this on its own!

### System Info

```shell
no matter
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Max10240** [comment]
ps: I know that i can use `vitest.config.mts` to instead of `vitest.config.ts`, but it would be better if using `.ts` were allowed too :)

**Comment by sheremet-va** [comment]
The team thinks that bundling separate type files for cjs and mjs is not worth it in the short or long term. The cjs config is already deprecated and Vite will drop support for it config in the future.

I recommend naming your config `vitest.config.mts` or patching Vitest with your package manager.
