### ISSUE TITLE
Some coverage.exclude glob patterns not matching for vitest 2 workspace

### ISSUE THREAD

**Issue by programmer24601** [vitest-dev/vitest#6133]
### Describe the bug

I have an npm/vitest workspace configured with a couple of packages. Running `vitest run --coverage --silent` from root package with a vitest.config.ts of:
```typescript
export default defineConfig({
  test: {
    coverage: {
      exclude: [
        ...configDefaults.exclude,
      ]
    }
  }
```

vitest.workspace.ts is:
```typescript
export default defineWorkspace(['packages/*']);
```

should apply with glob pattern `'**/*{.,-}{test,spec,bench,benchmark}?(-d).?(c|m)[jt]s?(x)',`

but doesn't match this file: `/packages/backend/functions/bob/src/a/b/c/alice.test.ts`, which according to https://globster.xyz/ does match.

### Reproduction

See above.

### System Info

```shell
vitest 2.0.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
The documentation instructs to use `coverageConfigDefaults.exclude`, not `configDefaults.exclude`. https://vitest.dev/config/#coverage-extension

> This option overrides all default options. Extend the default options when adding new patterns to ignore:
> 
> ```ts
> import { coverageConfigDefaults, defineConfig } from 'vitest/config'
> 
> export default defineConfig({
>   test: {
>     coverage: {
>       exclude: ['**/custom-pattern/**', ...coverageConfigDefaults.exclude]
>     },
>   },
> })
> 

As the minimal reproduction is missing and the description's partial code snippet is missing where the `configDefaults`, I'm not sure what's going on there.

**Comment by programmer24601** [comment]
Okay, easy mistake. I've switched over to the correct exclusion set, but now my custom exclusion rules in `package/a/vitest.config.ts` are not being inherited by `<rootDir>/vitest.config.ts` when running all tests from the root.

**Comment by AriPerkkio** [comment]
Vitest workspaces have never inherited the coverage options from projects like that. It would really help if you set up a minimal reproduction showing what the issue is.
