### ISSUE TITLE
(v2) `Error: Failed to load url` when dynamic importing js files generated during tests with relative path

### ISSUE THREAD

**Issue by hi-ogawa** [vitest-dev/vitest#6152]
### Describe the bug

I was investigating a test failure when upgrading Vitest v2 in vite-plugin-react repo https://github.com/vitejs/vite-plugin-react/pull/347 and this seems to be the cause. 

```ts
//// src/repro.test.ts

// this works
test("absolute ok", async () => {
	await writeFile("src/generated.js", "export default 'hello'");
	const mod = await import(path.join(import.meta.dirname, "./generated.js"));
	console.log(mod);
});

// this is error
test("relative error", async () => {
	await writeFile("src/generated.js", "export default 'hello'");
	const mod = await import("./generated.js");
	console.log(mod);
});
```

### Reproduction

code: https://github.com/hi-ogawa/reproductions/tree/main/vitest-plugin-react-v2
stackblitz: https://stackblitz.com/github/hi-ogawa/reproductions/tree/main/vitest-plugin-react-v2?file=src%2Frepro.test.ts

```sh
$ rm src/generated.js
$ npx vitest -t relative

 FAIL  src/repro.test.ts > relative error
Error: Failed to load url ./generated.js (resolved id: ./generated.js) in /home/projects/rlmibvxopx.github/src/repro.test.ts. Does the file exist?
 ❯ loadAndTransform node_modules/.pnpm/vite@5.3.4_@types+node@20.14.11/node_modules/vite/dist/node/chunks/dep-D8YhmIY-.js:52451:17
```

### System Info

```shell
(stackblitz)

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    vitest: 2.0.3 => 2.0.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Are you sure this is Vitest 2 issue, and not Vite 5? The error happens during static analysis and seems legit to me.

**Comment by hi-ogawa** [comment]
I'm not really sure and it's hard to believe, but I can only reproduce from Vitest v2 while Vite version is pinned.

I haven't debug the issue much, but just one surprising thing I found is that the test just succeeded when I added `VITE_NODE_DEBUG_DUMP=1 npx vitest -t relative`.

**Comment by hi-ogawa** [comment]
Hmm, after double checking reproduction, it doesn't look like this fails always 100% (but almost 95% locally).
Now after setting `server.fs.cachedChecks: false`, it looks like the test is passing 100%, so the issue might be some race condition.

I'll check if I can reproduce it on Vite SSR alone.

**Comment by toomuchdesign** [comment]
Running into the same issue (and only after Vitest v2 update).
Setting `server.fs.cachedChecks: false` seems to fix it.

Relevant PR:
https://github.com/toomuchdesign/openapi-ts-json-schema/pull/289

**Comment by hi-ogawa** [comment]
I filed an issue on Vite https://github.com/vitejs/vite/issues/17760.
I'm still not sure why this started to show up since Vitest v2. I bisected and it really seems to happen from first beta `v2.0.0-beta.1`, but I don't have a clue what's affecting it https://github.com/vitest-dev/vitest/releases/tag/v2.0.0-beta.1.

At least this seems to be an inconsistent behavior depending on `server.fs.cachedChecks`, so if it's fixed there, then Vitest side should happy.

**Comment by hi-ogawa** [comment]
I found why this started to happen since Vitest v2. It looks like Vite disabled "cached fs" when users had custom `server.watch.ignored`, which Vitest had it before v2 but removed in v2.0.0-beta.1 https://github.com/vitejs/vite/pull/15920

https://github.com/vitejs/vite/blob/0cde495ebeb48bcfb5961784a30bfaed997790a0/packages/vite/src/node/fsUtils.ts#L47-L56
