### ISSUE TITLE
Type error on mockImplementation with call signature in object type

### ISSUE THREAD

**Issue by freakzlike** [vitest-dev/vitest#6155]
### Describe the bug

I have a function type with additional properties:
```typescript
export interface Handler {
  (v: number): number;
  other(v: number): number;
}
```

When I try to use `mockImplementation` on the call signature, I receive the following type error
```typescript
mockedHandler.mockImplementation((v) => v * 1);
// Property 'other' is missing in type '(v: number) => number' but required in type 'Handler'
```

There was no error in v1. Now with v2, I have to pass the whole object even though `other` is not used and not working.
I expect that only the call signature type is required for `mockImplementation`

As additional help I found a helper to extract the call signature from an object type:
```typescript
type CallSignature<T extends (...a: any[]) => unknown> = (...a: Parameters<T>) => ReturnType<T>

const onlyCall: CallSignature<Handler> = (v) => v * 2
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-8ikkec?file=test%2Fbasic.test.ts&view=editor

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: latest => 2.0.3 
    vite: latest => 5.3.4 
    vitest: latest => 2.0.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by is-jonreeves** [comment]
Incase it helps narrow things down, we are also getting a bunch of similar typescript errors after upgrading from `2.0.2` to `2.0.3`.

**Comment by hi-ogawa** [comment]
I think OP's `vi.mocked + mockImplementation` was already broken in v2.0.0. 

@is-jonreeves If you are seeing a issue specific to 2.0.2 -> 2.0.3 (thus due to https://github.com/vitest-dev/vitest/pull/6086), then it would be great if you can provide a reproduction.

**Comment by is-jonreeves** [comment]
I tested `2.0.4` and it appears to have also resolved my issue. Thanks!

---

For what it's worth... I re-tried downgrading to `2.0.3` to make sure I wasn't mistaken, and there is definitely a type error over there.

Downgrading to `2.0.3`:
```
npm i -D vitest@2.0.3 @vitest/ui@2.0.3 @vitest/coverage-istanbul@2.0.3
```

Simplest example I could find in our code:
```ts
const mockedSelectIsUnlicensed = vi.spyOn(sessionSlice, 'selectIsUnlicensed');
...
mockedSelectIsUnlicensed.mockImplementation(() => true); // <--- complains in 2.0.3 even though type is correct
```

Type error in `2.0.3` (not in `2.0.2` or `2.0.4`):
```
Type '() => true' is not assignable to type '{ clearCache: () => void; resultsCount: () => number; resetResultsCount: () => void; }'
```

I don't have a full example I can share, but if it helps, the usecase is a real `redux` store where we have used `vi.spyOn` to override an exported selector.
