### ISSUE TITLE
Vitest failing to bundle nested dependency while Vite succeeds

### ISSUE THREAD

**Issue by brynshanahan** [vitest-dev/vitest#6156]
### Describe the bug

We have a component library that imports "react-focus-lock". When our component library is imported by a consumer in a Vitest test it resolves "react-focus-lock" as `{ default: FocusLockComponent }` rather than `FocusLockComponent`, while this might be an issue with how these packages are defining their package.exports the config currently works in Vite so I found it strange that it didn't work in Vitest.

I have been able to work around the issue by defining `includes` like mentioned [here](https://github.com/vitest-dev/vitest/issues/3936#issuecomment-2061973992)

The issue does appear when running the code in Node so I get why it's failing in Vitest but I think it's still unexpected that it fails in Vitest but not Vite.

Right now our solution is to tell the consumer to include 
"@components/react", "@components/modal", "react-focus-lock", "prop-types" in their `deps.include` arrays

### Reproduction

https://github.com/brynshanahan/Vitejs-Vite-forked

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 106.64 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.2 - /usr/local/bin/node
    Yarn: 3.4.1 - /usr/local/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
    pnpm: 8.11.0 - ~/Library/pnpm/pnpm
    bun: 1.0.26 - ~/.bun/bin/bun
  Browsers:
    Chrome: 126.0.6478.183
    Edge: 126.0.2592.102
    Safari: 17.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest doesn't bundle anything, it uses Vite dev server. The optimizer is disabled by default because we cannot "reload" the page when a dependency is bundled when running tests.

Unfortunately, this is expected behaviour. Dependencies that are not inlined go through Node.js module resolution, not Vite one, for performance reasons.  If you do not care for performance, you can enable `test.server.deps.inline: true`.

If you need 1-to-1 parity with Vite, use [Browser Mode](https://vitest.dev/guide/browser/#browser-mode) and run tests in the actual browser.

**Comment by brynshanahan** [comment]
Yeah that makes sense, thanks for the quick reply!
