### ISSUE TITLE
Vitest v2 reports zero coverage for types-only TypeScript files

### ISSUE THREAD

**Issue by igordanchenko** [vitest-dev/vitest#6158]
### Describe the bug

After upgrading to v2, I noticed a minor issue in the code coverage report — the code coverage is reported as zero for TypeScript files containing only TypeScript types. It is more of a cosmetic issue as it doesn't affect the overall coverage percentage, but it could still be a good idea to report coverage as 100% in this case as v1 used to.

### Reproduction

1) Open https://stackblitz.com/edit/vitest-v2-ts-coverage-bug?file=test%2Ffoo.test.ts
2) Download the sandbox to run the test locally
3) `npm install`
4) `npm run test:run`

Observe coverage report:

```
 % Coverage report from v8
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |                   
 foo.ts   |     100 |      100 |     100 |     100 |                   
 index.ts |     100 |      100 |     100 |     100 |                   
 types.ts |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
```

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 1.15 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
  Browsers:
    Chrome: 126.0.6478.127
    Safari: 17.5
  npmPackages:
    @vitest/coverage-v8: latest => 2.0.3 
    @vitest/ui: latest => 2.0.3 
    vite: latest => 5.3.4 
    vitest: latest => 2.0.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
That's expected. The types do not contain any code that could be run, as it's only compile time information. This was implemented in https://github.com/vitest-dev/vitest/issues/5423.

If you want to show incorrect coverage and mark these lines containing non-runtime code as covered, use `coverage.ignoreEmptyLines: false`.

Note that the total coverage percentages are shown correctly. The `types.ts` here is not decreasing total coverage:

<img width="400" src="https://github.com/user-attachments/assets/041a1ff5-2603-4673-aa08-da6f961e3872" />

<img width="400" src="https://github.com/user-attachments/assets/038c81cc-3c6a-48eb-bdd6-de2146b11b86" />

<img width="400" src="https://github.com/user-attachments/assets/e0135a5a-eb71-4f82-8d78-2b2bfe6e41ad" />

See also https://github.com/vitest-dev/vitest/issues/3605.

**Comment by AriPerkkio** [comment]
It's not really a work-around. It is correct to see that file as 0% in the report - the file doesn't contain any runtime code. It's imported from files that were tested.

**Comment by igordanchenko** [comment]
> It's not really a work-around. It is correct to see that file as 0% in the report - the file doesn't contain any runtime code. It's imported from files that were tested.

That's not entirely true as this behavior is somewhat inconsistent. The issue I described in this ticket is happening only when I export `types.ts` types from the barrel file (`index.ts`). If I remove that export, then `types.ts` is not included in the coverage report at all, even though the types are imported from the file that was tested.

> So something like below should do it:

```js
{
  coverage: {
    reporter: [
      ['text', { 'skipEmpty': true }],
      ['html', { 'skipEmpty': true }],
    ]
  }
}
```

👍

**Comment by AriPerkkio** [comment]
> even though the types are imported from the file that was tested

This sounds like a bug. Every file that is imported from the tested file should be included in the report.

**Comment by igordanchenko** [comment]
> This sounds like a bug. Every file that is imported from the tested file should be included in the report.

It doesn't get included in the report even with `all: true`. Would you like me to file a separate ticket for this with a repro?

**Comment by AriPerkkio** [comment]
Sure, thanks!
