### ISSUE TITLE
Reporters don't work properly. (output result two times)

### ISSUE THREAD

**Issue by vovsemenv** [vitest-dev/vitest#616]
### Describe the bug

json and junit reporters double their output in console. when you use output files everything works just fine.
i think its because `onFinished` hook work twice instead of one(tested it in custom reporter).

i think `onFinished` don't should be called twhice on a single run  

![image](https://user-images.githubusercontent.com/20096510/150698421-3ae41b32-17c5-40ba-8c9a-7babc43d3309.png)

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-qtqq9f?file=vite.config.ts

### System Info

```shell
System:
    OS: macOS 11.6.1
    CPU: (8) arm64 Apple M1
    Memory: 180.38 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 96.0.2
    Safari: 15.2
  npmPackages:
    @vitejs/plugin-vue: ^2.0.1 => 2.1.0 
    @vitejs/plugin-vue-jsx: ^1.3.3 => 1.3.3 
    vite: ^2.7.13 => 2.7.13 
    vitest: ^0.2.0 => 0.2.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by robcaldecott** [comment]
OMG I was just about to raise this!

Sample repo here: https://github.com/robcaldecott/vitest-multiple-reporters-bug

```
RUN  /Users/caldecor/Projects/vitest-multiple-reporters


 RUN  /Users/caldecor/Projects/vitest-multiple-reporters

 √ src/App.test.tsx > renders
 √ src/App.test.tsx > renders

Test Files  1 passed (1)
     Tests  1 passed (1)
      Time  1.95s (in thread 27ms, 7100.09%)


Test Files  1 passed (1)
     Tests  1 passed (1)
      Time  1.95s (in thread 27ms, 7104.01%)

JUNIT report written to /Users/caldecor/Projects/vitest-multiple-reporters/test-results.xml
JUNIT report written to /Users/caldecor/Projects/vitest-multiple-reporters/test-results.xml
```

**Comment by robcaldecott** [comment]
My config looks like this:

```
/// <reference types="vitest" />

import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  test: {
    environment: "jsdom",
    reporters: process.env.CI ? ["default", "junit"] : "default",
    outputFile: "./test-results.xml",
  },
});
```

```
npm run test:ci
```

**Comment by vovsemenv** [comment]
Yes, we have problem with output file too, but file rewite himself

**Comment by vovsemenv** [comment]
@antfu @Demivan Its actually dont fixed i get same two times output on @0.2.5
![image](https://user-images.githubusercontent.com/20096510/151619280-8b31680e-b80f-4287-a393-928a2417633e.png)

**Comment by vovsemenv** [comment]
same with built in reporters

**Comment by Demivan** [comment]
I think  https://github.com/vitest-dev/vitest/pull/644 broke is again. Need to add a test so it does not happen again.
@vovsemenv can you check it with 0.2.4?

**Comment by vovsemenv** [comment]
yep

**Comment by vovsemenv** [comment]
@Demivan 
0.2.4 is ok

only 0.2.5 broken

**Comment by vovsemenv** [comment]
bug happens only when you specify reporter as array

**Comment by sheremet-va** [comment]
Maybe we should just replace arrays by default and not merge them? We also get duplicates in deps.inline/exclude.

**Comment by Demivan** [comment]
Yeah. We need a separate method and not a deepMerge for this.

**Comment by sheremet-va** [comment]
> Yeah. We need a separate method and not a deepMerge for this.

`deepMerge` didn't have this behaviour before. I've added it when we split `deepMerge` into two for snapshots. I think we can just revert array merging, since nothing depends on it.

**Comment by Demivan** [comment]
Will do that and rename it to `mergeConfig` or something.
