### ISSUE TITLE
Vitest v2 coverage is reporting 'Unexpected reserved word' error

### ISSUE THREAD

**Issue by meteorlxy** [vitest-dev/vitest#6161]
### Describe the bug

- `vitest run` works well
- `vitest run --coverage` fails

<img width="1053" alt="image" src="https://github.com/user-attachments/assets/03be1ef2-cea1-4223-be4c-c425d437cb1d">

### Reproduction

Repository: https://github.com/mdit-vue/mdit-vue
CI log: https://github.com/mdit-vue/mdit-vue/actions/runs/9992201242/job/27616645356

### System Info

```shell
System:
    OS: macOS 14.4
    CPU: (10) arm64 Apple M1 Pro
    Memory: 334.61 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/Library/Caches/fnm_multishells/77642_1721308212385/bin/node
    npm: 10.5.0 - ~/Library/Caches/fnm_multishells/77642_1721308212385/bin/npm
    pnpm: 9.5.0 - ~/Library/Caches/fnm_multishells/77642_1721308212385/bin/pnpm
    Watchman: 2024.05.06.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 126.0.6478.182
    Safari: 17.4
  npmPackages:
    @vitest/coverage-istanbul: ^2.0.3 => 2.0.3 
    vitest: ^2.0.3 => 2.0.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Renaming the `index.d.cts` to `*.d.mts` or `*.d.ts` seems to fix the issue 🤔

**Comment by AriPerkkio** [comment]
Need to check if Vite transforms `*.cts` as Typescript files. Or if Vite supports `*.cts` at all as it's not ESM.

**Comment by sheremet-va** [comment]
> Need to check if Vite transforms `*.cts` as Typescript files. Or if Vite supports `*.cts` at all as it's not ESM.

Vite doesn't support transforming `cts` files: https://github.com/vitest-dev/vitest/issues/3987

**Comment by AriPerkkio** [comment]
As fix let's exclude `*.cts` from coverage completely.
