### ISSUE TITLE
Global coverage threshold should not exclude glob based thresholds

### ISSUE THREAD

**Issue by thor-juhasz** [vitest-dev/vitest#6165]
### Describe the bug

When using both global coverage thresholds *and* pattern based coverage thresholds, the "All files" tally reports correct numbers.

Setting the global thresholds based on this for the next run will fail the test run since the files matched by patterns are deducted from the global threshold numbers before checking if they pass.

### Reproduction

Use this in test config:

```typescript
coverage: {
    reporter: ['text', 'html'],
    thresholds: {
        lines: 50,

        'src/b.ts': {
            lines: 100,
        }
    },
},
```

src/a.ts:
```typescript
export function add(a: number, b: number): number {
    return a + b;
}
```

src/b.ts:
```typescript
export function subtract(a: number, b: number): number {
    return a - b;
}
```

Cover src/a.ts with a test and then run the tests:
```typescript
test('adds numbers', () => {
    expect(add(1, 2)).toBe(3);
});
```

You will see that it fails on global threshold, even though we have covered 100% of a.ts (and that passes), and 0% of b.ts, which results in a total of 50% coverage. And that is what the text reporter tells us.

However, the test run is failed as it only sees b.ts for the global thresholds, confusing users, implying the coverage numbers are somehow off.

### System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700K
    Memory: 29.25 GB / 62.54 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    Yarn: 4.3.1 - ~/.nvm/versions/node/v20.15.0/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
  Browsers:
    Chrome: 126.0.6478.126
  npmPackages:
    @vitejs/plugin-basic-ssl: ^1.1.0 => 1.1.0 
    @vitejs/plugin-vue: ^5.0.5 => 5.0.5 
    @vitest/coverage-istanbul: ^2.0.3 => 2.0.3 
    @vitest/ui: 2.0.3 => 2.0.3 
    vite: ^5.0.0 => 5.3.3 
    vitest: ^2.0.3 => 2.0.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
During the implementation of glob based thresholds I ran into this as well: https://github.com/vitest-dev/vitest/pull/4442#discussion_r1390465402. I didn't know whether this is a bug or not, so I followed Jest's way and implented the same logic. But now I think this is bug indeed.

The related code is here and there's also comment describing the current behavior:

https://github.com/vitest-dev/vitest/blob/807a2cbc4818462b9feaaecfedd0c49c6db8e4c8/packages/vitest/src/utils/coverage.ts#L221-L227
