### ISSUE TITLE
Support 100 shorthand option for pattern based coverage rules

### ISSUE THREAD

**Issue by thor-juhasz** [vitest-dev/vitest#6166]
### Clear and concise description of the problem

As documented [here](https://vitest.dev/config/#coverage-thresholds-100), we can use this:
```typescript
coverage: {
    thresholds: {
        '100': true,
    },
}
```

This I find to be very useful instead of typing out all of the options with the same value.
This is however, not supported for pattern based thresholds, where, I would argue, it becomes even more useful.

### Suggested solution

Allow `'100': true` in pattern based coverage tresholds:

```typescript
coverage: {
    thresholds: {
        lines: 50,
        function: 70,

        'src/path1/**/*': { '100': true },
        'src/path2/**/*': { '100': true },
        'src/path3/**/*': { '100': true },
        'src/path4/**/*': { '100': true },
        'src/path5/**/*': { '100': true },
    },
}
```

This reduces clutter far more than only allowing this for the global threshold config.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
Related code is around here:

https://github.com/vitest-dev/vitest/blob/807a2cbc4818462b9feaaecfedd0c49c6db8e4c8/packages/vitest/src/utils/coverage.ts#L167-L241
