### ISSUE TITLE
Istanbul failing to report coverage for CJS requires

### ISSUE THREAD

**Issue by stramel** [vitest-dev/vitest#6168]
### Describe the bug

When importing the source code using `require`, istanbul doesn't record any coverage for the source file. Simply switching to use v8 instead, correctly records the coverage. 

When importing the source code using `import`, both istanbul and v8 work correctly.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-zzwrqw?file=packages%2Fmath%2Ftest%2Fbasic.test.js

### System Info

```txt
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Max
    Memory: 321.14 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.volta/tools/image/node/20.15.1/bin/node
    Yarn: 1.22.19 - ~/.volta/bin/yarn
    npm: 10.8.2 - ~/.volta/tools/image/npm/10.8.2/bin/npm
  Browsers:
    Chrome: 126.0.6478.127
    Chrome Canary: 123.0.6270.0
    Edge: 126.0.2592.102
    Safari: 17.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
It works as intended. Vitest (and Vite) do not intercept `require()` so there's no way to instrument these files.

**Comment by stramel** [comment]
> It works as intended. Vitest (and Vite) do not intercept `require()` so there's no way to instrument these files.

Thanks for that information. Is it intended that the `v8` **does** provide coverage of `require()`?

**Comment by AriPerkkio** [comment]
The V8 coverage does the instrumentation on Node/V8 so it happens to every single file - even Node's built-in modules like `fs` and your dependencies in `node_modules`.
