### ISSUE TITLE
Vitest Startup Error 

### ISSUE THREAD

**Issue by Santhosh-Propvr** [vitest-dev/vitest#6171]
I am new to vitest and I want to use vitest in the vite, vue3 project I installed vitest using `npm install -D vitest`. After installing I added the `npm run test` in the scripts of package.json. When I try to run npm run test command I am getting startup error.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Startup Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
file:///C:/Testing/exp-tracker/node_modules/tinypool/dist/index.js:25
import { once, EventEmitterAsyncResource } from "events";
               ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'events' does not provide an export named 'EventEmitterAsyncResource'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:191:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:331:24)
    at async start (file:///C:/Testing/exp-tracker/node_modules/vitest/dist/vendor/cac.DUiZvzF_.js:1501:29)

To Reproduce:

These are my package.json config
 "dependencies": {
    "@headlessui/vue": "^1.7.17",
    "@heroicons/vue": "^2.1.1",
    "axios": "^1.6.5",
    "happy-dom": "^14.12.3",
    "pinia": "^2.1.7",
    "serve": "^14.2.3",
    "vue": "^3.3.11",
    "vue-router": "^4.2.5",
    "vue3-datepicker": "^0.4.0"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.6.2",
    "@vue/test-utils": "^2.4.6",
    "autoprefixer": "^10.4.16",
    "events": "^3.3.0",
    "postcss": "^8.4.33",
    "tailwindcss": "^3.4.1",
    "vite": "^5.0.8",
    "vitest": "^2.0.3"
  }
  
  My node version is v18.17.1 and my npm version is 10.5.0
  
  I am using windows 11 and vscode for development

**Comment by sheremet-va** [comment]
Please, use the bug report template.

**Comment by Santhosh-Propvr** [comment]
Hi Sheremet-va, 

In stackblitz vitest is working, but it is not working in my windows local machine. Many thanks for considering my request.

**Comment by FabienCH** [comment]
Hi @Santhosh-Propvr 
Try to update your node version. I had the same issue and it was fixed my I moved from v16.10.0 to v20.9.0

**Comment by Santhosh-Propvr** [comment]
Hi @FabienCH 
Thanks for your help.Will try your approach and update you.
