### ISSUE TITLE
Bug Report: userEvent click causing test timeout in Vitest but works in Jest

### ISSUE THREAD

**Issue by lukasalvarezdev** [vitest-dev/vitest#6179]
## Description
When running a test using `@testing-library/react` and `userEvent` with fake timers in Vitest, the test times out at the `await user.click(screen.getByRole('button'))` line. The same code works without issues in Jest.

## Reproduction

```tsx
import { render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'

vi.useFakeTimers()

it('explicitly test specific event', async () => {
  const callback = vi.fn()

  const { user } = setup(<App callback={callback} />)
  await user.click(screen.getByRole('button'))

  vi.runAllTimers()

  expect(callback).toHaveBeenCalledTimes(1)
})

export function setup(jsx: JSX.Element) {
  return {
    user: userEvent.setup({
      advanceTimers: vi.advanceTimersByTime,
    }),
    ...render(jsx),
  }
}

function App({ callback }: { callback: any }) {
  const onClick = () => {
    setTimeout(() => {
      callback(1)
    }, 1)
  }
  return <button onClick={onClick}>Click me</button>
}
```

## Expected Behavior
The test should pass and callback should be called once after the button is clicked and timers are run.

## Actual Behavior
The test times out at the await user.click(screen.getByRole('button')) line, and the setTimeout created by userEvent is never called.

## Additional Information
The exact same code works as expected when run with Jest.

### Reproduction

https://github.com/lukasalvarezdev/jest-remix-repro

### System Info

```shell
Using Vitest version: 2.0.3
@testing-library/react version: 16.0.0
@testing-library/user-event version: 14.5.2

Environment
Node version: v20.15.1
Operating System: MacOS
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You need to set `advanceTimers` to `vi.advanceTimersByTime`:

https://testing-library.com/docs/user-event/options#advancetimers

**Comment by lukasalvarezdev** [comment]
@sheremet-va I don't understand why you close it if that is the exact code I have in the repository and in the example I described in the issue. The issue is that I did set `advanceTimers` to `vi.advanceTimersByTime` and doesn't work.

**Comment by sheremet-va** [comment]
Sorry, I did not notice that. In any case, this cannot be a Vitest error since it fails on `user.click` line that we don't control. Indeed, with some digging, I found this error in `@testing-library/user-event` GitHub repository: https://github.com/testing-library/user-event/issues/1115

**Comment by lukasalvarezdev** [comment]
Thank you so much for your help, I'll follow up there.
