### ISSUE TITLE
Cannot read properties of undefined (reading 'navigator') when using `@vitest/browser`

### ISSUE THREAD

**Issue by nicojs** [vitest-dev/vitest#6187]
### Describe the bug

When running vitest inside a mocha test suite, the error "Cannot read properties of undefined (reading 'navigator')" is thrown from a global `afterEach` handler registered by `@vitest/browser`.

For example:

```
   ✔ should be able to start and close (1442ms)
    1) "after each" hook for "should be able to start and close"


  1 passing (1s)
  1 failing

  1) "after each" hook for "should be able to start and close":
     TypeError: Cannot read properties of undefined (reading 'navigator')
      at resetClipboardStubOnView (file:///home/nicojs/github/tmp/node_modules/@vitest/browser/dist/index.js:1058:32)
      at Context.<anonymous> (file:///home/nicojs/github/tmp/node_modules/@vitest/browser/dist/index.js:1069:21)
      at process.processImmediate (node:internal/timers:478:21)
      at process.callbackTrampoline (node:internal/async_hooks:130:17)

```

I've investigated this somewhat, and vitest includes some reset logic for mocking in its index.js bundle. However, this should not be included in the server-side code as it assumes running in the browser (as it tries to read from `globalThis.window.navigator`).

I cannot find this code inside the vitest monorepo, so I think it is a dependency that gets bundled in via rollup.

<details> 
<summary>Code that causes the issue</summary>

```js
const ClipboardStubControl = Symbol('Manage ClipboardSub');
function isClipboardStub(clipboard) {
    return !!(clipboard === null || clipboard === void 0 ? void 0 : clipboard[ClipboardStubControl]);
}
function resetClipboardStubOnView(window) {
    if (isClipboardStub(window.navigator.clipboard)) {
        window.navigator.clipboard[ClipboardStubControl].resetClipboardStub();
    }
}
function detachClipboardStubFromView(window) {
    if (isClipboardStub(window.navigator.clipboard)) {
        window.navigator.clipboard[ClipboardStubControl].detachClipboardStub();
    }
}
const g = globalThis;
/* istanbul ignore else */ if (typeof g.afterEach === 'function') {
    g.afterEach(()=>resetClipboardStubOnView(globalThis.window));
}
/* istanbul ignore else */ if (typeof g.afterAll === 'function') {
    g.afterAll(()=>detachClipboardStubFromView(globalThis.window));
}
```

</details>

### Reproduction

I've created a simple reproduction repo for this: 
[vitest-issue.zip](https://github.com/user-attachments/files/16326349/vitest-issue.zip)

The basics is that I've created a simple mocha test that starts and stops vitest. In the vitest config I've configured browser mode.

```js
// mocha test
import { createVitest } from 'vitest/node';
describe('test vitest', () => {

    it('should be able to start and close', async () => {
        const server = await createVitest('test', {});
        await server.start();
        await server.close();
    });
});
```

```js
// vitest.config.js

import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    globals: true,
    browser: {
      enabled: true,
      name: "chromium",
      provider: "playwright",
      headless: true,
    },
    root: "vitest-test",
  },
});

```

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 5.37 GB / 15.49 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
    pnpm: 9.4.0 - ~/.nvm/versions/node/v20.15.0/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.126
  npmPackages:
    @vitest/browser: ^2.0.3 => 2.0.3 
    vitest: ^2.0.3 => 2.0.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nicojs** [comment]
I don't think importing from `vitest` (which also imports from `@vitest/browser` by extension) should have side effects at all, correct?

**Comment by nicojs** [comment]
Excellent, thanks, @sheremet-va, for fixing it so fast 👐 I can confirm that it works (although I have no clue why, looking at the code 😅).

**Comment by sheremet-va** [comment]
> Excellent, thanks, @sheremet-va, for fixing it so fast 👐 I can confirm that it works (although I have no clue why, looking at the code 😅).

Rollup sees that it can't remove the file content because there is a side effect of calling a method on a `globalThis`. We are now saying to Rollup that it's OK to remove the file even if it detects side effects (basically, we override its detection)
