### ISSUE TITLE
`process.argv` mismatching between `1.6.0` and `2.0.x`

### ISSUE THREAD

**Issue by nazarhussain** [vitest-dev/vitest#6203]
### Describe the bug

The default value for `process.argv` does not match between above mentioned versions, when run with the `browsers` mode. 

- With `1.6.0` it's was undefined 
- With `2.0.x` it is an array with few values

If we use `vite-plugin-node-polyfills` to pollyfil the `process` it had different weird behavior. 

- With `1.6.0` it's was `[]`
- With `2.0.x` it is undefined 

The `vite-plugin-node-polyfills` version is same in both cases, so the shims does not change at all. 

### Reproduction

https://stackblitz.com/edit/vitest-2-env-argv
https://stackblitz.com/edit/vitest-1-env-argv

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (11) arm64 Apple M3 Pro
    Memory: 200.19 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.4.0 - ~/.asdf/installs/nodejs/22.4.0/bin/node
    Yarn: 1.22.22 - ~/.asdf/installs/nodejs/22.4.0/bin/yarn
    npm: 10.8.1 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Brave Browser: 126.1.67.134
    Safari: 17.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This probably happens because we want to statically replace testing-library's env vars: 

https://github.com/vitest-dev/vitest/blob/883f3482745772ccf24087246f4f7af7414ae233/packages/browser/src/node/plugin.ts#L339

But looks like adding `process.*` creates an empty `process` object globally:

https://github.com/vitejs/vite/blob/b240a8347e7b62bee9d2212625732bb0d8c78633/packages/vite/src/client/env.ts#L17

Not sure how to fix this yet.

**Comment by nazarhussain** [comment]
In our project a deep dependency is looking for `process.argv` and that is causing to fail the upgrade to vitest `2.0.x`. 

Until it's fixed, is there a workaround you could think of?

**Comment by sheremet-va** [comment]
> Until it's fixed, is there a workaround you could think of?

I don't think this can be fixed soon on Vite side, but you can define `process.argv` in `defined`:

```ts
export default defineConfig({
  defines: {
    'process.argv': '[]',
  }
})
```

**Comment by sheremet-va** [comment]
Looks like the previous fix breaks config bundling (esbuild hangs) with `headless: false`

**Comment by nazarhussain** [comment]
> > Until it's fixed, is there a workaround you could think of?
> 
> I don't think this can be fixed soon on Vite side, but you can define `process.argv` in `defines`:
> 
> ```ts
> export default defineConfig({
>   defines: {
>     'process.argv': '[]',
>   }
> })
> ```

In my case I had to also add one other attribute to process. 

```js
{
          define: {
            "process.argv": "[]",
            "process.nextTick": "function noop(){}",
          },
}
```
