### ISSUE TITLE
Test hangs waiting for promise to resolve

### ISSUE THREAD

**Issue by slauzinho** [vitest-dev/vitest#621]
### Describe the bug

Using the new `vi.setSystemTime` I added `vi.useFakeTimers();` but this seems to be breaking my async tests.
The tests now wait for the promise to resolve, and since we are using fake timers it never happens.

I saw an example that uses `await flushPromises()` but this doesn't seem to do the trick.

### Reproduction

https://stackblitz.com/edit/github-u4au2p?file=src/stores/counter.js

Run `yarn test` and see the test hang

### System Info

```shell
System:
    OS: macOS 10.15.6
    CPU: x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 204.80 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.6.1 - ~/.nvm/versions/node/v16.6.1/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v16.6.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    vite: ^2.7.12 => 2.7.13 
    vitest: ^0.2.1 => 0.2.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Demivan** [comment]
Problem is caused by your usage of `setImmediate` to resolve the promise. To advance timers and run `setImmediate` you can run `vi.runAllTimers` and it works fine:
https://stackblitz.com/edit/github-u4au2p-5duhjr?file=src%2Fstores%2Fcounter.js

**Comment by slauzinho** [comment]
What's the approach when using a real api call?

https://stackblitz.com/edit/github-u4au2p-urgmzt?file=src/stores/counter.js

**Comment by sheremet-va** [comment]
> What's the approach when using a real api call?
> 
> https://stackblitz.com/edit/github-u4au2p-urgmzt?file=src/stores/counter.js

You can follow guide from the [docs](https://vitest.dev/guide/mocking.html#requests) or use any kind of mocking library to mock `fetch` call, for example [vi-fetch](https://github.com/sheremet-va/vi-fetch) or [jest-fetch-mock](https://github.com/jefflau/jest-fetch-mock)

**Comment by slauzinho** [comment]
Yeah I know I can mock fetch or library but I'm actually using [MSW](https://mswjs.io/) to avoid having to mock all my requests.

**Comment by sheremet-va** [comment]
> Yeah I know I can mock fetch or library but I'm actually using [MSW](https://mswjs.io/) to avoid having to mock all my requests.

That is what our guide recommends.

**Comment by slauzinho** [comment]
Yeah and `MSW` works fine with vitest the issue is when I have to do `useFakeTimers` because of the new `setSystemTime ` API released in `0.2.1`. 

If I understood correctly by using `useFakeTimers` I will have to mock the API request because otherwise the promise never resolves?

**Comment by sheremet-va** [comment]
Hanging actually comes from `response.json`, and not from response.

**Comment by sheremet-va** [comment]
> With Jest I could just do:
> 
> ```ts
> jest.useFakeTimers('modern').setSystemTime(nee Date('2020-01-01'))
> ```
> 
> and it didn't hang.

Maybe you were using another package for fetch? Happy-dom uses `node-fetch`.

> Using the new vi.setSystemTime I added vi.useFakeTimers(); but this seems to be breaking my async tests.
> The tests now wait for the promise to resolve, and since we are using fake timers it never happens.

This is expected behaviour, unfortunately. I recommend using `mockdate` package, if you relied on `setMockedDate` before.

**Comment by slauzinho** [comment]
> 
> Maybe you were using another package for fetch? Happy-dom uses `node-fetch`.
> 
I'm using Axios

> > Using the new vi.setSystemTime I added vi.useFakeTimers(); but this seems to be breaking my async tests.
> > The tests now wait for the promise to resolve, and since we are using fake timers it never happens.
> 
> This is expected behaviour, unfortunately. I recommend using `mockdate` package, if you relied on `setMockedDate` before.
Thanks I will use `mockdate`, I actually had it install and was running on another test file without issues. 

Thank once again for your help 👍

**Comment by Demivan** [comment]
@sheremet-va would it be a good idea to bring back `setMockedDate` for current date mocking? I feel like fake-timers would be an overkill for most users.

**Comment by sheremet-va** [comment]
I do agree it's an overkill, but don't like having two methods for this.

We can use `mockdate` if timers aren't mocked in `setSytemTime` and reset it inside `useRealTimers`

**Comment by Demivan** [comment]
> We can use mockdate if timers aren't mocked in setSytemTime and reset it inside useRealTimers

That is a great idea.
