### ISSUE TITLE
Support for ctx.todo()

### ISSUE THREAD

**Issue by flowt-au** [vitest-dev/vitest#6212]
### Clear and concise description of the problem

I am using [vitest-cucumber](https://github.com/amiceli/vitest-cucumber) which is great. An upcoming release will support the Vitest `ctx.skip()` option by passing the ctx into the test (like Vitest does) like this:
```js
Then(`the result of test "<id>" should be <result>`, (ctx) => {
      ctx.skip()
})
```
I know in Vitest this is possible: `test.todo('unimplemented test')` but that can't be done in vitest-cucumber.

### Suggested solution

I would love the option of `ctx.todo(myMessage)` so I can write all the Gherkin, set the tests to have `ctx.todo()` then have them work like the `test.todo('unimplemented test')` does, with the addition of an optional custom message.
```js
Then(`the result of test "<id>" should be <result>`, (ctx) => {
      ctx.todo('Waiting for the client to ok this idea')
})
```
I think this would be of use to non-BDD testers too.

### Additional context

Anyway, thanks for a great library!
Murray

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I don't really understand where the optional message is reported? `ctx.skip` just marks the test as `skip` and keeps its name.

**Comment by flowt-au** [comment]
What I am proposing is that the additional message could appear on the report. Remembering that with BDD the feature files and step definitions are often written before any code and non-developers are often part of that spec development process.

At present, with ctx.skip() it says:
```
Then the result of test "three" should be 35 [skipped]
```

What I am suggesting is something like:
```
Then the result of test "three" should be 35 [ToDo: Waiting for the client to ok this idea]
```
or just:
```
Then the result of test "three" should be 35 [ToDo]
```
meaning this feature is not yet written, or whatever else the team decides it means.

This way, if the client or other non-developers are part of the BDD process they would see these comments in the report. Also, developers have more information about why a test is not executing, rather than just `[skipped]`. ie all the same reasons for test.todo(), just with more detail.

And, of course, if messages were also allowed in skip() devs could say _why_ it was skipped, and others who cannot see the comments in the test implementation would have more information.

Thanks,
Murray
