### ISSUE TITLE
UI coverage list filters/shrinks during watch

### ISSUE THREAD

**Issue by alexcroox** [vitest-dev/vitest#6225]
### Describe the bug

I'm trying to add tests to my project. I'm using the coverage UI to help me navigate this task and see where the gaps in testing are.

When the UI first launches I see all files in the coverage "all files" section.

However as I save tests the list shrinks, and might only show the file I just saved in a specific folder, rather than the other files that were previously visible. I think this has something to do with --watch where it only runs against files you just changed, but I want to always see all files so I can work through them.

Currently I have to keep restarting the process to get the full file list back.

### Reproduction

I'm launching with: `vitest --watch --config tests/vitest.unit-config.ts --ui`

I've tried the `test.coverage.all: true` option

```
import { defineVitestConfig } from '@nuxt/test-utils/config'

export default defineVitestConfig({
  test: {
    environment: 'happy-dom',
    globals: true,
    watch: false,
    clearMocks: true,
    mockReset: true,
    restoreMocks: true,
    setupFiles: ['./tests/unit/unitSetup.ts'],
    include: ['./**/*.spec.ts'],
    exclude: ['./node_modules', './dist', './.nuxt', './coverage', './tests/e2e', './**/*.e2e.spec.ts'],
    chaiConfig: {
      truncateThreshold: 0
    },
    coverage: {
      enabled: true,
      provider: 'v8',
      all: true,
      reportsDirectory: '../tests/unit/coverage'
    }
  }
})

```

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 513.00 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
  Browsers:
    Chrome: 126.0.6478.185
    Safari: 17.5
    Safari Technology Preview: 18.0
  npmPackages:
    @vitejs/plugin-vue: 5.0.5 => 5.0.5
    @vitest/coverage-v8: 2.0.4 => 2.0.4
    @vitest/ui: 2.0.4 => 2.0.4
    vitest: 2.0.4 => 2.0.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Requires https://github.com/vitest-dev/vitest/issues/5521#issuecomment-2057356311
