### ISSUE TITLE
[Vitest 2.x] Browser mode failure snapshots directory name can conflict with other tools

### ISSUE THREAD

**Issue by yannbf** [vitest-dev/vitest#6239]
### Describe the bug

When testing story files from Storybook using Vitest (e.g. `Button.stories.tsx`), the failures generate a directory like `__screenshots__/Button.stories.tsx/FailingStoryName.png`:

![image](https://github.com/user-attachments/assets/633705bb-5418-4fdb-b972-b8857fccbb71)

However because the Storybook indexer uses globs that match `*.stories.*`, it ends up detecting the directory too.
While Storybook could improve its matching mechanics, being able to modify the names used in the snapshots like Jest's `snapshotResolver` would be quite useful. There could be other tools which might conflict because of similar situations.

If Vitest appended `.snap` at the end of the directory name, this would also fix the issue.

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Maybe we should just have it in the name?

- __screenshots__
  - Button.stories.tsx_ReponsiveMovile-1.png

**Comment by sheremet-va** [comment]
Looks like cypress does the same, but their screenshot folder is in the root: https://docs.cypress.io/api/commands/screenshot#Naming-conventions

**Comment by yannbf** [comment]
Good point, I'll make sure we can handle this in Storybook! Thanks for investigating <3
