### ISSUE TITLE
Concurrent tests have wrong currentTestName 

### ISSUE THREAD

**Issue by DecathectZero** [vitest-dev/vitest#6242]
### Describe the bug

If you run `expect.getState().currentTestName` but have several tests inside `describe.concurrent`, it actually logs the wrong name.
This also implies that the global `expect` might be paired to the wrong test, and could be showing wrong info

### Reproduction

Run this test:

```
import { describe, expect, it } from 'vitest';

describe.concurrent('test', () => {
  it('case1', async () => {
    expect(expect.getState().currentTestName).toEqual('test > case1');
  });
  it('case2', async () => {
    expect(expect.getState().currentTestName).toEqual('test > case2');
  });
  it('case3', async () => {
    expect(expect.getState().currentTestName).toEqual('test > case3');
  });
  it('case4', async () => {
    expect(expect.getState().currentTestName).toEqual('test > case4');
  });
  it('case5', async () => {
    expect(expect.getState().currentTestName).toEqual('test > case5');
  });
  it('case6', async () => {
    expect(expect.getState().currentTestName).toEqual('test > case6');
  });
  it('case7', async () => {
    expect(expect.getState().currentTestName).toEqual('test > case7');
  });
  it('case8', async () => {
    expect(expect.getState().currentTestName).toEqual('test > case8');
  });
  it('case9', async () => {
    expect(expect.getState().currentTestName).toEqual('test > case9');
  });
});
```

### System Info

```shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 188.02 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.volta/tools/image/node/20.11.1/bin/node
    Yarn: 4.2.2 - ~/.volta/tools/image/yarn/4.2.2/bin/yarn
    npm: 10.2.4 - ~/.volta/tools/image/node/20.11.1/bin/npm
    bun: 1.1.21 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 126.0.6478.183
    Safari: 17.4.1
  npmPackages:
    vitest: 2.0.4 => 2.0.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DecathectZero** [comment]
I'm assuming we can also do 
`it('case1', async ({ expect }) => {` and that `expect` will have the right context. But is there no way to ensure this works on a global expect level?

**Comment by sheremet-va** [comment]
> I'm assuming we can also do `it('case1', async ({ expect }) => {` and that `expect` will have the right context. But is there no way to ensure this works on a global expect level?

There is a mechanism to do that in Node.js, but it's not supported in the browser. To not fragment the API, we are sticking with test context until that API is implemented in the browser.
