### ISSUE TITLE
Commonjs Translation Issues

### ISSUE THREAD

**Issue by zhangjixiangaa** [vitest-dev/vitest#6244]
### Describe the bug

![1031722307768_ pic](https://github.com/user-attachments/assets/7142c52d-1cbd-4231-b654-0a75ff8901bc)
![1041722307902_ pic](https://github.com/user-attachments/assets/4cd0393b-b5a6-4c6f-9a5d-1fae70080bb3)

### Reproduction

see images

### System Info

```shell
npm run test
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
The error message already told you what to do - add `@fec/oow` to `server.deps.inline`
