### ISSUE TITLE
Add in-source test example

### ISSUE THREAD

**Issue by sheremet-va** [vitest-dev/vitest#6250]
### Clear and concise description of the problem

We currently don't have any examples of in-source tests.

### Suggested solution

Add an example of in-source test to `examples` folder and link it in the documentation.

### Additional context

This should close #6229

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hakshu25** [comment]
I would like to work on this issue.
