### ISSUE TITLE
Linux: on large repos, the watcher fails with ENOSPC even when filtering

### ISSUE THREAD

**Issue by wmertens** [vitest-dev/vitest#6255]
### Describe the bug

The watcher seems to visit and watch all files in the tree, even when the entire subtree is excluded via negative include or exclude globs.

If you have a lot of files under your repo, for example from caching, this can cause vitest to run out of file descriptors.

I think the fix is to short-circuit the watching when an entire subtree would be matched by a glob.

### Reproduction

I experience it sometimes on https://github.com/QwikDev/qwik when there have been a bunch of rust builds.
I think it won't happen on stackblitz because it depends on how fs changes are monitored.

### System Info

```shell
System:
    OS: Linux 6.10 NixOS 24.11 (Vicuna) 24.11 (Vicuna)
    CPU: (16) x64 AMD Ryzen 7 7840HS with Radeon 780M Graphics
    Memory: 3.30 GB / 13.34 GB
    Container: Yes
    Shell: 5.2.26 - /run/current-system/sw/bin/bash
  Binaries:
    Node: 20.14.0 - /nix/store/ilkfhnqz4xczrliqjva8770x2svbfznd-nodejs-20.14.0/bin/node
    npm: 10.7.0 - /nix/store/ilkfhnqz4xczrliqjva8770x2svbfznd-nodejs-20.14.0/bin/npm
    pnpm: 9.0.5 - /nix/store/zw38hg36phakmnk3lxglyzvjwf2pivsa-corepack-nodejs-20.14.0/bin/pnpm
  npmPackages:
    vite: 5.3.5 => 5.3.5 
    vitest: 2.0.5 => 2.0.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wmertens** [comment]
Update: a simple repro: This should only watch the file vitest.config.js, but it reads the entire home directory.

```
$ cd
$ echo 'export default {include:["vitest.config.js"]}' > vitest.config.js
$ npx vitest 

 DEV  v2.0.5 /home/wmertens


⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: ELOOP: too many symbolic links encountered, stat '/home/wmertens/.cache/ms-playwright/ll'
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { errno: -40, code: 'ELOOP', syscall: 'stat', path: '/home/wmertens/.cache/ms-playwright/ll' }
```

**Comment by sheremet-va** [comment]
> Update: a simple repro: This should only watch the file vitest.config.js, but it reads the entire home directory.

Not sure why you think `include` should affect what is watched, it's only to filter test files from other files in your cwd or root directory. Vitest uses Vite's watcher without any modifications, you can see how it can be configured at https://vitejs.dev/config/server-options.html#server-watch

**Comment by wmertens** [comment]
@sheremet-va I'm not able to configure it. When I add
```
		server: {
			watch: {
				ignored(id) {
					console.log('watch', id)
					return true
				},
			},
		},
```
to the vite config or under `.test`, I don't see anything being logged, and I see it traversing all directories it shouldn't.

**Comment by wmertens** [comment]
I figured it out, I should have passed an array to `ignored` with the function in there.

This is what made my vitest runs zippy:
```
// {...vite config object
		server: {
			watch: {
				ignoreInitial: true,
				ignored: readFileSync('.gitignore', 'utf8')
					.split('\n')
					.filter(l => l && !l.startsWith('#'))
					.map(line => `${process.cwd()}/${line}`),
			},
		},
```
The cwd is needed for it to work. My gitignore is just simple entries, so YMMV.
