### ISSUE TITLE
`coverage.reporter` with a single value causes error while running tests without coverage (v2.0.x)

### ISSUE THREAD

**Issue by ildede** [vitest-dev/vitest#6260]
### Describe the bug

The documentation of `coverage.reporter` on both [V2](https://vitest.dev/config/#coverage-reporter) and [V1](https://v1.vitest.dev/config/#coverage-reporter) say that we can use `string` as a valid value.

So a minimal `vitest.config` like this, should work
```js
export default defineConfig({
  test: {
    coverage: {
      reporter: 'json',
    },
  },
})
```
This works fine with 1.6, but not in 2.0.x.

Error printed while executing `pnpm run test`. The error **is not** present while running `pnpm run test --coverage`

<img width="1241" alt="Screenshot 2024-08-01 at 18 22 23" src="https://github.com/user-attachments/assets/6a64106d-f2cf-4429-91a1-a1f97a913e54">

### Reproduction

A minimal reproduction case in this repository [ildede/vitest-single-reporter-error](https://github.com/ildede/vitest-single-reporter-error)

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 116.05 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/Library/pnpm/node
    npm: 10.1.0 - ~/Library/pnpm/npm
    pnpm: 9.5.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 127.0.6533.88
    Safari: 17.5
  npmPackages:
    vitest: ^2.0.5 => 2.0.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
We have test case for all reporter option types but all those run with `coverage: { enabled: true }`. This error case seems to come up only when coverage is disabled.

https://github.com/vitest-dev/vitest/blob/a7be50dbceea31611403542caca7ebf44e4e014a/test/coverage-test/test/reporters.test.ts#L7-L18

This might have been caused by refactoring done during https://github.com/vitest-dev/vitest/pull/6205.

**Comment by osmestad** [comment]
If anyone is wondering how to work around this (like me) until `2.1.x` gets released, wrapping the reporter string in an array should do the trick. So from:
```
coverage: { 
       reporter: 'json', 
}
```
to:
```
coverage: { 
       reporter: ['json'], 
}
```
