### ISSUE TITLE
Save Buffer to Snapshot File

### ISSUE THREAD

**Issue by cqh963852** [vitest-dev/vitest#6263]
### Clear and concise description of the problem

I am writing a `toMatchImageSnapshot` in browser mode.
Currently, I can get the expected and received buffer data. 
This can be used for comparison, but I have no way to write the png to a file.

![image](https://github.com/user-attachments/assets/b2c46e20-188c-4973-b11e-4e692bbabfe6)

### Suggested solution

Add a `WriteFileOptions` param instead "utf-8"

![image](https://github.com/user-attachments/assets/395f61e6-4a1f-411f-95a1-16a49241fa18)

### Alternative

Because fs cannot be used in the browser environment, it would be better if compatible interfaces for writeFile and readFile could be added.

### Additional context

I tried jest-image-snapshot but there were some errors in browser mode.

I thought it would be more appropriate to write a new one using the existing interface.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
`Buffer` doesn't exist in the browser so there is no reason to allow it. 

Storing the base64 string to compare it later is not useful because you cannot see the rendered image to look for differences.

We will release built-in visual regression assertions in the future ourselves one day.

> Because fs cannot be used in the browser environment, it would be better if compatible interfaces for writeFile and readFile could be added.

https://vitest.dev/guide/browser/commands.html#files-handling
