### ISSUE TITLE
`test.passWithNoTests` has no effect with workspaces

### ISSUE THREAD

**Issue by mikestopcontinues** [vitest-dev/vitest#6264]
### Describe the bug

While the CLI arg `--passWithNoTests` works, the config option `test.passWithNoTests` has no effect when running in a workspace environment.

However, it should work in circumstances where all active projects include this config option.

### Reproduction

```ts
import {defineConfig, defineWorkspace} from 'vitest/config';

export default defineWorkspace([
  defineConfig({test: {passWithNoTests: true, name: 'batch-a'}}),
  defineConfig({test: {passWithNoTests: true, name: 'batch-b'}}),
]);
```

Then run `pnpm vitest run`. It should exit with 0, but it exits with 1.

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Max
    Memory: 20.41 GB / 96.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.14.0 - ~/.local/state/fnm_multishells/25047_1722535431047/bin/node
    pnpm: 9.6.0 - ~/.local/state/fnm_multishells/25047_1722535431047/bin/pnpm
    bun: 1.1.21 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 127.0.6533.89
    Edge: 127.0.2651.86
    Safari: 17.5
  npmPackages:
    vitest: 2.0.5 => 2.0.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> the config option `test.passWithNoTests` has no effect when running in a workspace environment.

This is expected behavior: https://vitest.dev/config/#passwithnotests

`passWithNoTests` needs to be set in the global config.
