### ISSUE TITLE
Recursive option to test imported children

### ISSUE THREAD

**Issue by guidovdijk** [vitest-dev/vitest#6270]
### Clear and concise description of the problem

As a developer using Vitest I want to recursively test my own imported files when I run `vitest watch SpecificFileOrComponent` (or any equivalant command), so it is easier to test specific parts of my project (see "Additional context" for an example).

_I would like to make a PR for this potential feature_

### Suggested solution

An additional option we can add to the vitest command, like `--recursive` or `--re` to allow a recursive search.

_I apologies if this is an unwanted feature, but for my use-case it would be quite nice-to-have_

### Alternative

I could write something locally where I check all the import statements of my files and generate the `vitest watch` command with all my file names. But I feel like I am just overcomplicating at that point.

### Additional context

I have a lot of test files and when im working on part A of my application I do not care about B-to-Z.
I only care about what I use to make part A work.

### Example
There already exists an option to filter on name. However, this does not meet my use case.

When I have a file `ParentComponent` with the following import statements:
```
import Child1 from '...'
import Child2 from '...'
import useFunctionality from '...'

...
```

Child1:
```
import someFunction from '...'
...
```

(also run `SomeFunction` its tests)

I want to be able to test the `ParentComponent` and also the `Child1`, `Child2`, `useFunctionality`, `someFunction` and their imported files when running `vitest watch ParentComponent`.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
From the description it looks like you are looking for https://vitest.dev/guide/cli.html#vitest-related

**Comment by guidovdijk** [comment]
Ah, yes your right. Thanks mate!
