### ISSUE TITLE
This version of Node.js requires NODE_MODULE_VERSION 115

### ISSUE THREAD

**Issue by asamofal** [vitest-dev/vitest#6286]
### Describe the bug

Hi there! Would appretiate any help here...
I'm building an Electron app, have better-sqlite3 library in the project. On "postinstall" hook I rebuild the native module (better-sqlite3) for my version of node js (20.14.0). Rebuilding works fine (verified). Then I have a test where I try to test a connection to the DB. Here I get the error:

```
Error: The module 'node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 125. This version of Node.js requires
NODE_MODULE_VERSION 115. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

I've created another test where just run `console.log(Node.js version: ${process.version});`, it shows me the same 20.14.0. 
I don't understand from where this "NODE_MODULE_VERSION 115" comes from, wtf? What is 115? Is it v19.x?

<img width="1080" alt="image" src="https://github.com/user-attachments/assets/5933d4a5-7cbb-40ce-8525-ab376893459c">

### Reproduction

-

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (16) arm64 Apple M3 Max
    Memory: 3.30 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
  Browsers:
    Chrome: 127.0.6533.89
    Safari: 17.5
  npmPackages:
    @vitejs/plugin-vue: 5.1.2 => 5.1.2 
    vite: 5.3.5 => 5.3.5 
    vitest: ^2.0.5 => 2.0.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Electron has its own `NODE_MODULE_VERSION`. Try doing what the error says and recompile it against the same Node.js version.

The `NODE_MODULE_VERSION` was previously mentioned in https://nodejs.org/en/about/previous-releases but it was removed, so I don't know what Node.js version corresponds to `NODE_MODULE_VERSION`, but this is clearly not related to Vitest.

**Comment by asamofal** [comment]
@sheremet-va Yes, I know about Electron bundled with their own node version. I tried the way "switching to electron node version" but then vitest fails on Windows:
`cross-env ELECTRON_RUN_AS_NODE=1 electron node_modules/.bin/vitest run -r packages/main`

![image](https://github.com/user-attachments/assets/80ae4507-ff05-4348-b2ab-ca9023ece8af)

Anyway... you said vitest just using the local version of node and this error comes from node itself?
I just tried all the variants that I had in mind, where should I ask for help? Nodejs community? But the problem only when I run the test...

**Comment by sheremet-va** [comment]
> I tried the way "switching to electron node version" but then vitest fails on Windows:

Well, you can't run Vitest under Electron.

Make sure you have the same version globally as you have in Electron.

> Anyway... you said vitest just using the local version of node and this error comes from node itself?

The error comes from `better-sqlite3` because the versions of Node.js that you run locally and in Electron are different. There is nothing here to add, make sure they are the same, this is not a bug, you have misconfigured environment.

**Comment by asamofal** [comment]
> The error comes from better-sqlite3 because the versions of Node.js that you run locally and in Electron are different.

Thank you for the answer, just trying to figure out what's going on... I'm pretty sure I have the same node versions locally and in Electron.

>npm ls electron
> pos-inside@0.0.1 /Volumes/code/pos
>└── electron@31.3.1

In Electron v31.3.0 changelog: `Updated Node.js to v20.15.1`. Locally I switched to v20.15.1 as well:
> node -v
> v20.15.1

So I have the same versions 100%. And I have no problems with Electron, I can run dev/prod builds with no errors. But I have a problem only when I try to run the test, this is confusing me. I'm eager to ask this question in better-sqlite3 repo but don't know how to explain them that the problem only when I try to run the test..

**Comment by sheremet-va** [comment]
> I'm eager to ask this question in better-sqlite3 repo but don't know how to explain them that the problem only when I try to run the test..

The problem is not when you run a test, but when you run the code in local Node.js. Create a `js` file with your code and run it using `node your-file.js` - you should see the same error.

**Comment by asamofal** [comment]
> > I'm eager to ask this question in better-sqlite3 repo but don't know how to explain them that the problem only when I try to run the test..
> 
> The problem is not when you run a test, but when you run the code in local Node.js. Create a `js` file with your code and run it using `node your-file.js` - you should see the same error.

Indeed, you are correct. The same error running a simple js file (with local node) where I init better-sqlite3 connection. Will continue in this directions, thank you.
