### ISSUE TITLE
Declaring a variable name as "it" will throw an error

### ISSUE THREAD

**Issue by Conqorld** [vitest-dev/vitest#6295]
### Describe the bug

Error: Vitest failed to access its internal state.

One of the following is possible:
- "vitest" is imported directly without running "vitest" command
- "vitest" is imported inside "globalSetup" (to fix this, use "setupFiles" instead, because "globalSetup" runs in a different context)

### Reproduction

export function filterParmas<P extends { [key: string]: any }>(
  object: P,
  target: P | (keyof P)[],
): {} {
  const keys = Array.isArray(target) ? target : Object.keys(target);
  return keys.reduce((it, key) => ({ ...it, [key]: object[key] }), {});
}

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M3 Pro
    Memory: 394.69 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.15.0/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
    pnpm: 9.4.0 - ~/.nvm/versions/node/v20.15.0/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.90
    Safari: 17.5
  npmPackages:
    @vitejs/plugin-legacy: ^5.4.1 => 5.4.1 
    @vitejs/plugin-vue: ^5.0.5 => 5.0.5 
    vite: ^5.3.4 => 5.3.4 
    vitest: ^2.0.3 => 2.0.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Works fine here: https://stackblitz.com/~/edit/vitest-dev-vitest-tvszgt?file=test/suite.test.ts&initialPath=/__vitest__/
