### ISSUE TITLE
Exclude setting in vitest config doesn't seem to work

### ISSUE THREAD

**Issue by zr87** [vitest-dev/vitest#6321]
### Describe the bug

Hello there,
I am trying to exclude the `release.config.cjs` and files like `index.js` which are sitting in my root folder of the project.
I tried few different ways to add the entries, for example:

```
export default defineConfig({
	test: {
		exclude:[
			...configDefaults.exclude,
			'**/release.config.cjs', //or 'release.config.cjs' doesn't matter
			'index.js' // or even **/index.*
		],
		coverage: {
			reporter: ['text', 'json', 'html'],
		},
	},
})
```

<img width="329" alt="Screenshot at Aug 11 17-12-17" src="https://github.com/user-attachments/assets/569f5a53-7907-460f-9e8c-ac4f02399edf">

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-mmofno?file=vite.config.ts

in terminal run `npm run coverage`

both the `release.config.js` and `src/basic.ts` are counted in the coverage

<img width="384" alt="image" src="https://github.com/user-attachments/assets/40be7a43-cce1-41c1-ad82-524c6371d3c4">

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 97.78 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.volta/tools/image/node/20.15.1/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 10.7.0 - ~/.volta/tools/image/node/20.15.1/bin/npm
    pnpm: 9.7.0 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 127.0.6533.100
    Safari: 17.5
  npmPackages:
    @vitest/coverage-v8: ^2.0.5 => 2.0.5 
    vitest: ^2.0.5 => 2.0.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
The `test.exclude` tells Vitest which **test files** to not run, e.g. `exclude: ["tests/**/*.integration.test.ts"]` to ignore files that match that pattern.

The `test.coverage.exclude` tells Vitest which **source files** to ignore from coverage report, e.g. `coverage: { exclude: ["src/utils/**"] }` will not include files matching that pattern in coverage report, even when other `src/**` files are. 

See https://github.com/vitest-dev/vitest/issues/4877#issuecomment-1878177031 for example and https://github.com/vitest-dev/vitest/issues/4849 for duplicate issue. 

```diff
export default defineConfig({
	test: {
-		exclude:[
-			...configDefaults.exclude,
-			'**/release.config.cjs', //or 'release.config.cjs' doesn't matter
-			'index.js' // or even **/index.*
-		],
		coverage: {
			reporter: ['text', 'json', 'html'],
+			exclude:[
+				...configDefaults.exclude,
+				'**/release.config.cjs', //or 'release.config.cjs' doesn't matter
+				'index.js' // or even **/index.*
+			],
		},
	},
})
```
