### ISSUE TITLE
Custom Reporter - TaskMetadata is not being sent

### ISSUE THREAD

**Issue by JoFont** [vitest-dev/vitest#6326]
### Describe the bug

When attempting to pass a custom metadata key from the test to the reporter, when reading values from the reporter, metadata is always empty.

The case provided the test is failing but that doesn't change the issue, it is failing after supposedly setting value to the context. and when `console.log()` ing inside the reporter even for tests passing, metadata is always an empty object.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-qwznqt?file=test%2FCustomReporter.ts

in vitest.d.ts
```js
import type {} from "vitest";

declare module "vitest" {
  interface TaskMeta {
    tokenUsage?: number;
  }
}
```

In custom Reporter
```js
import { File } from "@vitest/runner/types";
import c from "tinyrainbow";
import { DefaultReporter } from "vitest/reporters";

export class AiReporter extends DefaultReporter {
  private _totalTokenUsage = 0;

  reportTestSummary(files: File[], errors: unknown[]) {
    super.reportTestSummary(files, errors);

    files.forEach((file) => {
      file.tasks.forEach((task) => {
        if (task.meta.tokenUsage) {
          this._totalTokenUsage += task.meta.tokenUsage;
        }
      });
    });

    this.ctx.logger.log(
      c.blue(`${"Total token usage:".padStart(11)} `),
      this._totalTokenUsage,
    );

    this.ctx.logger.log();
  }
}
```

In test.ts
```js
test("Correctly Parses One-Way Flight Boarding Pass", async (ctx) => {
    const boardingPass = fs.readFileSync(
      path.join(mockFolderPath, "flights", "boarding-pass-one-way.png"),
    );

    const boardingPassImage = await convertDocToImage(boardingPass);
    const result = await intelliDocumentParse(boardingPassImage, JOSE_CONTEXT);

    expect(result.type).toBe(INTELLI_RESULT_TYPE.SUCCESS);

    if (result.type === INTELLI_RESULT_TYPE.SUCCESS) {
      const { parsedDocument, usage } = result.data;

      ctx.task.meta.tokenUsage = usage.totalTokens;

      expect(() =>
        z.array(genericDocument).parse(parsedDocument),
      ).not.toThrow();
      expect(parsedDocument).toEqual([BOARDING_PASS_ONE_WAY]);
    }
  });
```

### System Info

```shell
Test Files  1 failed (1)
      Tests  1 failed | 5 skipped (6)
   Start at  15:18:46
   Duration  21.61s (transform 239ms, setup 0ms, collect 769ms, tests 20.61s, environment 0ms, prepare 52ms)

Total token usage:  0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JoFont** [comment]
Added StackBlitz reproduction: https://stackblitz.com/edit/vitest-dev-vitest-qwznqt?file=test%2FCustomReporter.ts

**Comment by sheremet-va** [comment]
Your test task ("CBasic Test") is located inside a suite task ("suite name"). You need to go one level deeper:

```ts
    files.forEach((file) => {
      file.tasks.forEach((task) => {
        if ('tasks' in task) {
          task.tasks.forEach((task) => {
            if (task.meta.tokenUsage) {
              this._totalTokenUsage += task.meta.tokenUsage;
            }
          });
        }
      });
    });
```

You can make your life easier by either using the new [Reported Task API](https://vitest.dev/advanced/reporters.html#reported-tasks):

```ts
const testFile = this.ctx.state.getReportedEntity(fileTask) as TestFile
for(const test of testFile.children.allTests()) {
    if (test.meta.tokenUsage) {
      this._totalTokenUsage += task.meta.tokenUsage;
    }
}
```

Or write a helper like this:

```ts
function getTests(suite: Arrayable<Task>): (Test | Custom)[] {
  const tests: (Test | Custom)[] = []
  const arraySuites = toArray(suite)
  for (const s of arraySuites) {
    if (isAtomTest(s)) {
      tests.push(s)
    }
    else {
      for (const task of s.tasks) {
        if (isAtomTest(task)) {
          tests.push(task)
        }
        else {
          const taskTests = getTests(task)
          for (const test of taskTests) {
            tests.push(test)
          }
        }
      }
    }
  }
  return tests
}
```

**Comment by JoFont** [comment]
Ah! Didn't notice that part, my bad. :/ 

Thank you so much for your help @sheremet-va! That did the trick!
