### ISSUE TITLE
`toMatchInlineSnapshot` produces invalid code when called inside a loop

### ISSUE THREAD

**Issue by silverwind** [vitest-dev/vitest#6327]
### Describe the bug

Calling `toMatchInlineSnapshot` within a loop produces invalid code:

```ts
import {test, expect} from "vitest";

test("snap", () => {
  for (const str of ["foo", "bar"]) {
    expect(str).toMatchInlineSnapshot();
    // transforms to expect(str).toMatchInlineSnapshot(`"foo"``"bar"`);
  }
});
```
The transformed code produces a runtime error:
```
TypeError: "\"foo\"" is not a function
```

Typescript also does not like it:
```
src/basic.test.ts:5:39 - error TS2349: This expression is not callable.
  Type 'String' has no call signatures.

8     expect(str).toMatchInlineSnapshot(`"foo"``"bar"`);
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-r8dfgp?file=src%2Fbasic.test.ts

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`toMatchInlineSnapshot` is not supported in a loop. We even throw an error when it's called in `test.each`.

**Comment by sheremet-va** [comment]
I guess we can try to find a way to throw an error here for a better DX, but I don't have ideas how. I will keep the issues as open for now.

**Comment by hi-ogawa** [comment]
I remembered Jest throws a better error for this case. I haven't checked how they do, but made a quick repro for a reference https://stackblitz.com/edit/github-tj5mf5?file=basic.test.js

```
 FAIL  ./basic.test.js
  ● Test suite failed to run

    Jest: Multiple inline snapshots for the same call are not supported.
```

**Comment by silverwind** [comment]
Could it be supported, though? It should be possible to encode multiple values in one string, but likely it will need some creative escaping to support all values.

**Comment by sheremet-va** [comment]
> Could it be supported, though? It should be possible to encode multiple values in one string, but likely it will need some creative escaping to support all possible values.

I don't think it could be supported or should be supported. It is much harder to support internally and it makes the result code look even less readable. Use `toMatchSnapshot` if you want to generate snapshots in a loop.
