### ISSUE TITLE
Exclude not working in the Vitest Workspace Config

### ISSUE THREAD

**Issue by stramel** [vitest-dev/vitest#6330]
### Describe the bug

When adding a `test.exclude` at the workspace level, it is ignored. However, if I put the same `test.exclude at the package level in a vitest config, it works. 

### Reproduction

https://stackblitz.com/edit/github-xucvwt?file=vitest.workspace.ts,packages%2Fclient%2Ftest%2Fmemory2048.test.ts

### System Info

```shell
npx envinfo --system --npmPackages '{vitest,@vitest/*,vite,@vitejs/*}' --binaries --browsers

  System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M2 Max
    Memory: 263.83 MB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.volta/tools/image/node/20.15.1/bin/node
    Yarn: 1.22.19 - ~/.volta/bin/yarn
    npm: 10.8.2 - ~/.volta/tools/image/npm/10.8.2/bin/npm
  Browsers:
    Chrome: 127.0.6533.73
    Chrome Canary: 123.0.6270.0
    Edge: 127.0.2651.98
    Safari: 17.5
  npmPackages:
    @vitest/coverage-v8: ^2.0.5 => 2.0.5
    vitest: ^2.0.3 => 2.0.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
> None of the configuration options are inherited from the root-level config file. 
> https://vitest.dev/guide/workspace.html#configuration

**Comment by stramel** [comment]
Okay, but shouldn't this

```js
{
    test: {
      exclude: [...configDefaults.exclude, 'test/memory2048.test.ts'],
    },
  },
```
  
prevent `test/memory2048.test.ts` from running when ran from the root level?

**Comment by AriPerkkio** [comment]
No, that just creates a new project with that setting. It's not applied to other projects.

This would work:

```ts
import { defineWorkspace, configDefaults } from 'vitest/config';

export default defineWorkspace([
  {
    extends: './packages/client/vitest.config.ts', 
    test: {
      name: 'Client',
      root: './packages/client',
      exclude: [...configDefaults.exclude, 'test/memory2048.test.ts'],
    },
  },
  {
    test: {
      name: 'Server',
      root: './packages/server',
      exclude: [...configDefaults.exclude, 'test/memory2048.test.ts'],
    },
  },
]);
```

**Comment by stramel** [comment]
Ah, okay, I misunderstood how that config worked. It seems a little burdensome to require a `vitest.config` at each package level with manual extension in order to support a monorepo with a shared config.

**Comment by AriPerkkio** [comment]
>  It seems a little burdensome to require a `vitest.config` at each package level with manual extension in order to support a monorepo with a shared config.

Yep. Any improvement ideas are welcome.

Similar issue came up here too: https://github.com/vitest-dev/vitest/discussions/6194#discussioncomment-10121949
