### ISSUE TITLE
Library is loadable by `vitest` but not `vite-node`

### ISSUE THREAD

**Issue by jimhigson** [vitest-dev/vitest#6335]
### Describe the bug

The library `unique-names-generator` can be loaded into vitest but not node-vite. My understanding is that node-vite is the engine behind vitest, so it should either work in both or fail in both.

Vitest correctly identifies this as a es6 file. Node-vite tries to load it as cjs.

This is probably due to the library exporting using `.m.js` extension (not `.mjs`) but that doesn't explain why it works in one and not the other.

## Expected behaviour:
* Works in both vitest and vite-node
* (not as good but consistent) - fails in both vitest and vite-node

## Actual behaviour
* `pnpm vitest` in the minimal reproduction passes
* `pnpm vite-node` in the minimal reproduction fails: pn

## Solution
* Make vite-node work like vitest

### Reproduction

[minimal reproduction on github](https://github.com/jimhigson/vitest-minimal-reproduction)

- see README.md in that repo for steps to run.

### System Info

```shell
System:
    OS: macOS 13.6.2
    CPU: (12) arm64 Apple M2 Max
    Memory: 53.94 MB / 32.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.20.2 - ~/.volta/tools/image/node/16.20.2/bin/node
    npm: 8.19.4 - ~/.volta/tools/image/node/16.20.2/bin/npm
    pnpm: 8.6.10 - ~/.volta/tools/image/pnpm/8.6.10/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.100
    Chrome Canary: 129.0.6652.0
    Edge: 127.0.2651.98
    Safari: 16.6
  npmPackages:
    vitest: ^2.0.5 => 2.0.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jimhigson** [comment]
Note that this can be worked around using an alias to force it to load the cjs module. However, this doesn't explain why vitest and vite-node are inconsistent (vite-node needs the workaround but not vitest)

```
import { defineConfig } from 'vite';

export default defineConfig({
  resolve: {
    alias: {
      'unique-names-generator': 'unique-names-generator/dist/index.js',
    },
  },
});
```

**Comment by sheremet-va** [comment]
> However, this doesn't explain why vitest and vite-node are inconsistent (vite-node needs the workaround but not vitest)

Vitest doesn't _just_ use `vite-node`, we change the Vite config value to make libraries like this work. It is in no way guaranteed that your code will work in both.

**Comment by sheremet-va** [comment]
> Vitest correctly identifies this as a es6 file. Node-vite tries to load it as cjs.

Vitest makes it possible to load _incrorectly_ configured package like `unique-names-generator`. It doesn't have an "exports" field or correct file extension. `vite-node` just loads the file using the default vite resolution. Ideally, it should ignore the `module` field, but it is not written to support such a use case out of the box. 

Vitest removes the `module` field from [`resolve.mainFields`](https://vitejs.dev/config/shared-options.html#resolve-mainfields). If you want to have the same behaviour, you can do it yourself:

```ts
export default defineConfig({
  resolve: {
    mainFields: ['main'],
  }
})
```
