### ISSUE TITLE
Cannot use vitest with NestJS and @types/fhir package

### ISSUE THREAD

**Issue by studiojms** [vitest-dev/vitest#6342]
### Describe the bug

When using vitest in a project that uses NestJS, Typescript, and the package `@types/fhir` (being imported into the project from `fhir/r4`), the package is not resolved by vitest and swc (direct dependency to use vitest with NestJS).
I tried setting up vitest without swc, but it didn't work.

The error that happens when tests are run is:

```
Error: Failed to load url fhir/r4 (resolved id: fhir/r4) in ./src/observation/entities/observation.model.ts. Does the file exist?
 ❯ loadAndTransform node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:51787:17
```

### Reproduction

Sample repo: https://github.com/studiojms/nest-vitest-fhir-sample
The problem can be reproduced by running `yarn test` in this repo

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M3
    Memory: 70.92 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.15.1/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
  Browsers:
    Brave Browser: 127.1.68.137
    Chrome: 127.0.6533.101
    Safari: 17.5
  npmPackages:
    @vitest/coverage-v8: ^2.0.5 => 2.0.5 
    vitest: ^2.0.5 => 2.0.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I don't think type files can actually be resolved by Vite if they are not annotated with a `type` keyword. Try this instead:

```ts
import { Observation as FhirObservation } from 'fhir/r4';
```

**Comment by studiojms** [comment]
@sheremet-va I tried adding the type keyword as you suggested, now I'm getting a different error:

```
Error: Nest can't resolve dependencies of the ObservationService (?). Please make sure that the argument "ObservationRepository" at index [0] is available in the RootTestModule context.

Potential solutions:
- Is RootTestModule a valid NestJS module?
- If "ObservationRepository" is a provider, is it part of the current RootTestModule?
- If "ObservationRepository" is exported from a separate @Module, is that module imported within RootTestModule?
  @Module({
    imports: [ /* the Module containing "ObservationRepository" */ ]
  })

 ❯ TestingInjector.lookupComponentInParentModules node_modules/@nestjs/core/injector/injector.js:254:19
 ❯ TestingInjector.resolveComponentInstance node_modules/@nestjs/core/injector/injector.js:207:33
 ❯ TestingInjector.resolveComponentInstance node_modules/@nestjs/testing/testing-injector.js:19:45
 ❯ resolveParam node_modules/@nestjs/core/injector/injector.js:128:38
 ❯ TestingInjector.resolveConstructorParams node_modules/@nestjs/core/injector/injector.js:143:27
 ❯ TestingInjector.loadInstance node_modules/@nestjs/core/injector/injector.js:70:13
 ❯ TestingInjector.loadProvider node_modules/@nestjs/core/injector/injector.js:97:9
 ❯ node_modules/@nestjs/core/injector/instance-loader.js:56:13
```

**Comment by studiojms** [comment]
@sheremet-va One more thing, by adding the type keyword, I started getting some errors when running the project (using swc)

**Comment by studiojms** [comment]
Using the `type` keyword solved the main problem
