### ISSUE TITLE
Getting this.coverageProvider?.generateCoverage is not a function with Vitest 2.0

### ISSUE THREAD

**Issue by bildungsroman** [vitest-dev/vitest#6343]
### Describe the bug

I updated `vitest` from 1.3.1 to 2.0.5 and `@vitest/coverage-v8` from 1.3.1 to 1.6.0. Now when I run tests, the tests are passing, but whenever I'm running with the `--coverage` flag I get the following error:
```shell
TypeError: this.coverageProvider?.generateCoverage is not a function
 ❯ node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js:14947:53
 ❯ Vitest.runFiles node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js:14955:12
 ❯ Vitest.start node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js:14804:7
 ❯ startVitest node_modules/vitest/dist/chunks/cli-api.OKfd3qJ0.js:15893:7
 ❯ start node_modules/vitest/dist/chunks/cac.DGgmCKmU.js:1499:17
 ❯ CAC.run node_modules/vitest/dist/chunks/cac.DGgmCKmU.js:1479:3
```

This is my `vitest.config.ts`:
```javascript
/// <reference types="vitest" />
import { defineConfig } from "vite";
import wasm from "vite-plugin-wasm";

export default defineConfig({
  plugins: [wasm()],
  test: {
    server: {
      deps: {
        inline: [],
      },
    },
    environment: "jsdom",
    coverage: {
      exclude: [
        "dist-package/",
        "src/__generated__/",
        "src/localDev.tsx",
        "src/_tests/",
      ],
      reporter: ["text", "cobertura", "html"],
    },
  },
});

```

### Reproduction

Run `vitest run --coverage` with `@vitest/coverage-v8` installed.

### System Info

```shell
System:
    OS: macOS 14.6
    CPU: (8) arm64 Apple M1
    Memory: 248.81 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.7.0 - ~/.nvm/versions/node/v20.7.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.7.0/bin/npm
  Browsers:
    Chrome: 127.0.6533.119
    Edge: 127.0.2651.98
    Safari: 17.6
  npmPackages:
    @vitejs/plugin-react: ^4.0.0 => 4.3.1 
    @vitest/coverage-v8: ^1.6.0 => 1.6.0 
    vite: ^5.1.7 => 5.2.13 
    vitest: ^2.0.5 => 2.0.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
> I updated vitest from 1.3.1 to <ins>**2.0.5**</ins> and @vitest/coverage-v8 from 1.3.1 to <ins>**1.6.0**</ins>

Update your `vitest` and `@vitest/coverage-*` packages to same version.

**Comment by AriPerkkio** [comment]
In future we'll print helpful warning in these cases: https://github.com/vitest-dev/vitest/pull/6317
