### ISSUE TITLE
Snapshots do not generate CSS class definitions

### ISSUE THREAD

**Issue by hal-alex** [vitest-dev/vitest#6345]
### Describe the bug

Hello, 

I am in the process of migrating a project from Jest to Vitest and I came across this issue where the CSS class definitions are not included inside the generated snapshots.

In Jest, each CSS class is defined at the top of the snapshot so any changes in the document's CSS properties can be caught by the matcher. 

For example, something like the below screenshot.

![image](https://github.com/user-attachments/assets/ca728e6e-0dc0-44da-9747-33a8d5124f45)

However, I noticed that Vitest does not include these CSS properties for each element in the snapshot, it seems to simply provides the classes. 

I tested it with vanilla CSS and Styled Components, the outcome is the same.

I also tried to play around with the `css` prop in `defineVitestConfig`, which didn't yield any results.

![image](https://github.com/user-attachments/assets/c6e35b14-1648-4434-9a75-10e0acf8f856)

[Here's an example](https://github.com/hal-alex/vitest-issue/blob/main/src/__tests__/__snapshots__/App.test.tsx.snap#L56) of the Vitest generated snapshot with a couple of my comments for a dummy project.

Does Vitest support this functionality? If so, how can I configure for it to work?

### Reproduction

Repo with the project can be found here: https://github.com/hal-alex/vitest-issue/tree/main

This is my `vite.config.ts` (yes I know there are some hacky parts here)

```import react from "@vitejs/plugin-react"
import tsconfigPaths from "vite-tsconfig-paths"
import svgr from "vite-plugin-svgr"
import { NodeGlobalsPolyfillPlugin } from "@esbuild-plugins/node-globals-polyfill"

import { defineConfig as defineViteConfig, mergeConfig } from "vite"
import { defineConfig as defineVitestConfig } from "vitest/config"

// https://vitejs.dev/config/
const viteConfig = defineViteConfig({
  plugins: [react(), tsconfigPaths(), svgr()],
  server: {
    port: 3000,
  },
  resolve: {
    alias: {
      src: "/src",
    },
  },
  build: {
    outDir: "build",
  },
  optimizeDeps: {
    esbuildOptions: {
      // Node.js global to browser globalThis
      define: {
        global: "globalThis",
      },
      // Enable esbuild polyfill plugins
      plugins: [
        NodeGlobalsPolyfillPlugin({
          buffer: true,
        }),
      ],
    },
  },
})

const vitestConfig = defineVitestConfig({
  test: {
    environment: "jsdom",
    globals: true,
    // css: true,
  },
})

export default mergeConfig(viteConfig, vitestConfig)```

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700K
    Memory: 47.86 GB / 63.79 GB
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @vitejs/plugin-react: ^4.3.1 => 4.3.1
    vite: ^5.4.0 => 5.4.0
    vitest: ^2.0.5 => 2.0.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Lani** [comment]
From your screenshot it looks like you previously have used the @emotion/jest package with Jest.

From my brief trial and error, you can use the same package with Vitest.

[Setup a Vitest setup file](https://vitest.dev/config/#setupfiles) and add the following code to the setup file:

```js
import { createSerializer } from '@emotion/jest';

expect.extend(MachineMatchers);
expect.addSnapshotSerializer(createSerializer({ includeStyles: true }));
```

**Comment by sheremet-va** [comment]
> From your screenshot it looks like you previously have used the @emotion/jest package with Jest.
> 
> From my brief trial and error, you can use the same package with Vitest.
> 
> [Setup a Vitest setup file](https://vitest.dev/config/#setupfiles) and add the following code to the setup file:
> 
> ```js
> import { createSerializer } from '@emotion/jest';
> 
> expect.addSnapshotSerializer(createSerializer({ includeStyles: true }));
> ```

This is a solution. You can also add `@emotion/jest/serializer` to your config:

```ts
export default defineConfig({
  test: {
    snapshotSerializers: [
      '@emotion/jest/serializer',
    ],
  },
})
```

Docs: https://emotion.sh/docs/@emotion/jest

**Comment by mankittens** [comment]
```js
import { createSerializer } from '@emotion/jest';

expect.addSnapshotSerializer(createSerializer({ includeStyles: true }));
```

The above solution worked for me. The below solution did not.

```js
export default defineConfig({
  test: {
    snapshotSerializers: [
      '@emotion/jest/serializer',
    ],
  },
})
```

Would be nice to have this as a part of the docs! 🙏

**Comment by hal-alex** [comment]
Thanks all for the replies. The project I am migrating uses styled components and not emotion. @Lani @sheremet-va  do you know what the solution would look like for styled components?
