### ISSUE TITLE
Support spread parameters for extensions [in types]

### ISSUE THREAD

**Issue by wheresrhys** [vitest-dev/vitest#6350]
### Clear and concise description of the problem

I'm porting [fetch-mock-jest](https://github.com/wheresrhys/fetch-mock-jest) to a new version for vitest.

In order to create an API that blends jest's mock function assertions and fetch-mock's filtering API I used the following signature:

```ts
toHaveLastFetched: ({ fetchMock }: { fetchMock: FetchMock }, filter: CallHistoryFilter, options: RouteConfig): SyncExpectationResult => {
```

Which in turn relies on jest's [use of spread parameters](https://github.com/jestjs/jest/blob/0d96de975783ee78192c1037862ea3089f52dc25/packages/expect/src/types.ts#L38): 

However vitest [does not use spread](https://github.com/vitest-dev/vitest/blob/99452a712c83e4e90a8afd5675e6573e1c22a43a/packages/expect/src/types.ts#L88), forcing me to put all my options in a single object, rather than the previous API design which was far more idiomatic fro fetch-mock users.

### Suggested solution

Implement the same API as jest.

I wonder if you are already doing this internally, only the types do not reflect it? (I have some tests which I would expect to fail, as I am passing additional parameters into my `RawMatcherFn` instances, however the tests pass; it is only the type checking that does not)

### Additional context

@fetch-mock/vitest codebase https://github.com/wheresrhys/fetch-mock/pull/781/files#diff-9a85644e0fd893bb1f83cfadf2bac0296379d4fb55a14d81d1f6699d0e13364fR34

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Seems like types are incorrect. We spread the value at runtime.

**Comment by wheresrhys** [comment]
I'll submit a PR that copies the typedef in from jest to see if that works
