### ISSUE TITLE
Ability to customize the "assetPrefix" for HTML report.

### ISSUE THREAD

**Issue by Zizzamia** [vitest-dev/vitest#6357]
### Clear and concise description of the problem

We are using Vite for https://onchainkit-coverage.vercel.app/, which loads really well when used at the top-level domain.

But as soon as we run the report in its own subfolder, https://onchainkit.xyz/coverage, the HTML report struggles to handle static files and page links.

### Suggested solution

I think one feature that could make this super easy is the ability to set `assetPrefix`. This would be similar to what Next.js has at https://nextjs.org/docs/app/api-reference/next-config-js/assetPrefix.

Ideally, that can be added to the report config
```
reporter: [
        [
          'html',
          {
            assetPrefix: 'https://onchainkit.xyz/coverage/',
          },
        ],
      ],
``` 

Thank you again for building Vitest. We really love writing test with it.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
It looks like all assets inside html are relative, so accessing https://onchainkit.xyz/coverage/index.html seems to work already. I think if you tweak a vercel config, then https://onchainkit.xyz/coverage/ would also work too (currently 404).

If you want trailing slash stripped `/coverage`, then it might need a different approach though.

**Comment by Zizzamia** [comment]
@hi-ogawa thank you for the quick reply. So we use the `vercel.json` rules to organize the coverage page.
Here file: https://github.com/coinbase/onchainkit/blob/main/vercel/vercel.json

Also, knowing https://onchainkit.xyz/coverage/index.html works and sublinks too https://onchainkit.xyz/coverage/src/identity/hooks/index.html, that's very good news. 🗞️

Now I wonder, if I should experiment with `vercel.json` rules a bit more.

**Comment by hi-ogawa** [comment]
Btw, Vitest's coverage reporter generation is delegated to istanbuljs (like html reporter here  https://github.com/istanbuljs/istanbuljs/blob/main/packages/istanbul-reports/lib/html/index.js), so the feature request needs to go there if this requires fundamental change.

I just found they support custom `linkMapper`, but playing with it, it looks tricky to achieve what you need (assuming what you want is to serve it without trailing slash https://onchainkit.xyz/coverage). Note that `<a href>` link is also relative, so implementing "assetPrefix" alone won't solve your issue.

One quick hack I'm thinking is to inject `<base>` https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base into your root index.html. Something like `<base href="/coverage/" />` would allow relative links to resolved correctly even when served in `/coverage`.

**Comment by Zizzamia** [comment]
Feel free to close this issue, I end up using https://onchainkit.xyz/coverage/ with `/` and do some re-routing magic to have https://onchainkit.xyz/coverage reroute to https://onchainkit.xyz/coverage/

**Comment by hi-ogawa** [comment]
Yeah, your setup looks good to me :+1:  Okay closing.
