### ISSUE TITLE
NestJS E2E tests failing when using vitest (when using sequelize query)

### ISSUE THREAD

**Issue by studiojms** [vitest-dev/vitest#6366]
### Describe the bug

I have a project using NestJS, Sequelize, Sequelize-Typescript, and Testcontainers. The E2E test is responsible for setting up some data and testing an API.
By relying on the sequelize-typescript project, when querying some data, the result should be an object populated. It works as desired when using jest, but after converting my tests to vitest, it's not working as expected.
My query result is returned with some empty fields (although the object brings the data I want in some hidden property).

```json
{
  subject: Subject {
    dataValues: {
      id: '59a59521-665c-4a21-86ea-8044da9c33ac',
      description: 'test',
      orderId: '56b6f0aa-c592-44d6-b0b7-e02dc1910a03',
      createdAt: 2024-08-19T18:38:18.962Z,
      updatedAt: 2024-08-19T18:38:18.962Z,
      observations: [Array]
    },
    _previousDataValues: {
      id: '59a59521-665c-4a21-86ea-8044da9c33ac',
      description: 'test',
      orderId: '56b6f0aa-c592-44d6-b0b7-e02dc1910a03',
      createdAt: 2024-08-19T18:38:18.962Z,
      updatedAt: 2024-08-19T18:38:18.962Z,
      observations: [Array]
    },
    uniqno: 1,
    _changed: Set(0) {},
    _options: {
      isNewRecord: false,
      _schema: null,
      _schemaDelimiter: '',
      include: [Array],
      includeNames: [Array],
      includeMap: [Object],
      includeValidated: true,
      attributes: [Array],
      raw: true
    },
    isNewRecord: false,
    observations: undefined,
    id: undefined,
    description: undefined,
    orderId: undefined
  }
}
```

If I try to get `subject.id`, `subject.description` or anything, it returns `undefined`.

What I am missing here? Why did it work with jest?

### Reproduction

To reproduce the bug, here's the repo: https://github.com/studiojms/nest-vitest-fhir-sample

The E2E test is here: https://github.com/studiojms/nest-vitest-fhir-sample/blob/main/test/app.e2e-spec.ts

This is the repo with jest setup for E2E (working): https://github.com/studiojms/nest-vitest-fhir-sample/tree/2042a1c32bf5c9e74e352b1bf2f67b07986d9afb

The problem happens at this line when it tries to check the query result: https://github.com/studiojms/nest-vitest-fhir-sample/blob/main/src/subject/subject.service.ts#L30

To execute the project, run:
```
npm run test:e2e
```
or
```
yarn test:e2e
```

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M3
    Memory: 68.89 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.15.1/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
  Browsers:
    Brave Browser: 127.1.68.141
    Chrome: 127.0.6533.120
    Safari: 17.6
  npmPackages:
    @vitest/coverage-v8: ^2.0.5 => 2.0.5 
    vitest: ^2.0.5 => 2.0.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
How is this different from https://github.com/vitest-dev/vitest/issues/6342? If the underlying issue is suspected to be same `fhir`, then I think you can add details there.

**Comment by studiojms** [comment]
@hi-ogawa this issue has nothing to do with #6342 , it's only related to the E2E tests, not `fhir` package. I'm just using the same project to reproduce the error

**Comment by hi-ogawa** [comment]
Thanks for closing the other issue :+1: 

Now looking at your vitest config https://github.com/studiojms/nest-vitest-fhir-sample/blob/2353826c6866e40c016c3b3be860a007f267f189/test/vitest.config.mts#L16, it might be necessary to enable swc's typescript decorator transpilation. There was `examples/nest` in the past (now it's removed though) and it looked like this:

https://github.com/vitest-dev/vitest/blob/d68a73908ef00f1b7c6584ef015657b3a11416bf/examples/nestjs/vitest.config.ts#L6-L18

**Comment by studiojms** [comment]
@hi-ogawa thanks for the tip, I tried adding the params to my `vitest.config` file, but unfortunately, it didn't produce the expected output, tests keep failing with the same error...

**Comment by hi-ogawa** [comment]
Hmm, I just noticed Nest.js has documentation for Vitest https://docs.nestjs.com/recipes/swc#vitest and it looks like just using `swc.vite` is meant to work. 

Then I would suspect `sequenlize-typescript` is having some issues with decorator on Vitest. It looks like there's an open issue there https://github.com/sequelize/sequelize-typescript/issues/1711 Probably tacking that reproduction might be an easier way to understand the issue.

**Comment by Davide-Gheri** [comment]
I had the same issue and I fixed it by adding `useDefineForClassFields: false` to the `jsc.transform`, my full Swc config in vitest is:

```typescript
swc.vite({
  module: { type: 'es6' },
  jsc: {
    transform: {
      useDefineForClassFields: false,
    },
  },
}),
```

As a note, useDefineForClassFields to false is the default swc config for @nestjs/cli

**Comment by studiojms** [comment]
Thank you so much @Davide-Gheri , that solved the problem
