### ISSUE TITLE
Extend existing `list` command to output only a list of file names

### ISSUE THREAD

**Issue by pleunv** [vitest-dev/vitest#6374]
### Clear and concise description of the problem

https://github.com/vitest-dev/vitest/issues/2901 lead to the introduction of the [`vitest list`](https://vitest.dev/guide/cli.html#vitest-list) command, but unfortunately this is pretty slow and requires some processing if you're only interested in a list of _files_ that will run with the given filters & flags (i.e. `--changed`), since it parses all test files and returns a list containing every individual test case. What I ideally would want is a command that returns which files are going to be executed given the provided filters & flags without drilling down to individual test cases, requiring only a lookup and eliminating the need for a parse, thus being a lot quicker.

My main use-case for this is dynamic sharding, where I dynamically determine the amount of shards and agents I want to spin up based on a predetermined number `TESTS_PER_SHARD` (i.e. `100`), which serves to keep the test performance stable, irregardless of number of tests. Jest for example can achieve this with [`--listTests [--json]`](https://jestjs.io/docs/cli#--listtests), which runs in under a second for ~1k test files and leads to the following output:

**`jest --listTests`**

```
/path/to/testA.spec.tsx
/path/to/testB.spec.tsx
```
**`jest --listTests --json`**

```
["/path/to/testA.spec.tsx", "/path/to/testB.spec.tsx"]
```

For comparison, running `vitest list --json` on an M1 MBP for the same ~1k files takes 3.5 minutes.

### Suggested solution

Since there is already a dedicated `list` command I suppose it would make sense to provide a new optional flag, i.e. `--filesOnly`.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
> since it parses all test files and returns a list containing every individual test case

It doesn't parse it, it runs the code to collect tests. This is what mocha does for example.

**Comment by Ma-hawaj** [comment]
Can I try working on this ?
