### ISSUE TITLE
stubs to contain events and props

### ISSUE THREAD

**Issue by steven-twerdochlib** [vitest-dev/vitest#6376]
### Clear and concise description of the problem

It would be great to be able to test custom components from the template area while stubbed. For example, lets say I have the following: `<customComponent @click="runRandomMethod" class="randomClass"><\customComponet>` in my class and customComponent.vue has a bunch of properties, mapGetters and methods. 
I don't care about the required props in another class or the methods so I would shallowMount it but the issue with this is I can't find the component to trigger a click event that would run "runRandomMethod()". I think it would be nice to somehow keep the events (things that start with @) and keep the props we send (things that start with :) and anything else like class so that we can test if another user accidentally changes something important there e.g. mispelling runRandomMethod.
Let me know if anything I said is confusion I would be happy to elaborate.

### Suggested solution

I'm not sure, you would have to change what stubbing returns I guess.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I think you meant to open an issue at https://github.com/vuejs/test-utils. Vitest doesn't provide any way to mount Vue components.
