### ISSUE TITLE
Incorrect Branch Coverage with coverage-v8 in Browser Mode and export Declaration

### ISSUE THREAD

**Issue by oscarmarina** [vitest-dev/vitest#6380]
### Describe the bug

I'm experiencing an issue with branch coverage when using coverage-v8 in browser mode, specifically with export declarations.

Here is the relevant code in my index.js file:

```js
export { CounterElement } from './CounterElement.js';
```

The branch coverage is reported incorrectly.

<img width="1169" alt="incorrect-coverage1" src="https://github.com/user-attachments/assets/b9218fe4-19c0-4fed-add3-db838e46f273">

<img width="1169" alt="incorrect-coverage2" src="https://github.com/user-attachments/assets/cfa34b66-d397-4ef2-a317-d364131d7016">

==

I believe this issue might be related to [issue #6300](https://github.com/vitest-dev/vitest/issues/6300).

### Reproduction

You can reproduce the issue with the following repository:

https://github.com/oscarmarina/lit-vitest-testing-comparison

1. Clone the repository
2. Run the following commands:

```js
npm i && npm run test
```

**Alternatively, you can reproduce it directly in StackBlitz:**

Open another terminal window and type the command npm run test.

https://stackblitz.com/github/oscarmarina/lit-vitest-testing-comparison

<img width="854" alt="stackblitz-run-test" src="https://github.com/user-attachments/assets/c6fb6dbf-dc6d-44a9-bd51-b52991d28d3b">

*
"Checking in StackBlitz, it only works with Istanbul coverage.

<img width="345" alt="Screenshot 2024-08-22 at 15 29 45" src="https://github.com/user-attachments/assets/179bd4c4-c6b8-4a40-83a6-a5b72ac37770">

With V8 coverage, the following error occurs: Error: CDP is not supported by the provider 'preview'."

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (8) arm64 Apple M3
    Memory: 86.33 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.5.1 - ~/.nvm/versions/node/v22.5.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.5.1/bin/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v22.5.1/bin/npm
  Browsers:
    Chrome: 127.0.6533.120
    Chrome Canary: 130.0.6671.0
    Edge: 127.0.2651.105
    Safari: 17.6
    Safari Technology Preview: 18.0
  npmPackages:
    @vitest/browser: ^2.1.0-beta.6 => 2.1.0-beta.6
    @vitest/coverage-istanbul: ^2.1.0-beta.6 => 2.1.0-beta.6
    @vitest/coverage-v8: ^2.1.0-beta.6 => 2.1.0-beta.6
    @vitest/ui: 2.1.0-beta.6 => 2.1.0-beta.6
    vite: ^5.4.0 => 5.4.1
    vitest: ^2.1.0-beta.6 => 2.1.0-beta.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
What's expected result here? Your test case is not importing that file so it's shown as uncovered.

**Comment by oscarmarina** [comment]
Hi @AriPerkkio, after reviewing your comment, which makes perfect sense, what actually happens is that when using the "istanbul reporter", the **index.js file is ignored** by default and is not included in the coverage.

**screenshot of coverage with istanbul reporter**
<img width="864" alt="istanbul reporter" src="https://github.com/user-attachments/assets/4116d486-1386-4b63-a829-fe83b50a757e">

Without changing anything, but using the "v8 reporter", the **index.js file is indeed considered**, and as you correctly pointed out, it makes sense that it would "fail."

Currently, I work with [Web Test Runner,](https://modern-web.dev/docs/test-runner/writing-tests/code-coverage/#ignoring-uncovered-lines) which also uses v8-to-istanbul, and the behavior is the same as when using Vitest with istanbul reporter, hence my confusion.

I understand this isn't an issue, but shouldn't the istanbul reporter take the index.js file into account?

**Comment by AriPerkkio** [comment]
> Currently, I work with [Web Test Runner,](https://modern-web.dev/docs/test-runner/writing-tests/code-coverage/#ignoring-uncovered-lines) which also uses v8-to-istanbul, and the behavior is the same as when using Vitest with istanbul provider, hence my confusion.

Looks like Web Test Runner does not support showing coverage for files that were not imported by test files. If you want same experience on Vitest, set [`coverage.all`](https://vitest.dev/config/#coverage-all) to `false`. Though I would not recommend this as it gives inaccurate results for your overall coverage.

- https://github.com/modernweb-dev/web/issues/1880
- https://github.com/modernweb-dev/web/issues/1873

> the "istanbul provider", the index.js file is ignored by default and is not included in the coverage.

I'm not sure why the file doesn't show up at all. Maybe because Istanbul doesn't instrument `import` and `export` statements at all? https://github.com/istanbuljs/istanbuljs/blob/main/packages/istanbul-lib-instrument/src/visitor.js
