### ISSUE TITLE
Test with `expect(promise).resolves` with promise that never resolves and without `await` hangs

### ISSUE THREAD

**Issue by 4ndypanda** [vitest-dev/vitest#6386]
### Describe the bug

The docs for https://vitest.dev/api/expect.html#resolves state
> If the assertion is not awaited, then you will have a false-positive test that will pass every time.

which made me think that the second test without the `await` on the assertion would just return and pass
```
import { expect, test } from 'vitest';

test('times out from test function timeout', async () => {
  await expect(new Promise((_resolve) => {})).resolves.toEqual(1);
});

test('hangs forever', async () => {
  expect(new Promise((_resolve) => {})).resolves.toEqual(1);
});
```
but instead it just hangs forever.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-7mithq?file=test%2Fbasic.test.ts

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: latest => 2.0.5 
    vite: latest => 5.4.2 
    vitest: latest => 2.0.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
`Promise.allSettled` is hanging and this is outside of test timeout logic, so nothing happens

https://github.com/vitest-dev/vitest/blob/85fb94a3081558b01f47bd763ccdaeb5df1b98cb/packages/runner/src/run.ts#L226-L228

It looks like the documentation for `resolves` warning is not correct and Vitest automatically awaits them.
