### ISSUE TITLE
support passing through arguments

### ISSUE THREAD

**Issue by sombriks** [vitest-dev/vitest#6390]
### Clear and concise description of the problem

i need this command to be valid: 

```bash
vitest run --coverage -- --env-file=.env --env-file=.env.test
```

### Suggested solution

add support for it

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Vitest doesn't support Node.js arguments and we don't have plans to support them. If you need to use `.env` file, you can use `--mode` flag that will [use your local `.env.{mode}`](https://vitejs.dev/guide/env-and-mode.html#env-variables-and-modes) by default. Note that envs need to start with `VITE_` by default, but it can be configured with [`envPrefix`](https://vitejs.dev/config/shared-options.html#envprefix).

**Comment by sombriks** [comment]
> Vitest doesn't support Node.js arguments and we don't have plans to support them. If you need to use `.env` file, you can use `--mode` flag that will [use your local `.env.{mode}`](https://vitejs.dev/guide/env-and-mode.html#env-variables-and-modes) by default. Note that envs need to start with `VITE_` by default, but it can be configured with [`envPrefix`](https://vitejs.dev/config/shared-options.html#envprefix).

i had no idea it was intentional, i will try an alternative approach, thanks.

**Comment by sombriks** [comment]
My usecase is vitest on backend, testing fastiify running under tsx. 

So the VITE_ prefix could be troublesome, since i only need vitest, not vite.

this config is my current workaround:

```typescript
import {defineConfig} from "vite";
import {config} from 'dotenv'

export default defineConfig({
    test: {
        env: {
            "NODE_ENV": "test",
            ...config({path: '.env'}).parsed,
            ...config({path: '.env.test'}).parsed,
        }
    },
})
```

**Comment by AriPerkkio** [comment]
You can also pass NodeJS exec arguments to test runner threads/processes. Note that these won't be available in main thread, e.g. reporters or global setup.

```ts
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    poolOptions: {
      forks: { execArgv: ["--env-file=.env.custom"] },

      // or threads if that pool is used
      threads: { execArgv: ["--env-file=.env.custom"] },
    },
  },
});
```

https://vitest.dev/config/#pooloptions-forks-execargv
