### ISSUE TITLE
"Unknown file extension .ts" when importing file ending with *-js like suffix

### ISSUE THREAD

**Issue by fgaudo** [vitest-dev/vitest#6418]
### Describe the bug

In a test file, when i import a local module called solid-js.ts (content is irrelevant) using an import like
```ts
import '../../../core/solid-js'
```

Then running vitest gives 
```sh
TypeError: Unknown file extension ".ts" for /Users/gaudo/Projects/fridgy/main/src/ui/core/solid-js.ts
```

If i rename the file to solid-jas.ts and import it like this
```ts
import '../../../core/solid-jas'
```

then the type error is gone, and vitest correctly tells me that there are no test suites.

It also happens if i add a `.js` suffix to the import statement

### Reproduction

Reproduction is shown in the description. A test file with only that import statement.

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 2.58 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    pnpm: 9.9.0 - ~/.nvm/versions/node/v20.17.0/bin/pnpm
  Browsers:
    Brave Browser: 128.1.69.153
    Safari: 17.5
  npmPackages:
    @vitest/coverage-v8: ^2.0.5 => 2.0.5
    vite: ^5.4.2 => 5.4.2
    vitest: ^2.0.5 => 2.0.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
I followed your description but I couldn't reproduce with our basic example https://stackblitz.com/edit/vitest-dev-vitest-dzakzb?file=test%2Frepro.test.ts

Either I missed some steps or you project has some plugins which is causing an issue, so it would be great to have a complete reproduction.

**Comment by fgaudo** [comment]
@hi-ogawa 
I tried copying all the configs, plugins and such on a stackblitz instance, but i could not reproduce it..
I even tried nesting the files in subdirectories in a similar way, with no result.

The only thing i can do is maybe create a temporary branch on my project with just that failing test for you to run.
But i understand that i could be asking too much..

Let me know if you want to try that way, otherwise i will just rename the file to avoid the error.

**Comment by hi-ogawa** [comment]
> The only thing i can do is maybe create a temporary branch on my project with just that failing test for you to run.

That's better than nothing, so please feel free to share (though we cannot guarantee anyone is going to look into it).

**Comment by fgaudo** [comment]
@hi-ogawa 
The project is this one https://github.com/fgaudo/fridgy/tree/vitest-test .
branch **vitest-test**.

In src/test i created a failing test and a green test, which differ only by the name of the imported file.

to install: `pnpm install`
to run the failing test: `pnpm exec vitest src/test/failing.test.ts`
to run the green test: `pnpm exec vitest src/test/success.test.ts`

**Comment by hi-ogawa** [comment]
Thanks for the repro. I didn't notice at first, but the error clearly depends on the exact string `"solid-js"`. Commenting out `solid` plugin also makes `src/test/failing.test.ts` pass, so the issue is likely on solid plugin side.

Not exactly same, but there's Vitest related issue reported there https://github.com/solidjs/vite-plugin-solid/issues/157. Please check on solid plugin repo.
