### ISSUE TITLE
vitest fails to recognize webpack module federation components because of which the tests fail

### ISSUE THREAD

**Issue by sumeetgodse** [vitest-dev/vitest#6466]
### Describe the bug

`vitest` fails to recognize webpack module federation components from remote applications because of which the tests fail

I am currently using vitest (0.33.0) in my application for testing the code. When I tried to upgrade to the latest version (2.0.5) , I encountered the below problem. I am not able to find a good way to fix this and proceed so creating this report.

<img width="377" alt="image" src="https://github.com/user-attachments/assets/00e86310-1d18-4627-b0aa-14a80e6a6931">

Any help to resolve the issue appreciated. Thanks!

### Reproduction

This is a very simple & minimal reproduction for the issue I am facing -

https://github.com/sumeetgodse/testing-microfes-1

Clone the repo

**app1**

- cd app1
- npm install
- npm start

<img width="379" alt="image" src="https://github.com/user-attachments/assets/552c87b2-4f8f-44ee-9a87-92c3465a3463">

Tests for app1 (tests for apps that do not import any module federation components PASS)

- npm test

<img width="390" alt="image" src="https://github.com/user-attachments/assets/242d4f76-d2c4-4c24-9627-9e2d4736f893">

**container**

- cd container
- npm install
- npm start

<img width="474" alt="image" src="https://github.com/user-attachments/assets/efa51281-be35-4293-a0d6-ace4d5a1896c">

Tests for container (FAILS)

<img width="380" alt="image" src="https://github.com/user-attachments/assets/2637a377-9c9b-488b-8615-3673abe64f9a">

Any help appreciated, Thanks!

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1265U
    Memory: 5.26 GB / 15.44 GB
  Binaries:
    Node: 18.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.3.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.10.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    vitest: ^2.0.5 => 2.0.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest doesn't know what `app1` is. To fix this, you can add aliases to your `vitest.config`, for example:

```ts
import { defineConfig } from 'vitest/config'
import { fileURLToPath } from 'node:url'

export default defineConfig({
  resolve: {
    alias: [
      { find: /^app1/, replacement: fileURLToPath(new URL('../app1/src/components', import.meta.url)) }
    ],
  },
})
```
