### ISSUE TITLE
some change should be marked as breaking change IMO

### ISSUE THREAD

**Issue by rluvaton** [vitest-dev/vitest#6468]
I think the following PR should be marked as breaking changed even thought it not following semver:
- https://github.com/vitest-dev/vitest/pull/5926

In my company we use nx and the vitest integration, the wrapper calling `startVitest`, and in case no files exist the process used to exit but now it hangs

I know the docs says it does not follow semver, but I think it should still be marked as breaking to have more people notice that

**Comment by sheremet-va** [comment]
Sure, I moved it to breaking changes: https://github.com/vitest-dev/vitest/releases/tag/v2.0.0-beta.13

**Comment by rluvaton** [comment]
Thanks, most people will read the 2.0.0 release changelog rather than the beta
https://github.com/vitest-dev/vitest/releases/tag/v2.0.0

**Comment by sheremet-va** [comment]
Ok, agree. Updated also the 2.0.0 page.

**Comment by rluvaton** [comment]
thanks
