### ISSUE TITLE
Website cached 

### ISSUE THREAD

**Issue by LeOndaz** [vitest-dev/vitest#6470]
### Describe the bug

This link doesn't work: https://arc.net/l/quote/lfyghfii (link to highlight)

But, the link is correct in the codebase, which means your caching system is doing something

### Reproduction

Open: https://arc.net/l/quote/lfyghfii
Open the codebase at the same place
Compare the links

### System Info

```shell
N/A
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Looks like a SPAM. I've deleted links and closed the issue.
