### ISSUE TITLE
provide and inject are missing

### ISSUE THREAD

**Issue by ThallesP** [vitest-dev/vitest#6475]
### Describe the bug

I need to pass some environment variables from the setup-global file to my tests (testcontainers) and the only way seems to be using provide and inject but they dont exist anymore? is the docs outdated?

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-ukvzcz?file=vite.config.ts

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 5600G with Radeon Graphics
    Memory: 7.35 GB / 11.37 GB
    Container: Yes
    Shell: 3.6.1 - /usr/bin/fish
  Binaries:
    Node: 20.15.0 - /run/user/1000/fnm_multishells/192225_1726063919715/bin/node
    npm: 10.7.0 - /run/user/1000/fnm_multishells/192225_1726063919715/bin/npm
    pnpm: 8.15.6 - /mnt/c/Program Files/nodejs/pnpm
  Browsers:
    Chrome: 127.0.6533.119
  npmPackages:
    vitest: ^2.0.5 => 2.0.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Does this help?

```diff
+ import type { GlobalSetupContext } from 'vitest/node'

+ export default function setup({ provide }: GlobalSetupContext) {
- export default function setup() {
-  //@ts-ignore
  provide('teste', 'teste');
}
```

https://vitest.dev/config/#globalsetup

**Comment by ThallesP** [comment]
> Does this help?
> 
> ```diff
> + import type { GlobalSetupContext } from 'vitest/node'
> 
> + export default function setup({ provide }: GlobalSetupContext) {
> - export default function setup() {
> -  //@ts-ignore
>   provide('teste', 'teste');
> }
> ```
> 
> https://vitest.dev/config/#globalsetup

damn sorry, for some reason I didn't see that the `provide` function is got from the parameters, I thought it was global for some reason. Anyway, closing this issue.
