### ISSUE TITLE
postgres client cannot connect correctly

### ISSUE THREAD

**Issue by himself65** [vitest-dev/vitest#6477]
### Describe the bug

I was using vitest to init postgres client and do some unit test but it crash on CI with some weird errors.

```shell
error: no PostgreSQL user name specified in startup packet
```

https://github.com/run-llama/LlamaIndexTS/actions/runs/10821140357/job/30022585957?pr=1186

But I move the code into node test runner it works well.

commit: https://github.com/run-llama/LlamaIndexTS/pull/1186/commits/9fdbecf23af978a4bd9bd139aa72940015111a95

### Reproduction

```ts
import pg from "pg";
import { describe, expect, test } from "vitest";

describe("pg - init", () => {
  test("init with client", async () => {
    const client = new pg.Client({
      database: "node_test",
    });
    await client.connect();
  });
});
```

### System Info

```shell
GitHub Action ubunutu-latest
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
I have to guess this is some infra setup issue like environment variable with github action `ankane/setup-postgres` or something. I don't think we can really debug your project's CI, so please prepare something more minimal.
