### ISSUE TITLE
type check not work

### ISSUE THREAD

**Issue by rikisamurai** [vitest-dev/vitest#6478]
### Describe the bug

I followed the official examples to use Vitest and Vite for type checking, but even when there are type errors, no errors are reported, and the test cases still pass.

```ts
import { expect, expectTypeOf, test } from 'vitest'

test('type', () => {
    expectTypeOf(1).toEqualTypeOf('2')
    expectTypeOf({ a: 11 }).toEqualTypeOf<{ a: string }>();
    expect(1).toBe(2) // not executed
})
```
there are type errors, but still pass.

### Reproduction

stackBlitz: https://stackblitz.com/~/github.com/rikisamurai/vitest-issue

or
```bash
 npm create vite@latest my-app -- --template react-ts
```
and follow https://github.com/vitest-dev/vitest/blob/main/examples/typecheck/test/type.test-d.ts 
 

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 170.70 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.10.0 - ~/Library/pnpm/pnpm
    bun: 1.1.26 - ~/.bun/bin/bun
  Browsers:
    Chrome: 128.0.6613.121
    Safari: 17.2.1
  npmPackages:
    @vitejs/plugin-react: ^4.3.1 => 4.3.1 
    @vitest/ui: ^2.0.5 => 2.0.5 
    vite: ^5.4.1 => 5.4.2 
    vitest: ^2.0.5 => 2.0.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Your `tsconfig.json` doesn't include any files.

```json
{
  "files": [],
  "references": [
    { "path": "./tsconfig.app.json" },
    { "path": "./tsconfig.node.json" }
  ]
}
```

By default Vitest uses the `tsconfig.json` that it can find: https://vitest.dev/config/#typecheck-tsconfig

So to make your repro work, let's define one of those custom `tsconfig.json` files in Vitest config:

```diff
export default defineConfig({
  plugins: [react()],
  test: {
    typecheck: {
      enabled: true,
+     tsconfig: 'tsconfig.app.json'
    },
  },
})
```

![image](https://github.com/user-attachments/assets/0900568c-a5e5-4a50-835c-4498e15dc084)

**Comment by rikisamurai** [comment]
> Your `tsconfig.json` doesn't `include` any files.
> 
> ```json
> {
>   "files": [],
>   "references": [
>     { "path": "./tsconfig.app.json" },
>     { "path": "./tsconfig.node.json" }
>   ]
> }
> ```
> 
> By default Vitest uses the `tsconfig.json` that it can find: https://vitest.dev/config/#typecheck-tsconfig
> 
> So to make your repro work, let's define one of those custom `tsconfig.json` files in Vitest config:
> 
> ```diff
> export default defineConfig({
>   plugins: [react()],
>   test: {
>     typecheck: {
>       enabled: true,
> +     tsconfig: 'tsconfig.app.json'
>     },
>   },
> })
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/14806298/366750089-0900568c-a5e5-4a50-835c-4498e15dc084.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjQwMDQsIm5iZiI6MTcyNjEyMzcwNCwicGF0aCI6Ii8xNDgwNjI5OC8zNjY3NTAwODktMDkwMDU2OGMtYTVlNS00YTUwLTgzNWMtNDQ5OGUxNWRjMDg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA2NDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMzQ4NzAwODdlMGJhZjhkYTQ1M2ZmZWJjNjQwM2IyOGI5ZjIwMDlhMTM4OGQxMjE0YTQ3ZjUzMjBmYjBlM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rQq5e-QhOk8rpWbjUxJm8u8j7UVQQMQwFlxSdACM-og)

Thank you very much for your help❤️! 
Is it expected that Vitest won't refer to references in this situation? Many beginners, like me, might encounter this issue after creating a project using the Vite template and then adding Vitest.

**Comment by AriPerkkio** [comment]
Oh right, there's `references`. Vitest uses `tsc --noEmit --pretty false -p tsconfig.json` to run the typechecks. Looks like `references` do not emit any type errors when `--build` flag is not used.

**Comment by AriPerkkio** [comment]
Oh right, there's `references`. Vitest uses `tsc --noEmit --pretty false -p tsconfig.json` to run the typechecks. Looks like `references` do not emit any type errors when `--build` flag is not used.

**Comment by mrazauskas** [comment]
See #3752. The `references` related behaviour was discussed there.

**Comment by AriPerkkio** [comment]
Thanks @mrazauskas, let's track this on https://github.com/vitest-dev/vitest/issues/3752.
