### ISSUE TITLE
[v2.1.0] All projects should have unique names error. Regression?

### ISSUE THREAD

**Issue by douglasg14b** [vitest-dev/vitest#6486]
### Describe the bug

After upgrading from `v2.0.5` to `2.1.0` I now get the `All projects should have unique names` error, for every package.

The problem goes away if I downgrade back to `2.0.5`

This seems like a regression maybe?

### Reproduction

Unknown, I am unable to repro outside of our environment. Downgrading versions resolves.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 8.41 GB / 11.68 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.0.6 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
  npmPackages:
    vitest: 2.0.5 => 2.0.5
```
```


### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You probably have miscofigured workspace config file. Check that you don't unintentionally have too broad glob. There were intentional changes to how they are reaolved

**Comment by anchan828** [comment]
Hi, I tried creating a reproduction project. I hope it can be of some help. It seems that this problem occurs simply by having multiple directories.

```ts
export default defineWorkspace(['packages/*', 'apps/*']);
```

https://stackblitz.com/edit/vitest-dev-vitest-xzxfav

**Comment by sheremet-va** [comment]
> Hi, I tried creating a reproduction project. I hope it can be of some help. It seems that this problem occurs simply by having multiple directories.
> 
> ```ts
> export default defineWorkspace(['packages/*', 'apps/*']);
> ```
> 
> [stackblitz.com/edit/vitest-dev-vitest-xzxfav](https://stackblitz.com/edit/vitest-dev-vitest-xzxfav)

Thank you! This is indeed a bug

**Comment by douglasg14b** [comment]
Does this PR resolve the problem, or does it just document the error better? 🤔

**Comment by sheremet-va** [comment]
It resolves the issue that was reproducible and documents how the glob works more clearly (I hope).
