### ISSUE TITLE
v2.1.0 [ERROR] No loader is configured for ".gitignore" files: .gitignore

### ISSUE THREAD

**Issue by ddolcimascolo** [vitest-dev/vitest#6487]
### Describe the bug

All my suites fail with

vitest --retry 2 --logHeapUsage --coverage.enabled true --coverage.provider istanbul --coverage.all false --pool threads --sequence.hooks parallel --shard 1/3
✘ [ERROR] No loader is configured for ".gitignore" files: .gitignore
failed to load config from /builds/stordata/cmdb/frontend/app-react/.gitignore
⎯⎯⎯⎯⎯⎯⎯ Startup Error ⎯⎯⎯⎯⎯⎯⎯⎯
Error: Build failed with 1 error:
error: No loader is configured for ".gitignore" files: .gitignore
    at failureErrorWithLog (/builds/stordata/cmdb/frontend/node_modules/esbuild/lib/main.js:1472:15)
    at /builds/stordata/cmdb/frontend/node_modules/esbuild/lib/main.js:945:25
    at runOnEndCallbacks (/builds/stordata/cmdb/frontend/node_modules/esbuild/lib/main.js:1315:45)
    at buildResponseToResult (/builds/stordata/cmdb/frontend/node_modules/esbuild/lib/main.js:943:7)
    at /builds/stordata/cmdb/frontend/node_modules/esbuild/lib/main.js:970:16
    at responseCallbacks.<computed> (/builds/stordata/cmdb/frontend/node_modules/esbuild/lib/main.js:622:9)
    at handleIncomingPacket (/builds/stordata/cmdb/frontend/node_modules/esbuild/lib/main.js:677:12)
    at Socket.readFromStdout (/builds/stordata/cmdb/frontend/node_modules/esbuild/lib/main.js:[60](https://gitlab.stordata.fr/stordata/cmdb/-/jobs/528586#L60)0:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:376:12) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

This is a monorepo with Vitest projects, using Vitest at the root of the monorepo with the command shown above. This happens when upgrading through a Renovate PR. 

Thanks,
David 

### Reproduction

I will try to set this up tomorrow morning (Paris time) 

### System Info

```shell
Will do tomorrow too
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You probably have miscofigured workspace config file

**Comment by ddolcimascolo** [comment]
Thx for your response. My workspace config file is as simple as

vitest.workspace.json
```
["app-react/*"]
```

And worked fine until then. Should I change something?

**Comment by ddolcimascolo** [comment]
I just double checked the doc and I'm doing exactly as documented, I have several folders, each one is a vite project.  
I indeed also have a `.gitignore` file in there but Vitest was ignoring it until then. If that's something that was supposed to **not work** in previous versions you probably should mention this in the doc.

What's your thoughts on this?

Thx,
David

**Comment by xiangzy1** [comment]
same issue.The message is "No loader is configured for .DS_Store"

**Comment by ddolcimascolo** [comment]
Alright guys, I changed my workspace configuration to 

```javascript
["app-react/*/vite.config.js"]
``` 

And Vitest started picking the tests as usual :+1: 
I still think that this looks like a breaking change, even though it was not supposed to work previously.

Keep up the good work !

Cheers,
David
