### ISSUE TITLE
`advanceTimersToNextFrame` doesn't advance timers immediately

### ISSUE THREAD

**Issue by kaisermann** [vitest-dev/vitest#6493]
### Describe the bug

The solution for #6346, implemented on #6347 doesn't seem to work as described in the original issue. 

Reproduction link is found below, but the code is:

```ts
import { vi, expect, test } from 'vitest';

vi.useFakeTimers();

test('works', () => {
  let frameRendered = false;

  window.requestAnimationFrame(() => {
    frameRendered = true;
  });

  vi.advanceTimersToNextFrame();

  expect(frameRendered).toBe(true); // throws, `frameRendered` is false
});
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-zd3lj1?file=test%2Fbasic.test.ts

### System Info

```shell
System:
  OS: macOS 14.1.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 113.53 MB / 32.00 GB
  Shell: 3.7.1 - /opt/homebrew/bin/fish
Binaries:
  Node: 18.17.1 - ~/.volta/tools/image/node/18.17.1/bin/node
  Yarn: 4.2.2 - ~/.volta/tools/image/yarn/4.2.2/bin/yarn
  npm: 9.6.7 - ~/.volta/tools/image/node/18.17.1/bin/npm
Browsers:
  Chrome: 128.0.6613.138
  Edge: 128.0.2739.79
  Safari: 17.1
NPM Packages:
  vitest: 2.1.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Does this help?

```diff
- vi.useFakeTimers();
+ vi.useFakeTimers({ toFake: ['requestAnimationFrame', 'setTimeout'] });
```

**Comment by kaisermann** [comment]
@AriPerkkio it does! I was sure I got a Typescript error when I tried to do that. This can be closed then as the defaults are documented on the website and in the JSDoc.

Though, we could change the [`Tip` content in the docs](https://vitest.dev/api/vi.html#vi-usefaketimers) to include all the non-default APIs.

**Comment by sheremet-va** [comment]
> This can be closed then as the defaults are documented on the website and in the JSDoc.

Just a note but this will be changed in the next major: https://github.com/vitest-dev/vitest/pull/6288
