### ISSUE TITLE
How to use alias with vitest workspace

### ISSUE THREAD

**Issue by andrew-vdb** [vitest-dev/vitest#6503]
### Clear and concise description of the problem

No documentation.

intellisense is working in my spec file no import error but vitest extension for some reason can not load module with alias

### Suggested solution

When using workspace, put the resolve in the "vitest.workspace.ts" !
```
import { defineWorkspace } from 'vitest/config'
import { resolve } from 'path';
export default defineWorkspace(
    [
        {
            test: {
                include: ['./packageName/**/*.spec.{ts,js}'],
                name: 'packageName',
                alias: {
                    '@': resolve(__dirname, './'),
                }
            }
        }
    ])
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
You could try something like:

```diff
import { defineWorkspace } from 'vitest/config'
import { resolve } from 'path';
export default defineWorkspace(
    [
        {
            test: {
                include: ['./packageName/**/*.spec.{ts,js}'],
                name: 'packageName',
                alias: {
-                    '@': resolve(__dirname, './'),
+                    '@': resolve(__dirname, './packageName'),
                }
            }
        }
    ])
```

But without seeing rest of your project's code it's impossible to help any further. 

Here's also one example that uses `alias` with workspaces: https://stackblitz.com/~/edit/vitest-sonar-reporter-workspaces?file=packages/server/vitest.config.ts.

**Comment by andrew-vdb** [comment]
The proposed solution is already working, sorry that i may not be clear enough. The issue is when i googled and reading the doc, no one mention to put alias in defineWorkspace

**Comment by AriPerkkio** [comment]
Doesn't https://vitest.dev/guide/workspace already cover configuring workspaces? What kind of change would you propose there? It shouldn't be `alias` specific as we simply cannot cover all possible configuration options there.

**Comment by andrew-vdb** [comment]
it can be faq or troubleshoot

when following conditions are true
- using alias
- typescript intellisense is working
- using vitest workspace
- vitest extensions in vs code give error of failed to import

Please add alias in vitest.workspace.ts

worse case they can also find this issue

**Comment by AriPerkkio** [comment]
> Please add alias in `vitest.workspace.ts`

You don't need to put `alias` in `vitest.workspace.ts`. It can be in projects `vitest.config.ts` too, as shown in https://stackblitz.com/~/edit/vitest-sonar-reporter-workspaces?file=packages/server/vitest.config.ts.

The documentation in https://vitest.dev/guide/workspace should already describe how to configure workspaces. The `alias` option doesn't have any special handling when used in workspaces so I don't see reason why it should be specifically mentioned there.
