### ISSUE TITLE
No tests found in stuite after upgrading from 2.0.5 to 2.1.1

### ISSUE THREAD

**Issue by smolak** [vitest-dev/vitest#6507]
### Describe the bug

I have tests in index.test.ts file. When using 2.0.5 - tests run fine. After the update, I have this error message:
```sh
 FAIL  src/index.test.ts [ src/index.test.ts ]
Error: No test found in suite src/index.test.ts
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/2]⎯

 FAIL  src/index.test.ts > MemoryAdapter
Error: No test found in suite MemoryAdapter
```

### Reproduction

In my repository https://github.com/smolak/stash-it, using turborepo, when on `main` branch https://github.com/smolak/stash-it/tree/main - tests for e.g. MemoryAdapter:
```sh
cd packages/memory-adapter
pnpm test
```
pass.

When on branch with vitest update https://github.com/smolak/stash-it/tree/update-vitest same command produces that error.

The only difference between branches is vitest's version (2.0.5 vs 2.1.1).

### System Info

```shell
System:
    OS: macOS 12.7.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 40.59 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.19.0 - ~/.nvm/versions/node/v18.19.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v18.19.0/bin/npm
    pnpm: 9.10.0 - ~/Library/pnpm/pnpm
    Watchman: 2024.08.26.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 84.1.11.104
    Chrome: 128.0.6613.138
    Edge: 128.0.2739.79
    Safari: 17.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
There are two Vitests `vitest@2.0.5` and `vitest@2.1.1` in a lock file  https://github.com/smolak/stash-it/blob/6ff5f019275efc7ebf3204d03844297fce9e1ab9/pnpm-lock.yaml#L2523-L2571 Can you try `pnpm dedupe`?

**Comment by danielbate** [comment]
We had the same problem, I believe it was related to the recent [globs and file paths](https://github.com/vitest-dev/vitest/pull/6316) change. Currently not upgrading our minor version until we've altered our setup to account for the above.

```json
"vitest": "~2.0.5"
```

**Comment by smolak** [comment]
That was it, thank you!
