### ISSUE TITLE
Don't run tests by default in UI mode

### ISSUE THREAD

**Issue by sazzer** [vitest-dev/vitest#6513]
### Clear and concise description of the problem

When starting the UI mode for Vitest, it would be useful if there was an option for the tests to not all run immediately. This would then allow people to start the UI and run specific tests as they're being developed, without the cost of running them all first.

### Suggested solution

A new command line flag to not run the tests on startup.

### Additional context

This is mostly going to be useful for things like E2E tests where they can be slow/expensive to run.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
There is already a flag for that: `--standalone`: https://vitest.dev/guide/cli.html#standalone

**Comment by sazzer** [comment]
Ooh - I looked and didn't see this  Thank you!
