### ISSUE TITLE
Individual snapshot files for snapshot 

### ISSUE THREAD

**Issue by diwic** [vitest-dev/vitest#6517]
### Clear and concise description of the problem

I have a test file that does a lot of a snapshot testing (over 100 snapshots), and the snapshots are quite large. The result is a single .snap file which is hard to diff. I would prefer 100 small files instead.

I can't see to change this with the `resolveSnapshotPath`.

### Suggested solution

Maybe provide the snapshot's unique identifier as an argument to  `resolveSnapshotPath` (and call it once for every snapshot)?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
[`toMatchFileSnapshot`](https://vitest.dev/api/expect.html#tomatchfilesnapshot) is perfect for this. Have you tried it?

**Comment by diwic** [comment]
Ah, totally missed that! Thanks for the help! Sorry for posting an issue about something already implemented.
