### ISSUE TITLE
`import` statements within `vitest.workspace` can't import `.ts` files using the `.js` extension

### ISSUE THREAD

**Issue by sxxov** [vitest-dev/vitest#6519]
### Describe the bug

thank you vitest team for this awesome project! i can't be happier leaving jest in the dust.

when using an `import` statment in `vitest.workspace.ts`, i can't import `.ts` files using the `.js` extension.
changing the extension to use `.ts` or removing the extension completely, makes the import succeed.

perculiarly, this seems to only fail if _the import is inside the `vitest.workspace.ts` file_, any further `.js` imports that exist within the imported modules will import successfully.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-t6tqec?file=vitest.workspace.ts

```ts
// vite.workspace.ts

import { foo } from './foo.js';
//       ^ Error: Failed to load url ./foo.js (resolved id: ./foo.js). Does the file exist?
//             at loadAndTransform (./node_modules/vite/dist/node/chunks/dep-DyBnyoVI.js:51857:17)
//             at async ViteNodeServer._transformRequest (./node_modules/vite-node/dist/server.mjs:524:16)
//             at async ViteNodeServer._fetchModule (./node_modules/vite-node/dist/server.mjs:486:17)
//             at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:277:46)
//             at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:206:14)
//             at async ViteNodeRunner.dependencyRequest (./node_modules/vite-node/dist/client.mjs:259:12)
//             at async C:\__Projects\Code\pawe\vitest.workspace.ts:4:31
//             at async ViteNodeRunner.runModule (./node_modules/vite-node/dist/client.mjs:399:5)
//             at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:381:5)
//             at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:206:14) {
//           code: 'ERR_LOAD_URL'

void foo;
```

```ts
// foo.ts

export foo = 'bar';
```

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 9 4900HS with Radeon Graphics
    Memory: 4.02 GB / 15.42 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.8.1 - ~\AppData\Roaming\npm\npm.CMD
    pnpm: 8.7.4 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @vitejs/plugin-react: ^4.3.1 => 4.3.1
    @vitest/browser: ^2.1.1 => 2.1.1
    vite: ^5.4.6 => 5.4.6
    vitest: ^2.1.1 => 2.1.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxxov** [comment]
> I thought this is same as https://github.com/vitest-dev/vitest/issues/5999, but it seems a bit different. Can you provide a reproduction? Maybe related to your `tsconfig.json`?

this issue is specific to `vitest.workspace.ts`. it's _only_ that file, from what i can see.

& notably it's also `.ts` (`vitest.workspace.ts`) -importing-> `.ts` (`foo.ts`),
whilst #5999 is for `.js` -importing-> `.ts`.

hope this helps!

**Comment by hi-ogawa** [comment]
Thanks for the repro. I thought the issue might be tsconfig `include` not covering `vitest.workspace.ts`, but changing it doesn't seem to matter.

**Comment by hi-ogawa** [comment]
It looks like this inconsistency is happening because Vitest is processing `vitest.workspace.ts` during Vite's `configureServer` plugin hook, which is technically before the complete server initialization, so probably Vite is not able to handle resolution properly.

Here is a repro with just Vite showing the difference of `transformRequest` during and after `configureServer` hook https://github.com/hi-ogawa/reproductions/tree/main/vitest-6519-transformRequest-during-configureServer

**Comment by hi-ogawa** [comment]
Digging this further, I found that Vite's import analysis (which replaces import of .js with .ts) is not happening since they also need `configureServer` hook to be called https://github.com/vitejs/vite/blob/f9691767ad763720065cc7c5c7f369f97b4e7ea8/packages/vite/src/node/plugins/importAnalysis.ts#L226

Interestingly this is not the case in Vite 6 since it can grab `this.environment` during `transform` hook without waiting for `configureServer` https://github.com/vitejs/vite/blob/ba56cf43b5480f8519349f7d7fe60718e9af5f1a/packages/vite/src/node/plugins/importAnalysis.ts#L258 and it actually works on Vite 6 https://stackblitz.com/edit/vitest-dev-vitest-oh5jyw?file=package.json

**Comment by sheremet-va** [comment]
> Digging this further, I found that Vite's import analysis (which replaces import of .js with .ts) is not happening since they also need `configureServer` hook to be called [vitejs/vite@`f969176`/packages/vite/src/node/plugins/importAnalysis.ts#L226](https://github.com/vitejs/vite/blob/f9691767ad763720065cc7c5c7f369f97b4e7ea8/packages/vite/src/node/plugins/importAnalysis.ts#L226)
> 
> Interestingly this is not the case in Vite 6 since it can grab `this.environment` during `transform` hook without waiting for `configureServer` [vitejs/vite@`ba56cf4`/packages/vite/src/node/plugins/importAnalysis.ts#L258](https://github.com/vitejs/vite/blob/ba56cf43b5480f8519349f7d7fe60718e9af5f1a/packages/vite/src/node/plugins/importAnalysis.ts#L258) and the same reproduction actually works with Vite 6 `overrides` [stackblitz.com/edit/vitest-dev-vitest-oh5jyw?file=package.json](https://stackblitz.com/edit/vitest-dev-vitest-oh5jyw?file=package.json)

Can't we just move Vitest's `configureServer` to `order: 'post'`? 🤔
