### ISSUE TITLE
Import of `@testing-library/jest-dom` does not work correctly in workspace configuration.

### ISSUE THREAD

**Issue by onozaty** [vitest-dev/vitest#6533]
### Describe the bug

Using `vitest.workspace.ts`, the two projects are tested and run together.

- vitest.workspace.ts
- package/client/vitest.config.ts
- package/server/vitest.config.ts

In `package/client`, I use `@testing-library/jest-dom` and use `setupFiles` to `import`.

With this configuration, tests run under `package/client` complete without problems.
When I run the test on root, it seems that the `@testing-library/jest-dom` is not imported properly and I get the following error.

```
node ➜ /workspaces/node-sandbox/vitest-monorepo-workspace-jest-dom (main) $ npm run test

> test
> vitest run


 RUN  v2.1.1 /workspaces/node-sandbox/vitest-monorepo-workspace-jest-dom

 ✓ |server| test/app.test.ts (3)
 ❯ |client| test/basic.test.tsx (1)
   × Link changes the state when hovered

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  |client| test/basic.test.tsx > Link changes the state when hovered
Error: Invalid Chai property: toHaveAccessibleName
 ❯ test/basic.test.tsx:14:14
     12|   const link = screen.getByText('Anthony Fu')
     13| 
     14|   expect(link).toHaveAccessibleName('Link is normal')
       |              ^
     15| 
     16|   await userEvent.hover(link)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

 Test Files  1 failed | 1 passed (2)
      Tests  1 failed | 3 passed (4)
   Start at  11:56:39
   Duration  1.05s (transform 56ms, setup 144ms, collect 396ms, tests 124ms, environment 426ms, prepare 149ms)
```

The `package/server` test ran fine from root.

After trying various options, if the dependency of `@testing-library/jest-dom` as follows,

- Add to root
- Remove from `package/client`

It now succeeds when run from root, but fails when run under `package/client`.

### Reproduction

I have placed the reproduced code below.

- https://github.com/onozaty/node-sandbox/tree/main/vitest-monorepo-workspace-jest-dom

### System Info

```shell
System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700T CPU @ 2.40GHz
    Memory: 6.77 GB / 9.65 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.17.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 9.10.0 - /usr/local/share/npm-global/bin/pnpm
  npmPackages:
    vitest: latest => 2.1.1 
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
There are multiple Vitest's installed in the setup. Could you use npm's workspaces or some other proper monorepo setup?

When you run Vitest from the root, it's using the closest it finds from `node_modules`. When `@testing-library/jest-dom` imports Vitest, it imports it from `package/client/node_modules/vitest`.

**Comment by onozaty** [comment]
Thanks for the advice.
So you are saying that I should make sure that vitest is one of them.

As you said, I was able to confirm success in both cases by removing vitest from `package/client`.

I would have preferred to have a complete configuration with only `package/client`, but I will do it this way.

Thank you very much.
