### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'stacks')

### ISSUE THREAD

**Issue by skyrpex** [vitest-dev/vitest#654]
### Describe the bug

The library https://github.com/colinhacks/zod throws a ZodError when the parsing fails. Seems like this error is not well handled by vitest and crashes during a call to `parseStacktrace`.

### Reproduction

https://stackblitz.com/edit/node-xzljid?file=test%2Fbasic.test.ts&view=editor

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (20) x64 Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz
    Memory: 18.66 GB / 31.27 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.3 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Firefox: 96.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Demivan** [comment]
Cause of the problem: Zod error cannot be serialized using `serializeError`.

**Comment by wieringen** [comment]
I believe this error is back. I'm using vitest together with @testing-library.  Some of my tests fail with: TypeError: Cannot read properties of undefined (reading 'stacks'). I narrowed the issue down to vitest not being able to handle jsdom/domexception errors. I have reproduced the issue by simply throwing a domexception error inside a test.

```
import DOMException from "domexception";
import {it, describe} from 'vitest'

describe('The Index Page', () => {
  it('should display content if no params are given', () => {
    throw new DOMException("Something went wrong", "BadThingsError");
  })
})
```

**Comment by ocodista** [comment]
Same happens with crypto-js.
