### ISSUE TITLE
Support coverage of Astro files

### ISSUE THREAD

**Issue by lloydjatkinson** [vitest-dev/vitest#6544]
### Clear and concise description of the problem

Provide coverage support for Astro files. Astro files comprise a "frontmatter" section, which is simply TS, and a template section which is TSX.

https://docs.astro.build/en/guides/testing/

### Suggested solution

Provide seemless support for Astro files

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
Code coverage should support Astro already.

**Comment by hi-ogawa** [comment]
Should we maybe add `.astro` to default extension config? https://vitest.dev/config/#coverage-extension

**Comment by AriPerkkio** [comment]
Yep, let's add that. Tested this quickly with an Astro project. It looks like their source maps are missing some gaps so coverage cannot be reported perfectly:

<img src="https://github.com/user-attachments/assets/27bc2b1e-d304-40f2-b9bb-c540c9f354d4" width="480px" />
