### ISSUE TITLE
Cannot spy on function being called in the function tested when both functions are named exports from the same file 

### ISSUE THREAD

**Issue by jfacoustic** [vitest-dev/vitest#6551]
### Describe the bug

When two functions are exported from the same file as named exports, and you try to test that one of them is called by the other with `vi.spyOn`, the spy doesn't detect that the spied function was invoked.

I got the test to work by moving the spied function to a separate module, but it makes more sense for the two functions to be in the same file. For some context, the two functions parse JSON into business objects that extend a base interface. If the JSON doesn't match any child interfaces, the helper function calls this helper function to return an object with only the base interface members.

I found the following related discussion that this is a bug, but I couldn't find a bug report corresponding to the discussion:
https://github.com/vitest-dev/vitest/discussions/3667

If this is an expected behavior of Vitest, it would be nice to include that in the documentation. (https://vitest.dev/api/vi.html#vi-spyon or https://vitest.dev/guide/common-errors)

### Reproduction

Example file being tested:

```ts
export function helperFunction() {
}

export function testedFunction() {
  helperFunction();
}
```

Example test file

```ts
import { describe, it, expect, vi } from "vitest";
import * as someModule from "~/someModule";

describe("some module tests") {
  describe("testedFunction") {
    it("calls helperFunction once") {
      const helperFunctionSpy = vi.spyOn(someModule, "helperFunction");
      someModule.testedFunction();
      
      expect(helperFunctionSpy).toHaveBeenCalledOnce(); // expected "helperFunction" to be called once, but got 0 times
    }
  }
}
```

I've also tried the following import variations:

```ts
import * as someModule from "~/someModule";
const { testedFunction } = someModule;
```

and 

```ts
import * as someModule from "~/someModule";
import { testedFunction } from "~/someModule";
```

as well as exporting the testedFunction as default.

### System Info

```shell
System:
    OS: macOS 14.6
    CPU: (8) arm64 Apple M1 Pro
    Memory: 220.73 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
    pnpm: 8.6.10 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 128.0.6613.138
    Safari: 17.6
  npmPackages:
    vite: ^5.1.0 => 5.4.6 
    vitest: ^1.6.0 => 1.6.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is expected behaviour: https://vitest.dev/guide/mocking.html#mocking-pitfalls

> it is not possible to mock calls to methods that are called inside other methods of the same file

**Comment by jfacoustic** [comment]
@sheremet-va Thanks a ton!  Would it be possible to add that to the v1 api documentation as well?

**Comment by sheremet-va** [comment]
Sure, PR is welcome
