### ISSUE TITLE
Vitest failed to find the current suite.  This is a bug in Vitest.

### ISSUE THREAD

**Issue by mzhubail** [vitest-dev/vitest#6556]
### Describe the bug

I'm trying to run a test from the vitest repo, and  I'm getting the following error

```
Error: Vitest failed to find the current suite. This is a bug in Vitest. Please, open an issue with reproduction.
 ❯ test/test-utils/index.ts:203:1
    201| const originalFiles = new Map<string, string>()
    202| const createdFiles = new Set<string>()
    203| afterEach(() => {
       | ^
    204|   originalFiles.forEach((content, file) => {
    205|     fs.writeFileSync(file, content, 'utf-8')
 ❯ test/cli/test/list.test.ts:3:31
```

### Reproduction

At the time of creating this, the main branch is at 87232420ebe0d5b6052529c0043ae4981590caf1.

```sh
git clone https://github.com/vitest-dev/vitest/
pnpm install
pnpm run build
pnpm exec vitest list cli/test/list.test.ts
```

### System Info

```shell
System:
    OS: Linux 6.9 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 8.18 GB / 15.45 GB
    Container: Yes
    Shell: 5.2.26 - /bin/bash
  Binaries:
    Node: 22.4.1 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.8.2 - /usr/bin/npm
    pnpm: 9.6.0 - /usr/bin/pnpm
  Browsers:
    Brave Browser: 127.1.68.128
    Chromium: 127.0.6533.72
  npmPackages:
    @vitest/browser: workspace:* => 2.1.1
    @vitest/coverage-istanbul: workspace:* => 2.1.1
    @vitest/coverage-v8: workspace:* => 2.1.1
    @vitest/ui: workspace:* => 2.1.1
    vite: ^5.4.0 => 5.4.0
    vitest: workspace:* => 2.1.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dvnrsn** [comment]
Also experiencing this with fresh vitest installation in fresh Hydrogen app 
![CleanShot 2024-09-24 at 16 55 04@2x](https://github.com/user-attachments/assets/6af66474-bb84-4cdb-8166-e3c8863883a4)

**Comment by hi-ogawa** [comment]
@mzhubail I'm assuming you're interested in contributing Vitest and trying to run tests locally. The command you used `pnpm exec vitest list cli/test/list.test.ts` is not how we run tests. 

If you want to run tests under `test/cli`, then you can run `pnpm -F @vitest/test-cli test` to target only specific workspace project. (or you can simply `cd test/cli` and then `pnpm test`).

@dvnrsn OP's issue was specifically about Vitest's development itself, so the issue you're seeing should be investigated separately. Please create a new issue with a reproduction.
