### ISSUE TITLE
Exclude commitlint config files in coverage default option

### ISSUE THREAD

**Issue by rwv** [vitest-dev/vitest#6568]
### Clear and concise description of the problem

exclude commitlint config files in coverage default option

### Suggested solution

add commitlint files pattern in default option

### Additional context

I am working on a PR

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by rwv** [comment]
commitlint config filename pattern: https://commitlint.js.org/reference/configuration.html#config-via-file

**Comment by AriPerkkio** [comment]
This is similar request as https://github.com/vitest-dev/vitest/issues/6508.

Instead of defining what file to exclude, you should rather instruct Vitest which files to include in the coverage. https://vitest.dev/guide/coverage.html#coverage-setup
