### ISSUE TITLE
TypeError: Cannot set property srcObject of [object Object] which has only a getter

### ISSUE THREAD

**Issue by zeid0ne** [vitest-dev/vitest#6573]
### Describe the bug

I have a component with a video element : 
![image](https://github.com/user-attachments/assets/f42df65f-11af-4df6-a164-d8efae8dd077)

I am linking a stream to it with the following code :
![image](https://github.com/user-attachments/assets/533e75e1-18d5-4433-8f51-d51224ee3ead)

That work well on my app.

I wrote a test with vitest v1.6.0 that call the lines of the image above. That worked well.

But after upgrading vitest to v2.1.1, the operation srcObject = stream throw an error inside vitest :

![image](https://github.com/user-attachments/assets/7a8cf057-fe99-4c9a-9d8b-9835c8079a12)

### Reproduction

Use the code above

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 7745HX with Radeon Graphics
    Memory: 15.30 GB / 31.69 GB
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.4.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (125.0.2535.92)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @vitejs/plugin-vue: ^3.2.0 => 3.2.0
    @vitest/coverage-istanbul: ^2.1.1 => 2.1.1
    @vitest/ui: ^2.1.1 => 2.1.1
    vitest: ^2.1.1 => 2.1.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zeid0ne** [comment]
Here is the minimal repo : https://stackblitz.com/edit/vitest-dev-vitest-ve6adl?file=package.json

The error occurs with happy-dom and not with jsdom

**Comment by hi-ogawa** [comment]
It looks like `HTMLMediaElement.srcObject` should be writable https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/srcObject, so the issue is on happy-dom side. Please report an issue on https://github.com/capricorn86/happy-dom
