### ISSUE TITLE
`--ui --standalone` doesn't show a list of tests until one is run

### ISSUE THREAD

**Issue by KaelWD** [vitest-dev/vitest#6574]
### Describe the bug

- Run `vitest watch --ui --standalone`
- **The UI opens with an empty list**
- Cause a test to run either by editing it or adding a filter in the terminal
- All the other test files will appear in the UI

### Reproduction

I are absolutely sure that the issue is obvious.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 14.88 GB / 31.26 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 22.6.0 - ~/.nvm/versions/node/v22.6.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v22.6.0/bin/npm
  Browsers:
    Chrome: 128.0.6613.119
    Firefox: 130.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
It looks like it was (partially?) working on v1 https://stackblitz.com/edit/vitest-dev-vitest-tnyyrm?file=package.json

<details><summary>screenshot</summary>

![image](https://github.com/user-attachments/assets/cbf48377-1811-4b43-8547-2193e4d65d2c)

</details>

It might be realted to UI rework done by https://github.com/vitest-dev/vitest/pull/5907
