### ISSUE TITLE
Error: getaddrinfo ENOTFOUND localhost

### ISSUE THREAD

**Issue by SanGuiChen** [vitest-dev/vitest#6576]
### Describe the bug

When I executed npx vitest, I encountered problems with ‘Error: getaddrinfo ENOTFOUND localhost’. 

My version information is as follows:
![image](https://github.com/user-attachments/assets/ef1e28f0-a1e2-400d-893c-44c51d2a90f2)

### Reproduction

empty

### System Info

```shell
Need to install the following packages:
  envinfo@7.14.0
Ok to proceed? (y) y

  System:
    OS: macOS 14.2
    CPU: (12) arm64 Apple M2 Pro
    Memory: 73.84 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/xxx/.bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.4.0/bin/yarn
    npm: 9.7.2 - ~/.nvm/versions/node/v20.4.0/bin/npm
    pnpm: 8.15.1 - ~/.nvm/versions/node/v20.4.0/bin/pnpm
  Browsers:
    Chrome: 129.0.6668.70
    Safari: 17.2
    Safari Technology Preview: 17.4
  npmPackages:
    @vitest/coverage-istanbul: ^1.2.2 => 1.6.0 
    vitest: ^1.3.1 => 1.6.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by abrdgrt** [comment]
it's an issue with his localhost not being recognised most likely on a mac, add localhost to your host file (/etc/hosts)
