### ISSUE TITLE
Add `testNamePattern` to help's CLI input

### ISSUE THREAD

**Issue by o-alexandrov** [vitest-dev/vitest#658]
### Clear and concise description of the problem

Similarly to Jest, it would be great if a user could **apply or change** `testNamePattern` while running:
- `vitest watch`

### Suggested solution

Same flow as in Jest:

1. while running `vitest watch`, a user clicks `h` to show help
2. user clicks `t` to apply or change the `testNamePattern`
3. user types pattern and clicks `Enter`
4. pattern for test names is applied

### Additional context

Same applies to file name filtering that as of now doesn't exist in `vitest`, but does in `jest`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by stygian-desolator** [comment]
https://vitest.dev/config/#include

**Comment by o-alexandrov** [comment]
@stygian-desolator how the link you pointed to applies to:
- ability to change `include` **during** `vitest watch`

that this issue describes?
