### ISSUE TITLE
Expect `toMatchObject` diff to match object type

### ISSUE THREAD

**Issue by msteen** [vitest-dev/vitest#6580]
### Describe the bug

When I use `expect(testObject).toMatchObject(expectedObject)` I expect the diff to report the correct type for `Received` as it does for `Expected`.

For example, say I have the two classes `Foo` and `Bar`:
```ts
class Foo {
  constructor(public value: number) {}
}
class Bar {
  constructor(public value: number) {}
}
```

Then I expect the following test:
```ts
test("foo", () => {
  expect(new Bar(2)).toMatchObject(new Foo(1))
})
```

To report the types as it does in the `AssertionError`
```
 FAIL  src/test.ts > foo
AssertionError: expected Bar{ value: 2 } to match object Foo{ value: 1 }

- Expected
+ Received

- Foo {
-   "value": 1,
+ Object {
+   "value": 2,
  }

 ❯ src/test.ts:44:22
     42| }
     43| test("foo", () => {
     44|   expect(new Bar(2)).toMatchObject(new Foo(1))
       |                      ^
     45| })
     46| 
```

Yet it shows expecting a `Foo` and receiving an `Object`, while I would expect `Object` to be `Bar` here.

Now there have been cases (when this problem occurs in a nested object) where I had to add additional logging on failure to determine that `Object` is in fact `Bar` to pinpoint the cause of the error, which would have been unnecessary if the diff reported the correct type.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-qmrkzs?file=test%2Fbasic.test.ts

### System Info

```shell
vitest/1.6.0 linux-x64 node-v22.7.0

  System:
    OS: Linux 6.8 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 2.94 GB / 31.06 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 22.7.0 - ~/.nvm/versions/node/v22.7.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v22.7.0/bin/npm
    pnpm: 9.9.0 - ~/.nvm/versions/node/v22.7.0/bin/pnpm
    bun: 1.1.26 - ~/.nvm/versions/node/v22.7.0/bin/bun
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
`toMatchObject(new Foo(1))`  should probably work same as `toMatchObject({ value: 1 })`, but it looks like this one shows a following diff: https://stackblitz.com/edit/vitest-dev-vitest-dfkaue?file=test%2Fbasic.test.ts

```
 FAIL  test/basic.test.ts > x
AssertionError: expected Bar{ value: 2 } to match object { value: 1 }

- Expected
+ Received

  Object {
-   "value": 1,
+   "value": 2,
  }

 ❯ eval test/basic.test.ts:9:22
      7| 
      8| test('x', () => {
      9|   expect(new Bar(2)).toMatchObject({ value: 1 });
       |                      ^
     10| });
     11| 
```

So, this could be the expected behavior than this (though not sure):

```
- Expected
+ Received

- Foo {
-   "value": 1,
+ Bar {
+   "value": 2,
  }
```

**Comment by hi-ogawa** [comment]
Looking it again, it's probably desirable to preserve prototypes inside diff, which is currently dropped "Received" side. This is due to a recent change to slim down the diff for `toMatchObject` https://github.com/vitest-dev/vitest/pull/5364

I checked Jest and they also got the same bug as this code is mostly based on them. Here is a repro in Jest https://stackblitz.com/edit/github-caqski?file=basic.test.js
