### ISSUE TITLE
Tests are not properly isolated in browser mode

### ISSUE THREAD

**Issue by josselinonduty** [vitest-dev/vitest#6588]
### Describe the bug

Browser mode with `isolate: true` doesn't isolate globalThis. Hence, global event listeners and events are shared leading to errors in test environment only.

### Reproduction

1. Clone https://github.com/wrakerjs/vitest-contrib
2. Run `npm install -D`
3. Make sure Playwright was correctly set up (`npm run postinstall`)
4. `npm run test`

Please see https://github.com/wrakerjs/vitest-contrib/blob/main/test/basic.test.ts

### System Info

```shell
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (16) x64 <redacted>
    Memory: <redacted>
    Container: Yes
    Shell: <redacted>
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    npm: 10.8.3 - ~/.nvm/versions/node/v20.13.1/bin/npm
  npmPackages:
    @vitest/browser: ^2.1.1 => 2.1.1 
    @vitest/ui: latest => 2.1.1 
    vite: latest => 5.4.8 
    vitest: latest => 2.1.1 
  playwright:
    version: 1.47.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is by design. Tests are isolated on the file level, not on the test function level. This is how it also works for Node.js tests.
