### ISSUE TITLE
--retry=2 gives wrong error: toMatchInlineSnapshot cannot be called multiple times at the same location

### ISSUE THREAD

**Issue by lydell** [vitest-dev/vitest#6589]
### Describe the bug

When you use the `--retry=n` flag (where `n > 0`), inline snapshots that succeeded on the first try fail on the retries with `toMatchInlineSnapshot cannot be called multiple times at the same location`. This means that if you precede a flaky assertion with an inline snapshot, the `--retry` flag does not work.

It sounds like the some state that `toMatchInlineSnapshot` carries needs to be reset between retries.

<sub>I later learned that `--retry=1` is enough – it’s the number of _retries_ not the number of total tries.</sub>

### Reproduction

https://github.com/lydell/vitest-inline-snapshot-retry

```js
import {expect, test} from "vitest";

test("demo", () => {
  // First an up-to-date snapshot.
  // Unfortunately, this fails on the second retry.
  expect("a").toMatchInlineSnapshot(`"a"`);

  // Then an assertion of a flaky function.
  expect(flakyFunction()).toBe(2);
});

// Imagine this being a flaky function that only sometimes gives the correct value.
// In this demo, we make it always succeed the second time. Which means that if you
// run with `--retry=2` the test should pass. However, since the snapshot fails on
// the second attempt, the test never passes. Comment out the snapshot test above
// to see it succeed.
let flakyCounter = 1;
function flakyFunction() {
  return flakyCounter++;
}
```

### System Info

```shell
System:
    OS: macOS 14.7
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.02 GB / 32.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 22.8.0 - ~/.local/share/nvm/v22.8.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - ~/.local/share/nvm/v22.8.0/bin/npm
    pnpm: 9.9.0 - /opt/homebrew/bin/pnpm
    bun: 1.1.27 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 129.0.6668.71
    Safari: 18.0
  npmPackages:
    vitest: 2.1.1 => 2.1.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
`toMatshSnapshot` is known to have an issue with `retry` https://github.com/vitest-dev/vitest/issues/5312, but the recent validation made it not work with `toMatshInlineSnapshot`.

Both could be fixed by the same approach mentioned in https://github.com/vitest-dev/vitest/issues/5312#issuecomment-2176222629
