### ISSUE TITLE
Concurrency amongst child `describe`s

### ISSUE THREAD

**Issue by privatenumber** [vitest-dev/vitest#661]
### Clear and concise description of the problem

When using `describe.concurrent`, I expect all children to run concurrently. However, it only seems to apply to `test` and not`describe`.

In this code snippet, `describe('A ...')` and `describe('B ...')` run sequentially:
```ts
import { describe, test } from 'vitest';

const sleep = (ms: number): Promise<void> => new Promise(resolve => setTimeout(resolve, ms));

describe.concurrent('Expect all immediate children to be concurrent', () => {

	describe.concurrent('A - should run concurrently with B', () => {
		test('sleep', async () => {
			await sleep(1000);
		});
	});

	describe.concurrent('B - should run concurrently with A', () => {
		test('sleep', async () => {
			await sleep(1000);
		});
	});
});
```

### Suggested solution

For all immediate children of `.concurrent` to run concurrently.

### Alternative

I'm curious why Vitest went with adding a `.concurrent` API instead of leveraging native `async` syntax. Perhaps to shorten the migration path from Jest, or to gather a list of tests to execute for display prior to executing them?

As an alternative, I think it could be simpler to default to async tests and making them run sequentially is done via `await`. Or "async" APIs or mode where the default is async:

```ts
import { describe, test } from 'vitest/async'
```

I would also like to make a feature request for `describe.each(...arr).concurrent()`, but these can be solved immediately with an async default.

### Additional context

To organize my tests, I group a lot of tests in `describe` blocks. However, this slows down the tests as they are no longer running concurrently.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DerYeger** [comment]
Regarding your alternative suggestion, I don't think that `async` and `concurrent` can be used interchangeably. There are plenty of use cases that may require asynchronous tests that couldn't be run concurrently.

I do like the alternative import, but I'd go with `vitest/concurrent` for the reason mentioned above.

**Comment by privatenumber** [comment]
> Regarding your alternative suggestion, I don't think that `async` and `concurrent` can be used interchangeably. There are plenty of use cases that may require asynchronous tests that couldn't be run concurrently.

Not sure if I follow. Can you provide an example?

**Comment by DerYeger** [comment]
> > Regarding your alternative suggestion, I don't think that `async` and `concurrent` can be used interchangeably. There are plenty of use cases that may require asynchronous tests that couldn't be run concurrently.
> 
> Not sure if I follow. Can you provide an example?

Basically anything that involves a global or shared state is often unsuited for concurrent test execution.
If tests require specific preconditions that are not mutated by outside code during their execution, they cannot be run concurrently and it's certainly feasible in the modern JS/TS environment to include `async` functions in such tests.

**Comment by privatenumber** [comment]
Thanks for explaining. I think I still stand by my `async` alternative though. Unless you were specifically talking about naming technicalities, then in that case I'm indifferent (eg. `vitest/concurrent` works for me).

---

> Basically anything that involves a global or shared state is often unsuited for concurrent test execution.

Sounds like you're talking about sequential vs parallel/concurrent/async problems.

> If tests require specific preconditions that are not mutated by outside code during their execution, they cannot be run concurrently

Or asynchronously.

> it's certainly feasible in the modern JS/TS environment to include async functions in such tests.

Sure, those tests can _contain_ `async` code in them because the preconditions are already "locked". But I'm not sure if I see the relevance of this point.

Assuming you're talking about whether entire test blocks can be run concurrently vs asynchronously: Yes, there are technical differences between the two, but in this case, I would argue they're interchangeable because these are async APIs interfacing over concurrent processes.

If you have one, I would love to see a concrete example that demonstrates the difference where test blocks that are run concurrently cannot also be run asynchronously.

**Comment by DerYeger** [comment]
I'm arguing against the opposite direction. There exists `async` code that cannot be run/tested concurrently. Hence `async` tests shouldn't implicitly run concurrently.

**Comment by privatenumber** [comment]
Do you have a concrete example where two async test blocks cannot be run concurrently?

The problem you outline in your example above applies both concurrent and async test blocks, and is more of a _sequential vs parallel/concurrent/async_ limitation than a _async vs concurrent_ one. 

And follow up question:
Correct me if I'm wrong... but in Vitest, I understand `.concurrent()` spawns threads to run the tests concurrently; is there, or can there be, an async API that runs the tests asynchronously?

I have many tests but they're all quite light so it would make more sense in my use-case if they run async instead of spawning multiple threads.

If there is no such API yet, I can either reword this feature request or open a new one.

**Comment by DerYeger** [comment]
> Do you have a concrete example where two async test blocks cannot be run concurrently?

Sure, https://stackblitz.com/edit/vitest-dev-vitest-vh8rky?file=test%2Fbasic.test.ts. Add `.concurrent` to the `describe` and it will fail.

> And follow up question: Correct me if I'm wrong... but in Vitest, I understand `.concurrent()` spawns threads to run the tests concurrently; is there, or can there be, an async API that runs the tests asynchronously?

Not as far as I can tell [from the implementation](https://github.com/vitest-dev/vitest/blob/95049058ae3d3d12f79de596e33fddc8f4bfa23e/packages/vitest/src/runtime/run.ts#L141).

**Comment by DerYeger** [comment]
I see what you mean now, but I don't think it's a plausible approach (please correct me if I'm wrong).
In your example, you are awaiting the declaration of tests, not their execution.
Even if it's possible to apply some JS magic to detect at runtime whether a function is awaited, I still don't see the added value over just declaring a test or suite as `concurrent` explicitly.

Maybe this suggestion should be raised as a separate feature request issue with your example in the main description itself, so it doesn't get lost in a bug report.

**Comment by privatenumber** [comment]
FWIW, it's straightforward to implement without any magic but I thought about it some more and I think this might be a very different path from the direction Vitest is headed in. I will withdraw my feature request and consider a different approach.

Thanks for discussing this with me @DerYeger

**Comment by DerYeger** [comment]
> FWIW, it's straightforward to implement without any magic but I thought about it some more and I think this might be a very different path from the direction Vitest is headed in: I'm trying to use Vitest for very simple unbundled Node.js testing but Vitest is designed to test bundled apps.
> 
> I will withdraw my feature request and consider a different approach.
> 
> Thanks for discussing this with me @DerYeger

I see. Introducing a bundler just for running tests may be too much.

Thank you too!
