### ISSUE TITLE
toThrowError() treats empty string param as though it is undefined

### ISSUE THREAD

**Issue by U-4-E-A** [vitest-dev/vitest#6618]
### Describe the bug

`toThrowError()` treats an empty string (`toThrowError('')`) as it would if the value was undefined when it should reject an empty string as it is not equal to the error.

### Reproduction

```
import { expect, test } from 'vitest'

function getFruitStock(type: string): void {
  if (type === 'pineapples') {
    throw new Error('Pineapples are not in stock')
  }
}

test('throws on pineapples', () => {
  // undefined error passes
  expect(() => getFruitStock('pineapples')).toThrowError()
  // error of empty string should fail as it does not represent the error but passes
  expect(() => getFruitStock('pineapples')).toThrowError('')
})

```

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13700H
    Memory: 4.36 GB / 15.73 GB
  Binaries:
    Node: 22.4.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    vitest: ^2.0.5 => 2.1.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
This might be a chai issue. It's very similar to https://github.com/vitest-dev/vitest/issues/5228 but this time it's empty string on "expected" side.

**Comment by hi-ogawa** [comment]
Just came back digging this, I'm not sure if this was actually a bug. `expect(error).toThrowError(string)` is meant to check substring `error.message.includes(string)`, so the empty string being no-op seems expected (at least as per https://main.vitest.dev/api/expect.html#tothrowerror).
