### ISSUE TITLE
Non declared variable causes vitest to freak out

### ISSUE THREAD

**Issue by yooneskh** [vitest-dev/vitest#663]
### Describe the bug

Using non declared variable causes vitest to panick without any useful error, although it should not error.

### Reproduction

this panicks
```js
import { test } from 'vitest';

test('basic test', () => {
  process = 1;
});
```

this works
```js
import { test } from 'vitest';

test('basic test', () => {
  const process = 1;
});
```

### System Info

```shell
System:
    OS: Linux 5.15 Fedora Linux 35 (Workstation Edition)
    CPU: (4) x64 Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz
    Memory: 3.98 GB / 11.57 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 17.0.1 - ~/.nvm/versions/node/v17.0.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v17.0.1/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v17.0.1/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
  npmPackages:
    vite: 2.8.0-beta.3 => 2.8.0-beta.3 
    vitest: ^0.2.5 => 0.2.5
```

### Used Package Manager

yarn

### Validations

- [x] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Demivan** [comment]
Problem is not with any undeclared variable. Reassigning `process` breaks when workers try to read `rpc` from it:
`TypeError: Cannot read properties of undefined (reading 'rpc')`

**Comment by sheremet-va** [comment]
Not sure if it's a bug. Maybe more helpful message would be appreciated, but don't reassign globals, that's a no-no 😃

**Comment by Demivan** [comment]
We should be able to save Vitest info into some separate global variable instead of `process`. So people can mess with it if they want :)

**Comment by yooneskh** [comment]
> Problem is not with any undeclared variable. Reassigning `process` breaks when workers try to read `rpc` from it: `TypeError: Cannot read properties of undefined (reading 'rpc')`

i was really unlucky then :)

**Comment by yooneskh** [comment]
> Not sure if it's a bug. Maybe more helpful message would be appreciated, but don't reassign globals, that's a no-no 😃

i agree. just a better error message would have been nice.
