### ISSUE TITLE
vitest with prisma failing randomly in CI 

### ISSUE THREAD

**Issue by formatlos** [vitest-dev/vitest#6635]
### Describe the bug

We are currently migrating our test-suite from jest to vitest. Everything runs smoothly locally, but on CI (Gitlab ci with k8s runner in our k8s cluster) the tests fail randomly every second or third run. 

We have almost 1000 test across 115 test files, when it fails it's 1 or 2 random testfiles having one of the following errors:

```
Error: Cannot find module '.prisma/client/default'
Require stack:
- /xxx/node_modules/@prisma/client/default.js
```
or 
```
⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯
Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.
⎯⎯⎯⎯ Unhandled Rejection ⎯⎯⎯⎯⎯
PrismaClientInitializationError: Prisma Client could not locate the Query Engine for runtime "debian-openssl-3.0.x".
This is likely caused by tooling that has not copied "libquery_engine-debian-openssl-3.0.x.so.node" to the deployment folder.
Ensure that you ran `prisma generate` and that "libquery_engine-debian-openssl-3.0.x.so.node" has been copied to "node_modules/.prisma/client".
We would appreciate if you could take the time to share some information with us.
Please help us by answering a few questions: https://pris.ly/engine-not-found-tooling-investigation
The following locations have been searched:
  /builds/xxx/node_modules/.prisma/client
  /builds/xxx/node_modules/@prisma/client
  /tmp/prisma-engines
  /builds/xxx/prisma
```

The files it can't find are in the node_modules folder. 

We are already running with `--pool=forks` and tried different settings in regards to poolOptions, but still the same behaviour. 
We did also compare the modules dump of a failed and successful run (which was exactly the same).

Any ideas how to solve that? 

### Reproduction

Run vitest in gitlab ci with a test suite using prisma

### System Info

```shell
System:
    OS: Linux 5.10 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
    Memory: 28.55 GB / 30.99 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 22.9.0 - /usr/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.8.2 - /usr/bin/npm
  npmPackages:
    @vitest/coverage-istanbul: ^2.1.1 => 2.1.1 
    vitest: ^2.1.1 => 2.1.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Can't really help without a reproduction. Maybe you are removing the prisma folder or regenerating it during a test? So when another test runs in parallel, the folder is no longer there. Try running tests with `--single-worker` (much slower) and `--no-isolate` (tests might break if they rely on a shared state). You can also try running tests with the `--sequence.shuffle` to randomise the order.

**Comment by formatlos** [comment]
thanks @sheremet-va for your quick response. 

I did find the issue: we do some parallel, transactional testing therefore we need to run migrations within each worker. We call `prisma migrate reset` but this does re-generate the client implicitly if not skipped with `--skip-generate`.
