### ISSUE TITLE
Missing toHaveAttribute from expect() return type

### ISSUE THREAD

**Issue by JesusTheHun** [vitest-dev/vitest#664]
### Describe the bug

The `expect` function return type does not include the `toHaveAttribute` function. The code runs fine though.

### Reproduction

```ts
import { test, expect } from 'vitest';

expect(element).toHaveAttribute("id"); // TS2339: Property 'toHaveAttribute' does not exist on type 'Assertion '.
```

### System Info

```shell
System:
    OS: macOS 12.2
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 394.17 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 3.1.1 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
    Watchman: 2022.01.17.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 97.0.4692.99
    Edge: 97.0.1072.76
    Firefox: 94.0.1
    Safari: 15.3
  npmPackages:
    @vitejs/plugin-react-refresh: ^1.3.6 => 1.3.6 
    vite: ^2.7.13 => 2.7.13 
    vitest: ^0.2.5 => 0.2.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
testing-library/jest-dom doesn't enhance vitest's expect type. This is out of scope of Vitest.

**Comment by JesusTheHun** [comment]
Ok I'm super confused here, I import `expect` from `vitest`, and my test is green.

**Comment by sheremet-va** [comment]
If you use `@testing-library/jest-dom`, it globally adds a matcher.

**Comment by JesusTheHun** [comment]
Then the expect way to do it is to import `expect` from both RTL and vitest?

**Comment by sheremet-va** [comment]
The expected way would be to create an issue in `@testing-library/jest-dom` to add their matchers to `Vi` namespace, so they will be visible to TypeScript.

There is no immediate solution except manually adding matchers to `Vi.Assertion`.

**Comment by vjee** [comment]
For anyone that has the same issue, the following seems to work well for me:
```ts
// tests.d.ts

import 'vitest';
import { TestingLibraryMatchers } from '@testing-library/jest-dom/matchers';

declare global {
  namespace Vi {
    interface Assertion<T = any> extends TestingLibraryMatchers<T, void> {}
  }
}
```
