### ISSUE TITLE
"You must provide a Promise to expect()" inconsistent between `resolves` and `rejects`

### ISSUE THREAD

**Issue by 0-CAT** [vitest-dev/vitest#6643]
### Describe the bug

If you call `await expect(async () => { ... }).rejects.toThrow()`, this will work as expected. However, change this to `await expect(async () => { ... }).resolves.not.toThrow()` and the test fails with the following error:

> **TypeError**: You must provide a Promise to expect() when using .resolves, not 'function'.

This appears to just be an inconsistency between the two, based on the source code:

![CleanShot 2024-10-04 at 20 37 27](https://github.com/user-attachments/assets/345eacc3-60a2-4e67-a447-fb606a58ca02)

![CleanShot 2024-10-04 at 20 38 09](https://github.com/user-attachments/assets/7bb7abc1-1333-49ba-89f2-9561bd205a82)

Seems like the Jest compatibility was not ported to `.resolves` but only to `.rejects`—looks like the bug is with that.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-9omsvx?file=test%2Fbasic.test.ts

### System Info

```shell
System:
    OS: macOS 15.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 98.27 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.0 - ~/.nvm/versions/node/v20.15.0/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.0/bin/npm
    pnpm: 9.6.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Safari: 18.1
  npmPackages:
    @vitest/coverage-v8: ^2.1.1 => 2.1.1
    @vitest/ui: ^2.1.1 => 2.1.1
    vitest: ^2.1.1 => 2.1.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> Seems like the Jest compatibility was not ported to `.resolves` but only to `.rejects`—looks like the bug is with that

Did you run the code in Jest to check this claim?

Vitest `.resolves` and `.rejects` API follows the Jest behavior. It doesn't accept a function in `.resolves`:

```
    Expected value   undefined
    Received:
      undefined
    
    Message:
      expect(received).resolves.not.toThrow()
    
    Matcher error: received value must be a promise
    
    Received has type:  function
    Received has value: [Function anonymous]

    Difference:

    Compared values have no visual difference
```
