### ISSUE TITLE
Add Cypress as a provider for browser mode 

### ISSUE THREAD

**Issue by OriR** [vitest-dev/vitest#6645]
### Clear and concise description of the problem

Currently, we have a codebase that's utilizing Cypress for e2e.
We also bundle our application with vite, as well as having many unit tests written with jest and we're considering migrating them to vitest and a bunch storybook stories.

Instead of having many tools, one for each purpose, we'd like to have them integrate with each other (just like the new storybook integration). Ideally we'd have Cypress, Storybook, vitest and vite all talk to each other.

### Suggested solution

Add a new browser mode provider for Cypress 

### Alternative

Allow for the creation of custom provider and let the community develop the Cypress integration, as well as extracting playwright and webdriverio to their own custom provider.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Cypress is a test runner, not a browser provider. They do not expose any APIs to just open a browser, like `playwright` and `webdriverio` do, so this request is not possible to achieve. 

> Allow for the creation of custom provider

It is already possible to create custom providers - the `browser.provider` field also accepts a file path, but beware that all Vitest API (and especially browser API) are experimental and can change at any time.
