### ISSUE TITLE
Can't `alias` module in browser mode when dependency is aliased

### ISSUE THREAD

**Issue by JCQuintas** [vitest-dev/vitest#6646]
### Describe the bug

Same as https://github.com/vitest-dev/vitest/issues/6483 which resolved this issue for `mock`

But for `vitest.config.ts` `resolve.alias`

We currently have the following in our package

```
    "date-fns": "2.30.0",
    "date-fns-v3": "npm:date-fns@3.6.0",
```

This is due to the different signatures between these two versions. In the final code, this is a peer dependency, so inside our code we only always use import from 'date-fns'.

But when testing, we want to test the actual library, which requires some aliasing.

```ts
// config.ts
import { defineConfig } from 'vite'

export default defineConfig({
  resolve: {
    alias: [
      {
        find: 'date-fns',
        replacement: 'date-fns-v3',
        customResolver(source, importer, options) {
          if (importer?.includes('DateFnsV3')) return source
          return null
        },
      }
    ]
  },
  test: {
    setupFiles: ['./vitest.setup.ts'],
  },
})

/// TypeError: Failed to fetch dynamically imported module: http://localhost:5173/Users/dev/vitest-browser-alias-mock/components/DateFnsV3.test.tsx?import&browserv=1726153861578
```

### Reproduction

https://github.com/JCQuintas/vitest-browser-alias-mock

## Important Files

Ensure you uncomment the alias in `vitest.config.ts`

## Running

```
pnpm test
```

### System Info

```shell
  System:
    OS: macOS 15.0.1
    CPU: (11) arm64 Apple M3 Pro
    Memory: 96.31 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 9.11.0 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
  Browsers:
    Brave Browser: 127.1.68.137
    Chrome: 129.0.6668.90
    Safari: 18.0.1
  npmPackages:
    @vitejs/plugin-react: ^4.3.1 => 4.3.2 
    @vitest/browser: latest => 2.1.2 
    @vitest/ui: latest => 2.1.2 
    vite: latest => 5.4.8 
    vitest: latest => 2.1.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I don't understand what you are trying to achieve, to be honest. Do you want to always resolve to `date-fn` locally? Even in `DateFnsV3`?

**Comment by JCQuintas** [comment]
I want that inside files that contain `DateFnsV3` in its name, the `date-fns` library should be replaced by `date-fns-v3`. This aliasing works correctly in JSDOM.

I see this as the similar issue from my [original topic](https://github.com/vitest-dev/vitest/issues/6483). There one of the issues was fixed, which is was using `vi.mock`

**Comment by sheremet-va** [comment]
> This aliasing works correctly in JSDOM.

This is debatable, Vitest in Node.js doesn't actually follow the same resolving mechanism and tries to resolve the same thing twice if it doesn't work. The error happening in the browser is the correct behaviour. As I said, try using this config with a normal Vite project and you will see.

**Comment by sheremet-va** [comment]
> I want files that contain `DateFnsV3` in its name to have `date-fns` library replaced by `date-fns-v3`.

This also doesn't explain what I asked. Do you want `date-fns/parse` to be resolved as `date-fns-v3/parse` or `date-fns-v3`?

**Comment by JCQuintas** [comment]
> This also doesn't explain what I asked. Do you want `date-fns/parse` to be resolved as `date-fns-v3/parse` or `date-fns-v3`?

I want `date-fns/parse` to become `date-fns-v3/parse`, but not only that. `date-fns` is modular, it has `date-fns/format`, `date-fns/addHours`, etc. All those instances should be changed as well.

**Comment by JCQuintas** [comment]
> This is debatable, Vitest in Node.js doesn't actually follow the same resolving mechanism and tries to resolve the same thing twice if it doesn't work. The error happening in the browser is the correct behaviour. As I said, try using this config with a normal Vite project and you will see the same error.

It is not debatable that it works. 🙃 

And I understand that running it in the browser gives me errors.

If I rename `vitest.config` to `vite.config` the errors become:

```
5:48:02 PM [vite] Pre-transform error: Failed to load url date-fns-v3/addHours (resolved id: date-fns-v3/addHours) in /Users/jcquintas/dev/vitest-browser-alias-mock/components/DateFnsV3.tsx. Does the file exist?
5:48:02 PM [vite] Pre-transform error: Failed to load url date-fns-v3/parse (resolved id: date-fns-v3/parse) in /Users/jcquintas/dev/vitest-browser-alias-mock/components/DateFnsV3.tsx. Does the file exist?
```

which means the config is working, but the files are not present 🤔

**Comment by sheremet-va** [comment]
> It is not debatable that it works. 🙃

It is debatable whether it works _correctly_.

> which means the config is working, but the files are not present 🤔

It means you misconfigured the `customResolver` API. Usually returning unresolved ids in the alias plugin doesn't work in Vite, you need to resolve it to the correct file. I personally don't know how to work with that API, I would recommend asking in Vite discord server.

In conclusion, the config works correctly. The error is expected, the fact that it works in Node.js fake `jsdom` environment is a bug in Vitest, it should print the same error.

**Comment by JCQuintas** [comment]
This is a more reasonable solution

```tsx
      {
        find: 'date-fns',
        replacement: 'date-fns-v3',
       async customResolver(source, importer, options) {
          if (importer?.includes('DateFnsV3')) {
            return import.meta.resolve(source).replace('file:', '')
          }
          return import.meta.resolve('date-fns').replace('file:', '')
        },
      }
```
