### ISSUE TITLE
Make --typecheck flag target only currently included test file

### ISSUE THREAD

**Issue by U-4-E-A** [vitest-dev/vitest#6648]
### Clear and concise description of the problem

Currently the `--typecheck` appears to include all files from `tsconfig.json` rather than only the currently includes test files from `vitest.config.ts`: -

```
import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    include: ['./__tests__/*test.live.*']
  }
})

```

### Suggested solution

When the `--typecheck` flag is set, have vitest interrogate `vitest.config.ts` to see which files are currently included and type only those.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
Does `--typecheck.include` work as expected here?

https://vitest.dev/config/#typecheck-include
