### ISSUE TITLE
Not all constituents of type  UserConfigExport  are callable

### ISSUE THREAD

**Issue by pereriksson** [vitest-dev/vitest#6659]
### Prerequisites
```
"vitest": "^2.1.2"
```

### Describe the bug

When configuring the vitest framework, and the vite config is defined using a function like so:

```
import { defineConfig, mergeConfig } from 'vitest/config';
import viteConfig from './vite.config';
import tsconfigPaths from 'vite-tsconfig-paths';

export default defineConfig(env => mergeConfig(
    viteConfig(env),
    {
      test: {
        ...
      },
      plugins: ...,
    },
  )
);

```

everything works, but typescript complains about `viteConfig(env)` that:

```
TS2349: This expression is not callable.
Not all constituents of type  UserConfigExport  are callable.
Type  UserConfig  has no call signatures.
```

### Reproduction

- Please see this minimal repo:
https://github.com/pereriksson/vitest-ts-bug

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 86.27 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.1.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.8.3 - /usr/local/bin/npm
    pnpm: 8.6.6 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 129.0.6668.90
    Edge: 129.0.2792.79
    Safari: 17.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by pereriksson** [comment]
@AriPerkkio done!

**Comment by sheremet-va** [comment]
This is an issue with Vite's `defineConfig` override. It doesn't provide an overload for an async function:

```diff
declare function defineConfig(config: UserConfig): UserConfig;
declare function defineConfig(config: Promise<UserConfig>): Promise<UserConfig>;
declare function defineConfig(config: UserConfigFnObject): UserConfigFnObject;
+ declare function defineConfig(config: UserConfigFnPromise): UserConfigFnPromise;
declare function defineConfig(config: UserConfigExport): UserConfigExport;
```

I'd suggest opening an issue in Vite repo.

**Comment by pereriksson** [comment]
@sheremet-va thanks a lot
