### ISSUE TITLE
Vitest never exits (hanging) with threads pool

### ISSUE THREAD

**Issue by gc** [vitest-dev/vitest#6663]
### Describe the bug

Note: The bug involves another dependency, `skia-canvas`. I don't know if the issue is in skia-canvas, or in vitest. It seems logical to report it here first.

When using `pool: "threads`, after my tests are finished:

1. The process never exits, unless I CTRL+C
2. If closed with CTRL+, a nodejs process is left running in the background (and more will keep stacking up each time)
3. It does NOT print the "vitest is hanging, try the hanging-process reporter" message.
4. I observed a worse issue, where CTRL+C wasn't able to close it, and I had to close the process in task manager to make it exit. However, I couldn't figure out what part of my production project was causing this, and the repro doesnt have this issue.
In this real project, I also get this error:
```Error: Failed to terminate worker
 ❯ Timeout._onTimeout node_modules/tinypool/dist/index.js:512:20
 ❯ listOnTimeout node:internal/timers:573:17
 ❯ process.processTimers node:internal/timers:514:```

### Reproduction

https://github.com/gc/skia-vitest-issue

Stackblitz not provided because the repro uses a native module (skia-canvas), alternatively here's the code needed:

Config
```ts
import { defineConfig } from 'vitest/config';

export default defineConfig({
	test: {
		pool: "threads",
	}
});
```

Test file (install skia-canvas)
```ts
import { test } from 'vitest';
import { Canvas } from 'skia-canvas';

test("make a canvas", async () => {
	const canvas = new Canvas(100, 100);
})
```

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 10.59 GB / 31.91 GB
  Binaries:
    Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.6 - C:\Program Files\nodejs\pnpm.CMD
    bun: 1.1.21 - C:\Program Files\nodejs\bun.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @vitest/coverage-v8: ^2.1.2 => 2.1.2
    vitest: ^2.1.2 => 2.1.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is an issue with how `skia-canvas` interact when using worker threads. Since it is a native package, they need to handle this case themselves.

Because such packages exist, Vitest provides a `forks` pool to use `child_process` instead. For the same reason, Vitest defaults to `forks` since Vitest 2.

**Comment by gc** [comment]
Thank you! (I was trying threads as it was faster in my case)
