### ISSUE TITLE
introduce VITEST_WORKER_ID or similar env var

### ISSUE THREAD

**Issue by capaj** [vitest-dev/vitest#667]
### Clear and concise description of the problem

jest has [JEST_WORKER_ID](https://jestjs.io/docs/environment-variables#jest_worker_id), which is useful for example when running X parallel tests, each test can connect to a different DB.

### Suggested solution

it would be nice to be able to use VITEST_WORKER_ID env var to identify workers.
Ideally this would be a positive integer rather then a UUID

### Alternative

the worker ID could also be available as an export that clients could import for example like:
```ts
import { workerId } from 'vitest'

```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by capaj** [comment]
this will be released in 0.3.7 right?

**Comment by sheremet-va** [comment]
> this will be released in 0.3.7 right?

Yes
