### ISSUE TITLE
.only on describe not working as expected

### ISSUE THREAD

**Issue by Tanavya** [vitest-dev/vitest#6671]
### Describe the bug

I am not sure what the behaviour of .only should be, but lets say I have 2 test files.

`test-1.test.ts`

```
describe("test-1", () => {
  test("0", () => {
    expect(0).toEqual(0);
  });
  test("1", () => {
    expect(1).toEqual(1);
  });
});
```

and
`test-2.test.ts`

```
describe.only("test-2", () => {
  test("0", () => {
    expect(0).toEqual(0);
  });
  test("1", () => {
    expect(1).toEqual(1);
  });
});
```

Then I would expect only `test-2.test.ts` to run, since it has a `.only` on the `describe`. But instead both tests are running and the `.only` isn't doing anything. I tried running vitest with `--allowEmpty` flag, but no effect either.

```
✓ src/__tests__/test-1.test.ts (2)
 ✓ src/__tests__/test-2.test.ts (2)

 Test Files  2 passed (2)
      Tests  4 passed (4)
   Start at  10:28:32
   Duration  198ms (transform 21ms, setup 33ms, collect 11ms, tests 23ms, environment 0ms, prepare 71ms)
```

### Reproduction

See above.

### System Info

```shell
System:
    OS: macOS 14.1
    CPU: (8) arm64 Apple M3
    Memory: 117.77 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.16.0 - ~/.proto/shims/node
    npm: 9.8.1 - ~/.nvm/versions/node/v18.18.0/bin/npm
    pnpm: 9.0.4 - ~/Library/pnpm/pnpm
    bun: 1.1.29 - ~/Development/ts-jest-sample/backend-vitest/node_modules/.bin/bun
  Browsers:
    Chrome: 129.0.6668.90
    Safari: 17.1
  npmPackages:
    vitest: ^2.1.2 => 2.1.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`.only` is limited to the file it's running in. If you need to filter the file, you can run `vitest test-1.spec.ts`.
