### ISSUE TITLE
workspace:  __vitest_browser_runner__.runTests is not a function

### ISSUE THREAD

**Issue by unional** [vitest-dev/vitest#6674]
### Describe the bug

I'm in a monorepo with one of the projects using storybook 8.3 with vitest integration in browser mode.

When running `vitest` on the project it is working fine.
But when running `vitest` at the root using workspace it fails with the ` __vitest_browser_runner__.runTests is not a function` error.

The error is similar to #6023, but I'm using `vitest` 2.1.2 and the resolution is working fine (I am using `pnpm` and `@vitest/runner` are all 2.1.2, and as mentioned above `vitest` is working when running directly).

I also tried to run against that project from the root and it also fail:

```sh
vitest "--project=@panwds/storybook" "--printConsoleTrace"


 DEV  v2.1.2 /Users/hwong/pan/panwds
      [@panwds/storybook] Browser runner started by playwright at http://localhost:5173/


⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Errors ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

Vitest caught 4 unhandled errors during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: __vitest_browser_runner__.runTests is not a function

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: __vitest_browser_runner__.runTests is not a function

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: __vitest_browser_runner__.runTests is not a function

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: __vitest_browser_runner__.runTests is not a function
```

### Reproduction

TBR - To Be Repro

### System Info

```shell
System:
    OS: macOS 14.7
    CPU: (10) arm64 Apple M1 Pro
    Memory: 70.25 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.9.0 - ~/.local/state/fnm_multishells/35483_1728501155293/bin/node
    npm: 10.8.3 - ~/.local/state/fnm_multishells/35483_1728501155293/bin/npm
    pnpm: 9.12.1 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
    bun: 0.1.6 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 129.1.70.119
    Chrome: 129.0.6668.90
    Safari: 18.0
  npmPackages:
    @vitest/browser: ^2.1.2 => 2.1.2 
    @vitest/coverage-v8: ^2.1.2 => 2.1.2 
    vitest: ^2.1.2 => 2.1.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
There are probably more errors in the console when you open the browser, by the way

**Comment by lfantone** [comment]
I'm facing the same issue, but something that I noticed is that fails only when running the test with `vitest run` while in watch mode works fine.

Could be something related with playwright closing the browser too soon?

**Comment by unional** [comment]
FYI I experienced this in both test and watch mode.

However, can't repro it in a new repro. Need to see what is causing it.

**Comment by unional** [comment]
The issue I experiencing is caused by https://github.com/pnpm/pnpm/issues/5585

What happens is there are 2 instances of `@vitest/browser`.
The one loaded at the workspace root `vitest` and the one loaded by the project `vitest` are two different instances (and likely the same for `vitest` key deps, where `__vitest_browser_runner__` is).

That's why the call fails

**Comment by lfantone** [comment]
I'm using `yarn` with node-linker as **node_modules**, but I do have the storybook [vitest plugin](https://storybook.js.org/docs/writing-tests/vitest-plugin), looking into their dependencies doesn't look to include `@vitest/browser`

**Comment by radnan** [comment]
for what it's worth - i had the same issue and what worked for is removing all `node_modules` folders and re-running `pnpm install`

```
find . -name node_modules -maxdepth 3 | xargs rm -rf
pnpm i
```

for whatever reason pnpm wasn't updating all the node_modules folders to point to the correct package versions

**Comment by unional** [comment]
@sheremet-va 
I have managed to create a simple enough repro: https://github.com/repobuddy/storybook

Please check out the `pnpm-dedupe` branch.
