### ISSUE TITLE
Add slow test detection

### ISSUE THREAD

**Issue by JesusTheHun** [vitest-dev/vitest#6680]
### Clear and concise description of the problem

The conclusion of #6534 is that slow test detection apply to any top level task within a file.
I use slow test to detect issues in a test _design_, so detecting a slow suite does not help me since tests can be added to a suite, leading to an increase in the overall time.

I understand that some people use that to make sure the test time is evenly distributed between shards ; that’s not my usage.

### Suggested solution

Either a granularity option, or a new option to detect slow test only.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
I don't understand the issue. The duration is reported for tests and suites. Don't look at a suite time if you don't need it

**Comment by sheremet-va** [comment]
> In the current state of things, slow top-level tasks are reported by highlighting the duration of the task. If a test duration is higher than the threshold, it is not highlighted.

It is a bug then, and not a feature request

**Comment by sheremet-va** [comment]
And I cannot reproduce it:

<img width="272" alt="Screenshot 2024-10-11 at 12 10 52" src="https://github.com/user-attachments/assets/d07c3632-65c6-4a6d-97c8-f265b683fb5e">
<img width="422" alt="Screenshot 2024-10-11 at 12 11 09" src="https://github.com/user-attachments/assets/891ba8dd-e01d-4788-81ea-2765a0864e48">
