### ISSUE TITLE
TestContext is not merged with provided generic in `for` calls

### ISSUE THREAD

**Issue by kamilogorek** [vitest-dev/vitest#6681]
### Describe the bug

When using `it.for` or `it.concurrent.for` methods, a generic `<T>` provided as a `TestContext` is not merged with a type generated by those calls.

It can be worked around using a global override, however it's not ideal, as not every test in my test suite has the context available.

```ts
declare module 'vitest' {
  export interface TestContext {
    locallyScopedVariable: number
  }
}
```

*This is only a type issue and when ignored, behavior is correct.*

### Reproduction

```ts
import { beforeEach, describe, it } from 'vitest'

interface LocalTestContext {
  locallyScopedVariable: number
}

describe('Concurrent TestContext', () => {
  beforeEach<LocalTestContext>(async (context) => {
    context.locallyScopedVariable = Math.random()
  })

  // Works as expected
  it<LocalTestContext>('should work with regular `it` call', async ({
    expect,
    locallyScopedVariable,
  }) => {
    expect(locallyScopedVariable).greaterThan(0).lessThan(1)
  })

  // Type 'string' is not assignable to type 'LocalTestContext'.
  it.concurrent.for<LocalTestContext>(['foo', 'bar', 'baz'])(
    'concurrent test #%s',
    // Property 'locallyScopedVariable' does not exist on type 'TaskContext<Test<object>> & TestContext'.
    async (_, { expect, locallyScopedVariable }) => {
      expect(locallyScopedVariable).greaterThan(0).lessThan(1)
    }
  )

  // Type 'string' is not assignable to type 'LocalTestContext'.
  it.concurrent.for<LocalTestContext>(['foo', 'bar', 'baz'])(
    'concurrent test #%s',
    // Property 'locallyScopedVariable' does not exist on type 'TaskContext<Test<object>> & TestContext'.
    async (_, { expect, locallyScopedVariable }) => {
      expect(locallyScopedVariable).greaterThan(0).lessThan(1)
    }
  )
})
```

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 80.09 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.n/bin/node
    npm: 10.8.2 - ~/.n/bin/npm
    pnpm: 9.11.0 - ~/.n/bin/pnpm
    bun: 1.1.29 - ~/.bun/bin/bun
  Browsers:
    Chrome: 129.0.6668.91
    Safari: 17.6
  npmPackages:
    @vitest/eslint-plugin: ^1.1.4 => 1.1.4
    vitest: ^2.1.1 => 2.1.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Can you check https://github.com/vitest-dev/vitest/issues/2892? It look like a duplicate, if so, sharing your workaround there would be great.

**Comment by kamilogorek** [comment]
It is indeed a duplicate, only for different changed methods.

My workaround is listed above, which is using global `vitest.TestContext` instead, which is also mentioned in the docs:

```ts
declare module 'vitest' {
  export interface TestContext {
    locallyScopedVariable: number
  }
}
```

After digging through some code, an issue is cause by methods definition on `TestForFunction`, which has it's first generic used for type inference of `cases`, but is effectively overwritten when `TestContext` is passed.

```ts
interface TestForFunction<ExtraContext> {
    <T>(cases: ReadonlyArray<T>): TestForFunctionReturn<T, ExtendedContext<Test> & ExtraContext>;
    (strings: TemplateStringsArray, ...values: any[]): TestForFunctionReturn<any, ExtendedContext<Test> & ExtraContext>;
}
```

Adding `ExtraContext` as a first generic works, but it messes up the inference entirely, requires passing input type manually and opens another can of worms with backwards compatibility, as it also breaks type inference of template values in `TemplateStringsArray` variant.

**Comment by hi-ogawa** [comment]
Thanks for investigating. Indeed, we already have that in the doc for the workaround, so it's not that bad :smiley: 
Closing this as a duplicate here. If you find a further idea, feel free to share in the original issue.
