### ISSUE TITLE
Should `vi.setConfig({ sequence: { concurrent: true } })` work?

### ISSUE THREAD

**Issue by hi-ogawa** [vitest-dev/vitest#6684]
### Describe the bug

Docs now mentions it's not supported https://vitest.dev/api/vi.html#vi-setconfig But it's available as typing of `vi.setConfig`.
https://github.com/vitest-dev/vitest/blob/2a50464d58e98f58fed513971a570a952081bfef/docs/api/vi.md?plain=1#L977-L980

But it might be a regression and possible to make it work again https://github.com/vitest-dev/vitest/pull/6653#issuecomment-2403730192

If not, we should update `RuntimeConfig` to hide it from typing.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-opxrtz?file=repro.test.ts

(based on tests from https://github.com/vitest-dev/vitest/issues/6652)

### System Info

```shell
(stackblitz)

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: 2.1.2 => 2.1.2 
    vite: latest => 5.4.8 
    vitest: 2.1.2 => 2.1.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Conceptually, I don't see why it wouldn't work:

```
vi.setConfig({ sequence: { concurrent: true } })
describe('suite1') // concurrent
describe('suite2') // concurrent
describe('suite3', { concurrent: false }) // sequential
```
