### ISSUE TITLE
userEvent.keyboard doesn't release pressed key with playwright provider

### ISSUE THREAD

**Issue by kwangure** [vitest-dev/vitest#6693]
### Describe the bug

Interactive API doesn't seem to release keys across consecutive tests or reruns.

Related issue: https://github.com/vitest-dev/vitest/issues/6082 (fixed)

### Reproduction

https://github.com/kwangure/vitest-matcher-rerun-repro

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Memory: 420.47 MB / 3.86 GB
  Binaries:
    Node: 20.16.0 - ~\.local\share\pnpm\node.EXE
    npm: 10.8.1 - ~\.local\share\pnpm\npm.CMD
    pnpm: 9.7.1 - ~\AppData\Local\Microsoft\WinGet\Packages\pnpm.pnpm_Microsoft.Winget.Source_8wekyb3d8bbwe\pnpm.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @vitest/browser: ^2.1.2 => 2.1.2
    vite: ^5.4.8 => 5.4.8
    vitest: ^2.1.2 => 2.1.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
I cannot reproduce following your reproduction steps. The test always succeeds.

**Comment by kwangure** [comment]
I've pulled a clean copy of the linked reproduction and I'm still able to trigger the bug. It succeeds on the initial run. Then I click the green "Rerun current test". In the new run, `Tab` doesn't focus the input because `Alt+Tab` (`Alt` from the previous run) is being pressed instead.

I'm using latest Chromium (1140) that playwright installs.

**Comment by kwangure** [comment]
Also able to reproduce with a 2 test setup as mentioned in the repro's readme:

This succeeds:

```typescript
import { expect, test } from "vitest";
import { render } from "vitest-browser-svelte";
import { userEvent } from "@vitest/browser/context";

import Combobox from "./component.svelte";

test("1", async () => {
	// await userEvent.keyboard("{Alt>}"); // Not okay. I didn't release `{Alt>}` with `{/Alt}`
});

test("2", async () => {
	const screen = render(Combobox);

	await userEvent.keyboard("[Tab]"); // focus input

	await expect.element(screen.getByRole("combobox")).toHaveFocus();
});
```

Quit Vitest watch mode. Uncomment the keypress.
This fails:
```typescript
import { expect, test } from "vitest";
import { render } from "vitest-browser-svelte";
import { userEvent } from "@vitest/browser/context";

import Combobox from "./component.svelte";

test("1", async () => {
	await userEvent.keyboard("{Alt>}"); // Not okay. I didn't release `{Alt>}` with `{/Alt}`
});

test("2", async () => {
	const screen = render(Combobox);

	await userEvent.keyboard("[Tab]"); // `Alt + Tab`

	await expect.element(screen.getByRole("combobox")).toHaveFocus(); // fails
});
```

**Comment by kwangure** [comment]
I'm able to reproduce both scenarios in Chromium 1140 and  Firefox 1465, on both Windows and Linux (WSL).

**Comment by hi-ogawa** [comment]
I can confirm it fails on my PC. Checking `keydown` also shows `alt` is being pressed for re-run.

```js
	document.addEventListener('keydown', (e) => {
		console.log([e.key, e.altKey])
	})
```

```
// initial run
stdout | src/component.test.ts > keydown repro
Tab false
stdout | src/component.test.ts > keydown repro
Alt true

// watch re-run
stdout | src/component.test.ts > keydown repro
Tab true
stdout | src/component.test.ts > keydown repro
Alt true
```
