### ISSUE TITLE
V8 import error inside vitest library

### ISSUE THREAD

**Issue by KaloyanYosifov** [vitest-dev/vitest#670]
### Describe the bug

I receive an import error locally on my machine and on stackblitz. I am using the latest version of vitest `0.2.6`

Here is the error:

```
(node:18) UnhandledPromiseRejectionWarning: file:///home/projects/vitejs-vite-tmqc9d/node_modules/vitest/dist/create-a1bc541a.js:13
import { takeCoverage } from 'v8';
         ^^^^^^^^^^^^
SyntaxError: The requested module 'v8' does not provide an export named 'takeCoverage'
```

### Reproduction

https://stackblitz.com/edit/vitejs-vite-tmqc9d

Run in terminal `npm install` and then `npm run test`

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (8) x64 Apple M1
    Memory: 22.05 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 98.0.4758.80
    Edge: 97.0.1072.76
    Safari: 15.0
    Safari Technology Preview: 15.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Demivan** [comment]
@KaloyanYosifov As a workaround update node to at least `14.18.0`

**Comment by Demivan** [comment]
@antfu `takeCoverage` was added in node `14.18.0`. Should we up the required node version?
Without `takeCoverage` there is no way to flush coverage to disk and have a complete coverage.

**Comment by rayfoss** [comment]
Alternative workaround, downgrade to [0.2.5](https://www.npmjs.com/package/vitest/v/0.2.5). It will run in Node 14.16.0 / Stackblitz
