### ISSUE TITLE
Add 'retry' option for beforeAll / afterAll / beforeEach / afterEach hooks

### ISSUE THREAD

**Issue by andrii-nastenko** [vitest-dev/vitest#6726]
### Clear and concise description of the problem

In my current project, we occasionally encounter API errors (unstable api) during the beforeAll hook. 

To handle this, we have wrap the logic in a custom retry function. But it's a lot of refactoring to wrap it across a whole project...

### Suggested solution

It would be great if Vitest provided an option via configuration file to enable retries for hooks globally (if possible).

Thank you!

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
`beforeEach` are already retried together when test fails (and this behavior makes sense), so having `beforeEach` specific retry might become confusing.

```ts
beforeEach({ retry: 2 }, () => {
});

test('repro', { retry: 2 }, () => {
});
```

It would help if you can elaborate your use case. It sounds odd that you only worry about retry in `beforeAll`, but I suppose you already configure the global retry for `test` https://vitest.dev/config/#retry and you want the same mechanism to cover `beforeAll` as well?

**Comment by andrii-nastenko** [comment]
Yea, I know, if tests fails - it retries failed test and beforeEach as well.

The main problem - we have some flaky endpoints in our beforeAll. So it would be nice to add retry feature for 'beforeAll' (and maybe for 'afterAll' as well)

**Comment by andrii-nastenko** [comment]
For retrying beforeAll logic - we wrap its content with async-retry.
https://www.npmjs.com/package/async-retry

```
export function waitWithRetry<T>(
  fn: (bail: (error?: Error) => void, retries: number) => T,
  options?: RetryOptions
): Promise<ReturnType<typeof fn>> {
  return asyncRetry(fn, {
    retries: 4,
    ...options,
  });
}
```

```
  beforeAll(async () => {
    await waitWithRetry(async () => {
      await SearchApiCaller.dashboardRecentlyViewed();
    });
  });
```

**Comment by hi-ogawa** [comment]
> Yea, I know, if tests fails - Vitest retries failed test and triggers beforeEach (but if beforeEach fails - it will not retry itself).

Probably this is not what you mean, but technically `beforeEach/afterEach` error is already cover by test retry like this https://stackblitz.com/edit/vitest-dev-vitest-qh23zk?file=test%2Frepro.test.ts

I just wanted to make sure this is current retry concept in Vitest, which requires integration with test runner. However, what you need for your use case seems something local and easier to deal with by structuring your code, like async retry wrapper.

If you want to reduce the boilerplate further, you can also create a helper for `beforeAll` like this https://stackblitz.com/edit/vitest-dev-vitest-n2arcf?file=test%2Frepro.test.ts

```ts
function myBeforeAll(retry: number, ...[fn]: Parameters<typeof beforeAll>) {
  beforeAll(async (...args) => {
    let errors: any[] = [];
    for (let i = 0; i < retry; i++) {
      await new Promise((r) => setTimeout(r, 100 * i));
      try {
        return await fn(...args);
      } catch (e) {
        errors.push(e);
      }
    }
    throw errors[errors.length - 1];
  });
}

myBeforeAll(4, async () => {
  await SearchApiCaller.dashboardRecentlyViewed()
});
```

Well, I just noticed that `beforeAll(fn, timeout)` supports timeout, which can be technically implemented as user land wrapper. So, we could do the same for retry like `beforeAll(fn, { timeout, retry, ...(and more)... })` :thinking:

**Comment by andrii-nastenko** [comment]
Thank you for suggestion with custom hooks!

**Comment by sheremet-va** [comment]
By the way, you can also use [`vi.waitFor`](https://vitest.dev/api/vi.html#vi-waitfor) in your hooks:

```ts
beforeAll(() => {
  await vi.waitFor(() => myFunction())
})
```

**Comment by sheremet-va** [comment]
My position on this is that `retry` exists because your assertions might fail or be unstable. There are no assertions in `beforeAll` or `afterAll` hooks, or at least there shouldn't be, so having a `retry` for hooks doesn't seem logical to me. You can always use `vi.waitFor` or `vi.waitUntil` in hooks to reliably get a value if your method of setting up data is unstable.
