### ISSUE TITLE
Allow `expect.element` to accept nullish values.

### ISSUE THREAD

**Issue by kwangure** [vitest-dev/vitest#6727]
### Clear and concise description of the problem

When I'm testing for something not being in the document, I have to do something like:

```typescript
await expect(screen.getByRole('button').query()).not.toBeInTheDocument();
```

When I'm testing for something being in the document I do:
```typescript
await expect.element(screen.getByRole('button')).toBeInTheDocument();
```

Once you know what to do, adding or removing `.element` or adding takes 2 seconds but it's a movement I do _very_ often. Also it took me 5 minutes to figure out what to do the first time `.query()` didn't work in `.element(...)`.

### Suggested solution

It's a small quality of life improvement, but it would be nice if I could do this.

```typescript
await expect.element(screen.getByRole('button').query()).not.toBeInTheDocument();
// .... modify document
await expect.element(screen.getByRole('button')).toBeInTheDocument();
```

This also improves the likely hood that Copilot and ChatGPT will guess the right the thing. Good for machine. Good for human.

### Alternative

Leave it as is.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
This is actually implemented in the latest versions. It works only for `toBeInTheDocument` for now

**Comment by sheremet-va** [comment]
This is part of 2.1.3 release.
