### ISSUE TITLE
`cacheDir` not honored if `deps.optimizer.{mode}.enabled` is true

### ISSUE THREAD

**Issue by Pistonight** [vitest-dev/vitest#6733]
### Describe the bug

`cacheDir` not honored if `deps.optimizer.{mode}.enabled` is true. vitest will save cache to `node_modules/.vite` as if `cacheDir` is not specified.

### Reproduction

Run
```bash
npm create vite@latest
npm i
```
Edit the config
```typescript
/// <reference types="vitest/config" />
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  cacheDir: ".vite",
  plugins: [react()],
  test: {
    deps: {
      optimizer: {
        ssr: {
          enabled: true // toggling this to repro
        }
      }
    }
  }
})

```
Create a test `src/App.test.tsx`
```tsx
import { describe, expect, test } from "vitest";
describe("App", () =>{
    test("works", () => {
        expect(1).not.toBe(2);
    });
});
```
Run
```
npx vitest
```
1. Observe cache is unexpectedly created in `node_modules/.vite`. 
2. Toggle `test.deps.optimizer.ssr.enabled` to `false`, and run `npx vitest` again
3. Observe cache is created in `.vite` as expected

### System Info

```shell
System:
    OS: Windows 11 10.0.26120
    CPU: (32) x64 AMD Ryzen 9 5950X 16-Core Processor
    Memory: 41.33 GB / 63.91 GB
  Binaries:
    Node: 18.20.4 - ~\dotbin\extra\portable\nvm\symlink\node.EXE
    npm: 10.7.0 - ~\dotbin\extra\portable\nvm\symlink\npm.CMD
    bun: 1.1.6 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (127.0.2651.86)
    Internet Explorer: 11.0.26100.1
  npmPackages:
    @vitejs/plugin-react: ^4.3.2 => 4.3.2
    vite: ^5.4.8 => 5.4.9
    vitest: ^2.1.3 => 2.1.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Pistonight** [comment]
I did notice that the deprecated `cache.dir` option behave correctly.

Seems like it's not checking vite cacheDir here but it should?

https://github.com/vitest-dev/vitest/blob/a939779f1db473f8be3de8454bc94de70cfe5b97/packages/vitest/src/node/plugins/utils.ts#L44C1-L64C81

**Comment by sheremet-va** [comment]
> Seems like it's not checking vite cacheDir here but it should?

Looks like a bug indeed. PR is welcome!

**Comment by Pistonight** [comment]
Thanks for confirming, just to clarify my understanding: how do these 3 properties relate and resolve exactly?
1. Vite `cacheDir`
2. Vitest `server.deps.cacheDir`
3. Vitest `cache.dir`

**Comment by hi-ogawa** [comment]
As par the change https://github.com/vitest-dev/vitest/pull/5229, the intent is to put things under `cacheDir + '/vitest'`. Vitest users don't need to configure `server.deps.cacheDir` and the others should mostly look like:

```ts
const finalCacheDir = cache.dir ?? join(cacheDir, "vitest")
```

By default Vite has `cacheDir = 'node_modules/.vite'`, so Vitest uses `node_modules/.vite/vitest`. If you explicitly set `cacheDir = '.vite'`, Vitest should probably use `.vite/vitest`.
