### ISSUE TITLE
Response.blob() does not return a node-module Blob

### ISSUE THREAD

**Issue by hb27** [vitest-dev/vitest#6741]
### Describe the bug

Hi,

When I used Response.blob() with vitest, it failed during type checks with a FileReader. 'TypeError: Failed to execute 'readAsBinaryString' on 'FileReader': parameter 1 is not of type 'Blob'.
The code works correctly with chrome when I returned an image file stream via Http Fetch.
It also works, if I pass the blob from Blob() constructor directly to file reader.
I included both the link and source files of the test.

I did some debugging and Response.blob() in vitest appears to return  Blob class but in chrome returns @nodemodules/type Blob class.

Thank you,
H. B

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-hqauzi?file=package.json

jsdom is required to use FileReader

Package.json
```
{
  "name": "@vitest/example-test",
  "type": "module",
  "private": true,
  "license": "MIT",
  "main": "index.js",
  "scripts": {
    "test": "vitest",
    "test:ui": "vitest --ui",
    "test:run": "vitest run"
  },
  "devDependencies": {
    "@vitest/ui": "latest",
    "vite": "latest",
    "vitest": "latest",
    "jsdom": "latest",
    "@testing-library/react": "latest"
  },
  "stackblitz": {
    "startCommand": "npm run test:ui"
  }
}
```

Test

```
// @vitest-environment jsdom

import { assert, expect, test } from 'vitest';
import { waitFor } from '@testing-library/react';
import { squared } from '../src/basic.js';
import { fileToBase64 } from 'filetobase64/filetobase64.js';

test('blob', async () => {
  const file = new Blob(['image'], { type: 'image/jpg' });
  const fileReader = new FileReader();
  let error = false;
  try{
  fileReader.readAsBinaryString(file);
  } catch(e) {
    console.log(error);
    error = e;
  }
  expect(error).toBeFalsy();
});

test('response', async () => {
  const file = new Blob(['image'], { type: 'image/jpg' });
  const response = new Response(file, {
    headers: { 'Content-type': 'image/jpg' },
  });
  const blob = await response.blob();
  const fileReader = new FileReader();
  let error = false;
  try{
  fileReader.readAsBinaryString(blob);
  } catch(e) {
    console.log(error);
    error = e;
  }
  expect(error).toBeFalsy();
});

```

### System Info

```shell
{
  "name": "@vitest/example-test",
  "type": "module",
  "private": true,
  "license": "MIT",
  "main": "index.js",
  "scripts": {
    "test": "vitest",
    "test:ui": "vitest --ui",
    "test:run": "vitest run"
  },
  "devDependencies": {
    "@vitest/ui": "latest",
    "vite": "latest",
    "vitest": "latest",
    "jsdom": "latest",
    "@testing-library/react": "latest"
  },
}
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
This is jsdom global issue and we have a duplicate issue https://github.com/vitest-dev/vitest/issues/4043
jsdom implements `Blob` and `FileReader`, but doesn't implement `Response`, so `Response.blob` returns Node's global `Blob`.

I tested `happy-dom` and the same test passes, so that can be the workaround.
