### ISSUE TITLE
resolveSnapshotPath to provide project root

### ISSUE THREAD

**Issue by unional** [vitest-dev/vitest#6742]
### Clear and concise description of the problem

Currently, `test.resolveSnapshotPath(testfilePath, extension)` does not provide a way to discover the project root.

This make it not possible to create snapshots relative to the project root in workspace use case.

for example:

```sh 
- packages
  - project-a
    # want to create snapshots here, similar to the default of `jest-image-snapshot`
    - __snapshot__
- vitest.config.ts
- vitest.workspace.ts
```

### Suggested solution

pass a context object to the function including project specific info, such as `root` and other information.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
You might be interested in this: https://github.com/vitest-dev/vitest/pull/1620
