### ISSUE TITLE
browser mode: css imported in a setup file should be auto reloaded

### ISSUE THREAD

**Issue by luisrudge** [vitest-dev/vitest#6744]
### Clear and concise description of the problem

I want to see css changes being hot reloaded when updating the test setup file.

### Suggested solution

Ideally, the css should be hot reloaded even if it's inside the test setup file

### Alternative

alternatively, you could re-run all the tests if anything changes in a test setup file (including any of the imported css files)

### Additional context

currently, if I import a css in a setup file, the css only gets reloaded if I re-run the test. it hot reloads if I import the file inside a test file.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
Can you provide a reproduction? I tested a simple example and it looks like css change is triggering re-run. https://stackblitz.com/edit/vitest-dev-vitest-fkctwg?file=repro-setup.js (this doesn't seem to run on stackblitz, but it's working locally)

**Comment by luisrudge** [comment]
I don't know exactly what happened, but must've been a misconfiguration on my end. I moved some files around etc and now it works. Sorry :(
