### ISSUE TITLE
browser testing: enable (or make it easier) to copy/paste text

### ISSUE THREAD

**Issue by luisrudge** [vitest-dev/vitest#6746]
### Clear and concise description of the problem

I want to paste text into an element

### Suggested solution

no idea 😅 I'm sure the drivers must have support for the clipboard api somehow

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
> no idea 😅 I'm sure the drivers must have support for the clipboard api somehow

I'm not sure. There are some issue on playwright https://github.com/microsoft/playwright/issues/15860 https://github.com/microsoft/playwright/issues/24039, which suggest workaround using `ClipboardEvent` or `navigator.clipboard` on window (so no cdp or bid based mechanism I suppose?)

Have you tried testing-library's clipboard api? https://testing-library.com/docs/user-event/clipboard

**Comment by luisrudge** [comment]
yeah I tried RTL with

```
await userEventTestingLibrary.keyboard('{Control}{c}');
await userEventTestingLibrary.keyboard('{Control}{v}');
```

and also 

```
await userEventTestingLibrary.paste('test');
```

but it didn't work

**Comment by luisrudge** [comment]
to be clear, I don't want to interact with window.navigator.clipboard. I need to test what happens when you paste into a specific text input

**Comment by hi-ogawa** [comment]
Once again, it looks working with this example of mine :sweat_smile: https://stackblitz.com/edit/vitest-dev-vitest-ccmzqe?file=test%2Frepro.test.ts Note that `{Control>}` is the command to hold down the key.

Can you share how you code looks like?

**Comment by hi-ogawa** [comment]
"Control+C/X/V" combo seems to mostly work on playwright and webdriverio, so we could implement testling-library-like `copy/cut/paste` API on top of that https://testing-library.com/docs/user-event/clipboard/
I'm not sure how we can expose `DataTransfer` though.

**Comment by luisrudge** [comment]
thanks for the repro, but it seems like it's not working?
<img width="1885" alt="image" src="https://github.com/user-attachments/assets/467e4a4f-d18d-433d-baa8-805d8f93ad3a">


the value is not there and nothing is logged to the console.

**Comment by luisrudge** [comment]
it also doesn't work locally
<img width="1787" alt="image" src="https://github.com/user-attachments/assets/cf718191-8ecc-421c-9560-0505d1959246">

**Comment by hi-ogawa** [comment]
Hmm weird, It's working on my Linux PC. Do you use Mac? According to https://github.com/microsoft/playwright/issues/8114, you might need `Meta` instead of `Control` for modifier.

**Comment by luisrudge** [comment]
after my [conversation in discord](https://discord.com/channels/917386801235247114/1297090218901377074) with @hi-ogawa, we figured out the issue:

- when you run in stackblitz, it always run in 'preview' (even if you configured playwright or webdriverio)
- so I had to test it locally, but since I'm using a Mac, I have to use the `Meta` key and not `Control`

For other people with the same issue, this is how you copy/paste content:

### Mac

```typescript
import { test } from 'vitest';
import { page, userEvent } from '@vitest/browser/context';

test('clipboard', async () => {
  document.body.innerHTML = `
    <input placeholder="first" />
    <input placeholder="second" />
  `;

  // write "hello" and copy to clipboard
  await userEvent.click(page.getByPlaceholder('first'));
  await userEvent.keyboard('hello');
  await userEvent.keyboard('{selectall}');
  await userEvent.keyboard('{Meta>}{c}{/Meta}');

  // paste twice into second
  await userEvent.click(page.getByPlaceholder('second'));
  await userEvent.keyboard('{Meta>}{v}{/Meta}');
  await userEvent.keyboard('{Meta>}{v}{/Meta}');

  // hellohello
  console.log(page.getByPlaceholder('second').query()?.value);
});
```

### Linux/Windows

```typescript
import { test } from 'vitest';
import { page, userEvent } from '@vitest/browser/context';

test('clipboard', async () => {
  document.body.innerHTML = `
    <input placeholder="first" />
    <input placeholder="second" />
  `;

  // write "hello" and copy to clipboard
  await userEvent.click(page.getByPlaceholder('first'));
  await userEvent.keyboard('hello');
  await userEvent.keyboard('{Control>}{a}{/Control}');
  await userEvent.keyboard('{Control>}{c}{/Control}');

  // paste twice into second
  await userEvent.click(page.getByPlaceholder('second'));
  await userEvent.keyboard('{Control>}{v}{/Control}');
  await userEvent.keyboard('{Control>}{v}{/Control}');

  // hellohello
  console.log(page.getByPlaceholder('second').query()?.value);
});
```

**Comment by luisrudge** [comment]
oh, nevermind. Playwright supports the `ControlOrMeta` key natively, so you can use just that 😅
https://playwright.dev/docs/api/class-keyboard#keyboard-press
