### ISSUE TITLE
In the UI show test report when clicking on a test

### ISSUE THREAD

**Issue by noam-honig** [vitest-dev/vitest#6747]
### Clear and concise description of the problem

Currently when I use the UI with the `--ui` flag, when I click a test on the UI nothing happens, there's a button to show the source code - but that's less useful (and also doesn't show the source of the test, just the source of the entire file)
There is an "Open test details" that is available only on the test file level - the same icon on the test level does the "show code" functionality.

### Suggested solution
The dream would be to click a test and see why it failed.

When I click on the test in the left panel, show that specific test's report.
If I had my way, the tabs should be "Report" "Console" (also preferrably for the clicked test only) than code and module graph.

Checkout this stackblitz to see my current experience:
https://stackblitz.com/edit/api-test-example-qrjqcu?file=test.spec.ts

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jycouet** [comment]
This would improve the UI and make it more usefull 👍
Thx

**Comment by pav-stastny** [comment]
It was really confusing for me, why clicking in the list does "nothing". Probabyl one small improvement before fully integrationg the suggestion, would be to handle click on list item same as the click on the ICON. Currently there is a cursor hinting interactive list element, but it does nothing. 

![image](https://github.com/user-attachments/assets/5324c8aa-00b3-4ed7-b1c3-6fa71e90effc)

**Comment by noam-honig** [comment]
@pav-stastny Yes but :)
on a file line - it opens the report tab, on a test line it opens the code tab (and doesn't even focus on the code for that test)

Quick solution, have it open the report tab for that test or if not possible, for the file.

Thanks

**Comment by joshuahhh** [comment]
This is especially bad because tests have `cursor: pointer`, which is supposed to mean the element is clickable, but it's not.

**Comment by sheremet-va** [comment]
Fixes by https://github.com/vitest-dev/vitest/pull/6900

**Comment by AlemTuzlak** [comment]
@sheremet-va Thank you so much for this! When can we expect this to drop? Will it be in v2.x.x or?

**Comment by sheremet-va** [comment]
This will be in Vitest 3 which comes out in January

**Comment by AlemTuzlak** [comment]
awesome! is it already in the beta that just came out? Would love to try it out

**Comment by sheremet-va** [comment]
> awesome! is it already in the beta that just came out? Would love to try it out

The beta is out, but this change is not yet released. Should be available later today though

**Comment by AlemTuzlak** [comment]
awesome, thank you so much!
