### ISSUE TITLE
`BaseSequencer` class uses deprecated type `WorkspaceSpec`

### ISSUE THREAD

**Issue by eskylake** [vitest-dev/vitest#6752]
### Describe the bug

`BaseSequencer` class uses `WorkspaceSpec` type, marked as @deprecated.

https://github.com/vitest-dev/vitest/blob/63f8b07042e9885d74daca7e175351c47078b99a/packages/vitest/src/node/sequencers/BaseSequencer.ts#L5

### Reproduction

You should see a warning about using the deprecated WorkspaceSpec type during the build process.

### System Info

```shell
System:
    OS: Linux 6.8 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
    Memory: 3.77 GB / 15.40 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.12.1 - ~/.volta/tools/image/node/20.12.1/bin/node
    Yarn: 3.7.0 - ~/.volta/tools/image/yarn/3.7.0/bin/yarn
    npm: 10.5.0 - ~/.volta/tools/image/node/20.12.1/bin/npm
    bun: 0.1.5 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 130.1.71.114
    Chrome: 130.0.6723.58
    Chromium: 129.0.6668.100
  npmPackages:
    @vitest/coverage-v8: ^2 => 2.1.1 
    vitest: ^2 => 2.1.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
What is the problem? It uses deprecated object because the arguments will change in Vitest 3, we can't just replace it.
