### ISSUE TITLE
unnecessary async breaking useFakeTimers

### ISSUE THREAD

**Issue by cjoecker** [vitest-dev/vitest#6758]
### Describe the bug

When an async function has no promise inside, tests with `vi.useFakeTimers` are not running.

### Reproduction

[StackBlitz](https://codesandbox.io/p/devbox/validated-form-error-forked-hrtpnc)

Code:
```ts
export function wait(ms: number) {
  return new Promise((resolve) => {
    return setTimeout(resolve, ms / 20);
  });
}

export function getLastSync(arr: number[]) {
  return arr.at(-1);
}

export async function getLastAsync(arr: number[]) {
  return arr.at(-1);
}

const myFunction = async (arr: number[]) => {
  // not working
  const lastItem = await getLastAsync(arr);

  // working
  //const lastItem = getLastAsync(arr);
  await wait(150);
  console.log("lastItem", lastItem);
  return "done";
};

test("function resolves within timeout", async () => {
  vi.useFakeTimers();

  const arr: number[] = [1, 2];

  const promise = myFunction(arr);

  vi.advanceTimersByTime(150);

  const result = await promise;
  expect(result).toBe("done");
});
```

### System Info

```shell
System:
    OS: macOS 15.0.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 86.53 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v16.19.1/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v16.19.1/bin/npm
    pnpm: 8.14.3 - ~/.nvm/versions/node/v16.19.1/bin/pnpm
  Browsers:
    Chrome: 129.0.6668.103
    Safari: 18.0.1
  npmPackages:
    @vitejs/plugin-react: ^4.3.2 => 4.3.2 
    @vitest/coverage-v8: ^2.1.2 => 2.1.2 
    vite: ^5.4.8 => 5.4.8 
    vitest: ^2.1.2 => 2.1.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
From what I can see in the reproduction, this works correctly. The `wait` wasn't called yet when you called `vi.advanceTimersByTime` because the `await getLastAsync` is blocking the thread. When you turn it into `const lastItem = getLastAsync(arr);`, the JavaScript sync execution stops on the `wait` like you expect. If your code always awaits a sync function, you can try awaiting the `queueMicrotask`.
