### ISSUE TITLE
Changed types for extending matchers

### ISSUE THREAD

**Issue by dosolkowski-work** [vitest-dev/vitest#6761]
### Describe the bug

Similar to #6660, it looks like the `Assertion<T>` type is being found in `@vitest/expect` now instead of `vitest` itself. This changed from v2.1.2 to v2.1.3. As a result, the [Extending Matchers](https://vitest.dev/guide/extending-matchers.html#extending-matchers) documentation on Vitest's own website no longer works; TypeScript will not find the custom matcher functions. If this change is desired, please update the documentation on the website to match.

### Reproduction

The code in [Extending Matchers](https://vitest.dev/guide/extending-matchers.html#extending-matchers) no longer works as-is. Instead, it must be changed to the following:

```ts
import '@vitest/expect'

interface CustomMatchers<R = unknown> {
  toBeFoo: () => R
}

declare module '@vitest/expect' {
  interface Assertion<T = any> extends CustomMatchers<T> {}
  interface AsymmetricMatchersContaining extends CustomMatchers {}
}
```

In addition, depending on the package manager setup, it may be necessary to add a package reference to `@vitest/expect`.

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13950HX
    Memory: 12.14 GB / 31.61 GB
  Binaries:
    Node: 20.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.2 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @vitest/coverage-istanbul: ^2.1.3 => 2.1.3
    @vitest/eslint-plugin: ^1.1.7 => 1.1.7
    @vitest/ui: ^2.1.3 => 2.1.3
    vite: ^5.4.9 => 5.4.9
    vitest: ^2.1.3 => 2.1.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
It's working for me https://github.com/hi-ogawa/reproductions/tree/main/vitest-6761-expect-extend Can you provide a reproduction?

**Comment by dosolkowski-work** [comment]
I was able to reproduce using a project created from the StackBlitz link: https://stackblitz.com/edit/vitest-dev-vitest-mskyqm

**Comment by dosolkowski-work** [comment]
I suspect the StackBlitz is not actually reproducing the issue, so I went back to my own reproduction.

1. [Initial version](https://github.com/dosolkowski-work/vite-workspace-experiment/tree/3177ca43ecbb6f8b092f20cb6d48a701fabb195c) on vitest 2.1.2: [no issues](https://github.com/dosolkowski-work/vite-workspace-experiment/actions/runs/11239342625) ✅
2. [Upgrade all dependencies](https://github.com/dosolkowski-work/vite-workspace-experiment/commit/94b4ba666c39c183b069d93f64322b488c09fd48) including vitest to 2.1.3: [custom matcher not found](https://github.com/dosolkowski-work/vite-workspace-experiment/actions/runs/11463206292) ❌
3. [Try different approach](https://github.com/dosolkowski-work/vite-workspace-experiment/commit/101e93034ea7d2423adf3ec12287fa556060718a) that matches the docs more accurately: [still not found](https://github.com/dosolkowski-work/vite-workspace-experiment/actions/runs/11463303498) ❌
4. [Change module](https://github.com/dosolkowski-work/vite-workspace-experiment/commit/8da92cd5c2348b5bc248090544b83a9f4f6a4ce0) to `@vitest/expect`: [now it works](https://github.com/dosolkowski-work/vite-workspace-experiment/actions/runs/11463494475) ✅

**Comment by hi-ogawa** [comment]
Can you try reproducing without `vitest-axe`? Maybe not relevant but it would help narrowing it down.

**Comment by hi-ogawa** [comment]
Not sure but this one looks hard. It looks like `@testing-library/jest-dom` also does `declare module`, so that seems like a part of the issue. It would be great if you can minimize the repro further (ideally only with `vitest`, `@testing-library/jest-dom`, `vitest-axe`, `typescript` also without monorepo).

**Comment by dosolkowski-work** [comment]
I made a new reproduction repository, and something strange is happening: https://github.com/dosolkowski-work/vitest-extend-types-issue/actions

Adding `vitest-axe` and the code around it introduced the problem, but if I *move* the helper function to a different file, suddenly everything is fine--I'm not sure if there's some special behavior of vitest with regards to `setupFiles` that makes things go haywire if I then import from the same file? Maybe it's just a bad idea in general to ever reference that file or export things from it?

**Comment by dosolkowski-work** [comment]
In the current scenario, the instant you attempt to import anything from `setupTests.ts` anywhere, everything shifts and breaks, and I have no idea why, but if you don't, everything behaves the way the docs say it should. I'll see if I can reproduce without `vitest-axe` in the picture.

**Comment by dosolkowski-work** [comment]
This is making less and less sense over time. It seems like it's probably not a vitest issue after all and can be closed. It's an incredibly specific combination of things that have to be in place for the problem to manifest, and no one thing seems to make a difference on its own. In the [simpler reproduction](https://github.com/dosolkowski-work/vitest-extend-types-issue), all you have to do is change where the `accessibilityViolationsCheck` helper function is imported from in `App.test.test`--if you import it from `setupTests`, everything explodes. If you import it from `testUtils`, everything is fine.
