### ISSUE TITLE
`vi.mocked()` with `partial: true` does the opposite of what's intended?

### ISSUE THREAD

**Issue by kahagerman** [vitest-dev/vitest#6781]
### Describe the bug

I'm new to vitest/mocking in general, so please tell me if I'm misunderstanding the use case here.

To my understanding, this code should compile. 
```typescript
const mockedObject: ComplexInterface = vi.mocked({onlyOneProperty: "set"}, {partial: true})
```
From the original issue (https://github.com/vitest-dev/vitest/issues/1739), the purpose of `partial: true` seems to be to allow defining only a few properties without typescript complaining.

But from what I can tell (simplifying the actual types somewhat), this function accepts the type `T`, and returns `Partial<T>`, where it should instead accept a `Partial<T>` and return `T`.

Am I simply misunderstanding this?  (If so, it may be worth explaining these options better in the docs.)

### Reproduction

N/A

### System Info

```shell
N/A
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This works correctly. "mocked" is just a type hint noop, it doesn't do anything. You need pass down a spy, and `partial` will allow you to call `mockReturnValue` on it with incomplete data
