### ISSUE TITLE
globalSetup executed twice with --ui

### ISSUE THREAD

**Issue by dominikg** [vitest-dev/vitest#679]
### Describe the bug

If you add a globalSetup file and run `vitest --ui` the setup function is executed twice

### Reproduction

https://stackblitz.com/edit/node-arkh2h?devtoolsheight=33&file=globalSetup.ts

run `npm run test` observe 'globalSetup' is logged twice

### System Info

```shell
Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.3.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: 96.0
  npmPackages:
    vitest: workspace:* => 0.2.7
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dominikg** [comment]
it looks like vite patches httpServer.listen https://github.com/vitejs/vite/blob/3311686bbcc12481495374c58cd1bc054d2429b8/packages/vite/src/node/server/index.ts#L579

to call buildStart, and vitest calls buildStart explicitly here https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/node/create.ts#L26  and then if --ui is set httpServer.listen is called by https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/node/create.ts#L29 

i'm not really sure why vitest is calling buildStart manually, my gut feeling is that this should be handled by vite internally.

cc @antfu

**Comment by patak-dev** [comment]
`buildStart` is needed before calling other hooks as some plugins are using this hook to initialize caches (the hook is also called when re-building in build watch mode so it is a good place to place this code instead of when constructing the plugin).

I think we should avoid the manual call to `buildStart` if `--ui` is enabled.
