### ISSUE TITLE
2.1.4: Failed to load source map for typescript.js

### ISSUE THREAD

**Issue by RobinTail** [vitest-dev/vitest#6806]
### Describe the bug

While upgrading vitest from 2.1.3 to 2.1.4 this error appeared in the beginning of the tests.
It's not causing tests to fail though.

```
 RUN  v2.1.4 ...
      Coverage enabled with istanbul

4:01:17 AM [vite] Failed to load source map for .../node_modules/typescript/lib/typescript.js.
Error: An error occurred while trying to read the map file at typescript.js.map
Error: ENOENT: no such file or directory, open '.../node_modules/typescript/lib/typescript.js.map'
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-lgenvr?file=src%2Fbasic.ts

Seems to be related to importing `typescript`:

```ts
import { factory } from 'typescript';
```

### System Info

```shell
System:
    OS: macOS 14.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 623.28 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.11.1/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.11.0 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
    bun: 1.1.32 - /usr/local/bin/bun
  Browsers:
    Chrome: 130.0.6723.70
    Safari: 18.0.1
  npmPackages:
    @vitest/coverage-istanbul: ^2.0.3 => 2.1.4
    vitest: ^2.0.3 => 2.1.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
With this change https://github.com/vitest-dev/vitest/pull/6724, we started to surface warning from plugins, so this is a part of it.

Technically this might be typescript package's issue since they have `sourceMappingURL` which points to a non-existing file.

```
$ tail node_modules/typescript/lib/typescript.js
//# sourceMappingURL=typescript.js.map

$ ls node_modules/typescript/lib/typescript*
node_modules/typescript/lib/typescript.d.ts
node_modules/typescript/lib/typescript.js    
```

**Comment by RobinTail** [comment]
> we started to surface warning from plugins

Well... #6724 aimed to address #6598 that was about custom plugins.
But there is no plugin here, right? It happens in a bare vitest example.

**Comment by RobinTail** [comment]
Related issue in Typescript https://github.com/microsoft/TypeScript/issues/32207

**Comment by hi-ogawa** [comment]
> Well... #6724 aimed to address #6598 that was about custom plugins.
> But there is no plugin here, right? It happens in a bare vitest example,

I meant plugins including Vite's internal ones and warning is coming from there.

Btw, another odd thing is that Vitest is transforming a giant `typescript.js`, which shouldn't be necessary. This could be an issue on Vitest side's heuristics, but for now you can enforce it from `test.server.deps.external` like this https://stackblitz.com/edit/vitest-dev-vitest-81tnhv?file=vite.config.ts

**Comment by RobinTail** [comment]
> test.server.deps.external

This resolves my problem. Thank you so much!

But you're right, that should have not been necessary taking into account that the default value for `test.server.deps.external` should be `[/node_modules/]`

**Comment by RobinTail** [comment]
`test.server.deps.external` is not present in the default config

https://github.com/vitest-dev/vitest/blob/47d7c0aeb6dac50b0279eb1d202a204f31ead52d/packages/vitest/src/defaults.ts#L102-L140

**Comment by RobinTail** [comment]
> odd thing

Made a fix for that in #6807 , @hi-ogawa

**Comment by hi-ogawa** [comment]
I haven't looked into this deeper, but It's likely that the issue about `external` is more complicated than that. Currently, we rely on quite a few checks here and changing the default entirely isn't intended.

**Comment by RobinTail** [comment]
when you'll release the fix, @sheremet-va ?

**Comment by sheremet-va** [comment]
> when you'll release the fix, @sheremet-va ?

today
