### ISSUE TITLE
Provide a way to get only the number of files or test cases that will be tested with `--changed` option without actually running tests

### ISSUE THREAD

**Issue by centraldogma99** [vitest-dev/vitest#6814]
### Clear and concise description of the problem

In my CI environment, I use the --changed option to run tests only on modified files for faster performance, alongside sharding for parallel processing. However, when there are few modified files and therefore a small number of tests, using sharding becomes inefficient as it consumes workers without improving performance. I want to configure the system to skip sharding when there are only a few tests and to use sharding only when there are many tests. Currently, though, there isn’t a way to determine the test load in advance.

### Suggested solution

I would like a CLI command that, without actually running tests, provides the number of files or test cases that would be tested when using the --changed option.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
There is `vitest list --filesOnly`: https://vitest.dev/guide/cli.html#vitest-list

You can combine it with other flags like `--changed`.
