### ISSUE TITLE
DOM not reset between tests when using jsdom/happy-dom

### ISSUE THREAD

**Issue by EvHaus** [vitest-dev/vitest#682]
### Describe the bug

I have a very simple project with a React component that I'm testing using `jsdom` (or `happy-dom`) and `@testing-library/react`. Each test passes when focused with `it.only()` but when all tests run together, they fail. They fail because the DOM is being polluted (not reset) between each test, so each `it()` test injects its own instance of the component whereas my test suite expects only 1 instance to exist at a time.

This is different from how Jest works. Not sure if this is intentional in Vitest or not. I can't seem to find a way to reset the DOM between each test without going deep into the JSDom internals.

### Reproduction

https://stackblitz.com/edit/node-tphuqu?file=index.test.tsx&view=editor

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 20.93 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
    Watchman: 2022.01.31.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 97.0.4692.99
    Chrome Canary: 100.0.4868.0
    Firefox: 96.0.2
    Safari: 15.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jamalvarez** [comment]
Try calling [the cleanup method from testing-library](https://testing-library.com/docs/react-testing-library/api/#cleanup) on a beforeEach for your tests 

I added it on top of your Demo and [tests are passing correctly now](https://stackblitz.com/edit/node-7ges4t?file=index.test.tsx) because 

> [ cleanup() ] Unmounts React trees that were mounted with [render](https://testing-library.com/docs/react-testing-library/api/#render).

Hope this helps!

**Comment by sheremet-va** [comment]
You can either cleanup DOM yourself like @jamalvarez suggested, or enable config globals: true, so testing-library could do it automatically.

**Comment by EvHaus** [comment]
Ah, I see. Because `globals` are off, the clean up doesn't run automatically?

Given the popularity of `react-testing-library`, would you be okay with me opening a PR to add this as a note in the docs somewhere?

**Comment by sheremet-va** [comment]
I am not against it.
