### ISSUE TITLE
Error code of test run with not default reporter always 0 even with unhandled error

### ISSUE THREAD

**Issue by underoot** [vitest-dev/vitest#6831]
### Describe the bug

When you have in the list of reporters any other than `basic` reporters, the vitest process always exits with a 0 status code. If you have the default or the basic reporter process exit, in case of an unhandled error, with status code 1.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-5r9pk4

`npm run test:run` — everything okay, we see error and `echo $?` gives us 1
`CI=1 npm run test:run` — not okay: we don't see error and `echo $?` gives us 0

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: latest => 2.1.4 
    vite: latest => 5.4.10 
    vitest: latest => 2.1.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Fixed by https://github.com/vitest-dev/vitest/pull/6808.
