### ISSUE TITLE
Show test failure details in UI report tab

### ISSUE THREAD

**Issue by uicrafts** [vitest-dev/vitest#684]
### Clear and concise description of the problem

Currently when a test fails, the details of the failure are shown in the terminal, but it would be great if they were also displayed in the UI. I've tested this on a React project with TypeScript. 

### Suggested solution

The UI of Vitest is such a killer feature, so thank you for building this! At the moment the UI only marks the test case as failed, but the "Report" tab only renders the name of the component. Ideally, it would display the details of the test failure. Has this been considered? 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by DerYeger** [comment]
Hi, thank you for the suggestion!

I created #685 to address this issue. Does the attached screenshot meet your requirements?

**Comment by uicrafts** [comment]
Thank you @DerYeger for your speedy PR!

Yeah it looks good! Out of curiosity, the `task: Task` object in the `collectFailed` function would receive the test failure output that's also shown in the terminal when unit or even snapshot tests fail?

**Comment by DerYeger** [comment]
> Thank you @DerYeger for your speedy PR!

Thanks!

> Yeah it looks good! Out of curiosity, the `task: Task` object in the `collectFailed` function would receive the test failure output that's also shown in the terminal when unit or even snapshot tests fail?

I'm not sure, since I haven't worked on the terminal output.
The UI report is only for a single file. So I guess the terminal output differs by collecting the failed tasks of all files.

**Comment by uicrafts** [comment]
That makes sense, thanks for explaining. Look forward to trying this out once it's merged (unless there's another way you'd want me to test this before merging and I'll be happy to do so).

**Comment by Demivan** [comment]
There is `logs` property on the Task that could be used for this.

**Comment by uicrafts** [comment]
Looks like there's some info here that may be potentially useful:

`logs?: UserConsoleLog[]`

```
export interface UserConsoleLog {
  content: string
  type: 'stdout' | 'stderr'
  taskId?: string
  time: number
}
```

https://github.com/vitest-dev/vitest/blob/77ba9fa8894cc9328676ec8bf729ec192986db37/packages/vitest/src/types/general.ts#L40

**Comment by DerYeger** [comment]
@Demivan @uicrafts In what way should the logs be used here? There already is a logs view.

**Comment by Demivan** [comment]
I thought logs are not being displayed if test fails. It they are, then everything is fine.

**Comment by uicrafts** [comment]
I apologize if perhaps I didn't clarify things correctly when opening this issue! The original idea/suggestion that prompted me to open this thread was that when tests fail, the terminal shows the log details for that failure, but the UI doesn't. Here's an example of a snapshot test (but the same happens with unit tests):

<img width="100%" height="60%" alt="image" src="https://user-images.githubusercontent.com/4595734/152655902-6e903d49-dc2a-4aca-afb5-85ac3e35d096.png">

<img width="975" alt="image" src="https://user-images.githubusercontent.com/4595734/152655908-5da2abdb-4046-46c3-8cc2-981223cc7470.png">

As you can see, the UI only displays the name of the failed component, but no logs/details for the test failure like we see in the terminal. @Demivan looking at the `UserConsoleLog` interface, would the `content` property contain the log failure (i.e. my first screenshot), or is it maybe just used for something else like capturing `console.log` calls from the user?

**Comment by userquin** [comment]
@uicrafts can you go in that case to code tab? IIRC that error is shown in the code.

**Comment by userquin** [comment]
![imagen](https://user-images.githubusercontent.com/6311119/152656384-2c9f0e09-d8a6-422a-a79a-c99c7ffb773a.png)

**Comment by uicrafts** [comment]
@userquin I thought that might be the case too initially, but it looks like the `Code` tab doesn't display any test failures and instead shows the source code (the whole `Modal.test.tsx` file), which is also pretty handy 👌

**Comment by userquin** [comment]
@uicrafts it seems `tsx` or tests with `snapshots` not working, tested on my repro (not working). It seems that codemirror is not updating either.

**Comment by uicrafts** [comment]
@userquin Ah, thanks for confirming on your end that it's a bug 👍 

Also, that's a nice tip about being able to update the tests and save the file from the UI -- another cool feature in Vitest 👌

**Comment by DerYeger** [comment]
@uicrafts I think my PR does just that.

![image](https://user-images.githubusercontent.com/7950094/152657778-ece8864c-6760-4e6a-af04-48a8af0f2617.png)

The `logs` are just your `console` output.

@Demivan The logs of failing tests are included.
