### ISSUE TITLE
ReferenceError: process is not defined - playwright

### ISSUE THREAD

**Issue by AllanOricil** [vitest-dev/vitest#6842]
### Describe the bug

bundled playwright throws the following exception when vitest is requiring it
<img width="954" alt="image" src="https://github.com/user-attachments/assets/4909dc40-f40e-4bb9-83b2-f21ead70bba3">

### Reproduction

Repository and branch: https://github.com/AllanOricil/nrg-template/tree/vitest

1. clone the above repo and checkout `vitest` branch
2. run `npm install`
3. run `npx playwright install`
4. run `npm run test`
5. verify you get the same error message

I can't use `playwright@v1.48.2` because of this other issue https://github.com/microsoft/playwright/issues/33031. After downgrading to `v1.47.2` I fixed the bundling issue reported in the aforementioned link.

### System Info

```shell
System:
    OS: macOS 14.4
    CPU: (8) arm64 Apple M1
    Memory: 49.50 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.18.0 - ~/.nvm/versions/node/v18.18.0/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 10.8.3 - ~/nrg-template/node_modules/.bin/npm
    pnpm: 8.9.0 - ~/.nvm/versions/node/v18.18.0/bin/pnpm
  Browsers:
    Brave Browser: 130.1.71.118
    Chrome: 130.0.6723.92
    Safari: 17.4
  npmPackages:
    @vitest/browser: ^2.1.4 => 2.1.4 
    @vitest/coverage-istanbul: ^2.1.4 => 2.1.4 
    @vitest/ui: ^2.1.4 => 2.1.4 
    vitest: ^2.1.4 => 2.1.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
I don't see Vitest browser test anymore in your reproduction https://github.com/AllanOricil/nrg-template/blob/4cc1100cf3b9396e634ff868f1c3818127f89453/vitest.config.js#L12

**Comment by hi-ogawa** [comment]
If you're referring to this commit https://github.com/AllanOricil/nrg-template/commit/0b62dc0769f3dac7574b1545fc5b4111e0f44620#diff-fadc0759b0097a9718f4e99e2781b157c2f6f270e50ef0ee6f33e8c6f8f8e83a, then it's not supposed to use `playwright` in this way for Vitest browser mode. Please follow the guide in the doc https://vitest.dev/guide/browser/#examples

**Comment by AllanOricil** [comment]
I gave up on it and used playwright directly. My use case was fixed and I gave up on this vitest feature.

**Comment by AllanOricil** [comment]
This is the commit

https://github.com/AllanOricil/nrg-template/commit/0b62dc0769f3dac7574b1545fc5b4111e0f44620

**Comment by AllanOricil** [comment]
And wtf is this comment anyways. If someone opens a bug, and you know what is wrong. The least you have to do is to say "WHAT" is wrong. I followed vitest docs and it didn't work. I followed playwright docs and it worked straight away.
