### ISSUE TITLE
New assertion matcher "toHaveBeenCalledOnceWith"

### ISSUE THREAD

**Issue by DMartens** [vitest-dev/vitest#6849]
### Clear and concise description of the problem

Currently there is no way to test whether a spy is only called once with certain arguments but both assertions are essential.
This currently requires two assertions:
`expect(spy).toHaveBeenCalledWith(...args)` and `expect(spy).toHaveBeenCalledOnce()`.
I argue this case is so common that there should be a matcher included by default for this.

### Suggested solution

Add a new default assertion matcher "toHaveBeenCalledOnceWith" which combines the checks of `toHaveBeenCalledOnce` and `toHaveBeenCalledWith`:
1. checks the spy has been called once
2. the provided arguments match
The matcher should throw on error when there are less than two arguments.

### Alternative

- Use `expect.extend` per project
- Add a more universal way to combine multiple assertion matchers

### Additional context

There is an existing matcher for Jest via [jest-extended](https://jest-extended.jestcommunity.dev/docs/matchers/Mock#tohavebeencalledexactlyoncewith).
I am willing to submit a PR for this if accepted.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
Yeah, it looks nice to have. We'll have `toHaveBeenCalledAfter/Before` soon https://github.com/vitest-dev/vitest/pull/6056, so `toHaveBeenCalledExactlyOnceWith` is the last one missing from https://jest-extended.jestcommunity.dev/docs/matchers/Mock
