### ISSUE TITLE
Dynamically specifying client vs server config

### ISSUE THREAD

**Issue by benmccann** [vitest-dev/vitest#6851]
### Clear and concise description of the problem

We want to test server-side code and client-side code that live in the same project, but have different file extensions. Different settings need to be passed to [`resolve.conditions`](https://vite.dev/config/shared-options#resolve-conditions) based on whether it's client vs server code. Right now we have to setup two different test suites with two different config files.

### Suggested solution

It would be nice if we could use a single config file. We could use Vite's conditional config (https://vite.dev/config/#conditional-config) and check the value of `isSsrBuild` in order to set the value of the `resolve.conditions` appropriately. Even better would be if vitest defaulted these appropriately.

We could invoke it with something like `vitest`/`vitest --ssr` just like we currently can do `vite build` or `vite build --ssr`

### Alternative

Vite 6 is introducing a new environments API: https://main.vitejs.dev/guide/api-environment. We could try to mirror this upcoming API to support running tests in client and server environments with the appropriate `resolve.conditions`

### Additional context

We'd like to use this for newly created SvelteKit projects that are using vitest: https://github.com/sveltejs/cli/issues/270

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
If you need to specify several configs, use the [workspace](https://vitest.dev/guide/workspace.html) feature. It allows specifying any number of custom configs.
