### ISSUE TITLE
[Linux] cannot terminate running test with await

### ISSUE THREAD

**Issue by mskonovalov** [vitest-dev/vitest#6886]
### Describe the bug

On Linux if I run a test that contains some async/await code, it cannot be stopped rather than with `kill -9`.

### Reproduction

```
describe('aaa', () => {
  it('should work', async () => {
    while (true) {
      logger.info('123123');
      await new Promise(resolve => setTimeout(resolve, 1000));
    }
  });
});
```

if I remove the timeout, all works just fine.
**ALSO `--pool=threads` works fine as well.**

https://github.com/user-attachments/assets/3df1bdae-d7d2-4451-b7ec-21e63f00392e

### System Info

```shell
"vitest": "2.1.1"
Ubuntu 20.04
Node 20.17
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mskonovalov** [comment]
I can confirm this is solely vitest issue as if I run the same code as a node script, it stops absolutely fine.

**Comment by hi-ogawa** [comment]
I couldn't reproduce with your code on my Linux PC. Just in case, can you provide a repro as git repo?
