### ISSUE TITLE
vite-node: Support interactive console (REPL)

### ISSUE THREAD

**Issue by rChaoz** [vitest-dev/vitest#6919]
### Clear and concise description of the problem

I like to test part of my code in the Node interactive console, i.e. [REPL](https://nodejs.org/api/repl.html):

```shell
$ node
> const { myFunc } = await import("$lib/my/file")
> myFunc(123)
```

However, this of course does not work because it doesn't resolve stuff (like the "$lib" alias, virtual modules etc.). For this, I use `vite-node`. But currently this only works with files - I have to create a file, run it with `vite-node`, repeat.

### Suggested solution

Allow running `vite-node` without arguments to enter interactive mode (REPL).

### Alternative

Keep using files instead.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
This is probably doable. I wonder if there's any tools already doing this. I have a prototype based on Vite 6's module runner in https://github.com/hi-ogawa/vite-environment-examples/tree/main/examples/browser-cli.

To make it work like node's repl, we'll need more proper transforms to handle declarations `let, const` and also add `return` to the last expression statement. I just found Node does something like this https://github.com/nodejs/node/blob/746b17e1a5a9d09294b4c993a0319be6e5c39837/lib/repl.js#L432

**Comment by hi-ogawa** [comment]
Team decided that we don't add a new feature on top of vite-node anymore as we plan to migrate to use a primitive from Vite core directly.  Repl-like feature can be implemented on top of Vite ssr/module runner level, so I'll experiment with that instead.

Thanks for the idea, but closing this issue for now.
