### ISSUE TITLE
Vitest cannot handle windows path separators as runner argument

### ISSUE THREAD

**Issue by alfeg** [vitest-dev/vitest#693]
### Describe the bug

According to documentation, it should be possible to debug with VSCode: https://vitest.dev/guide/debugging.html

In Windows VSCode supply path with widows style path separators. This causes Vite to not found any files:

```
PS > npm run test -- src\windows.ts
...
No test files found
```

### Reproduction

Any Vitest sample/example experience this issue under Windows OS in an attempt to debug test as described at  https://vitest.dev/guide/debugging.html

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 36.67 GB / 63.94 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 97.0.4692.99
    Edge: Spartan (44.22000.120.0), Chromium (98.0.1108.43)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @vitejs/plugin-vue: ^2.0.1 => 2.1.0
    vite: ^2.7.12 => 2.7.13
    vitest: ^0.2.7 => 0.2.7
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alfeg** [comment]
My current workaround is following:
I have a `vitest.debug.mjs` file in root of project:
```javascript
const last = process.argv.length - 1
process.argv[last] = process.argv[last].replaceAll("\\", "/")
import("vitest/dist/cli.js")
```

in `launch.json`
```json
 {
      "type": "pwa-node",
      "request": "launch",
      "name": "Debug Current Test File",
      "autoAttachChildProcesses": true,
      "cwd": "${workspaceFolder}",
      "skipFiles": [
        "<node_internals>/**",
        "**/node_modules/**"
      ],
      "program": "${workspaceRoot}/debug.vitest.mjs",
      "args": [
        "run",
        "${relativeFile}"
      ],
      "smartStep": true,
      "console": "integratedTerminal"
    }
```

**Comment by sheremet-va** [comment]
Does this work anywhere else? Node returns `\` as escaped in `process.argv`, so not sure what we can do? You need to escape them somehow.

**Comment by sheremet-va** [comment]
As far as I'm concered this should work on Windows: https://github.com/microsoft/vscode/issues/40256

**Comment by ciddan** [comment]
> As far as I'm concered this should work on Windows: [microsoft/vscode#40256](https://github.com/microsoft/vscode/issues/40256)

I've been digging a bit, and [this line](https://github.com/vitest-dev/vitest/blob/3eec387db647db3c03a333ab2513a251571c0bb8/packages/vitest/src/node/core.ts#L411) seems to be the offender.

In my simple project this is the state of that function:

![Screenshot 2022-03-16 010646](https://user-images.githubusercontent.com/1786344/158491951-6843eb16-5f11-4384-bd91-6b45c9f28fe9.png)

This is the command line:
```
c:; cd 'c:\Development\libs\http-client'; ${env:NODE_OPTIONS}='--require "c:/Users/cidda/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" --inspect-publish-uid=http'; ${env:VSCODE_INSPECTOR_OPTIONS}='{"inspectorIpc":"\\\\.\\pipe\\node-cdp.55792-6.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Program Files\\nodejs\\node.exe","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"C:\\Users\\cidda\\AppData\\Local\\Temp\\node-debug-callback-88e6de9ef8c17ff3"}'; & 'C:\Program Files\nodejs\node.exe' '.\node_modules\vitest\vitest.mjs' 'run' 'src\lib\HttpClient.spec.ts'
```

---

Running the following command line works as expected:

```
c:; cd 'c:\Development\libs\http-client'; ${env:NODE_OPTIONS}='--require "c:/Users/cidda/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" --inspect-publish-uid=http'; ${env:VSCODE_INSPECTOR_OPTIONS}='{"inspectorIpc":"\\\\.\\pipe\\node-cdp.55792-6.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Program Files\\nodejs\\node.exe","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"C:\\Users\\cidda\\AppData\\Local\\Temp\\node-debug-callback-88e6de9ef8c17ff3"}'; & 'C:\Program Files\nodejs\node.exe' '.\node_modules\vitest\vitest.mjs' 'run' 'src/lib/HttpClient.spec.ts'
```

The only difference between the two is the slashes in the file filter.

**Comment by jimwe** [comment]
Did this get picked up in 0.6.3? I'm still seeing this on Windows:
```
 DEV  v0.6.3 C:/builds/test-app/client
No test files found
```

**Comment by zaabta** [comment]
import { fileURLToPath } from "url";
import { configDefaults, defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    globals: true,
    exclude: [...configDefaults.exclude, "**/playwright/**"],
    alias: {
      "~/": fileURLToPath(new URL("./src/", import.meta.url)),
    },
  },
});
