### ISSUE TITLE
Add msw and Vitest globalSetup default/conventional paths to coverage exclude defaults

### ISSUE THREAD

**Issue by astorije** [vitest-dev/vitest#6947]
### Clear and concise description of the problem

It is not uncommon to use [msw](https://mswjs.io/) and Vitest/Jest together (for good reasons, Vitest and msw are both ❤️). Would you be open to excluding `**/mockServiceWorker.js` from the [default coverage files](https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/defaults.ts#L30-L48)?

Same question about: `globalSetup: "./vitest.globalSetup.ts"`, would `**/vitest.globalSetup.(c|m)[jt]s` be a good default to include?

### Suggested solution

I am happy to open a PR / PRs to add those if you think this is a reasonable addition.

### Alternative

A the moment, we are excluding these with:

```ts
exclude: [
  ...coverageConfigDefaults.exclude,
  "public/mockServiceWorker.js",
  "vitest.globalSetup.ts",
],
```

which of course is absolutely fine, but I wanted to check with y'all if this is something that would be beneficial to the community :)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
Hey @astorije - I understand your point but unfortunately we are not accepting new values into `coverage.exclude`. See https://github.com/vitest-dev/vitest/issues/6956 for reasoning.

**Comment by Karthik0521** [comment]
Yes
________________________________
