### ISSUE TITLE
Undici MockAgent cannot intercept fetch request anymore

### ISSUE THREAD

**Issue by Guymestef** [vitest-dev/vitest#6952]
### Describe the bug

Since the version 2.1.5, we cannot mock anymore our http calls with undici MockAgent due to the bug fix:
vitest:
Use fetch() implementation from happy-dom  -  by @capricorn86 in https://github.com/vitest-dev/vitest/pull/6879 [(3c56f)](https://github.com/vitest-dev/vitest/commit/3c56feb4)

### Reproduction

```typescript
import { MockAgent, setGlobalDispatcher } from 'undici';

describe('Test mock fetch with undici', () => {
    it('should success', async () => {
       
       const mockAgent = new MockAgent();
       mockAgent.disableNetConnect();
       setGlobalDispatcher(mockAgent);

        const apiMockPool = mockAgent.get('https://localhost');

       apiMockPool
         .intercept({ method: 'GET', path: '/api/v1/test' })
         .reply(200, { success: true })
         .persist();

       const result = await fetch('https://localhost/api/v1/test');
       expect(result).toBeDefined();
    });

```

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 16.25 GB / 31.71 GB
  Binaries:
    Node: 23.2.0 - ~\bin\node-v23.2.0-win-x64\node.EXE
    Yarn: 4.5.0 - ~\bin\node-v23.2.0-win-x64\yarn.CMD
    npm: 10.9.0 - ~\bin\node-v23.2.0-win-x64\npm.CMD
  Browsers:
    Edge: Chromium (128.0.2739.67)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @vitejs/plugin-react: ~4.3.3 => 4.3.3
    @vitest/coverage-v8: ~2.1.5 => 2.1.5
    vite: ~5.4.11 => 5.4.11
    vitest: ~2.1.5 => 2.1.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
As this looks more like a feature of happy-dom, can you open an issue there?

On Vitest, you can probably try overwriting fetch (and other) globals back to undici by following

```js
import { fetch } from "undici"
globalThis.fetch = fetch;
```

**Comment by Karthik0521** [comment]
Oh ok I'm scared no money go in where okok
________________________________
