### ISSUE TITLE
No indicator for skipped test cases on 2.2.0 reporter

### ISSUE THREAD

**Issue by hi-ogawa** [vitest-dev/vitest#6964]
### Describe the bug

- 2.1.5 https://stackblitz.com/edit/vitest-dev-vitest-fuycoy?file=test%2Fbasic.test.ts

```
 DEV  v2.1.5 /home/projects/vitest-dev-vitest-fuycoy
      UI started at http://localhost:51204/__vitest__/

 ✓ test/basic.test.ts (3)
   ✓ Math.sqrt()
   ↓ Squared [skipped] 
   ✓ JSON
```

- 2.2.0-beta.2 https://stackblitz.com/edit/vitest-dev-vitest-nfatqs?file=test%2Fbasic.test.ts

```
 DEV  v2.2.0-beta.2 /home/projects/vitest-dev-vitest-fuycoy
      UI started at http://localhost:51204/__vitest__/

 ✓ test/basic.test.ts (3 tests | 1 skipped) 2ms
   ✓ Math.sqrt()
   ✓ Squared
   ✓ JSON
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-nfatqs?file=test%2Fbasic.test.ts

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @vitest/ui: 2.2.0-beta.2 => 2.2.0-beta.2 
    vite: latest => 5.4.11 
    vitest: 2.2.0-beta.2 => 2.2.0-beta.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
Does latest `main` fix this? `https://pkg.pr.new/vitest@main`

- https://github.com/vitest-dev/vitest/pull/6932/commits/d562da0b5402cf460d28c6d3dd816c9e56a52efe

**Comment by hi-ogawa** [comment]
Ah, I didn't see the commit there. I was testing on top of main but just one commit before that PR.

It's looking good after rebase :+1: 

```
 DEV  v2.2.0-beta.2 /home/hiroshi/code/others/vitest/test/attest/fixtures

⏳ Waiting for TypeScript to check your project (this may take a while)...
 ✓ test/snapshot.test.ts (4 tests | 3 skipped) 13ms
   ✓ inline snapshot
   ↓ file snapshot
   ↓ type error
   ↓ completions
```
