### ISSUE TITLE
Property 'element' does not exist on type 'ExpectStatic'

### ISSUE THREAD

**Issue by Pinakin-Desai-HBK** [vitest-dev/vitest#6965]
### Describe the bug

Installed the latest vitest (2.1.5) but getting the following error - Property 'element' does not exist on type 'ExpectStatic'.

This was reported previously but seemed to have been fixed - https://github.com/vitest-dev/vitest/issues/4273

Test:
![image](https://github.com/user-attachments/assets/0c59f6e0-5757-4061-96ca-f7360e32c610)

package.json:
![image](https://github.com/user-attachments/assets/e123e2bd-ed39-4d19-96bd-d4dd6a0eb6b0)

vitest:
![image](https://github.com/user-attachments/assets/7f7a6402-e4be-482d-83dd-ecad06ee7148)

### Reproduction

Install the latest vitest and try to access the element property of expect.

### System Info

```shell
vitest 2.1.5
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Pinakin-Desai-HBK** [comment]
Here is an example - https://stackblitz.com/edit/vitejs-vite-vnkaxo?file=package.json,src%2Fassets%2FApp.test.tsx&terminal=dev

**Comment by kossnocorp** [comment]
Importing the `matchers.d.ts` directly in the test file helps, but it would be great to have a fix:

```ts
import "@vitest/browser/matchers.d.ts";

// Your tests...
```

**Comment by hi-ogawa** [comment]
Adding manually dts is necessary since `expect.element` is only available on browser mode. Closing as this is in the doc https://vitest.dev/guide/browser/assertion-api.html and we'll soon improve it better https://github.com/vitest-dev/vitest/pull/6934/

**Comment by Smrtnyk** [comment]
@hi-ogawa 
I am not a typescript expert, but just an idea.
Would it be possible to have a special `expect` that could be imported from `@vitest/browser` that would already have this automatically typed?

**Comment by kossnocorp** [comment]
I think it would be safe to include both the type and the dummy matcher that would throw an error if it's not the browser environment in the global expect, or, as suggested, have a separate browser expect/browserExpect. It will be great for discoverability and improve the DX.

**Comment by hi-ogawa** [comment]
> I think it would be safe to include both the type and the dummy matcher that would throw an error if it's not the browser environment in the global expect

Yeah, that might work, but I guess there are a few concerns:
- `@vitest/browser/matchers` might pollute too much (e.g. IDE auto-completion) as it includes jest-dom assertions too
- there's still provider specific extension for `@vitest/browser/matchers/providers/xxx`

**Comment by Pinakin-Desai-HBK** [comment]
> Adding manually dts is necessary since `expect.element` is only available on browser mode. Closing as this is in the doc https://vitest.dev/guide/browser/assertion-api.html and we'll soon improve it better #6934

I added the following but still have the issue:
`{
  "compilerOptions": {
    "types": [
      "@vitest/browser/providers/playwright"
    ]
  }
}`

I also see this error in tsconfig:

> Cannot find type definition file for '@vitest/browser/providers/playwright'.

**Comment by Pinakin-Desai-HBK** [comment]
> ```ts
> import "@vitest/browser/matchers.d.ts";
> ```

Thanks. This works too:

```ts
import "@vitest/browser/matchers";
```

**Comment by hi-ogawa** [comment]
> I don't see where it says to add it manually in that link.

@Pinakin-Desai-HBK I'm referring to the first paragraph in the doc. There are actually many ways to help tsc and the doc mentions that `compilerOptions.options` in `tsconfig.json`:

> If you are using TypeScript or want to have correct type hints in expect, make sure you have either @vitest/browser/providers/playwright or @vitest/browser/providers/webdriverio specified in your tsconfig depending on the provider you use. If you use the default preview provider, you can specify @vitest/browser/matchers instead.
