### ISSUE TITLE
Using .mjs files causes "Error: Vitest was initialised with native Node instead of Vite Node"

### ISSUE THREAD

**Issue by zth** [vitest-dev/vitest#697]
### Describe the bug

(this is solved, leaving this issue here for anyone else running into the same problem)

When tests have the `.mjs` extension, or tests import files explicitly with the `.mjs` extension, all tests would fail and I'd get a message saying: `Error: Vitest was initialised with native Node instead of Vite Node`.

Got help on the Discord, and the solution was to add this config:
```
export default defineConfig({
  test: {
    deps: {
      inline: [/(.*)\.mjs$/],
    },
  },
```

That solved the issue for me.

### Reproduction

-

### System Info

```shell
-
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zth** [comment]
Closing this immediately since it's already solved.

**Comment by sheremet-va** [comment]
I just want to point out that this RegExp will inline every `.mjs` file, including inside `node_modules`, so it is better to came up with a RegExp that covers only your source folder. Usually, `src`.
