### ISSUE TITLE
Browser Mode: Allow extended configuration of provider

### ISSUE THREAD

**Issue by JoaoCnh** [vitest-dev/vitest#6983]
### Clear and concise description of the problem

Running test suites in CI is quite different from running them on a local machine. CI is quite often slower and locators take more than the default 1000ms to locate elements or to perform actions (click, hover, etc).

It's possible to define a specific timeout for an `expect` or a `locator.click` for example but it would be nice to be able to set larger timeouts at a config level for when the tests run in CI.

### Suggested solution

add new properties in the `browser` config for the following:

- actionTimeout - optional and number
- expectTimeout - optional and number

This would under the hood configure the correct provider configurations if possible.

[Here's doc ref to Playwright test configuration](https://playwright.dev/docs/api/class-testoptions#test-options-action-timeout)

### Alternative

Allow full customisation of test configuration. 
Right now we're allowed to extend launch options and browser context options on playwright for example but we could extend this configuration to [Test Options](https://playwright.dev/docs/api/class-testoptions)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
I don't think `expectTimeout` would apply to Vitest? I would assume that's their async assertion's timeout, so for us, that would be probably `expect.element(() => ...)`, which can be configured by `expect.poll.timeout`.

**Comment by hi-ogawa** [comment]
I think `actionTimeout` is only anomaly for playwright since it's probably more like test runner concern than pure browser driver, so  they didn't include it in their `BrowserContextOptions`.

@JoaoCnh  Do you see anything missing for Vitest's provider options other than `actionTimeout`?

**Comment by JoaoCnh** [comment]
Hey, at the moment the only thing other than `actionTimeout` that I encountered was the ability to activate playwright tracing for debugging purposes in CI. But not sure what are the plans for Vitest regarding that in the future.

**Comment by hi-ogawa** [comment]
Indeed, https://playwright.dev/docs/api/class-testoptions#test-options-trace looks like another diff between https://playwright.dev/docs/api/class-testoptions and https://playwright.dev/docs/api/class-browser#browser-new-context
