### ISSUE TITLE
Allow specifiying an epsilon or precision for matching numbers

### ISSUE THREAD

**Issue by hfhchan-plb** [vitest-dev/vitest#6997]
### Clear and concise description of the problem

Allow specifying a precision or epsilon for matching numbers.

Floating point math is inherently not precise, and standard practice is to compare them based on some epsilon or a specific precision. 

### Suggested solution

.toMatchObject() may provide an additional param e.g. `{ epsilon: 1e-10 }` which would compare the difference between two numbers against the epsilon, or `{ precision: 10 }` which would call `.toPrecision(10)` on all numbers before comparison.

### Alternative

Epsilon: a custom `.toMatchObject()` can be implemented by the user, but would need to significantly duplicate the logic in `toMatchObject()`.
Precision: this can be done by the user recursively before passing the object into `toMatchObject()`.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hi-ogawa** [comment]
Can you explain more concrete use cases and what kind of tests you are writing? Seeing a concrete code (before and after with your suggested API) would help understand the issue better.

**Comment by hi-ogawa** [comment]
Depending on the context, you may try equality tester https://vitest.dev/api/expect.html#expect-addequalitytesters to make all number comparison to be imprecise.

https://stackblitz.com/edit/vitest-dev-vitest-yhzoqr?file=test%2Frepro.test.ts

```ts
import { test, expect } from 'vitest';

expect.addEqualityTesters([
  (a: unknown, b: unknown): boolean | undefined => {
    if (typeof a === 'number' && typeof b === 'number') {
      return Math.abs(a - b) < 0.1;
    }
    return (typeof a === 'number') !== (typeof b === 'number') || undefined;
  },
]);

test('repro', () => {
  expect(1).toEqual(1);
  expect(1).toEqual(1.05);
  expect(1).not.toEqual(1.2);
  expect(1).not.toEqual(2);
});
```

**Comment by sheremet-va** [comment]
I think a custom equality tester is the solution here. I don't see the usefulness of this feature in core.
