### ISSUE TITLE
Interactivity API: `shiftKey` not pressed in pointer events, when `keyboard('{Shift>}')` is active

### ISSUE THREAD

**Issue by gossi** [vitest-dev/vitest#7007]
### Describe the bug

Happy to switch to the new interactivity API (my code predates that API).

I'm doing a multi-select for a composite aria widget, so when holding down shift key and click an item, it will be selected.

Here is my idea to write the test code, as suggested at [testing-library](https://testing-library.com/docs/user-event/setup#starting-a-session-per-setup):

```ts
const user = userEvent.setup();
await user.keyboard('{Shift>}');
await user.click(thirdItem);
await user.keyboard('{/Shift}');
```

my code registers a `pointerup` event, which has this check:

```ts
handlePointer(event: PointerEvent, item: Item) {
  if (event.shiftKey) {
    this.selectShift(item);
  }

  // ...
}
```

but when logging the "click" event, the `shiftKey` property is set to `false`.

### Reproduction

Currently working on a public PR:

- https://github.com/hokulea/aria-voyager/pull/258
- [Tree 09cb308](https://github.com/hokulea/aria-voyager/tree/09cb30831b68127b0c3aca791636d1821954ead7)

Code:

- [Failing test](https://github.com/hokulea/aria-voyager/blob/09cb30831b68127b0c3aca791636d1821954ead7/packages/aria-voyager/tests/listbox/navigation/focus/with-multi-selection.test.ts#L13-L31)
- [Code](https://github.com/hokulea/aria-voyager/blob/09cb30831b68127b0c3aca791636d1821954ead7/packages/aria-voyager/src/navigation-patterns/selection-strategy.ts#L96-L108)

you might wanna put a `console.log()`/breakpoint at that function.

Setup:

- checkout repo above
- `pnpm install`
- `cd packages/aria-voyager`
- `pnpm test:ui`
- failing test is `tests/listbox/navigation/focus/with-multi-selection.test.ts`

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (11) arm64 Apple M3 Pro
    Memory: 67.67 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.10.0 - ~/.local/share/mise/installs/node/22/bin/node
    npm: 10.9.0 - ~/.local/share/mise/installs/node/22/bin/npm
    pnpm: 9.13.2 - ~/.local/share/mise/installs/node/22/bin/pnpm
    Watchman: 2024.07.08.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 103.1.41.100
    Chrome: 131.0.6778.86
    Edge: 124.0.2478.51
    Safari: 17.5
  npmPackages:
    @vitest/browser: ^2.1.8 => 2.1.8
    @vitest/coverage-istanbul: ^2.1.8 => 2.1.8
    @vitest/ui: ^2.1.8 => 2.1.8
    vite: 5.4.11 => 5.4.11
    vitest: ^2.1.8 => 2.1.8
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
It looks like you are using `provider: "preview"` and that mostly uses testing-library's event emulation inside js under the hood, so the issue might be there.

Can you try `provider: "playwright"` and see if it works? Also would be great to have a minimal repro as it's hard to get into the entire repository.

**Comment by gossi** [comment]
Thanks for the response. I did a quick check for three providers:

- preview: not working
- webdriverio: not working (error is some selector is wrong)
- playwright: actually works

I'm using wdio for CI and preview for development mode.

I will work on a smaller repro case.

**Comment by gossi** [comment]
I made a minimal repro case over here: https://github.com/gossi/repro-vitest-interactivity-api

It only happens for `preview` provider, I added tests for wdio and playwright.

I checked for `{Shift>}` key in particular, but that is an indicator, that control, option and meta key might also be affected.

**Comment by sheremet-va** [comment]
> I made a minimal repro case over here: [gossi/repro-vitest-interactivity-api](https://github.com/gossi/repro-vitest-interactivity-api)
> 
> It only happens for `preview` provider, I added tests for wdio and playwright.
> 
> I checked for `{Shift>}` key in particular, but that is an indicator, that control, option and meta key might also be affected.

The global `userEvent` uses locators under the hood, and the preview locator always uses the global `userEvent` from testing-library:

https://github.com/vitest-dev/vitest/blob/a11d565422e7b6ca9557b686b5a9d299d5e726ba/packages/browser/src/client/tester/locators/preview.ts#L61

This is a bug
