### ISSUE TITLE
Support for `vite@6` async plugins

### ISSUE THREAD

**Issue by manuel3108** [vitest-dev/vitest#7014]
### Describe the bug

Using `@sveltejs/kit@2.9.0` and `vitest@2.1.8` makes tsc fail with the following `vite.config.ts`

```js
import { defineConfig } from 'vitest/config';
import { sveltekit } from '@sveltejs/kit/vite';

export default defineConfig({
    plugins: [sveltekit()],
});
```

Problem was first reported in https://github.com/sveltejs/cli/issues/341. While a user is adding `vitest` to his project, we are switching out the imports inside `vite.config.ts` like this:

```js
// without vitest
import { defineConfig } from 'vite';

// with vitest
import { defineConfig } from "vitest/config";
```

This is likely caused by `vite@6` allowing plugins of type `Promise<whatever>`. Looks like this change was not backported to config used by `vitest`

### Reproduction

https://stackblitz.com/edit/node-zjetgl?file=vite.config.ts

Wait for `npm i` to complete. Run `npm run check`. The issue will appear. IntelliSense also complains

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    vite: ^6.0.0 => 6.0.2 
    vitest: ^2.1.8 => 2.1.8
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by niemyjski** [comment]
2.1.7 broke npm run check for us: 


```
import { sveltekit } from '@sveltejs/kit/vite';
import Icons from 'unplugin-icons/vite';
import { defineConfig } from 'vitest/config';

const aspNetConfig = getAspNetConfig();

export default defineConfig({
    build: {
        sourcemap: true,
        target: 'esnext'
    },
    plugins: [
        sveltekit(),
        Icons({
            compiler: 'svelte'
        })
    ],
```

```
Exceptionless\src\Exceptionless.Web\ClientApp\vite.config.ts:14:9
Error: No overload matches this call.
  The last overload gave the following error.
    Type 'Promise<Plugin<any>[]>' is not assignable to type 'PluginOption'.
      Type 'Promise<Plugin<any>[]>' is not assignable to type 'Promise<false | Plugin<any> | PluginOption[] | null | undefined>'.
        Type 'Plugin<any>[]' is not assignable to type 'false | Plugin<any> | PluginOption[] | null | undefined'.
          Type 'Plugin<any>[]' is not assignable to type 'PluginOption[]'.
            Type 'Plugin<any>' is not assignable to type 'PluginOption'.
```

**Comment by sheremet-va** [comment]
Vitest 2 doesn't support Vite 6 and will not support Vite 6 officially. You can use `resolutions` or `pnpm.overrides` to change the version range locally, Vite 6 API is the same and should work for Vitest 2.

If you migrated to Vite 6, use Vitest 3 (currently in beta), release is planned for January.

If you see any type errors in your config, check the lockfile to confirm that you have several Vite versions installed and resolve it with your package manager.
