### ISSUE TITLE
Stack trace line numbers incorrect using vite-node on Windows

### ISSUE THREAD

**Issue by rmuchall** [vitest-dev/vitest#7021]
### Describe the bug

Stack trace line numbers are incorrect when using vite-node on Windows.
Using the following dependency versions:
"vite": "5.4.11",
"vite-node": "2.1.8",
"vitest": "2.1.8"

### Reproduction

https://github.com/rmuchall/vite-node-bug

### System Info

```shell
System:
    OS: Windows 11 10.0.26100
    CPU: (2) x64 Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz
    Memory: 698.26 MB / 8.00 GB
  Binaries:
    Node: 22.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (129.0.2792.65)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rmuchall** [comment]
In the minimal reproduction repo. The stack trace should be line 15 but is instead showing as line 10.

**Comment by hi-ogawa** [comment]
This might be fixed recently (but not released) https://github.com/vitest-dev/vitest/pull/6786
Can you try pkg.pr.new https://vitest.dev/guide/#using-unreleased-commits?

**Comment by rmuchall** [comment]
Many thanks for your super fast response.
I can confirm that using the fix from https://pkg.pr.new/vite-node@main successfully resolves this issue.
Line numbers are working correctly again. Thank you!

**Comment by AriPerkkio** [comment]
Fixed by https://github.com/vitest-dev/vitest/pull/6786.
