### ISSUE TITLE
Stubbing `Intl` makes `vi.useFakeTimer` crashing

### ISSUE THREAD

**Issue by dubzzz** [vitest-dev/vitest#7024]
### Describe the bug

When stubbing the global `Intl` and replacing it by a partial copy of it, as follow:

```js
import { test, vi } from "vitest";

const UntouchedIntl = Intl;
test("My test (not working #2)", () => {
  vi.stubGlobal("Intl", { ...UntouchedIntl });
  vi.useFakeTimers();
});
```

We make `vi.useFakeTimer` resulting into the error:

```txt
TypeError: Cannot read properties of undefined (reading 'prototype')
```

**EDITED:** After my first steps of investigations, I'd say that if there is a bug on your side, it's limited to the fact that timers rely on potentially altered instances of `Intl` (and also others). If it's done on purpose just close my issue as the problem is mostly user side (see my suggestions of fixes on userland at https://github.com/vitest-dev/vitest/issues/7024#issuecomment-2519762650).

### Reproduction

I put multiple reproductions in the repository: https://github.com/dubzzz/bug-vitest-intl. By iterating over my initial test case that was aiming into stubbing `Intl.NumberFormat` to make sure it always relies on the US local, I reached several sub-cases with some working and others not working.

Something pretty interesting is that the stub is only causing troubles if done before the call to `vi.useFakeTimer`.

This one crashes:

```js
import { test, vi } from "vitest";

const UntouchedIntl = Intl;
test("My test (not working #2)", () => {
  vi.stubGlobal("Intl", { ...UntouchedIntl });
  vi.useFakeTimers();
});
```

This one does not crash:

```js
import { test, vi } from "vitest";

const UntouchedIntl = Intl;
test("My test (working #1)", () => {
  vi.useFakeTimers();
  vi.stubGlobal("Intl", { ...UntouchedIntl });
});
```

This one does not crash:

```js
import { test, vi } from "vitest";

const UntouchedIntl = Intl;
test("My test (working #2)", () => {
  vi.stubGlobal("Intl", UntouchedIntl);
  vi.useFakeTimers();
});
```

_Please note that my initial attempt (I'm gonna add it into the repo too) was only trying to spy on `Intl.NumberFormat` but it actually made the produced formatters fail when called on `format` in some cases. But so far I've not been able to restrict this case to something smaller that I can share._

### System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 5.49 GB / 7.74 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.17.0 - ~/nvm/current/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.8.2 - ~/nvm/current/bin/npm
    pnpm: 9.11.0 - ~/nvm/current/bin/pnpm
  npmPackages:
    vitest: ^2.1.8 => 2.1.8
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dubzzz** [comment]
The crash seems to happen here:

```js
	        ClockIntl.DateTimeFormat.prototype = Object.create(
	            NativeIntl.DateTimeFormat.prototype // undefined
	        );
```

**Comment by dubzzz** [comment]
What do you think about the idea of making sure that we use the untouched global and not one that may have been touched before we access it? We could rewrite `SafeIntl` that way `const SafeIntl = typeof Intl !== 'undefined' ? Intl : undefined` and then only rely on this instance.

**Comment by dubzzz** [comment]
In case other people face the same issue in the future, I have two working workarounds.

<details>
<summary>Option 1</summary>

We just make the stub a little bit more complex but we only rely on the primitives offered by Vitest.

```js
import { test, vi } from "vitest";

const UntouchedIntl = Intl;
const UntouchedIntlDescriptors = Object.getOwnPropertyDescriptors(Intl);

test("My test (working #4)", () => {
  const defaultLocale = "en-US";
  const NewIntl = {};
  Object.defineProperties(NewIntl, {
    ...UntouchedIntlDescriptors,
    NumberFormat: {
      ...UntouchedIntlDescriptors.NumberFormat,
      value: class extends UntouchedIntl.NumberFormat {
        constructor(...args) {
          if (args.length < 1) {
            super(defaultLocale);
          } else {
            const [locales, ...otherParams] = args;
            if (
              typeof locales === "string" ||
              (Array.isArray(locales) && locales.length !== 0)
            ) {
              super(...args);
            } else {
              super(defaultLocale, ...otherParams);
            }
          }
        }
      },
    },
  });
  vi.stubGlobal("Intl", NewIntl);
  vi.useFakeTimers();
});
```
</details>

<details>
<summary>Option 2</summary>

We bypass Vitest and pollute the prototype in a global way.

```js
// in vitest.setup.js

const defaultLocale = "en-US";
Intl.NumberFormat = class extends Intl.NumberFormat {
  constructor(...args) {
    if (args.length < 1) {
      super(defaultLocale);
    } else {
      const [locales, ...otherParams] = args;
      if (
        typeof locales === "string" ||
        (Array.isArray(locales) && locales.length !== 0)
      ) {
        super(...args);
      } else {
        super(defaultLocale, ...otherParams);
      }
    }
  }
};
```
</details>

**Comment by sheremet-va** [comment]
> What do you think about the idea of making sure that we use the untouched global and not one that may have been touched before we access it? We could rewrite `SafeIntl` that way `const SafeIntl = typeof Intl !== 'undefined' ? Intl : undefined` and then only rely on this instance.
> 
> If acceptable I can work on providing such fix, if you are ok with the idea.

I think if anything, this should be done on sinon side. I don't think this is an issue with Vitest, the `stubGlobal` just does this internally:

```ts
globalThis[key] = value
```
