### ISSUE TITLE
Multiple async describe causes some test to not be run.

### ISSUE THREAD

**Issue by MonsieurMan** [vitest-dev/vitest#703]
### Describe the bug

The bug is quite strange, when using multiple nested async describe, some test can be skipped for no apparent reason. 

As pointed out in the repro comments, commenting some describes make the previously skipped test to run.

There is no part of the form to do it, so, thank you guys a lot, that is amazing work you are doing here! 🚀 

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-trh7ej?file=test/suite.test.ts

I isolated a minimal repro with only three describe and an async function using a timeout.

### System Info

```shell
See provided StackBlitz.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Demivan** [comment]
Is this supported by Jest? I only see one closed merge request in Jest saying that they will not support it.

You can use async `beforeAll` and `beforeEach` in `describe` and don't mark `describe` as async.

**Comment by sheremet-va** [comment]
> Is this supported by Jest? I only see one closed merge request in Jest saying that they will not support it.
> 
> You can use async `beforeAll` and `beforeEach` in `describe` and don't mark `describe` as async.

Agree, describe should not be async.

**Comment by MonsieurMan** [comment]
@Demivan, it makes sense. In this case, shouldn't the type `SuiteFactory` here : https://github.com/vitest-dev/vitest/blob/735e5074fe333053b0ba53e8860372054e5b6b99/packages/vitest/src/types/tasks.ts#L81
be changed to not accept asynchronous functions?

**Comment by MonsieurMan** [comment]
To sum up for everyone. @antfu, if I understand #750 correctly, async `describe` will be supported? 🚀
