### ISSUE TITLE
CLI documentation for --pool option is incorrect for default value

### ISSUE THREAD

**Issue by austinhnelson** [vitest-dev/vitest#7035]
### Describe the bug

The description for the --pool option in the cli documentation is not correct for the default value. The default value used to be threads but was updated to forks in 2.0: https://vitest.dev/guide/migration.html 

### Reproduction

https://vitest.dev/guide/cli.html#pool 

### System Info

```shell
Standard browser
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AriPerkkio** [comment]
PR welcome:

https://github.com/vitest-dev/vitest/blob/d93989e81f5ac202c871e1e68e4abcb0b29e05bf/docs/guide/cli-generated.md?plain=1#L393-L398
