### ISSUE TITLE
Could not specify coverage provider per config

### ISSUE THREAD

**Issue by unional** [vitest-dev/vitest#7037]
### Describe the bug

In workspace, the `coverage` is specified in a common `vitest.config.ts` and not in individual config.
This prevents plugin authors to create configs that uses different providers.

For example:

```sh
vitest.config.ts
vitest.config.playwright.ts
vitest.config.webdriverio.ts
vitest.workspace.ts
```

```ts
// vitest.workspace.ts
export default [
  'vitest.config.playwright.ts',
  'vitest.config.webdriverio.ts'
]
```
`playwright` uses `coverage-v8` while `webdriverio` uses `istanbul`.
This scenario doesn't work at all when running `vitest run --coverage`.

It fails with:

```sh
Error: @vitest/coverage-v8 does not work with
{
  "browser": {
    "provider": "webdriverio",
    "name": "firefox"
  }
}
```

I've tried adding `test: { coverage: { provider: 'istanbul' } }` in `vitest.config.webdriverio.ts` and ignore the type error. But that has no effect.

### Reproduction

as described above

### System Info

```shell
System:
    OS: macOS 14.7.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 74.48 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.9.0 - ~/.local/state/fnm_multishells/36490_1733342322767/bin/node
    npm: 10.8.3 - ~/.local/state/fnm_multishells/36490_1733342322767/bin/npm
    pnpm: 9.13.2 - ~/.nvm/versions/node/v20.12.2/bin/pnpm
    bun: 0.1.6 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 131.1.73.91
    Chrome: 131.0.6778.87
    Safari: 18.1.1
  npmPackages:
    @vitejs/plugin-react: ^4.2.1 => 4.3.3 
    @vitest/browser: ^2.1.8 => 2.1.8 
    @vitest/coverage-istanbul: ^2.1.8 => 2.1.8 
    @vitest/expect: ^2.1.8 => 2.1.8 
    vite: ^5.3.5 => 5.4.11
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by unional** [comment]
This cannot repro on stackbliz as that fails with:

```sh
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Cannot find package '@vitest/browser' imported from /home/projects/vitest-dev-vitest-qbwddo/node_modules/vitest/dist/chunks/resolveConfig.RxKrDli4.js
 ❯ __node_internal_captureLargerStackTrace2 ../../../builtins.ddb8d84d.js:101:5335
 ❯ new NodeError ../../../builtins.ddb8d84d.js:101:4149
 ❯ packageResolve ../../../builtins.ddb8d84d.js:158:9724
 ❯ moduleResolve ../../../builtins.ddb8d84d.js:158:10188
 ❯ defaultResolve ../../../builtins.ddb8d84d.js:158:12372
```

**Comment by sheremet-va** [comment]
This is expected behavior. Coverage is done for the whole workspace, that's the whole point of having a workspace in the first place: https://vitest.dev/guide/workspace.html#configuration

**Comment by unional** [comment]
Yes, I understand that's what mentioned in the doc. But that makes it not possible to do what I described.

**Comment by sheremet-va** [comment]
> Yes, I understand that's what mentioned in the doc. But that makes it not possible to do what I described.

Yes, this use case is intentionally not supported and it is mentioned in the docs that it is intentionally not supported.

**Comment by unional** [comment]
ok, thanks for confirming.

**Comment by unional** [comment]
FYI I have tried for a few days but couldn't find a workable workaround

**Comment by sheremet-va** [comment]
There is no workaround. You can only have one coverage provider
