### ISSUE TITLE
Regression (0.2.8) - Only one test file is running other suites are skipped

### ISSUE THREAD

**Issue by arpowers** [vitest-dev/vitest#704]
### Describe the bug

After updating to version 0.2.8 only one out of the 3 test suites I have is running. The other two are skipped, (with no reason for them to actually be skipped)

Spent like 45 minutes trying to debug this before reverting to v0.2.7 which fixed the issue: 

![Screen Shot 2022-02-08 at 10 14 14 AM](https://user-images.githubusercontent.com/308134/153050222-2de4c45b-94db-43c5-a392-4a665d7024ea.jpg)

### Reproduction

#

### System Info

```shell
#
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by stygian-desolator** [comment]
Hi, Could you please provide a minimal reproduction? thanks.

**Comment by stygian-desolator** [comment]
Maybe it's the same problem as https://github.com/vitest-dev/vitest/issues/703

**Comment by arpowers** [comment]
@stygian-desolator  thanks this issue appears to have been fixed in one of the last releases.
