### ISSUE TITLE
cli: `vitest '**/*.integration.js'` does not behave as documented

### ISSUE THREAD

**Issue by mantoni** [vitest-dev/vitest#7045]
### Describe the bug

The [CLI documentation for "include"](https://vitest.dev/config/#include) states

> CLI: vitest [...include], vitest **/*.test.js
> A list of glob patterns that match your test files.

However, running `vitest '**/*.integration.js'` uses the pattern as a filter instead of an include:

```
> vitest --run '**/*.integration.js'

 RUN  v2.1.8 /Users/max/projects/...

filter:  **/*.integration.js
include: **/*.{test,spec}.?(c|m)[jt]s?(x)
exclude:  **/node_modules/**, **/dist/**, **/cypress/**, **/.{idea,git,cache,output,temp}/**, **/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*

No test files found, exiting with code 1
```

Setting a filter is documented as `-t`. There doesn't seem to be an explicit flag for overriding the default includes.

### Reproduction

```bash
npm init --yes
npm i vitest -D
npx vitest --run '**/*.integration.js'
```

Observe that the given pattern is shown as "filter" instead of "include".

### System Info

```shell
System:
    OS: macOS 15.1.1
    CPU: (8) arm64 Apple M1
    Memory: 269.09 MB / 16.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 22.12.0 - /opt/homebrew/bin/node
    npm: 10.9.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 131.0.6778.86
    Safari: 18.1.1
  npmPackages:
    vitest: ^2.1.8 => 2.1.8
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`vitest '**/*.integration.js'` is not what documentation says. Documentation shows `vitest **/*.integration.js`. The globbing should be done by your CLI

**Comment by mantoni** [comment]
Sorry for not the late reaction. It's still not working as advertised if I pass specific filenames, because it treats them as filters, not as includes.

```
❯ npx vitest --run test.integration.js

 RUN  v2.1.8 ...

filter:  test.integration.js
include: **/*.{test,spec}.?(c|m)[jt]s?(x)
exclude:  **/node_modules/**, **/dist/**, **/cypress/**, **/.{idea,git,cache,output,temp}/**, **/{karma,rollup,webpack,vite,vitest,jest,ava,babel,nyc,cypress,tsup,build,eslint,prettier}.config.*

No test files found, exiting with code 1
```

I can't fine any other way to change `include`.

**Comment by sheremet-va** [comment]
You cannot change `include` via a CLI, you can only filter included tests. Docs just mention the usage for people who are looking to filter tests
