### ISSUE TITLE
Absolute coverage thresholds

### ISSUE THREAD

**Issue by jonahkagan** [vitest-dev/vitest#7056]
### Clear and concise description of the problem

As a developer using Vitest, I want a way to specify absolute coverage thresholds instead of percentage coverage thresholds. The benefit of absolute thresholds is that you can freeze the code coverage at a specific number of uncovered lines, which then ensures that test coverage must be considered for any new additions to the code.

For example, let's say I start working on a package that has 1000 lines, 750 of which are covered (75% coverage), so I set the coverage threshold to 75% to "preserve" this amount of coverage. I then add a new feature with 10 lines, 8 of which are covered. The new coverage percentage is 75.05%, so I pass coverage. However, if only 7 lines of the new feature are covered, then the new coverage percentage is 74.95%, and I fail. This feels a bit arbitrary - I've only enforced that new code additions must have as good of coverage as the existing code.

With absolute coverage thresholds, I would specify my coverage threshold as "250 uncovered lines." When adding a new feature with 10 lines, all 10 lines must be covered (or marked to be ignored in coverage).

In my organization, our approach to code coverage is to strive for 100% coverage unless there's a reasonable tradeoff (e.g. a particular is too hard to reproduce in testing to make it worthwhile, in which case we explicitly mark that case to be ignored). This is easy to do for code that already has 100% coverage. But for any legacy code that doesn't, we can't really implement this policy very well without absolute coverage thresholds.

We are currently migrating from jest (which supports this feature) to vitest. We are loving vitest but are sad to lose this important piece of functionality.

### Suggested solution

Jest supports [configuring a coverage threshold](https://jestjs.io/docs/configuration#coveragethreshold-object) with a positive number, in which case its interpreted as a percentage, or a negative number, in which case its interpreted as an absolute threshold.

The advantage of this approach is that it doesn't add any new configuration options. The disadvantage is that it's not totally clear what's happening unless you read the docs.

I think it would also make sense to have a more explicit configuration option to use absolute or percentage thresholds in the coverage config. E.g. something like `coverage.thresholdType: 'percentage' | 'absolute'`.

I haven't yet looked into how to implement this in the code base, but I'd be happy to take the lead on researching and implementing the feature once its agreed that it would be a useful addition.

### Additional context

Thank you for your time and consideration!

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by AriPerkkio** [comment]
> The disadvantage is that it's not totally clear what's happening unless you read the docs.

I think this is the reason why Vitest doesn't support it. And also `nyc` and `c8` don't support it. But we can add it to Vitest just to be compatible with Jest. 

I think using the negative numbers is fine, but if you can come up with better API we could add that too. 

> I haven't yet looked into how to implement this in the code base, but I'd be happy to take the lead on researching and implementing the feature once its agreed that it would be a useful addition.

All coverage threholds related logic is in `packages/vitest/src/utils/coverage.ts`. Comparison is done here, though I think we need to consider negative numbers in `thresholds.autoUpdate` related logic too. The `summary.data[thresholdKey]` might hold info about uncovered lines already.

https://github.com/vitest-dev/vitest/blob/2fb585aea696c27c31fa8f64e0d00940516ecc1c/packages/vitest/src/utils/coverage.ts#L339-L391

Example test case:

https://github.com/vitest-dev/vitest/blob/2fb585aea696c27c31fa8f64e0d00940516ecc1c/test/coverage-test/test/threshold-failure.test.ts#L1-L33

**Comment by jonahkagan** [comment]
Thanks for the pointers @AriPerkkio - very helpful! I submitted a pull request here: https://github.com/vitest-dev/vitest/pull/7061.
