### ISSUE TITLE
Support for `define` global constants from vite.config

### ISSUE THREAD

**Issue by timleers** [vitest-dev/vitest#706]
### Clear and concise description of the problem

In our webapp we are using [vite's `define`](https://vitejs.dev/config/#define) for global constants. Unfortunately our tests using these constants are failing because the variables are not defined. Seems like vitest is ignoring everything included in the define context of the vite.config.js.

Do you plan to support that or did i miss something and its already working?

### Suggested solution

Parse 'define' part of the vite.config and provide items as constants.

### Alternative

Not use `define` in vite.config

### Additional context

if there is anything i can do to support this awesome project please let me know. I'm happy to contribute

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by stygian-desolator** [comment]
Could you please provide a reproduce demo ? I tried it and everything was fine.
https://stackblitz.com/edit/vitest-dev-vitest-b31hwg?file=vite.config.ts

**Comment by timleers** [comment]
Seems like the issue occurs only when using the constant within a vue component:
https://stackblitz.com/edit/vitejs-vite-w5twrd?file=src/components/HelloWorld.test.ts

**Comment by stygian-desolator** [comment]
> Seems like the issue occurs only when using the constant within a vue component: https://stackblitz.com/edit/vitejs-vite-w5twrd?file=src/components/HelloWorld.test.ts

I'm trying to solve this problem.
If you're desperate for a solution, try this
https://stackblitz.com/edit/vitejs-vite-y6gi6x?file=src%2Fcomponents%2FHelloWorld.vue
