### ISSUE TITLE
@vitest/mocker v3.0.0-beta.2 does not support vite v6 as a peer-dependency

### ISSUE THREAD

**Issue by christopherschroer** [vitest-dev/vitest#7072]
### Describe the bug

When installing vite v6 and vitest v3.0.0-beta.2 using pnpm, I get the following warning:

<img width="308" alt="image" src="https://github.com/user-attachments/assets/62b1d2d6-4562-4cc3-a1c3-8ef5a44b4408" />

It seems that @vitest/mocker v3.0.0-beta.2 does not support vite v6 as a peer-dependency

### Reproduction

See https://github.com/vitest-dev/vitest/blob/v3.0.0-beta.2/packages/mocker/package.json#L58 for the problematic line

### System Info

```shell
System:
    OS: Windows 11 10.0.22000
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 9.96 GB / 31.28 GB
  Binaries:
    Node: 22.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.15.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.22000.2600.0), Chromium (131.0.2903.51)
    Internet Explorer: 11.0.22000.2600
  npmPackages:
    @vitejs/plugin-react-swc: 3.7.2 => 3.7.2
    @vitest/coverage-v8: 3.0.0-beta.2 => 3.0.0-beta.2
    @vitest/ui: 3.0.0-beta.2 => 3.0.0-beta.2
    vite: 6.0.3 => 6.0.3
    vitest: 3.0.0-beta.2 => 3.0.0-beta.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Not released yet, but this has been fixed on main
- https://github.com/vitest-dev/vitest/pull/7058
