### ISSUE TITLE
Flag `dangerouslyIgnoreUnhandledErrors` is ignored in workspaces

### ISSUE THREAD

**Issue by dubzzz** [vitest-dev/vitest#7088]
### Describe the bug

The flag `dangerouslyIgnoreUnhandledErrors` seems to be totally ignored when running tests using the workspace setup, while it gets taken into account for the out-of-workspace setup.

### Reproduction

The reproduction is available at [repository with minimal reproduction](https://github.com/dubzzz/bug-vitest-workspace/tree/main).

It comes with two distinct directories:

- `local` - comes with a classical setup without any workspace
- `workspace` - comes with the same configuration but via a workspace setup

Each setup is defined for `dangerouslyIgnoreUnhandledErrors: true` but the workspace one ignores it totally.

You can compare the two by running:

```sh
npm ci
npm run repro
# prints success in local but not in workspace
```

### System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
    Memory: 5.55 GB / 7.74 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 20.17.0 - ~/nvm/current/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.8.2 - ~/nvm/current/bin/npm
    pnpm: 9.11.0 - ~/nvm/current/bin/pnpm
  npmPackages:
    vitest: ^2.1.8 => 2.1.8
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This option has a "star" in the documentation (https://vitest.dev/config/#dangerouslyignoreunhandlederrors) meaning you cannot use it in your project config, it needs to be defined in the root config

> All configuration options that are not supported inside a workspace project config have * sign next to them.

**Comment by dubzzz** [comment]
Sorry for the ping then.
