### ISSUE TITLE
Watch mode behaviour can't be override from CLI

### ISSUE THREAD

**Issue by ShivamJoker** [vitest-dev/vitest#710]
### Describe the bug

Watch mode behaviour can't be override by passing flags from CLI

### Reproduction

Create a basic test app from docs

Disable watch mode in config

```ts
/// <reference types="vitest" />
import { defineConfig } from "vite";

export default defineConfig({
  test: {
    watch: false,
  },
});
```

Try running watch mode from CLI

```sh
npx vitest watch
```

or

```sh
npx vitest --watch
```

Screenshots 👇

![image](https://user-images.githubusercontent.com/23727670/153142154-c7b8c08b-23ea-49b2-8d19-13f69d85a98d.png)

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 275.97 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Safari: 15.2
  npmPackages:
    vitest: ^0.2.7 => 0.2.7
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DerYeger** [comment]
I had a look at the source code and the config file is supposed to override the Cli args.
https://github.com/vitest-dev/vitest/blob/3df5d8b9708d4ce42e45ac6f4e5621188674207d/packages/vitest/src/node/plugins/index.ts#L48

Do you need so set `watch` to `false` in the config?
You could just disable watch mode by using `vitest` run when required.

**Comment by ShivamJoker** [comment]
Ohh the CLI should override it by default watch is enabled #696 (I sent PR for this)

**Comment by DerYeger** [comment]
> Ohh the CLI should override it by default watch is enabled #696 (I sent PR for this)

I'm not sure what you mean.
The default is `!process.env.CI && !argv.run`.
This is overridden by the CLI, which in return is overridden by the config.

**Comment by ShivamJoker** [comment]
@DerYeger thats what I am trying to say by default the watch is enabled, and to disable it I set the watch to false in config file.
But I want to table watch from the CLI flag, How do I do it?

**Comment by DerYeger** [comment]
You can't.
Remove the `watch: false` and use `vitest run` instead of `vitest`.
If you want watch mode enabled, use `vitest` or even `vitest run --watch`.

**Comment by ShivamJoker** [comment]
okay it works that way.

But I believe CLI should override the default config no matter what 🙅

**Comment by Demivan** [comment]
I agree with @ShivamJoker here. CLI args should override config.
I was using `threads: true` in config and `--no-threads` CLI arg was working just fine.

**Comment by DerYeger** [comment]
Will be closed by #702

**Comment by DerYeger** [comment]
Yes, as part of v0.3.0.

**Comment by sheremet-va** [comment]
> 

There is now an issue: `vitest run` enables watch mode (https://github.com/vitest-dev/vitest/pull/713#issuecomment-1033846352)
