### ISSUE TITLE
target[key].push is not a function (regression in v0.3.0)

### ISSUE THREAD

**Issue by cexbrayat** [vitest-dev/vitest#718]
### Describe the bug

Using vitest v0.3.0 and the following config:

```ts
  test: {
    reporters: ['default', 'json'],
  },
```

produces the error:

```
file:///Users/cedric/Code/ninjasquad/vue-pro-pack/ponyracer/node_modules/vitest/dist/index-f55e7b59.js:288
        target[key].push(...source[key]);
                    ^

TypeError: target[key].push is not a function
    at file:///Users/cedric/Code/ninjasquad/vue-pro-pack/ponyracer/node_modules/vitest/dist/index-f55e7b59.js:288:21
    at Array.forEach (<anonymous>)
    at deepMerge (file:///Users/cedric/Code/ninjasquad/vue-pro-pack/ponyracer/node_modules/vitest/dist/index-f55e7b59.js:280:25)
    at deepMerge (file:///Users/cedric/Code/ninjasquad/vue-pro-pack/ponyracer/node_modules/vitest/dist/index-f55e7b59.js:294:10)
    at Object.configResolved (file:///Users/cedric/Code/ninjasquad/vue-pro-pack/ponyracer/node_modules/vitest/dist/create-d3b904b2.js:9136:19)
    at /Users/cedric/Code/ninjasquad/vue-pro-pack/ponyracer/node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:70984:127
```

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-gzezln?file=vite.config.ts

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 16.09 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.volta/tools/image/node/16.13.2/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.4.1 - ~/.volta/tools/image/npm/8.4.1/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 96.0.2
    Safari: 15.2
  npmPackages:
    @vitejs/plugin-vue: 2.2.0 => 2.2.0
    vite: 2.8.0 => 2.8.0
    vitest: 0.3.0 => 0.3.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cexbrayat** [comment]
I think this is an issue with the default config, I'll open a PR

**Comment by DerYeger** [comment]
Shouldn't the field be named `reporter`?

**Comment by cexbrayat** [comment]
vitest picked `reporters` whereas the coverage reporters option is `reporter` 🤷

**Comment by sheremet-va** [comment]
reporter is cli only option, it gets merged

**Comment by DerYeger** [comment]
Weird, I'm seeing this in the Vitest repo

![image](https://user-images.githubusercontent.com/7950094/153232989-c23d822b-94a7-424b-91bc-7e64b6b45e62.png)

**Comment by cexbrayat** [comment]
This is the coverage reporter option, which is different from the test reporters

**Comment by DerYeger** [comment]
> This is the coverage reporter option, which is different from the test reporters

Totally, I was looking in the wrong place.
