### ISSUE TITLE
vitest run is watching files and does not quit

### ISSUE THREAD

**Issue by otakustay** [vitest-dev/vitest#719]
### Describe the bug

`vitest run` is now watching files.

![image](https://user-images.githubusercontent.com/639549/153231217-843ee47f-3758-4a8d-a639-08faac9012a7.png)

### Reproduction

Run `vitest run`

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 231.05 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /var/folders/9v/sx18bwn925b3f2rp2jfg952w0000gn/T/fnm_multishells/13654_1644417845070/bin/node
    Yarn: 1.22.15 - /var/folders/9v/sx18bwn925b3f2rp2jfg952w0000gn/T/fnm_multishells/13654_1644417845070/bin/yarn
    npm: 8.3.0 - /var/folders/9v/sx18bwn925b3f2rp2jfg952w0000gn/T/fnm_multishells/13654_1644417845070/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Safari: 15.2
  npmPackages:
    vite: ^2.8.0 => 2.8.0
    vitest: ^0.3.0 => 0.3.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by eberkund** [comment]
I still have this issue on 0.3.2, it says "run" rather than "watch" like the screenshot above but it doesn't exit after the tests finish. I have to press ctrl+C to quit vitest.

**Comment by mcremer-able** [comment]
I have also this issue 
![grafik](https://user-images.githubusercontent.com/102793246/187396504-ca3f3c31-d182-4281-981b-1908d87f75d5.png)
It shows run, but never stops

**Comment by sheremet-va** [comment]
> I have also this issue
> ![grafik](https://user-images.githubusercontent.com/102793246/187396504-ca3f3c31-d182-4281-981b-1908d87f75d5.png)
> It shows run, but never stops

please, open an issue with reproduction. you might just have another process hanging
