### ISSUE TITLE
Config `watch: false` requires `--no-run` to be overridden

### ISSUE THREAD

**Issue by DerYeger** [vitest-dev/vitest#727]
### Describe the bug

After `6772c5fa5ebf5eb0d101c64247e0bd9ecffcac87`, watch mode can no longer be enabled by passing the `--watch` flag if `watch` has been set to `false` in the config.

To use watch mode, the `--no-run` flag has to be passed in addition.

### Reproduction

1. Add `watch: false` to the config.
2. Run `vitest --watch`.

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 194.22 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.volta/tools/image/node/16.13.2/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.1.2 - ~/.volta/tools/image/node/16.13.2/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Safari: 15.2
  npmPackages:
    vite: ^2.7.13 => 2.7.13 
    vitest: workspace:* => 0.3.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by stygian-desolator** [comment]
Perhaps `options.run` could be deprecated, it duplicates `options.watch`. 🤔

**Comment by Aslemammad** [comment]
@DerYeger Hey, Please consider seeing #736 and see if it solves your problem! Thanks!
