### ISSUE TITLE
Running multiple test files crashes when canvas is installed (Error: Module did not self-register: '.../canvas/build/Release/canvas.node'.)

### ISSUE THREAD

**Issue by kleinfreund** [vitest-dev/vitest#740]
### Describe the bug

I’ve started exprimenting with Vitest and got all tests to pass individually; however, running `npx vitest run .` (or any set of test files together like `npx vitest run src/*.test.js`) crashes with the following error:

```
 RUN  /home/phil/dev/packages/vue-accessible-color-picker

node:internal/process/promises:265
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Module did not self-register: '/home/phil/dev/packages/vue-accessible-color-picker/node_modules/canvas/build/Release/canvas.node'.
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1185:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/phil/dev/packages/vue-accessible-color-picker/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

I’ve removed the `node_modules` directory contents several times, re-installed the dependencies, and the issue still happens. I’m writing this only because that’s the only tangible workaround I found for this problem.

### Reproduction

```
git clone https://github.com/kleinfreund/vue-accessible-color-picker.git
cd vue-accessible-color-picker
npm install

npm test
# or
npx vitest run .
```

**Expected behavior**:

Test suite runs with all tests passing.

**Actual behavior**:

Vitest crashes and no tests are run.

### Workaround: turn off threads

In https://github.com/vitest-dev/vitest/issues/740#issuecomment-1042648373, a workaround was presented. Turning off [threads](https://vitest.dev/config/#threads) stops the issue from happening. Using the following configuration, the tests start working:

```js
/// <reference types="vitest" />

import { defineConfig } from 'vite'
import Vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [
    Vue(),
  ],
  test: {
    threads: false,
    environment: 'jsdom',
  },
})
```

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 8.5.0 - ~/dev/packages/vue-accessible-color-picker/node_modules/.bin/npm
  npmPackages:
    @vitejs/plugin-vue: ^2.2.0 => 2.2.0 
    vite: ^2.8.1 => 2.8.1 
    vitest: ^0.3.4 => 0.3.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kleinfreund** [comment]
This is caused by the package [canvas](https://www.npmjs.com/package/canvas) being installed in my dependencies and used in my tests. JSDom automatically detects the package being present (see https://github.com/jsdom/jsdom#canvas-support) and allows me to test code that relies on `document.createElement('canvas').getContext('2d')`.

Removing it allows me to run multiple tests at once (e.g `npm test -- src/utilities/color-conversions/*` works), but naturally, the tests relying on the canvas integration into JSDom fail now.

Interestingly, if ran individually, the tests relying on canvas work fine with Vitest (e.g. `npm t -- src/ColorPicker.test.js` passes). Just running them collectively results in the error reported originally.

**Comment by bkuster** [comment]
We are having the same issue. Furthermore, once I get a singel test to compile (and run), re-running the test will choke and cause a segmentation fault or (erratically) some nice native binding errors. OS and versions same as OP.

![image](https://user-images.githubusercontent.com/11855207/154095889-5b90bc02-6c93-4a61-8ed8-05227666b846.png)

**Comment by kleinfreund** [comment]
I have a feeling this might be caused by https://github.com/Automattic/node-canvas/issues/1394.

**Comment by bkuster** [comment]
workaround: in your config set `threads: false`

**Comment by molily** [comment]
Is there any way to use `threads: true` while mocking or disabling jsdom? Disabling threads means losing many of vitest's benefits.

Apparently, npm 7+ always installs `canvas` since it's a peer dependency of `jsdom`. So [this code in jsdom](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/utils.js#L149-L165) require()s `canvas` even if it is not mentioned in my `package.json` dependencies.

I'm using `vite-plugin-svelte` and run into the "Module did not self-register" error if a test just includes a "Hello world" Svelte Component, without using the canvas API at all.

I‘ve tried `vi.mock('canvas', () => ({}));`. But this does not work, I guess because Vitest cannot mock what jsdom require()s. Any other ideas? Thanks.

**Comment by sheremet-va** [comment]
> Is there any way to use threads: true while mocking or disabling jsdom? Disabling threads means losing many of vitest's benefits.

What kind of benefits?

> Apparently, npm 7+ always installs canvas since it's a peer dependency of jsdom. So [this code in jsdom](https://github.com/jsdom/jsdom/blob/master/lib/jsdom/utils.js#L149-L165) require()s canvas even if it is not mentioned in my package.json dependencies.

As a workaround, maybe there is an old version of this module that doesn't throw? And you can pin it in your `package.json`.

Also, you can try using `heppy-dom` :)

**Comment by dawiidio** [comment]
`threads: false` makes things even worse. I'm using `@testing-library/react` and somehow setting `threads: false` breaks down all the `screen` usages while keeping `threads: true` breaks `canvas`  😅 so far the only solution I've found is this configuration:
```js
{   
       //...
        minThreads: 0,
        maxThreads: 1,
}
```
in the above example `canvas` seems to be happy and all the tests run without any changes. Nevertheless in this configuration everything is extremely slow. 

I also tried older versions of `canvas`, all with the same result.

**Comment by sheremet-va** [comment]
> `threads: false` makes things even worse

If you are running `--no-threads`, don't forget to call `cleanup` from `@testing-library` in your setupFile. Currently Vitest doesn't retain global hooks between tests, if `--no-threads` is called

**Comment by Doeke** [comment]
This bug is currently preventing me from switching over to Vitest.

- Happy-dom is not an option for me because it still lacks features I need
- `jsdom` package also installs `canvas`, and so `rm node_modules/canvas` only works temporarily only until the next `npm install`
- `threads: false` is too slow (I have many tests)

**Comment by jsolly** [comment]
Just want to add that because I am also using setup files, having threads turned off has additional performance hits.

> TIP
Note, that if you are running --no-threads, this setup file will be run in the same global scope multiple times. Meaning, that you are accessing the same global object before each test, so make sure you are not doing the same thing more than you need.

https://vitest.dev/config/#setupfiles

**Comment by MichaelFBA** [comment]
Seeing a similar issue with sharp
```
Error: 
Something went wrong installing the "sharp" module

Module did not self-register: '...../node_modules/sharp/build/Release/sharp-linux-x64.node'.

Possible solutions:
- Using worker threads? See https://sharp.pixelplumbing.com/install#worker-threads
- Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
```

**Comment by sheremet-va** [comment]
@MichaelFBA try calling `require('sharp')` in config file. Or in [`globalSetup`](https://vitest.dev/config/#globalsetup). These are the only places user can call code outside of worker thread.

**Comment by MichaelFBA** [comment]
> @MichaelFBA try calling `require('sharp')` in config file. Or in [`globalSetup`](https://vitest.dev/config/#globalsetup). These are the only places user can call code outside of a worker thread.

Yes I tried adding it to our global setup file for vitest. The issue seems to occur when running watch and only when you change a test does it break

**Comment by merkle-rking** [comment]
Since canvas is an optional peer dependency, we're considering a workaround to just not install peer dependencies locally and in our build agent. This only works for us because we don't have any other optional peer dependencies that we need to use locally or during testing. Though, if you did find yourself in that situation, you could list your optional peer dependencies as explicit dependencies.

```
npm ci --no-optional
```

**Comment by ludufre** [comment]
> > @MichaelFBA try calling `require('sharp')` in config file. Or in [`globalSetup`](https://vitest.dev/config/#globalsetup). These are the only places user can call code outside of a worker thread.
> 
> Yes I tried adding it to our global setup file for vitest. The issue seems to occur when running watch and only when you change a test does it break

Found any solution?

**Comment by SebCorbin** [comment]
Had the same problem with `pdfjs-dist` including canvas as optional, `npm i --no-optional` did the work for me

**Comment by mw-sezzle** [comment]
I ran into this when I had the wrong path for `include` in my `vite.config.ts` file

**Comment by EdenTurgeman** [comment]
@SebCorbin Did you manage to find the issue? I'm also dealing with the same issue with `pdfjs-dist`

**Comment by CodySchaaf** [comment]
I tried all the suggestions, and while disabling threading worked it broke ci. The thing that finally worked for me was blowing away my node_modules deleting the package-lock and clearing the npm cache. Then finally reinstalling everything.

**Comment by kleinfreund** [comment]
I'm also still having issues with this. This is not completely fixed.

- jsdom:
  - `threads: true` ❌ ("Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)")
  - `threads: false` ✅
  - `singleThread: true` ✅
- happy-dom:
  - `threads: true` ❌ ("TypeError: document.createElement(...).getContext is not a function")
  - `threads: false` ❌ ("TypeError: document.createElement(...).getContext is not a function")
  - `singleThread: true` ❌ ("TypeError: document.createElement(...).getContext is not a function")

**Comment by sheremet-va** [comment]
> I'm also still having issues with this. This is not completely fixed.
> 
> * jsdom:
>   
>   * `threads: true` ❌ "Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)" (note, canvas is installed)
>   * `threads: false` ✅
>   * `singleThread: true` ✅
> * happy-dom:
>   
>   * `threads: true` ❌ "TypeError: document.createElement(...).getContext is not a function"
>   * `threads: false` ❌ "TypeError: document.createElement(...).getContext is not a function"
>   * `singleThread: true` ❌ "TypeError: document.createElement(...).getContext is not a function"

This is package's limitation, not Vitest. `threads: true` is not supported when using `canvas` package.
