### ISSUE TITLE
Add mocked utility (a la ts-jest)

### ISSUE THREAD

**Issue by kentcdodds** [vitest-dev/vitest#745]
### Clear and concise description of the problem

When you mock a function in a module, TypeScript doesn't know that this function has been mocked:

```ts
import {vi} from 'vitest'
import {thing} from 'module'

vi.mock('module', () => {
  return {thing: vi.fn()}
})

test('thing', () => {
  // TypeScript doesn't like this line:
  thing.mockImplementation(() => 'hi')
  // etc...
})
```

### Suggested solution

With jest, we could use `mocked` from `ts-jest` test helpers (which apparently has been included in jest recently: https://kulshekhar.github.io/ts-jest/docs/guides/test-helpers

I would like something similar for vitest:

```ts
import {vi, mocked} from 'vitest'
import * as mod from 'module'

const thing = mocked(mod.thing)

vi.mock('module', () => {
  return {thing: vi.fn()}
})

test('thing', () => {
  // TypeScript can auto-complete this line now:
  thing.mockImplementation(() => 'hi')
  // etc...
})
```

### Alternative

Could install jest and use it's `mocked` utility.

### Additional context

I'm more than happy if there's an alternative solution to the problem that I haven't considered. I'm not married to the `mocked` utility. Seems like useful prior art though.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by kentcdodds** [comment]
Awesome, thanks. I've now found the docs for that here: https://vitest.dev/api/#vi-mocked

**Comment by kamatheuska** [comment]
The link by @kentcdodds is now https://vitest.dev/api/vi.html#vi-mocked
