### ISSUE TITLE
Vitest loads multiple formats of the same package

### ISSUE THREAD

**Issue by marvinhagemeister** [vitest-dev/vitest#747]
### Describe the bug

During a test run it seems like libraries can be loaded twice when something requests a commonjs module and something else the ESM variant.

```sh
TypeError [Error]: Cannot read properties of null (reading 'context')
    at Proxy.exports.useContext (/app/node_modules/preact/hooks/dist/hooks.js:1:2437)
    at d.ExampleConsumer [as constructor] (/app/app/src/preact-bug.test.jsx:38:41)
    at d.M [as render] (/app/node_modules/preact/dist/preact.js:1:7837)
    at j (file:///app/node_modules/preact/dist/preact.mjs:1:5752)
    at file:///app/node_modules/preact/dist/preact.mjs:1:1494
    at Array.some (<anonymous>)
    at g (file:///app/node_modules/preact/dist/preact.mjs:1:1392)
```

As indicated by the stack trace, somehow `preact.mjs` AND `preact.js` are loaded. This sounds like vite or vitest is including both a CommonJS and an ESM Module of the same library.

(Originally reported at https://github.com/preactjs/preact/issues/3220)

### Reproduction

1. Clone https://github.com/dancras/preact-bug
2. Run `npm install`
3. Run `npm run vitest`

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 92.44 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.6.2 - ~/.nvm/versions/node/v16.6.2/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 7.20.3 - ~/.nvm/versions/node/v16.6.2/bin/npm
    Watchman: 2021.10.18.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 89.1.21.73
    Chrome: 98.0.4758.80
    Chrome Canary: 100.0.4886.0
    Edge: 98.0.1108.51
    Firefox: 96.0.3
    Safari: 15.2
  npmPackages:
    vite: ^2.8.0 => 2.8.0 
    vitest: ^0.3.2 => 0.3.2 
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
To import libraries we use native `import`. And node doesn't understand `moudle` field, so I added `exports` field, and now I get another error.

```
  "exports": {
    ".": {
      "import": "./dist/hooks.module.js",
      "require": "./dist/hooks.js"
    }
  },
  ```
  
  ```
  TypeError: Cannot read properties of undefined (reading '__H')
 ❯ m node_modules/preact/hooks/dist/hooks.module.js:110:20

 ❯ p node_modules/preact/hooks/dist/hooks.module.js:138:2
 ❯ Object.l node_modules/preact/hooks/dist/hooks.module.js:135:19
 ❯ d.ExampleProvider [as constructor] src/preact-bug.test.jsx:12:30
 ❯ d.M [as render] node_modules/preact/dist/preact.js:1:7837
 ❯ I node_modules/preact/dist/preact.js:1:5598
 ❯ m node_modules/preact/dist/preact.js:1:2096
 ❯ I node_modules/preact/dist/preact.js:1:5831
 ❯ N node_modules/preact/dist/preact.js:1:7951
 ❯ node_modules/@testing-library/preact/dist/pure.js:90:26
 ❯ exports.act node_modules/preact/test-utils/dist/testUtils.js:1:790
 ❯ Proxy.render node_modules/@testing-library/preact/dist/pure.js:86:22
 ❯ src/preact-bug.test.jsx:43:4
 ❯ runTest node_modules/vitest/dist/entry.js:1728:40
 ❯ async runSuite node_modules/vitest/dist/entry.js:1792:13
 ❯ async runSuites node_modules/vitest/dist/entry.js:1820:5
 ❯ async startTests node_modules/vitest/dist/entry.js:1825:3
 ❯ async node_modules/vitest/dist/entry.js:1849:7
 ❯ async withEnv node_modules/vitest/dist/entry.js:1479:5
 ❯ async run node_modules/vitest/dist/entry.js:1848:5
 ```

**Comment by marvinhagemeister** [comment]
That's interesting. I would've assumed that bundlers only look at the top level `package.json` of a package where all the export mapping happens.

**Comment by sheremet-va** [comment]
> That's interesting. I would've assumed that bundlers only look at the top level `package.json` of a package where all the export mapping happens.

Vitest is not a bundler tho, and we dont use Vite to bundle code, only to transpile. Also we don't perform Vite's transformations on `node_modules` for perfomance reasons, but it's possible to `deps.inline` them in config.

**Comment by marvinhagemeister** [comment]
FYI: The issue described here seems to relate to the `dual package hazard` section in Node's module docs: https://nodejs.org/api/packages.html#dual-package-hazard

**Comment by sheremet-va** [comment]
> FYI: The issue described here seems to relate to the "dual package hazard" section in Node's module docs: https://nodejs.org/api/packages.html#dual-package-hazard

Yes, I think this is due to `testing-library` being `cjs` only. It `requires` preact to render, then user code `imports` hooks from `mjs`, where `currentComponent` is undefined

**Comment by sheremet-va** [comment]
So, to fix this we need to:

Either
- Have `exports` field in all of the `preact` packages
- AND build ESM `testing-library`
Or
Somehow import only `cjs` versions in Vitest, but this is harder, since we are ESM first, and would require some digging

**Comment by marvinhagemeister** [comment]
Agree that pushing for ESM rather than moving back to CJS seems like the preferable move. Maybe if `testing-library` is ESM that problem will be resolved.

**Comment by danielweck** [comment]
Yep, my Preact hook tests are broken because of this :)
I am going to try using `preact/text-utils` directly instead...

**Comment by userquin** [comment]
> * Somehow import only `cjs` versions in Vitest of these libraries, but this is harder, since we are ESM first, and it would be quite a rewrite - maybe some kind of config option will be necessary, but I would prefer the first variant, since it will work by default for most users

maybe this can help to load cjs https://github.com/iconify/iconify/blob/master/packages/utils/vitest.config.cjs running:
`vitest --config vitest.config.cjs`

**Comment by danielweck** [comment]
Ah, my workaround is to delete / rename `node_modules/preact/hooks/package.json`, which interferes with the top-level import map in `node_modules/preact/package.json` (which itself references `preact/hooks`)
👍

**Comment by brianblakely** [comment]
Running vitest in `--no-threads` mode resolved this issue for me. Although there are other issues now as a result of doing that, they seem more manageable.

**Comment by danielweck** [comment]
There's an update: https://github.com/testing-library/preact-testing-library/issues/50#issuecomment-1137453847
Unfortunately still fails at my end, so my workaround persists :)
(basically, a copy of https://github.com/testing-library/preact-testing-library/blob/1f9851894ff4fc772addef39855ecc0d8b219dca/src/pure.js and https://unpkg.com/browse/@testing-library/preact@3.1.1/types/index.d.ts in my ESM / TS codebase)

**Comment by danielweck** [comment]
Another update: fixed now :)
https://github.com/testing-library/preact-testing-library/issues/50#issuecomment-1138923859

**Comment by wight554** [comment]
> Another update: fixed now :) [testing-library/preact-testing-library#50 (comment)](https://github.com/testing-library/preact-testing-library/issues/50#issuecomment-1138923859)

Have you managed to get everything working ootb?
Last (>3.0.2) preact-testing library updates breaks `preact/hooks` import for me like here: https://github.com/preactjs/preact/issues/2690

**Comment by wight554** [comment]
> > Another update: fixed now :) [testing-library/preact-testing-library#50 (comment)](https://github.com/testing-library/preact-testing-library/issues/50#issuecomment-1138923859)
> 
> Have you managed to get everything working ootb? Last (>3.0.2) preact-testing library updates breaks `preact/hooks` import for me like here: [preactjs/preact#2690](https://github.com/preactjs/preact/issues/2690)

for those who came with typescript 4.7 and new module resolution config:
While `@testing-library/preact` fully supports esm, some of modulesyou use may not, eg recoil, mui (which is weird actually) in my case. That leads to CJS/ESM import issues (like `preact/hooks` error). To workaround this, use TypeScript CJS import [interop](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#commonjs-interoperability):
```
import tlp = require('@testing-library/preact');

const { screen, waitFor, fireEvent, cleanup } = tlp;
```

That did help in my case. If anyone has better solution, please share. Forcing everyone to have proper ESM support is nice, but it may take a lot of time

**Comment by danielweck** [comment]
Thanks for the tip @wight554 
As mentioned previously in this thread, what worked for me is the following (but I appreciate that projects with different dependency trees might experience different issues):

> Ah, my workaround is to delete / rename `node_modules/preact/hooks/package.json`, which interferes with the top-level import map in `node_modules/preact/package.json` (which itself references `preact/hooks`)

**Comment by sheremet-va** [comment]
Fixed, according to https://github.com/vitest-dev/vitest/issues/747#issuecomment-1138947503
