### ISSUE TITLE
Test fails in components which import svg

### ISSUE THREAD

**Issue by chin2km** [vitest-dev/vitest#748]
### Describe the bug

Test fails with message `SyntaxError: Unexpected token '<'` when the component you test imports an svg.

<img width="1041" alt="Screenshot 2022-02-14 at 12 27 41 AM" src="https://user-images.githubusercontent.com/10056971/153780106-e758978b-573b-4d8d-92e9-565f2651813c.png">

### Reproduction

The component I'm testing just has an svg import

```tsx
export enum ErrorBoundaryIconName {
  FlashWarning = 'FlashWarning',
}

export const errorPageInlineIconAssets: {
  [key in ErrorBoundaryIconName]: string;
} = {
  [ErrorBoundaryIconName.FlashWarning]: require('./ic-flash-warning.svg'),
};
```

### System Info

```shell
System:
    OS: macOS 11.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 210.08 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nodenv/versions/14.18.0/bin/node
    Yarn: 1.22.17 - ~/.nodenv/versions/14.18.0/bin/yarn
    npm: 6.14.15 - ~/.nodenv/versions/14.18.0/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 96.0.3
    Safari: 15.3
  npmPackages:
    @vitejs/plugin-react: ^1.2.0 => 1.2.0 
    vite: ^2.8.1 => 2.8.1 
    vitest: ^0.3.4 => 0.3.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Why shouldn’t it fail? require is native node, which will fail if it can’t parse something.
If you want Vite transform to take effect, try importing it.

**Comment by chin2km** [comment]
@sheremet-va Ok got it. I was looking something like [moduleNameMapper](https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring) in jest.

In jest its possible to configure it like this:

```tsx
  moduleNameMapper: {
    '\\.(svg)$':
      '<rootDir>/__tests__/fileMock.ts',
  }
  ```
  
  //=> fileMock.ts
  ```tsx
  module.exports = '<svg id="some-svg">';
```

**Comment by sheremet-va** [comment]
> @sheremet-va Ok got it. I was looking something like [moduleNameMapper](https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring) in jest.
> 
> In jest its possible to configure it like this:
> 
> ```tsx
>   moduleNameMapper: {
>     '\\.(svg)$': '__tests__/fileMock.ts',
>   }
> ```
> 
> //=> fileMock.ts
> 
> ```tsx
> module.exports = '<svg id="some-svg">';
> ```

It is imposible to do with `require` in Vitest. `require` is only for cjs compatability. We are ESM first, so please use `import`, then Vite transform will handle it for you.

**Comment by chin2km** [comment]
Ok, thanks for clarifying :) Closing the issue.
