### ISSUE TITLE
Not possible to update globals in before/after hooks

### ISSUE THREAD

**Issue by chin2km** [vitest-dev/vitest#755]
### Describe the bug

I have some globals like (__SERVER__ __CLIENT__) defined in vite.config.ts.
I see no way to update those in before/after hooks. 

It was possible to do with Jest like shown below.

How do we do this with vitest?

<img width="703" alt="Screenshot 2022-02-14 at 5 22 00 PM" src="https://user-images.githubusercontent.com/10056971/153904340-6ee35fa4-07f8-4e95-a194-a0a5aa5091e6.png">

### Reproduction

```tsx
    beforeAll(() => {
      globalThis.__SERVER__ = true;
      __SERVER__ = true;
    });
    afterAll(() => {
      globalThis.__SERVER__ = false;
      __SERVER__ = false;
    });
```
tried this and it doesnt work!

### System Info

```shell
System:
    OS: macOS 11.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 106.25 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.0 - ~/.nodenv/versions/14.18.0/bin/node
    Yarn: 1.22.17 - ~/.nodenv/versions/14.18.0/bin/yarn
    npm: 6.14.15 - ~/.nodenv/versions/14.18.0/bin/npm
  Browsers:
    Chrome: 98.0.4758.80
    Firefox: 96.0.3
    Safari: 15.3
  npmPackages:
    @vitejs/plugin-react: ^1.2.0 => 1.2.0 
    vite: ^2.8.1 => 2.8.1 
    vitest: ^0.3.4 => 0.3.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Are these variables from `define` in your vite.config?

If so, they are statically replaced in your code, so you can't reassign them. I would suggest conditionally apply them for tests like so:
```ts
export default defineConfig({
   define: process.env.VITEST ? {} : { __SERVER__: true }
})
```
