### ISSUE TITLE
`defineConfig` doesn't work properly

### ISSUE THREAD

**Issue by pd4d10** [vitest-dev/vitest#764]
### Describe the bug

Although `defineConfig` has been implemented by #749, it doesn't seem to work properly because of runtime limitations.

`import { defineConfig } from 'vitest'` would throw an error as follows:

```
      throw new Error("Vitest was initialized with native Node instead of Vite Node");
            ^

Error: Vitest was initialized with native Node instead of Vite Node
```

Perhaps we could change the API to

```diff
- import { defineConfig } from 'vitest'
+ import { defineConfig } from 'vitest/node'
```

and leave `vitest` as the entry point for testing runtime purposes.

### Reproduction

Set `vitest.config.mjs` as [this doc](https://vitest.dev/config/#configuration) describes

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 238.73 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nn/current/bin/node
    Yarn: 1.22.17 - ~/.nn/current/bin/yarn
    npm: 8.1.0 - ~/.nn/current/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 90.0.2
    Safari: 15.3
  npmPackages:
    @vitejs/plugin-legacy: ^1.6.4 => 1.7.1
    @vitejs/plugin-react: ^1.2.0 => 1.2.0
    vitest: ^0.3.5 => 0.3.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
`vitest/node` looks good to me. PR welcome!
