### ISSUE TITLE
Vitest --ui should go to /__vitest___

### ISSUE THREAD

**Issue by fadi-george** [vitest-dev/vitest#779]
### Describe the bug

When running older versions of Vitest (e.g. 0.2.7, 0.2.8) with the ui flag, it would open a tab with `/__vitest__` in the url. Current version does not do and leads to confusion.

### Reproduction

Download and run locally should open a browser with __vitest__ appended to the end
(0.2.7) https://stackblitz.com/edit/node-8iphaf?file=package.json

Download and run locally should, doesn't open with __vitest__ appended
(0.3.6) https://stackblitz.com/edit/node-ulsvxr?file=.stackblitzrc

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 572.81 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Brave Browser: 98.1.35.103
    Chrome: 98.0.4758.102
    Firefox: 96.0.3
    Safari: 15.2
  npmPackages:
    @vitejs/plugin-react: ^1.1.4 => 1.2.0 
    vite: 2.7.13 => 2.7.13 
    vitest: 0.2.7 => 0.2.7
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by uicrafts** [comment]
In `0.5.0` it goes to http://localhost:51204/__vitest__/ for me. However, see #833.

**Comment by edimitchel** [comment]
Can you confirm @fadi-george that the issue resolved? Feel free to reopen.
