### ISSUE TITLE
.env variables not loaded

### ISSUE THREAD

**Issue by fadi-george** [vitest-dev/vitest#780]
### Describe the bug

Previous versions (0.2.7) can load values from .env file, used in the app as import.meta.env.something.
Newer versions does not seem to do this.

### Reproduction

0.3.6 does not load .env https://stackblitz.com/edit/node-8ffahu?file=.env
0.2.7 works https://stackblitz.com/edit/node-inflqd?file=src%2FSomeComponent.spec.tsx

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 74.27 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Brave Browser: 98.1.35.103
    Chrome: 98.0.4758.102
    Firefox: 96.0.3
    Safari: 15.2
  npmPackages:
    @vitejs/plugin-react: ^1.1.4 => 1.1.4 
    vite: 2.7.13 => 2.7.13
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is fixed by https://github.com/vitest-dev/vitest/commit/1623b3c985364821f75a1d53ed499b74f47c63a6
Please wait for next release
