### ISSUE TITLE
Cannot override process.env.NODE_ENV

### ISSUE THREAD

**Issue by fadi-george** [vitest-dev/vitest#781]
### Describe the bug

Some scripts/code have conditionals that check against process.env.NODE_ENV. It should overridable for some test.

### Reproduction

https://stackblitz.com/edit/node-t29ck6?file=src%2Fsomething.spec.ts

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 212.92 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Brave Browser: 98.1.35.103
    Chrome: 98.0.4758.102
    Firefox: 96.0.3
    Safari: 15.2
  npmPackages:
    vitest: ^0.3.6 => 0.3.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is a known limitation https://github.com/vitejs/vite/pull/6935#pullrequestreview-884072390
