### ISSUE TITLE
Segmentation fault when a breakpoint is attached in VS Code

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [vitest-dev/vitest#795]
### Describe the bug

When running in VS Code with the recommended launch script from https://vitest.dev/guide/debugging.html, Vitest will error out with a 139 / Segmentation Fault if and only if a breakpoint is attached anywhere in the test file.

```plaintext
josh@LAPTOP-B0MQCQ9I:~/repos/repros$  cd /home/josh/repos/repros ; /usr/bin/env 'NODE_OPTIONS=--require /home/josh/.vscode-server/bin/899d46d82c4c95423fb7e10e68eba52050e30ba3/extensions/ms-vscode.js-debug/src/bootloader.bundle.js --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/tmp/node-cdp.29903-9.sock","deferredMode":false,"waitForDebugger":"","execPath":"/usr/bin/node","onlyEntrypoint":false,"autoAttachMode":"always","mandatePortTracking":true,"fileCallback":"/tmp/node-debug-callback-6863962514e5d6e5"}' /usr/bin/node ./node_modules/vitest/vitest.mjs run src/index.test.js
Debugger attached.

 RUN  /home/josh/repos/repros

Segmentation fault
```

This seems unrelated to the other 2-3 segfault issues.

### Reproduction

https://github.com/JoshuaKGoldberg/repros/tree/vitest-segmentation-fault

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz
    Memory: 12.01 GB / 24.94 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.0 - /usr/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.0 - /usr/bin/npm
  npmPackages:
    vitest: ^0.4.1 => 0.4.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by raulcesar** [comment]
I have also been having this problem, and have noticed it exists also in the [Peeky testrunner project](https://peeky.dev/)
Hope this information helps.

**Comment by Demivan** [comment]
Another hint is that it happens even with threads disabled

**Comment by TrickyPi** [comment]
<img width="724" alt="image" src="https://user-images.githubusercontent.com/33021497/155103028-61475ade-dda2-490a-9352-d7e79cd9e76e.png">
I didn't encounter this problem, it works...

**Comment by Demivan** [comment]
@TrickyPi What Vitest and Node version are you using. And what package manager?

**Comment by TrickyPi** [comment]
Vitest: v0.4.1
Node version: v16.13.1
package manager: yarn (version:1.22.15)

**Comment by TrickyPi** [comment]
My vscode info:
  Version: 1.63.2 (Universal)
  Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
  Date: 2021-12-15T09:37:28.172Z
  Electron: 13.5.2
  Chromium: 91.0.4472.164
  Node.js: 14.16.0
  V8: 9.1.269.39-electron.0
  OS: Darwin arm64 20.6.0

**Comment by raulcesar** [comment]
@TrickyPi, could you share your debugger launch config?

**Comment by TrickyPi** [comment]
<img width="699" alt="image" src="https://user-images.githubusercontent.com/33021497/155132726-a9a9a5c7-892b-4460-9f07-9be742b5f499.png">
same as here 
https://vitest.dev/guide/debugging.html#vscode

**Comment by raulcesar** [comment]
I noticed that my "Node.js" version in vscode was the same as that of @TrickyPi, but the version I am running in command line was v16.14.0. 

I decided to downgrade my version of node (with nvm) to v14.16.0 (to match vscode's version) and the error stopped appearing.
I started trying different versions of node, from 14.16 and up, and once I hit v16.8.0, the segmentation fault starts to occur.

Here is the complete list of versions I tried: 
Versions that work: v14.19.0, v15.12.0, v16.0.0, v16.3.0, v16.5.0, v16.7.0
Versions that resulted in segfault:  v16.8.0, v16.13.0, v16.14.0, v17.5.0

**Comment by TrickyPi** [comment]
I change my node version to v16.14.0, 
<img width="262" alt="image" src="https://user-images.githubusercontent.com/33021497/155134976-8637336e-fcd9-447b-b30a-1d5bccf0fbf4.png">
it also works.

**Comment by raulcesar** [comment]
Strange... when I run with v16.14.0, I get the error.
Made a very simple project (https://github.com/raulcesar/vscode-debug-segfault).
Here is the test:
![test-code](https://user-images.githubusercontent.com/1403840/155137172-c09ccf96-1b4d-4e5b-a117-6b702b28d85b.png)

 And here is the result:
![error-screenshot](https://user-images.githubusercontent.com/1403840/155137201-73b3ee55-94c0-4c2f-96af-0d09c71fae80.png)

@TrickyPi, with node v16.14.0, are you running vs code from command line (to make sure that VS-Code is running on that version)?

**Comment by TrickyPi** [comment]
Oh~, i did't use command line.
<img width="861" alt="image" src="https://user-images.githubusercontent.com/33021497/155138185-cbad4aab-b491-4947-bcc4-0be2f71f82f3.png">
when i use command line to start debugging, the segmentation fault starts to occur.

**Comment by raulcesar** [comment]
On this screen, the error has a little more information:
![vs-code-error-on-windows-2](https://user-images.githubusercontent.com/1403840/155161110-c79c7bcb-129f-470d-b0c0-6326d9fc6e1e.png)

**Comment by jasonwilliams** [comment]
I've managed to get to here before it segfaults:
https://github.com/vitest-dev/vitest/blob/main/packages/vitest/src/node/execute.ts#L19

Here is the call stack, right up to the point before it segfaults:

```
cachedRequest (/Users/me/workspace/next-page-tester/node_modules/vitest/dist/chunk-vite-node-utils.d38851ea.js:9318)
executeFile (/Users/me/workspace/next-page-tester/node_modules/vitest/dist/chunk-vite-node-utils.d38851ea.js:9311)
executeInViteNode (/Users/me/workspace/next-page-tester/node_modules/vitest/dist/worker.js:245)
await (Unknown Source:1)
startViteNode (/Users/me/workspace/next-page-tester/node_modules/vitest/dist/worker.js:283)
run (/Users/me/workspace/next-page-tester/node_modules/vitest/dist/worker.js:331)
<anonymous> (/Users/me/workspace/next-page-tester/node_modules/tinypool/dist/esm/worker.js:96)
await (Unknown Source:1)
onMessage (/Users/me/workspace/next-page-tester/node_modules/tinypool/dist/esm/worker.js:123)
atomicsWaitLoop (/Users/me/workspace/next-page-tester/node_modules/tinypool/dist/esm/worker.js:81)
<anonymous> (/Users/me/workspace/next-page-tester/node_modules/tinypool/dist/esm/worker.js:68)
await (Unknown Source:1)
<anonymous> (/Users/me/workspace/next-page-tester/node_modules/tinypool/dist/esm/worker.js:69)
[nodejs.internal.kHybridDispatch] (internal/event_target:643)
exports.emitMessage (Unknown Source:23)
callbackTrampoline (internal/async_hooks:130)
MESSAGEPORT (Unknown Source:1)
init (internal/inspector_async_hook:25)
emitInitNative (internal/async_hooks:201)
```

The argument passed is `'/Users/[me]/workspace/next-page-tester/node_modules/vitest/dist/entry.js'`

```
TypeError: callstack is not iterable
    at VitestRunner.directRequest (file:///Users/me/workspace/next-page-tester/node_modules/vitest/dist/chunk-vite-node-utils.d38851ea.js:9327:21)
    at VitestRunner.cachedRequest (file:///Users/me/workspace/next-page-tester/node_modules/vitest/dist/chunk-vite-node-utils.d38851ea.js:9322:26)
    at eval (eval at executeFile (file:///Users/me/workspace/next-page-tester/node_modules/vitest/dist/chunk-vite-node-utils.d38851ea.js:9311:45), <anonymous>:1:6)
    at VitestRunner.executeFile (file:///Users/me/workspace/next-page-tester/node_modules/vitest/dist/chunk-vite-node-utils.d38851ea.js:9311:45)
    at executeInViteNode (file:///Users/me/workspace/next-page-tester/node_modules/vitest/dist/worker.js:245:30)
    at async startViteNode (file:///Users/me/workspace/next-page-tester/node_modules/vitest/dist/worker.js:283:45)
    at async run (file:///Users/me/workspace/next-page-tester/node_modules/vitest/dist/worker.js:331:25)
    at async file:///Users/me/workspace/next-page-tester/node_modules/tinypool/dist/esm/worker.js:96:20

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
TypeError: callstack is not iterable
```


```
  System:
    OS: macOS 11.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 172.20 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.6.0 - ~/.nvm/versions/node/v17.6.0/bin/node
    npm: 8.5.1 - ~/.nvm/versions/node/v17.6.0/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Safari: 14.1.2
  npmPackages:
    vitest: 0.5.5 => 0.5.5 
```

**Comment by jasonwilliams** [comment]
@connor4312 do you have any inclination as to why it would only happen when in debug mode? But not when running node directly?

**Comment by connor4312** [comment]
Not really, though I am not an expert on V8 internals. But in general crashes when only in debug mode are not unprecedented. The debugger and the information it asks for will touch many more features of the runtime than any given program is likely to.

**Comment by raulcesar** [comment]
Hey guys, just did a recent update on my computer and decided to run some tests to see if anything changed.
the **TLDR** of it is that I think the problem has been corrected with vite 2.8.5 and vitest 0.5.8.

## Read on for the slightly longer story:
I found that when I used **YARN** or **NPM** (as opossed to **PNPM**) to install dependencies, the debugger worked without any problems. 
So I tried updating caches, comparing the "lock" files, etc. In the end, I ended up running a `pnpm -up vite --latest -r`, which upgraded vite to (2.8.5 and vitest to 0.5.8. After this, the segfault went away when using PNPM as well.

So here is the list of the tools I used (with versions):

**VSCode:**
Version: 1.64.2
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-10T19:07:05.314Z
Electron: 13.6.9
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.40-electron.0
OS: Linux x64 5.16.11-arch1-1

**node**: version: 16.14.0
**yarn**: version 1.22.17
**npm**: version 8.3.1
**pnpm**: 6.32.1

With this configuration, here are the result:

### vite v. 2.8.4 and vitest v. 0.5.1
If I use vite version 2.8.4 (with vitest 0.5.1):
YARN: works OK
NPM: works OK
PNPM: **_SEGFAULT_** (ONLY ON DEBUGGER). Works perfectly with "pnpm run test".

### vite version 2.8.5 and vitest 0.5.8::
YARN: works OK
NPM: works OK
PNPM: works OK

In my test project (https://github.com/raulcesar/vscode-debug-segfault), I have 2 commits with tags "SEGFAULT" and "NO-SEGFAULT" that illustrate the changes to dependencies.

Anyway, I hope this helps, and just want to say that I am loving vite and vitest, and will be using them both in an upcoming project.

**Comment by jasonwilliams** [comment]
I can also confirm that debugging works without segmentation faults on v0.5.9

**Comment by DannyFeliz** [comment]
should we close this issue then?
