### ISSUE TITLE
Default timeout time of hooks is different between documentation and configuration

### ISSUE THREAD

**Issue by togami2864** [vitest-dev/vitest#800]
### Describe the bug

According to [doc](https://vitest.dev/config/#hooktimeout), Default timeout time of hooks is `5000s`, but [default option value](https://github.com/vitest-dev/vitest/blob/b04dd8ffeffb528346d4d65bf1758666b41945d7/packages/vitest/src/types/config.ts#L159-L164) is`10000s`.
Which is the correct value?
([PR#702](https://github.com/vitest-dev/vitest/pull/702/files) changed that 5000s -> 10000s)

### Reproduction

None

### System Info

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
    Memory: 77.38 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.8.0 - ~/.nodenv/versions/16.8.0/bin/node
    Yarn: 1.22.17 - ~/.nodenv/versions/16.8.0/bin/yarn
    npm: 7.21.0 - ~/.nodenv/versions/16.8.0/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Safari: 14.1.2
  npmPackages:
    vite: ^2.8.2 => 2.8.1 
    vitest: workspace:* => 0.4.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
10 000 is correct one. Docs need to be updated, PR welcome.
