### ISSUE TITLE
Inconsistent behavior with Svelte contexts

### ISSUE THREAD

**Issue by AnatoleLucet** [vitest-dev/vitest#809]
### Describe the bug

While trying to migrate from Jest, I found that managing a Svelte context from outside a component seems to create some strange issues with Vitest.

### First issue: `Function called outside component initialization`
Let's say I call Svelte's `setContext` in a function - let's call it `initContext` - and this function is defined in a `.js` file beside the `.svelte` component, if I call `initContext` inside my Svelte component Vitest will throw `Function called outside component initialization (setContext)`.

According to the Svelte REPL [it should work](https://svelte.dev/repl/410523f9fbba4ce4b6adbf7bbd0b322d?version=3.46.4), but if you try it with Vitest, [it doesn't](https://stackblitz.com/edit/github-zrwj6k-isnfa8?file=components%2FHello.svelte).

### Second issue: using an object defined in a `.js` file as context key returns an `undefined` context
I actually stumbled on the first issue while trying to reproduce this one. I did manage to reproduce it on Stackblitz, but suddenly out of nowhere, the first issue appeared. So I guess I won't really have a repro for this one.

Using the [same Stackblitz as before](https://stackblitz.com/edit/github-zrwj6k-isnfa8?file=components%2FHello.svelte), `getContext` in `Hello.svelte` returned `undefined`. I figured out it was due to the `contextKey` being an object *and* being defined in another file (`context.ts`). If I change the value of `contextKey` to `export const contextKey = "myContext"`, it suddenly works perfectly (like in the Svelte REPL).
I guess Vitest is doing something with the imports which somehow redefines `contextKey`, thus making `contextKey === contextKey` false.

BTW using objects/symbols as context key *is* the [recommended way according to the Svelte doc](https://svelte.dev/tutorial/context-api).

### Reproduction

https://stackblitz.com/edit/github-zrwj6k-isnfa8?file=components%2Fcontext.ts

### System Info

```shell
Svelte
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Can you provide System Info? `Svelte` is not enough

`npx envinfo --system --npmPackages '{vitest,vite,@vitejs/*}' --binaries --browsers`

**Comment by AnatoleLucet** [comment]
Sure.
```
  System:
    OS: Linux 5.13 Manjaro Linux
    CPU: (10) x64 AMD Ryzen 7 3800X 8-Core Processor
    Memory: 20.99 GB / 23.95 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.18.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.4.1 - /usr/bin/npm
  Browsers:
    Firefox: 97.0
  npmPackages:
    vite: ^2.8.4 => 2.8.4 
    vitest: ^0.4.2 => 0.4.2 
```

I'm also unable to reproduce the first issue on my machine. It only appends on Stackblitz.

But after a bit more digging, I found out the second issue is caused by a circular dependency.
Here's a repro (you might want to try it on your local machine, because the first issue's still hiding the second one on Stackblitz):
https://stackblitz.com/edit/github-zrwj6k-ctpic7?file=components%2Fcontext.ts
As you can see, the `console.log` in `createSomeStuffWithMyContext` logs `undefined`.
I also added an `onMount` in `initContext` because I found out it never fires (even on my local machine), the `console.log('onMount')` is never logged.

I also updated the Svelte REPL (which seems to work fine with `createSomeStuffWithMyContext`): https://svelte.dev/repl/410523f9fbba4ce4b6adbf7bbd0b322d?version=3.46.4

**Comment by AnatoleLucet** [comment]
Just to sum up for easier reading:
-  `Function called outside component initialization` (only appears on stackblitz): https://stackblitz.com/edit/github-zrwj6k-ibjzfq?file=components%2Fcontext.ts
- Circular dependency makes `getContext` return `undefined` (needs to be tried on your local machine): https://stackblitz.com/edit/github-zrwj6k-ctpic7?file=components%2Fcontext.ts
- `onMount` called from another file doesn't seem to fire (needs to be tried on your local machine): https://stackblitz.com/edit/github-zrwj6k-jkftsn?file=components%2Fhello.ts

**Comment by sheremet-va** [comment]
> I'm also unable to reproduce the first issue on my machine. It only appends on Stackblitz.

I can't reproduce the second issue with object on Node 14.17 (with npm 6) and on Node 16.13.2 (with npm 8.1.2), but `onMounted` is not called on either of these

**Comment by userquin** [comment]
@sheremet-va stackblitz is using node 17:

![imagen](https://user-images.githubusercontent.com/6311119/154845600-20017fde-4ef4-4155-93e2-ef39e6892c3f.png)

**Comment by userquin** [comment]
@sheremet-va it is using node 14.17 and the error on local I'm trying to reproduce

**Comment by sheremet-va** [comment]
> > I'm also unable to reproduce the first issue on my machine. It only appends on Stackblitz.
> 
> I can't reproduce the second issue with object on Node 14.17 (with npm 6) and on Node 16.13.2 (with npm 8.1.2) - it logs `{ foo: 'bar' }`
> 
> But `onMounted` is not called on either of these

`onMounted` doesn't work because svelte is run in ssr mode.

**Comment by sheremet-va** [comment]
> @sheremet-va it is using node 14.17 and the error on local I'm trying to reproduce

Yes, I know, that's why I tried it.

**Comment by sheremet-va** [comment]
By default we are processing `.ts` files with ssr flag, `.svelte` so files are preccess without this flag. @AnatoleLucet add this to `test` config:

```ts
    transformMode: {
      web: [/\.svelte$/, /\.[jt]s$/]
    }
```

**Comment by userquin** [comment]
@sheremet-va your suggestion working also with node 16.13.0 (LTS)

**Comment by AnatoleLucet** [comment]
@sheremet-va seems like the `transformMode` resolves both the `onMount`, and `unefined` context issues. Thanks!
