### ISSUE TITLE
Date mock before module imported

### ISSUE THREAD

**Issue by maxsalven** [vitest-dev/vitest#810]
### Describe the bug

I have some Storybook stories where the component has a date prop, and the Storybook story provides today's date.

I'd like to mock these in vitest, however I'm not sure how.

I've tried using `vi.setSystemTime` in `setupFiles` but it doesn't work, and if I try in `globalSetup` I get an error (`Error: Vitest was initialized with native Node instead of Vite Node`).

Calling `MockDate.set("2017-01-01");` in `setupFiles` using the `mockdate` package works, but I'm wondering if there's a more vitest-y way to achieve this.

### Reproduction

https://github.com/maxsalven/vitest-mock-date/commit/7d1852128c721de56fcb6d15d3c78bc3b6983f51

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 539.47 MB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - /var/folders/0c/63_dh8t91pg75b9w6sktbpw80000gn/T/fnm_multishells/35332_1645333325565/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.2 - /var/folders/0c/63_dh8t91pg75b9w6sktbpw80000gn/T/fnm_multishells/35332_1645333325565/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Safari: 15.2
  npmPackages:
    @vitejs/plugin-react: ^1.2.0 => 1.2.0
    vite: latest => 2.8.4
    vitest: latest => 0.4.2
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
`vi.setSystemTime` is using `mockdate` under the hood, if you don't call `vi.useFakeTimers`, so I suggest just removing that call :)

**Comment by maxsalven** [comment]
Thanks, that does not seem to make the test past in the reproduction I linked to however.

**Comment by maxsalven** [comment]
Thanks, removing `useFakeTimers` and moving the `setSystemTime` call out of the `beforeAll` block worked.
