### ISSUE TITLE
Incorrect typing of test.each output

### ISSUE THREAD

**Issue by medihack** [vitest-dev/vitest#811]
### Describe the bug

There seems to be some incorrect typings of `test.each(...)`.

The following code
```
  test.each([
    [`<Card foo="alpha" bar='beta' />`, true],
    [`<Card foo="alpha" bar='beta'></Card>`, false],
  ])("can be parsed", (element, selfClosing) => {})
```
gives me `element` and `selfClosing` both of type `string | boolean`. I would expect `element` of type `string` and `selfClosing` of type `boolean`. Is it a (known) bug or my fault?

### Reproduction

Visit https://stackblitz.com/edit/vitest-dev-vitest-k9ye16?file=test%2Fbasic.test.ts&initialPath=__vitest__ and hover over both variables to view the type.

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Xeon(R) CPU @ 2.80GHz
    Memory: 5.77 GB / 62.81 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Aslemammad** [comment]
Let me investigate this!

**Comment by antfu** [comment]
You need to add `as const` - it's just how TypeScript works

```ts
test.each([
    [`<Card foo="alpha" bar='beta' />`, true],
    [`<Card foo="alpha" bar='beta'></Card>`, false],
  ] as const)("can be parsed", (element, selfClosing) => {})
```

**Comment by medihack** [comment]
@antfu Ok, thanks. Good to know. On the other side I don't have to do this in Jest. It just works there.

**Comment by antfu** [comment]
Good to know. Looks like we can do some type gymnastics here. Reference is here if someone want to pick it up.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/60cdd69ba4cabcc8518b126731c7f52fe962f223/types/jest/index.d.ts#L389-L405
