### ISSUE TITLE
Vitest not resolving test file from source-maps when running on compiled code

### ISSUE THREAD

**Issue by mikearnaldi** [vitest-dev/vitest#832]
### Describe the bug

In order to run vitest with other languages that compile to JS I was attempting a setup where vitest runs tests on compiled ESM code, in this scenario tests works as expected and source maps are loaded but the file of the test is not correctly linked back to the original generating an inconsistent report in case of errors.

### Reproduction

Repository: https://github.com/mikearnaldi/vitest-repro

Repro: `yarn build && yarn test`

As the following image shows the actual line number and column (21:17) are correct (so the source maps are processed) but file is resolved to the compiled file (`build/esm/test/basic.test.js`) producing an incorrect output

![Screenshot 2022-02-21 223300](https://user-images.githubusercontent.com/24249610/155033722-dde9d660-dc62-40e5-b776-f9e05000f7ac.png)

For simplicity the repository uses compiled typescript code (to avoid introducing any unknown languages in the equation)

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Xeon(R) CPU @ 2.80GHz
    Memory: 24.79 GB / 62.81 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 3.1.1 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  npmPackages:
    vite: ^2.7.13 => 2.7.13 
    vitest: ^0.2.5 => 0.2.5
```
```


### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by pesterhazy** [comment]
I'm running into the same issue when running tests compiled from ClojureScript via shadow-cljs. Instead of showing the original source, the compiled output is shown:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/106328/176520589-2048b51f-8cb8-408f-aceb-0013c85f8ded.png">

**Comment by sheremet-va** [comment]
> I'm running into the same issue when running tests compiled from ClojureScript via shadow-cljs. Instead of showing the original source, the compiled output is shown:

Please, create a separate issue with reproduction.
