### ISSUE TITLE
Unable to read .env

### ISSUE THREAD

**Issue by gemone** [vitest-dev/vitest#834]
### Describe the bug

`vitest` can not read `.env.dev`.

define `VITE_TEST_STR=global` in `.env`;

define `VITE_TEST_STR=dev` in `.env.development`;

but `vitest` can not read `dev` in `dev mode`.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-bguh8h?file=test/env.test.ts

### System Info

```shell
System:
    OS: Linux 5.10 Gentoo/Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 1.13 GB / 7.68 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 14.17.6 - /usr/bin/node
    Yarn: 1.22.15 - ~/.local/share/npm/bin/yarn
    npm: 8.4.1 - ~/.local/share/npm/bin/npm
  Browsers:
    Firefox: 91.6.0esr
  npmPackages:
    vite: ^2.8.3 => 2.8.3 
    vitest: ^0.5.1 => 0.5.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest sets mode to test. If you need to redefine it, use --mode or define mode property on Vite config.
