### ISSUE TITLE
Option to disable coloured output

### ISSUE THREAD

**Issue by robcaldecott** [vitest-dev/vitest#841]
### Clear and concise description of the problem

When running tests on CI (in our case Bamboo) the default output is in colour which causes some ugly output when viewing the raw logs:

![image](https://user-images.githubusercontent.com/796702/155363514-ce626dbb-9023-4ca1-97a5-131117fca558.png)

### Suggested solution

Peraps disable colours when `CI=true` or add a new CLI option to do so.

### Additional context

We're running tests for CI like this:

```
CI=true vitest run --coverage
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by robcaldecott** [comment]
Oh perfect, thanks @Demivan !

**Comment by Demivan** [comment]
If this works you can close the issue
