### ISSUE TITLE
Issue with 3rd party library loading vitest.

### ISSUE THREAD

**Issue by urkle** [vitest-dev/vitest#843]
### Describe the bug

I have a 3rd party library [vitest-plugins](https://github.com/OutOfOrder/vitest-plugins) where I am utilizing the vitest-plugin-set and vitest-plugin-context.   Now within the context of that repository everything works great.  
However when I try to pull that into another repository things fall apart.

Specifically I get this error "Vitest was initialized with native Node instead of Vite Node"

I have a vite-driven project (vue3 based) with some tests that work fine under vitest (0.5.4)

### Reproduction

The pre-amble is as follows (which works)

```javascript
import { describe, it, expect, beforeEach } from 'vitest';
import { describe as context } from 'vitest';
import { setActivePinia, createPinia } from 'pinia';
import { useMeetings } from '../meetings';
```

But when I switch it to this
```javascript
import { describe, it, expect, beforeEach } from 'vitest';
import { context } from 'vitest-plugin-context';
import { set } from 'vitest-plugin-set';
import { setActivePinia, createPinia } from 'pinia';
import { useMeetings } from '../meetings';
```

It fails with that error on which ever `plugin` is first. (both plugins pull in vitest, the first to pull in `describe` the second to pull in `beforeEach` and `afterEach`).  

1) how to I get more tracing information to figure out why this error is being thrown?
2) (once we answer 1) how to do we get this working correctly in the `plugin`.

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 16.18 GB / 64.00 GB
    Shell: 5.1.16 - /opt/local/bin/bash
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.17 - /opt/local/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
    Watchman: 0.0.0 - /opt/local/bin/watchman
  npmPackages:
    @vitejs/plugin-vue: ^2.2.2 => 2.2.2 
    vite: ^2.8.4 => 2.8.4 
    vitest: ^0.5.4 => 0.5.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You need to use `deps.inline` in your config, because Vitest imports need to be preprocessed.

**Comment by sheremet-va** [comment]
Also I would recommend changing the name `plugins` to something else, since it clashes with Vite `plugins` and creates confusion

**Comment by urkle** [comment]
> You need to use `deps.inline` in your config, because Vitest imports need to be preprocessed.

What value to I put there?  I've tried several things and I continually get the same error.

**Comment by urkle** [comment]
So, the "docs" for deps.inline talk about "when distributing a package as ES modules" which is the ONLY way I can distribute these plugins.  As they pull in vitest which only exports ES modules.

**Comment by sheremet-va** [comment]
> > You need to use `deps.inline` in your config, because Vitest imports need to be preprocessed.
> 
> What value to I put there? I've tried several things and I continually get the same error.

`/vitest-plugins/` should work

**Comment by urkle** [comment]
@sheremet-va thanks.. that worked.
