### ISSUE TITLE
Cannot spyOn default export of module

### ISSUE THREAD

**Issue by AndrewLeedham** [vitest-dev/vitest#855]
### Describe the bug

In Jest a common pattern for me was to `spyOn` the `default` export of a module. This no longer works in vitest. It throws the following error:
```
TypeError: Cannot redefine property: default
 ❯ eval test/suite.test.ts:5:16
      3| import b from '../src/b';
      4| 
      5| const aSpy = vi.spyOn(a, 'default');
       |                ^
      6| 
      7| describe('suite name', () => {
```

I get the feeling this is a limitation of ESM, a work around seems to be:
```
vi.mock('path/to/module', async () => {
  const actual = await requireActual('path/to/module');
  const mocked = {};
  for (const key of Object.keys(actual)) {
    if (typeof actual[key] === 'function') {
      mocked[key] = vi.fn(actual[key]);
    } else {
      mocked[key] = actual[key];
    }
  }
  return mocked;
})

import module from 'path/to/module';

const moduleSpy = vi.mocked(module);
```
However, this is a lot of code to include for every spy, so perhaps there could be an API like `vi.spyOnModule` that would automate this, so I could just do:

```
const moduleSpy = vi.spyOnModule('/path/to/module');
```

### Reproduction

I created a reproduction here: https://stackblitz.com/edit/vitest-dev-vitest-6igo9o?file=test/suite.test.ts

> Side note: the latest release (0.5.5) seems to have a regression where it does not show the error message, this seems to be because it checks for calls to `it`/`test` to detect if the file has tests. However, because `vi.spyOn` is failing before those tests are defined, the error message gets suppressed. Hence why I downgraded to `0.5.4` in the repro.

### System Info

```shell
System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 39.41 MB / 16.00 GB
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 98.0.4758.109
    Edge: 98.0.1108.62
    Firefox: 94.0.1
    Safari: 14.0.3
  npmPackages:
    @vitejs/plugin-react: ^1.2.0 => 1.2.0 
    vite: 2.8.3 => 2.8.3 
    vitest: 0.3.5 => 0.3.5
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by rszemplinski** [comment]
Thank you for posting your solution. I spent hours trying to get this to work to no avail but I got your solution to work for me right away

**Comment by sheremet-va** [comment]
You can also inline the module you are trying to import with `deps.inline: [/path-to-module/]`. This will basically do what your workaround does.

**Comment by nieyuyao** [comment]
@konpeki622 `tinyspy` tried to redefine descriptor, so an error occurred.

**Comment by sheremet-va** [comment]
Fixed by https://github.com/vitejs/vite/issues/8566
