### ISSUE TITLE
Snapshots are rendered with an extra " causing all other quotes to be esaped

### ISSUE THREAD

**Issue by LanFeusT23** [vitest-dev/vitest#856]
### Describe the bug

Rendered snapshots have a double quote `"` added immediately after the first ``` ` ``` (or `'` for inline snapshots, which feels wrong too?).

This occurs with no UI framework at all, as well as with Vue 3, using composition API and `script setup`. I haven't tested other frameworks but since it happens without an it probably happens with all of them.

This causes all snapshots to be escaped with `\\` everywhere making them much harder to read and compare.

Reproduced here: https://stackblitz.com/edit/vitejs-vite-pdqfzn

### Reproduction

1. Install vite `npm create vite@latest`
2. Add a test that will render snapshots:
```
import { test, it, describe, expect } from 'vitest';

describe('App', () => {
  it('should render the html inline', () => {
    expect(`<div class="test">Hello World</div>`).toMatchInlineSnapshot(
      '"<div class=\\"test\\">Hello World</div>"'
    );
  });

  it('should render the html in a snapshot file', () => {
    expect(`<div class="test">Hello World</div>`).toMatchSnapshot();
  });
});
```
=> snapshots are rended with `\\` everywhere to escape quotes.

### System Info

```shell
System:
    OS: Linux 5.4 Amazon Linux 2
    CPU: (16) x64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
    Memory: 18.33 GB / 62.79 GB
    Container: Yes
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Browsers:
    Firefox: support!
Mozilla Firefox 78.11.0esr
  npmPackages:
    @vitejs/plugin-vue: ^2.1.0 => 2.1.0 
    vite: ^2.7.13 => 2.7.13 
    vitest: ^0.5.3 => 0.5.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by robokozo** [comment]
I'm seeing this behavior too. It'd be great if the snapshots could contain as little code as possible. In my particular case, I often copy paste snapshots from code-reviews into something like https://play.tailwindcss.com/ for verification

**Comment by sheremet-va** [comment]
I see jest has the same behaviour. So, these are correct snapshots by default.

Did you previously use any snapshot options to not put strings inside `"`?

**Comment by robokozo** [comment]
I just used the vue-cli v5 to bootstrap an app with jest tests configured. This is what the snapshot looks like:

```
exports[`HelloWorld.vue renders props.msg when passed 1`] = `
<div class="hello">
  <h1>new message</h1>
  <p> For a guide and recipes on how to configure / customize this project,<br> check out the <a href="https://cli.vuejs.org" target="_blank" rel="noopener">vue-cli documentation</a>. </p>
  <h3>Installed CLI Plugins</h3>
  <ul>
    <li><a href="https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-babel" target="_blank" rel="noopener">babel</a></li>
    <li><a href="https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-unit-jest" target="_blank" rel="noopener">unit-jest</a></li>
  </ul>
  <h3>Essential Links</h3>
  <ul>
    <li><a href="https://vuejs.org" target="_blank" rel="noopener">Core Docs</a></li>
    <li><a href="https://forum.vuejs.org" target="_blank" rel="noopener">Forum</a></li>
    <li><a href="https://chat.vuejs.org" target="_blank" rel="noopener">Community Chat</a></li>
    <li><a href="https://twitter.com/vuejs" target="_blank" rel="noopener">Twitter</a></li>
    <li><a href="https://news.vuejs.org" target="_blank" rel="noopener">News</a></li>
  </ul>
  <h3>Ecosystem</h3>
  <ul>
    <li><a href="https://router.vuejs.org" target="_blank" rel="noopener">vue-router</a></li>
    <li><a href="https://vuex.vuejs.org" target="_blank" rel="noopener">vuex</a></li>
    <li><a href="https://github.com/vuejs/vue-devtools#vue-devtools" target="_blank" rel="noopener">vue-devtools</a></li>
    <li><a href="https://vue-loader.vuejs.org" target="_blank" rel="noopener">vue-loader</a></li>
    <li><a href="https://github.com/vuejs/awesome-vue" target="_blank" rel="noopener">awesome-vue</a></li>
  </ul>
</div>
`;
```

**Comment by sheremet-va** [comment]
> I just used the vue-cli v5 to bootstrap an app with jest tests configured. This is what the snapshot looks like:
> 
> ```
> exports[`HelloWorld.vue renders props.msg when passed 1`] = `
> <div class="hello">
>   <h1>new message</h1>
>   <p> For a guide and recipes on how to configure / customize this project,<br> check out the <a href="https://cli.vuejs.org" target="_blank" rel="noopener">vue-cli documentation</a>. </p>
>   <h3>Installed CLI Plugins</h3>
>   <ul>
>     <li><a href="https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-babel" target="_blank" rel="noopener">babel</a></li>
>     <li><a href="https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-unit-jest" target="_blank" rel="noopener">unit-jest</a></li>
>   </ul>
>   <h3>Essential Links</h3>
>   <ul>
>     <li><a href="https://vuejs.org" target="_blank" rel="noopener">Core Docs</a></li>
>     <li><a href="https://forum.vuejs.org" target="_blank" rel="noopener">Forum</a></li>
>     <li><a href="https://chat.vuejs.org" target="_blank" rel="noopener">Community Chat</a></li>
>     <li><a href="https://twitter.com/vuejs" target="_blank" rel="noopener">Twitter</a></li>
>     <li><a href="https://news.vuejs.org" target="_blank" rel="noopener">News</a></li>
>   </ul>
>   <h3>Ecosystem</h3>
>   <ul>
>     <li><a href="https://router.vuejs.org" target="_blank" rel="noopener">vue-router</a></li>
>     <li><a href="https://vuex.vuejs.org" target="_blank" rel="noopener">vuex</a></li>
>     <li><a href="https://github.com/vuejs/vue-devtools#vue-devtools" target="_blank" rel="noopener">vue-devtools</a></li>
>     <li><a href="https://vue-loader.vuejs.org" target="_blank" rel="noopener">vue-loader</a></li>
>     <li><a href="https://github.com/vuejs/awesome-vue" target="_blank" rel="noopener">awesome-vue</a></li>
>   </ul>
> </div>
> `;
> ```

Can you show what is passed to `expect`, when you call `toMatchSnapshot`?

**Comment by sheremet-va** [comment]
> Can you show what is passed to `expect`, when you call `toMatchSnapshot`?

nvm, I see `vue-cli` uses this serializer: https://www.npmjs.com/package/jest-serializer-vue

But I don't think we support serializers at the moment

**Comment by sheremet-va** [comment]
> But I don't think we support serializers at the moment

Right when I sent it, I found we have `expect.addSnapshotSerializer`. You can try passing [jest-serializer-vue](https://www.npmjs.com/package/jest-serializer-vue) to it, but I guess we also need to expose it as an option for easier install

**Comment by sheremet-va** [comment]
> > But I don't think we support serializers at the moment
> 
> Right when I sent it, I found we have `expect.addSnapshotSerializer`. You can try passing [jest-serializer-vue](https://www.npmjs.com/package/jest-serializer-vue) to it, but I guess we also need to expose it as an option for easier install

Or I guess we can inline them, since we have `ReactPlugin` for serializer - why don't add Vue? Since we are so close to it. @antfu what do you think?

**Comment by jagoncalves14** [comment]
@sheremet-va, @LanFeusT23, I was just about to open the same exact issue here on GitHub.

I'm working on a project where we are migrating from **Webpack+Jest** to **Vite+Vitest**.
Everything has been almost seemless so far, except for snapshots.

Just like @LanFeusT23 mentioned, between Jest and Vitest there are two "major" differences in the snapshot file that gets generated.

### **1. In Vitest, the snapshots contain a lot of //'s**

I have just put up two basic Stackblitz examples to compare between Jest and Vitest.
In Jest, the snapshots gets saved like the following:

```
`<div class="title">Hello World</div>`
```
[(Check Stackblitz Demo)](https://stackblitz.com/edit/vue-jest-demo?file=src%2Fcomponents%2F__snapshots__%2FHelloWorld.spec.js.snap)

While in Vitest, they're saved like this:
```
`"<div class=\\"title\\">Hello World</div>"`
```
[(Check Stackblitz Demo)](https://stackblitz.com/edit/vue-vitest-demo?file=src%2Fcomponents%2F__snapshots__%2FHelloWorld.spec.ts.snap)

There are two differences:
1. In Vitest, the whole HTML is wrapped around a double-quoted string;
2. Because of that, all double-quoted-strings are being escaped with `//`
(This is all what @LanFeusT23 have already pointed out)


### **2. In Vitest, the name of the module export for each snapshot is also different from Jest**

When tests are nested within describe and it/test functions, Vitest separates them with a `> `. I think that's cool, but it'd be even better if that could be, somehow, optional.
The reason for this is when we are migrating from Jest to Vitest, when running the snapshots, due to the fact that the snapshots come out with a different name, the CLI will not directly compare the snapshots for a replacement - it will assume that it is a new one that is being created from scratch.

Any chance of having any config option to change this?

**Comment by antfu** [comment]
@jagoncalves14 

### 1.

It's actually matched with Jest's **default** behavior. The quotes are added to distinguish strings and values. The behavior you see is is because the vue-cli presets include `jest-serializer-vue` which removes the quotes for HTML-like strings: https://github.com/eddyerburgh/jest-serializer-vue/blob/master/index.js

Like @sheremet-va mentioned, we do have `expect.addSnapshotSerializer` API that you might be able to pass the custom serializer to it. (tho I would doubt if [the HTML check](https://github.com/eddyerburgh/jest-serializer-vue/blob/600b2c0e68e4a15c113d22beb10d706947e7409a/index.js#L3) is sound enough)

### 2.

Currently, there is no way to configure it. Even tho Vitest is trying to make migration from Jest as easier as possible, they are still two different frameworks and we can't align everything with Jest. In this case, I would recommend removing the snapshot files and letting Vitest generate new ones so you can compare them with git's diff.

**Comment by jagoncalves14** [comment]
@antfu, thanks for the reply!

### **1.** 
You're totally right, I was missing the `jest-serializer-vue` and was able to add it using the `expect.addSnapshotSerializer`. I created my own serializer based on `jest-serializer-vue` one. Needed some extra replacements to remove any attributes that was bringing unique IDs.

For anyone that is interested and might find it useful, here is the code for that serializer:

```
// tests/vitest-serializer-vue.ts

import { ComponentPublicInstance } from 'vue'
import { VueWrapper } from '@vue/test-utils'
import beautify from 'pretty'

const isHtmlString = (received: string) => received && typeof received === 'string' && received[0] === '<'
const isVueWrapper = (received: VueWrapper<ComponentPublicInstance<any>>) =>
  received && typeof received === 'object' && typeof received['isVueInstance'] === 'function'
const removeServerRenderedText = (html: string) => html.replace(/ data-server-rendered="true"/, '')
const removeDataTestAttributes = (html: string) => html.replace(/ data-test="[-\w]+"/g, '')
const removeUniqueAttributes = (html: string) =>
  html
    .replace(/ data-server-rendered="true"/g, '')
    .replace(/ data-v-[-\w]+=""/g, '')
    .replace(/ data-test="[-\w]+"/g, '')
    .replace(/"el-tooltip-\d*"/g, '""')
    .replace(/"el-popper-\d*"/g, '""')
    .replace(/"el-popover-\d*"/g, '""')
    .replace(/"el-autocomplete-\d*"/g, '""')
    .replace(/"el-autocomplete-\d*\-item--\d*"/g, '""')
    .replace(/"el-collapse-head-\d*"/g, '""')
    .replace(/"el-collapse-content-\d*"/g, '""')
    .replace(/"dropdown-menu-\d*"/g, '""')
    .replace(/"line-chart-\w*(-\w*)*"/g, '""')
    .replace(/progress-circle-component__LinearGradient-\d*/g, '')
    .replace(/style=\"z-index: .*;\"/gi, '')
    .replace(/div-gpt-ad-\d*-\d*/g, '')

export default {
  test(received: any) {
    return isHtmlString(received) || isVueWrapper(received)
  },
  print(received: any) {
    let html = (isVueWrapper(received) ? received.html() : received) || ''
    html = removeServerRenderedText(html)
    html = removeDataTestAttributes(html)
    html = removeUniqueAttributes(html)

    return beautify(html, { indent_size: 2 })
  },
}

```

And on my setup file for Vitest's config, I added the following:
```
import vueSnapshotSerializer from 'test/vitest-serializer-vue'

// Add Snapshot Serializer
expect.addSnapshotSerializer(vueSnapshotSerializer)
```

### **2.**
I just thought that it could be a feature that could possibly attract more people to make the change from **Jest** to **Vitest**. 
On large applications/codebases, this could be something that can frighten people to do this change. 
Although, at the same time, I completely understand that this would never be something on the top of the priorities right now 👌 
Maybe something to think of for the future 😄

I'll be moving on with the migration by updating all the snapshots and compare them through git's diff, just like you suggested.

I appreciate all the help! Keep up the great work!

**Comment by sheremet-va** [comment]
I'm not sure if this is safe to do in Vitest core, since frontend unit testing is not it's only goal. We will mention it in Migration Guide tho.
