### ISSUE TITLE
Console UI support ANSI color

### ISSUE THREAD

**Issue by okxiaoliang4** [vitest-dev/vitest#857]
### Clear and concise description of the problem

console can't support ANSI color now.

### Suggested solution

maybe we can add [ansi-to-html](https://github.com/rburns/ansi-to-html) dependencies. or I can fork this and deletion some features.

```typescript
import Filter from 'ansi-to-html'

function formatConsoleLog(log: string) {
  const filter = new Filter()
  return filter.toHtml(log)
}
```
```html
<pre v-html="formatConsoleLog(log.content)" />
```

### Additional context

before: 
![image](https://user-images.githubusercontent.com/22525904/155767419-4e02486c-80a2-45ff-be28-e28f6329f384.png)

after:
![image](https://user-images.githubusercontent.com/22525904/155768776-9190151d-9392-4e88-8b77-20f353626bca.png)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by edimitchel** [comment]
Nice suggestion, if you are confortable to raise a PR, feel free, I can help you by reviewing your changes.

**Comment by craciuncezar** [comment]
I think we should we consider this for the reporter error as well, I noticed the same problem for the HTML in `@testing-library/dom` errors.

<img width="884" alt="Screenshot 2022-03-19 at 23 16 35" src="https://user-images.githubusercontent.com/27342306/159138801-781216d1-7e29-46df-a4cf-6c83cb5fd091.png">

**Comment by linux-china** [comment]
Same problem?  no color output to call `vitest test`, but it works well  with command wrapped by npm. 

![image](https://user-images.githubusercontent.com/46711/160220836-4650335d-d48e-4c3b-a90f-9f9216701d7f.png)

**Comment by userquin** [comment]
on ui it works (octal notation cannot be used on template strings):

![imagen](https://user-images.githubusercontent.com/6311119/161815793-a2f38a0f-3345-46ef-b1de-be94c65ac289.png)


![imagen](https://user-images.githubusercontent.com/6311119/161815638-c9ad478a-aef1-46fa-a212-f713305498c9.png)
