### ISSUE TITLE
Support ''use strict''

### ISSUE THREAD

**Issue by pikax** [vitest-dev/vitest#863]
### Clear and concise description of the problem

'use strict'  is useful for tests

```ts
// works on jest but not on vitest
test('should throw',()=>{ 
  const o = { id: 1}
  Object.defineProperty(o, 'id', {writable: false, configurable: false})
  
  expect(()=>o.id = 42).toThrowError(TypeError)
})
```

HTML script example/JSFiddle: 
```js
'use strict';

const o = { id: 1}

Object.defineProperty(o, 'id', {writable: false, configurable: false})

try {
  o.id = 23
  document.body.innerHTML = 'Not throwing exception'
} catch(e){
 document.body.innerHTML = `Comment 'use strict': ${e}`
}
```

https://stackblitz.com/edit/vitest-dev-vitest-5ta2zd?file=test/basicStrict.test.js

### Suggested solution

Respect 'use strict' on the file and allow set global strict on the `config`

### Alternative

There's a workaround, but is more tedious:

```ts
test('should freeze'){
  const o = { id: 1}

  Object.defineProperty(o, 'id', {writable: false, configurable: false})

  //expect(()=>o.id = 42).toThrowError(TypeError)

  o.id = 42
  expect(o.id).toBe(1)
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Isn't ESM strict by default?

**Comment by pikax** [comment]
> Isn't ESM strict by default?

The test is not passing, based on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty 
```ts
const object1 = {};

Object.defineProperty(object1, 'property1', {
  value: 42,
  writable: false
});

object1.property1 = 77;
// throws an error in strict mode

console.log(object1.property1);
// expected output: 42
```

That's my only explanation for the test not passing :D



> Should Vitest just prepend `'use strict'` when running tests?

On stackblitz code I added `use strict` and still not working
