### ISSUE TITLE
AssertionError with extra `Array` when using `toHaveBeenCalledWith `

### ISSUE THREAD

**Issue by runyasak** [vitest-dev/vitest#870]
### Describe the bug

Hi, I get an assertion error when using Vitest with my project, porting from Vue 2 + Jest to Vue 3 + Vitest.

### Reproduction

https://github.com/poorprogrammer/cfo/commit/0a726fcc93a578cfd10d44c6201f4c50c5e2a9bf#diff-c6d94278ab82b9448cd838edb7697c8349a8c27e8f5c24daf896c50a95b72824R18

This is part of code from my senior repository.

* `presenters/__tests__/Login.spec.js`

```
import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { LoginPresenter } from "@/presenters/Login";

class MockView {
  goTo() { }
}

describe("Login Presenter", () => {
  let p = new LoginPresenter(new MockView());

  const jsdomAlert = window.alert;
  beforeEach(() => {
    window.alert = vi.fn();
  });
  afterEach(() => {
    window.alert = jsdomAlert;
  });

  /* ...... */

  it("should redirect to home page after login success", async () => {
    givenLoginSuccess();
    await p.login();
    expectToRedirectToHomePage(p.view);
  });
  /* ...... */

  function expectToRedirectToHomePage(view) {
    expect(view.goTo).toHaveBeenCalledWith({ name: "home" });
  }
});
```

* `presenters/Login.js`

```
import API from "@/services/login";
export default class {
  constructor(view) {
    this.view = view;
    this.API = new API();
  }
  login() {
    this.API.login(this.username, this.password)
      .then((token) => {
        localStorage.setItem("token", token)
        this.view.goTo({name: 'home'})
      }, (error) => {
        this.showError(error);
      });
  }
  showError(error) {
    alert(error)
  }
}
```

When run test with `npm run test`, get error like this:

```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  src/presenters/__tests__/Login.spec.js > Login Presenter > should redirect to home page after login success
AssertionError: expected "goTo" to be called with arguments: [ { name: 'home' } ]
 ❯ expectToRedirectToHomePage src/presenters/__tests__/Login.spec.js:50:23
     48|   }
     49|   function expectToRedirectToHomePage(view) {
     50|     expect(view.goTo).toHaveBeenCalledWith({ name: "home" });
       |                       ^
     51|     // expect(view.goTo).toHaveBeenCalled();
     52|   }
 ❯ src/presenters/__tests__/Login.spec.js:29:5

  - Expected  - 3
  + Received  + 5
  
    Array [
  -   Object {
  -     "name": "home",
  -   },
  +   Array [
  +     Object {
  +       "name": "home",
  +     },
  +   ],
    ]

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

Test Files  1 failed (1)
Tests  1 failed | 3 skipped (4)
Time  2.86s (in thread 3ms, 85531.79%)
```

**Full Repository:** https://github.com/poorprogrammer/cfo/tree/upgrade-vue/web-new

I apologize for last time with posting on duplicated issue.
If you have any feedback or suggestions to resolve this error, please let us know.

Thank you

### System Info

```shell
System:
    OS: macOS 11.5.1
    CPU: (8) arm64 Apple M1
    Memory: 82.58 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 98.0.4758.109
    Safari: 14.1.2
  npmPackages:
    @vitejs/plugin-vue: ^2.2.2 => 2.2.2
    vite: ^2.8.4 => 2.8.4
    vitest: ^0.5.4 => 0.5.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by togami2864** [comment]
It seems that the execution of `this.view.goTo({name: 'home'})` in `Login.js` is failing :thinking:

It just looks like there is an extra array because it happens to have one argument.
The reason for the object which has an extra array in the error statement is that the function may take more than one argument. 

If `goTo` is defined like
```
goTo({name: 'home'}, foo)
```
the error would  throw like this.
```
AssertionError: expected "goTo" to be called with arguments: [ { name: 'home' } , foo]
```

**Comment by TrickyPi** [comment]
I ran into the `[Function goTo] is not a spy or a call to a spy!` error, could you try the following code?
```js
class MockView {
  goTo = vi.fn();
}
```

**Comment by juacompe** [comment]
> I ran into the `[Function goTo] is not a spy or a call to a spy!` error, could you try the following code?
> 
> ```js
> class MockView {
>   goTo = vi.fn();
> }
> ```

I tried and get `Parsing error: Unexpected token =` from eslint.

The `goTo` method was left empty because it is going to be spied on during the test. See the code below

```
  function givenLoginSuccess(res) {
    vi.spyOn(p.view, 'goTo')
    vi.spyOn(p.API, 'login').mockResolvedValue(res)
  }
```

I expect `p.view` to contain an instance of `MockView`.

**Comment by juacompe** [comment]
I have created a minimal reproducible example here https://github.com/juacompe/vitest-spy-on

run `npm run test:unit` to reproduce the error. I expect the test to pass.

Any comments or suggestions would be highly appreciated.

**Comment by juacompe** [comment]
I found that calling `p.view.goTo` directly would pass the test. But I still don't understand why.

```
  it("should redirect to home page after login success", async () => {
    givenLoginSuccess();
    // await p.login();
    p.view.goTo({ name: "home" });
    expectToRedirectToHomePage(p.view);
  });
```

**Comment by juacompe** [comment]
I found that without mocking API, the test also pass. See <https://github.com/juacompe/vitest-spy-on/commit/abd7efe1ed7852337b355b317248f96bd42767ee>

**Comment by SevenOutman** [comment]
Similar problem here. 

I was testing a React component and had an assertion like:

```js
expect(Component).toHaveBeenCalledWith(props);
```

The assertion failed and displayed message as shown below
    
<img width="488" alt="image" src="https://user-images.githubusercontent.com/8225666/160326064-803691fa-cf4f-44d5-b163-8bc643db7c06.png">

According to the message, `Component` was called with a `props` that had been an Array, but the real reason was `Component` had been called with not only `props` but also a `context` argument, which means a Component call was like

```js
Component(props, context)
```

Changed my assertion to 

```js
expect(Component).toHaveBeenCalledWith(props, expect.anything());
```

and test passed.

Apparently the diff message was miss-formatted with an extra nested Array.
