### ISSUE TITLE
Clear `vi.mock` calls when `clearMocks` is enabled

### ISSUE THREAD

**Issue by AndrewLeedham** [vitest-dev/vitest#872]
### Clear and concise description of the problem

The `clearMocks` config option currently only clears spies (which the documentation does state). I was expecting it to also clear mocks via `vi.mock` as the option does in Jest.

### Suggested solution

Clear both spies and mocks when `clearMocks` is enabled.

### Alternative

I can manually clear the mocks as a workaround, would just be nice to have a global option.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
You mean it resets values or just clears spies inside a mock?

```ts
test('1', async () => {
  const mocked = await import('./path')
  expect(mocked.object.deep).toBe(1)
  mocked.object.deep = 3
  expect(mocked.object.deep).toBe(3)
})
test('2, async () => {
  const mocked = await import('./path')
  expect(mocked.object.deep).toBe(1) // right now will fail here
  mocked.object.deep = 3
  expect(mocked.object.deep).toBe(3)
})
```

**Comment by AndrewLeedham** [comment]
I am meaning for call counts. So:
```javascript
test('1', async () => {
  const mocked = await import('./path')
  expect().toBe(1)
  mocked.object.deep = 3
  expect(mocked.object.deep).toBe(3)
})

test('2', async () => {
  const mocked = await import('./path')
  expect(mocked.object.deep).toBe(1) // right now will fail here
  mocked.object.deep = 3
  expect(mocked.object.deep).toBe(3)
})
```

**Comment by sheremet-va** [comment]
Cannot reproduce it. Can you confirm it is still broken?

**Comment by AndrewLeedham** [comment]
@sheremet-va Seems to be fixed now thanks: https://stackblitz.com/edit/vitest-dev-vitest-ichkoe?file=src/code.test.ts
