### ISSUE TITLE
Huge debugging improvement (show enumerable error properties)

### ISSUE THREAD

**Issue by aalexgabi** [vitest-dev/vitest#884]
### Clear and concise description of the problem

Error enumerable properties are not shown for test case:
```
import { test } from 'vitest';

test('throw error with context', () => {
  const err = new Error('This is an error with context');
  err.userId = 32;
  err.companyId = 64;
  throw err;
})
```

![image](https://user-images.githubusercontent.com/600821/156337522-c37b328b-6b28-407a-a634-ef3bd4570edf.png)

### Suggested solution

Show enumerable properties on errors as node does by default:
![image](https://user-images.githubusercontent.com/600821/156337855-e1be743a-c3ce-4e95-a942-ba011a231372.png)

### Alternative

At the very least please add an option to opt in for this behavior.

### Additional context

When calling a function transformSomething(array) the function might have many iterations inside but one iteration will fail becaue the item may be invalid. It's very useful when throwing an error, especially for logging to specify which iteration failed. 

For more context here is the equivalent issue for chromium dev tools console https://bugs.chromium.org/p/chromium/issues/detail?id=1251322&q=enumerable&can=2

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Resolved in https://github.com/vitest-dev/vitest/pull/1202
