### ISSUE TITLE
command option --mode results in 'true' instead of the value you try to set

### ISSUE THREAD

**Issue by awacode21** [vitest-dev/vitest#886]
### Describe the bug

According to the docs https://vitest.dev/guide/#options there is a command option `--mode `(as it is for vite) wherewith you could overwrite the mode. But when doing so it does not take the value you provide, instead it gets the value `true`

### Reproduction

Try to set command option --mode and check the resulting value of the defineConfig function params.

Default:
`{ mode: 'test', command: 'serve' }`

trying to overwrite :
`vitest --mode production`

results in
`{ mode: true, command: 'serve' }`

instead of
`{ mode: 'production', command: 'serve' }`

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Apple M1
    Memory: 26.54 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 98.0.4758.109
    Firefox: 97.0.1
    Safari: 15.2
  npmPackages:
    @vitejs/plugin-vue: 2.2.2 => 2.2.2
    vite: 2.8.4 => 2.8.4
    vitest: ^0.5.9 => 0.5.9
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by awacode21** [comment]
yes i know, i tried --mode production, but the result is not production, it is 'true'

or does it need to be --mode <production> ?

**Comment by sheremet-va** [comment]
> yes i know, i tried `--mode production`, but the result is not production, it is 'true'
> 
> or does it need to be `--mode <production> `?

I mean this is Vitest bug. `--mode` should be rewritten to `--mode <name>`
PR welcome

**Comment by awacode21** [comment]
@togami2864 you were faster than me open a PR. Thank you very much

**Comment by awacode21** [comment]
it got merged but not released. When will the next release containing the fix will take part?

**Comment by awacode21** [comment]
perfectly working
