### ISSUE TITLE
Test element-plus project, Cannot find module xxx , Did you mean to import xxx.js?

### ISSUE THREAD

**Issue by l-x-f** [vitest-dev/vitest#892]
###  Test element-plus project, Cannot find module xxx , Did you mean to import xxx.js? 

`login.test.ts`
```ts
import { describe, it, expect } from 'vitest'
import ElementPlus from 'element-plus'
import { mount } from '@vue/test-utils'
import login from '@/views/login/index.vue'

describe('login', () => {
  it('renders properly', () => {
    const wrapper = mount(login, {
      global: {
        plugins: [ElementPlus]
      }
    })
    expect(wrapper.get('.login-title')).toContain('login')
  })
})

```

```
$ yarn test
yarn run v1.22.11
$ vitest --environment jsdom

 RUN  v0.5.9 E:/study-projects/tests

 ❯ tests/login.test.ts (0)

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Suites 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
 FAIL  tests/login.test.ts [ tests/login.test.ts ]
Error: Cannot find module 'E:\study-projects\tests\node_modules\dayjs\plugin\customParseFormat' imported from E:\study-projects\tests\node_modules\element-plus\es\components\date-picker\src\date-picker.mjs
Did you mean to import dayjs/plugin/customParseFormat.js?
 ❯ new NodeError ../../../internal/errors.js:322:7
 ❯ finalizeResolution ../../../internal/modules/esm/resolve.js:308:11
 ❯ moduleResolve ../../../internal/modules/esm/resolve.js:731:10
 ❯ Loader.defaultResolve [as _resolve] ../../../internal/modules/esm/resolve.js:842:11
 ❯ Loader.resolve ../../../internal/modules/esm/loader.js:89:40
 ❯ Loader.getModuleJob ../../../internal/modules/esm/loader.js:242:28
 ❯ ModuleWrap.<anonymous> ../../../internal/modules/esm/module_job.js:76:40
 ❯ link ../../../internal/modules/esm/module_job.js:75:36

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

Test Files  1 failed (1)
     Tests  no tests
      Time  10.33s (in thread 0ms, Infinity%)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproduction

[https://github.com/l-x-f/vitest-demo](https://github.com/l-x-f/vitest-demo)

### System Info

```shell
system：Windows 10 家庭中文版 21H2 19044.1526
node:v14.18.0
yarn：1.22.11

"typescript": "^4.5.4"
"vite": "^2.8.0"
"vitest": "^0.5.9"
"vue-tsc": "^0.29.8"
"element-plus": "^2.0.4"
"pinia": "^2.0.11"
"vue": "^3.2.31"
"vue-router": "^4.0.12"
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HugoMuller** [comment]
Hi,

a fix is proposed here https://github.com/element-plus/element-plus/issues/4923#issuecomment-1023514728.

**Comment by sheremet-va** [comment]
> Hi,
> 
> a fix is proposed here [element-plus/element-plus#4923 (comment)](https://github.com/element-plus/element-plus/issues/4923#issuecomment-1023514728).

Yes, this is the only possible solution. Vitest imports dependencies using native Node `import` function. `inlining` firstly resolves the file with Vite transforms and then it is imported.
