### ISSUE TITLE
dark and light mode switch on docs

### ISSUE THREAD

**Issue by veritem** [vitest-dev/vitest#897]
### Clear and concise description of the problem

Thanks for working on vitest. users including me don't use dark and light mode always we switch every now and then. It would be great if there was a way to switch between themes. 

### Suggested solution

 It would be great if there was a button to switch between light and dark themes on docs

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by patak-dev** [comment]
There is ongoing work to create a new theme for VitePress, that will support light/dark mode. We are waiting for it to be ready. If someone wants to create a temporal switcher (maybe we need to wait one or two months), we could add it until the official theme is out

**Comment by sheremet-va** [comment]
Implemented
