### ISSUE TITLE
Vite-Node Import of '@js-temporal/polyfill' Is Undefined 

### ISSUE THREAD

**Issue by stolinski** [vitest-dev/vitest#902]
### Describe the bug

Importing this package works fine with Vite, Node and other environments but comes in as undefined with Vite-node / Vitest.

optimizeDeps has no impact as well. 

I looked through https://github.com/js-temporal/temporal-polyfill/blob/main/package.json but nothing stood out as being unusual, so I'm a bit lost as to why this import specifically fails.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-2aqiqv?file=test/basic.test.ts

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 6.84 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.0.1 - ~/.nvm/versions/node/v17.0.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v17.0.1/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v17.0.1/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Firefox: 95.0.2
    Firefox Developer Edition: 97.0
    Safari: 15.2
  npmPackages:
    vitest: ^0.5.9 => 0.5.9
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
This is fixed by #924

In the meantime you can use `deps.external`:

```ts
{
  deps: {
    external: [/@js-temporal/]
  }
}
```
