### ISSUE TITLE
Mocking `Math.random` and not restoring makes vitest hang up when coverage is enabled

### ISSUE THREAD

**Issue by sapphi-red** [vitest-dev/vitest#903]
### Describe the bug

When you

- enabled coverage
- mock `Math.random` and not restoring the original function after test

vitest hangs up.
If you run the same code with jest, it finishes.

```js
const t = typeof vi !== 'undefined' ? vi : jest

test('Math.random mock', () => {
  // const original = Math.random
  const mocked = t.fn(() => 0.1);
  Math.random = mocked
  // Math.random = original
});
```

When you restore `Math.random` it will work. (uncomment line 4 & 7)

I think it does not need to end the test successfully, but at least fail with timeout.
Because it is hard to find which test is hanging up.

### Reproduction

https://gist.github.com/sapphi-red/d3454a362c3b66e3654918516c808d7e

1. Download zip and extract
2. `npm ci`
3. `npm run jest` runs successfully
4. `npm run vitest` never ends

(stackblitz did not work)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 12.61 GB / 31.93 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.1.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 98.0.4758.102
    Edge: Spartan (44.19041.1266.0), Chromium (99.0.1150.30)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    vitest: ^0.5.9 => 0.5.9
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
We cannot guarantee that no one uses global APIs when running tests. Just restore it to original after each test:

```ts
afterEach(() => {
  Math.random = originalRandom
})
```

**Comment by sapphi-red** [comment]
I thought the environment which is running tests is isolated from the environment which is collecting coverage.
So even if a test is breaking the environment, it would not effect the main environment.

But actually the test did not fail with timeout. Is this intended? If it is intended, I am ok to close this issue.

**Comment by sheremet-va** [comment]
They are run in the same env (not isolated, like jest does with `vm` module). Vitest provides isolation through workers, unlike jest, who uses it only to run tests in parallel.

Currently we are not planning on changing the way tests are run, because `vm` has a poor ESM support (that is why jest is so bad at ESM), but we are ESM-first and it is simply not good enough, so we are waiting for the Node team to make a better support.

**Comment by sapphi-red** [comment]
Thank you for the explanation! I understand.
