### ISSUE TITLE
vi.mock implementation results in undefined modules

### ISSUE THREAD

**Issue by MarkLyck** [vitest-dev/vitest#949]
### Describe the bug

When attempting to mock a module or import with `vi.mock` the module or import ends up being undefined both in the test file and the file that's being tested. This is of course not intended.

Here is an example where I would expect my import of `@w11r/use-breakpoint` to be a function that returns an object with the set values:

```
import useBreakpoint from '@w11r/use-breakpoint'

vi.mock('@w11r/use-breakpoint', () => vi.fn())

test(('my test) => {
 useBreakpoint.mockImplementation(() => ({
      'isMobile-': true,
      'isSmall+': false,
  }))
}) 
```

However, in the above example I get the following error:

```
TypeError: Cannot read properties of undefined (reading 'mockImplementation')"
```

`useBreakpoint` is undefined. What's more worrisome is that in the file that's using useBreakpoint, it also becomes `undefined` in there.

I discovered this while trying to migrate from jest to vi.

The following code works in jest without issues:

```
import useBreakpoint from '@w11r/use-breakpoint'

jest.mock('@w11r/use-breakpoint', () => jest.fn())

test(('my test) => {
 useBreakpoint.mockImplementation(() => ({
      'isMobile-': true,
      'isSmall+': false,
  }))
}) 
```

This is breaking 40 of my unit tests, and it's not just 3rd party module imports. Even local mocks like this one

```
vi.mock('../Overrides', () => ({
  site: {
    View: () => <div>site override view</div>,
  },
}))
```

results in the "Overrides" module export being undefined in both the test and the actual file when running the unit tests.

See reproduction below for an example of this breaking.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-5koqg7?file=src/Component.test.tsx

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.79 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 99.1.36.112
    Chrome: 99.0.4844.51
    Firefox: 97.0
    Safari: 15.3
  npmPackages:
    @vitejs/plugin-react: ^1.2.0 => 1.2.0
    vite: ^2.8.6 => 2.8.6
    vitest: ^0.6.1 => 0.6.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
default exports should be placed on default key like: { default: vi.fn() }

cjs doesnt have this concept, so it “worked” in jest

**Comment by MarkLyck** [comment]
@sheremet-va 🤦‍♂️  ahh that totally makes sense.

Thank you for the explanation.

**Comment by ThibaudMZN** [comment]
Could you provide a working code example for this issue ?
I'm facing the same problem but cannot manage to make it work...

**Comment by sheremet-va** [comment]
> Could you provide a working code example for this issue ?
> I'm facing the same problem but cannot manage to make it work...

vi.mock(“path”, () => ({ default: “test” }))
