### ISSUE TITLE
`mock.instances` does not return instances

### ISSUE THREAD

**Issue by codyebberson** [vitest-dev/vitest#950]
### Describe the bug

The values inside `mock.instances` are not the instances.

### Reproduction

Here is example from the [Jest documentation](https://jestjs.io/docs/mock-function-api#mockfnmockinstances):

```js
const mockFn = jest.fn();

const a = new mockFn();
const b = new mockFn();

mockFn.mock.instances[0] === a; // true
mockFn.mock.instances[1] === b; // true
```
Consider this test:

```js
  it('instances', () => {
    const Spy = vi.fn(() => ({}))

    // @ts-expect-error ignore
    // eslint-disable-next-line no-new
    const a = new Spy()

    // @ts-expect-error ignore
    // eslint-disable-next-line no-new
    const b = new Spy()

    expect(Spy.mock.instances.length).toBe(2)
    expect(Spy.mock.instances[0]).toBe(a)
    expect(Spy.mock.instances[1]).toBe(b)
  })
```

Fails:

```
 FAIL  test/jest-mock.test.ts > jest mock compat layer > instances
AssertionError: expected spy{} to be {} // Object.is equality
 ❯ test/jest-mock.test.ts:242:34
    240|
    241|     expect(Spy.mock.instances.length).toBe(2)
    242|     expect(Spy.mock.instances[0]).toBe(a)
       |                                  ^
    243|     expect(Spy.mock.instances[1]).toBe(b)
    244|   })
 ❯ ../../packages/vitest/dist/vendor-index.36c88a6e.js:80:26
 ❯ runTest ../../packages/vitest/dist/entry.js:730:40
 ❯ async runSuite ../../packages/vitest/dist/entry.js:794:13
 ❯ async runSuite ../../packages/vitest/dist/entry.js:794:13
 ❯ async runFiles ../../packages/vitest/dist/entry.js:831:5
 ❯ async startTests ../../packages/vitest/dist/entry.js:837:3
 ❯ async ../../packages/vitest/dist/entry.js:862:7
 ❯ async withEnv ../../packages/vitest/dist/entry.js:464:5
 ❯ async run ../../packages/vitest/dist/entry.js:861:5

  - Expected   Object {}
  + Received   spy {}
```

If you use `const Spy = vi.fn()`, then the test will pass.

However, `const Spy = vi.fn(() => ({}))` is how the docs instruct you to mock types.  Consider the example from [Vitest Mocking](https://vitest.dev/guide/mocking.html#example-2):

```js
vi.mock('pg', () => {
  return {
    Client: vi.fn(() => ({
      connect: vi.fn(),
      query: vi.fn(),
      end: vi.fn(),
    })),
  }
})
```

Current workaround is to use `mock.results[].value`

```
-    const queue = (Queue as unknown as jest.Mock).mock.instances[0];
+    const queue = (Queue as unknown as SpyInstance<any[], Queue>).mock.results[0].value;
```

### System Info

```shell
$ npx envinfo --system --npmPackages '{vitest,vite,@vitejs/*}' --binaries --browsers

  System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
    Memory: 15.56 GB / 31.91 GB
  Binaries:
    Node: 16.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (99.0.1150.39)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    vite: ^2.8.6 => 2.8.6
    vitest: workspace:* => 0.6.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
What you are trying to do also is not achievable in jest (see https://stackblitz.com/edit/node-ljd6fj?file=test.spec.js).

Example from jest documentation also work with current implementation in Vitest. Returned object from constructor is not a context or instance of that class, so I don't see any problems here? 

As we discussed in PR, this is possible workaround:

```ts
const Client = vi.fn()
Client.prototype.connect = vi.fn()
Client.prototype.query = vi.fn()
Client.prototype.end = vi.fn()
```

You can also get object from `spy.mock.results`.

Closing issue now.
