### ISSUE TITLE
Error on dynamic imports using `AsyncConstructor` in Vitest

### ISSUE THREAD

**Issue by leonsilicon** [vitest-dev/vitest#960]
### Describe the bug

When using dynamic imports with `AsyncConstructor`:

```javascript
export async function arrayUniqEval() {
	const fn = async function () {}.constructor(
		"const { default: arrayUniq } = await import('array-uniq'); console.log(arrayUniq([1, 2, 2]))"
	);
	await fn();
}
await arrayUniqEval();
```

It works fine in Node:
![Screen Shot 2022-03-16 at 4 49 21 PM](https://user-images.githubusercontent.com/36966635/158688398-1b387ba9-cc52-47b2-8d62-763c0ff7cd12.png)

But, when run with Vitest, Vitest throws the following error:
```
 ❯ eval.test.js (1)
   × test

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 1 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯

 FAIL  eval.test.js > test
TypeError: A dynamic import callback was not specified.
 ❯ eval (eval at arrayUniqEval uniq.js:2:34), <anonymous>:3:32
 ❯ Module.arrayUniqEval uniq.js:5:8
      3|                "const { default: arrayUniq } = await import('array-uniq'); console.log(arrayUniq([1, 2, 2]))"
      4|        );
      5|        await fn();
       |        ^
      6| }
      7|
 ❯ eval.test.js:5:7

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯

Test Files  1 failed (1)
     Tests  1 failed (1)
      Time  2.41s (in thread 4ms, 68841.00%)
```

Might be related to this error: https://github.com/nodejs/node/issues/30591

### Reproduction

https://github.com/leonzalion/vitest-dynamic-import-eval

### System Info

```shell
System:
    OS: macOS 11.6.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 41.03 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/Library/pnpm/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/Library/pnpm/npm
  Browsers:
    Brave Browser: 99.1.36.111
    Chrome: 99.0.4844.51
    Firefox: 98.0
    Safari: 15.3
  npmPackages:
    vitest: ^0.6.3 => 0.6.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Native imports are not possible, until Node releases full ESM support for vm module.

Should we just statically replace it? @antfu

**Comment by antfu** [comment]
Sadly I think it might be the limitations currently. I would like to avoid adding more magic to transform it until we got better support from Node.

**Comment by JounQin** [comment]
I wasted a few hours to figure out it's vitest's issue. Move to jest then.

**Comment by lvqq** [comment]
Any updates or solutions about this issue? Face the same error while using dynamic import in vitest.

**Comment by igrep** [comment]
I faced a similar problem, which prevents me from developing my programming language whose current compile target is JavaScript.
So I'm curious what magic vitest does with `import`, which could give me a hint for a workaround.

**Comment by sheremet-va** [comment]
> I faced a similar problem, which prevents me from developing my programming language whose current compile target is JavaScript.
So I'm curious what magic vitest does with import, which could give me a hint for a workaround.

Vite transforms all `import` statements to `__vite_ssr_import__`, so we intercept it and run specified file with `vm.runInThisContext`. When it's not intercepted, `vm` fails, because we don't specify `import` callback (requires `--experimental-vm-modules` flag)

**Comment by sheremet-va** [comment]
This feature should work correctly with `--pool=vmThreads` or `--pool=vmForks`.

**Comment by talatkuyuk** [comment]
Hi @sheremet-va,
I tried both `--pool=vmThreads` and `--pool=vmForks` but it still throws error: `TypeError: A dynamic import callback was not specified.`

I converted the test using `jest` instead of `vitest` for experimental, `jest` works, and finds the dynamically imported module / modules during **sync / async function construction.**
