### ISSUE TITLE
Option to customize the maximum truncated output

### ISSUE THREAD

**Issue by shuding** [vitest-dev/vitest#962]
### Clear and concise description of the problem

Currently Vitest uses `process.stdout.columns || 80` as the limit of diff output. It would be great to have a way to customize that size, especially when you have a really long test snapshot.

```diff
- Expected   "something …
+ Received   "something …
```

### Suggested solution

An `outputTruncateLength` option.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by cuixiaorui** [comment]
please do you provide a demo for 'long test snapshot'

**Comment by styfle** [comment]
@cuixiaorui Here's an example where the color of the svg was `red` but we expected `blue`. The output in the default macOS Terminal do not show the diff, instead it truncates. 

```ts
import { it, expect } from 'vitest'

it('truncated', () => {
  const input = '<svgwidth="2000"height="4000"xmlns="http://www.w3.org/2000/svg"><pathd="M1010"/><circlecx="10"cy="10"r="2"fill="red"/></svg>'
  const output = '"<svgwidth=\\"2000\\"height=\\"4000\\"xmlns=\\"http://www.w3.org/2000/svg\\"><pathd=\\"M1010\\"/><circlecx=\\"10\\"cy=\\"10\\"r=\\"2\\"fill=\\"blue\\"/></svg>"'
  expect(input).toMatchInlineSnapshot(output)
})
```

<img width="571" alt="image" src="https://user-images.githubusercontent.com/229881/159016740-c6aa90c6-3db3-46e9-8e86-152b9d06b8f1.png">

**Comment by Aslemammad** [comment]
@styfle Let me check your demo and see if it's possible!

**Comment by jcalfee** [comment]
Where do I look when output is still truncated even though I specify `vitest --outputTruncateLength 9999`?

**Comment by jcalfee** [comment]
https://github.com/vitest-dev/vitest/issues/962

**Comment by nandastone** [comment]
If you're using testing-library and diffing DOM output please note it has its own internal print limit:

https://testing-library.com/docs/dom-testing-library/api-debugging/#automatic-logging

`DEBUG_PRINT_LIMIT=100000 pnpm test`
