### ISSUE TITLE
Support --forbidOnly

### ISSUE THREAD

**Issue by rockwotj** [vitest-dev/vitest#963]
### Clear and concise description of the problem

We recently integrated https://playwright.dev and I noticed they have an awesome --forbidOnly flag that fails tests that have test.only set. We've had issues in the past where devs have accidentally committed test.only in a file and tests were not being run in CI. A flag like this would be wonderful to prevent humans from accidently disabling tests.

See: https://playwright.dev/docs/test-cli

### Suggested solution

Add a flag and config variable to fail a test run if a file contains test.only

### Alternative

You could also auto enable this if the CI environment variable is set? That seems a bit aggressive and opinionated even if I agree with it :)

One could argue this could belong in a linter but it seems like a simpler thing to add here

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Demivan** [comment]
There is `allowOnly` option already and it defaults to `false` in CI :)

**Comment by rockwotj** [comment]
Amazing! I somehow missed it!
