### ISSUE TITLE
ReferenceError after update vitest to v0.7.0

### ISSUE THREAD

**Issue by ocavue** [vitest-dev/vitest#968]
### Describe the bug

After updating vitest to 0.7.0, we get this error `ReferenceError: __INTERNAL_REMIRROR_IDENTIFIER_KEY__ is not defined`. Downgrade vitest to 0.6.3 will fix this error.

 

### Reproduction

I created a mini repo for it: https://github.com/issueset/vitest-070-bug

```bash
bash-3.2$ git clone https://github.com/issueset/vitest-070-bug
bash-3.2$ cd vitest-070-bug/
bash-3.2$ pnpm install
bash-3.2$ pnpm test
 DEV  v0.7.0 /private/tmp/vitest-bug/vitest-070-bug

 ❯ code.test.ts (0)

 FAIL  code.test.ts [ code.test.ts ]
ReferenceError: __INTERNAL_REMIRROR_IDENTIFIER_KEY__ is not defined
 ❯ node_modules/.pnpm/@remirror+core@1.3.6_@remirror+pm@1.0.14/node_modules/@remirror/core/dist/remirror-core.esm.js:979:15
    977| class PlainExtension extends Extension {
    978|   /** @internal */
    979|   static get [__INTERNAL_REMIRROR_IDENTIFIER_KEY__]() {
       |               ^
    980|     return RemirrorIdentifier.PlainExtensionConstructor;
    981|   }
 ❯ async code.ts:1:234
 ❯ async code.test.ts:1:234

```
Downgrade to 0.6.3 then this error is gone:
```
bash-3.2$ git checkout v063
bash-3.2$ pnpm install
Packages: +1 -1
+-

dependencies:
- vitest 0.7.0
+ vitest 0.6.3

Progress: resolved 1, reused 1, downloaded 0, added 1, done
bash-3.2$ pnpm test
 DEV  v0.6.3 /private/tmp/vitest-bug/vitest-070-bug

 √ code.test.ts (1)

Test Files  1 passed (1)
     Tests  1 passed (1)
      Time  1.88s (in thread 2ms, 110871.76%)
 
```

### System Info

```shell
System:
    OS: macOS 11.6.4
    CPU: (8) arm64 Apple M1
    Memory: 113.64 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 99.0.4844.74
    Firefox: 97.0
    Safari: 15.3

```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Enable `deps.fallbackCJS` or inline your dependency using `deps.inline`. See [docs](https://vitest.dev/config/#deps)

**Comment by ocavue** [comment]
> Enable `deps.fallbackCJS` or inline your dependency using `deps.inline`.

That works. Thanks!

--- 

> if `package` doesn't have `type: "import"`.

I guess you mean `"type": "module"`?

---

I'm the maintainer of `@remirror/core` and I'd love to improve our CJS/ESM compatibility. Thanks for providing advice. We are using [preconstruct](https://preconstruct.tools) when bundling packages and thus using their recommend for file names and `package.json` structure.

> Node doesn't allow having files with the same extension to be treated as cjs or esm at the same time.

I never know this before. After reading the Node documentation more carefully, I agree with you. For example, the quoted paragraph below doesn't mention anything about conditional exports. Maybe Node.js team should state this more clearly in their document. 

> ### Enabling[#](https://nodejs.org/docs/latest-v16.x/api/esm.html#enabling)
>
> Node.js has two module systems: [CommonJS](https://nodejs.org/docs/latest-v16.x/api/modules.html) modules and ECMAScript modules.
>
> Authors can tell Node.js to use the ECMAScript modules loader via the `.mjs` file extension, the `package.json` [`"type"`](https://nodejs.org/docs/latest-v16.x/api/packages.html#type) field, or the [`--input-type`](https://nodejs.org/docs/latest-v16.x/api/cli.html#--input-typetype) flag. Outside of those cases, Node.js will use the CommonJS module loader. See [Determining module system](https://nodejs.org/docs/latest-v16.x/api/packages.html#determining-module-system) for more details.

I believe only a very small part of people in the community know this. As an example, it seems that Vite itself is recommending the incorrect `package.json` structure (correct me if I'm wrong). Even though Vite's library mode is for building browser-oriented libraries (instead of Node.js libraries), I guess these libraries still need to run on Node.js when using Vitest. Do you think it's a good idea to update the docs of Vite?

> https://vitejs.dev/guide/build.html#library-mode
> 
> Recommended `package.json` for your lib:
>
> ```
> {
>   "name": "my-lib",
>   "files": ["dist"],
>   "main": "./dist/my-lib.umd.js",
>   "module": "./dist/my-lib.es.js",
>   "exports": {
>     ".": {
>       "import": "./dist/my-lib.es.js",
>       "require": "./dist/my-lib.umd.js"
>     }
>   }
> }
> ```

**Comment by sheremet-va** [comment]
I think the reason people use it this way is because bundlers understand that syntax. And eventually it will be read only by bundlers.

Then Vitest comes in (there was no need to load it in esm before) and tries to load it with Native Node and fails.
