### ISSUE TITLE
coverage exlude option overrides defaults

### ISSUE THREAD

**Issue by wight554** [vitest-dev/vitest#976]
### Describe the bug

When using test.coverage.exlude options defaults are being overwritten instead of appending. If it's intentional , then it should be possible to import defaults or optionally append excludes

### Reproduction

set test.coverage.exlude, all defaults are being ignored

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 2.38 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 3.1.1 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
    Watchman: 2021.10.04.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 99.0.4844.74
    Edge: 99.0.1150.39
    Safari: 15.3
  npmPackages:
    vite: ^2.8.6 => 2.8.6 
    vitest: ^0.7.4 => 0.7.4
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Of course it is intended behaviour. If you need to merge them, import defaults from `vitest/config`.
