### ISSUE TITLE
mask-image inline css property is being erased

### ISSUE THREAD

**Issue by ivanRemotely** [vitest-dev/vitest#979]
### Describe the bug

Hey there!

I'm trying to use `mask-image` as an inline style, but it appears that for some reason Vitest is removing the property when running the tests. It does not happen outside the tests (with regular Vite builds), but it does happen in your own Vue sample: 

https://stackblitz.com/edit/vitest-dev-vitest-3zc5wj?file=components/Hello.vue

Here's the code I used:
```html
<div style="background-color: red; mask-image: url(../../assets/logo.svg)"></div>
```

and what I'm getting in Vitest:

```html
<div style="background-color: red;"></div>
```

Same with a non-local images, or even with non-url based values like `mask-image: radial-gradient(circle, black 50%, rgba(0, 0, 0, 0.5) 50%);`. I tried adding more properties before and after, with no luck. It seem `mask-image` itself is the issue, not its contents/position/neighbors. 

I also tried with the `-webkit` prefix (`-webkit-mask-image`), but that gets erased too.

If you see the logs, the `mask-image` css property is gone from the html. it seemingly does not happen with any other property. I am porting Jest tests and that property used to be there for sure. My tests use SCSS but since it happens in the sample it seems that the issue happens with css as well.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-3zc5wj?file=components/Hello.vue

### System Info

```shell
System:
    OS: macOS 11.6.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 129.18 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.2.0 - ~/.nvm/versions/node/v16.2.0/bin/node
    npm: 7.13.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 99.0.4844.74
    Firefox: 98.0
    Safari: 15.3
  npmPackages:
    @vitejs/plugin-vue: ^2.2.4 => 2.2.4 
    vite: ^2.8.0 => 2.8.6 
    vitest: ^0.7.2 => 0.7.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Vitest doesn't support DOM, so it has nothing to do with us. Please, open an issue at [`happy-dom`'s repository](https://github.com/capricorn86/happy-dom) or/and in the meantime use `jsdom`.
