### ISSUE TITLE
env variable for current test mode (watch/coverage/run)

### ISSUE THREAD

**Issue by wight554** [vitest-dev/vitest#984]
### Clear and concise description of the problem

Coverage reporting is somewhat unstable when using vitest in node project (nestjs in my case) when you transpile test code. In this case I need to use ts transform api (eg via @rollup/plugin-typescript) to get proper results and it's very slow comparing to typescript transpile api. I'd like to be able to use it only for coverage mode testing.

### Suggested solution

Provide env variable (eg VITEST_MODE) that'll expose current testing mode

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
But we already provide it with the same name even 🤔

**Comment by wight554** [comment]
well it's not documented and there's **watch** and **run** modes only

**Comment by sheremet-va** [comment]
Not sure if `coverage` should be a mode. Also you can check if the process uses coverage with `NODE_V8_COVERAGE` env.

**Comment by wight554** [comment]
tnx, that works
