### ISSUE TITLE
[UI] Open in editor links

### ISSUE THREAD

**Issue by craciuncezar** [vitest-dev/vitest#988]
### Clear and concise description of the problem

As a developer using Vitest it might be convenient if file paths in the web UI error texts could be links that redirect me to the broken code.

Since vitest is built on top of vite, the dev server should know how to respond to `/__open-in-editor?file=`, right? I think we can modify current file path text to be links that open vscode similar to how its done in vite error page.

If others feel there is value in this as well, I'm open to submit a PR for this issue.

### Suggested solution

This is how its done in [vite's client overlay] a simple fetch call to `/__open-in-editor?file=` (https://github.com/vitejs/vite/blob/71868579058512b51991718655e089a78b99d39c/packages/vite/src/client/overlay.ts#L171-L173).

### Additional context

https://user-images.githubusercontent.com/27342306/159131722-5128d119-abce-43b2-a7c1-f98974b179ab.mov

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by userquin** [comment]
@craciuncezar do you mean adding a link on the report or in the code editor?

** Report **
![imagen](https://user-images.githubusercontent.com/6311119/159133670-c31b93d6-7d99-4e07-a6ff-7f02e031d138.png)

** Code Editor **
![imagen](https://user-images.githubusercontent.com/6311119/159133695-1cdb0670-79e5-483d-bb2f-0bf30197d298.png)

**Comment by craciuncezar** [comment]
> @craciuncezar do you mean adding a link on the report or in the code editor?

In the report error - I was thinking that this file path can be a link that opens that particular file:line in your editor, similar to vite error page.

<img width="1025" alt="Screenshot 2022-03-19 at 22 42 44" src="https://user-images.githubusercontent.com/27342306/159137771-f20ea18b-0c2a-41d8-8aa2-ea29c5006699.png">

**Comment by userquin** [comment]
@craciuncezar testing on local, I need to figure out how to add to the report, check the console:

![imagen](https://user-images.githubusercontent.com/6311119/159158032-90044fcf-d67b-4130-928c-9764afda04fe.png)

**Comment by userquin** [comment]
@craciuncezar cehck the video on the PR

**Comment by craciuncezar** [comment]
Looks good to me 👍 thanks for making it happen @userquin

**Comment by userquin** [comment]
> Looks good to me 👍 thanks for making it happen @userquin

Added also to the code tab
