### ISSUE TITLE
Fuzzy serach in UI

### ISSUE THREAD

**Issue by craciuncezar** [vitest-dev/vitest#989]
### Clear and concise description of the problem

As a developer that uses Vitest and could have typos in search term I wish that the search in the UI uses a fuzzy implementation, similar to how is done in other tools I use (ie. vscode).

If others see value in this proposal I'm open to submit a PR for it.

### Suggested solution

If acceptable we can add `Fuse.js` as a dependecy and use its algo for the search.
https://fusejs.io/

The solution might be as simple as the following, replacing [this line](https://github.com/vitest-dev/vitest/blob/main/packages/ui/client/components/TasksList.vue#L29) with:

```TS
const fuse = new Fuse(props.tasks, { keys: ['name'] });
return fuse.search(search.value);
```

Obviously if you guys have any lib suggestion please feel free to share them.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by sheremet-va** [comment]
Implemented in #1035
