### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by peterroe** [vitest-dev/vitest#990]
### Describe the bug

demo online: https://stackblitz.com/edit/vitest-dev-vitest-gnawnk?file=vite.config.ts&initialPath=__vitest__

```shell
 FAIL  test/suite.test.ts > my vue component > should render
ReferenceError: document is not defined
 ❯ Proxy.mount node_modules/@vue/test-utils/dist/vue-test-utils.cjs.js:7757:14
 ❯ eval test/suite.test.ts:7:20
      5| describe('my vue component', () => {
      6|   it('should render', () => {
      7|     const wrapper = mount(MyComponent);
       |                    ^
      8|     expect(wrapper.html()).toMatchSnapshot();
      9|   });
```

### Reproduction

No need.

### System Info

```shell
No need.
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by stygian-desolator** [comment]
https://vitest.dev/config/#environment

``` ts
export default defineConfig({
  plugins: [vue()],
  test: {
    environment: 'happy-dom'
  },
});
```

**Comment by peterroe** [comment]
> https://vitest.dev/config/#environment
> 
> ```ts
> export default defineConfig({
>   plugins: [vue()],
>   test: {
>     environment: 'happy-dom'
>   },
> });
> ```

Thank you so mach!

**Comment by SoetZombie** [comment]
> https://vitest.dev/config/#environment
> 
> ```ts
> export default defineConfig({
>   plugins: [vue()],
>   test: {
>     environment: 'happy-dom'
>   },
> });
> ```

How do we do this when compiler options are set to esnext? 

```
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
```

TS2345: Argument of type '{ plugins: Plugin[]; test: { globals: boolean; environment: string; }; resolve: { alias: { '@': string; }; }; server: { https: true; }; css: { preprocessorOptions: { sass: { additionalData: string; }; scss: { ...; }; }; }; }' is not assignable to parameter of type 'UserConfigExport'.   Object literal may only specify known properties, and 'test' does not exist in type 'UserConfigExport'.

**Comment by Martin-Karsten** [comment]
> > https://vitest.dev/config/#environment
> > ```ts
> > export default defineConfig({
> >   plugins: [vue()],
> >   test: {
> >     environment: 'happy-dom'
> >   },
> > });
> > ```
> 
> How do we do this when compiler options are set to esnext?
> 
> ```
>   "compilerOptions": {
>     "target": "esnext",
>     "module": "esnext",
> ```
> 
> TS2345: Argument of type '{ plugins: Plugin[]; test: { globals: boolean; environment: string; }; resolve: { alias: { '@': string; }; }; server: { https: true; }; css: { preprocessorOptions: { sass: { additionalData: string; }; scss: { ...; }; }; }; }' is not assignable to parameter of type 'UserConfigExport'.   Object literal may only specify known properties, and 'test' does not exist in type 'UserConfigExport'.

You can define the environment in your package.json script. For example like this
"scripts": {
  "test": "vitest --environment jsdom"
}

**Comment by isimmons** [comment]
I had to reference the vitest types at the top of my vite.config.ts . Otherwise "test" is not a known property so typescript throws the error about test not being assignable to UserConfigExport

```js
/// <reference types="vitest" />
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  test: {
    environment: "happy-dom",
  },
});

```

**Comment by peterroe** [comment]
@isimmons You are right, check here please: https://vitest.dev/guide/#configuring-vitest
