### ISSUE TITLE
Cannot mock module that isn't installed (eg `vscode`)

### ISSUE THREAD

**Issue by zardoy** [vitest-dev/vitest#993]
### Describe the bug

I want to use vitest for unit tests in vscode extension project. Obviously `vscode` import is virtual module (it is defined only from vscode extension host). Installable only `@types/vscode` dependency.

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-z2k4md?file=test/source.ts.

AR:

`Error: Failed to resolve import "vscode" from "test/source.ts". Does the file exist?`

ER:

Mocked module implementation is used.

It worked with jest (I can drop a link to the project) with just defining `__mocks__/vscode.js`. I read the docs and it seems logical to work. As you can see I tried `vi.mock`, but it didn't work. Or am I doing something wrong?

### System Info

```shell
`envinfo` got crashed on stackblitz/
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Tchoupinax** [comment]
Hello,

Same error here
`Error: Failed to resolve import "vscode" from "src/file-parser/file-parser.ts". Does the file exist?`

**Comment by sheremet-va** [comment]
This is Vite issue. We are waiting for the solution. In the meantime you can create a plugin, that makes vscode a virtual module:

```ts
plugins: [
  {
     resolveId(id) {
       if(id === "vscode") return id
     },
     load(id) {
       if(id === "vscode") return ""
     }
  }
]
```

**Comment by sheremet-va** [comment]
The error doesn't occur on the latest Vitest and Vite versions.
