### ISSUE TITLE
Vitest fails to resolve tsconfig extends

### ISSUE THREAD

**Issue by michael-wolfenden** [vitest-dev/vitest#994]
### Describe the bug

Given the following `package.json`

```json
{
  "name": "vitest-test",
  "private": true,
  "license": "MIT",
  "type": "module",
  "main": "index.js",
  "scripts": {
    "test": "vitest",
    "test:ui": "vitest --ui",
    "test:run": "vitest run"
  },
  "devDependencies": {
    "@tsconfig/node14": "latest",
    "@vitest/ui": "latest",
    "vite": "latest",
    "vitest": "latest"
  },
  "stackblitz": {
    "startCommand": "npm run test:ui"
  }
}

```

and `tsconfig.json`

```json
{
  "extends": "@tsconfig/node14"
}
```

Running `vitest` results in the following error:

```
 FAIL  test/basic.test.ts [ test/basic.test.ts ]
Error: failed to resolve "extends":"@tsconfig/node14" in /home/projects/vitest-dev-vitest-ujcycp/tsconfig.json
 ❯ resolveExtends node_modules/vite/dist/node/chunks/dep-9c153816.js:22266:11
 ❯ parseExtends node_modules/vite/dist/node/chunks/dep-9c153816.js:22250:34
 ❯ parse$e node_modules/vite/dist/node/chunks/dep-9c153816.js:22201:24
 ❯ async loadTsconfigJsonForFile node_modules/vite/dist/node/chunks/dep-9c153816.js:22547:24
 ❯ async transformWithEsbuild node_modules/vite/dist/node/chunks/dep-9c153816.js:22380:36
 ❯ async TransformContext.transform node_modules/vite/dist/node/chunks/dep-9c153816.js:22468:32
 ❯ async Object.transform node_modules/vite/dist/node/chunks/dep-9c153816.js:38334:30
 ❯ async doTransform node_modules/vite/dist/node/chunks/dep-9c153816.js:53030:29
```

If I remove ` "extends": "@tsconfig/node14"` from `tsconfig.json`, the tests run successfully

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-ujcycp

### System Info

```shell
N/A
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/vitest-dev/vitest/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/vitest-dev/vitest/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://vitest.dev/guide).
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vitest/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vitest/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
> I think this one has been fixed in upstream and updated via [68b186c](https://github.com/vitest-dev/vitest/commit/68b186c47b2d5afd5757f8a508241202ce641113).

Hurray! Closing issue :)
